import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Liouville–Green & WKB
 * Subtopic am10c: Normal form & irregular singular points
 * 30 fully-worked questions (6 Foundation / 12 Standard / 12 Challenge).
 *
 * Theme: reducing a second-order ODE to normal form by removing the first-derivative
 * term (invariant I = r − ¼p² − ½p'), classifying the point z = ∞ via z = 1/t, and
 * reading off the irregular-singular-point rank and the e^{±∫√q} structure. Standard
 * equations (Bessel, spherical Bessel, modified Bessel, Hermite/Weber, Airy, Coulomb)
 * are reduced and their LG leading forms compared to known exact solutions.
 *
 * The invariant I and the z = 1/t change of variable were verified symbolically with
 * sympy for every question; LG-vs-exact comparisons were checked numerically with
 * scipy.special / mpmath. Pure classification statements carry no numerical anchor and
 * are flagged where relevant.
 */
export const questions: Question[] = [
  // ───────────────────────── FOUNDATION (6) ─────────────────────────
  {
    id: "am10c-001",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( y'' + p\\,y' + r\\,y = 0 \\) the substitution \\( y = w\\,\\exp\\!\\left(-\\tfrac12\\int p\\,dx\\right) \\) removes the first-derivative term. State the resulting equation for \\( w \\) and the invariant \\( I \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["normal form", "invariant", "removing y'"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the normal-form equation.", workingLatex: "w'' + I(x)\\, w = 0.", explanation: "The exponential factor is chosen precisely so that the \\( w' \\) term cancels, leaving a Schrödinger-type equation." },
        { stepNumber: 2, description: "State the invariant.", workingLatex: "I = r - \\frac{1}{4}p^{2} - \\frac{1}{2}p'.", explanation: "It is called the invariant because two equations related by \\( y \\mapsto f(x)y \\) share the same \\( I \\)." },
      ],
      finalAnswer: "\\( w'' + I\\,w = 0 \\) with \\( I = r - \\dfrac{1}{4}p^{2} - \\dfrac{1}{2}p' \\).",
      canonicalAnswer: "I = r - p^2/4 - p'/2",
    },
  },
  {
    id: "am10c-002",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Compute the invariant \\( I \\) of \\( y'' + 2x\\,y' + x^{2}\\,y = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["normal form", "invariant", "constant coefficients"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Read off \\( p \\) and \\( r \\).", workingLatex: "p = 2x, \\qquad r = x^{2}, \\qquad p' = 2.", explanation: "" },
        { stepNumber: 2, description: "Apply the invariant formula.", workingLatex: "I = x^{2} - \\frac{1}{4}(2x)^{2} - \\frac{1}{2}(2) = x^{2} - x^{2} - 1 = -1.", explanation: "The \\( x^{2} \\) terms cancel, leaving a constant." },
        { stepNumber: 3, description: "State the normal form.", workingLatex: "w'' - w = 0.", explanation: "A constant invariant means the normal form has constant coefficients: \\( w = A e^{x} + B e^{-x} \\)." },
      ],
      finalAnswer: "\\( I = -1 \\), so \\( w'' - w = 0 \\).",
      canonicalAnswer: "-1",
    },
  },
  {
    id: "am10c-003",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Reduce the spherical-Bessel equation \\( y'' + \\dfrac{2}{x}y' + \\left(1 - \\dfrac{\\ell(\\ell+1)}{x^{2}}\\right)y = 0 \\) to normal form, giving the substitution and the resulting equation for \\( w \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["normal form", "spherical Bessel", "substitution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the substitution.", workingLatex: "y = w\\,\\exp\\!\\left(-\\frac{1}{2}\\int \\frac{2}{x}\\,dx\\right) = w\\,e^{-\\ln x} = \\frac{w}{x}, \\qquad \\text{i.e. } w = x\\,y.", explanation: "With \\( p = 2/x \\) the integrating factor is \\( 1/x \\)." },
        { stepNumber: 2, description: "Compute the invariant.", workingLatex: "I = \\left(1 - \\frac{\\ell(\\ell+1)}{x^{2}}\\right) - \\frac{1}{4}\\frac{4}{x^{2}} - \\frac{1}{2}\\left(-\\frac{2}{x^{2}}\\right) = 1 - \\frac{\\ell(\\ell+1)}{x^{2}}.", explanation: "The two \\( 1/x^{2} \\) corrections cancel exactly." },
        { stepNumber: 3, description: "State the normal form.", workingLatex: "w'' + \\left(1 - \\frac{\\ell(\\ell+1)}{x^{2}}\\right)w = 0, \\qquad w = x\\,y.", explanation: "" },
      ],
      finalAnswer: "\\( w = x\\,y \\) satisfies \\( w'' + \\left(1 - \\dfrac{\\ell(\\ell+1)}{x^{2}}\\right)w = 0 \\).",
      canonicalAnswer: "w''+(1-l(l+1)/x^2)w=0, w=x y",
    },
  },
  {
    id: "am10c-004",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "An ODE \\( y'' + P(t)\\,y_{t} + R(t)\\,y = 0 \\) has a point \\( t = 0 \\). State the pole-order test that decides whether \\( t = 0 \\) is an ordinary point, a regular singular point, or an irregular singular point.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["classification", "regular singular", "irregular singular"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Ordinary point.", workingLatex: "P,\\ R \\text{ analytic at } t=0.", explanation: "Both coefficients are finite (no poles); power-series solutions exist." },
        { stepNumber: 2, description: "Regular singular point.", workingLatex: "t\\,P \\text{ and } t^{2}R \\text{ analytic at } t=0.", explanation: "Equivalently \\( P \\) has at most a simple pole and \\( R \\) at most a double pole; Frobenius series apply." },
        { stepNumber: 3, description: "Irregular singular point.", workingLatex: "\\text{either pole bound is exceeded.}", explanation: "Then no convergent Frobenius series in general; the solution carries an essential singularity / exponential factor." },
      ],
      finalAnswer: "Ordinary: \\( P,R \\) analytic; regular singular: \\( tP,\\,t^{2}R \\) analytic; irregular: otherwise.",
      canonicalAnswer: "regular singular iff P has pole order <=1 and R pole order <=2",
    },
  },
  {
    id: "am10c-005",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Compute the invariant \\( I \\) of the Bessel equation \\( y'' + \\dfrac{1}{x}y' + \\left(1 - \\dfrac{\\nu^{2}}{x^{2}}\\right)y = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["normal form", "Bessel", "invariant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Read off coefficients.", workingLatex: "p = \\frac{1}{x}, \\qquad r = 1 - \\frac{\\nu^{2}}{x^{2}}, \\qquad p' = -\\frac{1}{x^{2}}.", explanation: "" },
        { stepNumber: 2, description: "Apply the formula.", workingLatex: "I = \\left(1 - \\frac{\\nu^{2}}{x^{2}}\\right) - \\frac{1}{4}\\frac{1}{x^{2}} - \\frac{1}{2}\\left(-\\frac{1}{x^{2}}\\right) = 1 - \\frac{\\nu^{2} - \\frac14}{x^{2}}.", explanation: "Combine the three \\( 1/x^{2} \\) contributions: \\( -\\nu^{2} - \\tfrac14 + \\tfrac12 = -(\\nu^{2}-\\tfrac14) \\)." },
      ],
      finalAnswer: "\\( I = 1 - \\dfrac{\\nu^{2} - \\tfrac14}{x^{2}} \\).",
      canonicalAnswer: "1 - (nu^2 - 1/4)/x^2",
    },
  },
  {
    id: "am10c-006",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write the normal form \\( w'' + I\\,w = 0 \\) in the equivalent shape \\( W'' = Q(z)W \\), and express \\( Q \\) in terms of \\( p \\) and \\( r \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["normal form", "WKB form", "invariant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Move the invariant across.", workingLatex: "w'' + I\\,w = 0 \\;\\Longrightarrow\\; w'' = -I\\,w, \\qquad Q = -I.", explanation: "The LG/WKB form \\( W'' = QW \\) takes \\( Q = -I \\)." },
        { stepNumber: 2, description: "Substitute the invariant.", workingLatex: "Q = -\\left(r - \\frac{1}{4}p^{2} - \\frac{1}{2}p'\\right) = \\frac{1}{4}p^{2} + \\frac{1}{2}p' - r.", explanation: "Solutions then behave like \\( \\exp\\!\\left(\\pm\\int\\sqrt{Q}\\,dz\\right) \\) where \\( Q > 0 \\)." },
      ],
      finalAnswer: "\\( Q = \\dfrac{1}{4}p^{2} + \\dfrac{1}{2}p' - r \\).",
      canonicalAnswer: "Q = p^2/4 + p'/2 - r",
    },
  },

  // ───────────────────────── STANDARD (12) ─────────────────────────
  {
    id: "am10c-007",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 07",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the Bessel equation \\( y'' + \\dfrac{1}{x}y' + \\left(1 - \\dfrac{\\nu^{2}}{x^{2}}\\right)y = 0 \\) to normal form and hence find the leading LG (large-\\( x \\)) form of \\( y \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["normal form", "Bessel", "LG asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitution and invariant.", workingLatex: "w = \\sqrt{x}\\,y, \\qquad I = 1 - \\frac{\\nu^{2} - \\frac14}{x^{2}}.", explanation: "With \\( p = 1/x \\) the factor is \\( \\exp(-\\tfrac12\\int x^{-1}) = x^{-1/2} \\), so \\( y = x^{-1/2}w \\)." },
        { stepNumber: 2, description: "Normal form and large-\\( x \\) limit.", workingLatex: "w'' + \\left(1 - \\frac{\\nu^{2}-\\frac14}{x^{2}}\\right)w = 0 \\;\\xrightarrow{x\\to\\infty}\\; w'' + w = 0.", explanation: "The \\( 1/x^{2} \\) term is negligible, leaving a constant-coefficient oscillator." },
        { stepNumber: 3, description: "Solve and unscale.", workingLatex: "w \\sim A\\cos\\!\\left(x - \\phi\\right) \\;\\Longrightarrow\\; y = \\frac{w}{\\sqrt{x}} \\sim \\frac{A}{\\sqrt{x}}\\cos(x - \\phi).", explanation: "Numerical check: \\( J_{0}(x) \\sim \\sqrt{2/(\\pi x)}\\cos(x - \\pi/4) \\); at \\( x = 50 \\) exact \\( 0.05581 \\) vs LG \\( 0.05606 \\)." },
      ],
      finalAnswer: "\\( y \\sim \\dfrac{A}{\\sqrt{x}}\\cos(x - \\phi) \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "y ~ A cos(x-phi)/sqrt(x)",
    },
  },
  {
    id: "am10c-008",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 08",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Classify the point \\( z = \\infty \\) for the oscillator \\( y'' + y = 0 \\) by substituting \\( z = 1/t \\) and inspecting the transformed coefficients at \\( t = 0 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["classification", "point at infinity", "z=1/t"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the transformed equation.", workingLatex: "y_{tt} + \\left[\\frac{2}{t} - \\frac{p(1/t)}{t^{2}}\\right]y_{t} + \\frac{r(1/t)}{t^{4}}y = 0.", explanation: "This is the standard form after \\( z = 1/t \\); here \\( p = 0 \\) and \\( r = 1 \\)." },
        { stepNumber: 2, description: "Read off the new coefficients.", workingLatex: "P(t) = \\frac{2}{t}, \\qquad R(t) = \\frac{1}{t^{4}}.", explanation: "" },
        { stepNumber: 3, description: "Apply the pole-order test.", workingLatex: "P:\\ \\text{pole order }1\\ (\\le 1), \\qquad R:\\ \\text{pole order }4\\ (> 2).", explanation: "\\( R \\) violates the regular-singular bound, so \\( t = 0 \\) — i.e. \\( z = \\infty \\) — is irregular." },
      ],
      finalAnswer: "\\( z = \\infty \\) is an irregular singular point.",
      canonicalAnswer: "irregular singular point at infinity",
    },
  },
  {
    id: "am10c-009",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 09",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Classify \\( z = \\infty \\) for the Bessel equation \\( y'' + \\dfrac{1}{z}y' + \\left(1 - \\dfrac{\\nu^{2}}{z^{2}}\\right)y = 0 \\) using \\( z = 1/t \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["classification", "Bessel", "point at infinity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Transform the coefficients.", workingLatex: "P(t) = \\frac{2}{t} - \\frac{(1/(1/t))}{t^{2}} = \\frac{2}{t} - \\frac{t}{t^{2}} = \\frac{1}{t}.", explanation: "Here \\( p(1/t) = t \\), so the two \\( 1/t \\) pieces combine to \\( 1/t \\)." },
        { stepNumber: 2, description: "Transform \\( R \\).", workingLatex: "R(t) = \\frac{r(1/t)}{t^{4}} = \\frac{1 - \\nu^{2}t^{2}}{t^{4}} = \\frac{1}{t^{4}} - \\frac{\\nu^{2}}{t^{2}}.", explanation: "Substituting \\( z = 1/t \\) into \\( 1 - \\nu^{2}/z^{2} \\) gives \\( 1 - \\nu^{2}t^{2} \\)." },
        { stepNumber: 3, description: "Classify.", workingLatex: "P:\\ \\text{order }1, \\qquad R:\\ \\text{order }4 > 2 \\;\\Longrightarrow\\; \\text{irregular}.", explanation: "The leading \\( 1/t^{4} \\) pole in \\( R \\) makes \\( z = \\infty \\) irregular — consistent with the oscillatory \\( e^{\\pm i z} \\) behaviour." },
      ],
      finalAnswer: "\\( z = \\infty \\) is an irregular singular point of the Bessel equation.",
      canonicalAnswer: "irregular singular point at infinity",
    },
  },
  {
    id: "am10c-010",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 10",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For the constant-coefficient damped equation \\( y'' + 2b\\,y' + (b^{2} + \\omega_{0}^{2})\\,y = 0 \\) (\\( b,\\omega_{0} \\) constants), find the invariant and verify that the normal form recovers the exact solution.",
    marks: 3,
    yearCreated: 2026,
    tags: ["normal form", "exact comparison", "damped oscillator"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "p = 2b,\\ r = b^{2}+\\omega_{0}^{2},\\ p' = 0: \\quad I = (b^{2}+\\omega_{0}^{2}) - b^{2} - 0 = \\omega_{0}^{2}.", explanation: "The damping contributes \\( -\\tfrac14 p^{2} = -b^{2} \\), cancelling the \\( b^{2} \\) in \\( r \\)." },
        { stepNumber: 2, description: "Normal form and its solution.", workingLatex: "w'' + \\omega_{0}^{2}w = 0 \\;\\Longrightarrow\\; w = A\\cos\\omega_{0}x + B\\sin\\omega_{0}x.", explanation: "A pure undamped oscillator in \\( w \\)." },
        { stepNumber: 3, description: "Unscale.", workingLatex: "y = w\\,e^{-bx} = e^{-bx}\\left(A\\cos\\omega_{0}x + B\\sin\\omega_{0}x\\right).", explanation: "This is exactly the standard solution of the damped oscillator (verified by substitution), so the normal form is exact here, not just asymptotic." },
      ],
      finalAnswer: "\\( I = \\omega_{0}^{2} \\); \\( y = e^{-bx}(A\\cos\\omega_{0}x + B\\sin\\omega_{0}x) \\).",
      canonicalAnswer: "I = omega0^2",
    },
  },
  {
    id: "am10c-011",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 11",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the spherical-Bessel equation \\( y'' + \\dfrac{2}{x}y' + \\left(1 - \\dfrac{\\ell(\\ell+1)}{x^{2}}\\right)y = 0 \\) to normal form, and for \\( \\ell = 1 \\) compare the LG leading form with the exact solution \\( j_{1}(x) = \\dfrac{\\sin x}{x^{2}} - \\dfrac{\\cos x}{x} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["normal form", "spherical Bessel", "exact comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Normal form.", workingLatex: "w = x\\,y: \\quad w'' + \\left(1 - \\frac{\\ell(\\ell+1)}{x^{2}}\\right)w = 0.", explanation: "From the invariant \\( I = 1 - \\ell(\\ell+1)/x^{2} \\)." },
        { stepNumber: 2, description: "Large-\\( x \\) LG form.", workingLatex: "w'' + w \\approx 0 \\;\\Longrightarrow\\; w \\sim C\\cos\\!\\left(x - \\psi\\right), \\qquad y = \\frac{w}{x} \\sim \\frac{C}{x}\\cos(x - \\psi).", explanation: "The amplitude decays like \\( 1/x \\) and the phase is \\( x \\) to leading order." },
        { stepNumber: 3, description: "Compare with the exact \\( j_{1} \\).", workingLatex: "j_{1}(x) = \\frac{\\sin x}{x^{2}} - \\frac{\\cos x}{x} \\sim -\\frac{\\cos x}{x}.", explanation: "The \\( \\sin x / x^{2} \\) term is subdominant; the leading part is \\( -\\cos x / x \\), matching the LG form with \\( C = -1,\\ \\psi = 0 \\)." },
        { stepNumber: 4, description: "Numerical confirmation.", workingLatex: "x = 60: \\quad x\\,j_{1}(60) = 0.9473, \\qquad -\\cos 60 = 0.9524.", explanation: "The envelope \\( w = x\\,j_{1} \\) tracks \\( -\\cos x \\) to within the \\( O(1/x) \\) correction." },
      ],
      finalAnswer: "\\( y \\sim \\dfrac{C}{x}\\cos(x-\\psi) \\); for \\( \\ell = 1 \\), \\( j_{1}(x) \\sim -\\dfrac{\\cos x}{x} \\).",
      canonicalAnswer: "j_1(x) ~ -cos(x)/x",
    },
  },
  {
    id: "am10c-012",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 12",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the invariant of the modified Bessel equation \\( y'' + \\dfrac{1}{x}y' - \\left(1 + \\dfrac{\\nu^{2}}{x^{2}}\\right)y = 0 \\), and hence give the two LG leading forms as \\( x \\to \\infty \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["normal form", "modified Bessel", "LG asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "I = -\\left(1 + \\frac{\\nu^{2}}{x^{2}}\\right) - \\frac{1}{4x^{2}} + \\frac{1}{2x^{2}} = -1 - \\frac{\\nu^{2} - \\frac14}{x^{2}}.", explanation: "Same \\( 1/x^{2} \\) bookkeeping as Bessel, but \\( r \\) carries the opposite sign on the \\( O(1) \\) term." },
        { stepNumber: 2, description: "Normal form and its WKB potential.", workingLatex: "w = \\sqrt{x}\\,y: \\quad w'' - \\left(1 + \\frac{\\nu^{2}-\\frac14}{x^{2}}\\right)w = 0, \\qquad Q = 1 + \\cdots \\to 1.", explanation: "Now \\( Q = -I > 0 \\), so solutions are exponential rather than oscillatory." },
        { stepNumber: 3, description: "Leading LG forms.", workingLatex: "w \\sim A\\,e^{x} + B\\,e^{-x} \\;\\Longrightarrow\\; y = \\frac{w}{\\sqrt{x}} \\sim \\frac{A\\,e^{x} + B\\,e^{-x}}{\\sqrt{x}}.", explanation: "Numerical check (recessive branch): \\( K_{0}(x) \\sim \\sqrt{\\pi/(2x)}\\,e^{-x} \\); at \\( x = 30 \\) exact \\( 2.13\\times10^{-14} \\) vs LG \\( 2.14\\times10^{-14} \\)." },
      ],
      finalAnswer: "\\( y \\sim \\dfrac{A\\,e^{x} + B\\,e^{-x}}{\\sqrt{x}} \\) (e.g. \\( K_{\\nu} \\sim \\sqrt{\\tfrac{\\pi}{2x}}e^{-x} \\)).",
      canonicalAnswer: "y ~ (A e^x + B e^{-x})/sqrt(x)",
    },
  },
  {
    id: "am10c-013",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 13",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce \\( y'' + \\dfrac{2}{x}y' + y = 0 \\) to normal form, solve it exactly, and confirm that \\( y = \\dfrac{\\cos x}{x} \\) and \\( y = \\dfrac{\\sin x}{x} \\) are solutions.",
    marks: 4,
    yearCreated: 2026,
    tags: ["normal form", "exact comparison", "spherical Bessel l=0"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Invariant.", workingLatex: "p = \\frac{2}{x},\\ r = 1: \\quad I = 1 - \\frac{1}{4}\\frac{4}{x^{2}} - \\frac{1}{2}\\left(-\\frac{2}{x^{2}}\\right) = 1.", explanation: "The two \\( 1/x^{2} \\) terms cancel, giving a constant invariant." },
        { stepNumber: 2, description: "Normal form (exact, not just asymptotic).", workingLatex: "w = x\\,y: \\quad w'' + w = 0 \\;\\Longrightarrow\\; w = A\\cos x + B\\sin x.", explanation: "Because \\( I \\) is exactly constant, the normal form is solvable in closed form for all \\( x \\)." },
        { stepNumber: 3, description: "Unscale.", workingLatex: "y = \\frac{w}{x} = \\frac{A\\cos x + B\\sin x}{x}.", explanation: "So \\( \\cos x / x \\) and \\( \\sin x / x \\) are the two independent solutions (the \\( \\ell = 0 \\) spherical Bessel functions)." },
        { stepNumber: 4, description: "Verify directly.", workingLatex: "\\left(\\frac{\\cos x}{x}\\right)'' + \\frac{2}{x}\\left(\\frac{\\cos x}{x}\\right)' + \\frac{\\cos x}{x} = 0.", explanation: "Substitution (checked with sympy) gives identically zero, confirming the closed form." },
      ],
      finalAnswer: "\\( y = \\dfrac{A\\cos x + B\\sin x}{x} \\).",
      canonicalAnswer: "y = (A cos x + B sin x)/x",
    },
  },
  {
    id: "am10c-014",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 14",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Classify \\( z = \\infty \\) for the Airy equation \\( y'' - z\\,y = 0 \\) using \\( z = 1/t \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["classification", "Airy", "point at infinity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify \\( p, r \\) and transform.", workingLatex: "p = 0,\\ r = -z: \\quad P(t) = \\frac{2}{t}, \\qquad R(t) = \\frac{-1/t}{t^{4}} = -\\frac{1}{t^{5}}.", explanation: "With \\( r(1/t) = -1/t \\), dividing by \\( t^{4} \\) gives \\( R = -t^{-5} \\)." },
        { stepNumber: 2, description: "Apply the test.", workingLatex: "P:\\ \\text{order }1\\ (\\le 1), \\qquad R:\\ \\text{order }5\\ (> 2).", explanation: "\\( R \\) far exceeds the double-pole bound." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "z = \\infty \\text{ is irregular.}", explanation: "The high pole order signals the \\( e^{\\pm\\frac23 z^{3/2}} \\) (super-exponential) growth of the Airy functions." },
      ],
      finalAnswer: "\\( z = \\infty \\) is an irregular singular point of the Airy equation.",
      canonicalAnswer: "irregular singular point at infinity",
    },
  },
  {
    id: "am10c-015",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 15",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Distinguish a regular from an irregular singular point at \\( x = 0 \\) for the pair (a) \\( y'' + \\dfrac{1}{x}y' + \\dfrac{1}{x^{2}}y = 0 \\); (b) \\( y'' + \\dfrac{1}{x^{2}}y' + \\dfrac{1}{x}y = 0 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["classification", "finite singular point", "regular vs irregular"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Equation (a) pole orders.", workingLatex: "P = \\frac{1}{x}\\ (\\text{order }1), \\qquad R = \\frac{1}{x^{2}}\\ (\\text{order }2).", explanation: "" },
        { stepNumber: 2, description: "Classify (a).", workingLatex: "x P = 1,\\ x^{2}R = 1 \\text{ analytic} \\;\\Longrightarrow\\; \\text{regular singular}.", explanation: "Both bounds are met with equality; this is a Cauchy–Euler point." },
        { stepNumber: 3, description: "Equation (b) pole orders.", workingLatex: "P = \\frac{1}{x^{2}}\\ (\\text{order }2), \\qquad R = \\frac{1}{x}\\ (\\text{order }1).", explanation: "" },
        { stepNumber: 4, description: "Classify (b).", workingLatex: "xP = \\frac{1}{x} \\text{ not analytic} \\;\\Longrightarrow\\; \\text{irregular singular}.", explanation: "The simple-pole bound on \\( P \\) is violated, so \\( x = 0 \\) is irregular even though \\( R \\) is mild." },
      ],
      finalAnswer: "\\( \\text{(a) regular singular} \\); \\( \\text{(b) irregular singular} \\).",
      canonicalAnswer: "(a) regular singular, (b) irregular singular",
    },
  },
  {
    id: "am10c-016",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the Cauchy–Euler equation \\( y'' + \\dfrac{a}{x}y' + \\dfrac{b}{x^{2}}y = 0 \\) (\\( a,b \\) constants) to normal form and show the invariant has the form \\( I = c/x^{2} \\). Find \\( c \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["normal form", "Cauchy-Euler", "invariant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "I = \\frac{b}{x^{2}} - \\frac{1}{4}\\frac{a^{2}}{x^{2}} - \\frac{1}{2}\\left(-\\frac{a}{x^{2}}\\right) = \\frac{b - \\frac14 a^{2} + \\frac12 a}{x^{2}}.", explanation: "Each term is proportional to \\( 1/x^{2} \\)." },
        { stepNumber: 2, description: "Read off \\( c \\).", workingLatex: "c = b - \\frac{a^{2}}{4} + \\frac{a}{2}.", explanation: "" },
        { stepNumber: 3, description: "Note the structure.", workingLatex: "w = x^{a/2}y: \\quad w'' + \\frac{c}{x^{2}}w = 0,", explanation: "still a Cauchy–Euler (equidimensional) equation, so the class is preserved under reduction to normal form, as expected for an invariant." },
      ],
      finalAnswer: "\\( c = b - \\dfrac{a^{2}}{4} + \\dfrac{a}{2} \\), with \\( I = \\dfrac{c}{x^{2}} \\).",
      canonicalAnswer: "c = b - a^2/4 + a/2",
    },
  },
  {
    id: "am10c-017",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 17",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "The Weber (parabolic-cylinder) equation is \\( y'' + \\left(\\nu + \\tfrac12 - \\tfrac14 x^{2}\\right)y = 0 \\). It is already in normal form. Use LG/WKB to give the leading large-\\( x \\) exponential factor.",
    marks: 4,
    yearCreated: 2026,
    tags: ["LG asymptotics", "Weber", "parabolic cylinder"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the WKB potential.", workingLatex: "w'' = Q\\,w, \\qquad Q = -\\left(\\nu + \\frac12 - \\frac14 x^{2}\\right) = \\frac{x^{2}}{4} - \\nu - \\frac12.", explanation: "Since \\( p = 0 \\), no preliminary reduction is needed; \\( Q = -I \\)." },
        { stepNumber: 2, description: "Large-\\( x \\) WKB phase.", workingLatex: "Q \\sim \\frac{x^{2}}{4}, \\qquad \\int\\sqrt{Q}\\,dx \\sim \\int\\frac{x}{2}\\,dx = \\frac{x^{2}}{4}.", explanation: "The dominant balance \\( Q \\approx x^{2}/4 \\) controls the exponential." },
        { stepNumber: 3, description: "Leading factor.", workingLatex: "y \\sim Q^{-1/4}\\exp\\!\\left(\\pm\\int\\sqrt{Q}\\right) \\sim x^{-1/2}\\,e^{\\pm x^{2}/4}.", explanation: "The recessive solution carries \\( e^{-x^{2}/4} \\); combined with the algebraic prefactor this reproduces \\( D_{\\nu}(x) \\sim x^{\\nu}e^{-x^{2}/4} \\) (the algebraic power is refined by the next WKB order)." },
        { stepNumber: 4, description: "Numerical anchor.", workingLatex: "D_{1}(8) = 9.003\\times10^{-7}, \\qquad x^{\\nu}e^{-x^{2}/4}\\big|_{x=8,\\nu=1} = 9.003\\times10^{-7}.", explanation: "Exact and leading form agree to four significant figures." },
      ],
      finalAnswer: "Leading exponential factor \\( e^{\\pm x^{2}/4} \\); recessive solution \\( \\sim x^{\\nu}e^{-x^{2}/4} \\).",
      canonicalAnswer: "y ~ x^nu e^{-x^2/4}",
    },
  },
  {
    id: "am10c-018",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 18",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the Coulomb-wave equation \\( y'' + \\left(1 - \\dfrac{2\\eta}{x} - \\dfrac{\\ell(\\ell+1)}{x^{2}}\\right)y = 0 \\) and state the leading LG form as \\( x \\to \\infty \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["normal form", "Coulomb wave", "LG asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note it is already normal form.", workingLatex: "p = 0 \\;\\Longrightarrow\\; I = r = 1 - \\frac{2\\eta}{x} - \\frac{\\ell(\\ell+1)}{x^{2}}.", explanation: "No first-derivative term to remove." },
        { stepNumber: 2, description: "WKB potential and its large-\\( x \\) form.", workingLatex: "Q = -I = -1 + \\frac{2\\eta}{x} + \\frac{\\ell(\\ell+1)}{x^{2}} \\to -1.", explanation: "\\( Q < 0 \\) at large \\( x \\): the solution is oscillatory." },
        { stepNumber: 3, description: "Phase including the slow Coulomb term.", workingLatex: "\\int\\sqrt{-Q}\\,dx = \\int\\sqrt{1 - \\frac{2\\eta}{x} - \\cdots}\\,dx \\sim x - \\eta\\ln(2x) + \\text{const}.", explanation: "The \\( -2\\eta/x \\) term integrates to a logarithmic phase, the hallmark of the Coulomb field." },
        { stepNumber: 4, description: "State the LG form.", workingLatex: "y \\sim A\\sin\\!\\left(x - \\eta\\ln 2x - \\frac{\\ell\\pi}{2} + \\sigma_{\\ell}\\right).", explanation: "The amplitude is \\( O(1) \\) since \\( Q \\to -1 \\) (constant); the logarithmic phase shift is the standard Coulomb result." },
      ],
      finalAnswer: "\\( y \\sim A\\sin\\!\\left(x - \\eta\\ln 2x - \\tfrac{\\ell\\pi}{2} + \\sigma_{\\ell}\\right) \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "oscillatory with logarithmic Coulomb phase x - eta ln(2x)",
    },
  },

  // ───────────────────────── CHALLENGE (12) ─────────────────────────
  {
    id: "am10c-019",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 19",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the Hermite equation \\( y'' - 2x\\,y' + 2n\\,y = 0 \\) to normal form, identify the resulting equation, and state the exponential factor governing the large-\\( x \\) behaviour.",
    marks: 5,
    yearCreated: 2026,
    tags: ["normal form", "Hermite", "Weber connection"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "p = -2x,\\ r = 2n,\\ p' = -2: \\quad I = 2n - \\frac{1}{4}(4x^{2}) - \\frac{1}{2}(-2) = 2n + 1 - x^{2}.", explanation: "The \\( -\\tfrac14 p^{2} = -x^{2} \\) term generates the quadratic potential." },
        { stepNumber: 2, description: "Identify the substitution.", workingLatex: "y = w\\,\\exp\\!\\left(-\\frac12\\int -2x\\,dx\\right) = w\\,e^{x^{2}/2}, \\qquad w = y\\,e^{-x^{2}/2}.", explanation: "So \\( w \\) is the Hermite function \\( e^{-x^{2}/2}H_{n}(x) \\)." },
        { stepNumber: 3, description: "State the normal form.", workingLatex: "w'' + (2n + 1 - x^{2})\\,w = 0.", explanation: "This is exactly the Weber/parabolic-cylinder equation with \\( \\nu = n \\); the reduction maps Hermite to Weber." },
        { stepNumber: 4, description: "Large-\\( x \\) exponential factor.", workingLatex: "Q = x^{2} - 2n - 1 \\sim x^{2}, \\qquad \\int\\sqrt{Q} \\sim \\frac{x^{2}}{2} \\;\\Longrightarrow\\; w \\sim e^{\\pm x^{2}/2}.", explanation: "The recessive Hermite function \\( e^{-x^{2}/2}H_{n} \\) carries \\( w \\sim e^{-x^{2}/2} \\), so \\( H_{n} \\) itself grows like \\( e^{x^{2}/2}\\cdot e^{-x^{2}/2}\\cdot(\\text{poly}) \\) — i.e. polynomially, as it must for a polynomial." },
      ],
      finalAnswer: "Normal form \\( w'' + (2n+1-x^{2})w = 0 \\) (Weber); factor \\( e^{\\pm x^{2}/2} \\).",
      canonicalAnswer: "w''+(2n+1-x^2)w=0",
    },
  },
  {
    id: "am10c-020",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 20",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For the normal form \\( W'' = Q(z)W \\) with \\( Q \\sim z^{m} \\) as \\( z \\to \\infty \\), find the leading exponential factor of the solutions and hence the growth exponent (\"rank\") of the irregular singular point at \\( \\infty \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["rank", "exponential factor", "WKB phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the LG exponent.", workingLatex: "W \\sim Q^{-1/4}\\exp\\!\\left(\\pm\\int\\sqrt{Q}\\,dz\\right).", explanation: "Standard Liouville–Green leading form, valid where \\( Q \\) is large." },
        { stepNumber: 2, description: "Evaluate the phase integral.", workingLatex: "\\int\\sqrt{Q}\\,dz \\sim \\int z^{m/2}\\,dz = \\frac{z^{(m/2)+1}}{(m/2)+1} = \\frac{2\\,z^{(m+2)/2}}{m+2}.", explanation: "Provided \\( m \\ne -2 \\)." },
        { stepNumber: 3, description: "State the factor and rank.", workingLatex: "W \\sim \\exp\\!\\left(\\pm\\frac{2}{m+2}z^{(m+2)/2}\\right), \\qquad \\text{rank} = \\frac{m+2}{2}.", explanation: "The exponent grows like \\( z^{(m+2)/2} \\); this growth exponent is the rank of the irregular point." },
        { stepNumber: 4, description: "Check standard cases.", workingLatex: "m=0:\\ \\text{rank }1\\ (e^{\\pm z}); \\quad m=1:\\ \\text{rank }\\frac32\\ (e^{\\pm\\frac23 z^{3/2}}); \\quad m=2:\\ \\text{rank }2\\ (e^{\\pm z^{2}/2}).", explanation: "These match the oscillator/Bessel, Airy, and Weber/Hermite cases respectively." },
      ],
      finalAnswer: "\\( W \\sim \\exp\\!\\left(\\pm\\dfrac{2}{m+2}z^{(m+2)/2}\\right) \\); rank \\( = \\dfrac{m+2}{2} \\).",
      canonicalAnswer: "rank = (m+2)/2",
    },
  },
  {
    id: "am10c-021",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 21",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Classify \\( z = \\infty \\) for the Hermite equation \\( y'' - 2z\\,y' + 2n\\,y = 0 \\) via \\( z = 1/t \\), giving the pole orders of the transformed coefficients.",
    marks: 5,
    yearCreated: 2026,
    tags: ["classification", "Hermite", "point at infinity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Transform \\( P \\).", workingLatex: "P(t) = \\frac{2}{t} - \\frac{p(1/t)}{t^{2}} = \\frac{2}{t} - \\frac{-2/t}{t^{2}} = \\frac{2}{t} + \\frac{2}{t^{3}}.", explanation: "Here \\( p(z) = -2z \\) so \\( p(1/t) = -2/t \\); the second piece becomes \\( +2/t^{3} \\)." },
        { stepNumber: 2, description: "Transform \\( R \\).", workingLatex: "R(t) = \\frac{r(1/t)}{t^{4}} = \\frac{2n}{t^{4}}.", explanation: "\\( r = 2n \\) is constant." },
        { stepNumber: 3, description: "Read off pole orders.", workingLatex: "P:\\ \\text{order }3, \\qquad R:\\ \\text{order }4.", explanation: "Both exceed the regular-singular bounds (1 and 2)." },
        { stepNumber: 4, description: "Classify and relate to rank.", workingLatex: "z = \\infty \\text{ irregular}; \\quad Q \\sim z^{2} \\Rightarrow \\text{rank } 2.", explanation: "The high pole orders are consistent with the normal-form potential \\( Q \\sim z^{2} \\) found earlier, giving rank 2 and the \\( e^{\\pm z^{2}/2} \\) factor." },
      ],
      finalAnswer: "\\( z = \\infty \\) irregular: \\( P \\) has pole order 3, \\( R \\) order 4 (rank 2).",
      canonicalAnswer: "irregular, P order 3, R order 4, rank 2",
    },
  },
  {
    id: "am10c-022",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 22",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce \\( y'' + 2\\,y' + \\left(1 + \\dfrac{1}{x^{2}}\\right)y = 0 \\) to normal form, solve the normal form exactly (Cauchy–Euler), and write the general solution \\( y(x) \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["normal form", "exact comparison", "Cauchy-Euler"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "p = 2,\\ r = 1 + \\frac{1}{x^{2}},\\ p' = 0: \\quad I = 1 + \\frac{1}{x^{2}} - 1 - 0 = \\frac{1}{x^{2}}.", explanation: "The constant damping removes the \\( O(1) \\) part of \\( r \\), leaving a pure Euler potential." },
        { stepNumber: 2, description: "Substitution and normal form.", workingLatex: "y = w\\,e^{-x}, \\qquad w'' + \\frac{1}{x^{2}}w = 0.", explanation: "The factor is \\( \\exp(-\\tfrac12\\int 2) = e^{-x} \\)." },
        { stepNumber: 3, description: "Solve the Euler equation.", workingLatex: "w = x^{m}: \\quad m(m-1) + 1 = 0 \\;\\Longrightarrow\\; m = \\frac{1}{2} \\pm \\frac{\\sqrt{3}}{2}i.", explanation: "The indicial equation has complex roots." },
        { stepNumber: 4, description: "Real form of \\( w \\).", workingLatex: "w = \\sqrt{x}\\left[A\\cos\\!\\left(\\frac{\\sqrt3}{2}\\ln x\\right) + B\\sin\\!\\left(\\frac{\\sqrt3}{2}\\ln x\\right)\\right].", explanation: "Complex exponents \\( x^{1/2 \\pm i\\sqrt3/2} = \\sqrt{x}\\,e^{\\pm i(\\sqrt3/2)\\ln x} \\) give oscillation in \\( \\ln x \\)." },
        { stepNumber: 5, description: "Unscale.", workingLatex: "y = e^{-x}\\sqrt{x}\\left[A\\cos\\!\\left(\\frac{\\sqrt3}{2}\\ln x\\right) + B\\sin\\!\\left(\\frac{\\sqrt3}{2}\\ln x\\right)\\right].", explanation: "Verified by substitution in sympy: residual is identically zero." },
      ],
      finalAnswer: "\\( y = e^{-x}\\sqrt{x}\\left[A\\cos\\!\\left(\\tfrac{\\sqrt3}{2}\\ln x\\right) + B\\sin\\!\\left(\\tfrac{\\sqrt3}{2}\\ln x\\right)\\right] \\).",
      canonicalAnswer: "y = e^{-x} sqrt(x) [A cos((sqrt3/2)ln x)+B sin((sqrt3/2)ln x)]",
    },
  },
  {
    id: "am10c-023",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 23",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For the Airy equation \\( y'' = z\\,y \\) (already in normal form), use LG to obtain the leading recessive form as \\( z \\to +\\infty \\) and compare numerically with \\( \\mathrm{Ai}(z) \\sim \\dfrac{1}{2\\sqrt{\\pi}}z^{-1/4}e^{-\\frac23 z^{3/2}} \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["LG asymptotics", "Airy", "exact comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "WKB potential and phase.", workingLatex: "Q = z, \\qquad \\int\\sqrt{Q}\\,dz = \\int z^{1/2}\\,dz = \\frac{2}{3}z^{3/2}.", explanation: "\\( Q > 0 \\) for \\( z > 0 \\), so solutions are exponential (no oscillation)." },
        { stepNumber: 2, description: "LG leading form.", workingLatex: "y \\sim Q^{-1/4}\\exp\\!\\left(\\pm\\frac{2}{3}z^{3/2}\\right) = z^{-1/4}\\,e^{\\pm\\frac23 z^{3/2}}.", explanation: "The amplitude prefactor \\( Q^{-1/4} = z^{-1/4} \\) is the standard LG factor." },
        { stepNumber: 3, description: "Identify the recessive solution.", workingLatex: "\\mathrm{Ai}(z) \\sim \\frac{1}{2\\sqrt{\\pi}}\\,z^{-1/4}\\,e^{-\\frac23 z^{3/2}}.", explanation: "The decaying branch fixes the sign \\( - \\); the constant \\( 1/(2\\sqrt\\pi) \\) comes from matching, beyond leading LG." },
        { stepNumber: 4, description: "Numerical check.", workingLatex: "z = 9: \\quad \\mathrm{Ai}(9) = 2.471\\times10^{-9}, \\qquad \\frac{1}{2\\sqrt\\pi}\\,9^{-1/4}e^{-\\frac23 9^{3/2}} = 2.481\\times10^{-9}.", explanation: "Ratio \\( 0.996 \\); the small gap is the next LG order." },
      ],
      finalAnswer: "\\( y \\sim z^{-1/4}e^{\\pm\\frac23 z^{3/2}} \\); recessive \\( \\mathrm{Ai}(z) \\sim \\dfrac{1}{2\\sqrt\\pi}z^{-1/4}e^{-\\frac23 z^{3/2}} \\).",
      canonicalAnswer: "Ai(z) ~ (1/(2 sqrt pi)) z^{-1/4} e^{-2/3 z^{3/2}}",
    },
  },
  {
    id: "am10c-024",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 24",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce the Legendre equation in the angular variable \\( y'' + \\cot\\theta\\,y' + \\lambda\\,y = 0 \\) to normal form, and state the invariant.",
    marks: 5,
    yearCreated: 2026,
    tags: ["normal form", "Legendre", "invariant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify coefficients.", workingLatex: "p = \\cot\\theta, \\qquad p' = -\\csc^{2}\\theta, \\qquad r = \\lambda.", explanation: "" },
        { stepNumber: 2, description: "Apply the invariant formula.", workingLatex: "I = \\lambda - \\frac{1}{4}\\cot^{2}\\theta - \\frac{1}{2}(-\\csc^{2}\\theta) = \\lambda - \\frac{1}{4}\\cot^{2}\\theta + \\frac{1}{2}\\csc^{2}\\theta.", explanation: "" },
        { stepNumber: 3, description: "Simplify using \\( \\cot^{2} = \\csc^{2} - 1 \\).", workingLatex: "I = \\lambda - \\frac{1}{4}(\\csc^{2}\\theta - 1) + \\frac{1}{2}\\csc^{2}\\theta = \\lambda + \\frac{1}{4} + \\frac{1}{4}\\csc^{2}\\theta.", explanation: "Verified with sympy. The \\( \\csc^{2}\\theta \\) term blows up at the poles \\( \\theta = 0,\\pi \\), reflecting the singularities there." },
        { stepNumber: 4, description: "State the substitution.", workingLatex: "w = \\sqrt{\\sin\\theta}\\,y, \\qquad w'' + \\left(\\lambda + \\frac{1}{4} + \\frac{1}{4}\\csc^{2}\\theta\\right)w = 0.", explanation: "Since \\( \\exp(-\\tfrac12\\int\\cot\\theta) = (\\sin\\theta)^{-1/2} \\), we have \\( y = (\\sin\\theta)^{-1/2}w \\)." },
      ],
      finalAnswer: "\\( I = \\lambda + \\dfrac{1}{4} + \\dfrac{1}{4}\\csc^{2}\\theta \\), with \\( w = \\sqrt{\\sin\\theta}\\,y \\).",
      canonicalAnswer: "I = lambda + 1/4 + csc^2(theta)/4",
    },
  },
  {
    id: "am10c-025",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 25",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Classify \\( z = \\infty \\) for \\( y'' + \\dfrac{4}{z}y' + \\left(1 - \\dfrac{m^{2}}{z^{2}}\\right)y = 0 \\), then reduce to normal form and give the leading LG amplitude exponent.",
    marks: 6,
    yearCreated: 2026,
    tags: ["classification", "normal form", "LG asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Classify at infinity.", workingLatex: "P(t) = \\frac{2}{t} - \\frac{4/t}{t^{2}}\\cdot\\frac{1}{1} \\Rightarrow \\frac{2}{t} - \\frac{4}{t}\\cdot\\frac{1}{t^{?}}.", explanation: "Carefully: \\( p(z) = 4/z \\Rightarrow p(1/t) = 4t \\), so \\( P = 2/t - (4t)/t^{2} = 2/t - 4/t = -2/t \\)." },
        { stepNumber: 2, description: "Transformed coefficients.", workingLatex: "P(t) = -\\frac{2}{t}\\ (\\text{order }1), \\qquad R(t) = \\frac{1 - m^{2}t^{2}}{t^{4}}\\ (\\text{order }4).", explanation: "\\( R \\) has a pole of order 4, so \\( z = \\infty \\) is irregular." },
        { stepNumber: 3, description: "Invariant.", workingLatex: "I = \\left(1 - \\frac{m^{2}}{z^{2}}\\right) - \\frac{1}{4}\\frac{16}{z^{2}} - \\frac{1}{2}\\left(-\\frac{4}{z^{2}}\\right) = 1 - \\frac{m^{2} + 2}{z^{2}}.", explanation: "Combine: \\( -m^{2} - 4 + 2 = -(m^{2}+2) \\). (Verified with sympy.)" },
        { stepNumber: 4, description: "Substitution and LG amplitude.", workingLatex: "w = z^{2}y, \\qquad w'' + \\left(1 - \\frac{m^{2}+2}{z^{2}}\\right)w \\approx w'' + w = 0.", explanation: "With \\( p = 4/z \\), \\( \\exp(-\\tfrac12\\int 4/z) = z^{-2} \\), so \\( y = z^{-2}w \\); the amplitude of \\( y \\) decays like \\( z^{-2} \\)." },
        { stepNumber: 5, description: "Leading LG form.", workingLatex: "y \\sim \\frac{A}{z^{2}}\\cos(z - \\phi).", explanation: "Oscillatory (rank 1 at \\( \\infty \\)) with a \\( 1/z^{2} \\) amplitude from the prefactor." },
      ],
      finalAnswer: "\\( z = \\infty \\) irregular; \\( y \\sim \\dfrac{A}{z^{2}}\\cos(z - \\phi) \\).",
      canonicalAnswer: "y ~ A cos(z-phi)/z^2",
    },
  },
  {
    id: "am10c-026",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 26",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce \\( y'' + \\dfrac{1}{x}y' - \\left(k^{2} + \\dfrac{\\nu^{2}}{x^{2}}\\right)y = 0 \\) (with \\( k > 0 \\) constant) to normal form, and give the two leading LG forms as \\( x \\to \\infty \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["normal form", "modified Bessel", "LG asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the invariant.", workingLatex: "I = -\\left(k^{2} + \\frac{\\nu^{2}}{x^{2}}\\right) - \\frac{1}{4x^{2}} + \\frac{1}{2x^{2}} = -k^{2} - \\frac{\\nu^{2} - \\frac14}{x^{2}}.", explanation: "The \\( O(1) \\) part is \\( -k^{2} \\) (verified with sympy)." },
        { stepNumber: 2, description: "Substitution and normal form.", workingLatex: "w = \\sqrt{x}\\,y, \\qquad w'' - \\left(k^{2} + \\frac{\\nu^{2}-\\frac14}{x^{2}}\\right)w = 0.", explanation: "This is a scaled modified-Bessel equation; \\( Q \\to k^{2} > 0 \\)." },
        { stepNumber: 3, description: "Large-\\( x \\) WKB phase.", workingLatex: "\\int\\sqrt{Q}\\,dx \\sim \\int k\\,dx = kx \\;\\Longrightarrow\\; w \\sim A\\,e^{kx} + B\\,e^{-kx}.", explanation: "Exponential growth/decay at rate \\( k \\)." },
        { stepNumber: 4, description: "Unscale.", workingLatex: "y = \\frac{w}{\\sqrt{x}} \\sim \\frac{A\\,e^{kx} + B\\,e^{-kx}}{\\sqrt{x}}.", explanation: "These are \\( I_{\\nu}(kx) \\) and \\( K_{\\nu}(kx) \\); e.g. \\( K_{\\nu}(kx) \\sim \\sqrt{\\pi/(2kx)}\\,e^{-kx} \\)." },
      ],
      finalAnswer: "\\( y \\sim \\dfrac{A\\,e^{kx} + B\\,e^{-kx}}{\\sqrt{x}} \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "y ~ (A e^{kx} + B e^{-kx})/sqrt(x)",
    },
  },
  {
    id: "am10c-027",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 27",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Show that the invariant \\( I \\) is unchanged under the gauge transformation \\( y \\mapsto \\tilde{y} = f(x)\\,y \\), explaining why \\( I \\) (not \\( p \\) or \\( r \\)) characterises the equation.",
    marks: 6,
    yearCreated: 2026,
    tags: ["invariant", "gauge", "theory"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the transformed equation.", workingLatex: "y = \\frac{\\tilde y}{f}: \\quad y' = \\frac{\\tilde y'}{f} - \\frac{f'}{f^{2}}\\tilde y, \\quad y'' = \\frac{\\tilde y''}{f} - \\frac{2f'}{f^{2}}\\tilde y' + \\left(\\frac{2f'^{2}}{f^{3}} - \\frac{f''}{f^{2}}\\right)\\tilde y.", explanation: "Differentiate \\( y = \\tilde y / f \\) twice." },
        { stepNumber: 2, description: "Substitute into \\( y'' + p y' + r y = 0 \\) and multiply by \\( f \\).", workingLatex: "\\tilde y'' + \\left(p - \\frac{2f'}{f}\\right)\\tilde y' + \\tilde r\\,\\tilde y = 0, \\qquad \\tilde p = p - \\frac{2f'}{f}.", explanation: "The new first-derivative coefficient picks up \\( -2f'/f \\)." },
        { stepNumber: 3, description: "Compute the new \\( \\tilde r \\).", workingLatex: "\\tilde r = r - p\\frac{f'}{f} + \\frac{2f'^{2}}{f^{2}} - \\frac{f''}{f}.", explanation: "Collect the coefficients of \\( \\tilde y \\) after multiplying by \\( f \\)." },
        { stepNumber: 4, description: "Form the new invariant.", workingLatex: "\\tilde I = \\tilde r - \\frac{1}{4}\\tilde p^{2} - \\frac{1}{2}\\tilde p'.", explanation: "Now substitute \\( \\tilde p = p - 2f'/f \\) and \\( \\tilde r \\) above." },
        { stepNumber: 5, description: "Simplify.", workingLatex: "\\tilde I = r - \\frac{1}{4}p^{2} - \\frac{1}{2}p' = I.", explanation: "All the \\( f \\)-dependent terms cancel (confirmed by direct expansion / sympy). The reduction to normal form is the special case \\( f = \\exp(\\tfrac12\\int p) \\), which sets \\( \\tilde p = 0 \\)." },
        { stepNumber: 6, description: "Interpret.", workingLatex: "I \\text{ is gauge-invariant.}", explanation: "Hence \\( I \\) — equivalently \\( Q = -I \\) in \\( W'' = QW \\) — is the genuine geometric content; \\( p \\) and \\( r \\) separately are gauge artefacts." },
      ],
      finalAnswer: "\\( \\tilde I = I \\): the invariant is unchanged by \\( y \\mapsto f(x)y \\).",
      canonicalAnswer: "I is invariant under y -> f(x) y",
    },
  },
  {
    id: "am10c-028",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 28",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For the Bessel normal form \\( w'' + \\left(1 - \\dfrac{\\nu^{2}-\\tfrac14}{x^{2}}\\right)w = 0 \\), use LG with the next-order phase to recover the full leading asymptotic \\( J_{\\nu}(x) \\sim \\sqrt{\\dfrac{2}{\\pi x}}\\cos\\!\\left(x - \\dfrac{\\nu\\pi}{2} - \\dfrac{\\pi}{4}\\right) \\), and check it numerically.",
    marks: 6,
    yearCreated: 2026,
    tags: ["LG asymptotics", "Bessel", "phase", "exact comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "WKB potential.", workingLatex: "Q = -\\left(1 - \\frac{\\nu^{2}-\\frac14}{x^{2}}\\right) = -1 + \\frac{\\nu^{2}-\\frac14}{x^{2}}.", explanation: "\\( Q < 0 \\): oscillatory. The phase uses \\( \\sqrt{-Q} \\)." },
        { stepNumber: 2, description: "Expand the phase integrand.", workingLatex: "\\sqrt{-Q} = \\sqrt{1 - \\frac{\\nu^{2}-\\frac14}{x^{2}}} = 1 - \\frac{\\nu^{2}-\\frac14}{2x^{2}} + \\cdots", explanation: "Binomial expansion for large \\( x \\)." },
        { stepNumber: 3, description: "Integrate.", workingLatex: "\\int\\sqrt{-Q}\\,dx = x + \\frac{\\nu^{2}-\\frac14}{2x} + C + \\cdots", explanation: "The \\( 1/x^{2} \\) correction integrates to a vanishing \\( O(1/x) \\) phase shift; the constant \\( C \\) carries the \\( -\\nu\\pi/2 - \\pi/4 \\) offset fixed by matching at the turning point / origin." },
        { stepNumber: 4, description: "LG amplitude.", workingLatex: "w \\sim (-Q)^{-1/4}\\cos\\!\\left(\\int\\sqrt{-Q}\\right) \\sim \\cos\\!\\left(x - \\frac{\\nu\\pi}{2} - \\frac{\\pi}{4}\\right).", explanation: "Since \\( -Q \\to 1 \\), the amplitude prefactor \\( (-Q)^{-1/4} \\to 1 \\)." },
        { stepNumber: 5, description: "Unscale and normalise.", workingLatex: "y = \\frac{w}{\\sqrt{x}} \\;\\Longrightarrow\\; J_{\\nu}(x) \\sim \\sqrt{\\frac{2}{\\pi x}}\\cos\\!\\left(x - \\frac{\\nu\\pi}{2} - \\frac{\\pi}{4}\\right).", explanation: "The \\( \\sqrt{2/\\pi} \\) normalisation is fixed by matching to small-\\( x \\) Bessel behaviour, beyond LG." },
        { stepNumber: 6, description: "Numerical check.", workingLatex: "\\nu = 0,\\ x = 50: \\quad J_{0}(50) = 0.05581, \\qquad \\sqrt{\\frac{2}{50\\pi}}\\cos(50 - \\frac\\pi4) = 0.05606.", explanation: "Agreement to \\( O(1/x) \\), as expected from the leading LG form." },
      ],
      finalAnswer: "\\( J_{\\nu}(x) \\sim \\sqrt{\\dfrac{2}{\\pi x}}\\cos\\!\\left(x - \\dfrac{\\nu\\pi}{2} - \\dfrac{\\pi}{4}\\right) \\).",
      canonicalAnswer: "J_nu(x) ~ sqrt(2/(pi x)) cos(x - nu pi/2 - pi/4)",
    },
  },
  {
    id: "am10c-029",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 29",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Determine the number of formal exponential solutions and their leading factors at \\( z = \\infty \\) for \\( W'' = (z^{4} + z)\\,W \\), and state the rank of the irregular point.",
    marks: 5,
    yearCreated: 2026,
    tags: ["rank", "exponential factor", "formal solutions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the growth of \\( Q \\).", workingLatex: "Q = z^{4} + z \\sim z^{4}, \\qquad m = 4.", explanation: "The leading power of \\( Q \\) sets the rank via \\( (m+2)/2 \\)." },
        { stepNumber: 2, description: "Compute the LG phase.", workingLatex: "\\int\\sqrt{Q}\\,dz \\sim \\int z^{2}\\,dz = \\frac{z^{3}}{3}.", explanation: "Two signs give the dominant and subdominant solutions." },
        { stepNumber: 3, description: "Leading factors.", workingLatex: "W \\sim Q^{-1/4}\\,e^{\\pm z^{3}/3} \\sim z^{-1}\\,e^{\\pm z^{3}/3}.", explanation: "There are two formal exponential solutions (dominant \\( e^{+z^{3}/3} \\), subdominant \\( e^{-z^{3}/3} \\)); the amplitude prefactor is \\( Q^{-1/4}\\sim z^{-1} \\)." },
        { stepNumber: 4, description: "State the rank.", workingLatex: "\\text{rank} = \\frac{m+2}{2} = \\frac{6}{2} = 3.", explanation: "The exponent grows like \\( z^{3} \\), so the irregular singular point at \\( \\infty \\) has rank 3." },
      ],
      finalAnswer: "Two solutions \\( W \\sim z^{-1}e^{\\pm z^{3}/3} \\); rank 3.",
      canonicalAnswer: "W ~ z^{-1} e^{+- z^3/3}, rank 3",
    },
  },
  {
    id: "am10c-030",
    topicRef: "am10c",
    topicTitle: "Normal form & irregular singular points 30",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Reduce \\( y'' + (\\tan x)\\,y' + y = 0 \\) to normal form, giving the substitution and the invariant \\( I \\). Hence write the normal-form equation.",
    marks: 5,
    yearCreated: 2026,
    tags: ["normal form", "invariant", "trigonometric coefficient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify coefficients.", workingLatex: "p = \\tan x, \\qquad p' = \\sec^{2}x, \\qquad r = 1.", explanation: "" },
        { stepNumber: 2, description: "Apply the invariant formula.", workingLatex: "I = 1 - \\frac{1}{4}\\tan^{2}x - \\frac{1}{2}\\sec^{2}x.", explanation: "" },
        { stepNumber: 3, description: "Simplify with \\( \\tan^{2} = \\sec^{2} - 1 \\).", workingLatex: "I = 1 - \\frac{1}{4}(\\sec^{2}x - 1) - \\frac{1}{2}\\sec^{2}x = \\frac{5}{4} - \\frac{3}{4}\\sec^{2}x.", explanation: "Collect: \\( -\\frac14 - \\frac12 = -\\frac34 \\) on \\( \\sec^{2}x \\), and \\( 1 + \\frac14 = \\frac54 \\) constant (verified with sympy)." },
        { stepNumber: 4, description: "Substitution.", workingLatex: "y = w\\,\\exp\\!\\left(-\\frac12\\int\\tan x\\,dx\\right) = w\\,e^{\\frac12\\ln\\cos x} = w\\sqrt{\\cos x}.", explanation: "Since \\( \\int\\tan x = -\\ln\\cos x \\)." },
        { stepNumber: 5, description: "State the normal form.", workingLatex: "w'' + \\left(\\frac{5}{4} - \\frac{3}{4}\\sec^{2}x\\right)w = 0, \\qquad w = \\frac{y}{\\sqrt{\\cos x}}.", explanation: "The \\( \\sec^{2}x \\) term shows the (irregular-type) singularities at \\( x = \\pi/2 + n\\pi \\), where \\( \\cos x \\) vanishes." },
      ],
      finalAnswer: "\\( I = \\dfrac{5}{4} - \\dfrac{3}{4}\\sec^{2}x \\); \\( w'' + I\\,w = 0 \\) with \\( w = \\dfrac{y}{\\sqrt{\\cos x}} \\).",
      canonicalAnswer: "I = 5/4 - (3/4)sec^2(x)",
    },
  },
];
