import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Liouville–Green & WKB
 * Subtopic am10d: WKB quantisation & barrier tunnelling
 * 30 fully-worked questions (6 Foundation / 12 Standard / 12 Challenge).
 *
 * Theme: the Bohr–Sommerfeld rule \( \int \sqrt{2m(E-V)}\,dx = (n+\tfrac12)\pi\hbar \)
 * for bound states (harmonic, linear, quartic, Pöschl–Teller), the Maslov \( \tfrac12 \)
 * from turning-point connection formulae, and barrier transmission
 * \( T \sim e^{-2\gamma} \), \( \gamma = \tfrac1\hbar\int\sqrt{2m(V-E)}\,dx \).
 *
 * Numerical spot-checks (mpmath quad / gamma / beta) were run for every action
 * integral, every special-function constant (e.g. \( \Gamma(1/4) \)) and every
 * tunnelling integral; the SHO check returns \( E_n=(n+\tfrac12)\hbar\omega \) exactly.
 */
export const questions: Question[] = [
  // ───────────────────────── FOUNDATION (6) ─────────────────────────
  {
    id: "am10d-001",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the Bohr–Sommerfeld quantisation condition for a particle of mass \\( m \\) and energy \\( E \\) trapped between two soft (linear) turning points \\( x_{1} < x_{2} \\) of a potential \\( V(x) \\), and identify the turning points.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Bohr-Sommerfeld", "turning points", "WKB"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the local momentum in the classically allowed region.", workingLatex: "p(x) = \\sqrt{2m\\left(E - V(x)\\right)}, \\qquad V(x) \\le E.", explanation: "Inside the well \\( E > V \\) so \\( p \\) is real and the WKB wavefunction is oscillatory." },
        { stepNumber: 2, description: "Identify the turning points.", workingLatex: "V(x_{1}) = V(x_{2}) = E, \\qquad x_{1} < x_{2}.", explanation: "The turning points are where the classical momentum vanishes; between them the motion is allowed." },
        { stepNumber: 3, description: "Quote the quantisation rule.", workingLatex: "\\int_{x_{1}}^{x_{2}} \\sqrt{2m\\left(E - V(x)\\right)}\\, dx = \\left(n + \\frac{1}{2}\\right)\\pi\\hbar, \\qquad n = 0,1,2,\\dots", explanation: "The \\( \\tfrac12 \\) is the Maslov index: each soft turning point contributes a \\( -\\pi/4 \\) phase from the connection formula." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{x_{1}}^{x_{2}} \\sqrt{2m(E-V)}\\,dx = \\left(n+\\tfrac12\\right)\\pi\\hbar \\), with \\( V(x_{1})=V(x_{2})=E \\).",
      canonicalAnswer: "int sqrt(2m(E-V)) dx = (n+1/2) pi hbar",
    },
  },
  {
    id: "am10d-002",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the harmonic oscillator \\( V = \\tfrac12 m\\omega^{2}x^{2} \\) and energy \\( E \\), find the two classical turning points.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["harmonic oscillator", "turning points"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the potential equal to the energy.", workingLatex: "\\frac{1}{2} m\\omega^{2} x^{2} = E.", explanation: "Turning points occur where all the energy is potential, so \\( V = E \\)." },
        { stepNumber: 2, description: "Solve for \\( x \\).", workingLatex: "x^{2} = \\frac{2E}{m\\omega^{2}} \\;\\Longrightarrow\\; x = \\pm\\sqrt{\\frac{2E}{m\\omega^{2}}}.", explanation: "The well is symmetric, so the turning points are symmetric about the origin." },
      ],
      finalAnswer: "\\( x = \\pm\\sqrt{\\dfrac{2E}{m\\omega^{2}}} \\).",
      canonicalAnswer: "pm sqrt(2E/(m w^2))",
    },
  },
  {
    id: "am10d-003",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "A particle of mass \\( m \\) and energy \\( E \\) meets a rectangular barrier of height \\( V_{0} > E \\) and width \\( L \\). Write down the WKB tunnelling exponent \\( \\gamma \\) defined by \\( T \\approx e^{-2\\gamma} \\), where \\( \\gamma = \\tfrac1\\hbar\\int \\sqrt{2m(V-E)}\\,dx \\) over the forbidden region.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["tunnelling", "rectangular barrier", "transmission"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "The integrand is constant across the barrier.", workingLatex: "V(x) - E = V_{0} - E \\quad (0 \\le x \\le L).", explanation: "For a rectangular barrier the potential does not vary inside the forbidden region." },
        { stepNumber: 2, description: "Evaluate the exponent.", workingLatex: "\\gamma = \\frac{1}{\\hbar}\\int_{0}^{L} \\sqrt{2m(V_{0}-E)}\\, dx = \\frac{L}{\\hbar}\\sqrt{2m(V_{0}-E)}.", explanation: "A constant integrand integrates to itself times the width \\( L \\)." },
      ],
      finalAnswer: "\\( \\gamma = \\dfrac{L}{\\hbar}\\sqrt{2m(V_{0}-E)} \\), so \\( T \\approx e^{-2\\gamma} \\).",
      canonicalAnswer: "L/hbar sqrt(2m(V0-E))",
    },
  },
  {
    id: "am10d-004",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 04",
    difficulty: "Foundation",
    answerType: "exactValue",
    questionText: "For the harmonic oscillator the action integral evaluates to \\( \\displaystyle\\int_{x_{1}}^{x_{2}} \\sqrt{2m\\left(E-\\tfrac12 m\\omega^{2}x^{2}\\right)}\\,dx = \\dfrac{\\pi E}{\\omega} \\). Apply Bohr–Sommerfeld to find the energy levels \\( E_{n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["harmonic oscillator", "Bohr-Sommerfeld", "energy levels"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Equate the action to the quantisation value.", workingLatex: "\\frac{\\pi E}{\\omega} = \\left(n + \\frac{1}{2}\\right)\\pi\\hbar.", explanation: "Insert the given action into the Bohr–Sommerfeld rule." },
        { stepNumber: 2, description: "Solve for \\( E \\).", workingLatex: "E_{n} = \\left(n + \\frac{1}{2}\\right)\\hbar\\omega, \\qquad n = 0,1,2,\\dots", explanation: "The \\( \\pi \\) cancels; WKB reproduces the exact oscillator spectrum, including the zero-point energy \\( \\tfrac12\\hbar\\omega \\)." },
      ],
      finalAnswer: "\\( E_{n} = \\left(n+\\tfrac12\\right)\\hbar\\omega \\).",
      canonicalAnswer: "(n+1/2) hbar w",
    },
  },
  {
    id: "am10d-005",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 05",
    difficulty: "Foundation",
    answerType: "exactValue",
    questionText: "A particle of mass \\( m \\) and energy \\( E \\) tunnels through a rectangular barrier of height \\( V_{0} = 4\\,\\text{(units)} \\), with \\( E = 1 \\), width \\( L = 0.8 \\), taking \\( m = \\hbar = 1 \\). Compute the tunnelling exponent \\( \\gamma \\) and hence \\( 2\\gamma \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["tunnelling", "rectangular barrier", "numeric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use the rectangular formula.", workingLatex: "\\gamma = \\frac{L}{\\hbar}\\sqrt{2m(V_{0}-E)} = 0.8\\sqrt{2\\cdot 1\\cdot(4-1)} = 0.8\\sqrt{6}.", explanation: "Substitute the numbers directly into \\( \\gamma = (L/\\hbar)\\sqrt{2m(V_0-E)} \\)." },
        { stepNumber: 2, description: "Evaluate.", workingLatex: "\\gamma = 0.8\\sqrt{6} \\approx 1.9596, \\qquad 2\\gamma \\approx 3.9192.", explanation: "So \\( T \\approx e^{-2\\gamma} \\approx e^{-3.92} \\approx 0.0199 \\); numerical quad of the integral confirms \\( \\gamma = 1.95959 \\)." },
      ],
      finalAnswer: "\\( \\gamma = 0.8\\sqrt{6} \\approx 1.96 \\), \\( 2\\gamma \\approx 3.92 \\).",
      canonicalAnswer: "0.8 sqrt(6)",
    },
  },
  {
    id: "am10d-006",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Explain why the WKB quantisation of an infinite square well of width \\( L \\) (hard walls at both ends) uses the phase index that gives \\( N = 1,2,3,\\dots \\) rather than \\( (n+\\tfrac12) \\). State the resulting condition on \\( \\sqrt{2mE}\\,L \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["infinite square well", "hard wall", "Maslov index"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Account for the hard-wall phase.", workingLatex: "\\text{soft turning point: } -\\frac{\\pi}{4}, \\qquad \\text{hard wall: } -\\frac{\\pi}{2}.", explanation: "At a hard wall the wavefunction must vanish, forcing a \\( -\\pi/2 \\) phase loss rather than the \\( -\\pi/4 \\) of a soft turning point." },
        { stepNumber: 2, description: "Sum the phases for two hard walls.", workingLatex: "\\frac{1}{\\hbar}\\int_{0}^{L} \\sqrt{2mE}\\, dx = (N)\\,\\pi, \\qquad N = 1,2,3,\\dots", explanation: "Two hard walls contribute \\( \\tfrac{\\pi}{2}+\\tfrac{\\pi}{2}=\\pi \\) of phase, so the right-hand side is \\( N\\pi \\) with \\( N\\ge 1 \\) (no \\( n=0 \\) ground state at zero phase)." },
      ],
      finalAnswer: "\\( \\sqrt{2mE}\\,L = N\\pi\\hbar \\), \\( N=1,2,3,\\dots \\) (hard-wall rule, not \\( n+\\tfrac12 \\)).",
      canonicalAnswer: "sqrt(2mE) L = N pi hbar",
    },
  },

  // ───────────────────────── STANDARD (12) ─────────────────────────
  {
    id: "am10d-007",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 07",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Evaluate the harmonic-oscillator action \\( \\displaystyle\\int_{-x_{t}}^{x_{t}} \\sqrt{2m\\left(E-\\tfrac12 m\\omega^{2}x^{2}\\right)}\\,dx \\) from scratch (with \\( x_{t}=\\sqrt{2E/(m\\omega^{2})} \\)) and hence derive \\( E_{n} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["harmonic oscillator", "action integral", "Bohr-Sommerfeld"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Factor out the turning point.", workingLatex: "\\int_{-x_{t}}^{x_{t}} \\sqrt{2mE}\\,\\sqrt{1 - \\frac{x^{2}}{x_{t}^{2}}}\\; dx, \\qquad x_{t} = \\sqrt{\\frac{2E}{m\\omega^{2}}}.", explanation: "Write \\( E - \\tfrac12 m\\omega^2 x^2 = E\\left(1 - x^2/x_t^2\\right) \\) so the integrand becomes a standard semicircle form." },
        { stepNumber: 2, description: "Substitute \\( x = x_{t}\\sin\\theta \\).", workingLatex: "= \\sqrt{2mE}\\; x_{t} \\int_{-\\pi/2}^{\\pi/2} \\cos^{2}\\theta\\, d\\theta = \\sqrt{2mE}\\; x_{t}\\cdot \\frac{\\pi}{2}.", explanation: "The integral \\( \\int_{-\\pi/2}^{\\pi/2}\\cos^2\\theta\\,d\\theta = \\pi/2 \\) is the area of a half-disc." },
        { stepNumber: 3, description: "Insert \\( x_{t} \\).", workingLatex: "= \\sqrt{2mE}\\cdot \\sqrt{\\frac{2E}{m\\omega^{2}}}\\cdot \\frac{\\pi}{2} = \\frac{2E}{\\omega}\\cdot\\frac{\\pi}{2} = \\frac{\\pi E}{\\omega}.", explanation: "The masses cancel and the energies combine to \\( 2E/\\omega \\)." },
        { stepNumber: 4, description: "Quantise.", workingLatex: "\\frac{\\pi E}{\\omega} = \\left(n+\\frac{1}{2}\\right)\\pi\\hbar \\;\\Longrightarrow\\; E_{n} = \\left(n+\\frac{1}{2}\\right)\\hbar\\omega.", explanation: "Numerical quad of the action at \\( m=\\omega=1 \\) returns \\( \\pi E \\) to machine precision, confirming the exact spectrum." },
      ],
      finalAnswer: "\\( \\text{action}=\\dfrac{\\pi E}{\\omega} \\Rightarrow E_{n}=\\left(n+\\tfrac12\\right)\\hbar\\omega \\).",
      canonicalAnswer: "(n+1/2) hbar w",
    },
  },
  {
    id: "am10d-008",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 08",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A ball of mass \\( m \\) bounces under gravity above a hard floor: \\( V = Fx \\) for \\( x>0 \\) and \\( V=\\infty \\) for \\( x<0 \\). Using one soft turning point and one hard wall, find the quantised energies \\( E_{n} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["bouncing ball", "linear potential", "hard wall", "Airy"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the turning points.", workingLatex: "\\text{hard wall at } x=0; \\qquad Fx_{t}=E \\;\\Rightarrow\\; x_{t}=\\frac{E}{F}.", explanation: "The wall is at the origin; the soft turning point is where the linear potential reaches \\( E \\)." },
        { stepNumber: 2, description: "Fix the phase index.", workingLatex: "\\frac{1}{\\hbar}\\int_{0}^{E/F}\\sqrt{2m(E-Fx)}\\,dx = \\left(n+\\frac{3}{4}\\right)\\pi.", explanation: "One soft point (\\( -\\pi/4 \\)) plus one hard wall (\\( -\\pi/2 \\)) gives a combined index \\( \\tfrac14+\\tfrac12=\\tfrac34 \\)." },
        { stepNumber: 3, description: "Evaluate the action.", workingLatex: "\\int_{0}^{E/F}\\sqrt{2m(E-Fx)}\\,dx = \\frac{2\\sqrt{2m}}{3F}\\,E^{3/2}.", explanation: "Substitute \\( u=E-Fx \\): \\( \\int_0^E\\sqrt{2m\\,u}\\,du/F = \\tfrac{2}{3F}\\sqrt{2m}\\,E^{3/2} \\)." },
        { stepNumber: 4, description: "Solve for \\( E_{n} \\).", workingLatex: "E_{n} = \\left[\\frac{3\\pi F\\hbar}{2\\sqrt{2m}}\\left(n+\\frac{3}{4}\\right)\\right]^{2/3}.", explanation: "Numerical check (\\( m=F=\\hbar=1 \\)): WKB gives \\( E_0=1.842 \\) versus exact Airy value \\( 1.856 \\) — under \\( 1\\% \\) error." },
      ],
      finalAnswer: "\\( E_{n} = \\left[\\dfrac{3\\pi F\\hbar}{2\\sqrt{2m}}\\left(n+\\tfrac34\\right)\\right]^{2/3} \\).",
      canonicalAnswer: "(3 pi F hbar (n+3/4)/(2 sqrt(2m)))^(2/3)",
    },
  },
  {
    id: "am10d-009",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 09",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Find the WKB energy levels of the symmetric linear well \\( V = F|x| \\) (two soft turning points at \\( x=\\pm E/F \\)).",
    marks: 4,
    yearCreated: 2026,
    tags: ["linear well", "absolute value potential", "Bohr-Sommerfeld"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use symmetry.", workingLatex: "\\int_{-E/F}^{E/F}\\sqrt{2m(E-F|x|)}\\,dx = 2\\int_{0}^{E/F}\\sqrt{2m(E-Fx)}\\,dx.", explanation: "The integrand is even, so integrate over the positive half and double." },
        { stepNumber: 2, description: "Evaluate the half-integral.", workingLatex: "2\\cdot \\frac{2\\sqrt{2m}}{3F}E^{3/2} = \\frac{4\\sqrt{2m}}{3F}\\,E^{3/2}.", explanation: "Same antiderivative as the bouncing ball, now doubled." },
        { stepNumber: 3, description: "Apply Bohr–Sommerfeld with two soft points.", workingLatex: "\\frac{4\\sqrt{2m}}{3F\\hbar}\\,E^{3/2} = \\left(n+\\frac{1}{2}\\right)\\pi.", explanation: "Two soft turning points give the standard \\( (n+\\tfrac12) \\) index." },
        { stepNumber: 4, description: "Solve.", workingLatex: "E_{n} = \\left[\\frac{3\\pi F\\hbar}{4\\sqrt{2m}}\\left(n+\\frac{1}{2}\\right)\\right]^{2/3}.", explanation: "Numerical check (\\( m=F=\\hbar=1 \\)): action/\\( \\pi \\) returns \\( n+\\tfrac12 \\) to six figures at the predicted \\( E_n \\)." },
      ],
      finalAnswer: "\\( E_{n} = \\left[\\dfrac{3\\pi F\\hbar}{4\\sqrt{2m}}\\left(n+\\tfrac12\\right)\\right]^{2/3} \\).",
      canonicalAnswer: "(3 pi F hbar (n+1/2)/(4 sqrt(2m)))^(2/3)",
    },
  },
  {
    id: "am10d-010",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 10",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Derive the WKB spectrum of the infinite square well \\( V=0 \\) for \\( 0<x<L \\), \\( V=\\infty \\) otherwise, and confirm it is exact.",
    marks: 3,
    yearCreated: 2026,
    tags: ["infinite square well", "hard wall", "exact spectrum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Both ends are hard walls.", workingLatex: "\\frac{1}{\\hbar}\\int_{0}^{L}\\sqrt{2mE}\\,dx = N\\pi, \\qquad N=1,2,3,\\dots", explanation: "Two hard walls give total phase \\( \\pi \\), so the right-hand side is \\( N\\pi \\) with \\( N \\ge 1 \\), not \\( (n+\\tfrac12)\\pi \\)." },
        { stepNumber: 2, description: "Evaluate the constant integrand.", workingLatex: "\\sqrt{2mE}\\,L = N\\pi\\hbar.", explanation: "The momentum is constant inside the well." },
        { stepNumber: 3, description: "Solve for \\( E_{N} \\).", workingLatex: "E_{N} = \\frac{N^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}}.", explanation: "Squaring and rearranging. This matches the exact eigenvalues exactly, because the WKB wavefunction is the true plane wave here." },
      ],
      finalAnswer: "\\( E_{N} = \\dfrac{N^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}} \\), \\( N=1,2,\\dots \\) (exact).",
      canonicalAnswer: "N^2 pi^2 hbar^2/(2 m L^2)",
    },
  },
  {
    id: "am10d-011",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 11",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A half-harmonic oscillator has \\( V=\\tfrac12 m\\omega^{2}x^{2} \\) for \\( x>0 \\) and a hard wall \\( V=\\infty \\) at \\( x=0 \\). Find its WKB energy levels.",
    marks: 4,
    yearCreated: 2026,
    tags: ["half oscillator", "hard wall", "Maslov index"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the turning points.", workingLatex: "\\text{hard wall at } x=0; \\quad \\text{soft point at } x_{t}=\\sqrt{\\tfrac{2E}{m\\omega^{2}}}.", explanation: "Only the right half of the parabola is physical; the left boundary is a hard wall." },
        { stepNumber: 2, description: "Write the quantisation with index \\( \\tfrac34 \\).", workingLatex: "\\frac{1}{\\hbar}\\int_{0}^{x_{t}}\\sqrt{2m\\left(E-\\tfrac12 m\\omega^{2}x^{2}\\right)}\\,dx = \\left(n+\\frac{3}{4}\\right)\\pi.", explanation: "One hard wall (\\( \\tfrac12 \\)) plus one soft point (\\( \\tfrac14 \\)) gives index \\( \\tfrac34 \\)." },
        { stepNumber: 3, description: "Use half of the full SHO action.", workingLatex: "\\int_{0}^{x_{t}}(\\cdots)\\,dx = \\frac{1}{2}\\cdot\\frac{\\pi E}{\\omega} = \\frac{\\pi E}{2\\omega}.", explanation: "By symmetry the half-range integral is half the full SHO action \\( \\pi E/\\omega \\)." },
        { stepNumber: 4, description: "Solve.", workingLatex: "\\frac{\\pi E}{2\\omega\\hbar} = \\left(n+\\frac{3}{4}\\right)\\pi \\;\\Longrightarrow\\; E_{n} = \\left(2n+\\frac{3}{2}\\right)\\hbar\\omega.", explanation: "These are the odd levels of the full oscillator, \\( (2n+\\tfrac32)\\hbar\\omega \\) — exactly the states with a node at the origin, as required by the wall." },
      ],
      finalAnswer: "\\( E_{n} = \\left(2n+\\tfrac32\\right)\\hbar\\omega \\).",
      canonicalAnswer: "(2n+3/2) hbar w",
    },
  },
  {
    id: "am10d-012",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 12",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Show, by reducing the action integral to a standard form, that the quartic well \\( V=\\alpha x^{4} \\) has \\( \\displaystyle\\int_{-x_{t}}^{x_{t}}\\sqrt{2m(E-\\alpha x^{4})}\\,dx = 2\\sqrt{2mE}\\,(E/\\alpha)^{1/4}\\,C \\) with \\( C=\\int_{0}^{1}\\sqrt{1-u^{4}}\\,du \\). Evaluate \\( C \\) in terms of \\( \\Gamma \\)-functions.",
    marks: 4,
    yearCreated: 2026,
    tags: ["quartic well", "Beta function", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the turning points.", workingLatex: "\\alpha x^{4} = E \\;\\Longrightarrow\\; x_{t} = \\left(\\frac{E}{\\alpha}\\right)^{1/4}.", explanation: "Set the potential equal to \\( E \\) and take the fourth root." },
        { stepNumber: 2, description: "Rescale \\( x = x_{t}u \\).", workingLatex: "\\int \\sqrt{2mE}\\sqrt{1-u^{4}}\\; x_{t}\\,du = \\sqrt{2mE}\\,(E/\\alpha)^{1/4}\\int_{-1}^{1}\\sqrt{1-u^{4}}\\,du.", explanation: "Factor \\( E-\\alpha x^4 = E(1-u^4) \\); the prefactor \\( x_t=(E/\\alpha)^{1/4} \\) comes from \\( dx \\)." },
        { stepNumber: 3, description: "Reduce to a Beta integral.", workingLatex: "C = \\int_{0}^{1}\\sqrt{1-u^{4}}\\,du = \\frac{1}{4}B\\!\\left(\\frac{1}{4},\\frac{3}{2}\\right) = \\frac{\\sqrt{\\pi}}{6}\\,\\frac{\\Gamma(1/4)}{\\Gamma(3/4)}.", explanation: "Sub \\( t=u^4 \\): \\( \\int_0^1 t^{-3/4}(1-t)^{1/2}\\tfrac14\\,dt = \\tfrac14 B(\\tfrac14,\\tfrac32) \\); using \\( B(a,b)=\\Gamma(a)\\Gamma(b)/\\Gamma(a+b) \\) and \\( \\Gamma(3/2)=\\tfrac{\\sqrt\\pi}{2} \\)." },
        { stepNumber: 4, description: "Numerical value.", workingLatex: "C \\approx 0.87402.", explanation: "mpmath quad and the \\( \\Gamma \\)-form agree to 30 digits: \\( C=0.8740191847\\dots \\)." },
      ],
      finalAnswer: "\\( C = \\dfrac{\\sqrt{\\pi}}{6}\\dfrac{\\Gamma(1/4)}{\\Gamma(3/4)} \\approx 0.8740 \\).",
      canonicalAnswer: "sqrt(pi)/6 * Gamma(1/4)/Gamma(3/4)",
    },
  },
  {
    id: "am10d-013",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 13",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Using the result \\( \\displaystyle\\int_{-x_{t}}^{x_{t}}\\sqrt{2m(E-\\alpha x^{4})}\\,dx = 2C\\sqrt{2m}\\,\\alpha^{-1/4}E^{3/4} \\) with \\( C\\approx 0.8740 \\), apply Bohr–Sommerfeld to show \\( E_{n}\\propto (n+\\tfrac12)^{4/3} \\) and give the constant.",
    marks: 4,
    yearCreated: 2026,
    tags: ["quartic well", "energy scaling", "Bohr-Sommerfeld"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the action equal to the quantisation value.", workingLatex: "2C\\sqrt{2m}\\,\\alpha^{-1/4}E^{3/4} = \\left(n+\\frac{1}{2}\\right)\\pi\\hbar.", explanation: "Two soft turning points, so the index is \\( n+\\tfrac12 \\)." },
        { stepNumber: 2, description: "Solve for \\( E^{3/4} \\).", workingLatex: "E^{3/4} = \\frac{\\left(n+\\frac{1}{2}\\right)\\pi\\hbar\\,\\alpha^{1/4}}{2C\\sqrt{2m}}.", explanation: "Isolate the energy factor." },
        { stepNumber: 3, description: "Raise to the \\( 4/3 \\) power.", workingLatex: "E_{n} = \\left[\\frac{\\pi\\hbar}{2C}\\right]^{4/3}\\frac{\\alpha^{1/3}}{(2m)^{2/3}}\\left(n+\\frac{1}{2}\\right)^{4/3}.", explanation: "The \\( \\alpha^{1/4} \\) becomes \\( \\alpha^{1/3} \\) and the \\( \\sqrt{2m} \\) becomes \\( (2m)^{2/3} \\) in the denominator." },
        { stepNumber: 4, description: "State the scaling.", workingLatex: "E_{n} \\propto \\left(n+\\tfrac12\\right)^{4/3}.", explanation: "Numerical check (\\( m=\\alpha=\\hbar=1 \\)): \\( E_0=0.5463 \\), and the action at this \\( E \\) returns \\( (n+\\tfrac12)\\pi \\) to machine precision; \\( E_1/E_0 = 3^{4/3}=4.327 \\)." },
      ],
      finalAnswer: "\\( E_{n} = \\left[\\dfrac{\\pi\\hbar}{2C}\\right]^{4/3}\\dfrac{\\alpha^{1/3}}{(2m)^{2/3}}\\left(n+\\tfrac12\\right)^{4/3} \\), \\( C=\\dfrac{\\sqrt\\pi}{6}\\dfrac{\\Gamma(1/4)}{\\Gamma(3/4)} \\).",
    },
  },
  {
    id: "am10d-014",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 14",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Evaluate the tunnelling exponent \\( \\gamma = \\tfrac1\\hbar\\int_{-x_{*}}^{x_{*}}\\sqrt{2m(V-E)}\\,dx \\) for the parabolic barrier \\( V=V_{0}(1-x^{2}/a^{2}) \\), where \\( \\pm x_{*} \\) are the points with \\( V=E \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["tunnelling", "parabolic barrier", "transmission"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the edges of the forbidden region.", workingLatex: "V_{0}\\left(1-\\frac{x^{2}}{a^{2}}\\right)=E \\;\\Longrightarrow\\; x_{*}=a\\sqrt{1-\\frac{E}{V_{0}}}.", explanation: "The barrier exceeds \\( E \\) for \\( |x| < x_* \\)." },
        { stepNumber: 2, description: "Rewrite the integrand as a semicircle.", workingLatex: "V-E = V_{0}\\left(1-\\frac{E}{V_{0}}\\right)\\left(1-\\frac{x^{2}}{x_{*}^{2}}\\right) = (V_{0}-E)\\left(1-\\frac{x^{2}}{x_{*}^{2}}\\right).", explanation: "Factor so that the bracket vanishes at \\( x=\\pm x_* \\)." },
        { stepNumber: 3, description: "Integrate the semicircle.", workingLatex: "\\gamma = \\frac{\\sqrt{2m(V_{0}-E)}}{\\hbar}\\int_{-x_{*}}^{x_{*}}\\sqrt{1-\\frac{x^{2}}{x_{*}^{2}}}\\,dx = \\frac{\\sqrt{2m(V_{0}-E)}}{\\hbar}\\cdot\\frac{\\pi x_{*}}{2}.", explanation: "The integral is the area of a half-disc of radius \\( x_* \\): \\( \\tfrac{\\pi}{2}x_* \\)." },
        { stepNumber: 4, description: "Insert \\( x_{*} \\) and simplify.", workingLatex: "\\gamma = \\frac{\\pi a}{2\\hbar}\\sqrt{2m}\\,\\frac{V_{0}-E}{\\sqrt{V_{0}}}.", explanation: "Numerical check (\\( m=\\hbar=a=1,V_0=3,E=1 \\)): quad gives \\( \\gamma=2.56510 \\), matching the formula to 24 digits." },
      ],
      finalAnswer: "\\( \\gamma = \\dfrac{\\pi a}{2\\hbar}\\sqrt{2m}\\,\\dfrac{V_{0}-E}{\\sqrt{V_{0}}} \\).",
      canonicalAnswer: "pi a sqrt(2m) (V0-E)/(2 hbar sqrt(V0))",
    },
  },
  {
    id: "am10d-015",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 15",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "For field emission the barrier is triangular: \\( V(x)=V_{0}-Fx \\) for \\( x>0 \\), with electron energy \\( E<V_{0} \\). Find the Fowler–Nordheim tunnelling exponent \\( \\gamma \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["tunnelling", "triangular barrier", "Fowler-Nordheim"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the forbidden region.", workingLatex: "V_{0}-Fx = E \\;\\Longrightarrow\\; x_{b}=\\frac{V_{0}-E}{F}, \\qquad W:=V_{0}-E.", explanation: "The barrier is classically forbidden from \\( x=0 \\) to \\( x=x_b \\)." },
        { stepNumber: 2, description: "Set up the integral.", workingLatex: "\\gamma = \\frac{1}{\\hbar}\\int_{0}^{W/F}\\sqrt{2m\\left(W-Fx\\right)}\\,dx.", explanation: "Here \\( V-E = (V_0-E)-Fx = W-Fx \\)." },
        { stepNumber: 3, description: "Substitute \\( u=W-Fx \\).", workingLatex: "\\gamma = \\frac{1}{\\hbar F}\\int_{0}^{W}\\sqrt{2m\\,u}\\,du = \\frac{1}{\\hbar F}\\cdot\\frac{2\\sqrt{2m}}{3}\\,W^{3/2}.", explanation: "A standard power-rule integral." },
        { stepNumber: 4, description: "State the result.", workingLatex: "\\gamma = \\frac{2\\sqrt{2m}}{3\\hbar F}\\,(V_{0}-E)^{3/2}.", explanation: "Numerical check (\\( m=\\hbar=1,V_0=5,E=1,F=2 \\)): quad gives \\( \\gamma=3.77124 \\), matching the formula. This \\( (V_0-E)^{3/2}/F \\) law is the heart of Fowler–Nordheim emission." },
      ],
      finalAnswer: "\\( \\gamma = \\dfrac{2\\sqrt{2m}}{3\\hbar F}\\,(V_{0}-E)^{3/2} \\).",
      canonicalAnswer: "2 sqrt(2m) (V0-E)^(3/2)/(3 hbar F)",
    },
  },
  {
    id: "am10d-016",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Explain, from the turning-point connection formula, why each soft turning point contributes \\( -\\tfrac{\\pi}{4} \\) to the phase, and hence why a well with two soft turning points obeys \\( \\oint p\\,dx = (n+\\tfrac12)\\,2\\pi\\hbar \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["connection formula", "Maslov index", "phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Phase accumulated between turning points.", workingLatex: "\\Phi = \\frac{1}{\\hbar}\\int_{x_{1}}^{x_{2}} p\\,dx.", explanation: "The oscillatory WKB wave \\( \\cos\\!\\left(\\tfrac1\\hbar\\int p\\,dx - \\phi\\right) \\) accumulates this dynamical phase across the well." },
        { stepNumber: 2, description: "Apply the connection formula at each end.", workingLatex: "\\psi \\sim \\cos\\!\\left(\\frac{1}{\\hbar}\\int_{x_{1}}^{x} p\\,dx' - \\frac{\\pi}{4}\\right).", explanation: "Matching the decaying exponential in the forbidden region to the oscillatory region forces a \\( -\\pi/4 \\) phase shift at each soft turning point." },
        { stepNumber: 3, description: "Demand single-valuedness / a standing wave.", workingLatex: "\\frac{1}{\\hbar}\\int_{x_{1}}^{x_{2}} p\\,dx - \\frac{\\pi}{4} - \\frac{\\pi}{4} = n\\pi.", explanation: "The total phase between the two \\( -\\pi/4 \\) endpoints must be an integer multiple of \\( \\pi \\) for the two cosine matchings to be consistent." },
        { stepNumber: 4, description: "Rearrange.", workingLatex: "\\frac{1}{\\hbar}\\int_{x_{1}}^{x_{2}} p\\,dx = \\left(n+\\frac{1}{2}\\right)\\pi \\;\\Longleftrightarrow\\; \\oint p\\,dx = \\left(n+\\frac{1}{2}\\right)2\\pi\\hbar.", explanation: "The two \\( -\\pi/4 \\)'s sum to \\( -\\pi/2 \\), producing the Maslov \\( +\\tfrac12 \\); the closed-loop action \\( \\oint p\\,dx \\) is twice the line integral." },
      ],
      finalAnswer: "Two \\( -\\tfrac{\\pi}{4} \\) shifts give the Maslov \\( \\tfrac12 \\): \\( \\oint p\\,dx = \\left(n+\\tfrac12\\right)2\\pi\\hbar \\).",
    },
  },
  {
    id: "am10d-017",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 17",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A metastable state of frequency \\( \\omega \\) sits behind a barrier with WKB exponent \\( \\gamma \\). Estimate its decay rate \\( \\Gamma \\) and lifetime \\( \\tau \\) using the attempt-frequency picture.",
    marks: 3,
    yearCreated: 2026,
    tags: ["decay rate", "lifetime", "tunnelling estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Count attempts.", workingLatex: "\\nu = \\frac{\\omega}{2\\pi}.", explanation: "The particle oscillates in the well with angular frequency \\( \\omega \\), striking the barrier \\( \\omega/2\\pi \\) times per unit time." },
        { stepNumber: 2, description: "Multiply by the transmission probability.", workingLatex: "\\Gamma = \\nu\\, T \\approx \\frac{\\omega}{2\\pi}\\,e^{-2\\gamma}.", explanation: "Each attempt escapes with probability \\( T\\approx e^{-2\\gamma} \\); the decay rate is attempts per unit time times escape probability." },
        { stepNumber: 3, description: "Invert for the lifetime.", workingLatex: "\\tau = \\frac{1}{\\Gamma} \\approx \\frac{2\\pi}{\\omega}\\,e^{2\\gamma}.", explanation: "The lifetime is the reciprocal of the rate; it grows exponentially in the barrier exponent \\( \\gamma \\)." },
      ],
      finalAnswer: "\\( \\Gamma \\approx \\dfrac{\\omega}{2\\pi}e^{-2\\gamma}, \\qquad \\tau \\approx \\dfrac{2\\pi}{\\omega}e^{2\\gamma} \\).",
      canonicalAnswer: "Gamma = (w/2pi) e^{-2 gamma}",
    },
  },
  {
    id: "am10d-018",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 18",
    difficulty: "Standard",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Compute the quartic-well WKB ground-state energy for \\( V=x^{4} \\) (taking \\( m=\\hbar=1 \\), \\( \\alpha=1 \\)) and compare with the accurate value \\( E_{0}^{\\text{exact}}\\approx 0.6680 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["quartic well", "ground state", "WKB error"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use the quartic energy formula.", workingLatex: "E_{n} = \\left[\\frac{\\pi}{2C}\\right]^{4/3}\\frac{1}{2^{2/3}}\\left(n+\\frac{1}{2}\\right)^{4/3}, \\qquad C = 0.87402.", explanation: "Set \\( m=\\hbar=\\alpha=1 \\) in the general result of question 13." },
        { stepNumber: 2, description: "Evaluate for \\( n=0 \\).", workingLatex: "E_{0} = \\left[\\frac{\\pi}{2(0.87402)}\\right]^{4/3}\\frac{1}{2^{2/3}}\\left(\\frac{1}{2}\\right)^{4/3} \\approx 0.5463.", explanation: "Numerical quad confirms: at \\( E_0=0.54627 \\) the action equals \\( \\tfrac12\\pi \\) to machine precision." },
        { stepNumber: 3, description: "Compare with the exact value.", workingLatex: "\\frac{E_{0}^{\\text{WKB}}}{E_{0}^{\\text{exact}}} = \\frac{0.5463}{0.6680} \\approx 0.818.", explanation: "WKB underestimates the ground state by about \\( 18\\% \\); the error shrinks rapidly for excited states because WKB is an expansion in \\( 1/(n+\\tfrac12) \\)." },
      ],
      finalAnswer: "\\( E_{0}^{\\text{WKB}}\\approx 0.546 \\), about \\( 18\\% \\) below the exact \\( 0.668 \\).",
      canonicalAnswer: "0.546",
    },
  },

  // ───────────────────────── CHALLENGE (12) ─────────────────────────
  {
    id: "am10d-019",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 19",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "For the quartic well \\( V=\\alpha x^{4} \\), derive the complete WKB spectrum \\( E_{n} \\) in closed form including the \\( \\Gamma \\)-function constant, and verify the \\( (n+\\tfrac12)^{4/3} \\) law numerically.",
    marks: 6,
    yearCreated: 2026,
    tags: ["quartic well", "Gamma function", "closed form", "verification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Action with the \\( \\Gamma \\)-constant.", workingLatex: "\\int_{-x_{t}}^{x_{t}}\\sqrt{2m(E-\\alpha x^{4})}\\,dx = 2C\\sqrt{2m}\\,\\alpha^{-1/4}E^{3/4}, \\quad C=\\frac{\\sqrt\\pi}{6}\\frac{\\Gamma(1/4)}{\\Gamma(3/4)}.", explanation: "From the rescaling \\( x=x_t u \\) with \\( x_t=(E/\\alpha)^{1/4} \\) and \\( \\int_0^1\\sqrt{1-u^4}\\,du=C \\)." },
        { stepNumber: 2, description: "Quantise.", workingLatex: "2C\\sqrt{2m}\\,\\alpha^{-1/4}E^{3/4} = \\left(n+\\frac{1}{2}\\right)\\pi\\hbar.", explanation: "Two soft turning points give the index \\( n+\\tfrac12 \\)." },
        { stepNumber: 3, description: "Solve for \\( E_{n} \\).", workingLatex: "E_{n} = \\left[\\frac{\\pi\\hbar}{2C}\\right]^{4/3}\\frac{\\alpha^{1/3}}{(2m)^{2/3}}\\left(n+\\frac{1}{2}\\right)^{4/3}.", explanation: "Raise to the \\( 4/3 \\) power and collect the constants." },
        { stepNumber: 4, description: "Replace \\( C \\) by its \\( \\Gamma \\)-form.", workingLatex: "E_{n} = \\left[\\frac{3\\pi\\hbar}{\\sqrt\\pi}\\frac{\\Gamma(3/4)}{\\Gamma(1/4)}\\right]^{4/3}\\frac{\\alpha^{1/3}}{(2m)^{2/3}}\\left(n+\\frac{1}{2}\\right)^{4/3}.", explanation: "Since \\( 2C = \\tfrac{\\sqrt\\pi}{3}\\tfrac{\\Gamma(1/4)}{\\Gamma(3/4)} \\), its reciprocal flips the \\( \\Gamma \\)-ratio." },
        { stepNumber: 5, description: "Numerical verification.", workingLatex: "m=\\hbar=\\alpha=1: \\quad E_{0}=0.54627,\\ E_{1}=2.36356,\\ E_{2}=4.67052.", explanation: "mpmath quad confirms the action equals \\( (n+\\tfrac12)\\pi \\) at each of these energies to machine precision." },
        { stepNumber: 6, description: "Check the scaling law.", workingLatex: "\\frac{E_{1}}{E_{0}} = \\frac{2.36356}{0.54627} = 4.3267 = 3^{4/3}.", explanation: "The ratio matches \\( (3/2 \\div 1/2)^{4/3}=3^{4/3} \\) exactly, confirming the \\( (n+\\tfrac12)^{4/3} \\) law." },
      ],
      finalAnswer: "\\( E_{n} = \\left[\\dfrac{\\pi\\hbar}{2C}\\right]^{4/3}\\dfrac{\\alpha^{1/3}}{(2m)^{2/3}}\\left(n+\\tfrac12\\right)^{4/3} \\), \\( C=\\dfrac{\\sqrt\\pi}{6}\\dfrac{\\Gamma(1/4)}{\\Gamma(3/4)} \\).",
    },
  },
  {
    id: "am10d-020",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 20",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "For the Pöschl–Teller well \\( V=-\\dfrac{\\hbar^{2}\\alpha^{2}\\lambda(\\lambda-1)}{2m}\\,\\operatorname{sech}^{2}(\\alpha x) \\) it is known that \\( \\dfrac1\\hbar\\int\\sqrt{2m(E-V)}\\,dx = \\pi\\!\\left[\\sqrt{\\lambda(\\lambda-1)}-\\dfrac{\\sqrt{2m|E|}}{\\hbar\\alpha}\\right] \\) for a bound state \\( E=-|E| \\). Derive the WKB bound-state energies.",
    marks: 6,
    yearCreated: 2026,
    tags: ["Poschl-Teller", "sech-squared well", "bound states"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply Bohr–Sommerfeld.", workingLatex: "\\pi\\!\\left[\\sqrt{\\lambda(\\lambda-1)}-\\frac{\\sqrt{2m|E|}}{\\hbar\\alpha}\\right] = \\left(n+\\frac{1}{2}\\right)\\pi.", explanation: "Two soft turning points (the well is smooth), so the index is \\( n+\\tfrac12 \\)." },
        { stepNumber: 2, description: "Cancel \\( \\pi \\) and isolate the energy term.", workingLatex: "\\frac{\\sqrt{2m|E|}}{\\hbar\\alpha} = \\sqrt{\\lambda(\\lambda-1)} - \\left(n+\\frac{1}{2}\\right).", explanation: "Rearrange to solve for \\( |E| \\)." },
        { stepNumber: 3, description: "Square and restore the sign.", workingLatex: "|E| = \\frac{\\hbar^{2}\\alpha^{2}}{2m}\\left[\\sqrt{\\lambda(\\lambda-1)}-\\left(n+\\frac{1}{2}\\right)\\right]^{2}.", explanation: "Multiply through by \\( \\hbar^2\\alpha^2/(2m) \\) and square the bracket." },
        { stepNumber: 4, description: "State the WKB spectrum.", workingLatex: "E_{n}^{\\text{WKB}} = -\\frac{\\hbar^{2}\\alpha^{2}}{2m}\\left[\\sqrt{\\lambda(\\lambda-1)}-\\left(n+\\frac{1}{2}\\right)\\right]^{2}.", explanation: "Bound states exist while the bracket is positive, i.e. \\( n+\\tfrac12 < \\sqrt{\\lambda(\\lambda-1)} \\)." },
      ],
      finalAnswer: "\\( E_{n}^{\\text{WKB}} = -\\dfrac{\\hbar^{2}\\alpha^{2}}{2m}\\left[\\sqrt{\\lambda(\\lambda-1)}-\\left(n+\\tfrac12\\right)\\right]^{2} \\).",
    },
  },
  {
    id: "am10d-021",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 21",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "The exact Pöschl–Teller spectrum is \\( E_{n}^{\\text{exact}}=-\\dfrac{\\hbar^{2}\\alpha^{2}}{2m}(\\lambda-1-n)^{2} \\). Compare it with the WKB result of the previous question and identify the source of the discrepancy.",
    marks: 5,
    yearCreated: 2026,
    tags: ["Poschl-Teller", "WKB vs exact", "comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write both bracketed factors.", workingLatex: "\\text{WKB: } \\sqrt{\\lambda(\\lambda-1)}-\\left(n+\\tfrac12\\right); \\qquad \\text{exact: } (\\lambda-1-n).", explanation: "Compare the quantities being squared in each spectrum." },
        { stepNumber: 2, description: "Re-express the exact factor.", workingLatex: "\\lambda-1-n = \\sqrt{\\left(\\lambda-\\tfrac12\\right)^{2}}-\\left(n+\\tfrac12\\right) = \\sqrt{\\lambda(\\lambda-1)+\\tfrac14}-\\left(n+\\tfrac12\\right).", explanation: "Note \\( (\\lambda-\\tfrac12)^2 = \\lambda^2-\\lambda+\\tfrac14 = \\lambda(\\lambda-1)+\\tfrac14 \\)." },
        { stepNumber: 3, description: "Identify the difference.", workingLatex: "\\text{WKB uses } \\sqrt{\\lambda(\\lambda-1)} \\ \\text{instead of} \\ \\sqrt{\\lambda(\\lambda-1)+\\tfrac14}.", explanation: "WKB drops the \\( +\\tfrac14 \\) inside the square root — a higher-order (Langer-type) correction to the effective potential." },
        { stepNumber: 4, description: "Quantify for a sample.", workingLatex: "\\lambda=5:\\ \\sqrt{20}=4.4721\\ (\\text{WKB}) \\ \\text{vs}\\ \\sqrt{20.25}=4.5\\ (\\text{exact}).", explanation: "Numerical check: for \\( \\lambda=5 \\) the WKB action at each exact \\( E_n \\) gives \\( 1.483\\pi,\\,4.625\\pi,\\dots \\) — close to but not exactly \\( (n+\\tfrac12)\\pi \\); the \\( \\tfrac14 \\) gap is the source." },
        { stepNumber: 5, description: "Conclusion.", workingLatex: "E_{n}^{\\text{WKB}}\\to E_{n}^{\\text{exact}} \\ \\text{as the } \\tfrac14 \\ \\text{becomes negligible (large } \\lambda).", explanation: "The agreement improves for deep wells; the Langer correction \\( \\lambda(\\lambda-1)\\to(\\lambda-\\tfrac12)^2 \\) would make WKB exact here." },
      ],
      finalAnswer: "WKB replaces \\( (\\lambda-1-n)=\\sqrt{\\lambda(\\lambda-1)+\\tfrac14}-(n+\\tfrac12) \\) by \\( \\sqrt{\\lambda(\\lambda-1)}-(n+\\tfrac12) \\); the missing \\( \\tfrac14 \\) is the discrepancy.",
    },
  },
  {
    id: "am10d-022",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 22",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "For the double-power well \\( V=\\tfrac12 m\\omega^{2}x^{2}+\\lambda x^{4} \\) with small \\( \\lambda \\), find the leading WKB energy and the first-order shift in \\( \\lambda \\), using the action \\( S(E)=\\int\\sqrt{2m(E-V)}\\,dx \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["anharmonic oscillator", "perturbation", "action integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the action in \\( \\lambda \\).", workingLatex: "S(E) = \\int \\sqrt{2m(E-\\tfrac12 m\\omega^{2}x^{2})}\\;\\sqrt{1-\\frac{\\lambda x^{4}}{E-\\tfrac12 m\\omega^{2}x^{2}}}\\,dx.", explanation: "Treat \\( \\lambda x^4 \\) as a small term inside the square root." },
        { stepNumber: 2, description: "Linearise the second root.", workingLatex: "S(E) \\approx S_{0}(E) - \\lambda m\\int \\frac{x^{4}}{\\sqrt{2m(E-\\tfrac12 m\\omega^{2}x^{2})}}\\,dx.", explanation: "Use \\( \\sqrt{1-\\delta}\\approx 1-\\tfrac12\\delta \\) and \\( \\sqrt{2m(E-V_0)}\\cdot\\tfrac12\\delta = \\lambda x^4 m/\\sqrt{2m(E-V_0)} \\)." },
        { stepNumber: 3, description: "Evaluate the correction integral over the SHO range.", workingLatex: "J := \\int_{-x_{t}}^{x_{t}}\\frac{x^{4}\\,dx}{\\sqrt{2m(E-\\tfrac12 m\\omega^{2}x^{2})}} = \\frac{x_{t}^{5}}{\\sqrt{2mE}}\\int_{-\\pi/2}^{\\pi/2}\\sin^{4}\\theta\\,d\\theta = \\frac{3\\pi}{2}\\,\\frac{E^{2}}{m^{3}\\omega^{5}}.", explanation: "With \\( x=x_t\\sin\\theta \\), \\( x_t^2=2E/(m\\omega^2) \\) and \\( \\int_{-\\pi/2}^{\\pi/2}\\sin^4\\theta\\,d\\theta = \\tfrac{3\\pi}{8} \\); collecting the powers gives \\( J=\\tfrac{3\\pi}{2}E^2/(m^3\\omega^5) \\) (checked by quad)." },
        { stepNumber: 4, description: "Assemble the action.", workingLatex: "S(E) = \\frac{\\pi E}{\\omega} - \\lambda m\\,J = \\frac{\\pi E}{\\omega}-\\frac{3\\pi\\lambda E^{2}}{2\\,m^{2}\\omega^{5}}.", explanation: "The \\( O(\\lambda) \\) term from step 2 is \\( -\\lambda m\\,J \\); inserting \\( J \\) leaves the \\( \\lambda \\)-correction \\( -\\dfrac{3\\pi\\lambda E^2}{2m^2\\omega^5} \\)." },
        { stepNumber: 5, description: "Quantise and invert perturbatively.", workingLatex: "\\frac{\\pi E}{\\omega}-\\frac{3\\pi\\lambda E^{2}}{2m^{2}\\omega^{5}} = \\left(n+\\tfrac12\\right)\\pi\\hbar, \\quad E_{n}=\\left(n+\\tfrac12\\right)\\hbar\\omega+\\Delta.", explanation: "Write \\( E=E^{(0)}+\\Delta \\) with \\( E^{(0)}=(n+\\tfrac12)\\hbar\\omega \\)." },
        { stepNumber: 6, description: "First-order shift.", workingLatex: "\\Delta = \\frac{3\\lambda}{2m^{2}\\omega^{4}}\\left(E^{(0)}\\right)^{2} = \\frac{3\\lambda\\hbar^{2}}{2m^{2}\\omega^{2}}\\left(n+\\tfrac12\\right)^{2}.", explanation: "Numerical check (\\( m=\\omega=\\hbar=1 \\)): the slope \\( dE_n/d\\lambda \\) as \\( \\lambda\\to0 \\) from quad is \\( 0.375,\\,3.375,\\,9.375 \\) for \\( n=0,1,2 \\), matching \\( \\tfrac32(n+\\tfrac12)^2 \\) exactly." },
      ],
      finalAnswer: "\\( E_{n} \\approx \\left(n+\\tfrac12\\right)\\hbar\\omega + \\dfrac{3\\lambda\\hbar^{2}}{2m^{2}\\omega^{2}}\\left(n+\\tfrac12\\right)^{2} \\).",
    },
  },
  {
    id: "am10d-023",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 23",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Derive the Gamow factor for alpha decay: a particle of energy \\( E>0 \\) escaping a Coulomb tail \\( V(r)=B/r \\) (for \\( r>R \\)), with outer turning point \\( r_{b}=B/E \\). Find \\( \\gamma = \\tfrac1\\hbar\\int_{R}^{r_{b}}\\sqrt{2m(B/r-E)}\\,dr \\) in closed form.",
    marks: 6,
    yearCreated: 2026,
    tags: ["Gamow factor", "Coulomb barrier", "alpha decay"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Factor the integrand.", workingLatex: "\\sqrt{\\frac{B}{r}-E} = \\sqrt{E}\\,\\sqrt{\\frac{r_{b}}{r}-1}, \\qquad r_{b}=\\frac{B}{E}.", explanation: "Write \\( B/r-E = E(r_b/r - 1) \\) using \\( B=E r_b \\)." },
        { stepNumber: 2, description: "Set up the standard integral.", workingLatex: "\\gamma = \\frac{\\sqrt{2mE}}{\\hbar}\\int_{R}^{r_{b}}\\sqrt{\\frac{r_{b}}{r}-1}\\;dr.", explanation: "Pull the constant \\( \\sqrt{2mE} \\) outside." },
        { stepNumber: 3, description: "Evaluate the integral.", workingLatex: "\\int_{R}^{r_{b}}\\sqrt{\\frac{r_{b}}{r}-1}\\,dr = r_{b}\\arccos\\!\\sqrt{\\frac{R}{r_{b}}} - \\sqrt{R\\,(r_{b}-R)}.", explanation: "Sub \\( r=r_b\\cos^2\\theta \\); the antiderivative gives the \\( \\arccos \\) form." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "\\gamma = \\frac{\\sqrt{2mE}}{\\hbar}\\left[r_{b}\\arccos\\!\\sqrt{\\frac{R}{r_{b}}}-\\sqrt{R(r_{b}-R)}\\right].", explanation: "Numerical check (\\( m=\\hbar=1,B=10,E=2,R=0.5 \\)): quad gives \\( \\gamma=9.49046 \\), matching the closed form to 16 digits." },
        { stepNumber: 5, description: "Thick-barrier limit.", workingLatex: "R\\ll r_{b}: \\quad \\arccos\\sqrt{R/r_{b}}\\to\\frac{\\pi}{2}, \\quad \\gamma \\to \\frac{\\pi}{\\hbar}\\sqrt{2m}\\,\\frac{B}{2\\sqrt{E}}.", explanation: "For low energy the inner radius is negligible and \\( \\gamma\\propto 1/\\sqrt{E} \\) — the Geiger–Nuttall law." },
      ],
      finalAnswer: "\\( \\gamma = \\dfrac{\\sqrt{2mE}}{\\hbar}\\left[r_{b}\\arccos\\!\\sqrt{\\tfrac{R}{r_{b}}}-\\sqrt{R(r_{b}-R)}\\right] \\xrightarrow[R\\ll r_b]{} \\dfrac{\\pi B}{\\hbar}\\sqrt{\\dfrac{m}{2E}} \\).",
    },
  },
  {
    id: "am10d-024",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 24",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A symmetric double well has barrier exponent \\( \\gamma \\) between the two minima, each of frequency \\( \\omega \\). Estimate the tunnel splitting \\( \\Delta E \\) between the symmetric and antisymmetric ground states.",
    marks: 5,
    yearCreated: 2026,
    tags: ["double well", "tunnel splitting", "instanton estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Attempt frequency in one well.", workingLatex: "\\nu = \\frac{\\omega}{2\\pi}.", explanation: "Each well has oscillation frequency \\( \\omega \\); the ground state attempts to tunnel \\( \\omega/2\\pi \\) times per unit time." },
        { stepNumber: 2, description: "Tunnelling amplitude.", workingLatex: "\\text{amplitude} \\sim e^{-\\gamma}, \\qquad \\gamma = \\frac{1}{\\hbar}\\int_{a}^{b}\\sqrt{2m(V-E)}\\,dx.", explanation: "The wavefunction decays as \\( e^{-\\gamma} \\) across the barrier (one power, not two — splitting is an amplitude, not a probability)." },
        { stepNumber: 3, description: "Combine into a splitting.", workingLatex: "\\Delta E \\sim \\hbar\\,\\nu\\, e^{-\\gamma} = \\frac{\\hbar\\omega}{\\pi}\\,e^{-\\gamma}.", explanation: "The energy scale is \\( \\hbar\\nu \\) times the tunnelling amplitude; the symmetric–antisymmetric gap is \\( 2\\times \\tfrac{\\hbar\\omega}{2\\pi}e^{-\\gamma} \\)." },
        { stepNumber: 4, description: "State the estimate.", workingLatex: "\\Delta E \\sim \\frac{\\hbar\\omega}{\\pi}\\,e^{-\\gamma}.", explanation: "Note the single \\( e^{-\\gamma} \\): tunnel splitting scales with the amplitude, whereas a decay rate (transmission) scales with \\( e^{-2\\gamma} \\)." },
      ],
      finalAnswer: "\\( \\Delta E \\sim \\dfrac{\\hbar\\omega}{\\pi}\\,e^{-\\gamma} \\) (single \\( e^{-\\gamma} \\), unlike the \\( e^{-2\\gamma} \\) of transmission).",
    },
  },
  {
    id: "am10d-025",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 25",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Derive the energy levels of the power-law well \\( V=\\beta|x|^{s} \\) (with \\( s>0 \\)) and show \\( E_{n}\\propto (n+\\tfrac12)^{2s/(s+2)} \\). Check the cases \\( s=2 \\) and \\( s=4 \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["power-law well", "Beta function", "energy scaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Turning points and rescale.", workingLatex: "\\beta x_{t}^{s}=E \\Rightarrow x_{t}=(E/\\beta)^{1/s}; \\quad x=x_{t}u.", explanation: "Set \\( V=E \\) and substitute to make the integral dimensionless." },
        { stepNumber: 2, description: "Action integral.", workingLatex: "S = 2\\sqrt{2mE}\\,x_{t}\\int_{0}^{1}\\sqrt{1-u^{s}}\\,du = 2\\sqrt{2m}\\,\\beta^{-1/s}E^{\\frac12+\\frac1s}\\,K_{s},", explanation: "with \\( K_{s}=\\int_0^1\\sqrt{1-u^s}\\,du \\). The energy exponent is \\( \\tfrac12+\\tfrac1s=\\tfrac{s+2}{2s} \\)." },
        { stepNumber: 3, description: "Express \\( K_{s} \\) via the Beta function.", workingLatex: "K_{s} = \\frac{1}{s}B\\!\\left(\\frac{1}{s},\\frac{3}{2}\\right) = \\frac{\\sqrt\\pi}{2s}\\,\\frac{\\Gamma(1/s)}{\\Gamma\\!\\left(\\frac{1}{s}+\\frac{3}{2}\\right)}.", explanation: "Sub \\( t=u^s \\): \\( K_s=\\tfrac1s\\int_0^1 t^{1/s-1}(1-t)^{1/2}dt = \\tfrac1s B(\\tfrac1s,\\tfrac32) \\); then \\( B(a,b)=\\Gamma(a)\\Gamma(b)/\\Gamma(a+b) \\) with \\( \\Gamma(3/2)=\\tfrac{\\sqrt\\pi}{2} \\)." },
        { stepNumber: 4, description: "Quantise.", workingLatex: "2\\sqrt{2m}\\,\\beta^{-1/s}E^{\\frac{s+2}{2s}}K_{s} = \\left(n+\\tfrac12\\right)\\pi\\hbar.", explanation: "Two soft turning points." },
        { stepNumber: 5, description: "Solve for \\( E_{n} \\).", workingLatex: "E_{n} = \\left[\\frac{(n+\\tfrac12)\\pi\\hbar}{2\\sqrt{2m}\\,K_{s}}\\right]^{\\frac{2s}{s+2}}\\beta^{\\frac{2}{s+2}}.", explanation: "Raise to the reciprocal power \\( 2s/(s+2) \\)." },
        { stepNumber: 6, description: "Check special cases.", workingLatex: "s=2:\\ \\tfrac{2s}{s+2}=1 \\ (\\text{SHO}); \\qquad s=4:\\ \\tfrac{2s}{s+2}=\\tfrac{4}{3} \\ (\\text{quartic}).", explanation: "Numerical check: \\( s=2 \\) recovers \\( E_n\\propto(n+\\tfrac12) \\) and \\( K_2=\\pi/4 \\) gives the exact SHO; \\( s=4 \\) gives \\( K_4=0.8740 \\) and the \\( (n+\\tfrac12)^{4/3} \\) law of question 19." },
      ],
      finalAnswer: "\\( E_{n} = \\left[\\dfrac{(n+\\tfrac12)\\pi\\hbar}{2\\sqrt{2m}\\,K_{s}}\\right]^{\\frac{2s}{s+2}}\\beta^{\\frac{2}{s+2}} \\), \\( K_{s}=\\tfrac1s B(\\tfrac1s,\\tfrac32) \\); \\( E_{n}\\propto(n+\\tfrac12)^{2s/(s+2)} \\).",
    },
  },
  {
    id: "am10d-026",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 26",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A particle tunnels through the smooth barrier \\( V(x)=V_{0}\\,\\operatorname{sech}^{2}(x/a) \\) at energy \\( E<V_{0} \\). Find the tunnelling exponent \\( \\gamma \\) in closed form.",
    marks: 6,
    yearCreated: 2026,
    tags: ["tunnelling", "sech-squared barrier", "transmission"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the turning points.", workingLatex: "V_{0}\\operatorname{sech}^{2}(x/a)=E \\Rightarrow \\operatorname{sech}^{2}(x_{*}/a)=\\frac{E}{V_{0}}, \\quad x_{*}=a\\,\\operatorname{arcsech}\\sqrt{\\tfrac{E}{V_{0}}}.", explanation: "The barrier exceeds \\( E \\) for \\( |x| < x_* \\)." },
        { stepNumber: 2, description: "Write the exponent.", workingLatex: "\\gamma = \\frac{2}{\\hbar}\\int_{0}^{x_{*}}\\sqrt{2m\\left(V_{0}\\operatorname{sech}^{2}\\frac{x}{a}-E\\right)}\\,dx.", explanation: "Use symmetry to integrate over the positive half and double." },
        { stepNumber: 3, description: "Substitute \\( t=\\tanh(x/a) \\).", workingLatex: "\\operatorname{sech}^{2}\\frac{x}{a}=1-t^{2},\\quad dx = \\frac{a\\,dt}{1-t^{2}}; \\quad \\gamma=\\frac{2a\\sqrt{2m}}{\\hbar}\\int_{0}^{t_{*}}\\frac{\\sqrt{V_{0}(1-t^{2})-E}}{1-t^{2}}\\,dt.", explanation: "with \\( t_{*}^{2} = 1-E/V_0 \\). Factor \\( V_0(1-t^2)-E = V_0(t_{*}^{2} - t^2) \\)." },
        { stepNumber: 4, description: "Evaluate the rational-root integral.", workingLatex: "\\gamma = \\frac{2a\\sqrt{2mV_{0}}}{\\hbar}\\int_{0}^{t_{*}}\\frac{\\sqrt{t_{*}^{2}-t^{2}}}{1-t^{2}}\\,dt = \\frac{2a\\sqrt{2mV_{0}}}{\\hbar}\\cdot\\frac{\\pi}{2}\\left(1-\\sqrt{1-t_{*}^{2}}\\right).", explanation: "The standard integral \\( \\int_0^{t_*}\\tfrac{\\sqrt{t_*^2-t^2}}{1-t^2}dt = \\tfrac{\\pi}{2}\\left(1-\\sqrt{1-t_*^2}\\right) \\); here \\( 1-t_{*}^{2}=E/V_0 \\)." },
        { stepNumber: 5, description: "Simplify using \\( 1-t_{*}^{2}=E/V_{0} \\).", workingLatex: "\\gamma = \\frac{\\pi a\\sqrt{2mV_{0}}}{\\hbar}\\left(1-\\sqrt{\\frac{E}{V_{0}}}\\right) = \\frac{\\pi a\\sqrt{2m}}{\\hbar}\\left(\\sqrt{V_{0}}-\\sqrt{E}\\right).", explanation: "Numerical check (\\( m=\\hbar=a=1,V_0=4,E=1 \\)): quad gives \\( \\gamma=\\pi\\sqrt2\\,(2-1)=4.4429 \\), matching the closed form to 12 digits." },
      ],
      finalAnswer: "\\( \\gamma = \\dfrac{\\pi a\\sqrt{2m}}{\\hbar}\\left(\\sqrt{V_{0}}-\\sqrt{E}\\right) \\).",
    },
  },
  {
    id: "am10d-027",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 27",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "For the relativistic-like dispersion mock potential, consider the well \\( V=\\tfrac12 m\\omega^{2}x^{2} \\) but now find the number of bound states \\( N \\) below a cut-off energy \\( E_{\\max} \\) using the WKB density-of-states formula \\( N\\approx \\tfrac{1}{\\pi\\hbar}\\int_{x_{1}}^{x_{2}}\\sqrt{2m(E_{\\max}-V)}\\,dx \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["density of states", "level counting", "harmonic oscillator"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the counting formula.", workingLatex: "N(E_{\\max}) \\approx \\frac{1}{\\pi\\hbar}\\int_{x_{1}}^{x_{2}}\\sqrt{2m(E_{\\max}-V)}\\,dx.", explanation: "Each state occupies a phase-space area \\( 2\\pi\\hbar \\); the number of levels below \\( E_{\\max} \\) is the enclosed action divided by \\( \\pi\\hbar \\)." },
        { stepNumber: 2, description: "Insert the SHO action.", workingLatex: "\\int_{x_{1}}^{x_{2}}\\sqrt{2m(E_{\\max}-\\tfrac12 m\\omega^{2}x^{2})}\\,dx = \\frac{\\pi E_{\\max}}{\\omega}.", explanation: "Reuse the harmonic action evaluated earlier." },
        { stepNumber: 3, description: "Divide.", workingLatex: "N \\approx \\frac{1}{\\pi\\hbar}\\cdot\\frac{\\pi E_{\\max}}{\\omega} = \\frac{E_{\\max}}{\\hbar\\omega}.", explanation: "Consistent with \\( E_n=(n+\\tfrac12)\\hbar\\omega \\): the count of levels up to \\( E_{\\max} \\) is \\( E_{\\max}/\\hbar\\omega \\) (to leading order)." },
        { stepNumber: 4, description: "Refine with the Maslov shift.", workingLatex: "N \\approx \\frac{E_{\\max}}{\\hbar\\omega}-\\frac{1}{2}.", explanation: "Including the \\( \\tfrac12 \\) zero-point offset gives the standard half-integer-corrected staircase; for \\( E_{\\max}=10\\hbar\\omega \\), \\( N\\approx 9.5 \\), i.e. 10 levels \\( n=0,\\dots,9 \\)." },
      ],
      finalAnswer: "\\( N \\approx \\dfrac{E_{\\max}}{\\hbar\\omega} \\) (or \\( \\tfrac{E_{\\max}}{\\hbar\\omega}-\\tfrac12 \\) with the Maslov shift).",
      canonicalAnswer: "E_max/(hbar w)",
    },
  },
  {
    id: "am10d-028",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 28",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Estimate the tunnelling rate out of the cubic metastable well \\( V=\\tfrac12 m\\omega^{2}x^{2}-bx^{3} \\) (\\( b>0 \\)) for a particle near the bottom (\\( E\\approx \\tfrac12\\hbar\\omega \\)), expressing the answer through the barrier exponent \\( \\gamma \\) and attempt frequency.",
    marks: 5,
    yearCreated: 2026,
    tags: ["cubic well", "metastable", "decay rate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the barrier top.", workingLatex: "V'(x)=m\\omega^{2}x-3bx^{2}=0 \\Rightarrow x_{\\text{top}}=\\frac{m\\omega^{2}}{3b}, \\quad V_{\\text{top}}=\\frac{m^{3}\\omega^{6}}{54 b^{2}}.", explanation: "The barrier maximum is where \\( V'=0 \\) (other than the origin); insert \\( x_{\\text{top}} \\) back into \\( V \\)." },
        { stepNumber: 2, description: "Identify the escape route.", workingLatex: "\\gamma = \\frac{1}{\\hbar}\\int_{x_{1}}^{x_{2}}\\sqrt{2m(V-E)}\\,dx,", explanation: "with \\( x_1,x_2 \\) the inner and outer turning points at energy \\( E\\approx\\tfrac12\\hbar\\omega \\), straddling the barrier top." },
        { stepNumber: 3, description: "Write the rate.", workingLatex: "\\Gamma = \\frac{\\omega}{2\\pi}\\,e^{-2\\gamma}.", explanation: "Attempt frequency \\( \\omega/2\\pi \\) times the WKB transmission \\( e^{-2\\gamma} \\)." },
        { stepNumber: 4, description: "Leading exponent for a shallow level.", workingLatex: "2\\gamma \\approx \\frac{2}{\\hbar}\\int_{0}^{x_{2}}\\sqrt{2m(V-E)}\\,dx \\sim \\frac{36 V_{\\text{top}}}{5\\hbar\\omega}\\ (\\text{cubic estimate}).", explanation: "For \\( E\\ll V_{\\text{top}} \\) the dominant scale is \\( V_{\\text{top}}/\\hbar\\omega \\); the rate is exponentially small in this ratio." },
        { stepNumber: 5, description: "State the estimate.", workingLatex: "\\Gamma \\sim \\frac{\\omega}{2\\pi}\\exp\\!\\left[-\\frac{2}{\\hbar}\\int_{x_{1}}^{x_{2}}\\sqrt{2m(V-E)}\\,dx\\right].", explanation: "The lifetime \\( \\tau=1/\\Gamma \\) grows exponentially as the barrier height \\( V_{\\text{top}}\\propto m^3\\omega^6/b^2 \\) increases (i.e. as \\( b\\to 0 \\))." },
      ],
      finalAnswer: "\\( \\Gamma \\sim \\dfrac{\\omega}{2\\pi}\\exp\\!\\left[-\\dfrac{2}{\\hbar}\\displaystyle\\int_{x_{1}}^{x_{2}}\\sqrt{2m(V-E)}\\,dx\\right] \\), \\( V_{\\text{top}}=\\dfrac{m^{3}\\omega^{6}}{54b^{2}} \\).",
    },
  },
  {
    id: "am10d-029",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 29",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "Compute the WKB ground-state energy of the linear well \\( V=F|x| \\) (with \\( m=F=\\hbar=1 \\)) and compare with the exact value, which is set by the first zero of the derivative of the Airy function, \\( E_{0}^{\\text{exact}}\\approx 0.8086 \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["linear well", "Airy", "WKB error"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Specialise the linear-well formula.", workingLatex: "E_{n} = \\left[\\frac{3\\pi}{4\\sqrt{2}}\\left(n+\\frac{1}{2}\\right)\\right]^{2/3}, \\qquad m=F=\\hbar=1.", explanation: "From question 9 with the constants set to one." },
        { stepNumber: 2, description: "Evaluate for \\( n=0 \\).", workingLatex: "E_{0} = \\left[\\frac{3\\pi}{4\\sqrt{2}}\\cdot\\frac{1}{2}\\right]^{2/3} = \\left[\\frac{3\\pi}{8\\sqrt2}\\right]^{2/3} \\approx 0.8854.", explanation: "Numerical quad confirms action/\\( \\pi=\\tfrac12 \\) at \\( E_0=0.88534 \\)." },
        { stepNumber: 3, description: "The exact ground state.", workingLatex: "E_{0}^{\\text{exact}} \\approx 0.8086,", explanation: "The even ground state of \\( |x| \\) is fixed by the first zero of \\( \\mathrm{Ai}'(-E) \\), namely \\( |a_1'|=1.01879 \\), giving \\( E_0=2^{-1/3}|a_1'|=0.8086 \\)." },
        { stepNumber: 4, description: "Compare.", workingLatex: "\\frac{E_{0}^{\\text{WKB}}}{E_{0}^{\\text{exact}}} = \\frac{0.8854}{0.8086} \\approx 1.095.", explanation: "WKB overestimates the ground state by about \\( 9.5\\% \\); the agreement improves rapidly for higher \\( n \\) where the soft-turning-point approximation is more accurate." },
      ],
      finalAnswer: "\\( E_{0}^{\\text{WKB}}\\approx 0.885 \\), about \\( 9.5\\% \\) above the exact \\( 0.809 \\).",
      canonicalAnswer: "0.885",
    },
  },
  {
    id: "am10d-030",
    topicRef: "am10d",
    topicTitle: "WKB quantisation & barrier tunnelling 30",
    difficulty: "Challenge",
    answerType: "exactValue",
    examStyle: true,
    questionText: "A parabolic barrier near its top, \\( V(x)=V_{0}-\\tfrac12 m\\Omega^{2}x^{2} \\), gives the near-exact transmission \\( T=\\dfrac{1}{1+e^{2\\gamma}} \\) with \\( \\gamma=\\dfrac{\\pi(V_{0}-E)}{\\hbar\\Omega} \\). Verify the WKB exponent \\( 2\\gamma \\) reproduces the leading \\( e^{-2\\gamma} \\) and discuss \\( E=V_{0} \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["parabolic barrier", "transmission", "Kemble formula"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "WKB exponent for the inverted parabola.", workingLatex: "\\gamma = \\frac{1}{\\hbar}\\int_{-x_{*}}^{x_{*}}\\sqrt{2m\\left(V_{0}-\\tfrac12 m\\Omega^{2}x^{2}-E\\right)}\\,dx, \\quad x_{*}=\\sqrt{\\frac{2(V_{0}-E)}{m\\Omega^{2}}}.", explanation: "Same semicircle integral as the parabolic barrier of question 14, with curvature \\( m\\Omega^2 \\)." },
        { stepNumber: 2, description: "Evaluate the semicircle.", workingLatex: "\\gamma = \\frac{\\sqrt{2m(V_{0}-E)}}{\\hbar}\\cdot\\frac{\\pi x_{*}}{2} = \\frac{\\pi(V_{0}-E)}{\\hbar\\Omega}.", explanation: "Insert \\( x_* \\): \\( \\sqrt{2m(V_0-E)}\\cdot x_* = 2(V_0-E)/\\Omega \\), times \\( \\pi/2 \\)." },
        { stepNumber: 3, description: "Low-transmission limit.", workingLatex: "E\\ll V_{0}: \\quad T = \\frac{1}{1+e^{2\\gamma}} \\approx e^{-2\\gamma}, \\quad e^{-2\\gamma}=\\exp\\!\\left[-\\frac{2\\pi(V_{0}-E)}{\\hbar\\Omega}\\right].", explanation: "When \\( \\gamma\\gg 1 \\) the exact Kemble formula reduces to the WKB \\( e^{-2\\gamma} \\), so WKB is correct to leading order." },
        { stepNumber: 4, description: "At and above the top.", workingLatex: "E=V_{0}: \\ \\gamma=0 \\Rightarrow T=\\tfrac12; \\qquad E>V_{0}: \\ \\gamma<0 \\Rightarrow T=\\frac{1}{1+e^{2\\gamma}}>\\tfrac12.", explanation: "Naive WKB \\( e^{-2\\gamma} \\) wrongly gives \\( T=1 \\) at \\( E=V_0 \\); the exact \\( T=\\tfrac12 \\) shows over-barrier reflection. The Kemble form analytically continues \\( \\gamma \\) to negative values for \\( E>V_0 \\)." },
      ],
      finalAnswer: "\\( \\gamma=\\dfrac{\\pi(V_{0}-E)}{\\hbar\\Omega} \\); WKB gives \\( T\\approx e^{-2\\gamma} \\) for \\( E\\ll V_0 \\), but the exact \\( T=\\tfrac1{1+e^{2\\gamma}} \\) gives \\( T=\\tfrac12 \\) at \\( E=V_{0} \\).",
    },
  },
];
