import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Liouville–Green & WKB
 * Subtopic am10b: Airy asymptotics, turning points & connection formulae
 * 30 fully-worked questions (6 Foundation / 12 Standard / 12 Challenge).
 *
 * Theme: the large-argument asymptotics of the Airy function on both sides of
 * its turning point, the local Airy rescaling that resolves a simple turning
 * point of ε²y″ = q(x)y, and the connection formulae (with the −π/4 phase) that
 * splice the exponential Liouville–Green solution on the forbidden side to the
 * oscillatory solution on the allowed side; applications to locating large zeros.
 *
 * Numerical spot-checks (scipy.special.airy / mpmath.airyai / mpmath.airyaizero)
 * were run for every asymptotic amplitude, phase, decay rate and zero estimate
 * that is numerically checkable; pure structural ("identify the stretched
 * variable") reasoning carries no numeric check.
 */
export const questions: Question[] = [
  // ───────────────────────── FOUNDATION (6) ─────────────────────────
  {
    id: "am10b-001",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the leading-order asymptotic form of \\( \\mathrm{Ai}(x) \\) as \\( x \\to +\\infty \\), stating the prefactor and the exponential decay rate.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Airy function", "decaying asymptotics", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Quote the decaying form.", workingLatex: "\\mathrm{Ai}(x) \\sim \\frac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{-\\frac{2}{3} x^{3/2}}, \\qquad x \\to +\\infty.", explanation: "On the forbidden side the Airy function decays exponentially; the algebraic prefactor is \\( x^{-1/4} \\) and the rate is set by \\( \\tfrac{2}{3} x^{3/2} \\)." },
        { stepNumber: 2, description: "Identify the pieces.", workingLatex: "\\text{prefactor } \\frac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}, \\qquad \\text{rate } \\frac{2}{3} x^{3/2}.", explanation: "" },
      ],
      finalAnswer: "\\( \\mathrm{Ai}(x) \\sim \\dfrac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{-\\frac{2}{3} x^{3/2}} \\) as \\( x \\to +\\infty \\).",
      canonicalAnswer: "(1/(2 sqrt(pi))) x^{-1/4} exp(-(2/3) x^{3/2})",
    },
  },
  {
    id: "am10b-002",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the leading-order oscillatory asymptotic form of \\( \\mathrm{Ai}(-x) \\) as \\( x \\to +\\infty \\), including the \\( \\tfrac{\\pi}{4} \\) phase.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Airy function", "oscillatory asymptotics", "phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Quote the oscillatory form.", workingLatex: "\\mathrm{Ai}(-x) \\sim \\frac{1}{\\sqrt{\\pi}}\\, x^{-1/4} \\sin\\!\\left( \\frac{2}{3} x^{3/2} + \\frac{\\pi}{4} \\right), \\qquad x \\to +\\infty.", explanation: "On the allowed side the solution oscillates with a slowly-decaying \\( x^{-1/4} \\) envelope; the constant \\( +\\tfrac{\\pi}{4} \\) is the connection phase." },
        { stepNumber: 2, description: "Note the amplitude doubling.", workingLatex: "\\frac{1}{\\sqrt{\\pi}} = 2 \\cdot \\frac{1}{2\\sqrt{\\pi}}.", explanation: "The oscillatory amplitude is twice the decaying prefactor, the hallmark of the connection across the turning point." },
      ],
      finalAnswer: "\\( \\mathrm{Ai}(-x) \\sim \\dfrac{1}{\\sqrt{\\pi}}\\, x^{-1/4} \\sin\\!\\left( \\tfrac{2}{3} x^{3/2} + \\tfrac{\\pi}{4} \\right) \\) as \\( x \\to +\\infty \\).",
      canonicalAnswer: "(1/sqrt(pi)) x^{-1/4} sin((2/3) x^{3/2} + pi/4)",
    },
  },
  {
    id: "am10b-003",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The Airy equation is \\( y'' = x\\,y \\). State the location of its turning point and say on which side of it the solutions are oscillatory.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Airy equation", "turning point", "oscillatory vs exponential"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate where the coefficient vanishes.", workingLatex: "y'' = x\\,y, \\qquad q(x) = x = 0 \\;\\Longrightarrow\\; x = 0.", explanation: "A turning point is where the coefficient of \\( y \\) changes sign; here \\( q(x) = x \\) vanishes at the origin." },
        { stepNumber: 2, description: "Classify the two sides.", workingLatex: "x < 0:\\ \\text{oscillatory}, \\qquad x > 0:\\ \\text{exponential}.", explanation: "For \\( x < 0 \\) the equation is \\( y'' = -|x| y \\) (oscillatory); for \\( x > 0 \\) it is \\( y'' = +x\\,y \\) (exponential growth/decay)." },
      ],
      finalAnswer: "Turning point at \\( x = 0 \\); solutions are oscillatory for \\( x < 0 \\) and exponential for \\( x > 0 \\).",
      canonicalAnswer: "x=0; oscillatory for x<0",
    },
  },
  {
    id: "am10b-004",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the leading-order asymptotic form of \\( \\mathrm{Bi}(x) \\) as \\( x \\to +\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Airy function", "Bi", "growing asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Quote the growing form.", workingLatex: "\\mathrm{Bi}(x) \\sim \\frac{1}{\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{+\\frac{2}{3} x^{3/2}}, \\qquad x \\to +\\infty.", explanation: "\\( \\mathrm{Bi} \\) is the linearly independent solution that grows exponentially on the forbidden side; the rate is \\( +\\tfrac{2}{3} x^{3/2} \\)." },
        { stepNumber: 2, description: "Contrast with Ai.", workingLatex: "\\frac{\\text{Bi prefactor}}{\\text{Ai prefactor}} = \\frac{1/\\sqrt{\\pi}}{1/(2\\sqrt{\\pi})} = 2.", explanation: "The algebraic prefactor of \\( \\mathrm{Bi} \\) is twice that of the decaying \\( \\mathrm{Ai} \\)." },
      ],
      finalAnswer: "\\( \\mathrm{Bi}(x) \\sim \\dfrac{1}{\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{+\\frac{2}{3} x^{3/2}} \\) as \\( x \\to +\\infty \\).",
      canonicalAnswer: "(1/sqrt(pi)) x^{-1/4} exp((2/3) x^{3/2})",
    },
  },
  {
    id: "am10b-005",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "From the leading asymptotics of \\( \\mathrm{Ai}(x) \\), find the leading-order behaviour of \\( \\ln \\mathrm{Ai}(x) \\) as \\( x \\to +\\infty \\) (the dominant term only).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Airy function", "decay rate", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take the log of the leading form.", workingLatex: "\\ln \\mathrm{Ai}(x) \\sim \\ln\\!\\left( \\frac{1}{2\\sqrt{\\pi}} x^{-1/4} \\right) - \\frac{2}{3} x^{3/2}.", explanation: "The exponential factor dominates the algebraic prefactor and the constant." },
        { stepNumber: 2, description: "Keep the dominant term.", workingLatex: "\\ln \\mathrm{Ai}(x) \\sim -\\frac{2}{3} x^{3/2}.", explanation: "The \\( -\\tfrac14 \\ln x \\) and constant pieces are subdominant to \\( x^{3/2} \\)." },
      ],
      finalAnswer: "\\( \\ln \\mathrm{Ai}(x) \\sim -\\dfrac{2}{3} x^{3/2} \\) as \\( x \\to +\\infty \\).",
      canonicalAnswer: "-(2/3) x^{3/2}",
    },
  },
  {
    id: "am10b-006",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the equation \\( \\varepsilon^{2} y'' = q(x)\\,y \\) with a simple turning point at \\( x = a \\) (so \\( q(a) = 0,\\ q'(a) \\neq 0 \\)), write down the stretched local variable \\( \\xi \\) that reduces the equation to Airy form near \\( x = a \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["turning point", "local rescaling", "stretched variable"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Linearise the coefficient.", workingLatex: "q(x) \\approx q'(a)\\,(x - a) \\quad \\text{near } x = a.", explanation: "Near a simple turning point the coefficient is linear in \\( x - a \\)." },
        { stepNumber: 2, description: "State the local stretching.", workingLatex: "\\xi = \\left( \\frac{q'(a)}{\\varepsilon^{2}} \\right)^{1/3} (x - a).", explanation: "This is the distinguished scale on which \\( \\varepsilon^{2} y'' \\) and \\( q\\,y \\) balance; substituting reduces the equation to \\( W'' = \\xi\\,W \\)." },
      ],
      finalAnswer: "\\( \\xi = \\left( \\dfrac{q'(a)}{\\varepsilon^{2}} \\right)^{1/3} (x - a) \\).",
      canonicalAnswer: "(q'(a)/eps^2)^{1/3} (x-a)",
    },
  },

  // ───────────────────────── STANDARD (12) ─────────────────────────
  {
    id: "am10b-007",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 07",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Write down the two-term large-\\( x \\) asymptotic expansion of \\( \\mathrm{Ai}(x) \\), including the first algebraic correction inside the bracket.",
    marks: 3,
    yearCreated: 2026,
    tags: ["Airy function", "correction term", "asymptotic series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the asymptotic series.", workingLatex: "\\mathrm{Ai}(x) \\sim \\frac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{-\\frac{2}{3} x^{3/2}} \\left[ 1 - \\frac{5}{48} x^{-3/2} + \\frac{385}{4608} x^{-3} - \\cdots \\right].", explanation: "The bracket is an asymptotic series in the small quantity \\( x^{-3/2} \\)." },
        { stepNumber: 2, description: "Truncate to two terms.", workingLatex: "\\mathrm{Ai}(x) \\sim \\frac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{-\\frac{2}{3} x^{3/2}} \\left( 1 - \\frac{5}{48} x^{-3/2} \\right).", explanation: "Numerical check at \\( x = 5 \\): \\( \\mathrm{Ai}(5) = 1.083444\\times 10^{-4} \\); leading-only \\( = 1.092981\\times 10^{-4} \\); with the \\( -\\tfrac{5}{48} x^{-3/2} \\) term \\( = 1.082798\\times 10^{-4} \\), a clear improvement." },
      ],
      finalAnswer: "\\( \\mathrm{Ai}(x) \\sim \\dfrac{1}{2\\sqrt{\\pi}}\\, x^{-1/4}\\, e^{-\\frac{2}{3} x^{3/2}} \\left( 1 - \\dfrac{5}{48} x^{-3/2} \\right) \\).",
      canonicalAnswer: "(1/(2 sqrt(pi))) x^{-1/4} exp(-(2/3) x^{3/2}) (1 - (5/48) x^{-3/2})",
    },
  },
  {
    id: "am10b-008",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 08",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "By substituting \\( \\xi = (q'(a)/\\varepsilon^{2})^{1/3}(x - a) \\) into \\( \\varepsilon^{2} y'' = q'(a)(x - a)\\,y \\), show that the local equation reduces to the Airy equation \\( W'' = \\xi\\,W \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["turning point", "local rescaling", "Airy equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the change of variable.", workingLatex: "\\xi = \\kappa\\,(x - a), \\qquad \\kappa = \\left( \\frac{q'(a)}{\\varepsilon^{2}} \\right)^{1/3}, \\qquad \\frac{d}{dx} = \\kappa \\frac{d}{d\\xi}.", explanation: "Let \\( c = q'(a) \\) and write \\( W(\\xi) = y(x) \\)." },
        { stepNumber: 2, description: "Transform the second derivative.", workingLatex: "y'' = \\kappa^{2} W'', \\qquad \\varepsilon^{2} y'' = \\varepsilon^{2} \\kappa^{2}\\, W''.", explanation: "" },
        { stepNumber: 3, description: "Transform the right-hand side.", workingLatex: "q'(a)(x - a)\\,y = c \\cdot \\frac{\\xi}{\\kappa}\\, W.", explanation: "Use \\( x - a = \\xi/\\kappa \\)." },
        { stepNumber: 4, description: "Equate and simplify the coefficients.", workingLatex: "\\varepsilon^{2}\\kappa^{2}\\, W'' = \\frac{c}{\\kappa}\\,\\xi\\, W \\;\\Longrightarrow\\; W'' = \\frac{c}{\\varepsilon^{2}\\kappa^{3}}\\,\\xi\\, W.", explanation: "" },
        { stepNumber: 5, description: "Insert the definition of \\( \\kappa \\).", workingLatex: "\\kappa^{3} = \\frac{c}{\\varepsilon^{2}} \\;\\Longrightarrow\\; \\frac{c}{\\varepsilon^{2}\\kappa^{3}} = 1 \\;\\Longrightarrow\\; W'' = \\xi\\, W.", explanation: "The chosen scale makes the coefficient exactly unity, giving the Airy equation." },
      ],
      finalAnswer: "\\( W'' = \\xi\\, W \\).",
      canonicalAnswer: "W'' = xi W",
    },
  },
  {
    id: "am10b-009",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 09",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = q(x)\\,y \\) with a simple turning point at \\( x = a \\), state the connection formula linking the Liouville–Green solution that decays as \\( x \\to +\\infty \\) on the forbidden side \\( (x > a) \\) to the oscillatory solution on the allowed side \\( (x < a) \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["connection formula", "decaying to oscillatory", "-pi/4 phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the decaying LG solution (forbidden side).", workingLatex: "y \\sim \\frac{1}{q^{1/4}} \\exp\\!\\left( -\\frac{1}{\\varepsilon} \\int_{a}^{x} \\sqrt{q}\\; dt \\right), \\qquad x > a.", explanation: "On \\( x > a \\), \\( q > 0 \\); the decaying branch falls off as \\( x \\to +\\infty \\)." },
        { stepNumber: 2, description: "Write the matched oscillatory solution (allowed side).", workingLatex: "y \\sim \\frac{2}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon} \\int_{x}^{a} \\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right), \\qquad x < a.", explanation: "On \\( x < a \\), \\( q < 0 \\); the oscillatory branch carries amplitude \\( 2 \\) and the \\( -\\tfrac{\\pi}{4} \\) connection phase." },
        { stepNumber: 3, description: "State the rule.", workingLatex: "\\frac{1}{q^{1/4}} e^{-\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}} \\;\\longleftrightarrow\\; \\frac{2}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q} - \\frac{\\pi}{4} \\right).", explanation: "Decaying exponential \\( \\leftrightarrow \\) cosine with the \\( -\\tfrac{\\pi}{4} \\) shift and amplitude doubling." },
      ],
      finalAnswer: "\\( \\dfrac{1}{q^{1/4}} e^{-\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}} \\;\\longleftrightarrow\\; \\dfrac{2}{(-q)^{1/4}} \\cos\\!\\left( \\dfrac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q} - \\dfrac{\\pi}{4} \\right) \\).",
    },
  },
  {
    id: "am10b-010",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 10",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Verify that the connection-formula cosine \\( \\cos\\!\\left( \\tfrac{2}{3} x^{3/2} - \\tfrac{\\pi}{4} \\right) \\) equals the standard sine \\( \\sin\\!\\left( \\tfrac{2}{3} x^{3/2} + \\tfrac{\\pi}{4} \\right) \\) appearing in \\( \\mathrm{Ai}(-x) \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["phase", "connection formula", "trig identity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Let \\( \\theta = \\tfrac{2}{3} x^{3/2} \\) and expand the cosine.", workingLatex: "\\cos\\!\\left( \\theta - \\frac{\\pi}{4} \\right) = \\cos\\theta\\cos\\frac{\\pi}{4} + \\sin\\theta\\sin\\frac{\\pi}{4} = \\frac{\\cos\\theta + \\sin\\theta}{\\sqrt{2}}.", explanation: "" },
        { stepNumber: 2, description: "Expand the sine.", workingLatex: "\\sin\\!\\left( \\theta + \\frac{\\pi}{4} \\right) = \\sin\\theta\\cos\\frac{\\pi}{4} + \\cos\\theta\\sin\\frac{\\pi}{4} = \\frac{\\sin\\theta + \\cos\\theta}{\\sqrt{2}}.", explanation: "" },
        { stepNumber: 3, description: "Compare.", workingLatex: "\\cos\\!\\left( \\theta - \\frac{\\pi}{4} \\right) = \\sin\\!\\left( \\theta + \\frac{\\pi}{4} \\right).", explanation: "Numerical check at \\( \\theta = 2 \\): both equal \\( 0.348710 \\). The two standard ways of writing the connected oscillation agree." },
      ],
      finalAnswer: "\\( \\cos\\!\\left( \\tfrac{2}{3} x^{3/2} - \\tfrac{\\pi}{4} \\right) = \\sin\\!\\left( \\tfrac{2}{3} x^{3/2} + \\tfrac{\\pi}{4} \\right) \\).",
    },
  },
  {
    id: "am10b-011",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 11",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Using the asymptotic phase, derive the estimate for the large positive zeros \\( a_{s} \\) of \\( \\mathrm{Ai}(-a_{s}) = 0 \\), giving \\( a_{s} \\) in closed form.",
    marks: 4,
    yearCreated: 2026,
    tags: ["Airy zeros", "phase condition", "large zeros"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the oscillatory factor to zero.", workingLatex: "\\mathrm{Ai}(-a) \\sim \\frac{1}{\\sqrt{\\pi}} a^{-1/4} \\sin\\!\\left( \\frac{2}{3} a^{3/2} + \\frac{\\pi}{4} \\right) = 0.", explanation: "Zeros occur where the sine vanishes." },
        { stepNumber: 2, description: "Impose the phase condition.", workingLatex: "\\frac{2}{3} a_{s}^{3/2} + \\frac{\\pi}{4} = s\\pi, \\qquad s = 1, 2, \\dots", explanation: "The sine is zero at integer multiples of \\( \\pi \\)." },
        { stepNumber: 3, description: "Solve for \\( a_{s} \\).", workingLatex: "\\frac{2}{3} a_{s}^{3/2} = \\left( s - \\frac14 \\right)\\pi \\;\\Longrightarrow\\; a_{s} = \\left[ \\frac{3\\pi}{8}(4s - 1) \\right]^{2/3}.", explanation: "Numerical check (mpmath.airyaizero): \\( a_{1} = 2.33811 \\) vs estimate \\( 2.32025 \\); \\( a_{5} = 7.94413 \\) vs \\( 7.94249 \\); \\( a_{10} = 12.82878 \\) vs \\( 12.82814 \\) — accuracy improves with \\( s \\)." },
      ],
      finalAnswer: "\\( a_{s} \\sim \\left[ \\dfrac{3\\pi}{8}(4s - 1) \\right]^{2/3} \\) as \\( s \\to \\infty \\).",
      canonicalAnswer: "((3 pi/8)(4s-1))^{2/3}",
    },
  },
  {
    id: "am10b-012",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 12",
    difficulty: "Standard",
    answerType: "numeric",
    examStyle: true,
    questionText: "Use the asymptotic estimate \\( a_{s} \\approx \\left[ \\tfrac{3\\pi}{8}(4s - 1) \\right]^{2/3} \\) to approximate the first zero \\( a_{1} \\) of \\( \\mathrm{Ai}(-x) \\), and compare with the true value \\( 2.33811 \\). Give the estimate to 4 decimal places.",
    marks: 3,
    yearCreated: 2026,
    tags: ["Airy zeros", "numerical comparison", "verification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( s = 1 \\).", workingLatex: "a_{1} \\approx \\left[ \\frac{3\\pi}{8}(4 \\cdot 1 - 1) \\right]^{2/3} = \\left[ \\frac{9\\pi}{8} \\right]^{2/3}.", explanation: "" },
        { stepNumber: 2, description: "Evaluate.", workingLatex: "\\frac{9\\pi}{8} = 3.53429, \\qquad (3.53429)^{2/3} = 2.32025.", explanation: "" },
        { stepNumber: 3, description: "Compare with the exact zero.", workingLatex: "a_{1}^{\\text{est}} = 2.3203, \\qquad a_{1}^{\\text{true}} = 2.3381.", explanation: "Even the very first zero is captured to better than \\( 1\\% \\) by the leading asymptotic phase." },
      ],
      finalAnswer: "\\( a_{1} \\approx 2.3203 \\) (true \\( 2.3381 \\)).",
      canonicalAnswer: "2.3203",
    },
  },
  {
    id: "am10b-013",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 13",
    difficulty: "Standard",
    answerType: "numeric",
    examStyle: true,
    questionText: "Using only the leading term \\( \\mathrm{Ai}(x) \\sim \\tfrac{1}{2\\sqrt{\\pi}} x^{-1/4} e^{-\\frac{2}{3} x^{3/2}} \\), estimate \\( \\mathrm{Ai}(9) \\) and quote the relative error against the true value \\( 2.47117\\times 10^{-9} \\). Give the estimate to 3 significant figures.",
    marks: 3,
    yearCreated: 2026,
    tags: ["Airy function", "leading order", "numerical comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Evaluate the exponent.", workingLatex: "\\frac{2}{3} \\cdot 9^{3/2} = \\frac{2}{3} \\cdot 27 = 18, \\qquad e^{-18} = 1.523\\times 10^{-8}.", explanation: "" },
        { stepNumber: 2, description: "Assemble the prefactor.", workingLatex: "\\frac{1}{2\\sqrt{\\pi}} \\cdot 9^{-1/4} = \\frac{1}{2\\sqrt{\\pi}} \\cdot \\frac{1}{\\sqrt{3}} = 0.16286.", explanation: "Using \\( 9^{-1/4} = 3^{-1/2} \\)." },
        { stepNumber: 3, description: "Multiply.", workingLatex: "\\mathrm{Ai}(9) \\approx 0.16286 \\times 1.523\\times 10^{-8} = 2.480\\times 10^{-9}.", explanation: "Numerical check: true \\( 2.47117\\times 10^{-9} \\); relative error \\( \\approx 0.4\\% \\)." },
      ],
      finalAnswer: "\\( \\mathrm{Ai}(9) \\approx 2.48\\times 10^{-9} \\), relative error \\( \\approx 0.4\\% \\).",
      canonicalAnswer: "2.48e-9",
    },
  },
  {
    id: "am10b-014",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 14",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For the Airy equation \\( y'' = x\\,y \\), compute the Liouville–Green exponent \\( \\int_{0}^{x} \\sqrt{q(t)}\\; dt \\) (with \\( q = t \\)) and hence identify the exponential factor of the decaying solution on \\( x > 0 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["Liouville-Green", "WKB exponent", "Airy equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate.", workingLatex: "\\int_{0}^{x} \\sqrt{t}\\; dt = \\left[ \\frac{2}{3} t^{3/2} \\right]_{0}^{x} = \\frac{2}{3} x^{3/2}.", explanation: "Numerical check at \\( x = 3 \\): \\( \\int_{0}^{3}\\sqrt{t}\\,dt = 3.46410 = \\tfrac{2}{3}\\cdot 3^{3/2} \\)." },
        { stepNumber: 2, description: "Build the decaying LG factor.", workingLatex: "y \\sim x^{-1/4} \\exp\\!\\left( -\\frac{2}{3} x^{3/2} \\right).", explanation: "With \\( \\varepsilon = 1 \\) and \\( q^{1/4} = x^{1/4} \\), the decaying branch carries exactly the \\( e^{-\\frac{2}{3} x^{3/2}} \\) factor seen in \\( \\mathrm{Ai}(x) \\)." },
      ],
      finalAnswer: "\\( \\int_{0}^{x}\\sqrt{t}\\,dt = \\dfrac{2}{3} x^{3/2} \\); decaying factor \\( x^{-1/4} e^{-\\frac{2}{3} x^{3/2}} \\).",
      canonicalAnswer: "(2/3) x^{3/2}",
    },
  },
  {
    id: "am10b-015",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 15",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (x - 2)\\,y \\) (turning point at \\( x = 2 \\), so \\( q'(2) = 1 \\)) with \\( \\varepsilon = 0.1 \\), find the numerical value of the inner-layer stretching factor \\( \\kappa = (q'(2)/\\varepsilon^{2})^{1/3} \\) and state the inner variable \\( \\xi \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["turning point", "boundary layer width", "inner variable"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute the data.", workingLatex: "\\kappa = \\left( \\frac{q'(2)}{\\varepsilon^{2}} \\right)^{1/3} = \\left( \\frac{1}{(0.1)^{2}} \\right)^{1/3} = 100^{1/3}.", explanation: "" },
        { stepNumber: 2, description: "Evaluate.", workingLatex: "100^{1/3} = 4.6416.", explanation: "Numerical check: \\( 100^{1/3} = 4.64159 \\); the turning-point layer has width \\( \\kappa^{-1} \\approx 0.215 \\)." },
        { stepNumber: 3, description: "State the inner variable.", workingLatex: "\\xi = 4.6416\\,(x - 2).", explanation: "" },
      ],
      finalAnswer: "\\( \\kappa = 100^{1/3} \\approx 4.6416 \\), \\( \\xi = 4.6416\\,(x - 2) \\).",
      canonicalAnswer: "4.6416",
    },
  },
  {
    id: "am10b-016",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "State the connection formula for the growing Liouville–Green solution on the forbidden side and the sine-type oscillatory solution it matches to on the allowed side of a simple turning point at \\( x = a \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["connection formula", "growing solution", "sine matching"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the growing LG solution (forbidden side).", workingLatex: "y \\sim \\frac{1}{q^{1/4}} \\exp\\!\\left( +\\frac{1}{\\varepsilon} \\int_{a}^{x} \\sqrt{q}\\; dt \\right), \\qquad x > a.", explanation: "The growing branch increases as \\( x \\to +\\infty \\)." },
        { stepNumber: 2, description: "Write the matched oscillatory solution.", workingLatex: "y \\sim -\\frac{1}{(-q)^{1/4}} \\sin\\!\\left( \\frac{1}{\\varepsilon} \\int_{x}^{a} \\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right), \\qquad x < a.", explanation: "The growing exponential connects to a sine (with amplitude \\( 1 \\)), the second of the two standard rules; the sign is fixed by requiring a single-valued recessive/dominant pairing." },
        { stepNumber: 3, description: "State the rule.", workingLatex: "\\frac{1}{q^{1/4}} e^{+\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}} \\;\\longleftrightarrow\\; -\\frac{1}{(-q)^{1/4}} \\sin\\!\\left( \\frac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q} - \\frac{\\pi}{4} \\right).", explanation: "Growing exponential \\( \\leftrightarrow \\) (minus) sine, contrasting with the decaying \\( \\leftrightarrow \\) (twice) cosine rule." },
      ],
      finalAnswer: "\\( \\dfrac{1}{q^{1/4}} e^{+\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}} \\;\\longleftrightarrow\\; -\\dfrac{1}{(-q)^{1/4}} \\sin\\!\\left( \\dfrac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q} - \\dfrac{\\pi}{4} \\right) \\).",
    },
  },
  {
    id: "am10b-017",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 17",
    difficulty: "Standard",
    answerType: "numeric",
    examStyle: true,
    questionText: "The ratio \\( \\mathrm{Bi}(x)/\\mathrm{Ai}(x) \\) grows like \\( 2\\,e^{\\frac{4}{3} x^{3/2}} \\) as \\( x \\to +\\infty \\). Use this to estimate \\( \\mathrm{Bi}(6)/\\mathrm{Ai}(6) \\) to 2 significant figures, and compare with the true value \\( 6.57\\times 10^{8} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["Airy function", "Ai vs Bi", "exponential ratio"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of leading asymptotics.", workingLatex: "\\frac{\\mathrm{Bi}(x)}{\\mathrm{Ai}(x)} \\sim \\frac{\\frac{1}{\\sqrt{\\pi}} x^{-1/4} e^{+\\frac{2}{3} x^{3/2}}}{\\frac{1}{2\\sqrt{\\pi}} x^{-1/4} e^{-\\frac{2}{3} x^{3/2}}} = 2\\, e^{\\frac{4}{3} x^{3/2}}.", explanation: "The prefactor ratio is \\( 2 \\); the exponents add." },
        { stepNumber: 2, description: "Evaluate the exponent.", workingLatex: "\\frac{4}{3} \\cdot 6^{3/2} = \\frac{4}{3} \\cdot 14.6969 = 19.596.", explanation: "" },
        { stepNumber: 3, description: "Assemble.", workingLatex: "2\\, e^{19.596} = 2 \\times 3.239\\times 10^{8} = 6.48\\times 10^{8}.", explanation: "Numerical check: true ratio \\( \\mathrm{Bi}(6)/\\mathrm{Ai}(6) = 6.571\\times 10^{8} \\); estimate \\( 6.48\\times 10^{8} \\), within \\( \\sim 1.4\\% \\)." },
      ],
      finalAnswer: "\\( \\mathrm{Bi}(6)/\\mathrm{Ai}(6) \\approx 6.5\\times 10^{8} \\) (true \\( 6.57\\times 10^{8} \\)).",
      canonicalAnswer: "6.5e8",
    },
  },
  {
    id: "am10b-018",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 18",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( y'' = k^{2} x\\,y \\) with large parameter \\( k \\) (a turning point at \\( x = 0 \\)), find the width of the turning-point layer as a power of \\( k \\), and the local variable \\( \\xi \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["turning point", "layer width", "large parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Match to standard form.", workingLatex: "y'' = k^{2} x\\,y \\;\\Longleftrightarrow\\; \\varepsilon^{2} y'' = x\\,y, \\qquad \\varepsilon = \\frac{1}{k}.", explanation: "Here \\( q(x) = x \\), \\( q'(0) = 1 \\)." },
        { stepNumber: 2, description: "Read off the local scale.", workingLatex: "\\xi = \\left( \\frac{q'(0)}{\\varepsilon^{2}} \\right)^{1/3} x = k^{2/3}\\, x.", explanation: "" },
        { stepNumber: 3, description: "Identify the layer width.", workingLatex: "x = O\\!\\left( k^{-2/3} \\right).", explanation: "The turning-point region where the WKB approximation fails has width \\( k^{-2/3} \\)." },
      ],
      finalAnswer: "Layer width \\( O(k^{-2/3}) \\); \\( \\xi = k^{2/3} x \\).",
      canonicalAnswer: "k^{-2/3}",
    },
  },

  // ───────────────────────── CHALLENGE (12) ─────────────────────────
  {
    id: "am10b-019",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 19",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Starting from \\( \\mathrm{Ai}(x) \\sim \\tfrac{1}{2\\sqrt{\\pi}} x^{-1/4} e^{-\\frac{2}{3} x^{3/2}}[1 - \\tfrac{5}{48} x^{-3/2} + \\cdots] \\), obtain the three-term asymptotic expansion of \\( \\ln \\mathrm{Ai}(x) \\) (the \\( x^{3/2} \\), \\( \\ln x \\) and constant terms).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Airy function", "logarithm", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take the logarithm.", workingLatex: "\\ln \\mathrm{Ai}(x) = -\\frac{2}{3} x^{3/2} - \\frac{1}{4}\\ln x - \\ln\\!\\left( 2\\sqrt{\\pi} \\right) + \\ln\\!\\left[ 1 - \\frac{5}{48} x^{-3/2} + \\cdots \\right].", explanation: "Logs turn the product into a sum of the exponent, the algebraic prefactor and the bracket." },
        { stepNumber: 2, description: "Expand the bracket.", workingLatex: "\\ln\\!\\left[ 1 - \\frac{5}{48} x^{-3/2} + \\cdots \\right] = -\\frac{5}{48} x^{-3/2} + O(x^{-3}).", explanation: "This is a decaying \\( O(x^{-3/2}) \\) correction, subdominant to the three leading pieces." },
        { stepNumber: 3, description: "Collect the three leading terms.", workingLatex: "\\ln \\mathrm{Ai}(x) \\sim -\\frac{2}{3} x^{3/2} - \\frac{1}{4}\\ln x - \\ln\\!\\left( 2\\sqrt{\\pi} \\right).", explanation: "Numerical check at \\( x = 16 \\): \\( \\ln\\mathrm{Ai}(16) = -44.62693 \\); three-term form \\( = -42.66667 - 0.69315 - 1.26551 = -44.62533 \\)." },
      ],
      finalAnswer: "\\( \\ln \\mathrm{Ai}(x) \\sim -\\dfrac{2}{3} x^{3/2} - \\dfrac{1}{4}\\ln x - \\ln\\!\\left( 2\\sqrt{\\pi} \\right) \\).",
    },
  },
  {
    id: "am10b-020",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 20",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Construct the global solution of \\( \\varepsilon^{2} y'' = q(x)\\,y \\) (simple turning point at \\( x = a \\), \\( q > 0 \\) for \\( x > a \\)) that decays as \\( x \\to +\\infty \\), writing both the forbidden-side and allowed-side forms and identifying the \\( -\\tfrac{\\pi}{4} \\) phase.",
    marks: 5,
    yearCreated: 2026,
    tags: ["global solution", "connection formula", "decaying at infinity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Choose the recessive (decaying) branch on \\( x > a \\).", workingLatex: "y \\sim \\frac{C}{q^{1/4}} \\exp\\!\\left( -\\frac{1}{\\varepsilon}\\int_{a}^{x} \\sqrt{q}\\; dt \\right), \\qquad x > a.", explanation: "Decaying as \\( x \\to +\\infty \\) forces the recessive exponential; any admixture of the growing branch would blow up." },
        { stepNumber: 2, description: "Apply the connection formula.", workingLatex: "\\frac{1}{q^{1/4}} e^{-\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}} \\;\\longleftrightarrow\\; \\frac{2}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right).", explanation: "Decaying exponential maps to a cosine of doubled amplitude carrying the \\( -\\tfrac{\\pi}{4} \\) shift." },
        { stepNumber: 3, description: "Write the allowed-side solution.", workingLatex: "y \\sim \\frac{2C}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right), \\qquad x < a.", explanation: "The same constant \\( C \\) ties the two sides together." },
        { stepNumber: 4, description: "Interpret the phase.", workingLatex: "\\text{phase deficit} = -\\frac{\\pi}{4}.", explanation: "The \\( -\\tfrac{\\pi}{4} \\) is universal for a simple turning point and is exactly the phase that makes \\( \\mathrm{Ai} \\) (the decaying solution) match \\( \\sin(\\tfrac{2}{3}|x|^{3/2} + \\tfrac{\\pi}{4}) \\) on \\( x < 0 \\)." },
      ],
      finalAnswer: "\\( y \\sim \\dfrac{2C}{(-q)^{1/4}} \\cos\\!\\left( \\dfrac{1}{\\varepsilon}\\int_{x}^{a}\\sqrt{-q}\\, dt - \\dfrac{\\pi}{4} \\right) \\) for \\( x < a \\).",
    },
  },
  {
    id: "am10b-021",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 21",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Eigenvalue-type problem. For \\( y'' + \\lambda(1 - x)\\,y = 0 \\) on \\( x < 1 \\) with \\( y \\to 0 \\) as \\( x \\to +\\infty \\) (past the turning point \\( x = 1 \\)) and \\( y(0) = 0 \\), use the connection formula to derive the large-\\( \\lambda \\) quantisation condition for the allowed-region phase.",
    marks: 5,
    yearCreated: 2026,
    tags: ["eigenvalue", "quantisation", "connection formula"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the turning point and allowed region.", workingLatex: "y'' = -\\lambda(1 - x)\\,y, \\qquad \\text{turning point } x = 1, \\quad \\text{oscillatory for } x < 1.", explanation: "Writing \\( \\varepsilon^{2} = 1/\\lambda \\), this is \\( \\varepsilon^{2} y'' = (x - 1)y \\); for \\( x < 1 \\) the coefficient is negative, hence oscillatory." },
        { stepNumber: 2, description: "Decaying-at-infinity solution gives the allowed-side form.", workingLatex: "y \\sim \\frac{2C}{(1 - x)^{1/4}} \\cos\\!\\left( \\sqrt{\\lambda}\\int_{x}^{1}\\sqrt{1 - t}\\; dt - \\frac{\\pi}{4} \\right).", explanation: "Apply the decaying \\( \\leftrightarrow \\) cosine connection formula with \\( \\varepsilon = \\lambda^{-1/2} \\)." },
        { stepNumber: 3, description: "Evaluate the phase integral.", workingLatex: "\\int_{x}^{1}\\sqrt{1 - t}\\; dt = \\frac{2}{3}(1 - x)^{3/2}.", explanation: "" },
        { stepNumber: 4, description: "Impose the boundary condition \\( y(0) = 0 \\).", workingLatex: "\\cos\\!\\left( \\sqrt{\\lambda}\\cdot \\frac{2}{3} - \\frac{\\pi}{4} \\right) = 0 \\;\\Longrightarrow\\; \\frac{2}{3}\\sqrt{\\lambda} - \\frac{\\pi}{4} = \\left( n + \\frac12 \\right)\\pi.", explanation: "At \\( x = 0 \\) the phase integral is \\( \\tfrac{2}{3} \\); the cosine vanishes at odd multiples of \\( \\pi/2 \\)." },
        { stepNumber: 5, description: "Solve for the eigenvalues.", workingLatex: "\\sqrt{\\lambda_{n}} = \\frac{3}{2}\\left[ \\left( n + \\frac34 \\right)\\pi \\right] \\;\\Longrightarrow\\; \\lambda_{n} \\sim \\left[ \\frac{3\\pi}{2}\\left( n + \\frac34 \\right) \\right]^{2}.", explanation: "The \\( -\\tfrac{\\pi}{4} \\) connection phase shifts the standard \\( (n+\\tfrac12) \\) to \\( (n+\\tfrac34) \\)." },
      ],
      finalAnswer: "\\( \\dfrac{2}{3}\\sqrt{\\lambda} - \\dfrac{\\pi}{4} = \\left( n + \\tfrac12 \\right)\\pi \\), i.e. \\( \\lambda_{n} \\sim \\left[ \\tfrac{3\\pi}{2}(n + \\tfrac34) \\right]^{2} \\).",
    },
  },
  {
    id: "am10b-022",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 22",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Show that matching the inner Airy solution \\( W(\\xi) = \\mathrm{Ai}(\\xi) \\) to the outer Liouville–Green decaying solution on the forbidden side of a simple turning point reproduces the LG prefactor \\( q^{-1/4} \\) and the exponent \\( -\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q} \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["matched asymptotics", "inner-outer matching", "Liouville-Green"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the inner solution and its large-\\( \\xi \\) form.", workingLatex: "W(\\xi) = \\mathrm{Ai}(\\xi) \\sim \\frac{1}{2\\sqrt{\\pi}} \\xi^{-1/4} e^{-\\frac{2}{3}\\xi^{3/2}}, \\qquad \\xi \\to +\\infty.", explanation: "The inner region uses the stretched \\( \\xi = \\kappa(x - a) \\), \\( \\kappa = (q'(a)/\\varepsilon^{2})^{1/3} \\)." },
        { stepNumber: 2, description: "Express \\( \\xi^{3/2} \\) in outer variables.", workingLatex: "\\frac{2}{3}\\xi^{3/2} = \\frac{2}{3}\\kappa^{3/2}(x - a)^{3/2} = \\frac{2}{3}\\frac{\\sqrt{q'(a)}}{\\varepsilon}(x - a)^{3/2}.", explanation: "Use \\( \\kappa^{3/2} = (q'(a)/\\varepsilon^{2})^{1/2} \\)." },
        { stepNumber: 3, description: "Recognise the LG exponent.", workingLatex: "\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}\\; dt \\approx \\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q'(a)(t - a)}\\; dt = \\frac{2}{3}\\frac{\\sqrt{q'(a)}}{\\varepsilon}(x - a)^{3/2}.", explanation: "Near \\( a \\), \\( q \\approx q'(a)(t - a) \\); the integral matches the inner exponent exactly." },
        { stepNumber: 4, description: "Match the prefactor.", workingLatex: "\\xi^{-1/4} = \\kappa^{-1/4}(x - a)^{-1/4} \\propto \\big( q'(a)(x - a) \\big)^{-1/4} = q^{-1/4}.", explanation: "Up to constants the inner \\( \\xi^{-1/4} \\) becomes the outer \\( q^{-1/4} \\), confirming the LG amplitude." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "W \\;\\longrightarrow\\; \\frac{\\text{const}}{q^{1/4}} \\exp\\!\\left( -\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q}\\; dt \\right).", explanation: "The inner Airy solution, expanded for large \\( \\xi \\), is exactly the outer decaying LG solution; this is the matching that justifies the connection formula." },
      ],
      finalAnswer: "Inner \\( \\mathrm{Ai}(\\xi) \\) matches the outer \\( q^{-1/4} \\exp\\!\\left( -\\tfrac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{q} \\right) \\).",
    },
  },
  {
    id: "am10b-023",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 23",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Improve the large-zero estimate for \\( \\mathrm{Ai}(-a_{s}) = 0 \\) by including the next term of the oscillatory expansion. Using \\( \\mathrm{Ai}(-x) \\sim \\tfrac{1}{\\sqrt{\\pi}} x^{-1/4}[\\sin\\theta - \\tfrac{5}{48} x^{-3/2}\\cos\\theta] \\) with \\( \\theta = \\tfrac{2}{3} x^{3/2} + \\tfrac{\\pi}{4} \\), find the first correction to \\( \\theta_{s} = s\\pi \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["Airy zeros", "higher correction", "phase expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the bracket to zero.", workingLatex: "\\sin\\theta - \\frac{5}{48} x^{-3/2}\\cos\\theta = 0 \\;\\Longrightarrow\\; \\tan\\theta = \\frac{5}{48} x^{-3/2}.", explanation: "Divide through by \\( \\cos\\theta \\) (non-zero near a zero of \\( \\sin\\theta \\))." },
        { stepNumber: 2, description: "Solve for the small phase shift.", workingLatex: "\\theta = s\\pi + \\delta, \\qquad \\tan(s\\pi + \\delta) = \\tan\\delta \\approx \\delta = \\frac{5}{48} x^{-3/2}.", explanation: "Write \\( \\theta \\) as the leading zero \\( s\\pi \\) plus a small \\( \\delta \\)." },
        { stepNumber: 3, description: "Express the phase correction.", workingLatex: "\\frac{2}{3} a_{s}^{3/2} + \\frac{\\pi}{4} = s\\pi + \\frac{5}{48} a_{s}^{-3/2}.", explanation: "So the phase condition gains the small term \\( +\\tfrac{5}{48} a_{s}^{-3/2} \\)." },
        { stepNumber: 4, description: "Invert for \\( a_{s} \\).", workingLatex: "a_{s} = \\left[ \\frac{3\\pi}{8}(4s - 1) \\right]^{2/3}\\left[ 1 + \\frac{5}{48}\\,\\frac{a_{s}^{-3/2}}{(s - \\frac14)\\pi} + \\cdots \\right].", explanation: "Treating the right-hand correction perturbatively about the leading estimate; the bracketed factor is a small positive correction." },
        { stepNumber: 5, description: "Quantify at \\( s = 1 \\).", workingLatex: "a_{1}: \\quad \\frac{2}{3}a_{1}^{3/2} + \\frac{\\pi}{4} = \\pi + \\frac{5}{48}a_{1}^{-3/2}.", explanation: "Numerical check: solving this implicit relation gives \\( a_{1} = 2.3393 \\), much closer to the true \\( 2.33811 \\) than the leading estimate \\( 2.32025 \\)." },
        { stepNumber: 6, description: "State the corrected condition.", workingLatex: "\\frac{2}{3} a_{s}^{3/2} + \\frac{\\pi}{4} = s\\pi + \\frac{5}{48} a_{s}^{-3/2}.", explanation: "The correction decays like \\( a_{s}^{-3/2} \\), so the leading estimate is increasingly accurate for large \\( s \\)." },
      ],
      finalAnswer: "\\( \\dfrac{2}{3} a_{s}^{3/2} + \\dfrac{\\pi}{4} = s\\pi + \\dfrac{5}{48} a_{s}^{-3/2} \\).",
    },
  },
  {
    id: "am10b-024",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 24",
    difficulty: "Challenge",
    answerType: "numeric",
    examStyle: true,
    questionText: "Use the leading zero estimate \\( a_{s} \\approx [\\tfrac{3\\pi}{8}(4s - 1)]^{2/3} \\) to estimate the tenth zero \\( a_{10} \\) of \\( \\mathrm{Ai}(-x) \\) to 4 decimal places, and quote the percentage error against the true value \\( 12.82878 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["Airy zeros", "large index", "numerical accuracy"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( s = 10 \\).", workingLatex: "a_{10} \\approx \\left[ \\frac{3\\pi}{8}(40 - 1) \\right]^{2/3} = \\left[ \\frac{3\\pi}{8}\\cdot 39 \\right]^{2/3} = \\left[ 45.9458 \\right]^{2/3}.", explanation: "" },
        { stepNumber: 2, description: "Evaluate.", workingLatex: "(45.9458)^{2/3} = 12.8281.", explanation: "" },
        { stepNumber: 3, description: "Compare.", workingLatex: "\\text{error} = \\frac{12.82878 - 12.82814}{12.82878} \\approx 5\\times 10^{-5} = 0.005\\%.", explanation: "Numerical check (mpmath.airyaizero(10) = 12.82878): the leading phase estimate is accurate to four decimals by the tenth zero." },
      ],
      finalAnswer: "\\( a_{10} \\approx 12.8281 \\), error \\( \\approx 0.005\\% \\).",
      canonicalAnswer: "12.8281",
    },
  },
  {
    id: "am10b-025",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 25",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (x^{2} - 1)\\,y \\) there are turning points at \\( x = \\pm 1 \\). Near the simple turning point \\( x = 1 \\), find the appropriate local Airy variable \\( \\xi \\) (note \\( q'(1) = 2 \\)).",
    marks: 4,
    yearCreated: 2026,
    tags: ["turning point", "local rescaling", "multiple turning points"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Linearise \\( q \\) near \\( x = 1 \\).", workingLatex: "q(x) = x^{2} - 1 = (x - 1)(x + 1) \\approx 2(x - 1) \\quad \\text{near } x = 1.", explanation: "So \\( q'(1) = 2 \\); \\( x = 1 \\) is a simple turning point." },
        { stepNumber: 2, description: "Apply the standard local scale.", workingLatex: "\\xi = \\left( \\frac{q'(1)}{\\varepsilon^{2}} \\right)^{1/3}(x - 1) = \\left( \\frac{2}{\\varepsilon^{2}} \\right)^{1/3}(x - 1).", explanation: "" },
        { stepNumber: 3, description: "State the inner equation.", workingLatex: "W'' = \\xi\\, W, \\qquad W = \\mathrm{Ai}(\\xi)\\ \\text{or}\\ \\mathrm{Bi}(\\xi).", explanation: "The local problem at each simple turning point is Airy; the \\( 2^{1/3} \\) reflects the steeper slope \\( q'(1) = 2 \\)." },
      ],
      finalAnswer: "\\( \\xi = \\left( \\dfrac{2}{\\varepsilon^{2}} \\right)^{1/3}(x - 1) \\).",
      canonicalAnswer: "(2/eps^2)^{1/3} (x-1)",
    },
  },
  {
    id: "am10b-026",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 26",
    difficulty: "Challenge",
    answerType: "numeric",
    examStyle: true,
    questionText: "Compare the two-term Airy asymptotic with the leading term at \\( x = 2 \\): compute \\( \\tfrac{1}{2\\sqrt{\\pi}} x^{-1/4} e^{-\\frac{2}{3} x^{3/2}} \\) and its correction factor \\( (1 - \\tfrac{5}{48} x^{-3/2}) \\) at \\( x = 2 \\), and state which is closer to the true \\( \\mathrm{Ai}(2) = 0.0349241 \\). Give the corrected estimate to 4 decimal places (\\( \\times 10^{-2} \\)).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Airy function", "correction term", "numerical comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading factor.", workingLatex: "\\frac{2}{3}\\cdot 2^{3/2} = \\frac{2}{3}\\cdot 2.82843 = 1.88562, \\qquad e^{-1.88562} = 0.15183.", explanation: "" },
        { stepNumber: 2, description: "Prefactor and leading estimate.", workingLatex: "\\frac{1}{2\\sqrt{\\pi}}\\cdot 2^{-1/4} = 0.28209 \\cdot 0.84090 = 0.23719, \\qquad \\text{leading} = 0.23719\\times 0.15183 = 0.035993.", explanation: "Leading-only estimate \\( = 0.035993 \\)." },
        { stepNumber: 3, description: "Apply the correction.", workingLatex: "1 - \\frac{5}{48}\\cdot 2^{-3/2} = 1 - 0.10417\\cdot 0.35355 = 0.96317.", explanation: "" },
        { stepNumber: 4, description: "Corrected estimate.", workingLatex: "0.035993 \\times 0.96317 = 0.034668.", explanation: "Numerical check: true \\( \\mathrm{Ai}(2) = 0.0349241 \\); leading \\( 0.035993 \\) (error \\( 3.1\\% \\)); corrected \\( 0.034668 \\) (error \\( 0.7\\% \\)) — the two-term form is much closer." },
      ],
      finalAnswer: "Corrected \\( \\approx 3.4668\\times 10^{-2} \\) (true \\( 3.4924\\times 10^{-2} \\)); the two-term form is closer.",
      canonicalAnswer: "0.034668",
    },
  },
  {
    id: "am10b-027",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 27",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "A particle in a linear potential is governed by \\( -\\psi'' + x\\,\\psi = E\\,\\psi \\) on \\( x \\ge 0 \\) with \\( \\psi(0) = 0 \\) and \\( \\psi \\to 0 \\) as \\( x \\to +\\infty \\). Express the exact eigenfunctions in terms of \\( \\mathrm{Ai} \\), and give the quantisation condition for \\( E \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Airy equation", "eigenvalue", "linear potential"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Shift to Airy form.", workingLatex: "\\psi'' = (x - E)\\,\\psi, \\qquad u = x - E \\;\\Longrightarrow\\; \\psi'' = u\\,\\psi.", explanation: "The turning point sits at \\( x = E \\) (where the linear potential equals the energy)." },
        { stepNumber: 2, description: "Pick the decaying solution.", workingLatex: "\\psi(x) = c\\,\\mathrm{Ai}(x - E).", explanation: "\\( \\mathrm{Ai} \\) is the unique (up to scale) solution decaying as \\( u \\to +\\infty \\); \\( \\mathrm{Bi} \\) would grow." },
        { stepNumber: 3, description: "Impose \\( \\psi(0) = 0 \\).", workingLatex: "\\mathrm{Ai}(-E) = 0.", explanation: "The hard wall at \\( x = 0 \\) forces a zero of \\( \\mathrm{Ai} \\)." },
        { stepNumber: 4, description: "Quantise.", workingLatex: "E_{s} = a_{s}, \\qquad \\mathrm{Ai}(-a_{s}) = 0 \\;\\Longrightarrow\\; E_{s} \\sim \\left[ \\frac{3\\pi}{8}(4s - 1) \\right]^{2/3}.", explanation: "Numerical check: lowest energy \\( E_{1} = a_{1} = 2.33811 \\); leading estimate \\( 2.32025 \\). The energies are exactly the (negative-axis) zeros of \\( \\mathrm{Ai} \\)." },
      ],
      finalAnswer: "\\( \\psi_{s}(x) = c\\,\\mathrm{Ai}(x - E_{s}) \\) with \\( \\mathrm{Ai}(-E_{s}) = 0 \\), i.e. \\( E_{s} \\sim [\\tfrac{3\\pi}{8}(4s - 1)]^{2/3} \\).",
    },
  },
  {
    id: "am10b-028",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 28",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "From the relation \\( \\mathrm{Ai}(-x) \\sim \\tfrac{1}{\\sqrt{\\pi}} x^{-1/4} \\sin(\\tfrac{2}{3} x^{3/2} + \\tfrac{\\pi}{4}) \\), find the leading-order spacing \\( a_{s+1} - a_{s} \\) between consecutive large zeros of \\( \\mathrm{Ai}(-x) \\) as \\( s \\to \\infty \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Airy zeros", "zero spacing", "asymptotics"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase condition.", workingLatex: "\\frac{2}{3} a_{s}^{3/2} = \\left( s - \\frac14 \\right)\\pi \\;\\Longrightarrow\\; a_{s}^{3/2} = \\frac{3\\pi}{2}\\left( s - \\frac14 \\right).", explanation: "Consecutive zeros increase the phase by \\( \\pi \\), i.e. \\( s \\to s + 1 \\)." },
        { stepNumber: 2, description: "Take the increment in \\( s \\).", workingLatex: "\\Delta\\!\\left( a^{3/2} \\right) = \\frac{3\\pi}{2}, \\qquad \\frac{d}{da}\\,a^{3/2} = \\frac{3}{2} a^{1/2}.", explanation: "Use the differential approximation for the slowly-varying spacing." },
        { stepNumber: 3, description: "Solve for the spacing.", workingLatex: "\\frac{3}{2} a_{s}^{1/2}\\,(a_{s+1} - a_{s}) \\approx \\frac{3\\pi}{2} \\;\\Longrightarrow\\; a_{s+1} - a_{s} \\sim \\frac{\\pi}{\\sqrt{a_{s}}}.", explanation: "Numerical check: \\( a_{9} = 11.93602,\\ a_{10} = 12.82878 \\), so \\( \\Delta = 0.89276 \\); evaluating \\( \\pi/\\sqrt{a} \\) at the midpoint \\( a \\approx 12.38 \\) gives \\( 0.89279 \\). At larger \\( s \\): \\( a_{50} - a_{49} = 0.51121 \\) vs \\( \\pi/\\sqrt{a_{50}} = 0.50949 \\) — the spacing shrinks like \\( a^{-1/2} \\) as predicted." },
      ],
      finalAnswer: "\\( a_{s+1} - a_{s} \\sim \\dfrac{\\pi}{\\sqrt{a_{s}}} \\) as \\( s \\to \\infty \\).",
      canonicalAnswer: "pi/sqrt(a_s)",
    },
  },
  {
    id: "am10b-029",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 29",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Two simple turning points bound a classically allowed well in \\( \\varepsilon^{2} y'' = q(x)\\,y \\) (with \\( q < 0 \\) between \\( x = a \\) and \\( x = b \\), \\( q > 0 \\) outside). Applying the \\( -\\tfrac{\\pi}{4} \\) connection at each end, derive the Bohr–Sommerfeld quantisation condition.",
    marks: 6,
    yearCreated: 2026,
    tags: ["Bohr-Sommerfeld", "two turning points", "quantisation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Decaying solution to the right of \\( b \\), connected inward.", workingLatex: "y \\sim \\frac{2}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon}\\int_{x}^{b}\\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right).", explanation: "Decaying as \\( x \\to +\\infty \\) past \\( b \\), the connection gives a cosine with phase measured from \\( b \\) and deficit \\( -\\tfrac{\\pi}{4} \\)." },
        { stepNumber: 2, description: "Decaying solution to the left of \\( a \\), connected inward.", workingLatex: "y \\sim \\frac{2}{(-q)^{1/4}} \\cos\\!\\left( \\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{-q}\\; dt - \\frac{\\pi}{4} \\right).", explanation: "By symmetry, decaying as \\( x \\to -\\infty \\) gives a cosine with phase from \\( a \\) and its own \\( -\\tfrac{\\pi}{4} \\)." },
        { stepNumber: 3, description: "Require the two interior forms to coincide.", workingLatex: "\\frac{1}{\\varepsilon}\\int_{a}^{x}\\sqrt{-q} - \\frac{\\pi}{4} + \\frac{1}{\\varepsilon}\\int_{x}^{b}\\sqrt{-q} - \\frac{\\pi}{4} = n\\pi.", explanation: "The two cosines describe the same wave only if their phases sum to an integer multiple of \\( \\pi \\); the total phase across the well is the sum of the two partial integrals." },
        { stepNumber: 4, description: "Add the integrals.", workingLatex: "\\frac{1}{\\varepsilon}\\int_{a}^{b}\\sqrt{-q}\\; dt - \\frac{\\pi}{2} = n\\pi.", explanation: "The two partial phase integrals combine into the full well integral; the two \\( -\\tfrac{\\pi}{4} \\) shifts sum to \\( -\\tfrac{\\pi}{2} \\)." },
        { stepNumber: 5, description: "State the quantisation condition.", workingLatex: "\\frac{1}{\\varepsilon}\\int_{a}^{b}\\sqrt{-q}\\; dt = \\left( n + \\frac12 \\right)\\pi, \\qquad n = 0, 1, 2, \\dots", explanation: "The two end-point phase losses combine into the familiar \\( +\\tfrac12 \\) Maslov index — the hallmark of two simple turning points." },
      ],
      finalAnswer: "\\( \\dfrac{1}{\\varepsilon}\\displaystyle\\int_{a}^{b}\\sqrt{-q}\\; dt = \\left( n + \\tfrac12 \\right)\\pi \\), \\( n = 0, 1, 2, \\dots \\).",
    },
  },
  {
    id: "am10b-030",
    topicRef: "am10b",
    topicTitle: "Airy asymptotics, turning points & connection formulae 30",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Apply the Bohr–Sommerfeld condition \\( \\tfrac{1}{\\varepsilon}\\int_{a}^{b}\\sqrt{-q}\\,dt = (n + \\tfrac12)\\pi \\) to the harmonic-oscillator-type problem \\( \\varepsilon^{2} y'' = (x^{2} - E)\\,y \\) (turning points \\( x = \\pm\\sqrt{E} \\)), and find the quantised energies \\( E_{n} \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["Bohr-Sommerfeld", "harmonic oscillator", "quantisation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the allowed region and integrand.", workingLatex: "q = x^{2} - E < 0 \\ \\text{for}\\ |x| < \\sqrt{E}, \\qquad \\sqrt{-q} = \\sqrt{E - x^{2}}.", explanation: "Turning points at \\( x = \\pm\\sqrt{E} \\); the classically allowed region is \\( |x| < \\sqrt{E} \\)." },
        { stepNumber: 2, description: "Evaluate the phase integral.", workingLatex: "\\int_{-\\sqrt{E}}^{\\sqrt{E}} \\sqrt{E - x^{2}}\\; dx = \\frac{\\pi E}{2}.", explanation: "This is the area of a semicircle of radius \\( \\sqrt{E} \\): \\( \\tfrac{1}{2}\\pi(\\sqrt{E})^{2} = \\tfrac{\\pi E}{2} \\)." },
        { stepNumber: 3, description: "Insert into the quantisation condition.", workingLatex: "\\frac{1}{\\varepsilon}\\cdot \\frac{\\pi E}{2} = \\left( n + \\frac12 \\right)\\pi.", explanation: "" },
        { stepNumber: 4, description: "Solve for \\( E_{n} \\).", workingLatex: "E_{n} = 2\\varepsilon\\left( n + \\frac12 \\right) = (2n + 1)\\,\\varepsilon, \\qquad n = 0, 1, 2, \\dots", explanation: "The WKB energies are exactly the harmonic-oscillator levels \\( (2n+1)\\varepsilon \\); for the quadratic potential the leading-order WKB result is in fact exact, a well-known feature." },
        { stepNumber: 5, description: "State the spectrum.", workingLatex: "E_{n} = (2n + 1)\\,\\varepsilon.", explanation: "The \\( +\\tfrac12 \\) ground-state offset is the direct fingerprint of the two \\( -\\tfrac{\\pi}{4} \\) turning-point phases." },
      ],
      finalAnswer: "\\( E_{n} = (2n + 1)\\,\\varepsilon \\), \\( n = 0, 1, 2, \\dots \\).",
      canonicalAnswer: "(2n+1) eps",
    },
  },
];
