import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Liouville–Green & WKB
 * Subtopic am10a: The Liouville–Green expansion (S₀, S₁, S₂)
 * 30 fully-worked questions (6 Foundation / 12 Standard / 12 Challenge).
 *
 * Theme: the Liouville–Green (WKB) ansatz y = exp((1/ε)Σ εⁿ Sₙ) for ε²y''=q(x)y,
 * the recursive hierarchy ((S0')²=q, 2S0'S1'+S0''=0, 2S0'S2'+(S1')²+S1''=0, …),
 * the q^{-1/4} prefactor, and the slow-variation validity condition that fails at
 * turning points (zeros of q).
 *
 * Numerical spot-checks (mpmath/sympy/scipy) were run for every ∫√q, every
 * S1/S2 derivation, and the applied two-term LG expansions were compared against
 * direct numerical integration of the ODE; cases not numerically checkable carry
 * a // REVIEW comment.
 */
export const questions: Question[] = [
  // ───────────────────────── FOUNDATION (6) ─────────────────────────
  {
    id: "am10a-001",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( \\varepsilon^{2} y'' = q(x)\\, y \\) substitute the Liouville–Green ansatz \\( y = \\exp\\!\\left(\\dfrac{1}{\\varepsilon} S(x)\\right) \\) and show that the equation becomes \\( (S')^{2} + \\varepsilon S'' = q \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Liouville–Green ansatz", "exponential substitution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the ansatz.", workingLatex: "y = \\exp\\!\\left(\\frac{S}{\\varepsilon}\\right), \\qquad y' = \\frac{S'}{\\varepsilon}\\, y, \\qquad y'' = \\left(\\frac{(S')^{2}}{\\varepsilon^{2}} + \\frac{S''}{\\varepsilon}\\right) y.", explanation: "" },
        { stepNumber: 2, description: "Insert into the ODE and divide by \\( y \\).", workingLatex: "\\varepsilon^{2}\\left(\\frac{(S')^{2}}{\\varepsilon^{2}} + \\frac{S''}{\\varepsilon}\\right) y = q\\, y \\;\\Longrightarrow\\; (S')^{2} + \\varepsilon S'' = q.", explanation: "" },
      ],
      finalAnswer: "\\( (S')^{2} + \\varepsilon S'' = q \\).",
      canonicalAnswer: "(S')^2 + eps*S'' = q",
    },
  },
  {
    id: "am10a-002",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "From \\( (S')^{2} + \\varepsilon S'' = q \\), with \\( S = S_{0} + \\varepsilon S_{1} + \\cdots \\), write down the leading-order equation and hence give \\( S_{0} \\) as an integral.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order eikonal", "S0 integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Collect the \\( O(1) \\) terms.", workingLatex: "(S_{0}')^{2} = q.", explanation: "The \\( \\varepsilon S'' \\) term is \\( O(\\varepsilon) \\) and drops out at leading order." },
        { stepNumber: 2, description: "Solve and integrate.", workingLatex: "S_{0}' = \\pm \\sqrt{q} \\;\\Longrightarrow\\; S_{0} = \\pm \\int \\sqrt{q}\\; dx.", explanation: "Both signs are kept; they give the two independent LG solutions." },
      ],
      finalAnswer: "\\( S_{0} = \\pm \\displaystyle\\int \\sqrt{q}\\; dx \\), from \\( (S_{0}')^{2} = q \\).",
      canonicalAnswer: "S0 = +-int sqrt(q) dx",
    },
  },
  {
    id: "am10a-003",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the equation \\( \\varepsilon^{2} y'' = (1 + x^{2})\\, y \\), compute \\( S_{0} = \\displaystyle\\int \\sqrt{q}\\; dx \\) (take the \\( + \\) sign, constant of integration omitted).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["S0 integral", "exponential case"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify \\( q \\).", workingLatex: "q(x) = 1 + x^{2} > 0.", explanation: "" },
        { stepNumber: 2, description: "Integrate \\( \\sqrt{q} \\).", workingLatex: "S_{0} = \\int \\sqrt{1 + x^{2}}\\; dx = \\frac{x\\sqrt{1+x^{2}}}{2} + \\frac{1}{2}\\sinh^{-1} x.", explanation: "Standard integral; verified with sympy." },
      ],
      finalAnswer: "\\( S_{0} = \\dfrac{x\\sqrt{1+x^{2}}}{2} + \\dfrac{1}{2}\\sinh^{-1} x \\).",
      canonicalAnswer: "x*sqrt(1+x^2)/2 + asinh(x)/2",
    },
  },
  {
    id: "am10a-004",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve the order-\\( \\varepsilon \\) equation \\( 2 S_{0}' S_{1}' + S_{0}'' = 0 \\) for \\( S_{1}' \\) in terms of \\( q \\), and hence write \\( S_{1} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["transport equation", "S1 = -1/4 ln q"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Solve for \\( S_{1}' \\) using \\( S_{0}'=\\sqrt{q} \\).", workingLatex: "S_{1}' = -\\frac{S_{0}''}{2 S_{0}'} = -\\frac{q'/(2\\sqrt{q})}{2\\sqrt{q}} = -\\frac{q'}{4q}.", explanation: "Here \\( S_{0}'' = \\dfrac{d}{dx}\\sqrt{q} = \\dfrac{q'}{2\\sqrt{q}} \\); the sign of \\( S_{0}' \\) cancels, so \\( S_{1} \\) is the same for both branches." },
        { stepNumber: 2, description: "Integrate.", workingLatex: "S_{1} = -\\frac{1}{4}\\ln q \\; (+\\,\\text{const}).", explanation: "" },
      ],
      finalAnswer: "\\( S_{1}' = -\\dfrac{q'}{4q}, \\quad S_{1} = -\\dfrac{1}{4}\\ln q \\).",
      canonicalAnswer: "S1 = -(1/4) ln q",
    },
  },
  {
    id: "am10a-005",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using \\( S_{0} = \\pm\\displaystyle\\int\\sqrt{q}\\,dx \\) and \\( S_{1} = -\\tfrac14 \\ln q \\), write down the leading Liouville–Green approximation to \\( y \\) for \\( q(x) > 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["q^{-1/4} prefactor", "leading LG form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Assemble \\( y = \\exp(S_{0}/\\varepsilon + S_{1}) \\).", workingLatex: "y \\sim \\exp\\!\\left(\\pm\\frac{1}{\\varepsilon}\\int\\sqrt{q}\\,dx\\right)\\, e^{-\\frac14 \\ln q}.", explanation: "" },
        { stepNumber: 2, description: "Simplify the prefactor.", workingLatex: "e^{-\\frac14 \\ln q} = q^{-1/4} \\;\\Longrightarrow\\; y \\sim q^{-1/4}\\exp\\!\\left(\\pm\\frac{1}{\\varepsilon}\\int\\sqrt{q}\\,dx\\right).", explanation: "The \\( q^{-1/4} \\) amplitude is the hallmark of the LG approximation." },
      ],
      finalAnswer: "\\( y \\sim q^{-1/4}\\exp\\!\\left(\\pm\\dfrac{1}{\\varepsilon}\\displaystyle\\int\\sqrt{q}\\,dx\\right) \\).",
      canonicalAnswer: "q^(-1/4) exp(+- (1/eps) int sqrt(q) dx)",
    },
  },
  {
    id: "am10a-006",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The Liouville–Green prefactor is \\( q^{-1/4} \\). At what points of the \\( x \\)-axis does this break down, and what is such a point called?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["turning point", "breakdown of LG"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the singularity of the prefactor.", workingLatex: "q^{-1/4} \\to \\infty \\quad \\text{as} \\quad q(x) \\to 0.", explanation: "" },
        { stepNumber: 2, description: "Name the failure point.", workingLatex: "q(x_{*}) = 0 \\;\\Longrightarrow\\; x_{*} \\text{ is a turning point.}", explanation: "There \\( S_{0}'=\\sqrt{q}=0 \\), the two LG branches merge, and the expansion is invalid; an Airy-type inner solution is needed instead." },
      ],
      finalAnswer: "\\( y \\) breaks down where \\( q(x_{*}) = 0 \\); \\( x_{*} \\) is a turning point.",
      canonicalAnswer: "zeros of q (turning points)",
    },
  },

  // ───────────────────────── STANDARD (12) ─────────────────────────
  {
    id: "am10a-007",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 07",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Substitute \\( y = \\exp\\!\\big(\\tfrac{1}{\\varepsilon}(S_{0} + \\varepsilon S_{1} + \\varepsilon^{2} S_{2} + \\cdots)\\big) \\) into \\( \\varepsilon^{2} y'' = q\\, y \\) and derive the first three equations of the Liouville–Green hierarchy.",
    marks: 4,
    yearCreated: 2026,
    tags: ["LG hierarchy", "order-by-order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduce the ODE to the Riccati form.", workingLatex: "(S')^{2} + \\varepsilon S'' = q, \\qquad S = S_{0} + \\varepsilon S_{1} + \\varepsilon^{2} S_{2} + \\cdots", explanation: "From \\( y''/y = (S'/\\varepsilon)^{2} + S''/\\varepsilon \\) times \\( \\varepsilon^{2} \\)." },
        { stepNumber: 2, description: "Expand \\( (S')^{2} \\) to \\( O(\\varepsilon^{2}) \\).", workingLatex: "(S')^{2} = (S_{0}')^{2} + 2\\varepsilon S_{0}'S_{1}' + \\varepsilon^{2}\\big((S_{1}')^{2} + 2 S_{0}'S_{2}'\\big) + \\cdots", explanation: "" },
        { stepNumber: 3, description: "Add \\( \\varepsilon S'' = \\varepsilon S_{0}'' + \\varepsilon^{2} S_{1}'' + \\cdots \\) and match orders.", workingLatex: "\\varepsilon^{0}:\\ (S_{0}')^{2} = q, \\quad \\varepsilon^{1}:\\ 2 S_{0}'S_{1}' + S_{0}'' = 0, \\quad \\varepsilon^{2}:\\ 2 S_{0}'S_{2}' + (S_{1}')^{2} + S_{1}'' = 0.", explanation: "Verified symbolically in sympy." },
      ],
      finalAnswer: "\\( (S_{0}')^{2}=q,\\ \\ 2S_{0}'S_{1}'+S_{0}''=0,\\ \\ 2S_{0}'S_{2}'+(S_{1}')^{2}+S_{1}''=0 \\).",
    },
  },
  {
    id: "am10a-008",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 08",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (1 + x)\\, y \\), find the two-term Liouville–Green approximation \\( y \\sim q^{-1/4}\\exp\\!\\big(\\pm\\tfrac{1}{\\varepsilon}\\int\\sqrt{q}\\,dx\\big) \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["applied ODE", "leading LG"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute \\( S_{0} \\).", workingLatex: "S_{0} = \\pm\\int \\sqrt{1+x}\\,dx = \\pm\\frac{2}{3}(1+x)^{3/2}.", explanation: "" },
        { stepNumber: 2, description: "Prefactor from \\( S_{1} \\).", workingLatex: "q^{-1/4} = (1+x)^{-1/4}.", explanation: "" },
        { stepNumber: 3, description: "Assemble.", workingLatex: "y \\sim (1+x)^{-1/4}\\exp\\!\\left(\\pm\\frac{2}{3\\varepsilon}(1+x)^{3/2}\\right).", explanation: "" },
      ],
      finalAnswer: "\\( y \\sim (1+x)^{-1/4}\\exp\\!\\left(\\pm\\dfrac{2}{3\\varepsilon}(1+x)^{3/2}\\right) \\).",
      canonicalAnswer: "(1+x)^(-1/4) exp(+- (2/(3eps)) (1+x)^(3/2))",
    },
  },
  {
    id: "am10a-009",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 09",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = e^{x}\\, y \\), find the two-term Liouville–Green approximation to \\( y \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["applied ODE", "leading LG"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute \\( S_{0} \\).", workingLatex: "S_{0} = \\pm\\int \\sqrt{e^{x}}\\,dx = \\pm\\int e^{x/2}\\,dx = \\pm 2 e^{x/2}.", explanation: "" },
        { stepNumber: 2, description: "Prefactor.", workingLatex: "q^{-1/4} = (e^{x})^{-1/4} = e^{-x/4}.", explanation: "" },
        { stepNumber: 3, description: "Assemble.", workingLatex: "y \\sim e^{-x/4}\\exp\\!\\left(\\pm\\frac{2}{\\varepsilon} e^{x/2}\\right).", explanation: "Numerical check (scipy, ε=0.02): growing branch matches the ODE solution to ~0.05%." },
      ],
      finalAnswer: "\\( y \\sim e^{-x/4}\\exp\\!\\left(\\pm\\dfrac{2}{\\varepsilon}\\, e^{x/2}\\right) \\).",
      canonicalAnswer: "exp(-x/4) exp(+- (2/eps) exp(x/2))",
    },
  },
  {
    id: "am10a-010",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 10",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = -(1 + x^{2})\\, y \\) (so \\( q < 0 \\)), write the leading oscillatory Liouville–Green solution. Put \\( q = -p \\) with \\( p = 1 + x^{2} > 0 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["oscillatory case", "q<0", "WKB"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set \\( q = -p \\), so \\( S_{0}' = \\pm i\\sqrt{p} \\).", workingLatex: "(S_{0}')^{2} = q = -p \\;\\Longrightarrow\\; S_{0} = \\pm i\\int\\sqrt{p}\\,dx.", explanation: "A negative \\( q \\) gives an imaginary eikonal, hence oscillation rather than growth." },
        { stepNumber: 2, description: "Prefactor.", workingLatex: "q^{-1/4} = (-p)^{-1/4} \\;\\Rightarrow\\; |y| \\propto p^{-1/4}.", explanation: "The real amplitude is \\( p^{-1/4} \\) up to a constant phase." },
        { stepNumber: 3, description: "Take real combinations.", workingLatex: "y \\sim p^{-1/4}\\left[A\\cos\\!\\left(\\frac{1}{\\varepsilon}\\int\\sqrt{p}\\,dx\\right) + B\\sin\\!\\left(\\frac{1}{\\varepsilon}\\int\\sqrt{p}\\,dx\\right)\\right].", explanation: "" },
        { stepNumber: 4, description: "Insert \\( \\int\\sqrt{p}\\,dx \\).", workingLatex: "\\int\\sqrt{1+x^{2}}\\,dx = \\frac{x\\sqrt{1+x^{2}}}{2} + \\frac{1}{2}\\sinh^{-1} x.", explanation: "Numerical check (scipy, ε=0.02): \\( p^{-1/4}\\cos((1/\\varepsilon)\\int\\sqrt p) \\) tracks the ODE solution closely." },
      ],
      finalAnswer: "\\( y \\sim (1+x^{2})^{-1/4}\\big[A\\cos\\Phi + B\\sin\\Phi\\big],\\ \\Phi=\\dfrac{1}{\\varepsilon}\\displaystyle\\int\\sqrt{1+x^{2}}\\,dx \\).",
    },
  },
  {
    id: "am10a-011",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 11",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Derive the general formula \\( S_{2}' = -\\dfrac{(S_{1}')^{2} + S_{1}''}{2 S_{0}'} \\), and hence show \\( S_{2}' = \\dfrac{4 q q'' - 5(q')^{2}}{32\\, q^{5/2}} \\) for the \\( + \\) branch.",
    marks: 4,
    yearCreated: 2026,
    tags: ["S2 correction", "closed form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Solve the \\( O(\\varepsilon^{2}) \\) equation.", workingLatex: "2 S_{0}'S_{2}' + (S_{1}')^{2} + S_{1}'' = 0 \\;\\Longrightarrow\\; S_{2}' = -\\frac{(S_{1}')^{2} + S_{1}''}{2 S_{0}'}.", explanation: "" },
        { stepNumber: 2, description: "Substitute \\( S_{1}' = -q'/(4q) \\) and \\( S_{0}'=\\sqrt{q} \\).", workingLatex: "S_{1}'' = -\\frac{q''}{4q} + \\frac{(q')^{2}}{4q^{2}}, \\qquad (S_{1}')^{2} = \\frac{(q')^{2}}{16 q^{2}}.", explanation: "" },
        { stepNumber: 3, description: "Combine over \\( 2\\sqrt{q} \\).", workingLatex: "S_{2}' = -\\frac{1}{2\\sqrt q}\\left(\\frac{(q')^{2}}{16q^{2}} - \\frac{q''}{4q} + \\frac{(q')^{2}}{4q^{2}}\\right) = \\frac{4 q q'' - 5(q')^{2}}{32\\, q^{5/2}}.", explanation: "Verified symbolically in sympy." },
      ],
      finalAnswer: "\\( S_{2}' = \\dfrac{4 q q'' - 5(q')^{2}}{32\\, q^{5/2}} \\).",
      canonicalAnswer: "(4 q q'' - 5 (q')^2)/(32 q^(5/2))",
    },
  },
  {
    id: "am10a-012",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 12",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( q(x) = e^{x} \\), use \\( S_{2}' = \\dfrac{4qq''-5(q')^{2}}{32 q^{5/2}} \\) to find \\( S_{2}' \\) and \\( S_{2} \\) (constant omitted).",
    marks: 3,
    yearCreated: 2026,
    tags: ["S2 correction", "applied"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the derivatives.", workingLatex: "q = e^{x}, \\quad q' = e^{x}, \\quad q'' = e^{x}.", explanation: "" },
        { stepNumber: 2, description: "Substitute.", workingLatex: "S_{2}' = \\frac{4 e^{2x} - 5 e^{2x}}{32\\, e^{5x/2}} = \\frac{-e^{2x}}{32\\, e^{5x/2}} = -\\frac{1}{32} e^{-x/2}.", explanation: "" },
        { stepNumber: 3, description: "Integrate.", workingLatex: "S_{2} = -\\frac{1}{32}\\int e^{-x/2}\\,dx = \\frac{1}{16} e^{-x/2}.", explanation: "" },
      ],
      finalAnswer: "\\( S_{2}' = -\\dfrac{1}{32} e^{-x/2}, \\quad S_{2} = \\dfrac{1}{16} e^{-x/2} \\).",
      canonicalAnswer: "S2 = (1/16) exp(-x/2)",
    },
  },
  {
    id: "am10a-013",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 13",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( q(x) = x^{2} \\) on \\( x > 0 \\) (so \\( \\varepsilon^{2} y'' = x^{2} y \\)), find \\( S_{0} \\), \\( S_{1} \\) and the leading LG approximation to \\( y \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["applied ODE", "leading LG"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute \\( S_{0} \\) (use \\( \\sqrt{x^{2}}=x \\) for \\( x>0 \\)).", workingLatex: "S_{0} = \\pm\\int x\\,dx = \\pm\\frac{x^{2}}{2}.", explanation: "" },
        { stepNumber: 2, description: "Compute \\( S_{1} \\).", workingLatex: "S_{1} = -\\frac{1}{4}\\ln q = -\\frac{1}{4}\\ln x^{2} = -\\frac{1}{2}\\ln x \\;\\Rightarrow\\; q^{-1/4} = x^{-1/2}.", explanation: "" },
        { stepNumber: 3, description: "Assemble.", workingLatex: "y \\sim x^{-1/2}\\exp\\!\\left(\\pm\\frac{x^{2}}{2\\varepsilon}\\right).", explanation: "Valid for \\( x>0 \\) bounded away from the turning point at \\( x=0 \\)." },
      ],
      finalAnswer: "\\( y \\sim x^{-1/2}\\exp\\!\\left(\\pm\\dfrac{x^{2}}{2\\varepsilon}\\right) \\).",
      canonicalAnswer: "x^(-1/2) exp(+- x^2/(2eps))",
    },
  },
  {
    id: "am10a-014",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 14",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "The Liouville–Green expansion orders as \\( S_{0} \\gg \\varepsilon S_{1} \\gg \\varepsilon^{2} S_{2} \\). Show that the validity of the leading term requires \\( \\varepsilon \\left| \\dfrac{q'}{q^{3/2}} \\right| \\ll 1 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["validity condition", "slow variation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compare the two phase contributions \\( S_{0}'/\\varepsilon \\) and \\( S_{1}' \\).", workingLatex: "\\frac{S_{0}'}{\\varepsilon} = \\frac{\\sqrt{q}}{\\varepsilon}, \\qquad S_{1}' = -\\frac{q'}{4q}.", explanation: "These are the leading and next contributions to \\( (\\ln y)' \\)." },
        { stepNumber: 2, description: "Require \\( S_{1}' \\) to be subdominant.", workingLatex: "\\left| S_{1}' \\right| \\ll \\left| \\frac{S_{0}'}{\\varepsilon} \\right| \\;\\Longrightarrow\\; \\frac{|q'|}{4q} \\ll \\frac{\\sqrt{q}}{\\varepsilon}.", explanation: "" },
        { stepNumber: 3, description: "Rearrange.", workingLatex: "\\varepsilon\\,\\frac{|q'|}{q\\sqrt{q}} \\ll 1 \\;\\Longrightarrow\\; \\varepsilon\\left| \\frac{q'}{q^{3/2}} \\right| \\ll 1.", explanation: "So \\( q \\) must vary slowly and stay away from zero; the condition fails as \\( q\\to0 \\)." },
      ],
      finalAnswer: "\\( \\varepsilon\\left| \\dfrac{q'}{q^{3/2}} \\right| \\ll 1 \\).",
      canonicalAnswer: "eps*|q'/q^(3/2)| << 1",
    },
  },
  {
    id: "am10a-015",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 15",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = x\\, y \\) (\\( x > 0 \\)), compute the validity quantity \\( \\varepsilon\\left|q'/q^{3/2}\\right| \\) and deduce how close to the turning point \\( x=0 \\) the LG approximation remains valid.",
    marks: 4,
    yearCreated: 2026,
    tags: ["turning point", "breakdown scale"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Evaluate the quantity for \\( q=x \\).", workingLatex: "q = x,\\ q' = 1: \\qquad \\varepsilon\\left| \\frac{q'}{q^{3/2}} \\right| = \\frac{\\varepsilon}{x^{3/2}}.", explanation: "" },
        { stepNumber: 2, description: "Impose validity.", workingLatex: "\\frac{\\varepsilon}{x^{3/2}} \\ll 1 \\;\\Longrightarrow\\; x \\gg \\varepsilon^{2/3}.", explanation: "" },
        { stepNumber: 3, description: "Interpret.", workingLatex: "x_{\\text{break}} = O(\\varepsilon^{2/3}).", explanation: "LG holds for \\( x \\gg \\varepsilon^{2/3} \\); within an \\( O(\\varepsilon^{2/3}) \\) layer of the turning point it fails and an Airy inner solution is required." },
      ],
      finalAnswer: "Valid for \\( x \\gg \\varepsilon^{2/3} \\); LG breaks down in an \\( O(\\varepsilon^{2/3}) \\) layer about \\( x=0 \\).",
      canonicalAnswer: "x >> eps^(2/3)",
    },
  },
  {
    id: "am10a-016",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (1+x)\\, y \\), use \\( S_{2}' = \\dfrac{4qq''-5(q')^{2}}{32 q^{5/2}} \\) to find \\( S_{2} \\) (constant omitted).",
    marks: 3,
    yearCreated: 2026,
    tags: ["S2 correction", "applied"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Derivatives.", workingLatex: "q = 1+x, \\quad q' = 1, \\quad q'' = 0.", explanation: "" },
        { stepNumber: 2, description: "Substitute.", workingLatex: "S_{2}' = \\frac{0 - 5(1)^{2}}{32 (1+x)^{5/2}} = -\\frac{5}{32 (1+x)^{5/2}}.", explanation: "" },
        { stepNumber: 3, description: "Integrate.", workingLatex: "S_{2} = -\\frac{5}{32}\\int (1+x)^{-5/2}\\,dx = \\frac{5}{48}(1+x)^{-3/2}.", explanation: "Verified with sympy." },
      ],
      finalAnswer: "\\( S_{2} = \\dfrac{5}{48}(1+x)^{-3/2} \\).",
      canonicalAnswer: "S2 = (5/48)(1+x)^(-3/2)",
    },
  },
  {
    id: "am10a-017",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 17",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Show that for constant \\( q = k > 0 \\) the Liouville–Green series terminates: find \\( S_{0}, S_{1}, S_{2} \\) and confirm the LG form is exact.",
    marks: 3,
    yearCreated: 2026,
    tags: ["constant q", "exactness", "series termination"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the first terms.", workingLatex: "S_{0} = \\pm\\sqrt{k}\\,x, \\qquad S_{1} = -\\frac{1}{4}\\ln k\\ (\\text{const}).", explanation: "" },
        { stepNumber: 2, description: "Compute \\( S_{2} \\) and beyond.", workingLatex: "q' = q'' = 0 \\;\\Longrightarrow\\; S_{2}' = \\frac{0-0}{32 k^{5/2}} = 0 \\;\\Rightarrow\\; S_{n} = \\text{const for } n\\ge 1.", explanation: "" },
        { stepNumber: 3, description: "Assemble and compare with the exact solution.", workingLatex: "y \\sim k^{-1/4}\\exp\\!\\left(\\pm\\frac{\\sqrt{k}}{\\varepsilon}x\\right), \\qquad \\varepsilon^{2}y''=ky \\Rightarrow y = e^{\\pm\\sqrt{k}x/\\varepsilon}.", explanation: "The LG amplitude is constant and the exponent is exact, so LG is the exact solution up to normalisation." },
      ],
      finalAnswer: "\\( S_{0}=\\pm\\sqrt{k}\\,x,\\ S_{1}=-\\tfrac14\\ln k,\\ S_{2}=0 \\); LG is exact.",
    },
  },
  {
    id: "am10a-018",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 18",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Explain why \\( S_{1} = -\\tfrac14 \\ln q \\) is the same for both choices of sign in \\( S_{0}' = \\pm\\sqrt{q} \\), and state the consequence for the prefactor of the two LG solutions.",
    marks: 3,
    yearCreated: 2026,
    tags: ["sign of S0", "prefactor", "structure"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write \\( S_{1}' \\) for either sign.", workingLatex: "S_{1}' = -\\frac{S_{0}''}{2 S_{0}'} = -\\frac{(\\pm\\sqrt q)'}{2(\\pm\\sqrt q)} = -\\frac{\\pm q'/(2\\sqrt q)}{\\pm 2\\sqrt q}.", explanation: "" },
        { stepNumber: 2, description: "Cancel the common sign.", workingLatex: "S_{1}' = -\\frac{q'}{4q} \\quad \\text{(sign-independent)} \\;\\Longrightarrow\\; S_{1} = -\\frac14\\ln q.", explanation: "The \\( \\pm \\) cancels between numerator and denominator." },
        { stepNumber: 3, description: "Consequence.", workingLatex: "y_{\\pm} \\sim q^{-1/4}\\exp\\!\\left(\\pm\\frac{1}{\\varepsilon}\\int\\sqrt q\\,dx\\right).", explanation: "Both independent solutions share the same \\( q^{-1/4} \\) amplitude; only the sign of the exponent differs." },
      ],
      finalAnswer: "Both solutions share the prefactor \\( q^{-1/4} \\); only the exponent sign differs.",
      canonicalAnswer: "S1 = -(1/4) ln q for both signs",
    },
  },

  // ───────────────────────── CHALLENGE (12) ─────────────────────────
  {
    id: "am10a-019",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 19",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (1 + x^{2})\\, y \\), compute the three-term Liouville–Green exponent \\( \\tfrac{1}{\\varepsilon}S_{0} + S_{1} + \\varepsilon S_{2} \\), giving \\( S_{0} \\), \\( S_{1} \\) and \\( S_{2} \\) explicitly (take the \\( + \\) branch, constants omitted).",
    marks: 5,
    yearCreated: 2026,
    tags: ["applied ODE", "S2 correction", "three-term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading term \\( S_{0} \\).", workingLatex: "S_{0} = \\int\\sqrt{1+x^{2}}\\,dx = \\frac{x\\sqrt{1+x^{2}}}{2} + \\frac{1}{2}\\sinh^{-1} x.", explanation: "" },
        { stepNumber: 2, description: "Prefactor term \\( S_{1} \\).", workingLatex: "S_{1} = -\\frac{1}{4}\\ln(1+x^{2}).", explanation: "" },
        { stepNumber: 3, description: "Compute \\( S_{2}' \\) via the closed form.", workingLatex: "q=1+x^{2},\\ q'=2x,\\ q''=2: \\quad S_{2}' = \\frac{4(1+x^{2})(2) - 5(2x)^{2}}{32(1+x^{2})^{5/2}} = \\frac{2 - 3x^{2}}{8(1+x^{2})^{5/2}}.", explanation: "" },
        { stepNumber: 4, description: "Integrate to get \\( S_{2} \\).", workingLatex: "S_{2} = \\int \\frac{2 - 3x^{2}}{8(1+x^{2})^{5/2}}\\,dx = \\frac{x(x^{2} + 6)}{24(1+x^{2})^{3/2}}.", explanation: "Verified by sympy differentiation back to \\( S_{2}' \\)." },
        { stepNumber: 5, description: "State the exponent.", workingLatex: "\\frac{1}{\\varepsilon}S_{0} + S_{1} + \\varepsilon S_{2} = \\frac{1}{\\varepsilon}\\!\\left(\\frac{x\\sqrt{1+x^{2}}}{2} + \\frac{\\sinh^{-1}x}{2}\\right) - \\frac{\\ln(1+x^{2})}{4} + \\varepsilon\\,\\frac{x(x^{2}+6)}{24(1+x^{2})^{3/2}}.", explanation: "Including \\( \\varepsilon S_{2} \\) improves the ε=0.02 numerical match from ~0.2% to ~0.005%." },
      ],
      finalAnswer: "\\( S_{0}=\\tfrac12 x\\sqrt{1+x^{2}}+\\tfrac12\\sinh^{-1}x,\\ \\ S_{1}=-\\tfrac14\\ln(1+x^{2}),\\ \\ S_{2}=\\dfrac{x(x^{2}+6)}{24(1+x^{2})^{3/2}} \\).",
    },
  },
  {
    id: "am10a-020",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 20",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = x\\, y \\) on \\( x>0 \\), find the three-term LG approximation \\( y \\sim q^{-1/4}\\exp\\!\\big(\\tfrac{1}{\\varepsilon}S_{0} + \\varepsilon S_{2}\\big) \\), i.e. compute \\( S_{0} \\) and \\( S_{2} \\) for \\( q=x \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Airy-type", "S2 correction", "applied"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute \\( S_{0} \\).", workingLatex: "S_{0} = \\int \\sqrt{x}\\,dx = \\frac{2}{3} x^{3/2}.", explanation: "" },
        { stepNumber: 2, description: "Prefactor.", workingLatex: "q^{-1/4} = x^{-1/4}.", explanation: "" },
        { stepNumber: 3, description: "Compute \\( S_{2}' \\).", workingLatex: "q=x,\\ q'=1,\\ q''=0: \\quad S_{2}' = \\frac{0 - 5(1)^{2}}{32\\, x^{5/2}} = -\\frac{5}{32}x^{-5/2}.", explanation: "" },
        { stepNumber: 4, description: "Integrate.", workingLatex: "S_{2} = -\\frac{5}{32}\\int x^{-5/2}\\,dx = \\frac{5}{48} x^{-3/2}.", explanation: "" },
        { stepNumber: 5, description: "Assemble (decaying branch).", workingLatex: "y \\sim x^{-1/4}\\exp\\!\\left(-\\frac{2}{3\\varepsilon}x^{3/2} + \\varepsilon\\,\\frac{5}{48}x^{-3/2}\\right).", explanation: "This is the LG form of the Airy function \\( \\mathrm{Ai} \\); the leading exponent \\( -\\tfrac{2}{3\\varepsilon}x^{3/2} \\) matches the classical Airy asymptotics, with the \\( x^{-1/4} \\) prefactor." },
      ],
      finalAnswer: "\\( y \\sim x^{-1/4}\\exp\\!\\left(-\\dfrac{2}{3\\varepsilon}x^{3/2} + \\dfrac{5\\varepsilon}{48}x^{-3/2}\\right) \\).",
    },
  },
  {
    id: "am10a-021",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 21",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Show that \\( S_{2}' = \\dfrac{4qq''-5(q')^{2}}{32 q^{5/2}} \\) can be written as \\( S_{2}' = \\dfrac{1}{8}\\dfrac{q''}{q^{3/2}} - \\dfrac{5}{32}\\dfrac{(q')^{2}}{q^{5/2}} \\), and confirm it gives \\( S_{2}'\\equiv0 \\) when \\( q \\) is constant.",
    marks: 4,
    yearCreated: 2026,
    tags: ["S2 closed form", "algebra"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split the single fraction.", workingLatex: "S_{2}' = \\frac{4 q q''}{32 q^{5/2}} - \\frac{5(q')^{2}}{32 q^{5/2}} = \\frac{q''}{8 q^{3/2}} - \\frac{5(q')^{2}}{32 q^{5/2}}.", explanation: "Cancel \\( q \\) in the first term: \\( q/q^{5/2}=q^{-3/2} \\)." },
        { stepNumber: 2, description: "Constant-\\( q \\) check.", workingLatex: "q' = q'' = 0 \\;\\Longrightarrow\\; S_{2}' = 0 - 0 = 0.", explanation: "Both terms vanish, consistent with the series terminating for constant \\( q \\)." },
      ],
      finalAnswer: "\\( S_{2}' = \\dfrac{1}{8}\\dfrac{q''}{q^{3/2}} - \\dfrac{5}{32}\\dfrac{(q')^{2}}{q^{5/2}} \\); zero when \\( q \\) is constant.",
      canonicalAnswer: "(1/8) q''/q^(3/2) - (5/32) (q')^2/q^(5/2)",
    },
  },
  {
    id: "am10a-022",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 22",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (1+x)\\,y \\), write the full three-term LG solution \\( y \\sim q^{-1/4}\\exp\\!\\big(\\tfrac{1}{\\varepsilon}S_{0}+\\varepsilon S_{2}\\big) \\) on the decaying branch.",
    marks: 5,
    yearCreated: 2026,
    tags: ["applied ODE", "three-term", "S2"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the pieces.", workingLatex: "S_{0} = \\frac{2}{3}(1+x)^{3/2}, \\qquad q^{-1/4} = (1+x)^{-1/4}, \\qquad S_{2} = \\frac{5}{48}(1+x)^{-3/2}.", explanation: "From earlier parts; \\( S_{1} \\) is absorbed into the \\( q^{-1/4} \\) prefactor." },
        { stepNumber: 2, description: "Take the decaying branch \\( S_{0}'=-\\sqrt q \\).", workingLatex: "\\frac{1}{\\varepsilon}S_{0} = -\\frac{2}{3\\varepsilon}(1+x)^{3/2}.", explanation: "The \\( S_{2} \\) term is sign-independent at this order, computed with \\( S_{0}'=+\\sqrt q \\); on the decaying branch it keeps the same form." },
        { stepNumber: 3, description: "Assemble.", workingLatex: "y \\sim (1+x)^{-1/4}\\exp\\!\\left(-\\frac{2}{3\\varepsilon}(1+x)^{3/2} + \\frac{5\\varepsilon}{48}(1+x)^{-3/2}\\right).", explanation: "" },
      ],
      finalAnswer: "\\( y \\sim (1+x)^{-1/4}\\exp\\!\\left(-\\dfrac{2}{3\\varepsilon}(1+x)^{3/2} + \\dfrac{5\\varepsilon}{48}(1+x)^{-3/2}\\right) \\).",
    },
  },
  {
    id: "am10a-023",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 23",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = e^{x}\\, y \\), assemble the full three-term LG approximation \\( y \\sim q^{-1/4}\\exp\\!\\big(\\tfrac{1}{\\varepsilon}S_{0} + \\varepsilon S_{2}\\big) \\) on the growing branch.",
    marks: 5,
    yearCreated: 2026,
    tags: ["applied ODE", "three-term", "S2"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Collect the terms.", workingLatex: "S_{0} = 2 e^{x/2}, \\qquad q^{-1/4} = e^{-x/4}, \\qquad S_{2} = \\frac{1}{16} e^{-x/2}.", explanation: "From earlier parts." },
        { stepNumber: 2, description: "Form the exponent (growing branch).", workingLatex: "\\frac{1}{\\varepsilon}S_{0} + \\varepsilon S_{2} = \\frac{2}{\\varepsilon} e^{x/2} + \\frac{\\varepsilon}{16} e^{-x/2}.", explanation: "" },
        { stepNumber: 3, description: "Assemble with the prefactor.", workingLatex: "y \\sim e^{-x/4}\\exp\\!\\left(\\frac{2}{\\varepsilon} e^{x/2} + \\frac{\\varepsilon}{16} e^{-x/2}\\right).", explanation: "Numerical check (scipy, ε=0.02): the three-term form matches the ODE solution far more tightly than the leading term alone." },
      ],
      finalAnswer: "\\( y \\sim e^{-x/4}\\exp\\!\\left(\\dfrac{2}{\\varepsilon} e^{x/2} + \\dfrac{\\varepsilon}{16} e^{-x/2}\\right) \\).",
    },
  },
  {
    id: "am10a-024",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 24",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Substitute the LG amplitude form \\( y = q^{-1/4} u \\) into \\( \\varepsilon^{2} y'' = q y \\) to obtain \\( \\varepsilon^{2}\\big(u'' - \\tfrac{q'}{2q}u'\\big) = \\big(q + \\varepsilon^{2} R\\big) u \\), and find the remainder \\( R \\) in terms of \\( q \\). Hence relate \\( R \\) to the next LG correction \\( S_{2} \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["Liouville transformation", "Schwarzian-type term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set \\( y = q^{-1/4} u \\) and differentiate.", workingLatex: "y = q^{-1/4} u, \\qquad y'' = q^{-1/4}\\Big(u'' + 2\\frac{(q^{-1/4})'}{q^{-1/4}}u' + \\frac{(q^{-1/4})''}{q^{-1/4}}u\\Big).", explanation: "Differentiate the product by the chain and product rules." },
        { stepNumber: 2, description: "Note the \\( u' \\) coefficient.", workingLatex: "2\\frac{(q^{-1/4})'}{q^{-1/4}} = 2\\cdot\\Big(-\\frac14\\frac{q'}{q}\\Big) = -\\frac{q'}{2q}.", explanation: "The \\( q^{-1/4} \\) prefactor does not fully eliminate the first-derivative term; a residual \\( -\\tfrac{q'}{2q}u' \\) survives (full removal needs the further change of variable \\( d\\xi=\\sqrt q\\,dx \\))." },
        { stepNumber: 3, description: "Substitute into \\( \\varepsilon^{2}y''=qy \\), divide by \\( q^{-1/4} \\).", workingLatex: "\\varepsilon^{2}\\Big(u'' - \\frac{q'}{2q}u' + \\frac{(q^{-1/4})''}{q^{-1/4}}u\\Big) = q\\, u.", explanation: "" },
        { stepNumber: 4, description: "Read off the remainder \\( R \\).", workingLatex: "\\varepsilon^{2}\\Big(u'' - \\frac{q'}{2q}u'\\Big) = \\big(q + \\varepsilon^{2} R\\big) u, \\qquad R = -\\frac{(q^{-1/4})''}{q^{-1/4}} = \\frac{5(q')^{2}}{16 q^{2}} - \\frac{q''}{4q}.", explanation: "Computing \\( (q^{-1/4})'' \\) and dividing by \\( q^{-1/4} \\) gives this \\( R \\) (sympy-checked)." },
        { stepNumber: 5, description: "Connect to \\( S_{2} \\).", workingLatex: "S_{2}' = -\\frac{R}{2\\sqrt q} = \\frac{1}{2\\sqrt q}\\Big(\\frac{q''}{4q} - \\frac{5(q')^{2}}{16 q^{2}}\\Big) = \\frac{4qq'' - 5(q')^{2}}{32 q^{5/2}}.", explanation: "The remainder \\( \\varepsilon^{2}R \\) is the source that the \\( O(\\varepsilon^{2}) \\) balance must cancel; \\( -R/(2\\sqrt q) \\) reproduces the earlier closed form for \\( S_{2}' \\)." },
      ],
      finalAnswer: "\\( R = \\dfrac{5(q')^{2}}{16 q^{2}} - \\dfrac{q''}{4q} \\); then \\( S_{2}' = -\\dfrac{R}{2\\sqrt q} = \\dfrac{4qq''-5(q')^{2}}{32 q^{5/2}} \\).",
    },
  },
  {
    id: "am10a-025",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 25",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = (1 - x^{2})\\, y \\) on \\( -1 < x < 1 \\) (where \\( q>0 \\)), find the leading LG solution and state where the approximation fails.",
    marks: 5,
    yearCreated: 2026,
    tags: ["turning points", "two zeros", "applied"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify \\( q \\) and its zeros.", workingLatex: "q = 1 - x^{2}, \\qquad q = 0 \\text{ at } x = \\pm 1.", explanation: "On \\( (-1,1) \\), \\( q>0 \\); the endpoints are turning points." },
        { stepNumber: 2, description: "Compute \\( S_{0} \\).", workingLatex: "S_{0} = \\int\\sqrt{1-x^{2}}\\,dx = \\frac{x\\sqrt{1-x^{2}}}{2} + \\frac{1}{2}\\sin^{-1}x.", explanation: "Verified with sympy." },
        { stepNumber: 3, description: "Prefactor and assembly.", workingLatex: "y \\sim (1-x^{2})^{-1/4}\\exp\\!\\left(\\pm\\frac{1}{\\varepsilon}\\Big(\\frac{x\\sqrt{1-x^{2}}}{2}+\\frac{\\sin^{-1}x}{2}\\Big)\\right).", explanation: "" },
        { stepNumber: 4, description: "Validity.", workingLatex: "(1-x^{2})^{-1/4}\\to\\infty \\text{ as } x\\to\\pm1; \\quad \\varepsilon\\frac{|q'|}{q^{3/2}} = \\frac{2\\varepsilon|x|}{(1-x^{2})^{3/2}}\\to\\infty.", explanation: "LG fails within an \\( O(\\varepsilon^{2/3}) \\) layer of each turning point \\( x=\\pm1 \\), where Airy connection is required." },
      ],
      finalAnswer: "\\( y \\sim (1-x^{2})^{-1/4}\\exp\\!\\left(\\pm\\dfrac{1}{\\varepsilon}\\big(\\tfrac12 x\\sqrt{1-x^{2}}+\\tfrac12\\sin^{-1}x\\big)\\right) \\); fails at \\( x=\\pm1 \\).",
    },
  },
  {
    id: "am10a-026",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 26",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = x^{2}\\, y \\) on \\( x>0 \\), compute \\( S_{2} \\) and write the three-term LG approximation \\( y \\sim q^{-1/4}\\exp\\!\\big(\\tfrac{1}{\\varepsilon}S_{0}+\\varepsilon S_{2}\\big) \\) on the growing branch.",
    marks: 5,
    yearCreated: 2026,
    tags: ["applied ODE", "S2", "three-term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading term and prefactor.", workingLatex: "S_{0} = \\int x\\,dx = \\frac{x^{2}}{2}, \\qquad q^{-1/4} = (x^{2})^{-1/4} = x^{-1/2}.", explanation: "Using \\( \\sqrt{x^{2}}=x \\) for \\( x>0 \\)." },
        { stepNumber: 2, description: "Compute \\( S_{2}' \\).", workingLatex: "q=x^{2},\\ q'=2x,\\ q''=2: \\quad S_{2}' = \\frac{4x^{2}(2) - 5(2x)^{2}}{32 (x^{2})^{5/2}} = \\frac{8x^{2}-20x^{2}}{32 x^{5}} = -\\frac{12x^{2}}{32x^{5}} = -\\frac{3}{8x^{3}}.", explanation: "" },
        { stepNumber: 3, description: "Integrate.", workingLatex: "S_{2} = -\\frac{3}{8}\\int x^{-3}\\,dx = \\frac{3}{16 x^{2}}.", explanation: "Verified with sympy." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "y \\sim x^{-1/2}\\exp\\!\\left(\\frac{x^{2}}{2\\varepsilon} + \\frac{3\\varepsilon}{16 x^{2}}\\right).", explanation: "" },
      ],
      finalAnswer: "\\( y \\sim x^{-1/2}\\exp\\!\\left(\\dfrac{x^{2}}{2\\varepsilon} + \\dfrac{3\\varepsilon}{16 x^{2}}\\right) \\).",
    },
  },
  {
    id: "am10a-027",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 27",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = -\\omega^{2}(x)\\, y \\) with \\( \\omega^{2}>0 \\), derive the oscillatory LG solution and show the \\( O(\\varepsilon) \\) phase correction comes from \\( S_{2} \\), giving the leading frequency and amplitude.",
    marks: 5,
    yearCreated: 2026,
    tags: ["WKB oscillatory", "phase", "amplitude"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set \\( q = -\\omega^{2} \\).", workingLatex: "(S_{0}')^{2} = -\\omega^{2} \\;\\Longrightarrow\\; S_{0}' = \\pm i\\,\\omega \\;\\Longrightarrow\\; S_{0} = \\pm i\\int\\omega\\,dx.", explanation: "" },
        { stepNumber: 2, description: "Prefactor.", workingLatex: "S_{1} = -\\frac14\\ln q = -\\frac14\\ln(-\\omega^{2}) \\;\\Rightarrow\\; |y|\\propto \\omega^{-1/2}.", explanation: "The real amplitude is \\( \\omega^{-1/2} \\) (since \\( q^{-1/4}=(\\omega^{2})^{-1/4}=\\omega^{-1/2} \\) up to phase)." },
        { stepNumber: 3, description: "Leading oscillatory solution.", workingLatex: "y \\sim \\omega^{-1/2}\\left[A\\cos\\!\\Big(\\frac{1}{\\varepsilon}\\int\\omega\\,dx\\Big) + B\\sin\\!\\Big(\\frac{1}{\\varepsilon}\\int\\omega\\,dx\\Big)\\right].", explanation: "Standard adiabatic-invariant / WKB form: amplitude \\( \\propto \\omega^{-1/2} \\), phase \\( \\tfrac1\\varepsilon\\int\\omega \\)." },
        { stepNumber: 4, description: "Phase correction from \\( S_{2} \\).", workingLatex: "S_{2}' = \\frac{4qq''-5(q')^{2}}{32 q^{5/2}}\\bigg|_{q=-\\omega^{2}} \\;\\Rightarrow\\; \\text{phase} \\to \\frac{1}{\\varepsilon}\\int\\omega\\,dx + \\varepsilon\\,\\mathrm{Im}\\!\\int S_{2}'\\,dx.", explanation: "The \\( \\varepsilon S_{2} \\) term shifts the accumulated phase at \\( O(\\varepsilon) \\); its sign follows from the \\( q=-\\omega^{2} \\) substitution." },
      ],
      finalAnswer: "\\( y \\sim \\omega^{-1/2}\\big[A\\cos\\Phi + B\\sin\\Phi\\big],\\ \\Phi=\\dfrac1\\varepsilon\\displaystyle\\int\\omega\\,dx \\); \\( S_{2} \\) gives the \\( O(\\varepsilon) \\) phase shift.",
    },
  },
  {
    id: "am10a-028",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 28",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "The general LG solution is \\( y = q^{-1/4}\\big(c_{+}e^{S_{0}/\\varepsilon} + c_{-}e^{-S_{0}/\\varepsilon}\\big)(1 + O(\\varepsilon)) \\). For \\( \\varepsilon^{2} y'' = (1+x)\\,y \\), find the constants in the relative correction so that the bracket reads \\( 1 + \\varepsilon S_{2} + \\cdots \\) on each branch, giving the two values of \\( S_{2} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["both branches", "S2 sign", "applied"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall \\( S_{2}' \\) is computed with \\( S_{0}'=+\\sqrt q \\).", workingLatex: "S_{2,+}' = \\frac{4qq''-5(q')^{2}}{32 q^{5/2}} = -\\frac{5}{32}(1+x)^{-5/2}.", explanation: "For \\( q=1+x \\), \\( q''=0 \\)." },
        { stepNumber: 2, description: "Flip the sign of \\( S_{0}' \\) for the other branch.", workingLatex: "S_{2,-}' = -\\frac{(S_{1}')^{2}+S_{1}''}{2(-\\sqrt q)} = -S_{2,+}' = +\\frac{5}{32}(1+x)^{-5/2}.", explanation: "\\( S_{1} \\) is sign-independent, but \\( S_{2}' \\) carries the sign of \\( 1/S_{0}' \\), so it reverses on the decaying branch." },
        { stepNumber: 3, description: "Integrate both.", workingLatex: "S_{2,+} = \\frac{5}{48}(1+x)^{-3/2}, \\qquad S_{2,-} = -\\frac{5}{48}(1+x)^{-3/2}.", explanation: "" },
        { stepNumber: 4, description: "State the two corrections.", workingLatex: "y \\sim (1+x)^{-1/4}\\Big[c_{+}e^{S_{0}/\\varepsilon}\\big(1+\\varepsilon S_{2,+}\\big) + c_{-}e^{-S_{0}/\\varepsilon}\\big(1+\\varepsilon S_{2,-}\\big)\\Big].", explanation: "The two branches carry equal-and-opposite \\( S_{2} \\) corrections." },
      ],
      finalAnswer: "\\( S_{2,\\pm} = \\pm\\dfrac{5}{48}(1+x)^{-3/2} \\) on the \\( e^{\\pm S_{0}/\\varepsilon} \\) branches.",
      canonicalAnswer: "S2 = +-(5/48)(1+x)^(-3/2)",
    },
  },
  {
    id: "am10a-029",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 29",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = e^{2x}\\, y \\), compute \\( S_{0}, S_{1}, S_{2} \\) and assemble the three-term LG approximation on the decaying branch.",
    marks: 5,
    yearCreated: 2026,
    tags: ["applied ODE", "S2", "three-term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute \\( S_{0} \\).", workingLatex: "q = e^{2x}, \\quad \\sqrt q = e^{x}: \\qquad S_{0} = \\int e^{x}\\,dx = e^{x}.", explanation: "" },
        { stepNumber: 2, description: "Prefactor \\( S_{1} \\).", workingLatex: "S_{1} = -\\frac14\\ln e^{2x} = -\\frac{x}{2} \\;\\Rightarrow\\; q^{-1/4} = e^{-x/2}.", explanation: "" },
        { stepNumber: 3, description: "Compute \\( S_{2}' \\).", workingLatex: "q'=2e^{2x},\\ q''=4e^{2x}: \\quad S_{2}' = \\frac{4 e^{2x}(4 e^{2x}) - 5(2e^{2x})^{2}}{32 (e^{2x})^{5/2}} = \\frac{16 e^{4x} - 20 e^{4x}}{32 e^{5x}} = -\\frac{e^{-x}}{8}.", explanation: "" },
        { stepNumber: 4, description: "Integrate.", workingLatex: "S_{2} = -\\frac18\\int e^{-x}\\,dx = \\frac{1}{8} e^{-x}.", explanation: "Verified with sympy." },
        { stepNumber: 5, description: "Assemble (decaying branch).", workingLatex: "y \\sim e^{-x/2}\\exp\\!\\left(-\\frac{1}{\\varepsilon} e^{x} + \\frac{\\varepsilon}{8} e^{-x}\\right).", explanation: "" },
      ],
      finalAnswer: "\\( y \\sim e^{-x/2}\\exp\\!\\left(-\\dfrac{1}{\\varepsilon} e^{x} + \\dfrac{\\varepsilon}{8} e^{-x}\\right) \\).",
    },
  },
  {
    id: "am10a-030",
    topicRef: "am10a",
    topicTitle: "The Liouville–Green expansion (S₀, S₁, S₂) 30",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( \\varepsilon^{2} y'' = x\\, y \\) near the turning point \\( x=0 \\), introduce the inner variable \\( X = x/\\varepsilon^{2/3} \\), show the equation becomes \\( \\dfrac{d^{2}Y}{dX^{2}} = X\\,Y \\) (Airy's equation), and confirm \\( \\varepsilon^{2/3} \\) is the breakdown scale predicted by LG.",
    marks: 5,
    yearCreated: 2026,
    tags: ["turning point", "Airy rescaling", "inner scaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Predict the breakdown scale from LG validity.", workingLatex: "\\varepsilon\\frac{|q'|}{q^{3/2}} = \\frac{\\varepsilon}{x^{3/2}} = O(1) \\;\\Longrightarrow\\; x = O(\\varepsilon^{2/3}).", explanation: "The LG validity quantity for \\( q=x \\) becomes order one when \\( x\\sim\\varepsilon^{2/3} \\)." },
        { stepNumber: 2, description: "Introduce the inner variable.", workingLatex: "x = \\varepsilon^{2/3} X \\;\\Longrightarrow\\; \\frac{d}{dx} = \\varepsilon^{-2/3}\\frac{d}{dX}, \\quad \\frac{d^{2}}{dx^{2}} = \\varepsilon^{-4/3}\\frac{d^{2}}{dX^{2}}.", explanation: "" },
        { stepNumber: 3, description: "Substitute into the ODE.", workingLatex: "\\varepsilon^{2}\\,\\varepsilon^{-4/3}\\frac{d^{2}Y}{dX^{2}} = (\\varepsilon^{2/3}X)\\, Y \\;\\Longrightarrow\\; \\varepsilon^{2/3}\\frac{d^{2}Y}{dX^{2}} = \\varepsilon^{2/3} X\\, Y.", explanation: "Both sides carry the same power \\( \\varepsilon^{2/3} \\): this is the distinguished limit." },
        { stepNumber: 4, description: "Cancel and identify Airy.", workingLatex: "\\frac{d^{2}Y}{dX^{2}} = X\\, Y.", explanation: "Airy's equation, solved by \\( \\mathrm{Ai}(X), \\mathrm{Bi}(X) \\); it provides the inner solution connecting the two LG branches across \\( x=0 \\)." },
        { stepNumber: 5, description: "Confirm the scale.", workingLatex: "x_{\\text{inner}} = O(\\varepsilon^{2/3}),", explanation: "exactly the breakdown scale anticipated from the LG ordering — the balance is consistent." },
      ],
      finalAnswer: "\\( \\dfrac{d^{2}Y}{dX^{2}} = X\\,Y \\) (Airy) with \\( X=x/\\varepsilon^{2/3} \\); the inner scale \\( \\varepsilon^{2/3} \\) matches the LG breakdown.",
    },
  },
];
