import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — am1a
 * "Order notation, gauge functions & asymptotic sequences"
 * Topic group: Asymptotic Sequences & Series
 *
 * Scope: Landau order notation (O, o) and asymptotic equivalence (~); gauge /
 * scale functions; testing whether a sequence of functions {phi_n} is asymptotic
 * (phi_{n+1} = o(phi_n)) as x -> 0 or x -> oo. Also: uniqueness of asymptotic
 * power-series coefficients and beyond-all-orders (subdominant) terms.
 *
 * Seeded (and varied in constants / limits / framing) from Cambridge Part II
 * Asymptotic Methods Example Sheet 1: Q3 (is {1 - cosh(x^n)} asymptotic),
 * Q4 (product of asymptotic series), Q5 (reciprocal of an asymptotic series),
 * Q6 (uniqueness of coefficients; e^{-1/x} beyond all orders), Q7 (cosh in
 * sectors of the complex plane), Q8 (integrating an o-estimate).
 *
 * 30 questions: 6 Foundation, 12 Standard, 12 Challenge.
 *
 * Numerical / symbolic spot-checks (python3 sympy + mpmath) were run for the
 * limit, series-expansion, recursion and integral claims; see commit notes.
 * Pure existence / uniqueness arguments carry a // REVIEW comment.
 */
export const questions: Question[] = [
  // ── Foundation: core order-notation technique in isolation ────
  {
    id: "am1a-001",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Determine the simplest power \\( x^p \\) such that \\( 1 - \\cos x = O(x^p) \\) as \\( x \\to 0 \\), and state whether the relation can be sharpened to \\( \\sim \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["order notation", "Taylor series", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Taylor-expand the function about the limit point.", workingLatex: "1 - \\cos x = \\frac{x^2}{2} - \\frac{x^4}{24} + \\cdots", explanation: "Near \\( x = 0 \\) the constant terms cancel, so the first surviving term in the Maclaurin series sets the leading behaviour." },
        { stepNumber: 2, description: "Identify the leading term.", workingLatex: "1 - \\cos x = \\frac{x^2}{2}\\Bigl(1 - \\frac{x^2}{12} + \\cdots\\Bigr)", explanation: "Factoring out the leading power makes the bracket tend to \\( 1 \\), which is the hallmark of an exact leading-order estimate." },
        { stepNumber: 3, description: "Read off the order.", workingLatex: "\\frac{1-\\cos x}{x^2} \\to \\frac{1}{2} \\quad (x \\to 0)", explanation: "A finite non-zero limit of the ratio means \\( 1-\\cos x = O(x^2) \\), and \\( x^2 \\) is the smallest power for which this holds." },
        { stepNumber: 4, description: "Decide whether \\( \\sim \\) applies.", workingLatex: "1 - \\cos x \\sim \\tfrac{1}{2}x^2 \\quad (x \\to 0)", explanation: "Because the ratio tends to the specific constant \\( \\tfrac12 \\), we may write the sharper relation \\( 1-\\cos x \\sim \\tfrac12 x^2 \\); the bare \\( O(x^2) \\) only records the power." },
      ],
      finalAnswer: "\\( p = 2 \\); and indeed \\( 1 - \\cos x \\sim \\tfrac{1}{2}x^2 \\) as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-002",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Decide whether \\( e^{-x} = o(x^{-3}) \\) as \\( x \\to +\\infty \\), justifying your answer with a limit.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["little-o", "exponential decay", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write down the ratio that little-o requires.", workingLatex: "\\frac{e^{-x}}{x^{-3}} = x^3 e^{-x}", explanation: "By definition \\( f = o(g) \\) means \\( f/g \\to 0 \\); here \\( g = x^{-3} \\), so dividing flips it to a multiplying factor \\( x^3 \\)." },
        { stepNumber: 2, description: "Evaluate the limit.", workingLatex: "\\lim_{x \\to +\\infty} x^3 e^{-x} = 0", explanation: "The exponential \\( e^{-x} \\) decays faster than any power of \\( x \\) grows, so the product vanishes." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "e^{-x} = o(x^{-3}) \\quad (x \\to +\\infty)", explanation: "The ratio tends to zero, so \\( e^{-x} \\) is asymptotically negligible compared with \\( x^{-3} \\) — in fact compared with every power of \\( x \\)." },
      ],
      finalAnswer: "Yes: \\( x^3 e^{-x} \\to 0 \\), so \\( e^{-x} = o(x^{-3}) \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-003",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find a simple function \\( g(x) \\) such that \\( \\sqrt{x^2 + 4x} \\sim g(x) \\) as \\( x \\to +\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Factor out the dominant power inside the root.", workingLatex: "\\sqrt{x^2 + 4x} = \\sqrt{x^2}\\,\\sqrt{1 + \\frac{4}{x}} = x\\sqrt{1 + \\frac{4}{x}}", explanation: "For \\( x \\to +\\infty \\) we have \\( x>0 \\), so \\( \\sqrt{x^2} = x \\); pulling it out isolates a bracket that tends to \\( 1 \\)." },
        { stepNumber: 2, description: "Take the limit of the ratio with \\( g(x)=x \\).", workingLatex: "\\frac{\\sqrt{x^2+4x}}{x} = \\sqrt{1 + \\frac{4}{x}} \\to 1", explanation: "As \\( x \\to +\\infty \\) the term \\( 4/x \\to 0 \\), so the square root tends to \\( 1 \\); a unit limit is exactly the condition for \\( \\sim \\)." },
        { stepNumber: 3, description: "State the asymptotic equivalence.", workingLatex: "\\sqrt{x^2 + 4x} \\sim x \\quad (x \\to +\\infty)", explanation: "The simplest gauge function capturing the leading behaviour is \\( g(x)=x \\); the \\( 4x \\) under the root only affects lower-order terms." },
      ],
      finalAnswer: "\\( \\sqrt{x^2+4x} \\sim x \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-004",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The candidate gauge sequence is \\( \\phi_n(x) = x^{2n} \\) for \\( n = 1, 2, 3, \\ldots \\). Verify that it is an asymptotic sequence as \\( x \\to 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the defining condition.", workingLatex: "\\{\\phi_n\\}\\ \\text{is asymptotic} \\iff \\phi_{n+1}(x) = o\\bigl(\\phi_n(x)\\bigr)\\ \\text{for every } n", explanation: "An asymptotic sequence is one in which each term is negligible compared with the one before it, in the appropriate limit." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{2(n+1)}}{x^{2n}} = x^2", explanation: "The powers subtract, leaving \\( x^2 \\) independent of \\( n \\)." },
        { stepNumber: 3, description: "Take the limit as \\( x \\to 0 \\).", workingLatex: "\\lim_{x \\to 0} x^2 = 0", explanation: "The ratio vanishes, so \\( \\phi_{n+1} = o(\\phi_n) \\) holds for every \\( n \\)." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "\\{x^{2n}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to 0", explanation: "The negligibility condition holds uniformly in \\( n \\), so the sequence qualifies." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = x^2 \\to 0 \\), so \\( \\{x^{2n}\\} \\) is asymptotic as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-005",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Determine whether \\( \\ln x = O(x^{1/2}) \\) as \\( x \\to +\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["big-O", "logarithm", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the ratio for the order test.", workingLatex: "\\frac{\\ln x}{x^{1/2}}", explanation: "For \\( f = O(g) \\) it suffices that \\( f/g \\) is bounded as \\( x \\to \\infty \\); checking the limit settles boundedness." },
        { stepNumber: 2, description: "Apply L'Hopital's rule to the indeterminate \\( \\infty/\\infty \\).", workingLatex: "\\lim_{x \\to \\infty} \\frac{\\ln x}{x^{1/2}} = \\lim_{x \\to \\infty} \\frac{1/x}{\\tfrac{1}{2}x^{-1/2}} = \\lim_{x \\to \\infty} \\frac{2}{x^{1/2}} = 0", explanation: "Differentiating top and bottom turns the ratio into \\( 2x^{-1/2} \\), which clearly vanishes." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "\\ln x = o(x^{1/2}) \\subset O(x^{1/2}) \\quad (x \\to +\\infty)", explanation: "The limit is not merely bounded but zero, so the stronger little-o holds; in particular the big-O claim is true." },
      ],
      finalAnswer: "Yes — in fact \\( \\ln x = o(x^{1/2}) \\), which is stronger than \\( O(x^{1/2}) \\).",
    },
  },
  {
    id: "am1a-006",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the gauge function \\( g(x) \\) of the form \\( c\\,x^p \\) with \\( c \\neq 0 \\) such that \\( \\sin x - x \\sim g(x) \\) as \\( x \\to 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "Taylor series", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Maclaurin-expand the combination.", workingLatex: "\\sin x - x = \\Bigl(x - \\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots\\Bigr) - x = -\\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots", explanation: "The linear terms cancel, exposing the cubic as the leading non-zero contribution." },
        { stepNumber: 2, description: "Isolate the leading term.", workingLatex: "\\sin x - x = -\\frac{x^3}{6}\\Bigl(1 - \\frac{x^2}{20} + \\cdots\\Bigr)", explanation: "Factoring the cubic leaves a bracket tending to \\( 1 \\), so the cubic alone governs the leading behaviour." },
        { stepNumber: 3, description: "State the equivalence.", workingLatex: "\\sin x - x \\sim -\\frac{x^3}{6} \\quad (x \\to 0)", explanation: "The ratio \\( (\\sin x - x)/(-x^3/6) \\to 1 \\), so the gauge function is \\( -\\tfrac{1}{6}x^3 \\)." },
      ],
      finalAnswer: "\\( g(x) = -\\tfrac{1}{6}x^3 \\), i.e. \\( \\sin x - x \\sim -\\tfrac{1}{6}x^3 \\) as \\( x \\to 0 \\).",
    },
  },

  // ── Standard: typical sheet-level questions (3–4 marks) ────
  {
    id: "am1a-007",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether the sequence of functions \\( \\phi_n(x) = 1 - \\cosh(x^n) \\), for \\( n \\in \\{1, 2, 3, \\ldots\\} \\), is an asymptotic sequence as \\( x \\to 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "cosh", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand a single term using the series for cosh.", workingLatex: "\\cosh(x^n) = 1 + \\frac{x^{2n}}{2!} + \\frac{x^{4n}}{4!} + \\cdots", explanation: "Substituting \\( u = x^n \\) into \\( \\cosh u = 1 + u^2/2! + \\cdots \\) gives only even multiples of \\( n \\) in the exponents." },
        { stepNumber: 2, description: "Subtract from \\( 1 \\) to get the leading behaviour.", workingLatex: "\\phi_n(x) = 1 - \\cosh(x^n) = -\\frac{x^{2n}}{2} - \\frac{x^{4n}}{24} - \\cdots \\sim -\\frac{x^{2n}}{2}", explanation: "The constant \\( 1 \\) cancels, leaving a series whose first term \\( -\\tfrac12 x^{2n} \\) dominates as \\( x \\to 0 \\)." },
        { stepNumber: 3, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} \\sim \\frac{-\\tfrac12 x^{2(n+1)}}{-\\tfrac12 x^{2n}} = x^2", explanation: "Using the leading-order forms, the constant factors and the common power cancel, leaving \\( x^2 \\)." },
        { stepNumber: 4, description: "Take the limit as \\( x \\to 0 \\).", workingLatex: "\\lim_{x \\to 0} \\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\lim_{x\\to 0} x^2 = 0", explanation: "The ratio vanishes for every \\( n \\), so each term is little-o of its predecessor." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\phi_{n+1} = o(\\phi_n)\\ \\forall n \\implies \\{1 - \\cosh(x^n)\\}\\ \\text{is asymptotic as } x \\to 0", explanation: "The defining negligibility condition holds for all \\( n \\), so the sequence is indeed asymptotic at the origin." },
      ],
      finalAnswer: "Yes: \\( \\phi_n \\sim -\\tfrac12 x^{2n} \\), so \\( \\phi_{n+1}/\\phi_n \\to 0 \\) and the sequence is asymptotic as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-008",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether the sequence \\( \\phi_n(x) = e^{-nx} \\), for \\( n = 1, 2, 3, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "exponential", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the test.", workingLatex: "\\text{Need } \\phi_{n+1}(x) = o\\bigl(\\phi_n(x)\\bigr)\\ \\text{as } x \\to +\\infty\\ \\text{for every } n", explanation: "Asymptoticity is a statement about the ratio of consecutive terms in the stated limit." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{e^{-(n+1)x}}{e^{-nx}} = e^{-x}", explanation: "Exponent laws collapse the quotient to a single exponential, independent of \\( n \\)." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} e^{-x} = 0", explanation: "The ratio decays to zero, so the negligibility condition holds for every \\( n \\)." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "\\{e^{-nx}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to +\\infty", explanation: "Each \\( e^{-(n+1)x} \\) is exponentially smaller than \\( e^{-nx} \\), confirming the property." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = e^{-x} \\to 0 \\), so \\( \\{e^{-nx}\\} \\) is asymptotic as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-009",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the proposed sequence \\( \\phi_n(x) = x^{-n} \\sin x \\), for \\( n = 0, 1, 2, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\), and explain why \\( \\{x^{-n}\\} \\) is the natural underlying gauge sequence.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{-(n+1)}\\sin x}{x^{-n}\\sin x} = \\frac{1}{x}", explanation: "The common factor \\( \\sin x \\) cancels (for \\( x \\) where it is non-zero), leaving a pure power; the oscillation plays no role in the ratio." },
        { stepNumber: 2, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} \\frac{1}{x} = 0", explanation: "So \\( \\phi_{n+1} = o(\\phi_n) \\) for every \\( n \\), giving an asymptotic sequence." },
        { stepNumber: 3, description: "Address the shared oscillatory factor.", workingLatex: "\\phi_n(x) = \\sin x \\cdot x^{-n}, \\qquad |\\sin x| \\le 1", explanation: "The bounded factor \\( \\sin x \\) does not change orders of magnitude, so the powers \\( x^{-n} \\) alone control the hierarchy." },
        { stepNumber: 4, description: "State the underlying gauge sequence.", workingLatex: "\\{\\phi_n\\}\\ \\text{ranks by } \\{x^{-n}\\}_{n \\ge 0}", explanation: "Because each ratio reduces to \\( 1/x \\), the inverse-power sequence \\( \\{x^{-n}\\} \\) is the natural scale against which these terms are measured." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = 1/x \\to 0 \\); the gauge sequence is \\( \\{x^{-n}\\} \\).",
    },
  },
  {
    id: "am1a-010",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether \\( \\phi_n(x) = x^{n} (\\ln x)^{n} \\), for \\( n = 0, 1, 2, \\ldots \\), forms an asymptotic sequence as \\( x \\to 0^+ \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "logarithm", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{n+1}(\\ln x)^{n+1}}{x^{n}(\\ln x)^{n}} = x \\ln x", explanation: "Both the power of \\( x \\) and the power of \\( \\ln x \\) drop by one, leaving the single product \\( x\\ln x \\)." },
        { stepNumber: 2, description: "Evaluate the limit as \\( x \\to 0^+ \\).", workingLatex: "\\lim_{x \\to 0^+} x \\ln x = \\lim_{x \\to 0^+} \\frac{\\ln x}{1/x} = \\lim_{x \\to 0^+} \\frac{1/x}{-1/x^2} = \\lim_{x \\to 0^+}(-x) = 0", explanation: "Writing it as \\( \\infty/\\infty \\) and applying L'Hopital's rule shows the power beats the logarithm, so the product vanishes." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "\\phi_{n+1} = o(\\phi_n)\\ \\forall n \\implies \\{x^n (\\ln x)^n\\}\\ \\text{is asymptotic as } x \\to 0^+", explanation: "Although each term carries a logarithm, the ratio still tends to zero, so the sequence qualifies." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = x\\ln x \\to 0 \\), so the sequence is asymptotic as \\( x \\to 0^+ \\).",
    },
  },
  {
    id: "am1a-011",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the sequence \\( \\phi_n(x) = x^{1/n} \\), for \\( n = 1, 2, 3, \\ldots \\), is NOT an asymptotic sequence as \\( x \\to 0^+ \\). State a rearrangement of the same functions that is asymptotic.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "counterexample", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compare the exponents.", workingLatex: "\\frac{1}{n+1} < \\frac{1}{n} \\quad (n \\ge 1)", explanation: "The exponents decrease with \\( n \\), so as \\( x\\to 0^+ \\) a smaller positive power of \\( x \\) is actually LARGER, not smaller." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{1/(n+1)}}{x^{1/n}} = x^{\\frac{1}{n+1} - \\frac{1}{n}} = x^{-\\frac{1}{n(n+1)}}", explanation: "The exponent is negative because \\( 1/(n+1) - 1/n < 0 \\)." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{x \\to 0^+} x^{-\\frac{1}{n(n+1)}} = +\\infty", explanation: "A negative power of \\( x \\) blows up as \\( x \\to 0^+ \\), so \\( \\phi_{n+1} \\) is in fact much LARGER than \\( \\phi_n \\)." },
        { stepNumber: 4, description: "Diagnose the failure and repair it.", workingLatex: "\\phi_{n+1} \\neq o(\\phi_n);\\quad \\text{instead order them as } \\psi_n(x) = x^{1/(N-n)}\\ \\text{(decreasing exponent)}", explanation: "The list is in the wrong order. Reindexing so the exponents DECREASE — e.g. \\( x, x^{1/2}, x^{1/3}, \\ldots \\) read the other way — gives a genuine asymptotic sequence as \\( x\\to 0^+ \\), since then each ratio is a positive power of \\( x \\)." },
      ],
      finalAnswer: "Not asymptotic: \\( \\phi_{n+1}/\\phi_n = x^{-1/[n(n+1)]} \\to \\infty \\). Reordering with decreasing exponents (e.g. \\( x, x^{1/2}, x^{1/3},\\ldots \\) reversed) restores the property.",
    },
  },
  {
    id: "am1a-012",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( f(x) = \\dfrac{x}{1 + 2x} \\), find the order of the error \\( f(x) - x \\) as \\( x \\to 0 \\), expressing it as \\( \\sim c\\,x^p \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "geometric series", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the denominator as a geometric series.", workingLatex: "\\frac{1}{1+2x} = 1 - 2x + 4x^2 - \\cdots \\quad (|2x| < 1)", explanation: "For small \\( x \\) the factor \\( 1/(1+2x) \\) has the convergent expansion \\( \\sum (-2x)^k \\)." },
        { stepNumber: 2, description: "Multiply by \\( x \\).", workingLatex: "f(x) = x(1 - 2x + 4x^2 - \\cdots) = x - 2x^2 + 4x^3 - \\cdots", explanation: "Distributing the leading \\( x \\) shifts every power up by one." },
        { stepNumber: 3, description: "Subtract the linear part.", workingLatex: "f(x) - x = -2x^2 + 4x^3 - \\cdots \\sim -2x^2", explanation: "The leading \\( x \\) cancels, exposing the quadratic term as the dominant remainder." },
        { stepNumber: 4, description: "State the order.", workingLatex: "f(x) - x \\sim -2x^2 \\quad (x \\to 0), \\qquad p = 2,\\ c = -2", explanation: "The ratio \\( (f-x)/x^2 \\to -2 \\), so the error is exactly second order with coefficient \\( -2 \\)." },
      ],
      finalAnswer: "\\( f(x) - x \\sim -2x^2 \\) as \\( x \\to 0 \\) (\\( c=-2,\\ p=2 \\)).",
    },
  },
  {
    id: "am1a-013",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Two functions satisfy \\( f(x) = o(x^3) \\) and \\( g(x) = O(x^2) \\) as \\( x \\to 0 \\). Determine the sharpest order statement you can make for the product \\( f(x)g(x) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["order notation", "algebra of orders", "little-o"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Translate each hypothesis into a ratio statement.", workingLatex: "\\frac{f(x)}{x^3} \\to 0, \\qquad \\frac{g(x)}{x^2}\\ \\text{stays bounded}", explanation: "\\( f = o(x^3) \\) gives a vanishing ratio; \\( g = O(x^2) \\) gives a bounded ratio — that is all we may use." },
        { stepNumber: 2, description: "Multiply the two ratios.", workingLatex: "\\frac{f(x)g(x)}{x^5} = \\frac{f(x)}{x^3}\\cdot\\frac{g(x)}{x^2}", explanation: "Pairing the powers \\( x^3 \\) and \\( x^2 \\) gives \\( x^5 \\) in the denominator." },
        { stepNumber: 3, description: "Evaluate the limit of the product.", workingLatex: "\\frac{f(x)}{x^3}\\cdot\\frac{g(x)}{x^2} \\to 0 \\cdot (\\text{bounded}) = 0", explanation: "A factor tending to zero times a bounded factor tends to zero." },
        { stepNumber: 4, description: "State the result.", workingLatex: "f(x)g(x) = o(x^5) \\quad (x \\to 0)", explanation: "The product is little-o of \\( x^5 \\); this is the sharpest order guaranteed, since the o on \\( f \\) upgrades the combined estimate from \\( O \\) to \\( o \\)." },
      ],
      finalAnswer: "\\( f(x)g(x) = o(x^5) \\) as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-014",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order asymptotic behaviour of \\( \\tanh x \\) as \\( x \\to +\\infty \\), and express \\( 1 - \\tanh x \\) in the form \\( \\sim c\\,e^{-\\lambda x} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["tanh", "asymptotic equivalence", "exponential decay"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write tanh in exponential form.", workingLatex: "\\tanh x = \\frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}", explanation: "The definition exposes the competing exponentials whose ratio determines large-\\( x \\) behaviour." },
        { stepNumber: 2, description: "Divide numerator and denominator by \\( e^{x} \\).", workingLatex: "\\tanh x = \\frac{1 - e^{-2x}}{1 + e^{-2x}}", explanation: "Factoring out the dominant \\( e^{x} \\) leaves only the small quantity \\( e^{-2x} \\to 0 \\)." },
        { stepNumber: 3, description: "Read off the leading order.", workingLatex: "\\tanh x \\to 1 \\quad (x \\to +\\infty), \\qquad \\text{so } \\tanh x \\sim 1", explanation: "Both small terms vanish, so the limit is \\( 1 \\)." },
        { stepNumber: 4, description: "Expand the correction term.", workingLatex: "1 - \\tanh x = 1 - \\frac{1 - e^{-2x}}{1 + e^{-2x}} = \\frac{2 e^{-2x}}{1 + e^{-2x}}", explanation: "Combining over a common denominator isolates the exponentially small defect from \\( 1 \\)." },
        { stepNumber: 5, description: "Take the leading order of the defect.", workingLatex: "1 - \\tanh x \\sim 2 e^{-2x} \\quad (x \\to +\\infty)", explanation: "Since \\( 1 + e^{-2x} \\to 1 \\), the leading behaviour is \\( 2e^{-2x} \\), giving \\( c = 2,\\ \\lambda = 2 \\)." },
      ],
      finalAnswer: "\\( \\tanh x \\sim 1 \\); \\( 1 - \\tanh x \\sim 2e^{-2x} \\) as \\( x \\to +\\infty \\) (\\( c=2,\\ \\lambda=2 \\)).",
    },
  },
  {
    id: "am1a-015",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The functions \\( f \\) and \\( g \\) have asymptotic expansions \\( f(z) \\sim 1 + \\dfrac{2}{z} \\) and \\( g(z) \\sim 3 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\) (to the orders shown). Using \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), find the first three coefficients \\( c_0, c_1, c_2 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["product of series", "asymptotic expansion", "Cauchy product"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of each series.", workingLatex: "a_0 = 1,\\ a_1 = 2,\\ a_{\\ge 2} = 0; \\qquad b_0 = 3,\\ b_1 = 1,\\ b_{\\ge 2} = 0", explanation: "Reading off the given expansions identifies the only non-zero coefficients." },
        { stepNumber: 2, description: "Apply the Cauchy-product formula for \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = 1 \\cdot 3 = 3", explanation: "The leading coefficient is simply the product of the two leading coefficients." },
        { stepNumber: 3, description: "Compute \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = 1\\cdot 1 + 2\\cdot 3 = 7", explanation: "The order-\\( z^{-1} \\) coefficient collects every way the powers add to one." },
        { stepNumber: 4, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + 2\\cdot 1 + 0 = 2", explanation: "Only the \\( a_1 b_1 \\) term survives since the second-order coefficients vanish." },
        { stepNumber: 5, description: "Assemble the product expansion.", workingLatex: "f(z)g(z) \\sim 3 + \\frac{7}{z} + \\frac{2}{z^2} + \\cdots \\quad (z \\to \\infty)", explanation: "Direct multiplication \\( (1 + 2/z)(3 + 1/z) = 3 + 7/z + 2/z^2 \\) confirms the coefficients." },
      ],
      finalAnswer: "\\( c_0 = 3,\\ c_1 = 7,\\ c_2 = 2 \\).",
    },
  },
  {
    id: "am1a-016",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Decide, with justification, whether the relation \\( x^2 + x = o(x^2) \\) holds as \\( x \\to +\\infty \\), and give the correct order statement.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["order notation", "little-o", "common error"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Test the proposed little-o relation.", workingLatex: "\\frac{x^2 + x}{x^2} = 1 + \\frac{1}{x}", explanation: "For \\( o(x^2) \\) we would need this ratio to tend to zero." },
        { stepNumber: 2, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty}\\Bigl(1 + \\frac{1}{x}\\Bigr) = 1 \\neq 0", explanation: "The ratio tends to \\( 1 \\), not \\( 0 \\), so the little-o claim is false." },
        { stepNumber: 3, description: "Give the correct statements.", workingLatex: "x^2 + x \\sim x^2, \\qquad x^2 + x = O(x^2) \\quad (x \\to +\\infty)", explanation: "A unit limit means \\( x^2 + x \\) is asymptotically equivalent to \\( x^2 \\) (hence \\( O(x^2) \\)); only the subdominant part \\( x \\) is \\( o(x^2) \\)." },
      ],
      finalAnswer: "No, \\( x^2 + x \\neq o(x^2) \\); correctly \\( x^2 + x \\sim x^2 = O(x^2) \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-017",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether \\( \\phi_n(x) = (\\ln x)^{-n} \\), for \\( n = 1, 2, 3, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\), and comment on how slowly it varies compared with \\( \\{x^{-n}\\} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "logarithm", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{(\\ln x)^{-(n+1)}}{(\\ln x)^{-n}} = \\frac{1}{\\ln x}", explanation: "The powers of \\( \\ln x \\) subtract, leaving the reciprocal logarithm." },
        { stepNumber: 2, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} \\frac{1}{\\ln x} = 0", explanation: "Since \\( \\ln x \\to +\\infty \\), its reciprocal vanishes, so \\( \\phi_{n+1} = o(\\phi_n) \\) for every \\( n \\)." },
        { stepNumber: 3, description: "Conclude asymptoticity.", workingLatex: "\\{(\\ln x)^{-n}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to +\\infty", explanation: "The negligibility test passes for all \\( n \\)." },
        { stepNumber: 4, description: "Compare its rate of decay with inverse powers.", workingLatex: "(\\ln x)^{-n} = o(1)\\ \\text{but}\\ x^{-1} = o\\bigl((\\ln x)^{-n}\\bigr)\\ \\forall n", explanation: "Logarithms vary far more slowly than powers: every \\( (\\ln x)^{-n} \\) decays slower than even \\( x^{-1} \\), so this gauge sequence resolves much finer (slower) variation." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = 1/\\ln x \\to 0 \\); it decays far more slowly than any \\( x^{-n} \\).",
    },
  },
  {
    id: "am1a-018",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 18",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using \\( \\Gamma(s) = \\int_0^{\\infty} t^{s-1} e^{-t}\\,dt \\) and the substitution \\( t = u^2 \\), evaluate \\( \\Gamma(\\tfrac12) \\). This constant fixes the leading coefficient in many large-parameter (Laplace/Watson) gauge expansions.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Gamma function", "Gaussian integral", "special functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the integral at \\( s = \\tfrac12 \\).", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = \\int_0^{\\infty} t^{-1/2} e^{-t}\\,dt", explanation: "Setting \\( s = \\tfrac12 \\) gives the exponent \\( s-1 = -\\tfrac12 \\) on \\( t \\)." },
        { stepNumber: 2, description: "Substitute \\( t = u^2 \\).", workingLatex: "t = u^2 \\implies dt = 2u\\,du,\\quad t^{-1/2} = \\frac{1}{u}", explanation: "The substitution removes the awkward half-power; the limits stay \\( 0 \\to \\infty \\)." },
        { stepNumber: 3, description: "Rewrite the integral.", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = \\int_0^{\\infty} \\frac{1}{u} e^{-u^2}\\,(2u\\,du) = 2\\int_0^{\\infty} e^{-u^2}\\,du", explanation: "The factor \\( u \\) cancels, leaving a Gaussian integral over the half-line." },
        { stepNumber: 4, description: "Insert the Gaussian value.", workingLatex: "\\int_0^{\\infty} e^{-u^2}\\,du = \\frac{\\sqrt{\\pi}}{2}", explanation: "This is the standard half-line Gaussian, obtained from \\( \\int_{-\\infty}^{\\infty} e^{-u^2}du = \\sqrt{\\pi} \\) by symmetry." },
        { stepNumber: 5, description: "Combine.", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = 2 \\cdot \\frac{\\sqrt{\\pi}}{2} = \\sqrt{\\pi}", explanation: "The factor \\( 2 \\) cancels the halving, giving \\( \\sqrt{\\pi} \\approx 1.7725 \\)." },
      ],
      finalAnswer: "\\( \\Gamma\\!\\left(\\tfrac12\\right) = \\sqrt{\\pi} \\).",
      canonicalAnswer: "sqrt(pi)",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level (5+ marks) ────
  // REVIEW: parts of this argument are a uniqueness proof (limit-extraction of coefficients) that is not numerically checkable.
  {
    id: "am1a-019",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose a function admits an asymptotic power-series expansion \\( f(x) \\sim \\sum_{n=0}^{\\infty} a_n x^n \\) as \\( x \\to 0^+ \\). Show that the coefficients \\( a_n \\) are determined uniquely by \\( f \\), by giving an explicit limit formula for each \\( a_n \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["uniqueness", "asymptotic expansion", "gauge functions", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State what the expansion means at each order.", workingLatex: "f(x) - \\sum_{n=0}^{N} a_n x^n = o(x^{N}) \\quad (x \\to 0^+)", explanation: "By definition of an asymptotic expansion in the gauge sequence \\( \\{x^n\\} \\), truncating after \\( x^N \\) leaves an error negligible compared with \\( x^N \\)." },
        { stepNumber: 2, description: "Extract the leading coefficient.", workingLatex: "a_0 = \\lim_{x \\to 0^+} f(x)", explanation: "Taking \\( N = 0 \\), \\( f(x) - a_0 = o(1) \\to 0 \\), so \\( a_0 \\) is forced to be the limit of \\( f \\)." },
        { stepNumber: 3, description: "Peel off \\( a_0 \\) and rescale.", workingLatex: "\\frac{f(x) - a_0}{x} = a_1 + a_2 x + \\cdots, \\qquad a_1 = \\lim_{x \\to 0^+}\\frac{f(x) - a_0}{x}", explanation: "Subtracting the known \\( a_0 \\) and dividing by \\( x \\) exposes \\( a_1 \\) as the next limit; the remainder is still \\( o(1) \\)." },
        { stepNumber: 4, description: "Write the general recursive limit.", workingLatex: "a_N = \\lim_{x \\to 0^+} \\frac{f(x) - \\sum_{n=0}^{N-1} a_n x^n}{x^{N}}", explanation: "Inductively, once \\( a_0,\\ldots,a_{N-1} \\) are fixed, dividing the remainder by \\( x^N \\) and taking the limit pins down \\( a_N \\) — each step uses the \\( o(x^{N-1}) \\) bound from the previous order." },
        { stepNumber: 5, description: "Argue uniqueness.", workingLatex: "\\text{Each } a_N\\ \\text{is a limit of } f \\implies \\text{the sequence } \\{a_n\\}\\ \\text{is unique}", explanation: "Every coefficient is expressed purely in terms of \\( f \\) (and the earlier coefficients, themselves limits of \\( f \\)). Since limits are unique when they exist, no two distinct coefficient sequences can serve the same \\( f \\)." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "f \\sim \\sum a_n x^n\\ \\text{determines } \\{a_n\\}\\ \\text{uniquely}", explanation: "The explicit limit formula is the certificate of uniqueness; note it is one-way — the same coefficients can belong to different functions (see beyond-all-orders)." },
      ],
      finalAnswer: "\\( a_N = \\lim_{x \\to 0^+}\\bigl[f(x) - \\sum_{n=0}^{N-1}a_n x^n\\bigr]/x^N \\); each coefficient is a limit of \\( f \\), hence unique.",
    },
  },
  // REVIEW: this is a proof that all power-series coefficients of e^{-1/x} vanish; the vanishing of each limit is checkable but the "deduce non-uniqueness" step is an existence/logic argument.
  {
    id: "am1a-020",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( e(x) = \\exp(-1/x) \\) for \\( x > 0 \\). Show that in any expansion \\( e(x) \\sim \\beta_0 + \\beta_1 x + \\beta_2 x^2 + \\cdots \\) valid as \\( x \\to 0^+ \\), every coefficient \\( \\beta_k = 0 \\). Hence explain why a function is not determined by its asymptotic power series.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["beyond all orders", "exponentially small", "uniqueness", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the coefficient-extraction formula.", workingLatex: "\\beta_k = \\lim_{x \\to 0^+} \\frac{e(x) - (\\beta_0 + \\cdots + \\beta_{k-1}x^{k-1})}{x^k}", explanation: "The coefficients of an asymptotic power series are obtained by successive division by \\( x^k \\) and taking limits (uniqueness result)." },
        { stepNumber: 2, description: "Compare \\( e(x) \\) with any positive power.", workingLatex: "\\frac{\\exp(-1/x)}{x^k} = \\frac{e^{-1/x}}{x^k}", explanation: "We test how the exponentially small \\( e^{-1/x} \\) measures against the gauge function \\( x^k \\)." },
        { stepNumber: 3, description: "Substitute \\( s = 1/x \\to +\\infty \\).", workingLatex: "\\frac{e^{-1/x}}{x^k} = s^{k} e^{-s} \\quad (s = 1/x \\to +\\infty)", explanation: "As \\( x \\to 0^+ \\), \\( s \\to +\\infty \\), and \\( x^{-k} = s^{k} \\); the expression becomes a power times a decaying exponential." },
        { stepNumber: 4, description: "Take the limit.", workingLatex: "\\lim_{s \\to +\\infty} s^{k} e^{-s} = 0 \\quad \\text{for every } k \\ge 0", explanation: "Exponential decay beats every power, so \\( e(x) = o(x^k) \\) for all \\( k \\) — it is smaller than every term of the gauge sequence." },
        { stepNumber: 5, description: "Deduce all coefficients vanish by induction.", workingLatex: "\\beta_0 = \\lim e(x) = 0 \\implies \\beta_1 = \\lim \\frac{e(x)}{x} = 0 \\implies \\cdots \\implies \\beta_k = 0", explanation: "With \\( \\beta_0 = 0 \\) the numerator in step 1 is just \\( e(x) \\) again; step 4 makes every such limit zero, so by induction all \\( \\beta_k = 0 \\)." },
        { stepNumber: 6, description: "Draw the non-uniqueness conclusion.", workingLatex: "g(x) \\sim \\sum a_n x^n \\implies g(x) + e(x) \\sim \\sum a_n x^n\\ \\text{too}", explanation: "Since \\( e(x) \\) has the zero power series, adding it to any \\( g \\) leaves the asymptotic series unchanged. Thus distinct functions share one series: the coefficients do NOT determine \\( f \\). The hidden \\( e^{-1/x} \\) is 'beyond all orders'." },
      ],
      finalAnswer: "All \\( \\beta_k = 0 \\) (since \\( s^k e^{-s} \\to 0 \\)); so \\( g \\) and \\( g + e^{-1/x} \\) share the same series — the series does not determine \\( f \\).",
    },
  },
  // REVIEW: induction proof of the reciprocal-series recursion; the d_n values below were checked numerically against the series of 1/f.
  {
    id: "am1a-021",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim a_0 + \\dfrac{a_1}{z} + \\dfrac{a_2}{z^2} + \\cdots \\) as \\( z \\to \\infty \\) with \\( a_0 \\neq 0 \\). Show that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\) for \\( n \\ge 1 \\). Then evaluate \\( d_1, d_2 \\) for \\( a_0 = 2,\\ a_1 = 3,\\ a_2 = 1 \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal of series", "asymptotic expansion", "recursion", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit a reciprocal series and impose \\( f \\cdot (1/f) = 1 \\).", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\qquad f(z)\\cdot\\frac{1}{f(z)} = 1", explanation: "Since \\( a_0 \\neq 0 \\), \\( 1/f \\) has a leading term \\( 1/a_0 \\); we determine the \\( d_n \\) by demanding the product be the constant \\( 1 \\)." },
        { stepNumber: 2, description: "Multiply the two series (Cauchy product).", workingLatex: "\\Bigl(\\sum_{j} a_j z^{-j}\\Bigr)\\frac{1}{a_0}\\Bigl(\\sum_{m} d_m z^{-m}\\Bigr) = \\frac{1}{a_0}\\sum_{n=0}^{\\infty}\\Bigl(\\sum_{k=0}^{n} d_{n-k}a_k\\Bigr) z^{-n}", explanation: "Collecting all ways the powers \\( a_k \\) and \\( d_{n-k} \\) combine to \\( z^{-n} \\) gives the inner convolution sum." },
        { stepNumber: 3, description: "Match coefficients of \\( z^{-n} \\) on both sides.", workingLatex: "n = 0:\\ \\frac{1}{a_0} d_0 a_0 = 1 \\implies d_0 = 1", explanation: "The right side must equal \\( 1 \\) (which is \\( z^{0} \\) only), so the constant term gives \\( d_0 = 1 \\)." },
        { stepNumber: 4, description: "Set higher coefficients to zero.", workingLatex: "n \\ge 1:\\ \\frac{1}{a_0}\\sum_{k=0}^{n} d_{n-k} a_k = 0 \\implies \\sum_{k=0}^{n} d_{n-k}a_k = 0", explanation: "All powers \\( z^{-n} \\) with \\( n \\ge 1 \\) are absent from the constant \\( 1 \\), so each convolution sum must vanish — exactly the stated recursion." },
        { stepNumber: 5, description: "Solve the recursion for \\( d_1 \\).", workingLatex: "d_1 a_0 + d_0 a_1 = 0 \\implies d_1 = -\\frac{a_1}{a_0} = -\\frac{3}{2}", explanation: "The \\( n=1 \\) relation isolates \\( d_1 \\); substituting \\( a_0=2,\\ a_1=3 \\) gives \\( -\\tfrac32 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_2 \\).", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0 \\implies d_2 = -\\frac{d_1 a_1 + a_2}{a_0} = -\\frac{(-\\tfrac32)(3) + 1}{2}", explanation: "The \\( n=2 \\) relation uses the already-found \\( d_1 \\); substitute the given coefficients." },
        { stepNumber: 7, description: "Simplify.", workingLatex: "d_2 = -\\frac{-\\tfrac92 + 1}{2} = -\\frac{-\\tfrac72}{2} = \\frac{7}{4}", explanation: "Arithmetic gives \\( d_2 = \\tfrac74 \\); a numerical check of \\( 1/(2+3/z+1/z^2) \\) confirms \\( d_1=-1.5,\\ d_2=1.75 \\)." },
      ],
      finalAnswer: "\\( d_0 = 1,\\ d_1 = -\\tfrac{3}{2},\\ d_2 = \\tfrac{7}{4} \\).",
    },
  },
  {
    id: "am1a-022",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that if \\( f \\) is continuous and \\( f(x) = o(\\phi(x)) \\) as \\( x \\to +\\infty \\), where \\( \\phi \\) is continuous, positive and non-decreasing, then \\( \\displaystyle\\int_a^x f(t)\\,dt = o\\bigl(x\\,\\phi(x)\\bigr) \\) as \\( x \\to +\\infty \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration of orders", "little-o", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Translate the hypothesis into an epsilon statement.", workingLatex: "\\forall \\varepsilon > 0\\ \\exists X:\\ x > X \\implies |f(x)| < \\varepsilon\\,\\phi(x)", explanation: "\\( f = o(\\phi) \\) means \\( |f|/\\phi \\to 0 \\); equivalently, beyond some \\( X \\) the bound \\( |f| < \\varepsilon\\phi \\) holds for any chosen \\( \\varepsilon \\)." },
        { stepNumber: 2, description: "Split the integral at \\( X \\).", workingLatex: "\\int_a^x f(t)\\,dt = \\int_a^{X} f(t)\\,dt + \\int_{X}^{x} f(t)\\,dt", explanation: "The first piece is a fixed constant \\( C := \\int_a^X f \\); only the tail can grow with \\( x \\)." },
        { stepNumber: 3, description: "Bound the tail using the epsilon bound.", workingLatex: "\\left|\\int_{X}^{x} f(t)\\,dt\\right| \\le \\int_{X}^{x} |f(t)|\\,dt < \\varepsilon \\int_{X}^{x} \\phi(t)\\,dt", explanation: "On \\( [X,x] \\) we may apply \\( |f| < \\varepsilon\\phi \\) under the integral sign." },
        { stepNumber: 4, description: "Bound the integral of \\( \\phi \\) using monotonicity.", workingLatex: "\\int_{X}^{x} \\phi(t)\\,dt \\le (x - X)\\,\\phi(x) \\le x\\,\\phi(x)", explanation: "Because \\( \\phi \\) is non-decreasing, \\( \\phi(t) \\le \\phi(x) \\) on \\( [X,x] \\); the interval length is at most \\( x \\)." },
        { stepNumber: 5, description: "Combine the pieces.", workingLatex: "\\left|\\int_a^x f(t)\\,dt\\right| \\le |C| + \\varepsilon\\, x\\,\\phi(x)", explanation: "Adding the fixed constant to the bounded tail gives a bound in terms of \\( x\\phi(x) \\) plus a constant." },
        { stepNumber: 6, description: "Divide by \\( x\\phi(x) \\) and take limsup.", workingLatex: "\\frac{1}{x\\phi(x)}\\left|\\int_a^x f\\right| \\le \\frac{|C|}{x\\phi(x)} + \\varepsilon", explanation: "Since \\( \\phi > 0 \\) is non-decreasing, \\( x\\phi(x) \\to \\infty \\), so the constant term vanishes; the limsup is \\( \\le \\varepsilon \\)." },
        { stepNumber: 7, description: "Let \\( \\varepsilon \\to 0 \\).", workingLatex: "\\limsup_{x\\to\\infty}\\frac{1}{x\\phi(x)}\\left|\\int_a^x f\\right| \\le \\varepsilon\\ \\forall\\varepsilon \\implies \\int_a^x f = o(x\\phi(x))", explanation: "As \\( \\varepsilon \\) is arbitrary, the limit is zero, which is precisely the required little-o statement." },
      ],
      finalAnswer: "\\( \\int_a^x f(t)\\,dt = o\\bigl(x\\,\\phi(x)\\bigr) \\) as \\( x \\to +\\infty \\).",
    },
  },
  // REVIEW: cosh sector estimate is a complex-analytic argument; the magnitude comparison e^{Re(z)} vs e^{-Re(z)} is the checkable core, the sector boundary discussion is qualitative.
  {
    id: "am1a-023",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Taking \\( \\delta > 0 \\) fixed, show that \\( \\cosh z \\sim \\tfrac12 e^{z} \\) as \\( |z| \\to \\infty \\) in the sector \\( -\\tfrac{\\pi}{2} + \\delta < \\arg z < \\tfrac{\\pi}{2} - \\delta \\). Explain why the estimate fails on the imaginary axis (\\( \\delta = 0 \\)).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cosh", "complex asymptotics", "sectors", "Stokes lines"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write cosh as a sum of two exponentials.", workingLatex: "\\cosh z = \\frac{1}{2}e^{z} + \\frac{1}{2}e^{-z}", explanation: "The two exponentials compete; whichever has the larger modulus dominates as \\( |z| \\to \\infty \\)." },
        { stepNumber: 2, description: "Compare their moduli via the real part.", workingLatex: "|e^{z}| = e^{\\operatorname{Re} z}, \\qquad |e^{-z}| = e^{-\\operatorname{Re} z}", explanation: "The modulus of \\( e^{z} \\) depends only on \\( \\operatorname{Re} z = |z|\\cos(\\arg z) \\)." },
        { stepNumber: 3, description: "Use the sector to sign the real part.", workingLatex: "|\\arg z| < \\tfrac{\\pi}{2} - \\delta \\implies \\cos(\\arg z) \\ge \\sin\\delta > 0 \\implies \\operatorname{Re} z \\ge |z|\\sin\\delta", explanation: "Staying \\( \\delta \\) away from \\( \\pm\\tfrac{\\pi}{2} \\) keeps \\( \\cos(\\arg z) \\) bounded below by the positive constant \\( \\sin\\delta \\), so \\( \\operatorname{Re} z \\to +\\infty \\)." },
        { stepNumber: 4, description: "Form the ratio of subdominant to dominant term.", workingLatex: "\\frac{\\tfrac12 e^{-z}}{\\tfrac12 e^{z}} = e^{-2z}, \\qquad |e^{-2z}| = e^{-2\\operatorname{Re} z} \\le e^{-2|z|\\sin\\delta}", explanation: "The recessive term is smaller by a factor whose modulus decays like \\( e^{-2|z|\\sin\\delta} \\)." },
        { stepNumber: 5, description: "Take the limit.", workingLatex: "e^{-2|z|\\sin\\delta} \\to 0 \\quad (|z| \\to \\infty)", explanation: "Hence \\( \\tfrac12 e^{-z} = o(\\tfrac12 e^{z}) \\), so \\( \\cosh z \\sim \\tfrac12 e^{z} \\) throughout the sector." },
        { stepNumber: 6, description: "Explain the breakdown at \\( \\delta = 0 \\).", workingLatex: "\\arg z = \\pm\\tfrac{\\pi}{2}:\\ \\operatorname{Re} z = 0 \\implies |e^{z}| = |e^{-z}| = 1", explanation: "On the imaginary axis the two exponentials have equal modulus — neither dominates — so there is no single recessive term: this is exactly a Stokes/anti-Stokes line where the asymptotic balance changes and the estimate fails." },
      ],
      finalAnswer: "\\( \\cosh z \\sim \\tfrac12 e^{z} \\) in the sector; on \\( \\arg z = \\pm\\tfrac{\\pi}{2} \\) (\\( \\delta=0 \\)) the terms balance, so it fails.",
    },
  },
  {
    id: "am1a-024",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The integral \\( F(x) = \\displaystyle\\int_0^{\\infty} \\frac{t\\,e^{-t}}{1 + xt}\\,dt \\) has the asymptotic expansion \\( F(x) \\sim \\sum_{n=0}^{\\infty} (-1)^n n!\\,x^{n+1} \\) as \\( x \\to 0^+ \\). Show that \\( \\{x^{n+1}\\} \\) is an asymptotic sequence as \\( x \\to 0^+ \\), and explain why the series diverges for every fixed \\( x > 0 \\) yet is still a valid asymptotic expansion.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Stieltjes integral", "divergent asymptotic series", "asymptotic sequence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the gauge sequence.", workingLatex: "\\phi_n(x) = x^{n+1}, \\quad n = 0, 1, 2, \\ldots", explanation: "Each term of the series is a constant multiple of \\( x^{n+1} \\); these powers are the scale functions." },
        { stepNumber: 2, description: "Check the asymptotic-sequence condition.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{n+2}}{x^{n+1}} = x \\to 0 \\quad (x \\to 0^+)", explanation: "Consecutive powers differ by one factor of \\( x \\), which vanishes, so \\( \\{x^{n+1}\\} \\) is asymptotic." },
        { stepNumber: 3, description: "Examine the size of the coefficients.", workingLatex: "a_n = (-1)^n n! \\implies |a_n| = n! \\to \\infty\\ \\text{very fast}", explanation: "The factorial growth of the coefficients is the source of divergence." },
        { stepNumber: 4, description: "Apply the ratio test at fixed \\( x \\).", workingLatex: "\\left|\\frac{a_{n+1}x^{n+2}}{a_n x^{n+1}}\\right| = (n+1)\\,x \\to \\infty \\quad (n \\to \\infty)", explanation: "For any fixed \\( x > 0 \\) the term ratio grows without bound, so the series of numbers diverges." },
        { stepNumber: 5, description: "Reconcile divergence with asymptoticity.", workingLatex: "F(x) - \\sum_{n=0}^{N} (-1)^n n!\\,x^{n+1} = O\\bigl(x^{N+2}\\bigr) \\quad (x \\to 0^+,\\ N\\ \\text{fixed})", explanation: "Asymptoticity is a statement about \\( x \\to 0^+ \\) at FIXED truncation \\( N \\), not about \\( N \\to \\infty \\). For small \\( x \\) the partial sums approximate \\( F \\) extremely well even though letting \\( N \\to \\infty \\) ruins them." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\text{divergent as a series, yet } F(x) \\sim \\sum (-1)^n n!\\,x^{n+1}\\ \\text{asymptotically}", explanation: "This is the defining feature of an asymptotic (as opposed to convergent) expansion: optimal truncation, not summation, extracts the accuracy." },
      ],
      finalAnswer: "\\( \\phi_{n+1}/\\phi_n = x \\to 0 \\) (asymptotic sequence); the series diverges since \\( (n+1)x \\to \\infty \\), but the fixed-\\( N \\) remainder is \\( O(x^{N+2}) \\), so it is a valid asymptotic expansion.",
    },
  },
  {
    id: "am1a-025",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour of the exponential integral \\( E_1(x) = \\displaystyle\\int_x^{\\infty} \\frac{e^{-t}}{t}\\,dt \\) as \\( x \\to +\\infty \\), and obtain the first two terms of its asymptotic expansion by integration by parts. Identify the gauge sequence.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["exponential integral", "integration by parts", "asymptotic expansion", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts with \\( u = 1/t \\).", workingLatex: "E_1(x) = \\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty} - \\int_x^{\\infty} \\frac{e^{-t}}{t^2}\\,dt", explanation: "Choose \\( dv = e^{-t}dt \\Rightarrow v = -e^{-t} \\) and \\( u = 1/t \\); this trades one power of \\( 1/t \\) for the next." },
        { stepNumber: 2, description: "Evaluate the boundary term.", workingLatex: "\\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty} = \\frac{e^{-x}}{x}", explanation: "At \\( t = \\infty \\) the term vanishes; at \\( t = x \\) it gives \\( e^{-x}/x \\) — the leading term." },
        { stepNumber: 3, description: "State the leading order.", workingLatex: "E_1(x) \\sim \\frac{e^{-x}}{x} \\quad (x \\to +\\infty)", explanation: "The remaining integral is smaller by a further factor \\( 1/t \\), so the boundary term dominates." },
        { stepNumber: 4, description: "Integrate by parts again on the remainder.", workingLatex: "\\int_x^{\\infty} \\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x^2} - 2\\int_x^{\\infty} \\frac{e^{-t}}{t^3}\\,dt", explanation: "Repeating with \\( u = 1/t^2 \\) extracts the next boundary term \\( e^{-x}/x^2 \\)." },
        { stepNumber: 5, description: "Assemble two terms.", workingLatex: "E_1(x) = \\frac{e^{-x}}{x} - \\frac{e^{-x}}{x^2} + 2\\int_x^{\\infty} \\frac{e^{-t}}{t^3}\\,dt", explanation: "Substituting back combines the boundary terms; the remaining integral is \\( O(e^{-x}x^{-3}) \\)." },
        { stepNumber: 6, description: "Write the expansion and gauge sequence.", workingLatex: "E_1(x) \\sim e^{-x}\\Bigl(\\frac{1}{x} - \\frac{1}{x^2} + \\frac{2}{x^3} - \\cdots\\Bigr), \\quad \\phi_n = e^{-x}x^{-n}", explanation: "The natural gauge functions are \\( e^{-x}x^{-n} \\); since \\( \\phi_{n+1}/\\phi_n = 1/x \\to 0 \\), they form an asymptotic sequence. (Numerically, \\( e^{-10}(1/10 - 1/100 + 2/1000 - 6/10^4) \\) matches \\( E_1(10) \\) to \\( \\sim 10^{-3} \\) relative.)" },
      ],
      finalAnswer: "\\( E_1(x) \\sim \\dfrac{e^{-x}}{x} - \\dfrac{e^{-x}}{x^2} + \\cdots \\); gauge sequence \\( \\{e^{-x}x^{-n}\\} \\) with ratio \\( 1/x \\to 0 \\).",
    },
  },
  {
    id: "am1a-026",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( \\phi_n(x) = x^{a_n} \\) with exponents \\( a_n = n + \\tfrac{1}{n+1} \\) for \\( n = 0, 1, 2, \\ldots \\). Determine whether \\( \\{\\phi_n\\} \\) is an asymptotic sequence (i) as \\( x \\to 0^+ \\) and (ii) as \\( x \\to +\\infty \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the exponent gap between consecutive terms.", workingLatex: "a_{n+1} - a_n = \\Bigl[(n+1) + \\tfrac{1}{n+2}\\Bigr] - \\Bigl[n + \\tfrac{1}{n+1}\\Bigr] = 1 + \\frac{1}{n+2} - \\frac{1}{n+1}", explanation: "The integer parts contribute \\( +1 \\); the fractional parts contribute a small correction." },
        { stepNumber: 2, description: "Show the gap is positive.", workingLatex: "\\frac{1}{n+2} - \\frac{1}{n+1} = \\frac{-1}{(n+1)(n+2)} > -1 \\implies a_{n+1} - a_n = 1 - \\frac{1}{(n+1)(n+2)} > 0", explanation: "The fractional correction is small and negative but never as large as \\( 1 \\), so each exponent strictly exceeds its predecessor." },
        { stepNumber: 3, description: "Form the ratio.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = x^{a_{n+1} - a_n}, \\qquad a_{n+1} - a_n > 0", explanation: "The ratio is a positive power of \\( x \\) for every \\( n \\)." },
        { stepNumber: 4, description: "Resolve the case \\( x \\to 0^+ \\).", workingLatex: "x \\to 0^+:\\ x^{a_{n+1}-a_n} \\to 0 \\implies \\phi_{n+1} = o(\\phi_n)", explanation: "A positive power of \\( x \\) vanishes at the origin, so the sequence IS asymptotic as \\( x \\to 0^+ \\)." },
        { stepNumber: 5, description: "Resolve the case \\( x \\to +\\infty \\).", workingLatex: "x \\to +\\infty:\\ x^{a_{n+1}-a_n} \\to +\\infty \\implies \\phi_{n+1} \\neq o(\\phi_n)", explanation: "The same positive power blows up at infinity, so each term grows relative to the previous one — NOT asymptotic. (To rank at infinity one would reverse the ordering.)" },
      ],
      finalAnswer: "Asymptotic as \\( x \\to 0^+ \\) (ratio \\( \\to 0 \\)); not asymptotic as \\( x \\to +\\infty \\) (ratio \\( \\to \\infty \\)).",
    },
  },
  {
    id: "am1a-027",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(x) = \\dfrac{1}{1 - x} + e^{-1/x} \\) for \\( 0 < x < 1 \\). Find the asymptotic expansion of \\( h \\) as \\( x \\to 0^+ \\) to order \\( x^3 \\), and state precisely why this expansion does not capture \\( h \\) completely.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["beyond all orders", "geometric series", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the rational part as a geometric series.", workingLatex: "\\frac{1}{1 - x} = 1 + x + x^2 + x^3 + \\cdots \\quad (|x| < 1)", explanation: "For small \\( x \\) this is the standard convergent geometric series." },
        { stepNumber: 2, description: "Assess the exponential part against the power gauge.", workingLatex: "\\frac{e^{-1/x}}{x^n} = s^{n}e^{-s} \\to 0\\ (s = 1/x \\to \\infty)\\ \\ \\forall n", explanation: "As shown for \\( \\exp(-1/x) \\), this term is smaller than every power \\( x^n \\), i.e. \\( e^{-1/x} = o(x^n) \\) for all \\( n \\)." },
        { stepNumber: 3, description: "Combine to the requested order.", workingLatex: "h(x) \\sim 1 + x + x^2 + x^3 \\quad (x \\to 0^+)", explanation: "The exponential contributes nothing at any algebraic order, so the power series comes entirely from \\( 1/(1-x) \\)." },
        { stepNumber: 4, description: "State the limitation.", workingLatex: "h(x) - (1 + x + x^2 + x^3 + \\cdots) = e^{-1/x} \\neq 0", explanation: "The full power series misses the exponentially small term entirely: the difference between \\( h \\) and ALL its algebraic terms is the non-zero \\( e^{-1/x} \\)." },
        { stepNumber: 5, description: "Interpret.", workingLatex: "e^{-1/x}\\ \\text{is 'beyond all orders' in the gauge } \\{x^n\\}", explanation: "To see the exponential one must enrich the gauge sequence with \\( e^{-1/x} \\); the power-series gauge is blind to it. This is why two different functions can share one asymptotic power series." },
      ],
      finalAnswer: "\\( h(x) \\sim 1 + x + x^2 + x^3 + \\cdots \\); the power series misses \\( e^{-1/x} \\), which is beyond all algebraic orders.",
    },
  },
  {
    id: "am1a-028",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Decide whether the relation \\( O(x^2)\\cdot O(x^3) = O(x^5) \\) and the (false) candidate \\( o(x) + o(x) = o(x^2) \\) are correct as \\( x \\to 0 \\). Prove the true one and give the correct version of the false one.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["algebra of orders", "order notation", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up representatives for the product rule.", workingLatex: "f = O(x^2):\\ |f| \\le A x^2,\\qquad g = O(x^3):\\ |g| \\le B x^3\\ \\ (0 < x < \\delta)", explanation: "Big-O means each function is bounded by a constant times its gauge near the limit point." },
        { stepNumber: 2, description: "Multiply the bounds.", workingLatex: "|fg| \\le AB\\,x^{2}x^{3} = AB\\,x^{5}", explanation: "The product of the bounds bounds the product, and the powers add: \\( x^2 \\cdot x^3 = x^5 \\)." },
        { stepNumber: 3, description: "Conclude the product rule is true.", workingLatex: "fg = O(x^5) \\quad \\checkmark", explanation: "A constant \\( AB \\) times \\( x^5 \\) bounds \\( fg \\), so \\( O(x^2)\\cdot O(x^3) = O(x^5) \\) holds." },
        { stepNumber: 4, description: "Test the addition claim.", workingLatex: "f, g = o(x):\\ \\frac{f}{x} \\to 0,\\ \\frac{g}{x} \\to 0 \\implies \\frac{f + g}{x} \\to 0", explanation: "Adding two functions negligible against \\( x \\) gives a function still negligible against \\( x \\) — the gauge does NOT change to \\( x^2 \\)." },
        { stepNumber: 5, description: "Give the correct addition rule.", workingLatex: "o(x) + o(x) = o(x), \\quad \\text{not } o(x^2)", explanation: "Summation keeps the SAME (largest) gauge; raising the power to \\( x^2 \\) is the common error. The claimed \\( o(x^2) \\) is false, e.g. \\( f = g = x^{3/2} = o(x) \\) but \\( f + g = 2x^{3/2} \\neq o(x^2) \\)." },
      ],
      finalAnswer: "\\( O(x^2)\\cdot O(x^3) = O(x^5) \\) is TRUE; \\( o(x)+o(x) = o(x^2) \\) is FALSE — correctly \\( o(x) + o(x) = o(x) \\).",
    },
  },
  {
    id: "am1a-029",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using Laplace's method or otherwise, show that \\( I(x) = \\displaystyle\\int_0^{\\pi/2} \\exp\\!\\bigl(-x\\,t^3\\cos t\\bigr)\\,dt \\) has leading-order behaviour \\( I(x) \\sim \\dfrac{1}{3x^{1/3}}\\,\\Gamma\\!\\left(\\tfrac13\\right) \\) as \\( x \\to +\\infty \\). State the gauge function controlling the leading term.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace method", "Gamma function", "gauge functions", "large-parameter integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate where the exponent is least negative.", workingLatex: "\\psi(t) = t^3\\cos t \\ge 0\\ \\text{on}\\ [0,\\tfrac{\\pi}{2}],\\quad \\psi(0) = 0", explanation: "The integrand is \\( e^{-x\\psi} \\); the dominant contribution as \\( x \\to \\infty \\) comes from where \\( \\psi \\) is smallest, namely the endpoint \\( t = 0 \\)." },
        { stepNumber: 2, description: "Approximate the exponent near \\( t = 0 \\).", workingLatex: "\\cos t = 1 - \\tfrac{t^2}{2} + \\cdots \\implies \\psi(t) = t^3\\cos t \\sim t^3", explanation: "Near the origin \\( \\cos t \\to 1 \\), so the exponent behaves like \\( t^3 \\) — a cubic (degenerate) maximum of the integrand at the endpoint." },
        { stepNumber: 3, description: "Replace the integral by its local model.", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t^3}\\,dt", explanation: "Only a shrinking neighbourhood of \\( t = 0 \\) matters, so we may extend the upper limit to \\( \\infty \\) and drop the higher-order part of \\( \\cos t \\); the tail is exponentially small." },
        { stepNumber: 4, description: "Substitute to reach a Gamma integral.", workingLatex: "u = x t^3 \\implies t = (u/x)^{1/3},\\ dt = \\frac{1}{3}x^{-1/3}u^{-2/3}\\,du", explanation: "This change of variable maps the cubic exponent to a standard \\( e^{-u} \\) form and pulls out the \\( x \\)-dependence." },
        { stepNumber: 5, description: "Evaluate using the Gamma function.", workingLatex: "I(x) \\sim \\frac{1}{3}x^{-1/3}\\int_0^{\\infty} u^{-2/3} e^{-u}\\,du = \\frac{1}{3}x^{-1/3}\\,\\Gamma\\!\\left(\\tfrac13\\right)", explanation: "The remaining integral is \\( \\Gamma(1 - \\tfrac23) = \\Gamma(\\tfrac13) \\), since \\( \\int_0^\\infty u^{s-1}e^{-u}du = \\Gamma(s) \\) with \\( s = \\tfrac13 \\)." },
        { stepNumber: 6, description: "State the gauge function.", workingLatex: "I(x) \\sim \\frac{\\Gamma(1/3)}{3}\\,x^{-1/3}, \\qquad \\text{gauge } = x^{-1/3}", explanation: "The leading scale is the fractional power \\( x^{-1/3} \\) — the cubic endpoint maximum produces a one-third power, not the \\( x^{-1/2} \\) of an ordinary interior maximum. Numerically at \\( x = 1000 \\), \\( I \\approx 0.08972 \\) matches \\( \\Gamma(1/3)x^{-1/3}/3 \\)." },
      ],
      finalAnswer: "\\( I(x) \\sim \\dfrac{\\Gamma(1/3)}{3}\\,x^{-1/3} \\) as \\( x \\to +\\infty \\); leading gauge function \\( x^{-1/3} \\).",
    },
  },
  {
    id: "am1a-030",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The functions \\( f(z) \\sim \\sum_{n=0}^{\\infty} a_n z^{-n} \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} b_n z^{-n} \\) as \\( z \\to \\infty \\). Show that \\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), justifying carefully why the cross terms beyond order \\( N \\) are negligible.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["product of series", "asymptotic expansion", "Cauchy product", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write each function as a truncation plus remainder.", workingLatex: "f(z) = \\sum_{j=0}^{N} a_j z^{-j} + R_f, \\quad R_f = o(z^{-N}); \\qquad g(z) = \\sum_{k=0}^{N} b_k z^{-k} + R_g,\\ R_g = o(z^{-N})", explanation: "By definition each asymptotic expansion approximates its function up to a remainder that is little-o of the last retained gauge term." },
        { stepNumber: 2, description: "Multiply the two truncations.", workingLatex: "\\Bigl(\\sum_{j=0}^{N} a_j z^{-j}\\Bigr)\\Bigl(\\sum_{k=0}^{N} b_k z^{-k}\\Bigr) = \\sum_{n=0}^{2N}\\Bigl(\\sum_{k=0}^{n} a_{n-k}b_k\\Bigr) z^{-n}", explanation: "Collecting powers \\( z^{-n} \\) gives the Cauchy product; the inner sum is exactly \\( c_n \\)." },
        { stepNumber: 3, description: "Split the product into wanted and surplus orders.", workingLatex: "\\sum_{n=0}^{2N} c_n z^{-n} = \\sum_{n=0}^{N} c_n z^{-n} + \\underbrace{\\sum_{n=N+1}^{2N} c_n z^{-n}}_{= O(z^{-(N+1)}) = o(z^{-N})}", explanation: "Every surplus term has power \\( z^{-n} \\) with \\( n \\ge N+1 \\), hence is \\( o(z^{-N}) \\) — already negligible at the order we claim." },
        { stepNumber: 4, description: "Bound the remainder cross terms.", workingLatex: "R_f \\cdot g,\\ f\\cdot R_g,\\ R_f R_g:\\quad |R_f\\, g| \\le |R_f|\\,|g| = o(z^{-N})\\cdot O(1) = o(z^{-N})", explanation: "Since \\( g \\to b_0 = O(1) \\) and \\( R_f = o(z^{-N}) \\), each remainder-bearing product is little-o of \\( z^{-N} \\); the same holds for \\( fR_g \\) and \\( R_f R_g \\)." },
        { stepNumber: 5, description: "Assemble the full product.", workingLatex: "f(z)g(z) = \\sum_{n=0}^{N} c_n z^{-n} + o(z^{-N})", explanation: "Adding step 3's surplus and step 4's cross terms, every contribution beyond order \\( N \\) is \\( o(z^{-N}) \\)." },
        { stepNumber: 6, description: "Quote the defining condition of an asymptotic expansion.", workingLatex: "f(z)g(z) - \\sum_{n=0}^{N} c_n z^{-n} = o(z^{-N}) \\quad \\forall N", explanation: "This is precisely the statement that \\( \\sum c_n z^{-n} \\) is the asymptotic expansion of \\( fg \\), valid for every truncation order \\( N \\)." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n}, \\qquad c_n = \\sum_{k=0}^{n} a_{n-k} b_k", explanation: "The product of two asymptotic power series is the asymptotic power series whose coefficients are the Cauchy convolution of the originals." },
      ],
      finalAnswer: "\\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\); all beyond-order terms are \\( o(z^{-N}) \\).",
    },
  },
];
