import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — am1a
 * "Order notation, gauge functions & asymptotic sequences"
 * Topic group: Asymptotic Sequences & Series
 *
 * Scope: Landau order notation (O, o) and asymptotic equivalence (~); gauge /
 * scale functions; testing whether a sequence of functions {phi_n} is asymptotic
 * (phi_{n+1} = o(phi_n)) as x -> 0 or x -> oo. Also: uniqueness of asymptotic
 * power-series coefficients and beyond-all-orders (subdominant) terms.
 *
 * Seeded (and varied in constants / limits / framing) from Cambridge Part II
 * Asymptotic Methods Example Sheet 1: Q3 (is {1 - cosh(x^n)} asymptotic),
 * Q4 (product of asymptotic series), Q5 (reciprocal of an asymptotic series),
 * Q6 (uniqueness of coefficients; e^{-1/x} beyond all orders), Q7 (cosh in
 * sectors of the complex plane), Q8 (integrating an o-estimate).
 *
 * 30 questions: 6 Foundation, 12 Standard, 12 Challenge.
 *
 * Numerical / symbolic spot-checks (python3 sympy + mpmath) were run for the
 * limit, series-expansion, recursion and integral claims; see commit notes.
 * Pure existence / uniqueness arguments carry a // REVIEW comment.
 */
export const questions: Question[] = [
  // ── Foundation: core order-notation technique in isolation ────
  {
    id: "am1a-001",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Determine the simplest power \\( x^p \\) such that \\( 1 - \\cos x = O(x^p) \\) as \\( x \\to 0 \\), and state whether the relation can be sharpened to \\( \\sim \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["order notation", "Taylor series", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the strategy for order at the origin.", workingLatex: "1 - \\cos x = O(x^p)\\ ?\\quad (x \\to 0)", explanation: "Order notation about \\( x = 0 \\) is governed by the smallest surviving power in the Taylor series. The plan is therefore to expand \\( \\cos x \\), subtract, identify the leading power, and confirm it with a ratio limit." },
        { stepNumber: 2, description: "Write down the Maclaurin series of cosine.", workingLatex: "\\cos x = 1 - \\frac{x^2}{2} + \\frac{x^4}{24} - \\cdots", explanation: "We need enough terms to see which one survives the subtraction. The standard cosine series has only even powers because cosine is an even function; the first three terms are plenty here." },
        { stepNumber: 3, description: "Subtract the series from 1.", workingLatex: "1 - \\cos x = 1 - \\Bigl(1 - \\frac{x^2}{2} + \\frac{x^4}{24} - \\cdots\\Bigr)", explanation: "Writing the subtraction out in full, before simplifying, makes the cancellation of the constant explicit. This is the move that exposes the genuine leading order." },
        { stepNumber: 4, description: "Cancel the constant term.", workingLatex: "1 - \\cos x = \\frac{x^2}{2} - \\frac{x^4}{24} + \\cdots", explanation: "The constant \\( 1 \\) cancels against the leading \\( 1 \\) of the series, and every remaining sign flips. The first surviving term is the \\( x^2 \\), so near the origin the function behaves quadratically." },
        { stepNumber: 5, description: "Factor out the leading power.", workingLatex: "1 - \\cos x = \\frac{x^2}{2}\\Bigl(1 - \\frac{x^2}{12} + \\cdots\\Bigr)", explanation: "Pulling out \\( x^2/2 \\) leaves a bracket that tends to \\( 1 \\) as \\( x \\to 0 \\). When the bracket has a finite, non-zero limit you have correctly isolated the genuine leading order — neither too high nor too low a power." },
        { stepNumber: 6, description: "Recall the limit condition for big-O.", workingLatex: "f = O(x^2) \\iff \\frac{f(x)}{x^2}\\ \\text{stays bounded as } x \\to 0", explanation: "Big-O of \\( x^2 \\) requires only that the ratio \\( f/x^2 \\) remain bounded near the origin. We will check this directly using the factored form, which makes the ratio trivial to read off." },
        { stepNumber: 7, description: "Take the limit of the ratio with \\( x^2 \\).", workingLatex: "\\frac{1-\\cos x}{x^2} = \\frac{1}{2}\\Bigl(1 - \\frac{x^2}{12} + \\cdots\\Bigr) \\to \\frac{1}{2} \\quad (x \\to 0)", explanation: "The ratio tends to the finite, non-zero value \\( \\tfrac12 \\), confirming \\( 1-\\cos x = O(x^2) \\). No smaller power works: dividing by \\( x^p \\) with \\( p > 2 \\) would force the limit to blow up, so \\( p = 2 \\) is the simplest power." },
        { stepNumber: 8, description: "Upgrade the relation to \\( \\sim \\).", workingLatex: "1 - \\cos x \\sim \\frac{1}{2}x^2 \\quad (x \\to 0)", explanation: "Because the ratio tends to a specific constant \\( \\tfrac12 \\) rather than merely staying bounded, we may name the leading term outright and write the sharper relation. The bare \\( O(x^2) \\) records only the power; the \\( \\sim \\) also pins the coefficient \\( \\tfrac12 \\)." },
      ],
      finalAnswer: "\\( p = 2 \\); and indeed \\( 1 - \\cos x \\sim \\tfrac{1}{2}x^2 \\) as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-002",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Decide whether \\( e^{-x} = o(x^{-3}) \\) as \\( x \\to +\\infty \\), justifying your answer with a limit.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["little-o", "exponential decay", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the definition of little-o.", workingLatex: "f = o(g) \\iff \\frac{f(x)}{g(x)} \\to 0", explanation: "Little-o is strictly stronger than big-O: it demands the ratio actually vanish, not merely stay bounded. So the entire test reduces to evaluating a single limit of the ratio." },
        { stepNumber: 2, description: "Identify the two functions and their gauge.", workingLatex: "f(x) = e^{-x}, \\qquad g(x) = x^{-3}", explanation: "Naming \\( f \\) and \\( g \\) explicitly keeps the negative exponent on the gauge straight; the question is whether the exponential is negligible against the (already decaying) power \\( x^{-3} \\)." },
        { stepNumber: 3, description: "Form the ratio \\( e^{-x}/x^{-3} \\).", workingLatex: "\\frac{e^{-x}}{x^{-3}} = e^{-x}\\cdot x^{3} = x^3 e^{-x}", explanation: "Dividing by \\( x^{-3} \\) is the same as multiplying by \\( x^3 \\); the negative gauge exponent flips up into a multiplying factor. A common slip is to leave it downstairs and misjudge the limit." },
        { stepNumber: 4, description: "Recall that exponentials beat powers.", workingLatex: "x^k e^{-x} \\to 0 \\quad (x \\to +\\infty)\\ \\text{for every fixed } k", explanation: "This is the central fact of the whole topic: \\( e^{-x} \\) decays faster than any fixed power of \\( x \\) grows. It is the reason exponential terms are so often negligible against algebraic ones." },
        { stepNumber: 5, description: "Evaluate the limit at \\( k = 3 \\).", workingLatex: "\\lim_{x \\to +\\infty} x^3 e^{-x} = 0", explanation: "Applying the rule with \\( k = 3 \\), the product vanishes. (If you want to see it directly, three rounds of L'Hopital on \\( x^3/e^{x} \\) reduce the numerator to a constant over \\( e^x \\to \\infty \\).)" },
        { stepNumber: 6, description: "Conclude.", workingLatex: "e^{-x} = o(x^{-3}) \\quad (x \\to +\\infty)", explanation: "The ratio tends to zero, so \\( e^{-x} \\) is asymptotically negligible compared with \\( x^{-3} \\) — indeed compared with every power of \\( x \\), since the same argument works for any exponent \\( k \\)." },
      ],
      finalAnswer: "Yes: \\( x^3 e^{-x} \\to 0 \\), so \\( e^{-x} = o(x^{-3}) \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-003",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find a simple function \\( g(x) \\) such that \\( \\sqrt{x^2 + 4x} \\sim g(x) \\) as \\( x \\to +\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant term inside the root.", workingLatex: "x^2 + 4x:\\quad x^2 \\gg 4x \\quad (x \\to +\\infty)", explanation: "Asymptotic equivalence is set by the dominant balance. Inside the root, \\( x^2 \\) grows quadratically while \\( 4x \\) grows only linearly, so \\( x^2 \\) is the term to factor out." },
        { stepNumber: 2, description: "Factor the dominant power out of the root.", workingLatex: "\\sqrt{x^2 + 4x} = \\sqrt{x^2\\Bigl(1 + \\frac{4}{x}\\Bigr)}", explanation: "Factoring \\( x^2 \\) out from under the root separates the leading scale from a small correction \\( 4/x \\). This is the standard manoeuvre for extracting leading behaviour from a root." },
        { stepNumber: 3, description: "Split the square root over the product.", workingLatex: "\\sqrt{x^2\\Bigl(1 + \\frac{4}{x}\\Bigr)} = \\sqrt{x^2}\\,\\sqrt{1 + \\frac{4}{x}}", explanation: "The square root of a product is the product of the square roots (both factors are positive here), which isolates the awkward bracket from the clean power." },
        { stepNumber: 4, description: "Simplify \\( \\sqrt{x^2} \\) for positive \\( x \\).", workingLatex: "\\sqrt{x^2} = x \\quad (x > 0) \\implies \\sqrt{x^2+4x} = x\\sqrt{1 + \\frac{4}{x}}", explanation: "For \\( x \\to +\\infty \\) we have \\( x > 0 \\), so \\( \\sqrt{x^2} = x \\) — no modulus sign needed. (Had the limit been \\( x \\to -\\infty \\), we would instead write \\( \\sqrt{x^2} = |x| = -x \\).)" },
        { stepNumber: 5, description: "Take the limit of the ratio with \\( g(x)=x \\).", workingLatex: "\\frac{\\sqrt{x^2+4x}}{x} = \\sqrt{1 + \\frac{4}{x}} \\to \\sqrt{1} = 1", explanation: "As \\( x \\to +\\infty \\) the correction \\( 4/x \\to 0 \\), so the remaining root tends to \\( 1 \\). A unit limit of the ratio is precisely the condition for the relation \\( \\sim \\)." },
        { stepNumber: 6, description: "State the asymptotic equivalence.", workingLatex: "\\sqrt{x^2 + 4x} \\sim x \\quad (x \\to +\\infty)", explanation: "The simplest gauge function capturing the leading behaviour is \\( g(x)=x \\). The \\( 4x \\) under the root affects only lower-order terms — expanding the root further would surface it as a \\( +2 \\) correction, \\( \\sqrt{x^2+4x} = x + 2 + O(1/x) \\)." },
      ],
      finalAnswer: "\\( \\sqrt{x^2+4x} \\sim x \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-004",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The candidate gauge sequence is \\( \\phi_n(x) = x^{2n} \\) for \\( n = 1, 2, 3, \\ldots \\). Verify that it is an asymptotic sequence as \\( x \\to 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the defining condition.", workingLatex: "\\{\\phi_n\\}\\ \\text{is asymptotic} \\iff \\phi_{n+1}(x) = o\\bigl(\\phi_n(x)\\bigr)\\ \\text{for every } n", explanation: "An asymptotic sequence is one in which each term is negligible compared with the one before it, in the stated limit. The whole test reduces to the ratio of consecutive terms." },
        { stepNumber: 2, description: "Write the two consecutive terms.", workingLatex: "\\phi_n(x) = x^{2n}, \\qquad \\phi_{n+1}(x) = x^{2(n+1)} = x^{2n+2}", explanation: "Writing both terms out before dividing keeps the exponent bookkeeping clean: incrementing \\( n \\) by one raises the exponent by two, not by one." },
        { stepNumber: 3, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{2n+2}}{x^{2n}} = x^{(2n+2)-2n} = x^2", explanation: "The exponents subtract, leaving just \\( x^2 \\), independent of \\( n \\). That independence is convenient: one check settles all \\( n \\) at once." },
        { stepNumber: 4, description: "Take the limit as \\( x \\to 0 \\).", workingLatex: "\\lim_{x \\to 0} x^2 = 0", explanation: "The ratio vanishes, so \\( \\phi_{n+1} = o(\\phi_n) \\) holds for every \\( n \\) — each term really is negligible compared with its predecessor near the origin." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\{x^{2n}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to 0", explanation: "The negligibility condition holds uniformly in \\( n \\), so the sequence qualifies. Note this is for \\( x \\to 0 \\): higher powers shrink faster near the origin; at infinity the ordering would reverse and the sequence would fail." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = x^2 \\to 0 \\), so \\( \\{x^{2n}\\} \\) is asymptotic as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-005",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Determine whether \\( \\ln x = O(x^{1/2}) \\) as \\( x \\to +\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["big-O", "logarithm", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the big-O condition.", workingLatex: "f = O(g) \\iff \\frac{f(x)}{g(x)}\\ \\text{stays bounded as } x \\to \\infty", explanation: "For \\( f = O(g) \\) it suffices that the ratio \\( f/g \\) remain bounded; if the ratio actually tends to a finite limit that certainly qualifies. So we evaluate the limit of \\( \\ln x / x^{1/2} \\)." },
        { stepNumber: 2, description: "Set up the ratio for the order test.", workingLatex: "\\frac{\\ln x}{x^{1/2}}", explanation: "This is the quantity whose limiting behaviour decides the question. Both numerator and denominator grow without bound, so we must resolve the competition between them." },
        { stepNumber: 3, description: "Identify the \\( \\infty/\\infty \\) form.", workingLatex: "\\ln x \\to \\infty,\\quad x^{1/2} \\to \\infty \\quad (x \\to \\infty)", explanation: "Both numerator and denominator diverge, so the quotient is the indeterminate form \\( \\infty/\\infty \\). That is exactly the setting in which L'Hopital's rule may be applied." },
        { stepNumber: 4, description: "Differentiate numerator and denominator.", workingLatex: "\\frac{d}{dx}\\ln x = \\frac{1}{x}, \\qquad \\frac{d}{dx}x^{1/2} = \\frac{1}{2}x^{-1/2}", explanation: "L'Hopital replaces the ratio of functions by the ratio of their derivatives. The derivative of \\( \\ln x \\) is \\( 1/x \\); the power rule gives \\( \\tfrac12 x^{-1/2} \\) for the root." },
        { stepNumber: 5, description: "Form and simplify the derivative ratio.", workingLatex: "\\frac{1/x}{\\tfrac{1}{2}x^{-1/2}} = \\frac{1}{x}\\cdot\\frac{2}{x^{-1/2}} = \\frac{2 x^{1/2}}{x} = \\frac{2}{x^{1/2}}", explanation: "Dividing the two derivatives and using \\( x^{-1/2} \\) in the denominator (which flips up) collapses everything to \\( 2x^{-1/2} \\). Keeping the algebra explicit avoids the common error of mishandling the negative exponent." },
        { stepNumber: 6, description: "Take the limit.", workingLatex: "\\lim_{x \\to \\infty} \\frac{2}{x^{1/2}} = 0", explanation: "As \\( x \\to \\infty \\) the denominator grows without bound, so the ratio of derivatives — and hence the original ratio — tends to zero." },
        { stepNumber: 7, description: "Conclude, upgrading to little-o.", workingLatex: "\\ln x = o(x^{1/2}) \\subset O(x^{1/2}) \\quad (x \\to +\\infty)", explanation: "The limit is not merely bounded but zero, so the stronger little-o holds, and little-o always implies big-O. Hence the \\( O(x^{1/2}) \\) claim is true: logarithms grow slower than every positive power of \\( x \\)." },
      ],
      finalAnswer: "Yes — in fact \\( \\ln x = o(x^{1/2}) \\), which is stronger than \\( O(x^{1/2}) \\).",
    },
  },
  {
    id: "am1a-006",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the gauge function \\( g(x) \\) of the form \\( c\\,x^p \\) with \\( c \\neq 0 \\) such that \\( \\sin x - x \\sim g(x) \\) as \\( x \\to 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "Taylor series", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the Maclaurin series of sine.", workingLatex: "\\sin x = x - \\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots", explanation: "As with any \\( \\sim \\) at the origin, start from the Taylor series so you can see exactly which term survives the subtraction. Sine has only odd powers because it is an odd function." },
        { stepNumber: 2, description: "Subtract \\( x \\) from the series.", workingLatex: "\\sin x - x = \\Bigl(x - \\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots\\Bigr) - x", explanation: "Writing the subtraction explicitly makes the cancellation visible. The leading linear term of the series is exactly the \\( x \\) we are removing." },
        { stepNumber: 3, description: "Cancel the linear term.", workingLatex: "\\sin x - x = -\\frac{x^3}{6} + \\frac{x^5}{120} - \\cdots", explanation: "The linear terms cancel exactly, exposing the cubic as the leading non-zero contribution. Forgetting that the \\( x \\) cancels is the classic slip that leaves you thinking the answer is order \\( x \\)." },
        { stepNumber: 4, description: "Factor out the leading cubic.", workingLatex: "\\sin x - x = -\\frac{x^3}{6}\\Bigl(1 - \\frac{x^2}{20} + \\cdots\\Bigr)", explanation: "Factoring \\( -x^3/6 \\) leaves a bracket tending to \\( 1 \\), confirming the cubic alone governs the leading behaviour. The bracket's finite non-zero limit is what makes \\( -x^3/6 \\) the exact gauge." },
        { stepNumber: 5, description: "Confirm the ratio tends to one.", workingLatex: "\\frac{\\sin x - x}{-x^3/6} = 1 - \\frac{x^2}{20} + \\cdots \\to 1 \\quad (x \\to 0)", explanation: "A ratio tending to \\( 1 \\) is precisely the meaning of \\( \\sim \\). This is the formal check behind reading the leading term off the series." },
        { stepNumber: 6, description: "State the equivalence and identify \\( c, p \\).", workingLatex: "\\sin x - x \\sim -\\frac{1}{6}x^3 \\quad (x \\to 0), \\qquad c = -\\frac{1}{6},\\ p = 3", explanation: "So the gauge function is \\( -\\tfrac16 x^3 \\). Keep the minus sign — \\( \\sin x \\) lies just below \\( x \\) for small positive \\( x \\), so the difference is negative." },
      ],
      finalAnswer: "\\( g(x) = -\\tfrac{1}{6}x^3 \\), i.e. \\( \\sin x - x \\sim -\\tfrac{1}{6}x^3 \\) as \\( x \\to 0 \\).",
    },
  },

  // ── Standard: typical sheet-level questions (3–4 marks) ────
  {
    id: "am1a-007",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether the sequence of functions \\( \\phi_n(x) = 1 - \\cosh(x^n) \\), for \\( n \\in \\{1, 2, 3, \\ldots\\} \\), is an asymptotic sequence as \\( x \\to 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "cosh", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the test we must verify.", workingLatex: "\\text{Need } \\phi_{n+1}(x) = o\\bigl(\\phi_n(x)\\bigr)\\ \\text{as } x \\to 0\\ \\text{for every } n", explanation: "To show the sequence is asymptotic we must show each term is negligible against its predecessor near the origin. The plan is to find the leading order of \\( \\phi_n \\), then test the ratio of consecutive leading orders." },
        { stepNumber: 2, description: "Recall the cosh series.", workingLatex: "\\cosh u = 1 + \\frac{u^2}{2!} + \\frac{u^4}{4!} + \\cdots", explanation: "Cosh is even, so its Maclaurin series contains only even powers of its argument. We will substitute \\( u = x^n \\) to expand \\( \\cosh(x^n) \\)." },
        { stepNumber: 3, description: "Expand cosh of the argument \\( x^n \\).", workingLatex: "\\cosh(x^n) = 1 + \\frac{(x^n)^2}{2!} + \\frac{(x^n)^4}{4!} + \\cdots = 1 + \\frac{x^{2n}}{2} + \\frac{x^{4n}}{24} + \\cdots", explanation: "Substituting \\( u = x^n \\) raises each even power: \\( u^2 = x^{2n} \\), \\( u^4 = x^{4n} \\). So the exponents appearing are even multiples of \\( n \\)." },
        { stepNumber: 4, description: "Subtract from 1 to form \\( \\phi_n \\).", workingLatex: "\\phi_n(x) = 1 - \\cosh(x^n) = -\\frac{x^{2n}}{2} - \\frac{x^{4n}}{24} - \\cdots", explanation: "The constant \\( 1 \\) cancels and every remaining sign flips, leaving a series of negative even powers. Every term is negative, so \\( \\phi_n < 0 \\) for small \\( x \\)." },
        { stepNumber: 5, description: "Read off the leading order of \\( \\phi_n \\).", workingLatex: "\\phi_n(x) \\sim -\\frac{x^{2n}}{2} \\quad (x \\to 0)", explanation: "As \\( x \\to 0 \\) the first term \\( -\\tfrac12 x^{2n} \\) dominates every later term, so it controls the size of \\( \\phi_n \\). The leading order is all we need for the ratio test." },
        { stepNumber: 6, description: "Form the ratio of consecutive leading terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} \\sim \\frac{-\\tfrac12 x^{2(n+1)}}{-\\tfrac12 x^{2n}} = \\frac{x^{2n+2}}{x^{2n}} = x^2", explanation: "Using the leading-order forms, the constant factors \\( -\\tfrac12 \\) cancel and the exponents subtract to give \\( x^2 \\). The limit of the ratio is governed entirely by these leading terms." },
        { stepNumber: 7, description: "Take the limit as \\( x \\to 0 \\).", workingLatex: "\\lim_{x \\to 0} \\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\lim_{x\\to 0} x^2 = 0", explanation: "The ratio vanishes for every \\( n \\), so each term is little-o of its predecessor — the negligibility condition is satisfied uniformly in \\( n \\)." },
        { stepNumber: 8, description: "Conclude.", workingLatex: "\\phi_{n+1} = o(\\phi_n)\\ \\forall n \\implies \\{1 - \\cosh(x^n)\\}\\ \\text{is asymptotic as } x \\to 0", explanation: "The defining condition holds for all \\( n \\), so the sequence is asymptotic at the origin. In effect it behaves just like the power sequence \\( \\{x^{2n}\\} \\), up to the common constant \\( -\\tfrac12 \\)." },
      ],
      finalAnswer: "Yes: \\( \\phi_n \\sim -\\tfrac12 x^{2n} \\), so \\( \\phi_{n+1}/\\phi_n \\to 0 \\) and the sequence is asymptotic as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-008",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether the sequence \\( \\phi_n(x) = e^{-nx} \\), for \\( n = 1, 2, 3, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "exponential", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the test.", workingLatex: "\\text{Need } \\phi_{n+1}(x) = o\\bigl(\\phi_n(x)\\bigr)\\ \\text{as } x \\to +\\infty\\ \\text{for every } n", explanation: "Asymptoticity is a statement about the ratio of consecutive terms in the stated limit; here that limit is \\( x \\to +\\infty \\). We compute the ratio and check it vanishes." },
        { stepNumber: 2, description: "Write the two consecutive terms.", workingLatex: "\\phi_n(x) = e^{-nx}, \\qquad \\phi_{n+1}(x) = e^{-(n+1)x}", explanation: "Writing both out keeps the exponents explicit before we combine them; incrementing \\( n \\) adds one more factor of \\( x \\) into the (negative) exponent." },
        { stepNumber: 3, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{e^{-(n+1)x}}{e^{-nx}}", explanation: "Substitute the definitions before simplifying, so the cancellation in the exponent is visible rather than done in your head." },
        { stepNumber: 4, description: "Simplify with the laws of exponents.", workingLatex: "\\frac{e^{-(n+1)x}}{e^{-nx}} = e^{-(n+1)x + nx} = e^{-x}", explanation: "Subtracting exponents collapses the quotient to a single exponential, independent of \\( n \\) — so one limit settles every case at once." },
        { stepNumber: 5, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} e^{-x} = 0", explanation: "The ratio decays to zero, so the negligibility condition \\( \\phi_{n+1} = o(\\phi_n) \\) holds for every \\( n \\)." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\{e^{-nx}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to +\\infty", explanation: "Each \\( e^{-(n+1)x} \\) is exponentially smaller than \\( e^{-nx} \\) by the fixed factor \\( e^{-x} \\), confirming the property holds uniformly in \\( n \\)." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = e^{-x} \\to 0 \\), so \\( \\{e^{-nx}\\} \\) is asymptotic as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-009",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the proposed sequence \\( \\phi_n(x) = x^{-n} \\sin x \\), for \\( n = 0, 1, 2, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\), and explain why \\( \\{x^{-n}\\} \\) is the natural underlying gauge sequence.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the test and note the shared factor.", workingLatex: "\\text{Need } \\phi_{n+1} = o(\\phi_n);\\quad \\phi_n(x) = x^{-n}\\sin x", explanation: "Each term shares the same oscillatory factor \\( \\sin x \\), differing only in the power of \\( x \\). We expect that factor to cancel in the ratio, leaving a pure power to test." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{-(n+1)}\\sin x}{x^{-n}\\sin x}", explanation: "Write the ratio in full before cancelling, so the shared factor \\( \\sin x \\) is visible in both numerator and denominator." },
        { stepNumber: 3, description: "Cancel the common factor.", workingLatex: "\\frac{x^{-(n+1)}\\sin x}{x^{-n}\\sin x} = x^{-(n+1)+n} = x^{-1} = \\frac{1}{x}", explanation: "The factor \\( \\sin x \\) cancels wherever it is non-zero, leaving a pure power; the oscillation plays no role in the ratio. Strictly the ratio is undefined at the zeros of \\( \\sin x \\), but the order relation only concerns the limiting envelope." },
        { stepNumber: 4, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} \\frac{1}{x} = 0", explanation: "The ratio tends to zero, so \\( \\phi_{n+1} = o(\\phi_n) \\) for every \\( n \\), giving an asymptotic sequence." },
        { stepNumber: 5, description: "Note the oscillatory factor is bounded.", workingLatex: "\\phi_n(x) = \\sin x \\cdot x^{-n}, \\qquad |\\sin x| \\le 1", explanation: "Because \\( \\sin x \\) is bounded by \\( 1 \\), it never changes orders of magnitude — it cannot promote or demote a term within the hierarchy. The decay is carried entirely by the powers \\( x^{-n} \\)." },
        { stepNumber: 6, description: "Identify the underlying gauge sequence.", workingLatex: "\\{\\phi_n\\}\\ \\text{ranks by } \\{x^{-n}\\}_{n \\ge 0}", explanation: "Since each ratio reduces to \\( 1/x \\) once the \\( \\sin x \\) cancels, the inverse-power sequence \\( \\{x^{-n}\\} \\) is the natural scale against which these terms are measured; the \\( \\sin x \\) is just a common bounded prefactor." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = 1/x \\to 0 \\); the gauge sequence is \\( \\{x^{-n}\\} \\).",
    },
  },
  {
    id: "am1a-010",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether \\( \\phi_n(x) = x^{n} (\\ln x)^{n} \\), for \\( n = 0, 1, 2, \\ldots \\), forms an asymptotic sequence as \\( x \\to 0^+ \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "logarithm", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the two consecutive terms.", workingLatex: "\\phi_n(x) = x^n(\\ln x)^n, \\qquad \\phi_{n+1}(x) = x^{n+1}(\\ln x)^{n+1}", explanation: "Both the power of \\( x \\) and the power of \\( \\ln x \\) advance together when \\( n \\) increases. Laying them side by side makes the ratio straightforward to form." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{n+1}(\\ln x)^{n+1}}{x^{n}(\\ln x)^{n}} = x \\ln x", explanation: "Both the power of \\( x \\) and the power of \\( \\ln x \\) drop by one in the quotient, leaving the single product \\( x\\ln x \\), independent of \\( n \\). So one limit decides all cases." },
        { stepNumber: 3, description: "Reshape the product into a quotient.", workingLatex: "\\lim_{x \\to 0^+} x \\ln x = \\lim_{x \\to 0^+} \\frac{\\ln x}{1/x}", explanation: "As \\( x \\to 0^+ \\), \\( \\ln x \\to -\\infty \\) and \\( x \\to 0 \\), so \\( x\\ln x \\) is the indeterminate form \\( 0 \\cdot \\infty \\). It must be rewritten as a quotient before L'Hopital's rule can be applied; dividing by \\( 1/x \\) does this." },
        { stepNumber: 4, description: "Confirm the \\( \\infty/\\infty \\) form.", workingLatex: "\\ln x \\to -\\infty, \\qquad \\frac{1}{x} \\to +\\infty \\quad (x \\to 0^+)", explanation: "Numerator and denominator both diverge, so the quotient is a legitimate \\( \\infty/\\infty \\) form and L'Hopital's rule applies." },
        { stepNumber: 5, description: "Apply L'Hopital's rule.", workingLatex: "\\frac{\\ln x}{1/x} \\;\\xrightarrow{\\text{L'H}}\\; \\frac{d(\\ln x)/dx}{d(1/x)/dx} = \\frac{1/x}{-1/x^2}", explanation: "Differentiate top and bottom separately: \\( \\ln x \\) gives \\( 1/x \\), and \\( 1/x = x^{-1} \\) gives \\( -x^{-2} \\). The ratio of derivatives replaces the original quotient." },
        { stepNumber: 6, description: "Simplify and take the limit.", workingLatex: "\\frac{1/x}{-1/x^2} = -\\frac{x^2}{x} = -x \\to 0 \\quad (x \\to 0^+)", explanation: "The compound fraction simplifies to \\( -x \\), which tends to zero. The power beats the logarithm, so the product \\( x\\ln x \\) vanishes." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "\\phi_{n+1} = o(\\phi_n)\\ \\forall n \\implies \\{x^n (\\ln x)^n\\}\\ \\text{is asymptotic as } x \\to 0^+", explanation: "Although each term carries a logarithm, the algebraic factor \\( x \\) forces the ratio to zero, so the sequence qualifies. The logarithm only slows the decay; it does not reverse the ordering." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = x\\ln x \\to 0 \\), so the sequence is asymptotic as \\( x \\to 0^+ \\).",
    },
  },
  {
    id: "am1a-011",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the sequence \\( \\phi_n(x) = x^{1/n} \\), for \\( n = 1, 2, 3, \\ldots \\), is NOT an asymptotic sequence as \\( x \\to 0^+ \\). State a rearrangement of the same functions that is asymptotic.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "counterexample", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compare the exponents of consecutive terms.", workingLatex: "\\frac{1}{n+1} < \\frac{1}{n} \\quad (n \\ge 1)", explanation: "The exponents decrease with \\( n \\). Near \\( x = 0 \\) a smaller positive power of \\( x \\) is the LARGER quantity (e.g. \\( x^{1/2} > x \\) for \\( 0 < x < 1 \\)), so the proposed ordering is already suspect." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{1/(n+1)}}{x^{1/n}} = x^{\\frac{1}{n+1} - \\frac{1}{n}}", explanation: "Subtract the exponents to combine the powers; the resulting exponent records whether the next term is smaller (positive exponent) or larger (negative exponent) than its predecessor." },
        { stepNumber: 3, description: "Combine the exponent over a common denominator.", workingLatex: "\\frac{1}{n+1} - \\frac{1}{n} = \\frac{n - (n+1)}{n(n+1)} = \\frac{-1}{n(n+1)}", explanation: "Putting the two fractions over the common denominator \\( n(n+1) \\) gives a numerator \\( n-(n+1) = -1 \\)." },
        { stepNumber: 4, description: "Sign the exponent.", workingLatex: "\\frac{1}{n+1} - \\frac{1}{n} = -\\frac{1}{n(n+1)} < 0 \\quad \\forall n \\ge 1", explanation: "The exponent is strictly negative for every \\( n \\), since \\( n(n+1) > 0 \\). A negative power of \\( x \\) is the danger sign at the origin." },
        { stepNumber: 5, description: "Take the limit of the ratio.", workingLatex: "\\lim_{x \\to 0^+} x^{-\\frac{1}{n(n+1)}} = +\\infty", explanation: "A negative power of \\( x \\) blows up as \\( x \\to 0^+ \\), so \\( \\phi_{n+1} \\) is in fact much LARGER than \\( \\phi_n \\) — the opposite of what an asymptotic sequence requires." },
        { stepNumber: 6, description: "Diagnose the failure and repair the ordering.", workingLatex: "\\phi_{n+1} \\neq o(\\phi_n);\\quad \\text{instead use } \\psi_n(x) = x^{1/(N-n)}\\ \\text{(decreasing exponent)}", explanation: "The list is simply in the wrong order. Reindexing so the exponents DECREASE — reading \\( x, x^{1/2}, x^{1/3}, \\ldots \\) the other way — gives a genuine asymptotic sequence as \\( x\\to 0^+ \\), since then each ratio is a positive power of \\( x \\) tending to zero." },
      ],
      finalAnswer: "Not asymptotic: \\( \\phi_{n+1}/\\phi_n = x^{-1/[n(n+1)]} \\to \\infty \\). Reordering with decreasing exponents (e.g. \\( x, x^{1/2}, x^{1/3},\\ldots \\) reversed) restores the property.",
    },
  },
  {
    id: "am1a-012",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( f(x) = \\dfrac{x}{1 + 2x} \\), find the order of the error \\( f(x) - x \\) as \\( x \\to 0 \\), expressing it as \\( \\sim c\\,x^p \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic equivalence", "geometric series", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the geometric series for the denominator.", workingLatex: "\\frac{1}{1 + u} = 1 - u + u^2 - \\cdots \\quad (|u| < 1)", explanation: "The factor \\( 1/(1+2x) \\) has the form \\( 1/(1+u) \\) with \\( u = 2x \\). For small \\( x \\) this is a convergent geometric series with alternating signs coming from the \\( + \\) in the denominator." },
        { stepNumber: 2, description: "Expand the denominator with \\( u = 2x \\).", workingLatex: "\\frac{1}{1+2x} = 1 - 2x + (2x)^2 - \\cdots = 1 - 2x + 4x^2 - \\cdots", explanation: "Substituting \\( u = 2x \\) and squaring gives \\( (2x)^2 = 4x^2 \\). Keeping a couple of terms is enough to capture the error to leading order." },
        { stepNumber: 3, description: "Multiply through by \\( x \\).", workingLatex: "f(x) = x\\bigl(1 - 2x + 4x^2 - \\cdots\\bigr) = x - 2x^2 + 4x^3 - \\cdots", explanation: "Distributing the leading \\( x \\) shifts every power up by one, giving the series for \\( f \\) itself. This is the move that prepares the subtraction of the linear part." },
        { stepNumber: 4, description: "Subtract the linear part.", workingLatex: "f(x) - x = -2x^2 + 4x^3 - \\cdots", explanation: "The leading \\( x \\) cancels exactly, exposing the quadratic term as the dominant remainder. This cancellation is why the error is order \\( x^2 \\), not order \\( x \\)." },
        { stepNumber: 5, description: "Read off the leading order.", workingLatex: "f(x) - x \\sim -2x^2 \\quad (x \\to 0), \\qquad c = -2,\\ p = 2", explanation: "The ratio \\( (f-x)/x^2 \\to -2 \\), so the error is exactly second order with coefficient \\( -2 \\). The negative sign reflects that \\( f(x) \\) sits just below \\( x \\) for small positive \\( x \\)." },
      ],
      finalAnswer: "\\( f(x) - x \\sim -2x^2 \\) as \\( x \\to 0 \\) (\\( c=-2,\\ p=2 \\)).",
    },
  },
  {
    id: "am1a-013",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Two functions satisfy \\( f(x) = o(x^3) \\) and \\( g(x) = O(x^2) \\) as \\( x \\to 0 \\). Determine the sharpest order statement you can make for the product \\( f(x)g(x) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["order notation", "algebra of orders", "little-o"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Translate each hypothesis into a ratio statement.", workingLatex: "\\frac{f(x)}{x^3} \\to 0, \\qquad \\frac{g(x)}{x^2}\\ \\text{stays bounded}", explanation: "\\( f = o(x^3) \\) gives a vanishing ratio; \\( g = O(x^2) \\) gives only a bounded ratio. That asymmetry is the entire content we are permitted to use — nothing more is known about \\( f \\) or \\( g \\)." },
        { stepNumber: 2, description: "Decide the target gauge for the product.", workingLatex: "x^3 \\cdot x^2 = x^5", explanation: "When two functions multiply, their gauge exponents add. So the natural gauge to test the product against is \\( x^{3+2} = x^5 \\)." },
        { stepNumber: 3, description: "Form the product of the two ratios.", workingLatex: "\\frac{f(x)g(x)}{x^5} = \\frac{f(x)}{x^3}\\cdot\\frac{g(x)}{x^2}", explanation: "Splitting \\( x^5 \\) back into \\( x^3 \\cdot x^2 \\) lets us write the combined ratio as the product of the two individual ratios, each of which we already understand." },
        { stepNumber: 4, description: "Apply the zero-times-bounded lemma.", workingLatex: "\\frac{f(x)}{x^3}\\cdot\\frac{g(x)}{x^2} \\to 0 \\cdot (\\text{bounded}) = 0", explanation: "A factor tending to zero times a bounded factor tends to zero — this is the key lemma. It would fail if the bounded factor were instead allowed to blow up, which is why the \\( O \\) hypothesis on \\( g \\) is exactly strong enough." },
        { stepNumber: 5, description: "State the sharpest result.", workingLatex: "f(x)g(x) = o(x^5) \\quad (x \\to 0)", explanation: "The product is little-o of \\( x^5 \\), and this is the sharpest order guaranteed: the \\( o \\) on \\( f \\) upgrades the combined estimate from a mere \\( O(x^5) \\) to the stronger \\( o(x^5) \\)." },
      ],
      finalAnswer: "\\( f(x)g(x) = o(x^5) \\) as \\( x \\to 0 \\).",
    },
  },
  {
    id: "am1a-014",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order asymptotic behaviour of \\( \\tanh x \\) as \\( x \\to +\\infty \\), and express \\( 1 - \\tanh x \\) in the form \\( \\sim c\\,e^{-\\lambda x} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["tanh", "asymptotic equivalence", "exponential decay"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write tanh in exponential form.", workingLatex: "\\tanh x = \\frac{\\sinh x}{\\cosh x} = \\frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}", explanation: "The definition exposes the two competing exponentials whose relative size determines the large-\\( x \\) behaviour. As \\( x \\to +\\infty \\) the \\( e^x \\) terms dominate the \\( e^{-x} \\) terms." },
        { stepNumber: 2, description: "Divide top and bottom by \\( e^{x} \\).", workingLatex: "\\tanh x = \\frac{e^x(1 - e^{-2x})}{e^x(1 + e^{-2x})} = \\frac{1 - e^{-2x}}{1 + e^{-2x}}", explanation: "Factoring out the dominant \\( e^{x} \\) from numerator and denominator leaves only the small quantity \\( e^{-2x} \\). This is the standard way to take the limit of a ratio of exponentials cleanly." },
        { stepNumber: 3, description: "Read off the leading order.", workingLatex: "e^{-2x} \\to 0 \\implies \\tanh x \\to \\frac{1 - 0}{1 + 0} = 1, \\qquad \\tanh x \\sim 1", explanation: "Both occurrences of \\( e^{-2x} \\) vanish, so numerator and denominator both tend to \\( 1 \\) and the limit is \\( 1 \\). Hence the leading-order behaviour is simply \\( \\tanh x \\sim 1 \\)." },
        { stepNumber: 4, description: "Subtract from 1 over a common denominator.", workingLatex: "1 - \\tanh x = \\frac{(1 + e^{-2x}) - (1 - e^{-2x})}{1 + e^{-2x}}", explanation: "To measure how fast \\( \\tanh x \\) approaches \\( 1 \\), we form the defect \\( 1 - \\tanh x \\) over the common denominator. Writing it out before simplifying keeps the cancellation transparent." },
        { stepNumber: 5, description: "Simplify the numerator.", workingLatex: "1 - \\tanh x = \\frac{2 e^{-2x}}{1 + e^{-2x}}", explanation: "The two \\( 1 \\)'s cancel and the two \\( e^{-2x} \\) terms add, giving numerator \\( 2e^{-2x} \\). This isolates the exponentially small defect from \\( 1 \\)." },
        { stepNumber: 6, description: "Take the leading order of the defect.", workingLatex: "1 - \\tanh x \\sim 2 e^{-2x} \\quad (x \\to +\\infty), \\qquad c = 2,\\ \\lambda = 2", explanation: "Since the denominator \\( 1 + e^{-2x} \\to 1 \\), the leading behaviour is just the numerator \\( 2e^{-2x} \\). The approach to \\( 1 \\) is exponentially fast, not algebraically — a hallmark of \\( \\tanh \\)." },
      ],
      finalAnswer: "\\( \\tanh x \\sim 1 \\); \\( 1 - \\tanh x \\sim 2e^{-2x} \\) as \\( x \\to +\\infty \\) (\\( c=2,\\ \\lambda=2 \\)).",
    },
  },
  {
    id: "am1a-015",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The functions \\( f \\) and \\( g \\) have asymptotic expansions \\( f(z) \\sim 1 + \\dfrac{2}{z} \\) and \\( g(z) \\sim 3 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\) (to the orders shown). Using \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), find the first three coefficients \\( c_0, c_1, c_2 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["product of series", "asymptotic expansion", "Cauchy product"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of each series.", workingLatex: "a_0 = 1,\\ a_1 = 2,\\ a_{\\ge 2} = 0; \\qquad b_0 = 3,\\ b_1 = 1,\\ b_{\\ge 2} = 0", explanation: "Reading off the given expansions identifies the only non-zero coefficients. Treating the unstated higher coefficients as zero is what lets the Cauchy convolution formula terminate at a finite number of terms." },
        { stepNumber: 2, description: "Recall the Cauchy-product formula.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k}\\, b_k", explanation: "The coefficient of \\( z^{-n} \\) in the product collects every pairing of an \\( a \\)-index and a \\( b \\)-index whose powers add to \\( n \\). We apply it for \\( n = 0, 1, 2 \\) in turn." },
        { stepNumber: 3, description: "Compute \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = 1 \\cdot 3 = 3", explanation: "The leading coefficient is simply the product of the two leading coefficients — the only way to make a \\( z^{0} \\) term is \\( z^0 \\cdot z^0 \\)." },
        { stepNumber: 4, description: "Compute \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(1) + (2)(3) = 1 + 6 = 7", explanation: "The order-\\( z^{-1} \\) coefficient collects every pairing whose exponents add to one: the index pairs \\( (0,1) \\) and \\( (1,0) \\). Both contribute here." },
        { stepNumber: 5, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + (2)(1) + 0 = 2", explanation: "Of the three index pairs summing to two, only \\( a_1 b_1 \\) survives, since the second-order coefficients \\( a_2 \\) and \\( b_2 \\) both vanish." },
        { stepNumber: 6, description: "Cross-check by direct multiplication.", workingLatex: "\\Bigl(1 + \\frac{2}{z}\\Bigr)\\Bigl(3 + \\frac{1}{z}\\Bigr) = 3 + \\frac{1}{z} + \\frac{6}{z} + \\frac{2}{z^2} = 3 + \\frac{7}{z} + \\frac{2}{z^2}", explanation: "Multiplying the two truncated series out by hand reproduces \\( c_0 = 3, c_1 = 7, c_2 = 2 \\), confirming the convolution formula gave the right coefficients." },
      ],
      finalAnswer: "\\( c_0 = 3,\\ c_1 = 7,\\ c_2 = 2 \\).",
    },
  },
  {
    id: "am1a-016",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Decide, with justification, whether the relation \\( x^2 + x = o(x^2) \\) holds as \\( x \\to +\\infty \\), and give the correct order statement.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["order notation", "little-o", "common error"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State what the little-o claim demands.", workingLatex: "x^2 + x = o(x^2) \\iff \\frac{x^2 + x}{x^2} \\to 0", explanation: "Little-o of \\( x^2 \\) requires the ratio with \\( x^2 \\) to vanish. So we form that ratio and inspect its limit; if the limit is anything other than zero, the claim is false." },
        { stepNumber: 2, description: "Form and simplify the ratio.", workingLatex: "\\frac{x^2 + x}{x^2} = \\frac{x^2}{x^2} + \\frac{x}{x^2} = 1 + \\frac{1}{x}", explanation: "Dividing term by term separates the dominant part (which gives \\( 1 \\)) from the subdominant part (which gives \\( 1/x \\)). This makes the limit easy to read." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty}\\Bigl(1 + \\frac{1}{x}\\Bigr) = 1 \\neq 0", explanation: "The ratio tends to \\( 1 \\), not \\( 0 \\), so the little-o claim is false. A common slip is to assume that any lower-order add-on makes the whole thing \\( o \\) — but the dominant \\( x^2 \\) keeps the ratio at \\( 1 \\)." },
        { stepNumber: 4, description: "State the correct relations.", workingLatex: "x^2 + x \\sim x^2, \\qquad x^2 + x = O(x^2) \\quad (x \\to +\\infty)", explanation: "A unit limit means \\( x^2 + x \\) is asymptotically equivalent to \\( x^2 \\), hence also \\( O(x^2) \\). It is only the subdominant part \\( x \\) on its own that is \\( o(x^2) \\)." },
      ],
      finalAnswer: "No, \\( x^2 + x \\neq o(x^2) \\); correctly \\( x^2 + x \\sim x^2 = O(x^2) \\) as \\( x \\to +\\infty \\).",
    },
  },
  {
    id: "am1a-017",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine whether \\( \\phi_n(x) = (\\ln x)^{-n} \\), for \\( n = 1, 2, 3, \\ldots \\), is an asymptotic sequence as \\( x \\to +\\infty \\), and comment on how slowly it varies compared with \\( \\{x^{-n}\\} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "logarithm", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the two consecutive terms.", workingLatex: "\\phi_n(x) = (\\ln x)^{-n}, \\qquad \\phi_{n+1}(x) = (\\ln x)^{-(n+1)}", explanation: "Treating \\( \\ln x \\) as a single quantity raised to a power, the two terms differ only in that power. This sets up a clean ratio in the next step." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{(\\ln x)^{-(n+1)}}{(\\ln x)^{-n}} = (\\ln x)^{-1} = \\frac{1}{\\ln x}", explanation: "The powers of \\( \\ln x \\) subtract just like ordinary powers, leaving the reciprocal logarithm — independent of \\( n \\), so one limit settles every case." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{x \\to +\\infty} \\frac{1}{\\ln x} = 0", explanation: "Since \\( \\ln x \\to +\\infty \\), its reciprocal vanishes, so \\( \\phi_{n+1} = o(\\phi_n) \\) for every \\( n \\). The decay is genuine but slow, because \\( \\ln x \\) grows so feebly." },
        { stepNumber: 4, description: "Conclude asymptoticity.", workingLatex: "\\{(\\ln x)^{-n}\\}_{n \\ge 1}\\ \\text{is an asymptotic sequence as } x \\to +\\infty", explanation: "The negligibility test passes for all \\( n \\), so the sequence is asymptotic — but notice the ratio tends to zero very slowly, since the logarithm is such a weakly growing function." },
        { stepNumber: 5, description: "Compare its decay rate with inverse powers.", workingLatex: "x^{-1} = o\\bigl((\\ln x)^{-n}\\bigr)\\ \\forall n", explanation: "Logarithms vary far more slowly than powers: even \\( x^{-1} \\) is negligible against every \\( (\\ln x)^{-n} \\), because \\( x^{-1}/(\\ln x)^{-n} = (\\ln x)^n/x \\to 0 \\). So this gauge sequence resolves much finer, slower variation than the power scale \\( \\{x^{-n}\\} \\) ever could." },
      ],
      finalAnswer: "Yes: \\( \\phi_{n+1}/\\phi_n = 1/\\ln x \\to 0 \\); it decays far more slowly than any \\( x^{-n} \\).",
    },
  },
  {
    id: "am1a-018",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 18",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using \\( \\Gamma(s) = \\int_0^{\\infty} t^{s-1} e^{-t}\\,dt \\) and the substitution \\( t = u^2 \\), evaluate \\( \\Gamma(\\tfrac12) \\). This constant fixes the leading coefficient in many large-parameter (Laplace/Watson) gauge expansions.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Gamma function", "Gaussian integral", "special functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the integral at \\( s = \\tfrac12 \\).", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = \\int_0^{\\infty} t^{(1/2)-1} e^{-t}\\,dt = \\int_0^{\\infty} t^{-1/2} e^{-t}\\,dt", explanation: "Setting \\( s = \\tfrac12 \\) gives the exponent \\( s-1 = -\\tfrac12 \\) on \\( t \\). The half-power is awkward to integrate directly, which motivates the suggested substitution." },
        { stepNumber: 2, description: "Set up the substitution \\( t = u^2 \\).", workingLatex: "t = u^2 \\implies dt = 2u\\,du", explanation: "Differentiating \\( t = u^2 \\) gives \\( dt = 2u\\,du \\). Because \\( t \\) ranges over \\( [0,\\infty) \\) and we take \\( u \\ge 0 \\), the limits stay \\( 0 \\to \\infty \\)." },
        { stepNumber: 3, description: "Rewrite the half-power in terms of \\( u \\).", workingLatex: "t^{-1/2} = (u^2)^{-1/2} = \\frac{1}{u} \\quad (u \\ge 0)", explanation: "The substitution clears the half-power: \\( (u^2)^{-1/2} = u^{-1} \\). Taking the positive root is justified since \\( u \\ge 0 \\) on the range of integration." },
        { stepNumber: 4, description: "Substitute and cancel.", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = \\int_0^{\\infty} \\frac{1}{u}\\, e^{-u^2}\\,(2u\\,du) = 2\\int_0^{\\infty} e^{-u^2}\\,du", explanation: "Inserting \\( t^{-1/2} = 1/u \\), \\( e^{-t} = e^{-u^2} \\) and \\( dt = 2u\\,du \\), the factor \\( u \\) cancels the \\( 1/u \\), leaving a clean Gaussian integral over the half-line with a factor \\( 2 \\) outside." },
        { stepNumber: 5, description: "Insert the half-line Gaussian value.", workingLatex: "\\int_0^{\\infty} e^{-u^2}\\,du = \\frac{1}{2}\\int_{-\\infty}^{\\infty} e^{-u^2}\\,du = \\frac{1}{2}\\sqrt{\\pi}", explanation: "By the evenness of \\( e^{-u^2} \\), the half-line integral is half the full Gaussian \\( \\int_{-\\infty}^{\\infty} e^{-u^2}du = \\sqrt{\\pi} \\) — the standard result you should commit to memory." },
        { stepNumber: 6, description: "Combine.", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = 2 \\cdot \\frac{\\sqrt{\\pi}}{2} = \\sqrt{\\pi}", explanation: "The factor \\( 2 \\) cancels the halving, giving \\( \\sqrt{\\pi} \\approx 1.7725 \\) — the constant that seeds Laplace- and Watson-type leading coefficients throughout the course." },
      ],
      finalAnswer: "\\( \\Gamma\\!\\left(\\tfrac12\\right) = \\sqrt{\\pi} \\).",
      canonicalAnswer: "sqrt(pi)",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level (5+ marks) ────
  // REVIEW: parts of this argument are a uniqueness proof (limit-extraction of coefficients) that is not numerically checkable.
  {
    id: "am1a-019",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose a function admits an asymptotic power-series expansion \\( f(x) \\sim \\sum_{n=0}^{\\infty} a_n x^n \\) as \\( x \\to 0^+ \\). Show that the coefficients \\( a_n \\) are determined uniquely by \\( f \\), by giving an explicit limit formula for each \\( a_n \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["uniqueness", "asymptotic expansion", "gauge functions", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State what the expansion means at each order.", workingLatex: "f(x) - \\sum_{n=0}^{N} a_n x^n = o(x^{N}) \\quad (x \\to 0^+)", explanation: "By definition of an asymptotic expansion in the gauge sequence \\( \\{x^n\\} \\), truncating after \\( x^N \\) leaves an error negligible compared with the last retained term \\( x^N \\). This is the only fact we are allowed to use." },
        { stepNumber: 2, description: "Specialise to order zero.", workingLatex: "N = 0:\\quad f(x) - a_0 = o(1) \\quad (x \\to 0^+)", explanation: "Taking \\( N = 0 \\) retains only the constant term. The remainder \\( o(1) \\) means the difference \\( f(x) - a_0 \\) tends to zero, which is about to pin down \\( a_0 \\)." },
        { stepNumber: 3, description: "Extract the leading coefficient.", workingLatex: "o(1) \\to 0 \\implies a_0 = \\lim_{x \\to 0^+} f(x)", explanation: "Since the remainder vanishes, \\( a_0 \\) is forced to equal the limit of \\( f \\) at the origin — there is no freedom in it whatsoever." },
        { stepNumber: 4, description: "Peel off \\( a_0 \\) and rescale.", workingLatex: "\\frac{f(x) - a_0}{x} = a_1 + a_2 x + \\cdots = a_1 + o(1)", explanation: "Subtracting the now-known \\( a_0 \\) and dividing by \\( x \\) shifts the whole series down one order. The new leading term is \\( a_1 \\) and the new remainder is again \\( o(1) \\)." },
        { stepNumber: 5, description: "Extract the next coefficient.", workingLatex: "a_1 = \\lim_{x \\to 0^+}\\frac{f(x) - a_0}{x}", explanation: "Taking the limit of the rescaled quantity isolates \\( a_1 \\) just as before. The legitimacy of dividing by \\( x \\) relies on the \\( o(1) \\) bound from the order-zero step." },
        { stepNumber: 6, description: "Write the general recursive limit.", workingLatex: "a_N = \\lim_{x \\to 0^+} \\frac{f(x) - \\sum_{n=0}^{N-1} a_n x^n}{x^{N}}", explanation: "Inductively, once \\( a_0,\\ldots,a_{N-1} \\) are fixed, subtracting them and dividing by \\( x^N \\) leaves \\( a_N + o(1) \\); the limit pins down \\( a_N \\). Each step relies on the \\( o(x^{N-1}) \\) bound from the previous order to make the division legitimate." },
        { stepNumber: 7, description: "Argue uniqueness from the formula.", workingLatex: "\\text{Each } a_N\\ \\text{is a limit built from } f \\implies \\text{the sequence } \\{a_n\\}\\ \\text{is unique}", explanation: "Every coefficient is expressed purely in terms of \\( f \\) and the earlier coefficients (themselves limits of \\( f \\)). Since a limit, when it exists, is unique, no two distinct coefficient sequences can serve the same \\( f \\)." },
        { stepNumber: 8, description: "Conclude, and note the one-way nature.", workingLatex: "f \\sim \\sum a_n x^n\\ \\text{determines } \\{a_n\\}\\ \\text{uniquely}", explanation: "The explicit limit formula is the certificate of uniqueness. Crucially the implication is one-way: the same coefficients can belong to different functions, because beyond-all-orders terms like \\( e^{-1/x} \\) are invisible to this construction (see the next question)." },
      ],
      finalAnswer: "\\( a_N = \\lim_{x \\to 0^+}\\bigl[f(x) - \\sum_{n=0}^{N-1}a_n x^n\\bigr]/x^N \\); each coefficient is a limit of \\( f \\), hence unique.",
    },
  },
  // REVIEW: this is a proof that all power-series coefficients of e^{-1/x} vanish; the vanishing of each limit is checkable but the "deduce non-uniqueness" step is an existence/logic argument.
  {
    id: "am1a-020",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( e(x) = \\exp(-1/x) \\) for \\( x > 0 \\). Show that in any expansion \\( e(x) \\sim \\beta_0 + \\beta_1 x + \\beta_2 x^2 + \\cdots \\) valid as \\( x \\to 0^+ \\), every coefficient \\( \\beta_k = 0 \\). Hence explain why a function is not determined by its asymptotic power series.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["beyond all orders", "exponentially small", "uniqueness", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the coefficient-extraction formula.", workingLatex: "\\beta_k = \\lim_{x \\to 0^+} \\frac{e(x) - (\\beta_0 + \\cdots + \\beta_{k-1}x^{k-1})}{x^k}", explanation: "From the uniqueness result, the coefficients of an asymptotic power series are obtained by successive subtraction, division by \\( x^k \\), and taking limits. We now apply it to \\( e(x) = e^{-1/x} \\)." },
        { stepNumber: 2, description: "Set up the ratio against a single power.", workingLatex: "\\frac{e^{-1/x}}{x^k}", explanation: "To evaluate each \\( \\beta_k \\) we must understand how the exponentially small \\( e^{-1/x} \\) measures against the gauge function \\( x^k \\). So we study this ratio first, for general \\( k \\)." },
        { stepNumber: 3, description: "Substitute \\( s = 1/x \\to +\\infty \\).", workingLatex: "\\frac{e^{-1/x}}{x^k} = x^{-k} e^{-1/x} = s^{k} e^{-s} \\qquad (s = 1/x \\to +\\infty)", explanation: "As \\( x \\to 0^+ \\) the new variable \\( s = 1/x \\to +\\infty \\), and \\( x^{-k} = s^{k} \\). The ratio becomes a power times a decaying exponential, a form whose limit we know." },
        { stepNumber: 4, description: "Take the limit.", workingLatex: "\\lim_{s \\to +\\infty} s^{k} e^{-s} = 0 \\quad \\text{for every } k \\ge 0", explanation: "Exponential decay beats every fixed power, so the limit is zero for all \\( k \\). Equivalently \\( e(x) = o(x^k) \\) for all \\( k \\) — it is smaller than every term of the gauge sequence \\( \\{x^k\\} \\)." },
        { stepNumber: 5, description: "Deduce all coefficients vanish by induction.", workingLatex: "\\beta_0 = \\lim e(x) = 0 \\implies \\beta_1 = \\lim \\frac{e(x)}{x} = 0 \\implies \\cdots \\implies \\beta_k = 0", explanation: "With \\( \\beta_0 = 0 \\), the numerator in step 1 collapses back to \\( e(x) \\) at every stage; step 4 makes each such limit zero. By induction all \\( \\beta_k = 0 \\)." },
        { stepNumber: 6, description: "Draw the non-uniqueness conclusion.", workingLatex: "g(x) \\sim \\sum a_n x^n \\implies g(x) + e(x) \\sim \\sum a_n x^n\\ \\text{too}", explanation: "Since \\( e(x) \\) has the identically-zero power series, adding it to any \\( g \\) leaves the asymptotic series unchanged. Thus two distinct functions share one series: the coefficients do NOT determine \\( f \\). The hidden \\( e^{-1/x} \\) is said to lie 'beyond all orders'." },
      ],
      finalAnswer: "All \\( \\beta_k = 0 \\) (since \\( s^k e^{-s} \\to 0 \\)); so \\( g \\) and \\( g + e^{-1/x} \\) share the same series — the series does not determine \\( f \\).",
    },
  },
  // REVIEW: induction proof of the reciprocal-series recursion; the d_n values below were checked numerically against the series of 1/f.
  {
    id: "am1a-021",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim a_0 + \\dfrac{a_1}{z} + \\dfrac{a_2}{z^2} + \\cdots \\) as \\( z \\to \\infty \\) with \\( a_0 \\neq 0 \\). Show that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\) for \\( n \\ge 1 \\). Then evaluate \\( d_1, d_2 \\) for \\( a_0 = 2,\\ a_1 = 3,\\ a_2 = 1 \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal of series", "asymptotic expansion", "recursion", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit a reciprocal series with the right leading term.", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\qquad f(z)\\cdot\\frac{1}{f(z)} = 1", explanation: "Since \\( a_0 \\neq 0 \\), \\( 1/f \\) is finite at leading order with value \\( 1/a_0 \\). We determine the unknown \\( d_n \\) by demanding that the product of the two series be the constant \\( 1 \\)." },
        { stepNumber: 2, description: "Multiply the two series as a Cauchy product.", workingLatex: "\\Bigl(\\sum_{j} a_j z^{-j}\\Bigr)\\frac{1}{a_0}\\Bigl(\\sum_{m} d_m z^{-m}\\Bigr) = \\frac{1}{a_0}\\sum_{n=0}^{\\infty}\\Bigl(\\sum_{k=0}^{n} d_{n-k}a_k\\Bigr) z^{-n}", explanation: "Collecting every way the powers \\( a_k z^{-k} \\) and \\( d_{n-k} z^{-(n-k)} \\) combine to \\( z^{-n} \\) gives the inner convolution sum — exactly the structure of a series product." },
        { stepNumber: 3, description: "Match the constant term.", workingLatex: "n = 0:\\quad \\frac{1}{a_0}\\,(d_0 a_0) = 1 \\implies d_0 = 1", explanation: "The product must equal \\( 1 = z^0 \\), so the only \\( z^0 \\) coefficient gives \\( d_0 a_0 / a_0 = 1 \\), forcing \\( d_0 = 1 \\)." },
        { stepNumber: 4, description: "Force all higher coefficients to vanish.", workingLatex: "n \\ge 1:\\quad \\frac{1}{a_0}\\sum_{k=0}^{n} d_{n-k} a_k = 0 \\implies \\sum_{k=0}^{n} d_{n-k}a_k = 0", explanation: "Every power \\( z^{-n} \\) with \\( n \\ge 1 \\) is absent from the constant \\( 1 \\), so each convolution sum must be zero — precisely the stated recursion for the \\( d_n \\)." },
        { stepNumber: 5, description: "Write the \\( n=1 \\) relation.", workingLatex: "n = 1:\\quad d_1 a_0 + d_0 a_1 = 0", explanation: "The \\( n=1 \\) convolution has just the two terms \\( k=0 \\) and \\( k=1 \\). With \\( d_0 \\) already known, this is a single linear equation in \\( d_1 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_1 \\) and substitute.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{a_1}{a_0} = -\\frac{3}{2}", explanation: "Isolating \\( d_1 \\) and using \\( d_0 = 1 \\) gives \\( -a_1/a_0 \\). Substituting \\( a_0 = 2,\\ a_1 = 3 \\) yields \\( -\\tfrac32 \\)." },
        { stepNumber: 7, description: "Write out the \\( n=2 \\) relation.", workingLatex: "n = 2:\\quad \\sum_{k=0}^{2} d_{2-k} a_k = d_2 a_0 + d_1 a_1 + d_0 a_2 = 0", explanation: "The \\( n=2 \\) convolution has three terms. Two of them, \\( d_1 a_1 \\) and \\( d_0 a_2 \\), are already known, so this is a linear equation in the single unknown \\( d_2 \\)." },
        { stepNumber: 8, description: "Rearrange for \\( d_2 \\).", workingLatex: "d_2 = -\\frac{d_1 a_1 + d_0 a_2}{a_0} = -\\frac{(-\\tfrac32)(3) + (1)(1)}{2}", explanation: "Move the two known terms across and divide by \\( a_0 \\). Feed in \\( d_1 = -\\tfrac32 \\), \\( d_0 = 1 \\) and the given \\( a_1 = 3,\\ a_2 = 1 \\)." },
        { stepNumber: 9, description: "Simplify the arithmetic.", workingLatex: "d_2 = -\\frac{-\\tfrac92 + 1}{2} = -\\frac{-\\tfrac72}{2} = \\frac{7}{4}", explanation: "Compute \\( (-\\tfrac32)(3) = -\\tfrac92 \\), add \\( 1 \\) to get \\( -\\tfrac72 \\), then divide by \\( -a_0 = -2 \\) to land on \\( \\tfrac74 \\). A numerical check of \\( 1/(2+3/z+1/z^2) \\) confirms \\( d_1=-1.5,\\ d_2=1.75 \\)." },
      ],
      finalAnswer: "\\( d_0 = 1,\\ d_1 = -\\tfrac{3}{2},\\ d_2 = \\tfrac{7}{4} \\).",
    },
  },
  {
    id: "am1a-022",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that if \\( f \\) is continuous and \\( f(x) = o(\\phi(x)) \\) as \\( x \\to +\\infty \\), where \\( \\phi \\) is continuous, positive and non-decreasing, then \\( \\displaystyle\\int_a^x f(t)\\,dt = o\\bigl(x\\,\\phi(x)\\bigr) \\) as \\( x \\to +\\infty \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration of orders", "little-o", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Translate the hypothesis into an epsilon statement.", workingLatex: "\\forall \\varepsilon > 0\\ \\exists X:\\ x > X \\implies |f(x)| < \\varepsilon\\,\\phi(x)", explanation: "\\( f = o(\\phi) \\) means \\( |f|/\\phi \\to 0 \\); equivalently, beyond some threshold \\( X \\) the bound \\( |f| < \\varepsilon\\phi \\) holds for any chosen \\( \\varepsilon \\). Fixing \\( \\varepsilon \\) first and chasing the constant later is the standard \\( o \\)-to-integral technique." },
        { stepNumber: 2, description: "Split the integral at \\( X \\).", workingLatex: "\\int_a^x f(t)\\,dt = \\int_a^{X} f(t)\\,dt + \\int_{X}^{x} f(t)\\,dt", explanation: "The first piece is a fixed constant \\( C := \\int_a^X f \\), unaffected by \\( x \\); only the tail can grow as \\( x \\to \\infty \\), so we isolate it for separate treatment." },
        { stepNumber: 3, description: "Bound the tail by the integral of the modulus.", workingLatex: "\\left|\\int_{X}^{x} f(t)\\,dt\\right| \\le \\int_{X}^{x} |f(t)|\\,dt", explanation: "The modulus of an integral never exceeds the integral of the modulus — the triangle inequality for integrals. This lets us bring the pointwise bound on \\( |f| \\) to bear." },
        { stepNumber: 4, description: "Apply the epsilon bound under the integral.", workingLatex: "\\int_{X}^{x} |f(t)|\\,dt < \\varepsilon \\int_{X}^{x} \\phi(t)\\,dt", explanation: "On \\( [X,x] \\) the bound \\( |f| < \\varepsilon\\phi \\) holds pointwise, so it may be applied under the integral sign. The constant \\( \\varepsilon \\) pulls outside." },
        { stepNumber: 5, description: "Bound the integral of \\( \\phi \\) using monotonicity.", workingLatex: "\\int_{X}^{x} \\phi(t)\\,dt \\le (x - X)\\,\\phi(x) \\le x\\,\\phi(x)", explanation: "Because \\( \\phi \\) is non-decreasing, \\( \\phi(t) \\le \\phi(x) \\) for all \\( t \\le x \\); the interval has length \\( x - X \\le x \\). This is where the monotonicity hypothesis is essential — without it the bound could fail." },
        { stepNumber: 6, description: "Combine the pieces.", workingLatex: "\\left|\\int_a^x f(t)\\,dt\\right| \\le |C| + \\varepsilon\\, x\\,\\phi(x)", explanation: "Adding the fixed constant from step 2 to the bounded tail gives a bound expressed entirely in terms of \\( x\\phi(x) \\) plus a constant — exactly what we need to compare against \\( x\\phi(x) \\)." },
        { stepNumber: 7, description: "Divide by \\( x\\phi(x) \\) and take the limsup.", workingLatex: "\\frac{1}{x\\phi(x)}\\left|\\int_a^x f\\right| \\le \\frac{|C|}{x\\phi(x)} + \\varepsilon", explanation: "Since \\( \\phi > 0 \\) is non-decreasing, \\( x\\phi(x) \\to \\infty \\), so the constant term \\( |C|/(x\\phi(x)) \\to 0 \\); the limsup of the left side is therefore \\( \\le \\varepsilon \\)." },
        { stepNumber: 8, description: "Let \\( \\varepsilon \\to 0 \\).", workingLatex: "\\limsup_{x\\to\\infty}\\frac{1}{x\\phi(x)}\\left|\\int_a^x f\\right| \\le \\varepsilon\\ \\forall\\varepsilon \\implies \\int_a^x f = o(x\\phi(x))", explanation: "As \\( \\varepsilon \\) was arbitrary, the limsup is \\( 0 \\), hence the limit is \\( 0 \\) — precisely the required little-o statement. The moral: integrating an \\( o(\\phi) \\) estimate costs one factor of \\( x \\)." },
      ],
      finalAnswer: "\\( \\int_a^x f(t)\\,dt = o\\bigl(x\\,\\phi(x)\\bigr) \\) as \\( x \\to +\\infty \\).",
    },
  },
  // REVIEW: cosh sector estimate is a complex-analytic argument; the magnitude comparison e^{Re(z)} vs e^{-Re(z)} is the checkable core, the sector boundary discussion is qualitative.
  {
    id: "am1a-023",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Taking \\( \\delta > 0 \\) fixed, show that \\( \\cosh z \\sim \\tfrac12 e^{z} \\) as \\( |z| \\to \\infty \\) in the sector \\( -\\tfrac{\\pi}{2} + \\delta < \\arg z < \\tfrac{\\pi}{2} - \\delta \\). Explain why the estimate fails on the imaginary axis (\\( \\delta = 0 \\)).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cosh", "complex asymptotics", "sectors", "Stokes lines"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write cosh as a sum of two exponentials.", workingLatex: "\\cosh z = \\frac{1}{2}e^{z} + \\frac{1}{2}e^{-z}", explanation: "The two exponentials compete; whichever has the larger modulus dominates as \\( |z| \\to \\infty \\). Identifying which one wins, and showing the other is negligible, is the whole problem." },
        { stepNumber: 2, description: "Express their moduli via the real part.", workingLatex: "|e^{z}| = e^{\\operatorname{Re} z}, \\qquad |e^{-z}| = e^{-\\operatorname{Re} z}", explanation: "The modulus of a complex exponential depends only on the real part of its argument; the imaginary part contributes only a phase of unit modulus. So the comparison reduces to the sign and size of \\( \\operatorname{Re} z \\)." },
        { stepNumber: 3, description: "Relate the real part to the argument.", workingLatex: "\\operatorname{Re} z = |z|\\cos(\\arg z)", explanation: "In polar form \\( z = |z|e^{i\\arg z} \\), the real part is \\( |z|\\cos(\\arg z) \\). The sector restriction controls \\( \\cos(\\arg z) \\), which in turn controls \\( \\operatorname{Re} z \\)." },
        { stepNumber: 4, description: "Sign the real part using the sector.", workingLatex: "|\\arg z| < \\tfrac{\\pi}{2} - \\delta \\implies \\cos(\\arg z) \\ge \\sin\\delta > 0 \\implies \\operatorname{Re} z \\ge |z|\\sin\\delta", explanation: "Staying \\( \\delta \\) away from \\( \\pm\\tfrac{\\pi}{2} \\) keeps \\( \\cos(\\arg z) \\) bounded below by the positive constant \\( \\sin\\delta \\), so \\( \\operatorname{Re} z \\to +\\infty \\) at least linearly in \\( |z| \\)." },
        { stepNumber: 5, description: "Form the ratio of recessive to dominant term.", workingLatex: "\\frac{\\tfrac12 e^{-z}}{\\tfrac12 e^{z}} = e^{-2z}, \\qquad |e^{-2z}| = e^{-2\\operatorname{Re} z} \\le e^{-2|z|\\sin\\delta}", explanation: "The would-be subdominant term is smaller than the dominant one by the factor \\( e^{-2z} \\), whose modulus is controlled by the lower bound on \\( \\operatorname{Re} z \\) from step 4." },
        { stepNumber: 6, description: "Take the limit.", workingLatex: "e^{-2|z|\\sin\\delta} \\to 0 \\quad (|z| \\to \\infty)", explanation: "Because \\( \\sin\\delta > 0 \\) is a fixed positive constant, the bound decays to zero. Hence \\( \\tfrac12 e^{-z} = o(\\tfrac12 e^{z}) \\), so \\( \\cosh z \\sim \\tfrac12 e^{z} \\) throughout the sector." },
        { stepNumber: 7, description: "Explain the breakdown at \\( \\delta = 0 \\).", workingLatex: "\\arg z = \\pm\\tfrac{\\pi}{2}:\\ \\operatorname{Re} z = 0 \\implies |e^{z}| = |e^{-z}| = 1", explanation: "On the imaginary axis the two exponentials have equal modulus, so neither dominates and there is no single recessive term. This is exactly a Stokes/anti-Stokes line, where the asymptotic balance switches and the simple \\( \\sim \\tfrac12 e^z \\) estimate fails." },
      ],
      finalAnswer: "\\( \\cosh z \\sim \\tfrac12 e^{z} \\) in the sector; on \\( \\arg z = \\pm\\tfrac{\\pi}{2} \\) (\\( \\delta=0 \\)) the terms balance, so it fails.",
    },
  },
  {
    id: "am1a-024",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The integral \\( F(x) = \\displaystyle\\int_0^{\\infty} \\frac{t\\,e^{-t}}{1 + xt}\\,dt \\) has the asymptotic expansion \\( F(x) \\sim \\sum_{n=0}^{\\infty} (-1)^n n!\\,x^{n+1} \\) as \\( x \\to 0^+ \\). Show that \\( \\{x^{n+1}\\} \\) is an asymptotic sequence as \\( x \\to 0^+ \\), and explain why the series diverges for every fixed \\( x > 0 \\) yet is still a valid asymptotic expansion.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Stieltjes integral", "divergent asymptotic series", "asymptotic sequence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the gauge sequence.", workingLatex: "\\phi_n(x) = x^{n+1}, \\quad n = 0, 1, 2, \\ldots", explanation: "Each term of the series is a constant multiple \\( (-1)^n n! \\) of \\( x^{n+1} \\); stripping the coefficients leaves the scale functions \\( x^{n+1} \\), which are what an asymptotic-sequence test concerns." },
        { stepNumber: 2, description: "Check the asymptotic-sequence condition.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = \\frac{x^{n+2}}{x^{n+1}} = x \\to 0 \\quad (x \\to 0^+)", explanation: "Consecutive powers differ by one factor of \\( x \\), which vanishes, so \\( \\{x^{n+1}\\} \\) is a genuine asymptotic sequence. Note this concerns the gauges, not the (large) coefficients." },
        { stepNumber: 3, description: "Examine the size of the coefficients.", workingLatex: "a_n = (-1)^n n! \\implies |a_n| = n! \\to \\infty\\ \\text{factorially}", explanation: "The factorial growth of the coefficients is the source of the divergence we are about to find; it eventually overwhelms any fixed power of \\( x \\) once \\( n \\) is large enough." },
        { stepNumber: 4, description: "Apply the ratio test at fixed \\( x \\).", workingLatex: "\\left|\\frac{a_{n+1}x^{n+2}}{a_n x^{n+1}}\\right| = \\frac{(n+1)!}{n!}\\,x = (n+1)\\,x \\to \\infty \\quad (n \\to \\infty)", explanation: "For any fixed \\( x > 0 \\) the term-to-term ratio grows without bound, so by the ratio test the numerical series \\( \\sum (-1)^n n! x^{n+1} \\) diverges." },
        { stepNumber: 5, description: "Reconcile divergence with asymptoticity.", workingLatex: "F(x) - \\sum_{n=0}^{N} (-1)^n n!\\,x^{n+1} = O\\bigl(x^{N+2}\\bigr) \\quad (x \\to 0^+,\\ N\\ \\text{fixed})", explanation: "Asymptoticity is a statement about \\( x \\to 0^+ \\) at FIXED truncation \\( N \\), not about \\( N \\to \\infty \\). For small \\( x \\) the partial sums approximate \\( F \\) extremely well, even though letting \\( N \\to \\infty \\) ruins them." },
        { stepNumber: 6, description: "State the resolution.", workingLatex: "\\text{divergent as a series, yet } F(x) \\sim \\sum (-1)^n n!\\,x^{n+1}\\ \\text{asymptotically}", explanation: "This is the defining feature of an asymptotic (as opposed to convergent) expansion: accuracy comes from optimal truncation at a finite \\( N \\), not from summing the whole series." },
      ],
      finalAnswer: "\\( \\phi_{n+1}/\\phi_n = x \\to 0 \\) (asymptotic sequence); the series diverges since \\( (n+1)x \\to \\infty \\), but the fixed-\\( N \\) remainder is \\( O(x^{N+2}) \\), so it is a valid asymptotic expansion.",
    },
  },
  {
    id: "am1a-025",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour of the exponential integral \\( E_1(x) = \\displaystyle\\int_x^{\\infty} \\frac{e^{-t}}{t}\\,dt \\) as \\( x \\to +\\infty \\), and obtain the first two terms of its asymptotic expansion by integration by parts. Identify the gauge sequence.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["exponential integral", "integration by parts", "asymptotic expansion", "gauge functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Choose parts with \\( u = 1/t \\), \\( dv = e^{-t}dt \\).", workingLatex: "u = \\frac{1}{t},\\ dv = e^{-t}\\,dt \\implies du = -\\frac{1}{t^2}\\,dt,\\ v = -e^{-t}", explanation: "Differentiating \\( 1/t \\) lowers its power, while \\( e^{-t} \\) integrates to itself; this trade turns one power of \\( 1/t \\) into the next, which is what generates the successive terms of the expansion." },
        { stepNumber: 2, description: "Apply the integration-by-parts formula.", workingLatex: "E_1(x) = \\Bigl[\\,u\\,v\\,\\Bigr]_x^{\\infty} - \\int_x^{\\infty} v\\,du = \\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty} - \\int_x^{\\infty} \\frac{e^{-t}}{t^2}\\,dt", explanation: "Using \\( \\int u\\,dv = uv - \\int v\\,du \\); the two minus signs in \\( v\\,du = (-e^{-t})(-t^{-2}dt) \\) combine to give the \\( +e^{-t}/t^2 \\) integrand, subtracted overall." },
        { stepNumber: 3, description: "Evaluate the boundary term.", workingLatex: "\\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty} = 0 - \\left(-\\frac{e^{-x}}{x}\\right) = \\frac{e^{-x}}{x}", explanation: "At \\( t = \\infty \\) the term vanishes (the exponential kills the algebraic part); at \\( t = x \\) it gives \\( e^{-x}/x \\), the leading term of the expansion." },
        { stepNumber: 4, description: "State the leading order.", workingLatex: "E_1(x) \\sim \\frac{e^{-x}}{x} \\quad (x \\to +\\infty)", explanation: "The remaining integral carries an extra factor \\( 1/t \\le 1/x \\), so it is smaller than the boundary term, which therefore dominates and sets the leading behaviour." },
        { stepNumber: 5, description: "Integrate by parts again on the remainder.", workingLatex: "\\int_x^{\\infty} \\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x^2} - 2\\int_x^{\\infty} \\frac{e^{-t}}{t^3}\\,dt", explanation: "Repeating with \\( u = 1/t^2 \\) (so \\( du = -2t^{-3}dt \\)) extracts the next boundary term \\( e^{-x}/x^2 \\) and leaves a still-smaller integral with \\( 1/t^3 \\)." },
        { stepNumber: 6, description: "Assemble two terms and name the gauges.", workingLatex: "E_1(x) \\sim e^{-x}\\Bigl(\\frac{1}{x} - \\frac{1}{x^2} + \\frac{2}{x^3} - \\cdots\\Bigr), \\qquad \\phi_n = e^{-x}x^{-n}", explanation: "Substituting back, the boundary terms combine with alternating signs. The natural gauge functions are \\( e^{-x}x^{-n} \\); since \\( \\phi_{n+1}/\\phi_n = 1/x \\to 0 \\), they form an asymptotic sequence. Numerically, \\( e^{-10}(1/10 - 1/100 + 2/1000 - 6/10^4) \\) matches \\( E_1(10) \\) to about \\( 10^{-3} \\) relative." },
      ],
      finalAnswer: "\\( E_1(x) \\sim \\dfrac{e^{-x}}{x} - \\dfrac{e^{-x}}{x^2} + \\cdots \\); gauge sequence \\( \\{e^{-x}x^{-n}\\} \\) with ratio \\( 1/x \\to 0 \\).",
    },
  },
  {
    id: "am1a-026",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( \\phi_n(x) = x^{a_n} \\) with exponents \\( a_n = n + \\tfrac{1}{n+1} \\) for \\( n = 0, 1, 2, \\ldots \\). Determine whether \\( \\{\\phi_n\\} \\) is an asymptotic sequence (i) as \\( x \\to 0^+ \\) and (ii) as \\( x \\to +\\infty \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "gauge functions", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the exponent gap between consecutive terms.", workingLatex: "a_{n+1} - a_n = \\Bigl[(n+1) + \\tfrac{1}{n+2}\\Bigr] - \\Bigl[n + \\tfrac{1}{n+1}\\Bigr] = 1 + \\frac{1}{n+2} - \\frac{1}{n+1}", explanation: "Whether the sequence is asymptotic depends on the sign of the exponent gap, so we compute it first. The integer parts contribute \\( +1 \\); the fractional parts give a small correction." },
        { stepNumber: 2, description: "Combine the fractional correction.", workingLatex: "\\frac{1}{n+2} - \\frac{1}{n+1} = \\frac{(n+1)-(n+2)}{(n+1)(n+2)} = \\frac{-1}{(n+1)(n+2)}", explanation: "Over the common denominator \\( (n+1)(n+2) \\), the numerator is \\( (n+1)-(n+2) = -1 \\). So the correction is a small negative number, never below \\( -\\tfrac12 \\) in size since \\( (n+1)(n+2) \\ge 2 \\)." },
        { stepNumber: 3, description: "Conclude the gap is positive.", workingLatex: "a_{n+1} - a_n = 1 - \\frac{1}{(n+1)(n+2)} > 0", explanation: "The \\( +1 \\) dominates the small negative correction, so each exponent strictly exceeds its predecessor — the powers are genuinely increasing in \\( n \\)." },
        { stepNumber: 4, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{\\phi_{n+1}(x)}{\\phi_n(x)} = x^{a_{n+1} - a_n}, \\qquad a_{n+1} - a_n > 0", explanation: "The ratio is a positive power of \\( x \\) for every \\( n \\); its limit now depends entirely on which way \\( x \\) goes. We treat the two limits separately." },
        { stepNumber: 5, description: "Resolve the case \\( x \\to 0^+ \\).", workingLatex: "x \\to 0^+:\\ x^{a_{n+1}-a_n} \\to 0 \\implies \\phi_{n+1} = o(\\phi_n)", explanation: "A positive power of \\( x \\) vanishes at the origin, so the negligibility condition holds and the sequence IS asymptotic as \\( x \\to 0^+ \\)." },
        { stepNumber: 6, description: "Resolve the case \\( x \\to +\\infty \\).", workingLatex: "x \\to +\\infty:\\ x^{a_{n+1}-a_n} \\to +\\infty \\implies \\phi_{n+1} \\neq o(\\phi_n)", explanation: "The same positive power blows up at infinity, so each term grows relative to the previous one — NOT asymptotic. To rank these at infinity one would reverse the ordering of the exponents." },
      ],
      finalAnswer: "Asymptotic as \\( x \\to 0^+ \\) (ratio \\( \\to 0 \\)); not asymptotic as \\( x \\to +\\infty \\) (ratio \\( \\to \\infty \\)).",
    },
  },
  {
    id: "am1a-027",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(x) = \\dfrac{1}{1 - x} + e^{-1/x} \\) for \\( 0 < x < 1 \\). Find the asymptotic expansion of \\( h \\) as \\( x \\to 0^+ \\) to order \\( x^3 \\), and state precisely why this expansion does not capture \\( h \\) completely.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["beyond all orders", "geometric series", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the rational part as a geometric series.", workingLatex: "\\frac{1}{1 - x} = 1 + x + x^2 + x^3 + \\cdots \\quad (|x| < 1)", explanation: "For small \\( x \\) this is the standard convergent geometric series \\( \\sum x^k \\), which supplies the entire algebraic part of the answer." },
        { stepNumber: 2, description: "Substitute \\( s = 1/x \\) in the exponential ratio.", workingLatex: "\\frac{e^{-1/x}}{x^n} = x^{-n} e^{-1/x} = s^{n} e^{-s} \\qquad (s = 1/x \\to \\infty)", explanation: "To see how \\( e^{-1/x} \\) compares with each power gauge \\( x^n \\), substitute \\( s = 1/x \\); as \\( x \\to 0^+ \\) we have \\( s \\to \\infty \\), and \\( x^{-n} = s^n \\)." },
        { stepNumber: 3, description: "Show the exponential is beyond every power.", workingLatex: "\\lim_{s \\to \\infty} s^{n}e^{-s} = 0\\ \\ \\forall n \\implies e^{-1/x} = o(x^n)\\ \\forall n", explanation: "Exponential decay beats every fixed power, so the ratio vanishes for all \\( n \\). Hence \\( e^{-1/x} \\) is smaller than every power of \\( x \\) — it contributes nothing at any algebraic order." },
        { stepNumber: 4, description: "Combine to the requested order.", workingLatex: "h(x) \\sim 1 + x + x^2 + x^3 \\quad (x \\to 0^+)", explanation: "Since the exponential contributes nothing algebraically, the power series through \\( x^3 \\) comes entirely from \\( 1/(1-x) \\)." },
        { stepNumber: 5, description: "Identify exactly what the series omits.", workingLatex: "h(x) - (1 + x + x^2 + x^3 + \\cdots) = e^{-1/x} \\neq 0", explanation: "Even the FULL power series misses the exponentially small term: the difference between \\( h \\) and all of its algebraic terms is precisely the non-zero \\( e^{-1/x} \\)." },
        { stepNumber: 6, description: "Interpret the limitation.", workingLatex: "e^{-1/x}\\ \\text{is 'beyond all orders' in the gauge } \\{x^n\\}", explanation: "To see the exponential one must enrich the gauge sequence with \\( e^{-1/x} \\) itself; the pure power-series gauge is blind to it. This is exactly why two different functions can share one asymptotic power series." },
      ],
      finalAnswer: "\\( h(x) \\sim 1 + x + x^2 + x^3 + \\cdots \\); the power series misses \\( e^{-1/x} \\), which is beyond all algebraic orders.",
    },
  },
  {
    id: "am1a-028",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Decide whether the relation \\( O(x^2)\\cdot O(x^3) = O(x^5) \\) and the (false) candidate \\( o(x) + o(x) = o(x^2) \\) are correct as \\( x \\to 0 \\). Prove the true one and give the correct version of the false one.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["algebra of orders", "order notation", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up representatives for the product rule.", workingLatex: "f = O(x^2):\\ |f| \\le A x^2,\\qquad g = O(x^3):\\ |g| \\le B x^3\\ \\ (0 < x < \\delta)", explanation: "Big-O means each function is bounded by a constant times its gauge near the limit point. Working with explicit bounds \\( A, B \\) lets us prove the product rule directly rather than hand-wave it." },
        { stepNumber: 2, description: "Multiply the two bounds.", workingLatex: "|fg| = |f|\\,|g| \\le (A x^2)(B x^3) = AB\\,x^{5}", explanation: "The product of the bounds bounds the product, and the powers add: \\( x^2 \\cdot x^3 = x^5 \\). The combined constant is just \\( AB \\)." },
        { stepNumber: 3, description: "Conclude the product rule is true.", workingLatex: "fg = O(x^5) \\quad \\checkmark", explanation: "A single constant \\( AB \\) times \\( x^5 \\) bounds \\( fg \\), so \\( O(x^2)\\cdot O(x^3) = O(x^5) \\) holds — exactly the expected addition of exponents." },
        { stepNumber: 4, description: "Test the addition claim.", workingLatex: "f, g = o(x):\\ \\frac{f}{x} \\to 0,\\ \\frac{g}{x} \\to 0 \\implies \\frac{f + g}{x} = \\frac{f}{x} + \\frac{g}{x} \\to 0", explanation: "Adding two functions negligible against \\( x \\) gives a sum still negligible against \\( x \\), because limits add. The gauge does NOT improve to \\( x^2 \\)." },
        { stepNumber: 5, description: "Give the correct addition rule with a counterexample.", workingLatex: "o(x) + o(x) = o(x);\\quad \\text{e.g. } f = g = x^{3/2} = o(x),\\ f+g = 2x^{3/2} \\neq o(x^2)", explanation: "Summation keeps the SAME (largest) gauge; raising the power to \\( x^2 \\) is the common error. The counterexample \\( x^{3/2} \\) is \\( o(x) \\) yet \\( 2x^{3/2} \\) is not \\( o(x^2) \\), since \\( 2x^{3/2}/x^2 = 2x^{-1/2} \\to \\infty \\)." },
      ],
      finalAnswer: "\\( O(x^2)\\cdot O(x^3) = O(x^5) \\) is TRUE; \\( o(x)+o(x) = o(x^2) \\) is FALSE — correctly \\( o(x) + o(x) = o(x) \\).",
    },
  },
  {
    id: "am1a-029",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using Laplace's method or otherwise, show that \\( I(x) = \\displaystyle\\int_0^{\\pi/2} \\exp\\!\\bigl(-x\\,t^3\\cos t\\bigr)\\,dt \\) has leading-order behaviour \\( I(x) \\sim \\dfrac{1}{3x^{1/3}}\\,\\Gamma\\!\\left(\\tfrac13\\right) \\) as \\( x \\to +\\infty \\). State the gauge function controlling the leading term.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace method", "Gamma function", "gauge functions", "large-parameter integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate where the exponent is smallest.", workingLatex: "\\psi(t) = t^3\\cos t \\ge 0\\ \\text{on}\\ [0,\\tfrac{\\pi}{2}],\\quad \\psi(0) = 0", explanation: "The integrand is \\( e^{-x\\psi} \\); as \\( x \\to \\infty \\) the dominant contribution comes from where \\( \\psi \\) is smallest — here the endpoint \\( t = 0 \\), where \\( \\psi \\) actually reaches zero." },
        { stepNumber: 2, description: "Approximate the exponent near \\( t = 0 \\).", workingLatex: "\\cos t = 1 - \\tfrac{t^2}{2} + \\cdots \\implies \\psi(t) = t^3\\cos t \\sim t^3 \\quad (t \\to 0)", explanation: "Near the origin \\( \\cos t \\to 1 \\), so the exponent behaves like \\( t^3 \\) — a cubic (degenerate) minimum of \\( \\psi \\) at the endpoint, which is what produces a fractional power later." },
        { stepNumber: 3, description: "Replace the integral by its local model.", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t^3}\\,dt", explanation: "Only a shrinking neighbourhood of \\( t = 0 \\) contributes, so we may extend the upper limit to \\( \\infty \\) and drop the higher-order part of \\( \\cos t \\); the discarded tail is exponentially small." },
        { stepNumber: 4, description: "Substitute to reach a Gamma integral.", workingLatex: "u = x t^3 \\implies t = (u/x)^{1/3},\\ dt = \\frac{1}{3}x^{-1/3}u^{-2/3}\\,du", explanation: "This change of variable maps the cubic exponent to the standard \\( e^{-u} \\) form and pulls all the \\( x \\)-dependence out into the prefactor \\( x^{-1/3} \\). Differentiating \\( t = (u/x)^{1/3} \\) gives the stated \\( dt \\)." },
        { stepNumber: 5, description: "Evaluate using the Gamma function.", workingLatex: "I(x) \\sim \\frac{1}{3}x^{-1/3}\\int_0^{\\infty} u^{-2/3} e^{-u}\\,du = \\frac{1}{3}x^{-1/3}\\,\\Gamma\\!\\left(\\tfrac13\\right)", explanation: "The remaining integral is \\( \\int_0^\\infty u^{s-1}e^{-u}du = \\Gamma(s) \\) with \\( s - 1 = -\\tfrac23 \\), i.e. \\( s = \\tfrac13 \\), so it equals \\( \\Gamma(\\tfrac13) \\)." },
        { stepNumber: 6, description: "State the leading term and gauge function.", workingLatex: "I(x) \\sim \\frac{\\Gamma(1/3)}{3}\\,x^{-1/3}, \\qquad \\text{gauge } = x^{-1/3}", explanation: "The leading scale is the fractional power \\( x^{-1/3} \\): a cubic endpoint minimum yields a one-third power, not the \\( x^{-1/2} \\) of an ordinary interior maximum. Numerically at \\( x = 1000 \\), \\( I \\approx 0.08972 \\) matches \\( \\Gamma(1/3)x^{-1/3}/3 \\)." },
      ],
      finalAnswer: "\\( I(x) \\sim \\dfrac{\\Gamma(1/3)}{3}\\,x^{-1/3} \\) as \\( x \\to +\\infty \\); leading gauge function \\( x^{-1/3} \\).",
    },
  },
  {
    id: "am1a-030",
    topicRef: "am1a",
    topicTitle: "Order notation, gauge functions & asymptotic sequences 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The functions \\( f(z) \\sim \\sum_{n=0}^{\\infty} a_n z^{-n} \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} b_n z^{-n} \\) as \\( z \\to \\infty \\). Show that \\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), justifying carefully why the cross terms beyond order \\( N \\) are negligible.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["product of series", "asymptotic expansion", "Cauchy product", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write each function as a truncation plus remainder.", workingLatex: "f(z) = \\sum_{j=0}^{N} a_j z^{-j} + R_f, \\quad R_f = o(z^{-N}); \\qquad g(z) = \\sum_{k=0}^{N} b_k z^{-k} + R_g,\\ R_g = o(z^{-N})", explanation: "By definition each asymptotic expansion approximates its function up to a remainder that is little-o of the last retained gauge term \\( z^{-N} \\). The proof works by tracking where each remainder ends up." },
        { stepNumber: 2, description: "Multiply the two truncations.", workingLatex: "\\Bigl(\\sum_{j=0}^{N} a_j z^{-j}\\Bigr)\\Bigl(\\sum_{k=0}^{N} b_k z^{-k}\\Bigr) = \\sum_{n=0}^{2N}\\Bigl(\\sum_{k=0}^{n} a_{n-k}b_k\\Bigr) z^{-n}", explanation: "Collecting powers \\( z^{-n} \\) gives the Cauchy product; the inner sum is exactly the claimed coefficient \\( c_n \\). The product of two degree-\\( N \\) truncations reaches up to \\( z^{-2N} \\)." },
        { stepNumber: 3, description: "Split the product into wanted and surplus orders.", workingLatex: "\\sum_{n=0}^{2N} c_n z^{-n} = \\sum_{n=0}^{N} c_n z^{-n} + \\underbrace{\\sum_{n=N+1}^{2N} c_n z^{-n}}_{= O(z^{-(N+1)}) = o(z^{-N})}", explanation: "Every surplus term has power \\( z^{-n} \\) with \\( n \\ge N+1 \\), hence is already \\( o(z^{-N}) \\) — negligible at the order we are claiming, so it can be swept into the remainder." },
        { stepNumber: 4, description: "Bound the three remainder cross terms.", workingLatex: "R_f\\, g,\\ f\\, R_g,\\ R_f R_g:\\quad |R_f\\, g| \\le |R_f|\\,|g| = o(z^{-N})\\cdot O(1) = o(z^{-N})", explanation: "Since \\( g \\to b_0 = O(1) \\) and \\( R_f = o(z^{-N}) \\), the product \\( R_f g \\) is little-o of \\( z^{-N} \\); the same argument handles \\( f R_g \\) and \\( R_f R_g \\) (the last is even smaller)." },
        { stepNumber: 5, description: "Assemble the full product.", workingLatex: "f(z)g(z) = \\sum_{n=0}^{N} c_n z^{-n} + o(z^{-N})", explanation: "Adding step 3's surplus terms and step 4's remainder products, every contribution beyond order \\( N \\) is \\( o(z^{-N}) \\), leaving exactly the truncated series plus an admissible error." },
        { stepNumber: 6, description: "Quote the defining condition of an asymptotic expansion.", workingLatex: "f(z)g(z) - \\sum_{n=0}^{N} c_n z^{-n} = o(z^{-N}) \\quad \\forall N", explanation: "This is precisely the statement that \\( \\sum c_n z^{-n} \\) is the asymptotic expansion of \\( fg \\), since it holds for every truncation order \\( N \\)." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n}, \\qquad c_n = \\sum_{k=0}^{n} a_{n-k} b_k", explanation: "The product of two asymptotic power series is the asymptotic power series whose coefficients are the Cauchy convolution of the originals — the continuous analogue of multiplying ordinary power series." },
      ],
      finalAnswer: "\\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\); all beyond-order terms are \\( o(z^{-N}) \\).",
    },
  },
];
