import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — am1b
 * Algebra of asymptotic expansions: products & reciprocals
 * Topic group: Asymptotic Sequences & Series
 *
 * 30 fully-worked questions seeded from Cambridge Part II Asymptotic Methods
 * Example Sheet 1, Q4 (Cauchy product of two expansions) and Q5 (reciprocal of
 * a series with a0 != 0 via the convolution recurrence), with constants,
 * limits and framing varied.
 *
 * Conventions: worked-solution fractions use big \frac. Every numeric
 * reciprocal/product was checked against the convolution recurrence and, where
 * a closed form exists, against sympy series.
 */
export const questions: Question[] = [
  // ── Foundation: core Cauchy-product / reciprocal moves in isolation ────
  {
    id: "am1b-001",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Two functions have the asymptotic expansions \\( f(z) \\sim 1 + \\dfrac{2}{z} \\) and \\( g(z) \\sim 1 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\). Using the Cauchy product \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), find the coefficients \\( c_0, c_1, c_2 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficient sequences.", workingLatex: "a_0=1,\\ a_1=2,\\ a_2=0; \\qquad b_0=1,\\ b_1=1,\\ b_2=0.", explanation: "Both series terminate, so every coefficient beyond the written ones is zero." },
        { stepNumber: 2, description: "Apply the Cauchy product at n=0.", workingLatex: "c_0 = a_0 b_0 = 1\\cdot 1 = 1.", explanation: "The leading coefficient of a product is the product of the leading coefficients." },
        { stepNumber: 3, description: "Apply the Cauchy product at n=1.", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = 1\\cdot 1 + 2\\cdot 1 = 3.", explanation: "" },
        { stepNumber: 4, description: "Apply the Cauchy product at n=2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + 2\\cdot 1 + 0 = 2.", explanation: "" },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1 = 3,\\ c_2 = 2 \\).",
    },
  },
  {
    id: "am1b-002",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 2 + \\dfrac{1}{z} \\) and \\( g(z) \\sim 3 - \\dfrac{1}{z} \\) as \\( z \\to \\infty \\). Find the coefficients \\( c_0, c_1, c_2 \\) in \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_0=2,\\ a_1=1; \\qquad b_0=3,\\ b_1=-1.", explanation: "All higher coefficients vanish." },
        { stepNumber: 2, description: "Leading term.", workingLatex: "c_0 = a_0 b_0 = 2\\cdot 3 = 6.", explanation: "" },
        { stepNumber: 3, description: "Order z^{-1} term.", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = 2(-1) + 1\\cdot 3 = 1.", explanation: "" },
        { stepNumber: 4, description: "Order z^{-2} term.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + (1)(-1) + 0 = -1.", explanation: "Only the middle product survives because the outer coefficients are zero." },
      ],
      finalAnswer: "\\( c_0 = 6,\\ c_1 = 1,\\ c_2 = -1 \\).",
    },
  },
  {
    id: "am1b-003",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\), use the reciprocal recurrence \\( d_0 = 1,\\ \\sum_{k=0}^{n} d_{n-k} a_k = 0\\ (n\\ge 1) \\) to find \\( d_1, d_2, d_3 \\) in \\( \\dfrac{1}{f(z)} \\sim \\sum d_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients.", workingLatex: "a_0 = 1,\\ a_1 = 1,\\ a_2 = a_3 = \\cdots = 0.", explanation: "Here a_0 = 1, so the prefactor 1/a_0 is just 1 and the d_n are the reciprocal coefficients directly." },
        { stepNumber: 2, description: "Solve the recurrence at n=1.", workingLatex: "d_1 a_0 + d_0 a_1 = 0 \\;\\Rightarrow\\; d_1 = -\\frac{d_0 a_1}{a_0} = -1.", explanation: "Each step solves for the newest coefficient d_n using only earlier ones." },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0 \\;\\Rightarrow\\; d_2 = -(-1)(1) = 1.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 a_0 + d_2 a_1 + d_1 a_2 + d_0 a_3 = 0 \\;\\Rightarrow\\; d_3 = -(1)(1) = -1.", explanation: "The pattern d_n = (-1)^n is the geometric series, as expected since 1/(1+1/z) sums geometrically." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = 1,\\ d_3 = -1 \\).",
    },
  },
  {
    id: "am1b-004",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 2 + \\dfrac{4}{z} \\) as \\( z \\to \\infty \\), find \\( d_1 \\) and \\( d_2 \\) so that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{2}\\left(d_0 + \\dfrac{d_1}{z} + \\dfrac{d_2}{z^2} + \\cdots\\right) \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients.", workingLatex: "a_0 = 2,\\ a_1 = 4,\\ a_2 = 0.", explanation: "The prefactor 1/a_0 = 1/2 is pulled out; the recurrence still uses the full a_k." },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 a_0 + d_0 a_1 = 0 \\;\\Rightarrow\\; d_1 = -\\frac{(1)(4)}{2} = -2.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0 \\;\\Rightarrow\\; d_2 = -\\frac{(-2)(4) + 0}{2} = 4.", explanation: "" },
      ],
      finalAnswer: "\\( d_1 = -2,\\ d_2 = 4 \\); so \\( \\frac{1}{f} \\sim \\frac{1}{2}\\big(1 - \\frac{2}{z} + \\frac{4}{z^2} - \\cdots\\big) \\).",
    },
  },
  {
    id: "am1b-005",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Two expansions as \\( x \\to 0 \\) are \\( f(x) \\sim 1 + x + x^2 \\) and \\( g(x) \\sim 1 - x \\). Find the coefficients of \\( 1, x, x^2 \\) in the product \\( f(x)g(x) \\) using the Cauchy product on ascending powers.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "small parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=1; \\qquad b_0=1,\\ b_1=-1,\\ b_2=0.", explanation: "The Cauchy product formula is identical for ascending powers as x -> 0." },
        { stepNumber: 2, description: "Coefficient of x^0.", workingLatex: "c_0 = a_0 b_0 = 1.", explanation: "" },
        { stepNumber: 3, description: "Coefficient of x^1.", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = -1 + 1 = 0.", explanation: "" },
        { stepNumber: 4, description: "Coefficient of x^2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 - 1 + 1 = 0.", explanation: "" },
      ],
      finalAnswer: "\\( f g \\sim 1 + 0\\cdot x + 0\\cdot x^2 + \\cdots \\) (the \\(x\\) and \\(x^2\\) terms cancel).",
    },
  },
  {
    id: "am1b-006",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\dfrac{1}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (all \\( a_n = 1 \\)), use the reciprocal recurrence to find \\( d_1, d_2, d_3 \\) in \\( 1/f \\sim \\sum d_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients.", workingLatex: "a_0 = a_1 = a_2 = a_3 = \\cdots = 1.", explanation: "" },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -1.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -(d_1 a_1 + d_0 a_2) = -(-1 + 1) = 0.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 = -(d_2 a_1 + d_1 a_2 + d_0 a_3) = -(0 - 1 + 1) = 0.", explanation: "All coefficients past d_1 vanish: since f sums to 1/(1-1/z), its reciprocal is exactly 1 - 1/z." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = 0,\\ d_3 = 0 \\); so \\( 1/f \\sim 1 - \\frac{1}{z} \\).",
    },
  },

  // ── Standard: typical sheet-level products and reciprocals ────
  {
    id: "am1b-007",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim \\sum_{n=0}^{\\infty} (n+1) z^{-n} = 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\cdots \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} z^{-n} = 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) as \\( z \\to \\infty \\). Find the first four coefficients \\( c_0,\\dots,c_3 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Record the coefficient sequences.", workingLatex: "a_n = n+1: \\ 1,2,3,4,\\dots; \\qquad b_n = 1:\\ 1,1,1,1,\\dots.", explanation: "" },
        { stepNumber: 2, description: "Compute c_0.", workingLatex: "c_0 = a_0 b_0 = 1.", explanation: "" },
        { stepNumber: 3, description: "Compute c_1.", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = 1 + 2 = 3.", explanation: "" },
        { stepNumber: 4, description: "Compute c_2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 1 + 2 + 3 = 6.", explanation: "" },
        { stepNumber: 5, description: "Compute c_3.", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = 1+2+3+4 = 10.", explanation: "Because b_n = 1, c_n is the running sum a_0+\\cdots+a_n = 1+2+\\cdots+(n+1), the triangular numbers." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=3,\\ c_2=6,\\ c_3=10 \\) (triangular numbers).",
    },
  },
  {
    id: "am1b-008",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 - \\dfrac{1}{z} + \\dfrac{1}{z^2} - \\dfrac{1}{z^3} + \\cdots \\) (so \\( a_n = (-1)^n \\)) and \\( g(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) (so \\( b_n = 1 \\)). Find \\( c_0,\\dots,c_3 \\) of \\( f(z)g(z) \\) and identify the closed form.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Record coefficients.", workingLatex: "a_n = (-1)^n:\\ 1,-1,1,-1; \\qquad b_n = 1.", explanation: "" },
        { stepNumber: 2, description: "Compute c_0 and c_1.", workingLatex: "c_0 = 1, \\qquad c_1 = a_0 b_1 + a_1 b_0 = 1 - 1 = 0.", explanation: "" },
        { stepNumber: 3, description: "Compute c_2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 1 - 1 + 1 = 1.", explanation: "" },
        { stepNumber: 4, description: "Compute c_3.", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = 1 - 1 + 1 - 1 = 0.", explanation: "c_n is the partial sum of 1,-1,1,-1,\\dots: it equals 1 for even n and 0 for odd n." },
        { stepNumber: 5, description: "Identify the closed form.", workingLatex: "f \\sim \\frac{1}{1+1/z},\\ g \\sim \\frac{1}{1-1/z} \\;\\Rightarrow\\; fg \\sim \\frac{1}{1-1/z^2} = \\sum_{m\\ge 0} z^{-2m}.", explanation: "This matches c_n = 1 (n even), 0 (n odd)." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=0,\\ c_2=1,\\ c_3=0 \\); product \\( \\sim \\sum_{m} z^{-2m} \\).",
    },
  },
  {
    id: "am1b-009",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 2 + \\dfrac{3}{z} + \\dfrac{4}{z^2} + \\dfrac{5}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = n+2 \\)). Find \\( d_1, d_2, d_3 \\) so that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{2}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), with \\( d_0 = 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_0=2,\\ a_1=3,\\ a_2=4,\\ a_3=5.", explanation: "The prefactor 1/a_0 = 1/2 is factored out front; the recurrence uses a_0 in each denominator." },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{3}{2}.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -\\frac{d_1 a_1 + d_0 a_2}{a_0} = -\\frac{(-\\frac{3}{2})(3) + 4}{2} = -\\frac{-\\frac{9}{2}+4}{2} = \\frac{1}{4}.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 = -\\frac{d_2 a_1 + d_1 a_2 + d_0 a_3}{a_0} = -\\frac{\\frac{1}{4}(3) + (-\\frac{3}{2})(4) + 5}{2} = -\\frac{\\frac{3}{4} - 6 + 5}{2} = \\frac{1}{8}.", explanation: "" },
      ],
      finalAnswer: "\\( d_1 = -\\frac{3}{2},\\ d_2 = \\frac{1}{4},\\ d_3 = \\frac{1}{8} \\).",
    },
  },
  {
    id: "am1b-010",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\dfrac{4}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = n+1 \\)), find the reciprocal coefficients \\( d_1, d_2, d_3 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\) and identify the closed form.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_0=1,\\ a_1=2,\\ a_2=3,\\ a_3=4.", explanation: "Note f \\sim (1-1/z)^{-2}, so we expect 1/f \\sim (1-1/z)^2." },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -2.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -(d_1 a_1 + d_0 a_2) = -((-2)(2) + 3) = 1.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 = -(d_2 a_1 + d_1 a_2 + d_0 a_3) = -((1)(2) + (-2)(3) + 4) = 0.", explanation: "All higher d_n vanish: the reciprocal is the finite expansion (1 - 1/z)^2 = 1 - 2/z + 1/z^2." },
      ],
      finalAnswer: "\\( d_1=-2,\\ d_2=1,\\ d_3=0 \\); \\( 1/f \\sim 1 - \\frac{2}{z} + \\frac{1}{z^2} = (1-1/z)^2 \\).",
    },
  },
  {
    id: "am1b-011",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 3 + \\dfrac{1}{z^2} + \\dfrac{5}{z^4} \\) (so \\( a_0 = 3,\\ a_1 = 0,\\ a_2 = 1,\\ a_3 = 0,\\ a_4 = 5 \\)). Find \\( d_1, d_2, d_3, d_4 \\) in \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{3}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), with \\( d_0 = 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "even series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_0=3,\\ a_1=0,\\ a_2=1,\\ a_3=0,\\ a_4=5.", explanation: "Because the odd coefficients vanish, we expect the odd d_n to vanish too." },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = 0.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -\\frac{d_1 a_1 + d_0 a_2}{a_0} = -\\frac{0 + 1}{3} = -\\frac{1}{3}.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 = -\\frac{d_2 a_1 + d_1 a_2 + d_0 a_3}{a_0} = 0.", explanation: "Every term contains an odd-index a or the already-zero d_1." },
        { stepNumber: 5, description: "Solve at n=4.", workingLatex: "d_4 = -\\frac{d_3 a_1 + d_2 a_2 + d_1 a_3 + d_0 a_4}{a_0} = -\\frac{(-\\frac{1}{3})(1) + 5}{3} = -\\frac{14}{9}.", explanation: "" },
      ],
      finalAnswer: "\\( d_1 = 0,\\ d_2 = -\\frac{1}{3},\\ d_3 = 0,\\ d_4 = -\\frac{14}{9} \\).",
    },
  },
  {
    id: "am1b-012",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( x \\to 0 \\), \\( f(x) \\sim 1 + x + \\dfrac{x^2}{2} + \\dfrac{x^3}{6} \\) and \\( g(x) \\sim 1 - x + \\dfrac{x^2}{2} - \\dfrac{x^3}{6} \\). Find the coefficients of \\( x^0, x^1, x^2, x^3 \\) in the product \\( f(x)g(x) \\), and comment on the result.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "small parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_n:\\ 1,\\,1,\\,\\tfrac12,\\,\\tfrac16; \\qquad b_n:\\ 1,\\,-1,\\,\\tfrac12,\\,-\\tfrac16.", explanation: "These are the truncated series of e^{x} and e^{-x}." },
        { stepNumber: 2, description: "Coefficient of x^0.", workingLatex: "c_0 = a_0 b_0 = 1.", explanation: "" },
        { stepNumber: 3, description: "Coefficient of x^1.", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = -1 + 1 = 0.", explanation: "" },
        { stepNumber: 4, description: "Coefficient of x^2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = \\frac{1}{2} - 1 + \\frac{1}{2} = 0.", explanation: "" },
        { stepNumber: 5, description: "Coefficient of x^3.", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = -\\frac{1}{6} + \\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6} = 0.", explanation: "Consistent with e^{x}e^{-x} = 1: every coefficient past the constant cancels to this order." },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1 = c_2 = c_3 = 0 \\) (product \\(\\sim 1\\), matching \\(e^x e^{-x}=1\\)).",
    },
  },
  {
    id: "am1b-013",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = 1/n! \\)). Find the reciprocal coefficients \\( d_1, d_2, d_3 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\) and identify the function.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "exponential"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=\\frac{1}{2},\\ a_3=\\frac{1}{6}.", explanation: "f is the expansion of e^{1/z}, so we expect 1/f to be e^{-1/z}." },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -d_0 a_1 = -1.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -(d_1 a_1 + d_0 a_2) = -\\left(-1 + \\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=3.", workingLatex: "d_3 = -(d_2 a_1 + d_1 a_2 + d_0 a_3) = -\\left(\\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6}\\right) = -\\frac{1}{6}.", explanation: "These are the coefficients of e^{-1/z}: d_n = (-1)^n/n!." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = \\frac{1}{2},\\ d_3 = -\\frac{1}{6} \\); \\( 1/f \\sim e^{-1/z} \\).",
    },
  },
  {
    id: "am1b-014",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( x \\to 0 \\), \\( \\cos x \\sim 1 - \\dfrac{x^2}{2} + \\dfrac{x^4}{24} \\). Using the reciprocal recurrence on this series, find the expansion of \\( \\sec x = 1/\\cos x \\) up to and including the \\( x^4 \\) term.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients of cos x.", workingLatex: "a_0=1,\\ a_1=0,\\ a_2=-\\frac{1}{2},\\ a_3=0,\\ a_4=\\frac{1}{24}.", explanation: "Indexing by powers of x. Odd coefficients vanish, so odd d_n will vanish." },
        { stepNumber: 2, description: "Solve at n=1 and n=3.", workingLatex: "d_1 = -d_0 a_1 = 0, \\qquad d_3 = -(d_2 a_1 + d_1 a_2 + d_0 a_3) = 0.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -(d_1 a_1 + d_0 a_2) = -\\left(-\\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=4.", workingLatex: "d_4 = -(d_3 a_1 + d_2 a_2 + d_1 a_3 + d_0 a_4) = -\\left(\\frac{1}{2}\\cdot\\left(-\\frac{1}{2}\\right) + \\frac{1}{24}\\right) = \\frac{5}{24}.", explanation: "" },
        { stepNumber: 5, description: "Assemble sec x.", workingLatex: "\\sec x \\sim 1 + \\frac{x^2}{2} + \\frac{5x^4}{24}.", explanation: "Matches the standard Maclaurin series of sec x." },
      ],
      finalAnswer: "\\( \\sec x \\sim 1 + \\frac{x^2}{2} + \\frac{5x^4}{24} \\).",
    },
  },
  {
    id: "am1b-015",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{a}{z} \\) as \\( z \\to \\infty \\), where \\( a \\) is a constant. Using the reciprocal recurrence, show that \\( \\dfrac{1}{f(z)} \\sim \\sum_{n=0}^{\\infty} (-a)^n z^{-n} \\), and verify by summing the geometric series.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "geometric series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_0 = 1,\\ a_1 = a,\\ a_2 = a_3 = \\cdots = 0.", explanation: "" },
        { stepNumber: 2, description: "Set up the recurrence for n>=1.", workingLatex: "\\sum_{k=0}^{n} d_{n-k} a_k = d_n a_0 + d_{n-1} a_1 = d_n + a\\, d_{n-1} = 0.", explanation: "Only a_0 and a_1 are nonzero, so the convolution collapses to two terms." },
        { stepNumber: 3, description: "Solve the recurrence.", workingLatex: "d_n = -a\\, d_{n-1} \\;\\Rightarrow\\; d_n = (-a)^n d_0 = (-a)^n.", explanation: "A first-order geometric recurrence with d_0 = 1." },
        { stepNumber: 4, description: "Verify by direct summation.", workingLatex: "\\frac{1}{1 + a/z} = \\sum_{n=0}^{\\infty} \\left(-\\frac{a}{z}\\right)^n = \\sum_{n=0}^{\\infty} (-a)^n z^{-n}.", explanation: "The geometric series for |a/z| < 1 reproduces the recurrence coefficients exactly." },
      ],
      finalAnswer: "\\( d_n = (-a)^n \\), so \\( 1/f \\sim \\sum_{n\\ge 0} (-a)^n z^{-n} \\).",
    },
  },
  {
    id: "am1b-016",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} \\) and \\( g(z) \\sim 1 - \\dfrac{1}{z} \\). Find the first four coefficients of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_n:\\ 1,1,1,0; \\qquad b_n:\\ 1,-1,0,0.", explanation: "" },
        { stepNumber: 2, description: "Compute c_0 and c_1.", workingLatex: "c_0 = 1, \\qquad c_1 = a_0 b_1 + a_1 b_0 = -1 + 1 = 0.", explanation: "" },
        { stepNumber: 3, description: "Compute c_2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 - 1 + 1 = 0.", explanation: "" },
        { stepNumber: 4, description: "Compute c_3.", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = 0 + 0 - 1 + 0 = -1.", explanation: "The product equals (1+1/z+1/z^2)(1-1/z) = 1 - 1/z^3 by telescoping." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=0,\\ c_2=0,\\ c_3=-1 \\); product \\( \\sim 1 - z^{-3} \\).",
    },
  },
  {
    id: "am1b-017",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given the asymptotic expansion \\( f(z) \\sim 1 - \\dfrac{1}{z} - \\dfrac{1}{z^2} \\) as \\( z \\to \\infty \\) (so \\( a_0=1,\\ a_1=-1,\\ a_2=-1 \\), higher zero), find the reciprocal coefficients \\( d_1,\\dots,d_5 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "Fibonacci"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_0=1,\\ a_1=-1,\\ a_2=-1,\\ a_3=a_4=a_5=0.", explanation: "Since f \\sim 1 - 1/z - 1/z^2, its reciprocal is the Fibonacci generating function 1/(1 - w - w^2) with w = 1/z." },
        { stepNumber: 2, description: "Recurrence collapses to three terms.", workingLatex: "d_n a_0 + d_{n-1} a_1 + d_{n-2} a_2 = d_n - d_{n-1} - d_{n-2} = 0.", explanation: "For n >= 2 only a_0,a_1,a_2 contribute; for n=1 only a_0,a_1." },
        { stepNumber: 3, description: "Solve at n=1.", workingLatex: "d_1 = -d_0 a_1 = 1.", explanation: "" },
        { stepNumber: 4, description: "Solve at n=2,3.", workingLatex: "d_2 = d_1 + d_0 = 2, \\qquad d_3 = d_2 + d_1 = 3.", explanation: "" },
        { stepNumber: 5, description: "Solve at n=4,5.", workingLatex: "d_4 = d_3 + d_2 = 5, \\qquad d_5 = d_4 + d_3 = 8.", explanation: "The d_n are the Fibonacci numbers 1,1,2,3,5,8,\\dots." },
      ],
      finalAnswer: "\\( d_1=1,\\ d_2=2,\\ d_3=3,\\ d_4=5,\\ d_5=8 \\) (Fibonacci numbers).",
    },
  },
  {
    id: "am1b-018",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 4 + \\dfrac{2}{z} + \\dfrac{1}{z^2} \\). Find the first three coefficients (the constant, \\( z^{-1} \\) and \\( z^{-2} \\)) of \\( 1/f(z) \\), giving each in fully simplified form.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients and factor out 1/a_0.", workingLatex: "a_0=4,\\ a_1=2,\\ a_2=1; \\qquad \\frac{1}{f} \\sim \\frac{1}{4}\\sum d_n z^{-n}.", explanation: "" },
        { stepNumber: 2, description: "Solve at n=1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{2}{4} = -\\frac{1}{2}.", explanation: "" },
        { stepNumber: 3, description: "Solve at n=2.", workingLatex: "d_2 = -\\frac{d_1 a_1 + d_0 a_2}{a_0} = -\\frac{(-\\frac{1}{2})(2) + 1}{4} = 0.", explanation: "" },
        { stepNumber: 4, description: "Multiply through by 1/4.", workingLatex: "\\frac{1}{f} \\sim \\frac{1}{4} - \\frac{1}{8z} + \\frac{0}{z^2} + \\cdots.", explanation: "The coefficient of the actual expansion is d_n/a_0." },
      ],
      finalAnswer: "\\( \\frac{1}{f} \\sim \\frac{1}{4} - \\frac{1}{8z} + 0\\cdot z^{-2} + \\cdots \\).",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level ────
  {
    id: "am1b-019",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim \\sum_{n=0}^{\\infty} a_n z^{-n} \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} b_n z^{-n} \\) as \\( z \\to \\infty \\). Show that \\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "proof", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write each function as a truncation plus remainder.", workingLatex: "f(z) = \\sum_{n=0}^{N} a_n z^{-n} + R_f, \\qquad g(z) = \\sum_{n=0}^{N} b_n z^{-n} + R_g,", explanation: "By definition of an asymptotic expansion, the remainders satisfy R_f = o(z^{-N}) and R_g = o(z^{-N}) as z -> infinity." },
        { stepNumber: 2, description: "Multiply the two truncations.", workingLatex: "\\left(\\sum_{m=0}^{N} a_m z^{-m}\\right)\\left(\\sum_{j=0}^{N} b_j z^{-j}\\right) = \\sum_{m=0}^{N}\\sum_{j=0}^{N} a_m b_j\\, z^{-(m+j)}.", explanation: "A finite product of finite sums, so no convergence issues arise." },
        { stepNumber: 3, description: "Collect terms by total power.", workingLatex: "= \\sum_{n=0}^{N}\\left(\\sum_{k=0}^{n} a_{n-k} b_k\\right) z^{-n} \\; + \\; \\sum_{n=N+1}^{2N}(\\cdots) z^{-n}.", explanation: "Grouping by n = m + j gives exactly the Cauchy coefficient c_n; the leftover terms with n > N are all O(z^{-(N+1)})." },
        { stepNumber: 4, description: "Bound the cross terms involving remainders.", workingLatex: "R_f \\cdot g,\\ f\\cdot R_g,\\ R_f R_g = o(z^{-N}),", explanation: "Each remainder is o(z^{-N}) and the other factor is O(1), so every remainder cross-term is o(z^{-N})." },
        { stepNumber: 5, description: "Assemble the estimate.", workingLatex: "f(z)g(z) - \\sum_{n=0}^{N} c_n z^{-n} = o(z^{-N}) \\quad (z\\to\\infty).", explanation: "The high-power tail from Step 3 is O(z^{-(N+1)}) = o(z^{-N}), and the remainder terms are o(z^{-N})." },
        { stepNumber: 6, description: "Conclude for all N.", workingLatex: "\\therefore\\ f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n}, \\quad c_n = \\sum_{k=0}^{n} a_{n-k} b_k.", explanation: "Since N was arbitrary, the partial sums satisfy the defining estimate for every order, which is the definition of the asymptotic expansion." },
      ],
      finalAnswer: "\\( f g \\sim \\sum_{n} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\).",
    },
  },
  {
    id: "am1b-020",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim a_0 + \\dfrac{a_1}{z} + \\dfrac{a_2}{z^2} + \\cdots \\) as \\( z \\to \\infty \\) with \\( a_0 \\neq 0 \\). Show by induction (or otherwise) that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\) for \\( n \\ge 1 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "proof", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Since a_0 != 0, the reciprocal has a leading term.", workingLatex: "f(z) \\to a_0 \\neq 0 \\;\\Rightarrow\\; \\frac{1}{f(z)} \\to \\frac{1}{a_0} \\quad (z\\to\\infty).", explanation: "Continuity of the reciprocal at a nonzero value guarantees 1/f is well defined and bounded for large z, so it admits an expansion in z^{-n}." },
        { stepNumber: 2, description: "Posit the form and impose f * (1/f) = 1.", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\qquad f(z)\\cdot\\frac{1}{f(z)} \\sim 1.", explanation: "Write the unknown reciprocal coefficients and demand the product be asymptotic to the constant 1." },
        { stepNumber: 3, description: "Apply the Cauchy product (Q19) to f and 1/f.", workingLatex: "f\\cdot\\frac{1}{f} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty}\\left(\\sum_{k=0}^{n} a_{n-k} d_k\\right) z^{-n}.", explanation: "Multiplying two asymptotic series gives a Cauchy product; here one factor is f with coefficients a_k and the other carries d_k." },
        { stepNumber: 4, description: "Match the constant term (n=0).", workingLatex: "\\frac{1}{a_0}\\,a_0 d_0 = 1 \\;\\Rightarrow\\; d_0 = 1.", explanation: "The n=0 coefficient of the product must equal 1, fixing d_0." },
        { stepNumber: 5, description: "Match coefficients for n>=1.", workingLatex: "\\frac{1}{a_0}\\sum_{k=0}^{n} a_{n-k} d_k = 0 \\;\\Rightarrow\\; \\sum_{k=0}^{n} a_{n-k} d_k = 0.", explanation: "All coefficients of z^{-n} for n >= 1 in the constant 1 are zero. Re-indexing k -> n-k gives the stated form sum d_{n-k} a_k = 0." },
        { stepNumber: 6, description: "Solve the recurrence (the induction).", workingLatex: "a_0 d_n = -\\sum_{k=1}^{n} a_k d_{n-k} \\;\\Rightarrow\\; d_n = -\\frac{1}{a_0}\\sum_{k=1}^{n} a_k d_{n-k}.", explanation: "Since a_0 != 0 we can divide; the right side uses only d_0,...,d_{n-1}, so by induction every d_n is uniquely determined. This is the inductive step." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\quad d_0=1,\\ \\sum_{k=0}^{n} d_{n-k}a_k = 0.", explanation: "The coefficients exist and are unique for all n, completing the proof." },
      ],
      finalAnswer: "Reciprocal coefficients are uniquely determined by \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\).",
    },
  },
  {
    id: "am1b-021",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} + \\cdots = e^{1/z} \\) and \\( g(z) \\sim 1 - \\dfrac{1}{z} + \\dfrac{1}{2z^2} - \\dfrac{1}{6z^3} + \\cdots = e^{-1/z} \\). (a) Compute the first four Cauchy coefficients \\( c_0,\\dots,c_3 \\) of \\( fg \\). (b) Verify they are consistent with \\( fg = 1 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "exponential", "consistency check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_n = \\frac{1}{n!}:\\ 1,1,\\tfrac12,\\tfrac16; \\qquad b_n = \\frac{(-1)^n}{n!}:\\ 1,-1,\\tfrac12,-\\tfrac16.", explanation: "" },
        { stepNumber: 2, description: "Compute c_0 and c_1.", workingLatex: "c_0 = 1, \\qquad c_1 = a_0 b_1 + a_1 b_0 = -1 + 1 = 0.", explanation: "" },
        { stepNumber: 3, description: "Compute c_2.", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = \\frac{1}{2} - 1 + \\frac{1}{2} = 0.", explanation: "" },
        { stepNumber: 4, description: "Compute c_3.", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = -\\frac{1}{6} + \\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6} = 0.", explanation: "" },
        { stepNumber: 5, description: "General argument for consistency.", workingLatex: "c_n = \\sum_{k=0}^{n} \\frac{1}{(n-k)!}\\cdot\\frac{(-1)^k}{k!} = \\frac{1}{n!}\\sum_{k=0}^{n}\\binom{n}{k}(-1)^k = \\frac{(1-1)^n}{n!}.", explanation: "Factoring out 1/n! turns the sum into a binomial expansion of (1-1)^n." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "c_n = \\frac{0^n}{n!} = \\begin{cases}1 & n=0\\\\ 0 & n\\ge 1\\end{cases}", explanation: "So fg \\sim 1, exactly as e^{1/z}e^{-1/z} = 1 requires." },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1=c_2=c_3=0 \\); in general \\( c_n = 0^n/n! \\), so \\( fg \\sim 1 \\).",
    },
  },
  {
    id: "am1b-022",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(z) = \\sqrt{1 + 1/z} \\), which as \\( z \\to \\infty \\) has the binomial expansion \\( h(z) \\sim 1 + \\dfrac{1}{2z} - \\dfrac{1}{8z^2} + \\dfrac{1}{16z^3} - \\cdots \\). Using the Cauchy product, compute the coefficients of \\( h(z)^2 \\) up to \\( z^{-3} \\) and confirm they reproduce \\( 1 + 1/z \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "binomial series", "consistency check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of h.", workingLatex: "a_0=1,\\ a_1=\\frac{1}{2},\\ a_2=-\\frac{1}{8},\\ a_3=\\frac{1}{16}.", explanation: "These are the binomial coefficients \\binom{1/2}{n}." },
        { stepNumber: 2, description: "Square via the Cauchy product: c_n = sum a_{n-k} a_k.", workingLatex: "c_0 = a_0^2 = 1.", explanation: "" },
        { stepNumber: 3, description: "Coefficient of z^{-1}.", workingLatex: "c_1 = 2 a_0 a_1 = 2\\cdot\\frac{1}{2} = 1.", explanation: "" },
        { stepNumber: 4, description: "Coefficient of z^{-2}.", workingLatex: "c_2 = 2 a_0 a_2 + a_1^2 = 2\\left(-\\frac{1}{8}\\right) + \\frac{1}{4} = -\\frac{1}{4} + \\frac{1}{4} = 0.", explanation: "" },
        { stepNumber: 5, description: "Coefficient of z^{-3}.", workingLatex: "c_3 = 2 a_0 a_3 + 2 a_1 a_2 = 2\\cdot\\frac{1}{16} + 2\\cdot\\frac{1}{2}\\cdot\\left(-\\frac{1}{8}\\right) = \\frac{1}{8} - \\frac{1}{8} = 0.", explanation: "" },
        { stepNumber: 6, description: "Assemble.", workingLatex: "h(z)^2 \\sim 1 + \\frac{1}{z} + 0\\cdot z^{-2} + 0\\cdot z^{-3} = 1 + \\frac{1}{z}.", explanation: "Squaring the series for \\sqrt{1+1/z} returns 1 + 1/z, as it must." },
      ],
      finalAnswer: "\\( h^2 \\sim 1 + \\frac{1}{z} \\) (coefficients \\(1,1,0,0\\)).",
    },
  },
  {
    id: "am1b-023",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} \\) (the series of \\( e^{1/z} \\)). Using the reciprocal recurrence, find the coefficients of \\( 1/f \\) up to \\( z^{-3} \\); then, separately, obtain the same coefficients via the Cauchy-product identity and confirm they agree.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "exponential", "cross-method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients.", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=\\frac{1}{2},\\ a_3=\\frac{1}{6}.", explanation: "" },
        { stepNumber: 2, description: "Reciprocal recurrence, n=1,2.", workingLatex: "d_1 = -a_1 = -1, \\qquad d_2 = -(d_1 a_1 + a_2) = -\\left(-1 + \\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "Using a_0 = 1 so d_n = -sum_{k=1}^{n} a_k d_{n-k}." },
        { stepNumber: 3, description: "Reciprocal recurrence, n=3.", workingLatex: "d_3 = -(d_2 a_1 + d_1 a_2 + d_0 a_3) = -\\left(\\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6}\\right) = -\\frac{1}{6}.", explanation: "" },
        { stepNumber: 4, description: "Cross-check: the reciprocal of e^{1/z} is e^{-1/z}.", workingLatex: "\\frac{1}{e^{1/z}} = e^{-1/z} \\sim \\sum_{n} \\frac{(-1)^n}{n!} z^{-n}.", explanation: "An independent route: the reciprocal coefficient should be (-1)^n/n!." },
        { stepNumber: 5, description: "Compare.", workingLatex: "\\frac{(-1)^n}{n!}\\Big|_{n=1,2,3} = -1,\\ \\frac{1}{2},\\ -\\frac{1}{6}.", explanation: "Exactly the recurrence values from Steps 2-3." },
        { stepNumber: 6, description: "Confirm consistency via the convolution identity.", workingLatex: "\\sum_{k=0}^{3} a_{3-k} d_k = \\frac{1}{6}(1) + \\frac{1}{2}(-1) + 1\\cdot\\frac{1}{2} + 1\\cdot\\left(-\\frac{1}{6}\\right) = 0.", explanation: "The defining identity sum a_{n-k} d_k = 0 holds at n=3, confirming both methods agree." },
      ],
      finalAnswer: "\\( 1/f \\sim 1 - \\frac{1}{z} + \\frac{1}{2z^2} - \\frac{1}{6z^3} = e^{-1/z} \\).",
    },
  },
  {
    id: "am1b-024",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( \\sinh(1/z) \\sim \\dfrac{1}{z} + \\dfrac{1}{6z^3} + \\dfrac{1}{120 z^5} \\) and \\( \\cosh(1/z) \\sim 1 + \\dfrac{1}{2z^2} + \\dfrac{1}{24 z^4} \\). Find the asymptotic expansion of \\( \\tanh(1/z) = \\sinh(1/z)/\\cosh(1/z) \\) up to and including \\( z^{-5} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "hyperbolic", "quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reciprocate cosh(1/z).", workingLatex: "a_0=1,\\ a_2=\\frac{1}{2},\\ a_4=\\frac{1}{24}\\ (\\text{odd } a=0).", explanation: "Treat 1/\\cosh as a reciprocal series; let w = 1/z. The odd coefficients vanish." },
        { stepNumber: 2, description: "Reciprocal recurrence for sech.", workingLatex: "d_2 = -a_2 = -\\frac{1}{2}, \\qquad d_4 = -(d_2 a_2 + a_4) = -\\left(-\\frac{1}{4} + \\frac{1}{24}\\right) = \\frac{5}{24}.", explanation: "So 1/\\cosh \\sim 1 - \\frac{1}{2}w^2 + \\frac{5}{24}w^4, with w = 1/z (this is sech)." },
        { stepNumber: 3, description: "Set up the product sinh * sech.", workingLatex: "\\sinh:\\ s_1=1,\\ s_3=\\frac{1}{6},\\ s_5=\\frac{1}{120}; \\qquad \\mathrm{sech}:\\ r_0=1,\\ r_2=-\\frac{1}{2},\\ r_4=\\frac{5}{24}.", explanation: "Only odd powers survive in the product, since sinh is odd and sech is even." },
        { stepNumber: 4, description: "Coefficient of w^1.", workingLatex: "t_1 = s_1 r_0 = 1.", explanation: "" },
        { stepNumber: 5, description: "Coefficient of w^3.", workingLatex: "t_3 = s_1 r_2 + s_3 r_0 = -\\frac{1}{2} + \\frac{1}{6} = -\\frac{1}{3}.", explanation: "" },
        { stepNumber: 6, description: "Coefficient of w^5.", workingLatex: "t_5 = s_1 r_4 + s_3 r_2 + s_5 r_0 = \\frac{5}{24} - \\frac{1}{12} + \\frac{1}{120} = \\frac{25 - 10 + 1}{120} = \\frac{2}{15}.", explanation: "Matching the standard tanh series coefficients 1, -1/3, 2/15." },
        { stepNumber: 7, description: "Assemble in z.", workingLatex: "\\tanh(1/z) \\sim \\frac{1}{z} - \\frac{1}{3z^3} + \\frac{2}{15 z^5}.", explanation: "Replacing w by 1/z." },
      ],
      finalAnswer: "\\( \\tanh(1/z) \\sim \\frac{1}{z} - \\frac{1}{3z^3} + \\frac{2}{15z^5} \\).",
    },
  },
  {
    id: "am1b-025",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim \\sum a_n z^{-n} \\) with \\( a_0 \\neq 0 \\), and let \\( \\{d_n\\} \\) be its reciprocal coefficients (\\( d_0 = 1,\\ \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\)). Show that the leading reciprocal coefficients are \\( d_1 = -a_1/a_0 \\) and \\( d_2 = (a_1^2 - a_0 a_2)/a_0^2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "general coefficients"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the recurrence at n=1.", workingLatex: "\\sum_{k=0}^{1} d_{1-k} a_k = d_1 a_0 + d_0 a_1 = 0.", explanation: "The convolution at n=1 has only two terms." },
        { stepNumber: 2, description: "Solve for d_1.", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{a_1}{a_0}.", explanation: "Using d_0 = 1." },
        { stepNumber: 3, description: "Write the recurrence at n=2.", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0.", explanation: "" },
        { stepNumber: 4, description: "Substitute d_1.", workingLatex: "d_2 a_0 = -d_1 a_1 - a_2 = \\frac{a_1^2}{a_0} - a_2.", explanation: "Insert d_1 = -a_1/a_0 and d_0 = 1." },
        { stepNumber: 5, description: "Solve for d_2.", workingLatex: "d_2 = \\frac{a_1^2}{a_0^2} - \\frac{a_2}{a_0} = \\frac{a_1^2 - a_0 a_2}{a_0^2}.", explanation: "Divide by a_0 and combine over a common denominator." },
      ],
      finalAnswer: "\\( d_1 = -\\frac{a_1}{a_0},\\quad d_2 = \\frac{a_1^2 - a_0 a_2}{a_0^2} \\).",
    },
  },
  {
    id: "am1b-026",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) (all \\( a_n = 1 \\)) and \\( g(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\cdots \\) (all \\( b_n = n+1 \\)). (a) Find the Cauchy product \\( c_n \\) in closed form. (b) Identify the closed-form function \\( fg \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "closed form", "geometric series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the Cauchy coefficient.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k = \\sum_{k=0}^{n} 1\\cdot(k+1) = \\sum_{k=0}^{n}(k+1).", explanation: "Since a_{n-k} = 1 for all indices." },
        { stepNumber: 2, description: "Sum the arithmetic series.", workingLatex: "c_n = \\sum_{j=1}^{n+1} j = \\frac{(n+1)(n+2)}{2} = \\binom{n+2}{2}.", explanation: "These are the triangular-number-shifted binomials \\binom{n+2}{2}." },
        { stepNumber: 3, description: "Identify f and g as geometric forms.", workingLatex: "f \\sim \\frac{1}{1 - 1/z}, \\qquad g \\sim \\frac{1}{(1 - 1/z)^2}.", explanation: "Sum b_n = n+1: \\sum (n+1)w^n = (1-w)^{-2} with w = 1/z." },
        { stepNumber: 4, description: "Multiply.", workingLatex: "fg \\sim \\frac{1}{(1-1/z)^3} = \\sum_{n=0}^{\\infty}\\binom{n+2}{2} z^{-n}.", explanation: "The product (1-w)^{-1}(1-w)^{-2} = (1-w)^{-3}, whose coefficients are \\binom{n+2}{2}, confirming part (a)." },
      ],
      finalAnswer: "\\( c_n = \\binom{n+2}{2} = \\frac{(n+1)(n+2)}{2} \\); \\( fg \\sim (1-1/z)^{-3} \\).",
    },
  },
  {
    id: "am1b-027",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} \\) (series of \\( e^{1/z} \\)). Using the reciprocal recurrence, find the coefficients of \\( 1/f^2 \\) up to \\( z^{-3} \\) (i.e. expand \\( e^{-2/z} \\)) by first squaring \\( f \\) via the Cauchy product and then reciprocating.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "exponential", "composition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Square f via the Cauchy product.", workingLatex: "a_n = \\frac{1}{n!}:\\ 1,1,\\tfrac12,\\tfrac16.", explanation: "We need f^2 = e^{2/z}; squaring should give coefficients 2^n/n!." },
        { stepNumber: 2, description: "Compute the squared coefficients e_n.", workingLatex: "e_0=1,\\ e_1=2,\\ e_2 = 2\\cdot\\frac{1}{2} + 1 = 2,\\ e_3 = 2\\cdot\\frac{1}{6} + 2\\cdot 1\\cdot\\frac{1}{2} = \\frac{4}{3}.", explanation: "e_1 = 2a_0a_1; e_2 = 2a_0a_2 + a_1^2; e_3 = 2a_0a_3 + 2a_1a_2. These equal 2^n/n!: 1,2,2,4/3." },
        { stepNumber: 3, description: "Reciprocate f^2: n=1.", workingLatex: "d_1 = -e_1 = -2.", explanation: "Here e_0 = 1, so d_n = -sum_{k=1}^{n} e_k d_{n-k}." },
        { stepNumber: 4, description: "n=2.", workingLatex: "d_2 = -(d_1 e_1 + e_2) = -((-2)(2) + 2) = 2.", explanation: "" },
        { stepNumber: 5, description: "n=3.", workingLatex: "d_3 = -(d_2 e_1 + d_1 e_2 + e_3) = -\\left((2)(2) + (-2)(2) + \\frac{4}{3}\\right) = -\\frac{4}{3}.", explanation: "" },
        { stepNumber: 6, description: "Assemble and identify.", workingLatex: "\\frac{1}{f^2} \\sim 1 - \\frac{2}{z} + \\frac{2}{z^2} - \\frac{4}{3z^3} = e^{-2/z}.", explanation: "Coefficients (-2)^n/n!: 1, -2, 2, -4/3 — exactly e^{-2/z}." },
      ],
      finalAnswer: "\\( 1/f^2 \\sim 1 - \\frac{2}{z} + \\frac{2}{z^2} - \\frac{4}{3z^3} = e^{-2/z} \\).",
    },
  },
  {
    id: "am1b-028",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), the function \\( \\coth(z) = \\cosh z/\\sinh z \\) satisfies \\( \\coth z = 1 + 2e^{-2z} + 2e^{-4z} + \\cdots \\). Writing \\( u = e^{-2z} \\) (an exponentially small gauge as \\( z \\to \\infty \\)), find the reciprocal expansion of \\( \\coth z \\) (i.e. \\( \\tanh z \\)) as a series in \\( u \\) up to \\( u^3 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "exponentially small terms"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Express coth in the gauge u.", workingLatex: "\\coth z = 1 + 2u + 2u^2 + 2u^3 + \\cdots, \\qquad u = e^{-2z}.", explanation: "Geometric: \\coth z = (1+u)/(1-u) = 1 + 2\\sum_{n\\ge 1} u^n." },
        { stepNumber: 2, description: "List coefficients a_n.", workingLatex: "a_0 = 1,\\ a_1 = 2,\\ a_2 = 2,\\ a_3 = 2.", explanation: "" },
        { stepNumber: 3, description: "Reciprocal recurrence, n=1.", workingLatex: "d_1 = -a_1 = -2.", explanation: "a_0 = 1, so d_n = -sum_{k=1}^{n} a_k d_{n-k}." },
        { stepNumber: 4, description: "n=2.", workingLatex: "d_2 = -(d_1 a_1 + a_2) = -((-2)(2) + 2) = 2.", explanation: "" },
        { stepNumber: 5, description: "n=3.", workingLatex: "d_3 = -(d_2 a_1 + d_1 a_2 + a_3) = -((2)(2) + (-2)(2) + 2) = -2.", explanation: "" },
        { stepNumber: 6, description: "Assemble and identify.", workingLatex: "\\tanh z = \\frac{1}{\\coth z} \\sim 1 - 2u + 2u^2 - 2u^3 + \\cdots = \\frac{1-u}{1+u}.", explanation: "Consistent with \\tanh z = (1-u)/(1+u), confirming the reciprocal." },
      ],
      finalAnswer: "\\( \\tanh z \\sim 1 - 2u + 2u^2 - 2u^3 + \\cdots \\) with \\( u = e^{-2z} \\).",
    },
  },
  {
    id: "am1b-029",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\dfrac{4}{z^3} + \\cdots \\) (so \\( a_n = n+1 \\)) as \\( z \\to \\infty \\). Find the reciprocal coefficients \\( d_n \\) for all \\( n \\), and hence find the coefficients of \\( 1/f^2 \\) up to \\( z^{-3} \\) using the Cauchy product.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "closed form", "synoptic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise f as a closed form.", workingLatex: "f \\sim \\sum_{n\\ge 0}(n+1)z^{-n} = \\frac{1}{(1-1/z)^2}.", explanation: "Standard generating function \\sum(n+1)w^n = (1-w)^{-2}." },
        { stepNumber: 2, description: "Reciprocal recurrence, n=1,2,3.", workingLatex: "d_1 = -2,\\quad d_2 = -(d_1 a_1 + a_2) = -(-4 + 3) = 1,\\quad d_3 = -(d_2 a_1 + d_1 a_2 + a_3) = -(2 - 6 + 4) = 0.", explanation: "1/f = (1-1/z)^2 = 1 - 2/z + 1/z^2, so d_n = 0 for n >= 3. Thus d_0=1, d_1=-2, d_2=1, else 0." },
        { stepNumber: 3, description: "Write 1/f explicitly.", workingLatex: "\\frac{1}{f} \\sim 1 - \\frac{2}{z} + \\frac{1}{z^2}.", explanation: "A terminating series." },
        { stepNumber: 4, description: "Square 1/f via the Cauchy product: list coefficients.", workingLatex: "r_0=1,\\ r_1=-2,\\ r_2=1,\\ r_3=0.", explanation: "We want (1/f)^2 = 1/f^2 = (1-1/z)^4." },
        { stepNumber: 5, description: "Cauchy product for the square.", workingLatex: "p_0 = 1,\\ p_1 = 2r_0r_1 = -4,\\ p_2 = 2r_0r_2 + r_1^2 = 2 + 4 = 6,\\ p_3 = 2r_0r_3 + 2r_1r_2 = 0 - 4 = -4.", explanation: "These are the binomial coefficients of (1-1/z)^4: 1,-4,6,-4(,1)." },
        { stepNumber: 6, description: "Assemble.", workingLatex: "\\frac{1}{f^2} \\sim 1 - \\frac{4}{z} + \\frac{6}{z^2} - \\frac{4}{z^3} + \\cdots = (1-1/z)^4.", explanation: "Confirmed: 1/f^2 = [(1-1/z)^2]^2 = (1-1/z)^4." },
      ],
      finalAnswer: "\\( d_0=1,\\ d_1=-2,\\ d_2=1 \\) (else 0); \\( 1/f^2 \\sim 1 - \\frac{4}{z} + \\frac{6}{z^2} - \\frac{4}{z^3} = (1-1/z)^4 \\).",
    },
  },
  {
    id: "am1b-030",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( \\dfrac{\\sin(1/z)}{1/z} \\sim 1 - \\dfrac{1}{6z^2} + \\dfrac{1}{120 z^4} \\). Find the asymptotic expansion of its reciprocal \\( \\dfrac{1/z}{\\sin(1/z)} \\) up to and including \\( z^{-4} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients in w = 1/z.", workingLatex: "a_0 = 1,\\ a_2 = -\\frac{1}{6},\\ a_4 = \\frac{1}{120} \\quad (\\text{odd } a = 0).", explanation: "Index by powers of w = 1/z; odd coefficients vanish so the odd reciprocal coefficients vanish too." },
        { stepNumber: 2, description: "Reciprocal recurrence, n=2.", workingLatex: "d_2 = -a_2 = \\frac{1}{6}.", explanation: "a_0 = 1; d_n = -sum_{k=1}^{n} a_k d_{n-k}, and only even k contribute." },
        { stepNumber: 3, description: "Reciprocal recurrence, n=4.", workingLatex: "d_4 = -(d_2 a_2 + d_0 a_4) = -\\left(\\frac{1}{6}\\cdot\\left(-\\frac{1}{6}\\right) + \\frac{1}{120}\\right) = -\\left(-\\frac{1}{36} + \\frac{1}{120}\\right).", explanation: "" },
        { stepNumber: 4, description: "Simplify d_4.", workingLatex: "d_4 = -\\left(-\\frac{10}{360} + \\frac{3}{360}\\right) = -\\left(-\\frac{7}{360}\\right) = \\frac{7}{360}.", explanation: "Common denominator 360." },
        { stepNumber: 5, description: "Assemble in z.", workingLatex: "\\frac{1/z}{\\sin(1/z)} \\sim 1 + \\frac{1}{6z^2} + \\frac{7}{360 z^4}.", explanation: "These are the standard coefficients of x/\\sin x = 1 + x^2/6 + 7x^4/360, with x = 1/z." },
      ],
      finalAnswer: "\\( \\dfrac{1/z}{\\sin(1/z)} \\sim 1 + \\frac{1}{6z^2} + \\frac{7}{360 z^4} \\).",
    },
  },
];
