import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — am1b
 * Algebra of asymptotic expansions: products & reciprocals
 * Topic group: Asymptotic Sequences & Series
 *
 * 30 fully-worked questions seeded from Cambridge Part II Asymptotic Methods
 * Example Sheet 1, Q4 (Cauchy product of two expansions) and Q5 (reciprocal of
 * a series with a0 != 0 via the convolution recurrence), with constants,
 * limits and framing varied.
 *
 * Conventions: worked-solution fractions use big \frac. Every numeric
 * reciprocal/product was checked against the convolution recurrence and, where
 * a closed form exists, against sympy series.
 */
export const questions: Question[] = [
  // ── Foundation: core Cauchy-product / reciprocal moves in isolation ────
  {
    id: "am1b-001",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Two functions have the asymptotic expansions \\( f(z) \\sim 1 + \\dfrac{2}{z} \\) and \\( g(z) \\sim 1 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\). Using the Cauchy product \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\), find the coefficients \\( c_0, c_1, c_2 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the Cauchy-product formula.", workingLatex: "\\left(\\sum_{n} a_n z^{-n}\\right)\\left(\\sum_{n} b_n z^{-n}\\right) \\sim \\sum_{n} c_n z^{-n}, \\quad c_n = \\sum_{k=0}^{n} a_{n-k} b_k.", explanation: "To multiply two asymptotic power series in \\( 1/z \\) you collect, for each output power \\( z^{-n} \\), every way of pairing a term from \\( f \\) with a term from \\( g \\) whose exponents add to \\( n \\). That bookkeeping is exactly the convolution \\( c_n = \\sum_{k=0}^n a_{n-k} b_k \\). We will apply it at \\( n = 0, 1, 2 \\)." },
        { stepNumber: 2, description: "Read off the coefficient sequences.", workingLatex: "a_0=1,\\ a_1=2,\\ a_2=0; \\qquad b_0=1,\\ b_1=1,\\ b_2=0.", explanation: "Match each function to \\( \\sum a_n z^{-n} \\): the constant term is the \\( n=0 \\) coefficient and the \\( 1/z \\) term the \\( n=1 \\) coefficient. Both series terminate, so every coefficient beyond the written ones is zero — recording \\( a_2 = b_2 = 0 \\) explicitly keeps the convolution bookkeeping honest." },
        { stepNumber: 3, description: "Apply the Cauchy product at \\( n=0 \\).", workingLatex: "c_0 = a_0 b_0 = 1\\cdot 1 = 1.", explanation: "The \\( n=0 \\) sum has only the single index \\( k=0 \\), so \\( c_0 = a_0 b_0 \\). The leading coefficient of a product is just the product of the leading coefficients — there is nothing to add to it." },
        { stepNumber: 4, description: "List the index pairs contributing to \\( c_1 \\).", workingLatex: "n=1:\\ (a_{1}b_0)\\ \\text{and}\\ (a_0 b_1), \\quad \\text{subscripts } 1{+}0 \\text{ and } 0{+}1.", explanation: "At \\( n=1 \\) the convolution runs over \\( k=0,1 \\). The two ways of splitting the exponent 1 are \\( (1,0) \\) and \\( (0,1) \\); both contribute to the \\( z^{-1} \\) coefficient and neither may be dropped." },
        { stepNumber: 5, description: "Evaluate \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = 1\\cdot 1 + 2\\cdot 1 = 1 + 2 = 3.", explanation: "Substitute the coefficients into the two surviving terms and add. A common slip here is to keep only one of the cross terms; both \\( a_0 b_1 \\) and \\( a_1 b_0 \\) land on \\( z^{-1} \\)." },
        { stepNumber: 6, description: "List the index pairs contributing to \\( c_2 \\).", workingLatex: "n=2:\\ (a_2 b_0),\\ (a_1 b_1),\\ (a_0 b_2).", explanation: "At \\( n=2 \\) the three splittings of the exponent are \\( (2,0),(1,1),(0,2) \\). Writing them all out first means we never forget that the squared term \\( a_1 b_1 \\) sits in the middle." },
        { stepNumber: 7, description: "Evaluate \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + 2\\cdot 1 + 0 = 2.", explanation: "The outer two products vanish because \\( a_2 = b_2 = 0 \\), leaving only the middle term \\( a_1 b_1 = 2 \\). The zeros are why a finite product still has finitely many terms." },
        { stepNumber: 8, description: "Cross-check by direct multiplication.", workingLatex: "\\left(1+\\tfrac{2}{z}\\right)\\left(1+\\tfrac{1}{z}\\right) = 1 + \\tfrac{3}{z} + \\tfrac{2}{z^2}.", explanation: "Multiplying the two short polynomials in \\( 1/z \\) by hand gives constant 1, the \\( 1/z \\) term \\( (2+1)/z = 3/z \\), and the \\( 1/z^2 \\) term \\( 2/z^2 \\) — matching \\( c_0,c_1,c_2 \\) and confirming the convolution." },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1 = 3,\\ c_2 = 2 \\).",
    },
  },
  {
    id: "am1b-002",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 2 + \\dfrac{1}{z} \\) and \\( g(z) \\sim 3 - \\dfrac{1}{z} \\) as \\( z \\to \\infty \\). Find the coefficients \\( c_0, c_1, c_2 \\) in \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the Cauchy-product convolution.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k.", explanation: "The coefficient of \\( z^{-n} \\) in the product is the convolution of the two coefficient sequences. We will read off \\( a_n, b_n \\) and then apply this at \\( n = 0, 1, 2 \\)." },
        { stepNumber: 2, description: "Read off the coefficients.", workingLatex: "a_0=2,\\ a_1=1; \\qquad b_0=3,\\ b_1=-1.", explanation: "Watch the sign in \\( g \\): the \\( -1/z \\) term means \\( b_1 = -1 \\). All higher coefficients vanish since both series terminate; carrying the minus sign correctly is the whole difficulty of this question." },
        { stepNumber: 3, description: "Compute the leading term \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = 2\\cdot 3 = 6.", explanation: "At \\( n=0 \\) the convolution has the single term \\( k=0 \\). So the constant term of the product is just the product of the two constant terms, \\( 2 \\times 3 = 6 \\)." },
        { stepNumber: 4, description: "Set up the two terms of \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0.", explanation: "The exponent 1 splits as \\( (0,1) \\) and \\( (1,0) \\). The first uses the negative coefficient \\( b_1 = -1 \\); it is the term most often mishandled." },
        { stepNumber: 5, description: "Evaluate \\( c_1 \\).", workingLatex: "c_1 = (2)(-1) + (1)(3) = -2 + 3 = 1.", explanation: "The negative \\( b_1 \\) makes the first contribution \\( -2 \\); a common slip is to drop that minus sign and get \\( 5 \\) instead of \\( 1 \\)." },
        { stepNumber: 6, description: "Set up the three terms of \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0.", explanation: "At \\( n=2 \\) the splittings are \\( (0,2),(1,1),(2,0) \\). The outer two involve the second-order coefficients \\( a_2 \\) and \\( b_2 \\), which are zero here." },
        { stepNumber: 7, description: "Evaluate \\( c_2 \\).", workingLatex: "c_2 = 0 + (1)(-1) + 0 = -1.", explanation: "Only the middle product \\( a_1 b_1 \\) survives because the outer coefficients vanish. The result inherits the sign of \\( b_1 \\), giving \\( -1 \\)." },
        { stepNumber: 8, description: "Cross-check by direct multiplication.", workingLatex: "\\left(2+\\tfrac{1}{z}\\right)\\left(3-\\tfrac{1}{z}\\right) = 6 + \\tfrac{1}{z} - \\tfrac{1}{z^2}.", explanation: "Expanding directly: constant \\( 6 \\), the \\( 1/z \\) term \\( (-2+3)/z = 1/z \\), and the \\( 1/z^2 \\) term \\( (1)(-1)/z^2 = -1/z^2 \\). This matches \\( c_0,c_1,c_2 \\)." },
      ],
      finalAnswer: "\\( c_0 = 6,\\ c_1 = 1,\\ c_2 = -1 \\).",
    },
  },
  {
    id: "am1b-003",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{1}{z} \\) as \\( z \\to \\infty \\), use the reciprocal recurrence \\( d_0 = 1,\\ \\sum_{k=0}^{n} d_{n-k} a_k = 0\\ (n\\ge 1) \\) to find \\( d_1, d_2, d_3 \\) in \\( \\dfrac{1}{f(z)} \\sim \\sum d_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients of \\( f \\).", workingLatex: "a_0 = 1,\\ a_1 = 1,\\ a_2 = a_3 = \\cdots = 0.", explanation: "Here \\( a_0 = 1 \\), so the prefactor \\( 1/a_0 \\) is just 1 and the \\( d_n \\) are the reciprocal coefficients directly. The recurrence is solvable precisely because \\( a_0 \\neq 0 \\)." },
        { stepNumber: 2, description: "State where the recurrence comes from.", workingLatex: "f\\cdot\\frac{1}{f} = 1 \\;\\Rightarrow\\; \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\ (n\\ge 1), \\quad d_0 a_0 = 1.", explanation: "The reciprocal \\( \\sum d_n z^{-n} \\) is defined by demanding its Cauchy product with \\( f \\) equal the constant series \\( 1 \\). Matching the \\( z^{-n} \\) coefficient forces the convolution to zero for every \\( n\\ge 1 \\)." },
        { stepNumber: 3, description: "Write the recurrence at \\( n=1 \\).", workingLatex: "\\sum_{k=0}^{1} d_{1-k} a_k = d_1 a_0 + d_0 a_1 = 0.", explanation: "The convolution at \\( n=1 \\) has just the two terms \\( k=0 \\) and \\( k=1 \\). This is the statement that the \\( z^{-1} \\) coefficient of \\( f\\cdot(1/f)=1 \\) must vanish." },
        { stepNumber: 4, description: "Solve for \\( d_1 \\).", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{(1)(1)}{1} = -1.", explanation: "Isolate the newest coefficient \\( d_1 \\) by moving \\( d_0 a_1 \\) across and dividing by \\( a_0 \\). Every solve uses only coefficients already known, which is what makes the recurrence triangular and hence solvable in order." },
        { stepNumber: 5, description: "Write the recurrence at \\( n=2 \\).", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0.", explanation: "At \\( n=2 \\) the convolution has three terms. The unknown \\( d_2 \\) appears only in the \\( k=0 \\) term \\( d_2 a_0 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_2 \\).", workingLatex: "d_2 = -(d_1 a_1 + d_0 a_2) = -((-1)(1) + 0) = 1.", explanation: "Substitute \\( d_1=-1 \\) and \\( a_2=0 \\). The \\( d_0 a_2 \\) term drops out because \\( a_2=0 \\), leaving \\( d_2 = -(-1) = 1 \\)." },
        { stepNumber: 7, description: "Write the recurrence at \\( n=3 \\).", workingLatex: "d_3 a_0 + d_2 a_1 + d_1 a_2 + d_0 a_3 = 0.", explanation: "At \\( n=3 \\) there are four terms, but \\( a_2 = a_3 = 0 \\) kill two of them immediately." },
        { stepNumber: 8, description: "Solve for \\( d_3 \\) and spot the pattern.", workingLatex: "d_3 = -(d_2 a_1) = -(1)(1) = -1 \\;\\Rightarrow\\; d_n = (-1)^n.", explanation: "Only \\( d_2 a_1 \\) survives, giving \\( d_3 = -1 \\). The pattern \\( d_n = (-1)^n \\) is the geometric series, as expected since \\( 1/(1+1/z) = \\sum (-1/z)^n \\) sums geometrically." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = 1,\\ d_3 = -1 \\).",
    },
  },
  {
    id: "am1b-004",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 2 + \\dfrac{4}{z} \\) as \\( z \\to \\infty \\), find \\( d_1 \\) and \\( d_2 \\) so that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{2}\\left(d_0 + \\dfrac{d_1}{z} + \\dfrac{d_2}{z^2} + \\cdots\\right) \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients of \\( f \\).", workingLatex: "a_0 = 2,\\ a_1 = 4,\\ a_2 = a_3 = \\cdots = 0.", explanation: "Both written terms give \\( a_0 = 2 \\) and \\( a_1 = 4 \\); the series terminates so all later \\( a_k \\) vanish." },
        { stepNumber: 2, description: "Separate the prefactor from the recurrence.", workingLatex: "\\frac{1}{f} \\sim \\frac{1}{a_0}\\sum_n d_n z^{-n} = \\frac{1}{2}\\sum_n d_n z^{-n}.", explanation: "The prefactor \\( 1/a_0 = 1/2 \\) is pulled out front, but the recurrence \\( \\sum d_{n-k} a_k = 0 \\) still uses the full \\( a_k \\) — including \\( a_0 = 2 \\) in the denominator. Keeping the two separate avoids double-counting the \\( 1/2 \\)." },
        { stepNumber: 3, description: "Write the recurrence at \\( n=1 \\).", workingLatex: "d_1 a_0 + d_0 a_1 = 0.", explanation: "Only \\( a_0 \\) and \\( a_1 \\) are nonzero, so the convolution at \\( n=1 \\) collapses to these two terms." },
        { stepNumber: 4, description: "Solve for \\( d_1 \\).", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{(1)(4)}{2} = -2.", explanation: "Divide by \\( a_0 = 2 \\). Don't conflate this division by \\( a_0 \\) with the separate prefactor \\( 1/2 \\) — they are two different appearances of the leading coefficient." },
        { stepNumber: 5, description: "Write the recurrence at \\( n=2 \\).", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0.", explanation: "Three terms now; \\( a_2 = 0 \\) removes the last one, leaving \\( d_2 a_0 + d_1 a_1 = 0 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_2 \\).", workingLatex: "d_2 = -\\frac{d_1 a_1 + d_0 a_2}{a_0} = -\\frac{(-2)(4) + 0}{2} = -\\frac{-8}{2} = 4.", explanation: "Substitute \\( d_1 = -2 \\) and \\( a_2 = 0 \\). The numerator is \\( -8 \\), so \\( d_2 = -(-8)/2 = 4 \\)." },
        { stepNumber: 7, description: "Reassemble the expansion.", workingLatex: "\\frac{1}{f} \\sim \\frac{1}{2}\\left(1 - \\frac{2}{z} + \\frac{4}{z^2} - \\cdots\\right).", explanation: "Multiply the \\( d_n \\) back through by the prefactor \\( 1/2 \\). The pattern \\( d_n = (-2)^n \\) reflects \\( 1/(2(1+2/z)) \\) summing geometrically with ratio \\( -2/z \\)." },
      ],
      finalAnswer: "\\( d_1 = -2,\\ d_2 = 4 \\); so \\( \\frac{1}{f} \\sim \\frac{1}{2}\\big(1 - \\frac{2}{z} + \\frac{4}{z^2} - \\cdots\\big) \\).",
    },
  },
  {
    id: "am1b-005",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Two expansions as \\( x \\to 0 \\) are \\( f(x) \\sim 1 + x + x^2 \\) and \\( g(x) \\sim 1 - x \\). Find the coefficients of \\( 1, x, x^2 \\) in the product \\( f(x)g(x) \\) using the Cauchy product on ascending powers.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy product", "small parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the gauge and recall the formula.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k, \\qquad x \\to 0.", explanation: "Now the gauge is ascending powers of \\( x \\) as \\( x\\to 0 \\), but the Cauchy-product formula is identical — the index \\( n \\) is simply the power of \\( x \\) instead of the power of \\( 1/z \\). Nothing else changes." },
        { stepNumber: 2, description: "Read off the coefficients.", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=1; \\qquad b_0=1,\\ b_1=-1,\\ b_2=0.", explanation: "Match \\( f \\) and \\( g \\) to \\( \\sum a_n x^n \\). Note \\( g \\) has no \\( x^2 \\) term, so \\( b_2 = 0 \\); the sign \\( b_1 = -1 \\) drives the cancellations to come." },
        { stepNumber: 3, description: "Compute the coefficient of \\( x^0 \\).", workingLatex: "c_0 = a_0 b_0 = 1\\cdot 1 = 1.", explanation: "The constant term of the product is the product of the constant terms; there is only one index pair at \\( n=0 \\)." },
        { stepNumber: 4, description: "Compute the coefficient of \\( x^1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(-1) + (1)(1) = -1 + 1 = 0.", explanation: "The two contributions \\( -1 \\) and \\( +1 \\) cancel. Keep the sign of \\( b_1 = -1 \\) firmly attached to its term, or you will get \\( 2 \\) instead of \\( 0 \\)." },
        { stepNumber: 5, description: "Compute the coefficient of \\( x^2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + (1)(-1) + (1)(1) = 0.", explanation: "The first term vanishes since \\( b_2 = 0 \\); the remaining two, \\( -1 \\) and \\( +1 \\), again cancel, so the \\( x^2 \\) coefficient is also zero." },
        { stepNumber: 6, description: "Cross-check by direct multiplication.", workingLatex: "(1+x+x^2)(1-x) = 1 - x^3 \\;\\Rightarrow\\; 1 + 0\\cdot x + 0\\cdot x^2 - x^3.", explanation: "Expanding directly, the product telescopes to \\( 1 - x^3 \\): the \\( x \\) and \\( x^2 \\) coefficients are zero, matching the convolution. The leftover \\( -x^3 \\) is beyond the order we were asked for." },
      ],
      finalAnswer: "\\( f g \\sim 1 + 0\\cdot x + 0\\cdot x^2 + \\cdots \\) (the \\(x\\) and \\(x^2\\) terms cancel).",
    },
  },
  {
    id: "am1b-006",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\dfrac{1}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (all \\( a_n = 1 \\)), use the reciprocal recurrence to find \\( d_1, d_2, d_3 \\) in \\( 1/f \\sim \\sum d_n z^{-n} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients of \\( f \\).", workingLatex: "a_0 = a_1 = a_2 = a_3 = \\cdots = 1.", explanation: "Every coefficient is 1. Since \\( a_0 = 1 \\), the reciprocal coefficients \\( d_n \\) come straight from the recurrence with no prefactor to track." },
        { stepNumber: 2, description: "Specialise the recurrence to \\( a_0 = 1 \\).", workingLatex: "d_n = -\\sum_{k=1}^{n} a_k\\, d_{n-k} \\quad (n\\ge 1).", explanation: "Split the \\( k=0 \\) term \\( d_n a_0 = d_n \\) off the convolution \\( \\sum_{k=0}^n d_{n-k} a_k = 0 \\) and move the rest across. With \\( a_0 = 1 \\) there is no division, so each \\( d_n \\) is minus the convolution of earlier values." },
        { stepNumber: 3, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -(1)(1) = -1.", explanation: "At \\( n=1 \\) the only term is \\( -a_1 d_0 \\). With \\( a_1 = 1 \\) and \\( d_0 = 1 \\) this gives \\( d_1 = -1 \\)." },
        { stepNumber: 4, description: "Solve the recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -((1)(-1) + (1)(1)) = -(-1 + 1) = 0.", explanation: "Substitute \\( d_1 = -1 \\). The two terms \\( -1 \\) and \\( +1 \\) cancel, giving \\( d_2 = 0 \\)." },
        { stepNumber: 5, description: "Solve the recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -(0 + (1)(-1) + (1)(1)) = 0.", explanation: "With \\( d_2 = 0 \\) only the last two terms remain, and they cancel: \\( -1 + 1 = 0 \\), so \\( d_3 = 0 \\)." },
        { stepNumber: 6, description: "Identify the closed form.", workingLatex: "f \\sim \\frac{1}{1 - 1/z} \\;\\Rightarrow\\; \\frac{1}{f} \\sim 1 - \\frac{1}{z}.", explanation: "All coefficients past \\( d_1 \\) vanish because \\( f \\) sums to the geometric series \\( 1/(1-1/z) \\), whose reciprocal is exactly the two-term \\( 1 - 1/z \\). This is the cleanest possible check on the recurrence." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = 0,\\ d_3 = 0 \\); so \\( 1/f \\sim 1 - \\frac{1}{z} \\).",
    },
  },

  // ── Standard: typical sheet-level products and reciprocals ────
  {
    id: "am1b-007",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim \\sum_{n=0}^{\\infty} (n+1) z^{-n} = 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\cdots \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} z^{-n} = 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) as \\( z \\to \\infty \\). Find the first four coefficients \\( c_0,\\dots,c_3 \\) of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Record the coefficient sequences.", workingLatex: "a_n = n+1:\\ 1,2,3,4,\\dots; \\qquad b_n = 1:\\ 1,1,1,1,\\dots.", explanation: "Both series are infinite, so each Cauchy sum runs over all indices up to \\( n \\) with no early truncation. Writing the first few values out makes the convolutions easy to fill in." },
        { stepNumber: 2, description: "Note the simplification from \\( b_n \\equiv 1 \\).", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k = \\sum_{k=0}^{n} a_{n-k} = a_0 + a_1 + \\cdots + a_n.", explanation: "Because every \\( b_k = 1 \\), the convolution collapses to a plain running sum of the \\( a \\)-coefficients. Spotting this turns each Cauchy product into a cumulative total." },
        { stepNumber: 3, description: "Compute \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = 1\\cdot 1 = 1.", explanation: "The \\( n=0 \\) convolution has only the single \\( k=0 \\) term, so the leading coefficient is the product of the two leading coefficients." },
        { stepNumber: 4, description: "Compute \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(1) + (2)(1) = 1 + 2 = 3.", explanation: "By the running-sum simplification this is just \\( a_0 + a_1 = 1 + 2 \\)." },
        { stepNumber: 5, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 1 + 2 + 3 = 6.", explanation: "Again the running sum \\( a_0 + a_1 + a_2 = 1 + 2 + 3 = 6 \\)." },
        { stepNumber: 6, description: "Compute \\( c_3 \\).", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = 1+2+3+4 = 10.", explanation: "The running sum \\( 1+2+3+4 = 10 \\). The \\( c_n \\) are the triangular numbers \\( 1+2+\\cdots+(n+1) = \\binom{n+2}{2} \\)." },
        { stepNumber: 7, description: "Cross-check via closed forms.", workingLatex: "f \\sim (1-\\tfrac1z)^{-2},\\ g \\sim (1-\\tfrac1z)^{-1} \\Rightarrow fg \\sim (1-\\tfrac1z)^{-3} = \\sum \\binom{n+2}{2} z^{-n}.", explanation: "Recognising \\( f \\) and \\( g \\) as derivatives of the geometric series, their product is \\( (1-1/z)^{-3} \\), whose coefficients are exactly the triangular numbers \\( 1,3,6,10 \\) — an independent confirmation." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=3,\\ c_2=6,\\ c_3=10 \\) (triangular numbers).",
    },
  },
  {
    id: "am1b-008",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 - \\dfrac{1}{z} + \\dfrac{1}{z^2} - \\dfrac{1}{z^3} + \\cdots \\) (so \\( a_n = (-1)^n \\)) and \\( g(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) (so \\( b_n = 1 \\)). Find \\( c_0,\\dots,c_3 \\) of \\( f(z)g(z) \\) and identify the closed form.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Record the coefficient sequences.", workingLatex: "a_n = (-1)^n:\\ 1,-1,1,-1; \\qquad b_n = 1:\\ 1,1,1,1.", explanation: "The alternating signs of \\( f \\) are the source of all the cancellation to come. List them explicitly so the pattern of partial sums is visible." },
        { stepNumber: 2, description: "Simplify the convolution using \\( b_n \\equiv 1 \\).", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} = a_0 + a_1 + \\cdots + a_n.", explanation: "With every \\( b_k = 1 \\), each \\( c_n \\) is the partial sum of the alternating sequence \\( 1,-1,1,-1,\\dots \\). Partial sums of \\( (-1)^k \\) toggle between 1 and 0." },
        { stepNumber: 3, description: "Compute \\( c_0 \\) and \\( c_1 \\).", workingLatex: "c_0 = 1, \\qquad c_1 = a_0 + a_1 = 1 + (-1) = 0.", explanation: "The first partial sum is 1; the second, \\( 1 - 1 \\), cancels to 0." },
        { stepNumber: 4, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 + a_1 + a_2 = 1 - 1 + 1 = 1.", explanation: "An odd number of alternating terms doesn't fully cancel — the partial sum \\( 1-1+1 \\) leaves 1." },
        { stepNumber: 5, description: "Compute \\( c_3 \\).", workingLatex: "c_3 = a_0 + a_1 + a_2 + a_3 = 1 - 1 + 1 - 1 = 0.", explanation: "An even count cancels in pairs back to 0. So \\( c_n = 1 \\) for even \\( n \\) and \\( 0 \\) for odd \\( n \\)." },
        { stepNumber: 6, description: "Identify the closed form.", workingLatex: "f \\sim \\frac{1}{1+1/z},\\ g \\sim \\frac{1}{1-1/z} \\;\\Rightarrow\\; fg \\sim \\frac{1}{1-1/z^2} = \\sum_{m\\ge 0} z^{-2m}.", explanation: "Summing each geometric series and multiplying gives \\( 1/(1-1/z^2) \\), whose only nonzero coefficients sit at even powers — matching \\( c_n = 1 \\) (\\( n \\) even), \\( 0 \\) (\\( n \\) odd) exactly." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=0,\\ c_2=1,\\ c_3=0 \\); product \\( \\sim \\sum_{m} z^{-2m} \\).",
    },
  },
  {
    id: "am1b-009",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 2 + \\dfrac{3}{z} + \\dfrac{4}{z^2} + \\dfrac{5}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = n+2 \\)). Find \\( d_1, d_2, d_3 \\) so that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{2}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), with \\( d_0 = 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=2,\\ a_1=3,\\ a_2=4,\\ a_3=5.", explanation: "The prefactor \\( 1/a_0 = 1/2 \\) is factored out front; the recurrence \\( \\sum d_{n-k}a_k = 0 \\) still uses \\( a_0 = 2 \\) in each denominator. The two roles of \\( a_0 \\) must not be confused." },
        { stepNumber: 2, description: "State the recurrence solved for \\( d_n \\).", workingLatex: "d_n = -\\frac{1}{a_0}\\sum_{k=1}^{n} a_k\\, d_{n-k}.", explanation: "Peel off the \\( k=0 \\) term \\( d_n a_0 \\) and divide by \\( a_0 \\neq 0 \\). The right side uses only earlier \\( d \\)-values, so we can climb \\( n = 1, 2, 3 \\) in turn." },
        { stepNumber: 3, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -\\frac{a_1 d_0}{a_0} = -\\frac{(3)(1)}{2} = -\\frac{3}{2}.", explanation: "At \\( n=1 \\) the sum has the single term \\( a_1 d_0 \\). Divide it by \\( a_0 = 2 \\)." },
        { stepNumber: 4, description: "Form the numerator for \\( d_2 \\).", workingLatex: "a_1 d_1 + a_2 d_0 = (3)\\left(-\\frac{3}{2}\\right) + (4)(1) = -\\frac{9}{2} + 4 = -\\frac{1}{2}.", explanation: "Substitute \\( d_1 = -3/2 \\). Combining \\( -9/2 + 4 = -9/2 + 8/2 = -1/2 \\); keep the running fractions exact rather than rounding." },
        { stepNumber: 5, description: "Solve for \\( d_2 \\).", workingLatex: "d_2 = -\\frac{1}{a_0}\\left(-\\frac{1}{2}\\right) = -\\frac{1}{2}\\cdot\\left(-\\frac{1}{2}\\right) = \\frac{1}{4}.", explanation: "Divide the numerator \\( -1/2 \\) by \\( a_0 = 2 \\) and negate: \\( d_2 = 1/4 \\)." },
        { stepNumber: 6, description: "Form the numerator for \\( d_3 \\).", workingLatex: "a_1 d_2 + a_2 d_1 + a_3 d_0 = (3)\\tfrac14 + (4)\\left(-\\tfrac32\\right) + (5)(1) = \\frac{3}{4} - 6 + 5 = -\\frac{1}{4}.", explanation: "Each new \\( d_n \\) reuses all earlier \\( d \\)'s. Here \\( 3/4 - 6 + 5 = 3/4 - 1 = -1/4 \\)." },
        { stepNumber: 7, description: "Solve for \\( d_3 \\).", workingLatex: "d_3 = -\\frac{1}{a_0}\\left(-\\frac{1}{4}\\right) = -\\frac{1}{2}\\cdot\\left(-\\frac{1}{4}\\right) = \\frac{1}{8}.", explanation: "Divide the numerator \\( -1/4 \\) by \\( a_0 = 2 \\) and negate, giving \\( d_3 = 1/8 \\)." },
      ],
      finalAnswer: "\\( d_1 = -\\frac{3}{2},\\ d_2 = \\frac{1}{4},\\ d_3 = \\frac{1}{8} \\).",
    },
  },
  {
    id: "am1b-010",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( f(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\dfrac{4}{z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = n+1 \\)), find the reciprocal coefficients \\( d_1, d_2, d_3 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\) and identify the closed form.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=1,\\ a_1=2,\\ a_2=3,\\ a_3=4.", explanation: "Note \\( f \\sim \\sum (n+1)z^{-n} = (1-1/z)^{-2} \\), so we expect \\( 1/f \\sim (1-1/z)^2 \\), a terminating square. This is the result to aim at." },
        { stepNumber: 2, description: "Specialise the recurrence to \\( a_0 = 1 \\).", workingLatex: "d_n = -\\sum_{k=1}^{n} a_k\\, d_{n-k} \\quad (n\\ge 1).", explanation: "Because \\( a_0 = 1 \\) there is no division: each \\( d_n \\) is minus the convolution of the \\( a_k \\) with the earlier \\( d \\)-values." },
        { stepNumber: 3, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -(2)(1) = -2.", explanation: "At \\( n=1 \\) only \\( a_1 d_0 \\) appears, so \\( d_1 = -a_1 = -2 \\)." },
        { stepNumber: 4, description: "Solve the recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -((2)(-2) + (3)(1)) = -(-4 + 3) = 1.", explanation: "Substitute \\( d_1 = -2 \\). The bracket is \\( -4 + 3 = -1 \\), so \\( d_2 = 1 \\)." },
        { stepNumber: 5, description: "Solve the recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -((2)(1) + (3)(-2) + (4)(1)) = -(2 - 6 + 4) = 0.", explanation: "The bracket is \\( 2 - 6 + 4 = 0 \\), so \\( d_3 = 0 \\)." },
        { stepNumber: 6, description: "Identify the terminating closed form.", workingLatex: "\\frac{1}{f} \\sim 1 - \\frac{2}{z} + \\frac{1}{z^2} = \\left(1 - \\frac{1}{z}\\right)^2.", explanation: "All higher \\( d_n \\) vanish: the reciprocal is the finite expansion \\( (1-1/z)^2 = 1 - 2/z + 1/z^2 \\), confirming the prediction from Step 1." },
      ],
      finalAnswer: "\\( d_1=-2,\\ d_2=1,\\ d_3=0 \\); \\( 1/f \\sim 1 - \\frac{2}{z} + \\frac{1}{z^2} = (1-1/z)^2 \\).",
    },
  },
  {
    id: "am1b-011",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 3 + \\dfrac{1}{z^2} + \\dfrac{5}{z^4} \\) (so \\( a_0 = 3,\\ a_1 = 0,\\ a_2 = 1,\\ a_3 = 0,\\ a_4 = 5 \\)). Find \\( d_1, d_2, d_3, d_4 \\) in \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{3}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), with \\( d_0 = 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "even series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=3,\\ a_1=0,\\ a_2=1,\\ a_3=0,\\ a_4=5.", explanation: "Because the odd-index coefficients vanish (the series has only even powers of \\( 1/z \\)), we expect the odd reciprocal coefficients \\( d_1, d_3 \\) to vanish too. The prefactor \\( 1/3 \\) sits out front." },
        { stepNumber: 2, description: "State the recurrence solved for \\( d_n \\).", workingLatex: "d_n = -\\frac{1}{a_0}\\sum_{k=1}^{n} a_k\\, d_{n-k} = -\\frac{1}{3}\\sum_{k=1}^{n} a_k\\, d_{n-k}.", explanation: "Peel off \\( d_n a_0 \\) and divide by \\( a_0 = 3 \\). Only even-index \\( a_k \\) are nonzero, which will repeatedly knock terms out." },
        { stepNumber: 3, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -\\frac{a_1 d_0}{a_0} = -\\frac{(0)(1)}{3} = 0.", explanation: "Since \\( a_1 = 0 \\), the only term in the \\( n=1 \\) convolution is zero, so \\( d_1 = 0 \\)." },
        { stepNumber: 4, description: "Solve the recurrence at \\( n=2 \\).", workingLatex: "d_2 = -\\frac{a_1 d_1 + a_2 d_0}{a_0} = -\\frac{0 + (1)(1)}{3} = -\\frac{1}{3}.", explanation: "Only \\( a_2 d_0 = 1 \\) contributes; divide by \\( a_0 = 3 \\) to get \\( d_2 = -1/3 \\)." },
        { stepNumber: 5, description: "Solve the recurrence at \\( n=3 \\).", workingLatex: "d_3 = -\\frac{a_1 d_2 + a_2 d_1 + a_3 d_0}{a_0} = -\\frac{0 + 0 + 0}{3} = 0.", explanation: "Every term contains either an odd-index \\( a \\) (zero) or the already-zero \\( d_1 \\), so the whole numerator vanishes and \\( d_3 = 0 \\)." },
        { stepNumber: 6, description: "Assemble the numerator for \\( d_4 \\).", workingLatex: "a_1 d_3 + a_2 d_2 + a_3 d_1 + a_4 d_0 = (1)\\left(-\\tfrac13\\right) + (5)(1) = -\\frac{1}{3} + 5 = \\frac{14}{3}.", explanation: "Only \\( a_2 d_2 \\) and \\( a_4 d_0 \\) survive (the odd-index terms vanish). The sum is \\( -1/3 + 5 = 14/3 \\)." },
        { stepNumber: 7, description: "Solve for \\( d_4 \\).", workingLatex: "d_4 = -\\frac{1}{a_0}\\cdot\\frac{14}{3} = -\\frac{1}{3}\\cdot\\frac{14}{3} = -\\frac{14}{9}.", explanation: "Divide the numerator \\( 14/3 \\) by \\( a_0 = 3 \\) and negate, giving \\( d_4 = -14/9 \\)." },
      ],
      finalAnswer: "\\( d_1 = 0,\\ d_2 = -\\frac{1}{3},\\ d_3 = 0,\\ d_4 = -\\frac{14}{9} \\).",
    },
  },
  {
    id: "am1b-012",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( x \\to 0 \\), \\( f(x) \\sim 1 + x + \\dfrac{x^2}{2} + \\dfrac{x^3}{6} \\) and \\( g(x) \\sim 1 - x + \\dfrac{x^2}{2} - \\dfrac{x^3}{6} \\). Find the coefficients of \\( x^0, x^1, x^2, x^3 \\) in the product \\( f(x)g(x) \\), and comment on the result.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "small parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_n:\\ 1,\\,1,\\,\\tfrac12,\\,\\tfrac16; \\qquad b_n:\\ 1,\\,-1,\\,\\tfrac12,\\,-\\tfrac16.", explanation: "These are the truncated Taylor series of \\( e^{x} \\) and \\( e^{-x} \\), so we anticipate the product collapsing to 1. Watch the alternating signs in \\( b_n \\)." },
        { stepNumber: 2, description: "Recall the convolution formula.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k.", explanation: "The coefficient of \\( x^n \\) gathers every pairing whose exponents add to \\( n \\). We apply it at \\( n = 0, 1, 2, 3 \\)." },
        { stepNumber: 3, description: "Coefficient of \\( x^0 \\).", workingLatex: "c_0 = a_0 b_0 = 1\\cdot 1 = 1.", explanation: "The leading product of the two constant terms; only one index pair contributes at \\( n=0 \\)." },
        { stepNumber: 4, description: "Coefficient of \\( x^1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(-1) + (1)(1) = -1 + 1 = 0.", explanation: "The two contributions cancel; track the sign on \\( b_1 = -1 \\) carefully." },
        { stepNumber: 5, description: "Coefficient of \\( x^2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = (1)\\tfrac12 + (1)(-1) + \\tfrac12(1) = \\frac{1}{2} - 1 + \\frac{1}{2} = 0.", explanation: "Three terms: \\( 1/2 \\), then \\( (1)(-1) = -1 \\), then \\( (1/2)(1) = 1/2 \\). They sum to zero." },
        { stepNumber: 6, description: "Coefficient of \\( x^3 \\).", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = -\\frac{1}{6} + \\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6} = 0.", explanation: "The four terms are \\( (1)(-1/6),\\ (1)(1/2),\\ (1/2)(-1),\\ (1/6)(1) \\); they cancel in pairs." },
        { stepNumber: 7, description: "Comment on the result.", workingLatex: "f(x)g(x) \\sim 1 + 0\\cdot x + 0\\cdot x^2 + 0\\cdot x^3, \\qquad e^x e^{-x} = 1.", explanation: "Every coefficient past the constant cancels to this order, consistent with the exact identity \\( e^x e^{-x} = 1 \\). The truncated series reproduce the cancellation term by term." },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1 = c_2 = c_3 = 0 \\) (product \\(\\sim 1\\), matching \\(e^x e^{-x}=1\\)).",
    },
  },
  {
    id: "am1b-013",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} + \\cdots \\) as \\( z \\to \\infty \\) (so \\( a_n = 1/n! \\)). Find the reciprocal coefficients \\( d_1, d_2, d_3 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\) and identify the function.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "exponential"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=\\frac{1}{2},\\ a_3=\\frac{1}{6}.", explanation: "These are \\( 1/n! \\), so \\( f \\) is the expansion of \\( e^{1/z} \\); we therefore expect \\( 1/f = e^{-1/z} \\) with coefficients \\( (-1)^n/n! \\). Keep that target in mind as a check." },
        { stepNumber: 2, description: "Specialise the recurrence to \\( a_0 = 1 \\).", workingLatex: "d_n = -\\sum_{k=1}^{n} a_k\\, d_{n-k}.", explanation: "With \\( a_0 = 1 \\) there is no division; each \\( d_n \\) is minus the convolution of the \\( a_k \\) with earlier \\( d \\)-values." },
        { stepNumber: 3, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -(1)(1) = -1.", explanation: "At \\( n=1 \\) the only term is \\( -a_1 d_0 = -1 \\)." },
        { stepNumber: 4, description: "Solve the recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -\\left((1)(-1) + \\tfrac12(1)\\right) = -\\left(-1 + \\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "Substitute \\( d_1 = -1 \\): the bracket is \\( -1 + 1/2 = -1/2 \\), so \\( d_2 = 1/2 \\)." },
        { stepNumber: 5, description: "Solve the recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -\\left(\\tfrac12 + \\tfrac12(-1) + \\tfrac16\\right) = -\\frac{1}{6}.", explanation: "The bracket is \\( 1/2 - 1/2 + 1/6 = 1/6 \\), so \\( d_3 = -1/6 \\)." },
        { stepNumber: 6, description: "Identify the function.", workingLatex: "\\frac{1}{f} \\sim 1 - \\frac{1}{z} + \\frac{1}{2z^2} - \\frac{1}{6z^3} = e^{-1/z}, \\quad d_n = \\frac{(-1)^n}{n!}.", explanation: "The coefficients are \\( (-1)^n/n! \\), exactly the series of \\( e^{-1/z} \\). This is the reciprocal of \\( e^{1/z} \\), as it must be." },
      ],
      finalAnswer: "\\( d_1 = -1,\\ d_2 = \\frac{1}{2},\\ d_3 = -\\frac{1}{6} \\); \\( 1/f \\sim e^{-1/z} \\).",
    },
  },
  {
    id: "am1b-014",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( x \\to 0 \\), \\( \\cos x \\sim 1 - \\dfrac{x^2}{2} + \\dfrac{x^4}{24} \\). Using the reciprocal recurrence on this series, find the expansion of \\( \\sec x = 1/\\cos x \\) up to and including the \\( x^4 \\) term.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the coefficients of \\( \\cos x \\).", workingLatex: "a_0=1,\\ a_1=0,\\ a_2=-\\frac{1}{2},\\ a_3=0,\\ a_4=\\frac{1}{24}.", explanation: "Index by powers of \\( x \\). The odd coefficients vanish because cosine is even, so the odd reciprocal coefficients will vanish too — that halves the work." },
        { stepNumber: 2, description: "Specialise the recurrence to \\( a_0 = 1 \\).", workingLatex: "d_n = -\\sum_{k=1}^{n} a_k\\, d_{n-k}.", explanation: "With \\( a_0 = 1 \\) there is no division. The \\( d_n \\) are the coefficients of \\( \\sec x = 1/\\cos x \\)." },
        { stepNumber: 3, description: "Solve the odd cases \\( n=1,3 \\).", workingLatex: "d_1 = -a_1 d_0 = 0, \\qquad d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = 0.", explanation: "Every term in these convolutions contains an odd-index \\( a \\) (zero) or the already-zero \\( d_1 \\), so both vanish." },
        { stepNumber: 4, description: "Solve the recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -\\left(0 -\\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "Only \\( a_2 d_0 = -1/2 \\) contributes, so \\( d_2 = 1/2 \\)." },
        { stepNumber: 5, description: "Assemble the numerator for \\( d_4 \\).", workingLatex: "a_1 d_3 + a_2 d_2 + a_3 d_1 + a_4 d_0 = \\left(-\\tfrac12\\right)\\tfrac12 + \\tfrac{1}{24} = -\\frac{1}{4} + \\frac{1}{24} = -\\frac{5}{24}.", explanation: "Surviving terms are \\( a_2 d_2 = -1/4 \\) and \\( a_4 d_0 = 1/24 \\). Over denominator 24: \\( -6/24 + 1/24 = -5/24 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_4 \\).", workingLatex: "d_4 = -\\left(-\\frac{5}{24}\\right) = \\frac{5}{24}.", explanation: "Negating the numerator (since \\( a_0 = 1 \\)) gives \\( d_4 = 5/24 \\)." },
        { stepNumber: 7, description: "Assemble the series for \\( \\sec x \\).", workingLatex: "\\sec x \\sim 1 + \\frac{x^2}{2} + \\frac{5x^4}{24}.", explanation: "Collect \\( d_0, d_2, d_4 \\) onto the even powers. This matches the standard Maclaurin series of \\( \\sec x \\)." },
      ],
      finalAnswer: "\\( \\sec x \\sim 1 + \\frac{x^2}{2} + \\frac{5x^4}{24} \\).",
    },
  },
  {
    id: "am1b-015",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{a}{z} \\) as \\( z \\to \\infty \\), where \\( a \\) is a constant. Using the reciprocal recurrence, show that \\( \\dfrac{1}{f(z)} \\sim \\sum_{n=0}^{\\infty} (-a)^n z^{-n} \\), and verify by summing the geometric series.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "geometric series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0 = 1,\\ a_1 = a,\\ a_2 = a_3 = \\cdots = 0.", explanation: "Only the constant and \\( 1/z \\) terms are present, so the convolution will collapse to a two-term recurrence — the simplest nontrivial case." },
        { stepNumber: 2, description: "Set up the recurrence for \\( n\\ge 1 \\).", workingLatex: "\\sum_{k=0}^{n} d_{n-k} a_k = d_n a_0 + d_{n-1} a_1 = d_n + a\\, d_{n-1} = 0.", explanation: "Only \\( a_0 \\) and \\( a_1 \\) are nonzero, so for every \\( n\\ge 1 \\) the convolution keeps just the \\( k=0 \\) and \\( k=1 \\) terms. All higher \\( a_k \\) drop out." },
        { stepNumber: 3, description: "Rearrange to a first-order recurrence.", workingLatex: "d_n = -a\\, d_{n-1}.", explanation: "Each \\( d_n \\) is \\( -a \\) times the previous coefficient — a geometric recurrence with ratio \\( -a \\)." },
        { stepNumber: 4, description: "Unroll from \\( d_0 = 1 \\).", workingLatex: "d_n = (-a)\\, d_{n-1} = (-a)^2 d_{n-2} = \\cdots = (-a)^n d_0 = (-a)^n.", explanation: "Iterating the recurrence \\( n \\) times multiplies \\( d_0 = 1 \\) by \\( (-a)^n \\), giving the closed form for every coefficient." },
        { stepNumber: 5, description: "Verify by direct summation.", workingLatex: "\\frac{1}{1 + a/z} = \\sum_{n=0}^{\\infty} \\left(-\\frac{a}{z}\\right)^n = \\sum_{n=0}^{\\infty} (-a)^n z^{-n}.", explanation: "Treating \\( a/z \\) as the ratio, the geometric series \\( 1/(1+r) = \\sum (-r)^n \\) with \\( r = a/z \\) reproduces the recurrence coefficients exactly, confirming the result independently." },
      ],
      finalAnswer: "\\( d_n = (-a)^n \\), so \\( 1/f \\sim \\sum_{n\\ge 0} (-a)^n z^{-n} \\).",
    },
  },
  {
    id: "am1b-016",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} \\) and \\( g(z) \\sim 1 - \\dfrac{1}{z} \\). Find the first four coefficients of \\( f(z)g(z) \\sim \\sum c_n z^{-n} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_n:\\ 1,1,1,0; \\qquad b_n:\\ 1,-1,0,0.", explanation: "Both series terminate; the sign \\( b_1 = -1 \\) drives the cancellations. List the zeros explicitly to keep the convolution bookkeeping clean." },
        { stepNumber: 2, description: "Compute \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = (1)(1) = 1.", explanation: "The constant term is the product of the two leading coefficients." },
        { stepNumber: 3, description: "Compute \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(-1) + (1)(1) = -1 + 1 = 0.", explanation: "The two \\( z^{-1} \\) contributions cancel." },
        { stepNumber: 4, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = 0 + (1)(-1) + (1)(1) = 0.", explanation: "The first term is zero (\\( b_2 = 0 \\)); the remaining two, \\( -1 \\) and \\( +1 \\), cancel." },
        { stepNumber: 5, description: "Compute \\( c_3 \\).", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = 0 + 0 + (1)(-1) + 0 = -1.", explanation: "Only \\( a_2 b_1 = (1)(-1) \\) survives among the four pairs, giving \\( c_3 = -1 \\)." },
        { stepNumber: 6, description: "Cross-check by telescoping.", workingLatex: "\\left(1+\\tfrac1z+\\tfrac1{z^2}\\right)\\left(1-\\tfrac1z\\right) = 1 - \\frac{1}{z^3}.", explanation: "The product telescopes: it equals \\( 1 - 1/z^3 \\), so \\( c_0 = 1 \\), \\( c_1 = c_2 = 0 \\), and \\( c_3 = -1 \\), matching the convolution." },
      ],
      finalAnswer: "\\( c_0=1,\\ c_1=0,\\ c_2=0,\\ c_3=-1 \\); product \\( \\sim 1 - z^{-3} \\).",
    },
  },
  {
    id: "am1b-017",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given the asymptotic expansion \\( f(z) \\sim 1 - \\dfrac{1}{z} - \\dfrac{1}{z^2} \\) as \\( z \\to \\infty \\) (so \\( a_0=1,\\ a_1=-1,\\ a_2=-1 \\), higher zero), find the reciprocal coefficients \\( d_1,\\dots,d_5 \\) of \\( 1/f \\sim \\sum d_n z^{-n} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "Fibonacci"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=1,\\ a_1=-1,\\ a_2=-1,\\ a_3=a_4=a_5=0.", explanation: "Since \\( f \\sim 1 - 1/z - 1/z^2 \\), its reciprocal is the Fibonacci generating function \\( 1/(1 - w - w^2) \\) with \\( w = 1/z \\). That tells us the answer in advance." },
        { stepNumber: 2, description: "Collapse the recurrence to three terms.", workingLatex: "d_n a_0 + d_{n-1} a_1 + d_{n-2} a_2 = d_n - d_{n-1} - d_{n-2} = 0.", explanation: "For \\( n\\ge 2 \\) only \\( a_0,a_1,a_2 \\) contribute (the rest are zero); for \\( n=1 \\) only \\( a_0,a_1 \\). With \\( a_1=a_2=-1 \\) this rearranges to the Fibonacci rule." },
        { stepNumber: 3, description: "Read off the Fibonacci rule.", workingLatex: "d_n = d_{n-1} + d_{n-2} \\quad (n \\ge 2).", explanation: "Moving the negative terms across gives \\( d_n = d_{n-1} + d_{n-2} \\): each coefficient is the sum of the previous two." },
        { stepNumber: 4, description: "Solve at \\( n=1 \\) (the seed).", workingLatex: "d_1 a_0 + d_0 a_1 = 0 \\;\\Rightarrow\\; d_1 = -d_0 a_1 = -(1)(-1) = 1.", explanation: "At \\( n=1 \\) only the \\( a_0,a_1 \\) terms exist; the double negative gives \\( d_1 = 1 \\). With \\( d_0 = 1 \\) we have the two Fibonacci seeds." },
        { stepNumber: 5, description: "Solve at \\( n=2,3 \\).", workingLatex: "d_2 = d_1 + d_0 = 1 + 1 = 2, \\qquad d_3 = d_2 + d_1 = 2 + 1 = 3.", explanation: "Apply the Fibonacci rule with the seeds \\( d_0=1, d_1=1 \\)." },
        { stepNumber: 6, description: "Solve at \\( n=4,5 \\).", workingLatex: "d_4 = d_3 + d_2 = 3 + 2 = 5, \\qquad d_5 = d_4 + d_3 = 5 + 3 = 8.", explanation: "Continuing the recurrence. The \\( d_n \\) are the Fibonacci numbers \\( 1,1,2,3,5,8,\\dots \\), confirming the generating-function prediction." },
      ],
      finalAnswer: "\\( d_1=1,\\ d_2=2,\\ d_3=3,\\ d_4=5,\\ d_5=8 \\) (Fibonacci numbers).",
    },
  },
  {
    id: "am1b-018",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 4 + \\dfrac{2}{z} + \\dfrac{1}{z^2} \\). Find the first three coefficients (the constant, \\( z^{-1} \\) and \\( z^{-2} \\)) of \\( 1/f(z) \\), giving each in fully simplified form.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List coefficients and factor out \\( 1/a_0 \\).", workingLatex: "a_0=4,\\ a_1=2,\\ a_2=1; \\qquad \\frac{1}{f} \\sim \\frac{1}{4}\\sum_n d_n z^{-n}.", explanation: "Pulling out the prefactor \\( 1/a_0 = 1/4 \\) keeps the recurrence in terms of the normalised \\( d_n \\) with \\( d_0 = 1 \\). The actual expansion coefficient of \\( z^{-n} \\) will be \\( d_n/4 \\)." },
        { stepNumber: 2, description: "Solve the recurrence at \\( n=1 \\).", workingLatex: "d_1 = -\\frac{a_1 d_0}{a_0} = -\\frac{(2)(1)}{4} = -\\frac{1}{2}.", explanation: "From \\( d_1 a_0 + d_0 a_1 = 0 \\), divide \\( a_1 d_0 \\) by \\( a_0 = 4 \\)." },
        { stepNumber: 3, description: "Form the numerator for \\( d_2 \\).", workingLatex: "a_1 d_1 + a_2 d_0 = (2)\\left(-\\tfrac12\\right) + (1)(1) = -1 + 1 = 0.", explanation: "Substitute \\( d_1 = -1/2 \\); the numerator is \\( -1 + 1 = 0 \\)." },
        { stepNumber: 4, description: "Solve for \\( d_2 \\).", workingLatex: "d_2 = -\\frac{0}{a_0} = 0.", explanation: "With a zero numerator, \\( d_2 = 0 \\) regardless of \\( a_0 \\)." },
        { stepNumber: 5, description: "Re-apply the prefactor and report.", workingLatex: "\\frac{1}{f} \\sim \\frac{d_0}{4} + \\frac{d_1}{4z} + \\frac{d_2}{4z^2} = \\frac{1}{4} - \\frac{1}{8z} + \\frac{0}{z^2} + \\cdots.", explanation: "The reported coefficient of \\( z^{-n} \\) is \\( d_n/a_0 \\): \\( 1/4 \\), then \\( (-1/2)/4 = -1/8 \\), then \\( 0 \\). Don't forget to re-apply the \\( 1/4 \\) when stating the final coefficients." },
      ],
      finalAnswer: "\\( \\frac{1}{f} \\sim \\frac{1}{4} - \\frac{1}{8z} + 0\\cdot z^{-2} + \\cdots \\).",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level ────
  {
    id: "am1b-019",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim \\sum_{n=0}^{\\infty} a_n z^{-n} \\) and \\( g(z) \\sim \\sum_{n=0}^{\\infty} b_n z^{-n} \\) as \\( z \\to \\infty \\). Show that \\( f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "proof", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the definition of an asymptotic expansion.", workingLatex: "f(z) - \\sum_{n=0}^{N} a_n z^{-n} = o(z^{-N}) \\quad (z\\to\\infty), \\ \\forall N.", explanation: "The strategy is to work at a fixed truncation order \\( N \\), control the remainder, and then let \\( N \\) be arbitrary. The defining property is that the error after \\( N+1 \\) terms is smaller than the last retained term." },
        { stepNumber: 2, description: "Write each function as a truncation plus remainder.", workingLatex: "f(z) = \\sum_{n=0}^{N} a_n z^{-n} + R_f, \\qquad g(z) = \\sum_{n=0}^{N} b_n z^{-n} + R_g,", explanation: "By the definition just stated, the remainders satisfy \\( R_f = o(z^{-N}) \\) and \\( R_g = o(z^{-N}) \\). Splitting off the remainder lets us multiply finite polynomials exactly and bound the rest separately." },
        { stepNumber: 3, description: "Multiply the two truncated polynomials.", workingLatex: "\\left(\\sum_{m=0}^{N} a_m z^{-m}\\right)\\left(\\sum_{j=0}^{N} b_j z^{-j}\\right) = \\sum_{m=0}^{N}\\sum_{j=0}^{N} a_m b_j\\, z^{-(m+j)}.", explanation: "This is a finite product of finite sums, so we may expand freely with no convergence concerns — that is the whole point of truncating first." },
        { stepNumber: 4, description: "Collect terms by total power \\( n = m+j \\).", workingLatex: "= \\sum_{n=0}^{N}\\left(\\sum_{k=0}^{n} a_{n-k} b_k\\right) z^{-n} \\; + \\; \\sum_{n=N+1}^{2N}(\\cdots) z^{-n}.", explanation: "Grouping by \\( n = m+j \\) and writing \\( m = n-k,\\ j = k \\) gives exactly the Cauchy coefficient \\( c_n \\) for \\( n\\le N \\); the leftover high-power terms with \\( n > N \\) are all \\( O(z^{-(N+1)}) \\)." },
        { stepNumber: 5, description: "Bound the cross terms involving remainders.", workingLatex: "R_f \\cdot g = o(z^{-N}),\\quad f\\cdot R_g = o(z^{-N}),\\quad R_f R_g = o(z^{-N}).", explanation: "Each remainder is \\( o(z^{-N}) \\) and the other factor is \\( O(1) \\) (it tends to its finite leading value), so every remainder cross-term is itself \\( o(z^{-N}) \\)." },
        { stepNumber: 6, description: "Assemble the error estimate.", workingLatex: "f(z)g(z) - \\sum_{n=0}^{N} c_n z^{-n} = o(z^{-N}) \\quad (z\\to\\infty).", explanation: "The high-power tail from Step 4 is \\( O(z^{-(N+1)}) = o(z^{-N}) \\), and the remainder cross-terms from Step 5 are \\( o(z^{-N}) \\); their sum is \\( o(z^{-N}) \\)." },
        { stepNumber: 7, description: "Conclude for all \\( N \\).", workingLatex: "\\therefore\\ f(z)g(z) \\sim \\sum_{n=0}^{\\infty} c_n z^{-n}, \\quad c_n = \\sum_{k=0}^{n} a_{n-k} b_k.", explanation: "Since \\( N \\) was arbitrary, the partial sums satisfy the defining estimate at every order, which is precisely the definition of the asymptotic expansion." },
      ],
      finalAnswer: "\\( f g \\sim \\sum_{n} c_n z^{-n} \\) with \\( c_n = \\sum_{k=0}^{n} a_{n-k} b_k \\).",
    },
  },
  {
    id: "am1b-020",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim a_0 + \\dfrac{a_1}{z} + \\dfrac{a_2}{z^2} + \\cdots \\) as \\( z \\to \\infty \\) with \\( a_0 \\neq 0 \\). Show by induction (or otherwise) that \\( \\dfrac{1}{f(z)} \\sim \\dfrac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n} \\), where \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\) for \\( n \\ge 1 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "proof", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use \\( a_0 \\neq 0 \\) to justify the reciprocal.", workingLatex: "f(z) \\to a_0 \\neq 0 \\;\\Rightarrow\\; \\frac{1}{f(z)} \\to \\frac{1}{a_0} \\quad (z\\to\\infty).", explanation: "Continuity of the reciprocal at a nonzero value guarantees \\( 1/f \\) is well defined and bounded for large \\( z \\), so it admits an expansion in powers of \\( z^{-1} \\). The condition \\( a_0 \\neq 0 \\) is essential — it is what makes the leading term \\( 1/a_0 \\) finite." },
        { stepNumber: 2, description: "Posit the form and impose \\( f\\cdot(1/f) = 1 \\).", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\qquad f(z)\\cdot\\frac{1}{f(z)} \\sim 1.", explanation: "Write the unknown reciprocal coefficients \\( d_n \\) and demand that their product with \\( f \\) be asymptotic to the constant 1. Matching coefficients will pin down the \\( d_n \\)." },
        { stepNumber: 3, description: "Apply the Cauchy product (Q19) to \\( f \\) and \\( 1/f \\).", workingLatex: "f\\cdot\\frac{1}{f} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty}\\left(\\sum_{k=0}^{n} a_{n-k} d_k\\right) z^{-n}.", explanation: "Multiplying two asymptotic series gives a Cauchy product; here one factor is \\( f \\) with coefficients \\( a_k \\), the other carries \\( d_k \\) (times the prefactor \\( 1/a_0 \\))." },
        { stepNumber: 4, description: "Match the constant term (\\( n=0 \\)).", workingLatex: "\\frac{1}{a_0}\\,a_0 d_0 = 1 \\;\\Rightarrow\\; d_0 = 1.", explanation: "The \\( n=0 \\) coefficient of the product is \\( (1/a_0)a_0 d_0 \\), which must equal 1; this fixes \\( d_0 = 1 \\)." },
        { stepNumber: 5, description: "Match coefficients for \\( n\\ge 1 \\).", workingLatex: "\\frac{1}{a_0}\\sum_{k=0}^{n} a_{n-k} d_k = 0 \\;\\Rightarrow\\; \\sum_{k=0}^{n} a_{n-k} d_k = 0.", explanation: "All coefficients of \\( z^{-n} \\) for \\( n\\ge 1 \\) in the constant 1 are zero. The prefactor \\( 1/a_0 \\neq 0 \\) divides out, and re-indexing \\( k \\mapsto n-k \\) recasts this as the stated form \\( \\sum d_{n-k} a_k = 0 \\)." },
        { stepNumber: 6, description: "Solve the recurrence — the inductive step.", workingLatex: "a_0 d_n = -\\sum_{k=1}^{n} a_k d_{n-k} \\;\\Rightarrow\\; d_n = -\\frac{1}{a_0}\\sum_{k=1}^{n} a_k d_{n-k}.", explanation: "Split off the \\( k=0 \\) term (\\( a_0 d_n \\)) and divide by \\( a_0 \\neq 0 \\). The right side uses only \\( d_0,\\dots,d_{n-1} \\), so assuming those exist, \\( d_n \\) exists and is unique — the induction closes." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "\\frac{1}{f(z)} \\sim \\frac{1}{a_0}\\sum_{n=0}^{\\infty} d_n z^{-n}, \\quad d_0=1,\\ \\sum_{k=0}^{n} d_{n-k}a_k = 0.", explanation: "Base case \\( d_0 = 1 \\) plus the inductive step give existence and uniqueness of the coefficients for all \\( n \\), completing the proof." },
      ],
      finalAnswer: "Reciprocal coefficients are uniquely determined by \\( d_0 = 1 \\) and \\( \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\).",
    },
  },
  {
    id: "am1b-021",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} + \\cdots = e^{1/z} \\) and \\( g(z) \\sim 1 - \\dfrac{1}{z} + \\dfrac{1}{2z^2} - \\dfrac{1}{6z^3} + \\cdots = e^{-1/z} \\). (a) Compute the first four Cauchy coefficients \\( c_0,\\dots,c_3 \\) of \\( fg \\). (b) Verify they are consistent with \\( fg = 1 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "exponential", "consistency check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients.", workingLatex: "a_n = \\frac{1}{n!}:\\ 1,1,\\tfrac12,\\tfrac16; \\qquad b_n = \\frac{(-1)^n}{n!}:\\ 1,-1,\\tfrac12,-\\tfrac16.", explanation: "These are the Taylor coefficients of \\( e^{1/z} \\) and \\( e^{-1/z} \\) in the gauge \\( 1/z \\); the only difference is the alternating sign in \\( b_n \\)." },
        { stepNumber: 2, description: "Compute \\( c_0 \\).", workingLatex: "c_0 = a_0 b_0 = (1)(1) = 1.", explanation: "The leading product of the two constant terms." },
        { stepNumber: 3, description: "Compute \\( c_1 \\).", workingLatex: "c_1 = a_0 b_1 + a_1 b_0 = (1)(-1) + (1)(1) = -1 + 1 = 0.", explanation: "The two \\( z^{-1} \\) contributions cancel exactly." },
        { stepNumber: 4, description: "Compute \\( c_2 \\).", workingLatex: "c_2 = a_0 b_2 + a_1 b_1 + a_2 b_0 = \\tfrac12 + (1)(-1) + \\tfrac12(1) = \\frac{1}{2} - 1 + \\frac{1}{2} = 0.", explanation: "Three terms summing to zero: \\( 1/2 \\), \\( (1)(-1) \\), and \\( (1/2)(1) \\)." },
        { stepNumber: 5, description: "Compute \\( c_3 \\).", workingLatex: "c_3 = a_0 b_3 + a_1 b_2 + a_2 b_1 + a_3 b_0 = -\\frac{1}{6} + \\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6} = 0.", explanation: "All four contributions cancel in pairs." },
        { stepNumber: 6, description: "Give the general argument for consistency.", workingLatex: "c_n = \\sum_{k=0}^{n} \\frac{1}{(n-k)!}\\cdot\\frac{(-1)^k}{k!} = \\frac{1}{n!}\\sum_{k=0}^{n}\\binom{n}{k}(-1)^k = \\frac{(1-1)^n}{n!}.", explanation: "Multiplying numerator and denominator by \\( n! \\) turns each term into \\( \\binom{n}{k}(-1)^k \\); the sum is the binomial expansion of \\( (1-1)^n \\)." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "c_n = \\frac{0^n}{n!} = \\begin{cases}1 & n=0\\\\ 0 & n\\ge 1\\end{cases}", explanation: "\\( (1-1)^n = 0^n \\), which is 1 only at \\( n=0 \\). So \\( fg \\sim 1 \\), exactly as \\( e^{1/z}e^{-1/z} = 1 \\) requires." },
      ],
      finalAnswer: "\\( c_0 = 1,\\ c_1=c_2=c_3=0 \\); in general \\( c_n = 0^n/n! \\), so \\( fg \\sim 1 \\).",
    },
  },
  {
    id: "am1b-022",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(z) = \\sqrt{1 + 1/z} \\), which as \\( z \\to \\infty \\) has the binomial expansion \\( h(z) \\sim 1 + \\dfrac{1}{2z} - \\dfrac{1}{8z^2} + \\dfrac{1}{16z^3} - \\cdots \\). Using the Cauchy product, compute the coefficients of \\( h(z)^2 \\) up to \\( z^{-3} \\) and confirm they reproduce \\( 1 + 1/z \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "binomial series", "consistency check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( h \\).", workingLatex: "a_0=1,\\ a_1=\\frac{1}{2},\\ a_2=-\\frac{1}{8},\\ a_3=\\frac{1}{16}.", explanation: "These are the binomial coefficients \\( \\binom{1/2}{n} \\) of \\( (1+w)^{1/2} \\) with \\( w = 1/z \\). Squaring should return \\( (1+w)^1 = 1 + 1/z \\)." },
        { stepNumber: 2, description: "State the square formula.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} a_k.", explanation: "Squaring is the Cauchy product of the sequence with itself. Off-diagonal index pairs \\( (j, n-j) \\) and \\( (n-j, j) \\) give equal products, so they appear with a factor 2; a central diagonal term (when \\( n \\) is even) appears once." },
        { stepNumber: 3, description: "Coefficient of \\( z^{0} \\).", workingLatex: "c_0 = a_0^2 = 1^2 = 1.", explanation: "At \\( n=0 \\) the only term is \\( a_0^2 \\)." },
        { stepNumber: 4, description: "Coefficient of \\( z^{-1} \\).", workingLatex: "c_1 = 2 a_0 a_1 = 2\\cdot 1 \\cdot \\frac{1}{2} = 1.", explanation: "The two pairs \\( (0,1) \\) and \\( (1,0) \\) give the same product \\( a_0 a_1 \\), hence the factor 2." },
        { stepNumber: 5, description: "Coefficient of \\( z^{-2} \\).", workingLatex: "c_2 = 2 a_0 a_2 + a_1^2 = 2\\left(-\\frac{1}{8}\\right) + \\frac{1}{4} = -\\frac{1}{4} + \\frac{1}{4} = 0.", explanation: "The off-diagonal pair \\( (0,2) \\) appears twice; the diagonal \\( (1,1) \\) once. They cancel, as they must for the \\( z^{-2} \\) term to vanish." },
        { stepNumber: 6, description: "Coefficient of \\( z^{-3} \\).", workingLatex: "c_3 = 2 a_0 a_3 + 2 a_1 a_2 = 2\\cdot\\frac{1}{16} + 2\\cdot\\frac{1}{2}\\cdot\\left(-\\frac{1}{8}\\right) = \\frac{1}{8} - \\frac{1}{8} = 0.", explanation: "Both index pairs \\( (0,3) \\) and \\( (1,2) \\) appear twice (no diagonal at odd \\( n \\)). The two doubled products cancel." },
        { stepNumber: 7, description: "Assemble \\( h^2 \\).", workingLatex: "h(z)^2 \\sim 1 + \\frac{1}{z} + 0\\cdot z^{-2} + 0\\cdot z^{-3} = 1 + \\frac{1}{z}.", explanation: "Squaring the series for \\( \\sqrt{1+1/z} \\) returns \\( 1 + 1/z \\), as it must — a clean self-consistency check on the binomial coefficients." },
      ],
      finalAnswer: "\\( h^2 \\sim 1 + \\frac{1}{z} \\) (coefficients \\(1,1,0,0\\)).",
    },
  },
  {
    id: "am1b-023",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} \\) (the series of \\( e^{1/z} \\)). Using the reciprocal recurrence, find the coefficients of \\( 1/f \\) up to \\( z^{-3} \\); then, separately, obtain the same coefficients via the Cauchy-product identity and confirm they agree.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "exponential", "cross-method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_0=1,\\ a_1=1,\\ a_2=\\frac{1}{2},\\ a_3=\\frac{1}{6}.", explanation: "These are \\( 1/n! \\), the coefficients of \\( e^{1/z} \\). With \\( a_0 = 1 \\), the recurrence simplifies to \\( d_n = -\\sum_{k=1}^{n} a_k d_{n-k} \\)." },
        { stepNumber: 2, description: "Reciprocal recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -(1)(1) = -1.", explanation: "At \\( n=1 \\) the only term is \\( -a_1 d_0 = -a_1 \\)." },
        { stepNumber: 3, description: "Reciprocal recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -\\left((1)(-1) + \\tfrac12(1)\\right) = -\\left(-1 + \\frac{1}{2}\\right) = \\frac{1}{2}.", explanation: "Substitute \\( d_1=-1 \\): the bracket is \\( -1 + 1/2 = -1/2 \\), giving \\( d_2 = 1/2 \\)." },
        { stepNumber: 4, description: "Reciprocal recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -\\left(\\frac{1}{2} - \\frac{1}{2} + \\frac{1}{6}\\right) = -\\frac{1}{6}.", explanation: "The bracket telescopes: \\( 1/2 + (1/2)(-1) + 1/6 = 1/6 \\), so \\( d_3 = -1/6 \\)." },
        { stepNumber: 5, description: "Independent route: reciprocate \\( e^{1/z} \\) directly.", workingLatex: "\\frac{1}{e^{1/z}} = e^{-1/z} \\sim \\sum_{n} \\frac{(-1)^n}{n!} z^{-n}.", explanation: "The reciprocal of \\( e^{1/z} \\) is \\( e^{-1/z} \\) by elementary properties of the exponential, giving a closed-form check on the recurrence values." },
        { stepNumber: 6, description: "Compare the two routes.", workingLatex: "\\frac{(-1)^n}{n!}\\Big|_{n=1,2,3} = -1,\\ \\frac{1}{2},\\ -\\frac{1}{6}.", explanation: "Exactly the recurrence values from Steps 2–4, so both methods agree to this order." },
        { stepNumber: 7, description: "Confirm via the defining convolution identity.", workingLatex: "\\sum_{k=0}^{3} a_{3-k} d_k = \\frac{1}{6}(1) + \\frac{1}{2}(-1) + 1\\cdot\\frac{1}{2} + 1\\cdot\\left(-\\frac{1}{6}\\right) = 0.", explanation: "Plugging the coefficients into the identity \\( \\sum a_{n-k} d_k = 0 \\) at \\( n=3 \\) returns zero, the final cross-check." },
      ],
      finalAnswer: "\\( 1/f \\sim 1 - \\frac{1}{z} + \\frac{1}{2z^2} - \\frac{1}{6z^3} = e^{-1/z} \\).",
    },
  },
  {
    id: "am1b-024",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( \\sinh(1/z) \\sim \\dfrac{1}{z} + \\dfrac{1}{6z^3} + \\dfrac{1}{120 z^5} \\) and \\( \\cosh(1/z) \\sim 1 + \\dfrac{1}{2z^2} + \\dfrac{1}{24 z^4} \\). Find the asymptotic expansion of \\( \\tanh(1/z) = \\sinh(1/z)/\\cosh(1/z) \\) up to and including \\( z^{-5} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "hyperbolic", "quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the reciprocal of \\( \\cosh(1/z) \\).", workingLatex: "a_0=1,\\ a_2=\\frac{1}{2},\\ a_4=\\frac{1}{24}\\ (\\text{odd } a=0).", explanation: "A quotient is a product with a reciprocal, so first form \\( 1/\\cosh \\). Write \\( w = 1/z \\); since cosh is even, only even coefficients appear and only even reciprocal coefficients will be nonzero." },
        { stepNumber: 2, description: "Reciprocal recurrence for sech: \\( d_2 \\).", workingLatex: "d_2 = -a_2 = -\\frac{1}{2}.", explanation: "With \\( a_0 = 1 \\), \\( d_n = -\\sum_{k\\ge 1} a_k d_{n-k} \\); at \\( n=2 \\) only \\( a_2 d_0 \\) survives, giving \\( d_2 = -a_2 \\)." },
        { stepNumber: 3, description: "Reciprocal recurrence for sech: \\( d_4 \\).", workingLatex: "d_4 = -(a_2 d_2 + a_4 d_0) = -\\left(\\tfrac12\\cdot\\left(-\\tfrac12\\right) + \\tfrac{1}{24}\\right) = -\\left(-\\frac{1}{4} + \\frac{1}{24}\\right) = \\frac{5}{24}.", explanation: "The bracket is \\( -1/4 + 1/24 = -6/24 + 1/24 = -5/24 \\), so \\( d_4 = 5/24 \\). Hence \\( 1/\\cosh \\sim 1 - \\tfrac12 w^2 + \\tfrac{5}{24} w^4 \\)." },
        { stepNumber: 4, description: "Set up the product \\( \\sinh\\cdot\\mathrm{sech} \\).", workingLatex: "\\sinh:\\ s_1=1,\\ s_3=\\frac{1}{6},\\ s_5=\\frac{1}{120}; \\qquad \\mathrm{sech}:\\ r_0=1,\\ r_2=-\\frac{1}{2},\\ r_4=\\frac{5}{24}.", explanation: "Now multiply. Only odd powers of \\( w \\) survive: sinh is odd, sech is even, so their product is odd in \\( w \\)." },
        { stepNumber: 5, description: "Coefficient of \\( w^1 \\).", workingLatex: "t_1 = s_1 r_0 = (1)(1) = 1.", explanation: "The only way to reach total power 1 is \\( s_1 r_0 \\)." },
        { stepNumber: 6, description: "Coefficient of \\( w^3 \\).", workingLatex: "t_3 = s_1 r_2 + s_3 r_0 = (1)\\left(-\\tfrac12\\right) + \\tfrac16(1) = -\\frac{1}{2} + \\frac{1}{6} = -\\frac{1}{3}.", explanation: "Pairs summing to power 3: \\( (1,2) \\) and \\( (3,0) \\). Combine over denominator 6: \\( -3/6 + 1/6 = -2/6 = -1/3 \\)." },
        { stepNumber: 7, description: "Coefficient of \\( w^5 \\).", workingLatex: "t_5 = s_1 r_4 + s_3 r_2 + s_5 r_0 = \\frac{5}{24} - \\frac{1}{12} + \\frac{1}{120} = \\frac{25 - 10 + 1}{120} = \\frac{16}{120} = \\frac{2}{15}.", explanation: "Pairs \\( (1,4),(3,2),(5,0) \\), where \\( s_3 r_2 = (1/6)(-1/2) = -1/12 \\). Over denominator 120: \\( 25 - 10 + 1 = 16 \\), so \\( 16/120 = 2/15 \\)." },
        { stepNumber: 8, description: "Assemble in \\( z \\).", workingLatex: "\\tanh(1/z) \\sim \\frac{1}{z} - \\frac{1}{3z^3} + \\frac{2}{15 z^5}.", explanation: "Replace \\( w \\) by \\( 1/z \\). The coefficients \\( 1, -1/3, 2/15 \\) are the standard tanh Maclaurin coefficients, confirming the quotient." },
      ],
      finalAnswer: "\\( \\tanh(1/z) \\sim \\frac{1}{z} - \\frac{1}{3z^3} + \\frac{2}{15z^5} \\).",
    },
  },
  {
    id: "am1b-025",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f(z) \\sim \\sum a_n z^{-n} \\) with \\( a_0 \\neq 0 \\), and let \\( \\{d_n\\} \\) be its reciprocal coefficients (\\( d_0 = 1,\\ \\sum_{k=0}^{n} d_{n-k} a_k = 0 \\)). Show that the leading reciprocal coefficients are \\( d_1 = -a_1/a_0 \\) and \\( d_2 = (a_1^2 - a_0 a_2)/a_0^2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "general coefficients"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the recurrence at \\( n=1 \\).", workingLatex: "\\sum_{k=0}^{1} d_{1-k} a_k = d_1 a_0 + d_0 a_1 = 0.", explanation: "The convolution at \\( n=1 \\) has only the two terms \\( k=0 \\) and \\( k=1 \\). This is the symbolic analogue of the numeric reciprocal questions earlier." },
        { stepNumber: 2, description: "Solve for \\( d_1 \\).", workingLatex: "d_1 = -\\frac{d_0 a_1}{a_0} = -\\frac{a_1}{a_0}.", explanation: "Divide by \\( a_0 \\neq 0 \\) and use \\( d_0 = 1 \\). This is the general leading reciprocal coefficient." },
        { stepNumber: 3, description: "Write the recurrence at \\( n=2 \\).", workingLatex: "d_2 a_0 + d_1 a_1 + d_0 a_2 = 0.", explanation: "Now three terms, \\( k=0,1,2 \\). Solve for the unknown \\( d_2 \\), which sits in the \\( k=0 \\) term." },
        { stepNumber: 4, description: "Isolate \\( d_2 a_0 \\) and substitute \\( d_1 \\).", workingLatex: "d_2 a_0 = -d_1 a_1 - d_0 a_2 = -\\left(-\\frac{a_1}{a_0}\\right)a_1 - a_2 = \\frac{a_1^2}{a_0} - a_2.", explanation: "Insert \\( d_1 = -a_1/a_0 \\) and \\( d_0 = 1 \\); the term \\( -d_1 a_1 = a_1^2/a_0 \\). Carrying the double negative correctly is the crux." },
        { stepNumber: 5, description: "Solve for \\( d_2 \\) over a common denominator.", workingLatex: "d_2 = \\frac{1}{a_0}\\left(\\frac{a_1^2}{a_0} - a_2\\right) = \\frac{a_1^2}{a_0^2} - \\frac{a_2}{a_0} = \\frac{a_1^2 - a_0 a_2}{a_0^2}.", explanation: "Divide through by \\( a_0 \\) and combine over the common denominator \\( a_0^2 \\). This general formula specialises to all the numeric \\( d_2 \\) values computed in earlier questions." },
      ],
      finalAnswer: "\\( d_1 = -\\frac{a_1}{a_0},\\quad d_2 = \\frac{a_1^2 - a_0 a_2}{a_0^2} \\).",
    },
  },
  {
    id: "am1b-026",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{z^2} + \\cdots \\) (all \\( a_n = 1 \\)) and \\( g(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\cdots \\) (all \\( b_n = n+1 \\)). (a) Find the Cauchy product \\( c_n \\) in closed form. (b) Identify the closed-form function \\( fg \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy product", "closed form", "geometric series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the Cauchy coefficient.", workingLatex: "c_n = \\sum_{k=0}^{n} a_{n-k} b_k = \\sum_{k=0}^{n} 1\\cdot(k+1) = \\sum_{k=0}^{n}(k+1).", explanation: "Since \\( a_{n-k} = 1 \\) for every index, the convolution collapses to a plain sum of the \\( b_k = k+1 \\)." },
        { stepNumber: 2, description: "Re-index the sum to a standard form.", workingLatex: "c_n = \\sum_{k=0}^{n}(k+1) = \\sum_{j=1}^{n+1} j.", explanation: "Substituting \\( j = k+1 \\) shifts the range to \\( j = 1, \\dots, n+1 \\), turning the sum into the first \\( n+1 \\) positive integers." },
        { stepNumber: 3, description: "Apply the arithmetic-series formula.", workingLatex: "c_n = \\frac{(n+1)(n+2)}{2} = \\binom{n+2}{2}.", explanation: "The sum \\( 1 + 2 + \\cdots + (n+1) \\) is \\( \\tfrac12 (n+1)(n+2) \\), which equals the binomial \\( \\binom{n+2}{2} \\) — the triangular numbers." },
        { stepNumber: 4, description: "Identify \\( f \\) and \\( g \\) as geometric forms.", workingLatex: "f \\sim \\frac{1}{1 - 1/z}, \\qquad g \\sim \\frac{1}{(1 - 1/z)^2}.", explanation: "\\( \\sum w^n = (1-w)^{-1} \\) and \\( \\sum (n+1)w^n = (1-w)^{-2} \\), both with \\( w = 1/z \\). Recognising the generating functions gives an independent route." },
        { stepNumber: 5, description: "Multiply and read off the coefficients.", workingLatex: "fg \\sim \\frac{1}{(1-1/z)^3} = \\sum_{n=0}^{\\infty}\\binom{n+2}{2} z^{-n}.", explanation: "The product \\( (1-w)^{-1}(1-w)^{-2} = (1-w)^{-3} \\), whose coefficients are \\( \\binom{n+2}{2} \\) — confirming part (a) independently." },
      ],
      finalAnswer: "\\( c_n = \\binom{n+2}{2} = \\frac{(n+1)(n+2)}{2} \\); \\( fg \\sim (1-1/z)^{-3} \\).",
    },
  },
  {
    id: "am1b-027",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( f(z) \\sim 1 + \\dfrac{1}{z} + \\dfrac{1}{2z^2} + \\dfrac{1}{6z^3} \\) (series of \\( e^{1/z} \\)). Using the reciprocal recurrence, find the coefficients of \\( 1/f^2 \\) up to \\( z^{-3} \\) (i.e. expand \\( e^{-2/z} \\)) by first squaring \\( f \\) via the Cauchy product and then reciprocating.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "exponential", "composition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients of \\( f \\).", workingLatex: "a_n = \\frac{1}{n!}:\\ 1,1,\\tfrac12,\\tfrac16.", explanation: "\\( f = e^{1/z} \\), so \\( f^2 = e^{2/z} \\); squaring should give coefficients \\( 2^n/n! \\), and reciprocating then gives \\( e^{-2/z} \\). Keep both targets in mind." },
        { stepNumber: 2, description: "Square \\( f \\): the diagonal coefficients \\( e_0, e_1 \\).", workingLatex: "e_0 = a_0^2 = 1, \\qquad e_1 = 2 a_0 a_1 = 2\\cdot 1\\cdot 1 = 2.", explanation: "Use the square formula \\( e_n = \\sum_k a_{n-k} a_k \\). At \\( n=1 \\) the doubled off-diagonal pair gives \\( 2 a_0 a_1 \\)." },
        { stepNumber: 3, description: "Square \\( f \\): coefficient \\( e_2 \\).", workingLatex: "e_2 = 2 a_0 a_2 + a_1^2 = 2\\cdot\\frac{1}{2} + 1 = 1 + 1 = 2.", explanation: "The off-diagonal \\( (0,2) \\) appears twice, the diagonal \\( (1,1) \\) once. The total is 2." },
        { stepNumber: 4, description: "Square \\( f \\): coefficient \\( e_3 \\).", workingLatex: "e_3 = 2 a_0 a_3 + 2 a_1 a_2 = 2\\cdot\\frac{1}{6} + 2\\cdot 1\\cdot\\frac{1}{2} = \\frac{1}{3} + 1 = \\frac{4}{3}.", explanation: "Both odd-\\( n \\) pairs \\( (0,3),(1,2) \\) are doubled. The values \\( 1, 2, 2, 4/3 \\) equal \\( 2^n/n! \\), confirming \\( f^2 = e^{2/z} \\)." },
        { stepNumber: 5, description: "Reciprocate \\( f^2 \\): recurrence at \\( n=1 \\).", workingLatex: "d_1 = -e_1 = -2.", explanation: "Here \\( e_0 = 1 \\), so the reciprocal recurrence is \\( d_n = -\\sum_{k=1}^{n} e_k d_{n-k} \\); at \\( n=1 \\) this is \\( -e_1 \\)." },
        { stepNumber: 6, description: "Recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(e_1 d_1 + e_2 d_0) = -((2)(-2) + 2) = -(-4 + 2) = 2.", explanation: "Substitute \\( d_1=-2 \\): the bracket is \\( -4 + 2 = -2 \\), so \\( d_2 = 2 \\)." },
        { stepNumber: 7, description: "Recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(e_1 d_2 + e_2 d_1 + e_3 d_0) = -\\left((2)(2) + (2)(-2) + \\frac{4}{3}\\right) = -\\frac{4}{3}.", explanation: "The bracket is \\( 4 - 4 + 4/3 = 4/3 \\), so \\( d_3 = -4/3 \\)." },
        { stepNumber: 8, description: "Assemble and identify.", workingLatex: "\\frac{1}{f^2} \\sim 1 - \\frac{2}{z} + \\frac{2}{z^2} - \\frac{4}{3z^3} = e^{-2/z}.", explanation: "The coefficients are \\( (-2)^n/n! \\): \\( 1, -2, 2, -4/3 \\) — exactly the series of \\( e^{-2/z} \\), as expected." },
      ],
      finalAnswer: "\\( 1/f^2 \\sim 1 - \\frac{2}{z} + \\frac{2}{z^2} - \\frac{4}{3z^3} = e^{-2/z} \\).",
    },
  },
  {
    id: "am1b-028",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), the function \\( \\coth(z) = \\cosh z/\\sinh z \\) satisfies \\( \\coth z = 1 + 2e^{-2z} + 2e^{-4z} + \\cdots \\). Writing \\( u = e^{-2z} \\) (an exponentially small gauge as \\( z \\to \\infty \\)), find the reciprocal expansion of \\( \\coth z \\) (i.e. \\( \\tanh z \\)) as a series in \\( u \\) up to \\( u^3 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "exponentially small terms"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Express \\( \\coth \\) in the gauge \\( u \\).", workingLatex: "\\coth z = \\frac{1+u}{1-u} = 1 + 2u + 2u^2 + 2u^3 + \\cdots, \\qquad u = e^{-2z}.", explanation: "Using \\( \\coth z = (e^{z}+e^{-z})/(e^{z}-e^{-z}) = (1+u)/(1-u) = 1 + 2\\sum_{n\\ge 1} u^n \\). Here the small parameter is the exponentially small \\( u = e^{-2z} \\), not a power of \\( 1/z \\) — but the algebra is identical." },
        { stepNumber: 2, description: "List the coefficients \\( a_n \\).", workingLatex: "a_0 = 1,\\ a_1 = 2,\\ a_2 = 2,\\ a_3 = 2.", explanation: "Read directly off the series in \\( u \\). Since \\( a_0 = 1 \\), the reciprocal coefficients come straight from the recurrence with no prefactor." },
        { stepNumber: 3, description: "Reciprocal recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -(2)(1) = -2.", explanation: "With \\( a_0=1 \\), \\( d_n = -\\sum_{k=1}^{n} a_k d_{n-k} \\); at \\( n=1 \\) this is \\( -a_1 \\)." },
        { stepNumber: 4, description: "Recurrence at \\( n=2 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -((2)(-2) + (2)(1)) = -(-4 + 2) = 2.", explanation: "Substitute \\( d_1=-2 \\): bracket \\( -4 + 2 = -2 \\), so \\( d_2 = 2 \\)." },
        { stepNumber: 5, description: "Recurrence at \\( n=3 \\).", workingLatex: "d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -((2)(2) + (2)(-2) + (2)(1)) = -(4 - 4 + 2) = -2.", explanation: "The bracket is \\( 4 - 4 + 2 = 2 \\), so \\( d_3 = -2 \\)." },
        { stepNumber: 6, description: "Assemble and identify.", workingLatex: "\\tanh z = \\frac{1}{\\coth z} \\sim 1 - 2u + 2u^2 - 2u^3 + \\cdots = \\frac{1-u}{1+u}.", explanation: "The coefficients alternate in sign, consistent with \\( \\tanh z = (1-u)/(1+u) \\) — exactly the reciprocal of \\( (1+u)/(1-u) \\), confirming the result." },
      ],
      finalAnswer: "\\( \\tanh z \\sim 1 - 2u + 2u^2 - 2u^3 + \\cdots \\) with \\( u = e^{-2z} \\).",
    },
  },
  {
    id: "am1b-029",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f(z) \\sim 1 + \\dfrac{2}{z} + \\dfrac{3}{z^2} + \\dfrac{4}{z^3} + \\cdots \\) (so \\( a_n = n+1 \\)) as \\( z \\to \\infty \\). Find the reciprocal coefficients \\( d_n \\) for all \\( n \\), and hence find the coefficients of \\( 1/f^2 \\) up to \\( z^{-3} \\) using the Cauchy product.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "Cauchy product", "closed form", "synoptic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise \\( f \\) as a closed form.", workingLatex: "f \\sim \\sum_{n\\ge 0}(n+1)z^{-n} = \\frac{1}{(1-1/z)^2}.", explanation: "Standard generating function \\( \\sum(n+1)w^n = (1-w)^{-2} \\) with \\( w=1/z \\). This tells us in advance that \\( 1/f = (1-1/z)^2 \\) terminates." },
        { stepNumber: 2, description: "Reciprocal recurrence at \\( n=1 \\).", workingLatex: "d_1 = -a_1 d_0 = -2.", explanation: "With \\( a_0=1 \\), \\( d_1 = -a_1 = -2 \\)." },
        { stepNumber: 3, description: "Reciprocal recurrence at \\( n=2,3 \\).", workingLatex: "d_2 = -(a_1 d_1 + a_2 d_0) = -(-4 + 3) = 1, \\quad d_3 = -(a_1 d_2 + a_2 d_1 + a_3 d_0) = -(2 - 6 + 4) = 0.", explanation: "Substitute as we go: \\( d_2 = -((2)(-2)+3) = 1 \\), then \\( d_3 = -((2)(1)+(3)(-2)+4) = 0 \\). So \\( d_0=1, d_1=-2, d_2=1 \\), and \\( d_n = 0 \\) for \\( n\\ge 3 \\)." },
        { stepNumber: 4, description: "Write \\( 1/f \\) explicitly.", workingLatex: "\\frac{1}{f} \\sim 1 - \\frac{2}{z} + \\frac{1}{z^2} = \\left(1-\\frac{1}{z}\\right)^2.", explanation: "A terminating series equal to \\( (1-1/z)^2 \\), as predicted in Step 1." },
        { stepNumber: 5, description: "Prepare to square \\( 1/f \\): list its coefficients.", workingLatex: "r_0=1,\\ r_1=-2,\\ r_2=1,\\ r_3=0.", explanation: "We want \\( (1/f)^2 = 1/f^2 = (1-1/z)^4 \\); square the finite sequence \\( r \\) via the Cauchy product." },
        { stepNumber: 6, description: "Cauchy product for the square.", workingLatex: "p_0 = r_0^2 = 1,\\ p_1 = 2r_0 r_1 = -4,\\ p_2 = 2r_0 r_2 + r_1^2 = 2 + 4 = 6,\\ p_3 = 2r_0 r_3 + 2r_1 r_2 = 0 - 4 = -4.", explanation: "Use the square formula with doubled off-diagonal pairs. These are the binomial coefficients of \\( (1-1/z)^4 \\): \\( 1,-4,6,-4(,1) \\)." },
        { stepNumber: 7, description: "Assemble and identify.", workingLatex: "\\frac{1}{f^2} \\sim 1 - \\frac{4}{z} + \\frac{6}{z^2} - \\frac{4}{z^3} + \\cdots = (1-1/z)^4.", explanation: "Confirmed: \\( 1/f^2 = [(1-1/z)^2]^2 = (1-1/z)^4 \\), whose coefficients are the fourth-row binomials \\( 1,-4,6,-4,1 \\)." },
      ],
      finalAnswer: "\\( d_0=1,\\ d_1=-2,\\ d_2=1 \\) (else 0); \\( 1/f^2 \\sim 1 - \\frac{4}{z} + \\frac{6}{z^2} - \\frac{4}{z^3} = (1-1/z)^4 \\).",
    },
  },
  {
    id: "am1b-030",
    topicRef: "am1b",
    topicTitle: "Algebra of asymptotic expansions: products & reciprocals 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "As \\( z \\to \\infty \\), \\( \\dfrac{\\sin(1/z)}{1/z} \\sim 1 - \\dfrac{1}{6z^2} + \\dfrac{1}{120 z^4} \\). Find the asymptotic expansion of its reciprocal \\( \\dfrac{1/z}{\\sin(1/z)} \\) up to and including \\( z^{-4} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["reciprocal", "recurrence", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List the coefficients in \\( w = 1/z \\).", workingLatex: "a_0 = 1,\\ a_2 = -\\frac{1}{6},\\ a_4 = \\frac{1}{120} \\quad (\\text{odd } a = 0).", explanation: "Index by powers of \\( w = 1/z \\). The function is even in \\( w \\), so odd coefficients vanish and the odd reciprocal coefficients vanish too." },
        { stepNumber: 2, description: "Specialise the recurrence to \\( a_0 = 1 \\).", workingLatex: "d_n = -\\sum_{k\\ge 1} a_k\\, d_{n-k}, \\quad \\text{only even } k \\text{ contribute}.", explanation: "With \\( a_0 = 1 \\) there is no division, and only even-index \\( a_k \\) are nonzero, so the convolution keeps only even terms." },
        { stepNumber: 3, description: "Reciprocal recurrence at \\( n=2 \\).", workingLatex: "d_2 = -a_2 d_0 = -\\left(-\\frac{1}{6}\\right) = \\frac{1}{6}.", explanation: "At \\( n=2 \\) the single surviving term is \\( -a_2 d_0 \\), giving \\( d_2 = 1/6 \\)." },
        { stepNumber: 4, description: "Form the numerator for \\( d_4 \\).", workingLatex: "a_2 d_2 + a_4 d_0 = \\left(-\\frac{1}{6}\\right)\\frac{1}{6} + \\frac{1}{120} = -\\frac{1}{36} + \\frac{1}{120}.", explanation: "Surviving terms are \\( a_2 d_2 \\) and \\( a_4 d_0 \\); substitute \\( d_2 = 1/6 \\)." },
        { stepNumber: 5, description: "Combine over a common denominator.", workingLatex: "-\\frac{1}{36} + \\frac{1}{120} = -\\frac{10}{360} + \\frac{3}{360} = -\\frac{7}{360}.", explanation: "Use the common denominator 360: \\( 1/36 = 10/360 \\) and \\( 1/120 = 3/360 \\), so the numerator is \\( -7/360 \\)." },
        { stepNumber: 6, description: "Solve for \\( d_4 \\).", workingLatex: "d_4 = -\\left(-\\frac{7}{360}\\right) = \\frac{7}{360}.", explanation: "Negating the numerator (since \\( a_0 = 1 \\)) gives \\( d_4 = 7/360 \\)." },
        { stepNumber: 7, description: "Assemble in \\( z \\).", workingLatex: "\\frac{1/z}{\\sin(1/z)} \\sim 1 + \\frac{1}{6z^2} + \\frac{7}{360 z^4}.", explanation: "These are the standard coefficients of \\( x/\\sin x = 1 + x^2/6 + 7x^4/360 \\), with \\( x = 1/z \\) — confirming the reciprocal." },
      ],
      finalAnswer: "\\( \\dfrac{1/z}{\\sin(1/z)} \\sim 1 + \\frac{1}{6z^2} + \\frac{7}{360 z^4} \\).",
    },
  },
];
