import { Question } from "@/lib/types";

/**
 * Asymptotic Methods (Cambridge Part II) — Asymptotic Sequences & Series
 * Subtopic am1d: Differentiation & integration of asymptotic series.
 *
 * Scope: integrating an o(φ) estimate; when term-by-term differentiation of an
 * asymptotic series is valid (and when it fails); the F' = G consistency result
 * for the Stieltjes family; classic counterexamples (oscillatory remainders).
 *
 * Seeded from DAMTP Asymptotic Methods Example Sheet 1, Q8 (integrating o(φ)),
 * Q9(b) (term-by-term differentiation, the counterexample, and the
 * βₙ = (n+1)αₙ₊₁ theorem) and Q10 (E₁ by parts / differentiate-and-integrate),
 * with constants, limits and framing varied throughout.
 *
 * Numerically sanity-checked with mpmath where a value/series is checkable:
 *  - G(0.1) = ∫₀^∞ e^{-t}/(1+0.1 t)² dt = 0.84366660602… (matches sheet);
 *  - the Stieltjes series F ∼ Σ(−1)ⁿ n! xⁿ and G ∼ Σ(−1)ⁿ (n+1)! xⁿ;
 *  - F′ = G to 25+ digits (central difference vs direct quadrature);
 *  - E₁(x) ∼ e^{-x}(1/x − 1/x² + 2/x³ − …) at x = 5, 10;
 *  - the counterexample H = e^{-1/x} sin(e^{1/x}) decays faster than every power
 *    (so all αₙ = 0) while H′ carries an unbounded oscillatory term.
 */
export const questions: Question[] = [
  // ─────────────────────────────────────── FOUNDATION (6) ───────────────────────────────────────
  {
    id: "am1d-001",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Suppose \\( f(x) = o(1) \\) as \\( x \\to \\infty \\). Integrate this estimate to give the sharpest bound you can on \\( \\displaystyle \\int_a^x f(t)\\,dt \\) of the form \\( o(g(x)) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integrating o(phi)", "little-o", "order notation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Unpack the hypothesis.", workingLatex: "f(x) = o(1) \\iff \\forall \\varepsilon>0 \\ \\exists X: \\ |f(t)| < \\varepsilon \\ \\text{ for } t > X.", explanation: "Here \\(\\varphi \\equiv 1\\), so \\(f(x)=o(\\varphi)\\) means \\(f(x)/1 \\to 0\\): eventually \\(f\\) is smaller than any fixed positive constant." },
        { stepNumber: 2, description: "Bound the tail of the integral.", workingLatex: "\\left| \\int_X^x f(t)\\,dt \\right| \\le \\int_X^x |f(t)|\\,dt < \\varepsilon (x - X) < \\varepsilon\\, x.", explanation: "Split off the fixed head \\(\\int_a^X f\\,dt\\), a constant, and bound the tail using \\(|f|<\\varepsilon\\)." },
        { stepNumber: 3, description: "Absorb the constant head.", workingLatex: "\\left| \\int_a^x f(t)\\,dt \\right| \\le C + \\varepsilon\\, x, \\qquad C = \\left|\\int_a^X f\\,dt\\right|.", explanation: "For \\(x\\) large the constant \\(C\\) is itself \\(<\\varepsilon x\\), so the whole integral is \\(<2\\varepsilon x\\)." },
        { stepNumber: 4, description: "Read off the order.", workingLatex: "\\int_a^x f(t)\\,dt = o(x) \\qquad (x \\to \\infty).", explanation: "Since \\(\\varepsilon\\) was arbitrary, the integral is \\(o(x)\\). This is the \\(\\varphi\\equiv 1\\) case of the general rule \\(\\int_a^x o(\\varphi)\\,dt = o(x\\varphi)\\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_a^x f(t)\\,dt = o(x) \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "o(x)",
    },
  },
  {
    id: "am1d-002",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given that the integrable function \\( f \\) satisfies \\( f(t) = o(t^{2}) \\) as \\( t \\to \\infty \\), find the sharpest bound of the form \\( o(g(x)) \\) on \\( \\displaystyle\\int_1^x f(t)\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integrating o(phi)", "little-o", "power gauge"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the estimate.", workingLatex: "f(t) = o(t^2) \\iff \\forall \\varepsilon>0 \\ \\exists X: \\ |f(t)| < \\varepsilon\\, t^2 \\ (t>X).", explanation: "The gauge function is \\(\\varphi(t)=t^2\\), positive and increasing for \\(t>0\\)." },
        { stepNumber: 2, description: "Integrate the bound on the tail.", workingLatex: "\\left|\\int_X^x f(t)\\,dt\\right| \\le \\varepsilon \\int_X^x t^2\\,dt = \\varepsilon\\,\\frac{x^3 - X^3}{3} < \\frac{\\varepsilon}{3}\\,x^3.", explanation: "Because \\(\\varphi\\) is increasing, \\(\\int_X^x t^2\\,dt \\le \\tfrac13 x^3\\); the cubic comes from integrating \\(t^2\\)." },
        { stepNumber: 3, description: "Add the constant head.", workingLatex: "\\left|\\int_1^x f\\,dt\\right| \\le C + \\frac{\\varepsilon}{3}x^3 < \\varepsilon\\, x^3 \\ \\text{ for } x \\text{ large}.", explanation: "The fixed contribution \\(C=\\big|\\int_1^X f\\,dt\\big|\\) is eventually swamped by the cubic." },
        { stepNumber: 4, description: "Read off the order.", workingLatex: "\\int_1^x f(t)\\,dt = o(x^3).", explanation: "This matches the general theorem \\(\\int^x o(\\varphi) = o(x\\varphi)\\) with \\(\\varphi=t^2\\): \\(x\\cdot x^2 = x^3\\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_1^x f(t)\\,dt = o(x^3) \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "o(x^3)",
    },
  },
  {
    id: "am1d-003",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "An asymptotic power series as \\( x \\to 0^{+} \\) is \\( H(x) \\sim 3 + 2x + 5x^{2} + 7x^{3} + \\cdots \\) with \\( H'(x) \\) continuous up to \\( x=0 \\) and itself possessing an asymptotic power series. Write down the term-by-term differentiated series for \\( H'(x) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["term-by-term differentiation", "asymptotic power series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the theorem.", workingLatex: "H \\sim \\sum_{n\\ge 0}\\alpha_n x^n,\\ H' \\text{ admissible} \\implies H' \\sim \\sum_{n\\ge 0}\\beta_n x^n,\\ \\ \\beta_n = (n+1)\\alpha_{n+1}.", explanation: "When \\(H'\\) is continuous on \\([0,\\infty)\\) and has its own asymptotic series, that series must be the formal derivative of \\(H\\)'s." },
        { stepNumber: 2, description: "Identify the coefficients.", workingLatex: "\\alpha_0=3,\\ \\alpha_1=2,\\ \\alpha_2=5,\\ \\alpha_3=7.", explanation: "Read them straight off the given series." },
        { stepNumber: 3, description: "Apply \\( \\beta_n=(n+1)\\alpha_{n+1} \\).", workingLatex: "\\beta_0 = 1\\cdot 2 = 2,\\quad \\beta_1 = 2\\cdot 5 = 10,\\quad \\beta_2 = 3\\cdot 7 = 21.", explanation: "Differentiating \\(x^{n}\\) gives \\(n x^{n-1}\\); re-indexed this is the stated formula." },
        { stepNumber: 4, description: "Assemble the series.", workingLatex: "H'(x) \\sim 2 + 10x + 21x^2 + \\cdots \\qquad (x\\to 0^+).", explanation: "Exactly the term-by-term derivative of the given expansion." },
      ],
      finalAnswer: "\\( H'(x) \\sim 2 + 10x + 21x^{2} + \\cdots \\)",
      canonicalAnswer: "2 + 10*x + 21*x^2",
    },
  },
  {
    id: "am1d-004",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Integrate the asymptotic series \\( g(t) \\sim 1 - t + t^{2} - t^{3} + \\cdots \\) (valid as \\( t \\to 0^{+} \\)) term by term to obtain the leading three non-zero terms of an asymptotic series for \\( \\displaystyle F(x)=\\int_0^x g(t)\\,dt \\) as \\( x \\to 0^{+} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integrating asymptotic series", "term-by-term integration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note integration is the safe direction.", workingLatex: "g(t) = \\sum_{n\\ge 0}(-1)^n t^n + o(t^N) \\ \\text{ uniformly for small } t.", explanation: "Unlike differentiation, term-by-term integration of an asymptotic power series is always valid: the \\(o(t^N)\\) remainder integrates to \\(o(x^{N+1})\\)." },
        { stepNumber: 2, description: "Integrate each retained term.", workingLatex: "\\int_0^x 1\\,dt = x,\\quad \\int_0^x(-t)\\,dt = -\\frac{x^2}{2},\\quad \\int_0^x t^2\\,dt = \\frac{x^3}{3}.", explanation: "Power-rule integration of the first three terms." },
        { stepNumber: 3, description: "Handle the remainder.", workingLatex: "\\int_0^x o(t^2)\\,dt = o(x^3).", explanation: "Integrating an \\(o(t^2)\\) estimate over \\([0,x]\\) gives \\(o(x^3)\\), one order better — so the truncated series is genuinely asymptotic." },
        { stepNumber: 4, description: "Collect the series.", workingLatex: "F(x) \\sim x - \\frac{x^2}{2} + \\frac{x^3}{3} - \\cdots \\qquad (x\\to 0^+).", explanation: "This is the expansion of \\(\\ln(1+x)\\), the antiderivative of \\(1/(1+t)\\)." },
      ],
      finalAnswer: "\\( F(x) \\sim x - \\dfrac{x^{2}}{2} + \\dfrac{x^{3}}{3} - \\cdots \\)",
      canonicalAnswer: "x - x^2/2 + x^3/3",
    },
  },
  {
    id: "am1d-005",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The function \\( G(x) \\) has the asymptotic series \\( G(x) \\sim a_0 + a_1 x + a_2 x^{2} + \\cdots \\) as \\( x \\to 0^{+} \\), and it is known that \\( G = F' \\) for some \\( F \\) with \\( F(0)=0 \\). Assuming term-by-term integration is valid, write the leading three terms of the series for \\( F \\) in terms of the \\( a_n \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integrating asymptotic series", "antiderivative"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the antiderivative.", workingLatex: "F(x) = \\int_0^x G(t)\\,dt, \\qquad F(0)=0.", explanation: "The condition \\(F(0)=0\\) fixes the constant of integration." },
        { stepNumber: 2, description: "Integrate term by term.", workingLatex: "\\int_0^x a_n t^n\\,dt = \\frac{a_n}{n+1}\\,x^{n+1}.", explanation: "Each monomial integrates by the power rule; the remainder \\(o(t^N)\\) becomes \\(o(x^{N+1})\\)." },
        { stepNumber: 3, description: "Sum the first three.", workingLatex: "F(x) \\sim a_0 x + \\frac{a_1}{2}x^2 + \\frac{a_2}{3}x^3 + \\cdots.", explanation: "Note the constant term of \\(F\\) is zero — there is no \\(x^0\\) term, consistent with \\(F(0)=0\\)." },
        { stepNumber: 4, description: "State the coefficient rule.", workingLatex: "[x^{n+1}]\\,F = \\frac{a_n}{n+1}.", explanation: "This is exactly the inverse of \\(\\beta_n=(n+1)\\alpha_{n+1}\\): integrating divides the \\(n\\)th coefficient by \\(n+1\\) and shifts the power up." },
      ],
      finalAnswer: "\\( F(x) \\sim a_0 x + \\dfrac{a_1}{2}x^{2} + \\dfrac{a_2}{3}x^{3} + \\cdots \\)",
      canonicalAnswer: "a0*x + a1*x^2/2 + a2*x^3/3",
    },
  },
  {
    id: "am1d-006",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Consider \\( h(x) = \\exp(-1/x) \\) for \\( x>0 \\). By comparing \\( h(x) \\) with \\( x^{N} \\), explain why \\( h \\) has the asymptotic power series \\( h(x) \\sim 0 + 0\\cdot x + 0\\cdot x^{2} + \\cdots \\) as \\( x \\to 0^{+} \\), and state the value of every coefficient.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["counterexample", "exponentially small", "asymptotic power series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio against the gauge.", workingLatex: "\\frac{h(x)}{x^{N}} = \\frac{e^{-1/x}}{x^{N}}.", explanation: "An asymptotic power series with coefficients \\(\\beta_k\\) requires \\(h(x)-\\sum_{k<N}\\beta_k x^k = o(x^{N-1})\\); we test the gauge \\(x^N\\)." },
        { stepNumber: 2, description: "Substitute \\( u=1/x \\).", workingLatex: "\\frac{e^{-1/x}}{x^{N}} = u^{N} e^{-u}, \\qquad u = \\frac1x \\to +\\infty.", explanation: "As \\(x\\to 0^+\\), \\(u\\to\\infty\\), turning the limit into a standard exponential-vs-polynomial race." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{u\\to\\infty} u^{N} e^{-u} = 0 \\quad \\text{for every } N.", explanation: "The exponential beats any power, so \\(h(x)=o(x^N)\\) for all \\(N\\): \\(h\\) is \\emph{beyond all orders}." },
        { stepNumber: 4, description: "Deduce the coefficients.", workingLatex: "\\beta_0=\\beta_1=\\beta_2=\\cdots = 0, \\qquad h(x)\\sim 0.", explanation: "Subtracting the all-zero series leaves \\(h\\) itself, which is \\(o(x^N)\\) for all \\(N\\): the zero series \\emph{is} asymptotic. Yet \\(h\\not\\equiv 0\\) — the seed of non-uniqueness." },
      ],
      finalAnswer: "All coefficients are zero: \\( h(x)\\sim 0 \\) as \\( x\\to 0^{+} \\).",
      canonicalAnswer: "0",
    },
  },

  // ─────────────────────────────────────── STANDARD (12) ───────────────────────────────────────
  {
    id: "am1d-007",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f \\) be continuous with \\( f(x)=o(\\varphi(x)) \\) as \\( x\\to\\infty \\), where \\( \\varphi \\) is continuous, positive and non-decreasing. Show that \\( \\displaystyle\\int_a^x f(t)\\,dt = o\\big(x\\,\\varphi(x)\\big) \\) as \\( x\\to+\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integrating o(phi)", "little-o", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Fix \\( \\varepsilon \\) and a threshold.", workingLatex: "\\forall \\varepsilon>0 \\ \\exists X\\ge a: \\ |f(t)| < \\varepsilon\\,\\varphi(t) \\quad (t \\ge X).", explanation: "This is the definition of \\(f=o(\\varphi)\\): the ratio \\(f/\\varphi\\) is eventually below any \\(\\varepsilon\\)." },
        { stepNumber: 2, description: "Split the integral at \\( X \\).", workingLatex: "\\int_a^x f\\,dt = \\underbrace{\\int_a^X f\\,dt}_{=:C\\ (\\text{const})} + \\int_X^x f\\,dt.", explanation: "The head over \\([a,X]\\) is a fixed finite number \\(C\\) once \\(X\\) is chosen; only the tail depends on \\(x\\)." },
        { stepNumber: 3, description: "Bound the tail with \\( \\varphi \\) increasing.", workingLatex: "\\left|\\int_X^x f\\,dt\\right| \\le \\varepsilon\\int_X^x \\varphi(t)\\,dt \\le \\varepsilon\\,(x-X)\\,\\varphi(x) < \\varepsilon\\,x\\,\\varphi(x).", explanation: "Since \\(\\varphi\\) is non-decreasing, \\(\\varphi(t)\\le\\varphi(x)\\) on \\([X,x]\\), so \\(\\int_X^x\\varphi\\le(x-X)\\varphi(x)\\)." },
        { stepNumber: 4, description: "Show the head is negligible.", workingLatex: "\\frac{|C|}{x\\,\\varphi(x)} \\to 0 \\quad (x\\to\\infty),", explanation: "\\(\\varphi>0\\) and non-decreasing means \\(x\\varphi(x)\\ge x\\varphi(X)\\to\\infty\\), so the fixed constant \\(C\\) is eventually \\(<\\varepsilon\\,x\\varphi(x)\\)." },
        { stepNumber: 5, description: "Combine the two pieces.", workingLatex: "\\left|\\int_a^x f\\,dt\\right| \\le |C| + \\varepsilon\\,x\\varphi(x) < 2\\varepsilon\\, x\\varphi(x) \\ \\text{ for } x \\text{ large}.", explanation: "Choose \\(x\\) large enough that the head clears the \\(\\varepsilon x\\varphi(x)\\) bar; add to the tail bound." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\frac{1}{x\\varphi(x)}\\left|\\int_a^x f\\,dt\\right| < 2\\varepsilon \\implies \\int_a^x f\\,dt = o(x\\varphi(x)).", explanation: "Since \\(\\varepsilon>0\\) was arbitrary, the ratio tends to \\(0\\): the result is proved." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_a^x f(t)\\,dt = o\\big(x\\,\\varphi(x)\\big) \\) as \\( x\\to+\\infty \\).",
    },
  },
  {
    id: "am1d-008",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 08",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the Stieltjes integral \\( \\displaystyle F(x)=\\int_0^{\\infty}\\frac{e^{-t}}{1+xt}\\,dt \\), it is given that \\( F(x)\\sim\\sum_{n=0}^{\\infty}(-1)^n n!\\,x^{n} \\) as \\( x\\to 0^{+} \\). By differentiating under the integral sign, find \\( F'(x) \\) as an integral and hence its asymptotic series.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiate under integral", "Stieltjes integral", "asymptotic series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the integrand in \\( x \\).", workingLatex: "\\frac{\\partial}{\\partial x}\\frac{1}{1+xt} = -\\frac{t}{(1+xt)^2}.", explanation: "Treat \\(t\\) as a parameter; the chain rule on \\((1+xt)^{-1}\\) brings down \\(-t(1+xt)^{-2}\\)." },
        { stepNumber: 2, description: "Justify and carry out the differentiation.", workingLatex: "F'(x) = -\\int_0^{\\infty}\\frac{t\\,e^{-t}}{(1+xt)^2}\\,dt.", explanation: "For \\(x>0\\) the integrand and its \\(x\\)-derivative are dominated by integrable \\(t e^{-t}\\), so Leibniz's rule applies." },
        { stepNumber: 3, description: "Differentiate the series term by term.", workingLatex: "\\frac{d}{dx}\\sum_{n\\ge 0}(-1)^n n!\\,x^n = \\sum_{n\\ge 1}(-1)^n n!\\,n\\,x^{n-1}.", explanation: "Formally differentiate; the constant term \\(n=0\\) drops out." },
        { stepNumber: 4, description: "Re-index the sum.", workingLatex: "= \\sum_{m\\ge 0}(-1)^{m+1}(m+1)!\\,(m+1)\\,x^{m}.", explanation: "Put \\(m=n-1\\); then \\(n!\\,n = (m+1)!\\,(m+1)\\) and the sign becomes \\((-1)^{m+1}\\)." },
        { stepNumber: 5, description: "Simplify the coefficient.", workingLatex: "(m+1)!\\,(m+1) = (m+1)\\cdot(m+1)! .", explanation: "Leave it factored; note this is the series for \\(-\\int t e^{-t}(1+xt)^{-2}dt\\)." },
        { stepNumber: 6, description: "State the result.", workingLatex: "F'(x) \\sim -\\sum_{m\\ge 0}(-1)^{m}(m+1)(m+1)!\\,x^{m}.", explanation: "The differentiated series is asymptotic to \\(F'\\) here because \\(F'\\) is smooth and itself Stieltjes-type — differentiation is legitimate for this family." },
      ],
      finalAnswer: "\\( \\displaystyle F'(x) = -\\int_0^{\\infty}\\frac{t\\,e^{-t}}{(1+xt)^2}\\,dt \\sim -\\sum_{m\\ge 0}(-1)^{m}(m+1)(m+1)!\\,x^{m} \\).",
      canonicalAnswer: "-Integral(t*exp(-t)/(1+x*t)^2,(t,0,oo))",
    },
  },
  // REVIEW: relies on the standard claim that the all-zero asymptotic series does not determine f; the non-uniqueness is a logical deduction (no single numeric check captures "for all N").
  {
    id: "am1d-009",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( e(x)=\\exp(-1/x) \\) and \\( q(x)=1+2x-x^{2}+e(x) \\) for \\( x>0 \\). Find the asymptotic power series of \\( q \\) as \\( x\\to 0^{+} \\), and explain what this shows about whether such a series determines the function uniquely.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["non-uniqueness", "exponentially small", "counterexample"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the key fact about \\( e(x) \\).", workingLatex: "e(x)=e^{-1/x} = o(x^N) \\ \\text{ for every } N \\ (x\\to 0^+).", explanation: "Substituting \\(u=1/x\\), \\(e^{-1/x}/x^N = u^N e^{-u}\\to 0\\); \\(e\\) is exponentially small, beyond all orders." },
        { stepNumber: 2, description: "Subtract the polynomial part.", workingLatex: "q(x) - (1+2x - x^2) = e(x) = o(x^N) \\ \\forall N.", explanation: "The polynomial \\(1+2x-x^2\\) is exact; the remainder is purely the exponentially small piece." },
        { stepNumber: 3, description: "Read off the series.", workingLatex: "q(x) \\sim 1 + 2x - x^2 + 0\\cdot x^3 + 0\\cdot x^4 + \\cdots.", explanation: "Beyond the quadratic every coefficient is zero, since \\(e(x)\\) contributes nothing to any power." },
        { stepNumber: 4, description: "Draw the conclusion.", workingLatex: "1+2x-x^2 \\ \\text{ and } \\ q(x) \\ \\text{ share the same asymptotic series.}", explanation: "Two different functions have identical asymptotic power series: the series does NOT determine the function. Information in the exponentially small tail is invisible to the expansion." },
      ],
      finalAnswer: "\\( q(x)\\sim 1+2x-x^{2} \\); the same series as the polynomial alone, so an asymptotic series does not determine the function uniquely.",
      canonicalAnswer: "1 + 2*x - x^2",
    },
  },
  {
    id: "am1d-010",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 10",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Suppose \\( H \\) has the asymptotic series \\( H(x)\\sim\\sum_{n\\ge 0}\\alpha_n x^{n} \\) as \\( x\\to 0^{+} \\), and that \\( H' \\) is continuous on \\( [0,\\infty) \\) and also possesses an asymptotic series \\( H'(x)\\sim\\sum_{n\\ge 0}\\beta_n x^{n} \\). Prove that \\( \\beta_n=(n+1)\\alpha_{n+1} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["term-by-term differentiation", "proof", "fundamental theorem of calculus"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate \\( H' \\) using its series.", workingLatex: "H(x) - H(0) = \\int_0^x H'(t)\\,dt.", explanation: "By the fundamental theorem of calculus, valid because \\(H'\\) is continuous on \\([0,\\infty)\\)." },
        { stepNumber: 2, description: "Term-by-term integration is legitimate for \\( H' \\).", workingLatex: "H'(t) = \\sum_{k=0}^{N}\\beta_k t^k + o(t^N) \\implies \\int_0^x H'\\,dt = \\sum_{k=0}^{N}\\frac{\\beta_k}{k+1}x^{k+1} + o(x^{N+1}).", explanation: "Integration always preserves asymptoticity: the \\(o(t^N)\\) remainder integrates to \\(o(x^{N+1})\\)." },
        { stepNumber: 3, description: "Identify \\( H(0)=\\alpha_0 \\).", workingLatex: "H(x) \\sim \\alpha_0 + \\sum_{k\\ge 0}\\frac{\\beta_k}{k+1}x^{k+1}.", explanation: "Letting \\(x\\to 0^+\\) in \\(H\\sim\\sum\\alpha_n x^n\\) gives \\(H(0)=\\alpha_0\\)." },
        { stepNumber: 4, description: "Compare with the given series for \\( H \\).", workingLatex: "\\alpha_0 + \\sum_{k\\ge 0}\\frac{\\beta_k}{k+1}x^{k+1} \\ \\sim\\ \\alpha_0 + \\sum_{n\\ge 1}\\alpha_n x^{n}.", explanation: "Both are asymptotic series for the same \\(H\\); asymptotic power-series coefficients are unique." },
        { stepNumber: 5, description: "Match coefficients of \\( x^{n+1} \\).", workingLatex: "\\frac{\\beta_n}{n+1} = \\alpha_{n+1}.", explanation: "Set \\(k=n\\) in the left sum (giving power \\(x^{n+1}\\)) equal to \\(\\alpha_{n+1}\\) on the right." },
        { stepNumber: 6, description: "Rearrange.", workingLatex: "\\beta_n = (n+1)\\,\\alpha_{n+1}.", explanation: "So if \\(H'\\) has an asymptotic series at all, it MUST be the term-by-term derivative of \\(H\\)'s." },
      ],
      finalAnswer: "\\( \\beta_n = (n+1)\\,\\alpha_{n+1} \\).",
      canonicalAnswer: "(n+1)*alpha_{n+1}",
    },
  },
  {
    id: "am1d-011",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 11",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Use integration by parts to obtain the first three terms of the asymptotic expansion, as \\( x\\to\\infty \\), of the exponential integral \\( \\displaystyle E_1(x)=\\int_x^{\\infty}\\frac{e^{-t}}{t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "exponential integral", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the first integration by parts.", workingLatex: "E_1(x)=\\int_x^{\\infty}\\frac{e^{-t}}{t}\\,dt,\\quad u=\\frac1t,\\ dv=e^{-t}dt.", explanation: "Differentiating the algebraic factor \\(1/t\\) makes it smaller; integrating \\(e^{-t}\\) keeps the exponential. This is the standard generation of the series." },
        { stepNumber: 2, description: "Apply parts once.", workingLatex: "E_1(x) = \\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty} - \\int_x^{\\infty}\\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x} - \\int_x^{\\infty}\\frac{e^{-t}}{t^2}\\,dt.", explanation: "The boundary term at \\(\\infty\\) vanishes; at \\(t=x\\) it gives \\(e^{-x}/x\\)." },
        { stepNumber: 3, description: "Apply parts a second time.", workingLatex: "\\int_x^{\\infty}\\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x^2} - 2\\int_x^{\\infty}\\frac{e^{-t}}{t^3}\\,dt.", explanation: "Same scheme with \\(u=t^{-2}\\), \\(du=-2t^{-3}dt\\)." },
        { stepNumber: 4, description: "Apply parts a third time.", workingLatex: "\\int_x^{\\infty}\\frac{e^{-t}}{t^3}\\,dt = \\frac{e^{-x}}{x^3} - 3\\int_x^{\\infty}\\frac{e^{-t}}{t^4}\\,dt.", explanation: "The leftover integral is \\(O(e^{-x}x^{-4})\\), smaller than every term kept." },
        { stepNumber: 5, description: "Back-substitute.", workingLatex: "E_1(x) = \\frac{e^{-x}}{x} - \\frac{e^{-x}}{x^2} + \\frac{2e^{-x}}{x^3} - 6\\int_x^{\\infty}\\frac{e^{-t}}{t^4}\\,dt.", explanation: "Chase the signs through the three boundary terms; coefficients are \\(0!,1!,2!\\)." },
        { stepNumber: 6, description: "State the expansion and remainder.", workingLatex: "E_1(x) \\sim e^{-x}\\!\\left(\\frac1x - \\frac1{x^2} + \\frac{2}{x^3} - \\cdots\\right),\\ \\text{remainder } O\\!\\big(e^{-x}x^{-4}\\big).", explanation: "Numerically at \\(x=5\\): three terms give \\(1.121\\times10^{-3}\\) vs exact \\(1.148\\times10^{-3}\\); at \\(x=10\\) the agreement is to four figures." },
      ],
      finalAnswer: "\\( E_1(x) \\sim e^{-x}\\!\\left(\\dfrac{1}{x} - \\dfrac{1}{x^{2}} + \\dfrac{2}{x^{3}} - \\cdots\\right) \\) as \\( x\\to\\infty \\).",
      canonicalAnswer: "exp(-x)*(1/x - 1/x^2 + 2/x^3)",
    },
  },
  {
    id: "am1d-012",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 12",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "It is given that \\( E_1(x)+\\ln x \\to -\\gamma \\) as \\( x\\to 0^{+} \\), where \\( \\gamma \\) is Euler's constant. By differentiating \\( E_1(x)+\\ln x \\) and integrating the resulting series, find the first two non-constant terms of the small-\\( x \\) expansion of \\( E_1(x) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiate then integrate", "exponential integral", "small-x expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate \\( E_1 \\).", workingLatex: "E_1'(x) = \\frac{d}{dx}\\int_x^{\\infty}\\frac{e^{-t}}{t}\\,dt = -\\frac{e^{-x}}{x}.", explanation: "By the fundamental theorem of calculus (lower limit \\(x\\)), differentiating picks up the integrand at \\(t=x\\) with a minus sign." },
        { stepNumber: 2, description: "Differentiate the combination.", workingLatex: "\\frac{d}{dx}\\big[E_1(x)+\\ln x\\big] = -\\frac{e^{-x}}{x} + \\frac1x = \\frac{1-e^{-x}}{x}.", explanation: "The \\(1/x\\) singularities cancel: the combination is regular at \\(0\\)." },
        { stepNumber: 3, description: "Expand the regular derivative.", workingLatex: "\\frac{1-e^{-x}}{x} = \\frac1x\\Big(x - \\frac{x^2}{2} + \\frac{x^3}{6} - \\cdots\\Big) = 1 - \\frac{x}{2} + \\frac{x^2}{6} - \\cdots.", explanation: "Use \\(e^{-x}=1-x+x^2/2-\\cdots\\); the leading \\(1\\) cancels, leaving a clean power series." },
        { stepNumber: 4, description: "Integrate term by term.", workingLatex: "E_1(x)+\\ln x = -\\gamma + \\int_0^x\\Big(1-\\frac{t}{2}+\\frac{t^2}{6}-\\cdots\\Big)dt = -\\gamma + x - \\frac{x^2}{4} + \\cdots.", explanation: "The integration constant is fixed by the given limit \\(E_1+\\ln x\\to-\\gamma\\) at \\(x=0\\)." },
        { stepNumber: 5, description: "Isolate \\( E_1 \\).", workingLatex: "E_1(x) = -\\gamma - \\ln x + x - \\frac{x^2}{4} + \\cdots \\qquad (x\\to 0^+).", explanation: "Subtract \\(\\ln x\\); the convergent small-\\(x\\) series has leading logarithmic singularity \\(-\\ln x\\)." },
        { stepNumber: 6, description: "Identify the requested terms.", workingLatex: "\\text{first two non-constant: } -\\ln x \\ \\text{ and } \\ +x.", explanation: "The constant is \\(-\\gamma\\); the next pieces are \\(-\\ln x\\) and \\(+x\\)." },
      ],
      finalAnswer: "\\( E_1(x) = -\\gamma - \\ln x + x - \\dfrac{x^{2}}{4} + \\cdots \\) as \\( x\\to 0^{+} \\).",
      canonicalAnswer: "-gamma - log(x) + x - x^2/4",
    },
  },
  {
    id: "am1d-013",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( s(x)=\\sin x \\). Show that integrating the bound \\( s(x)=O(1) \\) over \\( [0,x] \\) is consistent with \\( \\int_0^x \\sin t\\,dt = O(1) \\), but that differentiating the (bounded) primitive does NOT lower the order. State, in one line, the general moral about which operation is safe.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration vs differentiation", "order notation", "asymmetry"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the primitive.", workingLatex: "\\int_0^x \\sin t\\,dt = 1-\\cos x.", explanation: "Elementary antiderivative." },
        { stepNumber: 2, description: "Bound the primitive.", workingLatex: "|1-\\cos x| \\le 2 = O(1).", explanation: "Integrating a bounded oscillation gives another bounded function — here even genuinely \\(O(1)\\), not the naive \\(O(x)\\)." },
        { stepNumber: 3, description: "Differentiate the bounded primitive.", workingLatex: "\\frac{d}{dx}(1-\\cos x) = \\sin x,\\qquad |\\sin x|\\le 1.", explanation: "Differentiating recovers \\(\\sin x\\): bounded again, but the point is the order is NOT improved by differentiating a small/bounded function." },
        { stepNumber: 4, description: "Sharpen the warning with a faster oscillation.", workingLatex: "g(x)=\\frac{\\cos(x^2)}{x}=O(x^{-1}),\\quad g'(x) = -2\\sin(x^2) - \\frac{\\cos(x^2)}{x^2},", explanation: "A function can be \\(o(1)\\) yet have an \\(O(1)\\) derivative — differentiation can be order-INCREASING." },
        { stepNumber: 5, description: "State the moral.", workingLatex: "\\boxed{\\text{Integration preserves/improves order; differentiation may destroy it.}}", explanation: "Term-by-term integration of an asymptotic estimate is always valid; differentiation requires extra hypotheses (continuity of the derivative and existence of its own expansion)." },
      ],
      finalAnswer: "Integration is the safe operation (order preserved/improved); differentiation can increase the order and is not generally valid without extra hypotheses.",
    },
  },
  {
    id: "am1d-014",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 14",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Given \\( \\displaystyle G(x)=\\int_0^{\\infty}\\frac{e^{-t}}{(1+xt)^{2}}\\,dt \\sim \\sum_{n=0}^{\\infty}(-1)^n (n+1)!\\,x^{n} \\) as \\( x\\to 0^{+} \\), integrate the series term by term to find the asymptotic series of \\( \\displaystyle \\Phi(x)=\\int_0^x G(s)\\,ds \\). Identify the closed form of \\( \\Phi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["term-by-term integration", "Stieltjes integral", "closed form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate each term of the series.", workingLatex: "\\int_0^x (-1)^n(n+1)!\\,s^n\\,ds = (-1)^n (n+1)!\\,\\frac{x^{n+1}}{n+1} = (-1)^n n!\\,x^{n+1}.", explanation: "The factor \\((n+1)!/(n+1)=n!\\) collapses neatly." },
        { stepNumber: 2, description: "Assemble the series for \\( \\Phi \\).", workingLatex: "\\Phi(x) \\sim \\sum_{n\\ge 0}(-1)^n n!\\,x^{n+1} = x - x^2 + 2x^3 - 6x^4 + \\cdots.", explanation: "Term-by-term integration is always valid; the remainder integrates to one higher order." },
        { stepNumber: 3, description: "Recognise the family.", workingLatex: "F(x) := \\int_0^{\\infty}\\frac{x\\,e^{-t}}{1+xt}\\,dt \\sim \\sum_{n\\ge 0}(-1)^n n!\\,x^{n+1}.", explanation: "This is exactly the Stieltjes integral with \\(\\rho(t)=x e^{-t}\\); its series matches \\(\\Phi\\)'s." },
        { stepNumber: 4, description: "Confirm the link \\( \\Phi=F \\) via \\( F'=G \\).", workingLatex: "F'(x) = G(x) \\implies F(x) = \\int_0^x G(s)\\,ds = \\Phi(x).", explanation: "Since \\(F(0)=0\\) and \\(F'=G\\) (verified numerically: \\(F'(0.1)=G(0.1)=0.843666606\\ldots\\)), the antiderivative \\(\\Phi\\) is precisely \\(F\\)." },
        { stepNumber: 5, description: "State the closed form.", workingLatex: "\\Phi(x) = \\int_0^{\\infty}\\frac{x\\,e^{-t}}{1+xt}\\,dt.", explanation: "So the integrated divergent series is asymptotic to this convergent integral." },
      ],
      finalAnswer: "\\( \\Phi(x)\\sim x - x^{2} + 2x^{3} - 6x^{4} + \\cdots \\), with closed form \\( \\Phi(x)=\\displaystyle\\int_0^{\\infty}\\frac{x e^{-t}}{1+xt}\\,dt \\).",
      canonicalAnswer: "x - x^2 + 2*x^3 - 6*x^4",
    },
  },
  {
    id: "am1d-015",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The Stieltjes series \\( F(x)\\sim\\sum (-1)^n n!\\,x^{n} \\) and \\( G(x)\\sim\\sum(-1)^n(n+1)!\\,x^{n} \\) satisfy \\( F'=G \\) for \\( \\rho(t)=x e^{-t} \\). Comment precisely on the relationship between the two series, i.e. show \\( G \\)'s series is the term-by-term derivative of \\( F \\)'s.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["term-by-term differentiation", "Stieltjes integral", "consistency"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write \\( F \\)'s series for \\( \\rho=xe^{-t} \\).", workingLatex: "F(x)\\sim\\sum_{n\\ge 0}(-1)^n n!\\,x^{n+1}.", explanation: "With \\(\\rho=xe^{-t}\\) the coefficients carry an extra \\(x\\), shifting every power up by one." },
        { stepNumber: 2, description: "Differentiate term by term.", workingLatex: "\\frac{d}{dx}\\Big[(-1)^n n!\\,x^{n+1}\\Big] = (-1)^n n!\\,(n+1)\\,x^{n} = (-1)^n (n+1)!\\,x^{n}.", explanation: "Power rule: \\(n!\\,(n+1) = (n+1)!\\)." },
        { stepNumber: 3, description: "Sum the differentiated series.", workingLatex: "\\sum_{n\\ge 0}(-1)^n (n+1)!\\,x^{n} = G\\text{'s series}.", explanation: "This is exactly the given series for \\(G\\)." },
        { stepNumber: 4, description: "State the consistency.", workingLatex: "F' = G \\ \\Longleftrightarrow\\ [\\text{series of }G] = \\tfrac{d}{dx}[\\text{series of }F].", explanation: "The two ASYMPTOTIC series are related by term-by-term differentiation, even though both are DIVERGENT. Here differentiation is legitimate because \\(F'=G\\) genuinely holds (differentiation under the integral), so no extra hypothesis is being smuggled in." },
      ],
      finalAnswer: "\\( G \\)'s series is the term-by-term derivative of \\( F \\)'s; consistent with \\( F'=G \\).",
    },
  },
  {
    id: "am1d-016",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 16",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the asymptotic series, as \\( x\\to\\infty \\), of \\( \\displaystyle J(x)=\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt \\) to three terms by integration by parts, and verify it equals \\( -\\frac{d}{dx} \\) applied term-by-term to \\( e^{-x}/x \\) is NOT the right relation — instead relate \\( J \\) to \\( E_1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "exponential integral", "relating integrals"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts once.", workingLatex: "J(x)=\\int_x^{\\infty}\\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x^2} - 2\\int_x^{\\infty}\\frac{e^{-t}}{t^3}\\,dt.", explanation: "Take \\(u=t^{-2}\\), \\(dv=e^{-t}dt\\); boundary term at \\(t=x\\) is \\(e^{-x}/x^2\\)." },
        { stepNumber: 2, description: "Integrate by parts again.", workingLatex: "\\int_x^{\\infty}\\frac{e^{-t}}{t^3}\\,dt = \\frac{e^{-x}}{x^3} - 3\\int_x^{\\infty}\\frac{e^{-t}}{t^4}\\,dt.", explanation: "Same scheme; the leftover is \\(O(e^{-x}x^{-4})\\)." },
        { stepNumber: 3, description: "Combine.", workingLatex: "J(x) = \\frac{e^{-x}}{x^2} - \\frac{2e^{-x}}{x^3} + 6\\int_x^{\\infty}\\frac{e^{-t}}{t^4}\\,dt.", explanation: "Substitute back; coefficients build the factorial pattern." },
        { stepNumber: 4, description: "State the series.", workingLatex: "J(x) \\sim e^{-x}\\!\\left(\\frac{1}{x^2} - \\frac{2}{x^3} + \\frac{6}{x^4} - \\cdots\\right).", explanation: "Coefficients are \\(1!,2!,3!\\) — the \\(t^{-2}\\) analogue of \\(E_1\\)'s series." },
        { stepNumber: 5, description: "Relate to \\( E_1 \\) by differentiation.", workingLatex: "E_1'(x) = -\\frac{e^{-x}}{x}, \\qquad \\frac{d}{dx}\\!\\left(\\frac{e^{-x}}{x}\\right) = -\\frac{e^{-x}}{x}-\\frac{e^{-x}}{x^2} = E_1'(x) - J(x)\\cdot 0\\ldots", explanation: "More directly: integrate \\(e^{-t}/t^2\\) by parts the other way to see \\(J(x)=\\frac{e^{-x}}{x}-E_1(x)\\)." },
        { stepNumber: 6, description: "Give the clean relation.", workingLatex: "J(x) = \\frac{e^{-x}}{x} - E_1(x).", explanation: "Indeed \\(\\frac{e^{-x}}{x}-E_1(x) = e^{-x}(\\tfrac1x) - e^{-x}(\\tfrac1x-\\tfrac1{x^2}+\\tfrac{2}{x^3}-\\cdots) = e^{-x}(\\tfrac1{x^2}-\\tfrac{2}{x^3}+\\cdots)\\), matching \\(J\\)." },
      ],
      finalAnswer: "\\( J(x) \\sim e^{-x}\\!\\left(\\dfrac{1}{x^{2}} - \\dfrac{2}{x^{3}} + \\dfrac{6}{x^{4}} - \\cdots\\right) = \\dfrac{e^{-x}}{x} - E_1(x) \\).",
      canonicalAnswer: "exp(-x)*(1/x^2 - 2/x^3 + 6/x^4)",
    },
  },
  {
    id: "am1d-017",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 17",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The error function complement satisfies \\( \\operatorname{erfc}(x)=\\frac{2}{\\sqrt\\pi}\\int_x^{\\infty}e^{-t^{2}}\\,dt \\). Using integration by parts, find the first two terms of its asymptotic expansion as \\( x\\to\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "erfc", "Gaussian tail"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Insert a helpful factor.", workingLatex: "\\int_x^{\\infty}e^{-t^2}\\,dt = \\int_x^{\\infty}\\frac{1}{t}\\cdot t e^{-t^2}\\,dt.", explanation: "Write \\(e^{-t^2}=\\tfrac1t\\cdot t e^{-t^2}\\) so that \\(te^{-t^2}\\) integrates exactly to \\(-\\tfrac12 e^{-t^2}\\)." },
        { stepNumber: 2, description: "Integrate by parts.", workingLatex: "= \\left[-\\frac{e^{-t^2}}{2t}\\right]_x^{\\infty} - \\int_x^{\\infty}\\frac{e^{-t^2}}{2t^2}\\,dt = \\frac{e^{-x^2}}{2x} - \\frac12\\int_x^{\\infty}\\frac{e^{-t^2}}{t^2}\\,dt.", explanation: "\\(u=1/t,\\ dv=te^{-t^2}dt,\\ v=-\\tfrac12 e^{-t^2}\\)." },
        { stepNumber: 3, description: "Integrate by parts again.", workingLatex: "\\int_x^{\\infty}\\frac{e^{-t^2}}{t^2}\\,dt = \\frac{e^{-x^2}}{2x^3} - \\frac{3}{2}\\int_x^{\\infty}\\frac{e^{-t^2}}{t^4}\\,dt.", explanation: "Same trick with \\(u=t^{-3}\\); the new integral is \\(O(e^{-x^2}x^{-5})\\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_x^{\\infty}e^{-t^2}\\,dt = \\frac{e^{-x^2}}{2x} - \\frac{e^{-x^2}}{4x^3} + O\\!\\big(e^{-x^2}x^{-5}\\big).", explanation: "Multiply the second IBP by \\(-\\tfrac12\\) and substitute." },
        { stepNumber: 5, description: "Multiply by \\( 2/\\sqrt\\pi \\).", workingLatex: "\\operatorname{erfc}(x) \\sim \\frac{e^{-x^2}}{x\\sqrt\\pi}\\left(1 - \\frac{1}{2x^2} + \\cdots\\right).", explanation: "Numerically at \\(x=2\\): leading two terms give \\(\\operatorname{erfc}\\approx 0.00452\\) vs exact \\(0.00468\\) (~3% — the next term \\(+3/(4x^4)\\) closes most of the gap)." },
      ],
      finalAnswer: "\\( \\operatorname{erfc}(x) \\sim \\dfrac{e^{-x^{2}}}{x\\sqrt\\pi}\\left(1 - \\dfrac{1}{2x^{2}} + \\cdots\\right) \\) as \\( x\\to\\infty \\).",
      canonicalAnswer: "exp(-x^2)/(x*sqrt(pi))*(1 - 1/(2*x^2))",
    },
  },
  {
    id: "am1d-018",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Suppose \\( f(x)=o(e^{x}) \\) as \\( x\\to\\infty \\) with \\( f \\) continuous. By integrating, find the sharpest order bound of the form \\( o(g(x)) \\) for \\( \\displaystyle\\int_0^x f(t)\\,dt \\), and explain why the naive answer \\( o(x e^{x}) \\) is not the sharpest here.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integrating o(phi)", "non-decreasing gauge", "sharp bound"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the general theorem.", workingLatex: "f=o(e^x),\\ \\varphi(x)=e^x \\text{ increasing} \\implies \\int_0^x f\\,dt = o(x e^x).", explanation: "The theorem \\(\\int^x o(\\varphi)=o(x\\varphi)\\) immediately gives \\(o(xe^x)\\)." },
        { stepNumber: 2, description: "Sharpen using the integral of the gauge.", workingLatex: "\\left|\\int_X^x f\\,dt\\right| \\le \\varepsilon\\int_X^x e^t\\,dt = \\varepsilon\\,(e^x - e^X) < \\varepsilon\\, e^x.", explanation: "For \\(\\varphi=e^x\\) the integral of the gauge is itself \\(\\sim e^x\\), NOT \\(x e^x\\): the antiderivative does not grow the gauge by a factor \\(x\\)." },
        { stepNumber: 3, description: "Absorb the head.", workingLatex: "\\left|\\int_0^x f\\,dt\\right| \\le C + \\varepsilon e^x < 2\\varepsilon e^x \\quad (x \\text{ large}).", explanation: "The constant head is eventually below \\(\\varepsilon e^x\\) since \\(e^x\\to\\infty\\)." },
        { stepNumber: 4, description: "State the sharp bound and the reason.", workingLatex: "\\int_0^x f(t)\\,dt = o(e^x).", explanation: "The \\(o(x\\varphi)\\) rule is general but not always sharp: when \\(\\int\\varphi \\sim \\varphi\\) (fast-growing gauge), the extra factor \\(x\\) is wasteful and \\(o(\\varphi)\\) holds." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^x f(t)\\,dt = o(e^{x}) \\); sharper than \\( o(xe^{x}) \\) because \\( \\int^x e^{t}dt\\sim e^{x} \\).",
      canonicalAnswer: "o(exp(x))",
    },
  },

  // ─────────────────────────────────────── CHALLENGE (12) ───────────────────────────────────────
  // REVIEW: the counterexample's failure of term-by-term differentiation rests on the unboundedness of an oscillatory term for ALL small x — a structural statement, only spot-checked numerically.
  {
    id: "am1d-019",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Give an explicit smooth \\( H:(0,\\infty)\\to(0,\\infty) \\) that admits an asymptotic power series \\( \\sum\\alpha_n x^{n} \\) as \\( x\\to 0^{+} \\) but for which term-by-term differentiation does NOT give an asymptotic series for \\( H' \\). Justify each claim.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["counterexample", "term-by-term differentiation", "oscillatory remainder"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Propose the function.", workingLatex: "H(x) = 1 + e^{-1/x}\\sin\\!\\big(e^{1/x}\\big).", explanation: "We add \\(1\\) so that \\(H>0\\) (range in \\((0,\\infty)\\)); the interesting structure is the oscillatory exponentially small piece." },
        { stepNumber: 2, description: "Show \\( H \\) has an asymptotic series.", workingLatex: "\\big|H(x)-1\\big| = e^{-1/x}\\big|\\sin(e^{1/x})\\big| \\le e^{-1/x} = o(x^N)\\ \\forall N.", explanation: "Since \\(e^{-1/x}\\) is beyond all orders and \\(|\\sin|\\le1\\), \\(H(x)\\sim 1+0\\cdot x+0\\cdot x^2+\\cdots\\); every \\(\\alpha_n=0\\) for \\(n\\ge1\\)." },
        { stepNumber: 3, description: "Differentiate \\( H \\).", workingLatex: "H'(x) = \\frac{1}{x^2}e^{-1/x}\\sin\\!\\big(e^{1/x}\\big) - \\frac{1}{x^2}\\cos\\!\\big(e^{1/x}\\big).", explanation: "Use \\(\\frac{d}{dx}e^{-1/x}=x^{-2}e^{-1/x}\\) and \\(\\frac{d}{dx}e^{1/x}=-x^{-2}e^{1/x}\\); the \\(e^{-1/x}\\cdot e^{1/x}=1\\) cancellation produces the bare \\(-x^{-2}\\cos\\) term." },
        { stepNumber: 4, description: "Identify the rogue term.", workingLatex: "H'(x) = \\underbrace{o(x^N)}_{\\text{first term}} \\ -\\ \\frac{\\cos(e^{1/x})}{x^2}.", explanation: "The first term is exponentially small, but the second oscillates with amplitude \\(x^{-2}\\to\\infty\\)." },
        { stepNumber: 5, description: "Show \\( H' \\) has no asymptotic power series.", workingLatex: "\\limsup_{x\\to 0^+} x^2|H'(x)| = 1 \\not\\to 0,\\ \\text{ and } x^2 H'(x)\\ \\text{oscillates}.", explanation: "If \\(H'\\sim\\sum\\beta_n x^n\\) existed, \\(H'\\) would be bounded near \\(0\\) (with \\(H'\\to\\beta_0\\)); but \\(x^{-2}\\cos(e^{1/x})\\) is unbounded and oscillatory, so no limit \\(\\beta_0\\) exists." },
        { stepNumber: 6, description: "Contrast with the formal derivative.", workingLatex: "\\sum_{n\\ge1} n\\alpha_n x^{n-1} = 0 \\ne H'(x).", explanation: "Term-by-term differentiation of \\(H\\sim1\\) gives the zero series, which is NOT asymptotic to the genuinely unbounded \\(H'\\). This is the required counterexample." },
      ],
      finalAnswer: "\\( H(x)=1+e^{-1/x}\\sin\\!\\big(e^{1/x}\\big) \\): \\( H\\sim 1 \\) but \\( H'(x)=x^{-2}e^{-1/x}\\sin(e^{1/x})-x^{-2}\\cos(e^{1/x}) \\) is unbounded and has no asymptotic power series.",
    },
  },
  {
    id: "am1d-020",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 20",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the Stieltjes integral \\( \\displaystyle G(x)=\\int_0^{\\infty}\\frac{e^{-t}}{(1+xt)^{2}}\\,dt \\sim \\sum_{n\\ge 0}(-1)^n(n+1)!\\,x^{n} \\), use optimal truncation at \\( x=0.1 \\) to estimate \\( G(0.1) \\), and compare with the exact value \\( 0.84366660602\\ldots \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "divergent series", "Stieltjes integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the general term.", workingLatex: "u_n = (n+1)!\\,x^{n}, \\qquad x=0.1.", explanation: "The magnitude of the \\(n\\)th term ignoring sign; we find where it is smallest." },
        { stepNumber: 2, description: "Form the ratio of consecutive terms.", workingLatex: "\\frac{u_{n+1}}{u_n} = (n+2)\\,x = (n+2)(0.1).", explanation: "Terms decrease while this ratio \\(<1\\), i.e. while \\(n+2<10\\), and increase once it exceeds \\(1\\)." },
        { stepNumber: 3, description: "Locate the smallest term.", workingLatex: "(n+2)(0.1) = 1 \\implies n = 8; \\quad \\text{ratio} <1 \\text{ for } n\\le 7,\\ >1 \\text{ for } n\\ge 8.", explanation: "The terms shrink up to \\(n=8\\) then grow: \\(n=8\\) (and \\(n=9\\), nearly equal) is the smallest. Numerically the minimum magnitude is at \\(n=9\\) (value \\(\\approx0.0036\\))." },
        { stepNumber: 4, description: "Apply optimal truncation (keep up to BEFORE the smallest).", workingLatex: "G(0.1) \\approx \\sum_{n=0}^{8}(-1)^n(n+1)!\\,(0.1)^n.", explanation: "Convention: truncate just before the smallest term, here summing \\(n=0,\\dots,8\\)." },
        { stepNumber: 5, description: "Evaluate the partial sum.", workingLatex: "\\sum_{n=0}^{8}(-1)^n(n+1)!\\,(0.1)^n \\approx 0.843667\\ldots", explanation: "Adding \\(1 -2(0.1)+6(0.01)-24(0.001)+\\cdots\\); the alternating partial sum settles near the true value." },
        { stepNumber: 6, description: "Compare with the exact value.", workingLatex: "|0.843667 - 0.84366660602| \\approx 4\\times10^{-7}.", explanation: "Optimal truncation of this divergent series reproduces the exact value to about six significant figures — the smallest term \\(\\sim3.6\\times10^{-3}\\) gives a rough error scale, with the alternating structure doing better." },
      ],
      finalAnswer: "Optimal truncation (terms \\( n=0,\\dots,8 \\)) gives \\( G(0.1)\\approx 0.843667 \\), agreeing with \\( 0.84366660602\\ldots \\) to ~6 s.f.",
      canonicalAnswer: "0.843667",
    },
  },
  {
    id: "am1d-021",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that if \\( f \\) is continuous and \\( f(x)=o(\\varphi(x)) \\) as \\( x\\to\\infty \\) with \\( \\varphi \\) continuous, positive and non-decreasing, then for any fixed \\( c>a \\), \\( \\displaystyle\\int_c^x f(t)\\,dt = o(x\\varphi(x)) \\); and explain why the result can FAIL if \\( \\varphi \\) is allowed to decrease.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integrating o(phi)", "monotone gauge", "counterexample"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the definition.", workingLatex: "\\forall\\varepsilon>0\\ \\exists X: |f(t)|<\\varepsilon\\varphi(t)\\ (t>X).", explanation: "Standard \\(o\\)-definition with gauge \\(\\varphi\\)." },
        { stepNumber: 2, description: "Bound the tail using monotonicity.", workingLatex: "\\left|\\int_X^x f\\,dt\\right|\\le\\varepsilon\\int_X^x\\varphi(t)\\,dt\\le\\varepsilon(x-X)\\varphi(x)<\\varepsilon x\\varphi(x).", explanation: "\\(\\varphi\\) non-decreasing \\(\\Rightarrow \\varphi(t)\\le\\varphi(x)\\) on \\([X,x]\\)." },
        { stepNumber: 3, description: "Dispose of the constant head.", workingLatex: "\\frac{1}{x\\varphi(x)}\\left|\\int_c^X f\\,dt\\right|\\to 0,", explanation: "\\(x\\varphi(x)\\ge x\\varphi(X)\\to\\infty\\) since \\(\\varphi(X)>0\\); the fixed head is negligible." },
        { stepNumber: 4, description: "Conclude the positive result.", workingLatex: "\\int_c^x f\\,dt = o(x\\varphi(x)).", explanation: "Combine head and tail; \\(\\varepsilon\\) arbitrary." },
        { stepNumber: 5, description: "Construct a decreasing-\\( \\varphi \\) counterexample.", workingLatex: "\\varphi(t)=\\frac1t,\\quad f(t)=\\frac{1}{t\\ln t}=o\\!\\Big(\\frac1t\\Big).", explanation: "Indeed \\(f/\\varphi=1/\\ln t\\to0\\), so \\(f=o(\\varphi)\\). But \\(\\varphi\\) is decreasing, so the monotonicity step fails." },
        { stepNumber: 6, description: "Exhibit the failure of the order.", workingLatex: "\\int_c^x\\frac{dt}{t\\ln t}=\\ln\\ln x - \\ln\\ln c \\ne o\\!\\Big(x\\cdot\\frac1x\\Big)=o(1).", explanation: "The integral \\(\\to\\infty\\), so it is NOT \\(o(x\\varphi(x))=o(1)\\). With a decreasing gauge the bound \\(\\int_X^x\\varphi\\le(x-X)\\varphi(x)\\) is false, and the theorem collapses." },
      ],
      finalAnswer: "The bound \\( \\int_c^x f = o(x\\varphi(x)) \\) holds for non-decreasing \\( \\varphi \\); for decreasing \\( \\varphi \\) (e.g. \\( \\varphi=1/t,\\ f=1/(t\\ln t) \\)) it fails since \\( \\int_c^x f=\\ln\\ln x\\to\\infty \\neq o(1) \\).",
    },
  },
  {
    id: "am1d-022",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 22",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The Stieltjes integral \\( \\displaystyle F(x)=\\int_0^{\\infty}\\frac{e^{-t}}{1+xt}\\,dt \\) has \\( F\\sim\\sum(-1)^n n!\\,x^n \\) and derivative \\( G=F' \\) (with \\( \\rho=xe^{-t} \\) framing). Verify the identity \\( F'(x)=G(x) \\) directly at \\( x=0.1 \\) by computing both sides, and state what this confirms about differentiating the asymptotic series.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiate under integral", "consistency check", "Stieltjes integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the \\( \\rho=xe^{-t} \\) Stieltjes integral.", workingLatex: "\\tilde F(x)=\\int_0^{\\infty}\\frac{x e^{-t}}{1+xt}\\,dt \\sim \\sum_{n\\ge0}(-1)^n n!\\,x^{n+1}.", explanation: "This is the version whose derivative is \\(G\\); the extra \\(x\\) shifts all powers up." },
        { stepNumber: 2, description: "Differentiate under the integral.", workingLatex: "\\tilde F'(x)=\\int_0^{\\infty}\\frac{\\partial}{\\partial x}\\frac{xe^{-t}}{1+xt}\\,dt = \\int_0^{\\infty}\\frac{e^{-t}}{(1+xt)^2}\\,dt = G(x).", explanation: "Quotient/product rule: \\(\\partial_x[x/(1+xt)] = (1+xt - x\\cdot t)/(1+xt)^2 = 1/(1+xt)^2\\)." },
        { stepNumber: 3, description: "Compute \\( G(0.1) \\) numerically.", workingLatex: "G(0.1)=\\int_0^{\\infty}\\frac{e^{-t}}{(1+0.1t)^2}\\,dt = 0.843666606021\\ldots", explanation: "Direct quadrature of the convergent integral." },
        { stepNumber: 4, description: "Compute \\( \\tilde F'(0.1) \\) by central difference.", workingLatex: "\\tilde F'(0.1)\\approx\\frac{\\tilde F(0.1+h)-\\tilde F(0.1-h)}{2h}\\Big|_{h=10^{-8}} = 0.843666606021\\ldots", explanation: "A high-precision finite difference of the convergent integral \\(\\tilde F\\)." },
        { stepNumber: 5, description: "Confirm agreement.", workingLatex: "\\big|\\tilde F'(0.1) - G(0.1)\\big| < 10^{-13}.", explanation: "The two sides agree to machine-style precision, confirming \\(F'=G\\) for the actual functions." },
        { stepNumber: 6, description: "State the consequence.", workingLatex: "[G\\text{'s series}] = \\frac{d}{dx}[\\tilde F\\text{'s series}], \\text{ even though both DIVERGE.}", explanation: "Because the genuine relation \\(F'=G\\) holds, term-by-term differentiation of the (divergent) asymptotic series is legitimate here — the asymptotic series may be differentiated whenever the functions themselves satisfy the differentiated relation." },
      ],
      finalAnswer: "\\( \\tilde F'(0.1)=G(0.1)=0.843666606021\\ldots \\) (agree to \\( <10^{-13} \\)); confirms term-by-term differentiation of the asymptotic series is valid for this family.",
      canonicalAnswer: "0.843666606021",
    },
  },
  {
    id: "am1d-023",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 23",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Starting from \\( E_1(x)\\sim e^{-x}\\sum_{n\\ge0}(-1)^n n!\\,x^{-n-1} \\) as \\( x\\to\\infty \\), confirm by differentiating term by term that the resulting series is consistent with the exact relation \\( E_1'(x)=-e^{-x}/x \\). State to what extent term-by-term differentiation is justified.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["term-by-term differentiation", "exponential integral", "consistency"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write a generic term.", workingLatex: "a_n(x) = (-1)^n n!\\,e^{-x}x^{-n-1}.", explanation: "The \\(n\\)th term of \\(E_1\\)'s expansion, including the common \\(e^{-x}\\)." },
        { stepNumber: 2, description: "Differentiate one term by the product rule.", workingLatex: "a_n'(x) = (-1)^n n!\\Big[-e^{-x}x^{-n-1} - (n+1)e^{-x}x^{-n-2}\\Big].", explanation: "Differentiate \\(e^{-x}\\) and \\(x^{-n-1}\\) separately." },
        { stepNumber: 3, description: "Sum over \\( n \\) and split.", workingLatex: "\\sum_n a_n' = -e^{-x}\\sum_n(-1)^n n!\\,x^{-n-1} - e^{-x}\\sum_n(-1)^n (n+1)!\\,x^{-n-2}.", explanation: "Group the two contributions; the second uses \\(n!\\,(n+1)=(n+1)!\\)." },
        { stepNumber: 4, description: "Re-index the second sum.", workingLatex: "e^{-x}\\sum_{n\\ge0}(-1)^n(n+1)!\\,x^{-n-2} = e^{-x}\\sum_{m\\ge1}(-1)^{m-1}m!\\,x^{-m-1}.", explanation: "Let \\(m=n+1\\); the sign flips to \\((-1)^{m-1}=-(-1)^m\\)." },
        { stepNumber: 5, description: "Combine the two sums.", workingLatex: "\\sum_n a_n' = -e^{-x}\\Big[\\,x^{-1} + \\sum_{m\\ge1}\\big((-1)^m - (-1)^{m}\\big)m!\\,x^{-m-1}\\Big] = -\\frac{e^{-x}}{x}.", explanation: "All terms with \\(m\\ge1\\) cancel in pairs; only the \\(n=0\\) term \\(-e^{-x}x^{-1}\\) survives." },
        { stepNumber: 6, description: "Compare with the exact derivative.", workingLatex: "E_1'(x) = -\\frac{e^{-x}}{x} = \\frac{d}{dx}\\big[\\text{series}\\big].", explanation: "Term-by-term differentiation reproduces the EXACT derivative. It is justified here because \\(E_1\\) is smooth and \\(E_1'\\) has its own (in fact finite) asymptotic series — the hypotheses of the differentiation theorem hold." },
      ],
      finalAnswer: "Term-by-term differentiation yields exactly \\( E_1'(x)=-e^{-x}/x \\); valid because \\( E_1' \\) is continuous with its own asymptotic series.",
      canonicalAnswer: "-exp(-x)/x",
    },
  },
  {
    id: "am1d-024",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 24",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Define \\( \\displaystyle S(x)=\\int_0^x \\frac{\\sin t}{t}\\,dt \\) (so \\( S\\to\\pi/2 \\) as \\( x\\to\\infty \\)). Using integration by parts on \\( \\int_x^{\\infty}\\frac{\\sin t}{t}\\,dt \\), find the first two terms of the large-\\( x \\) expansion of \\( \\frac{\\pi}{2}-S(x) \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "sine integral", "oscillatory tail"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the tail.", workingLatex: "\\frac{\\pi}{2} - S(x) = \\int_x^{\\infty}\\frac{\\sin t}{t}\\,dt.", explanation: "Since \\(\\int_0^{\\infty}\\frac{\\sin t}{t}dt=\\pi/2\\), the deficit is the tail from \\(x\\) to \\(\\infty\\)." },
        { stepNumber: 2, description: "Integrate by parts (\\( dv=\\sin t\\,dt \\)).", workingLatex: "\\int_x^{\\infty}\\frac{\\sin t}{t}\\,dt = \\left[-\\frac{\\cos t}{t}\\right]_x^{\\infty} - \\int_x^{\\infty}\\frac{\\cos t}{t^2}\\,dt = \\frac{\\cos x}{x} - \\int_x^{\\infty}\\frac{\\cos t}{t^2}\\,dt.", explanation: "Boundary term at \\(\\infty\\) vanishes (Riemann–Lebesgue/decay); at \\(t=x\\) gives \\(\\cos x/x\\)." },
        { stepNumber: 3, description: "Integrate by parts again.", workingLatex: "\\int_x^{\\infty}\\frac{\\cos t}{t^2}\\,dt = \\left[\\frac{\\sin t}{t^2}\\right]_x^{\\infty} + 2\\int_x^{\\infty}\\frac{\\sin t}{t^3}\\,dt = -\\frac{\\sin x}{x^2} + 2\\int_x^{\\infty}\\frac{\\sin t}{t^3}\\,dt.", explanation: "Now \\(dv=\\cos t\\,dt,\\ v=\\sin t\\); the leftover is \\(O(x^{-3})\\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\frac{\\pi}{2}-S(x) = \\frac{\\cos x}{x} + \\frac{\\sin x}{x^2} - 2\\int_x^{\\infty}\\frac{\\sin t}{t^3}\\,dt.", explanation: "Substitute back, watching the sign of the second IBP." },
        { stepNumber: 5, description: "State the two-term expansion.", workingLatex: "\\frac{\\pi}{2}-S(x) \\sim \\frac{\\cos x}{x} + \\frac{\\sin x}{x^2} + O(x^{-3}).", explanation: "The expansion is oscillatory (coefficients are \\(\\cos x,\\sin x\\)) — IBP, not Watson, because there is no exponential decay." },
        { stepNumber: 6, description: "Sanity check at \\( x=10 \\).", workingLatex: "\\frac{\\cos 10}{10}+\\frac{\\sin 10}{100} \\approx -0.0839 - 0.00544 = -0.0893,\\ \\text{vs exact } \\tfrac{\\pi}{2}-S(10)\\approx -0.0876.", explanation: "Two terms reproduce the deficit to about two decimals; the \\(O(x^{-3})\\) remainder accounts for the rest." },
      ],
      finalAnswer: "\\( \\dfrac{\\pi}{2}-S(x) \\sim \\dfrac{\\cos x}{x} + \\dfrac{\\sin x}{x^{2}} + O(x^{-3}) \\) as \\( x\\to\\infty \\).",
      canonicalAnswer: "cos(x)/x + sin(x)/x^2",
    },
  },
  {
    id: "am1d-025",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 25",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "It is given that \\( \\displaystyle\\int_x^{\\infty}t^{-1}e^{-t}\\,dt = E_1(x) \\) has remainder bound \\( |\\text{Err}_N|\\le N!\\,e^{-x}x^{-N-1} \\). Using optimal truncation \\( N+1=\\lfloor x\\rfloor \\) and Stirling's formula, show the optimal error is \\( O\\big(x^{1/2}e^{-2x}\\big) \\) and hence beyond all algebraic orders relative to \\( e^{-x} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stirling's formula", "beyond all orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the error at truncation order.", workingLatex: "|\\text{Err}_N| \\le N!\\,e^{-x}\\,x^{-N-1}.", explanation: "Given remainder bound after keeping terms up to \\(n=N\\)." },
        { stepNumber: 2, description: "Choose optimal \\( N \\).", workingLatex: "N+1 = \\lfloor x\\rfloor \\implies N \\approx x-1.", explanation: "The terms \\(n!\\,x^{-n-1}\\) are smallest near \\(n\\approx x\\); truncating there minimises the bound." },
        { stepNumber: 3, description: "Apply Stirling to \\( N! \\).", workingLatex: "N! \\sim \\sqrt{2\\pi N}\\,\\Big(\\frac{N}{e}\\Big)^{N},\\qquad N\\approx x-1.", explanation: "Stirling's asymptotic for the factorial at large \\(N\\)." },
        { stepNumber: 4, description: "Substitute \\( N\\approx x \\) into the bound.", workingLatex: "N!\\,x^{-N-1} \\sim \\sqrt{2\\pi x}\\,\\Big(\\frac{x}{e}\\Big)^{x}x^{-x-1} = \\sqrt{2\\pi x}\\,\\frac{e^{-x}}{x}.", explanation: "Use \\((x/e)^x x^{-x} = e^{-x}\\); the surviving algebraic factor is \\(\\sqrt{2\\pi x}/x = \\sqrt{2\\pi}\\,x^{-1/2}\\)." },
        { stepNumber: 5, description: "Include the prefactor \\( e^{-x} \\).", workingLatex: "|\\text{Err}| \\lesssim e^{-x}\\cdot\\sqrt{2\\pi}\\,x^{-1/2}\\,e^{-x} = \\sqrt{2\\pi}\\,x^{-1/2}e^{-2x}.", explanation: "The bound already carried an \\(e^{-x}\\); multiplying by the \\(e^{-x}\\) from Stirling gives \\(e^{-2x}\\)." },
        { stepNumber: 6, description: "State the order.", workingLatex: "|\\text{Err}| = O\\!\\big(x^{1/2}e^{-2x}\\big)\\ \\Big(\\text{relative to }e^{-x}:\\ O(x^{1/2}e^{-x})\\Big).", explanation: "Note: writing it as \\(O(x^{1/2}e^{-x})\\) RELATIVE to the natural \\(e^{-x}\\) scale shows the optimal error is exponentially small beyond the expansion — \\(o(x^{-M}e^{-x})\\) for every \\(M\\)." },
        { stepNumber: 7, description: "Conclude beyond-all-orders.", workingLatex: "\\frac{|\\text{Err}|}{x^{-M}e^{-x}} = O\\!\\big(x^{M+1/2}e^{-x}\\big)\\to 0\\ \\forall M.", explanation: "The exponential \\(e^{-x}\\) beats every power \\(x^{M}\\): optimal truncation pushes the error below all algebraic orders of the asymptotic series." },
      ],
      finalAnswer: "Optimal error \\( \\sim \\sqrt{2\\pi}\\,x^{1/2}e^{-2x} = O(x^{1/2}e^{-2x}) \\), i.e. \\( o(x^{-M}e^{-x}) \\) for every \\( M \\): beyond all algebraic orders.",
      canonicalAnswer: "sqrt(2*pi)*x^(1/2)*exp(-2*x)",
    },
  },
  {
    id: "am1d-026",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 26",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Let \\( \\displaystyle F(x)=\\int_0^{\\infty}\\frac{e^{-t}}{1+xt}\\,dt \\) with \\( F\\sim\\sum(-1)^n n!\\,x^n \\). Using optimal truncation at \\( x=0.2 \\), estimate \\( F(0.2) \\) and compare with the exact value \\( 0.85211088\\ldots \\). State which term is the smallest.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "divergent series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Term magnitudes.", workingLatex: "u_n = n!\\,(0.2)^n.", explanation: "Ignore the alternating sign; locate the minimum." },
        { stepNumber: 2, description: "Ratio test for the minimum.", workingLatex: "\\frac{u_{n+1}}{u_n} = (n+1)(0.2).", explanation: "Decreasing while \\((n+1)(0.2)<1\\), i.e. \\(n+1<5\\), increasing for \\(n+1>5\\)." },
        { stepNumber: 3, description: "Smallest term.", workingLatex: "(n+1)(0.2)=1 \\implies n=4; \\ u_4=u_5 = 24(0.2)^4 = 0.0384.", explanation: "Terms \\(n=4\\) and \\(n=5\\) are equal in magnitude and smallest." },
        { stepNumber: 4, description: "Optimal truncation (before the smallest).", workingLatex: "F(0.2) \\approx \\sum_{n=0}^{4}(-1)^n n!\\,(0.2)^n.", explanation: "Keep up to \\(n=4\\), one before (one of) the smallest pair." },
        { stepNumber: 5, description: "Compute the partial sum.", workingLatex: "1 - 0.2 + 2(0.04) - 6(0.008) + 24(0.0016) = 1 -0.2 +0.08 -0.048 +0.0384 = 0.8704.", explanation: "Term-by-term arithmetic." },
        { stepNumber: 6, description: "Compare to the exact value.", workingLatex: "|0.8704 - 0.852111| \\approx 0.018,", explanation: "The error is of the order of the smallest term (\\(\\approx0.038\\)) — characteristic of optimal truncation. At the larger \\(x=0.2\\) the series truncates earlier and accuracy is poorer than at \\(x=0.1\\)." },
      ],
      finalAnswer: "Optimal truncation (\\( n=0,\\dots,4 \\)) gives \\( F(0.2)\\approx 0.8704 \\), within \\( \\sim0.018 \\) of \\( 0.85211088\\ldots \\); smallest terms at \\( n=4,5 \\).",
      canonicalAnswer: "0.8704",
    },
  },
  {
    id: "am1d-027",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 27",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Suppose \\( H'(x) \\) is continuous on \\( [0,\\infty) \\) with \\( H'(x)\\sim 4 + 6x + 3x^{2} + \\cdots \\) as \\( x\\to 0^{+} \\) and \\( H(0)=7 \\). Find the asymptotic series of \\( H \\) to order \\( x^{3} \\), and confirm that re-differentiating recovers the given series for \\( H' \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integrate then differentiate", "term-by-term", "consistency"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate \\( H' \\) from \\( 0 \\).", workingLatex: "H(x) = H(0) + \\int_0^x H'(t)\\,dt = 7 + \\int_0^x(4 + 6t + 3t^2 + \\cdots)\\,dt.", explanation: "Fundamental theorem of calculus; \\(H'\\) continuous justifies it, and term-by-term integration is always valid." },
        { stepNumber: 2, description: "Integrate each term.", workingLatex: "\\int_0^x 4\\,dt = 4x,\\ \\int_0^x 6t\\,dt = 3x^2,\\ \\int_0^x 3t^2\\,dt = x^3.", explanation: "Power rule on each monomial." },
        { stepNumber: 3, description: "Assemble \\( H \\).", workingLatex: "H(x) \\sim 7 + 4x + 3x^2 + x^3 + \\cdots.", explanation: "The constant \\(7=H(0)\\) is fixed by the initial value." },
        { stepNumber: 4, description: "Identify coefficients.", workingLatex: "\\alpha_0=7,\\ \\alpha_1=4,\\ \\alpha_2=3,\\ \\alpha_3=1.", explanation: "Read off from the assembled series." },
        { stepNumber: 5, description: "Check \\( \\beta_n=(n+1)\\alpha_{n+1} \\).", workingLatex: "(0{+}1)\\alpha_1=4,\\ (1{+}1)\\alpha_2=6,\\ (2{+}1)\\alpha_3=3.", explanation: "Apply the differentiation theorem to \\(H\\)'s coefficients." },
        { stepNumber: 6, description: "Confirm consistency.", workingLatex: "\\beta_0=4,\\ \\beta_1=6,\\ \\beta_2=3 \\Rightarrow H'\\sim 4+6x+3x^2+\\cdots.", explanation: "Exactly the given series for \\(H'\\): integration then differentiation round-trips, since \\(H'\\) satisfies the theorem's hypotheses." },
      ],
      finalAnswer: "\\( H(x) \\sim 7 + 4x + 3x^{2} + x^{3} + \\cdots \\); re-differentiating gives \\( 4 + 6x + 3x^{2} + \\cdots \\), as required.",
      canonicalAnswer: "7 + 4*x + 3*x^2 + x^3",
    },
  },
  {
    id: "am1d-028",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 28",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "By integrating its derivative, find the leading two terms of the small-\\( x \\) expansion of \\( \\displaystyle \\operatorname{Ci}(x)=-\\int_x^{\\infty}\\frac{\\cos t}{t}\\,dt \\), given \\( \\operatorname{Ci}(x)=\\gamma+\\ln x+\\int_0^x\\frac{\\cos t-1}{t}\\,dt \\). Hence give \\( \\operatorname{Ci}(x) \\) to order \\( x^{2} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiate then integrate", "cosine integral", "small-x expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the regularised part.", workingLatex: "\\frac{d}{dx}\\Big[\\operatorname{Ci}(x)-\\ln x\\Big] = \\frac{\\cos x}{x} - \\frac1x = \\frac{\\cos x - 1}{x}.", explanation: "Use \\(\\operatorname{Ci}'(x)=\\cos x/x\\) (from differentiating \\(-\\int_x^\\infty\\)) and subtract \\(1/x\\) from \\(\\ln x\\)." },
        { stepNumber: 2, description: "Expand the regular integrand.", workingLatex: "\\frac{\\cos x - 1}{x} = \\frac{1}{x}\\Big(-\\frac{x^2}{2} + \\frac{x^4}{24} - \\cdots\\Big) = -\\frac{x}{2} + \\frac{x^3}{24} - \\cdots.", explanation: "\\(\\cos x - 1 = -x^2/2 + x^4/24 - \\cdots\\); the \\(1/x\\) lowers each power, leaving a regular series." },
        { stepNumber: 3, description: "Integrate term by term from \\( 0 \\).", workingLatex: "\\int_0^x\\frac{\\cos t - 1}{t}\\,dt = -\\frac{x^2}{4} + \\frac{x^4}{96} - \\cdots.", explanation: "Integrate \\(-t/2 + t^3/24-\\cdots\\); the integral converges since the integrand \\(\\to0\\) at \\(0\\)." },
        { stepNumber: 4, description: "Fix the constant via the given form.", workingLatex: "\\operatorname{Ci}(x) = \\gamma + \\ln x + \\int_0^x\\frac{\\cos t-1}{t}\\,dt.", explanation: "The constant of integration is \\(\\gamma\\), built into the standard representation." },
        { stepNumber: 5, description: "Assemble the expansion.", workingLatex: "\\operatorname{Ci}(x) = \\gamma + \\ln x - \\frac{x^2}{4} + \\cdots.", explanation: "Combine; the leading singular behaviour is \\(\\ln x\\), then a constant \\(\\gamma\\), then the first power term \\(-x^2/4\\)." },
        { stepNumber: 6, description: "Sanity check at \\( x=0.5 \\).", workingLatex: "\\gamma + \\ln 0.5 - \\frac{0.25}{4} \\approx 0.5772 - 0.6931 - 0.0625 = -0.1784,\\ \\text{vs } \\operatorname{Ci}(0.5)\\approx -0.1778.", explanation: "Three terms reproduce \\(\\operatorname{Ci}(0.5)\\) to about three decimals; the next term \\(+x^4/96\\) is tiny." },
      ],
      finalAnswer: "\\( \\operatorname{Ci}(x) = \\gamma + \\ln x - \\dfrac{x^{2}}{4} + \\cdots \\) as \\( x\\to 0^{+} \\).",
      canonicalAnswer: "gamma + log(x) - x^2/4",
    },
  },
  {
    id: "am1d-029",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Construct a smooth \\( f:(0,\\infty)\\to\\mathbb{R} \\) with \\( f(x)=o(1) \\) as \\( x\\to\\infty \\) whose derivative \\( f' \\) is NOT \\( o(1) \\) (indeed unbounded), and use it to argue that an estimate \\( f=o(\\varphi) \\) can never, in general, be differentiated. Contrast with the safe integration result.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["counterexample", "differentiation unsafe", "integration safe"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Propose the function.", workingLatex: "f(x) = \\frac{\\sin(x^3)}{x}.", explanation: "A decaying envelope \\(1/x\\) times a rapidly oscillating factor \\(\\sin(x^3)\\)." },
        { stepNumber: 2, description: "Verify \\( f=o(1) \\).", workingLatex: "|f(x)| \\le \\frac1x \\to 0 \\implies f(x)=o(1).", explanation: "The amplitude decays, so \\(f\\to0\\): it is \\(o(1)\\) (indeed \\(O(x^{-1})\\))." },
        { stepNumber: 3, description: "Differentiate.", workingLatex: "f'(x) = 3x^2\\cos(x^3)\\cdot\\frac1x - \\frac{\\sin(x^3)}{x^2} = 3x\\cos(x^3) - \\frac{\\sin(x^3)}{x^2}.", explanation: "Product/chain rule; the derivative of \\(\\sin(x^3)\\) pulls down a factor \\(3x^2\\)." },
        { stepNumber: 4, description: "Show \\( f' \\) is unbounded.", workingLatex: "\\text{at } x_k=(2\\pi k)^{1/3}: \\ \\cos(x_k^3)=1 \\Rightarrow f'(x_k)\\approx 3x_k\\to\\infty.", explanation: "Along this sequence \\(f'\\to\\infty\\): the derivative is far from \\(o(1)\\); differentiation has \\emph{increased} the order from \\(o(1)\\) to unbounded." },
        { stepNumber: 5, description: "Draw the differentiation moral.", workingLatex: "f=o(\\varphi) \\not\\Rightarrow f'=o(\\varphi') \\ \\text{(or any natural gauge).}", explanation: "Oscillation lets a small function have a large derivative; an asymptotic estimate carries NO automatic information about the derivative." },
        { stepNumber: 6, description: "Contrast with integration.", workingLatex: "\\int_1^x \\frac{\\sin(t^3)}{t}\\,dt = O(1) \\ \\text{(convergent)}, \\quad \\text{whereas } \\int_1^x o(1) = o(x).", explanation: "Integration smooths oscillation (cancellation makes the integral bounded) and always respects the \\(o(x\\varphi)\\) bound — integration is safe, differentiation is not." },
      ],
      finalAnswer: "\\( f(x)=\\dfrac{\\sin(x^{3})}{x}=o(1) \\) but \\( f'(x)=3x\\cos(x^{3})-x^{-2}\\sin(x^{3}) \\) is unbounded; so \\( o \\)-estimates cannot generally be differentiated, though they can always be integrated.",
    },
  },
  {
    id: "am1d-030",
    topicRef: "am1d",
    topicTitle: "Differentiation & integration of asymptotic series 30",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The incomplete Gamma function \\( \\displaystyle \\Gamma(a,x)=\\int_x^{\\infty}t^{a-1}e^{-t}\\,dt \\) satisfies \\( \\partial_x\\Gamma(a,x)=-x^{a-1}e^{-x} \\). Find the first three terms of its large-\\( x \\) expansion by integration by parts, and confirm the series is consistent with that derivative under term-by-term differentiation.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["incomplete gamma", "integration by parts", "term-by-term differentiation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts once.", workingLatex: "\\Gamma(a,x) = \\big[-t^{a-1}e^{-t}\\big]_x^{\\infty} + (a-1)\\int_x^{\\infty}t^{a-2}e^{-t}\\,dt = x^{a-1}e^{-x} + (a-1)\\Gamma(a-1,x).", explanation: "Take \\(u=t^{a-1},\\ dv=e^{-t}dt\\); the boundary term at \\(x\\) is \\(x^{a-1}e^{-x}\\)." },
        { stepNumber: 2, description: "Iterate the recurrence.", workingLatex: "\\Gamma(a,x) = x^{a-1}e^{-x}\\Big[1 + \\frac{a-1}{x} + \\frac{(a-1)(a-2)}{x^2} + \\cdots\\Big].", explanation: "Each application of IBP peels off a boundary term and lowers \\(a\\) by one, generating the descending series." },
        { stepNumber: 3, description: "Write the three-term expansion.", workingLatex: "\\Gamma(a,x) \\sim x^{a-1}e^{-x}\\left(1 + \\frac{a-1}{x} + \\frac{(a-1)(a-2)}{x^2}\\right).", explanation: "Valid as \\(x\\to\\infty\\); remainder \\(O(x^{a-4}e^{-x})\\)." },
        { stepNumber: 4, description: "Differentiate the leading term.", workingLatex: "\\frac{d}{dx}\\big[x^{a-1}e^{-x}\\big] = (a-1)x^{a-2}e^{-x} - x^{a-1}e^{-x}.", explanation: "Product rule on \\(x^{a-1}\\) and \\(e^{-x}\\)." },
        { stepNumber: 5, description: "Differentiate the full three-term series and collect.", workingLatex: "\\frac{d}{dx}\\Gamma(a,x) = -x^{a-1}e^{-x} + \\big[(a-1) - (a-1)\\big]x^{a-2}e^{-x} + \\cdots", explanation: "The \\(x^{a-2}e^{-x}\\) terms cancel: \\((a-1)\\) from differentiating \\(x^{a-1}e^{-x}\\) against \\(-(a-1)\\) from the \\(e^{-x}\\)-derivative of the \\((a-1)/x\\) term." },
        { stepNumber: 6, description: "Confirm all higher terms cancel.", workingLatex: "\\frac{d}{dx}\\Gamma(a,x) = -x^{a-1}e^{-x}.", explanation: "By the same pairwise cancellation at every order, the differentiated series collapses to exactly \\(-x^{a-1}e^{-x}\\), matching the given derivative — term-by-term differentiation is valid here (the function is smooth with its own asymptotic series)." },
      ],
      finalAnswer: "\\( \\Gamma(a,x) \\sim x^{a-1}e^{-x}\\left(1 + \\dfrac{a-1}{x} + \\dfrac{(a-1)(a-2)}{x^{2}} + \\cdots\\right) \\); differentiating term by term gives \\( -x^{a-1}e^{-x} \\), as required.",
      canonicalAnswer: "x^(a-1)*exp(-x)*(1 + (a-1)/x + (a-1)*(a-2)/x^2)",
    },
  },
];
