import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — § am2b
 * Optimal truncation: the least term
 * Topic group: Divergent Series & Optimal Truncation
 *
 * Locating the smallest term of a divergent asymptotic series, truncating one
 * term BEFORE it (the standard convention), and using the resulting partial sum
 * as a numerical estimate of the sum, with the smallest-term magnitude as an
 * error proxy.
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 1, esp.
 * Q9(c),(d) (Stieltjes integrals F, G) and Q10 (exponential integral E_1),
 * with constants/parameters varied. Recurring model series:
 *   E_1(x)   ~ e^{-x} \sum (-1)^n n!/x^{n+1}      term mag n!/x^{n+1}, n* ~ x
 *   F(x)     ~ \sum (-1)^n n! x^n                  term mag n! x^n,     n* ~ 1/x
 *   G(x)     ~ \sum (-1)^n (n+1)! x^n              term mag (n+1)! x^n, n* ~ 1/x
 *   erfc(x)  ~ (e^{-x^2}/(x\sqrt\pi)) \sum (-1)^n (2n-1)!!/(2x^2)^n,    n* ~ x^2
 *
 * All numerical estimates, smallest-term indices and reference values verified
 * with mpmath (quadrature for the integrals, mp.e1 for E_1, mp.erfc for erfc).
 */
export const questions: Question[] = [
  // ── FOUNDATION (6) — core technique in isolation, 2 marks, examStyle false ──
  {
    id: "am2b-001",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Consider the divergent asymptotic series whose general term has magnitude \\( |t_n| = \\dfrac{n!}{x^{\\,n+1}} \\) (the terms of \\( E_1(x) \\)). For \\( x = 8 \\), find the value of \\( n \\) that minimises \\( |t_n| \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "exponential integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of consecutive term magnitudes.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{(n+1)!\\,/\\,x^{\\,n+2}}{n!\\,/\\,x^{\\,n+1}} = \\frac{n+1}{x}.", explanation: "For a factorially divergent series the term magnitudes first decrease then increase; the ratio test on magnitudes locates the turning point." },
        { stepNumber: 2, description: "Terms shrink while the ratio is below 1.", workingLatex: "\\frac{n+1}{x} < 1 \\iff n < x - 1.", explanation: "While each term is smaller than the last the series is still usefully converging; the least term sits where the ratio crosses 1." },
        { stepNumber: 3, description: "Substitute \\( x = 8 \\).", workingLatex: "\\frac{n+1}{8} < 1 \\iff n < 7,\\qquad \\frac{n+1}{8} > 1 \\iff n > 7.", explanation: "The magnitude decreases up to \\( n = 7 \\) and increases beyond it." },
        { stepNumber: 4, description: "Identify the minimising index.", workingLatex: "n^\\ast = 7.", explanation: "At \\( n = 7 \\) the ratio equals exactly \\( 8/8 = 1 \\) only at the next step, so \\( n = 7 \\) is the smallest term: the rule of thumb \\( n^\\ast \\approx x \\)." },
      ],
      finalAnswer: "\\( n^\\ast = 7 \\)",
      canonicalAnswer: "7",
    },
  },
  {
    id: "am2b-002",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "An asymptotic series has term magnitudes \\( |t_n| = n!\\,x^{n} \\) (the terms of the Stieltjes integral \\( F(x) \\)). For \\( x = \\tfrac{1}{5} \\), find the index \\( n \\) of the least term.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "Stieltjes integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the ratio of consecutive magnitudes.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{(n+1)!\\,x^{\\,n+1}}{n!\\,x^{\\,n}} = (n+1)\\,x.", explanation: "Here larger \\( n \\) eventually multiplies in a factorial faster than the geometric factor \\( x^n \\) can damp it." },
        { stepNumber: 2, description: "Require the ratio below 1.", workingLatex: "(n+1)\\,x < 1 \\iff n < \\frac{1}{x} - 1.", explanation: "The least term lies near \\( n \\approx 1/x \\) for this family." },
        { stepNumber: 3, description: "Substitute \\( x = 1/5 \\).", workingLatex: "(n+1)\\cdot\\tfrac{1}{5} < 1 \\iff n < 4.", explanation: "Magnitudes fall up to \\( n = 4 \\); at \\( n = 4 \\) the next ratio is \\( 5\\cdot\\tfrac15 = 1 \\)." },
        { stepNumber: 4, description: "State the minimising index.", workingLatex: "n^\\ast = 4.", explanation: "The smallest term occurs at \\( n = 4 \\) (and \\( n = 5 \\) ties it, since the ratio there is exactly 1)." },
      ],
      finalAnswer: "\\( n^\\ast = 4 \\) (with \\( n = 5 \\) of equal magnitude)",
      canonicalAnswer: "4",
    },
  },
  {
    id: "am2b-003",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State, in words, the standard convention for the optimal truncation of a divergent asymptotic series, and explain which partial sum it tells you to retain.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "convention", "least term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the shape of a divergent asymptotic series.", workingLatex: "|t_0| > |t_1| > \\cdots > |t_{n^\\ast}| < |t_{n^\\ast+1}| < \\cdots", explanation: "The term magnitudes decrease to a minimum at \\( n^\\ast \\) (the least term) and then grow without bound." },
        { stepNumber: 2, description: "Locate the least term.", workingLatex: "n^\\ast = \\arg\\min_n |t_n|.", explanation: "The least term marks where adding further terms starts to hurt rather than help the estimate." },
        { stepNumber: 3, description: "Apply the convention.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{\\,n^\\ast - 1} t_n.", explanation: "By convention optimal truncation keeps all terms up to the one BEFORE the smallest, i.e. it stops just short of \\( n^\\ast \\)." },
        { stepNumber: 4, description: "State the error proxy.", workingLatex: "\\big|\\,\\text{sum} - S_{\\text{opt}}\\big| \\;\\lesssim\\; |t_{n^\\ast}|.", explanation: "The best accuracy obtainable is of the order of the least term retained — the smallest the truncation error can be made for this series." },
      ],
      finalAnswer: "Keep all terms up to the one before the smallest: \\( S_{\\text{opt}} = \\sum_{n=0}^{n^\\ast-1} t_n \\), with error \\( \\sim |t_{n^\\ast}| \\).",
    },
  },
  {
    id: "am2b-004",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the series with term magnitudes \\( |t_n| = \\dfrac{n!}{x^{\\,n+1}} \\), use the rule of thumb to estimate the least-term index \\( n^\\ast \\) for general large \\( x \\), and hence give the order of magnitude of the optimal error.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "Stirling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the consecutive-magnitude ratio to 1.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{n+1}{x} = 1 \\implies n^\\ast \\approx x.", explanation: "The minimum of the term magnitudes sits where consecutive terms are equal in size." },
        { stepNumber: 2, description: "Evaluate the least-term magnitude.", workingLatex: "|t_{n^\\ast}| \\approx \\frac{x!}{x^{\\,x+1}} = \\frac{1}{x}\\cdot\\frac{x!}{x^{\\,x}}.", explanation: "Substitute \\( n^\\ast \\approx x \\) into the term magnitude." },
        { stepNumber: 3, description: "Apply Stirling's formula \\( x! \\sim \\sqrt{2\\pi x}\\,x^x e^{-x} \\).", workingLatex: "|t_{n^\\ast}| \\approx \\frac{1}{x}\\cdot\\sqrt{2\\pi x}\\;e^{-x} = \\sqrt{\\frac{2\\pi}{x}}\\;e^{-x}.", explanation: "The factor \\( x^x \\) cancels, leaving an exponentially small residue — the hallmark of an optimally truncated series." },
        { stepNumber: 4, description: "State the optimal error order.", workingLatex: "\\text{error} \\;\\sim\\; |t_{n^\\ast}| \\;=\\; O\\!\\left(x^{-1/2} e^{-x}\\right).", explanation: "The best accuracy is exponentially small in \\( x \\); this is the precise sense in which the divergent series is still extremely useful." },
      ],
      finalAnswer: "\\( n^\\ast \\approx x \\), optimal error \\( \\sim \\sqrt{2\\pi/x}\\,e^{-x} = O(x^{-1/2}e^{-x}) \\).",
    },
  },
  {
    id: "am2b-005",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "An asymptotic series has term magnitudes \\( |t_n| = (n+1)!\\,x^{n} \\) (the terms of the Stieltjes integral \\( G(x) \\)). For \\( x = \\tfrac{1}{10} \\), find the least-term index \\( n \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "Stieltjes integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the consecutive-magnitude ratio.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{(n+2)!\\,x^{\\,n+1}}{(n+1)!\\,x^{\\,n}} = (n+2)\\,x.", explanation: "The extra \\( (n+1)! \\) shifts the factorial growth compared with the \\( n! x^n \\) family." },
        { stepNumber: 2, description: "Require the ratio below 1.", workingLatex: "(n+2)\\,x < 1 \\iff n < \\frac{1}{x} - 2.", explanation: "Least term near \\( n \\approx 1/x - 2 \\) for this family." },
        { stepNumber: 3, description: "Substitute \\( x = 1/10 \\).", workingLatex: "(n+2)\\cdot\\tfrac{1}{10} < 1 \\iff n < 8.", explanation: "Magnitudes fall up to \\( n = 8 \\); at \\( n = 8 \\) the next ratio is \\( 10\\cdot\\tfrac{1}{10} = 1 \\)." },
        { stepNumber: 4, description: "State the minimising index.", workingLatex: "n^\\ast = 8.", explanation: "The least term is at \\( n = 8 \\), with \\( n = 9 \\) tying it (ratio exactly 1)." },
      ],
      finalAnswer: "\\( n^\\ast = 8 \\) (with \\( n = 9 \\) of equal magnitude)",
      canonicalAnswer: "8",
    },
  },
  {
    id: "am2b-006",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The complementary error function has the asymptotic series with term magnitudes \\( |t_n| = \\dfrac{(2n-1)!!}{(2x^2)^n} \\). For \\( x = 2 \\), find the index \\( n \\) of the least term.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "error function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the consecutive-magnitude ratio.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{(2n+1)!!\\,/\\,(2x^2)^{n+1}}{(2n-1)!!\\,/\\,(2x^2)^{n}} = \\frac{2n+1}{2x^2}.", explanation: "The double factorial advances by the single factor \\( 2n+1 \\) at each step." },
        { stepNumber: 2, description: "Require the ratio below 1.", workingLatex: "\\frac{2n+1}{2x^2} < 1 \\iff n < x^2 - \\tfrac12.", explanation: "Least term near \\( n \\approx x^2 \\) for the erfc family." },
        { stepNumber: 3, description: "Substitute \\( x = 2 \\) so \\( x^2 = 4 \\).", workingLatex: "\\frac{2n+1}{8} < 1 \\iff n < \\tfrac{7}{2} = 3.5.", explanation: "Magnitudes decrease while \\( n \\le 3 \\) and increase once \\( n \\ge 4 \\)." },
        { stepNumber: 4, description: "State the minimising index.", workingLatex: "n^\\ast = 4.", explanation: "The first index with \\( 2n+1 > 2x^2 \\) is \\( n = 4 \\) (ratio \\( 9/8 > 1 \\)), while \\( n = 3 \\) still has ratio \\( 7/8 < 1 \\); the minimum is at \\( n = 4 \\)." },
      ],
      finalAnswer: "\\( n^\\ast = 4 \\)",
      canonicalAnswer: "4",
    },
  },

  // ── STANDARD (12) — sheet-level, 3–4 marks, examStyle true ──
  {
    id: "am2b-007",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 07",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "The exponential integral \\( E_1(x)=\\displaystyle\\int_x^\\infty \\frac{e^{-t}}{t}\\,dt \\) has the asymptotic series \\( E_1(x)\\sim e^{-x}\\sum_{n=0}^\\infty \\frac{(-1)^n n!}{x^{\\,n+1}} \\). For \\( x = 5 \\), locate the least term and use optimal truncation to estimate \\( E_1(5) \\). (Reference value \\( E_1(5)=0.00114830 \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "exponential integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{n+1}{x} = \\frac{n+1}{5}, \\quad <1 \\iff n < 4.", explanation: "The term magnitudes \\( n!/x^{n+1} \\) decrease until \\( n = 4 \\); the least term is at \\( n^\\ast = 4 \\)." },
        { stepNumber: 2, description: "Apply the truncation convention.", workingLatex: "S_{\\text{opt}} = e^{-5}\\sum_{n=0}^{3} \\frac{(-1)^n n!}{5^{\\,n+1}}.", explanation: "Keep all terms up to the one before the least term \\( n^\\ast = 4 \\), i.e. \\( n = 0,1,2,3 \\)." },
        { stepNumber: 3, description: "Evaluate the bracket.", workingLatex: "\\sum_{n=0}^{3}\\frac{(-1)^n n!}{5^{\\,n+1}} = \\frac{1}{5} - \\frac{1}{25} + \\frac{2}{125} - \\frac{6}{625} = 0.16640.", explanation: "Compute term by term: \\( 0.2 - 0.04 + 0.016 - 0.0096 \\)." },
        { stepNumber: 4, description: "Multiply by the prefactor.", workingLatex: "S_{\\text{opt}} = e^{-5}\\times 0.16640 = 0.0067379\\times 0.16640 = 0.0011212.", explanation: "Here \\( e^{-5} = 0.00673795 \\)." },
        { stepNumber: 5, description: "Compare with the reference value.", workingLatex: "\\big|S_{\\text{opt}} - E_1(5)\\big| = |0.0011212 - 0.0011483| = 2.7\\times 10^{-5}.", explanation: "The error is comparable to the least-term magnitude \\( e^{-5}\\cdot 4!/5^5 = 5.2\\times10^{-5} \\), as expected for optimal truncation." },
      ],
      finalAnswer: "\\( E_1(5) \\approx 0.0011212 \\)",
      canonicalAnswer: "0.0011212",
    },
  },
  {
    id: "am2b-008",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 08",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 5 },
    questionText: "Using the same series for the exponential integral, \\( E_1(x)\\sim e^{-x}\\sum_{n\\ge0}\\frac{(-1)^n n!}{x^{n+1}} \\), apply optimal truncation at \\( x = 8 \\) to estimate \\( E_1(8) \\). (Reference value \\( E_1(8)=3.7666\\times10^{-5} \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "exponential integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{n+1}{8} < 1 \\iff n < 7 \\implies n^\\ast = 7.", explanation: "The term magnitudes decrease up to \\( n = 7 \\), where they are smallest." },
        { stepNumber: 2, description: "Truncate one term before the least.", workingLatex: "S_{\\text{opt}} = e^{-8}\\sum_{n=0}^{6}\\frac{(-1)^n n!}{8^{\\,n+1}}.", explanation: "Retain \\( n = 0,\\dots,6 \\)." },
        { stepNumber: 3, description: "Build the bracket numerically.", workingLatex: "\\sum_{n=0}^{6}\\frac{(-1)^n n!}{8^{\\,n+1}} = 0.125 - 0.015625 + 0.003906 - 0.001465 + 0.000732 - 0.000458 + 0.000343.", explanation: "Each term is \\( n!/8^{n+1} \\) with alternating sign." },
        { stepNumber: 4, description: "Sum the bracket.", workingLatex: "= 0.112434.", explanation: "Adding the seven contributions gives \\( 0.112434 \\)." },
        { stepNumber: 5, description: "Apply the prefactor \\( e^{-8} = 3.35463\\times10^{-4} \\).", workingLatex: "S_{\\text{opt}} = 3.35463\\times10^{-4}\\times 0.112434 = 3.7718\\times10^{-5}.", explanation: "Multiply through by \\( e^{-8} \\)." },
        { stepNumber: 6, description: "Check against the reference.", workingLatex: "\\big|3.7718\\times10^{-5} - 3.7666\\times10^{-5}\\big| = 5.2\\times10^{-8}.", explanation: "The error \\( \\sim 5\\times10^{-8} \\) matches the least-term size; doubling \\( x \\) from 4 to 8 has bought several extra correct digits." },
      ],
      finalAnswer: "\\( E_1(8) \\approx 3.7718\\times10^{-5} \\)",
      canonicalAnswer: "0.000037718",
    },
  },
  {
    id: "am2b-009",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 09",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "The Stieltjes integral \\( G(x)=\\displaystyle\\int_0^\\infty \\frac{e^{-t}}{(1+xt)^2}\\,dt \\) has the asymptotic series \\( G(x)\\sim\\sum_{n\\ge0}(-1)^n (n+1)!\\,x^n \\). For \\( x = 0.1 \\), find the least term and use optimal truncation to estimate \\( G(0.1) \\). (Reference value \\( G(0.1)=0.843667 \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = (n+2)\\,x = (n+2)(0.1), \\quad <1 \\iff n < 8.", explanation: "Magnitudes \\( (n+1)!\\,x^n \\) fall until the ratio reaches 1; at \\( x = 0.1 \\) the least term is at \\( n^\\ast = 8 \\) (with \\( n = 9 \\) tied)." },
        { stepNumber: 2, description: "Apply the convention.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{7}(-1)^n (n+1)!\\,(0.1)^n.", explanation: "Keep all terms up to one before the least, i.e. \\( n = 0,\\dots,7 \\)." },
        { stepNumber: 3, description: "List the terms.", workingLatex: "1 - 2(0.1) + 6(0.01) - 24(0.001) + 120(10^{-4}) - 720(10^{-5}) + 5040(10^{-6}) - 40320(10^{-7}).", explanation: "These are \\( (n+1)!\\,x^n \\): \\( 1,\\,0.2,\\,0.06,\\,0.024,\\,0.012,\\,0.0072,\\,0.00504,\\,0.004032 \\)." },
        { stepNumber: 4, description: "Sum with alternating signs.", workingLatex: "= 1 - 0.2 + 0.06 - 0.024 + 0.012 - 0.0072 + 0.00504 - 0.004032 = 0.841808.", explanation: "Accumulate the partial sums to obtain \\( 0.841808 \\)." },
        { stepNumber: 5, description: "Compare with the reference value.", workingLatex: "\\big|0.841808 - 0.843667\\big| = 1.9\\times10^{-3}.", explanation: "The error sits at the level of the least term \\( 9!\\,x^8/8! = 3.6\\times10^{-3} \\), confirming optimal accuracy near three significant figures." },
      ],
      finalAnswer: "\\( G(0.1) \\approx 0.8418 \\)",
      canonicalAnswer: "0.841808",
    },
  },
  {
    id: "am2b-010",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 10",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 3 },
    questionText: "The Stieltjes integral \\( F(x)=\\displaystyle\\int_0^\\infty \\frac{e^{-t}}{1+xt}\\,dt \\) has the asymptotic series \\( F(x)\\sim\\sum_{n\\ge0}(-1)^n n!\\,x^n \\). For \\( x = 0.1 \\), apply optimal truncation to estimate \\( F(0.1) \\). (Reference value \\( F(0.1)=0.915633 \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = (n+1)\\,x = (n+1)(0.1), \\quad <1 \\iff n < 9.", explanation: "Magnitudes \\( n!\\,x^n \\) decrease until the ratio hits 1; at \\( x = 0.1 \\) the least term is at \\( n^\\ast = 9 \\) (with \\( n = 10 \\) tied)." },
        { stepNumber: 2, description: "Truncate one term before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{8}(-1)^n n!\\,(0.1)^n.", explanation: "Retain \\( n = 0,\\dots,8 \\)." },
        { stepNumber: 3, description: "List the term magnitudes \\( n!\\,(0.1)^n \\).", workingLatex: "1,\\;0.1,\\;0.02,\\;0.006,\\;0.0024,\\;0.0012,\\;0.00072,\\;0.000504,\\;0.0004032.", explanation: "Factorial growth is being outrun by \\( 0.1^n \\) until \\( n = 9 \\)." },
        { stepNumber: 4, description: "Sum with alternating signs.", workingLatex: "1 - 0.1 + 0.02 - 0.006 + 0.0024 - 0.0012 + 0.00072 - 0.000504 + 0.0004032 = 0.915819.", explanation: "Accumulate the alternating partial sums." },
        { stepNumber: 5, description: "Compare with the reference value.", workingLatex: "\\big|0.915819 - 0.915633\\big| = 1.9\\times10^{-4}.", explanation: "The error matches the least-term magnitude \\( 9!\\,(0.1)^9 = 3.6\\times10^{-4} \\), so the estimate is good to about three decimals." },
      ],
      finalAnswer: "\\( F(0.1) \\approx 0.9158 \\)",
      canonicalAnswer: "0.915819",
    },
  },
  {
    id: "am2b-011",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 11",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "The complementary error function satisfies \\( \\operatorname{erfc}(x)\\sim\\dfrac{e^{-x^2}}{x\\sqrt\\pi}\\sum_{n\\ge0}\\dfrac{(-1)^n (2n-1)!!}{(2x^2)^n} \\). For \\( x = 2.5 \\), locate the least term and use optimal truncation to estimate \\( \\operatorname{erfc}(2.5) \\). (Reference value \\( \\operatorname{erfc}(2.5)=4.0695\\times10^{-4} \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "error function", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{2n+1}{2x^2} = \\frac{2n+1}{12.5}, \\quad <1 \\iff n < 5.75.", explanation: "With \\( x^2 = 6.25 \\) the magnitudes decrease while \\( 2n+1 < 12.5 \\); the least term is at \\( n^\\ast = 6 \\)." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\frac{e^{-x^2}}{x\\sqrt\\pi}\\sum_{n=0}^{5}\\frac{(-1)^n(2n-1)!!}{(2x^2)^n}.", explanation: "Retain \\( n = 0,\\dots,5 \\); note \\( (2\\cdot0-1)!! = 1 \\)." },
        { stepNumber: 3, description: "Evaluate the bracket with \\( 2x^2 = 12.5 \\).", workingLatex: "1 - \\frac{1}{12.5} + \\frac{3}{12.5^2} - \\frac{15}{12.5^3} + \\frac{105}{12.5^4} - \\frac{945}{12.5^5} = 0.932724.", explanation: "Successive double factorials are \\( 1,1,3,15,105,945 \\)." },
        { stepNumber: 4, description: "Compute the prefactor.", workingLatex: "\\frac{e^{-6.25}}{2.5\\sqrt\\pi} = \\frac{0.00193045}{4.43113} = 4.35658\\times10^{-4}.", explanation: "Here \\( e^{-6.25} = 1.93045\\times10^{-3} \\) and \\( 2.5\\sqrt\\pi = 4.43113 \\)." },
        { stepNumber: 5, description: "Combine and compare.", workingLatex: "S_{\\text{opt}} = 4.35658\\times10^{-4}\\times 0.932724 = 4.0635\\times10^{-4}.", explanation: "Against the reference \\( 4.0695\\times10^{-4} \\) the error is \\( 6\\times10^{-7} \\), at the level of the least term." },
      ],
      finalAnswer: "\\( \\operatorname{erfc}(2.5) \\approx 4.064\\times10^{-4} \\)",
      canonicalAnswer: "0.00040635",
    },
  },
  {
    id: "am2b-012",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the exponential-integral series with term magnitudes \\( e^{-x}\\,n!/x^{n+1} \\), the smallest term at \\( x = 6 \\) occurs at \\( n^\\ast = 5 \\). Estimate the smallest achievable truncation error, and state how many correct significant figures this implies for \\( E_1(6) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "error estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the least-term magnitude.", workingLatex: "|t_{n^\\ast}| = e^{-6}\\,\\frac{5!}{6^{6}} = e^{-6}\\,\\frac{120}{46656}.", explanation: "The optimal error is of the order of the least term retained-but-discarded, namely \\( n^\\ast = 5 \\)." },
        { stepNumber: 2, description: "Simplify the bracket.", workingLatex: "\\frac{120}{46656} = 2.5720\\times10^{-3}.", explanation: "Divide \\( 120 \\) by \\( 6^6 = 46656 \\)." },
        { stepNumber: 3, description: "Multiply by \\( e^{-6} = 2.4788\\times10^{-3} \\).", workingLatex: "|t_{n^\\ast}| = 2.4788\\times10^{-3}\\times 2.5720\\times10^{-3} = 6.4\\times10^{-6}.", explanation: "So the truncation error cannot be made smaller than about \\( 6\\times10^{-6} \\)." },
        { stepNumber: 4, description: "Compare with the size of \\( E_1(6) \\).", workingLatex: "E_1(6)\\approx 3.60\\times10^{-4}, \\quad \\frac{6.4\\times10^{-6}}{3.60\\times10^{-4}} \\approx 1.8\\times10^{-2}.", explanation: "The relative error is around \\( 2\\% \\), so roughly two significant figures are reliable." },
      ],
      finalAnswer: "Optimal error \\( \\sim 6\\times10^{-6} \\); about 2 significant figures of \\( E_1(6) \\).",
    },
  },
  {
    id: "am2b-013",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 13",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 3 },
    questionText: "Apply optimal truncation to the Stieltjes series \\( F(x)\\sim\\sum_{n\\ge0}(-1)^n n!\\,x^n \\) at \\( x = 0.2 \\). Find the least-term index, give the truncated estimate of \\( F(0.2) \\), and quote the resulting error. (Reference value \\( F(0.2)=0.852111 \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "(n+1)\\,x = (n+1)(0.2) < 1 \\iff n < 4 \\implies n^\\ast = 5.", explanation: "Magnitudes fall while \\( n+1 < 5 \\); the minimum sits at \\( n^\\ast = 5 \\), since the ratio at \\( n=4 \\) is \\( 5\\cdot0.2 = 1 \\) (so \\( n=4 \\) and \\( n=5 \\) tie at the bottom)." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{4}(-1)^n n!\\,(0.2)^n.", explanation: "Retain \\( n = 0,\\dots,4 \\)." },
        { stepNumber: 3, description: "List the term magnitudes \\( n!\\,(0.2)^n \\).", workingLatex: "1,\\;0.2,\\;0.08,\\;0.048,\\;0.0384.", explanation: "Factorials \\( 1,1,2,6,24 \\) times \\( 0.2^n \\)." },
        { stepNumber: 4, description: "Sum with alternating signs.", workingLatex: "1 - 0.2 + 0.08 - 0.048 + 0.0384 = 0.8704.", explanation: "Accumulate the alternating partial sums." },
        { stepNumber: 5, description: "Quote the error.", workingLatex: "\\big|0.8704 - 0.852111\\big| = 1.8\\times10^{-2}.", explanation: "At \\( x = 0.2 \\) the least term is already \\( \\sim 0.038 \\), so optimal truncation only secures about one decimal place — divergent series stop being useful once \\( x \\) is not small." },
      ],
      finalAnswer: "\\( n^\\ast = 5 \\), \\( F(0.2)\\approx 0.870 \\), error \\( \\approx 1.8\\times10^{-2} \\).",
      canonicalAnswer: "0.8704",
    },
  },
  {
    id: "am2b-014",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 14",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "Use optimal truncation on the exponential-integral series at \\( x = 4 \\) to estimate \\( E_1(4) \\), and state the error. (Reference value \\( E_1(4)=3.7794\\times10^{-3} \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "exponential integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{n+1}{4} < 1 \\iff n < 3 \\implies n^\\ast = 3.", explanation: "Magnitudes \\( n!/4^{n+1} \\) decrease up to \\( n = 3 \\) (with \\( n = 3 \\) the least; ratio at \\( n=3 \\) is \\( 4/4 = 1 \\), so \\( n=3 \\) ties \\( n=2 \\) at the floor — take \\( n^\\ast = 3 \\))." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = e^{-4}\\sum_{n=0}^{2}\\frac{(-1)^n n!}{4^{\\,n+1}}.", explanation: "Retain \\( n = 0,1,2 \\)." },
        { stepNumber: 3, description: "Evaluate the bracket.", workingLatex: "\\frac{1}{4} - \\frac{1}{16} + \\frac{2}{64} = 0.25 - 0.0625 + 0.03125 = 0.21875.", explanation: "Terms \\( n!/4^{n+1} \\) with alternating signs." },
        { stepNumber: 4, description: "Apply the prefactor \\( e^{-4} = 1.83156\\times10^{-2} \\).", workingLatex: "S_{\\text{opt}} = 1.83156\\times10^{-2}\\times 0.21875 = 4.0065\\times10^{-3}.", explanation: "Multiply through by \\( e^{-4} \\)." },
        { stepNumber: 5, description: "State the error.", workingLatex: "\\big|4.0065\\times10^{-3} - 3.7794\\times10^{-3}\\big| = 2.3\\times10^{-4}.", explanation: "At \\( x = 4 \\) only about one to two significant figures are reliable; the error matches the least term \\( e^{-4}\\cdot 3!/4^4 = 4.3\\times10^{-4} \\)." },
      ],
      finalAnswer: "\\( E_1(4)\\approx 4.01\\times10^{-3} \\), error \\( \\approx 2.3\\times10^{-4} \\).",
      canonicalAnswer: "0.0040065",
    },
  },
  {
    id: "am2b-015",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Two asymptotic series have term magnitudes \\( |a_n| = n!/x^{n+1} \\) and \\( |b_n| = (n+1)!\\,y^n \\). Find general formulae for the least-term index of each (the integer where the magnitude is smallest), and explain why one favours large \\( x \\) and the other small \\( y \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "least term", "ratio test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Ratio for the first family.", workingLatex: "\\frac{|a_{n+1}|}{|a_n|} = \\frac{n+1}{x}.", explanation: "Magnitudes shrink while \\( n+1 < x \\), i.e. while \\( n \\) is below \\( x-1 \\)." },
        { stepNumber: 2, description: "Least-term index, first family.", workingLatex: "n^\\ast_a = \\lfloor x \\rfloor \\;\\; (\\text{the first } n \\text{ with } n+1 > x).", explanation: "The minimum sits at \\( n \\approx x \\); large \\( x \\) pushes the minimum to a high index where the term is exponentially small." },
        { stepNumber: 3, description: "Ratio for the second family.", workingLatex: "\\frac{|b_{n+1}|}{|b_n|} = (n+2)\\,y.", explanation: "Magnitudes shrink while \\( (n+2)y < 1 \\)." },
        { stepNumber: 4, description: "Least-term index, second family.", workingLatex: "n^\\ast_b = \\Big\\lfloor \\tfrac{1}{y} - 2 \\Big\\rfloor \\;\\; (\\text{first } n \\text{ with } (n+2)y > 1).", explanation: "The minimum sits at \\( n \\approx 1/y \\); small \\( y \\) pushes the minimum to a high index." },
        { stepNumber: 5, description: "Interpret the asymmetry.", workingLatex: "n^\\ast_a \\sim x \\to\\infty, \\qquad n^\\ast_b \\sim 1/y \\to\\infty.", explanation: "In family \\( a \\) the geometric factor is \\( x^{-n} \\), so large \\( x \\) delays the factorial blow-up; in family \\( b \\) it is \\( y^{n} \\), so small \\( y \\) does the same. Either way the optimal error is exponentially small in the large parameter." },
      ],
      finalAnswer: "\\( n^\\ast_a = \\lfloor x\\rfloor \\) (favours large \\( x \\)); \\( n^\\ast_b = \\lfloor 1/y - 2\\rfloor \\) (favours small \\( y \\)).",
    },
  },
  {
    id: "am2b-016",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 16",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "Apply optimal truncation to the Stieltjes series \\( G(x)\\sim\\sum_{n\\ge0}(-1)^n(n+1)!\\,x^n \\) at \\( x = 0.2 \\) to estimate \\( G(0.2) \\), and quote the error. (Reference value \\( G(0.2)=0.739446 \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "(n+2)\\,x = (n+2)(0.2) < 1 \\iff n < 3 \\implies n^\\ast = 3.", explanation: "Magnitudes \\( (n+1)!\\,x^n \\) fall while \\( n+2 < 5 \\); at \\( n = 3 \\) the ratio is \\( 5\\cdot0.2 = 1 \\), so \\( n = 3 \\) and \\( n = 4 \\) tie at the floor — take \\( n^\\ast = 3 \\)." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{2}(-1)^n(n+1)!\\,(0.2)^n.", explanation: "Retain \\( n = 0,1,2 \\)." },
        { stepNumber: 3, description: "List the terms.", workingLatex: "1,\\; 2(0.2)=0.4,\\; 6(0.04)=0.24.", explanation: "Coefficients are \\( (n+1)! = 1,2,6 \\) times \\( 0.2^n \\)." },
        { stepNumber: 4, description: "Sum with alternating signs.", workingLatex: "1 - 0.4 + 0.24 = 0.84.", explanation: "Accumulate the alternating partial sum." },
        { stepNumber: 5, description: "Quote the error.", workingLatex: "\\big|0.84 - 0.739446\\big| = 1.0\\times10^{-1}.", explanation: "At \\( x = 0.2 \\) the least term is \\( \\sim 0.19 \\), so the estimate is only correct to about one figure; \\( G \\) diverges faster than \\( F \\) because of the extra \\( (n+1) \\)." },
      ],
      finalAnswer: "\\( n^\\ast = 3 \\), \\( G(0.2)\\approx 0.84 \\), error \\( \\approx 0.10 \\).",
      canonicalAnswer: "0.84",
    },
  },
  {
    id: "am2b-017",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 17",
    difficulty: "Standard",
    answerType: "numeric",
    answerMeta: { requiredDp: 6 },
    questionText: "Apply optimal truncation to the exponential-integral series at \\( x = 10 \\) to estimate \\( E_1(10) \\). (Reference value \\( E_1(10)=4.15697\\times10^{-6} \\).)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "exponential integral", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{n+1}{10} < 1 \\iff n < 9 \\implies n^\\ast = 9.", explanation: "Magnitudes \\( n!/10^{n+1} \\) decrease up to \\( n = 9 \\); the rule \\( n^\\ast\\approx x \\) gives \\( n^\\ast = 9 \\) (with \\( n = 10 \\) tied)." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = e^{-10}\\sum_{n=0}^{8}\\frac{(-1)^n n!}{10^{\\,n+1}}.", explanation: "Retain \\( n = 0,\\dots,8 \\)." },
        { stepNumber: 3, description: "Build the bracket.", workingLatex: "0.1 - 0.01 + 0.002 - 0.0006 + 0.00024 - 0.00012 + 0.000072 - 0.0000504 + 0.00004032.", explanation: "Each term is \\( n!/10^{n+1} \\) with alternating sign." },
        { stepNumber: 4, description: "Sum the bracket.", workingLatex: "= 0.0915723.", explanation: "Accumulating the nine contributions gives \\( 0.0915723 \\)." },
        { stepNumber: 5, description: "Apply the prefactor \\( e^{-10} = 4.53999\\times10^{-5} \\).", workingLatex: "S_{\\text{opt}} = 4.53999\\times10^{-5}\\times 0.0915723 = 4.15730\\times10^{-6}.", explanation: "Multiply through by \\( e^{-10} \\)." },
        { stepNumber: 6, description: "Compare with the reference.", workingLatex: "\\big|4.15730\\times10^{-6} - 4.15697\\times10^{-6}\\big| = 3.3\\times10^{-10}.", explanation: "Five to six figures are reliable; the error matches the least term \\( e^{-10}\\cdot 9!/10^{10} \\sim 1.6\\times10^{-9} \\)." },
      ],
      finalAnswer: "\\( E_1(10)\\approx 4.15730\\times10^{-6} \\)",
      canonicalAnswer: "0.00000415730",
    },
  },
  {
    id: "am2b-018",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the exponential-integral series with least term near \\( n^\\ast\\approx x \\), use Stirling's formula to show that the optimal truncation error behaves like \\( \\sqrt{2\\pi/x}\\;e^{-x} \\), and confirm this is \\( o(x^{-M}) \\) as \\( x\\to\\infty \\) for every integer \\( M \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stirling", "beyond all orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the least-term magnitude.", workingLatex: "|t_{n^\\ast}| = e^{-x}\\,\\frac{n^\\ast!}{x^{\\,n^\\ast+1}}, \\qquad n^\\ast \\approx x.", explanation: "The optimal error is controlled by the smallest term, evaluated at \\( n^\\ast \\approx x \\)." },
        { stepNumber: 2, description: "Substitute \\( n^\\ast = x \\).", workingLatex: "|t_{n^\\ast}| \\approx e^{-x}\\,\\frac{x!}{x^{\\,x+1}} = \\frac{e^{-x}}{x}\\cdot\\frac{x!}{x^{\\,x}}.", explanation: "Isolate the ratio \\( x!/x^x \\), which Stirling controls." },
        { stepNumber: 3, description: "Apply Stirling \\( x! \\sim \\sqrt{2\\pi x}\\,x^x e^{-x} \\).", workingLatex: "\\frac{x!}{x^{\\,x}} \\sim \\sqrt{2\\pi x}\\;e^{-x}.", explanation: "The dominant \\( x^x \\) cancels, leaving an exponentially small factor." },
        { stepNumber: 4, description: "Combine.", workingLatex: "|t_{n^\\ast}| \\sim \\frac{e^{-x}}{x}\\,\\sqrt{2\\pi x}\\;e^{-x} \\;=\\; \\sqrt{\\frac{2\\pi}{x}}\\;e^{-2x}.", explanation: "Including the overall \\( e^{-x} \\) prefactor of \\( E_1 \\) gives \\( e^{-2x} \\); stripping the prefactor (the error relative to \\( e^{-x} \\)) leaves \\( \\sqrt{2\\pi/x}\\,e^{-x} \\)." },
        { stepNumber: 5, description: "Show it beats every power.", workingLatex: "\\lim_{x\\to\\infty} \\frac{\\sqrt{2\\pi/x}\\;e^{-x}}{x^{-M}} = \\sqrt{2\\pi}\\,\\lim_{x\\to\\infty} x^{M-1/2}e^{-x} = 0.", explanation: "An exponential beats any fixed power, so the optimal error is \\( o(x^{-M}) \\) for all \\( M \\): it lies beyond all orders of the asymptotic series." },
      ],
      finalAnswer: "Optimal error \\( \\sim \\sqrt{2\\pi/x}\\,e^{-x} = o(x^{-M}) \\) for every \\( M \\).",
    },
  },

  // ── CHALLENGE (12) — synoptic / multi-step / starred, 5+ marks ──
  {
    id: "am2b-019",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 19",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 6 },
    questionText: "Starting from \\( G(x)=\\displaystyle\\int_0^\\infty \\frac{e^{-t}}{(1+xt)^2}\\,dt \\), derive its asymptotic series, locate the least term at \\( x = 0.1 \\), and use optimal truncation to estimate \\( G(0.1) \\). Compare with the exact value \\( G(0.1)=0.843667 \\) and comment on the accuracy. (This is example-sheet Q9(c) with the convention spelled out.)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "Watson", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the integrand geometrically (formally).", workingLatex: "\\frac{1}{(1+xt)^2} = \\sum_{n=0}^\\infty (-1)^n (n+1)\\,(xt)^n.", explanation: "This is the binomial series for \\( (1+u)^{-2} \\); it converges only for \\( |xt| < 1 \\), so substituting under the integral is formal and yields an asymptotic, not convergent, series." },
        { stepNumber: 2, description: "Integrate term by term using \\( \\int_0^\\infty t^n e^{-t}\\,dt = n! \\).", workingLatex: "G(x) \\sim \\sum_{n=0}^\\infty (-1)^n (n+1)\\,x^n\\, n! = \\sum_{n=0}^\\infty (-1)^n (n+1)!\\,x^n.", explanation: "Each moment of \\( e^{-t} \\) is a factorial; the \\( (n+1) \\) merges with \\( n! \\) to give \\( (n+1)! \\)." },
        { stepNumber: 3, description: "Locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = (n+2)\\,x = (n+2)(0.1) < 1 \\iff n < 8 \\implies n^\\ast = 8.", explanation: "The least term sits at \\( n^\\ast = 8 \\) (with \\( n = 9 \\) tied), since at \\( n = 8 \\) the ratio is \\( 10\\cdot0.1 = 1 \\)." },
        { stepNumber: 4, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{7}(-1)^n (n+1)!\\,(0.1)^n.", explanation: "Retain \\( n = 0,\\dots,7 \\)." },
        { stepNumber: 5, description: "Evaluate the partial sum.", workingLatex: "1 - 0.2 + 0.06 - 0.024 + 0.012 - 0.0072 + 0.00504 - 0.004032 = 0.841808.", explanation: "Term magnitudes \\( (n+1)!\\,(0.1)^n \\) are \\( 1,0.2,0.06,0.024,0.012,0.0072,0.00504,0.004032 \\)." },
        { stepNumber: 6, description: "Compare and comment.", workingLatex: "\\big|0.841808 - 0.843667\\big| = 1.9\\times10^{-3} \\approx |t_{8}| = 3.6\\times10^{-3}.", explanation: "The error is bounded by the least term and is around \\( 0.2\\% \\): optimal truncation extracts about three correct figures from a wildly divergent series." },
      ],
      finalAnswer: "\\( G(0.1)\\approx 0.841808 \\) (error \\( \\approx 1.9\\times10^{-3} \\)).",
      canonicalAnswer: "0.841808",
    },
  },
  // REVIEW: relation F' = G between the two series is an exact identity argued by differentiation under the integral; verified that G's series equals the term-by-term derivative of F's series, but the structural claim is analytic, not a single numeric check.
  {
    id: "am2b-020",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The Stieltjes integrals satisfy \\( F'(x)=G(x) \\), with series \\( F\\sim\\sum(-1)^n n!\\,x^n \\) and \\( G\\sim\\sum(-1)^n(n+1)!\\,x^n \\). Show that the least-term index of \\( G \\) is one less than that of \\( F \\) for the same \\( x \\), and explain why differentiating an asymptotic series shifts the optimal truncation point.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "differentiation of series", "Stieltjes integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Least term of \\( F \\).", workingLatex: "\\frac{|F_{n+1}|}{|F_n|} = (n+1)\\,x < 1 \\iff n < \\tfrac1x - 1 \\implies n^\\ast_F = \\Big\\lceil \\tfrac1x \\Big\\rceil - 1.", explanation: "For \\( F \\) the magnitudes are \\( n!\\,x^n \\); the minimum is near \\( n \\approx 1/x - 1 \\)." },
        { stepNumber: 2, description: "Least term of \\( G \\).", workingLatex: "\\frac{|G_{n+1}|}{|G_n|} = (n+2)\\,x < 1 \\iff n < \\tfrac1x - 2 \\implies n^\\ast_G = \\Big\\lceil \\tfrac1x \\Big\\rceil - 2.", explanation: "For \\( G \\) the magnitudes are \\( (n+1)!\\,x^n \\); the minimum is near \\( n \\approx 1/x - 2 \\)." },
        { stepNumber: 3, description: "Compare the two indices.", workingLatex: "n^\\ast_G = n^\\ast_F - 1.", explanation: "The extra factorial factor in \\( G \\) makes each term larger relative to \\( F \\), so the magnitudes turn upward one step sooner." },
        { stepNumber: 4, description: "Connect to differentiation.", workingLatex: "F(x) \\sim \\sum_{n\\ge0} (-1)^n n!\\,x^n \\implies F'(x) \\sim \\sum_{n\\ge1} (-1)^n n!\\,n\\,x^{n-1} = \\sum_{m\\ge0}(-1)^{m+1}(m+1)!\\,x^m.", explanation: "Term-by-term differentiation lowers each power by one and multiplies by the old exponent; re-indexing reproduces (up to sign) the \\( G \\)-series, confirming \\( F' = G \\) at the level of series." },
        { stepNumber: 5, description: "Interpret the shift.", workingLatex: "\\text{coefficient } n! \\;\\longmapsto\\; (n+1)!: \\text{ faster growth} \\implies \\text{earlier least term}.", explanation: "Differentiation multiplies the \\( n \\)-th coefficient by roughly \\( n \\), accelerating the factorial divergence, so the optimal truncation point — and the best achievable accuracy — both retreat by one term." },
      ],
      finalAnswer: "\\( n^\\ast_G = n^\\ast_F - 1 \\); differentiation multiplies coefficients by \\( \\sim n \\), hastening divergence and moving the least term earlier.",
    },
  },
  {
    id: "am2b-021",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 21",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "Derive the asymptotic series of \\( E_1(x)=\\int_x^\\infty t^{-1}e^{-t}\\,dt \\) by repeated integration by parts, then for \\( x = 6 \\) locate the least term and use optimal truncation to estimate \\( E_1(6) \\). Compare with \\( E_1(6)=3.60082\\times10^{-4} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "integration by parts", "exponential integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts once.", workingLatex: "E_1(x) = \\left[-\\frac{e^{-t}}{t}\\right]_x^\\infty - \\int_x^\\infty \\frac{e^{-t}}{t^2}\\,dt = \\frac{e^{-x}}{x} - \\int_x^\\infty \\frac{e^{-t}}{t^2}\\,dt.", explanation: "Take \\( u = 1/t,\\; dv = e^{-t}\\,dt \\); the boundary term at infinity vanishes." },
        { stepNumber: 2, description: "Iterate the integration by parts.", workingLatex: "E_1(x) = e^{-x}\\!\\left(\\frac1x - \\frac{1}{x^2} + \\frac{2!}{x^3} - \\frac{3!}{x^4} + \\cdots\\right).", explanation: "Each step pulls out a boundary term \\( e^{-x}(-1)^n n!/x^{n+1} \\) and leaves a higher-order integral; the procedure never terminates, giving a divergent series." },
        { stepNumber: 3, description: "Write the general term and locate the least term.", workingLatex: "|t_n| = e^{-x}\\frac{n!}{x^{n+1}}, \\quad \\frac{n+1}{6} < 1 \\iff n < 5 \\implies n^\\ast = 5.", explanation: "At \\( x = 6 \\) the magnitudes shrink up to \\( n = 5 \\)." },
        { stepNumber: 4, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = e^{-6}\\sum_{n=0}^{4}\\frac{(-1)^n n!}{6^{\\,n+1}}.", explanation: "Retain \\( n = 0,\\dots,4 \\)." },
        { stepNumber: 5, description: "Evaluate the bracket.", workingLatex: "\\frac16 - \\frac{1}{36} + \\frac{2}{216} - \\frac{6}{1296} + \\frac{24}{7776} = 0.145576.", explanation: "Compute \\( 0.166667 - 0.027778 + 0.009259 - 0.004630 + 0.003086 \\)." },
        { stepNumber: 6, description: "Apply the prefactor and compare.", workingLatex: "S_{\\text{opt}} = e^{-6}\\times 0.145576 = 2.47875\\times10^{-3}\\times 0.145576 = 3.6088\\times10^{-4}.", explanation: "Against \\( E_1(6) = 3.60082\\times10^{-4} \\) the error is \\( \\sim 8\\times10^{-7} \\), at the least-term level — three to four reliable figures." },
      ],
      finalAnswer: "\\( E_1(6)\\approx 3.609\\times10^{-4} \\) (error \\( \\sim 8\\times10^{-7} \\)).",
      canonicalAnswer: "0.00036088",
    },
  },
  {
    id: "am2b-022",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 22",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 8 },
    questionText: "Apply optimal truncation to the complementary error function series at \\( x = 3 \\) to estimate \\( \\operatorname{erfc}(3) \\), and verify the error matches the least-term magnitude. (Reference value \\( \\operatorname{erfc}(3)=2.209050\\times10^{-5} \\).)",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "error function", "numerical estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "\\frac{2n+1}{2x^2} = \\frac{2n+1}{18} < 1 \\iff n < 8.5 \\implies n^\\ast = 9.", explanation: "With \\( x^2 = 9 \\), the magnitudes fall while \\( 2n+1 < 18 \\); the least term is at \\( n^\\ast = 9 \\) (rule \\( n^\\ast\\approx x^2 \\))." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\frac{e^{-9}}{3\\sqrt\\pi}\\sum_{n=0}^{8}\\frac{(-1)^n(2n-1)!!}{18^{\\,n}}.", explanation: "Retain \\( n = 0,\\dots,8 \\); \\( 2x^2 = 18 \\)." },
        { stepNumber: 3, description: "Evaluate the bracket.", workingLatex: "\\sum_{n=0}^{8}\\frac{(-1)^n(2n-1)!!}{18^{\\,n}} = 0.951901.", explanation: "Double factorials \\( 1,1,3,15,105,945,10395,135135,2027025 \\) over powers of 18, alternating; the sum settles at \\( 0.951901 \\)." },
        { stepNumber: 4, description: "Compute the prefactor.", workingLatex: "\\frac{e^{-9}}{3\\sqrt\\pi} = \\frac{1.234098\\times10^{-4}}{5.317361} = 2.320884\\times10^{-5}.", explanation: "Here \\( e^{-9} = 1.234098\\times10^{-4} \\) and \\( 3\\sqrt\\pi = 5.317361 \\)." },
        { stepNumber: 5, description: "Combine and compare.", workingLatex: "S_{\\text{opt}} = 2.320884\\times10^{-5}\\times 0.951901 = 2.20925\\times10^{-5}; \\quad \\text{error} \\approx 2\\times10^{-9}.", explanation: "Against \\( 2.20905\\times10^{-5} \\) the error is about \\( 2\\times10^{-9} \\), comparable to the least term times the prefactor — five to six reliable significant figures." },
      ],
      finalAnswer: "\\( \\operatorname{erfc}(3)\\approx 2.20925\\times10^{-5} \\) (error \\( \\sim 2\\times10^{-9} \\)).",
      canonicalAnswer: "0.0000220925",
    },
  },
  {
    id: "am2b-023",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the case \\( \\rho(t)=e^{-t} \\), the Stieltjes integral gives \\( F(x)=\\sum_{n=0}^{N}(-1)^n n!\\,x^n + \\mathrm{Err}_N \\) with bound \\( |\\mathrm{Err}_N|\\le (N+1)!\\,x^{N+1} \\). Defining optimal truncation by \\( N+1=\\lfloor x^{-1}\\rfloor \\), use Stirling's formula to show the optimal error bound is \\( O\\big(x^{-1/2}e^{-1/x}\\big) \\) and hence \\( o(x^M) \\) as \\( x\\to0^+ \\) for every integer \\( M \\). (Example-sheet Q9(d), varied.)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stirling", "error bound", "beyond all orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the optimal-error bound.", workingLatex: "|\\mathrm{Err}_N| \\le (N+1)!\\,x^{N+1}, \\qquad N+1 = \\lfloor x^{-1}\\rfloor =: K.", explanation: "By the convention we stop one before the least term; the bound is the magnitude of the first omitted term." },
        { stepNumber: 2, description: "Substitute \\( N+1 = K \\approx 1/x \\).", workingLatex: "|\\mathrm{Err}| \\le K!\\,x^{K}, \\qquad K \\approx \\frac1x.", explanation: "Replace the factorial index by the optimal value \\( K = \\lfloor 1/x\\rfloor \\)." },
        { stepNumber: 3, description: "Apply Stirling \\( K! \\sim \\sqrt{2\\pi K}\\,K^K e^{-K} \\).", workingLatex: "|\\mathrm{Err}| \\lesssim \\sqrt{2\\pi K}\\,K^K e^{-K}\\,x^{K} = \\sqrt{2\\pi K}\\,(Kx)^K e^{-K}.", explanation: "Group the \\( x^K \\) with \\( K^K \\)." },
        { stepNumber: 4, description: "Use \\( Kx \\approx 1 \\).", workingLatex: "(Kx)^K \\approx 1 \\implies |\\mathrm{Err}| \\lesssim \\sqrt{2\\pi K}\\;e^{-K} = \\sqrt{\\frac{2\\pi}{x}}\\;e^{-1/x}.", explanation: "Since \\( K\\approx 1/x \\), \\( (Kx)^K\\to1 \\) and \\( \\sqrt{2\\pi K} = \\sqrt{2\\pi/x} \\), \\( e^{-K} = e^{-1/x} \\)." },
        { stepNumber: 5, description: "State the order.", workingLatex: "|\\mathrm{Err}| = O\\!\\left(x^{-1/2}e^{-1/x}\\right) \\quad (x\\to0^+).", explanation: "This is the optimal (least-term) error bound." },
        { stepNumber: 6, description: "Show it beats every power.", workingLatex: "\\frac{x^{-1/2}e^{-1/x}}{x^{M}} = x^{-M-1/2}e^{-1/x} \\xrightarrow[x\\to0^+]{} 0.", explanation: "Putting \\( u = 1/x\\to\\infty \\), the ratio is \\( u^{M+1/2}e^{-u}\\to0 \\); the optimal error is smaller than every power of \\( x \\) — it lives beyond all orders." },
      ],
      finalAnswer: "Optimal error \\( = O\\big(x^{-1/2}e^{-1/x}\\big) = o(x^M) \\) for every \\( M \\), as \\( x\\to0^+ \\).",
    },
  },
  {
    id: "am2b-024",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A divergent asymptotic series has term magnitudes \\( |t_n| = \\Gamma(n+a)\\,z^{-n} \\) for a fixed constant \\( a>0 \\) and large \\( z \\). Find the least-term index \\( n^\\ast \\) in terms of \\( z \\) and \\( a \\), and the leading behaviour of the least-term magnitude.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Gamma function", "Stirling", "least term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the consecutive-magnitude ratio.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{\\Gamma(n+1+a)}{\\Gamma(n+a)}\\,z^{-1} = \\frac{n+a}{z}.", explanation: "The Gamma recurrence \\( \\Gamma(s+1) = s\\,\\Gamma(s) \\) gives the single factor \\( n+a \\)." },
        { stepNumber: 2, description: "Set the ratio to 1.", workingLatex: "\\frac{n+a}{z} = 1 \\implies n^\\ast \\approx z - a.", explanation: "The minimum sits where consecutive magnitudes are equal." },
        { stepNumber: 3, description: "Evaluate the least term.", workingLatex: "|t_{n^\\ast}| = \\Gamma(n^\\ast + a)\\,z^{-n^\\ast} \\approx \\Gamma(z)\\,z^{-(z-a)} = z^{a}\\,\\Gamma(z)\\,z^{-z}.", explanation: "Substitute \\( n^\\ast + a \\approx z \\) and \\( n^\\ast \\approx z - a \\)." },
        { stepNumber: 4, description: "Apply Stirling \\( \\Gamma(z)\\sim\\sqrt{2\\pi/z}\\,z^{z}e^{-z} \\).", workingLatex: "|t_{n^\\ast}| \\approx z^{a}\\,\\sqrt{\\frac{2\\pi}{z}}\\,z^{z}e^{-z}\\,z^{-z} = \\sqrt{2\\pi}\\;z^{\\,a-1/2}\\,e^{-z}.", explanation: "The \\( z^z \\) factors cancel, leaving an exponentially small magnitude scaled by a power \\( z^{a-1/2} \\)." },
        { stepNumber: 5, description: "State the results.", workingLatex: "n^\\ast \\approx z - a, \\qquad |t_{n^\\ast}| \\sim \\sqrt{2\\pi}\\;z^{\\,a-1/2}\\,e^{-z}.", explanation: "The least-term index tracks \\( z \\) (offset by \\( a \\)), and the optimal error is exponentially small with a power-law prefactor set by \\( a \\)." },
      ],
      finalAnswer: "\\( n^\\ast \\approx z - a \\); \\( |t_{n^\\ast}| \\sim \\sqrt{2\\pi}\\,z^{a-1/2}e^{-z} \\).",
    },
  },
  {
    id: "am2b-025",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 25",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 5 },
    questionText: "Compare optimal truncation of the exponential-integral series at \\( x = 5 \\) and \\( x = 7 \\): in each case give \\( n^\\ast \\), the optimally truncated estimate of \\( E_1(x) \\), and the error, then state how many extra correct figures the larger \\( x \\) buys. (References: \\( E_1(5)=1.14830\\times10^{-3} \\), \\( E_1(7)=1.15482\\times10^{-4} \\).)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "exponential integral", "comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Least terms.", workingLatex: "x=5:\\; n^\\ast = 4; \\qquad x=7:\\; n^\\ast = 6.", explanation: "From \\( (n+1)/x < 1 \\): \\( n^\\ast = 4 \\) at \\( x = 5 \\) and \\( n^\\ast = 6 \\) at \\( x = 7 \\), tracking \\( n^\\ast\\approx x \\)." },
        { stepNumber: 2, description: "Estimate at \\( x = 5 \\).", workingLatex: "S = e^{-5}\\sum_{n=0}^{3}\\frac{(-1)^n n!}{5^{\\,n+1}} = e^{-5}\\times 0.16640 = 1.12119\\times10^{-3}.", explanation: "Retain \\( n = 0,\\dots,3 \\); bracket \\( 0.2-0.04+0.016-0.0096 = 0.1664 \\)." },
        { stepNumber: 3, description: "Error at \\( x = 5 \\).", workingLatex: "\\big|1.12119\\times10^{-3} - 1.14830\\times10^{-3}\\big| = 2.7\\times10^{-5}.", explanation: "Relative error \\( \\approx 2.4\\% \\): about two figures." },
        { stepNumber: 4, description: "Estimate at \\( x = 7 \\).", workingLatex: "S = e^{-7}\\sum_{n=0}^{5}\\frac{(-1)^n n!}{7^{\\,n+1}} = e^{-7}\\times 0.126189 = 1.15069\\times10^{-4}.", explanation: "Retain \\( n = 0,\\dots,5 \\); the bracket \\( \\tfrac17-\\tfrac1{49}+\\tfrac{2}{343}-\\tfrac{6}{2401}+\\tfrac{24}{16807}-\\tfrac{120}{117649} = 0.126189 \\)." },
        { stepNumber: 5, description: "Error at \\( x = 7 \\).", workingLatex: "\\big|1.15069\\times10^{-4} - 1.15482\\times10^{-4}\\big| = 4.1\\times10^{-7}.", explanation: "Relative error \\( \\approx 0.36\\% \\): about three figures." },
        { stepNumber: 6, description: "Quantify the gain.", workingLatex: "\\frac{2.7\\times10^{-5}/1.15\\times10^{-3}}{4.1\\times10^{-7}/1.15\\times10^{-4}} \\approx \\frac{2.4\\%}{0.36\\%} \\approx 6.6.", explanation: "Going from \\( x = 5 \\) to \\( x = 7 \\) cuts the relative error by a factor of about \\( 7 \\) — roughly one extra correct significant figure, consistent with the \\( e^{-x} \\) law for the optimal error." },
      ],
      finalAnswer: "\\( x=5:\\, n^\\ast=4,\\,E_1\\approx1.1212\\times10^{-3} \\); \\( x=7:\\, n^\\ast=6,\\,E_1\\approx1.1507\\times10^{-4} \\); \\( \\sim 1 \\) extra figure.",
      canonicalAnswer: "0.00011507",
    },
  },
  {
    id: "am2b-026",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For an alternating divergent series with term magnitudes \\( |t_n| \\), show that the optimal-truncation error is bounded by the first omitted term, and explain why for an alternating asymptotic series the true sum is bracketed between consecutive partial sums. Apply this to bound the error of \\( F(0.1)\\sim\\sum(-1)^n n!\\,0.1^n \\) truncated at the least term.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "alternating series", "error bound"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the partial sums.", workingLatex: "S_N = \\sum_{n=0}^{N} t_n, \\qquad t_n = (-1)^n |t_n|.", explanation: "For an asymptotic series the terms alternate in sign while the magnitudes first decrease." },
        { stepNumber: 2, description: "Use the standard remainder property.", workingLatex: "S - S_N = \\sum_{n=N+1}^{\\infty} t_n, \\qquad |S - S_N| \\le |t_{N+1}| \\text{ (while magnitudes decrease)}.", explanation: "For an alternating series with decreasing terms the tail is bounded by, and has the sign of, its first term — the classic alternating-series estimate, valid here up to the least term." },
        { stepNumber: 3, description: "Bracketing between consecutive sums.", workingLatex: "S_{2k} > S > S_{2k+1} \\quad (\\text{or the reverse}),", explanation: "Even partial sums overshoot and odd ones undershoot (or vice versa), so the true sum lies strictly between any two consecutive partial sums while the terms decrease." },
        { stepNumber: 4, description: "Apply to \\( F(0.1) \\): least term at \\( n^\\ast=9 \\).", workingLatex: "S_{8} = 0.915819, \\quad |t_9| = 9!\\,(0.1)^9 = 3.6288\\times10^{-4}.", explanation: "Truncating at one before the least term gives \\( S_8 \\); the first omitted term \\( t_9 \\) bounds the error." },
        { stepNumber: 5, description: "State the bracket.", workingLatex: "0.915819 - 3.63\\times10^{-4} \\;<\\; F(0.1) \\;<\\; 0.915819, \\;\\text{ i.e. } F(0.1) = 0.91564 \\pm 1.8\\times10^{-4}.", explanation: "The true value \\( 0.915633 \\) indeed lies in this bracket; the half-least-term \\( \\sim 1.8\\times10^{-4} \\) is the realistic uncertainty of optimal truncation." },
      ],
      finalAnswer: "Error \\( \\le |t_{n^\\ast}| \\); \\( F(0.1) = 0.91564 \\pm 1.8\\times10^{-4} \\), bracketing the exact \\( 0.915633 \\).",
    },
  },
  {
    id: "am2b-027",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 27",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "Consider \\( I(x)=\\displaystyle\\int_0^\\infty \\frac{e^{-t}}{1+x^2 t}\\,dt \\). Find its asymptotic series in powers of \\( x^2 \\), locate the least term at \\( x = 0.4 \\) (so \\( x^2 = 0.16 \\)), and use optimal truncation to estimate \\( I(0.4) \\). (Reference value \\( I(0.4)=0.875687 \\).)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "change of parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the series.", workingLatex: "I(x) = \\int_0^\\infty \\frac{e^{-t}}{1+x^2 t}\\,dt \\sim \\sum_{n=0}^\\infty (-1)^n n!\\,(x^2)^n.", explanation: "This is the Stieltjes series \\( F \\) with \\( x \\) replaced by \\( x^2 \\); the integrand is expanded geometrically and integrated using \\( \\int_0^\\infty t^n e^{-t}\\,dt = n! \\)." },
        { stepNumber: 2, description: "Set \\( u = x^2 = 0.16 \\) and locate the least term.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = (n+1)\\,u = (n+1)(0.16) < 1 \\iff n < 5.25 \\implies n^\\ast = 6.", explanation: "Magnitudes \\( n!\\,u^n \\) fall while \\( n+1 < 1/0.16 = 6.25 \\); the least term is at \\( n^\\ast = 6 \\)." },
        { stepNumber: 3, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{5}(-1)^n n!\\,(0.16)^n.", explanation: "Retain \\( n = 0,\\dots,5 \\)." },
        { stepNumber: 4, description: "List the term magnitudes \\( n!\\,(0.16)^n \\).", workingLatex: "1,\\;0.16,\\;0.0512,\\;0.024576,\\;0.01572864,\\;0.0125829.", explanation: "Factorials \\( 1,1,2,6,24,120 \\) times \\( 0.16^n \\)." },
        { stepNumber: 5, description: "Sum with alternating signs.", workingLatex: "1 - 0.16 + 0.0512 - 0.024576 + 0.01572864 - 0.0125829 = 0.869770.", explanation: "Accumulate the alternating partial sums." },
        { stepNumber: 6, description: "Compare with the reference.", workingLatex: "\\big|0.869770 - 0.875687\\big| = 5.9\\times10^{-3}.", explanation: "With \\( u = 0.16 \\) the least term is \\( \\sim 0.013 \\), so only about two figures are secured; the change of parameter \\( x\\mapsto x^2 \\) does not improve the divergence rate." },
      ],
      finalAnswer: "\\( I(0.4)\\approx 0.8698 \\) (error \\( \\approx 5.9\\times10^{-3} \\)).",
      canonicalAnswer: "0.869770",
    },
  },
  {
    id: "am2b-028",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain the principle of superasymptotics: that the optimal (least-term) truncation error of a factorially divergent series is exponentially small in the large parameter, and contrast this with the algebraically small error of an ordinary convergent power series truncated at \\( N \\) terms. Illustrate using the generic term \\( |t_n| = n!/x^{n+1} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "superasymptotics", "beyond all orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Ordinary truncation of a convergent series.", workingLatex: "\\text{Convergent } \\sum a_n x^{-n}: \\quad |R_N| \\sim |a_{N+1}|\\,x^{-(N+1)} = O(x^{-(N+1)}).", explanation: "For a fixed truncation order \\( N \\) the error of a convergent series is only algebraically (power-law) small in \\( x \\)." },
        { stepNumber: 2, description: "Divergent series: fixed \\( N \\) also gives algebraic error.", workingLatex: "\\text{Asymptotic, fixed } N: \\quad |R_N| = O(x^{-(N+1)}).", explanation: "Holding \\( N \\) fixed and letting \\( x\\to\\infty \\), even a divergent asymptotic series gives algebraic accuracy — this is the usual asymptotic statement." },
        { stepNumber: 3, description: "Now let \\( N \\) grow with \\( x \\): optimal truncation.", workingLatex: "N^\\ast \\approx x: \\quad |t_{N^\\ast}| = \\frac{N^\\ast!}{x^{N^\\ast+1}} \\stackrel{\\text{Stirling}}{\\sim} \\sqrt{\\frac{2\\pi}{x}}\\;e^{-x}.", explanation: "Choosing the truncation order to track the least term collapses the error to exponentially small size." },
        { stepNumber: 4, description: "Contrast the two regimes.", workingLatex: "\\underbrace{O(x^{-(N+1)})}_{\\text{fixed } N,\\ \\text{algebraic}} \\quad\\longrightarrow\\quad \\underbrace{O(x^{-1/2}e^{-x})}_{\\text{optimal } N,\\ \\text{exponential}}.", explanation: "The exponential beats every power: superasymptotics extracts far more accuracy than naive fixed-order truncation, which is why the least-term rule is the standard convention." },
        { stepNumber: 5, description: "State the principle.", workingLatex: "\\text{Optimal error} = O\\!\\big(e^{-x}\\big) \\;\\ll\\; O\\!\\big(x^{-M}\\big) \\;\\forall M.", explanation: "The residual lies beyond all orders of the asymptotic series; resolving it further requires exponential asymptotics (Stokes phenomenon, hyperasymptotics)." },
      ],
      finalAnswer: "Optimal error is exponentially small \\( O(x^{-1/2}e^{-x}) \\), versus algebraic \\( O(x^{-(N+1)}) \\) for fixed-order truncation.",
    },
  },
  {
    id: "am2b-029",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 29",
    difficulty: "Challenge",
    answerType: "numeric",
    answerMeta: { requiredDp: 4 },
    questionText: "For the Stieltjes integral \\( F(x)=\\int_0^\\infty e^{-t}/(1+xt)\\,dt \\) at \\( x = 0.25 \\), determine the least-term index, apply optimal truncation to estimate \\( F(0.25) \\), and explain why optimal truncation gives a poor estimate here. (Reference value \\( F(0.25)=0.825383 \\).)",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Stieltjes integral", "limitations"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the least term.", workingLatex: "(n+1)\\,x = (n+1)(0.25) < 1 \\iff n < 3 \\implies n^\\ast = 3.", explanation: "With \\( 1/x = 4 \\), magnitudes \\( n!\\,(0.25)^n \\) fall while \\( n+1 < 4 \\); the least term is at \\( n^\\ast = 3 \\) (with \\( n = 4 \\) tied)." },
        { stepNumber: 2, description: "Truncate one before the least.", workingLatex: "S_{\\text{opt}} = \\sum_{n=0}^{2}(-1)^n n!\\,(0.25)^n.", explanation: "Retain only \\( n = 0,1,2 \\) — very few terms, because \\( x \\) is not small." },
        { stepNumber: 3, description: "List the term magnitudes \\( n!\\,(0.25)^n \\).", workingLatex: "1,\\;0.25,\\;0.125.", explanation: "Factorials \\( 1,1,2 \\) times \\( 0.25^n \\)." },
        { stepNumber: 4, description: "Sum with alternating signs.", workingLatex: "1 - 0.25 + 0.125 = 0.875.", explanation: "The optimal partial sum is just \\( 0.875 \\)." },
        { stepNumber: 5, description: "Compute the error and explain.", workingLatex: "\\big|0.875 - 0.825383\\big| = 5.0\\times10^{-2}; \\quad |t_{3}| = 6\\,(0.25)^3 = 0.094.", explanation: "The least term is already \\( \\sim 0.09 \\), so the best possible accuracy is only one figure. Optimal truncation is only powerful when the large parameter pushes \\( n^\\ast \\) high; at \\( x = 0.25 \\) the series diverges almost immediately." },
      ],
      finalAnswer: "\\( n^\\ast = 3 \\), \\( F(0.25)\\approx 0.875 \\), error \\( \\approx 0.050 \\) — only one reliable figure.",
      canonicalAnswer: "0.875",
    },
  },
  {
    id: "am2b-030",
    topicRef: "am2b",
    topicTitle: "Optimal truncation: the least term 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A function has the asymptotic series \\( S(x)\\sim\\sum_{n\\ge0}(-1)^n c_n\\,x^{-n} \\) with \\( c_n = A^{-n}\\,n! \\) for a constant \\( A>0 \\) (a factorially divergent tail with 'singularity distance' \\( A \\)). Find the least-term index and magnitude as functions of \\( x \\) and \\( A \\), and state how the optimal error depends on \\( A \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "Borel", "singularity distance", "Stirling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the term magnitude.", workingLatex: "|t_n| = c_n\\,x^{-n} = \\frac{n!}{(Ax)^{n}}.", explanation: "The coefficients \\( c_n = n!/A^n \\) model a series whose Borel transform has its nearest singularity a distance \\( A \\) from the origin." },
        { stepNumber: 2, description: "Form the consecutive ratio.", workingLatex: "\\frac{|t_{n+1}|}{|t_n|} = \\frac{n+1}{A x}.", explanation: "The factorial advances by \\( n+1 \\) while the denominator gains a factor \\( Ax \\)." },
        { stepNumber: 3, description: "Locate the least term.", workingLatex: "\\frac{n+1}{Ax} = 1 \\implies n^\\ast \\approx A x.", explanation: "The minimum sits at \\( n \\approx Ax \\): a larger singularity distance \\( A \\) pushes the least term to a higher index." },
        { stepNumber: 4, description: "Evaluate the least-term magnitude with Stirling.", workingLatex: "|t_{n^\\ast}| = \\frac{(Ax)!}{(Ax)^{Ax}} \\sim \\sqrt{2\\pi A x}\\;e^{-Ax}.", explanation: "Put \\( n^\\ast = Ax \\); Stirling cancels the \\( (Ax)^{Ax} \\) and leaves an exponentially small residue controlled by \\( Ax \\)." },
        { stepNumber: 5, description: "State the dependence on \\( A \\).", workingLatex: "n^\\ast \\approx Ax, \\qquad |t_{n^\\ast}| \\sim \\sqrt{2\\pi A x}\\;e^{-Ax}.", explanation: "The optimal error decays like \\( e^{-Ax} \\): the farther the Borel singularity (larger \\( A \\)), the more terms can be summed and the smaller the achievable error — the quantitative link between optimal truncation and the location of singularities." },
      ],
      finalAnswer: "\\( n^\\ast \\approx Ax \\); \\( |t_{n^\\ast}| \\sim \\sqrt{2\\pi Ax}\\,e^{-Ax} \\), so the optimal error is \\( O(e^{-Ax}) \\), smaller for larger \\( A \\).",
    },
  },
];
