import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — Laplace's Method § am4a
 * Laplace's method: interior maximum.
 * Ref: am4a
 *
 * 30 fully-worked questions on integrals of the form
 *   I(x) = ∫ g(t) e^{x φ(t)} dt
 * where φ attains an interior maximum at t₀ (φ'(t₀)=0, φ''(t₀)<0). The leading
 * behaviour comes from a Gaussian centred at t₀:
 *   I(x) ~ g(t₀) e^{x φ(t₀)} √( 2π / ( x |φ''(t₀)| ) ),  x → ∞.
 *
 * Seeded from Cambridge Part II Asymptotic Methods, Example Sheet 1
 * (Michaelmas 2025): Q12 and Q13 (Laplace's method), with the Gaussian-tail
 * machinery underlying Q9–Q11. Constants, limits and framing are varied.
 *
 * Leading and (where stated) second-order results were numerically checked with
 * mpmath at large x. Several finite-range integrals reduce exactly to modified
 * Bessel functions 2π I₀ or special-function values, which were used as exact
 * benchmarks.
 */
export const questions: Question[] = [
  // ─────────────────────────── FOUNDATION (6) ───────────────────────────
  {
    id: "am4a-001",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 01",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Gaussian integral \\( \\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\,dt \\) for \\( x > 0 \\). This is the basic building block of Laplace's method.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "Gaussian integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the standard Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a u^{2}}\\,du = \\sqrt{\\frac{\\pi}{a}}, \\qquad a > 0.", explanation: "This is the result \\(\\int e^{-u^2}du=\\sqrt{\\pi}\\) rescaled. Every leading-order Laplace estimate ends in an integral of exactly this shape, so it is worth knowing cold." },
        { stepNumber: 2, description: "Match the exponent to the standard form.", workingLatex: "a = x.", explanation: "Here the coefficient of \\(t^{2}\\) in the exponent is simply \\(x\\), so we set \\(a=x\\)." },
        { stepNumber: 3, description: "Substitute and conclude.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\,dt = \\sqrt{\\frac{\\pi}{x}}.", explanation: "As \\(x\\) grows the integrand concentrates ever more tightly near \\(t=0\\); the width of the bump scales like \\(x^{-1/2}\\), which is why the answer decays like \\(x^{-1/2}\\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-002",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 02",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\int_{-\\infty}^{\\infty} e^{-x t^{2}/2}\\,dt \\) for \\( x > 0 \\), and state how the result depends on \\( x \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "Gaussian integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the Gaussian coefficient.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a u^{2}}\\,du = \\sqrt{\\frac{\\pi}{a}}, \\qquad a = \\frac{x}{2}.", explanation: "The exponent is \\(-\\frac{x}{2}t^{2}\\), so the matching coefficient is \\(a=x/2\\). This half-coefficient form recurs because Laplace's method produces \\(\\tfrac12\\phi''(t_0)\\) in the exponent." },
        { stepNumber: 2, description: "Substitute the coefficient.", workingLatex: "\\sqrt{\\frac{\\pi}{x/2}} = \\sqrt{\\frac{2\\pi}{x}}.", explanation: "Dividing inside the root by \\(x/2\\) is the same as multiplying by \\(2/x\\)." },
        { stepNumber: 3, description: "State the answer and its scaling.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x t^{2}/2}\\,dt = \\sqrt{\\frac{2\\pi}{x}} \\propto x^{-1/2}.", explanation: "The integral decays like \\(x^{-1/2}\\); the prefactor \\(\\sqrt{2\\pi}\\) is exactly what appears in the general Laplace formula when \\(|\\phi''(t_0)|=1\\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-003",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{-3 x t^{2}}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "Gaussian integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Match to the standard Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a u^{2}}\\,du = \\sqrt{\\frac{\\pi}{a}}, \\qquad a = 3x.", explanation: "The coefficient of \\(t^{2}\\) is \\(3x\\); the factor \\(3\\) plays the role of \\(\\tfrac12|\\phi''(t_0)|\\) for a sharper peak." },
        { stepNumber: 2, description: "Substitute.", workingLatex: "I(x) = \\sqrt{\\frac{\\pi}{3x}}.", explanation: "A larger coefficient narrows the Gaussian, so the integral is smaller than for \\(e^{-xt^2}\\) by a factor \\(1/\\sqrt 3\\)." },
        { stepNumber: 3, description: "State the leading-order form.", workingLatex: "I(x) \\sim \\frac{1}{\\sqrt{3}}\\,\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Here the result is exact, but writing it with \\(\\sim\\) emphasises the \\(x^{-1/2}\\) scaling that survives in genuine Laplace problems." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\sqrt{\\frac{\\pi}{3x}} \\)",
      canonicalAnswer: "sqrt(pi/(3*x))",
    },
  },
  {
    id: "am4a-004",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The phase \\( \\phi(t) = 1 - \\tfrac12(t-2)^{2} \\). Locate its maximum on \\( \\mathbb{R} \\) and write down \\( \\phi(t_{0}) \\) and \\( \\phi''(t_{0}) \\), the two ingredients Laplace's method needs.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "\\phi'(t) = -(t-2).", explanation: "An interior maximum requires a stationary point, so we first find where \\(\\phi'\\) vanishes." },
        { stepNumber: 2, description: "Solve for the stationary point.", workingLatex: "\\phi'(t) = 0 \\;\\Longrightarrow\\; t_{0} = 2.", explanation: "This is interior to \\(\\mathbb{R}\\), so it is a genuine interior maximum rather than an endpoint effect." },
        { stepNumber: 3, description: "Evaluate the phase and its curvature there.", workingLatex: "\\phi(t_{0}) = 1, \\qquad \\phi''(t) = -1 \\;\\Rightarrow\\; \\phi''(t_{0}) = -1.", explanation: "Since \\(\\phi''(t_0)=-1<0\\) the stationary point is indeed a maximum. These two numbers, \\(\\phi(t_0)\\) and \\(\\phi''(t_0)\\), are exactly what feed into the Gaussian formula." },
      ],
      finalAnswer: "\\( t_{0} = 2,\\; \\phi(t_{0}) = 1,\\; \\phi''(t_{0}) = -1 \\)",
    },
  },
  {
    id: "am4a-005",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the leading-order Laplace estimate as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{-x(t-2)^{2}}\\,dt \\) by recognising the interior maximum.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the phase and its maximum.", workingLatex: "\\phi(t) = -(t-2)^{2}, \\quad t_{0} = 2, \\quad \\phi(t_{0}) = 0.", explanation: "The exponent is \\(x\\phi(t)\\); the peak sits at \\(t_0=2\\), interior to the range." },
        { stepNumber: 2, description: "Compute the curvature.", workingLatex: "\\phi''(t) = -2 \\;\\Rightarrow\\; |\\phi''(t_{0})| = 2.", explanation: "A constant second derivative means the Gaussian approximation is exact here, but the bookkeeping is identical to the general case." },
        { stepNumber: 3, description: "Apply the Laplace formula.", workingLatex: "I(x) \\sim e^{x\\phi(t_{0})}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(t_{0})|}} = \\sqrt{\\frac{2\\pi}{2x}}.", explanation: "Substituting \\(\\phi(t_0)=0\\) and \\(|\\phi''(t_0)|=2\\) into the master formula." },
        { stepNumber: 4, description: "Simplify.", workingLatex: "I(x) \\sim \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The shift to \\(t_0=2\\) does not change the size of the integral, only where the contribution comes from." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-006",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the general leading-order Laplace formula for \\( I(x) = \\int_{a}^{b} g(t)\\,e^{x\\phi(t)}\\,dt \\) when \\( \\phi \\) has a single interior maximum at \\( t_{0} \\) with \\( \\phi'(t_{0}) = 0 \\), \\( \\phi''(t_{0}) < 0 \\) and \\( g(t_{0}) \\neq 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Localise to the peak.", workingLatex: "I(x) \\approx g(t_{0})\\,e^{x\\phi(t_{0})}\\int_{-\\infty}^{\\infty} e^{\\frac{x}{2}\\phi''(t_{0})(t-t_{0})^{2}}\\,dt.", explanation: "For large \\(x\\) only a shrinking neighbourhood of \\(t_0\\) matters, so we Taylor-expand \\(\\phi\\) to second order and freeze \\(g\\) at \\(g(t_0)\\). The limits may be pushed to \\(\\pm\\infty\\) because the tails are exponentially small." },
        { stepNumber: 2, description: "Do the Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-\\frac{x}{2}|\\phi''(t_{0})|\\,s^{2}}\\,ds = \\sqrt{\\frac{2\\pi}{x\\,|\\phi''(t_{0})|}}.", explanation: "Write \\(\\phi''(t_0)=-|\\phi''(t_0)|\\) since the curvature is negative at a maximum; the integral is a standard Gaussian in \\(s=t-t_0\\)." },
        { stepNumber: 3, description: "Assemble the formula.", workingLatex: "I(x) \\sim g(t_{0})\\,e^{x\\phi(t_{0})}\\,\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(t_{0})|}}, \\qquad x \\to \\infty.", explanation: "This is the result every interior-maximum Laplace problem reduces to once \\(t_0\\), \\(\\phi(t_0)\\), \\(\\phi''(t_0)\\) and \\(g(t_0)\\) are known." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim g(t_{0})\\,e^{x\\phi(t_{0})}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(t_{0})|}} \\)",
    },
  },

  // ─────────────────────────── STANDARD (12) ───────────────────────────
  {
    id: "am4a-007",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using Laplace's method, find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\pi}^{\\pi} e^{x\\cos t}\\,dt \\). (You may note \\( I(x) = 2\\pi I_{0}(x) \\), where \\( I_{0} \\) is a modified Bessel function.)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "Bessel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum of the phase.", workingLatex: "\\phi(t) = \\cos t, \\quad \\phi'(t) = -\\sin t = 0 \\;\\Rightarrow\\; t_{0} = 0.", explanation: "On \\([-\\pi,\\pi]\\) the cosine is largest at \\(t=0\\), which is interior; the candidate at \\(t=\\pm\\pi\\) is a minimum." },
        { stepNumber: 2, description: "Record the phase value and curvature.", workingLatex: "\\phi(t_{0}) = \\cos 0 = 1, \\qquad \\phi''(t) = -\\cos t \\;\\Rightarrow\\; \\phi''(0) = -1.", explanation: "So \\(|\\phi''(t_0)|=1\\); the peak is a clean unit-curvature maximum." },
        { stepNumber: 3, description: "Identify the amplitude at the peak.", workingLatex: "g(t) = 1 \\;\\Rightarrow\\; g(t_{0}) = 1.", explanation: "There is no separate amplitude factor here, so \\(g(t_0)=1\\)." },
        { stepNumber: 4, description: "Apply the Laplace formula.", workingLatex: "I(x) \\sim g(t_{0})\\,e^{x\\phi(t_{0})}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(t_{0})|}} = e^{x}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "Substituting \\(g(t_0)=1\\), \\(\\phi(t_0)=1\\), \\(|\\phi''(t_0)|=1\\)." },
        { stepNumber: 5, description: "State the result.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Equivalently \\(I_0(x)\\sim e^x/\\sqrt{2\\pi x}\\), the textbook large-argument Bessel asymptotic — a useful independent confirmation." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-008",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{0}^{\\pi} e^{x\\sin t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the interior maximum.", workingLatex: "\\phi(t) = \\sin t, \\quad \\phi'(t) = \\cos t = 0 \\;\\Rightarrow\\; t_{0} = \\frac{\\pi}{2}.", explanation: "On \\([0,\\pi]\\) the sine peaks at \\(\\pi/2\\), strictly inside the interval; the endpoints give \\(\\sin t=0\\)." },
        { stepNumber: 2, description: "Evaluate phase and curvature at the peak.", workingLatex: "\\phi\\!\\left(\\tfrac{\\pi}{2}\\right) = 1, \\qquad \\phi''(t) = -\\sin t \\;\\Rightarrow\\; \\phi''\\!\\left(\\tfrac{\\pi}{2}\\right) = -1.", explanation: "Negative curvature confirms a maximum, with \\(|\\phi''(t_0)|=1\\)." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = 1.", explanation: "There is no amplitude factor, so \\(g(t_0)=1\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Because \\(t_0=\\pi/2\\) is interior, the full Gaussian width contributes; an endpoint maximum would have halved this. Numerically the ratio of integral to estimate tends to \\(1\\) as \\(x\\to\\infty\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-009",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\pi}^{\\pi} e^{2x\\cos t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the phase with the parameter absorbed.", workingLatex: "x\\phi(t) = 2x\\cos t \\;\\Rightarrow\\; \\phi(t) = 2\\cos t.", explanation: "Keep the large parameter as a single overall factor \\(x\\); the rescaled phase is \\(\\phi(t)=2\\cos t\\)." },
        { stepNumber: 2, description: "Locate the interior maximum.", workingLatex: "\\phi'(t) = -2\\sin t = 0 \\;\\Rightarrow\\; t_{0} = 0.", explanation: "The maximum is again at \\(t=0\\)." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "\\phi(0) = 2, \\qquad \\phi''(t) = -2\\cos t \\;\\Rightarrow\\; \\phi''(0) = -2.", explanation: "The doubled amplitude doubles both the peak height and the curvature: \\(|\\phi''(t_0)|=2\\)." },
        { stepNumber: 4, description: "Apply the Laplace formula.", workingLatex: "I(x) \\sim e^{2x}\\sqrt{\\frac{2\\pi}{2x}} = e^{2x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Substituting \\(\\phi(t_0)=2\\), \\(|\\phi''(t_0)|=2\\), \\(g(t_0)=1\\). Equivalently \\(2\\pi I_0(2x)\\), which matches numerically." },
        { stepNumber: 5, description: "State the result.", workingLatex: "I(x) \\sim e^{2x}\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The sharper peak (curvature \\(2\\)) makes the prefactor smaller than the \\(\\cos t\\) case by \\(1/\\sqrt 2\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{2x}\\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(2*x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4a-010",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} (2 + t)\\,e^{-x t^{2}}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify phase, peak and amplitude.", workingLatex: "\\phi(t) = -t^{2}, \\quad t_{0} = 0, \\quad \\phi(0) = 0, \\quad g(t) = 2 + t.", explanation: "The Gaussian weight \\(e^{-xt^2}\\) localises everything at \\(t_0=0\\); the amplitude is the polynomial \\(g(t)=2+t\\)." },
        { stepNumber: 2, description: "Curvature at the peak.", workingLatex: "\\phi''(t) = -2 \\;\\Rightarrow\\; |\\phi''(t_{0})| = 2.", explanation: "Constant curvature, magnitude \\(2\\)." },
        { stepNumber: 3, description: "Freeze the amplitude at the peak.", workingLatex: "g(t_{0}) = 2 + 0 = 2.", explanation: "Only \\(g(t_0)\\) survives at leading order; the linear part \\(t\\) is odd about \\(t_0=0\\) and contributes nothing at this order." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 2\\,\\sqrt{\\frac{2\\pi}{2x}} = 2\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The amplitude simply multiplies the Gaussian estimate by \\(g(t_0)=2\\); this matches the exact value \\(2\\sqrt{\\pi/x}\\) to many digits at large \\(x\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim 2\\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "2*sqrt(pi/x)",
    },
  },
  {
    id: "am4a-011",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} \\cos t\\;e^{-x t^{2}}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate phase and amplitude.", workingLatex: "\\phi(t) = -t^{2}, \\quad g(t) = \\cos t, \\quad t_{0} = 0.", explanation: "The large-parameter exponent is \\(-xt^2\\); the slowly varying factor is \\(g(t)=\\cos t\\). The peak is at \\(t_0=0\\)." },
        { stepNumber: 2, description: "Phase data at the peak.", workingLatex: "\\phi(0) = 0, \\qquad \\phi''(0) = -2 \\;\\Rightarrow\\; |\\phi''(0)| = 2.", explanation: "Standard quadratic phase with curvature magnitude \\(2\\)." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = \\cos 0 = 1.", explanation: "Only the value of \\(\\cos t\\) at the peak enters at leading order; its variation away from \\(t_0\\) is a higher-order correction." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot\\sqrt{\\frac{2\\pi}{2x}} = \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "So \\(I(x)\\sim\\sqrt{\\pi/x}\\). (The exact value is \\(\\sqrt{\\pi/x}\\,e^{-1/(4x)}\\), whose leading term is precisely this.)" },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-012",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{-x(t^{2} - 4t + 4)}\\,dt \\) by completing the square.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "completing the square"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complete the square in the exponent.", workingLatex: "t^{2} - 4t + 4 = (t - 2)^{2}.", explanation: "Recognising the perfect square immediately reveals the location of the peak." },
        { stepNumber: 2, description: "Read off phase and peak.", workingLatex: "\\phi(t) = -(t-2)^{2}, \\quad t_{0} = 2, \\quad \\phi(t_{0}) = 0.", explanation: "The maximum of \\(\\phi\\) is where the square vanishes, at \\(t_0=2\\)." },
        { stepNumber: 3, description: "Curvature at the peak.", workingLatex: "\\phi''(t) = -2 \\;\\Rightarrow\\; |\\phi''(t_{0})| = 2.", explanation: "Constant curvature magnitude \\(2\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{0}\\sqrt{\\frac{2\\pi}{2x}} = \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Because \\(\\phi(t_0)=0\\) there is no exponential growth; the shift of the peak to \\(t_0=2\\) leaves the magnitude unchanged." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-013",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-1}^{1} e^{x(1 - t^{2})}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the phase and its interior maximum.", workingLatex: "\\phi(t) = 1 - t^{2}, \\quad \\phi'(t) = -2t = 0 \\;\\Rightarrow\\; t_{0} = 0.", explanation: "The peak sits at \\(t_0=0\\), strictly inside \\([-1,1]\\)." },
        { stepNumber: 2, description: "Phase value and curvature.", workingLatex: "\\phi(0) = 1, \\qquad \\phi''(t) = -2 \\;\\Rightarrow\\; |\\phi''(t_{0})| = 2.", explanation: "Peak height \\(1\\), curvature magnitude \\(2\\)." },
        { stepNumber: 3, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{2x}} = e^{x}\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The finite limits \\(\\pm1\\) are far from the peak compared with the Gaussian width \\(O(x^{-1/2})\\), so extending to \\(\\pm\\infty\\) is justified and the endpoint contributions are exponentially negligible." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4a-014",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} \\frac{1}{1 + t^{2}}\\,e^{-x t^{2}}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate phase and amplitude.", workingLatex: "\\phi(t) = -t^{2}, \\quad g(t) = \\frac{1}{1 + t^{2}}, \\quad t_{0} = 0.", explanation: "The Gaussian \\(e^{-xt^2}\\) pins the contribution at \\(t_0=0\\); \\(g\\) is smooth and bounded there." },
        { stepNumber: 2, description: "Phase data at the peak.", workingLatex: "\\phi(0) = 0, \\qquad \\phi''(0) = -2 \\;\\Rightarrow\\; |\\phi''(0)| = 2.", explanation: "Curvature magnitude \\(2\\)." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = \\frac{1}{1 + 0} = 1.", explanation: "Only \\(g(0)=1\\) matters at leading order; the way \\(g\\) decays away from \\(0\\) affects only the \\(O(x^{-3/2})\\) correction." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot\\sqrt{\\frac{2\\pi}{2x}} = \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The rational amplitude is irrelevant to leading order precisely because the integral only ever sees its value at the peak." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-015",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{x(2t - t^{2})}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "\\phi(t) = 2t - t^{2}, \\quad \\phi'(t) = 2 - 2t.", explanation: "Set up to find where the quadratic phase peaks." },
        { stepNumber: 2, description: "Locate the maximum.", workingLatex: "\\phi'(t) = 0 \\;\\Rightarrow\\; t_{0} = 1.", explanation: "Interior to \\(\\mathbb{R}\\); the negative \\(t^2\\) coefficient guarantees it is a maximum." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "\\phi(1) = 2 - 1 = 1, \\qquad \\phi''(t) = -2 \\;\\Rightarrow\\; |\\phi''(t_{0})| = 2.", explanation: "Peak height \\(1\\), curvature magnitude \\(2\\). (Equivalently, complete the square: \\(2t-t^2=1-(t-1)^2\\).)" },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{2x}} = e^{x}\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The linear term in the phase has simply shifted the peak to \\(t_0=1\\) and raised it to height \\(1\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4a-016",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{0}^{\\pi} (1 + \\cos t)\\,e^{x\\sin t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the interior maximum of the phase.", workingLatex: "\\phi(t) = \\sin t, \\quad \\phi'(t) = \\cos t = 0 \\;\\Rightarrow\\; t_{0} = \\frac{\\pi}{2}.", explanation: "The phase \\(\\sin t\\) peaks at \\(\\pi/2\\), interior to \\([0,\\pi]\\)." },
        { stepNumber: 2, description: "Phase value and curvature.", workingLatex: "\\phi\\!\\left(\\tfrac{\\pi}{2}\\right) = 1, \\qquad \\phi''\\!\\left(\\tfrac{\\pi}{2}\\right) = -\\sin\\tfrac{\\pi}{2} = -1.", explanation: "Curvature magnitude \\(1\\) at the peak." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t) = 1 + \\cos t \\;\\Rightarrow\\; g\\!\\left(\\tfrac{\\pi}{2}\\right) = 1 + 0 = 1.", explanation: "The amplitude is evaluated at \\(t_0=\\pi/2\\); \\(\\cos(\\pi/2)=0\\) so \\(g(t_0)=1\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot e^{x}\\sqrt{\\frac{2\\pi}{x\\cdot 1}} = e^{x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Even though \\(g\\) varies appreciably across \\([0,\\pi]\\), only its peak value matters at leading order." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-017",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{-x\\cosh t}\\,dt \\). Note that the dominant contribution comes from the minimum of \\( \\cosh t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "minimum of phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rewrite so the phase has a maximum.", workingLatex: "I(x) = \\int_{-\\infty}^{\\infty} e^{x\\phi(t)}\\,dt, \\qquad \\phi(t) = -\\cosh t.", explanation: "With a minus sign, \\(\\phi=-\\cosh t\\) is maximised where \\(\\cosh t\\) is minimised — the integrand is largest at the bottom of the \\(\\cosh\\) well." },
        { stepNumber: 2, description: "Locate the maximum of the phase.", workingLatex: "\\phi'(t) = -\\sinh t = 0 \\;\\Rightarrow\\; t_{0} = 0.", explanation: "The only stationary point is at \\(t_0=0\\), interior to \\(\\mathbb{R}\\)." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "\\phi(0) = -1, \\qquad \\phi''(t) = -\\cosh t \\;\\Rightarrow\\; \\phi''(0) = -1.", explanation: "Peak height \\(-1\\) (so the exponential gives \\(e^{-x}\\)); curvature magnitude \\(1\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{-x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Equivalently \\(I(x)=2K_0(x)\\), whose large-argument asymptotic \\(K_0(x)\\sim\\sqrt{\\pi/(2x)}\\,e^{-x}\\) reproduces this exactly." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{-x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(-x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-018",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{x(t^{2} - \\frac{1}{4}t^{4})}\\,dt \\). (Hint: there are two symmetric maxima.)",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "multiple maxima"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the stationary points.", workingLatex: "\\phi(t) = t^{2} - \\tfrac14 t^{4}, \\quad \\phi'(t) = 2t - t^{3} = t(2 - t^{2}) = 0.", explanation: "Stationary points at \\(t=0\\) and \\(t=\\pm\\sqrt2\\)." },
        { stepNumber: 2, description: "Classify them.", workingLatex: "\\phi''(t) = 2 - 3t^{2}: \\quad \\phi''(0) = 2 > 0,\\;\\; \\phi''(\\pm\\sqrt2) = 2 - 6 = -4 < 0.", explanation: "So \\(t=0\\) is a local minimum, while \\(t=\\pm\\sqrt2\\) are the two maxima that dominate." },
        { stepNumber: 3, description: "Evaluate the phase at the maxima.", workingLatex: "\\phi(\\pm\\sqrt2) = 2 - \\tfrac14(4) = 1.", explanation: "Both maxima have the same height \\(1\\) by symmetry, so both contribute equally to the leading order." },
        { stepNumber: 4, description: "Apply Laplace's formula at one peak.", workingLatex: "I_{\\text{one}}(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x\\cdot 4}} = \\tfrac12\\,e^{x}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "Each peak has curvature magnitude \\(4\\), giving a \\(\\tfrac12\\) prefactor relative to unit curvature." },
        { stepNumber: 5, description: "Add the two equal contributions.", workingLatex: "I(x) \\sim 2\\cdot \\tfrac12\\,e^{x}\\sqrt{\\frac{2\\pi}{x}} = e^{x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "When several interior maxima share the same height, you sum their separate Gaussian contributions." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },

  // ─────────────────────────── CHALLENGE (12) ───────────────────────────
  {
    id: "am4a-019",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the two-term asymptotic expansion as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} (1 + t^{2})\\,e^{-x t^{2}}\\,dt \\), and verify it against the exact value.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "two-term expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise the integral splits exactly.", workingLatex: "I(x) = \\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\,dt + \\int_{-\\infty}^{\\infty} t^{2}\\,e^{-x t^{2}}\\,dt.", explanation: "Because the amplitude is a simple polynomial, the integral is elementary and we can obtain an exact two-term result to validate the Laplace machinery." },
        { stepNumber: 2, description: "Evaluate the first Gaussian moment.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\,dt = \\sqrt{\\frac{\\pi}{x}}.", explanation: "The zeroth moment — the leading Laplace term with \\(g(t_0)=1\\)." },
        { stepNumber: 3, description: "Evaluate the second Gaussian moment.", workingLatex: "\\int_{-\\infty}^{\\infty} t^{2}\\,e^{-x t^{2}}\\,dt = -\\frac{d}{dx}\\sqrt{\\frac{\\pi}{x}} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\cdot\\frac{1}{x}.", explanation: "Differentiating \\(\\sqrt{\\pi/x}\\) with respect to the parameter \\(x\\) brings down a factor \\(-t^2\\); the second moment is \\(\\tfrac{1}{2x}\\sqrt{\\pi/x}\\)." },
        { stepNumber: 4, description: "Add the two contributions.", workingLatex: "I(x) = \\sqrt{\\frac{\\pi}{x}}\\left(1 + \\frac{1}{2x}\\right).", explanation: "This is the exact value, and simultaneously its own two-term asymptotic expansion." },
        { stepNumber: 5, description: "State and interpret.", workingLatex: "I(x) \\sim \\sqrt{\\frac{\\pi}{x}}\\left(1 + \\frac{1}{2x} + \\cdots\\right), \\qquad x \\to \\infty.", explanation: "The leading term is the usual Laplace estimate; the \\(1/(2x)\\) correction comes from the curvature of the amplitude \\(g(t)=1+t^2\\) at the peak. The closed form matches a direct numerical evaluation to full precision." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\sqrt{\\frac{\\pi}{x}}\\left(1 + \\frac{1}{2x}\\right) \\)",
      canonicalAnswer: "sqrt(pi/x)*(1 + 1/(2*x))",
    },
  },
  {
    id: "am4a-020",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the two-term asymptotic expansion as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\pi}^{\\pi} e^{x\\cos t}\\,dt = 2\\pi I_{0}(x) \\), and identify the source of the correction term.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "two-term expansion", "Bessel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the phase about the peak.", workingLatex: "\\cos t = 1 - \\frac{t^{2}}{2} + \\frac{t^{4}}{24} - \\cdots, \\qquad t_{0} = 0.", explanation: "The leading Gaussian comes from \\(-t^2/2\\); the quartic term \\(t^4/24\\) is what generates the first correction." },
        { stepNumber: 2, description: "Write the localised integral.", workingLatex: "I(x) \\sim e^{x}\\int_{-\\infty}^{\\infty} e^{-\\frac{x}{2}t^{2}}\\,e^{\\frac{x}{24}t^{4}}\\,dt.", explanation: "Pull out \\(e^{x}\\) from \\(\\phi(0)=1\\); keep the quartic term in a separate factor to be expanded." },
        { stepNumber: 3, description: "Expand the quartic factor.", workingLatex: "e^{\\frac{x}{24}t^{4}} = 1 + \\frac{x}{24}t^{4} + \\cdots.", explanation: "The combination \\(x t^4\\) is \\(O(x^{-1})\\) on the Gaussian scale \\(t\\sim x^{-1/2}\\), so this is a legitimate small correction." },
        { stepNumber: 4, description: "Take the required Gaussian moments.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-\\frac{x}{2}t^{2}}\\,dt = \\sqrt{\\frac{2\\pi}{x}}, \\quad \\int_{-\\infty}^{\\infty} t^{4} e^{-\\frac{x}{2}t^{2}}\\,dt = \\frac{3}{x^{2}}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "Using \\(\\langle t^{4}\\rangle = 3/(x|\\phi''|)^{2}\\cdot\\) (normalisation) with \\(|\\phi''|=1\\): the fourth moment is \\(3/x^2\\) times the zeroth." },
        { stepNumber: 5, description: "Combine the two contributions.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{x}{24}\\cdot\\frac{3}{x^{2}}\\right) = e^{x}\\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{1}{8x}\\right).", explanation: "The quartic contributes \\(\\frac{x}{24}\\cdot\\frac{3}{x^2}=\\frac{1}{8x}\\)." },
        { stepNumber: 6, description: "State the result.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{1}{8x} + \\cdots\\right), \\qquad x \\to \\infty.", explanation: "This matches the classical large-argument expansion \\(I_0(x)\\sim \\frac{e^x}{\\sqrt{2\\pi x}}(1+\\frac{1}{8x}+\\cdots)\\); a numerical fit of \\((I/I_{\\text{lead}}-1)x\\) converges to \\(0.125\\) as \\(x\\to\\infty\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{1}{8x}\\right) \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)*(1 + 1/(8*x))",
    },
  },
  {
    id: "am4a-021",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} t^{2}\\,e^{-x t^{2}}\\,dt \\), and explain why the decay is faster than \\( x^{-1/2} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "vanishing amplitude"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the amplitude vanishes at the peak.", workingLatex: "\\phi(t) = -t^{2}, \\quad t_{0} = 0, \\quad g(t) = t^{2}, \\quad g(t_{0}) = 0.", explanation: "The naive Laplace formula gives \\(g(t_0)=0\\), so the usual leading term is absent and we must go to the next order in the amplitude." },
        { stepNumber: 2, description: "Rescale to the Gaussian width.", workingLatex: "t = \\frac{s}{\\sqrt{x}} \\;\\Rightarrow\\; dt = \\frac{ds}{\\sqrt{x}}, \\quad t^{2} = \\frac{s^{2}}{x}.", explanation: "On the natural scale \\(t\\sim x^{-1/2}\\) the amplitude \\(t^2\\) is itself \\(O(1/x)\\), which is the source of the extra decay." },
        { stepNumber: 3, description: "Rewrite the integral.", workingLatex: "I(x) = \\int_{-\\infty}^{\\infty} \\frac{s^{2}}{x}\\,e^{-s^{2}}\\,\\frac{ds}{\\sqrt{x}} = \\frac{1}{x^{3/2}}\\int_{-\\infty}^{\\infty} s^{2} e^{-s^{2}}\\,ds.", explanation: "All the \\(x\\)-dependence factors out as \\(x^{-3/2}\\)." },
        { stepNumber: 4, description: "Evaluate the standard moment.", workingLatex: "\\int_{-\\infty}^{\\infty} s^{2} e^{-s^{2}}\\,ds = \\frac{\\sqrt{\\pi}}{2}.", explanation: "A standard Gaussian second moment." },
        { stepNumber: 5, description: "Assemble and conclude.", workingLatex: "I(x) \\sim \\frac{\\sqrt{\\pi}}{2}\\,x^{-3/2}, \\qquad x \\to \\infty.", explanation: "Because the amplitude vanishes quadratically at the peak, the decay is \\(x^{-3/2}\\) instead of \\(x^{-1/2}\\). This matches the exact value \\(\\tfrac12\\sqrt{\\pi}\\,x^{-3/2}\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{\\sqrt{\\pi}}{2}\\,x^{-3/2} \\)",
      canonicalAnswer: "(sqrt(pi)/2)*x^(-3/2)",
    },
  },
  {
    id: "am4a-022",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the two-term asymptotic expansion as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{t}\\,e^{-x t^{2}/2}\\,dt \\), and verify it against the exact closed form.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "two-term expansion", "completing the square"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Combine the exponents.", workingLatex: "e^{t}e^{-x t^{2}/2} = \\exp\\!\\left(-\\frac{x}{2}t^{2} + t\\right).", explanation: "The amplitude \\(e^t\\) is not slowly varying, but here it can be merged with the phase and the integral done exactly — a useful exact benchmark for the method." },
        { stepNumber: 2, description: "Complete the square.", workingLatex: "-\\frac{x}{2}t^{2} + t = -\\frac{x}{2}\\left(t - \\frac{1}{x}\\right)^{2} + \\frac{1}{2x}.", explanation: "Completing the square shifts the effective peak to \\(t=1/x\\) and produces a constant \\(\\tfrac{1}{2x}\\)." },
        { stepNumber: 3, description: "Evaluate the shifted Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-\\frac{x}{2}(t - 1/x)^{2}}\\,dt = \\sqrt{\\frac{2\\pi}{x}}.", explanation: "A translation of a Gaussian leaves the integral unchanged." },
        { stepNumber: 4, description: "Write the exact value.", workingLatex: "I(x) = \\sqrt{\\frac{2\\pi}{x}}\\;e^{1/(2x)}.", explanation: "Exact for all \\(x>0\\)." },
        { stepNumber: 5, description: "Expand the exponential factor.", workingLatex: "e^{1/(2x)} = 1 + \\frac{1}{2x} + O(x^{-2}).", explanation: "For large \\(x\\) the constant \\(\\tfrac{1}{2x}\\) is small, so a Taylor expansion gives the asymptotic series." },
        { stepNumber: 6, description: "State the two-term expansion.", workingLatex: "I(x) \\sim \\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{1}{2x} + \\cdots\\right), \\qquad x \\to \\infty.", explanation: "The leading term is the Laplace estimate with \\(g(t_0)=e^0=1\\); the correction encodes how the rapidly varying amplitude shifts the effective peak. The closed form matched mpmath to full precision." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\sqrt{\\frac{2\\pi}{x}}\\,e^{1/(2x)} \\sim \\sqrt{\\frac{2\\pi}{x}}\\left(1 + \\frac{1}{2x}\\right) \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(1/(2*x))",
    },
  },
  {
    id: "am4a-023",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By writing \\( n! = \\Gamma(n+1) = \\int_{0}^{\\infty} t^{n} e^{-t}\\,dt \\) and substituting \\( t = n s \\), use Laplace's method to derive Stirling's formula \\( n! \\sim \\sqrt{2\\pi n}\\,\\left(\\frac{n}{e}\\right)^{n} \\) as \\( n \\to \\infty \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "Stirling's formula", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute to expose a large parameter.", workingLatex: "n! = \\int_{0}^{\\infty} t^{n} e^{-t}\\,dt = n^{n+1}\\int_{0}^{\\infty} e^{n(\\ln s - s)}\\,ds.", explanation: "With \\(t=ns\\) we get \\(t^n=n^n s^n\\), \\(e^{-t}=e^{-ns}\\), \\(dt=n\\,ds\\), and \\(s^n=e^{n\\ln s}\\). The exponent is now \\(n\\phi(s)\\) with the large parameter \\(n\\) out front." },
        { stepNumber: 2, description: "Identify the phase and its maximum.", workingLatex: "\\phi(s) = \\ln s - s, \\quad \\phi'(s) = \\frac{1}{s} - 1 = 0 \\;\\Rightarrow\\; s_{0} = 1.", explanation: "The peak of the integrand sits at \\(s_0=1\\), i.e. \\(t=n\\), interior to \\((0,\\infty)\\)." },
        { stepNumber: 3, description: "Phase value and curvature at the peak.", workingLatex: "\\phi(1) = \\ln 1 - 1 = -1, \\qquad \\phi''(s) = -\\frac{1}{s^{2}} \\;\\Rightarrow\\; \\phi''(1) = -1.", explanation: "Peak height \\(-1\\) gives the \\(e^{-n}\\) factor; curvature magnitude \\(1\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula to the integral.", workingLatex: "\\int_{0}^{\\infty} e^{n(\\ln s - s)}\\,ds \\sim e^{-n}\\sqrt{\\frac{2\\pi}{n\\cdot 1}} = e^{-n}\\sqrt{\\frac{2\\pi}{n}}.", explanation: "The amplitude is \\(1\\), so \\(g(s_0)=1\\); the maximum is interior so the full Gaussian width contributes." },
        { stepNumber: 5, description: "Reinstate the prefactor.", workingLatex: "n! \\sim n^{n+1}\\,e^{-n}\\sqrt{\\frac{2\\pi}{n}}.", explanation: "Multiply back the \\(n^{n+1}\\) pulled out in step 1." },
        { stepNumber: 6, description: "Simplify to Stirling's formula.", workingLatex: "n! \\sim n^{n}\\,e^{-n}\\,n\\cdot\\frac{\\sqrt{2\\pi}}{\\sqrt n} = \\sqrt{2\\pi n}\\,\\left(\\frac{n}{e}\\right)^{n}, \\qquad n \\to \\infty.", explanation: "Combining \\(n^{n+1}/\\sqrt n = n^{n}\\sqrt n\\) with \\(\\sqrt{2\\pi}\\) gives \\(\\sqrt{2\\pi n}\\). This is the canonical illustration of Laplace's method at an interior maximum." },
      ],
      finalAnswer: "\\( \\displaystyle n! \\sim \\sqrt{2\\pi n}\\,\\left(\\frac{n}{e}\\right)^{n} \\)",
      canonicalAnswer: "sqrt(2*pi*n)*(n/e)^n",
    },
  },
  {
    id: "am4a-024",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{0}^{\\infty} \\frac{e^{-x(t - \\ln t)}}{\\sqrt{t}}\\,dt \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write in standard form.", workingLatex: "I(x) = \\int_{0}^{\\infty} g(t)\\,e^{x\\phi(t)}\\,dt, \\quad \\phi(t) = -(t - \\ln t), \\quad g(t) = t^{-1/2}.", explanation: "The minus sign means the integrand peaks where \\(t-\\ln t\\) is smallest." },
        { stepNumber: 2, description: "Locate the interior maximum of the phase.", workingLatex: "\\phi'(t) = -\\left(1 - \\frac{1}{t}\\right) = 0 \\;\\Rightarrow\\; t_{0} = 1.", explanation: "Stationary point at \\(t_0=1\\), interior to \\((0,\\infty)\\)." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "\\phi(1) = -(1 - 0) = -1, \\qquad \\phi''(t) = -\\frac{1}{t^{2}} \\;\\Rightarrow\\; \\phi''(1) = -1.", explanation: "Peak height \\(-1\\) (giving \\(e^{-x}\\)); curvature magnitude \\(1\\)." },
        { stepNumber: 4, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = 1^{-1/2} = 1.", explanation: "The amplitude is smooth and nonzero at \\(t_0=1\\)." },
        { stepNumber: 5, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot e^{-x}\\sqrt{\\frac{2\\pi}{x\\cdot 1}} = e^{-x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "All ingredients combine in the master formula; verified numerically against the integral at large \\(x\\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{-x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(-x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-025",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{0}^{\\infty} e^{-x(t + \\frac{1}{t})}\\,dt \\), an integral related to the modified Bessel function \\( K_{1} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "Bessel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write in standard form.", workingLatex: "I(x) = \\int_{0}^{\\infty} e^{x\\phi(t)}\\,dt, \\qquad \\phi(t) = -\\left(t + \\frac{1}{t}\\right).", explanation: "The integrand is largest where \\(t+1/t\\) is smallest, by AM–GM at \\(t=1\\)." },
        { stepNumber: 2, description: "Locate the interior maximum.", workingLatex: "\\phi'(t) = -\\left(1 - \\frac{1}{t^{2}}\\right) = 0 \\;\\Rightarrow\\; t_{0} = 1.", explanation: "The single interior stationary point is at \\(t_0=1\\)." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "\\phi(1) = -(1 + 1) = -2, \\qquad \\phi''(t) = -\\frac{2}{t^{3}} \\;\\Rightarrow\\; \\phi''(1) = -2.", explanation: "Peak height \\(-2\\) gives \\(e^{-2x}\\); curvature magnitude \\(2\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{-2x}\\sqrt{\\frac{2\\pi}{2x}} = e^{-2x}\\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "With \\(g\\equiv1\\). Since \\(I(x)=2K_1(2x)\\) and \\(K_1(z)\\sim\\sqrt{\\pi/(2z)}\\,e^{-z}\\), setting \\(z=2x\\) reproduces this exactly." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{-2x}\\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(-2*x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4a-026",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The integral \\( I(x) = \\int_{0}^{\\pi} \\sin t\\;e^{x\\sin t}\\,dt \\) has an interior maximum of its phase. Find the leading-order behaviour as \\( x \\to \\infty \\), and comment on the role of the amplitude.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify phase, peak and amplitude.", workingLatex: "\\phi(t) = \\sin t, \\quad t_{0} = \\frac{\\pi}{2}, \\quad g(t) = \\sin t.", explanation: "Both the phase and the amplitude are \\(\\sin t\\), maximal at \\(t_0=\\pi/2\\)." },
        { stepNumber: 2, description: "Phase value and curvature.", workingLatex: "\\phi\\!\\left(\\tfrac{\\pi}{2}\\right) = 1, \\qquad \\phi''\\!\\left(\\tfrac{\\pi}{2}\\right) = -1.", explanation: "Curvature magnitude \\(1\\) at the interior peak." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = \\sin\\frac{\\pi}{2} = 1.", explanation: "The amplitude is at its own maximum here, but only its value \\(g(t_0)=1\\) (not its flatness) enters at leading order." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot e^{x}\\sqrt{\\frac{2\\pi}{x}} = e^{x}\\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Because \\(g(t_0)=1\\), the result coincides with the bare phase integral \\(\\int_0^\\pi e^{x\\sin t}dt\\) at leading order; the amplitude alters only the higher-order corrections." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-027",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{x(\\cos t - 1)}\\,dt \\) (taking the integral over one full period to be representative of the local Gaussian).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant peak.", workingLatex: "\\phi(t) = \\cos t - 1, \\quad \\phi(t) \\le 0, \\quad \\phi(0) = 0.", explanation: "The phase attains its maximum value \\(0\\) at \\(t=0\\) (and at every \\(2\\pi k\\)); near each peak the contribution is an identical Gaussian. We focus on the peak at \\(t_0=0\\)." },
        { stepNumber: 2, description: "Stationarity and curvature.", workingLatex: "\\phi'(t) = -\\sin t = 0 \\text{ at } t_{0}=0, \\qquad \\phi''(0) = -\\cos 0 = -1.", explanation: "Curvature magnitude \\(1\\)." },
        { stepNumber: 3, description: "Apply Laplace's formula to one peak.", workingLatex: "I_{\\text{peak}}(x) \\sim e^{0}\\sqrt{\\frac{2\\pi}{x}} = \\sqrt{\\frac{2\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "Each Gaussian bump contributes \\(\\sqrt{2\\pi/x}\\); the subtraction of \\(1\\) in the phase normalises the peak height to \\(0\\), so there is no exponential factor. (For the genuinely infinite range the peaks accumulate, but the local interior-maximum estimate per period is exactly this.)" },
      ],
      finalAnswer: "\\( \\displaystyle I_{\\text{peak}}(x) \\sim \\sqrt{\\frac{2\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(2*pi/x)",
    },
  },
  {
    id: "am4a-028",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of the ratio \\( R(x) = \\dfrac{\\int_{-\\infty}^{\\infty} t^{2} e^{x\\cos t - x}\\,dt}{\\int_{-\\infty}^{\\infty} e^{x\\cos t - x}\\,dt} \\) over a single period centred at \\( t = 0 \\). (This is the variance of the von Mises distribution at large concentration.)",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "moments", "ratio"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the phase about the peak.", workingLatex: "\\cos t - 1 = -\\frac{t^{2}}{2} + O(t^{4}), \\qquad t_{0} = 0.", explanation: "Near the peak the weight is approximately Gaussian, \\(e^{x(\\cos t-1)}\\approx e^{-x t^2/2}\\), with curvature \\(|\\phi''|=1\\)." },
        { stepNumber: 2, description: "Approximate the denominator.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x t^{2}/2}\\,dt = \\sqrt{\\frac{2\\pi}{x}}.", explanation: "The normalising Gaussian integral; the dropped \\(e^{x}\\) factor cancels in the ratio anyway." },
        { stepNumber: 3, description: "Approximate the numerator.", workingLatex: "\\int_{-\\infty}^{\\infty} t^{2}\\,e^{-x t^{2}/2}\\,dt = \\frac{1}{x}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "The second moment of a Gaussian of variance \\(1/x\\): \\(\\langle t^2\\rangle\\) times the normalisation, where \\(\\langle t^2\\rangle = 1/x\\)." },
        { stepNumber: 4, description: "Form the ratio.", workingLatex: "R(x) = \\frac{\\frac{1}{x}\\sqrt{2\\pi/x}}{\\sqrt{2\\pi/x}} = \\frac{1}{x}.", explanation: "The common Gaussian normalisation cancels, leaving just the variance." },
        { stepNumber: 5, description: "State the result.", workingLatex: "R(x) \\sim \\frac{1}{x}, \\qquad x \\to \\infty.", explanation: "The effective variance about the interior maximum is \\(1/(x|\\phi''(t_0)|)=1/x\\) — exactly the width of the Laplace Gaussian. This is why the von Mises distribution sharpens like \\(1/\\sqrt{x}\\)." },
      ],
      finalAnswer: "\\( \\displaystyle R(x) \\sim \\frac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am4a-029",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\cosh(\\alpha t)\\,dt \\) for a fixed constant \\( \\alpha \\), and compare with the exact value.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "amplitude factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate phase and amplitude.", workingLatex: "\\phi(t) = -t^{2}, \\quad g(t) = \\cosh(\\alpha t), \\quad t_{0} = 0.", explanation: "The Gaussian weight peaks at \\(t_0=0\\); the amplitude \\(\\cosh(\\alpha t)\\) is smooth and even." },
        { stepNumber: 2, description: "Phase data at the peak.", workingLatex: "\\phi(0) = 0, \\qquad \\phi''(0) = -2 \\;\\Rightarrow\\; |\\phi''(0)| = 2.", explanation: "Curvature magnitude \\(2\\)." },
        { stepNumber: 3, description: "Amplitude at the peak.", workingLatex: "g(t_{0}) = \\cosh 0 = 1.", explanation: "At leading order only \\(g(0)=1\\) survives, independent of \\(\\alpha\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim 1\\cdot\\sqrt{\\frac{2\\pi}{2x}} = \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "The leading term does not depend on \\(\\alpha\\) because the amplitude is flat (slope \\(0\\)) at the symmetric peak." },
        { stepNumber: 5, description: "Compare with the exact value.", workingLatex: "I(x) = \\sqrt{\\frac{\\pi}{x}}\\;e^{\\alpha^{2}/(4x)} \\sim \\sqrt{\\frac{\\pi}{x}}\\left(1 + \\frac{\\alpha^{2}}{4x} + \\cdots\\right).", explanation: "Completing the square in \\(-xt^2\\pm\\alpha t\\) gives the exact closed form; its leading term confirms the Laplace estimate, and the \\(\\alpha^2/(4x)\\) correction shows where the amplitude's curvature first enters." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4a-030",
    topicRef: "am4a",
    topicTitle: "Laplace's method: interior maximum 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( I(x) = \\int_{-\\pi/2}^{\\pi/2} e^{-x\\sin^{2} t}\\,dt \\), where the phase \\( \\phi(t) = -\\sin^{2} t \\) has an interior maximum.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the phase and its maximum.", workingLatex: "\\phi(t) = -\\sin^{2} t, \\quad \\phi'(t) = -2\\sin t\\cos t = -\\sin 2t = 0 \\;\\Rightarrow\\; t_{0} = 0.", explanation: "On \\((-\\pi/2,\\pi/2)\\) the phase is maximal where \\(\\sin t=0\\), i.e. at the interior point \\(t_0=0\\)." },
        { stepNumber: 2, description: "Phase value at the peak.", workingLatex: "\\phi(0) = -\\sin^{2} 0 = 0.", explanation: "Peak height \\(0\\), so there is no exponential prefactor." },
        { stepNumber: 3, description: "Compute the curvature.", workingLatex: "\\phi''(t) = -2\\cos 2t \\;\\Rightarrow\\; \\phi''(0) = -2.", explanation: "Differentiate \\(-\\sin 2t\\): \\(\\phi''(t)=-2\\cos 2t\\), giving \\(|\\phi''(0)|=2\\). Equivalently \\(\\sin^2 t = t^2 + O(t^4)\\), so \\(\\phi\\approx -t^2\\)." },
        { stepNumber: 4, description: "Apply Laplace's formula.", workingLatex: "I(x) \\sim e^{0}\\sqrt{\\frac{2\\pi}{2x}} = \\sqrt{\\frac{\\pi}{x}}, \\qquad x \\to \\infty.", explanation: "With \\(g\\equiv1\\), peak height \\(0\\) and curvature magnitude \\(2\\), the master formula gives \\(\\sqrt{\\pi/x}\\); confirmed numerically." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\sqrt{\\frac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
];
