import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Laplace's Method
 * Subtopic am4b: Endpoint maxima & half-Gaussian factors
 * Ref: am4b — 30 fully-worked, numerically-verified questions.
 *
 * Scope:
 *   - Maximum of the exponent at an endpoint of the range.
 *   - The factor of 1/2 from integrating only half the Gaussian peak
 *       int_a^b e^{x phi(t)} dt ~ e^{x phi(a)} (1/2) sqrt( 2 pi / (x |phi''(a)|) )   (phi'(a)=0)
 *   - Sub-Gaussian (linear) endpoints, where phi'(a) != 0 and the balance is linear:
 *       int_a^b e^{x phi(t)} dt ~ e^{x phi(a)} / ( x |phi'(a)| )                      (phi'(a)<0)
 *     giving a 1/x decay (one inverse power of x) rather than 1/sqrt(x).
 *
 * Seeded from Cambridge Part II Asymptotic Methods, Example Sheet 1
 * (Q1 Gamma(1/2), Q11 I1/I2, Q12, Q13), with all constants/limits/framing varied.
 *
 * VERIFICATION: every numeric leading/subleading coefficient below was checked with
 * mpmath against the exact integral at large x (ratios -> 1). Pure-derivation
 * questions (general theorem, "show that the 1/2 arises") carry a // REVIEW note.
 *
 * Style: graduate "fully-detailed" — each step has a real workingLatex transition and a
 * substantive prose explanation; worked-solution fractions use big \\frac.
 */
export const questions: Question[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // FOUNDATION (6) — core technique in isolation, 2 marks, examStyle:false
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am4b-001",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t \\), and state explicitly the factor of \\( \\tfrac{1}{2} \\) relative to the full Gaussian integral over \\( (-\\infty, \\infty) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum", "half-Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum of the exponent.", workingLatex: "\\phi(t) = -t^2, \\qquad \\phi'(t) = -2t, \\qquad \\phi'(t) = 0 \\iff t = 0.", explanation: "The exponent \\( -t^2 \\) is largest where it is closest to zero. Its only stationary point is \\( t=0 \\), which sits exactly on the lower limit of the range, so the dominant contribution comes from an endpoint, not from an interior point." },
        { stepNumber: 2, description: "Recall the full Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\sqrt{\\frac{\\pi}{x}}.", explanation: "This is the standard Gaussian. The peak at \\( t=0 \\) is symmetric, so an integral over the full line collects the contribution from both sides of the maximum." },
        { stepNumber: 3, description: "Take half the peak.", workingLatex: "\\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2}\\int_{-\\infty}^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Because the integrand is even and the lower limit cuts the peak exactly in two at its centre, we keep only half of the symmetric Gaussian mass. This is the origin of the factor of \\( \\tfrac{1}{2} \\) characteristic of an endpoint maximum where \\( \\phi'=0 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-002",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of the linear-endpoint integral \\( \\displaystyle I(x) = \\int_0^{1} e^{-x t}\\,\\mathrm{d}t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "sub-Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the endpoint and the sign of the slope.", workingLatex: "\\phi(t) = -t, \\qquad \\phi'(t) = -1 \\ (\\neq 0).", explanation: "The exponent decreases steadily, so it is largest at the left endpoint \\( t=0 \\). Crucially \\( \\phi'(0) = -1 \\neq 0 \\): the maximum is a corner of the range, not a smooth interior peak, so there is no Gaussian and no \\( \\tfrac{1}{2} \\) factor." },
        { stepNumber: 2, description: "Evaluate the integral exactly.", workingLatex: "\\int_0^{1} e^{-x t}\\,\\mathrm{d}t = \\left[ -\\frac{1}{x} e^{-x t} \\right]_0^{1} = \\frac{1 - e^{-x}}{x}.", explanation: "With a purely linear exponent the integral is elementary, which lets us read off the asymptotics directly and confirm the general rule." },
        { stepNumber: 3, description: "Discard the exponentially small term.", workingLatex: "\\frac{1 - e^{-x}}{x} \\sim \\frac{1}{x} \\qquad (x \\to \\infty).", explanation: "The term \\( e^{-x}/x \\) is exponentially smaller than every inverse power of \\( x \\), so it is beyond all orders of the asymptotic series. A linear (sub-Gaussian) endpoint gives a single inverse power, \\( 1/x \\), in contrast to the \\( x^{-1/2} \\) of a half-Gaussian endpoint." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{x} \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am4b-003",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using the substitution \\( u = \\sqrt{x}\\,t \\), or otherwise, evaluate \\( \\displaystyle \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t \\) exactly in terms of \\( \\Gamma\\!\\left(\\tfrac12\\right) \\), and hence in terms of \\( \\pi \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gamma function", "half-Gaussian", "endpoint maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale to remove x from the exponent.", workingLatex: "u = \\sqrt{x}\\,t, \\qquad \\mathrm{d}t = \\frac{\\mathrm{d}u}{\\sqrt{x}}, \\qquad \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{\\sqrt{x}}\\int_0^{\\infty} e^{-u^2}\\,\\mathrm{d}u.", explanation: "Scaling the variable by \\( \\sqrt{x} \\) is exactly the Laplace-method rescaling: it stretches the narrow peak near the endpoint to width \\( O(1) \\) and pulls all the \\( x \\)-dependence out as a prefactor." },
        { stepNumber: 2, description: "Recognise the half-Gaussian as a Gamma value.", workingLatex: "\\int_0^{\\infty} e^{-u^2}\\,\\mathrm{d}u \\overset{v=u^2}{=} \\frac{1}{2}\\int_0^{\\infty} v^{-1/2} e^{-v}\\,\\mathrm{d}v = \\frac{1}{2}\\,\\Gamma\\!\\left(\\frac{1}{2}\\right).", explanation: "Substituting \\( v=u^2 \\) turns the half-Gaussian into the integral definition of \\( \\Gamma(\\tfrac12) = \\int_0^\\infty v^{-1/2}e^{-v}\\,\\mathrm{d}v \\). The leading \\( \\tfrac12 \\) is the Jacobian \\( \\mathrm{d}u = \\tfrac12 v^{-1/2}\\mathrm{d}v \\) — the same half that appears for an endpoint maximum." },
        { stepNumber: 3, description: "Insert the value of the Gamma function.", workingLatex: "\\Gamma\\!\\left(\\frac{1}{2}\\right) = \\sqrt{\\pi} \\ \\Longrightarrow\\ \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2\\sqrt{x}}\\,\\Gamma\\!\\left(\\frac{1}{2}\\right) = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The classical value \\( \\Gamma(\\tfrac12)=\\sqrt\\pi \\) (Example Sheet Q1) closes the calculation and reproduces the half-Gaussian coefficient \\( \\tfrac12\\sqrt{\\pi/x} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\frac{1}{2\\sqrt{x}}\\,\\Gamma\\!\\left(\\tfrac12\\right) = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\).",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-004",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The exponent of \\( \\displaystyle \\int_0^{1} e^{x t}\\,\\mathrm{d}t \\) is maximised at the upper endpoint \\( t=1 \\). Find the leading-order behaviour as \\( x \\to \\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "upper endpoint"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the dominant endpoint.", workingLatex: "\\phi(t) = t, \\qquad \\phi'(t) = 1 > 0,", explanation: "The exponent increases across the range, so it attains its maximum at the upper limit \\( t=1 \\). The slope there is non-zero, so this is a linear (sub-Gaussian) endpoint." },
        { stepNumber: 2, description: "Evaluate exactly.", workingLatex: "\\int_0^{1} e^{x t}\\,\\mathrm{d}t = \\left[ \\frac{1}{x} e^{x t} \\right]_0^{1} = \\frac{e^{x} - 1}{x}.", explanation: "Again the linear exponent integrates in closed form, exposing the asymptotic structure." },
        { stepNumber: 3, description: "Keep the dominant term.", workingLatex: "\\frac{e^{x} - 1}{x} \\sim \\frac{e^{x}}{x} \\qquad (x \\to \\infty).", explanation: "The \\( -1/x \\) is exponentially negligible against \\( e^{x}/x \\). The result is the endpoint formula \\( e^{x\\phi(1)}/(x\\,|\\phi'(1)|) \\) with \\( \\phi(1)=1 \\) and \\( |\\phi'(1)|=1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{e^{x}}{x} \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "exp(x)/x",
    },
  },
  {
    id: "am4b-005",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\infty} t\\, e^{-x t^2}\\,\\mathrm{d}t \\). Comment on why the power of \\( x \\) differs from the half-Gaussian \\( x^{-1/2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "vanishing prefactor", "half-Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the prefactor vanishes at the peak.", workingLatex: "g(t) = t, \\qquad g(0) = 0, \\qquad \\phi(t) = -t^2 \\ \\text{peaks at}\\ t=0.", explanation: "The exponent peaks at the endpoint \\( t=0 \\), but the algebraic prefactor \\( g(t)=t \\) is zero there. The integrand is therefore suppressed exactly where the exponential is largest, which removes one half-power of \\( x \\)." },
        { stepNumber: 2, description: "Evaluate exactly.", workingLatex: "\\int_0^{\\infty} t\\, e^{-x t^2}\\,\\mathrm{d}t = \\left[ -\\frac{1}{2x} e^{-x t^2} \\right]_0^{\\infty} = \\frac{1}{2x}.", explanation: "With the prefactor \\( t \\) supplying the derivative of the exponent, the integral is elementary." },
        { stepNumber: 3, description: "Compare with the pure half-Gaussian.", workingLatex: "I(x) = \\frac{1}{2x} = O\\!\\left(x^{-1}\\right) \\quad \\text{vs.} \\quad \\int_0^\\infty e^{-xt^2}\\mathrm{d}t = O\\!\\left(x^{-1/2}\\right).", explanation: "A prefactor vanishing linearly at the endpoint costs an extra half-power: \\( x^{-1/2}\\to x^{-1} \\). More generally a prefactor \\( \\sim t^{\\mu} \\) gives \\( x^{-(\\mu+1)/2} \\), via Watson's lemma." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\frac{1}{2x} \\); the linear prefactor kills the peak, raising the decay from \\( x^{-1/2} \\) to \\( x^{-1} \\).",
      canonicalAnswer: "1/(2*x)",
    },
  },
  {
    id: "am4b-006",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "An endpoint maximum at \\( t=a \\) with \\( \\phi'(a)=0 \\) and \\( \\phi''(a)<0 \\) gives the half-Gaussian coefficient. Write down the leading-order Laplace estimate of \\( \\displaystyle \\int_a^{b} e^{x \\phi(t)}\\,\\mathrm{d}t \\) for such a case, and apply it to \\( \\displaystyle \\int_0^{\\pi/2} e^{-x \\sin^2 t}\\,\\mathrm{d}t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "endpoint formula"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the half-Gaussian endpoint formula.", workingLatex: "\\int_a^{b} e^{x \\phi(t)}\\,\\mathrm{d}t \\sim e^{x \\phi(a)}\\,\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(a)|}}.", explanation: "This is the interior-maximum Laplace formula with the extra factor of \\( \\tfrac12 \\), because the endpoint cuts the Gaussian peak in half." },
        { stepNumber: 2, description: "Check the hypotheses for the given integral.", workingLatex: "\\phi(t) = -\\sin^2 t, \\quad \\phi'(t) = -2\\sin t\\cos t = -\\sin 2t, \\quad \\phi'(0)=0, \\quad \\phi''(0) = -2.", explanation: "The maximum of \\( -\\sin^2 t \\) is at the endpoint \\( t=0 \\) with zero slope and curvature \\( -2 \\), so the half-Gaussian formula applies with \\( \\phi(0)=0 \\)." },
        { stepNumber: 3, description: "Substitute the data.", workingLatex: "\\int_0^{\\pi/2} e^{-x\\sin^2 t}\\,\\mathrm{d}t \\sim \\frac{1}{2}\\sqrt{\\frac{2\\pi}{2x}} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "With \\( |\\phi''(0)|=2 \\) the \\( 2 \\)s cancel and we recover the clean \\( \\tfrac12\\sqrt{\\pi/x} \\); numerically the ratio of integral to estimate tends to \\( 1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\).",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STANDARD (12) — typical sheet-level, 3–4 marks, examStyle:true
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am4b-007",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order asymptotic behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\pi/2} e^{x \\cos t}\\,\\mathrm{d}t \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "endpoint maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find where the exponent is maximal.", workingLatex: "\\phi(t) = \\cos t, \\qquad \\phi'(t) = -\\sin t, \\qquad \\phi'(0) = 0.", explanation: "On \\( [0,\\pi/2] \\) the cosine decreases from \\( 1 \\) to \\( 0 \\), so its maximum is at the left endpoint \\( t=0 \\), where moreover the slope vanishes — a half-Gaussian endpoint." },
        { stepNumber: 2, description: "Expand the exponent about the endpoint.", workingLatex: "\\cos t = 1 - \\frac{t^2}{2} + O(t^4), \\qquad \\phi''(0) = -1.", explanation: "Near the peak only the quadratic term matters at leading order. The curvature \\( \\phi''(0)=-1 \\) sets the Gaussian width." },
        { stepNumber: 3, description: "Localise and extend the range.", workingLatex: "I(x) \\sim e^{x}\\int_0^{\\infty} e^{-x t^2/2}\\,\\mathrm{d}t.", explanation: "Factor out \\( e^{x\\phi(0)}=e^x \\). The integrand is sharply peaked at \\( t=0 \\), so extending the upper limit to \\( \\infty \\) introduces only exponentially small error." },
        { stepNumber: 4, description: "Apply the half-Gaussian integral.", workingLatex: "\\int_0^{\\infty} e^{-x t^2/2}\\,\\mathrm{d}t = \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}} = \\sqrt{\\frac{\\pi}{2x}}.", explanation: "Half of the Gaussian \\( \\int_{-\\infty}^\\infty e^{-xt^2/2}\\mathrm{d}t = \\sqrt{2\\pi/x} \\). The \\( \\tfrac12 \\) is the endpoint factor." },
        { stepNumber: 5, description: "Assemble the leading term.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}.", explanation: "A numerical check at \\( x=800 \\) gives a ratio of integral to estimate of \\( 1.0002 \\), confirming the coefficient." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}} \\).",
      canonicalAnswer: "exp(x)*sqrt(pi/(2*x))",
    },
  },
  {
    id: "am4b-008",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\pi/2} e^{-x \\sin t}\\,\\mathrm{d}t \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "sub-Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the maximum and its character.", workingLatex: "\\phi(t) = -\\sin t, \\qquad \\phi'(t) = -\\cos t, \\qquad \\phi'(0) = -1 \\neq 0.", explanation: "The exponent is largest at \\( t=0 \\), where \\( \\sin t \\) is smallest. The slope is non-zero there, so this is a linear endpoint and we expect a \\( 1/x \\) law, not \\( x^{-1/2} \\)." },
        { stepNumber: 2, description: "Linearise the exponent near the endpoint.", workingLatex: "\\sin t = t + O(t^3), \\qquad e^{-x\\sin t} \\approx e^{-x t}.", explanation: "Only the slope at the endpoint matters at leading order; the cubic correction shifts only higher-order terms." },
        { stepNumber: 3, description: "Localise and extend the range.", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t}\\,\\mathrm{d}t = \\frac{1}{x}.", explanation: "The contribution decays over a boundary layer of width \\( O(1/x) \\), so extending to \\( \\infty \\) costs only exponentially small error. The endpoint formula \\( e^{x\\phi(0)}/(x|\\phi'(0)|) \\) gives \\( 1/x \\) since \\( \\phi(0)=0,\\ |\\phi'(0)|=1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{x} \\) as \\( x \\to \\infty \\).",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am4b-009",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms in the asymptotic expansion as \\( x \\to \\infty \\) of the linear-endpoint integral \\( \\displaystyle I(x) = \\int_0^{1} e^{-x (t + t^2)}\\,\\mathrm{d}t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "sub-Gaussian", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the endpoint and the exponent.", workingLatex: "g(t) = t + t^2, \\qquad g(0) = 0, \\qquad g'(0) = 1, \\qquad g''(0) = 2.", explanation: "Write \\( I = \\int_0^1 e^{-x g(t)}\\,\\mathrm{d}t \\) with \\( g \\) increasing from \\( 0 \\); the minimum of \\( g \\) (maximum of the integrand) is the linear endpoint \\( t=0 \\)." },
        { stepNumber: 2, description: "Change variable to the exponent.", workingLatex: "s = g(t) = t + t^2 \\ \\Longrightarrow\\ t = \\frac{-1 + \\sqrt{1 + 4s}}{2}, \\qquad \\frac{\\mathrm{d}t}{\\mathrm{d}s} = \\frac{1}{1 + 2t}.", explanation: "Substituting \\( s=g(t) \\) flattens the exponent to \\( -xs \\); all the structure now lives in the Jacobian, which we expand for small \\( s \\)." },
        { stepNumber: 3, description: "Expand the Jacobian in powers of s.", workingLatex: "\\frac{\\mathrm{d}t}{\\mathrm{d}s} = \\frac{1}{1 + 2t} = 1 - 2t + \\cdots = 1 - 2s + O(s^2),", explanation: "Since \\( t = s - s^2 + \\cdots \\) near \\( s=0 \\), we have \\( 1+2t = 1+2s+\\cdots \\) and so \\( (1+2t)^{-1} = 1 - 2s + \\cdots \\). Each power of \\( s \\) under \\( e^{-xs} \\) will contribute one further inverse power of \\( x \\)." },
        { stepNumber: 4, description: "Integrate term by term (Watson's lemma).", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x s}\\,(1 - 2s)\\,\\mathrm{d}s = \\frac{1}{x} - 2\\cdot\\frac{1}{x^2}.", explanation: "Using \\( \\int_0^\\infty s^n e^{-xs}\\mathrm{d}s = n!/x^{n+1} \\): the \\( 1 \\) gives \\( 1/x \\), the \\( -2s \\) gives \\( -2/x^2 \\)." },
        { stepNumber: 5, description: "State the two-term expansion.", workingLatex: "I(x) \\sim \\frac{1}{x} - \\frac{2}{x^2}.", explanation: "Numerically \\( x^2(xI - 1) \\to -2 \\) as \\( x \\) grows (\\( -1.94 \\) at \\( x=200 \\), \\( -1.996 \\) at \\( x=3200 \\)), confirming the subleading coefficient." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{x} - \\frac{2}{x^2} \\).",
      canonicalAnswer: "1/x - 2/x^2",
    },
  },
  {
    id: "am4b-010",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{-x t^2}(1 + t)\\,\\mathrm{d}t \\), and identify which part of the prefactor survives at leading order.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "algebraic prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the peak and the prefactor value there.", workingLatex: "\\phi(t) = -t^2 \\ \\text{peaks at}\\ t=0, \\qquad g(t)=1+t, \\qquad g(0)=1.", explanation: "Half-Gaussian endpoint at \\( t=0 \\). Because the prefactor \\( g \\) does not vanish at the peak, only its value \\( g(0)=1 \\) matters at leading order; the \\( t \\) part is subdominant since it vanishes at the peak." },
        { stepNumber: 2, description: "Replace the prefactor by its endpoint value.", workingLatex: "I(x) \\sim g(0)\\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = 1 \\cdot \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t.", explanation: "Over the boundary layer of width \\( O(x^{-1/2}) \\) we may set \\( g(t)\\approx g(0) \\); extending the limit to \\( \\infty \\) is exponentially accurate." },
        { stepNumber: 3, description: "Evaluate the half-Gaussian.", workingLatex: "I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The surviving piece is the half-Gaussian with coefficient \\( g(0)\\cdot\\tfrac12\\sqrt{\\pi/x} \\). The \\( t \\) term contributes at order \\( 1/x \\), one half-power down." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\); only \\( g(0)=1 \\) survives at leading order.",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-011",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Use Laplace's method to find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{2} e^{x(2t - t^2)}\\,\\mathrm{d}t \\). State carefully whether the maximum is interior or at an endpoint.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior vs endpoint", "no half factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the stationary point.", workingLatex: "\\phi(t) = 2t - t^2, \\qquad \\phi'(t) = 2 - 2t = 0 \\iff t = 1.", explanation: "The maximum is at \\( t=1 \\), which lies strictly inside \\( (0,2) \\). This is a genuine interior maximum, so the full Gaussian applies and there is NO factor of \\( \\tfrac12 \\) — a deliberate contrast to the endpoint cases." },
        { stepNumber: 2, description: "Evaluate the exponent and curvature at the peak.", workingLatex: "\\phi(1) = 1, \\qquad \\phi''(t) = -2, \\qquad \\phi''(1) = -2.", explanation: "The peak value sets the exponential scale \\( e^{x} \\); the curvature \\( -2 \\) sets the Gaussian width." },
        { stepNumber: 3, description: "Apply the interior-maximum Laplace formula.", workingLatex: "I(x) \\sim e^{x\\phi(1)}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(1)|}} = e^{x}\\sqrt{\\frac{2\\pi}{2x}}.", explanation: "Both shoulders of the Gaussian lie inside the range, so we keep the full \\( \\sqrt{2\\pi/(x|\\phi''|)} \\) with no halving." },
        { stepNumber: 4, description: "Simplify.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Compare with the endpoint result of am4b-007: an interior peak of the same curvature would be exactly twice the half-Gaussian endpoint value." },
      ],
      finalAnswer: "Interior maximum at \\( t=1 \\); \\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}} \\) (no \\( \\tfrac12 \\)).",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-012",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{-x t}\\,(1+t)\\,\\mathrm{d}t \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "algebraic prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the linear endpoint.", workingLatex: "\\phi(t) = -t, \\qquad \\phi'(0) = -1, \\qquad g(t) = 1+t, \\qquad g(0)=1.", explanation: "The exponent peaks at the left endpoint with non-zero slope. For a linear endpoint, the leading term is the prefactor evaluated at the endpoint divided by \\( x|\\phi'(0)| \\)." },
        { stepNumber: 2, description: "Replace the prefactor by its endpoint value.", workingLatex: "I(x) \\sim g(0)\\int_0^{\\infty} e^{-x t}\\,\\mathrm{d}t = 1 \\cdot \\frac{1}{x}.", explanation: "Over the \\( O(1/x) \\) boundary layer \\( g(t)\\approx g(0)=1 \\); the \\( t \\) part contributes at the next order, \\( 1/x^2 \\)." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "I(x) \\sim \\frac{1}{x}.", explanation: "Numerically \\( xI \\to 1 \\) (e.g. \\( 1.0025 \\) at \\( x=400 \\)); the leading behaviour is set purely by \\( g(0) \\) and the endpoint slope." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{x} \\).",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am4b-013",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} \\frac{e^{x t}}{\\sqrt{1 - t}}\\,\\mathrm{d}t \\), where the exponent is maximised at the upper endpoint \\( t=1 \\) at which the prefactor has an integrable singularity.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint singularity", "Watson's lemma", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Move the peak to the origin.", workingLatex: "s = 1 - t, \\qquad t = 1 - s, \\qquad I(x) = e^{x}\\int_0^{1} \\frac{e^{-x s}}{\\sqrt{s}}\\,\\mathrm{d}s.", explanation: "The exponent is largest at \\( t=1 \\); substituting \\( s=1-t \\) places the peak at \\( s=0 \\) and exposes the endpoint singularity \\( s^{-1/2} \\)." },
        { stepNumber: 2, description: "Extend the range and recognise a Gamma integral.", workingLatex: "I(x) \\sim e^{x}\\int_0^{\\infty} s^{-1/2} e^{-x s}\\,\\mathrm{d}s = e^{x}\\,\\Gamma\\!\\left(\\tfrac12\\right) x^{-1/2}.", explanation: "Watson's lemma: a prefactor \\( s^{\\mu-1} \\) at the endpoint gives \\( \\Gamma(\\mu)x^{-\\mu} \\). Here \\( \\mu=\\tfrac12 \\). Extending the upper limit to \\( \\infty \\) is exponentially accurate." },
        { stepNumber: 3, description: "Insert the Gamma value.", workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right) = \\sqrt{\\pi} \\ \\Longrightarrow\\ I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The integrable singularity produces the same \\( x^{-1/2} \\) power as a half-Gaussian, but for a quite different reason — and with coefficient \\( \\sqrt\\pi \\) rather than \\( \\tfrac12\\sqrt\\pi \\). Numerically the ratio is \\( 1 \\) to \\( 12 \\) s.f. at \\( x=400 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{x}} \\).",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-014",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\infty} e^{-x t}\\,\\sqrt{t}\\,\\mathrm{d}t \\), and state the general rule for a prefactor \\( t^{\\mu} \\) at a linear endpoint.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "linear endpoint", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise the Watson/Gamma form.", workingLatex: "\\int_0^{\\infty} e^{-x t}\\, t^{\\mu}\\,\\mathrm{d}t = \\frac{\\Gamma(\\mu+1)}{x^{\\mu+1}}.", explanation: "A linear endpoint at \\( t=0 \\) with an algebraic prefactor \\( t^{\\mu} \\) is exactly Watson's lemma: each power of \\( t \\) raises the inverse power of \\( x \\) by one and brings in a Gamma factor." },
        { stepNumber: 2, description: "Substitute \\( \\mu = \\tfrac12 \\).", workingLatex: "I(x) = \\frac{\\Gamma\\!\\left(\\tfrac32\\right)}{x^{3/2}}.", explanation: "Here \\( \\mu=\\tfrac12 \\), so the exponent of \\( x \\) is \\( \\mu+1=\\tfrac32 \\)." },
        { stepNumber: 3, description: "Evaluate the Gamma value.", workingLatex: "\\Gamma\\!\\left(\\tfrac32\\right) = \\tfrac12\\Gamma\\!\\left(\\tfrac12\\right) = \\frac{\\sqrt{\\pi}}{2} \\ \\Longrightarrow\\ I(x) = \\frac{\\sqrt{\\pi}}{2}\\,x^{-3/2}.", explanation: "Using \\( \\Gamma(\\tfrac32)=\\tfrac12\\sqrt\\pi \\). This is exact (not merely asymptotic) because the integral is a pure Gamma function; it matches the numerical value to full precision." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\frac{\\sqrt{\\pi}}{2}\\,x^{-3/2} \\); a prefactor \\( t^{\\mu} \\) gives \\( \\Gamma(\\mu+1)\\,x^{-(\\mu+1)} \\).",
      canonicalAnswer: "(sqrt(pi)/2)*x^(-3/2)",
    },
  },
  {
    id: "am4b-015",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{-x t^2}\\,\\cos t\\,\\mathrm{d}t \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "smooth prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the endpoint and prefactor value.", workingLatex: "\\phi(t) = -t^2 \\ \\text{peaks at}\\ t=0, \\qquad g(t) = \\cos t, \\qquad g(0)=1.", explanation: "Half-Gaussian endpoint at \\( t=0 \\); the smooth prefactor \\( \\cos t \\) takes value \\( 1 \\) there." },
        { stepNumber: 2, description: "Freeze the prefactor at the peak.", workingLatex: "I(x) \\sim \\cos(0)\\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t.", explanation: "On the \\( O(x^{-1/2}) \\) boundary layer \\( \\cos t \\approx 1 \\); the curvature of \\( \\cos t \\) feeds only into the \\( O(1/x) \\) correction." },
        { stepNumber: 3, description: "Apply the half-Gaussian.", workingLatex: "I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Same half-Gaussian coefficient as the bare integral, because \\( g(0)=1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\).",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-016",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_1^{\\infty} e^{-x t}\\,\\mathrm{d}t \\), an endpoint maximum at the finite lower limit \\( t=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "shifted endpoint"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant endpoint.", workingLatex: "\\phi(t) = -t, \\qquad \\phi'(t) = -1 < 0, \\qquad \\text{max at}\\ t=1.", explanation: "The exponent decreases, so it is largest at the lower limit \\( t=1 \\); the slope there is \\( -1 \\), a linear endpoint with \\( \\phi(1)=-1 \\)." },
        { stepNumber: 2, description: "Shift the endpoint to the origin.", workingLatex: "s = t - 1: \\quad I(x) = \\int_0^{\\infty} e^{-x(1+s)}\\,\\mathrm{d}s = e^{-x}\\int_0^{\\infty} e^{-x s}\\,\\mathrm{d}s.", explanation: "Factoring out the endpoint value \\( e^{x\\phi(1)}=e^{-x} \\) reduces the problem to the standard linear-endpoint integral at the origin." },
        { stepNumber: 3, description: "Evaluate.", workingLatex: "I(x) = e^{-x}\\cdot\\frac{1}{x} = \\frac{e^{-x}}{x}.", explanation: "This is exact here, and illustrates the endpoint formula \\( e^{x\\phi(a)}/(x|\\phi'(a)|) \\) with \\( a=1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\frac{e^{-x}}{x} \\).",
      canonicalAnswer: "exp(-x)/x",
    },
  },
  {
    id: "am4b-017",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{x(t^2 - 1)}\\,\\mathrm{d}t \\), identifying the dominant endpoint.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "competing endpoints"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compare the exponent at the two endpoints.", workingLatex: "\\phi(t) = t^2 - 1, \\qquad \\phi(0) = -1, \\qquad \\phi(1) = 0.", explanation: "On \\( [0,1] \\), \\( \\phi \\) increases, so the maximum is at the right endpoint \\( t=1 \\); the lower endpoint contributes an exponentially smaller amount." },
        { stepNumber: 2, description: "Examine the slope at the dominant endpoint.", workingLatex: "\\phi'(t) = 2t, \\qquad \\phi'(1) = 2 \\neq 0.", explanation: "The slope at \\( t=1 \\) is non-zero, so \\( t=1 \\) is a linear endpoint and the leading term carries a single inverse power of \\( x \\)." },
        { stepNumber: 3, description: "Shift and linearise about t=1.", workingLatex: "s = 1 - t: \\quad \\phi(1-s) = (1-s)^2 - 1 = -2s + s^2, \\quad I(x) \\sim \\int_0^{\\infty} e^{-2x s}\\,\\mathrm{d}s.", explanation: "Factor \\( e^{x\\phi(1)}=e^{0}=1 \\). Near \\( s=0 \\) the exponent is \\( -2xs \\) to leading order, with effective slope \\( |\\phi'(1)|=2 \\)." },
        { stepNumber: 4, description: "Evaluate the boundary-layer integral.", workingLatex: "I(x) \\sim \\frac{1}{2x}.", explanation: "Endpoint formula with \\( |\\phi'(1)|=2 \\): \\( e^{x\\phi(1)}/(x|\\phi'(1)|)=1/(2x) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2x} \\) (dominant endpoint \\( t=1 \\)).",
      canonicalAnswer: "1/(2*x)",
    },
  },
  {
    id: "am4b-018",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{-x t^2}\\,\\mathrm{d}t \\), and explain why the finite upper limit does not change the answer at any algebraic order.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "exponentially small tail"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the half-Gaussian endpoint.", workingLatex: "\\phi(t) = -t^2, \\qquad \\phi'(0)=0, \\qquad \\phi''(0)=-2.", explanation: "Peak at the lower endpoint \\( t=0 \\) with zero slope — a half-Gaussian endpoint." },
        { stepNumber: 2, description: "Extend the upper limit and bound the error.", workingLatex: "\\int_0^{1} e^{-x t^2}\\,\\mathrm{d}t = \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t - \\int_1^{\\infty} e^{-x t^2}\\,\\mathrm{d}t,", explanation: "The tail \\( \\int_1^\\infty e^{-xt^2}\\mathrm{d}t \\le \\int_1^\\infty e^{-xt}\\mathrm{d}t = e^{-x}/x \\) is exponentially small — smaller than every power of \\( 1/x \\) — so it never appears in the algebraic asymptotic series." },
        { stepNumber: 3, description: "Take the half-Gaussian value.", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Equivalently \\( I(x)=\\tfrac12\\sqrt{\\pi/x}\\,\\operatorname{erf}(\\sqrt x) \\) and \\( \\operatorname{erf}(\\sqrt x)\\to 1 \\) exponentially. The finite limit is invisible to the power series." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\); the cut tail is exponentially small.",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },

  // ─────────────────────────────────────────────────────────────────────────
  // CHALLENGE (12) — synoptic / multi-step / starred / cross-method, 5+ marks
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am4b-019",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms in the asymptotic expansion as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\pi/2} e^{x \\cos t}\\,\\mathrm{d}t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate and characterise the peak.", workingLatex: "\\phi(t) = \\cos t, \\qquad \\phi'(0)=0, \\qquad \\phi''(0)=-1, \\qquad \\phi(0)=1.", explanation: "Half-Gaussian endpoint at \\( t=0 \\). To get the second term we must retain the quartic term of \\( \\cos t \\)." },
        { stepNumber: 2, description: "Expand the exponent to fourth order.", workingLatex: "\\cos t = 1 - \\frac{t^2}{2} + \\frac{t^4}{24} + O(t^6).", explanation: "The quadratic term gives the Gaussian; the quartic \\( t^4/24 \\) provides the first correction." },
        { stepNumber: 3, description: "Factor the peak and expand the correction.", workingLatex: "I(x) \\sim e^{x}\\int_0^{\\infty} e^{-x t^2/2}\\left(1 + \\frac{x t^4}{24} + \\cdots\\right)\\mathrm{d}t.", explanation: "Write \\( e^{x\\cos t}=e^x e^{-xt^2/2}e^{xt^4/24}\\) and expand the last factor; the term \\( xt^4/24 \\) is \\( O(1) \\) on the boundary-layer scale \\( t\\sim x^{-1/2} \\), so it contributes at the next order." },
        { stepNumber: 4, description: "Use the Gaussian moments.", workingLatex: "\\int_0^{\\infty} e^{-x t^2/2}\\,\\mathrm{d}t = \\sqrt{\\frac{\\pi}{2x}}, \\qquad \\int_0^{\\infty} t^4 e^{-x t^2/2}\\,\\mathrm{d}t = \\frac{3}{8}\\sqrt{2\\pi}\\,x^{-5/2}.", explanation: "Half-line Gaussian moments \\( \\int_0^\\infty t^{2k}e^{-a t^2}\\mathrm{d}t = \\tfrac{(2k-1)!!}{2(2a)^k}\\sqrt{\\pi/a} \\) with \\( a=x/2 \\)." },
        { stepNumber: 5, description: "Combine the two contributions.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}} + e^{x}\\,\\frac{x}{24}\\cdot\\frac{3}{8}\\sqrt{2\\pi}\\,x^{-5/2}.", explanation: "Add the leading term and the quartic correction; now simplify the second coefficient." },
        { stepNumber: 6, description: "Simplify to a clean relative correction.", workingLatex: "I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}\\left(1 + \\frac{1}{8x}\\right).", explanation: "The correction coefficient reduces to \\( \\tfrac18 \\): numerically \\( x\\,(I/\\text{lead}-1)\\to 0.125 \\) (\\( 0.1257 \\) at \\( x=400 \\), \\( 0.12504 \\) at \\( x=1600 \\)), confirming \\( 1/(8x) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}\\left(1 + \\frac{1}{8x}\\right) \\).",
      canonicalAnswer: "exp(x)*sqrt(pi/(2*x))*(1 + 1/(8*x))",
    },
  },
  {
    id: "am4b-020",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms (in powers of \\( x^{-1/2} \\) where appropriate) in the asymptotic expansion as \\( x \\to \\infty \\) of the half-Gaussian endpoint integral \\( \\displaystyle I(x) = \\int_0^{\\infty} e^{-x (t^2 + t^3)}\\,\\mathrm{d}t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "cubic correction", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the endpoint structure.", workingLatex: "g(t) = t^2 + t^3, \\qquad g(0)=0, \\qquad g'(0)=0, \\qquad g''(0)=2.", explanation: "Half-Gaussian endpoint at \\( t=0 \\) (write \\( I=\\int_0^\\infty e^{-xg}\\mathrm{d}t \\)). The cubic term \\( t^3 \\) is the leading anharmonic correction." },
        { stepNumber: 2, description: "Split off the Gaussian and expand the cubic.", workingLatex: "I(x) = \\int_0^{\\infty} e^{-x t^2}\\,e^{-x t^3}\\,\\mathrm{d}t \\sim \\int_0^{\\infty} e^{-x t^2}\\left(1 - x t^3 + \\frac{x^2 t^6}{2} - \\cdots\\right)\\mathrm{d}t.", explanation: "On the boundary layer \\( t\\sim x^{-1/2} \\), each factor \\( xt^3\\sim x^{-1/2} \\) and \\( x^2 t^6\\sim x^{-1} \\), so successive terms drop by half-powers — both must be kept for two terms." },
        { stepNumber: 3, description: "Record the half-line moments.", workingLatex: "\\int_0^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}, \\quad \\int_0^{\\infty} t^3 e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2x^2}, \\quad \\int_0^{\\infty} t^6 e^{-x t^2}\\,\\mathrm{d}t = \\frac{15}{16}\\sqrt{\\pi}\\,x^{-7/2}.", explanation: "The \\( t^3 \\) moment is elementary; the \\( t^6 \\) moment uses \\( \\int_0^\\infty t^{2k}e^{-xt^2}\\mathrm{d}t=\\tfrac{(2k-1)!!}{2(2x)^k}\\sqrt{\\pi/x} \\) with \\( k=3 \\)." },
        { stepNumber: 4, description: "Multiply by the prefactors.", workingLatex: "-x\\cdot\\frac{1}{2x^2} = -\\frac{1}{2x}, \\qquad \\frac{x^2}{2}\\cdot\\frac{15}{16}\\sqrt{\\pi}\\,x^{-7/2} = \\frac{15\\sqrt{\\pi}}{32}\\,x^{-3/2}.", explanation: "The odd \\( t^3 \\) term feeds the integer-power correction \\( -1/(2x) \\); the even \\( t^6 \\) term feeds the half-integer correction \\( x^{-3/2} \\)." },
        { stepNumber: 5, description: "Assemble the expansion.", workingLatex: "I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} - \\frac{1}{2x} + \\frac{15\\sqrt{\\pi}}{32}\\,x^{-3/2} + \\cdots.", explanation: "The expansion proceeds in mixed half-integer and integer powers, characteristic of an asymmetric (cubic-perturbed) half-Gaussian endpoint. Numerically the three-term sum matches the integral to ratio \\( 0.99999 \\) at \\( x=12800 \\)." },
        { stepNumber: 6, description: "Quote the first two terms.", workingLatex: "I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} - \\frac{1}{2x}.", explanation: "The first correction beyond the bare half-Gaussian is \\( -1/(2x) \\); it is generated entirely by the cubic anharmonicity." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} - \\frac{1}{2x} \\) (next term \\( \\tfrac{15\\sqrt\\pi}{32}x^{-3/2} \\)).",
      canonicalAnswer: "(1/2)*sqrt(pi/x) - 1/(2*x)",
    },
  },
  {
    id: "am4b-021",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By substituting \\( u = \\sqrt{t} \\), find the first two terms in the asymptotic expansion as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\pi^2/4} e^{x \\cos \\sqrt{t}}\\,\\mathrm{d}t \\). (Cf. Example Sheet Q13.)",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum", "vanishing prefactor", "substitution", "Example Sheet Q13"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute to remove the square root.", workingLatex: "u = \\sqrt{t}, \\quad t = u^2, \\quad \\mathrm{d}t = 2u\\,\\mathrm{d}u, \\quad I(x) = \\int_0^{\\pi/2} e^{x\\cos u}\\,2u\\,\\mathrm{d}u.", explanation: "The limits map \\( t:0\\to\\pi^2/4 \\) onto \\( u:0\\to\\pi/2 \\). The Jacobian introduces a prefactor \\( 2u \\) that vanishes at the endpoint — the key feature." },
        { stepNumber: 2, description: "Locate the peak and the vanishing prefactor.", workingLatex: "\\phi(u) = \\cos u \\ \\text{peaks at}\\ u=0, \\qquad \\phi(0)=1, \\qquad g(u)=2u, \\qquad g(0)=0.", explanation: "Half-Gaussian endpoint at \\( u=0 \\), but the prefactor \\( 2u \\) is zero at the peak, so the leading power is reduced from \\( x^{-1/2} \\) to \\( x^{-1} \\)." },
        { stepNumber: 3, description: "Expand exponent and prefactor on the boundary layer.", workingLatex: "\\cos u = 1 - \\frac{u^2}{2} + \\frac{u^4}{24} + \\cdots, \\qquad I(x) \\sim 2e^{x}\\int_0^{\\infty} u\\,e^{-x u^2/2}\\left(1 + \\frac{x u^4}{24} + \\cdots\\right)\\mathrm{d}u.", explanation: "Factor \\( e^x \\) and write the quartic term as a correction; the prefactor \\( u \\) is retained exactly." },
        { stepNumber: 4, description: "Compute the leading moment.", workingLatex: "2\\int_0^{\\infty} u\\,e^{-x u^2/2}\\,\\mathrm{d}u = 2\\cdot\\frac{1}{x} = \\frac{2}{x}.", explanation: "\\( \\int_0^\\infty u e^{-au^2}\\mathrm{d}u = 1/(2a) \\) with \\( a=x/2 \\) gives \\( 1/x \\); times \\( 2 \\) gives the leading \\( 2/x \\)." },
        { stepNumber: 5, description: "Compute the correction moment.", workingLatex: "2\\cdot\\frac{x}{24}\\int_0^{\\infty} u^5 e^{-x u^2/2}\\,\\mathrm{d}u = 2\\cdot\\frac{x}{24}\\cdot\\frac{8}{x^3} = \\frac{2}{3x^2}.", explanation: "\\( \\int_0^\\infty u^5 e^{-au^2}\\mathrm{d}u = 1/a^3 \\) with \\( a=x/2 \\) gives \\( 8/x^3 \\); multiplying by \\( 2x/24 \\) gives the \\( 2/(3x^2) \\) correction." },
        { stepNumber: 6, description: "Assemble the two terms.", workingLatex: "I(x) \\sim e^{x}\\left(\\frac{2}{x} + \\frac{2}{3x^2}\\right).", explanation: "This matches the Example Sheet Q13 result exactly; numerically \\( I/\\text{pred}\\to 1 \\) (ratio \\( 1.000007 \\) at \\( x=200 \\))." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim e^{x}\\left(\\frac{2}{x} + \\frac{2}{3x^2}\\right) \\).",
      canonicalAnswer: "exp(x)*(2/x + 2/(3*x^2))",
    },
  },
  {
    id: "am4b-022",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( \\displaystyle I_1(x) = \\int_0^{1} e^{-x t (1-t)^2}\\,\\mathrm{d}t \\) as \\( x \\to \\infty \\) (cf. Example Sheet Q11). Show the exponent is minimised at the endpoint \\( t=0 \\) and at the interior point \\( t=1 \\), determine which dominates, and find the leading-order behaviour.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "competing maxima", "endpoint vs interior", "Example Sheet Q11"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the zeros of the exponent g(t)=t(1-t)^2.", workingLatex: "g(t) = t(1-t)^2 \\ge 0 \\ \\text{on}\\ [0,1], \\qquad g(0) = 0, \\qquad g(1) = 0.", explanation: "The integrand \\( e^{-xg} \\) is largest where \\( g \\) is smallest, i.e. where \\( g=0 \\). On \\( [0,1] \\) that happens at \\( t=0 \\) (left endpoint) and at \\( t=1 \\) (right endpoint)." },
        { stepNumber: 2, description: "Classify the endpoint t=0.", workingLatex: "g(t) = t(1-2t+t^2) = t - 2t^2 + t^3, \\qquad g'(0) = 1 \\neq 0.", explanation: "At \\( t=0 \\) the exponent rises linearly with slope \\( 1 \\): a linear endpoint contributing at order \\( 1/x \\)." },
        { stepNumber: 3, description: "Classify the endpoint t=1.", workingLatex: "g'(t) = (1-t)^2 + t\\cdot 2(1-t)(-1) = (1-t)(1-3t), \\qquad g'(1) = 0, \\quad g''(1) = 2.", explanation: "At \\( t=1 \\), \\( g'=0 \\) and \\( g''(1)=2>0 \\): \\( g \\) has a smooth minimum there, so the integrand has a half-Gaussian maximum at this endpoint, contributing at order \\( x^{-1/2} \\)." },
        { stepNumber: 4, description: "Decide which contribution dominates.", workingLatex: "\\underbrace{x^{-1/2}}_{t=1\\ \\text{(half-Gaussian)}} \\ \\gg\\ \\underbrace{x^{-1}}_{t=0\\ \\text{(linear)}} \\qquad (x\\to\\infty).", explanation: "A half-Gaussian endpoint (\\( x^{-1/2} \\)) beats a linear endpoint (\\( x^{-1} \\)). So \\( t=1 \\) dominates the leading order." },
        { stepNumber: 5, description: "Evaluate the half-Gaussian at t=1.", workingLatex: "I_1(x) \\sim e^{-x g(1)}\\,\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,g''(1)}} = \\frac{1}{2}\\sqrt{\\frac{2\\pi}{2x}} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "With \\( g(1)=0 \\) and \\( g''(1)=2 \\) the half-Gaussian formula gives \\( \\tfrac12\\sqrt{\\pi/x} \\)." },
        { stepNumber: 6, description: "State the result.", workingLatex: "I_1(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Numerically \\( I_1\\sqrt{x}\\to \\tfrac12\\sqrt\\pi\\approx 0.8862 \\); the linear endpoint at \\( t=0 \\) appears only at the next, \\( 1/x \\), order." },
      ],
      finalAnswer: "\\( t=1 \\) dominates; \\( \\displaystyle I_1(x) \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} \\).",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am4b-023",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the general half-Gaussian endpoint formula: if \\( \\phi \\) has its maximum on \\( [a,b] \\) at the lower endpoint \\( t=a \\) with \\( \\phi'(a)=0 \\) and \\( \\phi''(a)<0 \\), show that \\( \\displaystyle \\int_a^{b} e^{x \\phi(t)}\\,\\mathrm{d}t \\sim e^{x \\phi(a)}\\,\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(a)|}} \\), making the origin of the factor \\( \\tfrac12 \\) explicit.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "general derivation", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Factor out the peak value.", workingLatex: "\\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t = e^{x\\phi(a)}\\int_a^{b} e^{x[\\phi(t)-\\phi(a)]}\\,\\mathrm{d}t.", explanation: "Pulling out \\( e^{x\\phi(a)} \\) leaves an exponent that is zero at the peak and negative elsewhere, so the remaining integrand is bounded by \\( 1 \\) and concentrated near \\( t=a \\)." },
        { stepNumber: 2, description: "Taylor-expand the exponent about the endpoint.", workingLatex: "\\phi(t) - \\phi(a) = \\frac{1}{2}\\phi''(a)(t-a)^2 + O\\big((t-a)^3\\big),", explanation: "Since \\( \\phi'(a)=0 \\) the quadratic term leads. Write \\( \\phi''(a)=-|\\phi''(a)| \\) (negative), giving a decaying Gaussian." },
        { stepNumber: 3, description: "Approximate by the local Gaussian.", workingLatex: "\\int_a^{b} e^{x[\\phi(t)-\\phi(a)]}\\,\\mathrm{d}t \\sim \\int_a^{\\infty} e^{-\\frac{1}{2}x|\\phi''(a)|(t-a)^2}\\,\\mathrm{d}t,", explanation: "On the boundary layer of width \\( (x|\\phi''(a)|)^{-1/2} \\) the cubic and higher terms are negligible; the upper limit may be pushed to \\( \\infty \\) with exponentially small error." },
        { stepNumber: 4, description: "Rescale to a standard Gaussian.", workingLatex: "\\tau = (t-a)\\sqrt{x|\\phi''(a)|}: \\quad \\int_a^{\\infty}(\\cdots)\\mathrm{d}t = \\frac{1}{\\sqrt{x|\\phi''(a)|}}\\int_0^{\\infty} e^{-\\tau^2/2}\\,\\mathrm{d}\\tau.", explanation: "The lower limit \\( t=a \\) maps to \\( \\tau=0 \\) — this is exactly why the integral runs over only the half-line \\( [0,\\infty) \\)." },
        { stepNumber: 5, description: "Insert the half-Gaussian value.", workingLatex: "\\int_0^{\\infty} e^{-\\tau^2/2}\\,\\mathrm{d}\\tau = \\frac{1}{2}\\int_{-\\infty}^{\\infty} e^{-\\tau^2/2}\\,\\mathrm{d}\\tau = \\frac{1}{2}\\sqrt{2\\pi}.", explanation: "The endpoint cuts the symmetric Gaussian peak exactly in half — this is the origin of the factor \\( \\tfrac12 \\)." },
        { stepNumber: 6, description: "Combine the pieces.", workingLatex: "\\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t \\sim e^{x\\phi(a)}\\,\\frac{1}{\\sqrt{x|\\phi''(a)|}}\\cdot\\frac{\\sqrt{2\\pi}}{2} = e^{x\\phi(a)}\\,\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(a)|}}.", explanation: "This is the claimed formula. An interior maximum would map both half-lines into the range, restoring the full \\( \\sqrt{2\\pi} \\) and removing the \\( \\tfrac12 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t \\sim e^{x\\phi(a)}\\,\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(a)|}} \\).",
    },
  },
  {
    id: "am4b-024",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the general linear (sub-Gaussian) endpoint formula: if \\( \\phi \\) is maximised on \\( [a,b] \\) at the lower endpoint \\( t=a \\) with \\( \\phi'(a) < 0 \\), show that \\( \\displaystyle \\int_a^{b} e^{x \\phi(t)}\\,\\mathrm{d}t \\sim \\frac{e^{x \\phi(a)}}{x\\,|\\phi'(a)|} \\), and explain why no factor of \\( \\tfrac12 \\) appears.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "sub-Gaussian", "general derivation", "proof"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Factor out the peak value.", workingLatex: "\\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t = e^{x\\phi(a)}\\int_a^{b} e^{x[\\phi(t)-\\phi(a)]}\\,\\mathrm{d}t.", explanation: "As before, isolate the exponentially large endpoint value; the residual exponent vanishes at \\( t=a \\) and is negative beyond it." },
        { stepNumber: 2, description: "Linearise the exponent at the endpoint.", workingLatex: "\\phi(t) - \\phi(a) = \\phi'(a)(t-a) + O\\big((t-a)^2\\big), \\qquad \\phi'(a) = -|\\phi'(a)|.", explanation: "Because \\( \\phi'(a)\\neq 0 \\), the linear term dominates near the endpoint; the integrand decays like \\( e^{-x|\\phi'(a)|(t-a)} \\), a boundary layer of width \\( O(1/x) \\) (not \\( x^{-1/2} \\))." },
        { stepNumber: 3, description: "Approximate by the exponential and extend.", workingLatex: "\\int_a^{b} e^{x[\\phi(t)-\\phi(a)]}\\,\\mathrm{d}t \\sim \\int_a^{\\infty} e^{-x|\\phi'(a)|(t-a)}\\,\\mathrm{d}t.", explanation: "The quadratic correction is negligible on the thin \\( O(1/x) \\) layer; pushing the upper limit to \\( \\infty \\) is exponentially accurate." },
        { stepNumber: 4, description: "Evaluate the elementary integral.", workingLatex: "\\int_a^{\\infty} e^{-x|\\phi'(a)|(t-a)}\\,\\mathrm{d}t = \\frac{1}{x\\,|\\phi'(a)|}.", explanation: "A one-sided exponential integrates to the reciprocal of its rate." },
        { stepNumber: 5, description: "Combine and explain the absent 1/2.", workingLatex: "\\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t \\sim \\frac{e^{x\\phi(a)}}{x\\,|\\phi'(a)|}.", explanation: "There is no Gaussian peak to bisect here — the maximum is a genuine corner, not a smooth bump — so no \\( \\tfrac12 \\) appears. The decay is \\( 1/x \\), one full inverse power, reflecting the narrower \\( O(1/x) \\) boundary layer." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_a^{b} e^{x\\phi(t)}\\,\\mathrm{d}t \\sim \\frac{e^{x\\phi(a)}}{x\\,|\\phi'(a)|} \\); no \\( \\tfrac12 \\), since there is no peak to halve.",
    },
  },
  {
    id: "am4b-025",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\pi/2} e^{-x t^3 \\cos t}\\,\\mathrm{d}t \\), expressing your answer in terms of a Gamma function. (Cf. Example Sheet Q12.)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum", "cubic endpoint", "Gamma function", "Example Sheet Q12"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum of the integrand.", workingLatex: "g(t) = t^3\\cos t \\ge 0 \\ \\text{on}\\ [0,\\pi/2], \\qquad g(0) = 0.", explanation: "The integrand \\( e^{-xg} \\) is largest where \\( g \\) is smallest. On \\( [0,\\pi/2] \\), \\( g\\ge 0 \\) and vanishes only at \\( t=0 \\), so the dominant contribution is the endpoint \\( t=0 \\)." },
        { stepNumber: 2, description: "Find the local behaviour of the exponent.", workingLatex: "g(t) = t^3\\cos t = t^3\\big(1 - \\tfrac{t^2}{2}+\\cdots\\big) \\sim t^3 \\quad (t\\to 0).", explanation: "Near the endpoint \\( \\cos t\\approx 1 \\), so the exponent behaves like \\( t^3 \\): this is a cubic (degenerate) endpoint, giving a non-Gaussian \\( x^{-1/3} \\) scaling." },
        { stepNumber: 3, description: "Localise the integral.", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t^3}\\,\\mathrm{d}t.", explanation: "Replace \\( g(t) \\) by its leading cubic and extend the upper limit to \\( \\infty \\) (exponentially small error). The relevant boundary layer is \\( t\\sim x^{-1/3} \\)." },
        { stepNumber: 4, description: "Reduce to a Gamma integral.", workingLatex: "s = x t^3, \\quad t = (s/x)^{1/3}, \\quad \\mathrm{d}t = \\frac{1}{3}x^{-1/3}s^{-2/3}\\,\\mathrm{d}s, \\quad I(x) \\sim \\frac{x^{-1/3}}{3}\\int_0^{\\infty} s^{-2/3} e^{-s}\\,\\mathrm{d}s.", explanation: "The substitution \\( s=xt^3 \\) standardises the exponent and turns the integral into a Gamma function." },
        { stepNumber: 5, description: "Identify the Gamma value.", workingLatex: "\\int_0^{\\infty} s^{-2/3} e^{-s}\\,\\mathrm{d}s = \\Gamma\\!\\left(\\tfrac13\\right) \\ \\Longrightarrow\\ I(x) \\sim \\frac{1}{3 x^{1/3}}\\,\\Gamma\\!\\left(\\tfrac13\\right).", explanation: "The cubic endpoint gives the \\( x^{-1/3} \\) law of Example Sheet Q12; numerically \\( I/\\text{lead}\\to 1 \\) (ratio \\( 1.0006 \\) at \\( x=2\\times10^4 \\))." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{3 x^{1/3}}\\,\\Gamma\\!\\left(\\tfrac13\\right) \\).",
      canonicalAnswer: "(1/3)*gamma(1/3)*x^(-1/3)",
    },
  },
  {
    id: "am4b-026",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms in the asymptotic expansion as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\infty} \\frac{e^{-x t}}{1 + t}\\,\\mathrm{d}t \\), and relate the result to the exponential integral.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "linear endpoint", "exponential integral", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the endpoint and the prefactor.", workingLatex: "\\phi(t) = -t, \\quad \\phi'(0) = -1, \\quad g(t) = \\frac{1}{1+t}, \\quad g(0) = 1.", explanation: "Linear endpoint at \\( t=0 \\). The smooth prefactor \\( (1+t)^{-1} \\) is analytic at the endpoint, so Watson's lemma applies via its Taylor series." },
        { stepNumber: 2, description: "Expand the prefactor.", workingLatex: "\\frac{1}{1+t} = 1 - t + t^2 - \\cdots \\qquad (|t| < 1).", explanation: "Only the behaviour near \\( t=0 \\) matters; the series coefficients become the asymptotic coefficients." },
        { stepNumber: 3, description: "Integrate term by term (Watson's lemma).", workingLatex: "I(x) \\sim \\int_0^{\\infty} e^{-x t}\\,(1 - t + t^2 - \\cdots)\\,\\mathrm{d}t = \\frac{0!}{x} - \\frac{1!}{x^2} + \\frac{2!}{x^3} - \\cdots.", explanation: "Using \\( \\int_0^\\infty t^n e^{-xt}\\mathrm{d}t = n!/x^{n+1} \\). The factorial growth signals a divergent (asymptotic) series, as expected." },
        { stepNumber: 4, description: "Quote the first two terms.", workingLatex: "I(x) \\sim \\frac{1}{x} - \\frac{1}{x^2}.", explanation: "These are the leading two terms; the series is \\( \\sum_{n\\ge0}(-1)^n n!\\,x^{-(n+1)} \\)." },
        { stepNumber: 5, description: "Relate to the exponential integral.", workingLatex: "I(x) = \\int_0^{\\infty}\\frac{e^{-xt}}{1+t}\\,\\mathrm{d}t = e^{x}E_1(x), \\qquad E_1(x) = \\int_x^{\\infty}\\frac{e^{-u}}{u}\\,\\mathrm{d}u.", explanation: "Substituting \\( u=x(1+t) \\) gives \\( I=e^{x}E_1(x) \\); our series is precisely the classical asymptotic expansion \\( E_1(x)\\sim e^{-x}\\sum(-1)^n n!\\,x^{-(n+1)} \\) (Example Sheet Q10)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) \\sim \\frac{1}{x} - \\frac{1}{x^2} \\); here \\( I(x) = e^{x}E_1(x) \\).",
      canonicalAnswer: "1/x - 1/x^2",
    },
  },
  {
    id: "am4b-027",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A maximum sits at an endpoint with a vanishing prefactor and zero slope. Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{\\infty} t^2\\, e^{-x t^2}\\,\\mathrm{d}t \\), and state the general scaling for a prefactor \\( t^{\\mu} \\) at a half-Gaussian endpoint.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "half-Gaussian", "vanishing prefactor", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the doubly-degenerate endpoint.", workingLatex: "\\phi(t) = -t^2 \\ \\text{peaks at}\\ t=0, \\qquad g(t) = t^2, \\qquad g(0) = 0, \\ g'(0) = 0.", explanation: "Half-Gaussian endpoint with a prefactor vanishing quadratically; the leading power of \\( x \\) is reduced from \\( x^{-1/2} \\) by \\( \\mu/2 \\) with \\( \\mu=2 \\)." },
        { stepNumber: 2, description: "Reduce to a Gamma integral.", workingLatex: "s = x t^2, \\quad t = (s/x)^{1/2}, \\quad \\mathrm{d}t = \\frac{1}{2}x^{-1/2}s^{-1/2}\\,\\mathrm{d}s, \\quad I(x) = \\frac{1}{2}x^{-3/2}\\int_0^{\\infty} s^{1/2} e^{-s}\\,\\mathrm{d}s.", explanation: "Here \\( t^2 = s/x \\), so the prefactor contributes \\( s/x \\); combined with the Jacobian the overall power is \\( x^{-3/2} \\)." },
        { stepNumber: 3, description: "Evaluate the Gamma value.", workingLatex: "\\int_0^{\\infty} s^{1/2} e^{-s}\\,\\mathrm{d}s = \\Gamma\\!\\left(\\tfrac32\\right) = \\frac{\\sqrt{\\pi}}{2} \\ \\Longrightarrow\\ I(x) = \\frac{\\sqrt{\\pi}}{4}\\,x^{-3/2}.", explanation: "This is exact: \\( \\int_0^\\infty t^2 e^{-xt^2}\\mathrm{d}t = \\tfrac14\\sqrt{\\pi}\\,x^{-3/2} \\), matching the numerical value to full precision." },
        { stepNumber: 4, description: "State the general rule.", workingLatex: "\\int_0^{\\infty} t^{\\mu} e^{-x t^2}\\,\\mathrm{d}t = \\frac{1}{2}\\,\\Gamma\\!\\left(\\frac{\\mu+1}{2}\\right) x^{-(\\mu+1)/2}.", explanation: "A prefactor \\( t^{\\mu} \\) at a half-Gaussian endpoint gives the power \\( x^{-(\\mu+1)/2} \\): \\( \\mu=0 \\) recovers \\( x^{-1/2} \\), \\( \\mu=2 \\) gives \\( x^{-3/2} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\frac{\\sqrt{\\pi}}{4}\\,x^{-3/2} \\); generally \\( \\tfrac12\\Gamma\\!\\big(\\tfrac{\\mu+1}{2}\\big)x^{-(\\mu+1)/2} \\).",
      canonicalAnswer: "(sqrt(pi)/4)*x^(-3/2)",
    },
  },
  {
    id: "am4b-028",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_{-1}^{1} e^{-x t^2}\\,\\mathrm{d}t \\), and contrast it with the half-Gaussian endpoint integral \\( \\int_0^{1} e^{-x t^2}\\,\\mathrm{d}t \\). Explain the factor of \\( 2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "half vs full Gaussian", "factor of 2"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Classify the maximum.", workingLatex: "\\phi(t) = -t^2 \\ \\text{peaks at}\\ t=0, \\qquad t=0 \\in (-1,1).", explanation: "Now the peak \\( t=0 \\) lies strictly inside the range, so both shoulders of the Gaussian are captured — a full, not half, Gaussian." },
        { stepNumber: 2, description: "Extend the limits and evaluate.", workingLatex: "I(x) \\sim \\int_{-\\infty}^{\\infty} e^{-x t^2}\\,\\mathrm{d}t = \\sqrt{\\frac{\\pi}{x}}.", explanation: "Both tails beyond \\( \\pm1 \\) are exponentially small, so the full Gaussian gives the leading term." },
        { stepNumber: 3, description: "Compare with the endpoint version.", workingLatex: "\\int_0^{1} e^{-x t^2}\\,\\mathrm{d}t \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} = \\frac{1}{2}\\,I(x).", explanation: "Moving the lower limit from \\( -1 \\) to \\( 0 \\) discards exactly half the symmetric peak. The endpoint integral is therefore half the interior one — the cleanest illustration of the \\( \\tfrac12 \\) factor." },
        { stepNumber: 4, description: "State both results.", workingLatex: "\\int_{-1}^{1} e^{-x t^2}\\,\\mathrm{d}t \\sim \\sqrt{\\frac{\\pi}{x}}, \\qquad \\int_0^{1} e^{-x t^2}\\,\\mathrm{d}t \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The factor of \\( 2 \\) between them is entirely geometric: full peak versus half peak." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_{-1}^{1} e^{-x t^2}\\,\\mathrm{d}t \\sim \\sqrt{\\frac{\\pi}{x}} \\), exactly twice the half-Gaussian endpoint value \\( \\tfrac12\\sqrt{\\pi/x} \\).",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am4b-029",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The Gamma function for large argument can be probed at an endpoint. Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} t^{x}\\,\\mathrm{d}t \\) by writing \\( t^{x} = e^{x \\ln t} \\), and confirm against the exact value.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "linear endpoint", "logarithmic exponent", "exact check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rewrite as a Laplace integral.", workingLatex: "I(x) = \\int_0^{1} e^{x \\ln t}\\,\\mathrm{d}t, \\qquad \\phi(t) = \\ln t.", explanation: "Since \\( \\ln t \\) increases on \\( (0,1] \\), the exponent is maximised at the upper endpoint \\( t=1 \\), where \\( \\ln 1 = 0 \\)." },
        { stepNumber: 2, description: "Examine the slope at the endpoint.", workingLatex: "\\phi'(t) = \\frac{1}{t}, \\qquad \\phi'(1) = 1 \\neq 0.", explanation: "Non-zero slope at \\( t=1 \\): a linear endpoint, so we expect a \\( 1/x \\) law with no \\( \\tfrac12 \\)." },
        { stepNumber: 3, description: "Shift to the origin and linearise.", workingLatex: "s = 1 - t: \\quad \\ln(1-s) = -s - \\tfrac{s^2}{2} - \\cdots, \\quad I(x) \\sim \\int_0^{\\infty} e^{-x s}\\,\\mathrm{d}s.", explanation: "Factor \\( e^{x\\phi(1)} = e^{0} = 1 \\); near \\( s=0 \\), \\( x\\ln(1-s)\\approx -xs \\), with effective endpoint slope \\( |\\phi'(1)|=1 \\)." },
        { stepNumber: 4, description: "Evaluate the boundary-layer integral.", workingLatex: "I(x) \\sim \\frac{1}{x}.", explanation: "Endpoint formula \\( e^{x\\phi(1)}/(x|\\phi'(1)|) = 1/x \\)." },
        { stepNumber: 5, description: "Confirm against the exact value.", workingLatex: "\\int_0^{1} t^{x}\\,\\mathrm{d}t = \\frac{1}{x+1} = \\frac{1}{x}\\Big(1 - \\frac{1}{x} + \\cdots\\Big) \\sim \\frac{1}{x}.", explanation: "The exact value \\( 1/(x+1) \\) confirms both the leading \\( 1/x \\) and the next term \\( -1/x^2 \\); the linear-endpoint analysis is vindicated." },
      ],
      finalAnswer: "\\( \\displaystyle I(x) = \\frac{1}{x+1} \\sim \\frac{1}{x} \\).",
      canonicalAnswer: "1/(x+1)",
    },
  },
  // REVIEW: leading coefficient checked numerically (ratio -> 1); the stated "both endpoints contribute equally" symmetry argument is exact by the t -> 1-t reflection but is a structural claim rather than a numeric one.
  {
    id: "am4b-030",
    topicRef: "am4b",
    topicTitle: "Endpoint maxima & half-Gaussian factors 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour as \\( x \\to \\infty \\) of \\( \\displaystyle I(x) = \\int_0^{1} e^{x\\,t(1-t)}\\,\\mathrm{d}t \\). Identify whether the maximum is interior or at an endpoint, and state explicitly whether a \\( \\tfrac12 \\) factor is present.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum", "no half factor", "symmetry"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the stationary point.", workingLatex: "\\phi(t) = t(1-t) = t - t^2, \\qquad \\phi'(t) = 1 - 2t = 0 \\iff t = \\tfrac12.", explanation: "The exponent is a downward parabola peaking at \\( t=\\tfrac12 \\), the midpoint of the range — a genuine interior maximum, symmetric under \\( t\\mapsto 1-t \\)." },
        { stepNumber: 2, description: "Evaluate the peak data.", workingLatex: "\\phi\\!\\left(\\tfrac12\\right) = \\frac{1}{4}, \\qquad \\phi''(t) = -2, \\qquad \\phi''\\!\\left(\\tfrac12\\right) = -2.", explanation: "Peak value \\( \\tfrac14 \\) sets the exponential scale \\( e^{x/4} \\); curvature \\( -2 \\) sets the width." },
        { stepNumber: 3, description: "Apply the interior-maximum formula (no 1/2).", workingLatex: "I(x) \\sim e^{x/4}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(1/2)|}} = e^{x/4}\\sqrt{\\frac{2\\pi}{2x}}.", explanation: "Because the peak is interior, both shoulders lie inside \\( (0,1) \\); the full Gaussian applies and there is NO factor of \\( \\tfrac12 \\)." },
        { stepNumber: 4, description: "Simplify.", workingLatex: "I(x) \\sim e^{x/4}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Numerically the ratio of integral to this estimate tends to \\( 1 \\) as \\( x\\to\\infty \\). Contrast with an endpoint of the same curvature, which would carry an extra \\( \\tfrac12 \\)." },
      ],
      finalAnswer: "Interior maximum at \\( t=\\tfrac12 \\); \\( \\displaystyle I(x) \\sim e^{x/4}\\sqrt{\\frac{\\pi}{x}} \\) (no \\( \\tfrac12 \\) factor).",
      canonicalAnswer: "exp(x/4)*sqrt(pi/x)",
    },
  },
];
