import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — Laplace's Method § am4d
 * Ref: am4d
 * Laplace integrals for special functions: the Bessel function
 *   \( I_0(x) = \frac{1}{\pi}\int_0^\pi e^{x\cos\theta}\,d\theta \),
 * its large-\(x\) leading behaviour \( I_0(x)\sim e^x/\sqrt{2\pi x} \), and the
 * full subleading asymptotic series
 *   \( I_0(x)\sim \frac{e^x}{\sqrt{2\pi x}}\Big(1+\frac{1}{8x}+\frac{9}{128x^2}
 *      +\frac{225}{3072x^3}+\cdots\Big). \)
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 2, Q2
 * (the \( \int_0^{\pi/2} e^{-x\sin^2 t}\,dt \) expansion and the Bessel
 * application), with constants / limits / framing varied throughout.
 *
 * Key derivation spine (verified numerically with mpmath):
 *   cos θ = 1 − 2 sin²(θ/2) ⇒  I0(x) = (2e^x/π) ∫_0^{π/2} e^{−2x sin²u} du,
 *   then Watson/Laplace on the sheet integral with X = 2x gives the series.
 *   Series coefficient a_k = [1²·3²···(2k−1)²] / (k!·8^k):
 *     a0=1, a1=1/8, a2=9/128, a3=225/3072, a4=11025/98304.
 *
 * Numerical verification performed (mpmath, dps≥30):
 *   • I0(x) = (1/π)∫_0^π e^{x cosθ}dθ exactly (x=20).
 *   • 3-term series / I0(20) = 0.9999992; 4-term / I0(30) = 0.99999999.
 *   • Half-angle relation I0(x)=(2e^x/π)∫_0^{π/2}e^{−2x sin²u}du (x=30, exact).
 *   • Sheet expansion ∫_0^{π/2}e^{−x sin²t}dt ~ (π/4x)^{1/2}(1+…) (x=15).
 *   • Watson lemma forms ∫_0^∞ t^{s-1}e^{−xt}dt = Γ(s)/x^s.
 *   • Γ(1/2)² = π (reflection at z=1/2).
 *   • I0(10)=2815.72, 2-term approx=2813.52.
 */
export const questions: Question[] = [
  // ─────────────────────────── FOUNDATION (6) ───────────────────────────
  {
    id: "am4d-001",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Locate the point where the exponent is largest in the Laplace-type integral \\( \\displaystyle\\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta \\) for large \\( x>0 \\), and state the value of \\( \\cos\\theta \\) there.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace's method", "Bessel I0", "endpoint maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the controlling exponent.", workingLatex: "\\phi(\\theta) = \\cos\\theta, \\qquad \\theta\\in[0,\\pi].", explanation: "For a Laplace integral \\( \\int e^{x\\phi}\\,d\\theta \\) with \\( x\\to\\infty \\) the dominant contribution comes from wherever \\( \\phi \\) is maximal." },
        { stepNumber: 2, description: "Maximise on the interval.", workingLatex: "\\phi'(\\theta) = -\\sin\\theta = 0 \\;\\Rightarrow\\; \\theta = 0 \\text{ or } \\pi.", explanation: "On \\( [0,\\pi] \\), \\( \\cos\\theta \\) decreases monotonically from \\( 1 \\) to \\( -1 \\)." },
        { stepNumber: 3, description: "Select the maximum.", workingLatex: "\\phi(0)=1 > \\phi(\\pi)=-1.", explanation: "The maximum sits at the left endpoint \\( \\theta=0 \\); the integral is dominated by a neighbourhood of that endpoint." },
        { stepNumber: 4, description: "State the value of the cosine there.", workingLatex: "\\theta=0, \\qquad \\cos\\theta = 1.", explanation: "This is an endpoint maximum, so Laplace's method will use a half-neighbourhood expansion about \\( \\theta=0 \\)." },
      ],
      finalAnswer: "Maximum at \\( \\theta = 0 \\), where \\( \\cos\\theta = 1 \\).",
    },
  },
  {
    id: "am4d-002",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Near \\( \\theta=0 \\) write \\( \\cos\\theta = 1 - g(\\theta) \\). Find the leading quadratic behaviour of \\( g(\\theta) \\) as \\( \\theta\\to 0 \\), which controls the width of the Laplace peak.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Bessel I0", "Taylor expansion", "Laplace peak"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Taylor expand the cosine.", workingLatex: "\\cos\\theta = 1 - \\frac{\\theta^2}{2} + \\frac{\\theta^4}{24} - \\cdots", explanation: "About the maximum the exponent must be expanded; the quadratic term sets the Gaussian width." },
        { stepNumber: 2, description: "Read off the deficit function.", workingLatex: "g(\\theta) = 1 - \\cos\\theta = \\frac{\\theta^2}{2} - \\frac{\\theta^4}{24} + \\cdots", explanation: "Subtracting from \\( 1 \\) isolates how fast the exponent falls away from its maximum." },
        { stepNumber: 3, description: "State the leading quadratic.", workingLatex: "g(\\theta) \\sim \\frac{\\theta^2}{2} \\qquad (\\theta\\to 0).", explanation: "Hence \\( e^{x\\cos\\theta} \\sim e^{x} e^{-x\\theta^2/2} \\): a Gaussian of width \\( \\sim x^{-1/2} \\)." },
      ],
      finalAnswer: "\\( g(\\theta) = 1-\\cos\\theta \\sim \\tfrac{1}{2}\\theta^2 \\).",
    },
  },
  {
    id: "am4d-003",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Gaussian half-line integral \\( \\displaystyle\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta \\) for \\( x>0 \\), the building block of the Bessel \\( I_0 \\) Laplace estimate.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gaussian integral", "Laplace's method", "Bessel I0"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the full Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a\\theta^2}\\,d\\theta = \\sqrt{\\frac{\\pi}{a}}.", explanation: "The standard Gaussian integral with \\( a = x/2 \\)." },
        { stepNumber: 2, description: "Take the half by symmetry.", workingLatex: "\\int_0^{\\infty} e^{-a\\theta^2}\\,d\\theta = \\frac{1}{2}\\sqrt{\\frac{\\pi}{a}}.", explanation: "The integrand is even, so the half-line gives exactly half the full integral." },
        { stepNumber: 3, description: "Substitute \\( a=x/2 \\).", workingLatex: "\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta = \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}} = \\sqrt{\\frac{\\pi}{2x}}.", explanation: "This is the width factor that appears in \\( I_0(x)\\sim e^x/\\sqrt{2\\pi x} \\)." },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{2x}} \\).",
      canonicalAnswer: "sqrt(pi/(2*x))",
    },
  },
  {
    id: "am4d-004",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using the leading Laplace estimate \\( \\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta \\sim e^{x}\\sqrt{2\\pi/x}\\,\\cdot\\tfrac12 \\cdot 2 \\) only through the peak, derive the leading large-\\( x \\) behaviour of \\( I_0(x)=\\tfrac{1}{\\pi}\\int_0^\\pi e^{x\\cos\\theta}\\,d\\theta \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Bessel I0", "leading order", "Laplace's method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Approximate the exponent near the peak.", workingLatex: "e^{x\\cos\\theta} \\approx e^{x}\\,e^{-x\\theta^2/2} \\quad (\\theta\\to 0).", explanation: "Using \\( \\cos\\theta\\approx 1-\\theta^2/2 \\) from the maximum at \\( \\theta=0 \\)." },
        { stepNumber: 2, description: "Extend the upper limit to infinity.", workingLatex: "\\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta \\sim e^{x}\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta.", explanation: "The Gaussian decays on a scale \\( \\theta\\sim x^{-1/2}\\ll\\pi \\), so replacing \\( \\pi \\) by \\( \\infty \\) is exponentially harmless." },
        { stepNumber: 3, description: "Insert the Gaussian value.", workingLatex: "\\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}.", explanation: "Using \\( \\int_0^\\infty e^{-x\\theta^2/2}\\,d\\theta=\\sqrt{\\pi/2x} \\) from the building-block result." },
        { stepNumber: 4, description: "Divide by \\( \\pi \\).", workingLatex: "I_0(x) \\sim \\frac{1}{\\pi}\\,e^{x}\\sqrt{\\frac{\\pi}{2x}} = \\frac{e^{x}}{\\sqrt{2\\pi x}}.", explanation: "This is the celebrated leading asymptotic of the modified Bessel function." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^{x}}{\\sqrt{2\\pi x}} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am4d-005",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 05",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Show that the substitution \\( \\cos\\theta = 1 - 2\\sin^2 u \\) (with \\( u=\\theta/2 \\)) turns \\( I_0(x)=\\tfrac{1}{\\pi}\\int_0^\\pi e^{x\\cos\\theta}\\,d\\theta \\) into a multiple of \\( \\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du \\), and state that multiple.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Bessel I0", "substitution", "half-angle"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the half-angle identity.", workingLatex: "\\cos\\theta = 1 - 2\\sin^2\\!\\frac{\\theta}{2}.", explanation: "This rewrites the exponent so the maximum at \\( \\theta=0 \\) becomes the minimum of \\( \\sin^2 u \\) at \\( u=0 \\)." },
        { stepNumber: 2, description: "Change variable \\( u=\\theta/2 \\).", workingLatex: "\\theta = 2u, \\quad d\\theta = 2\\,du, \\quad u:0\\to \\tfrac{\\pi}{2}.", explanation: "The new variable maps the half-period \\( [0,\\pi] \\) onto \\( [0,\\pi/2] \\)." },
        { stepNumber: 3, description: "Rewrite the integral.", workingLatex: "I_0(x) = \\frac{1}{\\pi}\\int_0^{\\pi/2} e^{x(1-2\\sin^2 u)}\\,2\\,du = \\frac{2e^{x}}{\\pi}\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du.", explanation: "The constant \\( e^x \\) factors out, leaving exactly the Example-Sheet integral with parameter \\( 2x \\)." },
        { stepNumber: 4, description: "State the multiple.", workingLatex: "I_0(x) = \\frac{2e^{x}}{\\pi}\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du.", explanation: "The prefactor is \\( 2e^x/\\pi \\); this links \\( I_0 \\) directly to the sheet's expansion." },
      ],
      finalAnswer: "\\( I_0(x) = \\dfrac{2e^{x}}{\\pi}\\displaystyle\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du \\).",
      canonicalAnswer: "2*exp(x)/pi",
    },
  },
  {
    id: "am4d-006",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 06",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the first subleading coefficient \\( a_1 \\) in the asymptotic series \\( I_0(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{a_1}{x}+\\cdots\\Big) \\), and hence write the two-term approximation.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Bessel I0", "asymptotic series", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the general coefficient.", workingLatex: "a_k = \\frac{1^2\\cdot 3^2\\cdots(2k-1)^2}{k!\\,8^k}.", explanation: "This is the standard coefficient of the \\( I_0 \\) asymptotic expansion, obtained from Watson's lemma on the sheet integral." },
        { stepNumber: 2, description: "Evaluate at \\( k=1 \\).", workingLatex: "a_1 = \\frac{1^2}{1!\\cdot 8} = \\frac{1}{8}.", explanation: "Only the single factor \\( (2\\cdot1-1)^2=1 \\) appears in the numerator." },
        { stepNumber: 3, description: "Write the two-term form.", workingLatex: "I_0(x) \\sim \\frac{e^{x}}{\\sqrt{2\\pi x}}\\left(1+\\frac{1}{8x}\\right).", explanation: "At \\( x=10 \\) this gives \\( 2813.5 \\) against \\( I_0(10)=2815.7 \\): a clear improvement on the \\( 2778.8 \\) leading estimate." },
      ],
      finalAnswer: "\\( a_1 = \\dfrac{1}{8} \\); \\( I_0(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}\\Big) \\).",
      canonicalAnswer: "1/8",
    },
  },

  // ─────────────────────────── STANDARD (12) ───────────────────────────
  {
    id: "am4d-007",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "By applying Laplace's method to the endpoint maximum, derive the leading large-\\( x \\) asymptotic of \\( I_0(x)=\\tfrac1\\pi\\int_0^\\pi e^{x\\cos\\theta}\\,d\\theta \\), justifying carefully why the upper limit may be sent to infinity.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Laplace's method", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum.", workingLatex: "\\phi(\\theta)=\\cos\\theta, \\quad \\phi'(\\theta)=-\\sin\\theta, \\quad \\max \\text{ at } \\theta=0.", explanation: "On \\( [0,\\pi] \\) the cosine is largest at the left endpoint, so this is an endpoint-type Laplace problem." },
        { stepNumber: 2, description: "Expand about the endpoint.", workingLatex: "\\cos\\theta = 1 - \\frac{\\theta^2}{2} + O(\\theta^4).", explanation: "Only the quadratic term is needed for the leading order; higher terms contribute to the subleading series." },
        { stepNumber: 3, description: "Factor the maximal value.", workingLatex: "\\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta = e^{x}\\int_0^{\\pi} e^{-x(1-\\cos\\theta)}\\,d\\theta.", explanation: "Pulling out \\( e^x \\) isolates the decaying part of the integrand." },
        { stepNumber: 4, description: "Localise and extend the limit.", workingLatex: "\\approx e^{x}\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta.", explanation: "The integrand is sharply peaked of width \\( \\theta\\sim x^{-1/2} \\); extending the limit from \\( \\pi \\) to \\( \\infty \\) adds only an exponentially small error \\( O(e^{-c x}) \\)." },
        { stepNumber: 5, description: "Evaluate the Gaussian.", workingLatex: "\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta = \\sqrt{\\frac{\\pi}{2x}}.", explanation: "Half of the standard Gaussian with \\( a=x/2 \\)." },
        { stepNumber: 6, description: "Assemble and normalise.", workingLatex: "I_0(x) = \\frac{1}{\\pi}\\,e^{x}\\sqrt{\\frac{\\pi}{2x}} = \\frac{e^{x}}{\\sqrt{2\\pi x}}.", explanation: "Dividing by \\( \\pi \\) gives the standard leading asymptotic of the modified Bessel function of order zero." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^{x}}{\\sqrt{2\\pi x}} \\) as \\( x\\to\\infty \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am4d-008",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Starting from \\( I_0(x)=\\dfrac{2e^x}{\\pi}\\displaystyle\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du \\), substitute \\( s=\\sin u \\) and use Watson's lemma to obtain the leading term of \\( I_0(x) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Watson's lemma", "substitution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( s=\\sin u \\).", workingLatex: "du = \\frac{ds}{\\sqrt{1-s^2}}, \\qquad u:0\\to\\tfrac{\\pi}{2} \\;\\Rightarrow\\; s:0\\to 1.", explanation: "The exponent becomes \\( e^{-2x s^2} \\); the Jacobian carries the geometry of the substitution." },
        { stepNumber: 2, description: "Rewrite the integral.", workingLatex: "I_0(x) = \\frac{2e^x}{\\pi}\\int_0^{1} \\frac{e^{-2x s^2}}{\\sqrt{1-s^2}}\\,ds.", explanation: "The peak is at \\( s=0 \\); the amplitude \\( (1-s^2)^{-1/2}\\to 1 \\) there." },
        { stepNumber: 3, description: "Set \\( w=s^2 \\) for Watson's lemma.", workingLatex: "s=\\sqrt{w},\\; ds=\\frac{dw}{2\\sqrt{w}} \\;\\Rightarrow\\; I_0(x)=\\frac{e^x}{\\pi}\\int_0^{1}\\frac{w^{-1/2}e^{-2xw}}{\\sqrt{1-w}}\\,dw.", explanation: "Watson's lemma needs the standard form \\( \\int_0^\\infty w^{\\sigma-1}e^{-\\lambda w}\\phi(w)\\,dw \\) with \\( \\lambda=2x \\)." },
        { stepNumber: 4, description: "Use the leading amplitude.", workingLatex: "\\frac{1}{\\sqrt{1-w}} = 1 + O(w), \\qquad \\int_0^{\\infty} w^{-1/2}e^{-2xw}\\,dw = \\frac{\\Gamma(1/2)}{(2x)^{1/2}}.", explanation: "Watson's lemma: only the value of the amplitude at \\( w=0 \\) sets the leading term, and the limit may be extended to \\( \\infty \\)." },
        { stepNumber: 5, description: "Assemble the leading term.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\pi}\\cdot\\frac{\\sqrt{\\pi}}{\\sqrt{2x}} = \\frac{e^{x}}{\\sqrt{2\\pi x}}.", explanation: "With \\( \\Gamma(1/2)=\\sqrt\\pi \\), this reproduces the standard leading asymptotic." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^{x}}{\\sqrt{2\\pi x}} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am4d-009",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Continue the Watson's-lemma expansion of \\( I_0(x)=\\dfrac{e^x}{\\pi}\\displaystyle\\int_0^{1}\\dfrac{w^{-1/2}e^{-2xw}}{\\sqrt{1-w}}\\,dw \\) to find the first two terms of the asymptotic series.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Watson's lemma", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the amplitude.", workingLatex: "(1-w)^{-1/2} = 1 + \\frac{1}{2}w + \\frac{3}{8}w^2 + \\cdots", explanation: "Watson's lemma sums term-by-term the binomial expansion of the smooth amplitude." },
        { stepNumber: 2, description: "Apply the Gamma-moment formula.", workingLatex: "\\int_0^{\\infty} w^{m-1/2}e^{-2xw}\\,dw = \\frac{\\Gamma(m+\\tfrac12)}{(2x)^{m+1/2}}.", explanation: "Each power of \\( w \\) integrates to a Gamma value over a higher power of \\( 2x \\)." },
        { stepNumber: 3, description: "Term \\( m=0 \\).", workingLatex: "\\frac{e^x}{\\pi}\\cdot\\frac{\\Gamma(1/2)}{(2x)^{1/2}} = \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "The leading term, using \\( \\Gamma(1/2)=\\sqrt\\pi \\)." },
        { stepNumber: 4, description: "Term \\( m=1 \\).", workingLatex: "\\frac{e^x}{\\pi}\\cdot\\frac{1}{2}\\cdot\\frac{\\Gamma(3/2)}{(2x)^{3/2}} = \\frac{e^x}{\\sqrt{2\\pi x}}\\cdot\\frac{1}{8x}.", explanation: "Using \\( \\Gamma(3/2)=\\tfrac12\\sqrt\\pi \\): the factor \\( \\tfrac12\\cdot\\tfrac12 / (2x) = 1/(8x) \\) emerges after dividing out the leading term." },
        { stepNumber: 5, description: "Combine.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1 + \\frac{1}{8x}\\right).", explanation: "The next coefficient is \\( a_1=1/8 \\), matching the closed form \\( a_k = [1^2\\cdots(2k-1)^2]/(k!8^k) \\)." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}\\Big) \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x))",
    },
  },
  {
    id: "am4d-010",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 10",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Compute the next coefficient \\( a_2 \\) in \\( I_0(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}+\\dfrac{a_2}{x^2}+\\cdots\\Big) \\) directly from the closed-form coefficient rule, and state it as an exact fraction.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "asymptotic series", "coefficient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the coefficient rule.", workingLatex: "a_k = \\frac{[1\\cdot 3\\cdots(2k-1)]^2}{k!\\,8^k}.", explanation: "The squared double-factorial in the numerator is the signature of the \\( I_0 \\) series." },
        { stepNumber: 2, description: "Set \\( k=2 \\).", workingLatex: "a_2 = \\frac{(1\\cdot 3)^2}{2!\\cdot 8^2} = \\frac{9}{2\\cdot 64}.", explanation: "Numerator \\( (1\\cdot3)^2=9 \\); denominator \\( 2!\\cdot64=128 \\)." },
        { stepNumber: 3, description: "Simplify.", workingLatex: "a_2 = \\frac{9}{128}.", explanation: "Already in lowest terms. Numerically \\( a_2=0.0703125 \\), matching the standard tabulated value." },
      ],
      finalAnswer: "\\( a_2 = \\dfrac{9}{128} \\).",
      canonicalAnswer: "9/128",
    },
  },
  {
    id: "am4d-011",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write down the three-term asymptotic expansion of \\( I_0(x) \\) for large \\( x \\), and use it to estimate \\( I_0(20) \\) to leading-order accuracy, commenting on the closeness to the exact value \\( I_0(20)\\approx 4.3558\\times10^{7} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "asymptotic series", "numerical check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Assemble three coefficients.", workingLatex: "a_0=1,\\quad a_1=\\frac{1}{8},\\quad a_2=\\frac{9}{128}.", explanation: "Taken from the closed form \\( a_k=[1\\cdots(2k-1)]^2/(k!8^k) \\)." },
        { stepNumber: 2, description: "Write the series.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1 + \\frac{1}{8x} + \\frac{9}{128x^2}\\right).", explanation: "An asymptotic (divergent) series; truncating after a few terms gives the best practical accuracy at moderate \\( x \\)." },
        { stepNumber: 3, description: "Insert \\( x=20 \\).", workingLatex: "\\frac{e^{20}}{\\sqrt{40\\pi}}\\left(1+\\frac{1}{160}+\\frac{9}{51200}\\right).", explanation: "The bracket is \\( 1.006426 \\); the prefactor is \\( e^{20}/\\sqrt{40\\pi}\\approx 4.32801\\times10^{7} \\)." },
        { stepNumber: 4, description: "Evaluate and compare.", workingLatex: "\\approx 4.35582\\times 10^{7}.", explanation: "Three terms agree with the exact \\( I_0(20) \\) to about seven significant figures, illustrating the rapid accuracy of the series at \\( x=20 \\)." },
      ],
      finalAnswer: "\\( I_0(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}+\\dfrac{9}{128x^2}\\Big) \\); gives \\( I_0(20)\\approx 4.3558\\times10^{7} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x)+9/(128*x^2))",
    },
  },
  {
    id: "am4d-012",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using \\( \\displaystyle\\int_0^{\\pi/2} e^{-X\\sin^2 t}\\,dt \\sim \\Big(\\frac{\\pi}{4X}\\Big)^{1/2}\\Big(1+\\frac{1}{4X}+\\cdots\\Big) \\) from the example sheet, set \\( X=2x \\) and the prefactor \\( 2e^x/\\pi \\) to recover the first two terms of \\( I_0(x) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "example sheet", "rescaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the relation.", workingLatex: "I_0(x) = \\frac{2e^x}{\\pi}\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du.", explanation: "From the half-angle substitution; the sheet integral appears with parameter \\( X=2x \\)." },
        { stepNumber: 2, description: "Insert the sheet expansion with \\( X=2x \\).", workingLatex: "\\int_0^{\\pi/2} e^{-2x\\sin^2 u}\\,du \\sim \\left(\\frac{\\pi}{8x}\\right)^{1/2}\\left(1+\\frac{1}{8x}+\\cdots\\right).", explanation: "Substituting \\( X=2x \\) gives \\( \\pi/4X=\\pi/8x \\) and \\( 1/4X=1/8x \\)." },
        { stepNumber: 3, description: "Multiply by the prefactor.", workingLatex: "I_0(x) \\sim \\frac{2e^x}{\\pi}\\left(\\frac{\\pi}{8x}\\right)^{1/2}\\left(1+\\frac{1}{8x}\\right).", explanation: "The two pieces simply multiply." },
        { stepNumber: 4, description: "Simplify the prefactor.", workingLatex: "\\frac{2}{\\pi}\\left(\\frac{\\pi}{8x}\\right)^{1/2} = \\frac{2}{\\pi}\\cdot\\frac{\\sqrt{\\pi}}{2\\sqrt{2x}} = \\frac{1}{\\sqrt{2\\pi x}}.", explanation: "The factors of \\( 2 \\), \\( \\pi \\) and \\( \\sqrt{8} \\) collapse exactly to the Bessel prefactor." },
        { stepNumber: 5, description: "State the result.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1+\\frac{1}{8x}\\right).", explanation: "Both the leading term and the \\( 1/8x \\) correction match the direct Watson's-lemma derivation." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}\\Big) \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x))",
    },
  },
  {
    id: "am4d-013",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading large-\\( x \\) asymptotic of the related Laplace integral \\( \\displaystyle J(x)=\\int_0^{\\pi} \\cos\\theta\\,e^{x\\cos\\theta}\\,d\\theta \\), and identify it as \\( \\pi\\,I_1(x) \\) at leading order.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Bessel I1", "Laplace's method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the amplitude at the peak.", workingLatex: "\\text{Amplitude } \\cos\\theta \\to \\cos 0 = 1 \\text{ at the maximum } \\theta=0.", explanation: "Laplace's method: a smooth amplitude that is non-zero at the maximum contributes its endpoint value at leading order." },
        { stepNumber: 2, description: "Expand near \\( \\theta=0 \\).", workingLatex: "\\cos\\theta\\,e^{x\\cos\\theta} \\approx e^{x}\\,(1)\\,e^{-x\\theta^2/2}.", explanation: "Both the exponent and the amplitude are evaluated about the peak; corrections are \\( O(1/x) \\)." },
        { stepNumber: 3, description: "Integrate the Gaussian.", workingLatex: "J(x) \\sim e^{x}\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta = e^{x}\\sqrt{\\frac{\\pi}{2x}}.", explanation: "Identical Gaussian to the \\( I_0 \\) case because the amplitude is \\( 1 \\) at leading order." },
        { stepNumber: 4, description: "Relate to \\( I_1 \\).", workingLatex: "I_1(x) = \\frac{1}{\\pi}\\int_0^{\\pi}\\cos\\theta\\,e^{x\\cos\\theta}\\,d\\theta = \\frac{J(x)}{\\pi}.", explanation: "This is the standard integral representation of \\( I_1 \\), so \\( J=\\pi I_1 \\)." },
        { stepNumber: 5, description: "State the leading asymptotic.", workingLatex: "J(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}, \\qquad I_1(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "At leading order \\( I_1 \\) and \\( I_0 \\) share the same prefactor; they differ only in the subleading series (with \\( -3/8x \\) for \\( I_1 \\))." },
      ],
      finalAnswer: "\\( J(x)\\sim e^{x}\\sqrt{\\dfrac{\\pi}{2x}} = \\pi I_1(x) \\) at leading order, with \\( I_1(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}} \\).",
      canonicalAnswer: "exp(x)*sqrt(pi/(2*x))",
    },
  },
  {
    id: "am4d-014",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Determine the leading large-\\( x \\) behaviour of \\( \\displaystyle K(x)=\\int_0^{\\pi} e^{x\\cos\\theta}\\sin^2\\theta\\,d\\theta \\), noting that the amplitude vanishes quadratically at the peak.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "vanishing amplitude", "Laplace's method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Examine the amplitude at the peak.", workingLatex: "\\sin^2\\theta \\to 0 \\text{ at } \\theta=0, \\qquad \\sin^2\\theta \\approx \\theta^2.", explanation: "Because the amplitude vanishes at the maximum, the usual leading term is absent and the next order in the Gaussian moment is needed." },
        { stepNumber: 2, description: "Localise the integral.", workingLatex: "K(x) \\approx e^{x}\\int_0^{\\infty} \\theta^2\\,e^{-x\\theta^2/2}\\,d\\theta.", explanation: "Insert \\( \\sin^2\\theta\\approx\\theta^2 \\) and \\( \\cos\\theta\\approx 1-\\theta^2/2 \\); the leading contribution is a second Gaussian moment." },
        { stepNumber: 3, description: "Use the Gaussian moment.", workingLatex: "\\int_0^{\\infty} \\theta^2 e^{-a\\theta^2}\\,d\\theta = \\frac{1}{4}\\sqrt{\\frac{\\pi}{a^3}}, \\qquad a=\\frac{x}{2}.", explanation: "Standard even moment of the Gaussian; here it supplies an extra factor of \\( 1/x \\)." },
        { stepNumber: 4, description: "Substitute \\( a=x/2 \\).", workingLatex: "\\int_0^{\\infty}\\theta^2 e^{-x\\theta^2/2}\\,d\\theta = \\frac{1}{4}\\sqrt{\\frac{8\\pi}{x^3}} = \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x^3}} \\cdot \\frac{1}{2}.", explanation: "Simplifying \\( (x/2)^{-3/2}=2^{3/2}x^{-3/2} \\) gives \\( \\tfrac14\\cdot 2\\sqrt2\\,\\sqrt{\\pi}\\,x^{-3/2}=\\tfrac{1}{\\sqrt2}\\sqrt\\pi\\,x^{-3/2} \\)." },
        { stepNumber: 5, description: "Assemble the leading term.", workingLatex: "K(x) \\sim e^{x}\\cdot \\sqrt{\\frac{\\pi}{2}}\\,x^{-3/2} = \\sqrt{\\frac{\\pi}{2}}\\,\\frac{e^x}{x^{3/2}}.", explanation: "The vanishing amplitude suppresses \\( K \\) by one power of \\( x \\) relative to \\( \\pi I_0(x) \\): \\( K(x)\\sim (\\pi/x)\\,I_0(x)\\cdot\\tfrac12\\cdot 2 \\), i.e. \\( K \\sim \\sqrt{\\pi/2}\\,e^x x^{-3/2} \\)." },
      ],
      finalAnswer: "\\( K(x) \\sim \\sqrt{\\dfrac{\\pi}{2}}\\,\\dfrac{e^{x}}{x^{3/2}} \\).",
      canonicalAnswer: "sqrt(pi/2)*exp(x)/x^(3/2)",
    },
  },
  {
    id: "am4d-015",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the ratio \\( \\dfrac{I_0(x)}{I_0(2x)} \\) behaves like \\( \\sqrt{2}\\,e^{-x} \\) at leading order as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "ratio", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write each leading asymptotic.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}, \\qquad I_0(2x) \\sim \\frac{e^{2x}}{\\sqrt{4\\pi x}}.", explanation: "Apply \\( I_0(y)\\sim e^y/\\sqrt{2\\pi y} \\) at \\( y=x \\) and \\( y=2x \\)." },
        { stepNumber: 2, description: "Form the ratio.", workingLatex: "\\frac{I_0(x)}{I_0(2x)} \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\cdot\\frac{\\sqrt{4\\pi x}}{e^{2x}}.", explanation: "Divide the two leading forms directly." },
        { stepNumber: 3, description: "Simplify.", workingLatex: "= e^{x-2x}\\sqrt{\\frac{4\\pi x}{2\\pi x}} = e^{-x}\\sqrt{2}.", explanation: "The algebraic prefactors collapse to \\( \\sqrt{2} \\); the exponential dominates the decay." },
      ],
      finalAnswer: "\\( \\dfrac{I_0(x)}{I_0(2x)} \\sim \\sqrt{2}\\,e^{-x} \\).",
      canonicalAnswer: "sqrt(2)*exp(-x)",
    },
  },
  {
    id: "am4d-016",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using the integral representation \\( I_0(x)=\\tfrac1\\pi\\int_0^\\pi e^{x\\cos\\theta}\\,d\\theta \\), verify by differentiating under the integral sign that \\( I_0'(x)=I_1(x) \\), and state the leading asymptotic of \\( I_0'(x) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "differentiation under integral", "Bessel I1"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate under the integral.", workingLatex: "I_0'(x) = \\frac{1}{\\pi}\\int_0^{\\pi} \\frac{\\partial}{\\partial x}e^{x\\cos\\theta}\\,d\\theta = \\frac{1}{\\pi}\\int_0^{\\pi}\\cos\\theta\\,e^{x\\cos\\theta}\\,d\\theta.", explanation: "The integrand is smooth in \\( x \\) on a compact \\( \\theta \\)-interval, so differentiation passes through the integral." },
        { stepNumber: 2, description: "Recognise the representation.", workingLatex: "\\frac{1}{\\pi}\\int_0^{\\pi}\\cos\\theta\\,e^{x\\cos\\theta}\\,d\\theta = I_1(x).", explanation: "This is exactly the standard integral form of \\( I_1 \\), hence \\( I_0'=I_1 \\)." },
        { stepNumber: 3, description: "State the leading asymptotic.", workingLatex: "I_0'(x) = I_1(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "At leading order \\( I_1 \\) shares the \\( I_0 \\) prefactor (the amplitude \\( \\cos\\theta\\to1 \\) at the peak)." },
      ],
      finalAnswer: "\\( I_0'(x)=I_1(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am4d-017",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading large-\\( x \\) asymptotic of the integral \\( \\displaystyle M(x)=\\int_0^{\\pi/2} e^{x\\cos\\theta}\\,d\\theta \\), where the upper limit stops short of \\( \\pi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "interior endpoint", "Laplace's method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum.", workingLatex: "\\max_{[0,\\pi/2]}\\cos\\theta = \\cos 0 = 1 \\text{ at } \\theta=0.", explanation: "The maximum is still at the left endpoint \\( \\theta=0 \\); the shortened upper limit \\( \\pi/2 \\) is far from the peak." },
        { stepNumber: 2, description: "Localise near the peak.", workingLatex: "M(x) \\approx e^{x}\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta.", explanation: "Since the Gaussian width is \\( \\theta\\sim x^{-1/2}\\ll\\pi/2 \\), the contribution from near \\( \\theta=\\pi/2 \\) is exponentially small and the limit extends to \\( \\infty \\)." },
        { stepNumber: 3, description: "Evaluate.", workingLatex: "M(x) \\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}.", explanation: "Identical to the half of \\( \\pi I_0 \\): truncating at \\( \\pi/2 \\) makes no difference at leading order because all the weight sits near \\( \\theta=0 \\)." },
      ],
      finalAnswer: "\\( M(x) \\sim e^{x}\\sqrt{\\dfrac{\\pi}{2x}} \\) (so \\( M(x)\\sim \\pi I_0(x) \\)).",
      canonicalAnswer: "exp(x)*sqrt(pi/(2*x))",
    },
  },
  {
    id: "am4d-018",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "By substituting \\( v=2x\\sin^2 u \\) in the leading neighbourhood of \\( u=0 \\) in \\( I_0(x)=\\tfrac{2e^x}{\\pi}\\int_0^{\\pi/2}e^{-2x\\sin^2u}\\,du \\), confirm the leading term and identify the small parameter governing the corrections.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "scaling", "small parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale near the peak.", workingLatex: "\\sin^2 u \\approx u^2, \\qquad v = 2x u^2 \\;\\Rightarrow\\; u = \\sqrt{\\frac{v}{2x}}, \\; du=\\frac{dv}{2\\sqrt{2x\\,v}}.", explanation: "Near \\( u=0 \\) the exponent is approximately \\( -2x u^2 \\); the rescaling makes the exponent \\( O(1) \\)." },
        { stepNumber: 2, description: "Transform the integral.", workingLatex: "I_0(x) \\approx \\frac{2e^x}{\\pi}\\int_0^{\\infty} e^{-v}\\,\\frac{dv}{2\\sqrt{2x\\,v}} = \\frac{e^x}{\\pi\\sqrt{2x}}\\int_0^{\\infty} v^{-1/2}e^{-v}\\,dv.", explanation: "The upper limit extends to \\( \\infty \\) (exponentially small tail), giving a Gamma integral." },
        { stepNumber: 3, description: "Evaluate the Gamma.", workingLatex: "\\int_0^{\\infty} v^{-1/2}e^{-v}\\,dv = \\Gamma\\!\\left(\\tfrac12\\right) = \\sqrt{\\pi}.", explanation: "The defining integral of \\( \\Gamma(1/2) \\)." },
        { stepNumber: 4, description: "Assemble and identify the parameter.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\pi\\sqrt{2x}}\\sqrt{\\pi} = \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "Corrections come from \\( \\sin^2 u = u^2 - \\tfrac13 u^4+\\cdots \\); the small parameter is \\( 1/x \\), each correction adding a factor \\( 1/(8x) \\)-scale." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}} \\); corrections are organised in powers of \\( 1/x \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },

  // ─────────────────────────── CHALLENGE (12) ───────────────────────────
  {
    id: "am4d-019",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Following the example sheet, derive the full asymptotic series \\( \\displaystyle\\int_0^{\\pi/2} e^{-X\\sin^2 t}\\,dt \\sim \\Big(\\frac{\\pi}{4X}\\Big)^{1/2}\\sum_{n\\ge0} \\frac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,(4X)^n} \\) as \\( X\\to\\infty \\), then set \\( X=2x \\) to obtain the corresponding series for \\( I_0(x) \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "example sheet", "full series", "Watson's lemma"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( s=\\sin t \\).", workingLatex: "\\int_0^{\\pi/2} e^{-X\\sin^2 t}\\,dt = \\int_0^{1} \\frac{e^{-X s^2}}{\\sqrt{1-s^2}}\\,ds.", explanation: "The peak at \\( t=0 \\) becomes \\( s=0 \\); the Jacobian supplies the smooth amplitude \\( (1-s^2)^{-1/2} \\)." },
        { stepNumber: 2, description: "Set \\( w=s^2 \\).", workingLatex: "= \\frac{1}{2}\\int_0^{1} \\frac{w^{-1/2}e^{-Xw}}{\\sqrt{1-w}}\\,dw.", explanation: "Putting the integral in Watson's-lemma form with exponent \\( e^{-Xw} \\)." },
        { stepNumber: 3, description: "Binomial-expand the amplitude.", workingLatex: "(1-w)^{-1/2} = \\sum_{n\\ge0} \\binom{-1/2}{n}(-w)^n = \\sum_{n\\ge0} \\frac{(2n)!}{4^n (n!)^2}\\,w^n.", explanation: "The central binomial coefficient form; equivalently \\( \\frac{[1\\cdot3\\cdots(2n-1)]}{2^n n!} \\)." },
        { stepNumber: 4, description: "Integrate term by term (Watson).", workingLatex: "\\int_0^{\\infty} w^{n-1/2}e^{-Xw}\\,dw = \\frac{\\Gamma(n+\\tfrac12)}{X^{n+1/2}}.", explanation: "Watson's lemma justifies term-wise integration with the limit extended to \\( \\infty \\)." },
        { stepNumber: 5, description: "Combine the Gamma and binomial factors.", workingLatex: "\\frac{1}{2}\\sum_{n\\ge0}\\frac{(2n)!}{4^n(n!)^2}\\,\\frac{\\Gamma(n+\\tfrac12)}{X^{n+1/2}} = \\left(\\frac{\\pi}{4X}\\right)^{1/2}\\sum_{n\\ge0}\\frac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,(4X)^n}.", explanation: "Using \\( \\Gamma(n+\\tfrac12)=\\frac{(2n)!}{4^n n!}\\sqrt\\pi \\) and collecting, the squared double-factorial emerges, matching the sheet." },
        { stepNumber: 6, description: "Set \\( X=2x \\) and add the Bessel prefactor.", workingLatex: "I_0(x) = \\frac{2e^x}{\\pi}\\left(\\frac{\\pi}{8x}\\right)^{1/2}\\sum_{n\\ge0}\\frac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,(8x)^n} = \\frac{e^x}{\\sqrt{2\\pi x}}\\sum_{n\\ge0}\\frac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,(8x)^n}.", explanation: "The prefactor collapses to \\( 1/\\sqrt{2\\pi x} \\) and \\( 4X=8x \\) gives the standard \\( I_0 \\) coefficients \\( a_n=[1\\cdots(2n-1)]^2/(n!8^n) \\)." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\displaystyle\\sum_{n\\ge0}\\dfrac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,(8x)^n} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x)+9/(128*x^2)+225/(3072*x^3))",
    },
  },
  {
    id: "am4d-020",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 20",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Compute the third subleading coefficient \\( a_3 \\) of the \\( I_0 \\) series \\( I_0(x)\\sim\\dfrac{e^x}{\\sqrt{2\\pi x}}\\sum_n a_n x^{-n} \\), giving it as a fully reduced fraction, and verify the recurrence \\( a_{n+1}=\\dfrac{(2n+1)^2}{8(n+1)}a_n \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "coefficient", "recurrence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the closed form.", workingLatex: "a_n = \\frac{[1\\cdot3\\cdots(2n-1)]^2}{n!\\,8^n}.", explanation: "Established from the Watson's-lemma derivation." },
        { stepNumber: 2, description: "Form the ratio for the recurrence.", workingLatex: "\\frac{a_{n+1}}{a_n} = \\frac{(2n+1)^2}{(n+1)\\cdot 8}.", explanation: "The double-factorial gains the factor \\( (2n+1)^2 \\); \\( (n+1)! = (n+1)n! \\) and \\( 8^{n+1}=8\\cdot8^n \\) give the denominator." },
        { stepNumber: 3, description: "State the recurrence.", workingLatex: "a_{n+1} = \\frac{(2n+1)^2}{8(n+1)}\\,a_n.", explanation: "This matches the claimed recurrence exactly." },
        { stepNumber: 4, description: "Step up from \\( a_2 \\).", workingLatex: "a_3 = \\frac{(2\\cdot2+1)^2}{8\\cdot3}\\,a_2 = \\frac{25}{24}\\cdot\\frac{9}{128}.", explanation: "Using \\( a_2=9/128 \\) and \\( n=2 \\) in the recurrence." },
        { stepNumber: 5, description: "Simplify.", workingLatex: "a_3 = \\frac{225}{3072} = \\frac{75}{1024}.", explanation: "Reducing by \\( 3 \\): numerically \\( a_3=0.07324\\ldots \\), matching the tabulated coefficient." },
      ],
      finalAnswer: "\\( a_3 = \\dfrac{225}{3072} = \\dfrac{75}{1024} \\).",
      canonicalAnswer: "75/1024",
    },
  },
  {
    id: "am4d-021",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use the example-sheet reflection identity \\( \\Gamma(z)\\Gamma(1-z)=\\dfrac{\\pi}{\\sin\\pi z} \\) to express the coefficient \\( \\dfrac{\\Gamma(1/2)}{\\Gamma(1/2-m)\\,m!}\\,\\Gamma(1/2+m) \\) appearing in the \\( \\int_0^{\\pi/2}e^{x\\sin^2 t}dt \\) expansion as \\( \\dfrac{(-1)^m[1\\cdot3\\cdots(2m-1)]^2}{m!\\,4^m} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Gamma reflection", "coefficient identity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rewrite \\( \\Gamma(1/2-m) \\) via reflection.", workingLatex: "\\Gamma\\!\\left(\\tfrac12-m\\right)\\Gamma\\!\\left(\\tfrac12+m\\right) = \\frac{\\pi}{\\sin\\pi(\\tfrac12-m)} = \\frac{\\pi}{\\cos\\pi m} = (-1)^m\\pi.", explanation: "Set \\( z=\\tfrac12-m \\) so \\( 1-z=\\tfrac12+m \\); \\( \\sin\\pi(\\tfrac12-m)=\\cos\\pi m=(-1)^m \\)." },
        { stepNumber: 2, description: "Solve for the ratio of Gammas.", workingLatex: "\\frac{\\Gamma(\\tfrac12+m)}{\\Gamma(\\tfrac12-m)} = \\frac{(-1)^m\\pi}{\\Gamma(\\tfrac12-m)^2} = \\frac{(-1)^m\\,\\Gamma(\\tfrac12+m)^2}{\\pi}.", explanation: "Multiplying the reflection relation by \\( \\Gamma(\\tfrac12+m)/\\Gamma(\\tfrac12-m) \\) isolates the ratio in terms of \\( \\Gamma(\\tfrac12+m)^2 \\)." },
        { stepNumber: 3, description: "Insert \\( \\Gamma(1/2)=\\sqrt\\pi \\).", workingLatex: "\\frac{\\Gamma(\\tfrac12)\\,\\Gamma(\\tfrac12+m)}{\\Gamma(\\tfrac12-m)\\,m!} = \\frac{\\sqrt\\pi}{m!}\\cdot\\frac{(-1)^m\\,\\Gamma(\\tfrac12+m)^2}{\\pi}.", explanation: "The coefficient in the expansion is assembled from these pieces." },
        { stepNumber: 4, description: "Use the half-integer Gamma.", workingLatex: "\\Gamma\\!\\left(\\tfrac12+m\\right) = \\frac{(2m)!}{4^m\\,m!}\\sqrt\\pi = \\frac{[1\\cdot3\\cdots(2m-1)]}{2^m}\\sqrt{\\pi}.", explanation: "The standard product formula for the half-integer Gamma." },
        { stepNumber: 5, description: "Square and simplify.", workingLatex: "\\frac{\\sqrt\\pi}{m!}\\cdot\\frac{(-1)^m}{\\pi}\\cdot\\frac{[1\\cdot3\\cdots(2m-1)]^2}{4^m}\\pi = \\frac{(-1)^m[1\\cdot3\\cdots(2m-1)]^2}{m!\\,4^m}\\sqrt{\\pi}.", explanation: "The factors of \\( \\pi \\) collapse, leaving a single \\( \\sqrt\\pi \\) that pairs with the overall \\( e^x/2 \\) prefactor in the sheet expansion." },
        { stepNumber: 6, description: "State the coefficient.", workingLatex: "\\frac{\\Gamma(\\tfrac12)\\Gamma(\\tfrac12+m)}{\\Gamma(\\tfrac12-m)\\,m!} = \\sqrt\\pi\\,\\frac{(-1)^m[1\\cdot3\\cdots(2m-1)]^2}{m!\\,4^m}.", explanation: "The alternating sign and squared double-factorial confirm the structure quoted on the example sheet (the \\( (-1)^m \\) is the signature of the \\( +x\\sin^2 t \\) sign)." },
      ],
      finalAnswer: "Coefficient \\( = \\sqrt\\pi\\,\\dfrac{(-1)^m[1\\cdot3\\cdots(2m-1)]^2}{m!\\,4^m} \\).",
    },
  },
  {
    id: "am4d-022",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the subleading asymptotic of \\( I_0(x) \\) directly by expanding \\( e^{x\\cos\\theta}=e^x e^{-x(\\theta^2/2-\\theta^4/24+\\cdots)} \\) about \\( \\theta=0 \\), keeping the \\( \\theta^4 \\) term, and confirm the \\( 1/(8x) \\) correction.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "quartic correction", "Gaussian moments"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the exponent.", workingLatex: "x\\cos\\theta = x - \\frac{x\\theta^2}{2} + \\frac{x\\theta^4}{24} - \\cdots", explanation: "The quartic term is the leading correction beyond the Gaussian; it scales as \\( x\\theta^4 \\)." },
        { stepNumber: 2, description: "Factor and expand the correction exponential.", workingLatex: "e^{x\\cos\\theta} = e^{x}e^{-x\\theta^2/2}\\left(1 + \\frac{x\\theta^4}{24} + \\cdots\\right).", explanation: "Expand \\( e^{x\\theta^4/24}\\approx 1+x\\theta^4/24 \\); higher terms give \\( O(1/x^2) \\)." },
        { stepNumber: 3, description: "Integrate the leading Gaussian.", workingLatex: "\\frac{1}{\\pi}e^x\\int_0^{\\infty} e^{-x\\theta^2/2}\\,d\\theta = \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "The \\( n=0 \\) contribution, as before." },
        { stepNumber: 4, description: "Integrate the quartic correction.", workingLatex: "\\frac{1}{\\pi}e^x\\cdot\\frac{x}{24}\\int_0^{\\infty}\\theta^4 e^{-x\\theta^2/2}\\,d\\theta.", explanation: "We need the fourth Gaussian moment to capture the correction." },
        { stepNumber: 5, description: "Use the moment.", workingLatex: "\\int_0^{\\infty}\\theta^4 e^{-a\\theta^2}\\,d\\theta = \\frac{3}{8}\\sqrt{\\frac{\\pi}{a^5}}, \\quad a=\\frac{x}{2}.", explanation: "Standard even moment; with \\( a=x/2 \\) it is \\( \\frac{3}{8}\\sqrt{\\pi}\\,(2/x)^{5/2} \\)." },
        { stepNumber: 6, description: "Combine the correction.", workingLatex: "\\frac{e^x}{\\pi}\\cdot\\frac{x}{24}\\cdot\\frac{3}{8}\\sqrt{\\pi}\\left(\\frac{2}{x}\\right)^{5/2} = \\frac{e^x}{\\sqrt{2\\pi x}}\\cdot\\frac{1}{8x}.", explanation: "Simplifying the powers of \\( 2 \\) and \\( x \\): the \\( x \\) in front cancels four of the \\( x^{-5/2} \\), leaving \\( x^{-3/2} \\), i.e. one extra power of \\( 1/x \\) relative to leading, with coefficient \\( 1/8 \\)." },
        { stepNumber: 7, description: "Assemble.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1 + \\frac{1}{8x}\\right).", explanation: "The quartic-term computation reproduces \\( a_1=1/8 \\), independently of the Watson's-lemma route." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}\\Big) \\), the \\( \\theta^4 \\) term supplying the \\( 1/(8x) \\) correction.",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x))",
    },
  },
  {
    id: "am4d-023",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that for large \\( x \\) the modified Bessel functions satisfy \\( I_0(x)+I_1(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(2-\\dfrac{1}{4x}+\\cdots\\Big) \\), using \\( I_0\\sim\\frac{e^x}{\\sqrt{2\\pi x}}(1+\\frac{1}{8x}) \\) and \\( I_1\\sim\\frac{e^x}{\\sqrt{2\\pi x}}(1-\\frac{3}{8x}) \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Bessel I1", "series combination"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write both series.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1+\\frac{1}{8x}\\right), \\quad I_1(x)\\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1-\\frac{3}{8x}\\right).", explanation: "The \\( I_1 \\) correction is negative; its leading coefficient is \\( -(4\\cdot1^2-1)/8=-3/8 \\)." },
        { stepNumber: 2, description: "Add the brackets.", workingLatex: "\\left(1+\\frac{1}{8x}\\right) + \\left(1-\\frac{3}{8x}\\right) = 2 - \\frac{2}{8x}.", explanation: "Add the constant terms and the \\( 1/x \\) terms separately." },
        { stepNumber: 3, description: "Simplify.", workingLatex: "2 - \\frac{2}{8x} = 2 - \\frac{1}{4x}.", explanation: "Reducing \\( 2/8=1/4 \\)." },
        { stepNumber: 4, description: "Combine with the prefactor.", workingLatex: "I_0(x)+I_1(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(2 - \\frac{1}{4x}\\right).", explanation: "The shared prefactor \\( e^x/\\sqrt{2\\pi x} \\) factors out cleanly, confirming the stated result." },
      ],
      finalAnswer: "\\( I_0(x)+I_1(x)\\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(2-\\dfrac{1}{4x}\\Big) \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(2-1/(4*x))",
    },
  },
  {
    id: "am4d-024",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By writing the integrand as \\( e^{x\\cos\\theta}=e^{x}e^{-x(1-\\cos\\theta)} \\) and substituting \\( \\tau = 1-\\cos\\theta \\), show \\( I_0(x)=\\dfrac{e^x}{\\pi}\\displaystyle\\int_0^{2}\\dfrac{e^{-x\\tau}}{\\sqrt{\\tau(2-\\tau)}}\\,d\\tau \\) and obtain its leading large-\\( x \\) form via Watson's lemma.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "substitution", "Watson's lemma"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( \\tau=1-\\cos\\theta \\).", workingLatex: "d\\tau = \\sin\\theta\\,d\\theta, \\qquad \\theta:0\\to\\pi \\;\\Rightarrow\\; \\tau:0\\to 2.", explanation: "The maximum \\( \\theta=0 \\) maps to \\( \\tau=0 \\), the new lower limit and the location of the Watson peak." },
        { stepNumber: 2, description: "Express \\( \\sin\\theta \\) in \\( \\tau \\).", workingLatex: "\\sin\\theta = \\sqrt{1-\\cos^2\\theta} = \\sqrt{(1-\\cos\\theta)(1+\\cos\\theta)} = \\sqrt{\\tau(2-\\tau)}.", explanation: "Since \\( \\cos\\theta = 1-\\tau \\), we have \\( 1+\\cos\\theta = 2-\\tau \\)." },
        { stepNumber: 3, description: "Rewrite the integral.", workingLatex: "I_0(x) = \\frac{e^x}{\\pi}\\int_0^{2} \\frac{e^{-x\\tau}}{\\sqrt{\\tau(2-\\tau)}}\\,d\\tau.", explanation: "Dividing \\( d\\theta = d\\tau/\\sin\\theta \\) introduces the algebraic-branch-point amplitude at \\( \\tau=0 \\)." },
        { stepNumber: 4, description: "Identify the Watson exponent.", workingLatex: "\\frac{1}{\\sqrt{\\tau(2-\\tau)}} = \\frac{1}{\\sqrt{2}}\\,\\tau^{-1/2}\\left(1 + \\frac{\\tau}{4} + \\cdots\\right).", explanation: "Expanding \\( (2-\\tau)^{-1/2}=2^{-1/2}(1+\\tau/4+\\cdots) \\); the singularity \\( \\tau^{-1/2} \\) sets the half-integer power." },
        { stepNumber: 5, description: "Apply Watson's lemma at leading order.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\pi\\sqrt2}\\int_0^{\\infty}\\tau^{-1/2}e^{-x\\tau}\\,d\\tau = \\frac{e^x}{\\pi\\sqrt2}\\cdot\\frac{\\Gamma(1/2)}{x^{1/2}}.", explanation: "Only the amplitude at \\( \\tau=0 \\) matters at leading order; \\( \\Gamma(1/2)=\\sqrt\\pi \\)." },
        { stepNumber: 6, description: "Simplify.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\pi\\sqrt2}\\cdot\\frac{\\sqrt\\pi}{\\sqrt x} = \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "The factors collapse exactly to the standard prefactor; the \\( \\tau/4 \\) amplitude term would give the \\( 1/(8x) \\) correction at next order." },
      ],
      finalAnswer: "\\( I_0(x)=\\dfrac{e^x}{\\pi}\\displaystyle\\int_0^{2}\\dfrac{e^{-x\\tau}}{\\sqrt{\\tau(2-\\tau)}}\\,d\\tau \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}} \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am4d-025",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "From the representation \\( I_0(x)=\\dfrac{e^x}{\\pi}\\displaystyle\\int_0^2 \\dfrac{e^{-x\\tau}}{\\sqrt{2}\\,\\sqrt\\tau}\\big(1+\\tfrac{\\tau}{4}+\\tfrac{3\\tau^2}{32}+\\cdots\\big)\\,d\\tau \\), extract the first two terms of the asymptotic series for \\( I_0(x) \\) by term-by-term Watson's lemma.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "Watson's lemma", "subleading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the moment formula.", workingLatex: "\\int_0^{\\infty}\\tau^{m-1/2}e^{-x\\tau}\\,d\\tau = \\frac{\\Gamma(m+\\tfrac12)}{x^{m+1/2}}.", explanation: "Each power of \\( \\tau \\) in the amplitude integrates to a Gamma value over a higher power of \\( x \\)." },
        { stepNumber: 2, description: "Term \\( m=0 \\).", workingLatex: "\\frac{e^x}{\\pi\\sqrt2}\\cdot\\frac{\\Gamma(1/2)}{x^{1/2}} = \\frac{e^x}{\\sqrt{2\\pi x}}.", explanation: "The leading term, using \\( \\Gamma(1/2)=\\sqrt\\pi \\)." },
        { stepNumber: 3, description: "Term \\( m=1 \\) with amplitude coefficient \\( 1/4 \\).", workingLatex: "\\frac{e^x}{\\pi\\sqrt2}\\cdot\\frac{1}{4}\\cdot\\frac{\\Gamma(3/2)}{x^{3/2}}.", explanation: "The amplitude term \\( \\tau/4 \\) raises the power and brings in \\( \\Gamma(3/2)=\\tfrac12\\sqrt\\pi \\)." },
        { stepNumber: 4, description: "Simplify the correction.", workingLatex: "= \\frac{e^x}{\\pi\\sqrt2}\\cdot\\frac{1}{4}\\cdot\\frac{\\sqrt\\pi}{2\\,x^{3/2}} = \\frac{e^x}{\\sqrt{2\\pi x}}\\cdot\\frac{1}{8x}.", explanation: "Dividing by the leading term isolates the factor \\( \\tfrac14\\cdot\\tfrac12 / x = 1/(8x) \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1 + \\frac{1}{8x}\\right).", explanation: "Both terms agree with the established series; the \\( 3\\tau^2/32 \\) amplitude term would supply \\( a_2=9/128 \\) at the next order." },
      ],
      finalAnswer: "\\( I_0(x) \\sim \\dfrac{e^x}{\\sqrt{2\\pi x}}\\Big(1+\\dfrac{1}{8x}\\Big) \\).",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)*(1+1/(8*x))",
    },
  },
  {
    id: "am4d-026",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Verify the recurrence \\( a_{n+1}=\\dfrac{(2n+1)^2}{8(n+1)}a_n \\) implies the \\( I_0 \\) asymptotic series is divergent for every fixed \\( x \\), and estimate the optimal truncation index \\( N_\\star(x) \\) (where the terms are smallest).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "divergent series", "optimal truncation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Examine the term ratio.", workingLatex: "\\frac{a_{n+1}x^{-(n+1)}}{a_n x^{-n}} = \\frac{(2n+1)^2}{8(n+1)\\,x}.", explanation: "The \\( n \\)th term of the series is \\( a_n x^{-n} \\); we compare successive magnitudes." },
        { stepNumber: 2, description: "Large-\\( n \\) growth.", workingLatex: "\\frac{(2n+1)^2}{8(n+1)\\,x} \\sim \\frac{4n^2}{8nx} = \\frac{n}{2x} \\to \\infty.", explanation: "For fixed \\( x \\) the ratio grows without bound in \\( n \\), so terms eventually increase: the series diverges (it is asymptotic, not convergent)." },
        { stepNumber: 3, description: "Find where terms stop decreasing.", workingLatex: "\\frac{n}{2x} = 1 \\;\\Rightarrow\\; n \\approx 2x.", explanation: "The terms decrease while the ratio is \\( <1 \\) and grow once it exceeds \\( 1 \\); the minimum term sits near \\( n\\approx 2x \\)." },
        { stepNumber: 4, description: "State the optimal truncation.", workingLatex: "N_\\star(x) \\approx 2x.", explanation: "Truncating near \\( N_\\star \\) gives the best (superasymptotic) accuracy." },
        { stepNumber: 5, description: "Estimate the optimal error.", workingLatex: "\\text{smallest term} \\sim a_{N_\\star}x^{-N_\\star} \\sim e^{-2x}\\;(\\text{up to algebraic factors}).", explanation: "Stirling on \\( a_n\\sim (n!/2^n)\\cdots \\) with \\( n=2x \\) gives an exponentially small minimal term \\( \\sim e^{-2x} \\): the characteristic accuracy floor of the divergent expansion." },
      ],
      finalAnswer: "The series diverges for all \\( x \\); optimal truncation \\( N_\\star(x)\\approx 2x \\), with minimal error \\( \\sim e^{-2x} \\).",
    },
  },
  {
    id: "am4d-027",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A drum-like average gives \\( P(x)=\\dfrac{1}{2\\pi}\\displaystyle\\int_0^{2\\pi} e^{x\\cos\\theta}\\,d\\theta \\). Show \\( P(x)=I_0(x) \\) and hence find the two-term large-\\( x \\) expansion of \\( \\ln P(x) \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "logarithm", "asymptotic expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduce the full-period average.", workingLatex: "P(x) = \\frac{1}{2\\pi}\\int_0^{2\\pi} e^{x\\cos\\theta}\\,d\\theta = \\frac{1}{\\pi}\\int_0^{\\pi} e^{x\\cos\\theta}\\,d\\theta = I_0(x).", explanation: "The integrand is symmetric about \\( \\theta=\\pi \\), so the \\( [0,2\\pi] \\) integral is twice the \\( [0,\\pi] \\) one, cancelling the extra factor \\( 2 \\)." },
        { stepNumber: 2, description: "Insert the two-term series.", workingLatex: "I_0(x) \\sim \\frac{e^x}{\\sqrt{2\\pi x}}\\left(1+\\frac{1}{8x}\\right).", explanation: "Take logs of this to expand \\( \\ln P \\)." },
        { stepNumber: 3, description: "Take the logarithm.", workingLatex: "\\ln I_0(x) \\sim x - \\frac{1}{2}\\ln(2\\pi x) + \\ln\\!\\left(1+\\frac{1}{8x}\\right).", explanation: "The log of a product is the sum of logs; the exponential gives the linear \\( x \\)." },
        { stepNumber: 4, description: "Expand the last logarithm.", workingLatex: "\\ln\\!\\left(1+\\frac{1}{8x}\\right) = \\frac{1}{8x} + O\\!\\left(\\frac{1}{x^2}\\right).", explanation: "Using \\( \\ln(1+\\epsilon)=\\epsilon-\\epsilon^2/2+\\cdots \\) with \\( \\epsilon=1/8x \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "\\ln P(x) \\sim x - \\frac{1}{2}\\ln(2\\pi x) + \\frac{1}{8x}.", explanation: "The dominant term is linear in \\( x \\); the logarithmic and \\( 1/x \\) corrections follow." },
      ],
      finalAnswer: "\\( P(x)=I_0(x) \\); \\( \\ln P(x)\\sim x - \\tfrac12\\ln(2\\pi x) + \\dfrac{1}{8x} \\).",
      canonicalAnswer: "x - (1/2)*log(2*pi*x) + 1/(8*x)",
    },
  },
  {
    id: "am4d-028",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading large-\\( x \\) asymptotic of the generalised integral \\( \\displaystyle G(x)=\\int_0^{\\pi} e^{x\\cos\\theta}\\,\\theta^{2}\\,d\\theta \\), where the algebraic factor \\( \\theta^2 \\) vanishes at the peak.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "algebraic amplitude", "Gaussian moment"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note where the weight sits.", workingLatex: "\\text{Peak at } \\theta=0, \\quad \\text{amplitude } \\theta^2 \\to 0.", explanation: "Because the amplitude vanishes quadratically at the maximum, the leading behaviour comes from a second Gaussian moment, not the zeroth." },
        { stepNumber: 2, description: "Localise.", workingLatex: "G(x) \\approx e^{x}\\int_0^{\\infty} \\theta^2\\,e^{-x\\theta^2/2}\\,d\\theta.", explanation: "Replace \\( \\cos\\theta\\approx 1-\\theta^2/2 \\) and keep the algebraic factor exactly; the limit extends to \\( \\infty \\)." },
        { stepNumber: 3, description: "Use the second moment.", workingLatex: "\\int_0^{\\infty}\\theta^2 e^{-a\\theta^2}\\,d\\theta = \\frac{\\sqrt\\pi}{4}\\,a^{-3/2}, \\quad a=\\frac{x}{2}.", explanation: "Standard Gaussian moment; \\( a^{-3/2}=(x/2)^{-3/2}=2^{3/2}x^{-3/2} \\)." },
        { stepNumber: 4, description: "Substitute and simplify.", workingLatex: "G(x) \\sim e^{x}\\cdot\\frac{\\sqrt\\pi}{4}\\cdot 2^{3/2}x^{-3/2} = e^x\\sqrt{\\frac{\\pi}{2}}\\,x^{-3/2}.", explanation: "Collecting \\( \\tfrac14\\cdot2\\sqrt2 = \\tfrac{1}{\\sqrt2} \\), so the prefactor is \\( \\sqrt{\\pi/2} \\)." },
        { stepNumber: 5, description: "State the result.", workingLatex: "G(x) \\sim \\sqrt{\\frac{\\pi}{2}}\\,\\frac{e^x}{x^{3/2}}.", explanation: "The algebraic factor \\( \\theta^2 \\) suppresses the result by \\( 1/x \\) relative to \\( \\pi I_0(x) \\)." },
      ],
      finalAnswer: "\\( G(x) \\sim \\sqrt{\\dfrac{\\pi}{2}}\\,\\dfrac{e^{x}}{x^{3/2}} \\).",
      canonicalAnswer: "sqrt(pi/2)*exp(x)/x^(3/2)",
    },
  },
  {
    id: "am4d-029",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By relating \\( \\displaystyle\\int_0^{\\pi/2} e^{-x\\sin^2 t}\\,dt \\) (the decaying sheet integral) to the growing one via \\( t\\mapsto \\pi/2-t \\), and then to \\( I_0 \\), show the leading behaviour of \\( H(x)=\\displaystyle\\int_0^{\\pi/2}e^{-x\\sin^2 t}\\,dt \\) is \\( \\sqrt{\\pi/(4x)} \\) and explain why it is algebraically small, not exponentially small.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "example sheet", "decaying integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum of the exponent.", workingLatex: "-\\sin^2 t \\text{ is maximal where } \\sin^2 t \\text{ is minimal}: \\; t=0.", explanation: "For the decaying integral the dominant point is where \\( \\sin^2 t \\) is smallest, namely the endpoint \\( t=0 \\)." },
        { stepNumber: 2, description: "Expand about \\( t=0 \\).", workingLatex: "\\sin^2 t \\approx t^2, \\qquad e^{-x\\sin^2 t} \\approx e^{-x t^2}.", explanation: "Near the endpoint the exponent is a plain decaying Gaussian; there is no large \\( e^x \\) factor because the maximum value of the exponent is \\( 0 \\)." },
        { stepNumber: 3, description: "Integrate the Gaussian.", workingLatex: "H(x) \\sim \\int_0^{\\infty} e^{-x t^2}\\,dt = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}} = \\sqrt{\\frac{\\pi}{4x}}.", explanation: "Half of the standard Gaussian; the limit extends to \\( \\infty \\) with exponentially small error." },
        { stepNumber: 4, description: "Explain the size.", workingLatex: "H(x) \\sim \\left(\\frac{\\pi}{4x}\\right)^{1/2}.", explanation: "The exponent's maximum is \\( 0 \\), so \\( e^{x\\cdot 0}=1 \\): the integral decays only algebraically (\\( \\sim x^{-1/2} \\)), in contrast to the growing \\( I_0 \\) which carries the \\( e^x \\) factor." },
        { stepNumber: 5, description: "Connect to the sheet form.", workingLatex: "H(x) \\sim \\left(\\frac{\\pi}{4x}\\right)^{1/2}\\left(1+\\frac{1}{1!}\\frac{(1/2)^2}{x}\\cdot\\frac{1}{4}+\\cdots\\right).", explanation: "This is exactly the example-sheet expansion; the same coefficient machinery (squared double factorials) governs the corrections, but here there is no exponential prefactor." },
      ],
      finalAnswer: "\\( H(x) \\sim \\Big(\\dfrac{\\pi}{4x}\\Big)^{1/2} \\); algebraically small because the exponent's maximum value is \\( 0 \\).",
      canonicalAnswer: "sqrt(pi/(4*x))",
    },
  },
  // REVIEW: final part asks for a qualitative regime-of-validity discussion (when the two-term truncation beats the leading term), which is reasoned rather than a single numerically-checkable closed form; the numeric crossover values quoted were spot-checked but the conclusion is partly interpretive.
  {
    id: "am4d-030",
    topicRef: "am4d",
    topicTitle: "Laplace integrals for special functions (Bessel I₀) 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the Bessel asymptotic \\( I_0(x)\\sim\\dfrac{e^x}{\\sqrt{2\\pi x}}\\big(1+\\frac{1}{8x}+\\frac{9}{128x^2}\\big) \\), estimate the relative error of the leading-only term at \\( x=4 \\) and at \\( x=10 \\), and discuss the regime in which including the \\( 1/(8x) \\) term is worthwhile.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Bessel I0", "error estimate", "validity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Relative error of the leading term.", workingLatex: "\\frac{I_0(x)-\\frac{e^x}{\\sqrt{2\\pi x}}}{I_0(x)} \\approx 1 - \\frac{1}{1+\\frac{1}{8x}} \\approx \\frac{1}{8x}.", explanation: "Dividing the leading term by the (more accurate) two-term series, the relative deficit is approximately \\( 1/(8x) \\) for large \\( x \\)." },
        { stepNumber: 2, description: "Evaluate at \\( x=4 \\).", workingLatex: "\\frac{1}{8\\cdot4} = \\frac{1}{32} \\approx 3.1\\%.", explanation: "At \\( x=4 \\) the leading term alone is off by a few percent — the \\( e^x/\\sqrt{2\\pi x} \\) value underestimates \\( I_0(4) \\)." },
        { stepNumber: 3, description: "Evaluate at \\( x=10 \\).", workingLatex: "\\frac{1}{8\\cdot10} = \\frac{1}{80} \\approx 1.25\\%.", explanation: "At \\( x=10 \\) the leading error is about \\( 1.25\\% \\); indeed \\( e^{10}/\\sqrt{20\\pi}=2778.8 \\) versus \\( I_0(10)=2815.7 \\), a \\( 1.3\\% \\) gap." },
        { stepNumber: 4, description: "Assess the second correction.", workingLatex: "\\frac{9}{128x^2}\\Big/\\frac{1}{8x} = \\frac{9}{16x}.", explanation: "The \\( 1/x^2 \\) term is smaller than the \\( 1/x \\) term once \\( x \\gtrsim 1 \\); including \\( 1/(8x) \\) already removes the bulk of the error for \\( x\\gtrsim 3 \\)." },
        { stepNumber: 5, description: "State the regime.", workingLatex: "x \\gtrsim 3\\!-\\!4: \\text{ the two-term form is accurate to } \\lesssim 1\\%.", explanation: "Adding the \\( 1/(8x) \\) term is worthwhile whenever a sub-percent accuracy is needed at moderate \\( x \\); beyond \\( x\\approx 10 \\) even the leading term is within ~1%." },
      ],
      finalAnswer: "Leading-only relative error \\( \\approx 1/(8x) \\): about \\( 3.1\\% \\) at \\( x=4 \\) and \\( 1.25\\% \\) at \\( x=10 \\); the \\( 1/(8x) \\) term is worth keeping for \\( x\\gtrsim 3\\!-\\!4 \\).",
    },
  },
];
