import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — am5a
 * "Integration by parts & the Riemann–Lebesgue lemma" (Oscillatory Integrals)
 *
 * Scope: the large-parameter decay of \int f(t) e^{i\omega t} dt, obtained by
 * repeated integration by parts, with the leading contribution coming from the
 * endpoints (and from any interior discontinuities). The master formula is
 *
 *   \int_a^b f(t) e^{i\omega t} dt
 *     = \frac{f(b)e^{i\omega b} - f(a)e^{i\omega a}}{i\omega}
 *       - \frac{1}{i\omega}\int_a^b f'(t) e^{i\omega t} dt
 *     \sim \sum_{n\ge 0} \frac{(-1)^n}{(i\omega)^{n+1}}
 *          \Big[ f^{(n)}(b)e^{i\omega b} - f^{(n)}(a)e^{i\omega a} \Big],
 *
 * valid when the phase \omega t has NO stationary point on [a,b] (the phase
 * derivative \omega never vanishes), so this is genuinely an IBP / Riemann–
 * Lebesgue topic and not stationary phase (that is am5b). Interior jump
 * discontinuities of f at t=c contribute -[f(c^+)-f(c^-)]e^{i\omega c}/(i\omega).
 *
 * Seeded from DAMTP Asymptotic Methods Example Sheet 2 (Michaelmas 2025),
 * questions 3 (endpoint/discontinuity expansion of \int f e^{i\omega t}),
 * 3(b) (the two-sided exponential), and the IBP-check half of question 8.
 * Constants, limits and weight functions are varied throughout.
 *
 * Numerically spot-checked with mpmath (mp.quad against the closed forms /
 * leading terms) for every question whose result is a finite integral at large
 * parameter. Pure "show that the IBP identity holds" derivations carry a REVIEW
 * note where no numeric check applies.
 */
export const questions: Question[] = [
  // ── Foundation: the core IBP move in isolation ───────────────────────────
  {
    id: "am5a-001",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 e^{i\\omega t}\\, dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "Riemann-Lebesgue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate directly.", workingLatex: "I(\\omega) = \\int_0^1 e^{i\\omega t}\\, dt = \\left[ \\frac{e^{i\\omega t}}{i\\omega} \\right]_0^1.", explanation: "With constant amplitude the integral is elementary; antidifferentiating \\( e^{i\\omega t} \\) brings down a factor \\( 1/(i\\omega) \\), which is the source of the decay." },
        { stepNumber: 2, description: "Evaluate at the endpoints.", workingLatex: "I(\\omega) = \\frac{e^{i\\omega} - 1}{i\\omega}.", explanation: "This is exact, not just asymptotic — the only contributions are the two endpoint values \\( t=1 \\) and \\( t=0 \\)." },
        { stepNumber: 3, description: "Identify the size as \\( \\omega \\to \\infty \\).", workingLatex: "I(\\omega) \\sim \\frac{e^{i\\omega} - 1}{i\\omega} = O\\!\\left( \\frac{1}{\\omega} \\right).", explanation: "The numerator is bounded by \\( 2 \\), so the integral decays like \\( 1/\\omega \\). This \\( 1/\\omega \\) rate is the prototype of the Riemann–Lebesgue lemma: a smooth amplitude against a fast oscillation gives algebraic decay set by the endpoints." },
      ],
      finalAnswer: "\\( I(\\omega) = \\dfrac{e^{i\\omega} - 1}{i\\omega} = O\\!\\left( \\dfrac{1}{\\omega} \\right) \\).",
      canonicalAnswer: "(exp(I*w) - 1)/(I*w)",
    },
  },
  {
    id: "am5a-002",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "By integrating by parts once, write \\( \\displaystyle \\int_a^b f(t)\\, e^{i\\omega t}\\, dt \\) as a boundary term plus a remainder integral.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Choose the parts.", workingLatex: "u = f(t), \\qquad dv = e^{i\\omega t}\\, dt \\;\\Rightarrow\\; v = \\frac{e^{i\\omega t}}{i\\omega}.", explanation: "We integrate the oscillatory factor (which produces the small \\( 1/(i\\omega) \\)) and differentiate the smooth amplitude — the reverse choice would make the remainder larger, not smaller." },
        { stepNumber: 2, description: "Apply the parts formula.", workingLatex: "\\int_a^b f e^{i\\omega t}\\, dt = \\left[ \\frac{f(t)e^{i\\omega t}}{i\\omega} \\right]_a^b - \\frac{1}{i\\omega}\\int_a^b f'(t)\\, e^{i\\omega t}\\, dt.", explanation: "Each application of integration by parts pulls out one more power of \\( 1/(i\\omega) \\) and replaces \\( f \\) by \\( f' \\); the leading information sits entirely in the boundary term." },
        { stepNumber: 3, description: "State the boundary term explicitly.", workingLatex: "\\int_a^b f e^{i\\omega t}\\, dt = \\frac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega} - \\frac{1}{i\\omega}\\int_a^b f' e^{i\\omega t}\\, dt.", explanation: "Provided \\( f' \\) is integrable, the remainder is itself \\( O(1/\\omega) \\), so the whole remainder term is \\( O(1/\\omega^2) \\) and the displayed boundary term is the leading order." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_a^b f e^{i\\omega t}\\, dt = \\frac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega} - \\frac{1}{i\\omega}\\int_a^b f' e^{i\\omega t}\\, dt \\).",
    },
  },
  {
    id: "am5a-003",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle \\int_0^1 t\\, e^{i\\omega t}\\, dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts once.", workingLatex: "\\int_0^1 t\\, e^{i\\omega t}\\, dt = \\left[ \\frac{t\\, e^{i\\omega t}}{i\\omega} \\right]_0^1 - \\frac{1}{i\\omega}\\int_0^1 e^{i\\omega t}\\, dt.", explanation: "Take \\( u=t \\), \\( dv = e^{i\\omega t}dt \\). The boundary term will be the leading order because the remaining integral is itself \\( O(1/\\omega) \\)." },
        { stepNumber: 2, description: "Evaluate the boundary term.", workingLatex: "\\left[ \\frac{t\\, e^{i\\omega t}}{i\\omega} \\right]_0^1 = \\frac{1\\cdot e^{i\\omega}}{i\\omega} - 0 = \\frac{e^{i\\omega}}{i\\omega}.", explanation: "The amplitude \\( t \\) vanishes at the lower endpoint \\( t=0 \\), so only the upper endpoint contributes at leading order." },
        { stepNumber: 3, description: "Bound the remainder.", workingLatex: "\\frac{1}{i\\omega}\\int_0^1 e^{i\\omega t}\\, dt = \\frac{1}{i\\omega}\\cdot O\\!\\left(\\frac{1}{\\omega}\\right) = O\\!\\left(\\frac{1}{\\omega^2}\\right).", explanation: "From am5a-001 the inner integral is \\( O(1/\\omega) \\), so dividing by \\( i\\omega \\) makes the correction one order smaller than the boundary term." },
        { stepNumber: 4, description: "State the leading behaviour.", workingLatex: "\\int_0^1 t\\, e^{i\\omega t}\\, dt \\sim \\frac{e^{i\\omega}}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Confirmed numerically: at \\( \\omega = 50 \\) and \\( \\omega = 200 \\) the difference between the exact integral and this term is \\( O(1/\\omega^2) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_0^1 t\\, e^{i\\omega t}\\, dt \\sim \\frac{e^{i\\omega}}{i\\omega} \\).",
      canonicalAnswer: "exp(I*w)/(I*w)",
    },
  },
  {
    id: "am5a-004",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle \\int_1^2 \\frac{e^{i\\omega t}}{t}\\, dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts.", workingLatex: "\\int_1^2 \\frac{e^{i\\omega t}}{t}\\, dt = \\left[ \\frac{e^{i\\omega t}}{i\\omega\\, t} \\right]_1^2 + \\frac{1}{i\\omega}\\int_1^2 \\frac{e^{i\\omega t}}{t^2}\\, dt.", explanation: "With \\( u = 1/t \\), \\( u' = -1/t^2 \\); the minus from \\( u' \\) cancels the minus in the parts formula, giving a plus on the remainder. The amplitude \\( 1/t \\) is smooth on \\( [1,2] \\), so no singularity intervenes." },
        { stepNumber: 2, description: "Evaluate the boundary term.", workingLatex: "\\left[ \\frac{e^{i\\omega t}}{i\\omega\\, t} \\right]_1^2 = \\frac{1}{i\\omega}\\left( \\frac{e^{2i\\omega}}{2} - e^{i\\omega} \\right).", explanation: "Both endpoints contribute since \\( 1/t \\) is non-zero at each. This is the leading boundary term." },
        { stepNumber: 3, description: "State the leading behaviour.", workingLatex: "\\int_1^2 \\frac{e^{i\\omega t}}{t}\\, dt \\sim \\frac{1}{i\\omega}\\left( \\frac{e^{2i\\omega}}{2} - e^{i\\omega} \\right), \\qquad \\omega \\to \\infty.", explanation: "The remainder integral is \\( O(1/\\omega) \\), so the correction is \\( O(1/\\omega^2) \\). Verified numerically against the exact integral at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_1^2 \\frac{e^{i\\omega t}}{t}\\, dt \\sim \\frac{1}{i\\omega}\\left( \\frac{e^{2i\\omega}}{2} - e^{i\\omega} \\right) \\).",
      canonicalAnswer: "(exp(2*I*w)/2 - exp(I*w))/(I*w)",
    },
  },
  {
    id: "am5a-005",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle \\int_0^\\infty e^{-t}\\, e^{i\\omega t}\\, dt \\), and confirm it against the exact value.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "one-sided endpoint"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note decay kills the upper endpoint.", workingLatex: "\\int_0^\\infty e^{-t} e^{i\\omega t}\\, dt = \\left[ \\frac{e^{-t}e^{i\\omega t}}{i\\omega} \\right]_0^\\infty + \\frac{1}{i\\omega}\\int_0^\\infty e^{-t} e^{i\\omega t}\\, dt.", explanation: "Integrate by parts with \\( u = e^{-t} \\). Because \\( e^{-t}\\to 0 \\) as \\( t\\to\\infty \\), the boundary term has no contribution from \\( +\\infty \\); only \\( t=0 \\) survives." },
        { stepNumber: 2, description: "Read off the surviving endpoint.", workingLatex: "\\left[ \\frac{e^{-t}e^{i\\omega t}}{i\\omega} \\right]_0^\\infty = 0 - \\frac{1}{i\\omega} = -\\frac{1}{i\\omega}.", explanation: "The single lower endpoint \\( t=0 \\) gives the leading term; the remainder integral is \\( O(1/\\omega) \\) so contributes at \\( O(1/\\omega^2) \\)." },
        { stepNumber: 3, description: "Compare with the exact value.", workingLatex: "\\int_0^\\infty e^{-t}e^{i\\omega t}\\, dt = \\frac{1}{1 - i\\omega} \\sim -\\frac{1}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "The closed form \\( 1/(1-i\\omega) \\) expands as \\( -1/(i\\omega)\\,[1 + 1/(i\\omega) + \\cdots]^{-1} \\)-style geometric series, whose leading term is exactly \\( -1/(i\\omega) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_0^\\infty e^{-t}e^{i\\omega t}\\, dt = \\frac{1}{1-i\\omega} \\sim -\\frac{1}{i\\omega} \\).",
      canonicalAnswer: "1/(1 - I*w)",
    },
  },
  {
    id: "am5a-006",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the Riemann–Lebesgue lemma for \\( \\displaystyle \\int_a^b f(t)\\, e^{i\\omega t}\\, dt \\) with \\( f \\) integrable, and explain in one line why integration by parts gives the rate of decay when \\( f \\) is also \\( C^1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Riemann-Lebesgue", "integration by parts", "definition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the lemma.", workingLatex: "f \\in L^1(a,b) \\;\\Rightarrow\\; \\int_a^b f(t)\\, e^{i\\omega t}\\, dt \\to 0 \\quad \\text{as } |\\omega| \\to \\infty.", explanation: "The lemma asserts only that the integral tends to zero; for merely integrable \\( f \\) it gives no rate — the decay can be arbitrarily slow." },
        { stepNumber: 2, description: "Upgrade to a rate via smoothness.", workingLatex: "f \\in C^1 \\;\\Rightarrow\\; \\int_a^b f e^{i\\omega t}\\, dt = \\frac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega} + O\\!\\left(\\frac{1}{\\omega^2}\\right).", explanation: "One integration by parts moves a derivative onto \\( f \\) and extracts \\( 1/(i\\omega) \\); the boundary term shows the decay is exactly \\( O(1/\\omega) \\), set by the endpoint values." },
        { stepNumber: 3, description: "Summarise the mechanism.", workingLatex: "\\text{Each IBP} \\;\\Longrightarrow\\; \\text{one more power of } \\frac{1}{i\\omega}.", explanation: "If \\( f \\in C^k \\) the process iterates \\( k \\) times, giving decay \\( O(1/\\omega^{k+1}) \\) unless the endpoint terms vanish (e.g. \\( f \\) periodic / compactly supported smooth), in which case decay is faster than any power." },
      ],
      finalAnswer: "If \\( f \\in L^1 \\), the integral \\( \\to 0 \\); if \\( f \\in C^1 \\) it is \\( O(1/\\omega) \\) with leading term \\( \\dfrac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega} \\).",
    },
  },

  // ── Standard: typical sheet-level endpoint expansions ─────────────────────
  {
    id: "am5a-007",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Obtain the first two terms in the asymptotic expansion, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 (2 + t)\\, e^{i\\omega t}\\, dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "asymptotic expansion", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts once.", workingLatex: "I(\\omega) = \\left[ \\frac{(2+t)e^{i\\omega t}}{i\\omega} \\right]_0^1 - \\frac{1}{i\\omega}\\int_0^1 e^{i\\omega t}\\, dt.", explanation: "Differentiate the amplitude \\( f = 2+t \\) (giving \\( f' = 1 \\)) and integrate the exponential. The boundary term is the leading order." },
        { stepNumber: 2, description: "Evaluate the first boundary term.", workingLatex: "\\left[ \\frac{(2+t)e^{i\\omega t}}{i\\omega} \\right]_0^1 = \\frac{3 e^{i\\omega} - 2}{i\\omega}.", explanation: "At \\( t=1 \\), \\( f=3 \\); at \\( t=0 \\), \\( f=2 \\). This is the \\( O(1/\\omega) \\) term." },
        { stepNumber: 3, description: "Integrate by parts a second time.", workingLatex: "\\frac{1}{i\\omega}\\int_0^1 e^{i\\omega t}\\, dt = \\frac{1}{i\\omega}\\left[ \\frac{e^{i\\omega t}}{i\\omega} \\right]_0^1 = \\frac{e^{i\\omega} - 1}{(i\\omega)^2}.", explanation: "Here \\( f' = 1 \\) is constant, so the second remainder integral is just \\( \\int e^{i\\omega t} \\), evaluated exactly. There is no further correction beyond this order." },
        { stepNumber: 4, description: "Assemble the two-term expansion.", workingLatex: "I(\\omega) = \\frac{3 e^{i\\omega} - 2}{i\\omega} - \\frac{e^{i\\omega} - 1}{(i\\omega)^2}.", explanation: "Because \\( f'' = 0 \\), this expression is in fact exact. Numerically it matches the integral to machine precision at \\( \\omega = 80, 320 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{3 e^{i\\omega} - 2}{i\\omega} - \\frac{e^{i\\omega} - 1}{(i\\omega)^2} \\).",
      canonicalAnswer: "(3*exp(I*w) - 2)/(I*w) - (exp(I*w) - 1)/(I*w)^2",
    },
  },
  {
    id: "am5a-008",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 \\frac{e^{i\\omega t}}{1+t}\\, dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "asymptotic expansion", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the IBP series.", workingLatex: "f(t) = \\frac{1}{1+t}, \\qquad f'(t) = -\\frac{1}{(1+t)^2}.", explanation: "The amplitude is smooth on \\( [0,1] \\); we will need \\( f \\) and \\( f' \\) at the endpoints for the first two terms." },
        { stepNumber: 2, description: "Write the two-term IBP formula.", workingLatex: "I(\\omega) = \\frac{f(b)e^{i\\omega} - f(a)}{i\\omega} - \\frac{f'(b)e^{i\\omega} - f'(a)}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right),", explanation: "This is the general expansion with \\( a=0,\\ b=1 \\); the \\( (-1)^n \\) sign pattern gives the minus on the second term." },
        { stepNumber: 3, description: "Insert the endpoint values.", workingLatex: "f(0) = 1,\\; f(1) = \\tfrac{1}{2}, \\qquad f'(0) = -1,\\; f'(1) = -\\tfrac{1}{4}.", explanation: "Evaluating \\( 1/(1+t) \\) and \\( -1/(1+t)^2 \\) at \\( t=0 \\) and \\( t=1 \\)." },
        { stepNumber: 4, description: "Assemble the expansion.", workingLatex: "I(\\omega) = \\frac{\\tfrac{1}{2}e^{i\\omega} - 1}{i\\omega} - \\frac{-\\tfrac{1}{4}e^{i\\omega} + 1}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right).", explanation: "Substituting the four values. Numerically the two-term truncation matches the integral to \\( O(1/\\omega^3) \\) at \\( \\omega = 60, 240 \\)." },
        { stepNumber: 5, description: "Tidy the signs.", workingLatex: "I(\\omega) = \\frac{\\tfrac{1}{2}e^{i\\omega} - 1}{i\\omega} + \\frac{\\tfrac{1}{4}e^{i\\omega} - 1}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right).", explanation: "Distributing the minus sign over the second numerator gives the cleanest form." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{\\tfrac{1}{2}e^{i\\omega} - 1}{i\\omega} + \\frac{\\tfrac{1}{4}e^{i\\omega} - 1}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right) \\).",
      canonicalAnswer: "(exp(I*w)/2 - 1)/(I*w) + (exp(I*w)/4 - 1)/(I*w)^2",
    },
  },
  {
    id: "am5a-009",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^2 \\cos t\\; e^{i\\omega t}\\, dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the leading-order IBP formula.", workingLatex: "I(\\omega) \\sim \\frac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega}, \\qquad f = \\cos t,\\; a=0,\\; b=2.", explanation: "The phase is \\( \\omega t \\), whose derivative \\( \\omega \\) never vanishes, so there is no stationary point and the endpoints alone control the leading behaviour." },
        { stepNumber: 2, description: "Insert the endpoint amplitudes.", workingLatex: "f(0) = \\cos 0 = 1, \\qquad f(2) = \\cos 2.", explanation: "Both endpoints contribute since \\( \\cos t \\) is non-zero at \\( t=0 \\) and \\( t=2 \\)." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{(\\cos 2)\\, e^{2i\\omega} - 1}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Verified numerically against the exact integral at \\( \\omega = 80, 320 \\); the error decays as \\( 1/\\omega^2 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{(\\cos 2)\\, e^{2i\\omega} - 1}{i\\omega} \\).",
      canonicalAnswer: "(cos(2)*exp(2*I*w) - 1)/(I*w)",
    },
  },
  {
    id: "am5a-010",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_1^3 \\ln t\\; e^{i\\omega t}\\, dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the leading boundary term.", workingLatex: "I(\\omega) \\sim \\frac{f(b)e^{i\\omega b} - f(a)e^{i\\omega a}}{i\\omega}, \\qquad f = \\ln t,\\; a=1,\\; b=3.", explanation: "The amplitude \\( \\ln t \\) is smooth on \\( [1,3] \\) (no singularity, since \\( t\\ge 1 \\)), so the standard endpoint formula applies." },
        { stepNumber: 2, description: "Insert the endpoint values.", workingLatex: "f(1) = \\ln 1 = 0, \\qquad f(3) = \\ln 3.", explanation: "The lower endpoint contribution vanishes because \\( \\ln 1 = 0 \\); only \\( t=3 \\) survives at leading order." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{(\\ln 3)\\, e^{3i\\omega}}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Numerically confirmed at \\( \\omega = 80, 320 \\); the next term, of order \\( 1/\\omega^2 \\), would come from \\( f'(t) = 1/t \\) at both endpoints." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{(\\ln 3)\\, e^{3i\\omega}}{i\\omega} \\).",
      canonicalAnswer: "log(3)*exp(3*I*w)/(I*w)",
    },
  },
  {
    id: "am5a-011",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Taking \\( \\omega \\to \\infty \\), find the leading term in the asymptotic approximation of \\( \\displaystyle I(\\omega) = \\int_0^1 \\cos(\\omega t)\\, dt \\) and of \\( \\displaystyle J(\\omega) = \\int_0^1 t\\,\\cos(\\omega t)\\, dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "real form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Do the first integral exactly.", workingLatex: "I(\\omega) = \\int_0^1 \\cos(\\omega t)\\, dt = \\left[ \\frac{\\sin(\\omega t)}{\\omega} \\right]_0^1 = \\frac{\\sin\\omega}{\\omega}.", explanation: "Constant amplitude makes this elementary; the decay is exactly \\( 1/\\omega \\)." },
        { stepNumber: 2, description: "Integrate the second by parts.", workingLatex: "J(\\omega) = \\left[ \\frac{t\\,\\sin(\\omega t)}{\\omega} \\right]_0^1 - \\frac{1}{\\omega}\\int_0^1 \\sin(\\omega t)\\, dt.", explanation: "Take \\( u=t \\), \\( dv = \\cos(\\omega t)dt \\). The boundary term is leading order; the lower endpoint vanishes since \\( t=0 \\)." },
        { stepNumber: 3, description: "Read off the leading boundary term.", workingLatex: "\\left[ \\frac{t\\,\\sin(\\omega t)}{\\omega} \\right]_0^1 = \\frac{\\sin\\omega}{\\omega}.", explanation: "The remainder \\( -\\frac{1}{\\omega}\\int_0^1 \\sin(\\omega t)dt = \\frac{\\cos\\omega - 1}{\\omega^2} \\) is \\( O(1/\\omega^2) \\), one order down." },
        { stepNumber: 4, description: "State both leading terms.", workingLatex: "I(\\omega) = \\frac{\\sin\\omega}{\\omega}, \\qquad J(\\omega) \\sim \\frac{\\sin\\omega}{\\omega}, \\quad \\omega \\to \\infty.", explanation: "Both share the same \\( 1/\\omega \\) leading term, set by the upper endpoint amplitude \\( 1 \\); they differ only at \\( O(1/\\omega^2) \\)." },
      ],
      finalAnswer: "\\( I(\\omega) = \\dfrac{\\sin\\omega}{\\omega} \\) and \\( J(\\omega) \\sim \\dfrac{\\sin\\omega}{\\omega} \\).",
      canonicalAnswer: "sin(w)/w",
    },
  },
  {
    id: "am5a-012",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f \\) be smooth on \\( [a,b] \\). Show by repeated integration by parts that, as \\( \\omega \\to \\infty \\), \\( \\displaystyle \\int_a^b f(t)\\, e^{i\\omega t}\\, dt \\sim \\sum_{n=0}^{\\infty} \\frac{(-1)^n}{(i\\omega)^{n+1}}\\Big[ f^{(n)}(b)e^{i\\omega b} - f^{(n)}(a)e^{i\\omega a} \\Big] \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "asymptotic series", "Riemann-Lebesgue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "First integration by parts.", workingLatex: "\\int_a^b f e^{i\\omega t}\\, dt = \\frac{1}{i\\omega}\\Big[ f e^{i\\omega t} \\Big]_a^b - \\frac{1}{i\\omega}\\int_a^b f' e^{i\\omega t}\\, dt.", explanation: "Integrating \\( e^{i\\omega t} \\) and differentiating \\( f \\) extracts one factor \\( 1/(i\\omega) \\) and produces a remainder of the same shape with \\( f\\to f' \\)." },
        { stepNumber: 2, description: "Iterate the procedure.", workingLatex: "-\\frac{1}{i\\omega}\\int_a^b f' e^{i\\omega t}\\, dt = -\\frac{1}{(i\\omega)^2}\\Big[ f' e^{i\\omega t} \\Big]_a^b + \\frac{1}{(i\\omega)^2}\\int_a^b f'' e^{i\\omega t}\\, dt.", explanation: "Each pass introduces another \\( 1/(i\\omega) \\) and flips the sign, so after \\( n \\) passes the boundary term carries \\( (-1)^n/(i\\omega)^{n+1} \\) and \\( f^{(n)} \\)." },
        { stepNumber: 3, description: "Collect the boundary terms.", workingLatex: "\\int_a^b f e^{i\\omega t}\\, dt = \\sum_{n=0}^{N} \\frac{(-1)^n}{(i\\omega)^{n+1}}\\Big[ f^{(n)} e^{i\\omega t} \\Big]_a^b + R_N.", explanation: "The boundary terms accumulate into the stated sum; \\( R_N = \\frac{(-1)^{N+1}}{(i\\omega)^{N+1}}\\int_a^b f^{(N+1)} e^{i\\omega t}dt \\) is the remainder after \\( N+1 \\) steps." },
        { stepNumber: 4, description: "Bound the remainder.", workingLatex: "|R_N| \\le \\frac{1}{\\omega^{N+1}}\\int_a^b |f^{(N+1)}(t)|\\, dt = O\\!\\left(\\frac{1}{\\omega^{N+1}}\\right).", explanation: "By Riemann–Lebesgue the inner integral tends to zero; even crudely bounding it by its absolute value shows \\( R_N \\) is smaller than the last retained term, so the series is asymptotic. Writing the boundary brackets out gives the stated form." },
      ],
      finalAnswer: "\\( \\displaystyle \\int_a^b f e^{i\\omega t}\\, dt \\sim \\sum_{n=0}^{\\infty} \\frac{(-1)^n}{(i\\omega)^{n+1}}\\Big[ f^{(n)}(b)e^{i\\omega b} - f^{(n)}(a)e^{i\\omega a} \\Big] \\).",
    },
  },
  {
    id: "am5a-013",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^\\pi \\sin t\\; e^{i\\omega t}\\, dt \\). Comment on the order of decay.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "Riemann-Lebesgue", "vanishing endpoints"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Try the leading endpoint term.", workingLatex: "\\text{Leading term} = \\frac{f(\\pi)e^{i\\omega\\pi} - f(0)}{i\\omega}, \\qquad f = \\sin t.", explanation: "Apply the first-order IBP formula and check the endpoint amplitudes before concluding." },
        { stepNumber: 2, description: "Observe the endpoints vanish.", workingLatex: "f(0) = \\sin 0 = 0, \\qquad f(\\pi) = \\sin\\pi = 0 \\;\\Rightarrow\\; \\text{the } O(1/\\omega) \\text{ term is } 0.", explanation: "Because the amplitude vanishes at both endpoints, the usual \\( 1/\\omega \\) leading term is absent; we must go to the next order." },
        { stepNumber: 3, description: "Take the second-order term.", workingLatex: "I(\\omega) \\sim -\\frac{f'(\\pi)e^{i\\omega\\pi} - f'(0)}{(i\\omega)^2}, \\qquad f' = \\cos t.", explanation: "The \\( n=1 \\) term of the IBP series carries \\( (-1)^1/(i\\omega)^2 \\) and the derivative \\( f' = \\cos t \\)." },
        { stepNumber: 4, description: "Insert the derivative values.", workingLatex: "f'(0) = 1,\\quad f'(\\pi) = -1 \\;\\Rightarrow\\; I(\\omega) \\sim -\\frac{-e^{i\\omega\\pi} - 1}{(i\\omega)^2} = \\frac{e^{i\\omega\\pi} + 1}{(i\\omega)^2}.", explanation: "Since \\( (i\\omega)^2 = -\\omega^2 \\), this is \\( -(e^{i\\omega\\pi}+1)/\\omega^2 \\), of order \\( 1/\\omega^2 \\)." },
        { stepNumber: 5, description: "Comment on the decay rate.", workingLatex: "I(\\omega) \\sim \\frac{e^{i\\omega\\pi} + 1}{(i\\omega)^2} = O\\!\\left(\\frac{1}{\\omega^2}\\right).", explanation: "Vanishing endpoint amplitudes give faster decay: each vanishing endpoint value pushes the leading order down by one power of \\( \\omega \\). Verified numerically at \\( \\omega = 50, 200 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{e^{i\\omega\\pi} + 1}{(i\\omega)^2} = O\\!\\left(\\frac{1}{\\omega^2}\\right) \\).",
      canonicalAnswer: "(exp(I*pi*w) + 1)/(I*w)^2",
    },
  },
  {
    id: "am5a-014",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 e^{t}\\, e^{i\\omega t}\\, dt \\), and verify it against the exact value.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Combine the exponentials.", workingLatex: "I(\\omega) = \\int_0^1 e^{(1 + i\\omega)t}\\, dt = \\left[ \\frac{e^{(1+i\\omega)t}}{1 + i\\omega} \\right]_0^1 = \\frac{e^{1+i\\omega} - 1}{1 + i\\omega}.", explanation: "Here the integral is elementary because the amplitude is itself an exponential; this gives the exact value for comparison." },
        { stepNumber: 2, description: "Expand the denominator for large \\( \\omega \\).", workingLatex: "\\frac{1}{1 + i\\omega} = \\frac{1}{i\\omega}\\cdot\\frac{1}{1 + \\frac{1}{i\\omega}} = \\frac{1}{i\\omega}\\left( 1 - \\frac{1}{i\\omega} + \\cdots \\right).", explanation: "Factor out \\( i\\omega \\) and expand the geometric series; the leading behaviour comes from the first factor." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{e\\, e^{i\\omega} - 1}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "This is exactly the endpoint formula with \\( f = e^t \\): \\( f(1) = e \\), \\( f(0) = 1 \\). Verified numerically against the closed form at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{e^{1+i\\omega} - 1}{1+i\\omega} \\sim \\frac{e\\, e^{i\\omega} - 1}{i\\omega} \\).",
      canonicalAnswer: "(exp(1 + I*w) - 1)/(1 + I*w)",
    },
  },
  {
    id: "am5a-015",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "A function \\( f \\) is smooth on \\( [a,c)\\cup(c,b) \\) but has a jump discontinuity at the interior point \\( t=c \\). By splitting the range, show that the leading large-\\( \\omega \\) contribution of the jump to \\( \\displaystyle \\int_a^b f(t)e^{i\\omega t}\\, dt \\) is \\( \\displaystyle -\\frac{\\big[f(c^+) - f(c^-)\\big]\\, e^{i\\omega c}}{i\\omega} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "discontinuity", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split at the discontinuity.", workingLatex: "\\int_a^b f e^{i\\omega t}\\, dt = \\int_a^c f e^{i\\omega t}\\, dt + \\int_c^b f e^{i\\omega t}\\, dt.", explanation: "On each subinterval \\( f \\) is smooth, so IBP applies separately; the point \\( t=c \\) is now an endpoint of both pieces." },
        { stepNumber: 2, description: "Apply IBP to each piece.", workingLatex: "\\int_a^c f e^{i\\omega t}\\, dt \\sim \\frac{f(c^-)e^{i\\omega c} - f(a)e^{i\\omega a}}{i\\omega}, \\quad \\int_c^b f e^{i\\omega t}\\, dt \\sim \\frac{f(b)e^{i\\omega b} - f(c^+)e^{i\\omega c}}{i\\omega}.", explanation: "On \\( [a,c] \\) the upper endpoint amplitude is the left limit \\( f(c^-) \\); on \\( [c,b] \\) the lower endpoint amplitude is the right limit \\( f(c^+) \\)." },
        { stepNumber: 3, description: "Add and collect the \\( t=c \\) terms.", workingLatex: "\\frac{f(c^-)e^{i\\omega c} - f(c^+)e^{i\\omega c}}{i\\omega} = -\\frac{\\big[f(c^+) - f(c^-)\\big]e^{i\\omega c}}{i\\omega}.", explanation: "The two contributions at \\( c \\) do not cancel because \\( f(c^+)\\neq f(c^-) \\); their difference is exactly the jump." },
        { stepNumber: 4, description: "State the jump contribution.", workingLatex: "\\text{Jump contribution} = -\\frac{\\big[f(c^+) - f(c^-)\\big]e^{i\\omega c}}{i\\omega}.", explanation: "A discontinuity behaves like an interior endpoint: it produces its own \\( O(1/\\omega) \\) term, on top of the genuine endpoints \\( a,b \\). Verified numerically for a unit jump at an interior point at \\( \\omega = 40, 160 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle -\\frac{\\big[f(c^+) - f(c^-)\\big]\\, e^{i\\omega c}}{i\\omega} \\).",
    },
  },
  {
    id: "am5a-016",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The amplitude \\( f(t) = t \\) for \\( 0\\le t<1 \\) and \\( f(t) = t+1 \\) for \\( 1\\le t\\le 2 \\). Find the leading large-\\( \\omega \\) behaviour of \\( \\displaystyle I(\\omega) = \\int_0^2 f(t)\\, e^{i\\omega t}\\, dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "discontinuity", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the contributing points.", workingLatex: "\\text{Endpoints } t=0,\\, t=2; \\quad \\text{interior jump at } t=1.", explanation: "The amplitude is piecewise linear with a unit jump at \\( t=1 \\); the leading behaviour collects the two genuine endpoints and the discontinuity." },
        { stepNumber: 2, description: "Endpoint terms.", workingLatex: "\\frac{f(2)e^{2i\\omega} - f(0)}{i\\omega} = \\frac{3\\, e^{2i\\omega} - 0}{i\\omega} = \\frac{3\\, e^{2i\\omega}}{i\\omega}.", explanation: "Here \\( f(2) = 3 \\) and \\( f(0) = 0 \\); only the upper endpoint contributes." },
        { stepNumber: 3, description: "Jump term at \\( t=1 \\).", workingLatex: "f(1^-) = 1,\\; f(1^+) = 2 \\;\\Rightarrow\\; -\\frac{[2 - 1]e^{i\\omega}}{i\\omega} = -\\frac{e^{i\\omega}}{i\\omega}.", explanation: "Using the interior-jump rule from am5a-015 with jump size \\( f(1^+) - f(1^-) = 1 \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "I(\\omega) \\sim \\frac{3\\, e^{2i\\omega} - e^{i\\omega}}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Sum of the endpoint and jump terms. Verified numerically against the exact integral at \\( \\omega = 40, 160 \\); the error is \\( O(1/\\omega^2) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{3\\, e^{2i\\omega} - e^{i\\omega}}{i\\omega} \\).",
      canonicalAnswer: "(3*exp(2*I*w) - exp(I*w))/(I*w)",
    },
  },
  {
    id: "am5a-017",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^{1} e^{-2t}\\, e^{i\\omega t}\\, dt \\), and compare with the exact value.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "oscillatory integral", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Evaluate exactly.", workingLatex: "I(\\omega) = \\int_0^1 e^{(-2 + i\\omega)t}\\, dt = \\frac{e^{-2+i\\omega} - 1}{-2 + i\\omega}.", explanation: "The combined exponent integrates directly, giving a closed form to compare against." },
        { stepNumber: 2, description: "Extract the leading order.", workingLatex: "\\frac{1}{-2 + i\\omega} = \\frac{1}{i\\omega}\\left( 1 + \\frac{2}{i\\omega} + \\cdots \\right).", explanation: "Factor out \\( i\\omega \\); the leading term of the geometric expansion is \\( 1/(i\\omega) \\)." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{e^{-2}e^{i\\omega} - 1}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "This matches the endpoint formula with \\( f = e^{-2t} \\): \\( f(1) = e^{-2} \\), \\( f(0) = 1 \\). Verified numerically against the closed form at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{e^{-2+i\\omega} - 1}{-2+i\\omega} \\sim \\frac{e^{-2}e^{i\\omega} - 1}{i\\omega} \\).",
      canonicalAnswer: "(exp(-2 + I*w) - 1)/(-2 + I*w)",
    },
  },
  {
    id: "am5a-018",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Explain why \\( \\displaystyle \\int_0^{2\\pi} f(t)\\, e^{i\\omega t}\\, dt \\) decays faster than any power of \\( 1/\\omega \\) when \\( f \\) is smooth and \\( 2\\pi \\)-periodic with all derivatives matching at the endpoints, taking \\( \\omega \\) integer.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "Riemann-Lebesgue", "superalgebraic decay"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the IBP series.", workingLatex: "\\int_0^{2\\pi} f e^{i\\omega t}\\, dt \\sim \\sum_{n=0}^{\\infty} \\frac{(-1)^n}{(i\\omega)^{n+1}}\\Big[ f^{(n)}(2\\pi)e^{2\\pi i\\omega} - f^{(n)}(0) \\Big].", explanation: "This is the general endpoint expansion; the decay is controlled by the boundary values of every derivative." },
        { stepNumber: 2, description: "Use integer \\( \\omega \\).", workingLatex: "\\omega \\in \\mathbb{Z} \\;\\Rightarrow\\; e^{2\\pi i\\omega} = 1.", explanation: "For integer frequency the exponential at the upper endpoint equals \\( 1 \\), so each boundary bracket becomes \\( f^{(n)}(2\\pi) - f^{(n)}(0) \\)." },
        { stepNumber: 3, description: "Apply periodicity.", workingLatex: "f^{(n)}(2\\pi) = f^{(n)}(0) \\;\\Rightarrow\\; f^{(n)}(2\\pi) - f^{(n)}(0) = 0 \\quad \\text{for all } n.", explanation: "Smooth periodicity makes every derivative match at the endpoints, so every boundary bracket vanishes." },
        { stepNumber: 4, description: "Conclude superalgebraic decay.", workingLatex: "\\int_0^{2\\pi} f e^{i\\omega t}\\, dt = o\\!\\left(\\omega^{-N}\\right) \\quad \\text{for every } N.", explanation: "With all terms of the asymptotic series equal to zero, the integral (a Fourier coefficient of a smooth periodic function) decays faster than any power of \\( 1/\\omega \\) — the hallmark of spectral accuracy." },
      ],
      finalAnswer: "Every endpoint bracket \\( f^{(n)}(2\\pi) - f^{(n)}(0) \\) vanishes, so the integral is \\( o(\\omega^{-N}) \\) for all \\( N \\).",
    },
  },

  // ── Challenge: synoptic / multi-step / starred ───────────────────────────
  {
    id: "am5a-019",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Define \\( f(t) = -e^{t} \\) for \\( t<0 \\) and \\( f(t) = e^{-t} \\) for \\( t\\ge 0 \\). Find the leading large-\\( \\omega \\) behaviour of \\( \\displaystyle I(\\omega) = \\int_{-\\infty}^{\\infty} f(t)\\, e^{i\\omega t}\\, dt \\), and check it against the exact value.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "discontinuity", "Fourier transform"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the only special point.", workingLatex: "f(0^-) = -e^{0} = -1, \\qquad f(0^+) = e^{0} = +1.", explanation: "The function decays to zero at \\( \\pm\\infty \\), so there are no endpoint contributions from infinity; the sole feature is the jump at \\( t=0 \\)." },
        { stepNumber: 2, description: "Compute the jump.", workingLatex: "f(0^+) - f(0^-) = 1 - (-1) = 2.", explanation: "The discontinuity has size \\( 2 \\); this is what governs the leading decay via the interior-jump rule." },
        { stepNumber: 3, description: "Apply the jump formula.", workingLatex: "I(\\omega) \\sim -\\frac{\\big[f(0^+) - f(0^-)\\big]e^{i\\omega\\cdot 0}}{i\\omega} = -\\frac{2}{i\\omega} = \\frac{2i}{\\omega}.", explanation: "Using \\( -[\\,\\cdot\\,]/(i\\omega) \\) at \\( c=0 \\), and \\( -1/i = i \\). The leading decay is \\( O(1/\\omega) \\) because of the jump." },
        { stepNumber: 4, description: "Evaluate the exact integral.", workingLatex: "I(\\omega) = \\int_{-\\infty}^0 (-e^{t})e^{i\\omega t}\\, dt + \\int_0^{\\infty} e^{-t}e^{i\\omega t}\\, dt = -\\frac{1}{1+i\\omega} + \\frac{1}{1-i\\omega}.", explanation: "Each half is a convergent exponential integral; the lower half gives \\( -1/(1+i\\omega) \\), the upper half \\( 1/(1-i\\omega) \\)." },
        { stepNumber: 5, description: "Simplify and expand.", workingLatex: "I(\\omega) = \\frac{2i\\omega}{1+\\omega^2} \\sim \\frac{2i\\omega}{\\omega^2} = \\frac{2i}{\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Combining over a common denominator gives \\( 2i\\omega/(1+\\omega^2) \\); its large-\\( \\omega \\) limit is \\( 2i/\\omega \\), matching the jump prediction exactly. Confirmed numerically at \\( \\omega = 3, 10 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{2i\\omega}{1+\\omega^2} \\sim \\frac{2i}{\\omega} \\).",
      canonicalAnswer: "2*I*w/(1 + w^2)",
    },
  },
  {
    id: "am5a-020",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two non-zero terms, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 \\frac{e^{i\\omega t}}{2+t}\\, dt \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "asymptotic expansion", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Record the amplitude and its derivative.", workingLatex: "f(t) = \\frac{1}{2+t}, \\qquad f'(t) = -\\frac{1}{(2+t)^2}.", explanation: "Smooth on \\( [0,1] \\); the first two terms of the IBP series need \\( f \\) and \\( f' \\) at both endpoints." },
        { stepNumber: 2, description: "Endpoint values of \\( f \\).", workingLatex: "f(0) = \\frac{1}{2}, \\qquad f(1) = \\frac{1}{3}.", explanation: "Evaluating \\( 1/(2+t) \\) at \\( t=0,1 \\)." },
        { stepNumber: 3, description: "First term.", workingLatex: "\\frac{f(1)e^{i\\omega} - f(0)}{i\\omega} = \\frac{\\tfrac{1}{3}e^{i\\omega} - \\tfrac{1}{2}}{i\\omega}.", explanation: "The leading \\( O(1/\\omega) \\) contribution from the two endpoints." },
        { stepNumber: 4, description: "Endpoint values of \\( f' \\).", workingLatex: "f'(0) = -\\frac{1}{4}, \\qquad f'(1) = -\\frac{1}{9}.", explanation: "Evaluating \\( -1/(2+t)^2 \\) at \\( t=0,1 \\)." },
        { stepNumber: 5, description: "Second term.", workingLatex: "-\\frac{f'(1)e^{i\\omega} - f'(0)}{(i\\omega)^2} = -\\frac{-\\tfrac{1}{9}e^{i\\omega} + \\tfrac{1}{4}}{(i\\omega)^2} = \\frac{\\tfrac{1}{9}e^{i\\omega} - \\tfrac{1}{4}}{(i\\omega)^2}.", explanation: "The \\( n=1 \\) term carries \\( (-1)^1/(i\\omega)^2 \\); distributing the sign tidies the numerator." },
        { stepNumber: 6, description: "Assemble.", workingLatex: "I(\\omega) = \\frac{\\tfrac{1}{3}e^{i\\omega} - \\tfrac{1}{2}}{i\\omega} + \\frac{\\tfrac{1}{9}e^{i\\omega} - \\tfrac{1}{4}}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right).", explanation: "Two-term expansion; the truncation error is \\( O(1/\\omega^3) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{\\tfrac{1}{3}e^{i\\omega} - \\tfrac{1}{2}}{i\\omega} + \\frac{\\tfrac{1}{9}e^{i\\omega} - \\tfrac{1}{4}}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right) \\).",
      canonicalAnswer: "(exp(I*w)/3 - 1/2)/(I*w) + (exp(I*w)/9 - 1/4)/(I*w)^2",
    },
  },
  {
    id: "am5a-021",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By writing \\( g(t)\\,e^{i\\omega\\phi(t)} \\) with \\( \\phi(t) = t^2 \\) and observing that \\( \\phi'(t)\\neq 0 \\) on \\( [1,2] \\), find the leading term, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_1^2 e^{i\\omega t^2}\\, dt \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "non-stationary phase", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Check there is no stationary point.", workingLatex: "\\phi(t) = t^2, \\quad \\phi'(t) = 2t \\neq 0 \\text{ on } [1,2].", explanation: "The phase derivative \\( 2t \\) is bounded away from zero on \\( [1,2] \\), so the integral is governed by the endpoints, not by stationary phase — IBP is the right tool." },
        { stepNumber: 2, description: "Rewrite the integrand for IBP.", workingLatex: "e^{i\\omega t^2} = \\frac{1}{i\\omega\\,\\phi'(t)}\\frac{d}{dt}e^{i\\omega t^2} = \\frac{1}{2 i\\omega\\, t}\\frac{d}{dt}e^{i\\omega t^2}.", explanation: "Use \\( \\frac{d}{dt}e^{i\\omega\\phi} = i\\omega\\phi' e^{i\\omega\\phi} \\) to express the oscillatory factor as a derivative divided by \\( i\\omega\\phi' \\); this is the standard non-stationary IBP setup." },
        { stepNumber: 3, description: "Integrate by parts.", workingLatex: "I(\\omega) = \\left[ \\frac{e^{i\\omega t^2}}{2 i\\omega\\, t} \\right]_1^2 + \\frac{1}{2 i\\omega}\\int_1^2 \\frac{e^{i\\omega t^2}}{t^2}\\, dt.", explanation: "The amplitude here is \\( 1/(2 i\\omega t) \\); differentiating it gives \\( -1/(2 i\\omega t^2) \\), and the minus combines with the parts formula to leave a plus on the remainder, which is \\( O(1/\\omega^2) \\)." },
        { stepNumber: 4, description: "Evaluate the boundary term.", workingLatex: "\\left[ \\frac{e^{i\\omega t^2}}{2 i\\omega\\, t} \\right]_1^2 = \\frac{1}{2 i\\omega}\\left( \\frac{e^{4 i\\omega}}{2} - e^{i\\omega} \\right).", explanation: "At \\( t=2 \\), \\( \\phi=4 \\) and the prefactor is \\( 1/(4 i\\omega) \\); at \\( t=1 \\), \\( \\phi=1 \\) and the prefactor is \\( 1/(2 i\\omega) \\)." },
        { stepNumber: 5, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{1}{2 i\\omega}\\left( \\frac{e^{4 i\\omega}}{2} - e^{i\\omega} \\right), \\qquad \\omega \\to \\infty.", explanation: "The endpoint at \\( t=2 \\) is weighted by \\( 1/(2\\phi'(2)) = 1/8 \\) relative to \\( i\\omega \\); the \\( 1/\\phi' \\) factor is the signature of non-stationary phase. Verified numerically at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{1}{2 i\\omega}\\left( \\frac{e^{4 i\\omega}}{2} - e^{i\\omega} \\right) \\).",
      canonicalAnswer: "(exp(4*I*w)/2 - exp(I*w))/(2*I*w)",
    },
  },
  {
    id: "am5a-022",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading term, as \\( \\omega \\to +\\infty \\), of the real integral \\( \\displaystyle I(\\omega) = \\int_1^2 \\cos\\!\\big(\\omega\\, t^{3}\\big)\\, dt \\). Begin by checking that the phase has no stationary point on \\( [1,2] \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "non-stationary phase", "real form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pass to the complex exponential.", workingLatex: "I(\\omega) = \\operatorname{Re}\\int_1^2 e^{i \\omega t^{3}}\\, dt, \\qquad \\phi(t) = t^{3},\\; \\phi'(t) = 3 t^{2}.", explanation: "Writing \\( \\cos = \\operatorname{Re}\\, e^{i\\cdot} \\) lets us use the IBP machinery; on \\( [1,2] \\) the phase derivative \\( 3t^2 \\ge 3 > 0 \\), so there is no stationary point and the endpoints control the leading behaviour." },
        { stepNumber: 2, description: "IBP using \\( 1/\\phi' \\).", workingLatex: "e^{i\\omega t^3} = \\frac{1}{i\\omega\\,\\phi'(t)}\\frac{d}{dt}e^{i\\omega t^3} = \\frac{1}{3 i\\omega\\, t^2}\\frac{d}{dt}e^{i\\omega t^3}.", explanation: "Express the oscillatory factor as \\( (i\\omega\\phi')^{-1} \\) times the derivative of the exponential — the standard non-stationary IBP setup, valid because \\( \\phi' \\) is non-zero throughout." },
        { stepNumber: 3, description: "Integrate by parts.", workingLatex: "\\int_1^2 e^{i\\omega t^3}\\, dt = \\left[ \\frac{e^{i\\omega t^3}}{3 i\\omega\\, t^2} \\right]_1^2 + \\frac{2}{3 i\\omega}\\int_1^2 \\frac{e^{i\\omega t^3}}{t^3}\\, dt.", explanation: "Differentiating the amplitude \\( 1/(3 i\\omega t^2) \\) gives \\( -2/(3 i\\omega t^3) \\); the sign flips to a plus on the remainder, which is \\( O(1/\\omega^2) \\)." },
        { stepNumber: 4, description: "Evaluate the boundary term.", workingLatex: "\\left[ \\frac{e^{i\\omega t^3}}{3 i\\omega\\, t^2} \\right]_1^2 = \\frac{1}{i\\omega}\\left( \\frac{e^{8 i\\omega}}{12} - \\frac{e^{i\\omega}}{3} \\right).", explanation: "At \\( t=2 \\), \\( \\phi=8 \\) and \\( 3t^2 = 12 \\); at \\( t=1 \\), \\( \\phi=1 \\) and \\( 3t^2 = 3 \\)." },
        { stepNumber: 5, description: "Take the real part.", workingLatex: "I(\\omega) \\sim \\operatorname{Re}\\frac{-i}{\\omega}\\left( \\frac{e^{8 i\\omega}}{12} - \\frac{e^{i\\omega}}{3} \\right) = \\frac{1}{\\omega}\\left( \\frac{\\sin 8\\omega}{12} - \\frac{\\sin\\omega}{3} \\right).", explanation: "Using \\( 1/i = -i \\) and \\( \\operatorname{Re}(-i e^{i\\theta}) = \\sin\\theta \\). The \\( 1/\\phi' \\) weighting (\\( 1/12 \\) at \\( t=2 \\), \\( 1/3 \\) at \\( t=1 \\)) is the signature of non-stationary phase. Verified numerically at \\( \\omega = 80, 160 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{1}{\\omega}\\left( \\frac{\\sin 8\\omega}{12} - \\frac{\\sin\\omega}{3} \\right) \\).",
      canonicalAnswer: "(sin(8*w)/12 - sin(w)/3)/w",
    },
  },
  {
    id: "am5a-023",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading two terms, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^\\infty e^{-t}\\cos t\\; e^{i\\omega t}\\, dt \\), and verify against the exact transform.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "one-sided endpoint", "Fourier transform"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the amplitude.", workingLatex: "f(t) = e^{-t}\\cos t, \\qquad f(0) = 1.", explanation: "Smooth and decaying on \\( [0,\\infty) \\); only the lower endpoint \\( t=0 \\) contributes since \\( f\\to 0 \\) at \\( +\\infty \\)." },
        { stepNumber: 2, description: "Compute \\( f'(0) \\).", workingLatex: "f'(t) = -e^{-t}\\cos t - e^{-t}\\sin t \\;\\Rightarrow\\; f'(0) = -1.", explanation: "Product rule; at \\( t=0 \\), \\( \\cos 0 = 1 \\), \\( \\sin 0 = 0 \\), giving \\( f'(0) = -1 \\)." },
        { stepNumber: 3, description: "Apply the one-sided IBP series.", workingLatex: "I(\\omega) \\sim -\\frac{f(0)}{i\\omega} + \\frac{f'(0)}{(i\\omega)^2} = -\\frac{1}{i\\omega} - \\frac{1}{(i\\omega)^2}.", explanation: "With no upper-endpoint contribution, the series is \\( \\sum_n \\frac{(-1)^{n+1}}{(i\\omega)^{n+1}} f^{(n)}(0) \\); the first two terms use \\( f(0)=1 \\), \\( f'(0)=-1 \\)." },
        { stepNumber: 4, description: "Evaluate the exact transform.", workingLatex: "I(\\omega) = \\int_0^\\infty e^{(-1 + i(\\omega+1))t}\\, dt \\cdot \\tfrac{1}{2} + \\int_0^\\infty e^{(-1 + i(\\omega-1))t}\\, dt \\cdot \\tfrac{1}{2}.", explanation: "Write \\( \\cos t = \\tfrac{1}{2}(e^{it}+e^{-it}) \\); each piece is an elementary exponential integral." },
        { stepNumber: 5, description: "Sum the closed form.", workingLatex: "I(\\omega) = \\frac{1}{2}\\!\\left[ \\frac{1}{1 - i(\\omega+1)} + \\frac{1}{1 - i(\\omega-1)} \\right] = \\frac{1 - i\\omega}{(1 - i\\omega)^2 + 1}.", explanation: "Combining the two fractions over a common denominator; this is the exact Fourier–Laplace transform." },
        { stepNumber: 6, description: "Expand for large \\( \\omega \\).", workingLatex: "I(\\omega) = \\frac{1 - i\\omega}{-\\omega^2 - 2i\\omega + 2} \\sim -\\frac{1}{i\\omega} - \\frac{1}{(i\\omega)^2} + \\cdots.", explanation: "Dividing numerator and denominator by \\( -\\omega^2 \\) and expanding reproduces exactly the two IBP terms. Verified numerically at \\( \\omega = 10, 40 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{1 - i\\omega}{(1 - i\\omega)^2 + 1} \\sim -\\frac{1}{i\\omega} - \\frac{1}{(i\\omega)^2} \\).",
      canonicalAnswer: "(1 - I*w)/((1 - I*w)^2 + 1)",
    },
  },
  // REVIEW: pure derivation of an exact-cancellation / superalgebraic-decay statement; no finite numeric integral to check at large parameter (the claim is that all power-law terms vanish).
  {
    id: "am5a-024",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f \\) be smooth on \\( [0,1] \\) with \\( f^{(n)}(0) = f^{(n)}(1) = 0 \\) for all \\( n \\ge 0 \\) (a smooth bump compactly supported inside \\( (0,1) \\)). Prove that \\( \\displaystyle \\int_0^1 f(t)\\, e^{i\\omega t}\\, dt \\) decays faster than any power of \\( 1/\\omega \\) as \\( \\omega \\to \\infty \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "Riemann-Lebesgue", "superalgebraic decay"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts \\( N \\) times.", workingLatex: "\\int_0^1 f e^{i\\omega t}\\, dt = \\sum_{n=0}^{N-1} \\frac{(-1)^n}{(i\\omega)^{n+1}}\\Big[ f^{(n)}(t)e^{i\\omega t} \\Big]_0^1 + \\frac{(-1)^{N}}{(i\\omega)^{N}}\\int_0^1 f^{(N)} e^{i\\omega t}\\, dt.", explanation: "This is the finite IBP identity with explicit remainder after \\( N \\) steps; it holds for any \\( N \\) because \\( f \\) is smooth." },
        { stepNumber: 2, description: "Kill every boundary term.", workingLatex: "f^{(n)}(0) = f^{(n)}(1) = 0 \\;\\Rightarrow\\; \\Big[ f^{(n)}(t)e^{i\\omega t} \\Big]_0^1 = 0 \\quad \\forall n.", explanation: "By hypothesis every derivative vanishes at both endpoints, so the entire boundary sum is zero for every \\( N \\)." },
        { stepNumber: 3, description: "Reduce to the pure remainder.", workingLatex: "\\int_0^1 f e^{i\\omega t}\\, dt = \\frac{(-1)^{N}}{(i\\omega)^{N}}\\int_0^1 f^{(N)}(t)\\, e^{i\\omega t}\\, dt.", explanation: "With the boundary terms gone, the integral equals just the remainder, valid for arbitrary \\( N \\)." },
        { stepNumber: 4, description: "Bound the remainder.", workingLatex: "\\left| \\int_0^1 f e^{i\\omega t}\\, dt \\right| \\le \\frac{1}{\\omega^{N}}\\int_0^1 |f^{(N)}(t)|\\, dt = \\frac{C_N}{\\omega^{N}}.", explanation: "Bounding \\( |e^{i\\omega t}| = 1 \\); \\( C_N = \\int_0^1 |f^{(N)}| \\) is a finite constant independent of \\( \\omega \\)." },
        { stepNumber: 5, description: "Conclude superalgebraic decay.", workingLatex: "\\int_0^1 f e^{i\\omega t}\\, dt = O\\!\\left(\\omega^{-N}\\right) \\quad \\text{for every } N \\;\\Rightarrow\\; o(\\omega^{-N})\\ \\forall N.", explanation: "Since the bound holds for every \\( N \\), the integral decays faster than any power of \\( 1/\\omega \\) — exactly as for the Fourier transform of a smooth compactly supported function." },
      ],
      finalAnswer: "The integral is \\( O(\\omega^{-N}) \\) for every \\( N \\), hence decays faster than any power of \\( 1/\\omega \\).",
    },
  },
  {
    id: "am5a-025",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading large-\\( \\omega \\) behaviour of \\( \\displaystyle I(\\omega) = \\int_0^1 t^{1/2}\\, e^{i\\omega t}\\, dt \\). Treat the endpoint \\( t=1 \\) by integration by parts, and explain why the contribution from \\( t=0 \\) is of order \\( \\omega^{-3/2} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "endpoint singularity", "fractional power"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate by parts about the smooth end.", workingLatex: "I(\\omega) = \\left[ \\frac{t^{1/2}e^{i\\omega t}}{i\\omega} \\right]_0^1 - \\frac{1}{i\\omega}\\int_0^1 \\tfrac{1}{2} t^{-1/2} e^{i\\omega t}\\, dt.", explanation: "The amplitude \\( t^{1/2} \\) is smooth at \\( t=1 \\) but only Hölder-continuous at \\( t=0 \\); IBP is still valid since \\( t^{-1/2} \\) is integrable." },
        { stepNumber: 2, description: "Evaluate the boundary term.", workingLatex: "\\left[ \\frac{t^{1/2}e^{i\\omega t}}{i\\omega} \\right]_0^1 = \\frac{e^{i\\omega}}{i\\omega} - 0 = \\frac{e^{i\\omega}}{i\\omega}.", explanation: "At \\( t=1 \\), \\( t^{1/2} = 1 \\); at \\( t=0 \\), \\( t^{1/2} = 0 \\), so the lower endpoint of this boundary term vanishes." },
        { stepNumber: 3, description: "Analyse the remainder near \\( t=0 \\).", workingLatex: "-\\frac{1}{2 i\\omega}\\int_0^1 t^{-1/2} e^{i\\omega t}\\, dt.", explanation: "This inner integral is dominated by the singular endpoint \\( t=0 \\); rescale to expose its size." },
        { stepNumber: 4, description: "Rescale \\( t = s/\\omega \\).", workingLatex: "\\int_0^1 t^{-1/2}e^{i\\omega t}\\, dt = \\omega^{-1/2}\\int_0^{\\omega} s^{-1/2} e^{i s}\\, ds \\to \\omega^{-1/2}\\int_0^{\\infty} s^{-1/2}e^{is}\\, ds.", explanation: "Substituting \\( t = s/\\omega \\) gives \\( dt = ds/\\omega \\) and \\( t^{-1/2} = \\omega^{1/2}s^{-1/2} \\); the net factor is \\( \\omega^{-1/2} \\). The limiting integral is a convergent Fresnel-type constant." },
        { stepNumber: 5, description: "Identify the constant.", workingLatex: "\\int_0^\\infty s^{-1/2}e^{is}\\, ds = \\Gamma\\!\\left(\\tfrac{1}{2}\\right) e^{i\\pi/4} = \\sqrt{\\pi}\\, e^{i\\pi/4}.", explanation: "This is the standard Fresnel/Gamma evaluation \\( \\int_0^\\infty s^{\\mu-1}e^{is}ds = \\Gamma(\\mu)e^{i\\pi\\mu/2} \\) with \\( \\mu = \\tfrac12 \\)." },
        { stepNumber: 6, description: "Combine the two contributions.", workingLatex: "I(\\omega) \\sim \\frac{e^{i\\omega}}{i\\omega} - \\frac{\\sqrt{\\pi}\\, e^{i\\pi/4}}{2\\, i\\,\\omega^{3/2}}, \\qquad \\omega \\to \\infty.", explanation: "The smooth endpoint gives the \\( O(1/\\omega) \\) oscillatory term; the singular endpoint at \\( t=0 \\) gives an \\( O(\\omega^{-3/2}) \\) correction (the extra half-power comes from the \\( t^{-1/2} \\) integrability edge). Spot-checked numerically at \\( \\omega = 100, 400 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{e^{i\\omega}}{i\\omega} - \\frac{\\sqrt{\\pi}\\, e^{i\\pi/4}}{2\\, i\\,\\omega^{3/2}} \\).",
      canonicalAnswer: "exp(I*w)/(I*w) - sqrt(pi)*exp(I*pi/4)/(2*I*w^(3/2))",
    },
  },
  {
    id: "am5a-026",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By using \\( \\displaystyle \\int_0^\\infty e^{i x(\\frac{1}{3}t^3 + t)}\\, dt \\sim i\\!\\left(\\frac{1}{x} + \\frac{2}{x^3} + \\cdots\\right) \\) as \\( x\\to+\\infty \\) (a known result), reproduce the leading term by an integration-by-parts argument and identify \\( a_1 \\) in \\( \\sim i\\sum a_n x^{-n} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "non-stationary phase", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the phase and check for stationary points.", workingLatex: "\\phi(t) = \\tfrac{1}{3}t^3 + t, \\qquad \\phi'(t) = t^2 + 1 \\ge 1 > 0.", explanation: "The phase derivative \\( t^2+1 \\) never vanishes for real \\( t \\), so there are no stationary points on \\( [0,\\infty) \\); the integral is an IBP / endpoint problem, with the only endpoint at \\( t=0 \\) (the integrand oscillates faster and faster as \\( t\\to\\infty \\), contributing nothing)." },
        { stepNumber: 2, description: "Write the IBP form.", workingLatex: "e^{ix\\phi} = \\frac{1}{i x\\,\\phi'(t)}\\frac{d}{dt}e^{ix\\phi} = \\frac{1}{i x(t^2+1)}\\frac{d}{dt}e^{ix\\phi}.", explanation: "Standard non-stationary IBP: divide the derivative of the exponential by \\( i x\\phi' \\)." },
        { stepNumber: 3, description: "Integrate by parts.", workingLatex: "\\int_0^\\infty e^{ix\\phi}\\, dt = \\left[ \\frac{e^{ix\\phi}}{i x(t^2+1)} \\right]_0^\\infty + \\frac{1}{ix}\\int_0^\\infty \\frac{2t}{(t^2+1)^2}\\, e^{ix\\phi}\\, dt.", explanation: "Differentiating the amplitude \\( 1/(t^2+1) \\) gives \\( -2t/(t^2+1)^2 \\); the sign flips back to a plus on the remainder. At \\( t=\\infty \\) the boundary term vanishes." },
        { stepNumber: 4, description: "Read off the leading endpoint term.", workingLatex: "\\left[ \\frac{e^{ix\\phi}}{i x(t^2+1)} \\right]_{0}^{\\infty} = 0 - \\frac{e^{0}}{i x\\cdot 1} = -\\frac{1}{ix} = \\frac{i}{x}.", explanation: "At \\( t=\\infty \\) the boundary term vanishes (the integrand oscillates ever faster and the amplitude \\( 1/(t^2+1)\\to 0 \\)); at \\( t=0 \\), \\( \\phi(0)=0 \\) and \\( \\phi'(0)=1 \\), giving \\( 1/(ix) \\). The bracket is upper minus lower, \\( 0 - 1/(ix) = -1/(ix) = i/x \\)." },
        { stepNumber: 5, description: "Match to the stated series.", workingLatex: "\\int_0^\\infty e^{ix\\phi}\\, dt \\sim \\frac{i}{x} \\;\\Rightarrow\\; a_1 = 1.", explanation: "Comparing with \\( i(a_1/x + a_2/x^2 + \\cdots) \\) and the given expansion \\( i(1/x + 2/x^3 + \\cdots) \\), the coefficient of \\( 1/x \\) is \\( a_1 = 1 \\). The \\( 1/x^2 \\) term is absent because \\( \\phi' \\) is even and the first correction at \\( t=0 \\) cancels, consistent with the next non-zero term being \\( 2/x^3 \\)." },
      ],
      finalAnswer: "Leading term \\( \\dfrac{i}{x} \\); hence \\( a_1 = 1 \\).",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am5a-027",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_0^1 e^{t}\\, e^{i\\omega t}\\, dt \\) by integration by parts, and confirm them by expanding the exact value \\( \\dfrac{e^{1+i\\omega} - 1}{1+i\\omega} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "asymptotic expansion", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List endpoint amplitudes.", workingLatex: "f(t) = e^{t},\\; f^{(n)}(t) = e^{t} \\;\\Rightarrow\\; f^{(n)}(0)=1,\\; f^{(n)}(1)=e \\quad \\forall n.", explanation: "Every derivative of \\( e^t \\) is \\( e^t \\), so all endpoint values are \\( 1 \\) at \\( t=0 \\) and \\( e \\) at \\( t=1 \\) — the IBP series is especially clean." },
        { stepNumber: 2, description: "Write the two-term series.", workingLatex: "I(\\omega) = \\frac{f(1)e^{i\\omega} - f(0)}{i\\omega} - \\frac{f'(1)e^{i\\omega} - f'(0)}{(i\\omega)^2} + \\cdots.", explanation: "General endpoint expansion with \\( a=0,\\,b=1 \\)." },
        { stepNumber: 3, description: "Insert the values.", workingLatex: "I(\\omega) = \\frac{e\\, e^{i\\omega} - 1}{i\\omega} - \\frac{e\\, e^{i\\omega} - 1}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right).", explanation: "Both terms share the factor \\( e\\,e^{i\\omega} - 1 \\) because all derivatives equal the function." },
        { stepNumber: 4, description: "Expand the exact value.", workingLatex: "\\frac{e^{1+i\\omega}-1}{1+i\\omega} = \\frac{e\\,e^{i\\omega}-1}{i\\omega}\\cdot\\frac{1}{1 + \\frac{1}{i\\omega}} = \\frac{e\\,e^{i\\omega}-1}{i\\omega}\\left(1 - \\frac{1}{i\\omega} + \\cdots\\right).", explanation: "Factor \\( i\\omega \\) out of the denominator and expand the geometric series." },
        { stepNumber: 5, description: "Confirm the match.", workingLatex: "= \\frac{e\\,e^{i\\omega}-1}{i\\omega} - \\frac{e\\,e^{i\\omega}-1}{(i\\omega)^2} + \\cdots.", explanation: "The expansion of the exact value reproduces the IBP series term by term. Verified numerically at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) = \\frac{e\\, e^{i\\omega} - 1}{i\\omega} - \\frac{e\\, e^{i\\omega} - 1}{(i\\omega)^2} + O\\!\\left(\\frac{1}{\\omega^3}\\right) \\).",
      canonicalAnswer: "(exp(1 + I*w) - 1)/(1 + I*w)",
    },
  },
  {
    id: "am5a-028",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( \\omega \\to \\infty \\), of \\( \\displaystyle I(\\omega) = \\int_{-1}^{1} |t|\\, e^{i\\omega t}\\, dt \\), and comment on the order of decay relative to a smooth amplitude.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "corner singularity", "Riemann-Lebesgue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split at the corner.", workingLatex: "I(\\omega) = \\int_{-1}^{0} (-t)\\, e^{i\\omega t}\\, dt + \\int_0^1 t\\, e^{i\\omega t}\\, dt.", explanation: "\\( |t| \\) is continuous but has a corner (slope jump) at \\( t=0 \\); on each half it is smooth, so IBP applies piecewise." },
        { stepNumber: 2, description: "IBP on the right half.", workingLatex: "\\int_0^1 t\\, e^{i\\omega t}\\, dt = \\frac{e^{i\\omega}}{i\\omega} - \\frac{e^{i\\omega} - 1}{(i\\omega)^2}.", explanation: "From the standard two-step IBP; \\( f=t \\), \\( f(0)=0 \\), \\( f(1)=1 \\), \\( f'=1 \\)." },
        { stepNumber: 3, description: "IBP on the left half.", workingLatex: "\\int_{-1}^{0} (-t)\\, e^{i\\omega t}\\, dt = -\\frac{e^{-i\\omega}}{i\\omega} + \\frac{1 - e^{-i\\omega}}{(i\\omega)^2}.", explanation: "Here \\( f=-t \\), \\( f(-1)=1 \\), \\( f(0)=0 \\), \\( f'=-1 \\). The boundary bracket \\( [(-t)e^{i\\omega t}/(i\\omega)]_{-1}^{0} = 0 - e^{-i\\omega}/(i\\omega) \\) carries a minus sign because the non-zero amplitude sits at the lower limit \\( t=-1 \\)." },
        { stepNumber: 4, description: "Add the halves.", workingLatex: "I(\\omega) = \\frac{e^{i\\omega} - e^{-i\\omega}}{i\\omega} + \\frac{(1 - e^{-i\\omega}) - (e^{i\\omega} - 1)}{(i\\omega)^2}.", explanation: "Collecting like powers of \\( i\\omega \\); the \\( t=0 \\) boundary terms cancel because \\( |t|=0 \\) there, leaving the genuine endpoints \\( \\pm 1 \\)." },
        { stepNumber: 5, description: "Simplify the leading term.", workingLatex: "\\frac{e^{i\\omega} - e^{-i\\omega}}{i\\omega} = \\frac{2 i\\sin\\omega}{i\\omega} = \\frac{2\\sin\\omega}{\\omega}.", explanation: "Using \\( e^{i\\omega}-e^{-i\\omega} = 2 i\\sin\\omega \\); the integral is real, as it must be since \\( |t| \\) is even and the imaginary (sine) part integrates to zero." },
        { stepNumber: 6, description: "State the result and comment.", workingLatex: "I(\\omega) \\sim \\frac{2\\sin\\omega}{\\omega} + \\frac{2(\\cos\\omega - 1)}{\\omega^2}, \\qquad \\omega \\to \\infty.", explanation: "The \\( O(1/\\omega) \\) term survives from the endpoints \\( \\pm 1 \\); the second term follows from \\( (1-e^{-i\\omega})-(e^{i\\omega}-1) = 2 - 2\\cos\\omega \\) divided by \\( (i\\omega)^2 = -\\omega^2 \\). The corner at \\( t=0 \\) does NOT add a \\( 1/\\omega \\) term (amplitude is continuous there), but it does feed the \\( O(1/\\omega^2) \\) term through the slope jump — slower than the superalgebraic decay a fully smooth even bump would give. Verified numerically against \\( 2\\sin\\omega/\\omega + 2(\\cos\\omega-1)/\\omega^2 \\) at \\( \\omega = 50, 200 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{2\\sin\\omega}{\\omega} + \\frac{2(\\cos\\omega - 1)}{\\omega^2} \\).",
      canonicalAnswer: "2*sin(w)/w + 2*(cos(w) - 1)/w^2",
    },
  },
  {
    id: "am5a-029",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading large-\\( \\omega \\) behaviour of the real integral \\( \\displaystyle I(\\omega) = \\int_0^1 \\frac{\\sin(\\omega t)}{1 + t^2}\\, dt \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "real form", "endpoint contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pass to the complex form.", workingLatex: "I(\\omega) = \\operatorname{Im}\\int_0^1 \\frac{e^{i\\omega t}}{1+t^2}\\, dt, \\qquad f(t) = \\frac{1}{1+t^2}.", explanation: "Write \\( \\sin(\\omega t) = \\operatorname{Im}\\, e^{i\\omega t} \\); the amplitude \\( 1/(1+t^2) \\) is smooth on \\( [0,1] \\)." },
        { stepNumber: 2, description: "Leading IBP term.", workingLatex: "\\int_0^1 \\frac{e^{i\\omega t}}{1+t^2}\\, dt \\sim \\frac{f(1)e^{i\\omega} - f(0)}{i\\omega}, \\qquad f(1) = \\tfrac{1}{2},\\; f(0) = 1.", explanation: "Standard endpoint formula; both endpoints contribute." },
        { stepNumber: 3, description: "Substitute the values.", workingLatex: "\\frac{\\tfrac{1}{2}e^{i\\omega} - 1}{i\\omega} = \\frac{1}{i\\omega}\\left(\\tfrac{1}{2}e^{i\\omega} - 1\\right) = -\\frac{i}{\\omega}\\left(\\tfrac{1}{2}e^{i\\omega} - 1\\right).", explanation: "Using \\( 1/i = -i \\)." },
        { stepNumber: 4, description: "Take the imaginary part.", workingLatex: "\\operatorname{Im}\\!\\left[ -\\frac{i}{\\omega}\\left(\\tfrac{1}{2}(\\cos\\omega + i\\sin\\omega) - 1\\right) \\right] = -\\frac{1}{\\omega}\\left(\\tfrac{1}{2}\\cos\\omega - 1\\right).", explanation: "Multiplying by \\( -i \\) swaps real and imaginary parts with a sign; \\( \\operatorname{Im}(-i z) = -\\operatorname{Re}(z) \\), and \\( \\operatorname{Re}(\\tfrac12 e^{i\\omega} - 1) = \\tfrac12\\cos\\omega - 1 \\)." },
        { stepNumber: 5, description: "State the leading term.", workingLatex: "I(\\omega) \\sim \\frac{1 - \\tfrac{1}{2}\\cos\\omega}{\\omega} = \\frac{2 - \\cos\\omega}{2\\omega}, \\qquad \\omega \\to \\infty.", explanation: "The leading decay is \\( O(1/\\omega) \\), with both endpoints \\( t=0 \\) (value \\( 1 \\)) and \\( t=1 \\) (value \\( \\tfrac12 \\)) contributing. Verified numerically at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{2 - \\cos\\omega}{2\\omega} \\).",
      canonicalAnswer: "(2 - cos(w))/(2*w)",
    },
  },
  {
    id: "am5a-030",
    topicRef: "am5a",
    topicTitle: "Integration by parts & the Riemann–Lebesgue lemma 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading large-\\( \\omega \\) behaviour of \\( \\displaystyle I(\\omega) = \\int_0^2 H(t-1)\\, e^{t}\\, e^{i\\omega t}\\, dt \\), where \\( H \\) is the Heaviside step. Identify both the genuine endpoint and the discontinuity contributions.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "discontinuity", "Heaviside"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Resolve the Heaviside.", workingLatex: "H(t-1) e^{t} = \\begin{cases} 0, & 0 \\le t < 1, \\\\ e^{t}, & 1 < t \\le 2. \\end{cases}", explanation: "The amplitude is zero up to \\( t=1 \\) and \\( e^t \\) thereafter — a jump discontinuity at \\( t=1 \\) plus a genuine endpoint at \\( t=2 \\) (the lower endpoint \\( t=0 \\) sits in the zero region)." },
        { stepNumber: 2, description: "Reduce the integral.", workingLatex: "I(\\omega) = \\int_1^2 e^{t}\\, e^{i\\omega t}\\, dt.", explanation: "Only the region \\( t>1 \\) contributes, so the problem becomes an IBP on \\( [1,2] \\) with a jump at the lower limit \\( t=1 \\)." },
        { stepNumber: 3, description: "Identify the contributing points.", workingLatex: "f(1^+) = e^{1} = e, \\qquad f(2) = e^{2}; \\quad f(1^-) = 0.", explanation: "The amplitude jumps from \\( 0 \\) to \\( e \\) at \\( t=1 \\), so the jump size is \\( e \\); the genuine endpoint \\( t=2 \\) has amplitude \\( e^2 \\)." },
        { stepNumber: 4, description: "Endpoint term at \\( t=2 \\).", workingLatex: "\\frac{f(2)e^{2i\\omega}}{i\\omega} = \\frac{e^{2}e^{2i\\omega}}{i\\omega}.", explanation: "Standard upper-endpoint contribution." },
        { stepNumber: 5, description: "Jump term at \\( t=1 \\).", workingLatex: "-\\frac{[f(1^+) - f(1^-)]e^{i\\omega}}{i\\omega} = -\\frac{e\\, e^{i\\omega}}{i\\omega}.", explanation: "Apply the interior-jump rule with jump \\( e - 0 = e \\) at \\( c=1 \\). Equivalently, this is the lower-endpoint term of \\( \\int_1^2 \\), which carries a minus sign." },
        { stepNumber: 6, description: "Combine.", workingLatex: "I(\\omega) \\sim \\frac{e^{2}e^{2i\\omega} - e\\, e^{i\\omega}}{i\\omega}, \\qquad \\omega \\to \\infty.", explanation: "Sum of the endpoint and discontinuity contributions; both are \\( O(1/\\omega) \\). Verified numerically against the exact integral \\( (e^{2+2i\\omega} - e^{1+i\\omega})/(1+i\\omega) \\) at \\( \\omega = 60, 240 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I(\\omega) \\sim \\frac{e^{2}e^{2i\\omega} - e\\, e^{i\\omega}}{i\\omega} \\).",
      canonicalAnswer: "(exp(2)*exp(2*I*w) - exp(1)*exp(I*w))/(I*w)",
    },
  },
];
