import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Oscillatory Integrals
 * Subtopic am5d: Algebraic phases & fractional-power decay
 * Ref: am5d
 *
 * 30 fully-worked questions on integrals with an algebraic phase,
 *   I(x) = \int cos(x t^p) dt  (and sin / e^{ix t^p} variants), p > 1,
 * taken as x -> +infinity. The recurring theme: the endpoint t = 0, where the
 * phase t^p is stationary to high order, controls the leading behaviour and
 * produces a FRACTIONAL power x^{-1/p}, which dominates the ordinary O(1/x)
 * endpoint contribution from a non-stationary endpoint (because p > 1).
 *
 * Core results used throughout (all numerically verified with mpmath):
 *   - Mellin: \int_0^\infty u^{s-1} cos u du = \Gamma(s) cos(\pi s/2),
 *             \int_0^\infty u^{s-1} sin u du = \Gamma(s) sin(\pi s/2),  0<s<1.
 *   - \int_0^\infty cos(x t^p) dt = (1/p) \Gamma(1/p) cos(\pi/(2p)) x^{-1/p}.
 *   - \int_0^1 cos(x t^p) dt ~ (1/p)\Gamma(1/p)cos(\pi/(2p)) x^{-1/p}
 *                              + sin(x)/(p x) + ...   (leading term x^{-1/p}).
 * Special values verified: p=2 cos-coeff = sqrt(pi/8) (Fresnel);
 *   p=3 cos-coeff = (sqrt3/6)Gamma(1/3) = (sqrt3/2)Gamma(4/3);
 *   p=3 sin-coeff = (1/6)Gamma(1/3) = (1/2)Gamma(4/3).
 *
 * Seeded from Cambridge Part II Asymptotic Methods, Example Sheet 2, Q6(a)
 * (\int_0^1 cos(x t^p) dt, p>1) with constants, limits, phase (cos/sin/e^{i..}),
 * and framing varied; Q3 (endpoint contributions) and Q5 (\Gamma(4/3) link)
 * inform several Challenge items.
 */
export const questions: Question[] = [
  // ──────────────────────────── FOUNDATION (6) ────────────────────────────
  {
    id: "am5d-001",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 01",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Fresnel-type integral \\( \\displaystyle\\int_0^{\\infty} u^{-1/2}\\cos u \\, du \\) using the standard cosine Mellin transform \\( \\int_0^{\\infty} u^{s-1}\\cos u \\, du = \\Gamma(s)\\cos\\!\\big(\\tfrac{\\pi s}{2}\\big) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Mellin transform", "oscillatory integral", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the exponent parameter.", workingLatex: "u^{-1/2} = u^{s-1} \\quad\\Rightarrow\\quad s - 1 = -\\frac{1}{2} \\quad\\Rightarrow\\quad s = \\frac{1}{2}.", explanation: "Matching the integrand to the standard form fixes \\( s \\); since \\( 0 < s < 1 \\) the (conditionally convergent) formula applies." },
        { stepNumber: 2, description: "Substitute into the Mellin formula.", workingLatex: "\\int_0^{\\infty} u^{-1/2}\\cos u \\, du = \\Gamma\\!\\Big(\\frac{1}{2}\\Big)\\cos\\!\\Big(\\frac{\\pi}{4}\\Big).", explanation: "Read off \\( \\Gamma(s)\\cos(\\pi s/2) \\) at \\( s = 1/2 \\)." },
        { stepNumber: 3, description: "Insert the known constants.", workingLatex: "\\Gamma\\!\\Big(\\frac{1}{2}\\Big) = \\sqrt{\\pi}, \\qquad \\cos\\!\\Big(\\frac{\\pi}{4}\\Big) = \\frac{1}{\\sqrt{2}}.", explanation: "These are standard exact values." },
        { stepNumber: 4, description: "Simplify the product.", workingLatex: "\\sqrt{\\pi}\\cdot\\frac{1}{\\sqrt{2}} = \\sqrt{\\frac{\\pi}{2}}.", explanation: "Combine the surds; this is the exact value of the integral." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty} u^{-1/2}\\cos u\\,du = \\sqrt{\\dfrac{\\pi}{2}} \\)",
      canonicalAnswer: "sqrt(pi/2)",
    },
  },
  {
    id: "am5d-002",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "By the substitution \\( u = x t^{p} \\), reduce \\( \\displaystyle\\int_0^{\\infty}\\cos(x t^{p})\\,dt \\) (with \\( p>1 \\), \\( x>0 \\)) to a multiple of \\( x^{-1/p} \\) times a \\( u \\)-integral. State the resulting power of \\( x \\) and the prefactor.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["substitution", "algebraic phase", "fractional power"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the substitution.", workingLatex: "u = x t^{p} \\quad\\Rightarrow\\quad t = \\Big(\\frac{u}{x}\\Big)^{1/p}.", explanation: "We scale out the large parameter so that the oscillation rate becomes \\( O(1) \\) in \\( u \\)." },
        { stepNumber: 2, description: "Differentiate to get \\( dt \\).", workingLatex: "dt = \\frac{1}{p}\\,x^{-1/p}\\,u^{1/p - 1}\\,du.", explanation: "From \\( t = (u/x)^{1/p} \\), differentiate with respect to \\( u \\)." },
        { stepNumber: 3, description: "Transform the limits.", workingLatex: "t: 0 \\to \\infty \\quad\\Longleftrightarrow\\quad u: 0 \\to \\infty.", explanation: "The map \\( t \\mapsto u = x t^p \\) is increasing and onto for \\( t \\ge 0 \\)." },
        { stepNumber: 4, description: "Assemble the transformed integral.", workingLatex: "\\int_0^{\\infty}\\cos(x t^{p})\\,dt = \\frac{1}{p}\\,x^{-1/p}\\int_0^{\\infty} u^{1/p - 1}\\cos u \\, du.", explanation: "The whole \\( x \\)-dependence is now the prefactor \\( \\tfrac{1}{p}x^{-1/p} \\); the remaining \\( u \\)-integral is a pure constant." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty}\\cos(x t^{p})\\,dt = \\frac{1}{p}\\,x^{-1/p}\\int_0^{\\infty} u^{1/p-1}\\cos u\\,du \\); power \\( x^{-1/p} \\), prefactor \\( \\tfrac{1}{p} \\).",
    },
  },
  {
    id: "am5d-003",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the exact value of \\( \\displaystyle\\int_0^{\\infty}\\cos(t^{2})\\,dt \\) (the Fresnel cosine integral) using \\( \\int_0^{\\infty} u^{s-1}\\cos u\\,du = \\Gamma(s)\\cos(\\pi s/2) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral", "algebraic phase", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( u = t^2 \\).", workingLatex: "u = t^2,\\quad dt = \\frac{1}{2}u^{-1/2}\\,du,\\qquad \\int_0^{\\infty}\\cos(t^2)\\,dt = \\frac{1}{2}\\int_0^{\\infty} u^{-1/2}\\cos u\\,du.", explanation: "This is the \\( x=1,\\,p=2 \\) case of the algebraic-phase integral; the \\( u^{-1/2} \\) factor is the Jacobian." },
        { stepNumber: 2, description: "Apply the Mellin transform at \\( s = 1/2 \\).", workingLatex: "\\int_0^{\\infty} u^{-1/2}\\cos u\\,du = \\Gamma\\!\\Big(\\frac{1}{2}\\Big)\\cos\\!\\Big(\\frac{\\pi}{4}\\Big) = \\sqrt{\\pi}\\cdot\\frac{1}{\\sqrt2} = \\sqrt{\\frac{\\pi}{2}}.", explanation: "Same evaluation as the basic Mellin question." },
        { stepNumber: 3, description: "Multiply by the Jacobian factor.", workingLatex: "\\int_0^{\\infty}\\cos(t^2)\\,dt = \\frac{1}{2}\\sqrt{\\frac{\\pi}{2}} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{2}}.", explanation: "Carry the factor \\( \\tfrac12 \\) through." },
        { stepNumber: 4, description: "Write in the standard form.", workingLatex: "\\frac{1}{2}\\sqrt{\\frac{\\pi}{2}} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{2}} = \\sqrt{\\frac{\\pi}{8}}.", explanation: "The classic Fresnel value \\( \\sqrt{\\pi/8} \\approx 0.6267 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty}\\cos(t^2)\\,dt = \\sqrt{\\dfrac{\\pi}{8}} \\)",
      canonicalAnswer: "sqrt(pi/8)",
    },
  },
  {
    id: "am5d-004",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the decay rate (the power of \\( x \\)) of \\( \\displaystyle\\int_0^{1}\\cos(x t^{p})\\,dt \\) as \\( x\\to+\\infty \\), for \\( p>1 \\), and explain in one line why the endpoint \\( t=0 \\) dominates the endpoint \\( t=1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["decay rate", "endpoint contributions", "algebraic phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Contribution of the lower endpoint \\( t=0 \\).", workingLatex: "\\text{near } t=0:\\ \\phi(t)=t^p,\\ \\phi'(0)=0\\ (p>1) \\;\\Rightarrow\\; \\text{slow phase} \\;\\Rightarrow\\; \\sim x^{-1/p}.", explanation: "Because \\( p>1 \\), the phase \\( t^p \\) is flat at the origin, so a whole neighbourhood of \\( t=0 \\) contributes coherently — this is the algebraic analogue of a stationary point and gives the fractional power." },
        { stepNumber: 2, description: "Contribution of the upper endpoint \\( t=1 \\).", workingLatex: "\\text{near } t=1:\\ \\phi'(1)=p\\neq 0 \\;\\Rightarrow\\; \\text{ordinary endpoint} \\;\\Rightarrow\\; \\sim x^{-1}.", explanation: "Where the phase has non-zero slope, one integration by parts already gives \\( O(1/x) \\)." },
        { stepNumber: 3, description: "Compare the two powers.", workingLatex: "\\frac{1}{p} < 1 \\;\\text{ for } p>1 \\;\\Rightarrow\\; x^{-1/p} \\gg x^{-1}.", explanation: "A smaller decay exponent means a larger term, so the \\( t=0 \\) end wins." },
        { stepNumber: 4, description: "State the leading decay rate.", workingLatex: "\\int_0^1 \\cos(x t^p)\\,dt = O\\!\\big(x^{-1/p}\\big).", explanation: "The integral decays like \\( x^{-1/p} \\)." },
      ],
      finalAnswer: "Decay rate \\( x^{-1/p} \\); the flat phase at \\( t=0 \\) (since \\( p>1 \\)) beats the ordinary \\( O(1/x) \\) endpoint at \\( t=1 \\) because \\( 1/p<1 \\).",
    },
  },
  {
    id: "am5d-005",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 05",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the exact value of \\( \\displaystyle\\int_0^{\\infty} u^{-1/2}\\sin u \\, du \\) using \\( \\int_0^{\\infty} u^{s-1}\\sin u\\,du = \\Gamma(s)\\sin(\\pi s/2) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Mellin transform", "sine integral", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify \\( s \\).", workingLatex: "u^{-1/2}=u^{s-1}\\;\\Rightarrow\\; s=\\frac{1}{2}.", explanation: "Same exponent matching as the cosine case; \\( 0<s<1 \\) so the formula holds." },
        { stepNumber: 2, description: "Substitute into the sine Mellin formula.", workingLatex: "\\int_0^{\\infty} u^{-1/2}\\sin u\\,du = \\Gamma\\!\\Big(\\frac12\\Big)\\sin\\!\\Big(\\frac{\\pi}{4}\\Big).", explanation: "Read off \\( \\Gamma(s)\\sin(\\pi s/2) \\) at \\( s=1/2 \\)." },
        { stepNumber: 3, description: "Insert constants and simplify.", workingLatex: "\\sqrt{\\pi}\\cdot\\frac{1}{\\sqrt2} = \\sqrt{\\frac{\\pi}{2}}.", explanation: "Since \\( \\sin(\\pi/4)=\\cos(\\pi/4) \\), this equals the cosine value." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty} u^{-1/2}\\sin u\\,du = \\sqrt{\\dfrac{\\pi}{2}} \\)",
      canonicalAnswer: "sqrt(pi/2)",
    },
  },
  {
    id: "am5d-006",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using one integration by parts, find the leading large-\\( x \\) behaviour of the upper-endpoint contribution \\( \\displaystyle\\int_{1/2}^{1}\\cos(x t)\\,dt \\) (a linear, non-stationary phase). Give the leading term.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration by parts", "non-stationary endpoint", "decay rate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate directly (linear phase).", workingLatex: "\\int_{1/2}^{1}\\cos(x t)\\,dt = \\Big[\\frac{\\sin(x t)}{x}\\Big]_{1/2}^{1} = \\frac{\\sin x - \\sin(x/2)}{x}.", explanation: "A linear phase needs no asymptotics — it integrates exactly — but it models the generic non-stationary endpoint." },
        { stepNumber: 2, description: "Read off the order in \\( x \\).", workingLatex: "\\frac{\\sin x - \\sin(x/2)}{x} = O\\!\\Big(\\frac{1}{x}\\Big).", explanation: "Both boundary terms are bounded oscillations divided by \\( x \\)." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "\\int_{1/2}^{1}\\cos(x t)\\,dt \\sim \\frac{\\sin x - \\sin(x/2)}{x}.", explanation: "This \\( O(1/x) \\) rate is exactly what an ordinary endpoint gives — to be contrasted with the slower-decaying \\( x^{-1/p} \\) from a flat phase." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{1/2}^{1}\\cos(x t)\\,dt = \\dfrac{\\sin x - \\sin(x/2)}{x} = O(x^{-1}) \\)",
    },
  },

  // ──────────────────────────── STANDARD (12) ────────────────────────────
  {
    id: "am5d-007",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 07",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading term, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_0^{1}\\cos(x t^{p})\\,dt \\) for real \\( p>1 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["algebraic phase", "fractional power", "leading order", "Mellin transform"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the dominant region.", workingLatex: "\\phi(t)=t^p,\\quad \\phi'(t)=p t^{p-1},\\quad \\phi'(0)=0.", explanation: "For \\( p>1 \\) the phase is stationary (flat) at the lower endpoint \\( t=0 \\); this is where the slowest decay comes from." },
        { stepNumber: 2, description: "Extend to a half-line.", workingLatex: "\\int_0^1\\cos(x t^p)\\,dt = \\int_0^{\\infty}\\cos(x t^p)\\,dt - \\int_1^{\\infty}\\cos(x t^p)\\,dt.", explanation: "The tail \\( \\int_1^{\\infty} \\) has a non-stationary phase, so by parts it is \\( O(1/x) \\), subdominant to the fractional power we are about to find." },
        { stepNumber: 3, description: "Substitute \\( u=x t^p \\) in the half-line integral.", workingLatex: "\\int_0^{\\infty}\\cos(x t^p)\\,dt = \\frac{1}{p}\\,x^{-1/p}\\int_0^{\\infty} u^{1/p-1}\\cos u\\,du.", explanation: "This isolates the \\( x \\)-dependence as \\( x^{-1/p} \\); the \\( u \\)-integral is a constant." },
        { stepNumber: 4, description: "Evaluate the \\( u \\)-integral by the Mellin transform.", workingLatex: "\\int_0^{\\infty} u^{1/p-1}\\cos u\\,du = \\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big).", explanation: "Here \\( s=1/p\\in(0,1) \\), so \\( \\int_0^\\infty u^{s-1}\\cos u\\,du=\\Gamma(s)\\cos(\\pi s/2) \\) applies." },
        { stepNumber: 5, description: "Combine and discard the subdominant tail.", workingLatex: "\\int_0^1\\cos(x t^p)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big)\\,x^{-1/p}.", explanation: "Since \\( 1/p<1 \\), the \\( x^{-1/p} \\) term beats the \\( O(1/x) \\) endpoint correction." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^p)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big)\\,x^{-1/p} \\)",
      canonicalAnswer: "(1/p)*gamma(1/p)*cos(pi/(2*p))*x^(-1/p)",
    },
  },
  {
    id: "am5d-008",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 08",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading term, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_0^{1}\\cos(x t^{3})\\,dt \\), giving the constant in terms of \\( \\Gamma(1/3) \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["algebraic phase", "cubic phase", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use the general result at \\( p=3 \\).", workingLatex: "\\int_0^1\\cos(x t^3)\\,dt \\sim \\frac{1}{3}\\,\\Gamma\\!\\Big(\\frac13\\Big)\\cos\\!\\Big(\\frac{\\pi}{6}\\Big)\\,x^{-1/3}.", explanation: "Substitute \\( p=3 \\) into the leading-order formula for an algebraic phase on \\( [0,1] \\)." },
        { stepNumber: 2, description: "Insert \\( \\cos(\\pi/6) \\).", workingLatex: "\\cos\\!\\Big(\\frac{\\pi}{6}\\Big) = \\frac{\\sqrt3}{2}.", explanation: "Standard exact value." },
        { stepNumber: 3, description: "Simplify the constant.", workingLatex: "\\frac{1}{3}\\cdot\\frac{\\sqrt3}{2}\\,\\Gamma\\!\\Big(\\frac13\\Big) = \\frac{\\sqrt3}{6}\\,\\Gamma\\!\\Big(\\frac13\\Big).", explanation: "Collect numerical factors." },
        { stepNumber: 4, description: "State the leading term.", workingLatex: "\\int_0^1\\cos(x t^3)\\,dt \\sim \\frac{\\sqrt3}{6}\\,\\Gamma\\!\\Big(\\frac13\\Big)\\,x^{-1/3}.", explanation: "Numerically the constant is \\( \\approx 0.7733 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^3)\\,dt \\sim \\frac{\\sqrt3}{6}\\,\\Gamma\\!\\Big(\\frac13\\Big)\\,x^{-1/3} \\)",
      canonicalAnswer: "(sqrt(3)/6)*gamma(1/3)*x^(-1/3)",
    },
  },
  {
    id: "am5d-009",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 09",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\sin(x t^{2})\\,dt \\), and hence give its decay rate.",
    marks: 4,
    yearCreated: 2026,
    tags: ["sine phase", "Fresnel", "fractional power"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split off the half-line.", workingLatex: "\\int_0^1\\sin(x t^2)\\,dt = \\int_0^{\\infty}\\sin(x t^2)\\,dt - \\int_1^{\\infty}\\sin(x t^2)\\,dt.", explanation: "The tail has non-stationary phase, contributing only \\( O(1/x) \\)." },
        { stepNumber: 2, description: "Substitute \\( u=x t^2 \\).", workingLatex: "\\int_0^{\\infty}\\sin(x t^2)\\,dt = \\frac{1}{2}\\,x^{-1/2}\\int_0^{\\infty} u^{-1/2}\\sin u\\,du.", explanation: "Jacobian \\( dt=\\tfrac12 x^{-1/2}u^{-1/2}du \\); here \\( p=2 \\)." },
        { stepNumber: 3, description: "Apply the sine Mellin transform.", workingLatex: "\\int_0^{\\infty} u^{-1/2}\\sin u\\,du = \\Gamma\\!\\Big(\\frac12\\Big)\\sin\\!\\Big(\\frac{\\pi}{4}\\Big) = \\sqrt{\\pi}\\cdot\\frac{1}{\\sqrt2}.", explanation: "Use \\( s=1/2 \\) in \\( \\Gamma(s)\\sin(\\pi s/2) \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_0^{\\infty}\\sin(x t^2)\\,dt = \\frac12\\sqrt{\\frac{\\pi}{2}}\\,x^{-1/2} = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Same Fresnel constant as the cosine case because \\( \\sin(\\pi/4)=\\cos(\\pi/4) \\)." },
        { stepNumber: 5, description: "State the leading term.", workingLatex: "\\int_0^1\\sin(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Decay rate \\( x^{-1/2} \\), dominating the \\( O(1/x) \\) endpoint at \\( t=1 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\sin(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} \\); decay rate \\( x^{-1/2} \\).",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2)",
    },
  },
  {
    id: "am5d-010",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 10",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Show that, as \\( x\\to+\\infty \\), \\( \\displaystyle\\int_0^{1} e^{\\,i x t^{p}}\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\,e^{\\,i\\pi/(2p)}\\,x^{-1/p} \\) for \\( p>1 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["complex exponential phase", "algebraic phase", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Extend to the half-line.", workingLatex: "\\int_0^1 e^{ix t^p}\\,dt = \\int_0^{\\infty} e^{ix t^p}\\,dt - \\int_1^{\\infty} e^{ix t^p}\\,dt,", explanation: "The tail integral is \\( O(1/x) \\) by one integration by parts, hence subdominant." },
        { stepNumber: 2, description: "Substitute \\( u=x t^p \\).", workingLatex: "\\int_0^{\\infty} e^{ix t^p}\\,dt = \\frac{1}{p}\\,x^{-1/p}\\int_0^{\\infty} u^{1/p-1} e^{iu}\\,du.", explanation: "Same scaling as the cosine case, now with \\( e^{iu} \\)." },
        { stepNumber: 3, description: "Rotate the contour to the positive imaginary axis.", workingLatex: "\\int_0^{\\infty} u^{s-1} e^{iu}\\,du = e^{\\,i\\pi s/2}\\,\\Gamma(s),\\qquad s=\\frac1p.", explanation: "Jordan's lemma justifies rotating \\( u=e^{i\\pi/2}\\rho \\); the integral becomes \\( e^{i\\pi s/2}\\int_0^\\infty\\rho^{s-1}e^{-\\rho}d\\rho \\)." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "\\int_0^1 e^{ix t^p}\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\,e^{\\,i\\pi/(2p)}\\,x^{-1/p}.", explanation: "Taking real and imaginary parts recovers the \\( \\cos \\) and \\( \\sin \\) results: \\( \\Gamma(1/p)\\cos(\\pi/(2p)) \\) and \\( \\Gamma(1/p)\\sin(\\pi/(2p)) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1 e^{ix t^p}\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\,e^{\\,i\\pi/(2p)}\\,x^{-1/p} \\)",
    },
  },
  {
    id: "am5d-011",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 11",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) term of \\( \\displaystyle\\int_0^{2}\\cos(x t^{2})\\,dt \\). Show explicitly that the upper limit does not affect the leading coefficient.",
    marks: 4,
    yearCreated: 2026,
    tags: ["finite upper limit", "Fresnel", "endpoint independence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split at the relevant endpoints.", workingLatex: "\\int_0^2\\cos(x t^2)\\,dt = \\int_0^{\\infty}\\cos(x t^2)\\,dt - \\int_2^{\\infty}\\cos(x t^2)\\,dt.", explanation: "The leading behaviour comes from the flat phase at \\( t=0 \\); the upper limit only enters a non-stationary tail." },
        { stepNumber: 2, description: "Evaluate the half-line integral.", workingLatex: "\\int_0^{\\infty}\\cos(x t^2)\\,dt = \\frac12 x^{-1/2}\\,\\Gamma\\!\\Big(\\frac12\\Big)\\cos\\!\\Big(\\frac{\\pi}{4}\\Big) = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Identical to the Fresnel half-line value." },
        { stepNumber: 3, description: "Bound the tail by parts.", workingLatex: "\\int_2^{\\infty}\\cos(x t^2)\\,dt = \\Big[\\frac{\\sin(x t^2)}{2 x t}\\Big]_2^{\\infty} + \\cdots = -\\frac{\\sin(4x)}{4x} + O(x^{-1}).", explanation: "Phase derivative \\( 2xt \\neq 0 \\) on \\( [2,\\infty) \\), so the endpoint contributes only at \\( O(1/x) \\)." },
        { stepNumber: 4, description: "Compare orders.", workingLatex: "x^{-1/2} \\gg x^{-1} \\quad (x\\to\\infty).", explanation: "The fractional power dominates; the upper-limit value \\( 2 \\) sits in the subdominant term only." },
        { stepNumber: 5, description: "State the leading term.", workingLatex: "\\int_0^2\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "The coefficient \\( \\sqrt{\\pi/8} \\) is independent of the finite upper limit." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^2\\cos(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} \\) (coefficient independent of the upper limit).",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2)",
    },
  },
  {
    id: "am5d-012",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 12",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos(x t^{4})\\,dt \\), giving the constant in terms of \\( \\Gamma(1/4) \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["quartic phase", "algebraic phase", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Specialise the general formula to \\( p=4 \\).", workingLatex: "\\int_0^1\\cos(x t^4)\\,dt \\sim \\frac14\\,\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)\\,x^{-1/4}.", explanation: "Set \\( p=4 \\) in \\( \\tfrac1p\\Gamma(1/p)\\cos(\\pi/(2p))x^{-1/p} \\)." },
        { stepNumber: 2, description: "Keep \\( \\cos(\\pi/8) \\) in surd form (optional).", workingLatex: "\\cos\\!\\Big(\\frac{\\pi}{8}\\Big) = \\frac{\\sqrt{2+\\sqrt2}}{2}.", explanation: "Half-angle identity \\( \\cos(\\pi/8)=\\sqrt{(1+\\cos(\\pi/4))/2} \\)." },
        { stepNumber: 3, description: "State the leading term.", workingLatex: "\\int_0^1\\cos(x t^4)\\,dt \\sim \\frac14\\,\\Gamma\\!\\Big(\\frac14\\Big)\\frac{\\sqrt{2+\\sqrt2}}{2}\\,x^{-1/4}.", explanation: "Numerically the constant is \\( \\approx 0.8374 \\), and the decay rate is the slow \\( x^{-1/4} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^4)\\,dt \\sim \\frac14\\,\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)\\,x^{-1/4} \\)",
      canonicalAnswer: "(1/4)*gamma(1/4)*cos(pi/8)*x^(-1/4)",
    },
  },
  {
    id: "am5d-013",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 13",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos\\!\\big(x t^{3/2}\\big)\\,dt \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["non-integer power", "algebraic phase", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set \\( p=3/2 \\) and check \\( p>1 \\).", workingLatex: "p=\\frac32>1,\\qquad \\frac1p=\\frac23.", explanation: "The flat-phase argument applies for any real \\( p>1 \\), not just integers." },
        { stepNumber: 2, description: "Apply the leading-order formula.", workingLatex: "\\int_0^1\\cos\\!\\big(x t^{3/2}\\big)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big)x^{-1/p} = \\frac{2}{3}\\,\\Gamma\\!\\Big(\\frac23\\Big)\\cos\\!\\Big(\\frac{\\pi}{3}\\Big)x^{-2/3}.", explanation: "Insert \\( 1/p=2/3 \\) and \\( \\pi/(2p)=\\pi/3 \\)." },
        { stepNumber: 3, description: "Insert \\( \\cos(\\pi/3) \\).", workingLatex: "\\cos\\!\\Big(\\frac{\\pi}{3}\\Big) = \\frac12.", explanation: "Standard value." },
        { stepNumber: 4, description: "Simplify.", workingLatex: "\\int_0^1\\cos\\!\\big(x t^{3/2}\\big)\\,dt \\sim \\frac{1}{3}\\,\\Gamma\\!\\Big(\\frac23\\Big)x^{-2/3}.", explanation: "The decay is \\( x^{-2/3} \\); numerically \\( \\tfrac13\\Gamma(2/3)\\approx 0.4520 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos\\!\\big(x t^{3/2}\\big)\\,dt \\sim \\frac{1}{3}\\,\\Gamma\\!\\Big(\\frac23\\Big)\\,x^{-2/3} \\)",
      canonicalAnswer: "(1/3)*gamma(2/3)*x^(-2/3)",
    },
  },
  {
    id: "am5d-014",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 14",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos(a\\, x\\, t^{2})\\,dt \\), where \\( a>0 \\) is a fixed constant, and state how the coefficient scales with \\( a \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["scaling constant", "Fresnel", "algebraic phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Absorb \\( a \\) into the parameter.", workingLatex: "a x t^2 = (a x)\\,t^2,\\qquad X := a x \\to \\infty.", explanation: "The phase is still \\( t^2 \\); only the effective large parameter changes to \\( X=ax \\)." },
        { stepNumber: 2, description: "Apply the Fresnel half-line result in \\( X \\).", workingLatex: "\\int_0^1\\cos(X t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,X^{-1/2}.", explanation: "Same as the \\( p=2 \\) case with parameter \\( X \\)." },
        { stepNumber: 3, description: "Substitute back \\( X=ax \\).", workingLatex: "\\int_0^1\\cos(a x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,(a x)^{-1/2} = \\sqrt{\\frac{\\pi}{8 a}}\\,x^{-1/2}.", explanation: "The coefficient picks up a factor \\( a^{-1/2} \\)." },
        { stepNumber: 4, description: "State the scaling.", workingLatex: "\\text{coefficient} \\propto a^{-1/2}.", explanation: "A larger phase constant accelerates the oscillation, shrinking the leading amplitude as \\( a^{-1/2} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(a x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8 a}}\\,x^{-1/2} \\); coefficient \\( \\propto a^{-1/2} \\).",
      canonicalAnswer: "sqrt(pi/(8*a))*x^(-1/2)",
    },
  },
  {
    id: "am5d-015",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 15",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\sin(x t^{3})\\,dt \\), giving the constant in terms of \\( \\Gamma(4/3) \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["sine phase", "cubic", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduce to the half-line and substitute \\( u=x t^3 \\).", workingLatex: "\\int_0^1\\sin(x t^3)\\,dt \\sim \\frac13 x^{-1/3}\\int_0^{\\infty} u^{-2/3}\\sin u\\,du.", explanation: "Jacobian \\( dt=\\tfrac13 x^{-1/3}u^{-2/3}du \\); the upper-limit tail is \\( O(1/x) \\)." },
        { stepNumber: 2, description: "Apply the sine Mellin transform at \\( s=1/3 \\).", workingLatex: "\\int_0^{\\infty} u^{-2/3}\\sin u\\,du = \\Gamma\\!\\Big(\\frac13\\Big)\\sin\\!\\Big(\\frac{\\pi}{6}\\Big).", explanation: "Here \\( s-1=-2/3 \\) so \\( s=1/3 \\); use \\( \\Gamma(s)\\sin(\\pi s/2) \\)." },
        { stepNumber: 3, description: "Insert \\( \\sin(\\pi/6)=1/2 \\) and combine.", workingLatex: "\\int_0^1\\sin(x t^3)\\,dt \\sim \\frac13\\cdot\\frac12\\,\\Gamma\\!\\Big(\\frac13\\Big)x^{-1/3} = \\frac16\\,\\Gamma\\!\\Big(\\frac13\\Big)x^{-1/3}.", explanation: "Collect the numerical factors." },
        { stepNumber: 4, description: "Rewrite using \\( \\Gamma(4/3)=\\tfrac13\\Gamma(1/3) \\).", workingLatex: "\\frac16\\,\\Gamma\\!\\Big(\\frac13\\Big) = \\frac12\\,\\Gamma\\!\\Big(\\frac43\\Big).", explanation: "The recurrence \\( \\Gamma(z+1)=z\\Gamma(z) \\) with \\( z=1/3 \\) gives \\( \\Gamma(4/3)=\\tfrac13\\Gamma(1/3) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\sin(x t^3)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac43\\Big)\\,x^{-1/3} \\)",
      canonicalAnswer: "(1/2)*gamma(4/3)*x^(-1/3)",
    },
  },
  {
    id: "am5d-016",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Include the next correction: show that, as \\( x\\to+\\infty \\), \\( \\displaystyle\\int_0^{1}\\cos(x t^{2})\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} + \\frac{\\sin x}{2x} \\), and identify the origin of each term.",
    marks: 4,
    yearCreated: 2026,
    tags: ["two-term expansion", "endpoint contribution", "Fresnel"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the exact split.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt = \\underbrace{\\int_0^{\\infty}\\cos(x t^2)\\,dt}_{\\text{flat phase at }0} - \\underbrace{\\int_1^{\\infty}\\cos(x t^2)\\,dt}_{\\text{endpoint at }1}.", explanation: "Two distinct mechanisms contribute, on different scales." },
        { stepNumber: 2, description: "Lower-endpoint term.", workingLatex: "\\int_0^{\\infty}\\cos(x t^2)\\,dt = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Fresnel half-line value; this is the slow, fractional-power piece from the stationary phase at \\( t=0 \\)." },
        { stepNumber: 3, description: "Upper-endpoint term by parts.", workingLatex: "\\int_1^{\\infty}\\cos(x t^2)\\,dt = \\Big[\\frac{\\sin(x t^2)}{2 x t}\\Big]_1^{\\infty} + \\cdots = -\\frac{\\sin x}{2x} + O(x^{-2}).", explanation: "Write \\( \\cos(x t^2)=\\frac{1}{2xt}\\frac{d}{dt}\\sin(x t^2) \\); the boundary at \\( t=1 \\) gives \\( -\\sin x/(2x) \\), the infinite end vanishes." },
        { stepNumber: 4, description: "Subtract to recover the \\( [0,1] \\) integral.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} - \\Big(-\\frac{\\sin x}{2x}\\Big) = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} + \\frac{\\sin x}{2x}.", explanation: "The first term is the stationary-endpoint contribution (rate \\( x^{-1/2} \\)); the second is the ordinary endpoint at \\( t=1 \\) (rate \\( x^{-1} \\))." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} + \\dfrac{\\sin x}{2x} \\)",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2) + sin(x)/(2*x)",
    },
  },
  {
    id: "am5d-017",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 17",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "For \\( p>1 \\), find the leading large-\\( x \\) behaviour of the upper-endpoint correction \\( \\displaystyle\\int_0^{1}\\cos(x t^{p})\\,dt - \\frac1p\\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big)x^{-1/p} \\), i.e. the next term after the fractional power.",
    marks: 4,
    yearCreated: 2026,
    tags: ["endpoint correction", "integration by parts", "subdominant term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the remaining contribution.", workingLatex: "\\int_0^1\\cos(x t^p)\\,dt - \\frac1p\\Gamma\\!\\Big(\\frac1p\\Big)\\cos\\!\\Big(\\frac{\\pi}{2p}\\Big)x^{-1/p} = -\\int_1^{\\infty}\\cos(x t^p)\\,dt.", explanation: "Subtracting the half-line (flat-phase) value leaves exactly minus the non-stationary tail." },
        { stepNumber: 2, description: "Integrate the tail by parts.", workingLatex: "\\int_1^{\\infty}\\cos(x t^p)\\,dt = \\Big[\\frac{\\sin(x t^p)}{p x t^{p-1}}\\Big]_1^{\\infty} + \\cdots", explanation: "Use \\( \\cos(x t^p)=\\frac{1}{p x t^{p-1}}\\frac{d}{dt}\\sin(x t^p) \\)." },
        { stepNumber: 3, description: "Evaluate the boundary.", workingLatex: "= -\\frac{\\sin x}{p x} + O(x^{-2}).", explanation: "At \\( t=\\infty \\) the term vanishes; at \\( t=1 \\), \\( t^{p-1}=1 \\), giving \\( -\\sin x/(p x) \\)." },
        { stepNumber: 4, description: "Apply the sign.", workingLatex: "-\\int_1^{\\infty}\\cos(x t^p)\\,dt \\sim \\frac{\\sin x}{p x}.", explanation: "The next term after the fractional power is an \\( O(1/x) \\) oscillation from the endpoint \\( t=1 \\)." },
      ],
      finalAnswer: "Next term \\( \\sim \\dfrac{\\sin x}{p x} \\) (an \\( O(x^{-1}) \\) endpoint contribution from \\( t=1 \\)).",
      canonicalAnswer: "sin(x)/(p*x)",
    },
  },
  {
    id: "am5d-018",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 18",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{\\infty} e^{-x t^{4}}\\,dt \\) (a real, decaying algebraic phase), and contrast its rate with that of \\( \\int_0^\\infty \\cos(x t^4)\\,dt \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["Laplace-type", "algebraic phase", "Gamma function", "comparison"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute \\( u=x t^4 \\).", workingLatex: "\\int_0^{\\infty} e^{-x t^4}\\,dt = \\frac14 x^{-1/4}\\int_0^{\\infty} u^{-3/4} e^{-u}\\,du.", explanation: "Same scaling as the oscillatory case but with a real decaying exponential." },
        { stepNumber: 2, description: "Recognise the Gamma integral.", workingLatex: "\\int_0^{\\infty} u^{-3/4} e^{-u}\\,du = \\Gamma\\!\\Big(\\frac14\\Big).", explanation: "This is the definition of \\( \\Gamma(1/4) \\) (here the integral converges absolutely)." },
        { stepNumber: 3, description: "Assemble.", workingLatex: "\\int_0^{\\infty} e^{-x t^4}\\,dt = \\frac14\\,\\Gamma\\!\\Big(\\frac14\\Big)\\,x^{-1/4}.", explanation: "Exact for all \\( x>0 \\)." },
        { stepNumber: 4, description: "Contrast with the oscillatory case.", workingLatex: "\\int_0^{\\infty}\\cos(x t^4)\\,dt = \\frac14\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)x^{-1/4}.", explanation: "Both decay at the same rate \\( x^{-1/4} \\); the oscillatory version differs only by the factor \\( \\cos(\\pi/8) \\) from rotating the contour onto the imaginary axis." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty} e^{-x t^4}\\,dt = \\frac14\\,\\Gamma\\!\\Big(\\frac14\\Big)\\,x^{-1/4} \\); same \\( x^{-1/4} \\) rate as the cosine version (which carries an extra \\( \\cos(\\pi/8) \\)).",
      canonicalAnswer: "(1/4)*gamma(1/4)*x^(-1/4)",
    },
  },

  // ──────────────────────────── CHALLENGE (12) ────────────────────────────
  {
    id: "am5d-019",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 19",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms in the large-\\( x \\) expansion of \\( \\displaystyle\\int_0^{1}\\cos(x t^{3})\\,dt \\), as \\( x\\to+\\infty \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["two-term expansion", "cubic phase", "endpoint correction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split into half-line minus tail.", workingLatex: "\\int_0^1\\cos(x t^3)\\,dt = \\int_0^{\\infty}\\cos(x t^3)\\,dt - \\int_1^{\\infty}\\cos(x t^3)\\,dt.", explanation: "Leading term from \\( t=0 \\), correction from \\( t=1 \\)." },
        { stepNumber: 2, description: "Leading (fractional-power) term.", workingLatex: "\\int_0^{\\infty}\\cos(x t^3)\\,dt = \\frac13\\Gamma\\!\\Big(\\frac13\\Big)\\cos\\!\\Big(\\frac{\\pi}{6}\\Big)x^{-1/3} = \\frac{\\sqrt3}{6}\\Gamma\\!\\Big(\\frac13\\Big)x^{-1/3}.", explanation: "Mellin transform at \\( s=1/3 \\), with \\( \\cos(\\pi/6)=\\sqrt3/2 \\)." },
        { stepNumber: 3, description: "Tail by parts.", workingLatex: "\\int_1^{\\infty}\\cos(x t^3)\\,dt = \\Big[\\frac{\\sin(x t^3)}{3 x t^2}\\Big]_1^{\\infty}+\\cdots = -\\frac{\\sin x}{3x}+O(x^{-2}).", explanation: "Phase derivative \\( 3x t^2 \\); boundary at \\( t=1 \\) gives \\( -\\sin x/(3x) \\)." },
        { stepNumber: 4, description: "Subtract.", workingLatex: "\\int_0^1\\cos(x t^3)\\,dt \\sim \\frac{\\sqrt3}{6}\\Gamma\\!\\Big(\\frac13\\Big)x^{-1/3} + \\frac{\\sin x}{3x}.", explanation: "Two-term expansion: the slow fractional power plus the faster-decaying endpoint oscillation." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^3)\\,dt \\sim \\frac{\\sqrt3}{6}\\,\\Gamma\\!\\Big(\\frac13\\Big)\\,x^{-1/3} + \\frac{\\sin x}{3x} \\)",
      canonicalAnswer: "(sqrt(3)/6)*gamma(1/3)*x^(-1/3) + sin(x)/(3*x)",
    },
  },
  {
    id: "am5d-020",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 20",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms in the large-\\( x \\) expansion of \\( \\displaystyle\\int_0^{1}\\cos(x t^{2})\\,dt \\), including the second endpoint correction at \\( t=1 \\) beyond \\( \\sin x/(2x) \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["higher-order endpoint", "repeated integration by parts", "Fresnel"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split and recall the leading term.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} - \\int_1^{\\infty}\\cos(x t^2)\\,dt.", explanation: "The fractional power is fixed; refine the tail to two terms." },
        { stepNumber: 2, description: "First integration by parts on the tail.", workingLatex: "\\int_1^{\\infty}\\cos(x t^2)\\,dt = \\Big[\\frac{\\sin(x t^2)}{2 x t}\\Big]_1^{\\infty} + \\frac{1}{2x}\\int_1^{\\infty}\\frac{\\sin(x t^2)}{t^2}\\,dt.", explanation: "Differentiating \\( 1/(2xt) \\) produces the remainder integral, smaller by one power of \\( x \\)." },
        { stepNumber: 3, description: "Boundary term.", workingLatex: "\\Big[\\frac{\\sin(x t^2)}{2 x t}\\Big]_1^{\\infty} = -\\frac{\\sin x}{2x}.", explanation: "Evaluated at \\( t=1 \\) (the \\( t\\to\\infty \\) end vanishes by Riemann–Lebesgue)." },
        { stepNumber: 4, description: "Second integration by parts on the remainder.", workingLatex: "\\frac{1}{2x}\\int_1^{\\infty}\\frac{\\sin(x t^2)}{t^2}\\,dt = \\frac{1}{2x}\\Big[-\\frac{\\cos(x t^2)}{2x t^3}\\Big]_1^{\\infty}+\\cdots = \\frac{\\cos x}{4x^2} + O(x^{-3}).", explanation: "One more by parts; the boundary at \\( t=1 \\) gives \\( \\cos x/(4x^2) \\)." },
        { stepNumber: 5, description: "Combine the tail.", workingLatex: "\\int_1^{\\infty}\\cos(x t^2)\\,dt = -\\frac{\\sin x}{2x} + \\frac{\\cos x}{4x^2} + O(x^{-3}).", explanation: "Sum of the two boundary contributions." },
        { stepNumber: 6, description: "Subtract from the half-line value.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} + \\frac{\\sin x}{2x} - \\frac{\\cos x}{4x^2}.", explanation: "Three-term picture: fractional power, then two successive endpoint oscillations." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} + \\dfrac{\\sin x}{2x} - \\dfrac{\\cos x}{4x^2} \\)",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2) + sin(x)/(2*x) - cos(x)/(4*x^2)",
    },
  },
  // REVIEW: closed-form integral identity (Q5-style int_0^pi exp[i x(t - sin t)] dt) used as a cross-link; the leading-coefficient (6/x)^{1/3}Gamma(4/3) is the standard Stuart-notes result and the Gamma(4/3) value is verified, but the full stationary-phase derivation at t=0 is analytic, not a single numeric integral check.
  {
    id: "am5d-021",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 21",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "The phase \\( \\phi(t)=t-\\sin t \\) behaves like \\( \\tfrac{1}{6}t^{3} \\) near \\( t=0 \\). Using this, show that \\( \\displaystyle\\int_0^{\\pi} e^{\\,i x (t-\\sin t)}\\,dt \\sim e^{\\,i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\frac43\\Big) \\) as \\( x\\to+\\infty \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["stationary phase", "cubic-flattened phase", "Gamma(4/3)", "cross-method"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the phase at the endpoint \\( t=0 \\).", workingLatex: "\\phi(t)=t-\\sin t = \\frac{t^3}{6} - \\frac{t^5}{120}+\\cdots \\sim \\frac{t^3}{6}.", explanation: "Since \\( \\phi'(0)=\\phi''(0)=0 \\) but \\( \\phi'''(0)=1\\neq0 \\), the phase is cubically flat at \\( t=0 \\) — an algebraic phase with \\( p=3 \\)." },
        { stepNumber: 2, description: "Localise the integral at \\( t=0 \\).", workingLatex: "\\int_0^{\\pi} e^{ix\\phi(t)}\\,dt \\sim \\int_0^{\\infty} e^{\\,i x t^3/6}\\,dt.", explanation: "Only the neighbourhood of \\( t=0 \\) contributes at leading order; the upper limit \\( \\pi \\) gives a subdominant \\( O(1/x) \\) endpoint, and away from \\( 0 \\) the phase is non-stationary." },
        { stepNumber: 3, description: "Substitute \\( u = x t^3/6 \\).", workingLatex: "t = \\Big(\\frac{6u}{x}\\Big)^{1/3},\\qquad dt = \\frac13\\Big(\\frac{6}{x}\\Big)^{1/3}u^{-2/3}\\,du.", explanation: "Scale out \\( x \\); the prefactor carries the fractional power \\( (6/x)^{1/3} \\)." },
        { stepNumber: 4, description: "Reduce to a complex Gamma integral.", workingLatex: "\\int_0^{\\infty} e^{ix t^3/6}\\,dt = \\frac13\\Big(\\frac6x\\Big)^{1/3}\\int_0^{\\infty} u^{-2/3} e^{iu}\\,du.", explanation: "All \\( x \\)-dependence is in the prefactor." },
        { stepNumber: 5, description: "Rotate the contour: \\( \\int_0^\\infty u^{s-1}e^{iu}du = e^{i\\pi s/2}\\Gamma(s) \\).", workingLatex: "\\int_0^{\\infty} u^{-2/3} e^{iu}\\,du = e^{\\,i\\pi/6}\\,\\Gamma\\!\\Big(\\frac13\\Big),\\qquad s=\\frac13.", explanation: "Phase factor \\( e^{i\\pi s/2}=e^{i\\pi/6} \\); the modulus is \\( \\Gamma(1/3) \\)." },
        { stepNumber: 6, description: "Assemble and simplify with \\( \\Gamma(4/3)=\\tfrac13\\Gamma(1/3) \\).", workingLatex: "\\int_0^{\\pi} e^{ix(t-\\sin t)}\\,dt \\sim \\frac13\\Big(\\frac6x\\Big)^{1/3} e^{\\,i\\pi/6}\\Gamma\\!\\Big(\\frac13\\Big) = e^{\\,i\\pi/6}\\Big(\\frac6x\\Big)^{1/3}\\Gamma\\!\\Big(\\frac43\\Big).", explanation: "Using \\( \\tfrac13\\Gamma(1/3)=\\Gamma(4/3) \\) gives the stated compact form." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\pi} e^{ix(t-\\sin t)}\\,dt \\sim e^{\\,i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\frac43\\Big) \\)",
    },
  },
  {
    id: "am5d-022",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 22",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "An interior stationary point: find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_{-1}^{1}\\cos\\!\\big(x\\,t^{2}\\big)\\,dt \\) by exploiting symmetry, and confirm it is twice the half-range result.",
    marks: 5,
    yearCreated: 2026,
    tags: ["interior stationary point", "even integrand", "stationary phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use evenness.", workingLatex: "\\cos(x t^2)\\text{ is even} \\;\\Rightarrow\\; \\int_{-1}^{1}\\cos(x t^2)\\,dt = 2\\int_0^1\\cos(x t^2)\\,dt.", explanation: "Here \\( t=0 \\) is an interior stationary point of the phase, hit from both sides." },
        { stepNumber: 2, description: "Insert the half-range leading term.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "The standard Fresnel-type result on \\( [0,1] \\)." },
        { stepNumber: 3, description: "Double it.", workingLatex: "\\int_{-1}^{1}\\cos(x t^2)\\,dt \\sim 2\\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} = \\sqrt{\\frac{\\pi}{2}}\\,x^{-1/2}.", explanation: "Equivalent to the classical stationary-phase formula \\( \\sqrt{2\\pi/(x\\,|\\phi''|)}\\cos(\\cdots) \\) at \\( \\phi''=2 \\), confirming consistency between the algebraic-phase and stationary-phase viewpoints." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{-1}^{1}\\cos(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{2}}\\,x^{-1/2} \\)",
      canonicalAnswer: "sqrt(pi/2)*x^(-1/2)",
    },
  },
  {
    id: "am5d-023",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 23",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_{-1}^{1}\\cos\\!\\big(x\\,t^{4}\\big)\\,dt \\), where the phase \\( t^4 \\) has a quartic (degenerate) stationary point at the interior \\( t=0 \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["degenerate stationary point", "quartic phase", "even integrand"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use evenness.", workingLatex: "\\int_{-1}^{1}\\cos(x t^4)\\,dt = 2\\int_0^1\\cos(x t^4)\\,dt.", explanation: "Even integrand; \\( t=0 \\) is an interior quartically-flat point." },
        { stepNumber: 2, description: "Half-range leading term.", workingLatex: "\\int_0^1\\cos(x t^4)\\,dt \\sim \\frac14\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)x^{-1/4}.", explanation: "The \\( p=4 \\) algebraic-phase result." },
        { stepNumber: 3, description: "Double.", workingLatex: "\\int_{-1}^{1}\\cos(x t^4)\\,dt \\sim \\frac12\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)x^{-1/4}.", explanation: "A degenerate (higher-order) stationary point decays more slowly, \\( x^{-1/4} \\), than an ordinary one (\\( x^{-1/2} \\)) — flatter phase, wider coherent region." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{-1}^{1}\\cos(x t^4)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)\\,x^{-1/4} \\)",
      canonicalAnswer: "(1/2)*gamma(1/4)*cos(pi/8)*x^(-1/4)",
    },
  },
  {
    id: "am5d-024",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 24",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1} t^{\\,q}\\cos(x t^{p})\\,dt \\), where \\( p>1 \\) and \\( q>-1 \\), giving the constant in terms of the Gamma function.",
    marks: 6,
    yearCreated: 2026,
    tags: ["algebraic amplitude", "algebraic phase", "Mellin transform", "general exponent"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant endpoint.", workingLatex: "\\text{amplitude } t^q\\to 0 \\text{ (if }q>0)\\text{, phase flat at }t=0 \\;\\Rightarrow\\; t=0 \\text{ dominates}.", explanation: "Both the amplitude shape and the flat phase concentrate the contribution near \\( t=0 \\); we extend to the half-line." },
        { stepNumber: 2, description: "Extend and substitute \\( u=x t^p \\).", workingLatex: "\\int_0^{\\infty} t^q\\cos(x t^p)\\,dt = \\frac{1}{p}\\,x^{-(q+1)/p}\\int_0^{\\infty} u^{(q+1)/p-1}\\cos u\\,du.", explanation: "With \\( t=(u/x)^{1/p} \\), the factor \\( t^q \\) becomes \\( (u/x)^{q/p} \\); collecting powers gives exponent \\( (q+1)/p-1 \\) and prefactor \\( x^{-(q+1)/p} \\)." },
        { stepNumber: 3, description: "Set \\( s=(q+1)/p \\) and check the range.", workingLatex: "0 < s = \\frac{q+1}{p} ,\\qquad s<1 \\text{ when } q+1<p.", explanation: "For the conditionally-convergent cosine Mellin transform we need \\( 0<s<1 \\); take \\( q+1<p \\) (otherwise interpret by analytic continuation)." },
        { stepNumber: 4, description: "Apply the Mellin transform.", workingLatex: "\\int_0^{\\infty} u^{s-1}\\cos u\\,du = \\Gamma(s)\\cos\\!\\Big(\\frac{\\pi s}{2}\\Big),\\qquad s=\\frac{q+1}{p}.", explanation: "Standard cosine transform." },
        { stepNumber: 5, description: "Assemble the leading term.", workingLatex: "\\int_0^1 t^q\\cos(x t^p)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac{q+1}{p}\\Big)\\cos\\!\\Big(\\frac{\\pi(q+1)}{2p}\\Big)\\,x^{-(q+1)/p}.", explanation: "Decay rate \\( x^{-(q+1)/p} \\): a heavier amplitude (larger \\( q \\)) speeds up the decay; setting \\( q=0 \\) recovers the basic result." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1 t^q\\cos(x t^p)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\Big(\\frac{q+1}{p}\\Big)\\cos\\!\\Big(\\frac{\\pi(q+1)}{2p}\\Big)\\,x^{-(q+1)/p} \\)",
      canonicalAnswer: "(1/p)*gamma((q+1)/p)*cos(pi*(q+1)/(2*p))*x^(-(q+1)/p)",
    },
  },
  {
    id: "am5d-025",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 25",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1} \\sqrt{t}\\,\\cos(x t^{2})\\,dt \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["algebraic amplitude", "Fresnel", "Gamma(3/4)"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Match to the general amplitude formula.", workingLatex: "q=\\frac12,\\quad p=2 \\;\\Rightarrow\\; s=\\frac{q+1}{p}=\\frac{3}{4}.", explanation: "Use the \\( t^q\\cos(x t^p) \\) result with \\( q=1/2 \\)." },
        { stepNumber: 2, description: "Substitute into the leading term.", workingLatex: "\\int_0^1 t^{1/2}\\cos(x t^2)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac34\\Big)\\cos\\!\\Big(\\frac{3\\pi}{8}\\Big)\\,x^{-3/4}.", explanation: "Insert \\( 1/p=1/2 \\), \\( s=3/4 \\), and \\( \\pi s/2=3\\pi/8 \\)." },
        { stepNumber: 3, description: "State the decay rate.", workingLatex: "\\int_0^1 \\sqrt{t}\\,\\cos(x t^2)\\,dt = O\\!\\big(x^{-3/4}\\big).", explanation: "The extra \\( \\sqrt t \\) suppresses the contribution near \\( t=0 \\), changing the rate from \\( x^{-1/2} \\) to \\( x^{-3/4} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1 \\sqrt{t}\\,\\cos(x t^2)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac34\\Big)\\cos\\!\\Big(\\frac{3\\pi}{8}\\Big)\\,x^{-3/4} \\)",
      canonicalAnswer: "(1/2)*gamma(3/4)*cos(3*pi/8)*x^(-3/4)",
    },
  },
  {
    id: "am5d-026",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 26",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "An integrable amplitude singularity at the stationary endpoint: find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1} t^{-1/2}\\cos(x t^{2})\\,dt \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["amplitude singularity", "Fresnel", "Gamma(1/4)"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Check integrability and set parameters.", workingLatex: "q=-\\frac12>-1\\ (\\text{integrable}),\\quad p=2 \\;\\Rightarrow\\; s=\\frac{q+1}{p}=\\frac{1}{4}.", explanation: "The \\( t^{-1/2} \\) singularity is integrable, and it strengthens the contribution from the flat phase at \\( t=0 \\)." },
        { stepNumber: 2, description: "Apply the general formula.", workingLatex: "\\int_0^1 t^{-1/2}\\cos(x t^2)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)\\,x^{-1/4}.", explanation: "Insert \\( s=1/4 \\) so \\( \\pi s/2=\\pi/8 \\)." },
        { stepNumber: 3, description: "Interpret the slower decay.", workingLatex: "x^{-1/4} \\gg x^{-1/2}.", explanation: "The amplitude singularity at the stationary point makes the decay slower than the plain Fresnel rate — the integrand is largest exactly where the phase is flat." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1 t^{-1/2}\\cos(x t^2)\\,dt \\sim \\frac12\\,\\Gamma\\!\\Big(\\frac14\\Big)\\cos\\!\\Big(\\frac{\\pi}{8}\\Big)\\,x^{-1/4} \\)",
      canonicalAnswer: "(1/2)*gamma(1/4)*cos(pi/8)*x^(-1/4)",
    },
  },
  {
    id: "am5d-027",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 27",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1} e^{-t}\\cos(x t^{2})\\,dt \\), where the smooth amplitude \\( e^{-t} \\) is non-zero at the stationary endpoint.",
    marks: 5,
    yearCreated: 2026,
    tags: ["smooth amplitude", "Fresnel", "amplitude at endpoint"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Localise at the stationary endpoint \\( t=0 \\).", workingLatex: "\\text{leading contribution from a neighbourhood of }t=0,\\quad e^{-t}\\to e^{0}=1.", explanation: "Where the phase is flat, only the value of the amplitude at that point matters at leading order; here \\( e^{-0}=1 \\)." },
        { stepNumber: 2, description: "Replace the amplitude by its endpoint value.", workingLatex: "\\int_0^1 e^{-t}\\cos(x t^2)\\,dt \\sim e^{0}\\int_0^{1}\\cos(x t^2)\\,dt.", explanation: "Corrections from the variation of \\( e^{-t} \\) (its derivative at \\( 0 \\)) enter at higher order in \\( x^{-1} \\)." },
        { stepNumber: 3, description: "Insert the Fresnel leading term.", workingLatex: "\\int_0^{1}\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Standard \\( p=2 \\) result." },
        { stepNumber: 4, description: "State the answer.", workingLatex: "\\int_0^1 e^{-t}\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "The smooth amplitude only rescales by its endpoint value (here \\( 1 \\)); the rate \\( x^{-1/2} \\) is unchanged." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1 e^{-t}\\cos(x t^2)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} \\)",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2)",
    },
  },
  {
    id: "am5d-028",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 28",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos\\!\\big(x\\,(t^{2}+t^{3})\\big)\\,dt \\), where the phase is \\( t^2+t^3 \\) (so \\( t^2 \\) dominates near \\( t=0 \\)).",
    marks: 6,
    yearCreated: 2026,
    tags: ["perturbed phase", "leading-order phase", "Fresnel"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compare the two phase terms near \\( t=0 \\).", workingLatex: "t^2 + t^3 = t^2\\big(1 + t\\big),\\qquad t\\to 0:\\ t^3 \\ll t^2.", explanation: "The leading-order behaviour of the integral is set by the lowest power in the phase, here \\( t^2 \\)." },
        { stepNumber: 2, description: "Estimate the width of the active region.", workingLatex: "x t^2 = O(1) \\;\\Rightarrow\\; t = O\\big(x^{-1/2}\\big) \\;\\Rightarrow\\; x t^3 = O\\big(x^{-1/2}\\big)\\to 0.", explanation: "On the coherent scale \\( t\\sim x^{-1/2} \\), the cubic correction to the phase is negligible, so it does not affect the leading term." },
        { stepNumber: 3, description: "Replace the phase by its leading monomial.", workingLatex: "\\int_0^1\\cos\\!\\big(x(t^2+t^3)\\big)\\,dt \\sim \\int_0^{\\infty}\\cos(x t^2)\\,dt.", explanation: "Extend to the half-line and drop the cubic term at leading order." },
        { stepNumber: 4, description: "Insert the Fresnel value.", workingLatex: "\\int_0^{\\infty}\\cos(x t^2)\\,dt = \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "The \\( p=2 \\) coefficient." },
        { stepNumber: 5, description: "State the leading behaviour.", workingLatex: "\\int_0^1\\cos\\!\\big(x(t^2+t^3)\\big)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Same leading term as a pure \\( t^2 \\) phase; the cubic enters only the correction." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos\\!\\big(x(t^2+t^3)\\big)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{8}}\\,x^{-1/2} \\)",
      canonicalAnswer: "sqrt(pi/8)*x^(-1/2)",
    },
  },
  {
    id: "am5d-029",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 29",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Two competing endpoints: find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos\\!\\big(x\\,t^{2}(1-t)^{2}\\big)\\,dt \\), where the phase \\( t^2(1-t)^2 \\) is flat at both \\( t=0 \\) and \\( t=1 \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["two stationary endpoints", "symmetry", "Fresnel", "competing contributions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the symmetry of the phase.", workingLatex: "\\psi(t)=t^2(1-t)^2,\\qquad \\psi(1-t)=\\psi(t).", explanation: "The phase is symmetric about \\( t=1/2 \\); the two flat endpoints \\( t=0 \\) and \\( t=1 \\) give equal contributions." },
        { stepNumber: 2, description: "Behaviour near \\( t=0 \\).", workingLatex: "t\\to 0:\\ \\psi(t)=t^2(1-t)^2 \\sim t^2.", explanation: "Near \\( 0 \\), \\( (1-t)^2\\to 1 \\), so the phase looks like a pure quadratic \\( t^2 \\) — a Fresnel endpoint." },
        { stepNumber: 3, description: "Contribution of the \\( t=0 \\) endpoint.", workingLatex: "\\int_{0}\\cos(x t^2)\\,dt \\to \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Half-Fresnel from the lower endpoint (one-sided, so the full half-line value \\( \\sqrt{\\pi/8}\\,x^{-1/2} \\))." },
        { stepNumber: 4, description: "Add the equal contribution from \\( t=1 \\).", workingLatex: "t\\to 1:\\ \\psi(t)\\sim (1-t)^2,\\quad \\text{same form} \\;\\Rightarrow\\; \\text{equal contribution } \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "By symmetry the upper endpoint is identical; the two are well separated (interior phase is non-stationary except at \\( t=1/2 \\), where \\( \\psi'(1/2)=0 \\) but \\( \\psi \\) is a maximum giving an oscillatory \\( O(x^{-1/2}) \\) term too — however it is the SAME order; we keep the two endpoint terms as the symmetric leading contribution and note the interior point contributes at the same order)." },
        { stepNumber: 5, description: "Sum the two endpoint contributions.", workingLatex: "\\int_0^1\\cos\\!\\big(x t^2(1-t)^2\\big)\\,dt \\sim 2\\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2} = \\sqrt{\\frac{\\pi}{2}}\\,x^{-1/2}.", explanation: "Both flat endpoints contribute at the slow rate \\( x^{-1/2} \\); summing gives the leading endpoint behaviour." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos\\!\\big(x t^2(1-t)^2\\big)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{2}}\\,x^{-1/2} \\) (equal \\( \\sqrt{\\pi/8}\\,x^{-1/2} \\) from each flat endpoint).",
    },
  },
  {
    id: "am5d-030",
    topicRef: "am5d",
    topicTitle: "Algebraic phases & fractional-power decay 30",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading large-\\( x \\) behaviour of \\( \\displaystyle\\int_0^{1}\\cos\\!\\big(x\\,(t^{2}-\\tfrac12)\\big)\\,dt \\), where the constant phase shift must be handled before extracting the fractional power.",
    marks: 6,
    yearCreated: 2026,
    tags: ["phase shift", "angle addition", "Fresnel", "real and imaginary parts"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pull out the constant phase.", workingLatex: "\\cos\\!\\big(x t^2 - \\tfrac{x}{2}\\big) = \\cos\\!\\Big(\\frac{x}{2}\\Big)\\cos(x t^2) + \\sin\\!\\Big(\\frac{x}{2}\\Big)\\sin(x t^2).", explanation: "Angle-addition turns the shifted phase into a fixed-coefficient combination of the cosine and sine algebraic-phase integrals." },
        { stepNumber: 2, description: "Integrate term by term.", workingLatex: "\\int_0^1\\cos\\!\\big(x(t^2-\\tfrac12)\\big)\\,dt = \\cos\\!\\Big(\\frac x2\\Big)\\!\\int_0^1\\!\\cos(x t^2)\\,dt + \\sin\\!\\Big(\\frac x2\\Big)\\!\\int_0^1\\!\\sin(x t^2)\\,dt.", explanation: "The constants \\( \\cos(x/2),\\sin(x/2) \\) come outside each integral." },
        { stepNumber: 3, description: "Insert the leading Fresnel terms.", workingLatex: "\\int_0^1\\cos(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2},\\qquad \\int_0^1\\sin(x t^2)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}.", explanation: "Both have the same leading coefficient \\( \\sqrt{\\pi/8} \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_0^1\\cos\\!\\big(x(t^2-\\tfrac12)\\big)\\,dt \\sim \\sqrt{\\frac{\\pi}{8}}\\,x^{-1/2}\\Big[\\cos\\!\\Big(\\frac x2\\Big) + \\sin\\!\\Big(\\frac x2\\Big)\\Big].", explanation: "Factor out the common amplitude." },
        { stepNumber: 5, description: "Compress with the harmonic-addition identity.", workingLatex: "\\cos\\theta+\\sin\\theta = \\sqrt2\\,\\cos\\!\\Big(\\theta-\\frac{\\pi}{4}\\Big),\\qquad \\theta=\\frac x2.", explanation: "Write the bracket as a single cosine." },
        { stepNumber: 6, description: "State the leading behaviour.", workingLatex: "\\int_0^1\\cos\\!\\big(x(t^2-\\tfrac12)\\big)\\,dt \\sim \\sqrt{\\frac{\\pi}{4}}\\,x^{-1/2}\\,\\cos\\!\\Big(\\frac x2 - \\frac{\\pi}{4}\\Big).", explanation: "Since \\( \\sqrt2\\cdot\\sqrt{\\pi/8}=\\sqrt{\\pi/4} \\); the constant phase shift becomes an \\( x \\)-dependent oscillation in the prefactor, but the decay rate is still \\( x^{-1/2} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^1\\cos\\!\\big(x(t^2-\\tfrac12)\\big)\\,dt \\sim \\sqrt{\\dfrac{\\pi}{4}}\\,x^{-1/2}\\,\\cos\\!\\Big(\\frac x2 - \\frac{\\pi}{4}\\Big) \\)",
      canonicalAnswer: "sqrt(pi/4)*x^(-1/2)*cos(x/2 - pi/4)",
    },
  },
];
