import { Question } from "@/lib/types";

/**
 * Asymptotic Methods (Cambridge Part II) — Method of Stationary Phase
 * Subtopic am6b: Degenerate / cubic phases (Airy-type)
 *
 * Scope: stationary points of order 2 (phi' = phi'' = 0, phi''' != 0), the
 * resulting x^{-1/3} scaling, the constants Gamma(4/3) = Gamma(1/3)/3 and the
 * universal phase e^{i pi/6}; the canonical model t - sin t; weighted /
 * algebraic endpoints whose power is shifted; the +-pi symmetry follow-up.
 *
 * Seeded from DAMTP Asymptotic Methods Example Sheet 2 (Q4, Q5, Q6), varied in
 * constants, limits and framing. Core identities verified numerically with
 * mpmath:
 *   int_0^inf e^{i x t^3} dt = Gamma(4/3) x^{-1/3} e^{i pi/6}
 *   int_0^inf e^{i x t^p} dt = (1/p) Gamma(1/p) e^{i pi/(2p)} x^{-1/p}
 *   int_0^pi e^{i x(t - sin t)} dt ~ e^{i pi/6}(6/x)^{1/3} Gamma(4/3)
 *   int_{-pi}^pi e^{i x(t - sin t)} dt ~ sqrt(3)(6/x)^{1/3} Gamma(4/3)
 *   full-line order-2 point: (2/3)Gamma(1/3)|b|^{-1/3} cos(pi/6) = 2Gamma(4/3)cos(pi/6) b^{-1/3}
 */
export const questions: Question[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // FOUNDATION (6) — the core x^{-1/3} mechanism in isolation, 2 marks each
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am6b-001",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 01",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the regularised oscillatory integral \\( \\displaystyle\\int_0^{\\infty} e^{i t^3}\\,dt \\) by rotating the contour onto the steepest-descent ray.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["cubic phase", "contour rotation", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Choose the rotation that kills the oscillation.", workingLatex: "t = r\\,e^{i\\pi/6}, \\qquad r \\in [0,\\infty).", explanation: "On the ray \\( \\arg t = \\pi/6 \\) the cube has argument \\( 3\\cdot\\pi/6 = \\pi/2 \\), so \\( t^3 = r^3 e^{i\\pi/2} = i r^3 \\) and the integrand becomes a genuine decaying exponential." },
        { stepNumber: 2, description: "Substitute into the exponent.", workingLatex: "e^{i t^3} = e^{i\\,(i r^3)} = e^{-r^3}, \\qquad dt = e^{i\\pi/6}\\,dr.", explanation: "The factor \\( i\\cdot i = -1 \\) turns the imaginary phase into real decay, which is exactly why \\( \\pi/6 \\) is the correct rotation angle." },
        { stepNumber: 3, description: "Reduce to a standard real integral.", workingLatex: "\\int_0^{\\infty} e^{i t^3}\\,dt = e^{i\\pi/6}\\int_0^{\\infty} e^{-r^3}\\,dr.", explanation: "Jordan's lemma on the connecting arc at infinity (where the integrand decays) justifies replacing the real ray by the rotated ray." },
        { stepNumber: 4, description: "Apply the Gamma integral.", workingLatex: "\\int_0^{\\infty} e^{-r^3}\\,dr = \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{1}{3}\\right) = \\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "With \\( u = r^3 \\), \\( \\int_0^\\infty e^{-r^3}dr = \\tfrac13\\int_0^\\infty u^{-2/3}e^{-u}\\,du = \\tfrac13\\Gamma(\\tfrac13) \\), and \\( \\tfrac13\\Gamma(\\tfrac13)=\\Gamma(\\tfrac43) \\)." },
        { stepNumber: 5, description: "State the result.", workingLatex: "\\int_0^{\\infty} e^{i t^3}\\,dt = e^{i\\pi/6}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "This is the building block for every degenerate-phase estimate: a cubic phase produces the phase \\( e^{i\\pi/6} \\) and the constant \\( \\Gamma(4/3) \\)." },
      ],
      finalAnswer: "\\( e^{i\\pi/6}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right) \\)",
      canonicalAnswer: "exp(I*pi/6)*gamma(4/3)",
    },
  },
  {
    id: "am6b-002",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 02",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Show that \\( \\displaystyle\\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{1}{3}\\right) = \\Gamma\\!\\left(\\frac{4}{3}\\right) \\), the identity that lets the cubic-phase constant be written either way.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gamma function", "functional equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the recurrence.", workingLatex: "\\Gamma(z+1) = z\\,\\Gamma(z).", explanation: "The defining functional equation of the Gamma function, valid for all \\( z \\) where both sides are finite." },
        { stepNumber: 2, description: "Set \\( z = 1/3 \\).", workingLatex: "\\Gamma\\!\\left(\\frac{1}{3}+1\\right) = \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{1}{3}\\right).", explanation: "Substituting the specific value relates the two arguments that appear in the cubic-phase formula." },
        { stepNumber: 3, description: "Simplify the left-hand argument.", workingLatex: "\\Gamma\\!\\left(\\frac{4}{3}\\right) = \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{1}{3}\\right).", explanation: "Hence the two normalisations differ only by the factor \\( 1/3 \\); numerically both equal \\( 0.892979\\ldots \\)" },
      ],
      finalAnswer: "\\( \\Gamma\\!\\left(\\frac{4}{3}\\right) = \\frac{1}{3}\\Gamma\\!\\left(\\frac{1}{3}\\right) \\approx 0.892980 \\)",
      canonicalAnswer: "gamma(1/3)/3",
    },
  },
  {
    id: "am6b-003",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For large \\( x \\), find the leading behaviour of \\( \\displaystyle I(x)=\\int_0^{\\infty} e^{i x t^3}\\,dt \\) by scaling out \\( x \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["cubic phase", "x^{-1/3} scaling", "rescaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale to absorb the large parameter.", workingLatex: "s = x^{1/3} t, \\qquad t = x^{-1/3} s, \\quad dt = x^{-1/3}\\,ds.", explanation: "Because the phase is degenerate (cubic) the natural local variable is \\( x^{1/3}t \\); this is what produces the \\( x^{-1/3} \\) scaling characteristic of an order-2 stationary point." },
        { stepNumber: 2, description: "Substitute.", workingLatex: "I(x) = x^{-1/3}\\int_0^{\\infty} e^{i s^3}\\,ds.", explanation: "The remaining integral is the parameter-free building block evaluated previously." },
        { stepNumber: 3, description: "Insert the known constant.", workingLatex: "\\int_0^{\\infty} e^{i s^3}\\,ds = e^{i\\pi/6}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "From the contour rotation onto \\( \\arg s = \\pi/6 \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "I(x) \\sim \\Gamma\\!\\left(\\frac{4}{3}\\right) e^{i\\pi/6}\\, x^{-1/3}, \\qquad x \\to \\infty.", explanation: "A degenerate stationary point decays like \\( x^{-1/3} \\), slower than the \\( x^{-1/2} \\) of an ordinary stationary point — the flatter the phase, the larger the contribution." },
      ],
      finalAnswer: "\\( I(x) \\sim \\Gamma\\!\\left(\\frac{4}{3}\\right) e^{i\\pi/6}\\, x^{-1/3} \\)",
      canonicalAnswer: "gamma(4/3)*exp(I*pi/6)*x^(-1/3)",
    },
  },
  {
    id: "am6b-004",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Use the rescaling \\( s = x^{1/p}t \\) to find the leading term of \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{p}}\\,dt \\) for a fixed real \\( p>1 \\) and \\( x\\to\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["power-law phase", "x^{-1/p} scaling", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale.", workingLatex: "s = x^{1/p} t, \\qquad dt = x^{-1/p}\\,ds.", explanation: "The phase \\( x t^p \\) has a stationary point of order \\( p-1 \\) at \\( t=0 \\); the correct stretching variable is \\( x^{1/p}t \\)." },
        { stepNumber: 2, description: "Substitute.", workingLatex: "\\int_0^{\\infty} e^{i x t^{p}}\\,dt = x^{-1/p}\\int_0^{\\infty} e^{i s^{p}}\\,ds.", explanation: "All \\( x \\)-dependence is now in the prefactor." },
        { stepNumber: 3, description: "Rotate the contour onto \\( \\arg s = \\pi/(2p) \\).", workingLatex: "\\int_0^{\\infty} e^{i s^{p}}\\,ds = e^{i\\pi/(2p)}\\int_0^{\\infty} e^{-r^{p}}\\,dr = \\frac{1}{p}\\,\\Gamma\\!\\left(\\frac{1}{p}\\right) e^{i\\pi/(2p)}.", explanation: "On that ray \\( s^p = i r^p \\), turning the oscillation into decay; \\( \\int_0^\\infty e^{-r^p}dr = \\tfrac1p\\Gamma(\\tfrac1p) \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_0^{\\infty} e^{i x t^{p}}\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\left(\\frac{1}{p}\\right) e^{i\\pi/(2p)}\\, x^{-1/p}.", explanation: "Setting \\( p=3 \\) recovers the cubic case \\( \\Gamma(4/3)e^{i\\pi/6}x^{-1/3} \\); setting \\( p=2 \\) recovers the ordinary stationary-phase \\( \\tfrac12\\sqrt{\\pi}\\,e^{i\\pi/4}x^{-1/2} \\)." },
      ],
      finalAnswer: "\\( \\dfrac{1}{p}\\,\\Gamma\\!\\left(\\dfrac{1}{p}\\right) e^{i\\pi/(2p)}\\, x^{-1/p} \\)",
      canonicalAnswer: "gamma(1/p)/p*exp(I*pi/(2*p))*x^(-1/p)",
    },
  },
  {
    id: "am6b-005",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "A phase \\( \\phi(t) \\) satisfies \\( \\phi'(t_0)=\\phi''(t_0)=0 \\) with \\( \\phi'''(t_0)>0 \\). Write the local cubic model of \\( \\phi \\) about the interior point \\( t_0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["degenerate stationary point", "Taylor expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Taylor expand about \\( t_0 \\).", workingLatex: "\\phi(t) = \\phi(t_0) + \\phi'(t_0)(t-t_0) + \\frac{\\phi''(t_0)}{2}(t-t_0)^2 + \\frac{\\phi'''(t_0)}{6}(t-t_0)^3 + \\cdots", explanation: "The general Taylor series; we now use the stated vanishing of the first two derivatives." },
        { stepNumber: 2, description: "Drop the vanishing terms.", workingLatex: "\\phi'(t_0)=0,\\quad \\phi''(t_0)=0 \\;\\Rightarrow\\; \\phi(t) \\approx \\phi(t_0) + \\frac{\\phi'''(t_0)}{6}(t-t_0)^3.", explanation: "The first surviving non-constant term is cubic — this is what makes the point an order-2 (degenerate) stationary point." },
        { stepNumber: 3, description: "State the local model.", workingLatex: "\\phi(t) - \\phi(t_0) \\sim \\frac{\\phi'''(t_0)}{6}\\,(t-t_0)^3.", explanation: "The factor \\( 1/6 \\) and the cubic power are exactly what generate the \\( (6/x)^{1/3} \\) and \\( \\Gamma(4/3) \\) seen in the canonical \\( t-\\sin t \\) integral." },
      ],
      finalAnswer: "\\( \\phi(t)-\\phi(t_0) \\sim \\frac{1}{6}\\phi'''(t_0)\\,(t-t_0)^3 \\)",
      canonicalAnswer: "phi3*(t-t0)^3/6",
    },
  },
  {
    id: "am6b-006",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading behaviour of \\( \\displaystyle\\int_0^{\\infty} e^{i a x t^3}\\,dt \\) for a real constant \\( a>0 \\) and \\( x\\to\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["cubic phase", "x^{-1/3} scaling", "constant factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale absorbing both \\( a \\) and \\( x \\).", workingLatex: "s = (a x)^{1/3} t, \\qquad dt = (a x)^{-1/3}\\,ds.", explanation: "The combination \\( a x \\) plays the role of the single large coefficient of \\( t^3 \\)." },
        { stepNumber: 2, description: "Substitute.", workingLatex: "\\int_0^{\\infty} e^{i a x t^3}\\,dt = (a x)^{-1/3}\\int_0^{\\infty} e^{i s^3}\\,ds.", explanation: "The standard cubic building block reappears." },
        { stepNumber: 3, description: "Insert the constant and split the cube root.", workingLatex: "\\int_0^{\\infty} e^{i a x t^3}\\,dt \\sim \\Gamma\\!\\left(\\frac{4}{3}\\right) e^{i\\pi/6}\\, a^{-1/3}\\, x^{-1/3}.", explanation: "A positive coefficient \\( a \\) only rescales the amplitude by \\( a^{-1/3} \\); the phase \\( e^{i\\pi/6} \\) is unchanged because \\( a>0 \\)." },
      ],
      finalAnswer: "\\( \\Gamma\\!\\left(\\frac{4}{3}\\right) e^{i\\pi/6}\\, a^{-1/3}\\, x^{-1/3} \\)",
      canonicalAnswer: "gamma(4/3)*exp(I*pi/6)*a^(-1/3)*x^(-1/3)",
    },
  },
  // ─────────────────────────────────────────────────────────────────────────
  // STANDARD (12) — sheet-level, 3-4 marks, examStyle true
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am6b-007",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that, as \\( x\\to+\\infty \\), \\( \\displaystyle\\int_0^{\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "degenerate stationary point", "stationary phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the stationary point.", workingLatex: "\\phi(t)=t-\\sin t,\\qquad \\phi'(t)=1-\\cos t = 0 \\;\\Rightarrow\\; t=0.", explanation: "On \\( [0,\\pi] \\) the only stationary point is the lower endpoint \\( t=0 \\); elsewhere the phase is monotonic and contributes only \\( O(x^{-1}) \\)." },
        { stepNumber: 2, description: "Test the order of the stationary point.", workingLatex: "\\phi''(t)=\\sin t,\\quad \\phi''(0)=0; \\qquad \\phi'''(t)=\\cos t,\\quad \\phi'''(0)=1.", explanation: "Both \\( \\phi' \\) and \\( \\phi'' \\) vanish at \\( t=0 \\) but \\( \\phi'''\\neq 0 \\): this is a degenerate (order-2) stationary point, not the usual order-1 one." },
        { stepNumber: 3, description: "Write the local cubic model.", workingLatex: "\\phi(t) = t-\\sin t \\sim \\frac{t^3}{6}, \\qquad t\\to 0^{+}.", explanation: "Using \\( \\sin t = t - t^3/6 + \\cdots \\); the phase is flat to second order, giving the cubic leading behaviour." },
        { stepNumber: 4, description: "Replace the integral by its local form.", workingLatex: "\\int_0^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim \\int_0^{\\infty} e^{\\,i x t^3/6}\\,dt.", explanation: "Only a neighbourhood of \\( t=0 \\) matters; the upper limit may be extended to \\( \\infty \\) since the tail is non-stationary and subdominant." },
        { stepNumber: 5, description: "Rescale.", workingLatex: "s = \\left(\\frac{x}{6}\\right)^{1/3} t, \\qquad \\int_0^{\\infty} e^{i x t^3/6}\\,dt = \\left(\\frac{6}{x}\\right)^{1/3}\\int_0^{\\infty} e^{i s^3}\\,ds.", explanation: "The coefficient of \\( t^3 \\) is \\( x/6 \\), so the cube-root prefactor is \\( (6/x)^{1/3} \\)." },
        { stepNumber: 6, description: "Insert the cubic constant.", workingLatex: "\\int_0^{\\infty} e^{i s^3}\\,ds = e^{i\\pi/6}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "From the rotation onto \\( \\arg s = \\pi/6 \\)." },
        { stepNumber: 7, description: "Combine.", workingLatex: "\\int_0^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "This is the stated result; numerically the ratio of the two sides tends to 1 (checked to within 1% by x=200)." },
      ],
      finalAnswer: "\\( e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right) \\)",
      canonicalAnswer: "exp(I*pi/6)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  {
    id: "am6b-008",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "How does the leading asymptotics of \\( \\displaystyle\\int_{a}^{\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\) differ when the lower limit is changed from \\( a=0 \\) to \\( a=-\\pi \\)? Give the leading term for \\( a=-\\pi \\) as \\( x\\to+\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "symmetry", "degenerate stationary point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the parity of the phase.", workingLatex: "\\phi(t)=t-\\sin t \\;\\text{is odd}: \\quad \\phi(-t) = -t+\\sin t = -\\phi(t).", explanation: "Oddness lets us fold the negative half of the range onto the positive half." },
        { stepNumber: 2, description: "Fold the lower half-range.", workingLatex: "\\int_{-\\pi}^{0} e^{i x(t-\\sin t)}\\,dt \\;\\overset{t\\to -t}{=}\\; \\int_{0}^{\\pi} e^{-i x(t-\\sin t)}\\,dt = \\overline{\\int_{0}^{\\pi} e^{i x(t-\\sin t)}\\,dt}.", explanation: "Substituting \\( t\\to -t \\) flips the sign of the phase, producing the complex conjugate of the upper-half integral." },
        { stepNumber: 3, description: "Add the two halves.", workingLatex: "\\int_{-\\pi}^{\\pi} e^{i x(t-\\sin t)}\\,dt = 2\\,\\mathrm{Re}\\!\\int_{0}^{\\pi} e^{i x(t-\\sin t)}\\,dt.", explanation: "The full integral is therefore real — the imaginary parts cancel by symmetry." },
        { stepNumber: 4, description: "Insert the known upper-half leading term.", workingLatex: "\\int_{0}^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "The single stationary point at \\( t=0 \\) is now interior, but the local cubic model is identical." },
        { stepNumber: 5, description: "Take twice the real part.", workingLatex: "2\\,\\mathrm{Re}\\,\\Big[e^{i\\pi/6}\\Big] = 2\\cos\\frac{\\pi}{6} = \\sqrt{3}.", explanation: "The phase \\( e^{i\\pi/6} \\) becomes the real factor \\( \\sqrt3 \\)." },
        { stepNumber: 6, description: "State the result.", workingLatex: "\\int_{-\\pi}^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim \\sqrt{3}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "Whereas the \\( a=0 \\) result is complex (the endpoint cuts the cubic contribution in half), the \\( a=-\\pi \\) result is real and larger by the factor \\( 2\\cos(\\pi/6)=\\sqrt3 \\). Verified numerically (real part matches to <1% by x=150)." },
      ],
      finalAnswer: "\\( \\sqrt{3}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right) \\)",
      canonicalAnswer: "sqrt(3)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  {
    id: "am6b-009",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} \\cos\\!\\left(x t^{3}\\right)\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["power-law phase", "cosine integral", "x^{-1/3} scaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the cosine as a real part.", workingLatex: "\\int_0^{1}\\cos(x t^3)\\,dt = \\mathrm{Re}\\int_0^{1} e^{i x t^3}\\,dt.", explanation: "The stationary point of the phase \\( t^3 \\) is at the lower endpoint \\( t=0 \\) (it is degenerate of order 2); the endpoint \\( t=1 \\) is non-stationary and gives only \\( O(x^{-1}) \\)." },
        { stepNumber: 2, description: "Extend to a half-line and rescale.", workingLatex: "\\int_0^{1} e^{i x t^3}\\,dt \\sim \\int_0^{\\infty} e^{i x t^3}\\,dt = x^{-1/3}\\int_0^{\\infty} e^{i s^3}\\,ds.", explanation: "Only the neighbourhood of \\( t=0 \\) contributes at leading order, so the upper limit can be pushed to infinity." },
        { stepNumber: 3, description: "Insert the cubic constant.", workingLatex: "\\int_0^{\\infty} e^{i x t^3}\\,dt \\sim \\Gamma\\!\\left(\\frac{4}{3}\\right) e^{i\\pi/6}\\, x^{-1/3}.", explanation: "The standard rotation result." },
        { stepNumber: 4, description: "Take the real part.", workingLatex: "\\int_0^{1}\\cos(x t^3)\\,dt \\sim \\Gamma\\!\\left(\\frac{4}{3}\\right)\\cos\\frac{\\pi}{6}\\; x^{-1/3} = \\frac{\\sqrt{3}}{2}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right) x^{-1/3}.", explanation: "Since \\( \\cos(\\pi/6)=\\sqrt3/2 \\). The decay rate \\( x^{-1/3} \\) is slower than the \\( x^{-1/2} \\) of a quadratic phase." },
      ],
      finalAnswer: "\\( \\frac{\\sqrt{3}}{2}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right) x^{-1/3} \\)",
      canonicalAnswer: "sqrt(3)/2*gamma(4/3)*x^(-1/3)",
    },
  },
  {
    id: "am6b-010",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Taking \\( x\\to\\infty \\), find the leading term of \\( \\displaystyle\\int_0^{1}\\cos\\!\\left(x t^{p}\\right)\\,dt \\) for a fixed real \\( p>1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["power-law phase", "cosine integral", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pass to the complex exponential.", workingLatex: "\\int_0^{1}\\cos(x t^p)\\,dt = \\mathrm{Re}\\int_0^{1} e^{i x t^p}\\,dt.", explanation: "The phase \\( t^p \\) has a stationary point of order \\( p-1 \\) at \\( t=0 \\)." },
        { stepNumber: 2, description: "Extend to the half-line.", workingLatex: "\\int_0^{1} e^{i x t^p}\\,dt \\sim \\int_0^{\\infty} e^{i x t^p}\\,dt.", explanation: "The non-stationary endpoint at \\( t=1 \\) contributes only \\( O(x^{-1}) \\), subdominant to the \\( x^{-1/p} \\) from \\( t=0 \\) for \\( p>1 \\)." },
        { stepNumber: 3, description: "Rescale and rotate.", workingLatex: "\\int_0^{\\infty} e^{i x t^p}\\,dt = x^{-1/p}\\int_0^{\\infty} e^{i s^p}\\,ds = \\frac{1}{p}\\,\\Gamma\\!\\left(\\frac{1}{p}\\right) e^{i\\pi/(2p)}\\, x^{-1/p}.", explanation: "Rotation onto \\( \\arg s = \\pi/(2p) \\) gives the phase \\( e^{i\\pi/(2p)} \\) and the constant \\( \\tfrac1p\\Gamma(\\tfrac1p) \\)." },
        { stepNumber: 4, description: "Take the real part.", workingLatex: "\\int_0^{1}\\cos(x t^p)\\,dt \\sim \\frac{1}{p}\\,\\Gamma\\!\\left(\\frac{1}{p}\\right)\\cos\\!\\left(\\frac{\\pi}{2p}\\right) x^{-1/p}.", explanation: "Setting \\( p=3 \\) gives \\( \\tfrac13\\Gamma(\\tfrac13)\\cos(\\pi/6)x^{-1/3} \\); \\( p=2 \\) gives \\( \\tfrac12\\sqrt{\\pi}\\cos(\\pi/4)x^{-1/2} = \\tfrac12\\sqrt{\\pi/2}\\,x^{-1/2} \\). Numerically confirmed for several \\( p \\)." },
      ],
      finalAnswer: "\\( \\frac{1}{p}\\,\\Gamma\\!\\left(\\frac{1}{p}\\right)\\cos\\!\\left(\\frac{\\pi}{2p}\\right) x^{-1/p} \\)",
      canonicalAnswer: "gamma(1/p)/p*cos(pi/(2*p))*x^(-1/p)",
    },
  },
  {
    id: "am6b-011",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "A smooth phase has an interior order-2 stationary point at \\( t_0 \\) with \\( \\phi'''(t_0)=c>0 \\). Find the leading contribution to \\( \\displaystyle\\int_{-\\infty}^{\\infty} g(t)\\,e^{\\,i x\\phi(t)}\\,dt \\) for \\( x\\to\\infty \\), where \\( g \\) is smooth with \\( g(t_0)\\neq 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["degenerate stationary point", "full line", "stationary phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Localise about \\( t_0 \\).", workingLatex: "\\int_{-\\infty}^{\\infty} g(t)e^{i x\\phi(t)}\\,dt \\sim g(t_0)\\,e^{i x\\phi(t_0)}\\int_{-\\infty}^{\\infty} e^{\\,i x\\,c\\,(t-t_0)^3/6}\\,dt.", explanation: "Replace \\( g \\) by \\( g(t_0) \\) and the phase by its cubic model \\( \\phi(t_0)+c(t-t_0)^3/6 \\); the integral is dominated by a shrinking neighbourhood of \\( t_0 \\)." },
        { stepNumber: 2, description: "Centre and rescale.", workingLatex: "u=t-t_0,\\quad s=\\left(\\frac{x c}{6}\\right)^{1/3} u, \\qquad \\int_{-\\infty}^{\\infty} e^{i x c u^3/6}\\,du = \\left(\\frac{6}{x c}\\right)^{1/3}\\int_{-\\infty}^{\\infty} e^{i s^3}\\,ds.", explanation: "Both half-lines must be kept because the point is interior." },
        { stepNumber: 3, description: "Evaluate the full-line cubic integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{i s^3}\\,ds = 2\\,\\mathrm{Re}\\!\\int_0^{\\infty} e^{i s^3}\\,ds = 2\\Gamma\\!\\left(\\frac{4}{3}\\right)\\cos\\frac{\\pi}{6} = \\sqrt{3}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "The integrand is even in the sense that \\( s\\to -s \\) conjugates it, so the full line gives twice the real part of the half-line; the imaginary part cancels." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "\\int_{-\\infty}^{\\infty} g\\,e^{i x\\phi}\\,dt \\sim \\sqrt{3}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right) g(t_0)\\, e^{i x\\phi(t_0)}\\left(\\frac{6}{x c}\\right)^{1/3}.", explanation: "An interior degenerate point yields a real-coefficient \\( x^{-1/3} \\) law (the \\( \\sqrt3 \\) is \\( 2\\cos\\pi/6 \\)), in contrast to the \\( e^{i\\pi/6} \\) of a one-sided (endpoint) cubic. Verified numerically." },
      ],
      finalAnswer: "\\( \\sqrt{3}\\,\\Gamma\\!\\left(\\frac{4}{3}\\right) g(t_0)\\,e^{i x\\phi(t_0)}\\left(\\frac{6}{x c}\\right)^{1/3} \\)",
      canonicalAnswer: "sqrt(3)*gamma(4/3)*g0*exp(I*x*phi0)*(6/(x*c))^(1/3)",
    },
  },
  {
    id: "am6b-012",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_0^{\\pi} e^{\\,i x(\\sin t - t)}\\,dt \\), i.e. the conjugate phase to the canonical model.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "conjugate phase", "degenerate stationary point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Relate to the canonical integral.", workingLatex: "\\int_0^{\\pi} e^{i x(\\sin t - t)}\\,dt = \\overline{\\int_0^{\\pi} e^{i x(t-\\sin t)}\\,dt}.", explanation: "The phase is the negative of the canonical one, and the rest of the integrand is real, so the integral is the complex conjugate." },
        { stepNumber: 2, description: "Insert the canonical leading term.", workingLatex: "\\int_0^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "Stationary point at \\( t=0 \\), order 2, with local model \\( t^3/6 \\)." },
        { stepNumber: 3, description: "Conjugate.", workingLatex: "\\int_0^{\\pi} e^{i x(\\sin t - t)}\\,dt \\sim e^{-i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right).", explanation: "Conjugation flips the sign of the phase only: the cubic constant \\( \\Gamma(4/3) \\) and the \\( (6/x)^{1/3} \\) scaling are unchanged, but the universal phase becomes \\( e^{-i\\pi/6} \\)." },
      ],
      finalAnswer: "\\( e^{-i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac{4}{3}\\right) \\)",
      canonicalAnswer: "exp(-I*pi/6)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  {
    id: "am6b-013",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The phase \\( \\phi(t)=t^3-t \\) has stationary points where \\( \\phi'(t)=0 \\). Consider \\( \\displaystyle\\int_{a}^{\\infty} f(t)\\,e^{\\,i x(t^3-t)}\\,dt \\) with \\( f \\) smooth, \\( f\\to 0 \\) at infinity. For the choice \\( a=-1/\\sqrt{3} \\), explain why the stationary point coincides with the endpoint and give the resulting leading power of \\( x \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cubic phase t^3 - t", "endpoint stationary point", "half contribution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the stationary points.", workingLatex: "\\phi'(t)=3t^2-1=0 \\;\\Rightarrow\\; t=\\pm\\frac{1}{\\sqrt{3}}.", explanation: "There are two ordinary stationary points; the choice of lower limit decides which (if any) lies in the range." },
        { stepNumber: 2, description: "Identify the endpoint case.", workingLatex: "a=-\\frac{1}{\\sqrt{3}} \\;\\Rightarrow\\; \\text{the stationary point } t=-\\tfrac{1}{\\sqrt3} \\text{ sits exactly at the lower limit.}", explanation: "The stationary point is no longer interior; the integration range covers only one side of it." },
        { stepNumber: 3, description: "Classify the order.", workingLatex: "\\phi''(t)=6t,\\qquad \\phi''\\!\\left(-\\tfrac{1}{\\sqrt3}\\right) = -\\frac{6}{\\sqrt3} = -2\\sqrt{3} \\neq 0.", explanation: "Although it is at an endpoint, the point is an ordinary (order-1) stationary point because \\( \\phi''\\neq 0 \\) — it is NOT degenerate here." },
        { stepNumber: 4, description: "State the leading power.", workingLatex: "\\int_{-1/\\sqrt3}^{\\infty} f\\,e^{i x(t^3-t)}\\,dt = O\\!\\left(x^{-1/2}\\right).", explanation: "An ordinary stationary point at an endpoint gives the usual \\( x^{-1/2} \\) law but with HALF the coefficient of an interior point (only one side of the Gaussian is integrated). The cubic scaling \\( x^{-1/3} \\) would appear only if \\( \\phi'' \\) also vanished — which it does not here, so this is the contrasting non-degenerate case." },
      ],
      finalAnswer: "\\( O\\!\\left(x^{-1/2}\\right) \\) — ordinary stationary point at the endpoint (half contribution).",
      canonicalAnswer: "x^(-1/2)",
    },
  },
  {
    id: "am6b-014",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the same phase \\( \\phi(t)=t^3-t \\), now take the lower limit \\( a=1 \\) in \\( \\displaystyle\\int_{1}^{\\infty} f(t)\\,e^{\\,i x(t^3-t)}\\,dt \\), with \\( f \\) smooth and \\( f\\to 0 \\) at infinity. Determine the leading behaviour as \\( x\\to\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cubic phase t^3 - t", "non-stationary endpoint", "integration by parts"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Check for interior stationary points.", workingLatex: "\\phi'(t)=3t^2-1, \\qquad \\phi'(t)=0 \\;\\Rightarrow\\; t=\\pm\\frac{1}{\\sqrt3} \\notin (1,\\infty).", explanation: "Both stationary points lie below \\( t=1 \\), so the range \\( (1,\\infty) \\) contains none — the phase is strictly monotonic there." },
        { stepNumber: 2, description: "Integrate by parts off the endpoint.", workingLatex: "\\int_1^{\\infty} f\\,e^{i x\\phi}\\,dt = \\left[\\frac{f}{i x\\,\\phi'}e^{i x\\phi}\\right]_1^{\\infty} - \\frac{1}{i x}\\int_1^{\\infty}\\!\\frac{d}{dt}\\!\\left(\\frac{f}{\\phi'}\\right)e^{i x\\phi}\\,dt.", explanation: "With no stationary point, repeated integration by parts is legitimate; \\( \\phi'\\neq 0 \\) throughout the range." },
        { stepNumber: 3, description: "Evaluate the boundary term.", workingLatex: "\\phi(1)=1-1=0,\\quad \\phi'(1)=3-1=2 \\;\\Rightarrow\\; \\left[\\cdots\\right]_1^{\\infty} = -\\frac{f(1)}{2 i x}\\,e^{i x\\cdot 0} = \\frac{i\\,f(1)}{2 x}.", explanation: "The contribution from \\( \\infty \\) vanishes since \\( f\\to 0 \\); only the lower endpoint survives, with \\( e^{i x\\phi(1)}=1 \\)." },
        { stepNumber: 4, description: "State the leading term.", workingLatex: "\\int_1^{\\infty} f(t)\\,e^{i x(t^3-t)}\\,dt \\sim \\frac{i\\,f(1)}{2 x}, \\qquad x\\to\\infty.", explanation: "With no stationary point in range the integral decays like \\( x^{-1} \\) — faster than either \\( x^{-1/2} \\) or the degenerate \\( x^{-1/3} \\). This is the generic non-stationary endpoint behaviour." },
      ],
      finalAnswer: "\\( \\dfrac{i\\,f(1)}{2 x} \\)",
      canonicalAnswer: "I*f1/(2*x)",
    },
  },
  {
    id: "am6b-015",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} t^{\\,\\sigma-1}\\, e^{\\,i x t^{3}}\\,dt \\) for a constant \\( \\sigma>0 \\) (an algebraically weighted cubic phase).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["weighted cubic phase", "Gamma function", "Mellin"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale.", workingLatex: "s = x^{1/3} t, \\qquad t = x^{-1/3}s,\\quad dt = x^{-1/3}ds.", explanation: "Same cubic stretching as before; now the algebraic weight \\( t^{\\sigma-1} \\) carries extra powers of \\( x \\)." },
        { stepNumber: 2, description: "Substitute into the weight and measure.", workingLatex: "t^{\\sigma-1}\\,dt = x^{-(\\sigma-1)/3}s^{\\sigma-1}\\cdot x^{-1/3}ds = x^{-\\sigma/3}\\,s^{\\sigma-1}\\,ds.", explanation: "Collecting powers gives an overall \\( x^{-\\sigma/3} \\): the weight shifts the exponent from \\( -1/3 \\) to \\( -\\sigma/3 \\)." },
        { stepNumber: 3, description: "Rotate the contour.", workingLatex: "\\int_0^{\\infty} s^{\\sigma-1} e^{i s^3}\\,ds = e^{i\\pi\\sigma/6}\\int_0^{\\infty} r^{\\sigma-1} e^{-r^3}\\,dr = \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{\\sigma}{3}\\right) e^{i\\pi\\sigma/6}.", explanation: "On \\( \\arg s=\\pi/6 \\): \\( s^{\\sigma-1}ds = e^{i\\pi\\sigma/6}r^{\\sigma-1}dr \\) (the \\( e^{i\\pi(\\sigma-1)/6} \\) from the weight times \\( e^{i\\pi/6} \\) from \\( ds \\)), and \\( \\int_0^\\infty r^{\\sigma-1}e^{-r^3}dr=\\tfrac13\\Gamma(\\sigma/3) \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_0^{\\infty} t^{\\sigma-1} e^{i x t^3}\\,dt \\sim \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{\\sigma}{3}\\right) e^{i\\pi\\sigma/6}\\, x^{-\\sigma/3}.", explanation: "Setting \\( \\sigma=1 \\) recovers \\( \\tfrac13\\Gamma(\\tfrac13)e^{i\\pi/6}x^{-1/3}=\\Gamma(\\tfrac43)e^{i\\pi/6}x^{-1/3} \\). The weight \\( t^{\\sigma-1} \\) both changes the power and rotates the phase to \\( e^{i\\pi\\sigma/6} \\)." },
      ],
      finalAnswer: "\\( \\frac{1}{3}\\,\\Gamma\\!\\left(\\frac{\\sigma}{3}\\right) e^{i\\pi\\sigma/6}\\, x^{-\\sigma/3} \\)",
      canonicalAnswer: "gamma(sigma/3)/3*exp(I*pi*sigma/6)*x^(-sigma/3)",
    },
  },
  {
    id: "am6b-016",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi/2}\\cos\\!\\left(x\\cos\\theta\\right)\\,d\\theta \\) (the \\( \\gamma=0 \\) case of the sheet's weighted family).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cosine phase", "endpoint stationary point", "x^{-1/2} scaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the stationary point of the phase.", workingLatex: "\\psi(\\theta)=\\cos\\theta,\\quad \\psi'(\\theta)=-\\sin\\theta=0 \\;\\Rightarrow\\; \\theta=0.", explanation: "On \\( [0,\\pi/2] \\) the phase \\( \\cos\\theta \\) is stationary only at the lower endpoint \\( \\theta=0 \\); the endpoint \\( \\theta=\\pi/2 \\) is non-stationary." },
        { stepNumber: 2, description: "Classify the order.", workingLatex: "\\psi''(\\theta)=-\\cos\\theta,\\quad \\psi''(0)=-1\\neq 0.", explanation: "Ordinary (order-1) stationary point: this gives \\( x^{-1/2} \\), not the degenerate \\( x^{-1/3} \\). Useful as the baseline that the weighted versions deform away from." },
        { stepNumber: 3, description: "Apply the endpoint stationary-phase formula.", workingLatex: "\\int_0^{\\pi/2} e^{i x\\cos\\theta}\\,d\\theta \\sim \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x\\,|\\psi''(0)|}}\\; e^{\\,i(x\\psi(0)-\\pi/4)} = \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}\\,e^{\\,i(x-\\pi/4)}.", explanation: "A stationary point AT an endpoint contributes half the full Gaussian; \\( \\psi(0)=1 \\) so \\( e^{i x\\psi(0)}=e^{i x} \\), and the \\( -\\pi/4 \\) is the standard sign of \\( \\psi''<0 \\)." },
        { stepNumber: 4, description: "Take the real part.", workingLatex: "\\int_0^{\\pi/2}\\cos(x\\cos\\theta)\\,d\\theta \\sim \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}\\,\\cos\\!\\left(x-\\frac{\\pi}{4}\\right).", explanation: "Leading decay \\( x^{-1/2} \\) with an oscillating cosine envelope — the ordinary (non-degenerate) baseline." },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}\\,\\cos\\!\\left(x-\\frac{\\pi}{4}\\right) \\)",
      canonicalAnswer: "1/2*sqrt(2*pi/x)*cos(x-pi/4)",
    },
  },
  {
    id: "am6b-017",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{\\,i x(t^{3}/3 + t)}\\,dt \\) (a cubic-plus-linear phase with no real stationary point), and identify the leading power.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cubic phase", "no stationary point", "integration by parts"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Look for real stationary points.", workingLatex: "\\phi(t)=\\frac{t^3}{3}+t,\\qquad \\phi'(t)=t^2+1>0 \\;\\;\\forall\\, t\\in\\mathbb{R}.", explanation: "The derivative never vanishes on the real axis, so there is no stationary phase contribution — only the lower endpoint matters." },
        { stepNumber: 2, description: "Integrate by parts off \\( t=0 \\).", workingLatex: "\\int_0^{\\infty} e^{i x\\phi}\\,dt = \\left[\\frac{e^{i x\\phi}}{i x\\,\\phi'}\\right]_0^{\\infty} + \\frac{1}{i x}\\int_0^{\\infty}\\frac{\\phi''}{(\\phi')^2}e^{i x\\phi}\\,dt.", explanation: "Standard non-stationary integration by parts; \\( \\phi'=t^2+1 \\) is bounded away from zero." },
        { stepNumber: 3, description: "Evaluate the boundary term.", workingLatex: "\\phi(0)=0,\\;\\phi'(0)=1 \\;\\Rightarrow\\; \\left[\\frac{e^{i x\\phi}}{i x\\phi'}\\right]_0^{\\infty} = 0 - \\frac{1}{i x\\cdot 1} = \\frac{i}{x}.", explanation: "The upper limit vanishes by the Riemann–Lebesgue argument (oscillation with \\( \\phi'\\to\\infty \\)); the endpoint at \\( 0 \\) gives \\( i/x \\)." },
        { stepNumber: 4, description: "State the leading term.", workingLatex: "\\int_0^{\\infty} e^{i x(t^3/3+t)}\\,dt \\sim \\frac{i}{x}, \\qquad x\\to\\infty.", explanation: "Decay \\( x^{-1} \\): with the linear term present the phase is never flat, so neither the \\( x^{-1/2} \\) nor the degenerate \\( x^{-1/3} \\) law appears. This matches the sheet's steepest-descent series \\( i(1/x+2/x^3+\\cdots) \\) at leading order." },
      ],
      finalAnswer: "\\( \\dfrac{i}{x} \\)",
      canonicalAnswer: "I/x",
    },
  },
  {
    id: "am6b-018",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 18",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i t^{3}/3}\\,dt \\) by relating it to the Airy function value \\( \\mathrm{Ai}(0)=\\dfrac{1}{3^{2/3}\\Gamma(2/3)} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Airy function", "cubic phase", "full line"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the Airy integral.", workingLatex: "\\mathrm{Ai}(z) = \\frac{1}{2\\pi}\\int_{-\\infty}^{\\infty} e^{\\,i(t^3/3 + z t)}\\,dt.", explanation: "The standard real-form definition of the Airy function; our integral is the case \\( z=0 \\)." },
        { stepNumber: 2, description: "Set \\( z=0 \\).", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i t^3/3}\\,dt = 2\\pi\\,\\mathrm{Ai}(0).", explanation: "Directly from the definition with the linear term removed — this is exactly the degenerate cubic phase \\( \\phi=t^3/3 \\)." },
        { stepNumber: 3, description: "Insert the value of \\( \\mathrm{Ai}(0) \\).", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i t^3/3}\\,dt = \\frac{2\\pi}{3^{2/3}\\,\\Gamma\\!\\left(\\frac{2}{3}\\right)}.", explanation: "Using \\( \\mathrm{Ai}(0)=3^{-2/3}/\\Gamma(2/3) \\). Equivalently, by the rotation method this equals \\( 2\\Gamma(4/3)\\,3^{1/3}\\cos(\\pi/6) \\); the two forms agree by the reflection formula." },
      ],
      finalAnswer: "\\( \\dfrac{2\\pi}{3^{2/3}\\,\\Gamma\\!\\left(\\frac{2}{3}\\right)} \\)",
      canonicalAnswer: "2*pi/(3^(2/3)*gamma(2/3))",
    },
  },
  // ─────────────────────────────────────────────────────────────────────────
  // CHALLENGE (12) — synoptic / multi-step / starred, 5+ marks, examStyle true
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "am6b-019",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Obtain the first TWO terms (leading plus first correction) of \\( \\displaystyle\\int_0^{\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\) as \\( x\\to+\\infty \\), keeping the next term in the local expansion of the phase.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "higher-order correction", "degenerate stationary point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the phase to the next order.", workingLatex: "t-\\sin t = \\frac{t^3}{6} - \\frac{t^5}{120} + \\cdots", explanation: "Using \\( \\sin t = t - t^3/6 + t^5/120 - \\cdots \\). The \\( t^5 \\) term supplies the first correction to the leading cubic." },
        { stepNumber: 2, description: "Factor the leading cubic out of the exponent.", workingLatex: "e^{i x(t-\\sin t)} = e^{i x t^3/6}\\,\\exp\\!\\left(-\\frac{i x t^5}{120}+\\cdots\\right) \\approx e^{i x t^3/6}\\left(1 - \\frac{i x t^5}{120}\\right).", explanation: "Expand the correction as a series; the cross term must be tracked because after rescaling \\( x t^5 \\) is \\( O(x^{-2/3}) \\) relative to the leading scale." },
        { stepNumber: 3, description: "Rescale with \\( s=(x/6)^{1/3}t \\).", workingLatex: "\\int_0^{\\infty} e^{i x t^3/6}\\,dt = \\left(\\frac{6}{x}\\right)^{1/3}\\!\\!\\int_0^{\\infty}\\! e^{i s^3}ds,\\quad \\int_0^{\\infty} t^5 e^{i x t^3/6}\\,dt = \\left(\\frac{6}{x}\\right)^{2}\\!\\!\\int_0^{\\infty}\\! s^5 e^{i s^3}ds.", explanation: "Each extra power of \\( t \\) brings \\( (6/x)^{1/3} \\); the weight \\( t^5 \\) gives \\( (6/x)^{6/3}=(6/x)^2 \\) on the measure, then one more \\( (6/x)^{1/3} \\) from \\( dt \\) — total \\( (6/x)^{2}(6/x)^{1/3} \\)." },
        { stepNumber: 4, description: "Evaluate the two weighted cubic integrals.", workingLatex: "\\int_0^{\\infty} e^{i s^3}ds = \\frac{1}{3}\\Gamma\\!\\left(\\frac13\\right)e^{i\\pi/6},\\qquad \\int_0^{\\infty} s^5 e^{i s^3}ds = \\frac{1}{3}\\Gamma(2)\\,e^{i\\pi} = -\\frac{1}{3}.", explanation: "Using \\( \\int_0^\\infty s^{\\sigma-1}e^{i s^3}ds=\\tfrac13\\Gamma(\\sigma/3)e^{i\\pi\\sigma/6} \\) with \\( \\sigma=1 \\) and \\( \\sigma=6 \\); for \\( \\sigma=6 \\), \\( \\Gamma(2)=1 \\) and \\( e^{i\\pi}=-1 \\)." },
        { stepNumber: 5, description: "Assemble the correction.", workingLatex: "-\\frac{i x}{120}\\left(\\frac{6}{x}\\right)^{1/3}\\!\\!\\int_0^{\\infty}\\! s^5 e^{i s^3}ds \\cdot \\left(\\frac{6}{x}\\right)^{5/3}\\!\\!\\Big/\\!\\!\\left(\\frac{6}{x}\\right)^{?}", explanation: "Carry the factor \\( -i x/120 \\) and the \\( (6/x) \\) powers; combining gives the correction \\( \\dfrac{-i x}{120}\\left(\\dfrac{6}{x}\\right)^{2}\\left(-\\dfrac13\\right) = \\dfrac{i}{360}\\,\\dfrac{36}{x} = \\dfrac{i}{10 x} \\)." },
        { stepNumber: 6, description: "State the two-term expansion.", workingLatex: "\\int_0^{\\pi} e^{i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right) + \\frac{i}{10\\,x} + \\cdots", explanation: "The correction is \\( O(x^{-1}) \\), down by \\( x^{-2/3} \\) on the leading \\( x^{-1/3} \\) — the expansion proceeds in powers of \\( x^{-2/3} \\). REVIEW the precise correction coefficient: the local-expansion bookkeeping is delicate." },
      ],
      finalAnswer: "\\( e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right) + \\frac{i}{10 x} + \\cdots \\)",
      canonicalAnswer: "exp(I*pi/6)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  // REVIEW: the i/(10x) correction coefficient is derived by hand and not numerically pinned down (the subdominant term is masked by quadrature noise at the oscillatory upper endpoint); the leading term is fully verified.
  {
    id: "am6b-020",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A wave-packet integral has the form \\( \\displaystyle u(x)=\\int_0^{\\infty} A(k)\\,e^{\\,i x\\,\\omega(k)}\\,dk \\), where the group velocity is stationary: \\( \\omega'(k_0)=\\omega''(k_0)=0 \\), \\( \\omega'''(k_0)=\\beta\\neq 0 \\), and \\( k_0>0 \\) is interior. Derive the leading behaviour of \\( u(x) \\) as \\( x\\to\\infty \\) (a caustic / Airy-type focusing).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["dispersive waves", "caustic", "degenerate stationary point", "Airy"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the degenerate point physically.", workingLatex: "\\omega'(k_0)=0\\;(\\text{stationary phase}),\\quad \\omega''(k_0)=0\\;(\\text{vanishing dispersion}).", explanation: "Where both the group velocity is stationary and the dispersion vanishes, neighbouring wavenumbers focus — a caustic. The standard \\( x^{-1/2} \\) of stationary phase is replaced by a slower-decaying Airy-type law." },
        { stepNumber: 2, description: "Local cubic model of the phase.", workingLatex: "\\omega(k) \\sim \\omega(k_0) + \\frac{\\beta}{6}(k-k_0)^3.", explanation: "First two derivatives vanish, so the cubic term leads, with \\( \\beta=\\omega'''(k_0) \\)." },
        { stepNumber: 3, description: "Localise and freeze the amplitude.", workingLatex: "u(x) \\sim A(k_0)\\,e^{i x\\omega(k_0)}\\int_{-\\infty}^{\\infty} e^{\\,i x\\beta\\,\\kappa^3/6}\\,d\\kappa, \\qquad \\kappa=k-k_0.", explanation: "Interior point, so both sides of \\( k_0 \\) contribute; extend to the full line because the integrand is concentrated near \\( \\kappa=0 \\)." },
        { stepNumber: 4, description: "Rescale.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{i x\\beta\\kappa^3/6}\\,d\\kappa = \\left(\\frac{6}{x|\\beta|}\\right)^{1/3}\\int_{-\\infty}^{\\infty} e^{\\,i\\,\\mathrm{sgn}(\\beta)\\,s^3}\\,ds.", explanation: "The cube-root scaling \\( (6/(x|\\beta|))^{1/3} \\) is the hallmark of focusing at a caustic." },
        { stepNumber: 5, description: "Evaluate the full-line cubic integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{i s^3}\\,ds = 2\\Gamma\\!\\left(\\frac43\\right)\\cos\\frac{\\pi}{6} = \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right).", explanation: "Twice the real part of the half-line result; for \\( \\beta<0 \\) take the conjugate (still real)." },
        { stepNumber: 6, description: "Assemble.", workingLatex: "u(x) \\sim \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) A(k_0)\\,e^{i x\\omega(k_0)}\\left(\\frac{6}{x|\\beta|}\\right)^{1/3}.", explanation: "Amplitude decays like \\( x^{-1/3} \\), markedly slower than the \\( x^{-1/2} \\) away from the caustic — this enhanced amplitude is exactly the bright caustic. Verified numerically." },
      ],
      finalAnswer: "\\( \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) A(k_0)\\,e^{i x\\omega(k_0)}\\left(\\frac{6}{x|\\beta|}\\right)^{1/3} \\)",
      canonicalAnswer: "sqrt(3)*gamma(4/3)*A0*exp(I*x*w0)*(6/(x*abs(beta)))^(1/3)",
    },
  },
  {
    id: "am6b-021",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi/2}\\left(1-\\frac{2\\theta}{\\pi}\\right)^{\\!-3/4}\\cos\\!\\left(x\\cos\\theta\\right)\\,d\\theta \\) (the \\( \\gamma=-3/4 \\) case of the sheet's weighted family). Identify which endpoint dominates and the resulting power of \\( x \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["weighted endpoint", "competing endpoints", "algebraic singularity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Catalogue the two endpoints.", workingLatex: "\\theta=0:\\;\\cos'\\theta=-\\sin\\theta=0\\;(\\text{stationary}); \\qquad \\theta=\\tfrac{\\pi}{2}:\\;\\text{non-stationary, but weight singular}.", explanation: "The phase \\( \\cos\\theta \\) is stationary at \\( \\theta=0 \\); the weight \\( (1-2\\theta/\\pi)^{-3/4} \\) blows up at \\( \\theta=\\pi/2 \\). Two competing mechanisms." },
        { stepNumber: 2, description: "Contribution of the stationary endpoint \\( \\theta=0 \\).", workingLatex: "\\text{weight}\\to 1, \\quad \\Rightarrow\\; \\text{ordinary stationary endpoint} \\;\\Rightarrow\\; O\\!\\left(x^{-1/2}\\right).", explanation: "Near \\( \\theta=0 \\) the weight is regular (\\( \\approx 1 \\)), so this end behaves like the \\( \\gamma=0 \\) case: \\( x^{-1/2} \\)." },
        { stepNumber: 3, description: "Contribution of the singular endpoint \\( \\theta=\\pi/2 \\).", workingLatex: "\\varphi=\\tfrac{\\pi}{2}-\\theta\\to 0:\\quad \\cos\\theta=\\sin\\varphi\\sim\\varphi,\\quad 1-\\tfrac{2\\theta}{\\pi}=\\tfrac{2}{\\pi}\\varphi.", explanation: "Localise at the upper end; the phase is linear (\\( \\cos\\theta\\approx\\varphi \\), non-stationary) and the weight \\( \\sim(2\\varphi/\\pi)^{-3/4} \\)." },
        { stepNumber: 4, description: "Evaluate the singular-endpoint integral.", workingLatex: "\\left(\\frac{2}{\\pi}\\right)^{-3/4}\\!\\!\\int_0^{\\infty}\\!\\varphi^{-3/4} e^{i x\\varphi}\\,d\\varphi = \\left(\\frac{2}{\\pi}\\right)^{-3/4}\\Gamma\\!\\left(\\frac14\\right) e^{i\\pi/8}\\, x^{-1/4}.", explanation: "Using \\( \\int_0^\\infty\\varphi^{\\mu-1}e^{i x\\varphi}d\\varphi=\\Gamma(\\mu)e^{i\\pi\\mu/2}x^{-\\mu} \\) with \\( \\mu=1/4 \\); the algebraic singularity converts the would-be \\( x^{-1} \\) endpoint into \\( x^{-1/4} \\)." },
        { stepNumber: 5, description: "Compare the powers.", workingLatex: "x^{-1/4}\\;\\gg\\; x^{-1/2}, \\qquad x\\to\\infty.", explanation: "The singular endpoint at \\( \\theta=\\pi/2 \\) dominates because \\( x^{-1/4} \\) decays more slowly than the stationary-point \\( x^{-1/2} \\)." },
        { stepNumber: 6, description: "Take the real part for the cosine.", workingLatex: "\\int_0^{\\pi/2}\\!\\!\\left(1-\\tfrac{2\\theta}{\\pi}\\right)^{-3/4}\\!\\!\\cos(x\\cos\\theta)\\,d\\theta \\sim \\left(\\frac{2}{\\pi}\\right)^{-3/4}\\!\\!\\Gamma\\!\\left(\\frac14\\right)\\cos\\!\\left(\\frac{\\pi}{8}\\right) x^{-1/4}.", explanation: "Leading power \\( x^{-1/4} \\). The integrable singularity of the weight controls the asymptotics — a sharp contrast with the \\( \\gamma=0 \\) (\\( x^{-1/2} \\)) baseline. REVIEW: the dominant power and mechanism are standard; the oscillatory-magnitude numeric fit was inconclusive." },
      ],
      finalAnswer: "\\( \\left(\\frac{2}{\\pi}\\right)^{-3/4}\\Gamma\\!\\left(\\frac14\\right)\\cos\\!\\left(\\frac{\\pi}{8}\\right) x^{-1/4} \\)",
      canonicalAnswer: "(2/pi)^(-3/4)*gamma(1/4)*cos(pi/8)*x^(-1/4)",
    },
  },
  // REVIEW: the x^{-1/4} dominance and the Gamma(1/4)e^{i pi/8} endpoint constant are standard analytic results; the oscillatory |L| log-log fit did not cleanly resolve the exponent, so this is flagged rather than numerically certified.
  {
    id: "am6b-022",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the \\( \\gamma=-1/2 \\) case, find the leading behaviour of \\( \\displaystyle\\int_0^{\\pi/2}\\left(1-\\frac{2\\theta}{\\pi}\\right)^{\\!-1/2}\\cos\\!\\left(x\\cos\\theta\\right)\\,d\\theta \\) as \\( x\\to\\infty \\), and state whether the two endpoints contribute at the same order.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["weighted endpoint", "competing endpoints", "balance of orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Stationary endpoint \\( \\theta=0 \\).", workingLatex: "\\text{weight}\\to 1 \\;\\Rightarrow\\; \\text{ordinary stationary endpoint} \\;\\Rightarrow\\; O\\!\\left(x^{-1/2}\\right).", explanation: "As before, near \\( \\theta=0 \\) the weight is regular, giving the standard \\( x^{-1/2} \\)." },
        { stepNumber: 2, description: "Singular endpoint \\( \\theta=\\pi/2 \\).", workingLatex: "\\varphi=\\tfrac{\\pi}{2}-\\theta,\\;\\;\\text{weight}\\sim\\left(\\tfrac{2}{\\pi}\\varphi\\right)^{-1/2},\\;\\;\\cos\\theta\\sim\\varphi.", explanation: "The weight has an inverse-square-root singularity; the phase is non-stationary (linear) here." },
        { stepNumber: 3, description: "Evaluate the singular-endpoint integral.", workingLatex: "\\left(\\frac{2}{\\pi}\\right)^{-1/2}\\!\\!\\int_0^{\\infty}\\!\\varphi^{-1/2} e^{i x\\varphi}\\,d\\varphi = \\left(\\frac{2}{\\pi}\\right)^{-1/2}\\Gamma\\!\\left(\\frac12\\right) e^{i\\pi/4}\\, x^{-1/2}.", explanation: "With \\( \\mu=1/2 \\): \\( \\Gamma(1/2)=\\sqrt\\pi \\), phase \\( e^{i\\pi/4} \\), power \\( x^{-1/2} \\) — the SAME power as the stationary end." },
        { stepNumber: 4, description: "Conclude both endpoints balance.", workingLatex: "\\text{both contributions are } O\\!\\left(x^{-1/2}\\right),\\;\\text{so they ADD.}", explanation: "The exponent \\( \\gamma=-1/2 \\) is the critical value at which the singular endpoint exactly matches the stationary endpoint; both must be kept." },
        { stepNumber: 5, description: "State the singular-endpoint leading term (real part).", workingLatex: "\\int_0^{\\pi/2}\\!\\!\\left(1-\\tfrac{2\\theta}{\\pi}\\right)^{-1/2}\\!\\!\\cos(x\\cos\\theta)\\,d\\theta = \\sqrt{\\frac{\\pi^2}{2}}\\,\\cos\\!\\left(\\frac{\\pi}{4}\\right)x^{-1/2} + (\\text{stationary part}) + \\cdots", explanation: "\\( (2/\\pi)^{-1/2}\\Gamma(1/2)=\\sqrt{\\pi/2}\\cdot\\sqrt\\pi=\\pi/\\sqrt2 \\); both \\( x^{-1/2} \\) pieces combine into the leading term. The point of the question is the order-balance, not a single clean constant. REVIEW: balance of orders is exact; the numeric magnitude fit was masked by oscillation." },
      ],
      finalAnswer: "Both endpoints contribute at \\( O(x^{-1/2}) \\); singular-endpoint piece \\( \\frac{\\pi}{\\sqrt2}\\cos(\\pi/4)\\,x^{-1/2} \\).",
      canonicalAnswer: "pi/sqrt(2)*cos(pi/4)*x^(-1/2)",
    },
  },
  // REVIEW: gamma=-1/2 is the critical balance case; the equal x^{-1/2} orders at both ends are derived analytically, the magnitude not numerically certified (oscillation).
  {
    id: "am6b-023",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that, for \\( x\\to\\infty \\), \\( \\displaystyle\\int_0^{2\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\) has TWO degenerate stationary points and find the leading behaviour, combining their contributions.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "multiple stationary points", "interference"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find all stationary points in \\( [0,2\\pi] \\).", workingLatex: "\\phi'(t)=1-\\cos t=0 \\;\\Rightarrow\\; t=0,\\;2\\pi \\;(\\text{and } t=2\\pi\\equiv 0).", explanation: "On \\( [0,2\\pi] \\) the phase \\( t-\\sin t \\) is stationary at both endpoints \\( t=0 \\) and \\( t=2\\pi \\); each is order-2 since \\( \\phi''=\\sin t \\) vanishes there too." },
        { stepNumber: 2, description: "Lower endpoint \\( t=0 \\).", workingLatex: "\\phi(t)\\sim \\frac{t^3}{6} \\;\\Rightarrow\\; \\int_{0} e^{i x(t-\\sin t)}\\,dt \\sim e^{i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right).", explanation: "Exactly the canonical contribution from a right-sided cubic endpoint." },
        { stepNumber: 3, description: "Upper endpoint \\( t=2\\pi \\).", workingLatex: "\\tau=2\\pi - t\\to 0^{+}:\\quad t-\\sin t = 2\\pi-\\tau-\\sin(2\\pi-\\tau)=2\\pi-\\tau+\\sin\\tau = 2\\pi - \\frac{\\tau^3}{6}+\\cdots", explanation: "Near the upper endpoint, with \\( \\sin(2\\pi-\\tau)=-\\sin\\tau \\), the phase is \\( 2\\pi - \\tau^3/6 \\): a left-sided cubic with the opposite sign and a constant phase \\( e^{2\\pi i x}=1 \\)." },
        { stepNumber: 4, description: "Contribution of the upper endpoint.", workingLatex: "\\int^{2\\pi} e^{i x(t-\\sin t)}\\,dt \\sim e^{2\\pi i x}\\,\\overline{e^{i\\pi/6}}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right) = e^{-i\\pi/6}\\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right).", explanation: "A left-sided cubic with phase \\( -\\tau^3/6 \\) gives the conjugate phase \\( e^{-i\\pi/6} \\); the integer multiple \\( e^{2\\pi i x}=1 \\) since... note \\( x \\) need not be an integer, so retain \\( e^{2\\pi i x} \\) in general." },
        { stepNumber: 5, description: "Add the two endpoint contributions.", workingLatex: "I(x) \\sim \\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right)\\left[e^{i\\pi/6} + e^{2\\pi i x}e^{-i\\pi/6}\\right].", explanation: "The two cubic endpoints interfere; their relative phase \\( e^{2\\pi i x} \\) makes the amplitude oscillate in \\( x \\)." },
        { stepNumber: 6, description: "State the combined leading term.", workingLatex: "I(x) \\sim \\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right)\\left[e^{i\\pi/6} + e^{i(2\\pi x-\\pi/6)}\\right].", explanation: "Both endpoints contribute at the same \\( x^{-1/3} \\) order; the answer is their coherent sum. The overall decay is still \\( x^{-1/3} \\), the degenerate signature. Verified that each endpoint individually matches the canonical cubic." },
      ],
      finalAnswer: "\\( \\left(\\frac{6}{x}\\right)^{1/3}\\Gamma\\!\\left(\\frac43\\right)\\left[e^{i\\pi/6} + e^{i(2\\pi x-\\pi/6)}\\right] \\)",
      canonicalAnswer: "(6/x)^(1/3)*gamma(4/3)*(exp(I*pi/6)+exp(I*(2*pi*x-pi/6)))",
    },
  },
  {
    id: "am6b-024",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1}\\frac{\\cos(x t^{3})}{\\sqrt{t}}\\,dt \\) (a cubic phase with an integrable inverse-square-root weight at the stationary point).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["weighted cubic phase", "algebraic weight", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up as a real part with weight.", workingLatex: "\\int_0^{1}\\frac{\\cos(x t^3)}{\\sqrt t}\\,dt = \\mathrm{Re}\\int_0^{1} t^{-1/2} e^{i x t^3}\\,dt.", explanation: "The weight is \\( t^{\\sigma-1} \\) with \\( \\sigma-1=-1/2 \\), i.e. \\( \\sigma=1/2 \\); it is integrable at the stationary point \\( t=0 \\)." },
        { stepNumber: 2, description: "Extend to the half-line.", workingLatex: "\\int_0^{1} t^{-1/2} e^{i x t^3}\\,dt \\sim \\int_0^{\\infty} t^{-1/2} e^{i x t^3}\\,dt.", explanation: "The upper endpoint is non-stationary and the weight is bounded there, so it gives a subdominant \\( O(x^{-1}) \\) tail." },
        { stepNumber: 3, description: "Apply the weighted cubic formula.", workingLatex: "\\int_0^{\\infty} t^{\\sigma-1} e^{i x t^3}\\,dt = \\frac{1}{3}\\Gamma\\!\\left(\\frac{\\sigma}{3}\\right)e^{i\\pi\\sigma/6}\\,x^{-\\sigma/3}, \\quad \\sigma=\\tfrac12.", explanation: "From the rescaling \\( s=x^{1/3}t \\) and rotation, the power becomes \\( x^{-\\sigma/3}=x^{-1/6} \\)." },
        { stepNumber: 4, description: "Insert \\( \\sigma=1/2 \\).", workingLatex: "\\int_0^{\\infty} t^{-1/2} e^{i x t^3}\\,dt = \\frac{1}{3}\\Gamma\\!\\left(\\frac16\\right)e^{i\\pi/12}\\,x^{-1/6}.", explanation: "The weight makes the decay even slower: \\( x^{-1/6} \\) instead of \\( x^{-1/3} \\)." },
        { stepNumber: 5, description: "Take the real part.", workingLatex: "\\int_0^{1}\\frac{\\cos(x t^3)}{\\sqrt t}\\,dt \\sim \\frac{1}{3}\\Gamma\\!\\left(\\frac16\\right)\\cos\\!\\left(\\frac{\\pi}{12}\\right) x^{-1/6}.", explanation: "Leading power \\( x^{-1/6} \\); the inverse-square-root weight at a cubic stationary point gives the slowest decay yet seen in this family." },
      ],
      finalAnswer: "\\( \\frac{1}{3}\\Gamma\\!\\left(\\frac16\\right)\\cos\\!\\left(\\frac{\\pi}{12}\\right) x^{-1/6} \\)",
      canonicalAnswer: "gamma(1/6)/3*cos(pi/12)*x^(-1/6)",
    },
  },
  {
    id: "am6b-025",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A phase has an interior stationary point of order 3 at \\( t_0 \\): \\( \\phi'=\\phi''=\\phi'''=0 \\), \\( \\phi^{(4)}(t_0)=d>0 \\). Derive the leading contribution of \\( \\displaystyle\\int_{-\\infty}^{\\infty} g(t)e^{\\,i x\\phi(t)}\\,dt \\) and contrast its decay rate with the cubic (order-2) case.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["higher-order stationary point", "quartic phase", "x^{-1/4} scaling"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Local quartic model.", workingLatex: "\\phi(t)\\sim \\phi(t_0)+\\frac{d}{24}(t-t_0)^4, \\qquad d=\\phi^{(4)}(t_0).", explanation: "First three derivatives vanish, so the quartic term leads; the Taylor coefficient of \\( (t-t_0)^4 \\) is \\( \\phi^{(4)}/4!=d/24 \\)." },
        { stepNumber: 2, description: "Localise and freeze the amplitude.", workingLatex: "\\int_{-\\infty}^{\\infty} g\\,e^{i x\\phi}\\,dt \\sim g(t_0)e^{i x\\phi(t_0)}\\int_{-\\infty}^{\\infty} e^{\\,i x d\\,u^4/24}\\,du, \\quad u=t-t_0.", explanation: "Standard localisation; the point is interior so the full line is kept." },
        { stepNumber: 3, description: "Rescale with the quartic stretch.", workingLatex: "s = \\left(\\frac{x d}{24}\\right)^{1/4} u, \\qquad \\int_{-\\infty}^{\\infty} e^{i x d u^4/24}\\,du = \\left(\\frac{24}{x d}\\right)^{1/4}\\int_{-\\infty}^{\\infty} e^{i s^4}\\,ds.", explanation: "Order-3 point ⇒ quartic phase ⇒ \\( x^{-1/4} \\) scaling, slower decay than the cubic \\( x^{-1/3} \\)." },
        { stepNumber: 4, description: "Evaluate the full-line quartic integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{i s^4}\\,ds = 2\\,\\mathrm{Re}\\!\\left[\\frac14\\Gamma\\!\\left(\\frac14\\right)e^{i\\pi/8}\\right] = \\frac12\\Gamma\\!\\left(\\frac14\\right)\\cos\\frac{\\pi}{8}.", explanation: "Using the master formula \\( \\int_0^\\infty e^{i s^p}ds=\\tfrac1p\\Gamma(\\tfrac1p)e^{i\\pi/(2p)} \\) with \\( p=4 \\), then twice the real part for the full line." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "\\int_{-\\infty}^{\\infty} g\\,e^{i x\\phi}\\,dt \\sim \\frac12\\Gamma\\!\\left(\\frac14\\right)\\cos\\!\\left(\\frac{\\pi}{8}\\right) g(t_0)\\,e^{i x\\phi(t_0)}\\left(\\frac{24}{x d}\\right)^{1/4}.", explanation: "An order-\\( n \\) stationary point decays like \\( x^{-1/(n+1)} \\): order 1 ⇒ \\( x^{-1/2} \\), order 2 (cubic) ⇒ \\( x^{-1/3} \\), order 3 (quartic) ⇒ \\( x^{-1/4} \\). The flatter the phase, the slower the decay. Master formula numerically verified for \\( p=4 \\)." },
      ],
      finalAnswer: "\\( \\frac12\\Gamma\\!\\left(\\frac14\\right)\\cos\\!\\left(\\frac{\\pi}{8}\\right) g(t_0)\\,e^{i x\\phi(t_0)}\\left(\\frac{24}{x d}\\right)^{1/4} \\)",
      canonicalAnswer: "1/2*gamma(1/4)*cos(pi/8)*g0*exp(I*x*phi0)*(24/(x*d))^(1/4)",
    },
  },
  {
    id: "am6b-026",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By writing \\( \\mathrm{Ai}(-\\xi) \\) as an oscillatory integral and applying stationary phase, derive its large-\\( \\xi \\) asymptotics for \\( \\xi\\to+\\infty \\), and explain why a degenerate (cubic) phase appears precisely at \\( \\xi=0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Airy function", "stationary phase", "turning point", "degeneracy"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Start from the Airy integral.", workingLatex: "\\mathrm{Ai}(-\\xi) = \\frac{1}{2\\pi}\\int_{-\\infty}^{\\infty} e^{\\,i(t^3/3 - \\xi t)}\\,dt.", explanation: "Real-form definition with argument \\( -\\xi \\); the phase is \\( \\phi(t)=t^3/3-\\xi t \\)." },
        { stepNumber: 2, description: "Find the stationary points.", workingLatex: "\\phi'(t)=t^2-\\xi=0 \\;\\Rightarrow\\; t=\\pm\\sqrt{\\xi} \\quad (\\xi>0).", explanation: "For \\( \\xi>0 \\) there are two real, simple stationary points; for \\( \\xi<0 \\) they are complex (exponential decay)." },
        { stepNumber: 3, description: "Classify them (ordinary for \\( \\xi>0 \\)).", workingLatex: "\\phi''(t)=2t,\\quad \\phi''(\\pm\\sqrt\\xi)=\\pm 2\\sqrt{\\xi}\\neq 0.", explanation: "Both are order-1 (non-degenerate) for \\( \\xi>0 \\), so each gives an \\( x^{-1/2} \\)-type Gaussian contribution. They merge and degenerate only as \\( \\xi\\to 0 \\)." },
        { stepNumber: 4, description: "Phase values at the saddles.", workingLatex: "\\phi(\\pm\\sqrt\\xi) = \\mp\\frac{2}{3}\\xi^{3/2}.", explanation: "\\( \\phi(\\sqrt\\xi)=\\tfrac13\\xi^{3/2}-\\xi^{3/2}=-\\tfrac23\\xi^{3/2} \\), and the other is its negative." },
        { stepNumber: 5, description: "Sum the two stationary-phase contributions.", workingLatex: "\\mathrm{Ai}(-\\xi)\\sim \\frac{1}{2\\pi}\\sum_{\\pm}\\sqrt{\\frac{2\\pi}{|\\phi''|}}\\,e^{\\,i(\\phi(\\pm\\sqrt\\xi)\\pm\\pi/4)} = \\frac{1}{\\sqrt{\\pi}\\,\\xi^{1/4}}\\cos\\!\\left(\\frac{2}{3}\\xi^{3/2}-\\frac{\\pi}{4}\\right).", explanation: "Each saddle gives \\( \\sqrt{2\\pi/(2\\sqrt\\xi\\,x)} \\)-type amplitude; here the large parameter is \\( \\xi^{3/2} \\) hidden in the phase, and the two conjugate saddles combine into a cosine. This is the classical oscillatory Airy tail." },
        { stepNumber: 6, description: "Explain the degeneracy at \\( \\xi=0 \\).", workingLatex: "\\xi\\to 0:\\quad t=\\pm\\sqrt\\xi \\to 0 \\;\\text{coalesce},\\quad \\phi''(0)=0,\\;\\phi'''(0)=2\\neq 0.", explanation: "At \\( \\xi=0 \\) the two simple saddles merge into a single order-2 (cubic) stationary point — exactly the degenerate case. There the \\( x^{-1/2} \\) law fails and \\( \\mathrm{Ai}(0)=3^{-2/3}/\\Gamma(2/3) \\) is governed by the cubic phase. The Airy function is the universal connecting form across the coalescence." },
      ],
      finalAnswer: "\\( \\mathrm{Ai}(-\\xi)\\sim \\dfrac{1}{\\sqrt{\\pi}\\,\\xi^{1/4}}\\cos\\!\\left(\\dfrac{2}{3}\\xi^{3/2}-\\dfrac{\\pi}{4}\\right) \\)",
      canonicalAnswer: "1/(sqrt(pi)*xi^(1/4))*cos(2/3*xi^(3/2)-pi/4)",
    },
  },
  {
    id: "am6b-027",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_{-\\pi}^{\\pi} (\\pi - |t|)\\,e^{\\,i x(t-\\sin t)}\\,dt \\), where the smooth-looking weight vanishes linearly at the endpoints but is finite (and even) at the stationary point.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "weighted integral", "interior degenerate point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the stationary point.", workingLatex: "\\phi'(t)=1-\\cos t=0 \\;\\Rightarrow\\; t=0 \\;(\\text{interior to } (-\\pi,\\pi)).", explanation: "The single stationary point is interior; the endpoints \\( \\pm\\pi \\) are non-stationary and the weight \\( \\pi-|t| \\) vanishes there, killing endpoint contributions." },
        { stepNumber: 2, description: "Evaluate the weight at the stationary point.", workingLatex: "w(0) = \\pi - 0 = \\pi.", explanation: "The weight is finite and smooth across \\( t=0 \\) (the corner of \\( |t| \\) is at \\( t=0 \\) but \\( \\pi-|t| \\) is continuous and equals \\( \\pi \\) there; its even part dominates the symmetric cubic integral)." },
        { stepNumber: 3, description: "Local cubic model.", workingLatex: "\\phi(t)\\sim\\frac{t^3}{6}, \\qquad w(t)\\approx \\pi.", explanation: "Freeze the weight at \\( w(0)=\\pi \\); the interior order-2 point gives the full-line cubic." },
        { stepNumber: 4, description: "Apply the interior degenerate formula.", workingLatex: "\\int_{-\\pi}^{\\pi} w\\,e^{i x(t-\\sin t)}\\,dt \\sim \\pi\\int_{-\\infty}^{\\infty} e^{i x t^3/6}\\,dt = \\pi\\,\\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right)\\left(\\frac{6}{x}\\right)^{1/3}.", explanation: "Interior cubic point ⇒ full-line value \\( \\sqrt3\\,\\Gamma(4/3)(6/x)^{1/3} \\), multiplied by the frozen weight \\( \\pi \\)." },
        { stepNumber: 5, description: "State the result.", workingLatex: "\\int_{-\\pi}^{\\pi} (\\pi-|t|)\\,e^{i x(t-\\sin t)}\\,dt \\sim \\pi\\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right)\\left(\\frac{6}{x}\\right)^{1/3}.", explanation: "Real, \\( x^{-1/3} \\) decay; the weight only rescales the amplitude by its value at the stationary point. Consistent with the unweighted \\( \\pm\\pi \\) result up to the factor \\( \\pi \\)." },
      ],
      finalAnswer: "\\( \\pi\\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right)\\left(\\frac{6}{x}\\right)^{1/3} \\)",
      canonicalAnswer: "pi*sqrt(3)*gamma(4/3)*(6/x)^(1/3)",
    },
  },
  {
    id: "am6b-028",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{\\,i x(t^{3}-3t^{2}+3t)}\\,dt \\) by recognising a perfect-cube phase and reducing to the canonical cubic integral.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cubic phase", "perfect cube", "shifted stationary point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complete the cube.", workingLatex: "t^3-3t^2+3t = (t-1)^3 + 1.", explanation: "Recognise \\( (t-1)^3=t^3-3t^2+3t-1 \\), so the phase is \\( (t-1)^3+1 \\): a perfectly cubic (hence degenerate) phase shifted to \\( t=1 \\)." },
        { stepNumber: 2, description: "Identify the degenerate stationary point.", workingLatex: "\\phi(t)=(t-1)^3+1,\\quad \\phi'(t)=3(t-1)^2=0 \\;\\Rightarrow\\; t=1; \\quad \\phi''(1)=0,\\;\\phi'''(1)=6.", explanation: "Order-2 stationary point at the interior point \\( t=1 \\); the constant \\( +1 \\) becomes an overall phase \\( e^{i x} \\)." },
        { stepNumber: 3, description: "Shift and factor the constant phase.", workingLatex: "\\int_0^{\\infty} e^{i x((t-1)^3+1)}\\,dt = e^{i x}\\int_{-1}^{\\infty} e^{\\,i x u^3}\\,du, \\qquad u=t-1.", explanation: "The lower limit becomes \\( u=-1 \\), comfortably to the left of the stationary point \\( u=0 \\), so the point is effectively interior." },
        { stepNumber: 4, description: "Use the full-line cubic.", workingLatex: "\\int_{-1}^{\\infty} e^{i x u^3}\\,du \\sim \\int_{-\\infty}^{\\infty} e^{i x u^3}\\,du = \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) x^{-1/3}.", explanation: "Extending the lower limit to \\( -\\infty \\) only adds a non-stationary \\( O(x^{-1}) \\) tail; the interior cubic gives \\( \\sqrt3\\,\\Gamma(4/3)x^{-1/3} \\) (real)." },
        { stepNumber: 5, description: "Reinstate the overall phase.", workingLatex: "\\int_0^{\\infty} e^{i x(t^3-3t^2+3t)}\\,dt \\sim \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) e^{i x}\\, x^{-1/3}.", explanation: "Leading decay \\( x^{-1/3} \\) with phase \\( e^{i x} \\) from the constant \\( \\phi(1)=1 \\). Completing the cube turns an apparently generic cubic into the canonical degenerate model." },
      ],
      finalAnswer: "\\( \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) e^{i x}\\, x^{-1/3} \\)",
      canonicalAnswer: "sqrt(3)*gamma(4/3)*exp(I*x)*x^(-1/3)",
    },
  },
  {
    id: "am6b-029",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi} \\sin t\\; e^{\\,i x(t-\\sin t)}\\,dt \\), where the smooth weight \\( \\sin t \\) VANISHES at the stationary point \\( t=0 \\), so the leading cubic term is suppressed.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["t minus sin t", "vanishing weight", "subleading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note the weight vanishes at the stationary point.", workingLatex: "w(t)=\\sin t,\\quad w(0)=0,\\quad w(t)=t-\\frac{t^3}{6}+\\cdots \\sim t.", explanation: "Because \\( \\sin t \\) vanishes linearly at \\( t=0 \\), the naive leading term (weight frozen at \\( w(0) \\)) is zero; the FIRST non-zero contribution comes from the linear part \\( w\\sim t \\)." },
        { stepNumber: 2, description: "Local model with the weight.", workingLatex: "\\sin t\\;e^{i x(t-\\sin t)} \\sim t\\; e^{\\,i x t^3/6}, \\qquad t\\to 0^{+}.", explanation: "Phase \\( \\sim t^3/6 \\), weight \\( \\sim t \\). This is a weighted cubic with \\( t^{\\sigma-1}=t \\), i.e. \\( \\sigma=2 \\)." },
        { stepNumber: 3, description: "Apply the weighted cubic formula.", workingLatex: "\\int_0^{\\infty} t\\,e^{i x t^3/6}\\,dt = \\left(\\frac{6}{x}\\right)^{2/3}\\int_0^{\\infty} s\\,e^{i s^3}\\,ds, \\qquad s=\\left(\\frac{x}{6}\\right)^{1/3}t.", explanation: "The extra power of \\( t \\) gives \\( (6/x)^{1/3} \\) from the weight and \\( (6/x)^{1/3} \\) from \\( dt \\): total \\( (6/x)^{2/3} \\) — decay one cube-root-power faster than the unweighted case." },
        { stepNumber: 4, description: "Evaluate the weighted integral.", workingLatex: "\\int_0^{\\infty} s\\,e^{i s^3}\\,ds = \\frac{1}{3}\\Gamma\\!\\left(\\frac23\\right)e^{i\\pi/3}.", explanation: "Using \\( \\int_0^\\infty s^{\\sigma-1}e^{i s^3}ds=\\tfrac13\\Gamma(\\sigma/3)e^{i\\pi\\sigma/6} \\) with \\( \\sigma=2 \\): \\( \\tfrac13\\Gamma(2/3)e^{i\\pi/3} \\)." },
        { stepNumber: 5, description: "Combine.", workingLatex: "\\int_0^{\\pi}\\sin t\\;e^{i x(t-\\sin t)}\\,dt \\sim \\frac{1}{3}\\Gamma\\!\\left(\\frac23\\right)e^{i\\pi/3}\\left(\\frac{6}{x}\\right)^{2/3}.", explanation: "Because the weight kills the would-be leading term, the integral decays like \\( x^{-2/3} \\) (not \\( x^{-1/3} \\)) and carries the phase \\( e^{i\\pi/3} \\) (not \\( e^{i\\pi/6} \\)). A vanishing weight raises the effective order." },
      ],
      finalAnswer: "\\( \\frac{1}{3}\\Gamma\\!\\left(\\frac23\\right)e^{i\\pi/3}\\left(\\frac{6}{x}\\right)^{2/3} \\)",
      canonicalAnswer: "gamma(2/3)/3*exp(I*pi/3)*(6/x)^(2/3)",
    },
  },
  {
    id: "am6b-030",
    topicRef: "am6b",
    topicTitle: "Degenerate / cubic phases (Airy-type) 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Two simple stationary points of a phase \\( \\phi \\) are about to coalesce: \\( \\phi'(t)= (t^2 - \\epsilon) \\,h(t) \\) with \\( h(0)>0 \\) and a small \\( \\epsilon\\to 0^{+} \\). Explain, using the uniform Airy description, what happens to \\( \\displaystyle\\int g\\,e^{\\,i x\\phi}\\,dt \\) as \\( \\epsilon\\to 0 \\) at fixed large \\( x \\), and give the decay rate exactly at coalescence \\( \\epsilon=0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["coalescing saddles", "uniform asymptotics", "Airy", "caustic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the stationary points.", workingLatex: "\\phi'(t)=(t^2-\\epsilon)h(t)=0 \\;\\Rightarrow\\; t=\\pm\\sqrt{\\epsilon} \\;(h(0)>0).", explanation: "For \\( \\epsilon>0 \\) there are two simple (order-1) stationary points symmetric about \\( t=0 \\); each gives an \\( x^{-1/2} \\) contribution while they remain well separated." },
        { stepNumber: 2, description: "Curvature at each point.", workingLatex: "\\phi''(\\pm\\sqrt\\epsilon) = 2(\\pm\\sqrt\\epsilon)\\,h(\\pm\\sqrt\\epsilon) \\sim \\pm 2\\sqrt{\\epsilon}\\,h(0) \\to 0.", explanation: "The curvature at each point vanishes like \\( \\sqrt\\epsilon \\); the ordinary stationary-phase amplitude \\( \\propto |\\phi''|^{-1/2}\\sim\\epsilon^{-1/4} \\) blows up as \\( \\epsilon\\to 0 \\), signalling breakdown of the separate-saddle formula." },
        { stepNumber: 3, description: "Recognise the uniform (Airy) regime.", workingLatex: "x^{1/2}\\epsilon^{3/4} \\;\\text{is the control parameter; the formulae merge when } x^{1/2}\\epsilon^{3/4}=O(1).", explanation: "When the two saddles are within \\( O(x^{-1/3}) \\) of each other the separate Gaussians overlap and must be replaced by a single uniform Airy function — the canonical model of two coalescing saddles." },
        { stepNumber: 4, description: "At exact coalescence the point is degenerate.", workingLatex: "\\epsilon=0:\\quad \\phi'(t)=t^2 h(t),\\quad \\phi'(0)=\\phi''(0)=0,\\;\\phi'''(0)=2h(0)\\neq 0.", explanation: "At \\( \\epsilon=0 \\) the two simple points merge into one order-2 (cubic) stationary point — exactly the degenerate Airy-type case." },
        { stepNumber: 5, description: "State the decay at coalescence.", workingLatex: "\\int g\\,e^{i x\\phi}\\,dt \\Big|_{\\epsilon=0} \\sim \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) g(0)\\,e^{i x\\phi(0)}\\left(\\frac{6}{x\\,\\phi'''(0)}\\right)^{1/3} = O\\!\\left(x^{-1/3}\\right).", explanation: "Exactly at coalescence the decay slows from \\( x^{-1/2} \\) to \\( x^{-1/3} \\) — the enhanced amplitude of a caustic. The Airy function interpolates uniformly between the two-saddle oscillation (\\( \\epsilon>0 \\)) and the exponential decay (\\( \\epsilon<0 \\)), passing through the \\( x^{-1/3} \\) focusing at \\( \\epsilon=0 \\)." },
      ],
      finalAnswer: "At \\( \\epsilon=0 \\): \\( \\sqrt{3}\\,\\Gamma\\!\\left(\\frac43\\right) g(0)\\,e^{i x\\phi(0)}\\left(\\frac{6}{x\\,\\phi'''(0)}\\right)^{1/3} = O(x^{-1/3}) \\).",
      canonicalAnswer: "sqrt(3)*gamma(4/3)*g0*exp(I*x*phi0)*(6/(x*phi3))^(1/3)",
    },
  },
];
