import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — § am7a
 * Method of Steepest Descent I: Saddle points & paths of steepest descent.
 * Ref: am7a
 *
 * 30 fully-worked questions on the geometry that underlies the saddle-point
 * method for integrals of the form
 *
 *   I(lambda) = \int_C g(z) e^{lambda h(z)} dz,   lambda -> +\infty,
 *
 * specifically: LOCATING saddle points (h'(z0)=0); the level lines of the
 * harmonic functions Re h and Im h through a saddle; distinguishing the
 * STEEPEST-DESCENT path (Im h = const, Re h decreasing away from z0) from the
 * steepest-ASCENT path (Im h = const, Re h increasing); the local descent
 * directions phi = (pi - arg h''(z0))/2 (and + pi); and the careful CHOICE OF
 * ROOT SIGN when parametrising the descent path / taking the square root of a
 * curvature.
 *
 * Conventions used throughout:
 *   - At a simple saddle, h(z) ~ h(z0) + (1/2) h''(z0) (z - z0)^2.
 *   - Write h''(z0) = |h''(z0)| e^{i alpha}. On a steepest path the increment
 *     (z - z0) = r e^{i phi} makes (1/2) h''(z0)(z-z0)^2 REAL:
 *       descent: 2 phi + alpha = pi  (so the quadratic is negative real),
 *       ascent : 2 phi + alpha = 0   (so the quadratic is positive real).
 *   - The leading saddle-point contribution along a descent path is
 *       I ~ g(z0) e^{lambda h(z0)} sqrt( 2 pi / (lambda |h''(z0)|) ) e^{i phi},
 *     with phi the descent direction the contour actually follows.
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 2
 * (Method of Steepest Descent, Q7, Q8, Q9, Q10), with phases, saddles and
 * limits varied. The saddle locations, level-line identities (Im h = const),
 * the descent/ascent angle convention and the leading-term formula were all
 * checked symbolically with sympy and numerically with mpmath:
 *   - Q7 seed:  Im(t + t^3/3) = 2/3 verified exactly on x = sqrt((2+y)/3y)(y-1).
 *   - Q10 seed: h = z - 2 z^{1/2} on z_+ = (1 + i tau)^2 gives h = -1 - tau^2
 *               (Im constant, Re strictly decreasing -> genuine descent);
 *               parabola y^2 = 4(1 - x).
 *   - Leading formula validated on real Gaussian int e^{-x t^2/2} dt = sqrt(2pi/x).
 *   - Descent/ascent angles cross-checked for h'' in {2, 2i, -2, 1+i, -3i, 6, -2}.
 */
export const questions: Question[] = [
  // ── Foundation: the core technique in isolation ─────────────────────────
  {
    id: "am7a-001",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 01",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the saddle point of \\( h(z) = z^2 - z \\), i.e. the point where \\( h'(z) = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["saddle point", "stationary point of phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "h'(z) = 2z - 1.", explanation: "A saddle point of the integrand \\( e^{\\lambda h(z)} \\) is a point where the exponent is locally stationary, so we set the derivative of \\( h \\) to zero." },
        { stepNumber: 2, description: "Set the derivative to zero.", workingLatex: "2z - 1 = 0 \\;\\implies\\; z_0 = \\tfrac{1}{2}.", explanation: "There is a single, simple root, so \\( h \\) has one simple saddle point. 'Simple' means \\( h''(z_0) \\neq 0 \\), which we confirm next." },
        { stepNumber: 3, description: "Confirm it is a simple saddle.", workingLatex: "h''(z) = 2, \\qquad h''(z_0) = 2 \\neq 0.", explanation: "Since \\( h'' \\) is non-zero at \\( z_0 \\), the point is a non-degenerate (order-one) saddle: locally \\( h(z) \\approx h(z_0) + (z - z_0)^2 \\)." },
      ],
      finalAnswer: "\\( z_0 = \\tfrac{1}{2} \\)",
      canonicalAnswer: "1/2",
    },
  },
  {
    id: "am7a-002",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 02",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find all saddle points of \\( h(z) = z^3 - 3z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["saddle point", "cubic phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate and set to zero.", workingLatex: "h'(z) = 3z^2 - 3 = 0 \\;\\implies\\; z^2 = 1.", explanation: "Saddle points are the zeros of \\( h' \\). A cubic phase has a quadratic derivative, so we expect up to two saddles." },
        { stepNumber: 2, description: "Solve for the saddles.", workingLatex: "z_0 = +1 \\quad\\text{or}\\quad z_0 = -1.", explanation: "Both roots are real here, but in general saddles may be complex; the algebra is identical." },
        { stepNumber: 3, description: "Check non-degeneracy.", workingLatex: "h''(z) = 6z, \\qquad h''(1) = 6, \\quad h''(-1) = -6.", explanation: "Both values are non-zero, so each is a simple saddle. The opposite signs of \\( h'' \\) will give the two saddles steepest-descent paths in different directions." },
      ],
      finalAnswer: "\\( z_0 = \\pm 1 \\)",
      canonicalAnswer: "1, -1",
    },
  },
  {
    id: "am7a-003",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The phase \\( h(z) = iz^2 \\) has a saddle at \\( z_0 = 0 \\). Find the two directions (as angles \\( \\phi \\) measured from \\( z_0 \\)) along which the steepest-descent path leaves the saddle.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent direction", "argument of curvature"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the curvature at the saddle.", workingLatex: "h''(z) = 2i, \\qquad h''(0) = 2i = 2\\,e^{i\\pi/2}.", explanation: "Near the saddle \\( h(z) \\approx h(z_0) + \\tfrac12 h''(z_0)(z-z_0)^2 \\); the argument of \\( h''(z_0) \\) fixes the orientation of the descent and ascent lines." },
        { stepNumber: 2, description: "Impose the descent condition.", workingLatex: "\\text{Put } z = re^{i\\phi}: \\;\\; \\tfrac12 h''(z_0) z^2 = i r^2 e^{i(2\\phi)} \\text{ real and negative} \\iff 2\\phi + \\tfrac{\\pi}{2} = \\pi.", explanation: "On a steepest-descent path \\( \\operatorname{Im} h \\) is constant and \\( \\operatorname{Re} h \\) decreases, so the quadratic term must be real and negative: \\( \\arg(\\tfrac12 h'' z^2) = \\pi \\)." },
        { stepNumber: 3, description: "Solve for the descent directions.", workingLatex: "2\\phi = \\pi - \\tfrac{\\pi}{2} = \\tfrac{\\pi}{2} \\;\\implies\\; \\phi = \\tfrac{\\pi}{4} \\ \\text{or}\\ \\phi = \\tfrac{\\pi}{4} + \\pi = \\tfrac{5\\pi}{4}.", explanation: "There are two opposite descent directions because adding \\( \\pi \\) to \\( \\phi \\) leaves \\( e^{i2\\phi} \\) unchanged. (The ascent lines are at \\( \\phi = -\\pi/4, 3\\pi/4 \\).)" },
      ],
      finalAnswer: "\\( \\phi = \\tfrac{\\pi}{4} \\) and \\( \\phi = \\tfrac{5\\pi}{4} \\)",
      canonicalAnswer: "pi/4, 5*pi/4",
    },
  },
  {
    id: "am7a-004",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 04",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The phase \\( h(z) = z^2 \\) has a saddle at \\( z_0 = 0 \\). State the steepest-descent directions and the steepest-ascent directions there.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "steepest ascent"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Curvature at the saddle.", workingLatex: "h''(0) = 2 = 2\\,e^{i\\cdot 0}, \\qquad \\alpha := \\arg h''(0) = 0.", explanation: "With \\( z = re^{i\\phi} \\) the quadratic term is \\( \\tfrac12 h''(0) z^2 = r^2 e^{i2\\phi} \\); its sign relative to the real axis decides descent versus ascent." },
        { stepNumber: 2, description: "Descent: quadratic real and negative.", workingLatex: "2\\phi + \\alpha = \\pi \\;\\implies\\; \\phi = \\tfrac{\\pi}{2}, \\ \\tfrac{3\\pi}{2}.", explanation: "Along these vertical directions \\( z^2 = -r^2 < 0 \\), so \\( \\operatorname{Re} h \\) decreases — the integrand decays. These are the descent (valley) lines." },
        { stepNumber: 3, description: "Ascent: quadratic real and positive.", workingLatex: "2\\phi + \\alpha = 0 \\;\\implies\\; \\phi = 0, \\ \\pi.", explanation: "Along the real axis \\( z^2 = r^2 > 0 \\), so \\( \\operatorname{Re} h \\) increases — the integrand grows. These are the ascent (ridge) lines, which the steepest-descent contour must avoid." },
      ],
      finalAnswer: "Descent: \\( \\phi = \\tfrac{\\pi}{2}, \\tfrac{3\\pi}{2} \\); ascent: \\( \\phi = 0, \\pi \\).",
      canonicalAnswer: "descent pi/2,3pi/2; ascent 0,pi",
    },
  },
  {
    id: "am7a-005",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the phase \\( h(z) = z - 2z^{1/2} \\) (principal branch, cut along the negative real axis), show that \\( z_0 = 1 \\) is a saddle point and evaluate \\( h(z_0) \\) and \\( h''(z_0) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["saddle point", "branch cut"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "h'(z) = 1 - z^{-1/2}.", explanation: "Differentiate \\( -2z^{1/2} \\) using \\( \\tfrac{d}{dz} z^{1/2} = \\tfrac12 z^{-1/2} \\); the constant cut keeps \\( z^{1/2} \\) single-valued away from the negative real axis." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "1 - z^{-1/2} = 0 \\;\\implies\\; z^{1/2} = 1 \\;\\implies\\; z_0 = 1.", explanation: "On the principal branch \\( z^{1/2} = 1 \\) gives \\( z_0 = 1 \\), which lies off the cut, so it is a legitimate saddle of the analytic phase." },
        { stepNumber: 3, description: "Evaluate the phase and curvature there.", workingLatex: "h(1) = 1 - 2 = -1, \\qquad h''(z) = \\tfrac12 z^{-3/2}, \\quad h''(1) = \\tfrac12.", explanation: "The value \\( h(z_0) = -1 \\) sets the exponential scale \\( e^{-\\lambda} \\) of the saddle contribution; \\( h''(1) = \\tfrac12 > 0 \\) is real and positive, fixing the descent geometry." },
      ],
      finalAnswer: "\\( z_0 = 1,\\ h(z_0) = -1,\\ h''(z_0) = \\tfrac{1}{2} \\)",
    },
  },
  {
    id: "am7a-006",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the phase \\( h(t) = it - \\tfrac{1}{2}t^2 \\), find the saddle point \\( t_0 \\) and the steepest-descent direction there.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["saddle point", "steepest descent direction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the saddle.", workingLatex: "h'(t) = i - t = 0 \\;\\implies\\; t_0 = i.", explanation: "The saddle lies off the real axis, at \\( t_0 = i \\); the original integration contour will have to be deformed up to pass through it." },
        { stepNumber: 2, description: "Compute the curvature.", workingLatex: "h''(t) = -1, \\qquad h''(t_0) = -1 = e^{i\\pi}, \\quad \\alpha = \\pi.", explanation: "The curvature is a negative real number, so its argument is \\( \\alpha = \\pi \\); this enters the descent-direction condition." },
        { stepNumber: 3, description: "Apply the descent condition.", workingLatex: "2\\phi + \\alpha = \\pi \\;\\implies\\; 2\\phi = 0 \\;\\implies\\; \\phi = 0 \\ \\text{or}\\ \\pi.", explanation: "With \\( h''(t_0) < 0 \\) the descent path runs horizontally through \\( t_0 = i \\); along it \\( \\tfrac12 h'' (t-t_0)^2 = -\\tfrac12 r^2 < 0 \\), so \\( \\operatorname{Re} h \\) decreases as required." },
      ],
      finalAnswer: "\\( t_0 = i \\); steepest-descent directions \\( \\phi = 0, \\pi \\) (horizontal).",
    },
  },

  // ── Standard: typical sheet-level ───────────────────────────────────────
  {
    id: "am7a-007",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 07",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The integral \\( f(\\theta) = \\dfrac{1}{2\\pi i}\\displaystyle\\int_{C} \\exp\\!\\big(\\theta(t + \\tfrac13 t^3)\\big)\\,dt \\) has phase \\( h(t) = t + \\tfrac13 t^3 \\). Find both saddle points and the value of \\( h \\) at each.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "complex saddle"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "h'(t) = 1 + t^2.", explanation: "Saddle points solve \\( h'(t)=0 \\). Because \\( 1 + t^2 \\) has no real roots, the saddles are a complex-conjugate pair." },
        { stepNumber: 2, description: "Solve for the saddles.", workingLatex: "1 + t^2 = 0 \\;\\implies\\; t = \\pm i.", explanation: "The two saddles sit symmetrically on the imaginary axis; the path \\( C \\) (from the lower-right sector to the upper-right sector) will be deformed to descend through them." },
        { stepNumber: 3, description: "Evaluate the phase at \\( t = i \\).", workingLatex: "h(i) = i + \\tfrac13 i^3 = i - \\tfrac13 i = \\tfrac{2i}{3}.", explanation: "Using \\( i^3 = -i \\). The value is purely imaginary, so \\( |e^{\\theta h(i)}| = 1 \\): this saddle gives an oscillatory, not exponentially small, contribution." },
        { stepNumber: 4, description: "Evaluate the phase at \\( t = -i \\).", workingLatex: "h(-i) = -i + \\tfrac13(-i)^3 = -i + \\tfrac13 i = -\\tfrac{2i}{3}.", explanation: "By conjugate symmetry \\( h(-i) = \\overline{h(i)} \\). The two saddles contribute complex-conjugate terms whose sum is real, consistent with \\( f(\\theta) \\) being real." },
      ],
      finalAnswer: "\\( t = \\pm i \\), with \\( h(i) = \\tfrac{2i}{3} \\) and \\( h(-i) = -\\tfrac{2i}{3} \\).",
      canonicalAnswer: "t=i: 2i/3; t=-i: -2i/3",
    },
  },
  {
    id: "am7a-008",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the phase \\( h(t) = t + \\tfrac13 t^3 \\), determine the curvature \\( h''(t) \\) at the saddle \\( t_0 = i \\) and hence the two steepest-descent directions there.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent direction", "complex saddle"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the second derivative.", workingLatex: "h'(t) = 1 + t^2, \\qquad h''(t) = 2t.", explanation: "We need \\( h'' \\) at the saddle to expand \\( h(t) \\approx h(t_0) + \\tfrac12 h''(t_0)(t-t_0)^2 \\) and read off the local geometry." },
        { stepNumber: 2, description: "Evaluate at the saddle.", workingLatex: "h''(i) = 2i = 2\\,e^{i\\pi/2}, \\qquad \\alpha := \\arg h''(i) = \\tfrac{\\pi}{2}.", explanation: "The modulus \\( |h''| = 2 \\) sets the width of the saddle; the argument \\( \\alpha = \\pi/2 \\) orients the descent and ascent lines." },
        { stepNumber: 3, description: "Apply the descent condition.", workingLatex: "(t - t_0) = re^{i\\phi}: \\quad 2\\phi + \\alpha = \\pi \\;\\implies\\; 2\\phi = \\tfrac{\\pi}{2}.", explanation: "On a descent path the quadratic \\( \\tfrac12 h''(t_0)(t-t_0)^2 \\) is real and negative, so its argument \\( 2\\phi + \\alpha \\) must equal \\( \\pi \\)." },
        { stepNumber: 4, description: "Solve for the directions.", workingLatex: "\\phi = \\tfrac{\\pi}{4} \\quad\\text{or}\\quad \\phi = \\tfrac{\\pi}{4} + \\pi = \\tfrac{5\\pi}{4}.", explanation: "The descent path leaves \\( t_0 = i \\) at \\( 45^\\circ \\) and continues at \\( 225^\\circ \\). To run from the lower-right to the upper-right sector the contour traverses these in the appropriate order." },
      ],
      finalAnswer: "\\( h''(i) = 2i \\); steepest-descent directions \\( \\phi = \\tfrac{\\pi}{4},\\ \\tfrac{5\\pi}{4} \\).",
    },
  },
  {
    id: "am7a-009",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( h(t) = t + \\tfrac13 t^3 \\) with \\( t = x + iy \\). Show that the level line \\( \\operatorname{Im} h = \\tfrac23 \\) passes through the saddle \\( t_0 = i \\), and write \\( \\operatorname{Im} h \\) explicitly in terms of \\( x \\) and \\( y \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["level line", "steepest descent path", "Im h constant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the phase in real and imaginary parts.", workingLatex: "t^3 = (x+iy)^3 = x^3 - 3xy^2 + i(3x^2 y - y^3).", explanation: "Steepest paths are level lines of \\( \\operatorname{Im} h \\), so we separate \\( h \\) into real and imaginary parts. Recall \\( (x+iy)^3 \\) by the binomial expansion." },
        { stepNumber: 2, description: "Collect the imaginary part.", workingLatex: "\\operatorname{Im} h = y + \\tfrac13(3x^2 y - y^3) = y\\big(x^2 - \\tfrac13 y^2 + 1\\big).", explanation: "The constant term contributes \\( \\operatorname{Im} t = y \\); factor out \\( y \\) to display the level lines cleanly." },
        { stepNumber: 3, description: "Check the saddle value.", workingLatex: "\\operatorname{Im} h(i) = \\operatorname{Im}\\big(\\tfrac{2i}{3}\\big) = \\tfrac23.", explanation: "At \\( t_0 = i \\) we have \\( x=0, y=1 \\), giving \\( 1\\cdot(0 - \\tfrac13 + 1) = \\tfrac23 \\), which matches. The steepest-descent and steepest-ascent lines through \\( t_0 \\) are the two branches of \\( y(x^2 - \\tfrac13 y^2 + 1) = \\tfrac23 \\)." },
      ],
      finalAnswer: "\\( \\operatorname{Im} h = y\\big(x^2 - \\tfrac13 y^2 + 1\\big) \\), equal to \\( \\tfrac23 \\) at \\( t_0=i \\).",
    },
  },
  {
    id: "am7a-010",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( h(z) = z - 2z^{1/2} \\) (principal branch) with saddle \\( z_0 = 1 \\). Verify that the parametrised curve \\( z_+(\\tau) = (1 + i\\tau)^2,\\ \\tau \\ge 0 \\), is a steepest-descent path by showing \\( h\\big(z_+(\\tau)\\big) = -1 - \\tau^2 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent path", "branch cut", "parametrisation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take the square root on the curve.", workingLatex: "z_+(\\tau) = (1 + i\\tau)^2 \\;\\implies\\; z_+^{1/2} = 1 + i\\tau.", explanation: "Choosing the principal root: for \\( \\tau \\ge 0 \\) the point \\( 1 + i\\tau \\) lies in the right half-plane \\( (\\operatorname{Re} > 0) \\), so it is the principal value of \\( z_+^{1/2} \\). This is the key sign choice." },
        { stepNumber: 2, description: "Expand the curve.", workingLatex: "z_+(\\tau) = 1 - \\tau^2 + 2i\\tau.", explanation: "Square out \\( (1+i\\tau)^2 = 1 + 2i\\tau + (i\\tau)^2 \\). We will substitute this together with the root into \\( h \\)." },
        { stepNumber: 3, description: "Substitute into the phase.", workingLatex: "h(z_+) = (1 - \\tau^2 + 2i\\tau) - 2(1 + i\\tau) = -1 - \\tau^2.", explanation: "The imaginary parts cancel exactly: \\( 2i\\tau - 2i\\tau = 0 \\). This cancellation is the whole point — it shows \\( \\operatorname{Im} h \\) is constant along the curve." },
        { stepNumber: 4, description: "Confirm descent.", workingLatex: "\\operatorname{Im} h = 0 = \\operatorname{Im} h(z_0), \\qquad \\operatorname{Re} h = -1 - \\tau^2 \\ \\text{decreasing in } \\tau.", explanation: "\\( \\operatorname{Im} h \\) is constant (level line) and \\( \\operatorname{Re} h \\) strictly decreases as \\( \\tau \\) grows, so the integrand \\( e^{k h} \\) decays — this is a genuine steepest-DESCENT path, not ascent." },
      ],
      finalAnswer: "\\( h(z_+(\\tau)) = -1 - \\tau^2 \\): \\( \\operatorname{Im} h \\) constant, \\( \\operatorname{Re} h \\) decreasing, so steepest descent.",
    },
  },
  {
    id: "am7a-011",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( h(z) = z - 2z^{1/2} \\) with saddle \\( z_0 = 1 \\), the two steepest-descent paths are \\( z_\\pm(\\tau) = 1 - \\tau^2 \\pm 2i\\tau,\\ \\tau \\ge 0 \\). Show they form the two halves of a single parabola and find its equation in real form.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent path", "parabola", "real form"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Read off the real coordinates.", workingLatex: "z = x + iy: \\quad x = 1 - \\tau^2, \\qquad y = \\pm 2\\tau.", explanation: "Both branches have the same \\( x(\\tau) = 1 - \\tau^2 \\); they differ only by the sign of \\( y \\), so together they are symmetric about the real axis." },
        { stepNumber: 2, description: "Eliminate the parameter.", workingLatex: "\\tau = \\frac{|y|}{2} \\;\\implies\\; \\tau^2 = \\frac{y^2}{4}.", explanation: "Square the \\( y \\)-relation so the \\( \\pm \\) sign disappears; both halves then satisfy the same equation, confirming they are one curve." },
        { stepNumber: 3, description: "Substitute to get the parabola.", workingLatex: "x = 1 - \\frac{y^2}{4} \\;\\iff\\; y^2 = 4(1 - x).", explanation: "A leftward-opening parabola with vertex at the saddle \\( (1,0) \\), crossing the real axis exactly at \\( z_0 = 1 \\) — as a steepest-descent path through a saddle must." },
      ],
      finalAnswer: "\\( y^2 = 4(1 - x) \\) (vertex at the saddle \\( z_0 = 1 \\)).",
    },
  },
  {
    id: "am7a-012",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The phase \\( h(t) = i(t + t^2) \\) arises in \\( \\int_0^1 t^{-1/2} e^{i\\lambda(t+t^2)}\\,dt \\). Find the saddle point of \\( h \\) and explain why it does not lie on the integration range \\( (0,1) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "endpoint contributions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "h'(t) = i(1 + 2t).", explanation: "Even though the integral is over a real interval, the saddle method works with the analytic continuation of \\( h \\) into the complex \\( t \\)-plane." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "i(1 + 2t) = 0 \\;\\implies\\; t_0 = -\\tfrac12.", explanation: "The single saddle sits at \\( t_0 = -\\tfrac12 \\), on the negative real axis." },
        { stepNumber: 3, description: "Compare with the range.", workingLatex: "t_0 = -\\tfrac12 \\notin (0,1).", explanation: "Because the saddle lies outside \\( (0,1) \\), it gives no interior contribution. The asymptotics are instead governed by the endpoints \\( t=0 \\) and \\( t=1 \\), reached by steepest-descent paths emanating from each endpoint." },
        { stepNumber: 4, description: "Note the endpoint phase values.", workingLatex: "h(0) = 0, \\qquad h(1) = 2i, \\qquad h''(t) = 2i.", explanation: "The constant curvature \\( h'' = 2i \\) sets the descent direction at each endpoint; the endpoint with the larger \\( \\operatorname{Im} h \\) needs its own contour treatment." },
      ],
      finalAnswer: "Saddle at \\( t_0 = -\\tfrac12 \\), outside \\( (0,1) \\); endpoints dominate.",
    },
  },
  {
    id: "am7a-013",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( h(t) = i(t + t^2) \\), \\( t = x+iy \\), find the steepest-descent path through the endpoint \\( t = 0 \\) (the level line \\( \\operatorname{Im} h = 0 \\) on which \\( \\operatorname{Re} h \\) decreases), and give its direction at \\( t = 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent path", "endpoint", "level line"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Split the phase into real and imaginary parts.", workingLatex: "h = i\\big[(x+iy) + (x+iy)^2\\big] = i\\big[x + x^2 - y^2 + i(y + 2xy)\\big].", explanation: "Expand \\( (x+iy)^2 = x^2 - y^2 + 2ixy \\) and group, before multiplying through by \\( i \\)." },
        { stepNumber: 2, description: "Multiply out the leading \\( i \\).", workingLatex: "h = -\\,(y + 2xy) + i\\,(x + x^2 - y^2).", explanation: "Multiplying by \\( i \\) swaps real and imaginary parts (with a sign): \\( \\operatorname{Re} h = -(y+2xy) \\) and \\( \\operatorname{Im} h = x + x^2 - y^2 \\)." },
        { stepNumber: 3, description: "Impose the level-line condition through the origin.", workingLatex: "\\operatorname{Im} h = x + x^2 - y^2 = 0 \\quad (\\text{since } \\operatorname{Im} h(0)=0).", explanation: "Steepest paths keep \\( \\operatorname{Im} h \\) fixed at its saddle/endpoint value, here \\( 0 \\). This conic passes through the origin." },
        { stepNumber: 4, description: "Linearise near the origin to get the direction.", workingLatex: "x - y^2 \\approx 0 \\Rightarrow x \\approx y^2 \\to 0, \\quad\\text{so the path leaves along } x = 0 \\ (\\phi = \\tfrac{\\pi}{2}).", explanation: "Near \\( t=0 \\) the quadratic terms are negligible, so \\( x \\approx 0 \\): the descent path leaves vertically. Checking \\( \\operatorname{Re} h = -y(1+2x)\\approx -y \\) decreases for \\( y>0 \\), confirming descent into the upper half-plane." },
      ],
      finalAnswer: "Path \\( x + x^2 - y^2 = 0 \\); leaves \\( t=0 \\) vertically (\\( \\phi = \\tfrac{\\pi}{2} \\)).",
    },
  },
  {
    id: "am7a-014",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The phase \\( h(z) = k(z - 2z^{1/2}) \\) appears with \\( k\\to+\\infty \\). At the saddle \\( z_0 = 1 \\), compute the leading steepest-descent contribution to \\( \\displaystyle\\int_C \\frac{e^{h(z)}}{z - c}\\,dz \\) (amplitude \\( g(z) = 1/(z-c) \\), \\( c \\) real, \\( c<1 \\)).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point method", "leading term", "amplitude"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Gather saddle data.", workingLatex: "h(1) = -1, \\quad h''(1) = \\tfrac12 = \\tfrac12 e^{i\\cdot 0}, \\quad g(1) = \\frac{1}{1 - c}.", explanation: "We rescale \\( h \\) to absorb \\( k \\): writing \\( h = k\\,\\tilde h \\) with \\( \\tilde h = z - 2z^{1/2} \\), the saddle data are \\( \\tilde h(1) = -1 \\), \\( \\tilde h''(1) = \\tfrac12 \\)." },
        { stepNumber: 2, description: "Descent direction from the curvature.", workingLatex: "\\alpha = \\arg \\tilde h''(1) = 0 \\;\\implies\\; \\phi = \\frac{\\pi - \\alpha}{2} = \\frac{\\pi}{2}.", explanation: "Since \\( \\tilde h''(1)>0 \\), the descent path crosses the saddle vertically (\\( \\phi = \\pi/2 \\)), matching the parabola \\( y^2 = 4(1-x) \\) at its vertex." },
        { stepNumber: 3, description: "Apply the saddle-point formula.", workingLatex: "I(k) \\sim g(z_0)\\,e^{k\\tilde h(z_0)}\\sqrt{\\frac{2\\pi}{k\\,|\\tilde h''(z_0)|}}\\;e^{i\\phi}.", explanation: "The standard simple-saddle result; \\( e^{i\\phi} \\) is the tangent direction of the descent contour and supplies the correct phase." },
        { stepNumber: 4, description: "Substitute.", workingLatex: "I(k) \\sim \\frac{1}{1-c}\\,e^{-k}\\sqrt{\\frac{2\\pi}{k\\cdot \\tfrac12}}\\;e^{i\\pi/2} = \\frac{i}{1-c}\\,e^{-k}\\,\\frac{2\\sqrt{\\pi}}{\\sqrt{k}}.", explanation: "With \\( |\\tilde h''| = \\tfrac12 \\), \\( \\sqrt{2\\pi/(k/2)} = 2\\sqrt{\\pi/k} \\), and \\( e^{i\\pi/2} = i \\). The pole at \\( c<1 \\) is not crossed, so only the saddle contributes." },
      ],
      finalAnswer: "\\( I(k) \\sim \\dfrac{2i\\sqrt{\\pi}}{(1-c)\\sqrt{k}}\\,e^{-k} \\)",
      canonicalAnswer: "2*i*sqrt(pi)/((1-c)*sqrt(k))*exp(-k)",
    },
  },
  {
    id: "am7a-015",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( h(t) = -t^4/4 + t^2/2 \\), find all saddle points and classify the steepest-descent direction at each (the central saddle versus the two outer saddles).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "multiple saddles", "descent direction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the saddles.", workingLatex: "h'(t) = -t^3 + t = -t(t^2 - 1) = 0 \\;\\implies\\; t_0 = 0,\\ \\pm 1.", explanation: "A quartic phase gives a cubic derivative with three roots, hence three saddles to compare." },
        { stepNumber: 2, description: "Curvature at the central saddle.", workingLatex: "h''(t) = -3t^2 + 1, \\quad h''(0) = 1 = e^{i\\cdot 0}.", explanation: "At \\( t_0 = 0 \\), \\( h'' > 0 \\): the descent direction is \\( \\phi = (\\pi - 0)/2 = \\tfrac{\\pi}{2} \\), i.e. vertical (along the imaginary axis)." },
        { stepNumber: 3, description: "Curvature at the outer saddles.", workingLatex: "h''(\\pm 1) = -3 + 1 = -2 = 2e^{i\\pi}.", explanation: "At \\( t_0 = \\pm 1 \\), \\( h'' < 0 \\): the descent direction is \\( \\phi = (\\pi - \\pi)/2 = 0 \\), i.e. horizontal (along the real axis)." },
        { stepNumber: 4, description: "Summarise.", workingLatex: "\\begin{aligned} t_0 = 0:&\\ \\text{descent vertical }(\\phi=\\tfrac\\pi2),\\\\ t_0 = \\pm1:&\\ \\text{descent horizontal }(\\phi=0).\\end{aligned}", explanation: "The central saddle is a 'valley running up-down', the outer saddles 'valleys running left-right'; on the real axis the central point is a local maximum of \\( \\operatorname{Re} h \\) (ascent) while the outer points are minima (descent)." },
      ],
      finalAnswer: "\\( t_0 = 0 \\) (descent \\( \\phi=\\tfrac\\pi2 \\)); \\( t_0 = \\pm1 \\) (descent \\( \\phi=0 \\)).",
    },
  },
  {
    id: "am7a-016",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "At a simple saddle \\( z_0 \\) the curvature is \\( h''(z_0) = 1 + i \\). Find the steepest-descent directions and the steepest-ascent directions, expressing each angle in radians.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["descent direction", "ascent direction", "argument"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the argument of the curvature.", workingLatex: "h''(z_0) = 1 + i = \\sqrt{2}\\,e^{i\\pi/4}, \\qquad \\alpha = \\tfrac{\\pi}{4}.", explanation: "Write the curvature in polar form. Only its argument \\( \\alpha \\) is needed to orient the descent/ascent lines." },
        { stepNumber: 2, description: "Descent directions.", workingLatex: "2\\phi + \\alpha = \\pi \\;\\implies\\; \\phi = \\frac{\\pi - \\pi/4}{2} = \\frac{3\\pi}{8},\\ \\frac{3\\pi}{8} + \\pi = \\frac{11\\pi}{8}.", explanation: "Descent requires the quadratic \\( \\tfrac12 h''(z_0)(z-z_0)^2 \\) to be real and negative." },
        { stepNumber: 3, description: "Ascent directions.", workingLatex: "2\\phi + \\alpha = 0 \\;\\implies\\; \\phi = -\\frac{\\pi}{8},\\ -\\frac{\\pi}{8} + \\pi = \\frac{7\\pi}{8}.", explanation: "Ascent requires the quadratic to be real and positive; the ascent lines bisect the descent lines, sitting at \\( 90^\\circ \\) to them." },
      ],
      finalAnswer: "Descent: \\( \\tfrac{3\\pi}{8}, \\tfrac{11\\pi}{8} \\); ascent: \\( -\\tfrac{\\pi}{8}, \\tfrac{7\\pi}{8} \\).",
    },
  },
  {
    id: "am7a-017",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Consider \\( \\int_0^\\infty \\exp\\!\\big(ix(\\tfrac13 t^3 + t)\\big)\\,dt \\) with \\( x\\to+\\infty \\). Show the phase has no saddle on the path of integration, identify where the saddles are, and state which feature of the integral then governs the leading asymptotics.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "endpoint dominance"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the phase and differentiate.", workingLatex: "h(t) = i\\big(\\tfrac13 t^3 + t\\big), \\qquad h'(t) = i(t^2 + 1).", explanation: "Factoring out \\( x \\) leaves the phase \\( h \\); its stationary points are the saddles of the saddle-point method." },
        { stepNumber: 2, description: "Locate the saddles.", workingLatex: "t^2 + 1 = 0 \\;\\implies\\; t = \\pm i.", explanation: "The saddles are at \\( \\pm i \\), off the real axis. Neither lies on the contour \\( [0,\\infty) \\)." },
        { stepNumber: 3, description: "Check the contour.", workingLatex: "\\pm i \\notin [0,\\infty), \\qquad h(0) = 0.", explanation: "With no interior saddle and rapid oscillation along the ray, only the endpoint \\( t=0 \\) fails to cancel; the upper limit contributes nothing because of decay on a rotated contour." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "I(x) \\sim \\text{endpoint contribution at } t=0 = O\\!\\left(\\tfrac1x\\right).", explanation: "Integration by parts (or a steepest-descent contour rotated off \\( t=0 \\)) gives a leading term \\( i/x \\): the asymptotics are endpoint-governed, not saddle-governed, because the saddles are not reachable without leaving the valley structure of the contour." },
      ],
      finalAnswer: "Saddles at \\( t = \\pm i \\) (off-contour); leading behaviour is the endpoint contribution \\( \\sim i/x \\).",
    },
  },
  {
    id: "am7a-018",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "At a saddle \\( z_0 \\) the two candidate descent tangents are \\( e^{i\\pi/4} \\) and \\( e^{i5\\pi/4} \\). If the contour must run from a point below-right of \\( z_0 \\) to a point above-left of \\( z_0 \\), state the orientation (the order in which the directions are traversed) and explain the sign choice.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["orientation", "choice of root sign", "descent path"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the two tangent rays.", workingLatex: "\\hat{e}_1 = e^{i\\pi/4} \\ (\\text{up-right}), \\qquad \\hat{e}_2 = e^{i5\\pi/4} \\ (\\text{down-left}).", explanation: "The descent path is a single line through \\( z_0 \\); the two directions are its two ends. Only the sense (orientation) is undetermined so far." },
        { stepNumber: 2, description: "Match endpoints to directions.", workingLatex: "\\text{enter from below-right} \\Rightarrow \\text{arrive along } -\\hat{e}_2 = \\hat{e}_1\\ \\text{into } z_0;\\ \\text{leave along } \\hat{e}_1.", explanation: "Coming from below-right means approaching \\( z_0 \\) heading up-left, then continuing up-left after the saddle toward the above-left endpoint — i.e. the contour is traversed in the \\( e^{i\\pi/4} \\) sense throughout the second half." },
        { stepNumber: 3, description: "State the orientation and sign.", workingLatex: "(z - z_0) = \\tau\\,e^{i\\pi/4}, \\quad \\tau:\\ -\\infty \\to +\\infty \\ \\text{(taking } +\\sqrt{} \\text{)}.", explanation: "We parametrise \\( z - z_0 = \\tau e^{i\\pi/4} \\) with \\( \\tau \\) increasing from negative to positive; this choice (the \\( + \\) square root of the curvature direction) makes the contour run from the below-right valley to the above-left valley, fixing the overall sign of the saddle contribution." },
      ],
      finalAnswer: "Traverse in the \\( e^{i\\pi/4} \\) sense (\\( \\tau: -\\infty\\to+\\infty \\)); take the \\( + \\) root.",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level ─────────────────────
  {
    id: "am7a-019",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( f(\\theta) = \\dfrac{1}{2\\pi i}\\displaystyle\\int_C \\exp\\!\\big(\\theta(t+\\tfrac13 t^3)\\big)\\,dt \\) with the path running from the sector \\( -\\tfrac{\\pi}{2}<\\arg t<-\\tfrac{\\pi}{6} \\) to \\( \\tfrac{\\pi}{6}<\\arg t<\\tfrac{\\pi}{2} \\), show that the steepest-descent path through the saddle \\( t=i \\) is \\( x = +\\big(\\tfrac{2+y}{3y}\\big)^{1/2}(y-1) \\) for \\( y>0 \\), justifying the choice of square-root sign.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent path", "choice of root sign", "level line"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the level-line equation.", workingLatex: "\\operatorname{Im} h = y\\big(x^2 - \\tfrac13 y^2 + 1\\big) = \\tfrac23 \\quad(\\text{value at } t=i).", explanation: "Steepest paths through \\( t=i \\) are level lines of \\( \\operatorname{Im} h \\); we derived \\( \\operatorname{Im} h = y(x^2 - \\tfrac13 y^2 + 1) \\) and at \\( t=i \\) it equals \\( \\tfrac23 \\)." },
        { stepNumber: 2, description: "Solve for \\( x^2 \\).", workingLatex: "x^2 = \\frac{2}{3y} + \\frac{y^2}{3} - 1 = \\frac{2 + y^3 - 3y}{3y}.", explanation: "Rearrange the level-line equation. We must factor the numerator to extract the branch through the saddle." },
        { stepNumber: 3, description: "Factor the cubic numerator.", workingLatex: "y^3 - 3y + 2 = (y-1)^2(y+2) \\;\\implies\\; x^2 = \\frac{(y-1)^2(y+2)}{3y}.", explanation: "The double root at \\( y=1 \\) reflects the saddle at \\( t=i \\) (\\( x=0, y=1 \\)); the factor \\( (y-1)^2 \\) makes \\( x\\to0 \\) as \\( y\\to1 \\), as it must on the path through the saddle." },
        { stepNumber: 4, description: "Take the square root.", workingLatex: "x = \\pm\\,|y-1|\\sqrt{\\frac{y+2}{3y}} \\quad (y>0).", explanation: "Both \\( (y-1)^2 \\) and \\( \\tfrac{y+2}{3y} \\) are non-negative for \\( y>0 \\), so the square root is real. The sign and the \\( |y-1| \\) must now be fixed by the geometry of the contour." },
        { stepNumber: 5, description: "Fix the sign from the prescribed sectors.", workingLatex: "x \\to +\\infty \\ \\text{as } y\\to0^+ \\ (\\arg t \\to 0^+), \\quad x>0 \\ \\text{for } y>1.", explanation: "The contour ends in \\( \\tfrac{\\pi}{6}<\\arg t<\\tfrac{\\pi}{2} \\), so on the relevant branch \\( x>0 \\) for large \\( y \\); choosing the \\( + \\) root and writing \\( |y-1|\\to(y-1) \\) for \\( y>1 \\) (and the corresponding signed form for \\( 0<y<1 \\)) gives a single smooth curve." },
        { stepNumber: 6, description: "State the descent branch.", workingLatex: "x = +\\Big(\\frac{2+y}{3y}\\Big)^{1/2}(y-1), \\qquad y>0.", explanation: "This branch is the steepest-DESCENT path (one checks \\( \\operatorname{Re} h \\) decreases away from \\( t=i \\) along it); the mirror sign would give the steepest-ascent path, which the contour must not follow." },
      ],
      finalAnswer: "\\( x = +\\big(\\tfrac{2+y}{3y}\\big)^{1/2}(y-1),\\ y>0 \\) (the \\( + \\) root is forced by the prescribed end-sectors).",
    },
  },
  {
    id: "am7a-020",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Continuing the previous problem, show that the steepest-descent path through the second saddle \\( t=-i \\) is \\( x = -\\big(\\tfrac{y-2}{3y}\\big)^{1/2}(y+1) \\) for \\( y<0 \\), again justifying the root sign.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent path", "second saddle", "choice of root sign"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Level-line value at the second saddle.", workingLatex: "\\operatorname{Im} h(-i) = -\\tfrac23, \\qquad y(x^2 - \\tfrac13 y^2 + 1) = -\\tfrac23.", explanation: "By conjugate symmetry \\( h(-i) = -\\tfrac{2i}{3} \\), so the level line through the lower saddle is \\( \\operatorname{Im} h = -\\tfrac23 \\)." },
        { stepNumber: 2, description: "Solve for \\( x^2 \\).", workingLatex: "x^2 = \\frac{-2}{3y} + \\frac{y^2}{3} - 1 = \\frac{-2 + y^3 - 3y}{3y}.", explanation: "Rearrange, keeping \\( y<0 \\) in mind so that the eventual quotient stays non-negative." },
        { stepNumber: 3, description: "Factor the numerator.", workingLatex: "y^3 - 3y - 2 = (y+1)^2(y-2) \\;\\implies\\; x^2 = \\frac{(y+1)^2(y-2)}{3y}.", explanation: "The double root at \\( y=-1 \\) marks the saddle \\( t=-i \\) (\\( x=0,y=-1 \\)); for \\( y<0 \\) both \\( (y-2)<0 \\) and \\( 3y<0 \\), so the quotient is positive — the path is real." },
        { stepNumber: 4, description: "Take the square root.", workingLatex: "x = \\pm\\,|y+1|\\sqrt{\\frac{y-2}{3y}} = \\pm\\,|y+1|\\sqrt{\\frac{2-y}{3|y|}} \\quad(y<0).", explanation: "Rewriting with \\( |y| = -y \\) makes the positivity explicit. The branch and sign are again set by the contour geometry." },
        { stepNumber: 5, description: "Fix the sign.", workingLatex: "x \\to -\\infty \\ \\text{as } y\\to 0^- \\ (\\arg t \\to \\pi^-),\\ \\text{but contour starts in } -\\tfrac{\\pi}{2}<\\arg t<-\\tfrac{\\pi}{6}.", explanation: "The contour begins in the lower-right sector, where \\( x>0,y<0 \\). Tracking the connected branch from there through \\( t=-i \\) selects the \\( - \\) sign written below, with \\( |y+1|\\to(y+1) \\) handled consistently so the curve is smooth." },
        { stepNumber: 6, description: "State the descent branch.", workingLatex: "x = -\\Big(\\frac{y-2}{3y}\\Big)^{1/2}(y+1), \\qquad y<0.", explanation: "Here \\( \\tfrac{y-2}{3y}>0 \\) for \\( y<0 \\), so the radicand is positive. This is the steepest-DESCENT path; the conjugate symmetry with the \\( t=+i \\) branch guarantees the two saddle contributions are complex conjugates." },
      ],
      finalAnswer: "\\( x = -\\big(\\tfrac{y-2}{3y}\\big)^{1/2}(y+1),\\ y<0 \\) (the \\( - \\) root is forced by the start sector).",
    },
  },
  {
    id: "am7a-021",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using the two saddles \\( t=\\pm i \\) of \\( h(t) = t+\\tfrac13 t^3 \\) (with \\( h''(\\pm i) = \\pm 2i \\)), apply the saddle-point method to show that \\( f(\\theta) = \\dfrac{1}{2\\pi i}\\displaystyle\\int_C e^{\\theta h(t)}\\,dt \\sim (\\pi\\theta)^{-1/2}\\cos\\!\\big(\\tfrac23\\theta - \\tfrac{\\pi}{4}\\big) \\) as \\( \\theta\\to\\infty \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point method", "two saddles", "Airy-type"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Saddle data for \\( t=i \\).", workingLatex: "h(i) = \\tfrac{2i}{3}, \\quad h''(i) = 2i = 2e^{i\\pi/2}, \\quad \\phi_+ = \\frac{\\pi - \\pi/2}{2} = \\frac{\\pi}{4}.", explanation: "The descent contour crosses \\( t=i \\) at angle \\( \\phi_+ = \\pi/4 \\), the direction matching the path from the lower-right to the upper-right sector." },
        { stepNumber: 2, description: "Contribution of \\( t=i \\).", workingLatex: "\\frac{1}{2\\pi i}\\,e^{\\theta h(i)}\\sqrt{\\frac{2\\pi}{\\theta|h''(i)|}}\\,e^{i\\phi_+} = \\frac{1}{2\\pi i}\\,e^{2i\\theta/3}\\sqrt{\\frac{\\pi}{\\theta}}\\,e^{i\\pi/4}.", explanation: "Insert into the simple-saddle formula with \\( |h''| = 2 \\): \\( \\sqrt{2\\pi/(2\\theta)} = \\sqrt{\\pi/\\theta} \\). The prefactor \\( 1/(2\\pi i) \\) carries through." },
        { stepNumber: 3, description: "Saddle data for \\( t=-i \\).", workingLatex: "h(-i) = -\\tfrac{2i}{3}, \\quad h''(-i) = -2i = 2e^{-i\\pi/2}, \\quad \\phi_- = \\frac{\\pi + \\pi/2}{2} = \\frac{3\\pi}{4}.", explanation: "The lower saddle is crossed at \\( \\phi_- = 3\\pi/4 \\) so the contour proceeds upward-left, consistent with a single connected steepest-descent path." },
        { stepNumber: 4, description: "Contribution of \\( t=-i \\).", workingLatex: "\\frac{1}{2\\pi i}\\,e^{-2i\\theta/3}\\sqrt{\\frac{\\pi}{\\theta}}\\,e^{i3\\pi/4}.", explanation: "Same modulus \\( |h''|=2 \\); the conjugate phase \\( e^{-2i\\theta/3} \\) and descent angle \\( e^{i3\\pi/4} \\) appear." },
        { stepNumber: 5, description: "Add the two contributions.", workingLatex: "f \\sim \\frac{1}{2\\pi i}\\sqrt{\\frac{\\pi}{\\theta}}\\Big[e^{i(2\\theta/3 + \\pi/4)} + e^{i(-2\\theta/3 + 3\\pi/4)}\\Big].", explanation: "Factor the common \\( \\tfrac{1}{2\\pi i}\\sqrt{\\pi/\\theta} \\). We now combine the bracket into a cosine." },
        { stepNumber: 6, description: "Combine into a cosine.", workingLatex: "e^{i(2\\theta/3+\\pi/4)} + e^{i(-2\\theta/3+3\\pi/4)} = 2\\,e^{i\\pi/2}\\cos\\!\\Big(\\tfrac23\\theta - \\tfrac{\\pi}{4}\\Big).", explanation: "Write each exponent as (mean) \\(\\pm\\) (half-difference): mean \\( = \\tfrac{\\pi/4+3\\pi/4}{2} = \\tfrac{\\pi}{2} \\), half-difference \\( = \\tfrac23\\theta - \\tfrac{\\pi}{4} \\). Then \\( e^{ia}+e^{ib} = 2e^{i(a+b)/2}\\cos\\tfrac{a-b}{2} \\)." },
        { stepNumber: 7, description: "Simplify the prefactor.", workingLatex: "f \\sim \\frac{2 e^{i\\pi/2}}{2\\pi i}\\sqrt{\\frac{\\pi}{\\theta}}\\cos\\!\\Big(\\tfrac23\\theta - \\tfrac{\\pi}{4}\\Big) = (\\pi\\theta)^{-1/2}\\cos\\!\\Big(\\tfrac23\\theta - \\tfrac{\\pi}{4}\\Big).", explanation: "Since \\( e^{i\\pi/2} = i \\), the factor \\( \\tfrac{2i}{2\\pi i} = \\tfrac1\\pi \\); then \\( \\tfrac1\\pi\\sqrt{\\pi/\\theta} = (\\pi\\theta)^{-1/2} \\). This is the required Airy-type result." },
      ],
      finalAnswer: "\\( f(\\theta) \\sim (\\pi\\theta)^{-1/2}\\cos\\!\\big(\\tfrac23\\theta - \\tfrac{\\pi}{4}\\big) \\)",
      canonicalAnswer: "(pi*theta)^(-1/2)*cos(2*theta/3 - pi/4)",
    },
  },
  {
    id: "am7a-022",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(z) = k(z - 2z^{1/2}) \\), \\( k\\to+\\infty \\), with saddle \\( z_0=1 \\) and steepest-descent parabola \\( z(\\tau) = 1 - \\tau^2 + 2i\\tau \\). For \\( I(k) = \\displaystyle\\int_{\\gamma-i\\infty}^{\\gamma+i\\infty}\\frac{e^{k(z-2z^{1/2})}}{z - c}\\,dz \\) with \\( c \\) real and \\( c<1 \\), use the parametrisation to obtain the leading behaviour.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point method", "parametrised contour", "leading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute the parametrisation.", workingLatex: "z - 2z^{1/2} = -1 - \\tau^2, \\qquad dz = (-2\\tau + 2i)\\,d\\tau.", explanation: "Along the descent path \\( h/k = -1 - \\tau^2 \\) (derived earlier) and \\( dz/d\\tau = \\tfrac{d}{d\\tau}(1-\\tau^2+2i\\tau) = -2\\tau + 2i \\)." },
        { stepNumber: 2, description: "Write the integral in \\( \\tau \\).", workingLatex: "I(k) = e^{-k}\\int_{-\\infty}^{\\infty}\\frac{e^{-k\\tau^2}}{z(\\tau) - c}\\,(2i - 2\\tau)\\,d\\tau.", explanation: "The contour from \\( \\gamma - i\\infty \\) to \\( \\gamma + i\\infty \\) is deformed onto the parabola, with \\( \\tau \\) running over \\( (-\\infty,\\infty) \\); the dominant factor is the Gaussian \\( e^{-k\\tau^2} \\)." },
        { stepNumber: 3, description: "Laplace-localise at \\( \\tau=0 \\).", workingLatex: "z(0) = 1, \\quad \\frac{2i - 2\\tau}{z(\\tau)-c}\\Big|_{\\tau=0} = \\frac{2i}{1 - c}.", explanation: "As \\( k\\to\\infty \\) the Gaussian concentrates at \\( \\tau=0 \\) (the saddle); replace the smooth amplitude by its value there." },
        { stepNumber: 4, description: "Do the Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-k\\tau^2}\\,d\\tau = \\sqrt{\\frac{\\pi}{k}}.", explanation: "Standard Gaussian; the leading saddle contribution is the amplitude-at-saddle times this width." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "I(k) \\sim e^{-k}\\cdot\\frac{2i}{1-c}\\cdot\\sqrt{\\frac{\\pi}{k}} = \\frac{2i\\sqrt{\\pi}}{(1-c)\\sqrt{k}}\\,e^{-k}.", explanation: "Because \\( c<1 \\) lies to the left of the saddle and the deformation does not cross the pole at \\( z=c \\), there is no residue term; the saddle alone gives the leading asymptotics — matching the direct formula." },
      ],
      finalAnswer: "\\( I(k) \\sim \\dfrac{2i\\sqrt{\\pi}}{(1-c)\\sqrt{k}}\\,e^{-k} \\)",
      canonicalAnswer: "2*i*sqrt(pi)/((1-c)*sqrt(k))*exp(-k)",
    },
  },
  {
    id: "am7a-023",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 23",
    difficulty: "Challenge",
    answerType: "expression",
    // REVIEW: residue / pole-crossing argument is a topological deformation claim, not a single numeric value, so it is not directly verified numerically; saddle term itself matches am7a-022.
    questionText: "For \\( I(k) = \\displaystyle\\int_{\\gamma-i\\infty}^{\\gamma+i\\infty}\\frac{e^{k(z-2z^{1/2})}}{z-c}\\,dz \\) (saddle \\( z_0=1 \\), \\( h(1)=-1 \\)) with \\( c \\) real and \\( 1<c<\\gamma \\), explain why a residue term now appears and give the leading asymptotic behaviour.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point method", "pole crossing", "residue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the pole relative to the saddle.", workingLatex: "\\text{pole at } z=c, \\quad 1 < c < \\gamma.", explanation: "The original contour is the vertical line \\( \\operatorname{Re} z = \\gamma \\), to the RIGHT of the pole. The pole now sits between the saddle \\( z_0=1 \\) and the contour." },
        { stepNumber: 2, description: "Deform onto the steepest-descent parabola.", workingLatex: "y^2 = 4(1-x) \\ \\text{(vertex at } z_0=1).", explanation: "To pick up the saddle we push the contour left onto the descent parabola through \\( z_0=1 \\); in doing so it sweeps across the pole at \\( z=c \\) (since \\( 1<c<\\gamma \\))." },
        { stepNumber: 3, description: "Account for the crossed pole by a residue.", workingLatex: "I(k) = 2\\pi i\\,\\operatorname{Res}_{z=c}\\frac{e^{k(z-2z^{1/2})}}{z-c} + I_{\\text{saddle}}(k).", explanation: "By the residue theorem, deforming a contour across a simple pole adds \\( 2\\pi i \\) times the residue (sign set by the leftward, i.e. clockwise-relative, crossing)." },
        { stepNumber: 4, description: "Evaluate the residue.", workingLatex: "\\operatorname{Res}_{z=c} = e^{k(c - 2c^{1/2})} = e^{-k(2\\sqrt{c} - c)}.", explanation: "The residue of \\( g(z)/(z-c) \\) at the simple pole is \\( g(c) = e^{k(c-2\\sqrt c)} \\). For \\( 1<c \\), \\( c - 2\\sqrt c > -1 \\), so this exponential is LARGER than the saddle's \\( e^{-k} \\)." },
        { stepNumber: 5, description: "Compare magnitudes.", workingLatex: "e^{k(c - 2\\sqrt c)} \\gg e^{-k}\\,k^{-1/2} \\quad\\text{since } c - 2\\sqrt c > -1 \\text{ for } c>1.", explanation: "Let \\( \\psi(c)=c-2\\sqrt c \\); \\( \\psi(1)=-1 \\) and \\( \\psi'(c)=1-1/\\sqrt c>0 \\) for \\( c>1 \\), so \\( \\psi(c)>-1 \\). The residue dominates the algebraically-corrected saddle term exponentially." },
        { stepNumber: 6, description: "State the leading behaviour.", workingLatex: "I(k) \\sim 2\\pi i\\,e^{-k(2\\sqrt c - c)}, \\qquad k\\to+\\infty.", explanation: "When the pole lies between the saddle and the original contour the residue is the dominant contribution; the saddle term \\( \\tfrac{2i\\sqrt\\pi}{(1-c)\\sqrt k}e^{-k} \\) is exponentially subdominant." },
      ],
      finalAnswer: "\\( I(k) \\sim 2\\pi i\\,e^{-k(2\\sqrt{c}-c)} \\) (residue dominates the saddle term).",
      canonicalAnswer: "2*pi*i*exp(-k*(2*sqrt(c)-c))",
    },
  },
  {
    id: "am7a-024",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( h(t) = i(t + t^2) \\) on the contour for \\( \\int_0^1 t^{-1/2} e^{i\\lambda(t+t^2)}\\,dt \\), \\( \\lambda\\to\\infty \\). The saddle \\( t=-\\tfrac12 \\) is off-range, so the integral is endpoint-dominated. Find the leading contribution from the endpoint \\( t=0 \\), including the effect of the \\( t^{-1/2} \\) singularity.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["endpoint contribution", "algebraic singularity", "steepest descent"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Localise near \\( t=0 \\).", workingLatex: "t + t^2 \\approx t, \\qquad I_0(\\lambda) \\approx \\int_0^{\\delta} t^{-1/2} e^{i\\lambda t}\\,dt.", explanation: "Near the lower endpoint the phase is \\( \\approx t \\) and the amplitude \\( t^{-1/2} \\) is singular; the contribution is controlled by this neighbourhood." },
        { stepNumber: 2, description: "Rotate onto the steepest-descent ray.", workingLatex: "t = \\frac{s}{\\lambda}\\,e^{i\\pi/2} = \\frac{is}{\\lambda}, \\quad s\\ge 0, \\qquad i\\lambda t = -s.", explanation: "The steepest-descent path from \\( t=0 \\) leaves vertically (\\( \\arg t = \\pi/2 \\)), turning the oscillatory \\( e^{i\\lambda t} \\) into the decaying \\( e^{-s} \\). This is the rotation that makes the endpoint integral convergent." },
        { stepNumber: 3, description: "Transform the measure and amplitude.", workingLatex: "t^{-1/2} = \\Big(\\frac{is}{\\lambda}\\Big)^{-1/2} = \\lambda^{1/2} s^{-1/2} e^{-i\\pi/4}, \\quad dt = \\frac{i}{\\lambda}\\,ds.", explanation: "Using \\( i^{-1/2} = e^{-i\\pi/4} \\) (principal branch). Collecting the \\( \\lambda \\)-powers: \\( \\lambda^{1/2}\\cdot\\lambda^{-1} = \\lambda^{-1/2} \\)." },
        { stepNumber: 4, description: "Assemble the gamma integral.", workingLatex: "I_0 \\sim e^{-i\\pi/4}\\,i\\,\\lambda^{-1/2}\\int_0^{\\infty} s^{-1/2} e^{-s}\\,ds.", explanation: "Combine \\( t^{-1/2}\\,dt = e^{-i\\pi/4}\\lambda^{1/2}s^{-1/2}\\cdot\\tfrac{i}{\\lambda}ds \\); extending the upper limit to \\( \\infty \\) costs only exponentially small error." },
        { stepNumber: 5, description: "Evaluate the gamma function.", workingLatex: "\\int_0^\\infty s^{-1/2}e^{-s}\\,ds = \\Gamma\\!\\big(\\tfrac12\\big) = \\sqrt{\\pi}.", explanation: "The standard value \\( \\Gamma(\\tfrac12) = \\sqrt\\pi \\)." },
        { stepNumber: 6, description: "Combine phases.", workingLatex: "i\\,e^{-i\\pi/4} = e^{i\\pi/2}e^{-i\\pi/4} = e^{i\\pi/4}.", explanation: "The factor \\( i \\) from \\( dt \\) and \\( e^{-i\\pi/4} \\) from \\( t^{-1/2} \\) combine to \\( e^{i\\pi/4} \\)." },
        { stepNumber: 7, description: "State the endpoint contribution.", workingLatex: "I_0(\\lambda) \\sim \\sqrt{\\frac{\\pi}{\\lambda}}\\,e^{i\\pi/4}.", explanation: "This \\( \\lambda^{-1/2} \\) decay is slower than the \\( \\lambda^{-1} \\) one would get from a non-singular endpoint, because the \\( t^{-1/2} \\) singularity strengthens the lower-endpoint contribution." },
      ],
      finalAnswer: "\\( I_0(\\lambda) \\sim \\sqrt{\\dfrac{\\pi}{\\lambda}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/lambda)*exp(i*pi/4)",
    },
  },
  {
    id: "am7a-025",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( I(x) = \\displaystyle\\int_0^\\infty e^{ix(\\frac13 t^3 + t)}\\,dt \\), \\( x\\to+\\infty \\). The saddles are at \\( t=\\pm i \\), off the contour. By rotating the contour onto the steepest-descent ray from \\( t=0 \\), find the leading term, and confirm it via integration by parts.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["endpoint contribution", "steepest descent", "integration by parts"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Phase and endpoint behaviour.", workingLatex: "h(t) = i\\big(\\tfrac13 t^3 + t\\big), \\quad h(0)=0, \\quad h'(0) = i.", explanation: "With saddles \\( \\pm i \\) unreachable, the leading contribution comes from the lower endpoint \\( t=0 \\), where the phase behaves like \\( e^{ixt} \\)." },
        { stepNumber: 2, description: "Rotate onto the descent ray.", workingLatex: "t = \\frac{is}{x}, \\quad s\\ge0: \\quad ix\\big(\\tfrac13 t^3 + t\\big) = -s + O(s^3/x^2).", explanation: "Near \\( t=0 \\) the descent ray is vertical (\\( \\arg t=\\pi/2 \\)); the cubic term is higher order in \\( 1/x \\) and does not affect the leading result." },
        { stepNumber: 3, description: "Reduce to a gamma integral.", workingLatex: "I(x) \\sim \\frac{i}{x}\\int_0^\\infty e^{-s}\\,ds = \\frac{i}{x}.", explanation: "With \\( dt = \\tfrac{i}{x}\\,ds \\) and amplitude \\( 1 \\), the integral becomes \\( \\tfrac ix\\Gamma(1) = \\tfrac ix \\)." },
        { stepNumber: 4, description: "Confirm by integration by parts.", workingLatex: "I(x) = \\int_0^\\infty \\frac{1}{ix(t^2+1)}\\,d\\big(e^{ix(\\frac13 t^3+t)}\\big).", explanation: "Write the integrand as \\( \\tfrac{1}{ix h'(t)} \\) times the derivative of the exponential, with \\( h'(t)=i(t^2+1) \\Rightarrow ix\\cdot\\tfrac{h'}{i} \\)... more directly, factor out \\( \\tfrac{1}{ix(t^2+1)} \\)." },
        { stepNumber: 5, description: "Take the boundary term.", workingLatex: "\\Big[\\frac{e^{ix(\\frac13 t^3+t)}}{ix(t^2+1)}\\Big]_0^\\infty = 0 - \\frac{1}{ix} = \\frac{i}{x}.", explanation: "The upper limit vanishes (oscillation + the \\( 1/t^2 \\) decay); the lower limit gives \\( -\\tfrac{1}{ix} = \\tfrac ix \\). The remaining integral is \\( O(x^{-2}) \\), so the boundary term is the leading order — agreeing with the steepest-descent rotation." },
      ],
      finalAnswer: "\\( I(x) \\sim \\dfrac{i}{x} \\) (confirmed by integration by parts).",
      canonicalAnswer: "i/x",
    },
  },
  {
    id: "am7a-026",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( h(t) = i\\big(t^3 - t\\big) \\) (so \\( \\int f(t)e^{ix(t^3-t)}\\,dt \\), as in Stokes' problem with \\( t^3-t \\) in place of \\( t^3 \\)... use \\( h(t)=i(t^3-t) \\)), find the saddle points, their curvatures, and the steepest-descent direction at each.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "Stokes problem", "descent direction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the saddles.", workingLatex: "h'(t) = i(3t^2 - 1) = 0 \\;\\implies\\; t = \\pm\\frac{1}{\\sqrt3}.", explanation: "Both saddles are real here (the phase \\( t^3 - t \\) has real stationary points), unlike the purely \\( t^3 \\) case; this is the structure behind Stokes' problem with two real stationary-phase points." },
        { stepNumber: 2, description: "Curvature at \\( t=+1/\\sqrt3 \\).", workingLatex: "h''(t) = 6it, \\quad h''\\!\\Big(\\tfrac{1}{\\sqrt3}\\Big) = \\frac{6i}{\\sqrt3} = 2\\sqrt3\\,i = 2\\sqrt3\\,e^{i\\pi/2}.", explanation: "Positive-imaginary curvature; argument \\( \\alpha = \\pi/2 \\)." },
        { stepNumber: 3, description: "Descent direction at \\( t=+1/\\sqrt3 \\).", workingLatex: "\\phi_+ = \\frac{\\pi - \\pi/2}{2} = \\frac{\\pi}{4}.", explanation: "Descent leaves this saddle at \\( 45^\\circ \\) (and \\( 225^\\circ \\)), tilting into the upper half-plane." },
        { stepNumber: 4, description: "Curvature at \\( t=-1/\\sqrt3 \\).", workingLatex: "h''\\!\\Big(-\\tfrac{1}{\\sqrt3}\\Big) = -2\\sqrt3\\,i = 2\\sqrt3\\,e^{-i\\pi/2}, \\quad \\alpha = -\\frac{\\pi}{2}.", explanation: "Negative-imaginary curvature at the second (left) saddle." },
        { stepNumber: 5, description: "Descent direction at \\( t=-1/\\sqrt3 \\).", workingLatex: "\\phi_- = \\frac{\\pi - (-\\pi/2)}{2} = \\frac{3\\pi}{4}.", explanation: "Descent leaves this saddle at \\( 135^\\circ \\) (and \\( -45^\\circ \\)). The two saddles, being a real pair with conjugate curvatures, contribute complex-conjugate stationary-phase terms whose sum is the leading real oscillatory behaviour." },
      ],
      finalAnswer: "Saddles \\( t=\\pm\\tfrac{1}{\\sqrt3} \\); \\( h''=\\pm2\\sqrt3\\,i \\); descent \\( \\phi_+=\\tfrac\\pi4,\\ \\phi_-=\\tfrac{3\\pi}{4} \\).",
    },
  },
  {
    id: "am7a-027",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The Gamma function admits \\( \\Gamma(x+1) = \\displaystyle\\int_0^\\infty e^{x\\ln t - t}\\,dt \\). By the substitution \\( t = x s \\), identify the saddle of the resulting phase, its curvature, and the steepest-descent direction, en route to Stirling's formula.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "Stirling", "Laplace phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale to expose the large parameter.", workingLatex: "t = xs:\\quad \\Gamma(x+1) = x^{x+1}\\int_0^\\infty e^{x(\\ln s - s)}\\,ds.", explanation: "With \\( \\ln t = \\ln x + \\ln s \\) and \\( dt = x\\,ds \\), the integral becomes \\( e^{x\\ln x}\\cdot x\\int e^{x(\\ln s - s)}ds \\); the phase \\( h(s) = \\ln s - s \\) now carries the large parameter \\( x \\) cleanly." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "h(s) = \\ln s - s, \\quad h'(s) = \\frac1s - 1 = 0 \\;\\implies\\; s_0 = 1.", explanation: "The (real) saddle is at \\( s_0 = 1 \\), i.e. \\( t = x \\): the integrand peaks where \\( t \\) equals the large parameter." },
        { stepNumber: 3, description: "Phase value and curvature.", workingLatex: "h(1) = -1, \\qquad h''(s) = -\\frac{1}{s^2}, \\quad h''(1) = -1.", explanation: "\\( h(1) = -1 \\) gives the factor \\( e^{-x} \\); \\( h''(1) = -1 < 0 \\) confirms a maximum of the real phase, a genuine descent point for Laplace's method." },
        { stepNumber: 4, description: "Descent direction.", workingLatex: "h''(1) = -1 = e^{i\\pi}, \\quad \\alpha = \\pi, \\quad \\phi = \\frac{\\pi - \\pi}{2} = 0.", explanation: "Real negative curvature: the steepest-descent path is along the real axis (\\( \\phi=0 \\)), which is exactly the original contour — no deformation needed, this is ordinary Laplace's method." },
        { stepNumber: 5, description: "Leading (Stirling) term.", workingLatex: "\\Gamma(x+1) \\sim x^{x+1}e^{-x}\\sqrt{\\frac{2\\pi}{x\\,|h''(1)|}} = \\sqrt{2\\pi x}\\;x^{x}e^{-x}.", explanation: "Apply the saddle formula with \\( g=1 \\), \\( |h''|=1 \\): \\( x^{x+1}e^{-x}\\sqrt{2\\pi/x} = \\sqrt{2\\pi x}\\,x^x e^{-x} \\). This is the leading Stirling approximation." },
      ],
      finalAnswer: "Saddle \\( s_0=1 \\), \\( h''(1)=-1 \\), descent along \\( \\phi=0 \\); \\( \\Gamma(x+1)\\sim\\sqrt{2\\pi x}\\,x^x e^{-x} \\).",
      canonicalAnswer: "sqrt(2*pi*x)*x^x*exp(-x)",
    },
  },
  {
    id: "am7a-028",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A phase \\( h(z) = e^{i\\beta} z^2 \\) (with \\( 0<\\beta<\\pi \\) a fixed constant) has a saddle at \\( z=0 \\). Find the steepest-descent direction \\( \\phi(\\beta) \\), and determine the value of \\( \\beta \\) for which the descent path coincides with the line \\( \\arg z = \\tfrac{\\pi}{6} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["descent direction", "parameter dependence", "choice of root sign"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Curvature and its argument.", workingLatex: "h''(z) = 2e^{i\\beta}, \\quad h''(0) = 2e^{i\\beta}, \\quad \\alpha = \\beta.", explanation: "The curvature argument is simply \\( \\beta \\); the descent geometry rotates with \\( \\beta \\)." },
        { stepNumber: 2, description: "Descent direction.", workingLatex: "\\phi = \\frac{\\pi - \\alpha}{2} = \\frac{\\pi - \\beta}{2} \\quad(\\text{and } \\phi + \\pi).", explanation: "From \\( 2\\phi + \\alpha = \\pi \\). As \\( \\beta \\) increases from \\( 0 \\) to \\( \\pi \\), the descent line swings from vertical (\\( \\pi/2 \\)) down to horizontal (\\( 0 \\))." },
        { stepNumber: 3, description: "Match to the required line.", workingLatex: "\\frac{\\pi - \\beta}{2} = \\frac{\\pi}{6} \\;\\implies\\; \\pi - \\beta = \\frac{\\pi}{3} \\;\\implies\\; \\beta = \\frac{2\\pi}{3}.", explanation: "Solve for \\( \\beta \\). One checks \\( 0<\\tfrac{2\\pi}{3}<\\pi \\), so it is admissible." },
        { stepNumber: 4, description: "Verify the sign / branch.", workingLatex: "\\beta = \\tfrac{2\\pi}{3}: \\ \\tfrac12 h''(0)z^2 = e^{i2\\pi/3}\\,r^2 e^{i\\pi/3} = r^2 e^{i\\pi} = -r^2 < 0.\\ \\checkmark", explanation: "Substituting \\( z = re^{i\\pi/6} \\) makes the quadratic real and negative, confirming \\( \\arg z = \\pi/6 \\) is genuinely the descent (not ascent) direction for \\( \\beta = 2\\pi/3 \\)." },
      ],
      finalAnswer: "\\( \\phi(\\beta) = \\tfrac{\\pi-\\beta}{2} \\); the descent path is \\( \\arg z = \\tfrac{\\pi}{6} \\) when \\( \\beta = \\tfrac{2\\pi}{3} \\).",
      canonicalAnswer: "beta = 2*pi/3",
    },
  },
  {
    id: "am7a-029",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that for the phase \\( h(z) = z^2 \\) the steepest-descent and steepest-ascent lines through the saddle \\( z=0 \\) are orthogonal, and prove the general result that at any simple saddle the descent and ascent directions always make an angle of \\( \\tfrac{\\pi}{4} \\) with each other... (correct: they bisect at \\( \\tfrac{\\pi}{4} \\)) — establish the true angle between adjacent descent and ascent lines.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["descent vs ascent", "orthogonality", "general result"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Descent and ascent for \\( h=z^2 \\).", workingLatex: "h''(0)=2,\\ \\alpha=0: \\quad \\text{descent } \\phi=\\tfrac\\pi2,\\tfrac{3\\pi}2; \\quad \\text{ascent } \\phi=0,\\pi.", explanation: "Descent solves \\( 2\\phi=\\pi \\), ascent solves \\( 2\\phi=0 \\). The descent lines are vertical, the ascent lines horizontal." },
        { stepNumber: 2, description: "Angle between them in this case.", workingLatex: "\\tfrac\\pi2 - 0 = \\tfrac\\pi2.", explanation: "The descent and ascent lines are at \\( 90^\\circ \\) — orthogonal. We now show this holds at every simple saddle." },
        { stepNumber: 3, description: "General descent and ascent conditions.", workingLatex: "\\text{descent: } 2\\phi_d + \\alpha = \\pi; \\qquad \\text{ascent: } 2\\phi_a + \\alpha = 0.", explanation: "With \\( \\alpha = \\arg h''(z_0) \\) the same for both, only the right-hand side differs by \\( \\pi \\)." },
        { stepNumber: 4, description: "Subtract.", workingLatex: "2(\\phi_d - \\phi_a) = \\pi \\;\\implies\\; \\phi_d - \\phi_a = \\frac{\\pi}{2}.", explanation: "The descent and ascent directions differ by exactly \\( \\tfrac{\\pi}{2} \\) for ANY \\( \\alpha \\): the level lines \\( \\operatorname{Re} h=\\text{const} \\) and \\( \\operatorname{Im} h=\\text{const} \\) of an analytic function cross orthogonally (Cauchy–Riemann)." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\boxed{\\ \\phi_d - \\phi_a = \\tfrac{\\pi}{2}\\ } \\quad\\text{(always orthogonal).}", explanation: "Hence the original premise of a \\( \\pi/4 \\) angle is FALSE; the correct, branch-independent result is orthogonality, a direct consequence of \\( h \\) being holomorphic. (The \\( \\pi/4 \\) figure is the angle each makes with the real axis only in the special case \\( \\alpha=\\pi/2 \\).)" },
      ],
      finalAnswer: "Descent and ascent lines are orthogonal: \\( \\phi_d - \\phi_a = \\tfrac{\\pi}{2} \\) at every simple saddle.",
      canonicalAnswer: "pi/2",
    },
  },
  {
    id: "am7a-030",
    topicRef: "am7a",
    topicTitle: "Saddle points & paths of steepest descent 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( I(x) = \\displaystyle\\int_{-\\infty}^{\\infty} e^{x(z^2 - z^4/4)}\\,dz \\) ... (the integrand grows; instead take) \\( I(x) = \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x(z^4/4 - z^2/2)}\\,dz \\), \\( x\\to+\\infty \\). Identify the relevant saddles on the real axis, decide which dominate, and give the leading two-saddle asymptotic.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple saddles", "competing saddles", "leading term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the phase.", workingLatex: "h(z) = -\\big(\\tfrac14 z^4 - \\tfrac12 z^2\\big), \\quad h'(z) = -(z^3 - z) = -z(z^2-1).", explanation: "We want \\( \\int e^{x h} \\) with \\( h \\) bounded above so the integral converges; \\( h'=0 \\) gives the saddles." },
        { stepNumber: 2, description: "Find the saddles.", workingLatex: "z = 0,\\ \\pm 1.", explanation: "Three real saddles. We compare \\( h \\) at each to see which control the leading asymptotics." },
        { stepNumber: 3, description: "Phase values.", workingLatex: "h(0) = 0, \\qquad h(\\pm1) = -\\big(\\tfrac14 - \\tfrac12\\big) = +\\tfrac14.", explanation: "The outer saddles have the LARGER \\( h \\) (\\( +\\tfrac14 > 0 \\)); since the contribution scales as \\( e^{xh} \\), the two saddles \\( z=\\pm1 \\) dominate exponentially over \\( z=0 \\)." },
        { stepNumber: 4, description: "Curvature at the dominant saddles.", workingLatex: "h''(z) = -(3z^2 - 1), \\quad h''(\\pm1) = -(3 - 1) = -2.", explanation: "Real negative curvature: each outer saddle is a maximum of \\( h \\) along the real axis, so descent is along the real axis (\\( \\phi=0 \\)) — the contour need not leave the real line." },
        { stepNumber: 5, description: "Single-saddle contribution.", workingLatex: "I_{\\pm1} \\sim e^{x h(\\pm1)}\\sqrt{\\frac{2\\pi}{x\\,|h''(\\pm1)|}} = e^{x/4}\\sqrt{\\frac{2\\pi}{2x}} = e^{x/4}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Laplace's formula at each maximum, with \\( g=1 \\), \\( |h''|=2 \\)." },
        { stepNumber: 6, description: "Add the two equal contributions.", workingLatex: "I(x) \\sim 2\\,e^{x/4}\\sqrt{\\frac{\\pi}{x}}.", explanation: "By the even symmetry \\( z\\mapsto -z \\), the two outer saddles contribute equally; their sum is twice one of them. The central saddle \\( z=0 \\) adds only an \\( O(1) \\) term, exponentially negligible." },
        { stepNumber: 7, description: "State the leading asymptotic.", workingLatex: "I(x) \\sim 2\\sqrt{\\frac{\\pi}{x}}\\,e^{x/4}, \\qquad x\\to+\\infty.", explanation: "Two real maxima of equal height combine to give twice the single-saddle Laplace contribution — the canonical 'two competing dominant saddles' result." },
      ],
      finalAnswer: "\\( I(x) \\sim 2\\sqrt{\\dfrac{\\pi}{x}}\\,e^{x/4} \\) (the saddles \\( z=\\pm1 \\) dominate).",
      canonicalAnswer: "2*sqrt(pi/x)*exp(x/4)",
    },
  },
];
