import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — am7b "Leading-order steepest descent"
 * Topic group: Method of Steepest Descent I
 * Scope: deform the contour onto a saddle, replace the integrand by a local
 * Gaussian, and read off the leading term. Worked exemplar: the Cambridge Part II
 * Asymptotic Methods Example Sheet 2 result
 *   f(theta) = (1/2 pi i) ∫_C exp(theta(t + t^3/3)) dt
 *            ~ (pi theta)^{-1/2} cos(2 theta/3 - pi/4).
 *
 * Seeded from DAMTP Asymptotic Methods Example Sheet 2 (Michaelmas 2025),
 * questions 5, 7, 8, 9 (steepest descent / stationary phase), with constants,
 * limits and framing varied. Leading-order Gaussian integrals
 *   ∫_{-∞}^{∞} e^{-a t^2} dt = sqrt(pi/a)   and   ∫_{-∞}^{∞} e^{i x t^2} dt = sqrt(pi/x) e^{i pi/4}
 * are the workhorses; each closed-form leading coefficient below was checked
 * numerically with mpmath (contour-rotation Fresnel + saddle amplitude checks).
 */
export const questions: Question[] = [
  // ──────────────────────────────────────────────────────────────────
  // FOUNDATION (6) — the core Gaussian / saddle move in isolation, 2 marks
  // ──────────────────────────────────────────────────────────────────
  {
    id: "am7b-001",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 01",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Gaussian integral \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-a t^2}\\,dt \\) for \\( a>0 \\). This is the local integral that appears once a steepest-descent contour has been straightened at a saddle.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian integral", "saddle point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the unit Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-u^2}\\,du = \\sqrt{\\pi}.", explanation: "This is the standard result obtained by squaring the integral and passing to polar coordinates." },
        { stepNumber: 2, description: "Rescale to introduce \\( a \\).", workingLatex: "u = \\sqrt{a}\\,t, \\qquad du = \\sqrt{a}\\,dt.", explanation: "After a saddle is straightened the curvature \\( a = \\tfrac12|\\phi''| \\) sets the width of the Gaussian, so we absorb it by rescaling." },
        { stepNumber: 3, description: "Substitute and read off the value.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a t^2}\\,dt = \\frac{1}{\\sqrt{a}}\\int_{-\\infty}^{\\infty} e^{-u^2}\\,du = \\sqrt{\\frac{\\pi}{a}}.", explanation: "The factor \\( a^{-1/2} \\) is precisely where the \\( \\theta^{-1/2} \\) prefactor of a leading-order steepest-descent estimate comes from." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-a t^2}\\,dt = \\sqrt{\\dfrac{\\pi}{a}} \\)",
      canonicalAnswer: "sqrt(pi/a)",
    },
  },
  {
    id: "am7b-002",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 02",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "By rotating the contour onto the steepest-descent ray, evaluate the Fresnel-type integral \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "Fresnel integral", "contour rotation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the steepest-descent direction.", workingLatex: "i x t^2 = -x\\,(e^{-i\\pi/4} t)^2 \\cdot(-1)\\;\\Rightarrow\\; t = e^{i\\pi/4} u.", explanation: "Writing \\( i = e^{i\\pi/2} \\), the phase \\( i x t^2 \\) becomes real and negative along the ray \\( \\arg t = \\pi/4 \\); that ray is the path of steepest descent through the saddle at \\( t=0 \\)." },
        { stepNumber: 2, description: "Substitute the rotated variable.", workingLatex: "t = e^{i\\pi/4} u,\\quad dt = e^{i\\pi/4}\\,du,\\quad i x t^2 = i x\\, e^{i\\pi/2} u^2 = -x u^2.", explanation: "Cauchy's theorem lets us swing the contour from the real axis onto this ray because the integrand is entire and decays in the connecting sectors." },
        { stepNumber: 3, description: "Reduce to a real Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,dt = e^{i\\pi/4}\\int_{-\\infty}^{\\infty} e^{-x u^2}\\,du = e^{i\\pi/4}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The \\( e^{i\\pi/4} \\) phase is the hallmark of a real stationary point of a purely oscillatory integral." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,dt = \\sqrt{\\dfrac{\\pi}{x}}\\;e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(i*pi/4)",
    },
  },
  {
    id: "am7b-003",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the value of the half-line stationary-phase integral \\( \\displaystyle\\int_{0}^{\\infty} \\cos\\!\\big(x t^2\\big)\\,dt \\) for \\( x>0 \\), the building block for an endpoint at a stationary point.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["stationary phase", "Fresnel integral", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the cosine as a real part.", workingLatex: "\\int_{0}^{\\infty}\\cos(x t^2)\\,dt = \\operatorname{Re}\\int_{0}^{\\infty} e^{\\,i x t^2}\\,dt.", explanation: "Real oscillatory integrals are handled by complexifying and taking the real part at the end." },
        { stepNumber: 2, description: "Use the rotated Gaussian on the half-line.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x t^2}\\,dt = e^{i\\pi/4}\\int_{0}^{\\infty} e^{-x u^2}\\,du = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\;e^{i\\pi/4}.", explanation: "The half-line gives exactly half the full-line Fresnel value found in the previous question." },
        { stepNumber: 3, description: "Take the real part.", workingLatex: "\\operatorname{Re}\\!\\left[\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}\\right] = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\cdot\\frac{1}{\\sqrt 2} = \\sqrt{\\frac{\\pi}{8x}}.", explanation: "Since \\( \\cos(\\pi/4)=1/\\sqrt2 \\) the \\( \\sqrt2 \\) folds the \\( 2 \\) into an \\( 8 \\) under the root." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{0}^{\\infty}\\cos(x t^2)\\,dt = \\sqrt{\\dfrac{\\pi}{8x}} \\)",
      canonicalAnswer: "sqrt(pi/(8*x))",
    },
  },
  {
    id: "am7b-004",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 04",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Locate the saddle point of the phase \\( \\phi(t) = t - \\tfrac13 t^3 \\) on the real axis and state the local quadratic approximation of \\( \\phi \\) there.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["saddle point", "steepest descent", "local expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "\\phi'(t) = 1 - t^2.", explanation: "Saddle points are the stationary points of the exponent; this is where the steepest-descent analysis is centred." },
        { stepNumber: 2, description: "Solve for the saddles.", workingLatex: "1 - t^2 = 0 \\;\\Longrightarrow\\; t = \\pm 1.", explanation: "There are two real saddles; we expand about the relevant one, here \\( t_0 = 1 \\)." },
        { stepNumber: 3, description: "Compute the curvature.", workingLatex: "\\phi''(t) = -2t,\\qquad \\phi''(1) = -2,\\qquad \\phi(1) = 1 - \\tfrac13 = \\tfrac23.", explanation: "The second derivative fixes the width and orientation of the local Gaussian." },
        { stepNumber: 4, description: "Write the local quadratic.", workingLatex: "\\phi(t) \\approx \\frac{2}{3} - (t-1)^2 \\quad\\text{near } t=1.", explanation: "Substituting \\( \\phi(1)=\\tfrac23 \\) and \\( \\tfrac12\\phi''(1)=-1 \\) into the Taylor form \\( \\phi(t_0)+\\tfrac12\\phi''(t_0)(t-t_0)^2 \\)." },
      ],
      finalAnswer: "\\( t_0 = 1 \\), with \\( \\phi(t)\\approx \\tfrac23 - (t-1)^2 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am7b-005",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 05",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Given a single non-degenerate saddle at \\( t_0 \\) with \\( \\phi''(t_0) < 0 \\), state the leading-order steepest-descent estimate of \\( \\displaystyle\\int_C g(t)\\,e^{\\lambda\\phi(t)}\\,dt \\) as \\( \\lambda\\to\\infty \\), assuming \\( g(t_0)\\neq 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle point formula", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand the exponent about the saddle.", workingLatex: "\\phi(t) \\approx \\phi(t_0) + \\tfrac12\\phi''(t_0)(t-t_0)^2.", explanation: "On the steepest-descent contour the quadratic term is real and negative, so the integrand is a sharp Gaussian as \\( \\lambda\\to\\infty \\)." },
        { stepNumber: 2, description: "Freeze the slowly-varying factor.", workingLatex: "g(t) \\approx g(t_0).", explanation: "Only a neighbourhood of width \\( \\lambda^{-1/2} \\) contributes, over which \\( g \\) is essentially constant." },
        { stepNumber: 3, description: "Do the Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\frac{\\lambda}{2}\\phi''(t_0)\\,s^2}\\,ds = \\sqrt{\\frac{2\\pi}{\\lambda\\,|\\phi''(t_0)|}}.", explanation: "Here \\( s=t-t_0 \\) runs along the descent direction and \\( \\phi''(t_0)<0 \\) guarantees convergence." },
        { stepNumber: 4, description: "Assemble the estimate.", workingLatex: "\\int_C g(t)\\,e^{\\lambda\\phi(t)}\\,dt \\sim g(t_0)\\,e^{\\lambda\\phi(t_0)}\\sqrt{\\frac{2\\pi}{\\lambda\\,|\\phi''(t_0)|}}.", explanation: "This is the master leading-order formula; the \\( \\lambda^{-1/2} \\) decay is universal for a non-degenerate saddle." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim g(t_0)\\,e^{\\lambda\\phi(t_0)}\\sqrt{\\dfrac{2\\pi}{\\lambda\\,|\\phi''(t_0)|}} \\)",
      canonicalAnswer: "g0*exp(lambda*phi0)*sqrt(2*pi/(lambda*abs(phi2)))",
    },
  },
  {
    id: "am7b-006",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 06",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x(t^2 - 2 t)}\\,dt \\) for \\( x>0 \\) by completing the square, the move that recentres a contour on its saddle.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "completing the square", "Gaussian integral"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complete the square in the exponent.", workingLatex: "t^2 - 2t = (t-1)^2 - 1.", explanation: "The shift moves the maximum of the integrand to the saddle \\( t=1 \\), exactly the recentring step of steepest descent." },
        { stepNumber: 2, description: "Factor out the saddle value.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x((t-1)^2 - 1)}\\,dt = e^{x}\\int_{-\\infty}^{\\infty} e^{-x(t-1)^2}\\,dt.", explanation: "The constant \\( e^{x} \\) is the exponential of the phase evaluated at the saddle." },
        { stepNumber: 3, description: "Apply the Gaussian result.", workingLatex: "e^{x}\\int_{-\\infty}^{\\infty} e^{-x s^2}\\,ds = e^{x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "With \\( s=t-1 \\) this is the standard Gaussian; the answer is exact because the exponent is purely quadratic." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x(t^2 - 2 t)}\\,dt = e^{x}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  // ──────────────────────────────────────────────────────────────────
  // STANDARD (12) — typical sheet-level, 3–4 marks, examStyle true
  // ──────────────────────────────────────────────────────────────────
  {
    id: "am7b-007",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 07",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Use the method of steepest descent to find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x(t^2-1)^2/2}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "two saddles", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the phase and its saddles.", workingLatex: "\\phi(t) = -\\tfrac12(t^2-1)^2,\\qquad \\phi'(t) = -2t(t^2-1).", explanation: "The minima of \\( (t^2-1)^2 \\) are the maxima of the integrand, hence the dominant saddles." },
        { stepNumber: 2, description: "Solve for the maxima.", workingLatex: "\\phi'(t)=0 \\Rightarrow t = 0,\\ \\pm 1; \\quad \\phi(\\pm1)=0,\\ \\phi(0)=-\\tfrac12.", explanation: "The two saddles \\( t=\\pm1 \\) sit at the maximum value \\( \\phi=0 \\); \\( t=0 \\) is exponentially subdominant." },
        { stepNumber: 3, description: "Compute the curvature at \\( t=1 \\).", workingLatex: "\\phi''(t) = -2(3t^2-1),\\qquad \\phi''(\\pm1) = -4.", explanation: "Both maxima are non-degenerate with the same curvature, so they contribute equally." },
        { stepNumber: 4, description: "Apply the saddle formula at one maximum.", workingLatex: "\\int_{\\text{near }1} e^{x\\phi}\\,dt \\sim e^{0}\\sqrt{\\frac{2\\pi}{x\\cdot 4}} = \\sqrt{\\frac{\\pi}{2x}}.", explanation: "Each Gaussian peak contributes \\( \\sqrt{2\\pi/(x|\\phi''|)} \\)." },
        { stepNumber: 5, description: "Add the two equal contributions.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x(t^2-1)^2/2}\\,dt \\sim 2\\sqrt{\\frac{\\pi}{2x}} = \\sqrt{\\frac{2\\pi}{x}}.", explanation: "The two symmetric maxima both lie at height \\( \\phi=0 \\), so neither dominates and we sum them." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{2\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(2*pi/x)",
    },
  },
  {
    id: "am7b-008",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 08",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading term, as \\( x\\to+\\infty \\), of the oscillatory integral \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i x (t^2 + 2 t)}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "completing the square", "steepest descent"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complete the square in the phase.", workingLatex: "t^2 + 2t = (t+1)^2 - 1.", explanation: "The stationary point of the phase sits at \\( t=-1 \\)." },
        { stepNumber: 2, description: "Pull out the stationary value.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x((t+1)^2-1)}\\,dt = e^{-i x}\\int_{-\\infty}^{\\infty} e^{\\,i x (t+1)^2}\\,dt.", explanation: "The factor \\( e^{-ix} \\) is \\( e^{ix\\phi(t_0)} \\) with \\( \\phi(-1)=-1 \\)." },
        { stepNumber: 3, description: "Apply the Fresnel result.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x s^2}\\,ds = \\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}.", explanation: "Rotating onto the \\( \\arg s=\\pi/4 \\) ray turns the integral into a real Gaussian; here the result is exact." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x (t^2+2t)}\\,dt = \\sqrt{\\frac{\\pi}{x}}\\,e^{i(\\pi/4 - x)}.", explanation: "The stationary-phase phase \\( -x \\) and the universal \\( \\pi/4 \\) combine in the exponent." },
      ],
      finalAnswer: "\\( \\displaystyle \\sqrt{\\dfrac{\\pi}{x}}\\;e^{i(\\pi/4 - x)} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(i*(pi/4 - x))",
    },
  },
  {
    id: "am7b-009",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 09",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Determine the leading-order asymptotics, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} \\cos\\!\\big(x(t^2+2t)\\big)\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "real oscillatory integral", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pass to the complex exponential.", workingLatex: "\\int_{-\\infty}^{\\infty}\\cos\\!\\big(x(t^2+2t)\\big)\\,dt = \\operatorname{Re}\\int_{-\\infty}^{\\infty} e^{\\,i x(t^2+2t)}\\,dt.", explanation: "Stationary phase is cleanest on the complex form." },
        { stepNumber: 2, description: "Reuse the completed-square result.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x(t^2+2t)}\\,dt = \\sqrt{\\frac{\\pi}{x}}\\,e^{i(\\pi/4 - x)}.", explanation: "Stationary point at \\( t=-1 \\), phase value \\( -1 \\), and the \\( e^{i\\pi/4} \\) Fresnel factor." },
        { stepNumber: 3, description: "Take the real part.", workingLatex: "\\operatorname{Re}\\!\\left[\\sqrt{\\frac{\\pi}{x}}\\,e^{i(\\pi/4 - x)}\\right] = \\sqrt{\\frac{\\pi}{x}}\\,\\cos\\!\\Big(\\frac{\\pi}{4}-x\\Big).", explanation: "Only the cosine of the combined phase survives." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{\\pi}{x}}\\,\\cos\\!\\Big(x-\\dfrac{\\pi}{4}\\Big) \\)",
      canonicalAnswer: "sqrt(pi/x)*cos(x - pi/4)",
    },
  },
  {
    id: "am7b-010",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 10",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Apply the method of steepest descent to obtain the leading term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} \\frac{e^{-x(t^2-2t)}}{1+t^2}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "slowly varying prefactor", "saddle point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate phase and prefactor.", workingLatex: "\\phi(t) = -(t^2-2t),\\qquad g(t) = \\frac{1}{1+t^2}.", explanation: "The exponential controls the asymptotics; \\( g \\) is the slowly-varying amplitude." },
        { stepNumber: 2, description: "Find the saddle.", workingLatex: "\\phi'(t) = -(2t-2) = 0 \\Rightarrow t_0 = 1,\\quad \\phi(1) = 1.", explanation: "The maximum of the exponent is at \\( t=1 \\)." },
        { stepNumber: 3, description: "Curvature and prefactor value.", workingLatex: "\\phi''(t) = -2,\\qquad g(1) = \\frac{1}{2}.", explanation: "Non-degenerate maximum; freeze \\( g \\) at the saddle." },
        { stepNumber: 4, description: "Insert into the saddle formula.", workingLatex: "\\int \\sim g(1)\\,e^{x\\phi(1)}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(1)|}} = \\frac{1}{2}\\,e^{x}\\sqrt{\\frac{2\\pi}{2x}}.", explanation: "Apply \\( g(t_0)e^{x\\phi(t_0)}\\sqrt{2\\pi/(x|\\phi''|)} \\)." },
        { stepNumber: 5, description: "Simplify.", workingLatex: "\\frac{1}{2}\\,e^{x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "\\( \\sqrt{2\\pi/(2x)} = \\sqrt{\\pi/x} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\frac{e^{x}}{2}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "(1/2)*exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am7b-011",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 11",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order steepest-descent estimate, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,x(2t - t^2)}\\,t^2\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle point", "polynomial prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Read off phase and amplitude.", workingLatex: "\\phi(t) = 2t - t^2,\\qquad g(t) = t^2.", explanation: "The exponent peaks where \\( \\phi \\) is maximal." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "\\phi'(t) = 2 - 2t = 0 \\Rightarrow t_0 = 1,\\quad \\phi(1) = 1.", explanation: "Single non-degenerate maximum at \\( t=1 \\)." },
        { stepNumber: 3, description: "Curvature and prefactor.", workingLatex: "\\phi''(t) = -2,\\qquad g(1) = 1.", explanation: "Evaluate the amplitude at the saddle: \\( g(1)=1^2=1 \\)." },
        { stepNumber: 4, description: "Assemble the leading term.", workingLatex: "\\int \\sim g(1)\\,e^{x}\\sqrt{\\frac{2\\pi}{x\\cdot 2}} = e^{x}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The \\( t^2 \\) factor contributes only its value at \\( t=1 \\) at leading order." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim e^{x}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am7b-012",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 12",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The phase \\( \\phi(t) = i\\big(t + \\tfrac13 t^3\\big) \\) has saddles where \\( \\phi'=0 \\). Find the saddle points, the value of \\( \\phi \\) at each, and the curvature \\( \\phi'' \\) there.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["saddle point", "steepest descent", "complex phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "\\phi'(t) = i\\,(1 + t^2).", explanation: "Saddles are the roots of \\( \\phi'(t)=0 \\)." },
        { stepNumber: 2, description: "Solve for the saddles.", workingLatex: "1 + t^2 = 0 \\Rightarrow t = \\pm i.", explanation: "The saddles are purely imaginary, off the original real contour, so the contour must be deformed onto them." },
        { stepNumber: 3, description: "Evaluate the phase at each saddle.", workingLatex: "\\phi(i) = i\\big(i + \\tfrac13 i^3\\big) = i\\big(i - \\tfrac13 i\\big) = i\\cdot\\tfrac23 i = -\\tfrac23,\\quad \\phi(-i) = -\\tfrac23.", explanation: "Both give the real value \\( -\\tfrac23 \\); a real negative exponent means genuine exponential decay along the descent paths." },
        { stepNumber: 4, description: "Compute the curvature.", workingLatex: "\\phi''(t) = 2 i t,\\qquad \\phi''(i) = -2,\\qquad \\phi''(-i) = 2.", explanation: "The curvatures are real with opposite sign, fixing the orientation of the local Gaussian on each descent path." },
      ],
      finalAnswer: "\\( t=\\pm i;\\ \\phi(\\pm i)=-\\tfrac23;\\ \\phi''(i)=-2,\\ \\phi''(-i)=2 \\)",
      canonicalAnswer: "i,-i",
    },
  },
  {
    id: "am7b-013",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 13",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( \\lambda\\to\\infty \\), of the endpoint-dominated integral \\( \\displaystyle\\int_{0}^{\\infty} t^{-1/2}\\,e^{\\,i\\lambda t}\\,dt \\). (This is the algebraic-endpoint contribution that appears in steepest-descent problems with a branch point at an endpoint.)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["endpoint contribution", "branch point", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rotate the contour onto the descent ray.", workingLatex: "t = \\frac{s}{-i\\lambda}\\cdot(-1)\\;\\Rightarrow\\; \\text{set } i\\lambda t = -s,\\ t = \\frac{s}{\\lambda}e^{i\\pi/2}.", explanation: "Writing \\( i = e^{i\\pi/2} \\), the substitution \\( i\\lambda t = -s \\) sends the phase to \\( e^{-s} \\) along the rotated ray, the steepest-descent path from the endpoint." },
        { stepNumber: 2, description: "Transform the integral.", workingLatex: "\\int_{0}^{\\infty} t^{-1/2}e^{\\,i\\lambda t}\\,dt = \\Big(\\frac{e^{i\\pi/2}}{\\lambda}\\Big)^{1/2}\\int_{0}^{\\infty} s^{-1/2}e^{-s}\\,ds.", explanation: "Each factor of \\( t \\) carries the rotation \\( e^{i\\pi/2}/\\lambda \\); the \\( t^{-1/2} \\) gives the half-power of that factor." },
        { stepNumber: 3, description: "Recognise the Gamma integral.", workingLatex: "\\int_{0}^{\\infty} s^{-1/2}e^{-s}\\,ds = \\Gamma\\!\\Big(\\tfrac12\\Big) = \\sqrt{\\pi}.", explanation: "This is the defining integral of \\( \\Gamma(1/2) \\)." },
        { stepNumber: 4, description: "Collect the phase and prefactor.", workingLatex: "\\Big(\\frac{e^{i\\pi/2}}{\\lambda}\\Big)^{1/2}\\sqrt{\\pi} = \\sqrt{\\frac{\\pi}{\\lambda}}\\;e^{i\\pi/4}.", explanation: "The half of \\( e^{i\\pi/2} \\) is the familiar \\( e^{i\\pi/4} \\); since the exponent is exactly linear the result is exact, not just leading order." },
      ],
      finalAnswer: "\\( \\displaystyle\\int_{0}^{\\infty} t^{-1/2}e^{\\,i\\lambda t}\\,dt = \\sqrt{\\dfrac{\\pi}{\\lambda}}\\;e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/lambda)*exp(i*pi/4)",
    },
  },
  {
    id: "am7b-014",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 14",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Use steepest descent to find the leading term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,e^{-t^2}\\,dt \\). Treat \\( x\\to\\infty \\) and keep the genuine large-parameter contribution.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "Gaussian damping", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Combine the exponents.", workingLatex: "i x t^2 - t^2 = -(1 - i x)\\,t^2.", explanation: "Both factors are quadratic, so the whole integrand is a single complex Gaussian." },
        { stepNumber: 2, description: "Apply the complex Gaussian formula.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-(1-i x)t^2}\\,dt = \\sqrt{\\frac{\\pi}{\\,1 - i x\\,}}.", explanation: "Valid since \\( \\operatorname{Re}(1-ix)=1>0 \\); the principal branch of the root is taken." },
        { stepNumber: 3, description: "Take the large-\\( x \\) limit.", workingLatex: "1 - i x \\sim -i x = x\\,e^{-i\\pi/2}\\quad (x\\to\\infty).", explanation: "The constant \\( 1 \\) is negligible against \\( ix \\) at leading order." },
        { stepNumber: 4, description: "Read off the leading term.", workingLatex: "\\sqrt{\\frac{\\pi}{x\\,e^{-i\\pi/2}}} = \\sqrt{\\frac{\\pi}{x}}\\;e^{i\\pi/4}.", explanation: "Half of the phase \\( +i\\pi/2 \\) gives \\( e^{i\\pi/4} \\): the damping makes the stationary-phase value rigorous." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{\\pi}{x}}\\;e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(i*pi/4)",
    },
  },
  {
    id: "am7b-015",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 15",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order asymptotics, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{0}^{\\infty} e^{-x\\,t^2}\\cos t\\,dt \\) and comment on why the \\( \\cos t \\) factor only contributes its value at the endpoint.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace/steepest descent", "endpoint maximum", "half Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the dominant point.", workingLatex: "\\phi(t) = -t^2 \\text{ is maximal at the endpoint } t=0.", explanation: "On \\( [0,\\infty) \\) the exponent peaks at the lower limit, so this is an endpoint contribution, not an interior saddle." },
        { stepNumber: 2, description: "Freeze the amplitude at the endpoint.", workingLatex: "\\cos t \\to \\cos 0 = 1 \\quad (t\\to 0).", explanation: "The Gaussian confines the integral to \\( t = O(x^{-1/2}) \\), where \\( \\cos t \\approx 1 \\)." },
        { stepNumber: 3, description: "Do the half-line Gaussian.", workingLatex: "\\int_{0}^{\\infty} e^{-x t^2}\\,dt = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "The endpoint maximum captures only half a Gaussian, hence the factor \\( \\tfrac12 \\)." },
        { stepNumber: 4, description: "Combine.", workingLatex: "\\int_{0}^{\\infty} e^{-x t^2}\\cos t\\,dt \\sim \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}.", explanation: "Higher Taylor terms of \\( \\cos t \\) give only \\( O(x^{-3/2}) \\) corrections." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "(1/2)*sqrt(pi/x)",
    },
  },
  {
    id: "am7b-016",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 16",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For \\( x\\to+\\infty \\), find the leading term of \\( \\displaystyle\\int_{0}^{\\infty} \\cos\\!\\big(x\\,t^3\\big)\\,dt \\). (A cubic endpoint stationary point.)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "degenerate endpoint", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complexify.", workingLatex: "\\int_{0}^{\\infty}\\cos(x t^3)\\,dt = \\operatorname{Re}\\int_{0}^{\\infty} e^{\\,i x t^3}\\,dt.", explanation: "Real oscillatory integral handled via its complex form." },
        { stepNumber: 2, description: "Rotate onto the descent ray.", workingLatex: "i x t^3 = -s \\Rightarrow t = \\Big(\\frac{s}{x}\\Big)^{1/3} e^{i\\pi/6},\\quad dt = \\frac{e^{i\\pi/6}}{3}\\Big(\\frac{1}{x}\\Big)^{1/3} s^{-2/3}\\,ds.", explanation: "For \\( t^3 \\) the steepest-descent ray makes angle \\( \\pi/6 \\); the substitution turns the phase into \\( e^{-s} \\)." },
        { stepNumber: 3, description: "Reduce to a Gamma integral.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x t^3}\\,dt = \\frac{e^{i\\pi/6}}{3}\\,x^{-1/3}\\int_{0}^{\\infty} s^{-2/3}e^{-s}\\,ds = \\frac{e^{i\\pi/6}}{3}\\,x^{-1/3}\\,\\Gamma\\!\\Big(\\tfrac13\\Big).", explanation: "Here \\( \\int_0^\\infty s^{-2/3}e^{-s}\\,ds = \\Gamma(1/3) \\)." },
        { stepNumber: 4, description: "Tidy the prefactor.", workingLatex: "\\frac{1}{3}\\Gamma\\!\\Big(\\tfrac13\\Big) = \\frac{1}{3}\\cdot 3\\,\\Gamma\\!\\Big(\\tfrac43\\Big)\\cdot\\frac{1}{?}\\;\\Rightarrow\\; \\frac{1}{3}\\Gamma\\!\\Big(\\tfrac13\\Big)=\\Gamma\\!\\Big(\\tfrac43\\Big).", explanation: "Using \\( \\Gamma(4/3)=\\tfrac13\\Gamma(1/3) \\) from \\( \\Gamma(z+1)=z\\Gamma(z) \\)." },
        { stepNumber: 5, description: "Take the real part.", workingLatex: "\\int_{0}^{\\infty}\\cos(x t^3)\\,dt = \\Gamma\\!\\Big(\\tfrac43\\Big)\\,x^{-1/3}\\cos\\frac{\\pi}{6} = \\frac{\\sqrt3}{2}\\,\\Gamma\\!\\Big(\\tfrac43\\Big)\\,x^{-1/3}.", explanation: "\\( \\cos(\\pi/6)=\\sqrt3/2 \\); the slower \\( x^{-1/3} \\) decay reflects the cubic flatness at the endpoint." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\frac{\\sqrt3}{2}\\,\\Gamma\\!\\Big(\\tfrac43\\Big)\\,x^{-1/3} \\)",
      canonicalAnswer: "(sqrt(3)/2)*gamma(4/3)*x^(-1/3)",
    },
  },
  {
    id: "am7b-017",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 17",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x\\cosh t}\\,dt \\) using steepest descent about the saddle on the real axis.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "cosh phase", "saddle point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the phase.", workingLatex: "\\phi(t) = -\\cosh t,\\qquad \\phi'(t) = -\\sinh t.", explanation: "The integrand is largest where \\( \\cosh t \\) is smallest." },
        { stepNumber: 2, description: "Find the saddle.", workingLatex: "\\sinh t = 0 \\Rightarrow t_0 = 0,\\quad \\phi(0) = -1.", explanation: "Single minimum of \\( \\cosh \\) at the origin." },
        { stepNumber: 3, description: "Compute curvature.", workingLatex: "\\phi''(t) = -\\cosh t,\\qquad \\phi''(0) = -1.", explanation: "Non-degenerate maximum of the exponent." },
        { stepNumber: 4, description: "Apply the saddle formula.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-x\\cosh t}\\,dt \\sim e^{-x}\\sqrt{\\frac{2\\pi}{x\\cdot 1}} = \\sqrt{\\frac{2\\pi}{x}}\\;e^{-x}.", explanation: "This reproduces the known leading behaviour of \\( 2K_0(x) \\) as \\( x\\to\\infty \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{2\\pi}{x}}\\;e^{-x} \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(-x)",
    },
  },
  {
    id: "am7b-018",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 18",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order asymptotics, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,e^{-t^4}\\,dt \\). The smooth weight \\( e^{-t^4} \\) is non-singular at the stationary point \\( t=0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "smooth prefactor", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the stationary point.", workingLatex: "\\phi(t)=t^2,\\quad \\phi'(t)=2t = 0 \\Rightarrow t_0 = 0.", explanation: "The oscillatory phase \\( x t^2 \\) is stationary only at \\( t=0 \\); the weight \\( g(t)=e^{-t^4} \\) is smooth there with \\( g(0)=1 \\)." },
        { stepNumber: 2, description: "Localise and freeze the weight.", workingLatex: "g(t)=e^{-t^4} \\to 1 \\quad\\text{on the window } t = O(x^{-1/2}).", explanation: "As \\( x\\to\\infty \\) the contribution comes from \\( |t|\\lesssim x^{-1/2} \\), where \\( t^4 = O(x^{-2})\\to 0 \\), so the weight is asymptotically \\( 1 \\)." },
        { stepNumber: 3, description: "Reduce to the Fresnel integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,e^{-t^4}\\,dt \\sim \\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,dt.", explanation: "Replace the weight by its value at the stationary point at leading order." },
        { stepNumber: 4, description: "Apply the rotated Gaussian.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x t^2}\\,dt = \\sqrt{\\frac{\\pi}{x}}\\;e^{i\\pi/4}.", explanation: "Rotate onto the \\( \\arg t=\\pi/4 \\) descent ray; the quartic weight only modifies higher-order terms." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{\\pi}{x}}\\;e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(i*pi/4)",
    },
  },
  // ──────────────────────────────────────────────────────────────────
  // CHALLENGE (12) — synoptic / starred-level / cross-method, 5+ marks
  // ──────────────────────────────────────────────────────────────────
  {
    id: "am7b-019",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 19",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For \\( \\theta>0 \\) define \\( \\displaystyle f(\\theta) = \\frac{1}{2\\pi i}\\int_{C} \\exp\\!\\Big(\\theta\\big(t + \\tfrac13 t^3\\big)\\Big)\\,dt \\), where \\( C \\) runs from \\( \\infty \\) in \\( -\\tfrac{\\pi}{2}<\\arg t<-\\tfrac{\\pi}{6} \\) to \\( \\infty \\) in \\( \\tfrac{\\pi}{6}<\\arg t<\\tfrac{\\pi}{2} \\). Show that, as \\( \\theta\\to\\infty \\), \\( f(\\theta) \\sim (\\pi\\theta)^{-1/2}\\cos\\!\\big(\\tfrac{2}{3}\\theta - \\tfrac{\\pi}{4}\\big) \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "two saddles", "Airy-type", "exemplar"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the saddles.", workingLatex: "\\phi(t)=t+\\tfrac13 t^3,\\quad \\phi'(t)=1+t^2=0 \\Rightarrow t=\\pm i.", explanation: "Both saddles are purely imaginary; the prescribed contour can be deformed to pass through them along steepest-descent paths." },
        { stepNumber: 2, description: "Evaluate the phase at the saddles.", workingLatex: "\\phi(i)=i+\\tfrac13 i^3 = i-\\tfrac13 i = \\tfrac23 i,\\qquad \\phi(-i)=-\\tfrac23 i.", explanation: "The phase is purely imaginary, so each saddle contributes an oscillatory factor \\( e^{\\pm 2 i\\theta/3} \\)." },
        { stepNumber: 3, description: "Compute the curvatures.", workingLatex: "\\phi''(t)=2t,\\qquad \\phi''(i)=2i = 2e^{i\\pi/2},\\qquad \\phi''(-i)=-2i = 2e^{-i\\pi/2}.", explanation: "The steepest-descent direction at a saddle satisfies \\( \\arg(dt) = \\tfrac{\\pi}{2}-\\tfrac12\\arg\\phi'' \\)." },
        { stepNumber: 4, description: "Steepest-descent contribution of one saddle.", workingLatex: "I_{\\pm} = e^{\\theta\\phi(\\pm i)}\\sqrt{\\frac{2\\pi}{\\theta\\,|\\phi''|}}\\;e^{i\\alpha_{\\pm}},\\quad \\alpha_{\\pm}=\\frac{\\pi}{2}-\\tfrac12\\arg\\phi''(\\pm i).", explanation: "The general saddle contribution carries the Gaussian amplitude times the phase \\( e^{i\\alpha} \\) of the descent direction." },
        { stepNumber: 5, description: "Insert the data for \\( t=i \\).", workingLatex: "\\alpha_{+}=\\frac{\\pi}{2}-\\frac{\\pi}{4}=\\frac{\\pi}{4},\\quad I_{+}=e^{\\,2 i\\theta/3}\\sqrt{\\frac{2\\pi}{2\\theta}}\\,e^{i\\pi/4}=\\sqrt{\\frac{\\pi}{\\theta}}\\;e^{\\,i(2\\theta/3+\\pi/4)}.", explanation: "Substitute \\( |\\phi''|=2 \\), \\( \\arg\\phi''(i)=\\pi/2 \\)." },
        { stepNumber: 6, description: "Contribution of the conjugate saddle.", workingLatex: "I_{-}=\\sqrt{\\frac{\\pi}{\\theta}}\\;e^{-i(2\\theta/3+\\pi/4)}.", explanation: "By symmetry \\( t=-i \\) gives the complex conjugate, with the descent direction traversed in the opposite sense consistent with the contour orientation." },
        { stepNumber: 7, description: "Combine and apply the \\( 1/(2\\pi i) \\) prefactor.", workingLatex: "f(\\theta)=\\frac{1}{2\\pi i}\\,(I_{+}-I_{-}) = \\frac{1}{2\\pi i}\\sqrt{\\frac{\\pi}{\\theta}}\\cdot 2 i\\sin\\!\\Big(\\frac{2\\theta}{3}+\\frac{\\pi}{4}\\Big).", explanation: "The orientation of \\( C \\) produces the difference of the two saddle contributions; \\( e^{i\\beta}-e^{-i\\beta}=2i\\sin\\beta \\)." },
        { stepNumber: 8, description: "Simplify to the stated cosine.", workingLatex: "f(\\theta)=\\frac{1}{\\sqrt{\\pi\\theta}}\\sin\\!\\Big(\\frac{2\\theta}{3}+\\frac{\\pi}{4}\\Big)=(\\pi\\theta)^{-1/2}\\cos\\!\\Big(\\frac{2\\theta}{3}-\\frac{\\pi}{4}\\Big).", explanation: "Using \\( \\sin(\\beta+\\tfrac{\\pi}{4})=\\cos(\\beta-\\tfrac{\\pi}{4}) \\); this is the required leading-order result, with relative error \\( O(\\theta^{-1}) \\)." },
      ],
      finalAnswer: "\\( \\displaystyle f(\\theta)\\sim (\\pi\\theta)^{-1/2}\\cos\\!\\Big(\\frac{2\\theta}{3}-\\frac{\\pi}{4}\\Big) \\)",
      canonicalAnswer: "(pi*theta)^(-1/2)*cos(2*theta/3 - pi/4)",
    },
  },
  {
    id: "am7b-020",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 20",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Show that, as \\( x\\to+\\infty \\), \\( \\displaystyle\\int_{0}^{\\pi} \\exp\\!\\big[i x(t-\\sin t)\\big]\\,dt \\sim e^{i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\frac{4}{3}\\Big) \\), and identify why the decay is \\( x^{-1/3} \\) rather than \\( x^{-1/2} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "degenerate stationary point", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find stationary points of the phase.", workingLatex: "\\psi(t)=t-\\sin t,\\quad \\psi'(t)=1-\\cos t = 0 \\Rightarrow t=0.", explanation: "On \\( [0,\\pi] \\) the only stationary point is the endpoint \\( t=0 \\)." },
        { stepNumber: 2, description: "Check the degeneracy.", workingLatex: "\\psi''(t)=\\sin t,\\ \\psi''(0)=0;\\quad \\psi'''(0)=\\cos 0 = 1.", explanation: "The second derivative vanishes, so the stationary point is degenerate — the first non-zero term is cubic." },
        { stepNumber: 3, description: "Local expansion of the phase.", workingLatex: "t-\\sin t = \\frac{t^3}{6} + O(t^5).", explanation: "Taylor series of \\( \\sin t \\); the cubic flatness is what produces the \\( x^{-1/3} \\) scale." },
        { stepNumber: 4, description: "Reduce to a model cubic integral.", workingLatex: "\\int_{0}^{\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\sim \\int_{0}^{\\infty} \\exp\\!\\Big(\\frac{i x t^3}{6}\\Big)\\,dt.", explanation: "Extend the upper limit to \\( \\infty \\); the tail is non-stationary and contributes at higher order." },
        { stepNumber: 5, description: "Rotate onto the descent ray and reduce to Gamma.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i a t^3}\\,dt = \\frac{e^{i\\pi/6}}{3}\\,a^{-1/3}\\,\\Gamma\\!\\Big(\\tfrac13\\Big),\\quad a=\\frac{x}{6}.", explanation: "Same \\( \\pi/6 \\) rotation and \\( \\Gamma(1/3) \\) reduction as the cubic-endpoint model." },
        { stepNumber: 6, description: "Substitute and tidy.", workingLatex: "\\frac{e^{i\\pi/6}}{3}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\tfrac13\\Big) = e^{i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\tfrac43\\Big).", explanation: "Using \\( \\tfrac13\\Gamma(1/3)=\\Gamma(4/3) \\) gives exactly the stated form." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim e^{i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\frac{4}{3}\\Big) \\) — degenerate (cubic) stationary point gives \\( x^{-1/3} \\).",
      canonicalAnswer: "exp(i*pi/6)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  {
    id: "am7b-021",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 21",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Use the method of steepest descent to obtain the leading term, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_{0}^{\\infty} \\exp\\!\\Big[i x\\big(\\tfrac13 t^3 + t\\big)\\Big]\\,dt \\). Confirm the leading coefficient by an integration-by-parts argument.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "integration by parts", "no real saddle"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Look for real stationary points.", workingLatex: "g(t)=\\tfrac13 t^3+t,\\quad g'(t)=t^2+1>0 \\ \\forall t.", explanation: "There is no real stationary point, so the contribution comes from the endpoint \\( t=0 \\), found by integration by parts / contour deformation." },
        { stepNumber: 2, description: "Integrate by parts using the phase derivative.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x g}\\,dt = \\left[\\frac{e^{\\,i x g}}{i x\\,g'}\\right]_{0}^{\\infty} - \\int_{0}^{\\infty} e^{\\,i x g}\\,\\frac{d}{dt}\\!\\Big(\\frac{1}{i x\\,g'}\\Big)dt.", explanation: "Write \\( e^{ixg}=\\dfrac{1}{ixg'}\\dfrac{d}{dt}e^{ixg} \\) and integrate by parts; this is the standard endpoint expansion." },
        { stepNumber: 3, description: "Evaluate the boundary term.", workingLatex: "\\left[\\frac{e^{\\,i x g}}{i x\\,g'}\\right]_{0}^{\\infty} = 0 - \\frac{e^{0}}{i x\\,g'(0)} = -\\frac{1}{i x\\cdot 1} = \\frac{i}{x}.", explanation: "At \\( t=\\infty \\) the oscillation gives no net contribution (Riemann–Lebesgue along the deformed ray); at \\( t=0 \\), \\( g'(0)=1 \\)." },
        { stepNumber: 4, description: "Identify the leading term.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x(\\frac13 t^3 + t)}\\,dt \\sim \\frac{i}{x}.", explanation: "The remaining integral is \\( O(x^{-2}) \\) smaller, so the boundary term is the leading behaviour." },
        { stepNumber: 5, description: "Cross-check via steepest descent.", workingLatex: "\\text{Deform } t\\to \\text{ray with } g\\to -is/x:\\ \\text{endpoint contribution} = \\frac{i}{x}.", explanation: "The descent path from \\( t=0 \\) reproduces the same \\( i/x \\); both methods agree." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\frac{i}{x} \\)",
      canonicalAnswer: "i/x",
    },
  },
  {
    id: "am7b-022",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 22",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Let \\( h(t)=i(t+t^2) \\). By integrating along the constant-imaginary-phase (steepest) path through the endpoint \\( t=0 \\), find the leading-order term, as \\( \\lambda\\to\\infty \\), of \\( \\displaystyle\\int_{0}^{1} t^{-1/2}\\exp\\!\\big[i\\lambda(t+t^2)\\big]\\,dt \\), i.e. the constant \\( c_1 \\) in \\( \\sim c_1\\lambda^{-1/2} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "branch-point endpoint", "Gamma function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant endpoint.", workingLatex: "\\text{Phase } \\lambda(t+t^2)\\text{ has no interior stationary point on }(0,1).", explanation: "Both endpoints contribute; the \\( t^{-1/2} \\) singularity at \\( t=0 \\) makes that endpoint dominant (it decays like \\( \\lambda^{-1/2} \\), slower than the \\( t=1 \\) endpoint's \\( \\lambda^{-1} \\))." },
        { stepNumber: 2, description: "Localise and linearise at \\( t=0 \\).", workingLatex: "t+t^2 \\approx t,\\qquad \\int_{0}^{1} t^{-1/2} e^{\\,i\\lambda(t+t^2)}\\,dt \\sim \\int_{0}^{\\infty} t^{-1/2} e^{\\,i\\lambda t}\\,dt.", explanation: "Near \\( t=0 \\) the quadratic term is negligible; extend the limit to \\( \\infty \\) since the upper part is subdominant." },
        { stepNumber: 3, description: "Rotate onto the descent ray.", workingLatex: "i\\lambda t = -s \\Rightarrow t = \\frac{e^{i\\pi/2}}{\\lambda}\\,s,\\quad t^{-1/2}\\,dt = \\Big(\\frac{e^{i\\pi/2}}{\\lambda}\\Big)^{1/2} s^{-1/2}\\,ds.", explanation: "The steepest-descent path from the endpoint is the ray \\( \\arg t=\\pi/2 \\), where the phase becomes \\( e^{-s} \\)." },
        { stepNumber: 4, description: "Reduce to \\( \\Gamma(1/2) \\).", workingLatex: "\\int_{0}^{\\infty} t^{-1/2}e^{\\,i\\lambda t}\\,dt = \\Big(\\frac{e^{i\\pi/2}}{\\lambda}\\Big)^{1/2}\\Gamma\\!\\Big(\\tfrac12\\Big) = \\sqrt{\\frac{\\pi}{\\lambda}}\\;e^{i\\pi/4}.", explanation: "With \\( \\Gamma(1/2)=\\sqrt\\pi \\) and half of \\( e^{i\\pi/2} \\) giving \\( e^{i\\pi/4} \\)." },
        { stepNumber: 5, description: "Read off the constant \\( c_1 \\).", workingLatex: "c_1 = \\sqrt{\\pi}\\,e^{i\\pi/4}.", explanation: "So the leading term is \\( c_1\\lambda^{-1/2} \\) with \\( c_1=\\sqrt\\pi\\,e^{i\\pi/4} \\); the \\( t=1 \\) endpoint supplies the next, \\( O(\\lambda^{-1}) \\), term." },
      ],
      finalAnswer: "\\( \\displaystyle c_1 = \\sqrt{\\pi}\\,e^{i\\pi/4} \\), so the integral \\( \\sim \\sqrt{\\pi}\\,e^{i\\pi/4}\\,\\lambda^{-1/2} \\)",
      canonicalAnswer: "sqrt(pi)*exp(i*pi/4)",
    },
  },
  {
    id: "am7b-023",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 23",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using steepest descent, find the leading-order behaviour as \\( x\\to\\infty \\) of the modified Bessel function \\( \\displaystyle I_0(x)=\\frac{1}{\\pi}\\int_{0}^{\\pi} e^{\\,x\\cos\\theta}\\,d\\theta \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Bessel function", "endpoint maximum"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the maximum of the exponent.", workingLatex: "\\phi(\\theta)=\\cos\\theta,\\quad \\phi'(\\theta)=-\\sin\\theta=0\\Rightarrow \\theta=0\\ (\\text{endpoint}).", explanation: "On \\( [0,\\pi] \\) the exponent is largest at the endpoint \\( \\theta=0 \\), where \\( \\cos\\theta=1 \\)." },
        { stepNumber: 2, description: "Expand the phase near \\( \\theta=0 \\).", workingLatex: "\\cos\\theta \\approx 1 - \\frac{\\theta^2}{2}.", explanation: "The endpoint is a (one-sided) quadratic maximum." },
        { stepNumber: 3, description: "Reduce to a half Gaussian.", workingLatex: "\\int_{0}^{\\pi} e^{\\,x\\cos\\theta}\\,d\\theta \\sim e^{x}\\int_{0}^{\\infty} e^{-x\\theta^2/2}\\,d\\theta = e^{x}\\cdot\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "The endpoint maximum captures half of the Gaussian \\( \\int e^{-x\\theta^2/2} \\), giving the factor \\( \\tfrac12 \\)." },
        { stepNumber: 4, description: "Divide by \\( \\pi \\) and simplify.", workingLatex: "I_0(x) \\sim \\frac{1}{\\pi}\\cdot\\frac{e^{x}}{2}\\sqrt{\\frac{2\\pi}{x}} = \\frac{e^{x}}{\\sqrt{2\\pi x}}.", explanation: "This is the classical large-argument asymptotic of \\( I_0 \\)." },
      ],
      finalAnswer: "\\( \\displaystyle I_0(x)\\sim \\frac{e^{x}}{\\sqrt{2\\pi x}} \\)",
      canonicalAnswer: "exp(x)/sqrt(2*pi*x)",
    },
  },
  {
    id: "am7b-024",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 24",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "By the method of steepest descent applied to \\( \\displaystyle\\Gamma(x+1)=\\int_{0}^{\\infty} t^{x}e^{-t}\\,dt \\), derive the leading-order Stirling formula \\( \\Gamma(x+1)\\sim \\sqrt{2\\pi x}\\,\\big(x/e\\big)^{x} \\) as \\( x\\to\\infty \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Stirling", "Gamma function", "Laplace"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the integrand in exponential form.", workingLatex: "t^{x}e^{-t} = \\exp\\big(x\\ln t - t\\big).", explanation: "To apply steepest descent we need a single large parameter \\( x \\) multiplying a phase; the exponent is \\( x\\ln t - t \\)." },
        { stepNumber: 2, description: "Rescale to expose \\( x \\) as the large factor.", workingLatex: "t = x\\,u:\\quad x\\ln t - t = x\\ln x + x(\\ln u - u).", explanation: "The substitution \\( t=xu \\) makes \\( x \\) multiply the \\( u \\)-dependent phase \\( \\phi(u)=\\ln u - u \\)." },
        { stepNumber: 3, description: "Find the saddle.", workingLatex: "\\phi(u)=\\ln u - u,\\quad \\phi'(u)=\\frac1u - 1 = 0 \\Rightarrow u_0=1,\\ \\phi(1)=-1.", explanation: "Single interior maximum at \\( u=1 \\)." },
        { stepNumber: 4, description: "Compute the curvature.", workingLatex: "\\phi''(u) = -\\frac{1}{u^2},\\qquad \\phi''(1) = -1.", explanation: "Non-degenerate maximum, width \\( \\sim x^{-1/2} \\)." },
        { stepNumber: 5, description: "Apply the saddle formula, including the Jacobian.", workingLatex: "\\Gamma(x+1) = x^{x+1}\\!\\int_{0}^{\\infty} e^{\\,x\\phi(u)}\\,du \\sim x^{x+1}\\,e^{-x}\\sqrt{\\frac{2\\pi}{x\\cdot 1}}.", explanation: "The factor \\( dt=x\\,du \\) gives the extra power \\( x^{x+1} \\); the Gaussian gives \\( \\sqrt{2\\pi/x} \\)." },
        { stepNumber: 6, description: "Collect.", workingLatex: "\\Gamma(x+1) \\sim x^{x}\\,e^{-x}\\sqrt{2\\pi x} = \\sqrt{2\\pi x}\\,\\Big(\\frac{x}{e}\\Big)^{x}.", explanation: "Combining \\( x^{x+1}\\sqrt{2\\pi/x}=x^{x}\\sqrt{2\\pi x} \\) gives the leading-order Stirling formula." },
      ],
      finalAnswer: "\\( \\displaystyle \\Gamma(x+1)\\sim \\sqrt{2\\pi x}\\,\\Big(\\frac{x}{e}\\Big)^{x} \\)",
      canonicalAnswer: "sqrt(2*pi*x)*(x/e)^x",
    },
  },
  {
    id: "am7b-025",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 25",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The phase \\( h(z)=k\\big(z-2z^{1/2}\\big) \\) has a saddle where \\( h'=0 \\). Find the saddle point, verify that the steepest-descent paths leaving it are \\( z_{\\pm}(\\tau)=1-\\tau^2\\pm 2 i\\tau \\) (\\( \\tau\\ge 0 \\)), and give the parabola they trace in real form \\( x=x(y) \\) with \\( z=x+iy \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "steepest paths", "parabola", "branch cut"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "h(z)=k\\big(z-2z^{1/2}\\big),\\quad h'(z)=k\\Big(1 - z^{-1/2}\\Big).", explanation: "With the branch cut on the negative real axis, \\( z^{1/2}>0 \\) for \\( z>0 \\)." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "1 - z^{-1/2}=0 \\Rightarrow z^{1/2}=1 \\Rightarrow z_0 = 1.", explanation: "The single saddle sits on the positive real axis at \\( z=1 \\)." },
        { stepNumber: 3, description: "Phase value and the steepest-descent condition.", workingLatex: "h(1)=k(1-2)=-k;\\quad \\text{steepest descent: } \\operatorname{Im}\\,h(z)=\\operatorname{Im}\\,h(1)=0.", explanation: "Steepest paths keep the imaginary part of \\( h \\) constant and equal to its value at the saddle (here \\( 0 \\))." },
        { stepNumber: 4, description: "Check the proposed parametrisation.", workingLatex: "z=1-\\tau^2+2 i\\tau = (1+i\\tau)^2 \\Rightarrow z^{1/2}=1+i\\tau.", explanation: "Recognising the perfect square makes \\( z^{1/2} \\) explicit on the right branch (\\( \\operatorname{Re}>0 \\))." },
        { stepNumber: 5, description: "Confirm \\( \\operatorname{Im} h \\) is constant.", workingLatex: "z-2z^{1/2} = (1+i\\tau)^2 - 2(1+i\\tau) = -1 - \\tau^2,\\quad h = -k(1+\\tau^2)\\ \\text{(real)}.", explanation: "\\( \\operatorname{Im} h=0 \\) for all \\( \\tau \\) and \\( \\operatorname{Re} h=-k(1+\\tau^2)\\le -k \\) decreases away from the saddle — these are genuine descent paths." },
        { stepNumber: 6, description: "Eliminate \\( \\tau \\) for the real-form parabola.", workingLatex: "x = 1-\\tau^2,\\ y = 2\\tau \\Rightarrow \\tau = \\tfrac{y}{2},\\quad x = 1 - \\frac{y^2}{4}.", explanation: "The two halves (\\( \\tau\\ge0 \\) for each sign) join into the single parabola \\( x=1-\\tfrac14 y^2 \\) through the saddle \\( (1,0) \\)." },
      ],
      finalAnswer: "\\( z_0=1 \\); steepest-descent parabola \\( x = 1 - \\dfrac{y^2}{4} \\)",
      canonicalAnswer: "1 - y^2/4",
    },
  },
  {
    id: "am7b-026",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 26",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} \\frac{e^{\\,i x(t^3/3 - t)}}{1 + t^2}\\,dt \\), keeping only the contribution of the dominant real stationary point and explaining which one it is.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "two stationary points", "prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the stationary points.", workingLatex: "\\psi(t)=\\tfrac13 t^3 - t,\\quad \\psi'(t)=t^2-1=0\\Rightarrow t=\\pm1.", explanation: "Two simple real stationary points contribute, each with its own phase." },
        { stepNumber: 2, description: "Curvatures and phase values.", workingLatex: "\\psi''(t)=2t:\\ \\psi''(1)=2,\\ \\psi''(-1)=-2;\\quad \\psi(1)=-\\tfrac23,\\ \\psi(-1)=\\tfrac23.", explanation: "Both are non-degenerate; each yields an \\( x^{-1/2} \\) term, so both are equally dominant and must be summed." },
        { stepNumber: 3, description: "Stationary-phase contribution at \\( t=1 \\).", workingLatex: "I_{1}=\\frac{1}{1+1^2}\\,e^{\\,i x\\psi(1)}\\sqrt{\\frac{2\\pi}{x\\,|\\psi''(1)|}}\\,e^{i\\pi/4} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{\\,i(-2x/3+\\pi/4)}.", explanation: "For \\( \\psi''>0 \\) the phase factor is \\( e^{+i\\pi/4} \\); the prefactor \\( g(1)=\\tfrac12 \\)." },
        { stepNumber: 4, description: "Stationary-phase contribution at \\( t=-1 \\).", workingLatex: "I_{-1}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{\\,i(2x/3-\\pi/4)}.", explanation: "For \\( \\psi''<0 \\) the phase factor is \\( e^{-i\\pi/4} \\); \\( g(-1)=\\tfrac12 \\)." },
        { stepNumber: 5, description: "Sum the two contributions.", workingLatex: "I_{1}+I_{-1} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\cdot 2\\cos\\!\\Big(\\frac{2x}{3}-\\frac{\\pi}{4}\\Big).", explanation: "The conjugate pair combines into a cosine, mirroring the exemplar \\( f(\\theta) \\)." },
        { stepNumber: 6, description: "State the leading term.", workingLatex: "\\int \\sim \\sqrt{\\frac{\\pi}{x}}\\,\\cos\\!\\Big(\\frac{2x}{3}-\\frac{\\pi}{4}\\Big).", explanation: "Neither stationary point alone dominates; the real result is the cosine of the combined phase." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{\\pi}{x}}\\,\\cos\\!\\Big(\\frac{2x}{3}-\\frac{\\pi}{4}\\Big) \\)",
      canonicalAnswer: "sqrt(pi/x)*cos(2*x/3 - pi/4)",
    },
  },
  {
    id: "am7b-027",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 27",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order asymptotics, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{0}^{\\infty} e^{-x(t-\\ln t)}\\,dt \\) by steepest descent about its interior saddle.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "logarithmic phase", "saddle point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the phase.", workingLatex: "\\phi(t) = -(t-\\ln t),\\qquad \\phi'(t) = -\\Big(1-\\frac1t\\Big).", explanation: "Maximising the exponent \\( -(t-\\ln t) \\) means minimising \\( t-\\ln t \\)." },
        { stepNumber: 2, description: "Find the saddle.", workingLatex: "1-\\frac1t = 0 \\Rightarrow t_0 = 1,\\quad \\phi(1) = -(1-0) = -1.", explanation: "Single interior minimum of \\( t-\\ln t \\) at \\( t=1 \\)." },
        { stepNumber: 3, description: "Compute the curvature.", workingLatex: "\\phi''(t) = -\\frac{1}{t^2},\\qquad \\phi''(1) = -1.", explanation: "Non-degenerate maximum of the exponent." },
        { stepNumber: 4, description: "Apply the saddle formula.", workingLatex: "\\int_{0}^{\\infty} e^{-x(t-\\ln t)}\\,dt \\sim e^{-x}\\sqrt{\\frac{2\\pi}{x\\cdot 1}} = \\sqrt{\\frac{2\\pi}{x}}\\;e^{-x}.", explanation: "The saddle is interior, so the full Gaussian (not a half) contributes. Note the integral equals \\( \\Gamma(x+1)/x^{x} \\), consistent with Stirling." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt{\\dfrac{2\\pi}{x}}\\;e^{-x} \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(-x)",
    },
  },
  {
    id: "am7b-028",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 28",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading term, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_{-\\pi}^{\\pi}\\exp\\!\\big[i x(t-\\sin t)\\big]\\,dt \\), and contrast it with the result for the integral over \\( [0,\\pi] \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "degenerate stationary point", "symmetry"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the interior stationary point.", workingLatex: "\\psi'(t)=1-\\cos t = 0 \\Rightarrow t=0 \\in(-\\pi,\\pi).", explanation: "Now \\( t=0 \\) is a genuine interior point, so both descent directions contribute (unlike the one-sided \\( [0,\\pi] \\) case)." },
        { stepNumber: 2, description: "Local cubic behaviour.", workingLatex: "t-\\sin t = \\frac{t^3}{6} + O(t^5),\\quad \\psi''(0)=0.", explanation: "Degenerate (cubic) stationary point, giving an \\( x^{-1/3} \\) scale." },
        { stepNumber: 3, description: "Symmetrise the model integral.", workingLatex: "\\int_{-\\pi}^{\\pi} e^{\\,i x(t-\\sin t)}\\,dt \\sim \\int_{-\\infty}^{\\infty} \\exp\\!\\Big(\\frac{i x t^3}{6}\\Big)\\,dt.", explanation: "Extend to the whole line; for a cubic, the full-line integral is twice the real part of the half-line one." },
        { stepNumber: 4, description: "Use the half-line cubic result.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x t^3/6}\\,dt = e^{i\\pi/6}\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\tfrac43\\Big).", explanation: "This is exactly the \\( [0,\\pi] \\) result." },
        { stepNumber: 5, description: "Combine the two halves.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{\\,i x t^3/6}\\,dt = 2\\operatorname{Re}\\Big[e^{i\\pi/6}\\Big] \\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\tfrac43\\Big) = \\sqrt3\\,\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\tfrac43\\Big).", explanation: "The \\( t<0 \\) half is the complex conjugate of the \\( t>0 \\) half, so the sum is \\( 2\\operatorname{Re} \\); \\( 2\\cos(\\pi/6)=\\sqrt3 \\). The full integral is real, unlike the complex \\( [0,\\pi] \\) result." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\sqrt3\\,\\Big(\\frac{6}{x}\\Big)^{1/3}\\Gamma\\!\\Big(\\frac43\\Big) \\) (real, vs. the complex \\( [0,\\pi] \\) value)",
      canonicalAnswer: "sqrt(3)*(6/x)^(1/3)*gamma(4/3)",
    },
  },
  {
    id: "am7b-029",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 29",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using steepest descent on \\( \\displaystyle J(x)=\\int_{-\\infty}^{\\infty} \\exp\\!\\big[\\,x(i t - \\tfrac12 t^2)\\big]\\,dt \\), find its exact leading behaviour as \\( x\\to\\infty \\) and identify the (complex) saddle.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "complex saddle", "completing the square"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the saddle.", workingLatex: "\\phi(t)=i t - \\tfrac12 t^2,\\quad \\phi'(t)=i - t = 0 \\Rightarrow t_0 = i.", explanation: "The saddle is off the real axis at \\( t=i \\); the contour deforms up to it." },
        { stepNumber: 2, description: "Phase value at the saddle.", workingLatex: "\\phi(i) = i\\cdot i - \\tfrac12 i^2 = -1 + \\tfrac12 = -\\tfrac12.", explanation: "The exponential prefactor is \\( e^{-x/2} \\)." },
        { stepNumber: 3, description: "Curvature.", workingLatex: "\\phi''(t) = -1,\\qquad \\phi''(i) = -1.", explanation: "Real negative curvature: the steepest-descent path through \\( t=i \\) is horizontal." },
        { stepNumber: 4, description: "Apply the saddle formula.", workingLatex: "J(x) \\sim e^{\\,x\\phi(i)}\\sqrt{\\frac{2\\pi}{x\\,|\\phi''(i)|}} = e^{-x/2}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "Because the exponent is exactly quadratic, completing the square shows this leading term is in fact exact." },
        { stepNumber: 5, description: "Confirm by completing the square.", workingLatex: "i t - \\tfrac12 t^2 = -\\tfrac12(t-i)^2 - \\tfrac12,\\quad J(x)=e^{-x/2}\\!\\int_{-\\infty}^{\\infty}\\! e^{-x(t-i)^2/2}\\,dt = e^{-x/2}\\sqrt{\\frac{2\\pi}{x}}.", explanation: "The shift of contour to pass through \\( t=i \\) is justified by Cauchy's theorem; the result matches the saddle estimate exactly." },
      ],
      finalAnswer: "\\( \\displaystyle J(x) = \\sqrt{\\dfrac{2\\pi}{x}}\\;e^{-x/2} \\) (saddle at \\( t=i \\))",
      canonicalAnswer: "sqrt(2*pi/x)*exp(-x/2)",
    },
  },
  {
    id: "am7b-030",
    topicRef: "am7b",
    topicTitle: "Leading-order steepest descent 30",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to+\\infty \\), of \\( \\displaystyle\\int_{0}^{\\infty} \\frac{\\cos(x t^2)}{1+t}\\,dt \\), arising from a stationary point at the endpoint with a slowly-varying algebraic prefactor.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "endpoint stationary point", "prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Complexify and localise.", workingLatex: "\\int_{0}^{\\infty}\\frac{\\cos(x t^2)}{1+t}\\,dt = \\operatorname{Re}\\int_{0}^{\\infty}\\frac{e^{\\,i x t^2}}{1+t}\\,dt.", explanation: "The phase \\( x t^2 \\) is stationary at the endpoint \\( t=0 \\), which dominates." },
        { stepNumber: 2, description: "Freeze the prefactor at the endpoint.", workingLatex: "\\frac{1}{1+t} \\to \\frac{1}{1+0} = 1 \\quad (t\\to 0).", explanation: "The Fresnel window has width \\( x^{-1/2} \\), over which \\( (1+t)^{-1}\\approx 1 \\)." },
        { stepNumber: 3, description: "Apply the half-line Fresnel integral.", workingLatex: "\\int_{0}^{\\infty} e^{\\,i x t^2}\\,dt = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\;e^{i\\pi/4}.", explanation: "Endpoint stationary point gives half the full-line value, with the universal \\( e^{i\\pi/4} \\)." },
        { stepNumber: 4, description: "Take the real part.", workingLatex: "\\operatorname{Re}\\!\\left[\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}\\right] = \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\cdot\\frac{1}{\\sqrt2} = \\frac{1}{2}\\sqrt{\\frac{\\pi}{2x}}.", explanation: "\\( \\cos(\\pi/4)=1/\\sqrt2 \\); equivalently \\( \\sqrt{\\pi/(8x)} \\)." },
      ],
      finalAnswer: "\\( \\displaystyle \\sim \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{2x}} = \\sqrt{\\dfrac{\\pi}{8x}} \\)",
      canonicalAnswer: "sqrt(pi/(8*x))",
    },
  },
];
