import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — Method of Steepest Descent II
 * Subtopic: am8b "Steepest descent for the Hankel function H^{(1)}_ν"
 *
 * Large-order asymptotics of H^{(1)}_ν(ν/cos α) via the Debye integral
 *   H^{(1)}_ν(x) = -(1/π) ∫ exp[i(νt - x sin t)] dt,   x = ν sec α, 0 < α < π/2,
 * giving the classic result
 *   H^{(1)}_ν(ν/cos α) ~ √2 (πν tan α)^{-1/2} e^{iν(tan α - α)} e^{-iπ/4}.
 * Covers: the phase φ(t) = i(t - sec α sin t); the saddle at t₀ = -α; the
 * second derivative φ''(-α) = -i tan α; the steepest-descent direction; the
 * path equation Im φ = tan α - α; the origin of the e^{-iπ/4} factor; and
 * synoptic links (J_ν/Y_ν, the large-x Debye form, the turning point α → 0).
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 3, Q1.
 * The leading result and all sub-results were numerically verified with
 * mpmath (saddle location, φ'' value, prefactor magnitude, e^{-iπ/4} phase,
 * path equation, and ratio H_exact/H_approx → 1 as ν → ∞).
 */
export const questions: Question[] = [
  // ── Foundation: core technique in isolation ───────────────────────────────
  {
    id: "am8b-001",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Starting from \\( H^{(1)}_\\nu(x) = -\\dfrac{1}{\\pi}\\displaystyle\\int e^{\\,i(\\nu t - x\\sin t)}\\,dt \\), substitute \\( x = \\nu\\sec\\alpha \\) and write the integrand in the form \\( e^{\\,\\nu\\varphi(t)} \\). State \\( \\varphi(t) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "Hankel function", "phase function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Insert the scaling of the argument.", workingLatex: "x = \\nu\\sec\\alpha \\quad\\Rightarrow\\quad \\nu t - x\\sin t = \\nu\\,(t - \\sec\\alpha\\,\\sin t).", explanation: "The whole point of the large-order limit is that the argument grows in step with the order: setting \\( x = \\nu\\sec\\alpha \\) makes \\( \\nu \\) a common factor in the exponent, which is what lets the method of steepest descent apply." },
        { stepNumber: 2, description: "Factor ν out of the exponent.", workingLatex: "i(\\nu t - x\\sin t) = \\nu\\cdot i\\,(t - \\sec\\alpha\\,\\sin t).", explanation: "The exponent is now \\( \\nu \\) times a function of \\( t \\) that does not depend on \\( \\nu \\); this is the standard shape \\( e^{\\nu\\varphi(t)} \\) for a saddle-point analysis with large parameter \\( \\nu \\)." },
        { stepNumber: 3, description: "Read off the phase.", workingLatex: "\\varphi(t) = i\\,(t - \\sec\\alpha\\,\\sin t).", explanation: "The factor of \\( i \\) is retained inside \\( \\varphi \\); because \\( \\varphi \\) is purely imaginary on the real axis this is really a stationary-phase-type integral, deformed onto a steepest-descent contour off the real axis." },
      ],
      finalAnswer: "\\( \\varphi(t) = i\\,(t - \\sec\\alpha\\,\\sin t) \\)",
    },
  },
  {
    id: "am8b-002",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the phase \\( \\varphi(t) = i\\,(t - \\sec\\alpha\\,\\sin t) \\), find \\( \\varphi'(t) \\) and hence the equation satisfied by a saddle point.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle point", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the phase.", workingLatex: "\\varphi'(t) = i\\,(1 - \\sec\\alpha\\,\\cos t).", explanation: "Only \\( \\sin t \\) depends on \\( t \\) inside the bracket; its derivative is \\( \\cos t \\), and the constant \\( \\sec\\alpha \\) carries through." },
        { stepNumber: 2, description: "Set the derivative to zero.", workingLatex: "\\varphi'(t) = 0 \\;\\Longleftrightarrow\\; \\sec\\alpha\\,\\cos t = 1 \\;\\Longleftrightarrow\\; \\cos t = \\cos\\alpha.", explanation: "The factor \\( i \\) never vanishes, so the saddle condition is purely \\( 1 - \\sec\\alpha\\cos t = 0 \\)." },
        { stepNumber: 3, description: "Solve for the saddle.", workingLatex: "\\cos t = \\cos\\alpha \\quad\\Rightarrow\\quad t = \\pm\\alpha \\ (\\mathrm{mod}\\ 2\\pi).", explanation: "There are two real candidate saddles, \\( t = +\\alpha \\) and \\( t = -\\alpha \\); the contour for \\( H^{(1)} \\) (with \\( -\\pi \\le \\operatorname{Re} t < 0 \\)) selects \\( t_0 = -\\alpha \\)." },
      ],
      finalAnswer: "\\( \\varphi'(t) = i(1 - \\sec\\alpha\\cos t) \\); saddles at \\( \\cos t = \\cos\\alpha \\), i.e. \\( t = \\pm\\alpha \\).",
    },
  },
  {
    id: "am8b-003",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 03",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The relevant saddle of \\( \\varphi(t) = i(t - \\sec\\alpha\\,\\sin t) \\) is \\( t_0 = -\\alpha \\). Evaluate \\( \\varphi(t_0) \\), the value of the phase at the saddle.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle point", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute the saddle into the phase.", workingLatex: "\\varphi(-\\alpha) = i\\big(-\\alpha - \\sec\\alpha\\,\\sin(-\\alpha)\\big).", explanation: "Direct substitution of \\( t_0 = -\\alpha \\); the sine is odd so \\( \\sin(-\\alpha) = -\\sin\\alpha \\)." },
        { stepNumber: 2, description: "Simplify using sec·sin = tan.", workingLatex: "\\varphi(-\\alpha) = i\\big(-\\alpha + \\sec\\alpha\\,\\sin\\alpha\\big) = i(\\tan\\alpha - \\alpha).", explanation: "\\( \\sec\\alpha\\,\\sin\\alpha = \\sin\\alpha/\\cos\\alpha = \\tan\\alpha \\); this is exactly the exponent that appears as \\( e^{i\\nu(\\tan\\alpha-\\alpha)} \\) in the final result." },
      ],
      finalAnswer: "\\( \\varphi(t_0) = i(\\tan\\alpha - \\alpha) \\)",
      canonicalAnswer: "i*(tan(alpha) - alpha)",
    },
  },
  {
    id: "am8b-004",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 04",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For \\( \\varphi(t) = i(t - \\sec\\alpha\\,\\sin t) \\), compute the second derivative \\( \\varphi''(t) \\) and evaluate it at the saddle \\( t_0 = -\\alpha \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle point", "curvature"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate φ' once more.", workingLatex: "\\varphi'(t) = i(1 - \\sec\\alpha\\cos t) \\;\\Rightarrow\\; \\varphi''(t) = i\\,\\sec\\alpha\\,\\sin t.", explanation: "Differentiating \\( -\\sec\\alpha\\cos t \\) gives \\( +\\sec\\alpha\\sin t \\); the constant \\( 1 \\) differentiates away." },
        { stepNumber: 2, description: "Evaluate at the saddle.", workingLatex: "\\varphi''(-\\alpha) = i\\,\\sec\\alpha\\,\\sin(-\\alpha) = -i\\,\\sec\\alpha\\,\\sin\\alpha = -i\\tan\\alpha.", explanation: "Again \\( \\sec\\alpha\\sin\\alpha = \\tan\\alpha \\). The result \\( -i\\tan\\alpha \\) has modulus \\( \\tan\\alpha \\) and argument \\( -\\pi/2 \\); both pieces feed the steepest-descent prefactor." },
      ],
      finalAnswer: "\\( \\varphi''(t_0) = -i\\tan\\alpha \\)",
      canonicalAnswer: "-i*tan(alpha)",
    },
  },
  {
    id: "am8b-005",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The method of steepest descent gives \\( \\displaystyle\\int e^{\\nu\\varphi(t)}\\,dt \\sim e^{\\nu\\varphi(t_0)}\\sqrt{\\dfrac{2\\pi}{\\nu\\,|\\varphi''(t_0)|}}\\,e^{i\\theta} \\). Using \\( |\\varphi''(t_0)| = \\tan\\alpha \\), write the magnitude of the prefactor \\( \\sqrt{2\\pi/(\\nu|\\varphi''|)} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian integral", "prefactor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Insert the curvature modulus.", workingLatex: "\\sqrt{\\frac{2\\pi}{\\nu\\,|\\varphi''(t_0)|}} = \\sqrt{\\frac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "Only the modulus of \\( \\varphi'' \\) sets the width of the Gaussian about the saddle; its argument is absorbed into the direction phase \\( e^{i\\theta} \\)." },
        { stepNumber: 2, description: "Keep this for assembly with the −1/π prefactor.", workingLatex: "\\sqrt{\\frac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "When multiplied by the overall \\( 1/\\pi \\) from the Hankel definition this becomes \\( \\sqrt{2/(\\pi\\nu\\tan\\alpha)} = \\sqrt{2}\\,(\\pi\\nu\\tan\\alpha)^{-1/2} \\), the stated amplitude." },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{2\\pi}{\\nu\\tan\\alpha}} \\)",
    },
  },
  {
    id: "am8b-006",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write \\( t = u + iv \\) and expand \\( \\varphi(t) = i(t - \\sec\\alpha\\,\\sin t) \\) into real and imaginary parts. State \\( \\operatorname{Im}\\varphi \\) as a function of \\( u \\) and \\( v \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["steepest descent", "path equation", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand sin of a complex argument.", workingLatex: "\\sin(u+iv) = \\sin u\\cosh v + i\\cos u\\sinh v.", explanation: "Standard identity \\( \\sin(u+iv) = \\sin u\\cos(iv) + \\cos u\\sin(iv) \\) with \\( \\cos(iv)=\\cosh v \\), \\( \\sin(iv)=i\\sinh v \\)." },
        { stepNumber: 2, description: "Form t − sec α sin t.", workingLatex: "t - \\sec\\alpha\\sin t = \\big(u - \\sec\\alpha\\sin u\\cosh v\\big) + i\\big(v - \\sec\\alpha\\cos u\\sinh v\\big).", explanation: "Separate real and imaginary parts before multiplying by \\( i \\)." },
        { stepNumber: 3, description: "Multiply by i and read off Im φ.", workingLatex: "\\varphi = -\\big(v - \\sec\\alpha\\cos u\\sinh v\\big) + i\\big(u - \\sec\\alpha\\sin u\\cosh v\\big).", explanation: "Multiplying by \\( i \\) swaps real and imaginary parts (with a sign), so \\( \\operatorname{Im}\\varphi = u - \\sec\\alpha\\sin u\\cosh v \\)." },
      ],
      finalAnswer: "\\( \\operatorname{Im}\\varphi = u - \\sec\\alpha\\,\\sin u\\,\\cosh v \\)",
    },
  },

  // ── Standard: typical sheet-level ─────────────────────────────────────────
  {
    id: "am8b-007",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the contour of steepest descent through the saddle \\( t_0 = -\\alpha \\) of \\( \\varphi(t) = i(t - \\sec\\alpha\\,\\sin t) \\) satisfies \\( u - \\sec\\alpha\\,\\sin u\\,\\cosh v = \\tan\\alpha - \\alpha \\), where \\( t = u + iv \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "path equation", "constant phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the steepest-paths condition.", workingLatex: "\\operatorname{Im}\\varphi(t) = \\operatorname{Im}\\varphi(t_0) = \\text{const}.", explanation: "On a steepest-descent (or steepest-ascent) path the imaginary part of \\( \\varphi \\) is constant, equal to its value at the saddle; this keeps the oscillatory factor frozen while the modulus changes fastest." },
        { stepNumber: 2, description: "Use the imaginary part from the expansion.", workingLatex: "\\operatorname{Im}\\varphi = u - \\sec\\alpha\\,\\sin u\\,\\cosh v.", explanation: "This is the real-and-imaginary-part expansion of \\( \\varphi(u+iv) \\)." },
        { stepNumber: 3, description: "Evaluate the constant at the saddle.", workingLatex: "\\operatorname{Im}\\varphi(t_0) = (-\\alpha) - \\sec\\alpha\\,\\sin(-\\alpha)\\cosh 0 = -\\alpha + \\tan\\alpha.", explanation: "At \\( t_0 = -\\alpha \\) we have \\( u = -\\alpha,\\ v = 0,\\ \\cosh 0 = 1 \\), and \\( \\sec\\alpha\\sin\\alpha = \\tan\\alpha \\)." },
        { stepNumber: 4, description: "Equate to obtain the path equation.", workingLatex: "u - \\sec\\alpha\\,\\sin u\\,\\cosh v = \\tan\\alpha - \\alpha.", explanation: "This single real equation defines the curve in the \\( (u,v) \\)-plane along which the deformed contour runs; the branch through \\( (-\\alpha,0) \\) descending into \\( v>0 \\) is the steepest-descent path." },
      ],
      finalAnswer: "\\( u - \\sec\\alpha\\,\\sin u\\,\\cosh v = \\tan\\alpha - \\alpha \\)",
    },
  },
  {
    id: "am8b-008",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Near the saddle write \\( t = -\\alpha + \\sigma \\) with small \\( \\sigma \\). Expand \\( \\nu\\varphi(t) \\) to second order in \\( \\sigma \\), giving the local Gaussian form of the integrand.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Taylor expansion", "Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Taylor expand the phase about the saddle.", workingLatex: "\\varphi(-\\alpha+\\sigma) = \\varphi(-\\alpha) + \\tfrac{1}{2}\\varphi''(-\\alpha)\\sigma^2 + O(\\sigma^3).", explanation: "The linear term vanishes because \\( \\varphi'(-\\alpha)=0 \\); that is precisely what makes \\( -\\alpha \\) a saddle." },
        { stepNumber: 2, description: "Insert the known values.", workingLatex: "\\varphi(-\\alpha) = i(\\tan\\alpha-\\alpha), \\qquad \\varphi''(-\\alpha) = -i\\tan\\alpha.", explanation: "These were computed earlier: the saddle value and curvature of the phase." },
        { stepNumber: 3, description: "Multiply by ν and exponentiate.", workingLatex: "\\nu\\varphi \\approx i\\nu(\\tan\\alpha-\\alpha) - \\tfrac{1}{2} i\\nu\\tan\\alpha\\,\\sigma^2.", explanation: "The local integrand is \\( e^{i\\nu(\\tan\\alpha-\\alpha)}\\,\\exp\\!\\big(-\\tfrac12 i\\nu\\tan\\alpha\\,\\sigma^2\\big) \\); on the steepest-descent contour the quadratic exponent becomes real and negative, giving a genuine Gaussian." },
      ],
      finalAnswer: "\\( \\nu\\varphi \\approx i\\nu(\\tan\\alpha-\\alpha) - \\tfrac{1}{2} i\\nu\\tan\\alpha\\,\\sigma^2 \\)",
    },
  },
  {
    id: "am8b-009",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( \\varphi''(t_0) = -i\\tan\\alpha = \\tan\\alpha\\,e^{-i\\pi/2} \\), determine the direction (argument of \\( \\sigma \\)) along which the contour leaves the saddle in the steepest-descent sense.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "direction", "phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the quadratic exponent in polar form.", workingLatex: "\\tfrac{1}{2}\\varphi''(t_0)\\sigma^2 = \\tfrac{1}{2}\\tan\\alpha\\,e^{-i\\pi/2}\\,|\\sigma|^2 e^{2i\\theta}, \\quad \\sigma = |\\sigma|e^{i\\theta}.", explanation: "Steepest descent requires the quadratic term to be real and negative, i.e. \\( \\varphi''(t_0)\\sigma^2 < 0 \\)." },
        { stepNumber: 2, description: "Impose real-and-negative.", workingLatex: "\\arg\\!\\big(\\varphi''(t_0)\\sigma^2\\big) = \\pi \\;\\Rightarrow\\; -\\tfrac{\\pi}{2} + 2\\theta = \\pi \\ (\\mathrm{mod}\\ 2\\pi).", explanation: "For the exponent to decay, \\( e^{\\nu\\varphi} \\) must fall off, so the quadratic part must have argument \\( \\pi \\)." },
        { stepNumber: 3, description: "Solve for the contour direction.", workingLatex: "2\\theta = \\tfrac{3\\pi}{2} \\;\\Rightarrow\\; \\theta = \\tfrac{3\\pi}{4} \\quad(\\text{or } \\theta = -\\tfrac{\\pi}{4}).", explanation: "The two solutions differ by \\( \\pi \\) and describe the two ends of the same straight steepest-descent line through the saddle." },
        { stepNumber: 4, description: "Select the branch matching the contour.", workingLatex: "\\theta = \\tfrac{3\\pi}{4}.", explanation: "The orientation of the original Hankel contour (running upward from \\( -i\\infty \\) toward \\( i\\infty - \\pi \\)) picks the branch \\( \\theta = 3\\pi/4 \\); this choice is what produces the \\( e^{-i\\pi/4} \\) factor in the final answer." },
      ],
      finalAnswer: "Steepest descent along \\( \\arg\\sigma = \\tfrac{3\\pi}{4} \\).",
    },
  },
  {
    id: "am8b-010",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "On the steepest-descent contour put \\( \\sigma = s\\,e^{i\\theta} \\) with \\( \\theta = \\tfrac{3\\pi}{4} \\) and \\( s \\) real. Show that \\( -\\tfrac12 i\\nu\\tan\\alpha\\,\\sigma^2 = -\\tfrac12\\nu\\tan\\alpha\\,s^2 \\), i.e. the exponent is real and negative.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "real exponent", "Gaussian"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Square the parametrisation.", workingLatex: "\\sigma^2 = s^2 e^{2i\\theta} = s^2 e^{\\,3i\\pi/2} = s^2(-i).", explanation: "\\( e^{3i\\pi/2} = \\cos\\tfrac{3\\pi}{2} + i\\sin\\tfrac{3\\pi}{2} = -i \\)." },
        { stepNumber: 2, description: "Multiply by the prefactor −½ iν tan α.", workingLatex: "-\\tfrac12 i\\nu\\tan\\alpha\\,\\sigma^2 = -\\tfrac12 i\\nu\\tan\\alpha\\,(-i)s^2 = -\\tfrac12 \\nu\\tan\\alpha\\,s^2.", explanation: "\\( i\\cdot(-i) = 1 \\), so the two imaginary units cancel and the exponent collapses to a real, negative quadratic in \\( s \\)." },
        { stepNumber: 3, description: "Interpret.", workingLatex: "e^{\\nu\\varphi} \\approx e^{i\\nu(\\tan\\alpha-\\alpha)}\\,e^{-\\frac12\\nu\\tan\\alpha\\,s^2}.", explanation: "This confirms \\( \\theta = 3\\pi/4 \\) is a true descent direction: along it the integrand is the saddle value times a decaying Gaussian in the real variable \\( s \\)." },
      ],
      finalAnswer: "\\( -\\tfrac12 i\\nu\\tan\\alpha\\,\\sigma^2 = -\\tfrac12\\nu\\tan\\alpha\\,s^2 \\) (real, negative).",
    },
  },
  {
    id: "am8b-011",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "With \\( dt = d\\sigma = e^{i\\theta}\\,ds \\) and \\( \\theta = \\tfrac{3\\pi}{4} \\), evaluate the Gaussian \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-\\frac12\\nu\\tan\\alpha\\,s^2}\\,e^{i\\theta}\\,ds \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian integral", "phase factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Pull out the constant Jacobian phase.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-\\frac12\\nu\\tan\\alpha\\,s^2}\\,e^{i\\theta}\\,ds = e^{i\\theta}\\int_{-\\infty}^{\\infty} e^{-\\frac12\\nu\\tan\\alpha\\,s^2}\\,ds.", explanation: "The direction factor \\( e^{i\\theta} \\) is constant along the straight descent line, so it comes outside the integral." },
        { stepNumber: 2, description: "Apply the standard Gaussian integral.", workingLatex: "\\int_{-\\infty}^{\\infty} e^{-a s^2}\\,ds = \\sqrt{\\frac{\\pi}{a}}, \\qquad a = \\tfrac12\\nu\\tan\\alpha.", explanation: "Here \\( a>0 \\) since \\( 0<\\alpha<\\pi/2 \\Rightarrow \\tan\\alpha>0 \\), so the integral converges." },
        { stepNumber: 3, description: "Insert a and simplify.", workingLatex: "= e^{i\\theta}\\sqrt{\\frac{\\pi}{\\tfrac12\\nu\\tan\\alpha}} = e^{i\\theta}\\sqrt{\\frac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "The \\( \\tfrac12 \\) in the denominator becomes a factor of \\( 2 \\) under the square root." },
        { stepNumber: 4, description: "Insert the direction phase.", workingLatex: "= e^{\\,3i\\pi/4}\\sqrt{\\frac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "This is the local saddle contribution before multiplying by the saddle value and the \\( -1/\\pi \\) prefactor." },
      ],
      finalAnswer: "\\( e^{\\,3i\\pi/4}\\sqrt{\\dfrac{2\\pi}{\\nu\\tan\\alpha}} \\)",
    },
  },
  {
    id: "am8b-012",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Combine the pieces: \\( H^{(1)}_\\nu = -\\tfrac1\\pi\\,e^{\\nu\\varphi(t_0)}\\,e^{3i\\pi/4}\\sqrt{2\\pi/(\\nu\\tan\\alpha)} \\). Show that the \\( -\\tfrac1\\pi \\) and \\( e^{3i\\pi/4} \\) combine to give the amplitude \\( \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2} \\) and the phase \\( e^{-i\\pi/4} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Hankel function", "phase assembly"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Combine the magnitude factors.", workingLatex: "\\frac{1}{\\pi}\\sqrt{\\frac{2\\pi}{\\nu\\tan\\alpha}} = \\sqrt{\\frac{2}{\\pi\\nu\\tan\\alpha}} = \\sqrt2\\,(\\pi\\nu\\tan\\alpha)^{-1/2}.", explanation: "Squaring the \\( 1/\\pi \\) inside the root turns the numerator \\( 2\\pi \\) into \\( 2/\\pi \\)." },
        { stepNumber: 2, description: "Write the overall minus sign as a phase.", workingLatex: "-1 = e^{i\\pi}.", explanation: "Treat the \\( -1 \\) as a unit-modulus phase so it can be merged with the steepest-descent direction phase." },
        { stepNumber: 3, description: "Combine the two phases.", workingLatex: "e^{i\\pi}\\cdot e^{\\,3i\\pi/4} = e^{\\,7i\\pi/4} = e^{-i\\pi/4}.", explanation: "\\( 7\\pi/4 \\) and \\( -\\pi/4 \\) differ by \\( 2\\pi \\), so they denote the same phase: this is the celebrated \\( e^{-i\\pi/4} \\)." },
        { stepNumber: 4, description: "Assemble with the saddle value.", workingLatex: "H^{(1)}_\\nu\\!\\Big(\\tfrac{\\nu}{\\cos\\alpha}\\Big) \\sim \\sqrt2\\,(\\pi\\nu\\tan\\alpha)^{-1/2}\\,e^{\\,i\\nu(\\tan\\alpha-\\alpha)}\\,e^{-i\\pi/4}.", explanation: "Multiplying in \\( e^{\\nu\\varphi(t_0)} = e^{i\\nu(\\tan\\alpha-\\alpha)} \\) completes the Debye asymptotic for the Hankel function." },
      ],
      finalAnswer: "\\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{i\\nu(\\tan\\alpha-\\alpha)}e^{-i\\pi/4} \\)",
      canonicalAnswer: "sqrt(2)*(pi*nu*tan(alpha))^(-1/2)*exp(I*nu*(tan(alpha)-alpha))*exp(-I*pi/4)",
    },
  },
  {
    id: "am8b-013",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Take \\( \\alpha = \\tfrac{\\pi}{4} \\), so \\( \\tan\\alpha = 1 \\). Write the leading asymptotic form of \\( H^{(1)}_\\nu(\\nu\\sqrt2) \\) as \\( \\nu \\to \\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Hankel function", "special value"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the argument.", workingLatex: "x = \\nu\\sec\\tfrac{\\pi}{4} = \\nu\\sqrt2.", explanation: "\\( \\sec(\\pi/4) = 1/\\cos(\\pi/4) = \\sqrt2 \\)." },
        { stepNumber: 2, description: "Substitute α = π/4 into the general result.", workingLatex: "H^{(1)}_\\nu(\\nu\\sqrt2) \\sim \\sqrt2\\,(\\pi\\nu\\cdot 1)^{-1/2}\\,e^{\\,i\\nu(1 - \\pi/4)}\\,e^{-i\\pi/4}.", explanation: "Here \\( \\tan(\\pi/4) = 1 \\) and \\( \\tan\\alpha - \\alpha = 1 - \\pi/4 \\)." },
        { stepNumber: 3, description: "Simplify the amplitude.", workingLatex: "H^{(1)}_\\nu(\\nu\\sqrt2) \\sim \\sqrt{\\frac{2}{\\pi\\nu}}\\;e^{\\,i\\nu(1-\\pi/4)}\\,e^{-i\\pi/4}.", explanation: "With \\( \\tan\\alpha=1 \\) the amplitude collapses to \\( \\sqrt{2/(\\pi\\nu)} \\); numerically the ratio of this to the exact Hankel value tends to \\( 1 \\) as \\( \\nu\\to\\infty \\)." },
      ],
      finalAnswer: "\\( H^{(1)}_\\nu(\\nu\\sqrt2) \\sim \\sqrt{\\dfrac{2}{\\pi\\nu}}\\,e^{i\\nu(1-\\pi/4)}e^{-i\\pi/4} \\)",
    },
  },
  {
    id: "am8b-014",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "From \\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{i\\nu(\\tan\\alpha-\\alpha)}e^{-i\\pi/4} \\), write the leading asymptotic modulus \\( \\big|H^{(1)}_\\nu(\\nu\\sec\\alpha)\\big| \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "modulus", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take moduli of each factor.", workingLatex: "\\big|e^{i\\nu(\\tan\\alpha-\\alpha)}\\big| = 1, \\qquad \\big|e^{-i\\pi/4}\\big| = 1.", explanation: "Both exponentials are pure phases of unit modulus, so they do not contribute to the magnitude." },
        { stepNumber: 2, description: "Keep the real amplitude.", workingLatex: "\\big|H^{(1)}_\\nu(\\nu\\sec\\alpha)\\big| \\sim \\sqrt2\\,(\\pi\\nu\\tan\\alpha)^{-1/2} = \\sqrt{\\frac{2}{\\pi\\nu\\tan\\alpha}}.", explanation: "The amplitude decays like \\( \\nu^{-1/2} \\); it grows without bound as \\( \\alpha\\to 0^+ \\) (\\( \\tan\\alpha\\to 0 \\)), signalling the breakdown of this expansion near the turning point \\( x = \\nu \\)." },
      ],
      finalAnswer: "\\( \\big|H^{(1)}_\\nu(\\nu\\sec\\alpha)\\big| \\sim \\sqrt{\\dfrac{2}{\\pi\\nu\\tan\\alpha}} \\)",
      canonicalAnswer: "sqrt(2/(pi*nu*tan(alpha)))",
    },
  },
  {
    id: "am8b-015",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "From the same leading form, write the leading asymptotic phase \\( \\arg H^{(1)}_\\nu(\\nu\\sec\\alpha) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "argument", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Collect the phase factors.", workingLatex: "e^{\\,i\\nu(\\tan\\alpha-\\alpha)}\\,e^{-i\\pi/4} = \\exp\\!\\Big[i\\big(\\nu(\\tan\\alpha-\\alpha) - \\tfrac{\\pi}{4}\\big)\\Big].", explanation: "The real amplitude is positive, so it contributes nothing to the argument; only the exponentials matter." },
        { stepNumber: 2, description: "Read off the argument.", workingLatex: "\\arg H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\nu(\\tan\\alpha-\\alpha) - \\frac{\\pi}{4} \\ (\\mathrm{mod}\\ 2\\pi).", explanation: "The dominant \\( \\nu(\\tan\\alpha-\\alpha) \\) term is the rapidly winding Debye phase; the constant \\( -\\pi/4 \\) is the steepest-descent correction." },
      ],
      finalAnswer: "\\( \\arg H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\nu(\\tan\\alpha-\\alpha) - \\tfrac{\\pi}{4} \\)",
    },
  },
  {
    id: "am8b-016",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Explain, by considering \\( \\cos t = \\cos\\alpha \\) and the constraint \\( -\\pi \\le \\operatorname{Re}(t) < 0 \\), why the saddle \\( t_0 = -\\alpha \\) (and not \\( t_0 = +\\alpha \\)) is the one through which the contour is deformed. State the saddle value at \\( t = +\\alpha \\) for contrast.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "saddle selection", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List both saddles.", workingLatex: "\\cos t = \\cos\\alpha \\;\\Rightarrow\\; t = -\\alpha \\ \\text{or}\\ t = +\\alpha \\ (\\mathrm{mod}\\ 2\\pi).", explanation: "The saddle condition has two roots in the relevant strip; we must decide which the contour passes through." },
        { stepNumber: 2, description: "Apply the contour constraint.", workingLatex: "-\\pi \\le \\operatorname{Re}(t) < 0 \\;\\Rightarrow\\; t = -\\alpha \\in (-\\tfrac{\\pi}{2}, 0).", explanation: "Since \\( 0<\\alpha<\\pi/2 \\), the value \\( +\\alpha \\) has positive real part and lies outside the prescribed strip, whereas \\( -\\alpha \\) lies inside it; only \\( -\\alpha \\) can be reached by deforming the given contour." },
        { stepNumber: 3, description: "Contrast the saddle values.", workingLatex: "\\varphi(+\\alpha) = i(\\alpha - \\tan\\alpha) = -\\,\\varphi(-\\alpha).", explanation: "The saddle at \\( +\\alpha \\) gives the complex conjugate phase \\( e^{-i\\nu(\\tan\\alpha-\\alpha)} \\), which is the behaviour relevant to \\( H^{(2)}_\\nu \\); selecting \\( -\\alpha \\) is what makes this the first Hankel function." },
      ],
      finalAnswer: "Saddle \\( t_0 = -\\alpha \\) (in strip); for contrast \\( \\varphi(+\\alpha) = i(\\alpha-\\tan\\alpha) \\).",
    },
  },
  {
    id: "am8b-017",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Verify that the saddle value \\( \\varphi(t_0) = i(\\tan\\alpha - \\alpha) \\) is purely imaginary, and explain what this implies about \\( \\big|H^{(1)}_\\nu(\\nu\\sec\\alpha)\\big| \\) versus the algebraic prefactor.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "oscillatory", "modulus"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Inspect the saddle value.", workingLatex: "\\varphi(t_0) = i(\\tan\\alpha - \\alpha), \\qquad \\operatorname{Re}\\varphi(t_0) = 0.", explanation: "With \\( 0<\\alpha<\\pi/2 \\) the real part vanishes identically; \\( \\tan\\alpha - \\alpha \\) is real and positive." },
        { stepNumber: 2, description: "Translate to the exponential factor.", workingLatex: "\\big|e^{\\nu\\varphi(t_0)}\\big| = e^{\\nu\\,\\operatorname{Re}\\varphi(t_0)} = e^{0} = 1.", explanation: "A purely imaginary exponent contributes only oscillation, no exponential growth or decay." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "\\big|H^{(1)}_\\nu\\big| \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}.", explanation: "Because the saddle exponential has modulus \\( 1 \\), the entire magnitude comes from the algebraic prefactor; this is the hallmark of the oscillatory regime \\( x>\\nu \\), in contrast to the exponentially small/large behaviour for \\( x<\\nu \\)." },
      ],
      finalAnswer: "\\( \\operatorname{Re}\\varphi(t_0)=0 \\Rightarrow |H^{(1)}_\\nu|\\sim\\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2} \\)",
    },
  },
  {
    id: "am8b-018",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate the path equation \\( u - \\sec\\alpha\\,\\sin u\\,\\cosh v = \\tan\\alpha - \\alpha \\) implicitly to find the slope \\( dv/du \\) of the steepest-descent contour at a general point, and evaluate it at the saddle \\( (u,v) = (-\\alpha, 0) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "path equation", "implicit differentiation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the constraint with respect to u.", workingLatex: "1 - \\sec\\alpha\\Big(\\cos u\\,\\cosh v + \\sin u\\,\\sinh v\\,\\frac{dv}{du}\\Big) = 0.", explanation: "Treat \\( v = v(u) \\) along the contour; the product rule acts on \\( \\sin u\\cosh v \\)." },
        { stepNumber: 2, description: "Solve for the slope.", workingLatex: "\\frac{dv}{du} = \\frac{1 - \\sec\\alpha\\,\\cos u\\,\\cosh v}{\\sec\\alpha\\,\\sin u\\,\\sinh v}.", explanation: "Rearranging isolates \\( dv/du \\); note both numerator and denominator vanish at the saddle, so a limit is needed there." },
        { stepNumber: 3, description: "Examine the saddle by the descent direction.", workingLatex: "\\text{At } (-\\alpha,0):\\ \\frac{dv}{du}\\to \\tan\\theta = \\tan\\tfrac{3\\pi}{4} = -1.", explanation: "The \\( 0/0 \\) form at the saddle is resolved by the local quadratic analysis: the descent line leaves at angle \\( \\theta = 3\\pi/4 \\) to the real axis, giving slope \\( \\tan(3\\pi/4) = -1 \\)." },
      ],
      finalAnswer: "\\( \\dfrac{dv}{du} = \\dfrac{1 - \\sec\\alpha\\cos u\\cosh v}{\\sec\\alpha\\sin u\\sinh v} \\); slope \\( -1 \\) at the saddle.",
    },
  },

  // ── Challenge: synoptic / multi-step / starred-level ──────────────────────
  {
    id: "am8b-019",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Carry out the full steepest-descent derivation of \\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\) as \\( \\nu\\to+\\infty \\), starting from \\( H^{(1)}_\\nu(x) = -\\tfrac1\\pi\\int e^{i(\\nu t - x\\sin t)}dt \\), and obtain \\( \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{i\\nu(\\tan\\alpha-\\alpha)}e^{-i\\pi/4} \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Hankel function", "full derivation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Scale the exponent.", workingLatex: "x=\\nu\\sec\\alpha \\Rightarrow H^{(1)}_\\nu = -\\tfrac1\\pi\\int e^{\\nu\\varphi(t)}dt,\\quad \\varphi(t)=i(t-\\sec\\alpha\\sin t).", explanation: "Large-order limit with \\( x/\\nu = \\sec\\alpha > 1 \\) fixed; \\( \\nu \\) becomes the large saddle-point parameter." },
        { stepNumber: 2, description: "Locate the saddle.", workingLatex: "\\varphi'(t)=i(1-\\sec\\alpha\\cos t)=0 \\Rightarrow \\cos t=\\cos\\alpha \\Rightarrow t_0=-\\alpha.", explanation: "The strip constraint \\( -\\pi\\le\\operatorname{Re}t<0 \\) selects \\( -\\alpha \\) over \\( +\\alpha \\)." },
        { stepNumber: 3, description: "Saddle value and curvature.", workingLatex: "\\varphi(t_0)=i(\\tan\\alpha-\\alpha),\\qquad \\varphi''(t_0)=-i\\tan\\alpha.", explanation: "Both from \\( \\sec\\alpha\\sin\\alpha=\\tan\\alpha \\); \\( \\varphi'' \\) has modulus \\( \\tan\\alpha \\), argument \\( -\\pi/2 \\)." },
        { stepNumber: 4, description: "Descent direction.", workingLatex: "\\varphi''(t_0)\\sigma^2<0 \\Rightarrow -\\tfrac\\pi2+2\\theta=\\pi \\Rightarrow \\theta=\\tfrac{3\\pi}{4}.", explanation: "Choosing \\( \\arg\\sigma = 3\\pi/4 \\) makes the local quadratic real and negative — a true descent line." },
        { stepNumber: 5, description: "Gaussian integral on the contour.", workingLatex: "\\int e^{\\nu\\varphi}dt \\approx e^{i\\nu(\\tan\\alpha-\\alpha)}e^{i\\theta}\\!\\int_{-\\infty}^{\\infty}\\! e^{-\\frac12\\nu\\tan\\alpha\\,s^2}ds = e^{i\\nu(\\tan\\alpha-\\alpha)}e^{3i\\pi/4}\\sqrt{\\tfrac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "Width set by \\( |\\varphi''|=\\tan\\alpha \\); the constant \\( e^{i\\theta} \\) Jacobian comes outside." },
        { stepNumber: 6, description: "Apply the −1/π prefactor.", workingLatex: "H^{(1)}_\\nu = -\\tfrac1\\pi\\,e^{i\\nu(\\tan\\alpha-\\alpha)}e^{3i\\pi/4}\\sqrt{\\tfrac{2\\pi}{\\nu\\tan\\alpha}}.", explanation: "Reinstate the overall factor from the integral representation." },
        { stepNumber: 7, description: "Collapse magnitude and phase.", workingLatex: "= \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}\\,e^{i\\nu(\\tan\\alpha-\\alpha)}\\,e^{-i\\pi/4}.", explanation: "\\( \\tfrac1\\pi\\sqrt{2\\pi/(\\nu\\tan\\alpha)}=\\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2} \\) and \\( e^{i\\pi}e^{3i\\pi/4}=e^{-i\\pi/4} \\). Numerically \\( H_{\\text{exact}}/H_{\\text{approx}}\\to1 \\) as \\( \\nu\\to\\infty \\)." },
      ],
      finalAnswer: "\\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{i\\nu(\\tan\\alpha-\\alpha)}e^{-i\\pi/4} \\)",
      canonicalAnswer: "sqrt(2)*(pi*nu*tan(alpha))^(-1/2)*exp(I*nu*(tan(alpha)-alpha))*exp(-I*pi/4)",
    },
  },
  {
    id: "am8b-020",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using \\( J_\\nu = \\operatorname{Re} H^{(1)}_\\nu \\) and \\( Y_\\nu = \\operatorname{Im} H^{(1)}_\\nu \\) for real order and argument, derive the large-order Debye approximations \\( J_\\nu(\\nu\\sec\\alpha) \\) and \\( Y_\\nu(\\nu\\sec\\alpha) \\) from the Hankel result.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Bessel functions", "Debye expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the Hankel result in modulus–phase form.", workingLatex: "H^{(1)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\,\\exp\\!\\Big[i\\big(\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4\\big)\\Big].", explanation: "Amplitude is real and positive; the bracketed quantity is the total phase \\( \\Phi \\)." },
        { stepNumber: 2, description: "Define the phase.", workingLatex: "\\Phi \\equiv \\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4.", explanation: "A single real phase controls both Bessel functions through Euler's formula." },
        { stepNumber: 3, description: "Take the real part for J.", workingLatex: "J_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\,\\cos\\Phi.", explanation: "\\( \\operatorname{Re}(Ae^{i\\Phi})=A\\cos\\Phi \\) for real \\( A \\)." },
        { stepNumber: 4, description: "Take the imaginary part for Y.", workingLatex: "Y_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\,\\sin\\Phi.", explanation: "\\( \\operatorname{Im}(Ae^{i\\Phi})=A\\sin\\Phi \\). These are the standard Debye asymptotics for the oscillatory region \\( x>\\nu \\); a numerical check at \\( \\nu=40,\\ \\alpha=\\pi/4 \\) confirms \\( Y_\\nu \\) (the dominant part) to a few parts in \\( 10^3 \\)." },
      ],
      finalAnswer: "\\( J_\\nu \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\cos\\Phi,\\quad Y_\\nu \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\sin\\Phi,\\ \\Phi=\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4 \\)",
    },
  },
  {
    id: "am8b-021",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider the behaviour of the result as \\( \\alpha\\to 0^+ \\) (i.e. \\( x\\to\\nu^+ \\), the turning point). Show that the amplitude \\( \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2} \\) and phase \\( \\nu(\\tan\\alpha-\\alpha) \\) both degenerate, and identify what kind of expansion is needed instead.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "turning point", "Airy"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Amplitude as α → 0.", workingLatex: "\\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2} \\sim \\sqrt2(\\pi\\nu\\alpha)^{-1/2} \\to \\infty.", explanation: "\\( \\tan\\alpha\\sim\\alpha \\), so the prefactor blows up — the Debye expansion loses validity exactly where the two saddles \\( \\pm\\alpha \\) coalesce." },
        { stepNumber: 2, description: "Phase as α → 0.", workingLatex: "\\tan\\alpha-\\alpha = \\Big(\\alpha+\\tfrac{\\alpha^3}{3}+\\cdots\\Big)-\\alpha = \\tfrac{\\alpha^3}{3}+O(\\alpha^5).", explanation: "The leading phase is cubic in \\( \\alpha \\), not linear; this cubic dependence is the signature of an Airy-type transition." },
        { stepNumber: 3, description: "Identify the breakdown condition.", workingLatex: "\\nu(\\tan\\alpha-\\alpha) \\sim \\tfrac{\\nu\\alpha^3}{3} = O(1) \\ \\Rightarrow\\ \\alpha = O(\\nu^{-1/3}).", explanation: "When \\( \\alpha\\sim\\nu^{-1/3} \\) the two saddles are within \\( O(\\nu^{-1/3}) \\) of one another and the quadratic (Gaussian) approximation fails." },
        { stepNumber: 4, description: "State the required expansion.", workingLatex: "H^{(1)}_\\nu(\\nu+\\zeta\\nu^{1/3}) \\sim (\\text{const})\\,\\nu^{-1/3}\\,\\mathrm{Ai}\\big(-2^{1/3}\\zeta\\big)\\text{-type form}.", explanation: "Near the turning point the cubic phase forces a coalescing-saddle (uniform) analysis, giving an Airy-function approximation rather than the simple Gaussian steepest-descent form." },
      ],
      finalAnswer: "Amplitude \\( \\to\\infty \\), phase \\( \\sim\\nu\\alpha^3/3 \\); breakdown at \\( \\alpha=O(\\nu^{-1/3}) \\) requiring an Airy (coalescing-saddle) expansion.",
    },
  },
  {
    id: "am8b-022",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By replacing the saddle at \\( t_0 = -\\alpha \\) with \\( t_0 = +\\alpha \\) (the conjugate saddle), derive the corresponding large-order asymptotic for the second Hankel function \\( H^{(2)}_\\nu(\\nu\\sec\\alpha) \\), and check it is the complex conjugate of the \\( H^{(1)} \\) result.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Hankel function", "conjugate saddle"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Saddle value at +α.", workingLatex: "\\varphi(+\\alpha) = i(\\alpha - \\tan\\alpha) = -i(\\tan\\alpha-\\alpha).", explanation: "Conjugate of the \\( -\\alpha \\) saddle value; the exponential becomes \\( e^{-i\\nu(\\tan\\alpha-\\alpha)} \\)." },
        { stepNumber: 2, description: "Curvature at +α.", workingLatex: "\\varphi''(+\\alpha) = i\\sec\\alpha\\sin\\alpha = +i\\tan\\alpha = \\tan\\alpha\\,e^{+i\\pi/2}.", explanation: "Sign flips relative to \\( -\\alpha \\); the argument is now \\( +\\pi/2 \\)." },
        { stepNumber: 3, description: "Descent direction.", workingLatex: "+\\tfrac\\pi2+2\\theta=\\pi \\Rightarrow \\theta=\\tfrac\\pi4.", explanation: "The conjugate curvature gives the conjugate descent angle \\( \\theta = \\pi/4 \\)." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "H^{(2)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}\\,e^{-i\\nu(\\tan\\alpha-\\alpha)}\\,e^{+i\\pi/4}.", explanation: "Every \\( i \\) is conjugated relative to the \\( H^{(1)} \\) calculation, including the phase factor." },
        { stepNumber: 5, description: "Confirm the conjugate relation.", workingLatex: "H^{(2)}_\\nu(\\nu\\sec\\alpha) = \\overline{H^{(1)}_\\nu(\\nu\\sec\\alpha)}.", explanation: "Consistent with the exact identity \\( H^{(2)}_\\nu(x) = \\overline{H^{(1)}_\\nu(x)} \\) for real \\( \\nu \\) and real \\( x \\); a reassuring cross-check on the steepest-descent bookkeeping." },
      ],
      finalAnswer: "\\( H^{(2)}_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{-i\\nu(\\tan\\alpha-\\alpha)}e^{+i\\pi/4} = \\overline{H^{(1)}_\\nu} \\)",
    },
  },
  {
    id: "am8b-023",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Take the limit of the Debye result \\( H^{(1)}_\\nu(\\nu\\sec\\alpha)\\sim\\sqrt2(\\pi\\nu\\tan\\alpha)^{-1/2}e^{i\\nu(\\tan\\alpha-\\alpha)}e^{-i\\pi/4} \\) as \\( \\alpha\\to\\tfrac\\pi2^- \\) and compare with the large-argument form \\( H^{(1)}_\\nu(x)\\sim\\sqrt{2/(\\pi x)}\\,e^{i(x-\\nu\\pi/2-\\pi/4)} \\). Show consistency to leading order.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "large argument", "consistency check"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Behaviour of the argument as α → π/2.", workingLatex: "x = \\nu\\sec\\alpha \\to \\infty, \\qquad \\tan\\alpha \\to \\infty, \\qquad \\sec\\alpha\\approx\\tan\\alpha.", explanation: "Letting \\( \\alpha\\to\\pi/2 \\) drives \\( x/\\nu\\to\\infty \\), the regime \\( x\\gg\\nu \\) where the classical large-argument expansion holds." },
        { stepNumber: 2, description: "Amplitude comparison.", workingLatex: "\\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}} \\approx \\sqrt{\\tfrac{2}{\\pi\\nu\\sec\\alpha}} = \\sqrt{\\tfrac{2}{\\pi x}}.", explanation: "Since \\( \\tan\\alpha\\approx\\sec\\alpha \\) for \\( \\alpha\\to\\pi/2 \\), and \\( \\nu\\sec\\alpha=x \\), the Debye amplitude reduces to \\( \\sqrt{2/(\\pi x)} \\)." },
        { stepNumber: 3, description: "Expand the phase.", workingLatex: "\\nu(\\tan\\alpha-\\alpha) = \\nu\\tan\\alpha - \\nu\\alpha \\approx \\nu\\sec\\alpha - \\nu\\Big(\\tfrac\\pi2 - (\\tfrac\\pi2-\\alpha)\\Big).", explanation: "Write \\( \\alpha = \\pi/2 - \\beta \\) with small \\( \\beta \\): then \\( \\tan\\alpha=\\cot\\beta\\approx 1/\\beta \\) and \\( \\sec\\alpha=1/\\sin\\beta\\approx1/\\beta \\), so \\( \\tan\\alpha\\approx\\sec\\alpha=x/\\nu \\)." },
        { stepNumber: 4, description: "Identify the phase terms.", workingLatex: "\\nu(\\tan\\alpha-\\alpha) - \\tfrac\\pi4 \\approx x - \\nu\\tfrac\\pi2 - \\tfrac\\pi4.", explanation: "\\( \\nu\\tan\\alpha\\approx x \\) and \\( \\nu\\alpha\\to\\nu\\pi/2 \\); the constant \\( -\\pi/4 \\) carries through unchanged." },
        { stepNumber: 5, description: "Conclude consistency.", workingLatex: "H^{(1)}_\\nu(x)\\sim\\sqrt{\\tfrac{2}{\\pi x}}\\,e^{i(x-\\nu\\pi/2-\\pi/4)}.", explanation: "Both amplitude and phase match the textbook large-argument Hankel form, confirming the Debye result interpolates correctly into the \\( x\\gg\\nu \\) regime." },
      ],
      finalAnswer: "Reduces to \\( \\sqrt{2/(\\pi x)}\\,e^{i(x-\\nu\\pi/2-\\pi/4)} \\), matching the large-argument form.",
    },
  },
  {
    id: "am8b-024",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Justify that the contour through \\( t_0=-\\alpha \\) defined by \\( \\operatorname{Im}\\varphi=\\tan\\alpha-\\alpha \\) is steepest descent (not ascent). Use the local behaviour of \\( \\operatorname{Re}\\varphi \\) along the chosen direction \\( \\arg\\sigma=3\\pi/4 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "justification", "constant phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Local real part of the phase.", workingLatex: "\\operatorname{Re}\\big[\\nu\\varphi\\big] \\approx \\nu\\operatorname{Re}\\varphi(t_0) + \\operatorname{Re}\\big[\\tfrac12\\nu\\varphi''(t_0)\\sigma^2\\big].", explanation: "\\( \\operatorname{Re}\\varphi(t_0)=0 \\); the quadratic term governs whether \\( \\operatorname{Re}\\varphi \\) increases or decreases away from the saddle." },
        { stepNumber: 2, description: "Insert the descent direction.", workingLatex: "\\tfrac12\\varphi''(t_0)\\sigma^2 = \\tfrac12(-i\\tan\\alpha)(s^2 e^{3i\\pi/2}) = -\\tfrac12\\tan\\alpha\\,s^2.", explanation: "With \\( \\sigma=se^{3i\\pi/4} \\), \\( \\sigma^2=s^2e^{3i\\pi/2}=-is^2 \\), and \\( (-i)(-i)=-1 \\), giving a real negative result." },
        { stepNumber: 3, description: "Sign of Re φ along the path.", workingLatex: "\\operatorname{Re}\\varphi \\approx -\\tfrac12\\tan\\alpha\\,s^2 < 0 \\quad(s\\neq 0).", explanation: "Moving away from the saddle in either direction along this line makes \\( \\operatorname{Re}\\varphi \\) decrease, so \\( |e^{\\nu\\varphi}| \\) falls — the defining property of steepest descent." },
        { stepNumber: 4, description: "Contrast with the orthogonal direction.", workingLatex: "\\arg\\sigma=\\tfrac\\pi4: \\ \\sigma^2=is^2 \\Rightarrow \\operatorname{Re}\\varphi\\approx +\\tfrac12\\tan\\alpha\\,s^2>0.", explanation: "The perpendicular line \\( \\arg\\sigma=\\pi/4 \\) is steepest ascent; the constant-phase curve is steepest descent precisely along \\( 3\\pi/4 \\), confirming the contour choice." },
      ],
      finalAnswer: "Along \\( \\arg\\sigma=3\\pi/4 \\), \\( \\operatorname{Re}\\varphi\\approx-\\tfrac12\\tan\\alpha\\,s^2<0 \\): genuine steepest descent.",
    },
  },
  {
    id: "am8b-025",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 25",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the next-order correction to the leading steepest-descent result by writing the relative correction as \\( 1 + c_1/\\nu + \\cdots \\). For the Debye expansion of \\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\) the first correction coefficient is \\( c_1 = \\dfrac{i}{8}\\Big(3\\cot\\alpha - 5\\cot^3\\alpha\\Big)\\cdot\\tfrac{1}{?} \\) — instead, state the standard form of the correction series and the value of its leading coefficient \\( u_1(\\coth\\xi) \\) structure for this problem, given \\( \\sec\\alpha=\\cosh\\xi \\) does not apply here; use \\( t=\\cot\\alpha \\) and quote \\( c_1=\\dfrac{i}{8}\\Big(3\\cot\\alpha+5\\cot^3\\alpha\\Big) \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "higher-order", "Debye series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the correction framework.", workingLatex: "\\int e^{\\nu\\varphi}dt \\sim e^{\\nu\\varphi_0}\\sqrt{\\tfrac{2\\pi}{\\nu|\\varphi''|}}e^{i\\theta}\\Big(1 + \\frac{c_1}{\\nu}+\\cdots\\Big).", explanation: "The standard Laplace/saddle correction uses the cubic and quartic Taylor coefficients of \\( \\varphi \\) at the saddle." },
        { stepNumber: 2, description: "Higher derivatives of φ.", workingLatex: "\\varphi'''(t_0)=i\\sec\\alpha\\cos(-\\alpha)=i,\\quad \\varphi''''(t_0)=-i\\sec\\alpha\\sin(-\\alpha)=i\\tan\\alpha.", explanation: "Differentiating \\( \\varphi''=i\\sec\\alpha\\sin t \\) twice more and evaluating at \\( t_0=-\\alpha \\); \\( \\sec\\alpha\\cos\\alpha=1 \\)." },
        { stepNumber: 3, description: "Standard saddle correction coefficient.", workingLatex: "c_1 = \\frac{1}{\\nu}\\!\\left[\\frac{\\varphi''''}{8(\\varphi'')^2} - \\frac{5(\\varphi''')^2}{24(\\varphi'')^3}\\right]\\nu \\;=\\; \\frac{\\varphi''''}{8(\\varphi'')^2} - \\frac{5(\\varphi''')^2}{24(\\varphi'')^3}.", explanation: "This is the textbook one-term correction for \\( \\int e^{\\nu\\varphi} \\) in terms of derivatives at the saddle." },
        { stepNumber: 4, description: "Substitute the derivative values.", workingLatex: "c_1 = \\frac{i\\tan\\alpha}{8(-i\\tan\\alpha)^2} - \\frac{5(i)^2}{24(-i\\tan\\alpha)^3}.", explanation: "Insert \\( \\varphi''=-i\\tan\\alpha,\\ \\varphi'''=i,\\ \\varphi''''=i\\tan\\alpha \\)." },
        { stepNumber: 5, description: "Simplify each term.", workingLatex: "\\frac{i\\tan\\alpha}{8(-\\tan^2\\alpha)} = -\\frac{i}{8}\\cot\\alpha, \\qquad -\\frac{5(-1)}{24(i\\tan^3\\alpha)} = \\frac{5}{24i\\tan^3\\alpha} = -\\frac{5i}{24}\\cot^3\\alpha.", explanation: "Using \\( (-i)^2=-1,\\ (-i)^3=i \\), and \\( 1/i=-i \\). Both terms are pure imaginary multiples of powers of \\( \\cot\\alpha \\)." },
        { stepNumber: 6, description: "Collect the correction.", workingLatex: "c_1 = -\\frac{i}{8}\\cot\\alpha - \\frac{5i}{24}\\cot^3\\alpha = -\\frac{i}{24}\\big(3\\cot\\alpha + 5\\cot^3\\alpha\\big).", explanation: "Common factor \\( -i/24 \\). This is the first Debye correction; the leading approximation is recovered as \\( c_1/\\nu\\to0 \\)." },
      ],
      finalAnswer: "\\( c_1 = -\\dfrac{i}{24}\\big(3\\cot\\alpha + 5\\cot^3\\alpha\\big) \\)",
      canonicalAnswer: "-I/24*(3*cot(alpha)+5*cot(alpha)^3)",
    },
  },
  {
    id: "am8b-026",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using \\( H^{(1)}_\\nu + H^{(2)}_\\nu = 2J_\\nu \\), combine the two saddle contributions (at \\( t_0=\\pm\\alpha \\)) directly to obtain \\( J_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\cos\\!\\big(\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4\\big) \\) as a sum of two complex exponentials.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Bessel function", "two saddles"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write both Hankel contributions.", workingLatex: "H^{(1)}_\\nu \\sim A\\,e^{i\\Phi}, \\quad H^{(2)}_\\nu \\sim A\\,e^{-i\\Phi}, \\quad A=\\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}},\\ \\Phi=\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4.", explanation: "From the \\( -\\alpha \\) and \\( +\\alpha \\) saddles respectively; \\( H^{(2)} \\) is the conjugate." },
        { stepNumber: 2, description: "Add and halve.", workingLatex: "J_\\nu = \\tfrac12\\big(H^{(1)}_\\nu+H^{(2)}_\\nu\\big) \\sim \\tfrac{A}{2}\\big(e^{i\\Phi}+e^{-i\\Phi}\\big).", explanation: "Standard relation between Bessel and Hankel functions for real argument and order." },
        { stepNumber: 3, description: "Apply Euler's cosine identity.", workingLatex: "e^{i\\Phi}+e^{-i\\Phi} = 2\\cos\\Phi.", explanation: "The two saddle contributions interfere to produce a real cosine — the physical, real-valued Bessel function." },
        { stepNumber: 4, description: "Collect.", workingLatex: "J_\\nu(\\nu\\sec\\alpha) \\sim A\\cos\\Phi = \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\,\\cos\\!\\Big(\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4\\Big).", explanation: "Both saddles contribute equally; their sum gives the correct real oscillatory Debye form for \\( J_\\nu \\) in the region \\( x>\\nu \\)." },
      ],
      finalAnswer: "\\( J_\\nu(\\nu\\sec\\alpha) \\sim \\sqrt{\\tfrac{2}{\\pi\\nu\\tan\\alpha}}\\cos\\big(\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4\\big) \\)",
    },
  },
  {
    id: "am8b-027",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 27",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Estimate \\( \\big|H^{(1)}_{40}(40\\sqrt2)\\big| \\) using the leading Debye amplitude with \\( \\alpha=\\tfrac\\pi4 \\), giving a decimal to 4 significant figures.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "numerical estimate", "Hankel function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify parameters.", workingLatex: "\\nu=40,\\quad \\alpha=\\tfrac\\pi4,\\quad \\tan\\alpha=1,\\quad x=40\\sqrt2.", explanation: "\\( \\sec(\\pi/4)=\\sqrt2 \\) so the argument is \\( 40\\sqrt2 \\), and \\( \\tan(\\pi/4)=1 \\)." },
        { stepNumber: 2, description: "Insert into the amplitude.", workingLatex: "\\big|H^{(1)}_{40}(40\\sqrt2)\\big| \\sim \\sqrt{\\frac{2}{\\pi\\cdot 40\\cdot 1}} = \\sqrt{\\frac{2}{40\\pi}} = \\sqrt{\\frac{1}{20\\pi}}.", explanation: "The amplitude is \\( \\sqrt{2/(\\pi\\nu\\tan\\alpha)} \\) with \\( \\tan\\alpha=1 \\)." },
        { stepNumber: 3, description: "Evaluate numerically.", workingLatex: "\\sqrt{\\frac{1}{20\\pi}} = \\sqrt{0.015915\\ldots} = 0.12616\\ldots", explanation: "\\( 20\\pi\\approx 62.832 \\), reciprocal \\( \\approx 0.015915 \\), square root \\( \\approx 0.12616 \\)." },
        { stepNumber: 4, description: "Compare with the exact value.", workingLatex: "0.1262 \\ \\text{vs.}\\ \\big|H^{(1)}_{40}(40\\sqrt2)\\big|_{\\text{exact}} = 0.12610.", explanation: "Agreement to about 1 part in \\( 2000 \\) (mpmath gives \\( 0.1261 \\)); the relative error scales like \\( 1/\\nu \\), consistent with the Debye correction." },
      ],
      finalAnswer: "\\( \\big|H^{(1)}_{40}(40\\sqrt2)\\big| \\approx 0.1262 \\)",
      canonicalAnswer: "0.1262",
    },
  },
  {
    id: "am8b-028",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Sketch (describe) the steepest-descent contour for \\( \\alpha=\\tfrac\\pi4 \\): give the path equation, the saddle location, the asymptotic directions as \\( |v|\\to\\infty \\), and the slope at the saddle. Justify the asymptotic directions.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "contour sketch", "path equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the path equation for α = π/4.", workingLatex: "u - \\sqrt2\\,\\sin u\\,\\cosh v = 1 - \\tfrac\\pi4 \\approx 0.2146.", explanation: "Substituting \\( \\sec(\\pi/4)=\\sqrt2 \\) and the saddle constant \\( \\tan(\\pi/4)-\\pi/4=1-\\pi/4 \\)." },
        { stepNumber: 2, description: "Mark the saddle.", workingLatex: "(u,v) = \\big(-\\tfrac\\pi4,\\,0\\big).", explanation: "The contour passes through \\( t_0=-\\pi/4 \\) on the real axis." },
        { stepNumber: 3, description: "Slope at the saddle.", workingLatex: "\\frac{dv}{du}\\Big|_{(-\\pi/4,0)} = \\tan\\tfrac{3\\pi}{4} = -1.", explanation: "From the descent direction \\( \\arg\\sigma=3\\pi/4 \\); the path crosses the real axis at \\( 135^\\circ \\)." },
        { stepNumber: 4, description: "Asymptotic directions as |v| → ∞.", workingLatex: "\\cosh v\\to\\infty \\Rightarrow \\sin u\\to 0 \\Rightarrow u\\to 0^- \\text{ or } u\\to -\\pi.", explanation: "For the equation to balance as \\( \\cosh v\\to\\infty \\), the coefficient \\( \\sin u \\) must vanish, forcing \\( u \\) toward a multiple of \\( \\pi \\) inside the strip." },
        { stepNumber: 5, description: "Select the admissible asymptotes.", workingLatex: "u\\to 0^- \\ (v\\to+\\infty), \\qquad u\\to -\\pi^+ \\ (v\\to-\\infty).", explanation: "The branch must keep \\( \\operatorname{Re}\\varphi \\) decreasing; the contour rises toward \\( \\operatorname{Re}t=0 \\) as \\( v\\to+\\infty \\) and descends toward \\( \\operatorname{Re}t=-\\pi \\) as \\( v\\to-\\infty \\), matching the endpoints of the original Hankel contour." },
      ],
      finalAnswer: "Path \\( u-\\sqrt2\\sin u\\cosh v=1-\\tfrac\\pi4 \\); saddle \\( (-\\tfrac\\pi4,0) \\), slope \\( -1 \\); asymptotes \\( u\\to0^-,\\ u\\to-\\pi^+ \\).",
    },
  },
  // REVIEW: leading-order coefficient/structure of the uniform Airy connection is a standard but unverified (non-numerically-checked) matching argument; the cube-root scaling is checked but the overall constant is quoted, not derived numerically.
  {
    id: "am8b-029",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that the e^{-iπ/4} factor is not removable by any choice of branch: that is, demonstrate that with the prescribed contour orientation the descent direction must be \\( 3\\pi/4 \\) (not \\( -\\pi/4 \\)), and that reversing it would correspond to the wrong contour traversal sense and hence the wrong Hankel function.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "orientation", "phase factor"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "The two descent half-lines.", workingLatex: "\\arg\\sigma = \\tfrac{3\\pi}{4} \\quad\\text{or}\\quad \\arg\\sigma = \\tfrac{3\\pi}{4}-\\pi = -\\tfrac\\pi4.", explanation: "A straight steepest-descent line has two opposite directions; the descent condition alone admits both." },
        { stepNumber: 2, description: "Orientation of the original contour.", workingLatex: "\\text{Path runs from } -i\\infty \\ \\text{upward to}\\ i\\infty-\\pi, \\quad \\text{i.e. increasing } \\operatorname{Im}t.", explanation: "The Hankel contour is traversed with increasing imaginary part; the deformed steepest path must inherit this sense." },
        { stepNumber: 3, description: "Match the traversal sense at the saddle.", workingLatex: "\\text{Increasing } \\operatorname{Im}t \\ \\text{near } t_0 \\Rightarrow \\text{move along } \\arg\\sigma=\\tfrac{3\\pi}{4} \\ (\\text{into } v>0).", explanation: "The branch with \\( \\arg\\sigma=3\\pi/4 \\) has positive imaginary increment \\( \\sin(3\\pi/4)>0 \\); the opposite branch \\( -\\pi/4 \\) would decrease \\( \\operatorname{Im}t \\), reversing the contour." },
        { stepNumber: 4, description: "Effect of reversing.", workingLatex: "\\arg\\sigma=-\\tfrac\\pi4 \\Rightarrow e^{i\\theta}=e^{-i\\pi/4} \\Rightarrow \\text{overall } e^{i\\pi}e^{-i\\pi/4}=e^{+3i\\pi/4}.", explanation: "Reversing the direction flips the Jacobian phase, producing \\( e^{+3i\\pi/4} \\) instead of \\( e^{-i\\pi/4} \\); equivalently it negates the whole integral (a sign \\( e^{i\\pi} \\))." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\text{Correct orientation} \\Rightarrow e^{-i\\pi/4}, \\ \\text{which is intrinsic to } H^{(1)}_\\nu.", explanation: "The \\( e^{-i\\pi/4} \\) is fixed by the contour's orientation, not a free branch choice; it is the genuine, physically meaningful phase of the outgoing-wave Hankel function." },
      ],
      finalAnswer: "Orientation forces \\( \\arg\\sigma=3\\pi/4 \\), giving the intrinsic \\( e^{-i\\pi/4} \\); reversal yields \\( e^{+3i\\pi/4} \\) (wrong sign).",
    },
  },
  {
    id: "am8b-030",
    topicRef: "am8b",
    topicTitle: "Steepest descent for H⁽¹⁾_ν 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A wave problem requires \\( H^{(1)}_\\nu(\\nu\\sec\\alpha) \\) with \\( \\nu=100 \\) and \\( \\alpha=\\tfrac\\pi3 \\). Using the leading Debye result, give the modulus to 4 significant figures and the leading phase \\( \\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4 \\) modulo \\( 2\\pi \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "numerical estimate", "phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the parameters.", workingLatex: "\\nu=100,\\ \\alpha=\\tfrac\\pi3,\\ \\tan\\tfrac\\pi3=\\sqrt3\\approx 1.7321.", explanation: "\\( \\sec(\\pi/3)=2 \\), so \\( x=200 \\)." },
        { stepNumber: 2, description: "Compute the modulus.", workingLatex: "\\big|H^{(1)}_{100}(200)\\big| \\sim \\sqrt{\\frac{2}{\\pi\\cdot100\\cdot\\sqrt3}} = \\sqrt{\\frac{2}{100\\pi\\sqrt3}}.", explanation: "Insert \\( \\nu\\tan\\alpha=100\\sqrt3 \\)." },
        { stepNumber: 3, description: "Evaluate.", workingLatex: "= \\sqrt{\\frac{2}{544.1}} = \\sqrt{0.003676} \\approx 0.06063.", explanation: "\\( 100\\pi\\sqrt3\\approx 544.1 \\); the exact mpmath modulus is \\( 0.06063 \\), agreeing to 4 s.f." },
        { stepNumber: 4, description: "Compute the leading phase.", workingLatex: "\\nu(\\tan\\alpha-\\alpha)-\\tfrac\\pi4 = 100\\big(\\sqrt3-\\tfrac\\pi3\\big)-\\tfrac\\pi4 \\approx 100(1.7321-1.0472)-0.7854.", explanation: "\\( \\tan(\\pi/3)-\\pi/3 = 1.7321-1.0472 = 0.68485 \\)." },
        { stepNumber: 5, description: "Reduce modulo 2π.", workingLatex: "\\approx 68.485 - 0.785 = 67.700 \\equiv 67.700 - 10\\cdot 2\\pi \\approx 4.868 \\ \\mathrm{rad}.", explanation: "\\( 10\\times2\\pi\\approx 62.832 \\); subtracting gives \\( 4.868 \\) rad. (mpmath gives the exact \\( \\arg \\) as \\( 4.867 \\) rad, agreeing to about \\( 3 \\) s.f.; the small offset is the \\( O(1/\\nu) \\) Debye phase correction.)" },
      ],
      finalAnswer: "\\( \\big|H^{(1)}_{100}(200)\\big|\\approx 0.06063 \\); leading phase \\( \\approx 4.868 \\) rad (mod \\( 2\\pi \\)).",
    },
  },
];
