import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — am9a
 * Iterative (fixed-point) asymptotics of roots
 * Topic group: Asymptotics of Algebraic & Transcendental Equations
 *
 * 30 fully-worked questions (6 Foundation, 12 Standard, 12 Challenge).
 * Technique: rearrange an algebraic / transcendental equation to the fixed-point
 * form x = g(x; parameter), substitute the leading behaviour, and iterate to
 * generate successive corrections of an asymptotic expansion of the root.
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 3, Q2
 * (x + x^{1/2} + 2 ln x = t + ln t), with constants / limits / framing varied.
 * Numerically checked roots and iterates with mpmath (see generation notes).
 *
 * Worked-solution fractions use big \\frac (project convention overriding the
 * style guide's \\tfrac rule).
 */
export const questions: Question[] = [
  // ────────────────────── FOUNDATION (6) ──────────────────────
  {
    id: "am9a-001",
    topicRef: "am9a",
    topicTitle: "Iterative roots 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Consider the equation \\( x^2 + \\varepsilon x - 1 = 0 \\) with small \\( \\varepsilon > 0 \\). Rearrange it into a fixed-point form \\( x = g(x) \\) suitable for iterating towards the positive root near \\( x = 1 \\), and state the leading-order approximation \\( x_0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "regular perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Isolate the dominant balance.", workingLatex: "x^2 = 1 - \\varepsilon x", explanation: "The two terms that survive as \\( \\varepsilon \\to 0 \\) are \\( x^2 \\) and \\( -1 \\); the \\( \\varepsilon x \\) term is a small correction. Keep it on the right so it is treated as a perturbation." },
        { stepNumber: 2, description: "Take the positive square root.", workingLatex: "x = \\sqrt{\\,1 - \\varepsilon x\\,}", explanation: "We want the root near \\( +1 \\), so take the positive branch. This is the fixed-point map \\( x = g(x) \\)." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x_0 = \\sqrt{1 - \\varepsilon \\cdot 0}\\Big|_{\\varepsilon = 0} = 1", explanation: "Setting \\( \\varepsilon = 0 \\) gives the unperturbed root, which seeds the iteration." },
      ],
      finalAnswer: "\\( x = \\sqrt{1 - \\varepsilon x} \\), with leading order \\( x_0 = 1 \\).",
    },
  },
  {
    id: "am9a-002",
    topicRef: "am9a",
    topicTitle: "Iterative roots 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The equation \\( x = N + \\ln x \\) has one large root as \\( N \\to +\\infty \\). Perform one iteration of the fixed-point map starting from \\( x_0 = N \\) to obtain the next approximation \\( x_1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the fixed-point map.", workingLatex: "x = g(x) = N + \\ln x", explanation: "The equation is already in the form \\( x = g(x) \\); the \\( \\ln x \\) term is small relative to \\( N \\)." },
        { stepNumber: 2, description: "Seed with the leading balance.", workingLatex: "x_0 = N", explanation: "Since \\( \\ln x = o(x) \\), the dominant balance is \\( x \\sim N \\)." },
        { stepNumber: 3, description: "Substitute once.", workingLatex: "x_1 = N + \\ln x_0 = N + \\ln N", explanation: "Feeding \\( x_0 = N \\) back through \\( g \\) gives the first correction \\( \\ln N \\)." },
      ],
      finalAnswer: "\\( x_1 = N + \\ln N \\).",
    },
  },
  {
    id: "am9a-003",
    topicRef: "am9a",
    topicTitle: "Iterative roots 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The equation \\( x^3 + x = N \\) has a large positive root as \\( N \\to +\\infty \\). Write it in a fixed-point form that isolates the cube, and give the leading-order approximation.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "cubic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant balance.", workingLatex: "x^3 \\sim N \\quad (x \\to \\infty)", explanation: "For large \\( N \\) the cubic term dominates the linear term, so \\( x^3 \\approx N \\)." },
        { stepNumber: 2, description: "Solve for x to form the map.", workingLatex: "x = \\left( N - x \\right)^{1/3}", explanation: "Move the small linear term to the right and take the real cube root; this is \\( x = g(x) \\)." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x_0 = N^{1/3}", explanation: "Dropping the \\( -x \\) correction inside the cube root gives the leading behaviour." },
      ],
      finalAnswer: "\\( x = (N - x)^{1/3} \\), with \\( x_0 = N^{1/3} \\).",
    },
  },
  {
    id: "am9a-004",
    topicRef: "am9a",
    topicTitle: "Iterative roots 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The transcendental equation \\( x\\,e^{x} = t \\) has a large root as \\( t \\to +\\infty \\). Take logarithms to write it as a fixed-point map \\( x = g(x) \\), and give the leading-order approximation \\( x_0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "Lambert W"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x + x = \\ln t", explanation: "Logarithms turn the product into a sum, exposing the additive structure." },
        { stepNumber: 2, description: "Isolate the large term.", workingLatex: "x = \\ln t - \\ln x", explanation: "The term \\( x \\) dominates \\( \\ln x \\), so put \\( \\ln x \\) on the right as the small correction. This is the map." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x_0 = \\ln t", explanation: "Dropping the \\( \\ln x \\) term gives \\( x \\sim \\ln t \\), the leading behaviour of the Lambert \\( W \\) function for large argument." },
      ],
      finalAnswer: "\\( x = \\ln t - \\ln x \\), with \\( x_0 = \\ln t \\).",
    },
  },
  {
    id: "am9a-005",
    topicRef: "am9a",
    topicTitle: "Iterative roots 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The cubic \\( x^3 - x + \\varepsilon = 0 \\) has a small root near the origin for small \\( \\varepsilon > 0 \\). Rearrange to a fixed-point map suited to this root and perform one iteration from \\( x_0 = 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "small root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Isolate the linear term.", workingLatex: "x = \\varepsilon + x^3", explanation: "Near the origin \\( x^3 \\ll x \\), so the dominant balance is \\( x \\approx \\varepsilon \\); keep \\( x^3 \\) as the correction." },
        { stepNumber: 2, description: "Seed the iteration.", workingLatex: "x_0 = 0", explanation: "Starting from zero, the first pass picks up the forcing term \\( \\varepsilon \\)." },
        { stepNumber: 3, description: "Iterate once.", workingLatex: "x_1 = \\varepsilon + x_0^3 = \\varepsilon", explanation: "The cube of zero vanishes, giving \\( x_1 = \\varepsilon \\) as the leading approximation." },
      ],
      finalAnswer: "\\( x = \\varepsilon + x^3 \\), with \\( x_1 = \\varepsilon \\).",
    },
  },
  {
    id: "am9a-006",
    topicRef: "am9a",
    topicTitle: "Iterative roots 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The equation \\( x = 1 + \\varepsilon \\sin x \\) with small \\( \\varepsilon \\) has a root near \\( x = 1 \\). Perform one iteration of the fixed-point map starting from \\( x_0 = 1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the map.", workingLatex: "x = g(x) = 1 + \\varepsilon \\sin x", explanation: "The equation is already a contraction near \\( x = 1 \\) because \\( |g'(x)| = |\\varepsilon \\cos x| < 1 \\) for small \\( \\varepsilon \\)." },
        { stepNumber: 2, description: "Seed the iteration.", workingLatex: "x_0 = 1", explanation: "Setting \\( \\varepsilon = 0 \\) gives the unperturbed root \\( x = 1 \\)." },
        { stepNumber: 3, description: "Iterate once.", workingLatex: "x_1 = 1 + \\varepsilon \\sin 1", explanation: "Substituting \\( x_0 = 1 \\) gives the first correction \\( \\varepsilon \\sin 1 \\)." },
      ],
      finalAnswer: "\\( x_1 = 1 + \\varepsilon \\sin 1 \\).",
    },
  },

  // ────────────────────── STANDARD (12) ──────────────────────
  {
    id: "am9a-007",
    topicRef: "am9a",
    topicTitle: "Iterative roots 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the expansion of the positive root of \\( x^2 + \\varepsilon x - 1 = 0 \\) as \\( \\varepsilon \\to 0 \\), using the iteration \\( x = \\sqrt{1 - \\varepsilon x} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "binomial expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed with the leading root.", workingLatex: "x_0 = 1", explanation: "Setting \\( \\varepsilon = 0 \\) gives \\( x^2 = 1 \\), so the positive root is \\( 1 \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\sqrt{1 - \\varepsilon \\cdot 1} = (1 - \\varepsilon)^{1/2}", explanation: "Substitute \\( x_0 = 1 \\) into the map." },
        { stepNumber: 3, description: "Binomial-expand to order \\( \\varepsilon^2 \\).", workingLatex: "x_1 = 1 - \\frac{1}{2}\\varepsilon - \\frac{1}{8}\\varepsilon^2 + O(\\varepsilon^3)", explanation: "Use \\( (1+u)^{1/2} = 1 + \\frac{1}{2}u - \\frac{1}{8}u^2 + \\cdots \\) with \\( u = -\\varepsilon \\)." },
        { stepNumber: 4, description: "Second iteration to fix the \\( \\varepsilon^2 \\) term.", workingLatex: "x_2 = \\sqrt{1 - \\varepsilon x_1} = \\sqrt{1 - \\varepsilon\\left(1 - \\tfrac{1}{2}\\varepsilon\\right) + O(\\varepsilon^3)}", explanation: "The order-\\( \\varepsilon^2 \\) term of the root needs the order-\\( \\varepsilon \\) correction of \\( x \\) fed back in, so one more pass is required." },
        { stepNumber: 5, description: "Expand and collect.", workingLatex: "x_2 = \\left(1 - \\varepsilon + \\tfrac{1}{2}\\varepsilon^2\\right)^{1/2} = 1 - \\frac{1}{2}\\varepsilon + \\frac{1}{8}\\varepsilon^2 + O(\\varepsilon^3)", explanation: "Now the \\( \\varepsilon^2 \\) coefficient is stable: \\( \\frac{1}{2}\\cdot\\frac{1}{2} - \\frac{1}{8} = +\\frac{1}{8} \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\dfrac{1}{2}\\varepsilon + \\dfrac{1}{8}\\varepsilon^2 \\).",
      canonicalAnswer: "1 - eps/2 + eps^2/8",
    },
  },
  {
    id: "am9a-008",
    topicRef: "am9a",
    topicTitle: "Iterative roots 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( x = N + \\ln x \\) has a large root as \\( N \\to +\\infty \\). Iterate the fixed-point map to find the first three terms of the expansion in descending order of magnitude.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = N", explanation: "The dominant balance is \\( x \\sim N \\) because \\( \\ln x = o(x) \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = N + \\ln N", explanation: "Substitute \\( x_0 = N \\) to obtain the leading correction \\( \\ln N \\)." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = N + \\ln\\!\\left(N + \\ln N\\right) = N + \\ln N + \\ln\\!\\left(1 + \\frac{\\ln N}{N}\\right)", explanation: "Factor \\( N \\) out of the logarithm so the small ratio \\( (\\ln N)/N \\) is exposed." },
        { stepNumber: 4, description: "Expand the logarithm.", workingLatex: "\\ln\\!\\left(1 + \\frac{\\ln N}{N}\\right) = \\frac{\\ln N}{N} + O\\!\\left(\\frac{(\\ln N)^2}{N^2}\\right)", explanation: "Use \\( \\ln(1+u) = u - \\frac{u^2}{2} + \\cdots \\) with \\( u = (\\ln N)/N \\)." },
        { stepNumber: 5, description: "Collect the three terms.", workingLatex: "x \\sim N + \\ln N + \\frac{\\ln N}{N}", explanation: "These are the leading three contributions in decreasing magnitude." },
      ],
      finalAnswer: "\\( x \\sim N + \\ln N + \\dfrac{\\ln N}{N} \\).",
      canonicalAnswer: "N + log(N) + log(N)/N",
    },
  },
  {
    id: "am9a-009",
    topicRef: "am9a",
    topicTitle: "Iterative roots 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms in the large-\\( N \\) expansion of the positive root of \\( x^3 + x = N \\), using the iteration \\( x = (N - x)^{1/3} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "cubic", "binomial expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed with the dominant balance.", workingLatex: "x_0 = N^{1/3}", explanation: "For large \\( N \\), \\( x^3 \\approx N \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\left(N - N^{1/3}\\right)^{1/3}", explanation: "Substitute \\( x_0 = N^{1/3} \\) into the map." },
        { stepNumber: 3, description: "Factor out N.", workingLatex: "x_1 = N^{1/3}\\left(1 - N^{-2/3}\\right)^{1/3}", explanation: "Pull \\( N \\) out of the bracket so the small quantity \\( N^{-2/3} \\) is exposed." },
        { stepNumber: 4, description: "Binomial-expand.", workingLatex: "\\left(1 - N^{-2/3}\\right)^{1/3} = 1 - \\frac{1}{3}N^{-2/3} + O\\!\\left(N^{-4/3}\\right)", explanation: "Use \\( (1+u)^{1/3} = 1 + \\frac{1}{3}u + \\cdots \\) with \\( u = -N^{-2/3} \\)." },
        { stepNumber: 5, description: "Collect the two terms.", workingLatex: "x \\sim N^{1/3} - \\frac{1}{3}N^{-1/3}", explanation: "Multiplying through by \\( N^{1/3} \\) gives the leading two terms." },
      ],
      finalAnswer: "\\( x \\sim N^{1/3} - \\dfrac{1}{3}N^{-1/3} \\).",
      canonicalAnswer: "N^(1/3) - (1/3)*N^(-1/3)",
    },
  },
  {
    id: "am9a-010",
    topicRef: "am9a",
    topicTitle: "Iterative roots 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( x\\,e^{x} = t \\) defines the Lambert \\( W \\) function \\( x = W(t) \\). Using the iteration \\( x = \\ln t - \\ln x \\), find the first two terms of \\( W(t) \\) as \\( t \\to +\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "Lambert W", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = \\ln t", explanation: "The dominant balance of \\( x = \\ln t - \\ln x \\) is \\( x \\sim \\ln t \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\ln t - \\ln(\\ln t)", explanation: "Substitute \\( x_0 = \\ln t \\); the correction is the iterated logarithm \\( \\ln\\ln t \\)." },
        { stepNumber: 3, description: "Write in standard notation.", workingLatex: "x \\sim L_1 - L_2, \\qquad L_1 = \\ln t,\\ L_2 = \\ln\\ln t", explanation: "The classical asymptotic series for \\( W(t) \\) is organised in the variables \\( L_1, L_2 \\)." },
        { stepNumber: 4, description: "State the two-term result.", workingLatex: "W(t) \\sim \\ln t - \\ln\\ln t", explanation: "Further iterations generate the next term \\( (\\ln\\ln t)/\\ln t \\), but two terms are requested." },
      ],
      finalAnswer: "\\( W(t) \\sim \\ln t - \\ln\\ln t \\).",
      canonicalAnswer: "log(t) - log(log(t))",
    },
  },
  {
    id: "am9a-011",
    topicRef: "am9a",
    topicTitle: "Iterative roots 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms of the small root of \\( x^3 - x + \\varepsilon = 0 \\) near the origin as \\( \\varepsilon \\to 0 \\), using \\( x = \\varepsilon + x^3 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "small root", "cubic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = \\varepsilon", explanation: "Near the origin \\( x \\approx \\varepsilon \\), since \\( x^3 \\) is negligible at leading order." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\varepsilon + x_0^3 = \\varepsilon + \\varepsilon^3", explanation: "Cube \\( x_0 = \\varepsilon \\) and add the forcing." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = \\varepsilon + (\\varepsilon + \\varepsilon^3)^3 = \\varepsilon + \\varepsilon^3 + 3\\varepsilon^5 + O(\\varepsilon^7)", explanation: "Expand the cube: \\( (\\varepsilon + \\varepsilon^3)^3 = \\varepsilon^3 + 3\\varepsilon^5 + \\cdots \\). The series proceeds in odd powers." },
        { stepNumber: 4, description: "Collect the three terms.", workingLatex: "x \\sim \\varepsilon + \\varepsilon^3 + 3\\varepsilon^5", explanation: "These are the first three non-zero contributions." },
      ],
      finalAnswer: "\\( x \\sim \\varepsilon + \\varepsilon^3 + 3\\varepsilon^5 \\).",
      canonicalAnswer: "eps + eps^3 + 3*eps^5",
    },
  },
  {
    id: "am9a-012",
    topicRef: "am9a",
    topicTitle: "Iterative roots 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( x + 2\\ln x = t \\) has a large root as \\( t \\to +\\infty \\). Use the iteration \\( x = t - 2\\ln x \\) to find the first three terms of the expansion.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = t", explanation: "Since \\( \\ln x = o(x) \\), the leading balance is \\( x \\sim t \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = t - 2\\ln t", explanation: "Substitute \\( x_0 = t \\) to pick up the \\( -2\\ln t \\) correction." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = t - 2\\ln\\!\\left(t - 2\\ln t\\right) = t - 2\\ln t - 2\\ln\\!\\left(1 - \\frac{2\\ln t}{t}\\right)", explanation: "Factor \\( t \\) out of the logarithm to expose the small ratio." },
        { stepNumber: 4, description: "Expand the logarithm.", workingLatex: "-2\\ln\\!\\left(1 - \\frac{2\\ln t}{t}\\right) = \\frac{4\\ln t}{t} + O\\!\\left(\\frac{(\\ln t)^2}{t^2}\\right)", explanation: "Use \\( \\ln(1+u) \\approx u \\) with \\( u = -2(\\ln t)/t \\)." },
        { stepNumber: 5, description: "Collect the three terms.", workingLatex: "x \\sim t - 2\\ln t + \\frac{4\\ln t}{t}", explanation: "Three terms in decreasing order of magnitude." },
      ],
      finalAnswer: "\\( x \\sim t - 2\\ln t + \\dfrac{4\\ln t}{t} \\).",
      canonicalAnswer: "t - 2*log(t) + 4*log(t)/t",
    },
  },
  {
    id: "am9a-013",
    topicRef: "am9a",
    topicTitle: "Iterative roots 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms in the large-\\( N \\) expansion of the root of \\( x\\,\\ln x = N \\), using the iteration \\( x = N / \\ln x \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = \\frac{N}{\\ln N}", explanation: "Since \\( x \\to \\infty \\), \\( \\ln x \\sim \\ln N \\) at leading order, giving \\( x \\sim N/\\ln N \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\frac{N}{\\ln x_0} = \\frac{N}{\\ln N - \\ln\\ln N}", explanation: "Here \\( \\ln x_0 = \\ln N - \\ln\\ln N \\), since \\( x_0 = N/\\ln N \\)." },
        { stepNumber: 3, description: "Factor and expand the denominator.", workingLatex: "x_1 = \\frac{N}{\\ln N}\\left(1 - \\frac{\\ln\\ln N}{\\ln N}\\right)^{-1} = \\frac{N}{\\ln N}\\left(1 + \\frac{\\ln\\ln N}{\\ln N} + \\cdots\\right)", explanation: "Use \\( (1-u)^{-1} = 1 + u + \\cdots \\) with \\( u = (\\ln\\ln N)/\\ln N \\)." },
        { stepNumber: 4, description: "Collect the two terms.", workingLatex: "x \\sim \\frac{N}{\\ln N} + \\frac{N\\,\\ln\\ln N}{(\\ln N)^2}", explanation: "These are the leading two contributions; both are large but the second is down by a factor \\( (\\ln\\ln N)/\\ln N \\)." },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{N}{\\ln N} + \\dfrac{N\\,\\ln\\ln N}{(\\ln N)^2} \\).",
      canonicalAnswer: "N/log(N) + N*log(log(N))/log(N)^2",
    },
  },
  {
    id: "am9a-014",
    topicRef: "am9a",
    topicTitle: "Iterative roots 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the expansion of the root of \\( x = 1 + \\varepsilon \\sin x \\) near \\( x = 1 \\) as \\( \\varepsilon \\to 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric", "Taylor expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = 1", explanation: "At \\( \\varepsilon = 0 \\) the root is \\( x = 1 \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = 1 + \\varepsilon \\sin 1", explanation: "Substitute \\( x_0 = 1 \\) to obtain the \\( O(\\varepsilon) \\) correction." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = 1 + \\varepsilon \\sin\\!\\left(1 + \\varepsilon \\sin 1\\right)", explanation: "Feed the improved value back through the map." },
        { stepNumber: 4, description: "Taylor-expand the sine.", workingLatex: "\\sin\\!\\left(1 + \\varepsilon \\sin 1\\right) = \\sin 1 + \\varepsilon \\sin 1 \\cos 1 + O(\\varepsilon^2)", explanation: "Use \\( \\sin(1+h) = \\sin 1 + h\\cos 1 + \\cdots \\) with \\( h = \\varepsilon \\sin 1 \\)." },
        { stepNumber: 5, description: "Collect to order \\( \\varepsilon^2 \\).", workingLatex: "x \\sim 1 + \\varepsilon \\sin 1 + \\varepsilon^2 \\sin 1 \\cos 1", explanation: "The \\( \\varepsilon^2 \\) term may also be written \\( \\frac{1}{2}\\varepsilon^2 \\sin 2 \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 + \\varepsilon \\sin 1 + \\dfrac{1}{2}\\varepsilon^2 \\sin 2 \\).",
      canonicalAnswer: "1 + eps*sin(1) + eps^2*sin(1)*cos(1)",
    },
  },
  {
    id: "am9a-015",
    topicRef: "am9a",
    topicTitle: "Iterative roots 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( \\tan x = x \\) has a sequence of large positive roots, one just below each \\( (n + \\tfrac{1}{2})\\pi \\). Writing \\( x_n = (n + \\tfrac{1}{2})\\pi - \\delta \\) with small \\( \\delta \\), set up and iterate a fixed-point map to find the first two terms of \\( x_n \\) for large \\( n \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric", "large eigenvalue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use the cotangent shift.", workingLatex: "\\tan\\!\\left[\\left(n+\\tfrac{1}{2}\\right)\\pi - \\delta\\right] = \\cot \\delta = \\frac{1}{\\tan\\delta}", explanation: "Shifting by an odd multiple of \\( \\pi/2 \\) turns \\( \\tan \\) into \\( \\cot \\)." },
        { stepNumber: 2, description: "Rewrite the equation for \\( \\delta \\).", workingLatex: "\\frac{1}{\\tan\\delta} = x \\quad\\Longrightarrow\\quad \\delta = \\arctan\\frac{1}{x}", explanation: "Invert to express the small shift \\( \\delta \\) through the unknown root \\( x \\)." },
        { stepNumber: 3, description: "Form the fixed-point map.", workingLatex: "x = \\left(n+\\tfrac{1}{2}\\right)\\pi - \\arctan\\frac{1}{x}", explanation: "Substitute \\( \\delta \\) back. For large \\( n \\), \\( \\arctan(1/x) \\) is a small correction." },
        { stepNumber: 4, description: "Seed and iterate once.", workingLatex: "x_0 = \\left(n+\\tfrac{1}{2}\\right)\\pi, \\qquad x_1 = \\left(n+\\tfrac{1}{2}\\right)\\pi - \\arctan\\frac{1}{(n+\\tfrac{1}{2})\\pi}", explanation: "Substitute the leading value into the arctangent." },
        { stepNumber: 5, description: "Expand the arctangent.", workingLatex: "x_n \\sim \\left(n+\\tfrac{1}{2}\\right)\\pi - \\frac{1}{\\left(n+\\tfrac{1}{2}\\right)\\pi}", explanation: "Use \\( \\arctan u \\approx u \\) for small \\( u = 1/[(n+\\tfrac12)\\pi] \\)." },
      ],
      finalAnswer: "\\( x_n \\sim \\left(n+\\dfrac{1}{2}\\right)\\pi - \\dfrac{1}{\\left(n+\\frac{1}{2}\\right)\\pi} \\).",
      canonicalAnswer: "(n+1/2)*pi - 1/((n+1/2)*pi)",
    },
  },
  {
    id: "am9a-016",
    topicRef: "am9a",
    topicTitle: "Iterative roots 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The quadratic \\( \\varepsilon x^2 + x - 1 = 0 \\) has a regular root near \\( x = 1 \\) for small \\( \\varepsilon \\). Use the iteration \\( x = 1 - \\varepsilon x^2 \\) to find the first three terms of this root.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "singular perturbation", "regular root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange for the regular root.", workingLatex: "x = 1 - \\varepsilon x^2", explanation: "Isolating the linear term keeps \\( \\varepsilon x^2 \\) as the small correction; this captures the \\( O(1) \\) root." },
        { stepNumber: 2, description: "Seed the iteration.", workingLatex: "x_0 = 1", explanation: "At \\( \\varepsilon = 0 \\), \\( x = 1 \\)." },
        { stepNumber: 3, description: "First iteration.", workingLatex: "x_1 = 1 - \\varepsilon", explanation: "Substitute \\( x_0 = 1 \\): \\( x_1 = 1 - \\varepsilon(1)^2 \\)." },
        { stepNumber: 4, description: "Second iteration.", workingLatex: "x_2 = 1 - \\varepsilon(1 - \\varepsilon)^2 = 1 - \\varepsilon\\left(1 - 2\\varepsilon + \\varepsilon^2\\right)", explanation: "Square \\( x_1 \\) and substitute." },
        { stepNumber: 5, description: "Collect to order \\( \\varepsilon^2 \\).", workingLatex: "x \\sim 1 - \\varepsilon + 2\\varepsilon^2", explanation: "Keep terms up to \\( \\varepsilon^2 \\); the \\( \\varepsilon^3 \\) term is dropped." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\varepsilon + 2\\varepsilon^2 \\).",
      canonicalAnswer: "1 - eps + 2*eps^2",
    },
  },
  {
    id: "am9a-017",
    topicRef: "am9a",
    topicTitle: "Iterative roots 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms in the small-\\( \\varepsilon \\) expansion of the root of \\( x = \\cos(\\varepsilon x) \\) near \\( x = 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = 1", explanation: "At \\( \\varepsilon = 0 \\), \\( \\cos 0 = 1 \\), so \\( x = 1 \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = \\cos(\\varepsilon)", explanation: "Substitute \\( x_0 = 1 \\) into the map." },
        { stepNumber: 3, description: "Expand the cosine.", workingLatex: "x_1 = 1 - \\frac{1}{2}\\varepsilon^2 + O(\\varepsilon^4)", explanation: "Use \\( \\cos u = 1 - \\frac{u^2}{2} + \\cdots \\) with \\( u = \\varepsilon \\). The correction enters at \\( O(\\varepsilon^2) \\)." },
        { stepNumber: 4, description: "Confirm stability.", workingLatex: "x_2 = \\cos(\\varepsilon x_1) = 1 - \\frac{1}{2}\\varepsilon^2 + O(\\varepsilon^4)", explanation: "Because \\( x_1 = 1 + O(\\varepsilon^2) \\), feeding it back changes only the \\( O(\\varepsilon^4) \\) term, so the two-term result is stable." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\dfrac{1}{2}\\varepsilon^2 \\).",
      canonicalAnswer: "1 - eps^2/2",
    },
  },
  {
    id: "am9a-018",
    topicRef: "am9a",
    topicTitle: "Iterative roots 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( x = a + \\dfrac{b}{x} \\) with constants \\( a, b > 0 \\) and large \\( a \\) has a root near \\( x = a \\). Iterate the fixed-point map to find the first three terms in inverse powers of \\( a \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "continued fraction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = a", explanation: "For large \\( a \\), the term \\( b/x \\) is a small correction, so \\( x \\sim a \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = a + \\frac{b}{a}", explanation: "Substitute \\( x_0 = a \\) into the map." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = a + \\frac{b}{a + \\frac{b}{a}} = a + \\frac{b}{a}\\left(1 + \\frac{b}{a^2}\\right)^{-1}", explanation: "Factor \\( a \\) out of the denominator to expose the small quantity \\( b/a^2 \\)." },
        { stepNumber: 4, description: "Expand the denominator.", workingLatex: "x_2 = a + \\frac{b}{a}\\left(1 - \\frac{b}{a^2} + \\cdots\\right) = a + \\frac{b}{a} - \\frac{b^2}{a^3} + \\cdots", explanation: "Use \\( (1+u)^{-1} = 1 - u + \\cdots \\)." },
      ],
      finalAnswer: "\\( x \\sim a + \\dfrac{b}{a} - \\dfrac{b^2}{a^3} \\).",
      canonicalAnswer: "a + b/a - b^2/a^3",
    },
  },

  // ────────────────────── CHALLENGE (12) ──────────────────────
  {
    id: "am9a-019",
    topicRef: "am9a",
    topicTitle: "Iterative roots 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( x + x^{1/2} + 2\\ln x = t \\) as \\( t \\to +\\infty \\). Using a fixed-point iteration, find the first four terms in the asymptotic expansion of the root \\( x(t) \\), in decreasing order of magnitude.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm", "Cambridge Part II"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the fixed-point map.", workingLatex: "x = t - x^{1/2} - 2\\ln x", explanation: "The dominant balance is \\( x \\sim t \\); the half-power and logarithm are successively smaller corrections." },
        { stepNumber: 2, description: "Seed and take the first iteration.", workingLatex: "x_0 = t, \\qquad x_1 = t - t^{1/2} - 2\\ln t", explanation: "Substitute \\( x_0 = t \\). The largest correction is \\( -t^{1/2} \\), then \\( -2\\ln t \\)." },
        { stepNumber: 3, description: "Refine the half-power term.", workingLatex: "x_1^{1/2} = t^{1/2}\\left(1 - t^{-1/2} - 2t^{-1}\\ln t\\right)^{1/2} = t^{1/2} - \\frac{1}{2} + O\\!\\left(t^{-1/2}\\ln t\\right)", explanation: "Expand \\( (1+u)^{1/2} \\approx 1 + \\frac{u}{2} \\) with \\( u = -t^{-1/2} - 2t^{-1}\\ln t \\); the \\( -t^{-1/2} \\) inside contributes the constant \\( -\\frac{1}{2} \\)." },
        { stepNumber: 4, description: "Refine the logarithm term.", workingLatex: "2\\ln x_1 = 2\\ln t + 2\\ln\\!\\left(1 - t^{-1/2} - \\cdots\\right) = 2\\ln t - 2t^{-1/2} + O\\!\\left(t^{-1}\\ln t\\right)", explanation: "Use \\( \\ln(1+u) \\approx u \\); the leading correction to \\( 2\\ln x \\) is \\( -2t^{-1/2} \\), which is smaller than the constant \\( \\frac{1}{2} \\)." },
        { stepNumber: 5, description: "Assemble the second iterate.", workingLatex: "x_2 = t - \\left(t^{1/2} - \\tfrac{1}{2}\\right) - 2\\ln t + O\\!\\left(t^{-1/2}\\ln t\\right)", explanation: "Substitute the refined half-power and logarithm into \\( x = t - x^{1/2} - 2\\ln x \\). The \\( +\\frac{1}{2} \\) is the new term that the second iteration reveals." },
        { stepNumber: 6, description: "Collect the four leading terms.", workingLatex: "x \\sim t - t^{1/2} - 2\\ln t + \\frac{1}{2}", explanation: "In decreasing magnitude: \\( t,\\ -t^{1/2},\\ -2\\ln t,\\ +\\frac{1}{2} \\)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - 2\\ln t + \\dfrac{1}{2} \\).",
      canonicalAnswer: "t - t^(1/2) - 2*log(t) + 1/2",
    },
  },
  {
    id: "am9a-020",
    topicRef: "am9a",
    topicTitle: "Iterative roots 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( \\varepsilon x^2 + x - 1 = 0 \\) has two roots for small \\( \\varepsilon > 0 \\). Find the first two terms of the large (singular) root, which diverges as \\( \\varepsilon \\to 0 \\), by constructing an appropriate fixed-point iteration.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "singular perturbation", "dominant balance"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the singular dominant balance.", workingLatex: "\\varepsilon x^2 + x - 1 = 0,\\quad \\varepsilon x^2 \\sim -x \\ \\Rightarrow\\ x \\sim -\\frac{1}{\\varepsilon}", explanation: "The lost root appears when the highest-order term \\( \\varepsilon x^2 \\) balances \\( x \\). This requires \\( x = O(1/\\varepsilon) \\), large and negative." },
        { stepNumber: 2, description: "Divide through by \\( \\varepsilon x \\).", workingLatex: "\\frac{\\varepsilon x^2 + x - 1}{\\varepsilon x} = x + \\frac{1}{\\varepsilon} - \\frac{1}{\\varepsilon x} = 0", explanation: "Dividing by \\( \\varepsilon x \\) (non-zero for the singular root) separates the large \\( 1/\\varepsilon \\) from the \\( O(1) \\) piece \\( 1/(\\varepsilon x) \\) when \\( x = O(1/\\varepsilon) \\)." },
        { stepNumber: 3, description: "Solve for the leading x to form the map.", workingLatex: "x = -\\frac{1}{\\varepsilon} + \\frac{1}{\\varepsilon x}", explanation: "Move the first-power \\( x \\) to one side; the remaining \\( 1/(\\varepsilon x) \\) term is the small correction for the singular root." },
        { stepNumber: 4, description: "Seed and iterate.", workingLatex: "x_0 = -\\frac{1}{\\varepsilon}, \\qquad x_1 = -\\frac{1}{\\varepsilon} + \\frac{1}{\\varepsilon(-1/\\varepsilon)} = -\\frac{1}{\\varepsilon} - 1", explanation: "Substitute \\( x_0 = -1/\\varepsilon \\): the correction \\( 1/(\\varepsilon x_0) = -1 \\)." },
        { stepNumber: 5, description: "State the two-term expansion.", workingLatex: "x \\sim -\\frac{1}{\\varepsilon} - 1", explanation: "The next iteration confirms the constant \\( -1 \\) is stable and produces an \\( O(\\varepsilon) \\) correction." },
      ],
      finalAnswer: "\\( x \\sim -\\dfrac{1}{\\varepsilon} - 1 \\).",
      canonicalAnswer: "-1/eps - 1",
    },
  },
  {
    id: "am9a-021",
    topicRef: "am9a",
    topicTitle: "Iterative roots 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms of the Lambert-\\( W \\) root of \\( x\\,e^{x} = t \\) as \\( t \\to +\\infty \\), using the iteration \\( x = \\ln t - \\ln x \\). Express the answer in terms of \\( L_1 = \\ln t \\) and \\( L_2 = \\ln\\ln t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "Lambert W", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = L_1 = \\ln t", explanation: "The dominant balance gives \\( x \\sim \\ln t \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = L_1 - \\ln L_1 = L_1 - L_2", explanation: "Since \\( \\ln x_0 = \\ln\\ln t = L_2 \\)." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = L_1 - \\ln\\!\\left(L_1 - L_2\\right) = L_1 - \\ln L_1 - \\ln\\!\\left(1 - \\frac{L_2}{L_1}\\right)", explanation: "Factor \\( L_1 \\) out of the logarithm to expose the small ratio \\( L_2/L_1 \\)." },
        { stepNumber: 4, description: "Expand the logarithm.", workingLatex: "-\\ln\\!\\left(1 - \\frac{L_2}{L_1}\\right) = \\frac{L_2}{L_1} + O\\!\\left(\\frac{L_2^2}{L_1^2}\\right)", explanation: "Use \\( \\ln(1+u) \\approx u \\) with \\( u = -L_2/L_1 \\)." },
        { stepNumber: 5, description: "Collect the three terms.", workingLatex: "x \\sim L_1 - L_2 + \\frac{L_2}{L_1}", explanation: "This is the start of the standard asymptotic series for \\( W(t) \\)." },
      ],
      finalAnswer: "\\( W(t) \\sim L_1 - L_2 + \\dfrac{L_2}{L_1} \\), where \\( L_1 = \\ln t,\\ L_2 = \\ln\\ln t \\).",
      canonicalAnswer: "L1 - L2 + L2/L1",
    },
  },
  {
    id: "am9a-022",
    topicRef: "am9a",
    topicTitle: "Iterative roots 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( x\\,e^{-x} = \\varepsilon \\) has a large root \\( x \\to \\infty \\) as \\( \\varepsilon \\to 0^{+} \\). Find the first three terms of this root in terms of \\( M_1 = \\ln(1/\\varepsilon) \\) and \\( M_2 = \\ln\\ln(1/\\varepsilon) \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm", "Lambert W"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x - x = \\ln\\varepsilon = -M_1", explanation: "With \\( M_1 = \\ln(1/\\varepsilon) = -\\ln\\varepsilon \\)." },
        { stepNumber: 2, description: "Form the fixed-point map.", workingLatex: "x = M_1 + \\ln x", explanation: "Rearranging \\( x = -\\ln\\varepsilon + \\ln x = M_1 + \\ln x \\). The \\( \\ln x \\) term is the small correction." },
        { stepNumber: 3, description: "Seed and iterate once.", workingLatex: "x_0 = M_1, \\qquad x_1 = M_1 + \\ln M_1 = M_1 + M_2", explanation: "Since \\( \\ln M_1 = \\ln\\ln(1/\\varepsilon) = M_2 \\)." },
        { stepNumber: 4, description: "Second iteration.", workingLatex: "x_2 = M_1 + \\ln\\!\\left(M_1 + M_2\\right) = M_1 + \\ln M_1 + \\ln\\!\\left(1 + \\frac{M_2}{M_1}\\right)", explanation: "Factor \\( M_1 \\) out of the logarithm." },
        { stepNumber: 5, description: "Expand the logarithm.", workingLatex: "\\ln\\!\\left(1 + \\frac{M_2}{M_1}\\right) = \\frac{M_2}{M_1} + O\\!\\left(\\frac{M_2^2}{M_1^2}\\right)", explanation: "Use \\( \\ln(1+u) \\approx u \\)." },
        { stepNumber: 6, description: "Collect the three terms.", workingLatex: "x \\sim M_1 + M_2 + \\frac{M_2}{M_1}", explanation: "Note the sign difference from \\( W(t) \\): here the map has \\( +\\ln x \\), so all three terms add." },
      ],
      finalAnswer: "\\( x \\sim M_1 + M_2 + \\dfrac{M_2}{M_1} \\), with \\( M_1 = \\ln(1/\\varepsilon),\\ M_2 = \\ln\\ln(1/\\varepsilon) \\).",
      canonicalAnswer: "M1 + M2 + M2/M1",
    },
  },
  {
    id: "am9a-023",
    topicRef: "am9a",
    topicTitle: "Iterative roots 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms in the large-\\( N \\) expansion of the positive root of \\( x^3 + x = N \\), continuing the iteration \\( x = (N - x)^{1/3} \\) to one more order than the leading two terms.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "cubic", "binomial expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the two-term result.", workingLatex: "x \\approx N^{1/3} - \\frac{1}{3}N^{-1/3}", explanation: "From the first iteration; we now feed this back to get the next term." },
        { stepNumber: 2, description: "Form the second iterate.", workingLatex: "x_2 = \\left(N - N^{1/3} + \\tfrac{1}{3}N^{-1/3}\\right)^{1/3}", explanation: "Substitute the two-term approximation into \\( x = (N-x)^{1/3} \\)." },
        { stepNumber: 3, description: "Factor out N.", workingLatex: "x_2 = N^{1/3}\\left(1 - N^{-2/3} + \\tfrac{1}{3}N^{-4/3}\\right)^{1/3}", explanation: "Pull \\( N \\) out; the bracket is \\( 1 + u \\) with \\( u = -N^{-2/3} + \\frac{1}{3}N^{-4/3} \\)." },
        { stepNumber: 4, description: "Binomial-expand to second order.", workingLatex: "(1+u)^{1/3} = 1 + \\frac{1}{3}u - \\frac{1}{9}u^2 + \\cdots", explanation: "We need \\( u \\) and \\( u^2 \\); note \\( u^2 = N^{-4/3} + O(N^{-2}) \\)." },
        { stepNumber: 5, description: "Collect terms order by order.", workingLatex: "(1+u)^{1/3} = 1 - \\frac{1}{3}N^{-2/3} + \\left(\\frac{1}{9} - \\frac{1}{9}\\right)N^{-4/3} + \\cdots = 1 - \\frac{1}{3}N^{-2/3} + 0\\cdot N^{-4/3}", explanation: "The \\( N^{-4/3} \\) contributions cancel: \\( \\frac{1}{3}\\cdot\\frac{1}{3} \\) from \\( \\frac{1}{3}u \\) minus \\( \\frac{1}{9} \\) from \\( -\\frac{1}{9}u^2 \\)." },
        { stepNumber: 6, description: "Multiply back by \\( N^{1/3} \\).", workingLatex: "x \\sim N^{1/3} - \\frac{1}{3}N^{-1/3} + 0\\cdot N^{-1} = N^{1/3} - \\frac{1}{3}N^{-1/3}", explanation: "The \\( N^{-1} \\) coefficient vanishes; the next non-zero correction is at \\( O(N^{-5/3}) \\)." },
      ],
      finalAnswer: "\\( x \\sim N^{1/3} - \\dfrac{1}{3}N^{-1/3} + 0\\cdot N^{-1} \\) (the \\( N^{-1} \\) term vanishes).",
      canonicalAnswer: "N^(1/3) - (1/3)*N^(-1/3)",
    },
  },
  {
    id: "am9a-024",
    topicRef: "am9a",
    topicTitle: "Iterative roots 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( \\cot x = x \\) has large positive roots near \\( x = n\\pi \\). Writing \\( x_n = n\\pi + \\delta \\) with small \\( \\delta \\), set up a fixed-point iteration and find the first two terms of \\( x_n \\) for large \\( n \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Shift by \\( n\\pi \\).", workingLatex: "\\cot(n\\pi + \\delta) = \\cot\\delta = x", explanation: "Cotangent has period \\( \\pi \\), so the shift by \\( n\\pi \\) leaves \\( \\cot\\delta \\)." },
        { stepNumber: 2, description: "Invert for the small shift.", workingLatex: "\\cot\\delta = x \\ \\Rightarrow\\ \\delta = \\operatorname{arccot} x = \\arctan\\frac{1}{x}", explanation: "For large \\( x \\), \\( \\delta \\) is small and positive." },
        { stepNumber: 3, description: "Form the map.", workingLatex: "x = n\\pi + \\arctan\\frac{1}{x}", explanation: "Substitute \\( \\delta \\) back; the arctangent is the small correction." },
        { stepNumber: 4, description: "Seed and iterate once.", workingLatex: "x_0 = n\\pi, \\qquad x_1 = n\\pi + \\arctan\\frac{1}{n\\pi}", explanation: "Substitute the leading value into the arctangent." },
        { stepNumber: 5, description: "Expand the arctangent.", workingLatex: "x_n \\sim n\\pi + \\frac{1}{n\\pi}", explanation: "Use \\( \\arctan u \\approx u \\) for small \\( u = 1/(n\\pi) \\)." },
      ],
      finalAnswer: "\\( x_n \\sim n\\pi + \\dfrac{1}{n\\pi} \\).",
      canonicalAnswer: "n*pi + 1/(n*pi)",
    },
  },
  {
    id: "am9a-025",
    topicRef: "am9a",
    topicTitle: "Iterative roots 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms of the large root of \\( \\tan x = x \\) near \\( (n+\\tfrac{1}{2})\\pi \\), continuing the iteration \\( x = (n+\\tfrac{1}{2})\\pi - \\arctan(1/x) \\) past the leading correction. Let \\( c = (n+\\tfrac{1}{2})\\pi \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric", "large eigenvalue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the two-term result.", workingLatex: "x_1 = c - \\frac{1}{c}", explanation: "From the first iteration, with \\( c = (n+\\tfrac{1}{2})\\pi \\)." },
        { stepNumber: 2, description: "Second iterate set-up.", workingLatex: "x_2 = c - \\arctan\\frac{1}{x_1} = c - \\arctan\\frac{1}{c - 1/c}", explanation: "Feed \\( x_1 \\) back into the map." },
        { stepNumber: 3, description: "Expand the reciprocal.", workingLatex: "\\frac{1}{c - 1/c} = \\frac{1}{c}\\left(1 - \\frac{1}{c^2}\\right)^{-1} = \\frac{1}{c} + \\frac{1}{c^3} + O(c^{-5})", explanation: "Use \\( (1-u)^{-1} = 1 + u + \\cdots \\) with \\( u = 1/c^2 \\)." },
        { stepNumber: 4, description: "Expand the arctangent.", workingLatex: "\\arctan\\!\\left(\\frac{1}{c} + \\frac{1}{c^3}\\right) = \\left(\\frac{1}{c} + \\frac{1}{c^3}\\right) - \\frac{1}{3}\\frac{1}{c^3} + O(c^{-5})", explanation: "Use \\( \\arctan u = u - \\frac{u^3}{3} + \\cdots \\); the \\( u^3 \\) term contributes \\( -\\frac{1}{3c^3} \\)." },
        { stepNumber: 5, description: "Combine the \\( c^{-3} \\) terms.", workingLatex: "\\arctan\\frac{1}{x_1} = \\frac{1}{c} + \\left(1 - \\frac{1}{3}\\right)\\frac{1}{c^3} = \\frac{1}{c} + \\frac{2}{3c^3}", explanation: "Add \\( 1/c^3 \\) (from the reciprocal expansion) and \\( -1/(3c^3) \\) (from the arctangent)." },
        { stepNumber: 6, description: "Collect the three terms.", workingLatex: "x \\sim c - \\frac{1}{c} - \\frac{2}{3c^3}, \\qquad c = \\left(n+\\tfrac{1}{2}\\right)\\pi", explanation: "Three terms in decreasing magnitude." },
      ],
      finalAnswer: "\\( x \\sim c - \\dfrac{1}{c} - \\dfrac{2}{3c^3} \\), with \\( c = \\left(n+\\frac{1}{2}\\right)\\pi \\).",
      canonicalAnswer: "c - 1/c - 2/(3*c^3)",
    },
  },
  {
    id: "am9a-026",
    topicRef: "am9a",
    topicTitle: "Iterative roots 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms in the small-\\( \\varepsilon \\) expansion of the positive root of \\( x^2 + \\varepsilon x - 1 = 0 \\), and verify the constant term by comparison with the exact quadratic formula.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "verification", "binomial expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Iterate to three terms.", workingLatex: "x \\sim 1 - \\frac{1}{2}\\varepsilon + \\frac{1}{8}\\varepsilon^2", explanation: "From the fixed-point map \\( x = \\sqrt{1-\\varepsilon x} \\), as in the Standard version." },
        { stepNumber: 2, description: "Write the exact root.", workingLatex: "x = \\frac{-\\varepsilon + \\sqrt{\\varepsilon^2 + 4}}{2}", explanation: "Quadratic formula, taking the \\( + \\) sign for the positive root." },
        { stepNumber: 3, description: "Factor the surd.", workingLatex: "\\sqrt{\\varepsilon^2 + 4} = 2\\sqrt{1 + \\tfrac{1}{4}\\varepsilon^2} = 2\\left(1 + \\frac{1}{8}\\varepsilon^2 - \\frac{1}{128}\\varepsilon^4 + \\cdots\\right)", explanation: "Binomial expansion of \\( (1+u)^{1/2} \\) with \\( u = \\varepsilon^2/4 \\)." },
        { stepNumber: 4, description: "Substitute back.", workingLatex: "x = \\frac{-\\varepsilon + 2 + \\frac{1}{4}\\varepsilon^2 + \\cdots}{2} = 1 - \\frac{1}{2}\\varepsilon + \\frac{1}{8}\\varepsilon^2 + \\cdots", explanation: "Divide through by \\( 2 \\). The exact expansion matches the iterated result term by term." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "x \\sim 1 - \\frac{1}{2}\\varepsilon + \\frac{1}{8}\\varepsilon^2", explanation: "The iteration reproduces the genuine Taylor coefficients, confirming consistency." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\dfrac{1}{2}\\varepsilon + \\dfrac{1}{8}\\varepsilon^2 \\), confirmed by the exact formula.",
      canonicalAnswer: "1 - eps/2 + eps^2/8",
    },
  },
  {
    id: "am9a-027",
    topicRef: "am9a",
    topicTitle: "Iterative roots 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( x = t - e^{-x} \\) has a root that grows with \\( t \\) as \\( t \\to +\\infty \\). Find the first three terms of the asymptotic expansion of the root, where the correction is exponentially small.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "exponentially small", "beyond all orders"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed the iteration.", workingLatex: "x_0 = t", explanation: "Since \\( e^{-x} \\to 0 \\) as \\( x \\to \\infty \\), the leading balance is \\( x \\sim t \\)." },
        { stepNumber: 2, description: "First iteration.", workingLatex: "x_1 = t - e^{-t}", explanation: "Substitute \\( x_0 = t \\). The correction \\( e^{-t} \\) is exponentially small — smaller than any power of \\( 1/t \\)." },
        { stepNumber: 3, description: "Second iteration.", workingLatex: "x_2 = t - e^{-x_1} = t - e^{-t + e^{-t}}", explanation: "Feed \\( x_1 \\) back; the exponent acquires the small term \\( e^{-t} \\)." },
        { stepNumber: 4, description: "Expand the inner exponential.", workingLatex: "e^{-t + e^{-t}} = e^{-t}\\left(1 + e^{-t} + \\cdots\\right) = e^{-t} + e^{-2t} + \\cdots", explanation: "Use \\( e^{u} = 1 + u + \\cdots \\) with \\( u = e^{-t} \\)." },
        { stepNumber: 5, description: "Collect the three terms.", workingLatex: "x \\sim t - e^{-t} - e^{-2t}", explanation: "The series is in powers of the exponentially small quantity \\( e^{-t} \\); it lies beyond all orders of any power series in \\( 1/t \\)." },
      ],
      finalAnswer: "\\( x \\sim t - e^{-t} - e^{-2t} \\).",
      canonicalAnswer: "t - exp(-t) - exp(-2*t)",
    },
  },
  {
    id: "am9a-028",
    topicRef: "am9a",
    topicTitle: "Iterative roots 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms in the expansion of the root of \\( \\tan x = \\dfrac{1}{x} \\) near \\( x = n\\pi \\) for large \\( n \\). Write \\( x_n = n\\pi + \\delta \\) with small \\( \\delta \\), and let \\( c = n\\pi \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "trigonometric"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Shift by \\( n\\pi \\).", workingLatex: "\\tan(n\\pi + \\delta) = \\tan\\delta = \\frac{1}{x}", explanation: "Tangent has period \\( \\pi \\), so the equation becomes \\( \\tan\\delta = 1/x \\)." },
        { stepNumber: 2, description: "Form the map for \\( \\delta \\).", workingLatex: "\\delta = \\arctan\\frac{1}{x} \\ \\Rightarrow\\ x = c + \\arctan\\frac{1}{x}, \\quad c = n\\pi", explanation: "For large \\( n \\) the root is just above \\( n\\pi \\)." },
        { stepNumber: 3, description: "Seed and iterate.", workingLatex: "x_0 = c, \\qquad x_1 = c + \\arctan\\frac{1}{c}", explanation: "Substitute the leading value." },
        { stepNumber: 4, description: "Second iterate with reciprocal expansion.", workingLatex: "x_2 = c + \\arctan\\frac{1}{c + 1/c}, \\qquad \\frac{1}{c + 1/c} = \\frac{1}{c} - \\frac{1}{c^3} + O(c^{-5})", explanation: "Expand \\( (c + 1/c)^{-1} = c^{-1}(1 + c^{-2})^{-1} \\)." },
        { stepNumber: 5, description: "Expand the arctangent.", workingLatex: "\\arctan\\!\\left(\\frac{1}{c} - \\frac{1}{c^3}\\right) = \\frac{1}{c} - \\frac{1}{c^3} - \\frac{1}{3c^3} + O(c^{-5}) = \\frac{1}{c} - \\frac{4}{3c^3}", explanation: "Combine the reciprocal correction \\( -1/c^3 \\) with the arctangent cubic term \\( -1/(3c^3) \\)." },
        { stepNumber: 6, description: "Collect the three terms.", workingLatex: "x \\sim c + \\frac{1}{c} - \\frac{4}{3c^3}, \\qquad c = n\\pi", explanation: "Three terms in decreasing magnitude." },
      ],
      finalAnswer: "\\( x \\sim n\\pi + \\dfrac{1}{n\\pi} - \\dfrac{4}{3(n\\pi)^3} \\).",
      canonicalAnswer: "c + 1/c - 4/(3*c^3)",
    },
  },
  // REVIEW: eps^3 coefficient (-5) numerically confirmed with mpmath findroot — 4-term relative error shrinks 7.98e-5 (eps=0.05) -> 2.16e-6 (eps=0.02), i.e. at the eps^4 rate, confirming the -5*eps^3 term.
  {
    id: "am9a-029",
    topicRef: "am9a",
    topicTitle: "Iterative roots 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first four terms in the small-\\( \\varepsilon \\) expansion of the regular root of \\( \\varepsilon x^2 + x - 1 = 0 \\) near \\( x = 1 \\), using \\( x = 1 - \\varepsilon x^2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "regular root", "singular perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Seed and first iteration.", workingLatex: "x_0 = 1, \\qquad x_1 = 1 - \\varepsilon", explanation: "Substitute \\( x_0 = 1 \\) into \\( x = 1 - \\varepsilon x^2 \\)." },
        { stepNumber: 2, description: "Second iteration.", workingLatex: "x_2 = 1 - \\varepsilon(1-\\varepsilon)^2 = 1 - \\varepsilon + 2\\varepsilon^2 - \\varepsilon^3", explanation: "Expand \\( (1-\\varepsilon)^2 = 1 - 2\\varepsilon + \\varepsilon^2 \\) and multiply by \\( \\varepsilon \\)." },
        { stepNumber: 3, description: "Third iteration.", workingLatex: "x_3 = 1 - \\varepsilon\\left(1 - \\varepsilon + 2\\varepsilon^2\\right)^2", explanation: "Use the order-\\( \\varepsilon^2 \\) part of \\( x_2 \\) inside the square; terms beyond \\( \\varepsilon^2 \\) in \\( x_2 \\) only affect \\( O(\\varepsilon^4) \\)." },
        { stepNumber: 4, description: "Square and keep to \\( \\varepsilon^2 \\).", workingLatex: "\\left(1 - \\varepsilon + 2\\varepsilon^2\\right)^2 = 1 - 2\\varepsilon + 5\\varepsilon^2 + O(\\varepsilon^3)", explanation: "Cross terms: \\( -2\\varepsilon \\) from \\( 2\\cdot1\\cdot(-\\varepsilon) \\); \\( 5\\varepsilon^2 = \\varepsilon^2 + 4\\varepsilon^2 \\) from \\( (-\\varepsilon)^2 + 2\\cdot1\\cdot2\\varepsilon^2 \\)." },
        { stepNumber: 5, description: "Multiply by \\( -\\varepsilon \\) and collect.", workingLatex: "x_3 = 1 - \\varepsilon + 2\\varepsilon^2 - 5\\varepsilon^3 + O(\\varepsilon^4)", explanation: "The four-term expansion of the regular root." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\varepsilon + 2\\varepsilon^2 - 5\\varepsilon^3 \\).",
      canonicalAnswer: "1 - eps + 2*eps^2 - 5*eps^3",
    },
  },
  {
    id: "am9a-030",
    topicRef: "am9a",
    topicTitle: "Iterative roots 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( x = N + \\ln x \\) has a large root as \\( N \\to +\\infty \\). Find the first four terms of its expansion, keeping all contributions through order \\( (\\ln N)/N \\) and \\( (\\ln N)^2 / N^2 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["iterative roots", "fixed point", "logarithm", "higher order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the three-term result.", workingLatex: "x \\approx N + \\ln N + \\frac{\\ln N}{N}", explanation: "From two iterations; we push to one more order." },
        { stepNumber: 2, description: "Set up the next iterate.", workingLatex: "x = N + \\ln\\!\\left(N + \\ln N + \\frac{\\ln N}{N}\\right)", explanation: "Feed the three-term value into \\( \\ln x \\)." },
        { stepNumber: 3, description: "Factor N out.", workingLatex: "x = N + \\ln N + \\ln\\!\\left(1 + \\frac{\\ln N}{N} + \\frac{\\ln N}{N^2}\\right)", explanation: "Let \\( u = \\dfrac{\\ln N}{N} + \\dfrac{\\ln N}{N^2} \\); the last term is negligible at this order." },
        { stepNumber: 4, description: "Expand the logarithm to second order.", workingLatex: "\\ln(1+u) = u - \\frac{u^2}{2} + \\cdots = \\frac{\\ln N}{N} - \\frac{1}{2}\\frac{(\\ln N)^2}{N^2} + \\cdots", explanation: "Here \\( u^2 = (\\ln N)^2/N^2 + O(N^{-3}\\ln^2 N) \\)." },
        { stepNumber: 5, description: "Collect the four terms.", workingLatex: "x \\sim N + \\ln N + \\frac{\\ln N}{N} - \\frac{(\\ln N)^2}{2N^2}", explanation: "Four terms ordered by magnitude." },
      ],
      finalAnswer: "\\( x \\sim N + \\ln N + \\dfrac{\\ln N}{N} - \\dfrac{(\\ln N)^2}{2N^2} \\).",
      canonicalAnswer: "N + log(N) + log(N)/N - log(N)^2/(2*N^2)",
    },
  },
];
