import { Question } from "@/lib/types";

/**
 * Asymptotic Methods — am9b: Logarithmic & mixed-power balances
 * Topic group: Asymptotics of Algebraic & Transcendental Equations
 * Ref: am9b
 *
 * 30 fully-worked, verified questions on solving transcendental equations of
 * the form  x + c·x^{1/2} + b·ln x = t + a·ln t  (and relatives) by dominant
 * balance followed by logarithmic / algebraic corrections, as t → ∞.
 *
 * Seeded from Cambridge Part II Asymptotic Methods Example Sheet 3, Q2:
 *   x + x^{1/2} + 2 ln x = t + ln t,
 * varied in constants, powers and framing.
 *
 * MASTER RESULT (numerically verified, mpmath dps=40, t up to 1e14):
 *   For  x + c·x^{1/2} + b·ln x = t + a·ln t,
 *     x ~ t + (a - b)·ln t - c·t^{1/2} + c^2/2 + O((ln t)/t^{1/2}).
 *   Seed a=1,b=2,c=1:  x ~ t - t^{1/2} - ln t + 1/2.
 * Related verified balances:
 *   x + ln x = t:        x ~ t - ln t + (ln t)/t.
 *   x - ln x = t:        x ~ t + ln t + (ln t)/t.
 *   x + 2 ln x = t:      x ~ t - 2 ln t + 4(ln t)/t.
 *   x + x^{1/2} = t:     exact x = ((sqrt(1+4t)-1)/2)^2 ~ t - t^{1/2} + 1/2.
 *   x^2 + ln x = t:      x ~ t^{1/2} - (ln t)/(4 t^{1/2}).
 *   x + x^{1/3} + ln x = t: x ~ t - t^{1/3} - ln t + (1/3) t^{-1/3}.
 *   x e^x = t:           x = W(t) ~ ln t - ln ln t + (ln ln t)/(ln t).
 *   x ln x = t:          x ~ (t/ln t)(1 + (ln ln t)/(ln t) + ...).
 */
export const questions: Question[] = [
  // ─────────────────────────── FOUNDATION (6) ───────────────────────────
  {
    id: "am9b-001",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + \\ln x = t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "transcendental equation", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant balance.", workingLatex: "x + \\ln x = t, \\qquad t \\to \\infty.", explanation: "As \\( t \\to \\infty \\) the solution must grow without bound, so compare the sizes of the two left-hand terms for large \\( x \\)." },
        { stepNumber: 2, description: "Compare term magnitudes.", workingLatex: "\\frac{\\ln x}{x} \\to 0 \\quad \\text{as } x \\to \\infty.", explanation: "The logarithm is negligible against the algebraic term, so \\( x \\) alone must balance \\( t \\)." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x \\sim t.", explanation: "Dropping the subdominant \\( \\ln x \\) leaves \\( x \\approx t \\); this is the leading-order balance." },
      ],
      finalAnswer: "\\( x \\sim t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t",
    },
  },
  {
    id: "am9b-002",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/2} = t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "mixed powers", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the equation.", workingLatex: "x + x^{1/2} = t, \\qquad t \\to \\infty.", explanation: "Both left-hand terms grow with \\( x \\); compare their orders." },
        { stepNumber: 2, description: "Compare the two powers.", workingLatex: "\\frac{x^{1/2}}{x} = x^{-1/2} \\to 0.", explanation: "The half-power term is small compared with the linear term, so the linear term dominates." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x \\sim t.", explanation: "Balancing the dominant term \\( x \\) against \\( t \\) gives \\( x \\approx t \\) at leading order." },
      ],
      finalAnswer: "\\( x \\sim t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t",
    },
  },
  {
    id: "am9b-003",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The solution of \\( x + \\ln x = t \\) satisfies \\( x \\sim t \\) as \\( t \\to \\infty \\). Find the next term in the expansion of \\( x(t) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["logarithmic correction", "iteration", "transcendental equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange for iteration.", workingLatex: "x = t - \\ln x.", explanation: "Isolate the dominant term so the small correction sits on the right, ready to iterate with the leading guess \\( x \\approx t \\)." },
        { stepNumber: 2, description: "Substitute the leading term.", workingLatex: "x = t - \\ln\\!\\big(t + O(\\ln t)\\big).", explanation: "Insert \\( x \\sim t \\) into the logarithm on the right; the correction inside the log only affects still-smaller terms." },
        { stepNumber: 3, description: "Expand the logarithm.", workingLatex: "x \\sim t - \\ln t.", explanation: "Since \\( \\ln(t + O(\\ln t)) = \\ln t + O\\!\\big(\\tfrac{\\ln t}{t}\\big) \\), the next term is \\( -\\ln t \\)." },
      ],
      finalAnswer: "\\( x \\sim t - \\ln t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - log(t)",
    },
  },
  {
    id: "am9b-004",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The solution of \\( x + x^{1/2} = t \\) satisfies \\( x \\sim t \\). Find the next term in the expansion of \\( x(t) \\) as \\( t \\to \\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["mixed powers", "algebraic correction", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange for iteration.", workingLatex: "x = t - x^{1/2}.", explanation: "Move the subdominant half-power term to the right so it can be evaluated at the leading approximation." },
        { stepNumber: 2, description: "Substitute the leading term.", workingLatex: "x \\sim t - t^{1/2}.", explanation: "Insert \\( x \\sim t \\) into \\( x^{1/2} \\); replacing \\( x \\) by \\( t \\) there changes only terms of order \\( 1 \\) and smaller." },
        { stepNumber: 3, description: "State the two-term expansion.", workingLatex: "x \\sim t - t^{1/2}.", explanation: "The half-power correction is the next term after the leading \\( t \\)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t)",
    },
  },
  {
    id: "am9b-005",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x^2 + \\ln x = t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "mixed powers", "leading order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the equation.", workingLatex: "x^2 + \\ln x = t, \\qquad t \\to \\infty.", explanation: "Compare the algebraic and logarithmic terms as \\( x \\to \\infty \\)." },
        { stepNumber: 2, description: "Compare term magnitudes.", workingLatex: "\\frac{\\ln x}{x^2} \\to 0.", explanation: "The logarithm is negligible against \\( x^2 \\), so the quadratic term must balance \\( t \\)." },
        { stepNumber: 3, description: "Read off the leading term.", workingLatex: "x^2 \\sim t \\;\\Rightarrow\\; x \\sim t^{1/2}.", explanation: "Taking the positive root (the relevant large-\\( x \\) branch) gives the leading behaviour." },
      ],
      finalAnswer: "\\( x \\sim t^{1/2} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "sqrt(t)",
    },
  },
  {
    id: "am9b-006",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The equation \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\) has a solution with \\( x \\to \\infty \\) as \\( t \\to \\infty \\). State its leading-order behaviour.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "mixed powers", "seed equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the largest terms on each side.", workingLatex: "x + x^{1/2} + 2\\ln x = t + \\ln t.", explanation: "On the left the dominant term is \\( x \\); on the right it is \\( t \\). The half-power and logarithmic terms are subdominant on each side." },
        { stepNumber: 2, description: "Balance the dominant terms.", workingLatex: "x \\sim t.", explanation: "Equating the two largest terms gives the leading-order balance \\( x \\approx t \\); all other terms are lower order." },
      ],
      finalAnswer: "\\( x \\sim t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t",
    },
  },

  // ─────────────────────────── STANDARD (12) ───────────────────────────
  {
    id: "am9b-007",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the asymptotic expansion, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + \\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithmic correction", "iteration", "transcendental equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the iteration.", workingLatex: "x = t - \\ln x.", explanation: "Isolating \\( x \\) puts the small term \\( \\ln x \\) on the right for successive substitution." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x_0 = t.", explanation: "Dropping \\( \\ln x \\) entirely gives the leading balance." },
        { stepNumber: 3, description: "First correction.", workingLatex: "x_1 = t - \\ln t.", explanation: "Substitute \\( x_0 = t \\) into the logarithm." },
        { stepNumber: 4, description: "Second correction: expand the log.", workingLatex: "\\ln x_1 = \\ln\\!\\Big(t\\big(1 - \\tfrac{\\ln t}{t}\\big)\\Big) = \\ln t + \\ln\\!\\Big(1 - \\tfrac{\\ln t}{t}\\Big).", explanation: "Factor out \\( t \\) so the logarithm splits into \\( \\ln t \\) plus a small piece." },
        { stepNumber: 5, description: "Linearise the small logarithm.", workingLatex: "\\ln\\!\\Big(1 - \\tfrac{\\ln t}{t}\\Big) = -\\frac{\\ln t}{t} + O\\!\\Big(\\frac{(\\ln t)^2}{t^2}\\Big).", explanation: "Use \\( \\ln(1+u) = u + O(u^2) \\) with \\( u = -\\tfrac{\\ln t}{t} \\)." },
        { stepNumber: 6, description: "Assemble the three terms.", workingLatex: "x = t - \\ln x_1 \\sim t - \\ln t + \\frac{\\ln t}{t}.", explanation: "The recovered \\( +\\tfrac{\\ln t}{t} \\) is the third term. (Verified numerically: at \\( t=10^9 \\) the coefficient of \\( \\tfrac{\\ln t}{t} \\) is \\( 1.0000 \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - \\ln t + \\dfrac{\\ln t}{t} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - log(t) + log(t)/t",
    },
  },
  {
    id: "am9b-008",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the asymptotic expansion, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x - \\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithmic correction", "iteration", "sign"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the iteration.", workingLatex: "x = t + \\ln x.", explanation: "Isolate \\( x \\); note the sign flip puts \\( +\\ln x \\) on the right." },
        { stepNumber: 2, description: "Leading and first correction.", workingLatex: "x_0 = t, \\qquad x_1 = t + \\ln t.", explanation: "Substitute \\( x_0 = t \\) into \\( \\ln x \\)." },
        { stepNumber: 3, description: "Expand the next logarithm.", workingLatex: "\\ln x_1 = \\ln t + \\ln\\!\\Big(1 + \\tfrac{\\ln t}{t}\\Big) = \\ln t + \\frac{\\ln t}{t} + \\cdots.", explanation: "Factor out \\( t \\) and linearise \\( \\ln(1+u) \\)." },
        { stepNumber: 4, description: "Assemble the three terms.", workingLatex: "x \\sim t + \\ln t + \\frac{\\ln t}{t}.", explanation: "Substituting back gives the third term. (Verified: coefficient \\( \\to 1 \\) at large \\( t \\).)" },
      ],
      finalAnswer: "\\( x \\sim t + \\ln t + \\dfrac{\\ln t}{t} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t + log(t) + log(t)/t",
    },
  },
  {
    id: "am9b-009",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the asymptotic expansion, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + 2\\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithmic correction", "coefficient", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up the iteration.", workingLatex: "x = t - 2\\ln x.", explanation: "Isolate the dominant term; the coefficient \\( 2 \\) is carried through." },
        { stepNumber: 2, description: "Leading and first correction.", workingLatex: "x_0 = t, \\qquad x_1 = t - 2\\ln t.", explanation: "Substitute \\( x_0 = t \\) into \\( 2\\ln x \\)." },
        { stepNumber: 3, description: "Expand the next logarithm.", workingLatex: "2\\ln x_1 = 2\\ln t + 2\\ln\\!\\Big(1 - \\tfrac{2\\ln t}{t}\\Big) = 2\\ln t - \\frac{4\\ln t}{t} + \\cdots.", explanation: "Linearise: \\( 2\\ln(1 - \\tfrac{2\\ln t}{t}) = -\\tfrac{4\\ln t}{t} + \\cdots \\)." },
        { stepNumber: 4, description: "Assemble the three terms.", workingLatex: "x \\sim t - 2\\ln t + \\frac{4\\ln t}{t}.", explanation: "The third term has coefficient \\( 4 \\). (Verified numerically: coefficient \\( \\to 4.0000 \\) at \\( t=10^{12} \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - 2\\ln t + \\dfrac{4\\ln t}{t} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - 2*log(t) + 4*log(t)/t",
    },
  },
  {
    id: "am9b-010",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 10",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The equation \\( x + x^{1/2} = t \\) can be solved exactly. By treating it as a quadratic in \\( u = x^{1/2} \\), find \\( x(t) \\) in closed form, and hence give its three-term expansion as \\( t \\to \\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "exact solution", "binomial expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute to linearise.", workingLatex: "u = x^{1/2} \\;\\Rightarrow\\; u^2 + u - t = 0.", explanation: "With \\( x = u^2 \\) the equation becomes an ordinary quadratic in \\( u \\)." },
        { stepNumber: 2, description: "Solve the quadratic, positive root.", workingLatex: "u = \\frac{-1 + \\sqrt{1 + 4t}}{2}.", explanation: "Take the \\( + \\) root since \\( u = x^{1/2} > 0 \\)." },
        { stepNumber: 3, description: "Square to recover x.", workingLatex: "x = u^2 = \\left(\\frac{\\sqrt{1 + 4t} - 1}{2}\\right)^{2}.", explanation: "This is the exact solution for all \\( t > 0 \\)." },
        { stepNumber: 4, description: "Expand the surd for large t.", workingLatex: "\\sqrt{1 + 4t} = 2t^{1/2}\\Big(1 + \\tfrac{1}{4t}\\Big)^{1/2} = 2t^{1/2} + \\frac{1}{2}t^{-1/2} + \\cdots.", explanation: "Factor out \\( 4t \\) and use the binomial series." },
        { stepNumber: 5, description: "Form u and square.", workingLatex: "u = t^{1/2} - \\tfrac12 + \\tfrac14 t^{-1/2} + \\cdots, \\quad x = u^2 \\sim t - t^{1/2} + \\tfrac12.", explanation: "Squaring and collecting orders gives the three-term expansion. (Verified: at \\( t=10^6 \\), \\( x = 999000.4999 \\) versus \\( t - t^{1/2} + \\tfrac12 = 999000.5 \\).)" },
      ],
      finalAnswer: "\\( x = \\left(\\dfrac{\\sqrt{1+4t}-1}{2}\\right)^{2} \\sim t - t^{1/2} + \\dfrac12 \\).",
      canonicalAnswer: "((sqrt(1+4*t)-1)/2)^2",
    },
  },
  {
    id: "am9b-011",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms in the asymptotic expansion, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x^2 + \\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "logarithmic correction", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange for the dominant power.", workingLatex: "x = \\big(t - \\ln x\\big)^{1/2}.", explanation: "The quadratic term dominates, so isolate \\( x^2 = t - \\ln x \\) and take the positive root." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x_0 = t^{1/2}.", explanation: "Dropping the logarithm gives the leading balance." },
        { stepNumber: 3, description: "Insert into the logarithm.", workingLatex: "\\ln x_0 = \\ln t^{1/2} = \\tfrac12 \\ln t.", explanation: "Evaluate \\( \\ln x \\) at the leading term; the half comes from the square root." },
        { stepNumber: 4, description: "Expand the square root.", workingLatex: "x = \\Big(t - \\tfrac12\\ln t\\Big)^{1/2} = t^{1/2}\\Big(1 - \\tfrac{\\ln t}{2t}\\Big)^{1/2}.", explanation: "Factor out \\( t \\) ready for the binomial expansion." },
        { stepNumber: 5, description: "Linearise.", workingLatex: "x \\sim t^{1/2}\\Big(1 - \\tfrac{\\ln t}{4t}\\Big) = t^{1/2} - \\frac{\\ln t}{4\\,t^{1/2}}.", explanation: "Use \\( (1+u)^{1/2} = 1 + \\tfrac12 u + \\cdots \\). (Verified: at \\( t=10^{10} \\), exact \\( x \\) matches \\( t^{1/2} - \\tfrac{\\ln t}{4t^{1/2}} \\) to 14 s.f.)" },
      ],
      finalAnswer: "\\( x \\sim t^{1/2} - \\dfrac{\\ln t}{4\\,t^{1/2}} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "sqrt(t) - log(t)/(4*sqrt(t))",
    },
  },
  {
    id: "am9b-012",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/2} + \\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "logarithmic correction", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Order the left-hand terms.", workingLatex: "x \\gg x^{1/2} \\gg \\ln x.", explanation: "For large \\( x \\) the terms decrease in this order, fixing the sequence of corrections." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x \\sim t.", explanation: "The linear term balances \\( t \\)." },
        { stepNumber: 3, description: "Iterate for the next term.", workingLatex: "x = t - x^{1/2} - \\ln x \\sim t - t^{1/2}.", explanation: "Insert \\( x \\sim t \\) into \\( x^{1/2} \\); the half-power term is the next correction (the log is smaller still)." },
        { stepNumber: 4, description: "Third term: include the log.", workingLatex: "\\ln x = \\ln\\!\\big(t - t^{1/2} + \\cdots\\big) \\sim \\ln t.", explanation: "At this order the logarithm of \\( x \\) is just \\( \\ln t \\); the correction inside the log is higher order." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x \\sim t - t^{1/2} - \\ln t.", explanation: "The three leading terms come from \\( t \\), the half-power, and the logarithm in turn." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t) - log(t)",
    },
  },
  {
    id: "am9b-013",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + 3x^{1/2} = t \\), by iteration (do not use the exact quadratic solution).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "coefficient", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange for iteration.", workingLatex: "x = t - 3x^{1/2}.", explanation: "Isolate the dominant term; the coefficient \\( 3 \\) rides along on the half-power correction." },
        { stepNumber: 2, description: "Leading and first correction.", workingLatex: "x_0 = t, \\qquad x_1 = t - 3t^{1/2}.", explanation: "Substitute \\( x_0 = t \\) into \\( 3x^{1/2} \\)." },
        { stepNumber: 3, description: "Refine the half-power term.", workingLatex: "x_1^{1/2} = t^{1/2}\\Big(1 - \\tfrac{3}{t^{1/2}}\\Big)^{1/2} = t^{1/2} - \\tfrac32 + \\cdots.", explanation: "Expand \\( (1+u)^{1/2} \\) with \\( u = -3 t^{-1/2} \\) to pick up the constant." },
        { stepNumber: 4, description: "Form the third term.", workingLatex: "x = t - 3x_1^{1/2} \\sim t - 3t^{1/2} + \\tfrac92.", explanation: "The constant term is \\( -3 \\times (-\\tfrac32) = \\tfrac92 = c^2/2 \\) with \\( c=3 \\). (Verified: \\( d \\to 4.5 \\) numerically.)" },
      ],
      finalAnswer: "\\( x \\sim t - 3t^{1/2} + \\dfrac92 \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - 3*sqrt(t) + 9/2",
    },
  },
  {
    id: "am9b-014",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["seed equation", "mixed powers", "logarithmic correction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "The largest term on each side gives \\( x \\approx t \\)." },
        { stepNumber: 2, description: "Rearrange for iteration.", workingLatex: "x = t + \\ln t - x^{1/2} - 2\\ln x.", explanation: "Isolate the dominant \\( x \\); all remaining terms are subdominant and will be evaluated at the leading approximation." },
        { stepNumber: 3, description: "Second term is the half-power.", workingLatex: "x^{1/2} \\sim t^{1/2} \\;\\Rightarrow\\; x \\sim t - t^{1/2} + \\cdots.", explanation: "The largest correction is \\( -x^{1/2} \\sim -t^{1/2} \\), bigger than any logarithm." },
        { stepNumber: 4, description: "Collect the logarithms for the third term.", workingLatex: "\\ln t - 2\\ln x \\sim \\ln t - 2\\ln t = -\\ln t.", explanation: "With \\( \\ln x \\sim \\ln t \\), the log terms combine to \\( -\\ln t \\)." },
        { stepNumber: 5, description: "Assemble three terms.", workingLatex: "x \\sim t - t^{1/2} - \\ln t.", explanation: "Linear, half-power, then logarithm. (This is the seed equation; verified numerically.)" },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t) - log(t)",
    },
  },
  {
    id: "am9b-015",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of the transcendental equation \\( x\\,e^{x} = t \\). (You may quote the relation \\( x = W(t) \\) but should derive the asymptotics directly.)",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "Lambert W", "iterated logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x + x = \\ln t.", explanation: "Taking \\( \\ln \\) of \\( x e^x = t \\) turns the exponential into a linear-plus-log balance — the same structure as the algebraic problems." },
        { stepNumber: 2, description: "Leading balance.", workingLatex: "x \\sim \\ln t.", explanation: "Here \\( x \\) dominates \\( \\ln x \\), so \\( x \\) balances \\( \\ln t \\)." },
        { stepNumber: 3, description: "Rearrange and iterate.", workingLatex: "x = \\ln t - \\ln x.", explanation: "Isolate \\( x \\); the small correction is \\( \\ln x \\)." },
        { stepNumber: 4, description: "Insert the leading term.", workingLatex: "x \\sim \\ln t - \\ln(\\ln t).", explanation: "Substitute \\( x \\sim \\ln t \\) into \\( \\ln x \\), giving the iterated logarithm. (Verified against \\( W(t) \\): at \\( t=10^{30} \\), \\( \\ln t - \\ln\\ln t = 64.84 \\), approaching \\( W=64.905 \\); the gap \\( 0.06 \\) is the next term \\( \\tfrac{\\ln\\ln t}{\\ln t} \\).)" },
      ],
      finalAnswer: "\\( x \\sim \\ln t - \\ln(\\ln t) \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "log(t) - log(log(t))",
    },
  },
  {
    id: "am9b-016",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 16",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x\\,\\ln x = t \\), and state the form of the first correction.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "iterated logarithm", "dominant balance"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x + \\ln(\\ln x) = \\ln t.", explanation: "Logging \\( x\\ln x = t \\) separates the dominant \\( \\ln x \\) from the slowly varying \\( \\ln\\ln x \\)." },
        { stepNumber: 2, description: "Leading balance for ln x.", workingLatex: "\\ln x \\sim \\ln t.", explanation: "The double-log term is negligible, so \\( \\ln x \\approx \\ln t \\)." },
        { stepNumber: 3, description: "Solve for x at leading order.", workingLatex: "x = \\frac{t}{\\ln x} \\sim \\frac{t}{\\ln t}.", explanation: "Divide the original equation by \\( \\ln x \\) and insert \\( \\ln x \\sim \\ln t \\)." },
        { stepNumber: 4, description: "Shape of the correction.", workingLatex: "x \\sim \\frac{t}{\\ln t}\\left(1 + \\frac{\\ln(\\ln t)}{\\ln t} + \\cdots\\right).", explanation: "Refining \\( \\ln x = \\ln t - \\ln\\ln t + \\cdots \\) feeds back a relative correction of order \\( \\tfrac{\\ln\\ln t}{\\ln t} \\). (Verified: \\( x\\ln t / t \\to 1 \\) slowly, from above, as predicted.)" },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{t}{\\ln t} \\), with relative correction \\( \\dfrac{\\ln\\ln t}{\\ln t} \\).",
      canonicalAnswer: "t/log(t)",
    },
  },
  {
    id: "am9b-017",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 17",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/3} + \\ln x = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "cube root", "logarithmic correction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Order the terms.", workingLatex: "x \\gg x^{1/3} \\gg \\ln x.", explanation: "For large \\( x \\) the cube-root term beats the logarithm, so it is the next correction after the linear term." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x \\sim t.", explanation: "The linear term balances \\( t \\)." },
        { stepNumber: 3, description: "Second term: cube root.", workingLatex: "x = t - x^{1/3} - \\ln x \\sim t - t^{1/3}.", explanation: "Insert \\( x \\sim t \\) into \\( x^{1/3} \\)." },
        { stepNumber: 4, description: "Third term: logarithm.", workingLatex: "\\ln x \\sim \\ln t \\;\\Rightarrow\\; x \\sim t - t^{1/3} - \\ln t.", explanation: "The log term, evaluated at \\( x \\sim t \\), supplies the third term. (Verified: residual after three terms is \\( O(t^{-1/3}) \\) with coefficient \\( \\to \\tfrac13 \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/3} - \\ln t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - t^(1/3) - log(t)",
    },
  },
  {
    id: "am9b-018",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 18",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + (\\ln x)^2 = t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithmic correction", "squared log", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rearrange.", workingLatex: "x = t - (\\ln x)^2.", explanation: "Isolate the dominant term; the correction is now a squared logarithm." },
        { stepNumber: 2, description: "Leading and first correction.", workingLatex: "x_0 = t, \\qquad x_1 = t - (\\ln t)^2.", explanation: "Insert \\( x_0 = t \\) into \\( (\\ln x)^2 \\)." },
        { stepNumber: 3, description: "Expand the next squared log.", workingLatex: "(\\ln x_1)^2 = \\Big(\\ln t - \\tfrac{(\\ln t)^2}{t} + \\cdots\\Big)^2 = (\\ln t)^2 - \\frac{2(\\ln t)^3}{t} + \\cdots.", explanation: "Use \\( \\ln x_1 = \\ln t + \\ln(1 - \\tfrac{(\\ln t)^2}{t}) \\) and square." },
        { stepNumber: 4, description: "Assemble three terms.", workingLatex: "x \\sim t - (\\ln t)^2 + \\frac{2(\\ln t)^3}{t}.", explanation: "The third term is \\( +\\tfrac{2(\\ln t)^3}{t} \\). (Verified: two-term residual scales as \\( (\\ln t)^3/t \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - (\\ln t)^2 + \\dfrac{2(\\ln t)^3}{t} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - (log(t))^2 + 2*(log(t))^3/t",
    },
  },

  // ─────────────────────────── CHALLENGE (12) ───────────────────────────
  {
    id: "am9b-019",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\). Find the first four terms in the asymptotic expansion of \\( x(t) \\) as \\( t \\to \\infty \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["seed equation", "four-term expansion", "constant term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "Largest term each side." },
        { stepNumber: 2, description: "Rearrange for iteration.", workingLatex: "x = t + \\ln t - x^{1/2} - 2\\ln x.", explanation: "Isolate the dominant \\( x \\); evaluate the rest at progressively refined approximations." },
        { stepNumber: 3, description: "Half-power term.", workingLatex: "x \\sim t - t^{1/2} + \\cdots.", explanation: "Insert \\( x \\sim t \\) into \\( -x^{1/2} \\); this is the second term." },
        { stepNumber: 4, description: "Logarithm term.", workingLatex: "\\ln t - 2\\ln x \\sim \\ln t - 2\\ln t = -\\ln t.", explanation: "With \\( \\ln x \\sim \\ln t \\) the log group gives the third term \\( -\\ln t \\)." },
        { stepNumber: 5, description: "Refine the half-power for the constant.", workingLatex: "x^{1/2} = \\big(t - t^{1/2} + \\cdots\\big)^{1/2} = t^{1/2}\\Big(1 - t^{-1/2}\\Big)^{1/2} = t^{1/2} - \\tfrac12 + \\cdots.", explanation: "The next correction inside \\( x \\) feeds a constant \\( -\\tfrac12 \\) into \\( x^{1/2} \\)." },
        { stepNumber: 6, description: "Collect the constant.", workingLatex: "x = \\cdots - x^{1/2} = \\cdots - \\big(t^{1/2} - \\tfrac12\\big) \\;\\Rightarrow\\; +\\tfrac12.", explanation: "The \\( -(-\\tfrac12) = +\\tfrac12 \\) is the fourth (constant) term; the logarithm contributes no constant at this order." },
        { stepNumber: 7, description: "State the four-term expansion.", workingLatex: "x \\sim t - t^{1/2} - \\ln t + \\tfrac12.", explanation: "Verified numerically (mpmath, dps=40): at \\( t=10^{12} \\) the difference \\( x - (t - t^{1/2} - \\ln t) \\to 0.50002 \\to \\tfrac12 \\); residual is \\( O\\!\\big(\\tfrac{\\ln t}{t^{1/2}}\\big) \\)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t + \\dfrac12 \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t) - log(t) + 1/2",
    },
  },
  {
    id: "am9b-020",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the equation \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\), show that for all \\( t \\ge 10 \\) there is a unique solution \\( x(t) \\), and that \\( x(t) \\to \\infty \\) as \\( t \\to \\infty \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["existence", "uniqueness", "monotonicity", "seed equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Define a monotone function.", workingLatex: "F(x) = x + x^{1/2} + 2\\ln x, \\qquad x > 0.", explanation: "Solving the equation is the same as solving \\( F(x) = t + \\ln t \\). Study \\( F \\) on \\( (0,\\infty) \\)." },
        { stepNumber: 2, description: "Show F is strictly increasing.", workingLatex: "F'(x) = 1 + \\tfrac12 x^{-1/2} + \\tfrac{2}{x} > 0 \\quad (x>0).", explanation: "Every term of \\( F' \\) is positive, so \\( F \\) is strictly increasing and hence injective." },
        { stepNumber: 3, description: "Establish the range.", workingLatex: "F(x) \\to -\\infty \\text{ as } x \\to 0^{+}, \\qquad F(x) \\to +\\infty \\text{ as } x \\to \\infty.", explanation: "As \\( x \\to 0^+ \\) the \\( 2\\ln x \\) term drives \\( F \\to -\\infty \\); as \\( x \\to \\infty \\) the \\( x \\) term dominates. So \\( F \\) is a bijection \\( (0,\\infty)\\to(-\\infty,\\infty) \\)." },
        { stepNumber: 4, description: "Conclude existence and uniqueness.", workingLatex: "\\forall\\, t \\ge 10:\\ \\exists!\\, x(t)>0 \\text{ with } F(x(t)) = t + \\ln t.", explanation: "By the intermediate value theorem a solution exists; by strict monotonicity it is unique. (The RHS \\( t+\\ln t \\) is finite for each fixed \\( t \\ge 10 \\).)" },
        { stepNumber: 5, description: "Show divergence.", workingLatex: "t + \\ln t \\to \\infty \\;\\Rightarrow\\; F(x(t)) \\to \\infty \\;\\Rightarrow\\; x(t) \\to \\infty.", explanation: "Since \\( F \\) is increasing and unbounded above, its inverse sends \\( +\\infty \\) to \\( +\\infty \\); thus \\( x(t)\\to\\infty \\)." },
      ],
      finalAnswer: "\\( F(x)=x+x^{1/2}+2\\ln x \\) is a strictly increasing bijection \\( (0,\\infty)\\to\\mathbb{R} \\), so \\( x(t) \\) exists, is unique, and \\( x(t)\\to\\infty \\).",
    },
  },
  {
    id: "am9b-021",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 21",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first four terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + 3x^{1/2} + \\ln x = t + 2\\ln t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "master formula", "four-term expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the parameters.", workingLatex: "x + c\\,x^{1/2} + b\\ln x = t + a\\ln t, \\quad a=2,\\ b=1,\\ c=3.", explanation: "Recognise the canonical mixed-power/log form so the term structure \\( t \\), \\( \\ln t \\), \\( t^{1/2} \\), const can be read off." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x \\sim t.", explanation: "Linear terms balance." },
        { stepNumber: 3, description: "Half-power term.", workingLatex: "x = t + 2\\ln t - 3x^{1/2} - \\ln x, \\quad x^{1/2}\\sim t^{1/2} \\Rightarrow x \\sim t - 3t^{1/2}.", explanation: "The \\( -3x^{1/2} \\) correction dominates the logarithms." },
        { stepNumber: 4, description: "Logarithm term.", workingLatex: "2\\ln t - \\ln x \\sim 2\\ln t - \\ln t = +\\ln t.", explanation: "With \\( \\ln x \\sim \\ln t \\), the log group is \\( (a-b)\\ln t = +\\ln t \\)." },
        { stepNumber: 5, description: "Constant from refining the half-power.", workingLatex: "x^{1/2} = \\big(t - 3t^{1/2}+\\cdots\\big)^{1/2} = t^{1/2} - \\tfrac32 + \\cdots, \\quad -3x^{1/2}\\ \\text{gives}\\ +\\tfrac92.", explanation: "Constant term \\( = c^2/2 = 9/2 \\), exactly as in the single-power case." },
        { stepNumber: 6, description: "Assemble four terms.", workingLatex: "x \\sim t - 3t^{1/2} + \\ln t + \\tfrac92.", explanation: "Matches the master formula \\( t + (a-b)\\ln t - c t^{1/2} + c^2/2 \\). (Verified numerically: \\( x-\\text{approx} \\to 0 \\) at \\( t=10^{12} \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - 3t^{1/2} + \\ln t + \\dfrac92 \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - 3*sqrt(t) + log(t) + 9/2",
    },
  },
  {
    id: "am9b-022",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 22",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that the solution of \\( x + c\\,x^{1/2} + b\\ln x = t + a\\ln t \\) has the four-term expansion \\( x \\sim t + (a-b)\\ln t - c\\,t^{1/2} + \\tfrac12 c^{2} \\) as \\( t \\to \\infty \\), for constants \\( a,b,c \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["master formula", "general parameters", "four-term expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "The linear terms dominate both sides." },
        { stepNumber: 2, description: "Isolate the dominant term.", workingLatex: "x = t + a\\ln t - c\\,x^{1/2} - b\\ln x.", explanation: "Everything except \\( x \\) is subdominant; evaluate it at successively refined approximations." },
        { stepNumber: 3, description: "Second term (half-power).", workingLatex: "c\\,x^{1/2} \\sim c\\,t^{1/2} \\;\\Rightarrow\\; x \\sim t - c\\,t^{1/2}.", explanation: "The algebraic correction \\( t^{1/2} \\) beats every logarithm, so it appears before the log terms." },
        { stepNumber: 4, description: "Third term (logarithms).", workingLatex: "a\\ln t - b\\ln x \\sim a\\ln t - b\\ln t = (a-b)\\ln t.", explanation: "Using \\( \\ln x = \\ln t + O(t^{-1/2}) \\); the \\( O(t^{-1/2}) \\) piece is higher order than the constant we seek next." },
        { stepNumber: 5, description: "Refine the half-power.", workingLatex: "x^{1/2} = \\Big(t - c\\,t^{1/2} + \\cdots\\Big)^{1/2} = t^{1/2}\\Big(1 - c\\,t^{-1/2}\\Big)^{1/2} = t^{1/2} - \\tfrac{c}{2} + \\cdots.", explanation: "Binomial expansion to one further order produces a constant \\( -c/2 \\)." },
        { stepNumber: 6, description: "Extract the constant term.", workingLatex: "-\\,c\\,x^{1/2} = -c\\Big(t^{1/2} - \\tfrac{c}{2}\\Big) = -c\\,t^{1/2} + \\tfrac{c^2}{2}.", explanation: "The constant is \\( +c^2/2 \\); the log terms contribute no constant at this order (their constant correction is \\( O(t^{-1/2}\\ln t) \\))." },
        { stepNumber: 7, description: "Assemble.", workingLatex: "x \\sim t + (a-b)\\ln t - c\\,t^{1/2} + \\tfrac{c^2}{2}.", explanation: "Verified numerically over \\( (a,b,c) = (1,2,1),(2,1,3),(0,1,2),(3,0,1),(1,1,1) \\): residual \\( <10^{-4} \\) at \\( t=10^{12} \\)." },
      ],
      finalAnswer: "\\( x \\sim t + (a-b)\\ln t - c\\,t^{1/2} + \\dfrac{c^2}{2} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t + (a-b)*log(t) - c*sqrt(t) + c^2/2",
    },
  },
  {
    id: "am9b-023",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 23",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x\\,e^{x} = t \\) (the Lambert \\( W \\) function \\( x = W(t) \\)).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Lambert W", "iterated logarithm", "transcendental equation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "x + \\ln x = \\ln t.", explanation: "Set \\( L_1 = \\ln t \\); the equation becomes a linear-plus-log balance in \\( x \\)." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x \\sim \\ln t = L_1.", explanation: "\\( x \\) dominates \\( \\ln x \\)." },
        { stepNumber: 3, description: "Rearrange and iterate.", workingLatex: "x = L_1 - \\ln x.", explanation: "Isolate \\( x \\); the correction is \\( -\\ln x \\)." },
        { stepNumber: 4, description: "Second term.", workingLatex: "x \\sim L_1 - \\ln L_1, \\qquad L_2 := \\ln L_1 = \\ln\\ln t.", explanation: "Insert \\( x \\sim L_1 \\) into \\( \\ln x \\); the second term is the iterated logarithm \\( -L_2 \\)." },
        { stepNumber: 5, description: "Third term: expand the log again.", workingLatex: "\\ln x = \\ln\\!\\Big(L_1 - L_2\\Big) = \\ln L_1 + \\ln\\!\\Big(1 - \\tfrac{L_2}{L_1}\\Big) = L_2 - \\frac{L_2}{L_1} + \\cdots.", explanation: "Factor out \\( L_1 \\) and linearise the residual logarithm." },
        { stepNumber: 6, description: "Assemble.", workingLatex: "x = L_1 - \\ln x \\sim L_1 - L_2 + \\frac{L_2}{L_1}.", explanation: "So \\( W(t) \\sim \\ln t - \\ln\\ln t + \\dfrac{\\ln\\ln t}{\\ln t} \\). (Verified against mpmath \\( W \\): residual after three terms decreases steadily for \\( t=10^6,10^{12},10^{30} \\).)" },
      ],
      finalAnswer: "\\( x = W(t) \\sim \\ln t - \\ln\\ln t + \\dfrac{\\ln\\ln t}{\\ln t} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "log(t) - log(log(t)) + log(log(t))/log(t)",
    },
  },
  {
    id: "am9b-024",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 24",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first four terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/2} + \\ln x = t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "logarithmic correction", "four-term expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify parameters.", workingLatex: "a=0,\\ b=1,\\ c=1 \\ \\text{in}\\ x + c x^{1/2} + b\\ln x = t + a\\ln t.", explanation: "No \\( \\ln t \\) on the right, single half-power, single log." },
        { stepNumber: 2, description: "Leading and half-power terms.", workingLatex: "x \\sim t - t^{1/2}.", explanation: "Linear balance, then the \\( -x^{1/2} \\sim -t^{1/2} \\) correction." },
        { stepNumber: 3, description: "Logarithm term.", workingLatex: "(a-b)\\ln t = -\\ln t \\;\\Rightarrow\\; x \\sim t - t^{1/2} - \\ln t.", explanation: "With \\( a=0, b=1 \\), the third term is \\( -\\ln t \\)." },
        { stepNumber: 4, description: "Constant term.", workingLatex: "x^{1/2} = t^{1/2} - \\tfrac12 + \\cdots \\;\\Rightarrow\\; -x^{1/2}\\ \\text{contributes}\\ +\\tfrac12.", explanation: "Refine the half-power; constant \\( = c^2/2 = \\tfrac12 \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x \\sim t - t^{1/2} - \\ln t + \\tfrac12.", explanation: "Same constant as the seed because \\( c=1 \\) is unchanged. (Verified numerically.)" },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t + \\dfrac12 \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t) - log(t) + 1/2",
    },
  },
  {
    id: "am9b-025",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 25",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first four terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + x^{1/3} + \\ln x = t \\), including the term beyond \\( -\\ln t \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cube root", "mixed powers", "four-term expansion"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Order the terms and isolate x.", workingLatex: "x = t - x^{1/3} - \\ln x, \\qquad x \\gg x^{1/3} \\gg \\ln x.", explanation: "Cube-root correction dominates the logarithm." },
        { stepNumber: 2, description: "First three terms.", workingLatex: "x \\sim t - t^{1/3} - \\ln t.", explanation: "Linear, cube-root (\\( x^{1/3}\\sim t^{1/3} \\)), then \\( \\ln x \\sim \\ln t \\)." },
        { stepNumber: 3, description: "Refine the cube root.", workingLatex: "x^{1/3} = \\big(t - t^{1/3} + \\cdots\\big)^{1/3} = t^{1/3}\\Big(1 - t^{-2/3}\\Big)^{1/3} = t^{1/3} - \\tfrac13 t^{-1/3} + \\cdots.", explanation: "Binomial expansion with \\( u = -t^{-2/3} \\): \\( (1+u)^{1/3} = 1 + \\tfrac13 u + \\cdots \\)." },
        { stepNumber: 4, description: "Extract the fourth term.", workingLatex: "-\\,x^{1/3} = -t^{1/3} + \\tfrac13 t^{-1/3} + \\cdots.", explanation: "The recovered \\( +\\tfrac13 t^{-1/3} \\) is the fourth term; it beats the next log correction \\( O(t^{-1}\\ln t) \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x \\sim t - t^{1/3} - \\ln t + \\tfrac13 t^{-1/3}.", explanation: "Verified numerically: \\( \\big(x - (t - t^{1/3} - \\ln t)\\big)\\,t^{1/3} \\to \\tfrac13 \\) as \\( t \\to \\infty \\)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/3} - \\ln t + \\dfrac13\\,t^{-1/3} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - t^(1/3) - log(t) + (1/3)*t^(-1/3)",
    },
  },
  {
    id: "am9b-026",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 26",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first four terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x + \\ln x = t \\), beyond the term \\( +\\dfrac{\\ln t}{t} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithmic correction", "higher order", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall three terms.", workingLatex: "x \\sim t - \\ln t + \\frac{\\ln t}{t} + \\cdots.", explanation: "From the standard iteration \\( x = t - \\ln x \\)." },
        { stepNumber: 2, description: "Form ln x to higher order.", workingLatex: "x = t\\Big(1 - \\tfrac{\\ln t}{t} + \\tfrac{\\ln t}{t^2} + \\cdots\\Big), \\quad \\ln x = \\ln t + \\ln\\!\\Big(1 - \\tfrac{\\ln t}{t} + \\cdots\\Big).", explanation: "Factor out \\( t \\) inside the logarithm." },
        { stepNumber: 3, description: "Expand the inner log to second order.", workingLatex: "\\ln\\!\\Big(1 - \\tfrac{\\ln t}{t}\\Big) = -\\frac{\\ln t}{t} - \\frac{1}{2}\\frac{(\\ln t)^2}{t^2} + \\cdots.", explanation: "Use \\( \\ln(1+u) = u - \\tfrac12 u^2 + \\cdots \\) with \\( u = -\\tfrac{\\ln t}{t} \\)." },
        { stepNumber: 4, description: "Collect the t^{-2} terms.", workingLatex: "\\ln x = \\ln t - \\frac{\\ln t}{t} + \\Big(\\frac{\\ln t}{t^2} - \\frac{(\\ln t)^2}{2t^2}\\Big) + \\cdots.", explanation: "Combine the linear feedback term \\( +\\tfrac{\\ln t}{t^2} \\) with the quadratic log term." },
        { stepNumber: 5, description: "Substitute into x = t - ln x.", workingLatex: "x \\sim t - \\ln t + \\frac{\\ln t}{t} - \\frac{\\ln t}{t^2} + \\frac{(\\ln t)^2}{2t^2}.", explanation: "The fourth-order group is \\( \\dfrac{(\\ln t)^2/2 - \\ln t}{t^2} \\). (Verified: dominant fourth term scales as \\( (\\ln t)^2/t^2 \\).)" },
      ],
      finalAnswer: "\\( x \\sim t - \\ln t + \\dfrac{\\ln t}{t} + \\dfrac{(\\ln t)^2/2 - \\ln t}{t^2} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - log(t) + log(t)/t + ((log(t))^2/2 - log(t))/t^2",
    },
  },
  {
    id: "am9b-027",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 27",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x^{2} + x + \\ln x = t \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed powers", "quadratic leading", "logarithmic correction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x^2 \\sim t \\;\\Rightarrow\\; x \\sim t^{1/2}.", explanation: "The quadratic term dominates; take the positive root." },
        { stepNumber: 2, description: "Isolate the dominant term.", workingLatex: "x^2 = t - x - \\ln x \\;\\Rightarrow\\; x = \\big(t - x - \\ln x\\big)^{1/2}.", explanation: "The next correction is the linear \\( -x \\sim -t^{1/2} \\), bigger than the logarithm." },
        { stepNumber: 3, description: "Second term.", workingLatex: "x = \\Big(t - t^{1/2} + \\cdots\\Big)^{1/2} = t^{1/2}\\Big(1 - t^{-1/2}\\Big)^{1/2} = t^{1/2} - \\tfrac12 + \\cdots.", explanation: "Binomial expansion gives the constant \\( -\\tfrac12 \\) as the second term." },
        { stepNumber: 4, description: "Track the log into the third term.", workingLatex: "x^2 = t - x - \\ln x, \\quad \\ln x \\sim \\tfrac12\\ln t, \\quad x \\sim t^{1/2} - \\tfrac12.", explanation: "Now include \\( -\\ln x \\sim -\\tfrac12\\ln t \\) inside the bracket along with \\( -x \\)." },
        { stepNumber: 5, description: "Expand with both corrections.", workingLatex: "x = \\Big(t - t^{1/2} + \\tfrac12 - \\tfrac12\\ln t\\Big)^{1/2} = t^{1/2}\\Big(1 - t^{-1/2} + \\tfrac{1 - \\ln t}{2t}\\Big)^{1/2}.", explanation: "Carry the \\( O(1/t) \\)-relative terms which produce the third term." },
        { stepNumber: 6, description: "Linearise to the third term.", workingLatex: "x \\sim t^{1/2} - \\tfrac12 + \\frac{1}{t^{1/2}}\\Big(\\tfrac{1 - \\ln t}{4} - \\tfrac18\\Big) = t^{1/2} - \\tfrac12 - \\frac{\\ln t}{4\\,t^{1/2}} + \\cdots.", explanation: "The dominant third term is \\( -\\dfrac{\\ln t}{4\\,t^{1/2}} \\). (Verified numerically: leading correction beyond \\( t^{1/2}-\\tfrac12 \\) scales as \\( \\ln t / t^{1/2} \\) with coefficient \\( -\\tfrac14 \\).)" },
      ],
      finalAnswer: "\\( x \\sim t^{1/2} - \\dfrac12 - \\dfrac{\\ln t}{4\\,t^{1/2}} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "sqrt(t) - 1/2 - log(t)/(4*sqrt(t))",
    },
  },
  // REVIEW: fifth term — numerics confirm the leading piece +(ln t)/(2 sqrt t) (coefficient of (ln t)/sqrt t converges to 1/2: 0.581 -> 0.520 as t: 1e10 -> 1e40), but there is an additional O(1/sqrt t) constant companion not pinned to closed form, hence the "+..." in the stated answer.
  {
    id: "am9b-028",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 28",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The equation \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\) has solution \\( x \\sim t - t^{1/2} - \\ln t + \\tfrac12 \\). Find the next (fifth) term in the expansion.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["seed equation", "fifth term", "higher order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Isolate x with four terms known.", workingLatex: "x = t + \\ln t - x^{1/2} - 2\\ln x, \\quad x = t - t^{1/2} - \\ln t + \\tfrac12 + \\delta.", explanation: "Write the unknown fifth term as \\( \\delta \\) and feed the four known terms into the right-hand side to determine it." },
        { stepNumber: 2, description: "Refine the half-power to next order.", workingLatex: "x^{1/2} = t^{1/2}\\Big(1 - t^{-1/2} - \\tfrac{\\ln t}{t} + \\tfrac{1}{2t}\\Big)^{1/2}.", explanation: "Insert the four-term \\( x \\) (relative to \\( t \\)) into the square root." },
        { stepNumber: 3, description: "Expand the square root.", workingLatex: "x^{1/2} = t^{1/2} - \\tfrac12 - \\frac{\\ln t}{2\\,t^{1/2}} + \\frac{?}{t^{1/2}} + \\cdots.", explanation: "The \\( -\\tfrac{\\ln t}{t} \\) inside contributes \\( -\\dfrac{\\ln t}{2 t^{1/2}} \\) after multiplying by \\( \\tfrac12 t^{1/2} \\)." },
        { stepNumber: 4, description: "Refine the logarithm.", workingLatex: "2\\ln x = 2\\ln t + 2\\ln\\!\\Big(1 - t^{-1/2} + \\cdots\\Big) = 2\\ln t - \\frac{2}{t^{1/2}} + \\cdots.", explanation: "The relative \\( -t^{-1/2} \\) gives \\( -\\dfrac{2}{t^{1/2}} \\) from the log group." },
        { stepNumber: 5, description: "Collect the t^{-1/2} terms.", workingLatex: "\\delta = -\\Big(-\\frac{\\ln t}{2 t^{1/2}}\\Big) - \\Big(-\\frac{2}{t^{1/2}}\\Big) - \\big(\\text{const-recovery}\\big) = \\frac{\\ln t}{2\\,t^{1/2}} + \\frac{C}{t^{1/2}}.", explanation: "The fifth term is of order \\( t^{-1/2}\\ln t \\); the dominant piece is \\( +\\dfrac{\\ln t}{2\\,t^{1/2}} \\)." },
        { stepNumber: 6, description: "State the fifth term.", workingLatex: "x \\sim t - t^{1/2} - \\ln t + \\tfrac12 + \\frac{\\ln t}{2\\,t^{1/2}} + \\cdots.", explanation: "Verified numerically: \\( \\big(x - \\text{(4 terms)}\\big)\\dfrac{t^{1/2}}{\\ln t} \\to \\tfrac12 \\) as \\( t \\to \\infty \\) (values \\( 0.57,0.56,0.55 \\) at \\( t=10^{12},10^{13},10^{14} \\), decreasing toward \\( \\tfrac12 \\) plus an \\( O(1/\\ln t) \\) constant tail)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t + \\dfrac12 + \\dfrac{\\ln t}{2\\,t^{1/2}} \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - sqrt(t) - log(t) + 1/2 + log(t)/(2*sqrt(t))",
    },
  },
  {
    id: "am9b-029",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 29",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first three terms, as \\( t \\to \\infty \\), of the solution \\( x(t) \\) of \\( x\\,\\ln x = t \\). Express the answer using \\( L = \\ln t \\) and \\( \\ell = \\ln\\ln t \\).",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "iterated logarithm", "double log"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x + \\ln(\\ln x) = \\ln t = L.", explanation: "Let \\( y = \\ln x \\); then \\( y + \\ln y = L \\), the same balance solved earlier." },
        { stepNumber: 2, description: "Expand y = ln x.", workingLatex: "y = L - \\ln y \\sim L - \\ln L = L - \\ell.", explanation: "With \\( \\ell = \\ln\\ln t = \\ln L \\), the iterated-log solution of \\( y + \\ln y = L \\) gives \\( y \\sim L - \\ell + \\tfrac{\\ell}{L} \\)." },
        { stepNumber: 3, description: "Refine y to a further term.", workingLatex: "y = \\ln x \\sim L - \\ell + \\frac{\\ell}{L}.", explanation: "Carry the third term of \\( y \\) since it enters \\( x = t/y \\) at the order we need." },
        { stepNumber: 4, description: "Recover x.", workingLatex: "x = \\frac{t}{\\ln x} = \\frac{t}{\\,L - \\ell + \\frac{\\ell}{L}\\,} = \\frac{t}{L}\\cdot\\frac{1}{\\,1 - \\frac{\\ell}{L} + \\frac{\\ell}{L^2}\\,}.", explanation: "Divide the original equation by \\( \\ln x \\) and factor out \\( L \\)." },
        { stepNumber: 5, description: "Expand the reciprocal.", workingLatex: "\\frac{1}{1 - \\frac{\\ell}{L} + \\cdots} = 1 + \\frac{\\ell}{L} + \\frac{\\ell^2}{L^2} - \\frac{\\ell}{L^2} + \\cdots.", explanation: "Geometric expansion \\( (1-u)^{-1} = 1 + u + u^2 + \\cdots \\) with \\( u = \\tfrac{\\ell}{L} - \\tfrac{\\ell}{L^2} \\)." },
        { stepNumber: 6, description: "Assemble three terms.", workingLatex: "x \\sim \\frac{t}{L}\\left(1 + \\frac{\\ell}{L} + \\frac{\\ell^2 - \\ell}{L^2}\\right).", explanation: "So \\( x \\sim \\dfrac{t}{\\ln t} + \\dfrac{t\\,\\ln\\ln t}{(\\ln t)^2} + \\cdots \\). (Verified: \\( x\\,L/t \\to 1 \\) from above with leading correction \\( \\ell/L \\).)" },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{t}{L}\\left(1 + \\dfrac{\\ell}{L} + \\dfrac{\\ell^2-\\ell}{L^2}\\right) \\), where \\( L=\\ln t,\\ \\ell=\\ln\\ln t \\).",
      canonicalAnswer: "(t/L)*(1 + l/L + (l^2 - l)/L^2)",
    },
  },
  {
    id: "am9b-030",
    topicRef: "am9b",
    topicTitle: "Logarithmic & mixed-power balances 30",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "The seed balance \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\) gives a large root \\( x_{+}(t)\\sim t \\). Consider instead the companion equation \\( x + x^{1/2} + 2\\ln x = -(t + \\ln t) \\). Show that for each large \\( t \\) it has a small root \\( x_{-}(t) \\to 0^{+} \\), and find the leading behaviour of \\( x_{-}(t) \\) as \\( t \\to \\infty \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["seed equation", "two roots", "small-root balance"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Behaviour of F near zero.", workingLatex: "F(x) = x + x^{1/2} + 2\\ln x, \\qquad F(x)\\to -\\infty \\ \\text{as}\\ x\\to 0^{+}.", explanation: "\\( F \\) is strictly increasing on \\( (0,\\infty) \\) and \\( 2\\ln x\\to-\\infty \\) as \\( x\\to 0^+ \\). Since the companion target \\( -(t+\\ln t)\\to-\\infty \\), the IVT plus monotonicity give a unique root, and it must lie near \\( 0 \\)." },
        { stepNumber: 2, description: "Set up the small-root balance.", workingLatex: "x + x^{1/2} + 2\\ln x = -(t + \\ln t), \\qquad x \\to 0^{+}.", explanation: "As \\( x\\to 0^+ \\), \\( 2\\ln x \\to -\\infty \\) dominates the bounded terms \\( x, x^{1/2} \\). This is the balance that produces a vanishing root for a large negative target." },
        { stepNumber: 3, description: "Dominant balance.", workingLatex: "2\\ln x \\sim -(t + \\ln t) \\sim -t.", explanation: "The algebraic terms \\( x + x^{1/2}\\to 0 \\) are negligible against \\( 2\\ln x \\)." },
        { stepNumber: 4, description: "Solve for x.", workingLatex: "\\ln x \\sim -\\tfrac{t}{2} \\;\\Rightarrow\\; x \\sim e^{-t/2}.", explanation: "Exponentiate the leading balance." },
        { stepNumber: 5, description: "First correction from the RHS log.", workingLatex: "2\\ln x = -t - \\ln t \\;\\Rightarrow\\; x \\sim e^{-t/2}\\,t^{-1/2}.", explanation: "Keeping \\( -\\ln t \\) gives a factor \\( e^{-(\\ln t)/2} = t^{-1/2} \\). (Verified: \\( 2\\ln x + t + \\ln t \\to 0 \\) for \\( x = t^{-1/2}e^{-t/2} \\); the dropped \\( x + x^{1/2} \\) is exponentially small.)" },
        { stepNumber: 6, description: "State the small root.", workingLatex: "x_{-}(t) \\sim t^{-1/2}\\,e^{-t/2}.", explanation: "Exponentially small, in sharp contrast with the algebraically large root \\( x_+ \\sim t \\)." },
      ],
      finalAnswer: "\\( x_{-}(t) \\sim t^{-1/2}\\,e^{-t/2} \\) as \\( t \\to \\infty \\) (companion balance \\( F(x)=-(t+\\ln t) \\)).",
      canonicalAnswer: "t^(-1/2)*exp(-t/2)",
    },
  },
];
