import { Question } from "@/lib/types";

/**
 * Graduate Asymptotic Methods — Asymptotics of Algebraic & Transcendental Equations
 * Subtopic am9c: Dominant balance & rescaling
 * 30 fully-worked questions (6 Foundation / 12 Standard / 12 Challenge).
 *
 * Theme: identifying the dominant balance in an equation containing a small (or
 * large) parameter, rescaling to expose hidden roots, and generating systematic
 * correction terms. Seeded from DAMTP Asymptotic Methods Example Sheet 3 Q2
 * (the transcendental equation x + x^{1/2} + 2 ln x = t + ln t) and standard
 * singular-perturbation material of this type. Constants/framings varied.
 *
 * Numerical spot-checks (mpmath/sympy) were run for every root/expansion that is
 * numerically checkable; pure "show that it is the dominant balance" reasoning
 * carries a // REVIEW comment where it could not be checked numerically.
 */
export const questions: Question[] = [
  // ───────────────────────── FOUNDATION (6) ─────────────────────────
  {
    id: "am9c-001",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Consider \\( \\varepsilon x^{2} + x - 1 = 0 \\) with \\( 0 < \\varepsilon \\ll 1 \\). By identifying the dominant balance, find the leading-order approximation to the root that remains \\( O(1) \\) as \\( \\varepsilon \\to 0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "regular root", "singular perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the small term aside.", workingLatex: "\\varepsilon x^{2} + x - 1 = 0, \\qquad \\varepsilon \\to 0.", explanation: "The coefficient \\( \\varepsilon \\) multiplies the highest power, so the equation is singularly perturbed: setting \\( \\varepsilon = 0 \\) lowers the degree from two to one and loses a root." },
        { stepNumber: 2, description: "Take the reduced (leading-order) balance.", workingLatex: "x - 1 \\approx 0.", explanation: "For an \\( O(1) \\) root the term \\( \\varepsilon x^{2} \\) is \\( O(\\varepsilon) \\) and negligible against \\( x \\) and \\( 1 \\). The dominant balance is between the two \\( O(1) \\) terms." },
        { stepNumber: 3, description: "Solve the reduced equation.", workingLatex: "x_{0} = 1.", explanation: "This is the regular root; it is close to the root of the unperturbed linear equation." },
      ],
      finalAnswer: "\\( x \\sim 1 \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am9c-002",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( \\varepsilon x^{2} + x - 1 = 0 \\) with \\( 0 < \\varepsilon \\ll 1 \\), the equation has two roots but the reduced equation has only one. Use the rescaling \\( x = X/\\varepsilon \\) to locate the leading-order behaviour of the lost (large) root.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["rescaling", "singular root", "distinguished limit"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute the rescaling.", workingLatex: "\\varepsilon \\left( \\frac{X}{\\varepsilon} \\right)^{2} + \\frac{X}{\\varepsilon} - 1 = 0.", explanation: "The lost root must be large, so we look for a scaling that promotes the previously-negligible \\( \\varepsilon x^{2} \\) term into the balance." },
        { stepNumber: 2, description: "Simplify.", workingLatex: "\\frac{X^{2}}{\\varepsilon} + \\frac{X}{\\varepsilon} - 1 = 0 \\;\\Longrightarrow\\; X^{2} + X - \\varepsilon = 0.", explanation: "Multiplying through by \\( \\varepsilon \\) shows the two leading terms \\( X^{2} \\) and \\( X \\) now balance, with \\( \\varepsilon \\) demoted to a small correction." },
        { stepNumber: 3, description: "Take the leading balance and solve.", workingLatex: "X^{2} + X \\approx 0 \\;\\Longrightarrow\\; X_{0} = -1.", explanation: "We discard \\( X = 0 \\) since that returns the regular root; the genuinely new root is \\( X = -1 \\)." },
        { stepNumber: 4, description: "Undo the rescaling.", workingLatex: "x = \\frac{X}{\\varepsilon} \\sim -\\frac{1}{\\varepsilon}.", explanation: "The lost root is \\( O(1/\\varepsilon) \\), confirming why setting \\( \\varepsilon = 0 \\) made it vanish to infinity." },
      ],
      finalAnswer: "\\( x \\sim -\\dfrac{1}{\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "-1/eps",
    },
  },
  {
    id: "am9c-003",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order approximation, as \\( \\varepsilon \\to 0^{+} \\), to the root of \\( x = 2 + \\varepsilon x^{3} \\) that is \\( O(1) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["regular perturbation", "dominant balance"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the dominant balance.", workingLatex: "x = 2 + \\varepsilon x^{3}.", explanation: "The term \\( \\varepsilon x^{3} \\) is \\( O(\\varepsilon) \\) for an \\( O(1) \\) root, so at leading order it is negligible." },
        { stepNumber: 2, description: "Drop the small term.", workingLatex: "x_{0} = 2.", explanation: "Balancing the two \\( O(1) \\) terms gives the leading root directly; this is a regular perturbation, since \\( \\varepsilon = 0 \\) does not change the count of \\( O(1) \\) roots near \\( x = 2 \\)." },
      ],
      finalAnswer: "\\( x \\sim 2 \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am9c-004",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "As \\( t \\to \\infty \\), determine the leading-order behaviour of the solution \\( x(t) \\) of \\( x + \\ln x = t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["transcendental equation", "dominant balance", "large parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Guess the dominant term.", workingLatex: "x + \\ln x = t.", explanation: "As \\( t \\to \\infty \\) we expect \\( x \\to \\infty \\). Of the two left-hand terms, \\( x \\) grows far faster than \\( \\ln x \\), so \\( x \\) must carry the balance against \\( t \\)." },
        { stepNumber: 2, description: "Balance the dominant terms.", workingLatex: "x \\approx t.", explanation: "Neglecting \\( \\ln x \\) relative to \\( x \\) gives the leading balance \\( x \\sim t \\)." },
        { stepNumber: 3, description: "Check consistency.", workingLatex: "\\frac{\\ln x}{x} \\sim \\frac{\\ln t}{t} \\to 0.", explanation: "The neglected term is asymptotically smaller than the retained ones, so the balance is self-consistent." },
      ],
      finalAnswer: "\\( x \\sim t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t",
    },
  },
  {
    id: "am9c-005",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order approximation, as \\( \\varepsilon \\to 0^{+} \\), to the small root of \\( x^{3} - x + \\varepsilon = 0 \\) (the root near \\( x = 0 \\)).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["dominant balance", "regular root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Look for the balance near the origin.", workingLatex: "x^{3} - x + \\varepsilon = 0.", explanation: "Near \\( x = 0 \\) the cubic term \\( x^{3} \\) is much smaller than the linear term \\( x \\), so the dominant balance is between \\( -x \\) and \\( +\\varepsilon \\)." },
        { stepNumber: 2, description: "Balance the two dominant terms.", workingLatex: "-x + \\varepsilon \\approx 0 \\;\\Longrightarrow\\; x_{0} = \\varepsilon.", explanation: "This gives a small root proportional to \\( \\varepsilon \\)." },
        { stepNumber: 3, description: "Confirm the discarded term is subdominant.", workingLatex: "x^{3} \\sim \\varepsilon^{3} \\ll \\varepsilon.", explanation: "The cubic term is \\( O(\\varepsilon^{3}) \\), negligible against the \\( O(\\varepsilon) \\) terms, so the balance is consistent." },
      ],
      finalAnswer: "\\( x \\sim \\varepsilon \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "eps",
    },
  },
  {
    id: "am9c-006",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The equation \\( \\varepsilon x^{2} - x + 1 = 0 \\) has a regular root near \\( x = 1 \\) and a singular root. Using the rescaling \\( x = X/\\varepsilon \\), find the leading-order behaviour of the singular root as \\( \\varepsilon \\to 0^{+} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["rescaling", "singular root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the rescaling.", workingLatex: "\\varepsilon \\left( \\frac{X}{\\varepsilon} \\right)^{2} - \\frac{X}{\\varepsilon} + 1 = 0 \\;\\Longrightarrow\\; \\frac{X^{2} - X}{\\varepsilon} + 1 = 0.", explanation: "The substitution \\( x = X/\\varepsilon \\) is chosen so that the highest-degree term is no longer suppressed by \\( \\varepsilon \\)." },
        { stepNumber: 2, description: "Multiply through by \\( \\varepsilon \\).", workingLatex: "X^{2} - X + \\varepsilon = 0.", explanation: "Now \\( X^{2} \\) and \\( -X \\) are the two dominant \\( O(1) \\) terms." },
        { stepNumber: 3, description: "Take the leading balance.", workingLatex: "X^{2} - X \\approx 0 \\;\\Longrightarrow\\; X_{0} = 1, \\qquad x \\sim \\frac{1}{\\varepsilon}.", explanation: "Discarding \\( X = 0 \\) (the regular root) leaves \\( X = 1 \\); unscaling gives a singular root of size \\( 1/\\varepsilon \\)." },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{1}{\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1/eps",
    },
  },

  // ───────────────────────── STANDARD (12) ─────────────────────────
  {
    id: "am9c-007",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 07",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms in the asymptotic expansion, as \\( \\varepsilon \\to 0^{+} \\), of the regular root of \\( \\varepsilon x^{2} + x - 1 = 0 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["regular perturbation", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit a regular expansion.", workingLatex: "x = x_{0} + \\varepsilon x_{1} + O(\\varepsilon^{2}).", explanation: "The regular root is a smooth perturbation of the reduced root, so it admits a power series in \\( \\varepsilon \\)." },
        { stepNumber: 2, description: "Substitute into the equation.", workingLatex: "\\varepsilon (x_{0} + \\varepsilon x_{1})^{2} + (x_{0} + \\varepsilon x_{1}) - 1 = 0.", explanation: "We now collect terms order by order in \\( \\varepsilon \\)." },
        { stepNumber: 3, description: "Collect the \\( O(1) \\) terms.", workingLatex: "x_{0} - 1 = 0 \\;\\Longrightarrow\\; x_{0} = 1.", explanation: "The leading order reproduces the reduced equation, fixing \\( x_{0} = 1 \\)." },
        { stepNumber: 4, description: "Collect the \\( O(\\varepsilon) \\) terms.", workingLatex: "x_{0}^{2} + x_{1} = 0 \\;\\Longrightarrow\\; x_{1} = -x_{0}^{2} = -1.", explanation: "The \\( \\varepsilon x_{0}^{2} \\) contribution from the quadratic term enters here and must be cancelled by \\( x_{1} \\)." },
        { stepNumber: 5, description: "Assemble the expansion.", workingLatex: "x \\sim 1 - \\varepsilon.", explanation: "Numerical check at \\( \\varepsilon = 10^{-3} \\): exact regular root \\( 0.999002 \\) versus \\( 1 - \\varepsilon = 0.999 \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\varepsilon \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1 - eps",
    },
  },
  {
    id: "am9c-008",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 08",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), of the singular root of \\( \\varepsilon x^{2} + x - 1 = 0 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["rescaling", "singular root", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescale to capture the large root.", workingLatex: "x = \\frac{X}{\\varepsilon} \\;\\Longrightarrow\\; X^{2} + X - \\varepsilon = 0.", explanation: "Substituting and multiplying by \\( \\varepsilon \\) demotes the \\( -1 \\) to a small \\( -\\varepsilon \\) correction." },
        { stepNumber: 2, description: "Expand \\( X \\) in powers of \\( \\varepsilon \\).", workingLatex: "X = X_{0} + \\varepsilon X_{1} + O(\\varepsilon^{2}).", explanation: "The rescaled equation is itself a regular perturbation problem in \\( X \\)." },
        { stepNumber: 3, description: "Leading order.", workingLatex: "X_{0}^{2} + X_{0} = 0 \\;\\Longrightarrow\\; X_{0} = -1.", explanation: "We take the non-trivial root \\( X_{0} = -1 \\); the root \\( X_{0} = 0 \\) corresponds to the regular root." },
        { stepNumber: 4, description: "Order \\( \\varepsilon \\).", workingLatex: "2 X_{0} X_{1} + X_{1} - 1 = 0 \\;\\Longrightarrow\\; X_{1}(2X_{0}+1) = 1 \\;\\Longrightarrow\\; X_{1} = -1.", explanation: "With \\( X_{0} = -1 \\) we have \\( 2X_{0}+1 = -1 \\), so \\( X_{1} = -1 \\)." },
        { stepNumber: 5, description: "Unscale.", workingLatex: "x = \\frac{X_{0} + \\varepsilon X_{1}}{\\varepsilon} \\sim -\\frac{1}{\\varepsilon} - 1.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact singular root \\( -100.9902 \\) versus \\( -1/\\varepsilon - 1 = -101 \\)." },
      ],
      finalAnswer: "\\( x \\sim -\\dfrac{1}{\\varepsilon} - 1 \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "-1/eps - 1",
    },
  },
  {
    id: "am9c-009",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 09",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), in the expansion of the root of \\( x = 2 + \\varepsilon x^{3} \\) near \\( x = 2 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["regular perturbation", "iteration", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit the expansion.", workingLatex: "x = x_{0} + \\varepsilon x_{1} + O(\\varepsilon^{2}).", explanation: "The root is a regular perturbation of \\( x_{0} = 2 \\)." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x_{0} = 2.", explanation: "Dropping the \\( O(\\varepsilon) \\) term gives the reduced balance." },
        { stepNumber: 3, description: "Substitute and expand the cubic.", workingLatex: "x_{0} + \\varepsilon x_{1} = 2 + \\varepsilon (x_{0} + \\varepsilon x_{1})^{3} = 2 + \\varepsilon x_{0}^{3} + O(\\varepsilon^{2}).", explanation: "Only the leading part of the cube contributes at \\( O(\\varepsilon) \\)." },
        { stepNumber: 4, description: "Order \\( \\varepsilon \\).", workingLatex: "x_{1} = x_{0}^{3} = 8.", explanation: "Matching the \\( O(\\varepsilon) \\) coefficients gives \\( x_{1} = 8 \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x \\sim 2 + 8\\varepsilon.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact root \\( 2.09149 \\) versus \\( 2 + 8\\varepsilon = 2.08 \\), consistent to leading correction." },
      ],
      finalAnswer: "\\( x \\sim 2 + 8\\varepsilon \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "2 + 8*eps",
    },
  },
  {
    id: "am9c-010",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 10",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), in the expansion of the root of \\( x = 1 + \\varepsilon \\sin x \\) near \\( x = 1 \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["regular perturbation", "transcendental", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit the expansion.", workingLatex: "x = x_{0} + \\varepsilon x_{1} + O(\\varepsilon^{2}).", explanation: "The presence of the small \\( \\varepsilon \\sin x \\) term suggests a regular perturbation about the reduced root." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x_{0} = 1.", explanation: "Setting \\( \\varepsilon = 0 \\) gives \\( x_{0} = 1 \\)." },
        { stepNumber: 3, description: "Expand the nonlinearity.", workingLatex: "\\sin x = \\sin x_{0} + \\varepsilon x_{1} \\cos x_{0} + \\cdots", explanation: "Taylor-expand \\( \\sin x \\) about \\( x_{0} \\); only \\( \\sin x_{0} \\) is needed at first order." },
        { stepNumber: 4, description: "Order \\( \\varepsilon \\).", workingLatex: "x_{1} = \\sin x_{0} = \\sin 1.", explanation: "Matching the \\( O(\\varepsilon) \\) terms gives the first correction." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x \\sim 1 + \\varepsilon \\sin 1.", explanation: "Numerical check at \\( \\varepsilon = 0.05 \\): exact root \\( 1.043201 \\) versus \\( 1 + 0.05\\sin 1 = 1.042074 \\); the remaining gap is \\( O(\\varepsilon^{2}) \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 + \\varepsilon \\sin 1 \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1 + eps*sin(1)",
    },
  },
  {
    id: "am9c-011",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 11",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "As \\( t \\to \\infty \\), find the first two terms in the asymptotic expansion of the solution \\( x(t) \\) of \\( x + \\ln x = t \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["transcendental equation", "iteration", "large parameter"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "As shown by dominant balance, \\( x \\) dominates \\( \\ln x \\), so \\( x \\sim t \\) at leading order." },
        { stepNumber: 2, description: "Iterate by isolating the dominant term.", workingLatex: "x = t - \\ln x.", explanation: "Rearranging puts the largest term \\( x \\) alone and the smaller correction \\( -\\ln x \\) on the right, ready for substitution." },
        { stepNumber: 3, description: "Substitute the leading estimate.", workingLatex: "x = t - \\ln x \\approx t - \\ln t.", explanation: "Using \\( x \\sim t \\) inside the slowly-varying \\( \\ln \\) generates the next term; the error in \\( \\ln x \\) is \\( \\ln(1 + O(\\ln t / t)) = o(1) \\)." },
        { stepNumber: 4, description: "State the expansion.", workingLatex: "x \\sim t - \\ln t.", explanation: "Numerical check at \\( t = 100 \\): exact root \\( 96.39 \\) versus \\( t - \\ln t = 95.39 \\); the \\( O(1) \\) gap is the next, \\( (\\ln t)/t \\)-order term." },
      ],
      finalAnswer: "\\( x \\sim t - \\ln t \\) as \\( t \\to \\infty \\).",
      canonicalAnswer: "t - log(t)",
    },
  },
  {
    id: "am9c-012",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 12",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), in the expansion of the root of \\( \\varepsilon x^{2} + 2x - 1 = 0 \\) that stays bounded.",
    marks: 3,
    yearCreated: 2026,
    tags: ["regular perturbation", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit the expansion.", workingLatex: "x = x_{0} + \\varepsilon x_{1} + O(\\varepsilon^{2}).", explanation: "The bounded root is a regular perturbation of the linear-equation root." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "2 x_{0} - 1 = 0 \\;\\Longrightarrow\\; x_{0} = \\tfrac{1}{2}.", explanation: "Discarding \\( \\varepsilon x^{2} \\) leaves the dominant balance \\( 2x = 1 \\)." },
        { stepNumber: 3, description: "Order \\( \\varepsilon \\).", workingLatex: "x_{0}^{2} + 2 x_{1} = 0 \\;\\Longrightarrow\\; x_{1} = -\\frac{x_{0}^{2}}{2} = -\\frac{1}{8}.", explanation: "The quadratic term feeds \\( x_{0}^{2} \\) into the \\( O(\\varepsilon) \\) balance." },
        { stepNumber: 4, description: "Assemble.", workingLatex: "x \\sim \\frac{1}{2} - \\frac{\\varepsilon}{8}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact root \\( 0.498756 \\) versus \\( 1/2 - \\varepsilon/8 = 0.49875 \\)." },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{1}{2} - \\dfrac{\\varepsilon}{8} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1/2 - eps/8",
    },
  },
  {
    id: "am9c-013",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 13",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "The cubic \\( x^{3} - x + \\varepsilon = 0 \\) has three real roots for small \\( \\varepsilon > 0 \\). Find the first two terms of each of the three roots as \\( \\varepsilon \\to 0^{+} \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["dominant balance", "regular perturbation", "multiple roots"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduced equation.", workingLatex: "x^{3} - x = 0 \\;\\Longrightarrow\\; x_{0} \\in \\{0, 1, -1\\}.", explanation: "Setting \\( \\varepsilon = 0 \\) gives three simple roots; each perturbs regularly because the cubic stays degree three." },
        { stepNumber: 2, description: "General first correction.", workingLatex: "x = x_{0} + \\varepsilon x_{1}: \\quad (3 x_{0}^{2} - 1) x_{1} + 1 = 0 \\;\\Longrightarrow\\; x_{1} = \\frac{-1}{3 x_{0}^{2} - 1}.", explanation: "Linearising about each simple root, the derivative \\( 3x^{2} - 1 \\) is non-zero there, so the implicit function theorem guarantees a regular correction." },
        { stepNumber: 3, description: "Root near \\( 0 \\).", workingLatex: "x_{0} = 0: \\quad x_{1} = \\frac{-1}{-1} = 1 \\;\\Longrightarrow\\; x \\sim \\varepsilon.", explanation: "Here the dominant balance is \\( -x + \\varepsilon = 0 \\)." },
        { stepNumber: 4, description: "Roots near \\( \\pm 1 \\).", workingLatex: "x_{0} = \\pm 1: \\quad x_{1} = \\frac{-1}{2} \\;\\Longrightarrow\\; x \\sim \\pm 1 - \\frac{\\varepsilon}{2}.", explanation: "For both \\( x_{0} = 1 \\) and \\( x_{0} = -1 \\), \\( 3x_{0}^{2} - 1 = 2 \\), giving the same correction \\( -\\varepsilon/2 \\)." },
        { stepNumber: 5, description: "State all three.", workingLatex: "x \\sim \\varepsilon, \\qquad x \\sim 1 - \\frac{\\varepsilon}{2}, \\qquad x \\sim -1 - \\frac{\\varepsilon}{2}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): roots \\( 0.010001,\\, 0.994962,\\, -1.004963 \\) match \\( \\varepsilon,\\, 1-\\varepsilon/2,\\, -1-\\varepsilon/2 \\)." },
      ],
      finalAnswer: "\\( x \\sim \\varepsilon, \\quad x \\sim 1 - \\tfrac{\\varepsilon}{2}, \\quad x \\sim -1 - \\tfrac{\\varepsilon}{2} \\).",
    },
  },
  {
    id: "am9c-014",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 14",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading-order behaviour, as \\( \\varepsilon \\to 0^{+} \\), of the two large roots of \\( \\varepsilon x^{3} + x - 1 = 0 \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["rescaling", "distinguished limit", "singular roots"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Count roots and identify the lost ones.", workingLatex: "\\varepsilon x^{3} + x - 1 = 0.", explanation: "The reduced equation \\( x - 1 = 0 \\) is linear, so two of the three roots are lost as \\( \\varepsilon \\to 0 \\) and must be large." },
        { stepNumber: 2, description: "Seek the distinguished scaling.", workingLatex: "x = \\delta(\\varepsilon)\\, X, \\quad X = O(1): \\qquad \\varepsilon \\delta^{3} X^{3} + \\delta X - 1 = 0.", explanation: "We choose \\( \\delta \\) so that the cubic term re-enters the dominant balance." },
        { stepNumber: 3, description: "Balance the cubic against the linear term.", workingLatex: "\\varepsilon \\delta^{3} = \\delta \\;\\Longrightarrow\\; \\delta = \\varepsilon^{-1/2}.", explanation: "Setting the two dominant terms to the same order fixes the distinguished limit \\( \\delta = \\varepsilon^{-1/2} \\); the \\( -1 \\) is then \\( O(1) \\) and subdominant to terms of size \\( \\varepsilon^{-1/2} \\)." },
        { stepNumber: 4, description: "Leading balance in \\( X \\).", workingLatex: "X^{3} + X \\approx 0 \\;\\Longrightarrow\\; X^{2} = -1 \\;\\Longrightarrow\\; X = \\pm i.", explanation: "Dividing by \\( \\delta = \\varepsilon^{-1/2} \\), the leading balance is \\( X^{3} + X = 0 \\); discarding \\( X = 0 \\) gives the complex pair." },
        { stepNumber: 5, description: "Unscale.", workingLatex: "x \\sim \\pm \\frac{i}{\\sqrt{\\varepsilon}}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-3} \\): the two large roots are \\( -0.4995 \\pm 31.63 i \\), and \\( 1/\\sqrt{\\varepsilon} = 31.62 \\) matches the imaginary part." },
      ],
      finalAnswer: "\\( x \\sim \\pm \\dfrac{i}{\\sqrt{\\varepsilon}} \\) as \\( \\varepsilon \\to 0 \\).",
    },
  },
  {
    id: "am9c-015",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 15",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "As \\( \\varepsilon \\to 0^{+} \\), find the leading-order behaviour of the (large, positive) solution of the transcendental equation \\( x\\, e^{x} = \\dfrac{1}{\\varepsilon} \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["transcendental equation", "dominant balance", "logarithmic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "\\ln x + x = \\ln \\frac{1}{\\varepsilon} = L, \\qquad L := \\ln(1/\\varepsilon).", explanation: "Logarithms convert the product into a sum and reveal that \\( x \\) is comparable to the large quantity \\( L \\)." },
        { stepNumber: 2, description: "Dominant balance.", workingLatex: "x \\sim L.", explanation: "Since \\( x \\gg \\ln x \\) for large \\( x \\), the leading balance is \\( x \\sim L \\)." },
        { stepNumber: 3, description: "First correction by iteration.", workingLatex: "x = L - \\ln x \\approx L - \\ln L.", explanation: "Isolating the dominant \\( x \\) and substituting \\( x \\sim L \\) into the slowly-varying \\( \\ln x \\) gives the next term." },
        { stepNumber: 4, description: "State the result.", workingLatex: "x \\sim L - \\ln L = \\ln\\frac{1}{\\varepsilon} - \\ln\\ln\\frac{1}{\\varepsilon}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-3} \\): exact root \\( 5.2496 \\) versus \\( L - \\ln L = 5.249 \\) (with \\( L = 6.9078 \\))." },
      ],
      finalAnswer: "\\( x \\sim \\ln\\dfrac{1}{\\varepsilon} - \\ln\\ln\\dfrac{1}{\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\).",
    },
  },
  {
    id: "am9c-016",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 16",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading-order location of the large positive roots of \\( \\tan x = \\dfrac{1}{x} \\), and the first correction, as the root index \\( n \\to \\infty \\).",
    marks: 4,
    yearCreated: 2026,
    tags: ["transcendental equation", "large roots", "perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the roots to leading order.", workingLatex: "\\tan x = \\frac{1}{x} \\to 0 \\;\\Longrightarrow\\; x \\approx n\\pi.", explanation: "For large \\( x \\) the right side is small, so the root sits just past a zero of \\( \\tan \\), i.e. near \\( x = n\\pi \\)." },
        { stepNumber: 2, description: "Set up a local correction.", workingLatex: "x = n\\pi + \\xi, \\qquad \\xi \\ll 1.", explanation: "Write the root as the leading value plus a small displacement \\( \\xi \\)." },
        { stepNumber: 3, description: "Expand the tangent.", workingLatex: "\\tan(n\\pi + \\xi) = \\tan \\xi \\approx \\xi.", explanation: "Tangent has period \\( \\pi \\) and \\( \\tan\\xi \\approx \\xi \\) for small \\( \\xi \\)." },
        { stepNumber: 4, description: "Balance against the right-hand side.", workingLatex: "\\xi \\approx \\frac{1}{x} \\approx \\frac{1}{n\\pi}.", explanation: "Replacing \\( x \\) by its leading value \\( n\\pi \\) in the small right-hand side fixes \\( \\xi \\)." },
        { stepNumber: 5, description: "State the expansion.", workingLatex: "x \\sim n\\pi + \\frac{1}{n\\pi}.", explanation: "Numerical check at \\( n = 5 \\): exact root \\( 15.7713 \\) versus \\( 5\\pi + 1/(5\\pi) = 15.7716 \\)." },
      ],
      finalAnswer: "\\( x \\sim n\\pi + \\dfrac{1}{n\\pi} \\) as \\( n \\to \\infty \\).",
    },
  },
  {
    id: "am9c-017",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 17",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), of the small positive root of \\( x = \\varepsilon\\, e^{x} \\).",
    marks: 3,
    yearCreated: 2026,
    tags: ["transcendental equation", "iteration", "regular root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the small root.", workingLatex: "x = \\varepsilon\\, e^{x}.", explanation: "For small \\( \\varepsilon \\) one root is small (the other is large). For the small root \\( e^{x} \\approx 1 \\), so \\( x \\approx \\varepsilon \\)." },
        { stepNumber: 2, description: "Leading order.", workingLatex: "x_{0} = \\varepsilon.", explanation: "The dominant balance is \\( x \\approx \\varepsilon \\cdot 1 \\)." },
        { stepNumber: 3, description: "Iterate.", workingLatex: "x = \\varepsilon\\, e^{x} = \\varepsilon \\left( 1 + x + \\cdots \\right) \\approx \\varepsilon(1 + \\varepsilon).", explanation: "Substituting \\( x \\approx \\varepsilon \\) into the exponential and expanding gives the first correction." },
        { stepNumber: 4, description: "State the expansion.", workingLatex: "x \\sim \\varepsilon + \\varepsilon^{2}.", explanation: "Numerical check at \\( \\varepsilon = 0.05 \\): exact small root \\( 0.052773 \\) versus \\( \\varepsilon + \\varepsilon^{2} = 0.0525 \\)." },
      ],
      finalAnswer: "\\( x \\sim \\varepsilon + \\varepsilon^{2} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "eps + eps^2",
    },
  },
  {
    id: "am9c-018",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 18",
    difficulty: "Standard",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading-order location of the large positive roots of \\( \\cos x = \\varepsilon x \\) (with \\( 0 < \\varepsilon \\ll 1 \\)) near \\( x = (n + \\tfrac12)\\pi \\), and the first correction.",
    marks: 4,
    yearCreated: 2026,
    tags: ["transcendental equation", "large roots", "perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the leading roots.", workingLatex: "\\cos x = \\varepsilon x.", explanation: "For the right-hand side to be small the cosine must be small, so the root lies near a zero of \\( \\cos \\), i.e. \\( x \\approx (n+\\tfrac12)\\pi \\)." },
        { stepNumber: 2, description: "Local displacement.", workingLatex: "x = \\left(n+\\tfrac12\\right)\\pi + \\xi, \\qquad \\xi \\ll 1.", explanation: "Write the root as the leading value plus a small \\( \\xi \\)." },
        { stepNumber: 3, description: "Expand the cosine.", workingLatex: "\\cos\\!\\left[(n+\\tfrac12)\\pi + \\xi\\right] = \\mp \\sin \\xi \\approx \\mp\\, \\xi.", explanation: "At an odd multiple of \\( \\pi/2 \\), cosine vanishes and its local slope is \\( \\pm 1 \\); take the branch giving a real small root." },
        { stepNumber: 4, description: "Balance.", workingLatex: "\\mp \\xi \\approx \\varepsilon\\left(n+\\tfrac12\\right)\\pi \\;\\Longrightarrow\\; |\\xi| \\approx \\varepsilon\\left(n+\\tfrac12\\right)\\pi.", explanation: "Using the leading value of \\( x \\) in the slowly-varying right-hand side fixes the magnitude of \\( \\xi \\)." },
        { stepNumber: 5, description: "State the result.", workingLatex: "x \\sim \\left(n+\\tfrac12\\right)\\pi - \\varepsilon\\left(n+\\tfrac12\\right)\\pi = \\left(n+\\tfrac12\\right)\\pi\\,(1 - \\varepsilon).", explanation: "Numerical check at \\( n=4,\\ \\varepsilon=10^{-2} \\): exact root \\( 13.9967 \\) versus \\( (4.5)\\pi(1-0.01) = 13.9958 \\)." },
      ],
      finalAnswer: "\\( x \\sim \\left(n+\\tfrac12\\right)\\pi\\,(1 - \\varepsilon) \\) as \\( n \\to \\infty \\).",
    },
  },

  // ───────────────────────── CHALLENGE (12) ─────────────────────────
  {
    id: "am9c-019",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 19",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Consider \\( x + x^{1/2} + 2\\ln x = t + \\ln t \\). Find the first four terms in the asymptotic expansion of \\( x(t) \\) as \\( t \\to \\infty \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["transcendental equation", "dominant balance", "iteration", "exam sheet 3"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "The fastest-growing term on each side is \\( x \\) and \\( t \\); \\( x^{1/2} \\), \\( \\ln x \\), \\( \\ln t \\) are all subdominant, giving \\( x \\sim t \\)." },
        { stepNumber: 2, description: "Isolate \\( x \\) for iteration.", workingLatex: "x = t + \\ln t - x^{1/2} - 2\\ln x.", explanation: "Move every subdominant term to the right; each will be evaluated using the previous estimate of \\( x \\)." },
        { stepNumber: 3, description: "Second term from \\( -x^{1/2} \\).", workingLatex: "x = t + \\ln t - t^{1/2} - 2\\ln t + \\cdots = t - t^{1/2} + \\cdots", explanation: "Substitute \\( x \\sim t \\): the largest correction is \\( -x^{1/2} \\sim -t^{1/2} \\), dominating the logarithms." },
        { stepNumber: 4, description: "Collect the logarithmic terms.", workingLatex: "\\ln t - 2\\ln x \\sim \\ln t - 2\\ln t = -\\ln t.", explanation: "With \\( x \\sim t \\), \\( 2\\ln x \\sim 2\\ln t \\); combined with the \\( +\\ln t \\) on the right this leaves \\( -\\ln t \\) as the third-order term." },
        { stepNumber: 5, description: "Three-term estimate.", workingLatex: "x \\sim t - t^{1/2} - \\ln t.", explanation: "So far \\( x = t - t^{1/2} - \\ln t + c + \\cdots \\) for a constant \\( c \\) to be found." },
        { stepNumber: 6, description: "Determine the constant via \\( x^{1/2} \\).", workingLatex: "x^{1/2} = t^{1/2}\\left(1 - t^{-1/2} - \\tfrac{\\ln t}{t} + \\cdots\\right)^{1/2} = t^{1/2} - \\tfrac12 + \\cdots", explanation: "Expand \\( x^{1/2} = (t - t^{1/2} - \\cdots)^{1/2} \\); the \\( -t^{1/2}/t^{1/2} \\) piece contributes a constant \\( -\\tfrac12 \\) under the half-power." },
        { stepNumber: 7, description: "Balance the constant terms.", workingLatex: "-x^{1/2} = -t^{1/2} + \\tfrac12 + \\cdots \\;\\Longrightarrow\\; c = \\tfrac12.", explanation: "The \\( +\\tfrac12 \\) emerging from \\( -x^{1/2} \\) is the only \\( O(1) \\) contribution, so the constant term is \\( \\tfrac12 \\)." },
        { stepNumber: 8, description: "State the four-term expansion.", workingLatex: "x \\sim t - t^{1/2} - \\ln t + \\frac{1}{2}.", explanation: "Numerical check at \\( t = 10^{8} \\): exact root \\( 99989982.08 \\); the three-term form \\( t - t^{1/2} - \\ln t = 99989981.58 \\) leaves a residual \\( \\approx 0.50 \\), confirming \\( c = \\tfrac12 \\)." },
      ],
      finalAnswer: "\\( x \\sim t - t^{1/2} - \\ln t + \\dfrac{1}{2} \\) as \\( t \\to \\infty \\).",
    },
  },
  {
    id: "am9c-020",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 20",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first three terms, as \\( \\varepsilon \\to 0^{+} \\), of the regular root of \\( \\varepsilon x^{2} + x - 1 = 0 \\), and verify the third term against the exact quadratic formula.",
    marks: 5,
    yearCreated: 2026,
    tags: ["regular perturbation", "higher correction", "verification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Posit a three-term expansion.", workingLatex: "x = x_{0} + \\varepsilon x_{1} + \\varepsilon^{2} x_{2} + O(\\varepsilon^{3}).", explanation: "Carry one more order than before to capture \\( x_{2} \\)." },
        { stepNumber: 2, description: "Substitute and group by order.", workingLatex: "\\varepsilon(x_{0} + \\varepsilon x_{1} + \\cdots)^{2} + (x_{0} + \\varepsilon x_{1} + \\varepsilon^{2}x_{2}) - 1 = 0.", explanation: "Expand the square keeping terms to \\( O(\\varepsilon^{2}) \\): \\( (x_{0}+\\varepsilon x_{1})^{2} = x_{0}^{2} + 2\\varepsilon x_{0}x_{1} + \\cdots \\)." },
        { stepNumber: 3, description: "Orders \\( O(1) \\) and \\( O(\\varepsilon) \\).", workingLatex: "x_{0} = 1, \\qquad x_{0}^{2} + x_{1} = 0 \\;\\Rightarrow\\; x_{1} = -1.", explanation: "These reproduce the earlier two-term result." },
        { stepNumber: 4, description: "Order \\( \\varepsilon^{2} \\).", workingLatex: "2 x_{0} x_{1} + x_{2} = 0 \\;\\Longrightarrow\\; x_{2} = -2 x_{0} x_{1} = 2.", explanation: "The \\( \\varepsilon \\cdot 2 x_{0} x_{1} \\) cross-term sits at \\( O(\\varepsilon^{2}) \\) and must be cancelled by \\( x_{2} \\)." },
        { stepNumber: 5, description: "Compare with the exact root.", workingLatex: "x = \\frac{-1 + \\sqrt{1 + 4\\varepsilon}}{2\\varepsilon} = \\frac{-1 + (1 + 2\\varepsilon - 2\\varepsilon^{2} + \\cdots)}{2\\varepsilon} = 1 - \\varepsilon + 2\\varepsilon^{2} - \\cdots", explanation: "Expanding \\( \\sqrt{1+4\\varepsilon} = 1 + 2\\varepsilon - 2\\varepsilon^{2} + 4\\varepsilon^{3} - \\cdots \\) and dividing by \\( 2\\varepsilon \\) confirms \\( x_{2} = 2 \\)." },
        { stepNumber: 6, description: "State the expansion.", workingLatex: "x \\sim 1 - \\varepsilon + 2\\varepsilon^{2}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact \\( 0.990195 \\) versus \\( 1 - \\varepsilon + 2\\varepsilon^{2} = 0.9902 \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 - \\varepsilon + 2\\varepsilon^{2} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1 - eps + 2*eps^2",
    },
  },
  {
    id: "am9c-021",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 21",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "The quartic \\( \\varepsilon x^{4} + x^{3} - 1 = 0 \\) has three \\( O(1) \\) roots and one large root as \\( \\varepsilon \\to 0^{+} \\). Find the first two terms of the large root.",
    marks: 5,
    yearCreated: 2026,
    tags: ["rescaling", "distinguished limit", "singular root"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Count the lost roots.", workingLatex: "\\varepsilon x^{4} + x^{3} - 1 = 0.", explanation: "The reduced cubic \\( x^{3} - 1 = 0 \\) has three roots (one real, two complex), all \\( O(1) \\). Since the full equation is quartic, exactly one root is lost to infinity as \\( \\varepsilon \\to 0 \\)." },
        { stepNumber: 2, description: "Rescale \\( x = \\delta X \\).", workingLatex: "\\varepsilon \\delta^{4} X^{4} + \\delta^{3} X^{3} - 1 = 0.", explanation: "We look for the dominant balance that re-promotes the quartic term for the large root." },
        { stepNumber: 3, description: "Balance quartic against cubic.", workingLatex: "\\varepsilon \\delta^{4} = \\delta^{3} \\;\\Longrightarrow\\; \\delta = \\frac{1}{\\varepsilon}.", explanation: "Equating the two highest-degree terms gives the distinguished limit \\( \\delta = 1/\\varepsilon \\); the \\( -1 \\) is then negligible at leading order." },
        { stepNumber: 4, description: "Rescaled equation.", workingLatex: "x = \\frac{X}{\\varepsilon}: \\quad \\frac{X^{4}}{\\varepsilon^{3}} + \\frac{X^{3}}{\\varepsilon^{3}} - 1 = 0 \\;\\Longrightarrow\\; X^{4} + X^{3} - \\varepsilon^{3} = 0.", explanation: "Multiplying by \\( \\varepsilon^{3} \\) shows \\( X^{4} \\) and \\( X^{3} \\) balance, with the \\( -1 \\) demoted to \\( -\\varepsilon^{3} \\)." },
        { stepNumber: 5, description: "Leading balance in \\( X \\).", workingLatex: "X^{4} + X^{3} \\approx 0 \\;\\Longrightarrow\\; X^{3}(X + 1) = 0 \\;\\Longrightarrow\\; X_{0} = -1.", explanation: "The triple root \\( X = 0 \\) returns the \\( O(1) \\) roots; the new large root is \\( X_{0} = -1 \\)." },
        { stepNumber: 6, description: "First correction.", workingLatex: "X = -1 + \\eta: \\ (4X_{0}^{3}+3X_{0}^{2})\\eta - \\varepsilon^{3} = 0 \\;\\Rightarrow\\; (-1)\\eta = \\varepsilon^{3} \\;\\Rightarrow\\; \\eta = -\\varepsilon^{3}.", explanation: "Linearising about \\( X_{0} = -1 \\): the derivative \\( 4X^{3}+3X^{2} = -1 \\) there, so the correction \\( \\eta = -\\varepsilon^{3} \\) is tiny." },
        { stepNumber: 7, description: "Unscale.", workingLatex: "x = \\frac{-1 - \\varepsilon^{3}}{\\varepsilon} = -\\frac{1}{\\varepsilon} - \\varepsilon^{2}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): the real large root is \\( -100.0001 \\), matching \\( -1/\\varepsilon - \\varepsilon^{2} = -100.0001 \\)." },
      ],
      finalAnswer: "\\( x \\sim -\\dfrac{1}{\\varepsilon} - \\varepsilon^{2} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "-1/eps - eps^2",
    },
  },
  {
    id: "am9c-022",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 22",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "As \\( \\varepsilon \\to 0^{+} \\), find the first three terms in the asymptotic expansion of the large positive root of \\( x^{2} e^{-x} = \\varepsilon \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["transcendental equation", "iteration", "logarithmic terms"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "2\\ln x - x = \\ln \\varepsilon \\;\\Longrightarrow\\; x - 2\\ln x = \\ln\\frac{1}{\\varepsilon} = L.", explanation: "Define \\( L = \\ln(1/\\varepsilon) \\to \\infty \\). Logs linearise the product and expose the dominant term \\( x \\)." },
        { stepNumber: 2, description: "Leading balance.", workingLatex: "x \\sim L.", explanation: "Since \\( x \\gg \\ln x \\), the dominant balance is \\( x \\sim L \\)." },
        { stepNumber: 3, description: "Isolate \\( x \\) for iteration.", workingLatex: "x = L + 2\\ln x.", explanation: "Put the dominant \\( x \\) on the left and treat \\( 2\\ln x \\) as a slowly-varying correction." },
        { stepNumber: 4, description: "First correction.", workingLatex: "x \\approx L + 2\\ln L.", explanation: "Substituting \\( x \\sim L \\) into \\( 2\\ln x \\) gives the second term." },
        { stepNumber: 5, description: "Second correction.", workingLatex: "x = L + 2\\ln\\!\\left(L + 2\\ln L\\right) = L + 2\\ln L + 2\\ln\\!\\left(1 + \\frac{2\\ln L}{L}\\right) \\approx L + 2\\ln L + \\frac{4\\ln L}{L}.", explanation: "Expand the logarithm: \\( \\ln(1 + 2\\ln L/L) \\approx 2\\ln L/L \\), giving the third term \\( 4\\ln L / L \\)." },
        { stepNumber: 6, description: "State the expansion.", workingLatex: "x \\sim L + 2\\ln L + \\frac{4\\ln L}{L}, \\qquad L = \\ln\\frac{1}{\\varepsilon}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-4} \\) (\\(L = 9.2103\\)): exact root \\( 14.568 \\) versus \\( L + 2\\ln L + 4\\ln L/L = 9.210 + 4.441 + 0.964 = 14.615 \\); convergence is slow (logarithmic) but the terms decrease as predicted." },
      ],
      finalAnswer: "\\( x \\sim \\ln\\dfrac{1}{\\varepsilon} + 2\\ln\\ln\\dfrac{1}{\\varepsilon} + \\dfrac{4\\ln\\ln(1/\\varepsilon)}{\\ln(1/\\varepsilon)} \\).",
    },
  },
  {
    id: "am9c-023",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 23",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( \\varepsilon \\to 0^{+} \\), of the two roots of \\( \\varepsilon x^{2} + x - 1 = 0 \\) that arise from the singular balance, using the rescaling \\( x = X/\\varepsilon \\) and continuing one order beyond leading order. Hence state both the regular and singular roots to two terms.",
    marks: 6,
    yearCreated: 2026,
    tags: ["rescaling", "matching counts", "two-term expansions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rescaled equation.", workingLatex: "x = \\frac{X}{\\varepsilon}: \\qquad X^{2} + X - \\varepsilon = 0.", explanation: "This regularised equation has two roots in \\( X \\); one gives the regular root (\\( X = O(\\varepsilon) \\)) and one the singular root (\\( X = O(1) \\))." },
        { stepNumber: 2, description: "Small-\\( X \\) root recovers the regular root.", workingLatex: "X^{2} + X - \\varepsilon = 0,\\ \\ X \\ \\text{small} \\;\\Rightarrow\\; X \\approx \\varepsilon - \\varepsilon^{2} + \\cdots", explanation: "For the small root \\( X^{2} \\ll X \\), so \\( X \\approx \\varepsilon \\); one more iterate gives \\( X \\approx \\varepsilon(1 - \\varepsilon) \\). Then \\( x = X/\\varepsilon \\approx 1 - \\varepsilon \\), the regular root." },
        { stepNumber: 3, description: "Order-one root gives the singular root.", workingLatex: "X = X_{0} + \\varepsilon X_{1}: \\quad X_{0}^{2} + X_{0} = 0 \\;\\Rightarrow\\; X_{0} = -1.", explanation: "Discarding \\( X_{0} = 0 \\) (already used) leaves \\( X_{0} = -1 \\)." },
        { stepNumber: 4, description: "First correction to the singular root.", workingLatex: "(2 X_{0} + 1) X_{1} - 1 = 0 \\;\\Rightarrow\\; X_{1} = \\frac{1}{2X_{0}+1} = -1.", explanation: "With \\( X_{0} = -1 \\), \\( 2X_{0}+1 = -1 \\), so \\( X_{1} = -1 \\)." },
        { stepNumber: 5, description: "Unscale the singular root.", workingLatex: "x = \\frac{X_{0} + \\varepsilon X_{1}}{\\varepsilon} \\sim -\\frac{1}{\\varepsilon} - 1.", explanation: "The rescaling has unfolded the lost root and produced its correction in one calculation." },
        { stepNumber: 6, description: "Collect both roots.", workingLatex: "x_{\\text{reg}} \\sim 1 - \\varepsilon, \\qquad x_{\\text{sing}} \\sim -\\frac{1}{\\varepsilon} - 1.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact roots \\( 0.990195 \\) and \\( -100.9902 \\), matching \\( 1-\\varepsilon \\) and \\( -1/\\varepsilon - 1 \\)." },
      ],
      finalAnswer: "\\( x_{\\text{reg}} \\sim 1 - \\varepsilon, \\quad x_{\\text{sing}} \\sim -\\dfrac{1}{\\varepsilon} - 1 \\).",
    },
  },
  {
    id: "am9c-024",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 24",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "As \\( \\varepsilon \\to 0^{+} \\), find the first two terms of the large positive root of \\( e^{-x} = \\varepsilon x \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["transcendental equation", "logarithmic terms", "iteration"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take logarithms.", workingLatex: "-x = \\ln \\varepsilon + \\ln x \\;\\Longrightarrow\\; x + \\ln x = \\ln\\frac{1}{\\varepsilon} = L.", explanation: "Define \\( L = \\ln(1/\\varepsilon) \\). The large root corresponds to the regime where \\( e^{-x} \\) is exponentially small, balanced against \\( \\varepsilon x \\)." },
        { stepNumber: 2, description: "Leading balance.", workingLatex: "x \\sim L.", explanation: "\\( x \\gg \\ln x \\), so \\( x \\sim L \\) at leading order." },
        { stepNumber: 3, description: "Iterate.", workingLatex: "x = L - \\ln x \\approx L - \\ln L.", explanation: "Isolate the dominant \\( x \\) and substitute \\( x \\sim L \\) into the small \\( -\\ln x \\) term." },
        { stepNumber: 4, description: "State the result.", workingLatex: "x \\sim L - \\ln L = \\ln\\frac{1}{\\varepsilon} - \\ln\\ln\\frac{1}{\\varepsilon}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-5} \\) (\\( L = 11.5129 \\)): exact root \\( 9.2846 \\) versus \\( L - \\ln L = 11.513 - 2.444 = 9.069 \\); the gap is the next \\( (\\ln L)/L \\)-order term." },
      ],
      finalAnswer: "\\( x \\sim \\ln\\dfrac{1}{\\varepsilon} - \\ln\\ln\\dfrac{1}{\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\).",
    },
  },
  {
    id: "am9c-025",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 25",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "The equation \\( \\varepsilon x^{3} - x^{2} + 1 = 0 \\) has two \\( O(1) \\) roots and one large root as \\( \\varepsilon \\to 0^{+} \\). Find the first two terms of the large root.",
    marks: 6,
    yearCreated: 2026,
    tags: ["rescaling", "singular root", "correction term"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the lost root.", workingLatex: "\\varepsilon x^{3} - x^{2} + 1 = 0.", explanation: "The reduced quadratic \\( -x^{2} + 1 = 0 \\) gives \\( x = \\pm 1 \\); the third (cubic) root is lost and must be large." },
        { stepNumber: 2, description: "Rescale \\( x = \\delta X \\) and find the balance.", workingLatex: "\\varepsilon \\delta^{3} X^{3} - \\delta^{2} X^{2} + 1 = 0.", explanation: "Balance the cubic against the quadratic: \\( \\varepsilon \\delta^{3} = \\delta^{2} \\Rightarrow \\delta = 1/\\varepsilon \\)." },
        { stepNumber: 3, description: "Rescaled equation.", workingLatex: "x = \\frac{X}{\\varepsilon}: \\quad \\frac{X^{3}}{\\varepsilon^{2}} - \\frac{X^{2}}{\\varepsilon^{2}} + 1 = 0 \\;\\Longrightarrow\\; X^{3} - X^{2} + \\varepsilon^{2} = 0.", explanation: "Multiplying by \\( \\varepsilon^{2} \\) makes the \\( +1 \\) into a tiny \\( +\\varepsilon^{2} \\) correction." },
        { stepNumber: 4, description: "Leading balance.", workingLatex: "X^{3} - X^{2} \\approx 0 \\;\\Longrightarrow\\; X_{0} = 1.", explanation: "Discarding the double root \\( X = 0 \\) (the \\( O(1) \\) roots) leaves \\( X_{0} = 1 \\)." },
        { stepNumber: 5, description: "First correction.", workingLatex: "X = 1 + \\eta: \\ (1+\\eta)^{3} - (1+\\eta)^{2} + \\varepsilon^{2} = 0 \\;\\Rightarrow\\; \\eta + \\varepsilon^{2} \\approx 0 \\;\\Rightarrow\\; \\eta = -\\varepsilon^{2}.", explanation: "Linearising about \\( X = 1 \\): the derivative of \\( X^{3} - X^{2} \\) is \\( 3X^{2} - 2X = 1 \\) there, so \\( \\eta = -\\varepsilon^{2} \\)." },
        { stepNumber: 6, description: "Unscale.", workingLatex: "x = \\frac{1 - \\varepsilon^{2}}{\\varepsilon} = \\frac{1}{\\varepsilon} - \\varepsilon.", explanation: "Numerical check at \\( \\varepsilon = 10^{-2} \\): exact large root \\( 99.99 \\) versus \\( 1/\\varepsilon - \\varepsilon = 99.99 \\)." },
      ],
      finalAnswer: "\\( x \\sim \\dfrac{1}{\\varepsilon} - \\varepsilon \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1/eps - eps",
    },
  },
  {
    id: "am9c-026",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 26",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first three terms, as \\( \\varepsilon \\to 0^{+} \\), in the expansion of the root near \\( x = 1 \\) of the transcendental equation \\( x\\, e^{-\\varepsilon x} = 1 \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["transcendental", "regular perturbation", "higher correction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduced root.", workingLatex: "\\varepsilon = 0: \\quad x = 1 \\;\\Longrightarrow\\; x_{0} = 1.", explanation: "Setting \\( \\varepsilon = 0 \\) removes the exponential factor, leaving \\( x = 1 \\)." },
        { stepNumber: 2, description: "Posit a regular expansion.", workingLatex: "x = 1 + \\varepsilon x_{1} + \\varepsilon^{2} x_{2} + O(\\varepsilon^{3}).", explanation: "The factor \\( e^{-\\varepsilon x} = 1 - \\varepsilon x + \\cdots \\) is a smooth perturbation, so a power series in \\( \\varepsilon \\) is appropriate." },
        { stepNumber: 3, description: "Expand the exponential.", workingLatex: "e^{-\\varepsilon x} = 1 - \\varepsilon x + \\frac{\\varepsilon^{2} x^{2}}{2} + O(\\varepsilon^{3}).", explanation: "We need the exponential to \\( O(\\varepsilon^{2}) \\); inside it, use \\( x = 1 + \\varepsilon x_{1} + \\cdots \\)." },
        { stepNumber: 4, description: "Form the product and collect orders.", workingLatex: "x\\,e^{-\\varepsilon x} = (1 + \\varepsilon x_{1} + \\varepsilon^{2}x_{2})\\left(1 - \\varepsilon x + \\tfrac12\\varepsilon^{2}x^{2}\\right) = 1.", explanation: "Substitute \\( x = 1 + \\varepsilon x_{1} \\) where it appears in the exponential's coefficients and multiply out." },
        { stepNumber: 5, description: "Order \\( \\varepsilon \\).", workingLatex: "x_{1} - 1 = 0 \\;\\Longrightarrow\\; x_{1} = 1.", explanation: "The \\( O(\\varepsilon) \\) terms are \\( x_{1} \\) (from the prefactor) and \\( -x_{0} = -1 \\) (from \\( -\\varepsilon x \\)); they must cancel." },
        { stepNumber: 6, description: "Order \\( \\varepsilon^{2} \\).", workingLatex: "x_{2} - (x_{1} + x_{1}) + \\tfrac12 = 0 \\;\\Longrightarrow\\; x_{2} - 2 + \\tfrac12 = 0 \\;\\Longrightarrow\\; x_{2} = \\tfrac32.", explanation: "The \\( O(\\varepsilon^{2}) \\) terms are \\( x_{2} \\), the cross term \\( -x_{1}\\cdot 1 - 1\\cdot x_{1} = -2x_{1} \\) (since \\( -\\varepsilon x = -\\varepsilon(1+\\varepsilon x_{1}) \\) contributes \\( -x_{1} \\) and the prefactor \\( \\times(-\\varepsilon x) \\) contributes another \\( -x_{1} \\)), and \\( +\\tfrac12 \\) from \\( \\tfrac12\\varepsilon^{2}x_{0}^{2} \\)." },
        { stepNumber: 7, description: "State the expansion.", workingLatex: "x \\sim 1 + \\varepsilon + \\frac{3}{2}\\varepsilon^{2}.", explanation: "Numerical check at \\( \\varepsilon = 0.05 \\): exact root \\( 1.054120 \\) versus \\( 1 + \\varepsilon + \\tfrac32\\varepsilon^{2} = 1.053750 \\); the gap is \\( O(\\varepsilon^{3}) \\)." },
      ],
      finalAnswer: "\\( x \\sim 1 + \\varepsilon + \\dfrac{3}{2}\\varepsilon^{2} \\) as \\( \\varepsilon \\to 0 \\).",
      canonicalAnswer: "1 + eps + (3/2)*eps^2",
    },
  },
  {
    id: "am9c-027",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 27",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the first two terms, as \\( n \\to \\infty \\), of the large positive roots of \\( x \\tan x = 1 \\).",
    marks: 6,
    yearCreated: 2026,
    tags: ["transcendental equation", "large roots", "perturbation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading-order location.", workingLatex: "x \\tan x = 1 \\;\\Longrightarrow\\; \\tan x = \\frac{1}{x} \\to 0 \\;\\Longrightarrow\\; x \\approx n\\pi.", explanation: "For large \\( x \\) the product is fixed at \\( 1 \\) only if \\( \\tan x \\to 0 \\), placing the root near \\( n\\pi \\)." },
        { stepNumber: 2, description: "Local displacement.", workingLatex: "x = n\\pi + \\xi, \\qquad \\xi \\ll 1.", explanation: "Write the root as the leading value plus a small \\( \\xi \\)." },
        { stepNumber: 3, description: "Expand the equation.", workingLatex: "(n\\pi + \\xi)\\tan(n\\pi + \\xi) = (n\\pi + \\xi)\\tan\\xi = 1.", explanation: "Using the \\( \\pi \\)-periodicity of \\( \\tan \\)." },
        { stepNumber: 4, description: "Leading balance for \\( \\xi \\).", workingLatex: "(n\\pi)\\,\\xi \\approx 1 \\;\\Longrightarrow\\; \\xi \\approx \\frac{1}{n\\pi}.", explanation: "With \\( \\tan\\xi \\approx \\xi \\) and \\( x \\approx n\\pi \\), the leading correction is \\( \\xi \\approx 1/(n\\pi) \\)." },
        { stepNumber: 5, description: "Refine using more of \\( \\tan\\xi \\).", workingLatex: "(n\\pi + \\xi)\\left(\\xi + \\tfrac{\\xi^{3}}{3}\\right) = 1 \\;\\Rightarrow\\; n\\pi\\,\\xi + \\xi^{2} \\approx 1 \\;\\Rightarrow\\; \\xi \\approx \\frac{1}{n\\pi} - \\frac{1}{(n\\pi)^{3}}.", explanation: "Keeping the \\( \\xi \\) inside the bracket and the leading \\( \\tan\\xi \\) term, solve \\( n\\pi\\,\\xi + \\xi^{2} = 1 \\) iteratively; \\( \\xi^{2} \\approx 1/(n\\pi)^{2} \\) gives the next term \\( -1/(n\\pi)^{3} \\)." },
        { stepNumber: 6, description: "State the expansion.", workingLatex: "x \\sim n\\pi + \\frac{1}{n\\pi} - \\frac{1}{(n\\pi)^{3}}.", explanation: "Numerical check at \\( n = 5 \\): exact root \\( 15.77128 \\) versus \\( 5\\pi + 1/(5\\pi) - 1/(5\\pi)^{3} = 15.70796 + 0.06366 - 0.000258 = 15.77137 \\) — agreement to four decimal places." },
      ],
      finalAnswer: "\\( x \\sim n\\pi + \\dfrac{1}{n\\pi} - \\dfrac{1}{(n\\pi)^{3}} \\) as \\( n \\to \\infty \\).",
    },
  },
  {
    id: "am9c-028",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 28",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "The quadratic \\( x^{2} - 2x + (1 - \\varepsilon) = 0 \\) has a double root at \\( \\varepsilon = 0 \\). Find the leading-order behaviour of the splitting of the two roots for small \\( \\varepsilon > 0 \\), and identify the appropriate local scaling.",
    marks: 5,
    yearCreated: 2026,
    tags: ["coalescing roots", "rescaling", "fractional powers"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduced double root.", workingLatex: "\\varepsilon = 0: \\quad x^{2} - 2x + 1 = (x-1)^{2} = 0 \\;\\Longrightarrow\\; x_{0} = 1.", explanation: "At \\( \\varepsilon = 0 \\) the two roots coincide at \\( x = 1 \\). A regular power-series ansatz fails because the derivative of the polynomial vanishes there." },
        { stepNumber: 2, description: "Local scaling near the double root.", workingLatex: "x = 1 + \\eta, \\qquad \\eta \\ \\text{small}.", explanation: "Shift to the double root; the splitting will be measured by \\( \\eta \\)." },
        { stepNumber: 3, description: "Substitute.", workingLatex: "(1+\\eta)^{2} - 2(1+\\eta) + 1 - \\varepsilon = \\eta^{2} - \\varepsilon = 0.", explanation: "The linear terms cancel exactly (the hallmark of a double root), leaving the dominant balance \\( \\eta^{2} \\sim \\varepsilon \\)." },
        { stepNumber: 4, description: "Read off the fractional power.", workingLatex: "\\eta^{2} = \\varepsilon \\;\\Longrightarrow\\; \\eta = \\pm \\varepsilon^{1/2}.", explanation: "The balance forces a half-power scaling \\( \\eta = O(\\varepsilon^{1/2}) \\) — coalescing roots split as a square root of the perturbation." },
        { stepNumber: 5, description: "State the two roots.", workingLatex: "x \\sim 1 \\pm \\sqrt{\\varepsilon}.", explanation: "This is exact here, since \\( (x-1)^{2} = \\varepsilon \\) gives \\( x = 1 \\pm \\sqrt{\\varepsilon} \\); the example illustrates why a double root demands an \\( \\varepsilon^{1/2} \\) rescaling rather than an integer-power expansion." },
      ],
      finalAnswer: "\\( x \\sim 1 \\pm \\sqrt{\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\); the local scale is \\( \\varepsilon^{1/2} \\).",
    },
  },
  {
    id: "am9c-029",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 29",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "As \\( t \\to \\infty \\), find the first three terms in the asymptotic expansion of the solution \\( x(t) \\) of \\( x + \\sqrt{x} = t \\).",
    marks: 5,
    yearCreated: 2026,
    tags: ["transcendental equation", "iteration", "fractional powers"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Leading balance.", workingLatex: "x \\sim t.", explanation: "The term \\( \\sqrt{x} \\) is subdominant to \\( x \\), so \\( x \\sim t \\) at leading order." },
        { stepNumber: 2, description: "Isolate \\( x \\).", workingLatex: "x = t - \\sqrt{x}.", explanation: "Put the dominant \\( x \\) alone; \\( \\sqrt{x} \\) is the correction." },
        { stepNumber: 3, description: "Second term.", workingLatex: "x \\approx t - \\sqrt{t}.", explanation: "Substitute \\( x \\sim t \\) into \\( \\sqrt{x} \\) to get the next term." },
        { stepNumber: 4, description: "Third term by re-expansion.", workingLatex: "\\sqrt{x} = \\sqrt{t - \\sqrt{t} + \\cdots} = \\sqrt{t}\\left(1 - \\frac{1}{\\sqrt{t}}\\right)^{1/2} = \\sqrt{t} - \\frac{1}{2} + \\cdots", explanation: "Expand the square root: \\( (1 - t^{-1/2})^{1/2} = 1 - \\tfrac12 t^{-1/2} + \\cdots \\), and \\( \\sqrt{t}\\cdot(-\\tfrac12 t^{-1/2}) = -\\tfrac12 \\)." },
        { stepNumber: 5, description: "Assemble.", workingLatex: "x = t - \\sqrt{x} = t - \\sqrt{t} + \\frac{1}{2}.", explanation: "Numerical check at \\( t = 10^{4} \\): the exact root of \\( x + \\sqrt{x} = 10^{4} \\) is \\( 9900.503 \\) versus \\( t - \\sqrt{t} + \\tfrac12 = 10000 - 100 + 0.5 = 9900.5 \\)." },
      ],
      finalAnswer: "\\( x \\sim t - \\sqrt{t} + \\dfrac{1}{2} \\) as \\( t \\to \\infty \\).",
    },
  },
  {
    id: "am9c-030",
    topicRef: "am9c",
    topicTitle: "Dominant balance & rescaling 30",
    difficulty: "Challenge",
    answerType: "expression",
    examStyle: true,
    questionText: "Find the leading-order behaviour, as \\( \\varepsilon \\to 0^{+} \\), of all three roots of \\( \\varepsilon^{2} x^{3} + \\varepsilon x^{2} - x + 1 = 0 \\), identifying every distinguished scaling.",
    marks: 6,
    yearCreated: 2026,
    tags: ["dominant balance", "distinguished limit", "multiple scalings"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduced equation.", workingLatex: "\\varepsilon = 0: \\quad -x + 1 = 0 \\;\\Longrightarrow\\; x_{0} = 1.", explanation: "Only one \\( O(1) \\) root survives; the other two are lost to large scales and need rescaling." },
        { stepNumber: 2, description: "Regular root correction.", workingLatex: "x = 1 + \\varepsilon a + \\cdots: \\ \\varepsilon(1)^{2} - \\varepsilon a + \\cdots = 0 \\;\\Rightarrow\\; a = 1 \\;\\Rightarrow\\; x \\sim 1 + \\varepsilon.", explanation: "At \\( O(\\varepsilon) \\): \\( \\varepsilon x^{2} \\) contributes \\( \\varepsilon \\) and \\( -x \\) contributes \\( -\\varepsilon a \\); balancing gives \\( a = 1 \\)." },
        { stepNumber: 3, description: "Seek the first large scale.", workingLatex: "x = \\delta X: \\ \\varepsilon^{2}\\delta^{3} X^{3} + \\varepsilon \\delta^{2} X^{2} - \\delta X + 1 = 0.", explanation: "Try to balance the \\( \\varepsilon x^{2} \\) term against the \\( -x \\) term: \\( \\varepsilon \\delta^{2} = \\delta \\Rightarrow \\delta = 1/\\varepsilon \\)." },
        { stepNumber: 4, description: "Balance at \\( \\delta = 1/\\varepsilon \\).", workingLatex: "x = \\frac{X}{\\varepsilon}: \\ \\varepsilon^{2}\\frac{X^{3}}{\\varepsilon^{3}} + \\varepsilon \\frac{X^{2}}{\\varepsilon^{2}} - \\frac{X}{\\varepsilon} + 1 = 0 \\;\\Rightarrow\\; X^{3} + X^{2} - X + \\varepsilon = 0.", explanation: "Multiplying by \\( \\varepsilon \\): the cubic, quadratic and linear terms are all \\( O(1) \\); but this is degree three in \\( X \\) and would suggest three more roots. We must check which balance is genuinely distinguished." },
        { stepNumber: 5, description: "Identify the two genuine large roots.", workingLatex: "X^{3} + X^{2} - X \\approx 0 \\;\\Rightarrow\\; X(X^{2}+X-1)=0 \\;\\Rightarrow\\; X = \\frac{-1\\pm\\sqrt5}{2}.", explanation: "The root \\( X = 0 \\) corresponds to the already-found regular root (\\( x = O(1) \\)). The other two, \\( X = \\tfrac{-1\\pm\\sqrt5}{2} \\), give the large roots at scale \\( 1/\\varepsilon \\)." },
        { stepNumber: 6, description: "Unscale the large roots.", workingLatex: "x \\sim \\frac{1}{\\varepsilon}\\cdot\\frac{-1+\\sqrt5}{2}, \\qquad x \\sim \\frac{1}{\\varepsilon}\\cdot\\frac{-1-\\sqrt5}{2}.", explanation: "Numerical check at \\( \\varepsilon = 10^{-3} \\): exact roots are \\( 1.001,\\ 617.3,\\ -1618.3 \\); the leading-order predictions \\( 1+\\varepsilon = 1.001 \\), \\( (\\!-1+\\sqrt5)/(2\\varepsilon) = 618.0 \\), \\( (\\!-1-\\sqrt5)/(2\\varepsilon) = -1618.0 \\) match (the small relative gaps are the next, \\( O(1) \\), corrections)." },
      ],
      finalAnswer: "\\( x \\sim 1 + \\varepsilon, \\quad x \\sim \\dfrac{-1\\pm\\sqrt5}{2\\varepsilon} \\) as \\( \\varepsilon \\to 0 \\).",
    },
  },
];
