import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — Asymptotic Sequences & Series
 * Ref:   am1  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Order notation and gauge functions; asymptotic sequences; manipulating
 * asymptotic expansions (sum, product, reciprocal); generating expansions of
 * standard functions at large/small argument; divergent series & optimal
 * truncation; asymptotic solution of algebraic/transcendental equations.
 *
 * DRAFT (year-3): style pinned to content/undergrad/examples/am1.md; correctness
 * independently checked where tractable, // REVIEW flags mark anything the
 * checker could not fully establish. Expert review required before student use.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am1-001",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to\\infty} x^{10}e^{-x} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["order notation", "limits"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compare exponential decay with polynomial growth.",
          workingLatex: "e^{x}=\\sum_{k\\ge0}\\frac{x^{k}}{k!}>\\frac{x^{11}}{11!}",
          explanation: "The exponential dominates any fixed power, so x^{10}e^{-x} < 11!/x \\to 0.",
        },
        {
          stepNumber: 2,
          description: "Take the limit.",
          workingLatex: "0\\le x^{10}e^{-x}<\\frac{11!}{x}\\to0",
          explanation: "This is why e^{-x}=o(x^{-n}) for every n: it is subdominant to all powers.",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am1-002",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to\\infty} \\dfrac{\\ln x}{x} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["order notation", "limits", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply L'Hôpital to the ∞/∞ form.",
          workingLatex: "\\lim_{x\\to\\infty}\\frac{\\ln x}{x}=\\lim_{x\\to\\infty}\\frac{1/x}{1}",
          explanation: "Logarithms grow more slowly than any positive power of x.",
        },
        {
          stepNumber: 2,
          description: "Evaluate.",
          workingLatex: "\\lim_{x\\to\\infty}\\frac{1}{x}=0",
          explanation: "Hence \\ln x = o(x) as x\\to\\infty.",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am1-003",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to 0^{+}} x^{1/2}\\ln x \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["order notation", "limits", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rewrite as a quotient and apply L'Hôpital.",
          workingLatex: "x^{1/2}\\ln x=\\frac{\\ln x}{x^{-1/2}}",
          explanation: "This is a -∞/∞ form as x\\to0^{+}.",
        },
        {
          stepNumber: 2,
          description: "Differentiate top and bottom.",
          workingLatex: "\\frac{1/x}{-\\tfrac12 x^{-3/2}}=-2x^{1/2}\\to0",
          explanation: "So x^{1/2} beats the logarithmic singularity.",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am1-004",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "As \\( x\\to\\infty \\), the function \\( f(x)=3x^{3}-5x^{2}+7 \\) satisfies \\( f(x)\\sim a\\,x^{n} \\). State the integer \\( n \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order behaviour", "asymptotic equivalence"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Factor out the dominant power.",
          workingLatex: "f(x)=3x^{3}\\left(1-\\frac{5}{3x}+\\frac{7}{3x^{3}}\\right)",
          explanation: "As x\\to\\infty the bracket \\to 1, so the highest power controls the size.",
        },
        {
          stepNumber: 2,
          description: "Read off the leading power.",
          workingLatex: "f(x)\\sim 3x^{3}\\Rightarrow n=3",
          explanation: "",
        },
      ],
      finalAnswer: "\\( n=3 \\)",
      canonicalAnswer: "3",
    },
  },
  {
    id: "am1-005",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "As \\( x\\to 0 \\), \\( 1-\\cos x\\sim c\\,x^{2} \\). Find \\( c \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order behaviour", "Taylor series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the Maclaurin series of cos x.",
          workingLatex: "\\cos x=1-\\frac{x^{2}}{2}+\\frac{x^{4}}{24}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Subtract from 1 and take the leading term.",
          workingLatex: "1-\\cos x=\\frac{x^{2}}{2}-\\cdots\\sim\\frac{1}{2}x^{2}",
          explanation: "So c=1/2.",
        },
      ],
      finalAnswer: "\\( c=\\frac{1}{2} \\)",
      canonicalAnswer: "1/2",
    },
  },
  {
    id: "am1-006",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "As \\( x\\to 0 \\), \\( \\tan x - x\\sim c\\,x^{3} \\). Find \\( c \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order behaviour", "Taylor series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the Maclaurin series of tan x.",
          workingLatex: "\\tan x=x+\\frac{x^{3}}{3}+\\frac{2x^{5}}{15}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Subtract x and take the leading term.",
          workingLatex: "\\tan x-x=\\frac{x^{3}}{3}+\\cdots\\sim\\frac{1}{3}x^{3}",
          explanation: "So c=1/3.",
        },
      ],
      finalAnswer: "\\( c=\\frac{1}{3} \\)",
      canonicalAnswer: "1/3",
    },
  },
  {
    id: "am1-007",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Show that \\( \\{x^{-n}\\}_{n=0}^{\\infty} \\) is an asymptotic sequence as \\( x\\to\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "order notation", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "State the defining condition.",
          workingLatex: "\\phi_{n+1}(x)=o\\big(\\phi_{n}(x)\\big)\\ \\text{as }x\\to\\infty",
          explanation: "An asymptotic sequence is one in which each term is subdominant to the previous.",
        },
        {
          stepNumber: 2,
          description: "Form the ratio of consecutive terms.",
          workingLatex: "\\frac{x^{-(n+1)}}{x^{-n}}=\\frac{1}{x}\\to0",
          explanation: "The ratio tends to zero for every n, which is exactly the o(\\cdot) condition.",
        },
      ],
      finalAnswer: "\\( \\{x^{-n}\\} \\) is an asymptotic sequence (shown)",
    },
  },
  {
    id: "am1-008",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to\\infty} \\dfrac{2x^{2}+1}{x^{2}+x} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order behaviour", "limits"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Divide numerator and denominator by x².",
          workingLatex: "\\frac{2+x^{-2}}{1+x^{-1}}",
          explanation: "Comparing leading terms gives the asymptotic ratio.",
        },
        {
          stepNumber: 2,
          description: "Let x→∞.",
          workingLatex: "\\frac{2+0}{1+0}=2",
          explanation: "Hence the quotient is asymptotic to 2.",
        },
      ],
      finalAnswer: "\\( 2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am1-009",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "In the expansion \\( e^{1/x}\\sim\\sum_{n\\ge0}\\dfrac{a_n}{x^{n}} \\) as \\( x\\to\\infty \\), state the coefficient \\( a_1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute the small quantity 1/x into the exponential series.",
          workingLatex: "e^{1/x}=1+\\frac{1}{x}+\\frac{1}{2x^{2}}+\\cdots",
          explanation: "Valid because 1/x\\to0 as x\\to\\infty.",
        },
        {
          stepNumber: 2,
          description: "Read off the coefficient of 1/x.",
          workingLatex: "a_1=1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( a_1=1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am1-010",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "In \\( \\ln(1+x)\\sim\\sum_{n\\ge1}a_n x^{n} \\) as \\( x\\to 0 \\), state the coefficient \\( a_2 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the Maclaurin series.",
          workingLatex: "\\ln(1+x)=x-\\frac{x^{2}}{2}+\\frac{x^{3}}{3}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Read off the coefficient of x².",
          workingLatex: "a_2=-\\frac{1}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( a_2=-\\frac{1}{2} \\)",
      canonicalAnswer: "-1/2",
    },
  },
  {
    id: "am1-011",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to\\infty} x\\big(e^{1/x}-1\\big) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["leading-order behaviour", "limits", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the exponential for small 1/x.",
          workingLatex: "e^{1/x}-1=\\frac{1}{x}+\\frac{1}{2x^{2}}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Multiply by x and take the limit.",
          workingLatex: "x\\Big(\\frac{1}{x}+\\frac{1}{2x^{2}}+\\cdots\\Big)=1+\\frac{1}{2x}+\\cdots\\to1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am1-012",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\lim_{x\\to 0^{+}} \\dfrac{e^{-1/x}}{x^{5}} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["beyond all orders", "limits"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute u=1/x→∞.",
          workingLatex: "\\frac{e^{-1/x}}{x^{5}}=u^{5}e^{-u},\\quad u=\\frac{1}{x}\\to\\infty",
          explanation: "Turns the x\\to0^{+} singularity into a large-u decay.",
        },
        {
          stepNumber: 2,
          description: "Exponential beats the power.",
          workingLatex: "u^{5}e^{-u}\\to0",
          explanation: "So e^{-1/x} is smaller than every power x^{n}: it lies beyond all orders.",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am1-013",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z)\\sim 1+\\dfrac{2}{z}+\\dfrac{3}{z^{2}} \\) and \\( g(z)\\sim 1-\\dfrac{1}{z} \\) as \\( z\\to\\infty \\). Using \\( c_n=\\sum_{k=0}^{n}a_{n-k}b_k \\), find the terms of \\( f(z)g(z) \\) up to \\( z^{-2} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "product rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Record the coefficients.",
          workingLatex: "a_0=1,a_1=2,a_2=3;\\quad b_0=1,b_1=-1,b_2=0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply the Cauchy-product formula.",
          workingLatex: "c_0=1,\\ c_1=a_0b_1+a_1b_0=-1+2=1,\\ c_2=a_0b_2+a_1b_1+a_2b_0=0-2+3=1",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Assemble the product expansion.",
          workingLatex: "f(z)g(z)\\sim1+\\frac{1}{z}+\\frac{1}{z^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 1+\\frac{1}{z}+\\frac{1}{z^{2}} \\)",
      canonicalAnswer: "1+1/z+1/z^2",
    },
  },
  {
    id: "am1-014",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "For \\( f(z)\\sim 1+\\dfrac{1}{z}+\\dfrac{1}{z^{2}} \\) as \\( z\\to\\infty \\), find the coefficient of \\( z^{-2} \\) in the expansion of \\( 1/f(z) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "reciprocal"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write f=1+u with u small.",
          workingLatex: "u=\\frac{1}{z}+\\frac{1}{z^{2}},\\qquad \\frac{1}{f}=1-u+u^{2}-\\cdots",
          explanation: "Geometric expansion is valid because u\\to0 as z\\to\\infty.",
        },
        {
          stepNumber: 2,
          description: "Collect terms to order z^{-2}.",
          workingLatex: "u^{2}=\\frac{1}{z^{2}}+\\cdots\\Rightarrow \\frac{1}{f}=1-\\frac{1}{z}+\\Big(-1+1\\Big)\\frac{1}{z^{2}}+\\cdots",
          explanation: "The z^{-2} contributions are -1 (from -u) and +1 (from u²).",
        },
        {
          stepNumber: 3,
          description: "Read off the coefficient.",
          workingLatex: "[z^{-2}]\\,\\frac{1}{f}=0",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am1-015",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms of the asymptotic expansion of \\( \\sqrt{x^{2}+1} \\) as \\( x\\to+\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "binomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Factor out the dominant power.",
          workingLatex: "\\sqrt{x^{2}+1}=x\\Big(1+\\frac{1}{x^{2}}\\Big)^{1/2}",
          explanation: "Valid for x>0; the bracket is a binomial in the small quantity x^{-2}.",
        },
        {
          stepNumber: 2,
          description: "Binomial-expand to two terms.",
          workingLatex: "\\Big(1+\\frac{1}{x^{2}}\\Big)^{1/2}=1+\\frac{1}{2x^{2}}-\\frac{1}{8x^{4}}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Multiply through by x.",
          workingLatex: "\\sqrt{x^{2}+1}\\sim x+\\frac{1}{2x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x+\\frac{1}{2x} \\)",
      canonicalAnswer: "x+1/(2x)",
    },
  },
  {
    id: "am1-016",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the coefficient of \\( x^{2} \\) in the expansion of \\( (1+x)^{1/3} \\) as \\( x\\to 0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "binomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the binomial series with exponent 1/3.",
          workingLatex: "(1+x)^{1/3}=1+\\frac{1}{3}x+\\frac{\\frac13(\\frac13-1)}{2!}x^{2}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify the x² coefficient.",
          workingLatex: "\\frac{\\frac13\\cdot(-\\frac23)}{2}=\\frac{-\\frac29}{2}=-\\frac{1}{9}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\frac{1}{9} \\)",
      canonicalAnswer: "-1/9",
    },
  },
  {
    id: "am1-017",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Find the coefficient of \\( x^{-2} \\) in the asymptotic expansion of \\( \\dfrac{x+1}{x-1} \\) as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "geometric series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write in terms of the small quantity 1/x.",
          workingLatex: "\\frac{x+1}{x-1}=\\frac{1+x^{-1}}{1-x^{-1}}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand the denominator geometrically.",
          workingLatex: "(1+x^{-1})(1+x^{-1}+x^{-2}+\\cdots)=1+\\frac{2}{x}+\\frac{2}{x^{2}}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Read off the coefficient.",
          workingLatex: "[x^{-2}]=2",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am1-018",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "The divergent series \\( \\sum_{n\\ge0}(-1)^{n}n!\\,x^{n} \\) is asymptotic as \\( x\\to0^{+} \\). For \\( x=0.15 \\), find the index \\( n \\) of the term of smallest magnitude.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["divergent series", "optimal truncation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Form the ratio of consecutive term magnitudes.",
          workingLatex: "\\frac{|t_{n+1}|}{|t_n|}=\\frac{(n+1)!\\,x^{n+1}}{n!\\,x^{n}}=(n+1)x",
          explanation: "Terms shrink while (n+1)x<1 and grow once (n+1)x>1.",
        },
        {
          stepNumber: 2,
          description: "Locate where the ratio passes through 1.",
          workingLatex: "(n+1)(0.15)<1\\iff n+1<6.67\\iff n\\le5",
          explanation: "So |t_n| keeps decreasing up to n=6 and increases thereafter.",
        },
        {
          stepNumber: 3,
          description: "Identify the smallest term.",
          workingLatex: "n=6",
          explanation: "The ratio at n=5\\to6 is 0.9<1 (still shrinking) and at n=6\\to7 is 1.05>1 (growing).",
        },
      ],
      finalAnswer: "\\( n=6 \\)",
      canonicalAnswer: "6",
    },
  },
  {
    id: "am1-019",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order asymptotic behaviour of the large root of \\( x\\,e^{x}=t \\) as \\( t\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take logs to expose the dominant balance.",
          workingLatex: "\\ln x+x=\\ln t",
          explanation: "As t\\to\\infty the root x\\to\\infty, and x dominates \\ln x.",
        },
        {
          stepNumber: 2,
          description: "Balance the largest terms.",
          workingLatex: "x\\sim\\ln t",
          explanation: "Since \\ln x=o(x), the leading balance is x\\approx\\ln t. (Next term is -\\ln\\ln t.)",
        },
      ],
      finalAnswer: "\\( x\\sim\\ln t \\)",
      canonicalAnswer: "ln(t)",
    },
  },
  {
    id: "am1-020",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour of the positive root of \\( x^{2}+\\ln x=t \\) as \\( t\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compare the sizes of the two left-hand terms.",
          workingLatex: "x^{2}+\\ln x=t,\\qquad \\ln x=o(x^{2})",
          explanation: "For large t the root is large, so x² dominates \\ln x.",
        },
        {
          stepNumber: 2,
          description: "Balance leading terms.",
          workingLatex: "x^{2}\\sim t\\Rightarrow x\\sim\\sqrt{t}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim\\sqrt{t} \\)",
      canonicalAnswer: "sqrt(t)",
    },
  },
  {
    id: "am1-021",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The equation \\( \\varepsilon x^{2}+x-1=0 \\) has a root that stays \\( O(1) \\) as \\( \\varepsilon\\to0^{+} \\). Find this root to two terms in \\( \\varepsilon \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit a regular expansion.",
          workingLatex: "x=x_0+\\varepsilon x_1+\\cdots",
          explanation: "At ε=0 the equation reduces to x-1=0, so x_0=1.",
        },
        {
          stepNumber: 2,
          description: "Substitute and collect O(ε).",
          workingLatex: "\\varepsilon x_0^{2}+(x_0+\\varepsilon x_1)-1=0\\Rightarrow \\varepsilon(x_0^{2}+x_1)=0",
          explanation: "The O(1) part gives x_0=1; the O(ε) part gives x_1=-x_0^{2}=-1.",
        },
        {
          stepNumber: 3,
          description: "Assemble.",
          workingLatex: "x\\sim1-\\varepsilon",
          explanation: "Check: exact root \\tfrac{-1+\\sqrt{1+4\\varepsilon}}{2\\varepsilon}=1-\\varepsilon+\\cdots.",
        },
      ],
      finalAnswer: "\\( x\\sim 1-\\varepsilon \\)",
      canonicalAnswer: "1-epsilon",
    },
  },
  {
    id: "am1-022",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( \\varepsilon x^{2}+x-1=0 \\), find the leading behaviour of the root that diverges as \\( \\varepsilon\\to0^{+} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The lost root needs a dominant-balance rescaling.",
          workingLatex: "\\varepsilon x^{2}+x-1=0",
          explanation: "Setting ε=0 drops the x² term and loses a root; for the large root, εx² must balance x.",
        },
        {
          stepNumber: 2,
          description: "Balance εx² against x.",
          workingLatex: "\\varepsilon x^{2}\\sim -x\\Rightarrow x\\sim-\\frac{1}{\\varepsilon}",
          explanation: "The two largest terms balance when x=O(ε^{-1}); the -1 is then negligible at leading order.",
        },
      ],
      finalAnswer: "\\( x\\sim -\\dfrac{1}{\\varepsilon} \\)",
      canonicalAnswer: "-1/epsilon",
    },
  },
  {
    id: "am1-023",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the coefficient of \\( x^{-2} \\) in the expansion of \\( x\\ln\\!\\big(1+\\tfrac1x\\big) \\) as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the logarithm in the small quantity 1/x.",
          workingLatex: "\\ln\\Big(1+\\frac1x\\Big)=\\frac1x-\\frac{1}{2x^{2}}+\\frac{1}{3x^{3}}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Multiply by x.",
          workingLatex: "x\\ln\\Big(1+\\frac1x\\Big)=1-\\frac{1}{2x}+\\frac{1}{3x^{2}}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Read off the coefficient of x^{-2}.",
          workingLatex: "\\frac{1}{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{3} \\)",
      canonicalAnswer: "1/3",
    },
  },
  {
    id: "am1-024",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour of \\( x-\\big(x^{3}-x\\big)^{1/3} \\) as \\( x\\to+\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "binomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Factor the dominant power out of the cube root.",
          workingLatex: "(x^{3}-x)^{1/3}=x\\Big(1-\\frac{1}{x^{2}}\\Big)^{1/3}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Binomial-expand.",
          workingLatex: "x\\Big(1-\\frac{1}{3x^{2}}-\\cdots\\Big)=x-\\frac{1}{3x}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Subtract from x.",
          workingLatex: "x-(x^{3}-x)^{1/3}\\sim\\frac{1}{3x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{3x} \\)",
      canonicalAnswer: "1/(3x)",
    },
  },
  {
    id: "am1-025",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the coefficient of \\( x^{4} \\) in the Maclaurin expansion of \\( \\dfrac{\\sin x}{x} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Taylor series", "asymptotic expansion"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Divide the sine series by x.",
          workingLatex: "\\frac{\\sin x}{x}=\\frac{1}{x}\\Big(x-\\frac{x^{3}}{6}+\\frac{x^{5}}{120}-\\cdots\\Big)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify and read off the x⁴ term.",
          workingLatex: "1-\\frac{x^{2}}{6}+\\frac{x^{4}}{120}-\\cdots\\Rightarrow [x^{4}]=\\frac{1}{120}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{120} \\)",
      canonicalAnswer: "1/120",
    },
  },
  {
    id: "am1-026",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the coefficient of \\( x^{2} \\) in the Maclaurin expansion of \\( \\dfrac{e^{x}-1}{x} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Taylor series", "asymptotic expansion"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Divide the exponential series by x.",
          workingLatex: "\\frac{e^{x}-1}{x}=\\frac{1}{x}\\Big(x+\\frac{x^{2}}{2}+\\frac{x^{3}}{6}+\\frac{x^{4}}{24}+\\cdots\\Big)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify and pick out the x² term.",
          workingLatex: "1+\\frac{x}{2}+\\frac{x^{2}}{6}+\\cdots\\Rightarrow [x^{2}]=\\frac{1}{6}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{6} \\)",
      canonicalAnswer: "1/6",
    },
  },
  {
    id: "am1-027",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Find the coefficient of \\( x^{-1} \\) in the asymptotic expansion of \\( \\arctan x \\) as \\( x\\to+\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "inverse trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the identity relating arctan x to arctan(1/x).",
          workingLatex: "\\arctan x=\\frac{\\pi}{2}-\\arctan\\frac{1}{x}\\quad(x>0)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand arctan(1/x) for large x.",
          workingLatex: "\\arctan\\frac1x=\\frac1x-\\frac{1}{3x^{3}}+\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Combine and read off the 1/x coefficient.",
          workingLatex: "\\arctan x=\\frac{\\pi}{2}-\\frac1x+\\frac{1}{3x^{3}}-\\cdots\\Rightarrow [x^{-1}]=-1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -1 \\)",
      canonicalAnswer: "-1",
    },
  },
  {
    id: "am1-028",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that \\( \\big\\{(\\ln x)^{-n}\\big\\}_{n=0}^{\\infty} \\) is an asymptotic sequence as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic sequence", "logarithm", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "State the condition to verify.",
          workingLatex: "(\\ln x)^{-(n+1)}=o\\big((\\ln x)^{-n}\\big)?",
          explanation: "Each term must be subdominant to the previous as x\\to\\infty.",
        },
        {
          stepNumber: 2,
          description: "Form the ratio.",
          workingLatex: "\\frac{(\\ln x)^{-(n+1)}}{(\\ln x)^{-n}}=\\frac{1}{\\ln x}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Take the limit.",
          workingLatex: "\\frac{1}{\\ln x}\\to0\\ \\text{as }x\\to\\infty",
          explanation: "The ratio tends to 0 for every n, so the sequence is asymptotic.",
        },
      ],
      finalAnswer: "\\( \\{(\\ln x)^{-n}\\} \\) is an asymptotic sequence (shown)",
    },
  },
  {
    id: "am1-029",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Find the coefficient of \\( x^{2} \\) in the Maclaurin expansion of \\( \\dfrac{1}{1+x+x^{2}} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "geometric series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Treat x+x² as the small quantity and expand.",
          workingLatex: "\\frac{1}{1+(x+x^{2})}=1-(x+x^{2})+(x+x^{2})^{2}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Collect powers up to x².",
          workingLatex: "1-x-x^{2}+x^{2}+\\cdots=1-x+0\\cdot x^{2}+\\cdots",
          explanation: "The -x² (from -(x+x²)) cancels the +x² (from (x+x²)²).",
        },
        {
          stepNumber: 3,
          description: "Read off the coefficient.",
          workingLatex: "[x^{2}]=0",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am1-030",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "As \\( x\\to\\infty \\), \\( \\big(1+\\tfrac1x\\big)^{x}\\sim e+\\dfrac{c}{x}+\\cdots \\). Find \\( c \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "exponential", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write the power as an exponential of a logarithm.",
          workingLatex: "\\Big(1+\\frac1x\\Big)^{x}=\\exp\\!\\Big(x\\ln\\big(1+\\tfrac1x\\big)\\Big)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand the exponent.",
          workingLatex: "x\\ln\\big(1+\\tfrac1x\\big)=1-\\frac{1}{2x}+\\frac{1}{3x^{2}}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Exponentiate to first order.",
          workingLatex: "e^{1-\\frac{1}{2x}+\\cdots}=e\\Big(1-\\frac{1}{2x}+\\cdots\\Big)=e-\\frac{e}{2x}+\\cdots",
          explanation: "Hence c=-e/2.",
        },
      ],
      finalAnswer: "\\( c=-\\frac{e}{2} \\)",
      canonicalAnswer: "-e/2",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am1-031",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using the Cauchy product, find the coefficient of \\( x^{2} \\) in the Maclaurin expansion of \\( \\dfrac{e^{x}}{1-x} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "Cauchy product"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write each factor as a power series.",
          workingLatex: "e^{x}=\\sum_{k\\ge0}\\frac{x^{k}}{k!},\\qquad \\frac{1}{1-x}=\\sum_{j\\ge0}x^{j}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "The coefficient of xⁿ is the Cauchy product.",
          workingLatex: "[x^{n}]=\\sum_{m=0}^{n}\\frac{1}{m!}",
          explanation: "Each term of 1/(1-x) contributes 1, so the convolution sums reciprocal factorials.",
        },
        {
          stepNumber: 3,
          description: "Evaluate at n=2.",
          workingLatex: "[x^{2}]=\\frac{1}{0!}+\\frac{1}{1!}+\\frac{1}{2!}=\\frac{5}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{5}{2} \\)",
      canonicalAnswer: "5/2",
    },
  },
  {
    id: "am1-032",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that the function \\( g(x)=e^{-1/x^{2}} \\) (with \\( g(0)=0 \\)) has every coefficient zero in any expansion \\( g(x)\\sim\\sum_{n\\ge0}\\beta_n x^{n} \\) as \\( x\\to0^{+} \\), and deduce that \\( g \\) is asymptotically smaller than every power of \\( x \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["beyond all orders", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute the ratio of g to an arbitrary power.",
          workingLatex: "\\frac{e^{-1/x^{2}}}{x^{n}}=u^{n/2}e^{-u},\\quad u=\\frac{1}{x^{2}}\\to\\infty",
          explanation: "Substituting u=1/x² turns x\\to0^{+} into u\\to\\infty.",
        },
        {
          stepNumber: 2,
          description: "Exponential decay dominates every power.",
          workingLatex: "u^{n/2}e^{-u}\\to0\\Rightarrow g(x)=o(x^{n})\\ \\forall n",
          explanation: "So g is smaller than every gauge xⁿ as x\\to0^{+}.",
        },
        {
          stepNumber: 3,
          description: "Extract the coefficients recursively.",
          workingLatex: "\\beta_0=\\lim_{x\\to0^{+}}g=0,\\quad \\beta_n=\\lim_{x\\to0^{+}}\\frac{g-\\sum_{k<n}\\beta_kx^{k}}{x^{n}}=0",
          explanation: "Since g=o(xⁿ) for all n, each successive coefficient is forced to vanish.",
        },
        {
          stepNumber: 4,
          description: "Conclude.",
          workingLatex: "g(x)\\sim 0+0\\cdot x+0\\cdot x^{2}+\\cdots",
          explanation: "g is non-zero yet has the identically-zero asymptotic power series — it lies beyond all orders.",
        },
      ],
      finalAnswer: "All \\( \\beta_n=0 \\); \\( g \\) is beyond all orders (shown)",
    },
  },
  {
    id: "am1-033",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "numeric",
    questionText: "For the asymptotic series \\( \\sum_{n\\ge0}(-1)^{n}n!\\,x^{n} \\) at \\( x=0.1 \\), optimal truncation keeps terms up to index \\( N=\\lfloor 1/x\\rfloor-1 \\). State \\( N \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["divergent series", "optimal truncation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find where terms stop decreasing.",
          workingLatex: "\\frac{|t_{n+1}|}{|t_n|}=(n+1)x=(n+1)(0.1)",
          explanation: "Terms decrease while (n+1)(0.1)<1, i.e. n<9.",
        },
        {
          stepNumber: 2,
          description: "Apply the stated optimal-truncation rule.",
          workingLatex: "N=\\Big\\lfloor\\frac1x\\Big\\rfloor-1=\\lfloor10\\rfloor-1=9",
          explanation: "Keep all terms up to the one before the smallest (near n≈1/x).",
        },
      ],
      finalAnswer: "\\( N=9 \\)",
      canonicalAnswer: "9",
    },
  },
  {
    id: "am1-034",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "numeric",
    questionText: "If \\( y=x+x^{2} \\) for small \\( x \\), invert the relation as an asymptotic series \\( x=y+\\sum_{k\\ge2}c_k y^{k} \\) as \\( y\\to0 \\), and find \\( c_3 \\) (the coefficient of \\( y^{3} \\)).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["series reversion", "asymptotic expansion"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit the reverted series.",
          workingLatex: "x=y+c_2y^{2}+c_3y^{3}+\\cdots",
          explanation: "x\\to0 as y\\to0 and the leading term matches x\\sim y.",
        },
        {
          stepNumber: 2,
          description: "Substitute into y=x+x² and demand consistency.",
          workingLatex: "y=(y+c_2y^{2}+c_3y^{3})+(y+c_2y^{2}+\\cdots)^{2}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Match coefficients of y² and y³.",
          workingLatex: "y^{2}:\\ c_2+1=0\\Rightarrow c_2=-1;\\quad y^{3}:\\ c_3+2c_2=0",
          explanation: "The y³ terms are c_3 (from x) and 2c_2 (from the cross term of x²).",
        },
        {
          stepNumber: 4,
          description: "Solve for c₃.",
          workingLatex: "c_3=-2c_2=2",
          explanation: "So x=y-y^{2}+2y^{3}-\\cdots.",
        },
      ],
      finalAnswer: "\\( c_3=2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am1-035",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the equation \\( x-\\varepsilon\\sin x=t \\) with \\( 0<\\varepsilon\\ll1 \\), find the first two terms (in powers of \\( \\varepsilon \\)) of the asymptotic solution \\( x(t) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "iteration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit a perturbation series.",
          workingLatex: "x=x_0+\\varepsilon x_1+\\cdots",
          explanation: "At ε=0 the equation gives x_0=t.",
        },
        {
          stepNumber: 2,
          description: "Substitute and expand the sine about x₀=t.",
          workingLatex: "x_0+\\varepsilon x_1-\\varepsilon\\sin(x_0+\\cdots)=t",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Collect O(ε).",
          workingLatex: "x_1-\\sin x_0=0\\Rightarrow x_1=\\sin t",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Assemble.",
          workingLatex: "x\\sim t+\\varepsilon\\sin t",
          explanation: "This is the leading Kepler-type correction.",
        },
      ],
      finalAnswer: "\\( x\\sim t+\\varepsilon\\sin t \\)",
      canonicalAnswer: "t+epsilon*sin(t)",
    },
  },
  {
    id: "am1-036",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A quantity satisfies \\( f(h)\\sim L+a h^{2}+b h^{4} \\) as \\( h\\to0 \\). Form the combination \\( F(h)=\\dfrac{4f(h/2)-f(h)}{3} \\) and find the coefficient of \\( h^{4} \\) in \\( F(h) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Richardson extrapolation", "asymptotic expansion"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand f(h/2).",
          workingLatex: "f(h/2)\\sim L+a\\frac{h^{2}}{4}+b\\frac{h^{4}}{16}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Form 4f(h/2)−f(h).",
          workingLatex: "4f(h/2)-f(h)=3L+\\Big(a h^{2}-a h^{2}\\Big)+\\Big(\\frac{b}{4}-b\\Big)h^{4}",
          explanation: "The h² terms cancel by design (that is the point of Richardson extrapolation).",
        },
        {
          stepNumber: 3,
          description: "Divide by 3 and read off the h⁴ coefficient.",
          workingLatex: "F(h)=L-\\frac{b}{4}h^{4}\\Rightarrow [h^{4}]=-\\frac{b}{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\dfrac{b}{4} \\)",
      canonicalAnswer: "-b/4",
    },
  },
  // REVIEW: remainder/optimal-error bound argument is standard (Stieltjes series) but the
  // sharpness of the stated bound was not machine-verified — confirm before student use.
  {
    id: "am1-037",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( S_N(x)=\\sum_{n=0}^{N}(-1)^{n}n!\\,x^{n} \\) be the truncation of the Stieltjes series for \\( F(x)=\\int_0^{\\infty}\\dfrac{e^{-t}}{1+xt}\\,dt \\) (\\( x>0 \\)). Show that the remainder satisfies \\( |F(x)-S_N(x)|\\le (N+1)!\\,x^{N+1} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["divergent series", "remainder bound", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the finite geometric identity for 1/(1+xt).",
          workingLatex: "\\frac{1}{1+xt}=\\sum_{n=0}^{N}(-xt)^{n}+\\frac{(-xt)^{N+1}}{1+xt}",
          explanation: "Exact identity: a finite sum plus an explicit remainder.",
        },
        {
          stepNumber: 2,
          description: "Integrate term by term against e^{-t}.",
          workingLatex: "\\int_0^{\\infty}e^{-t}(-xt)^{n}\\,dt=(-x)^{n}n!\\Rightarrow \\int_0^{\\infty}\\frac{e^{-t}}{1+xt}dt=S_N(x)+R_N",
          explanation: "Using \\int_0^{\\infty}t^{n}e^{-t}dt=n! gives exactly the Stieltjes terms.",
        },
        {
          stepNumber: 3,
          description: "Bound the remainder integrand.",
          workingLatex: "|R_N|=\\Big|\\int_0^{\\infty}\\frac{e^{-t}(-xt)^{N+1}}{1+xt}dt\\Big|\\le x^{N+1}\\int_0^{\\infty}t^{N+1}e^{-t}dt",
          explanation: "Since 0<1/(1+xt)\\le1 for x,t>0.",
        },
        {
          stepNumber: 4,
          description: "Evaluate the bounding integral.",
          workingLatex: "|R_N|\\le x^{N+1}(N+1)!",
          explanation: "Hence the series is asymptotic with error of the size of the first omitted term.",
        },
      ],
      finalAnswer: "\\( |F-S_N|\\le (N+1)!\\,x^{N+1} \\) (shown)",
    },
  },
  {
    id: "am1-038",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( \\{\\phi_n\\} \\) be an asymptotic sequence as \\( x\\to x_0 \\). Prove that if \\( f\\sim\\sum a_n\\phi_n \\) and \\( f\\sim\\sum b_n\\phi_n \\), then \\( a_n=b_n \\) for all \\( n \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["asymptotic expansion", "uniqueness", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Subtract the two expansions.",
          workingLatex: "0\\sim\\sum_{n}(a_n-b_n)\\phi_n",
          explanation: "Both represent the same f, so their difference is asymptotic to 0.",
        },
        {
          stepNumber: 2,
          description: "Suppose not all coefficients agree; take the first index where they differ.",
          workingLatex: "\\text{let }m=\\min\\{n:a_n\\neq b_n\\}",
          explanation: "We derive a contradiction at this index.",
        },
        {
          stepNumber: 3,
          description: "Divide the leading surviving term by φ_m.",
          workingLatex: "\\frac{f-\\sum_{n<m}a_n\\phi_n}{\\phi_m}\\to a_m\\quad\\text{and}\\quad\\to b_m",
          explanation: "By definition of an asymptotic expansion, the partial-sum remainder divided by φ_m tends to the next coefficient; the higher terms vanish since φ_{n}=o(φ_m).",
        },
        {
          stepNumber: 4,
          description: "Conclude.",
          workingLatex: "a_m=b_m\\ \\Rightarrow\\ \\text{contradiction}\\ \\Rightarrow\\ a_n=b_n\\ \\forall n",
          explanation: "The limit is unique, so a_m=b_m, contradicting the choice of m. Hence all coefficients coincide.",
        },
      ],
      finalAnswer: "Coefficients are unique: \\( a_n=b_n \\) (shown)",
    },
  },
  {
    id: "am1-039",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms of the large root of \\( x\\,e^{x}=t \\) as \\( t\\to\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["transcendental equation", "iteration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take logs.",
          workingLatex: "x+\\ln x=\\ln t",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Leading balance, then iterate once.",
          workingLatex: "x_0=\\ln t;\\quad x=\\ln t-\\ln x\\approx \\ln t-\\ln(\\ln t)",
          explanation: "Substituting x≈\\ln t into the \\ln x term gives the first correction.",
        },
        {
          stepNumber: 3,
          description: "State the two-term expansion.",
          workingLatex: "x\\sim\\ln t-\\ln\\ln t",
          explanation: "Higher corrections involve (\\ln\\ln t)/(\\ln t).",
        },
      ],
      finalAnswer: "\\( x\\sim\\ln t-\\ln\\ln t \\)",
      canonicalAnswer: "ln(t)-ln(ln(t))",
    },
  },
  // REVIEW: the full asymptotic (repeated integration by parts → divergent Stieltjes series)
  // is standard; verify the induction step rigour before student use.
  {
    id: "am1-040",
    topicRef: "am1",
    topicTitle: "Asymptotic Sequences & Series",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "By repeated integration by parts, show that \\( F(x)=\\int_0^{\\infty}\\dfrac{e^{-t}}{1+xt}\\,dt\\sim\\sum_{n\\ge0}(-1)^{n}n!\\,x^{n} \\) as \\( x\\to0^{+} \\), and explain why the series diverges for every \\( x>0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["divergent series", "asymptotic expansion", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the kernel in a finite geometric series with remainder.",
          workingLatex: "\\frac{1}{1+xt}=\\sum_{n=0}^{N}(-xt)^{n}+\\frac{(-xt)^{N+1}}{1+xt}",
          explanation: "Exact for all N; the last term is the controlled remainder.",
        },
        {
          stepNumber: 2,
          description: "Integrate against e^{-t} using the Gamma integral.",
          workingLatex: "\\int_0^{\\infty}t^{n}e^{-t}\\,dt=n!\\Rightarrow F(x)=\\sum_{n=0}^{N}(-1)^{n}n!\\,x^{n}+R_N",
          explanation: "Each term reproduces (-1)ⁿn!xⁿ, the claimed series.",
        },
        {
          stepNumber: 3,
          description: "Bound the remainder by the first omitted term.",
          workingLatex: "|R_N|\\le (N+1)!\\,x^{N+1}=o(x^{N})\\ \\text{as }x\\to0^{+}",
          explanation: "For fixed N the remainder is smaller than the last retained term — the defining property of an asymptotic expansion.",
        },
        {
          stepNumber: 4,
          description: "Show divergence at fixed x.",
          workingLatex: "\\Big|\\frac{(-1)^{n+1}(n+1)!x^{n+1}}{(-1)^{n}n!x^{n}}\\Big|=(n+1)x\\to\\infty",
          explanation: "For any fixed x>0 the terms eventually grow without bound, so the series diverges despite being asymptotic.",
        },
      ],
      finalAnswer: "\\( F(x)\\sim\\sum(-1)^{n}n!\\,x^{n} \\), divergent for all \\( x>0 \\) (shown)",
    },
  },
];
