import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — Asymptotic Expansion of Integrals; Watson's Lemma
 * Ref:   am2  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Standard transform integrals and Gamma values; Watson's lemma (Laplace-type
 * integrals from the small-t behaviour of the amplitude); Laplace's method
 * (interior and endpoint maxima); integration-by-parts tails (E1, erfc, Stirling);
 * optimal truncation of the resulting divergent series.
 *
 * DRAFT (year-3): every leading coefficient and multi-term claim was numerically
 * verified with mpmath; style pinned to content/undergrad/examples/am2.md.
 * // REVIEW marks proofs whose rigour was not machine-checked. Expert review
 * required before student use.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am2-001",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the value of \\( \\Gamma\\!\\left(\\tfrac12\\right) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gamma function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recall the standard half-integer Gamma value.",
          workingLatex: "\\Gamma\\!\\left(\\tfrac12\\right)=\\int_0^{\\infty}t^{-1/2}e^{-t}\\,dt=\\sqrt{\\pi}",
          explanation: "Follows from the Gaussian integral after the substitution t=u².",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\pi} \\)",
      canonicalAnswer: "sqrt(pi)",
    },
  },
  {
    id: "am2-002",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Using \\( \\Gamma(z+1)=z\\,\\Gamma(z) \\), evaluate \\( \\Gamma\\!\\left(\\tfrac32\\right) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gamma function", "recurrence"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the recurrence with z=1/2.",
          workingLatex: "\\Gamma\\!\\left(\\tfrac32\\right)=\\tfrac12\\,\\Gamma\\!\\left(\\tfrac12\\right)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Insert Γ(1/2)=√π.",
          workingLatex: "\\tfrac12\\sqrt{\\pi}=\\frac{\\sqrt{\\pi}}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{\\sqrt{\\pi}}{2} \\)",
      canonicalAnswer: "sqrt(pi)/2",
    },
  },
  {
    id: "am2-003",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{-x t}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate the exponential.",
          workingLatex: "\\int_0^{\\infty}e^{-xt}\\,dt=\\left[-\\frac{1}{x}e^{-xt}\\right]_0^{\\infty}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Evaluate the limits.",
          workingLatex: "0-\\left(-\\frac{1}{x}\\right)=\\frac{1}{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am2-004",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} t\\,e^{-x t}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace integral", "Gamma function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the standard moment integral.",
          workingLatex: "\\int_0^{\\infty}t^{n}e^{-xt}\\,dt=\\frac{n!}{x^{n+1}}",
          explanation: "This is Γ(n+1)/x^{n+1}; the n! form holds for integer n.",
        },
        {
          stepNumber: 2,
          description: "Set n=1.",
          workingLatex: "\\frac{1!}{x^{2}}=\\frac{1}{x^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x^{2}} \\)",
      canonicalAnswer: "1/x^2",
    },
  },
  {
    id: "am2-005",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{-x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gaussian integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the half-line Gaussian integral.",
          workingLatex: "\\int_0^{\\infty}e^{-a t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{a}}",
          explanation: "Half of the full-line value √(π/a).",
        },
        {
          stepNumber: 2,
          description: "Set a=x.",
          workingLatex: "\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)/2",
    },
  },
  {
    id: "am2-006",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gaussian integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Quote the Gaussian integral.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{-x t^{2}}\\,dt=\\sqrt{\\frac{\\pi}{x}}",
          explanation: "This is the building block of Laplace's method for an interior maximum.",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am2-007",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} t^{1/2}e^{-x t}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Gamma function", "Laplace integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the Gamma-function moment integral.",
          workingLatex: "\\int_0^{\\infty}t^{\\alpha}e^{-x t}\\,dt=\\frac{\\Gamma(\\alpha+1)}{x^{\\alpha+1}}",
          explanation: "With α=1/2.",
        },
        {
          stepNumber: 2,
          description: "Insert Γ(3/2)=√π/2.",
          workingLatex: "\\frac{\\Gamma(3/2)}{x^{3/2}}=\\frac{\\sqrt{\\pi}}{2\\,x^{3/2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{\\sqrt{\\pi}}{2\\,x^{3/2}} \\)",
      canonicalAnswer: "sqrt(pi)/(2*x^(3/2))",
    },
  },
  {
    id: "am2-008",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t}}{1+t}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Watson's lemma", "leading order"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The amplitude near t=0 controls the large-x behaviour.",
          workingLatex: "\\frac{1}{1+t}=1-t+t^{2}-\\cdots,\\qquad \\frac{1}{1+t}\\Big|_{t=0}=1",
          explanation: "By Watson's lemma the leading term comes from the value of the amplitude at t=0.",
        },
        {
          stepNumber: 2,
          description: "Apply the leading Watson term a₀·Γ(1)/x.",
          workingLatex: "\\int_0^{\\infty}\\frac{e^{-xt}}{1+t}\\,dt\\sim\\frac{1}{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am2-009",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_x^{\\infty} e^{-t}\\,dt \\) and hence give its leading behaviour as \\( x\\to\\infty \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["tail integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate directly.",
          workingLatex: "\\int_x^{\\infty}e^{-t}\\,dt=\\left[-e^{-t}\\right]_x^{\\infty}=e^{-x}",
          explanation: "Exact, so the leading behaviour is itself.",
        },
      ],
      finalAnswer: "\\( e^{-x} \\)",
      canonicalAnswer: "exp(-x)",
    },
  },
  {
    id: "am2-010",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of the tail \\( \\displaystyle\\int_x^{\\infty} e^{-t^{2}}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["tail integral", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write the integrand to expose a derivative.",
          workingLatex: "e^{-t^{2}}=\\frac{1}{-2t}\\frac{d}{dt}\\big(e^{-t^{2}}\\big)",
          explanation: "Prepare for integration by parts using that −2t e^{−t²} is the derivative of e^{−t²}.",
        },
        {
          stepNumber: 2,
          description: "Integrate by parts; the boundary term dominates.",
          workingLatex: "\\int_x^{\\infty}e^{-t^{2}}\\,dt=\\frac{e^{-x^{2}}}{2x}-\\frac{1}{2}\\int_x^{\\infty}\\frac{e^{-t^{2}}}{t^{2}}\\,dt\\sim\\frac{e^{-x^{2}}}{2x}",
          explanation: "The remaining integral is smaller by a factor 1/x², so the boundary term is leading.",
        },
      ],
      finalAnswer: "\\( \\dfrac{e^{-x^{2}}}{2x} \\)",
      canonicalAnswer: "exp(-x^2)/(2*x)",
    },
  },
  {
    id: "am2-011",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} e^{-x t}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Laplace integral", "endpoint"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate exactly.",
          workingLatex: "\\int_0^{1}e^{-xt}\\,dt=\\frac{1-e^{-x}}{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Drop the exponentially small term.",
          workingLatex: "\\frac{1-e^{-x}}{x}\\sim\\frac{1}{x}",
          explanation: "e^{−x} is beyond all orders relative to 1/x, so the endpoint t=0 dominates.",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am2-012",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} (2+t)\\,e^{-x t}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Watson's lemma", "leading order"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate term by term.",
          workingLatex: "\\int_0^{\\infty}(2+t)e^{-xt}\\,dt=\\frac{2}{x}+\\frac{1}{x^{2}}",
          explanation: "Using ∫t^n e^{−xt}dt = n!/x^{n+1}.",
        },
        {
          stepNumber: 2,
          description: "Keep the dominant term.",
          workingLatex: "\\sim\\frac{2}{x}",
          explanation: "The amplitude value at t=0 is 2, giving 2/x at leading order.",
        },
      ],
      finalAnswer: "\\( \\dfrac{2}{x} \\)",
      canonicalAnswer: "2/x",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am2-013",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x t}\\cos t\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Laplace integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Evaluate the integral exactly.",
          workingLatex: "\\int_0^{\\infty}e^{-x t}\\cos t\\,dt=\\frac{x}{x^{2}+1}",
          explanation: "Standard Laplace transform of cos t.",
        },
        {
          stepNumber: 2,
          description: "Expand for large x in powers of 1/x.",
          workingLatex: "\\frac{x}{x^{2}+1}=\\frac{1}{x}\\cdot\\frac{1}{1+x^{-2}}=\\frac{1}{x}\\Big(1-\\frac{1}{x^{2}}+\\cdots\\Big)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Read off two terms.",
          workingLatex: "\\sim\\frac{1}{x}-\\frac{1}{x^{3}}",
          explanation: "Matches Watson's lemma with cos t = 1 − t²/2 + …",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x}-\\frac{1}{x^{3}} \\)",
      canonicalAnswer: "1/x-1/x^3",
    },
  },
  {
    id: "am2-014",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using Watson's lemma, find the first three terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t}}{1+t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the amplitude about t=0.",
          workingLatex: "\\frac{1}{1+t}=\\sum_{n\\ge0}(-1)^{n}t^{n}",
          explanation: "The coefficients aₙ=(−1)ⁿ feed Watson's lemma.",
        },
        {
          stepNumber: 2,
          description: "Apply ∫t^n e^{−xt}dt = n!/x^{n+1} term by term.",
          workingLatex: "\\int_0^{\\infty}\\frac{e^{-xt}}{1+t}\\,dt\\sim\\sum_{n\\ge0}(-1)^{n}\\frac{n!}{x^{n+1}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Write the first three terms.",
          workingLatex: "\\frac{1}{x}-\\frac{1}{x^{2}}+\\frac{2}{x^{3}}",
          explanation: "Using 0!=1, 1!=1, 2!=2.",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x}-\\frac{1}{x^{2}}+\\frac{2}{x^{3}} \\)",
      canonicalAnswer: "1/x-1/x^2+2/x^3",
    },
  },
  {
    id: "am2-015",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t}}{\\sqrt{1+t}}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "binomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Binomial-expand the amplitude.",
          workingLatex: "(1+t)^{-1/2}=1-\\frac{1}{2}t+\\frac{3}{8}t^{2}-\\cdots",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply Watson's lemma term by term.",
          workingLatex: "\\int_0^{\\infty}(1+t)^{-1/2}e^{-xt}\\,dt\\sim\\frac{1}{x}-\\frac{1}{2}\\cdot\\frac{1!}{x^{2}}+\\cdots",
          explanation: "Each tⁿ contributes aₙ·n!/x^{n+1}.",
        },
        {
          stepNumber: 3,
          description: "Keep two terms.",
          workingLatex: "\\sim\\frac{1}{x}-\\frac{1}{2x^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x}-\\frac{1}{2x^{2}} \\)",
      canonicalAnswer: "1/x-1/(2*x^2)",
    },
  },
  {
    id: "am2-016",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{\\sqrt{t}\\,e^{-x t}}{1+t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Gamma function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find the small-t form of the amplitude.",
          workingLatex: "\\frac{\\sqrt{t}}{1+t}=t^{1/2}\\big(1-t+\\cdots\\big)\\sim t^{1/2}",
          explanation: "The leading power is t^{1/2}, so α=1/2 in Watson's lemma.",
        },
        {
          stepNumber: 2,
          description: "Apply the Watson leading term a₀Γ(α+1)/x^{α+1}.",
          workingLatex: "\\sim\\frac{\\Gamma(3/2)}{x^{3/2}}=\\frac{\\sqrt{\\pi}}{2\\,x^{3/2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\sqrt{\\pi}}{2\\,x^{3/2}} \\)",
      canonicalAnswer: "sqrt(pi)/(2*x^(3/2))",
    },
  },
  {
    id: "am2-017",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t^{2}}}{1+t^{2}}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "Gaussian"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Near t=0 the amplitude is ≈1.",
          workingLatex: "\\frac{1}{1+t^{2}}\\Big|_{t=0}=1",
          explanation: "The factor e^{−x t²} concentrates the integral near t=0 as x→∞.",
        },
        {
          stepNumber: 2,
          description: "Replace the amplitude by its value and use the half-Gaussian.",
          workingLatex: "\\int_0^{\\infty}e^{-x t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)/2",
    },
  },
  {
    id: "am2-018",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-x(t^{2}+t^{4})}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "Gaussian"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Identify the dominant part of the exponent near the maximum.",
          workingLatex: "t^{2}+t^{4}\\sim t^{2}\\quad(t\\to0)",
          explanation: "The maximum of the integrand is at t=0, where t⁴ is negligible against t².",
        },
        {
          stepNumber: 2,
          description: "Use the full-line Gaussian.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{-x t^{2}}\\,dt=\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am2-019",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x\\cosh t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Locate the maximum of −cosh t.",
          workingLatex: "\\cosh t=1+\\frac{t^{2}}{2}+\\cdots,\\qquad \\min_{t\\ge0}\\cosh t=\\cosh 0=1",
          explanation: "The exponent is largest at the endpoint t=0, where cosh''(0)=1.",
        },
        {
          stepNumber: 2,
          description: "Quadratic approximation gives a half-Gaussian.",
          workingLatex: "\\int_0^{\\infty}e^{-x(1+t^{2}/2)}\\,dt=e^{-x}\\cdot\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}",
          explanation: "Endpoint maximum contributes half of the full Gaussian width.",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "\\sim\\sqrt{\\frac{\\pi}{2x}}\\,e^{-x}",
          explanation: "This is the leading term of the modified Bessel function K₀(x).",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{2x}}\\,e^{-x} \\)",
      canonicalAnswer: "sqrt(pi/(2*x))*exp(-x)",
    },
  },
  {
    id: "am2-020",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi/2} e^{x\\cos t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find the maximum of cos t on the interval.",
          workingLatex: "\\cos t=1-\\frac{t^{2}}{2}+\\cdots,\\qquad \\max_{[0,\\pi/2]}\\cos t=\\cos0=1",
          explanation: "Maximum at the endpoint t=0 with cos''(0)=−1.",
        },
        {
          stepNumber: 2,
          description: "Half-Gaussian about the endpoint.",
          workingLatex: "\\int_0^{\\infty}e^{x(1-t^{2}/2)}\\,dt=e^{x}\\cdot\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "\\sim e^{x}\\sqrt{\\frac{\\pi}{2x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}\\sqrt{\\dfrac{\\pi}{2x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/(2*x))",
    },
  },
  {
    id: "am2-021",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x\\sinh t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "substitution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Small-t behaviour of the exponent.",
          workingLatex: "\\sinh t=t+\\frac{t^{3}}{6}+\\cdots\\sim t",
          explanation: "Near t=0 the integral behaves like a pure Laplace integral.",
        },
        {
          stepNumber: 2,
          description: "Leading contribution from t≈0.",
          workingLatex: "\\int_0^{\\infty}e^{-x t}\\,dt=\\frac{1}{x}",
          explanation: "Equivalently substitute u=sinh t; the Jacobian is 1 at t=0.",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "am2-022",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using integration by parts, find the first two terms, as \\( x\\to\\infty \\), of the exponential integral \\( E_1(x)=\\displaystyle\\int_x^{\\infty}\\frac{e^{-t}}{t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "exponential integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate by parts with u=1/t.",
          workingLatex: "E_1(x)=\\left[-\\frac{e^{-t}}{t}\\right]_x^{\\infty}-\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt=\\frac{e^{-x}}{x}-\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate by parts again for the next term.",
          workingLatex: "\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt=\\frac{e^{-x}}{x^{2}}-2\\int_x^{\\infty}\\frac{e^{-t}}{t^{3}}\\,dt",
          explanation: "Each step lowers the size by a factor 1/x.",
        },
        {
          stepNumber: 3,
          description: "Combine to two terms.",
          workingLatex: "E_1(x)\\sim e^{-x}\\Big(\\frac{1}{x}-\\frac{1}{x^{2}}\\Big)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{-x}\\Big(\\frac{1}{x}-\\frac{1}{x^{2}}\\Big) \\)",
      canonicalAnswer: "exp(-x)*(1/x-1/x^2)",
    },
  },
  {
    id: "am2-023",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration by parts", "tail integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate by parts with u=t^{-2}.",
          workingLatex: "\\int_x^{\\infty}\\frac{e^{-t}}{t^{2}}\\,dt=\\frac{e^{-x}}{x^{2}}-2\\int_x^{\\infty}\\frac{e^{-t}}{t^{3}}\\,dt",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "The remaining integral is smaller by 1/x.",
          workingLatex: "\\sim\\frac{e^{-x}}{x^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{e^{-x}}{x^{2}} \\)",
      canonicalAnswer: "exp(-x)/x^2",
    },
  },
  {
    id: "am2-024",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x t}\\sin t\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Laplace integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Evaluate exactly.",
          workingLatex: "\\int_0^{\\infty}e^{-x t}\\sin t\\,dt=\\frac{1}{x^{2}+1}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand for large x.",
          workingLatex: "\\frac{1}{x^{2}+1}\\sim\\frac{1}{x^{2}}",
          explanation: "Consistent with Watson's lemma: sin t = t + … gives leading t¹, i.e. Γ(2)/x²=1/x².",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x^{2}} \\)",
      canonicalAnswer: "1/x^2",
    },
  },
  {
    id: "am2-025",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "The large-x expansion of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t}}{1+t}\\,dt \\) is \\( \\sum_{n\\ge0}(-1)^{n}n!\\,x^{-(n+1)} \\). At \\( x=4.5 \\), find the index \\( n \\) of the smallest-magnitude term.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["optimal truncation", "divergent series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Ratio of consecutive term magnitudes.",
          workingLatex: "\\frac{|t_{n+1}|}{|t_n|}=\\frac{(n+1)!\\,x^{-(n+2)}}{n!\\,x^{-(n+1)}}=\\frac{n+1}{x}",
          explanation: "Terms shrink while (n+1)/x < 1.",
        },
        {
          stepNumber: 2,
          description: "Find where the ratio crosses 1.",
          workingLatex: "\\frac{n+1}{4.5}<1\\iff n<3.5",
          explanation: "So magnitudes decrease up to n=4 (ratio at n=3→4 is 4/4.5<1) and grow after (5/4.5>1).",
        },
        {
          stepNumber: 3,
          description: "Identify the smallest term.",
          workingLatex: "n=4",
          explanation: "",
        },
      ],
      finalAnswer: "\\( n=4 \\)",
      canonicalAnswer: "4",
    },
  },
  {
    id: "am2-026",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the leading-order Stirling approximation to \\( \\Gamma(x+1) \\) as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Stirling's formula", "Laplace's method"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write Γ(x+1) as a Laplace-type integral.",
          workingLatex: "\\Gamma(x+1)=\\int_0^{\\infty}t^{x}e^{-t}\\,dt=\\int_0^{\\infty}e^{x\\ln t-t}\\,dt",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Maximise the exponent and apply Laplace's method at t=x.",
          workingLatex: "\\frac{d}{dt}(x\\ln t-t)=0\\Rightarrow t=x,\\qquad \\Gamma(x+1)\\sim\\sqrt{2\\pi x}\\,\\Big(\\frac{x}{e}\\Big)^{x}",
          explanation: "The second derivative −x/t²=−1/x sets the Gaussian width.",
        },
      ],
      finalAnswer: "\\( \\sqrt{2\\pi x}\\,\\big(\\frac{x}{e}\\big)^{x} \\)",
      canonicalAnswer: "sqrt(2*pi*x)*(x/e)^x",
    },
  },
  {
    id: "am2-027",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} e^{x t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate exactly.",
          workingLatex: "\\int_0^{1}e^{x t}\\,dt=\\frac{e^{x}-1}{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Keep the dominant endpoint (t=1) contribution.",
          workingLatex: "\\frac{e^{x}-1}{x}\\sim\\frac{e^{x}}{x}",
          explanation: "The maximum of e^{xt} is at the endpoint t=1; the −1 is negligible.",
        },
      ],
      finalAnswer: "\\( \\dfrac{e^{x}}{x} \\)",
      canonicalAnswer: "exp(x)/x",
    },
  },
  {
    id: "am2-028",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} t\\,e^{x t}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate by parts.",
          workingLatex: "\\int_0^{1}t\\,e^{x t}\\,dt=\\left[\\frac{t\\,e^{x t}}{x}\\right]_0^{1}-\\frac{1}{x}\\int_0^{1}e^{x t}\\,dt=\\frac{e^{x}}{x}-\\frac{e^{x}-1}{x^{2}}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Keep the dominant term.",
          workingLatex: "\\sim\\frac{e^{x}}{x}",
          explanation: "The endpoint value (t=1, amplitude 1) controls the leading behaviour.",
        },
      ],
      finalAnswer: "\\( \\dfrac{e^{x}}{x} \\)",
      canonicalAnswer: "exp(x)/x",
    },
  },
  {
    id: "am2-029",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x t}\\ln(1+t)\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the amplitude about t=0.",
          workingLatex: "\\ln(1+t)=t-\\frac{t^{2}}{2}+\\cdots",
          explanation: "Leading power t¹, so α=1 with a₀=1.",
        },
        {
          stepNumber: 2,
          description: "Apply the leading Watson term.",
          workingLatex: "\\sim\\frac{\\Gamma(2)}{x^{2}}=\\frac{1}{x^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x^{2}} \\)",
      canonicalAnswer: "1/x^2",
    },
  },
  {
    id: "am2-030",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{-x t^{3}}\\,dt \\) for \\( x>0 \\) in closed form.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Gamma function", "substitution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute u=x t³.",
          workingLatex: "u=x t^{3},\\quad t=(u/x)^{1/3},\\quad dt=\\tfrac13 x^{-1/3}u^{-2/3}\\,du",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Reduce to a Gamma integral.",
          workingLatex: "\\frac{1}{3}x^{-1/3}\\int_0^{\\infty}u^{-2/3}e^{-u}\\,du=\\frac{1}{3}x^{-1/3}\\Gamma\\!\\left(\\tfrac13\\right)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Write using Γ(4/3)=⅓Γ(1/3).",
          workingLatex: "\\frac{\\Gamma(4/3)}{x^{1/3}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\Gamma(4/3)}{x^{1/3}} \\)",
      canonicalAnswer: "gamma(4/3)/x^(1/3)",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am2-031",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x\\cosh t}\\,dt \\) (i.e. of \\( K_0(x) \\)).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "Bessel function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the exponent to quartic order at the endpoint.",
          workingLatex: "\\cosh t=1+\\frac{t^{2}}{2}+\\frac{t^{4}}{24}+\\cdots",
          explanation: "The t⁴ term provides the first correction beyond the Gaussian.",
        },
        {
          stepNumber: 2,
          description: "Factor the leading Gaussian and expand the correction.",
          workingLatex: "e^{-x\\cosh t}=e^{-x}e^{-x t^{2}/2}\\Big(1-\\frac{x t^{4}}{24}+\\cdots\\Big)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Integrate using ∫₀^∞ t⁴ e^{−x t²/2}dt = 3√(2π)\\,x^{-5/2}/4 … and collect.",
          workingLatex: "\\int_0^{\\infty}e^{-x\\cosh t}\\,dt\\sim\\sqrt{\\frac{\\pi}{2x}}\\,e^{-x}\\Big(1-\\frac{1}{8x}\\Big)",
          explanation: "The −1/(8x) is the standard first correction to K₀.",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{2x}}\\,e^{-x}\\Big(1-\\frac{1}{8x}\\Big) \\)",
      canonicalAnswer: "sqrt(pi/(2*x))*exp(-x)*(1-1/(8*x))",
    },
  },
  // REVIEW: full Stirling-correction derivation (Laplace's method to next order) is standard;
  // the 1/12 coefficient is numerically confirmed but the algebra was not machine-checked.
  {
    id: "am2-032",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "In Stirling's expansion \\( \\Gamma(x+1)\\sim\\sqrt{2\\pi x}\\,(x/e)^{x}\\big(1+\\tfrac{c}{x}+\\cdots\\big) \\), find the constant \\( c \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Stirling's formula", "Laplace's method"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute t=x(1+s) to centre the maximum.",
          workingLatex: "\\Gamma(x+1)=\\int e^{x\\ln t-t}\\,dt=x^{x+1}e^{-x}\\int_{-1}^{\\infty}e^{x[\\ln(1+s)-s]}\\,ds",
          explanation: "The exponent has its maximum at s=0.",
        },
        {
          stepNumber: 2,
          description: "Expand the exponent to quartic order.",
          workingLatex: "\\ln(1+s)-s=-\\frac{s^{2}}{2}+\\frac{s^{3}}{3}-\\frac{s^{4}}{4}+\\cdots",
          explanation: "The s³ and s⁴ terms give the O(1/x) correction.",
        },
        {
          stepNumber: 3,
          description: "Apply the standard Laplace correction formula and collect.",
          workingLatex: "\\int e^{-x s^{2}/2}\\Big(1+\\tfrac{x s^{3}}{3}+\\tfrac{x^{2}s^{6}}{18}-\\tfrac{x s^{4}}{4}+\\cdots\\Big)ds\\Rightarrow 1+\\frac{1}{12x}+\\cdots",
          explanation: "The Gaussian moments combine to +1/(12x).",
        },
        {
          stepNumber: 4,
          description: "Read off c.",
          workingLatex: "c=\\frac{1}{12}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( c=\\frac{1}{12} \\)",
      canonicalAnswer: "1/12",
    },
  },
  {
    id: "am2-033",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi} e^{x\\sin t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "interior maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Locate the interior maximum of sin t.",
          workingLatex: "\\frac{d}{dt}\\sin t=\\cos t=0\\Rightarrow t=\\frac{\\pi}{2},\\quad \\sin\\tfrac\\pi2=1,\\ \\sin''\\tfrac\\pi2=-1",
          explanation: "Interior maximum, so the full Gaussian width applies.",
        },
        {
          stepNumber: 2,
          description: "Apply the interior-maximum Laplace formula.",
          workingLatex: "\\int_a^b e^{x\\phi(t)}\\,dt\\sim e^{x\\phi(t_0)}\\sqrt{\\frac{2\\pi}{x|\\phi''(t_0)|}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Substitute φ(t₀)=1, |φ''|=1.",
          workingLatex: "\\sim e^{x}\\sqrt{\\frac{2\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}\\sqrt{\\dfrac{2\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(2*pi/x)",
    },
  },
  {
    id: "am2-034",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\sqrt{t}\\,\\cos t\\;e^{-x t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Gamma function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find the leading small-t power of the amplitude.",
          workingLatex: "\\sqrt{t}\\,\\cos t=t^{1/2}\\Big(1-\\frac{t^{2}}{2}+\\cdots\\Big)\\sim t^{1/2}",
          explanation: "α=1/2, a₀=1 (the cosine contributes only at higher order).",
        },
        {
          stepNumber: 2,
          description: "Apply the Watson leading term.",
          workingLatex: "\\sim\\frac{\\Gamma(3/2)}{x^{3/2}}=\\frac{\\sqrt{\\pi}}{2\\,x^{3/2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\sqrt{\\pi}}{2\\,x^{3/2}} \\)",
      canonicalAnswer: "sqrt(pi)/(2*x^(3/2))",
    },
  },
  {
    id: "am2-035",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The complementary error function has \\( \\operatorname{erfc}(x)\\sim\\dfrac{e^{-x^{2}}}{x\\sqrt{\\pi}}\\big(1+\\tfrac{c}{x^{2}}+\\cdots\\big) \\) as \\( x\\to\\infty \\). Find \\( c \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["error function", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write erfc as a tail integral and integrate by parts.",
          workingLatex: "\\operatorname{erfc}(x)=\\frac{2}{\\sqrt{\\pi}}\\int_x^{\\infty}e^{-t^{2}}\\,dt=\\frac{2}{\\sqrt{\\pi}}\\Big(\\frac{e^{-x^{2}}}{2x}-\\frac12\\int_x^{\\infty}\\frac{e^{-t^{2}}}{t^{2}}\\,dt\\Big)",
          explanation: "Using e^{−t²}=(−1/2t)d/dt(e^{−t²}).",
        },
        {
          stepNumber: 2,
          description: "Integrate by parts once more.",
          workingLatex: "\\int_x^{\\infty}\\frac{e^{-t^{2}}}{t^{2}}\\,dt=\\frac{e^{-x^{2}}}{2x^{3}}-\\frac{3}{2}\\int_x^{\\infty}\\frac{e^{-t^{2}}}{t^{4}}\\,dt",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Collect to relative order 1/x².",
          workingLatex: "\\operatorname{erfc}(x)\\sim\\frac{e^{-x^{2}}}{x\\sqrt{\\pi}}\\Big(1-\\frac{1}{2x^{2}}+\\cdots\\Big)\\Rightarrow c=-\\frac12",
          explanation: "",
        },
      ],
      finalAnswer: "\\( c=-\\frac{1}{2} \\)",
      canonicalAnswer: "-1/2",
    },
  },
  {
    id: "am2-036",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x\\,[\\,t-\\ln(1+t)\\,]}\\,dt \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Laplace's method", "endpoint maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Examine the exponent φ(t)=t−ln(1+t).",
          workingLatex: "\\phi(0)=0,\\quad \\phi'(t)=\\frac{t}{1+t},\\quad \\phi'(0)=0,\\quad \\phi''(0)=1",
          explanation: "φ has a minimum at the endpoint t=0 with quadratic vanishing.",
        },
        {
          stepNumber: 2,
          description: "Quadratic approximation near t=0.",
          workingLatex: "\\phi(t)\\approx\\frac{1}{2}\\phi''(0)\\,t^{2}=\\frac{t^{2}}{2}",
          explanation: "Because φ'(0)=0, the leading decay is Gaussian, not exponential-linear.",
        },
        {
          stepNumber: 3,
          description: "Half-Gaussian at the endpoint.",
          workingLatex: "\\int_0^{\\infty}e^{-x t^{2}/2}\\,dt=\\frac{1}{2}\\sqrt{\\frac{2\\pi}{x}}=\\sqrt{\\frac{\\pi}{2x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{2x}} \\)",
      canonicalAnswer: "sqrt(pi/(2*x))",
    },
  },
  {
    id: "am2-037",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty} e^{-x t}\\,\\frac{\\sin t}{t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Laplace integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recognise the closed form.",
          workingLatex: "\\int_0^{\\infty}e^{-x t}\\frac{\\sin t}{t}\\,dt=\\operatorname{arccot}(x)=\\arctan\\frac{1}{x}",
          explanation: "Differentiating w.r.t. x gives −1/(x²+1); integrating back with arctan(1/x)→0 fixes the constant.",
        },
        {
          stepNumber: 2,
          description: "Expand arctan(1/x) for large x.",
          workingLatex: "\\arctan\\frac{1}{x}=\\frac{1}{x}-\\frac{1}{3x^{3}}+\\cdots",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{x}-\\frac{1}{3x^{3}} \\)",
      canonicalAnswer: "1/x-1/(3*x^3)",
    },
  },
  {
    id: "am2-038",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the first two terms, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t^{2}}}{1+t}\\,dt \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Gaussian", "mixed powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the amplitude and integrate against the Gaussian kernel.",
          workingLatex: "\\frac{1}{1+t}=1-t+t^{2}-\\cdots,\\qquad \\int_0^{\\infty}t^{n}e^{-x t^{2}}\\,dt=\\frac{1}{2}\\frac{\\Gamma(\\tfrac{n+1}{2})}{x^{(n+1)/2}}",
          explanation: "Even and odd powers give half-integer and integer powers of x respectively.",
        },
        {
          stepNumber: 2,
          description: "Take the n=0 and n=1 contributions.",
          workingLatex: "n=0:\\ \\frac{1}{2}\\frac{\\Gamma(1/2)}{x^{1/2}}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}};\\quad n=1:\\ -\\frac{1}{2}\\frac{\\Gamma(1)}{x}=-\\frac{1}{2x}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Combine.",
          workingLatex: "\\sim\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}-\\frac{1}{2x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}-\\frac{1}{2x} \\)",
      canonicalAnswer: "sqrt(pi/x)/2-1/(2*x)",
    },
  },
  {
    id: "am2-039",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\infty}\\frac{e^{-x t}}{\\sqrt{t}\\,(1+t)}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "Gamma function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Leading small-t power of the amplitude.",
          workingLatex: "\\frac{1}{\\sqrt{t}\\,(1+t)}=t^{-1/2}\\big(1-t+\\cdots\\big)\\sim t^{-1/2}",
          explanation: "α=−1/2 (>−1, so Watson's lemma applies and the integral converges).",
        },
        {
          stepNumber: 2,
          description: "Apply the Watson leading term a₀Γ(α+1)/x^{α+1}.",
          workingLatex: "\\sim\\frac{\\Gamma(1/2)}{x^{1/2}}=\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  // REVIEW: Watson's-lemma proof of the leading term (uniform tail bound + Gamma integral)
  // is standard; rigour of the remainder estimate not machine-checked.
  {
    id: "am2-040",
    topicRef: "am2",
    topicTitle: "Expansion of Integrals; Watson's Lemma",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Prove the leading term of Watson's lemma: if \\( f(t)\\sim a_0 t^{\\alpha} \\) (\\( \\alpha>-1 \\)) as \\( t\\to0^{+} \\) and \\( f \\) grows at most exponentially, then \\( \\displaystyle\\int_0^{\\infty} e^{-x t}f(t)\\,dt\\sim a_0\\dfrac{\\Gamma(\\alpha+1)}{x^{\\alpha+1}} \\) as \\( x\\to\\infty \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Watson's lemma", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Split the range at a small δ.",
          workingLatex: "\\int_0^{\\infty}e^{-x t}f(t)\\,dt=\\int_0^{\\delta}+\\int_{\\delta}^{\\infty}",
          explanation: "The tail beyond δ is exponentially small because f grows at most exponentially.",
        },
        {
          stepNumber: 2,
          description: "Bound the tail.",
          workingLatex: "\\Big|\\int_{\\delta}^{\\infty}e^{-x t}f(t)\\,dt\\Big|\\le C\\int_{\\delta}^{\\infty}e^{-(x-b)t}\\,dt=O\\big(e^{-(x-b)\\delta}\\big)",
          explanation: "Here |f(t)|≤Ce^{bt}; for x>b this is beyond all orders in 1/x.",
        },
        {
          stepNumber: 3,
          description: "On (0,δ) replace f by its leading term with controlled error.",
          workingLatex: "\\int_0^{\\delta}e^{-x t}\\big(a_0 t^{\\alpha}+o(t^{\\alpha})\\big)\\,dt",
          explanation: "The o(t^{α}) part contributes o(x^{−α−1}) by the same Gamma integral with a smaller power.",
        },
        {
          stepNumber: 4,
          description: "Extend to ∞ and evaluate the Gamma integral.",
          workingLatex: "a_0\\int_0^{\\infty}t^{\\alpha}e^{-x t}\\,dt=a_0\\frac{\\Gamma(\\alpha+1)}{x^{\\alpha+1}}",
          explanation: "Extending the upper limit to ∞ only adds an exponentially small error, giving the claimed leading term.",
        },
      ],
      finalAnswer: "\\( \\displaystyle\\int_0^{\\infty}e^{-x t}f(t)\\,dt\\sim a_0\\frac{\\Gamma(\\alpha+1)}{x^{\\alpha+1}} \\) (shown)",
    },
  },
];
