import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — Stationary Phase & Steepest Descent
 * Ref:   am3  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Fresnel integrals and the oscillatory Gamma identity; method of stationary
 * phase (interior, endpoint, degenerate stationary points); Riemann–Lebesgue
 * decay of non-stationary oscillatory integrals; method of steepest descent
 * (real saddles, Gaussian shifts, two-saddle / Airy results).
 *
 * Large parameter is written x (→ +∞). DRAFT (year-3): leading terms verified
 * numerically with mpmath (Fresnel/Gamma identity ∫₀^∞ uˢ⁻¹eⁱᵘ du = Γ(s)e^{iπs/2},
 * Airy special functions). Style pinned to content/undergrad/examples/am3.md.
 * // REVIEW marks oscillatory-Airy / Stokes items. Expert review required.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am3-001",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Fresnel integral \\( \\displaystyle\\int_0^{\\infty}\\cos(t^{2})\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take the real part of the complex Fresnel integral.",
          workingLatex: "\\int_0^{\\infty}e^{i t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\pi}\\,e^{i\\pi/4}",
          explanation: "Rotate the contour onto the steepest-descent ray arg t = π/4; the standard value follows.",
        },
        {
          stepNumber: 2,
          description: "Real part gives the cosine integral.",
          workingLatex: "\\int_0^{\\infty}\\cos(t^{2})\\,dt=\\frac{1}{2}\\sqrt{\\pi}\\cos\\frac{\\pi}{4}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{2}} \\)",
      canonicalAnswer: "sqrt(pi/2)/2",
    },
  },
  {
    id: "am3-002",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate the Fresnel integral \\( \\displaystyle\\int_0^{\\infty}\\sin(t^{2})\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take the imaginary part of the complex Fresnel integral.",
          workingLatex: "\\int_0^{\\infty}\\sin(t^{2})\\,dt=\\frac{1}{2}\\sqrt{\\pi}\\sin\\frac{\\pi}{4}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{2}}",
          explanation: "Im of ½√π e^{iπ/4}; equal to the cosine integral by symmetry of the π/4 phase.",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{2}} \\)",
      canonicalAnswer: "sqrt(pi/2)/2",
    },
  },
  {
    id: "am3-003",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{i t^{2}}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral", "contour rotation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the oscillatory Gamma identity with s=1/2.",
          workingLatex: "\\int_0^{\\infty}t^{s-1}e^{it}\\,dt=\\Gamma(s)e^{i\\pi s/2}",
          explanation: "Substitute u=t² (so the integral becomes this with s=1/2).",
        },
        {
          stepNumber: 2,
          description: "Substitute and simplify.",
          workingLatex: "\\int_0^{\\infty}e^{it^{2}}\\,dt=\\frac{1}{2}\\Gamma\\!\\left(\\tfrac12\\right)e^{i\\pi/4}=\\frac{1}{2}\\sqrt{\\pi}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\pi}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "(1/2)*sqrt(pi)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-004",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i t^{2}}\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The integrand is even, so double the half-line value.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{it^{2}}\\,dt=2\\int_0^{\\infty}e^{it^{2}}\\,dt=2\\cdot\\frac{1}{2}\\sqrt{\\pi}\\,e^{i\\pi/4}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "\\sqrt{\\pi}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\pi}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-005",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the magnitude of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral", "magnitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Scale the Fresnel integral.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{i x t^{2}}\\,dt=\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "Replace t² by xt², i.e. a=x in ∫e^{iat²}dt=√(π/a)e^{iπ/4}.",
        },
        {
          stepNumber: 2,
          description: "Take the modulus (the phase has unit magnitude).",
          workingLatex: "\\left|\\int_{-\\infty}^{\\infty}e^{i x t^{2}}\\,dt\\right|=\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "sqrt(pi/x)",
    },
  },
  {
    id: "am3-006",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "As \\( x\\to\\infty \\), \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{2}}\\,dt \\) scales like \\( x^{p} \\). Find \\( p \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["stationary phase", "scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recall the Fresnel scaling.",
          workingLatex: "\\int_0^{\\infty}e^{i x t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}\\propto x^{-1/2}",
          explanation: "A simple (quadratic) stationary point gives the characteristic x^{−1/2} decay.",
        },
      ],
      finalAnswer: "\\( p=-\\frac{1}{2} \\)",
      canonicalAnswer: "-1/2",
    },
  },
  {
    id: "am3-007",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( \\displaystyle\\lim_{x\\to\\infty}\\int_0^{1}\\cos(x t)\\,dt \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate directly.",
          workingLatex: "\\int_0^{1}\\cos(x t)\\,dt=\\frac{\\sin x}{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Take the limit.",
          workingLatex: "\\frac{\\sin x}{x}\\to0",
          explanation: "This is the Riemann–Lebesgue lemma: with no stationary point the oscillatory integral decays.",
        },
      ],
      finalAnswer: "\\( 0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am3-008",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "As \\( x\\to\\infty \\), \\( \\displaystyle\\int_0^{1} e^{i x t}\\,dt \\) decays like \\( x^{-n} \\). Find \\( n \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue", "endpoint"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "\\int_0^{1}e^{i x t}\\,dt=\\frac{e^{ix}-1}{ix}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Read off the decay rate.",
          workingLatex: "\\left|\\frac{e^{ix}-1}{ix}\\right|=O\\!\\left(\\frac{1}{x}\\right)\\Rightarrow n=1",
          explanation: "With no stationary point, the endpoints give O(1/x) decay.",
        },
      ],
      finalAnswer: "\\( n=1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am3-009",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Find the stationary point of the phase \\( \\phi(t)=t^{2}-4t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["stationary phase", "stationary point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set the derivative to zero.",
          workingLatex: "\\phi'(t)=2t-4=0",
          explanation: "Stationary phase points are where φ'(t)=0.",
        },
        {
          stepNumber: 2,
          description: "Solve.",
          workingLatex: "t=2",
          explanation: "",
        },
      ],
      finalAnswer: "\\( t=2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am3-010",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the interior stationary point of \\( \\phi(t)=\\cos t \\) on \\( (0,2\\pi) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["stationary phase", "stationary point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate and set to zero.",
          workingLatex: "\\phi'(t)=-\\sin t=0\\Rightarrow t=\\pi\\ \\text{in }(0,2\\pi)",
          explanation: "t=0,2π are endpoints; the interior root is t=π.",
        },
      ],
      finalAnswer: "\\( t=\\pi \\)",
      canonicalAnswer: "pi",
    },
  },
  {
    id: "am3-011",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "An oscillatory integral with a single simple stationary point decays like \\( x^{-p} \\) as \\( x\\to\\infty \\). State \\( p \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["stationary phase", "scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The local width of the stationary region scales like x^{−1/2}.",
          workingLatex: "\\phi(t)\\approx\\phi(t_0)+\\tfrac12\\phi''(t_0)(t-t_0)^{2}\\Rightarrow \\text{width}\\sim x^{-1/2}",
          explanation: "The quadratic phase gives a Fresnel-width contribution of order x^{−1/2}.",
        },
        {
          stepNumber: 2,
          description: "State the decay exponent.",
          workingLatex: "p=\\frac{1}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( p=\\frac{1}{2} \\)",
      canonicalAnswer: "1/2",
    },
  },
  {
    id: "am3-012",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the argument (phase) of \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-i x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Fresnel integral", "phase"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Conjugate of the standard Fresnel integral.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{-i x t^{2}}\\,dt=\\sqrt{\\frac{\\pi}{x}}\\,e^{-i\\pi/4}",
          explanation: "Negating the phase reflects the steepest-descent ray to arg t = −π/4.",
        },
        {
          stepNumber: 2,
          description: "Read off the argument.",
          workingLatex: "\\arg=-\\frac{\\pi}{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\frac{\\pi}{4} \\)",
      canonicalAnswer: "-pi/4",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am3-013",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral", "stationary phase"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rotate the contour to the steepest-descent ray t=e^{iπ/4}s.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{i x t^{2}}\\,dt=e^{i\\pi/4}\\int_{-\\infty}^{\\infty}e^{-x s^{2}}\\,ds",
          explanation: "On t=e^{iπ/4}s the phase ixt² becomes −xs², a real Gaussian.",
        },
        {
          stepNumber: 2,
          description: "Evaluate the Gaussian.",
          workingLatex: "e^{i\\pi/4}\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-014",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{2}}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Half of the even full-line integral.",
          workingLatex: "\\int_0^{\\infty}e^{i x t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "(1/2)*sqrt(pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-015",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty}\\cos(x t^{2})\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Real part of the scaled Fresnel integral.",
          workingLatex: "\\int_0^{\\infty}\\cos(x t^{2})\\,dt=\\operatorname{Re}\\Big(\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}e^{i\\pi/4}\\Big)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use cos(π/4)=1/√2.",
          workingLatex: "\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\cdot\\frac{1}{\\sqrt2}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{2x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{2x}} \\)",
      canonicalAnswer: "sqrt(pi/(2*x))/2",
    },
  },
  {
    id: "am3-016",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty}\\sin(x t^{2})\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Imaginary part of the scaled Fresnel integral.",
          workingLatex: "\\int_0^{\\infty}\\sin(x t^{2})\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\sin\\frac{\\pi}{4}=\\frac{1}{2}\\sqrt{\\frac{\\pi}{2x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{2x}} \\)",
      canonicalAnswer: "sqrt(pi/(2*x))/2",
    },
  },
  {
    id: "am3-017",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{3}}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["oscillatory integral", "Gamma identity"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute u=x t³.",
          workingLatex: "u=x t^{3},\\quad \\int_0^{\\infty}e^{i x t^{3}}\\,dt=\\frac{1}{3}x^{-1/3}\\int_0^{\\infty}u^{-2/3}e^{iu}\\,du",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply ∫₀^∞ u^{s−1}e^{iu}du = Γ(s)e^{iπs/2} with s=1/3.",
          workingLatex: "\\frac{1}{3}x^{-1/3}\\,\\Gamma\\!\\left(\\tfrac13\\right)e^{i\\pi/6}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{3}\\,\\Gamma\\!\\left(\\tfrac13\\right)x^{-1/3}e^{i\\pi/6} \\)",
      canonicalAnswer: "(1/3)*gamma(1/3)*x^(-1/3)*exp(I*pi/6)",
    },
  },
  {
    id: "am3-018",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "As \\( x\\to\\infty \\), \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{4}}\\,dt \\) scales like \\( x^{p} \\). Find \\( p \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["oscillatory integral", "scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute u=x t⁴.",
          workingLatex: "\\int_0^{\\infty}e^{i x t^{4}}\\,dt=\\frac{1}{4}x^{-1/4}\\int_0^{\\infty}u^{-3/4}e^{iu}\\,du",
          explanation: "A degenerate (quartic) stationary point at t=0 gives x^{−1/4}.",
        },
        {
          stepNumber: 2,
          description: "Read off the exponent.",
          workingLatex: "p=-\\frac{1}{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( p=-\\frac{1}{4} \\)",
      canonicalAnswer: "-1/4",
    },
  },
  {
    id: "am3-019",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i x (t^{2}+2t)}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "completing the square"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Complete the square in the phase.",
          workingLatex: "t^{2}+2t=(t+1)^{2}-1",
          explanation: "The stationary point is at t=−1.",
        },
        {
          stepNumber: 2,
          description: "Shift and apply the Fresnel integral.",
          workingLatex: "e^{-ix}\\int_{-\\infty}^{\\infty}e^{i x s^{2}}\\,ds=e^{-ix}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}}\\,e^{i(\\pi/4-x)} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(I*(pi/4-x))",
    },
  },
  {
    id: "am3-020",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "An amplitude \\( g \\) with \\( g(0)=2 \\) gives \\( \\displaystyle\\int_{-\\infty}^{\\infty} g(t)\\,e^{i x t^{2}}\\,dt \\). State the magnitude of its leading term as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Replace the amplitude by its value at the stationary point.",
          workingLatex: "\\int_{-\\infty}^{\\infty}g(t)e^{i x t^{2}}\\,dt\\sim g(0)\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "Only the amplitude at the stationary point t=0 survives at leading order.",
        },
        {
          stepNumber: 2,
          description: "Take the magnitude with g(0)=2.",
          workingLatex: "\\Big|2\\sqrt{\\tfrac{\\pi}{x}}e^{i\\pi/4}\\Big|=2\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "2*sqrt(pi/x)",
    },
  },
  {
    id: "am3-021",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{-t^{2}}e^{i x t^{2}}\\,dt \\) in closed form, and give its leading behaviour as \\( x\\to\\infty \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Gaussian", "stationary phase"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Combine the exponents into one Gaussian.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{-(1-ix)t^{2}}\\,dt=\\sqrt{\\frac{\\pi}{1-ix}}",
          explanation: "Standard Gaussian with complex coefficient (Re>0).",
        },
        {
          stepNumber: 2,
          description: "Large-x limit.",
          workingLatex: "\\sqrt{\\frac{\\pi}{1-ix}}\\sim\\sqrt{\\frac{\\pi}{-ix}}=\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "1/√(−i)=e^{iπ/4}, recovering the Fresnel phase.",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{1-ix}}\\sim\\sqrt{\\dfrac{\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-022",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Use the method of steepest descent (a real saddle) to evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{x(t-t^{2})}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Complete the square to find the saddle.",
          workingLatex: "t-t^{2}=\\frac{1}{4}-\\Big(t-\\frac12\\Big)^{2}",
          explanation: "Maximum (saddle on the real axis) at t=1/2 with value 1/4.",
        },
        {
          stepNumber: 2,
          description: "Gaussian integral about the saddle.",
          workingLatex: "e^{x/4}\\int_{-\\infty}^{\\infty}e^{-x s^{2}}\\,ds=e^{x/4}\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x/4}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x/4)*sqrt(pi/x)",
    },
  },
  {
    id: "am3-023",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{x(2t-t^{2})}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Complete the square.",
          workingLatex: "2t-t^{2}=1-(t-1)^{2}",
          explanation: "Saddle at t=1, value 1.",
        },
        {
          stepNumber: 2,
          description: "Gaussian about the saddle.",
          workingLatex: "e^{x}\\sqrt{\\frac{\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}\\sqrt{\\dfrac{\\pi}{x}} \\)",
      canonicalAnswer: "exp(x)*sqrt(pi/x)",
    },
  },
  {
    id: "am3-024",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} e^{i x t}\\,dt \\) coming from the endpoint \\( t=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue", "endpoint", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate exactly.",
          workingLatex: "\\int_0^{1}e^{i x t}\\,dt=\\frac{e^{ix}-1}{ix}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Isolate the non-oscillating endpoint piece.",
          workingLatex: "=\\frac{e^{ix}}{ix}-\\frac{1}{ix},\\qquad \\text{(t=0 piece)}=-\\frac{1}{ix}=\\frac{i}{x}",
          explanation: "The t=1 piece oscillates as e^{ix}; the t=0 endpoint gives i/x.",
        },
      ],
      finalAnswer: "\\( \\dfrac{i}{x} \\)",
      canonicalAnswer: "I/x",
    },
  },
  {
    id: "am3-025",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order term, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} t\\,e^{i x t}\\,dt \\) coming from the endpoint \\( t=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue", "endpoint", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate by parts.",
          workingLatex: "\\int_0^{1}t\\,e^{i x t}\\,dt=\\Big[\\frac{t\\,e^{ixt}}{ix}\\Big]_0^{1}-\\frac{1}{ix}\\int_0^{1}e^{ixt}\\,dt",
          explanation: "The boundary term at t=1 dominates at O(1/x).",
        },
        {
          stepNumber: 2,
          description: "Take the t=1 boundary contribution.",
          workingLatex: "\\frac{e^{ix}}{ix}=-\\frac{i\\,e^{ix}}{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\dfrac{i\\,e^{ix}}{x} \\)",
      canonicalAnswer: "-I*exp(I*x)/x",
    },
  },
  {
    id: "am3-026",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find the stationary points of the phase \\( \\phi(t)=\\tfrac13 t^{3}-t \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "stationary point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate and set to zero.",
          workingLatex: "\\phi'(t)=t^{2}-1=0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve.",
          workingLatex: "t=\\pm1",
          explanation: "Two simple stationary points; their contributions interfere (Airy-type behaviour).",
        },
      ],
      finalAnswer: "\\( t=\\pm1 \\)",
      canonicalAnswer: "{-1, 1}",
    },
  },
  {
    id: "am3-027",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the phase \\( \\phi(t)=\\tfrac13 t^{3}-t \\), the stationary point \\( t=1 \\) contributes a phase factor \\( e^{i\\theta} \\) from the Fresnel rotation. Find \\( \\theta \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "phase factor"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute the sign of the second derivative.",
          workingLatex: "\\phi''(t)=2t,\\qquad \\phi''(1)=2>0",
          explanation: "A positive φ'' gives the +π/4 Fresnel rotation.",
        },
        {
          stepNumber: 2,
          description: "State the rotation phase.",
          workingLatex: "\\theta=+\\frac{\\pi}{4}",
          explanation: "(The point t=−1, with φ''=−2<0, would give −π/4.)",
        },
      ],
      finalAnswer: "\\( \\theta=\\frac{\\pi}{4} \\)",
      canonicalAnswer: "pi/4",
    },
  },
  {
    id: "am3-028",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_{-\\infty}^{\\infty}\\frac{e^{i x t^{2}}}{1+t^{2}}\\,dt \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Amplitude value at the stationary point t=0.",
          workingLatex: "\\frac{1}{1+t^{2}}\\Big|_{t=0}=1",
          explanation: "The stationary point is at t=0; only g(0) matters at leading order.",
        },
        {
          stepNumber: 2,
          description: "Apply the Fresnel leading term.",
          workingLatex: "\\sim\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-029",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i x t^{2}/2}\\,dt \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply ∫e^{iat²}dt=√(π/a)e^{iπ/4} with a=x/2.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{i x t^{2}/2}\\,dt=\\sqrt{\\frac{\\pi}{x/2}}\\,e^{i\\pi/4}=\\sqrt{\\frac{2\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{2\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-030",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "If a smooth phase \\( \\phi \\) has no stationary point on \\( [a,b] \\) (\\( \\phi'\\neq0 \\) throughout), then \\( \\int_a^b g\\,e^{i x\\phi}\\,dt=O(x^{-n}) \\). State \\( n \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue", "integration by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate by parts once.",
          workingLatex: "\\int_a^b g\\,e^{i x\\phi}\\,dt=\\Big[\\frac{g}{i x\\phi'}e^{i x\\phi}\\Big]_a^b-\\frac{1}{ix}\\int_a^b\\Big(\\frac{g}{\\phi'}\\Big)'e^{i x\\phi}\\,dt",
          explanation: "Possible because φ'≠0; the boundary term is O(1/x).",
        },
        {
          stepNumber: 2,
          description: "Read off the order.",
          workingLatex: "n=1",
          explanation: "Each integration by parts gains a further factor 1/x.",
        },
      ],
      finalAnswer: "\\( n=1 \\)",
      canonicalAnswer: "1",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am3-031",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order stationary-phase contribution, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{\\pi} e^{i x\\sin t}\\,dt \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "interior maximum"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Locate and classify the interior stationary point.",
          workingLatex: "\\frac{d}{dt}\\sin t=\\cos t=0\\Rightarrow t=\\frac{\\pi}{2},\\quad \\sin\\tfrac\\pi2=1,\\ \\phi''=-\\sin\\tfrac\\pi2=-1",
          explanation: "Interior stationary point; φ''<0 gives the −π/4 rotation.",
        },
        {
          stepNumber: 2,
          description: "Apply the stationary-phase formula.",
          workingLatex: "\\int g\\,e^{i x\\phi}\\,dt\\sim g(t_0)\\sqrt{\\frac{2\\pi}{x|\\phi''|}}\\,e^{i x\\phi(t_0)+i\\,\\mathrm{sgn}(\\phi'')\\pi/4}",
          explanation: "Here g=1, |φ''|=1.",
        },
        {
          stepNumber: 3,
          description: "Substitute.",
          workingLatex: "\\sim\\sqrt{\\frac{2\\pi}{x}}\\,e^{i(x-\\pi/4)}",
          explanation: "The endpoints t=0,π contribute only O(1/x), so this is the leading term.",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{2\\pi}{x}}\\,e^{i(x-\\pi/4)} \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(I*(x-pi/4))",
    },
  },
  {
    id: "am3-032",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that, as \\( x\\to\\infty \\), \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{i x(\\tfrac13 t^{3}-t)}\\,dt\\sim 2\\sqrt{\\frac{\\pi}{x}}\\cos\\!\\Big(\\frac{2x}{3}-\\frac{\\pi}{4}\\Big) \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "two saddles", "Airy"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Stationary points and data.",
          workingLatex: "\\phi'=t^{2}-1=0\\Rightarrow t=\\pm1;\\quad \\phi(\\pm1)=\\mp\\tfrac23,\\ \\phi''(\\pm1)=\\pm2",
          explanation: "Two simple stationary points contribute and interfere.",
        },
        {
          stepNumber: 2,
          description: "Apply stationary phase at each point.",
          workingLatex: "t=1:\\ \\sqrt{\\frac{\\pi}{x}}e^{-2ix/3+i\\pi/4};\\quad t=-1:\\ \\sqrt{\\frac{\\pi}{x}}e^{+2ix/3-i\\pi/4}",
          explanation: "Using √(2π/(x|φ''|))=√(π/x) since |φ''|=2.",
        },
        {
          stepNumber: 3,
          description: "Add the conjugate pair.",
          workingLatex: "\\sqrt{\\frac{\\pi}{x}}\\Big(e^{-i(2x/3-\\pi/4)}+e^{+i(2x/3-\\pi/4)}\\Big)=2\\sqrt{\\frac{\\pi}{x}}\\cos\\!\\Big(\\frac{2x}{3}-\\frac{\\pi}{4}\\Big)",
          explanation: "Consistent with 2π x^{−1/3}Ai(−x^{2/3}) and the Airy oscillatory asymptotic.",
        },
      ],
      finalAnswer: "\\( 2\\sqrt{\\dfrac{\\pi}{x}}\\cos\\!\\Big(\\dfrac{2x}{3}-\\dfrac{\\pi}{4}\\Big) \\) (shown)",
      canonicalAnswer: "2*sqrt(pi/x)*cos(2*x/3-pi/4)",
    },
  },
  {
    id: "am3-033",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty} e^{x(i t-\\tfrac12 t^{2})}\\,dt \\) for \\( x>0 \\) by completing the square / shifting the contour.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Gaussian shift"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Complete the square in t.",
          workingLatex: "i t-\\tfrac12 t^{2}=-\\tfrac12(t-i)^{2}-\\tfrac12",
          explanation: "The saddle is at t=i (off the real axis); shift the contour to pass through it.",
        },
        {
          stepNumber: 2,
          description: "Evaluate the shifted Gaussian.",
          workingLatex: "e^{-x/2}\\int_{-\\infty}^{\\infty}e^{-x s^{2}/2}\\,ds=e^{-x/2}\\sqrt{\\frac{2\\pi}{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{2\\pi}{x}}\\,e^{-x/2} \\)",
      canonicalAnswer: "sqrt(2*pi/x)*exp(-x/2)",
    },
  },
  {
    id: "am3-034",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Evaluate \\( \\displaystyle\\int_0^{\\infty} e^{i x t^{4}}\\,dt \\) for \\( x>0 \\) using the oscillatory Gamma identity.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["oscillatory integral", "degenerate stationary point", "Gamma identity"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute u=x t⁴.",
          workingLatex: "\\int_0^{\\infty}e^{i x t^{4}}\\,dt=\\frac{1}{4}x^{-1/4}\\int_0^{\\infty}u^{-3/4}e^{iu}\\,du",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply ∫₀^∞ u^{s−1}e^{iu}du=Γ(s)e^{iπs/2} with s=1/4.",
          workingLatex: "\\frac{1}{4}x^{-1/4}\\,\\Gamma\\!\\left(\\tfrac14\\right)e^{i\\pi/8}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{1}{4}\\,\\Gamma\\!\\left(\\tfrac14\\right)x^{-1/4}e^{i\\pi/8} \\)",
      canonicalAnswer: "(1/4)*gamma(1/4)*x^(-1/4)*exp(I*pi/8)",
    },
  },
  // REVIEW: Airy steepest-descent leading term is the classical result; the saddle-point
  // contour deformation was not machine-checked beyond the numerical asymptotic ratio.
  {
    id: "am3-035",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "State the leading steepest-descent asymptotic of the Airy function \\( \\mathrm{Ai}(x) \\) as \\( x\\to+\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["steepest descent", "Airy function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Airy integral and its saddle.",
          workingLatex: "\\mathrm{Ai}(x)=\\frac{1}{2\\pi}\\int_{-\\infty}^{\\infty}e^{i(s^{3}/3+xs)}\\,ds",
          explanation: "For x>0 the saddle is at s=i√x on the imaginary axis (real exponent there).",
        },
        {
          stepNumber: 2,
          description: "Steepest descent through the saddle.",
          workingLatex: "\\mathrm{Ai}(x)\\sim\\frac{1}{2\\sqrt{\\pi}}\\,x^{-1/4}\\exp\\!\\Big(-\\frac{2}{3}x^{3/2}\\Big)",
          explanation: "The exponential decay rate is the saddle value −⅔x^{3/2}.",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{2\\sqrt{\\pi}}\\,x^{-1/4}\\exp\\!\\big(-\\tfrac23 x^{3/2}\\big) \\)",
      canonicalAnswer: "(1/(2*sqrt(pi)))*x^(-1/4)*exp(-(2/3)*x^(3/2))",
    },
  },
  {
    id: "am3-036",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Prove that if \\( g,\\phi \\) are smooth on \\( [a,b] \\) with \\( \\phi'\\neq0 \\) throughout, then \\( \\displaystyle\\int_a^b g(t)\\,e^{i x\\phi(t)}\\,dt=O(x^{-1}) \\) as \\( x\\to\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Riemann–Lebesgue", "integration by parts", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rewrite the integrand to expose a derivative of the exponential.",
          workingLatex: "e^{i x\\phi}=\\frac{1}{i x\\phi'}\\frac{d}{dt}\\big(e^{i x\\phi}\\big)",
          explanation: "Valid because φ'≠0 everywhere on [a,b].",
        },
        {
          stepNumber: 2,
          description: "Integrate by parts.",
          workingLatex: "\\int_a^b g\\,e^{i x\\phi}\\,dt=\\Big[\\frac{g}{i x\\phi'}e^{i x\\phi}\\Big]_a^b-\\frac{1}{i x}\\int_a^b\\Big(\\frac{g}{\\phi'}\\Big)'e^{i x\\phi}\\,dt",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Bound both pieces.",
          workingLatex: "|\\,\\cdot\\,|\\le\\frac{1}{x}\\Big(\\Big|\\tfrac{g}{\\phi'}\\Big|_a^b+\\int_a^b\\big|(g/\\phi')'\\big|\\,dt\\Big)=O\\!\\Big(\\frac{1}{x}\\Big)",
          explanation: "Both the boundary term and the remaining integral carry a factor 1/x, and g/φ' and its derivative are bounded on the compact interval.",
        },
      ],
      finalAnswer: "\\( \\int_a^b g\\,e^{i x\\phi}\\,dt=O(x^{-1}) \\) (shown)",
    },
  },
  {
    id: "am3-037",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading-order behaviour, as \\( x\\to\\infty \\), of \\( \\displaystyle\\int_0^{1} e^{i x t^{2}}\\,dt \\), explaining the role of the endpoint \\( t=0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "endpoint stationary point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Identify the stationary point.",
          workingLatex: "\\phi(t)=t^{2},\\quad \\phi'(t)=2t=0\\Rightarrow t=0",
          explanation: "The stationary point sits exactly at the endpoint t=0, so only half the Fresnel contribution is captured.",
        },
        {
          stepNumber: 2,
          description: "Half-Fresnel from the endpoint.",
          workingLatex: "\\int_0^{\\infty}e^{i x t^{2}}\\,dt=\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "Extending to ∞ only adds the t=1 endpoint piece, which is O(1/x).",
        },
        {
          stepNumber: 3,
          description: "State the leading term.",
          workingLatex: "\\int_0^{1}e^{i x t^{2}}\\,dt\\sim\\frac{1}{2}\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}",
          explanation: "The O(x^{−1/2}) endpoint-stationary term dominates the O(x^{−1}) contribution from t=1.",
        },
      ],
      finalAnswer: "\\( \\frac{1}{2}\\sqrt{\\dfrac{\\pi}{x}}\\,e^{i\\pi/4} \\)",
      canonicalAnswer: "(1/2)*sqrt(pi/x)*exp(I*pi/4)",
    },
  },
  {
    id: "am3-038",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the stationary-phase leading term: for a simple interior stationary point \\( t_0 \\) with \\( \\phi''(t_0)>0 \\), show \\( \\displaystyle\\int g(t)e^{i x\\phi(t)}\\,dt\\sim g(t_0)e^{i x\\phi(t_0)}\\sqrt{\\frac{2\\pi}{x\\phi''(t_0)}}\\,e^{i\\pi/4} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Localise near the stationary point.",
          workingLatex: "\\text{Away from }t_0,\\ \\phi'\\neq0\\Rightarrow O(x^{-1})\\ \\text{(Riemann–Lebesgue)}",
          explanation: "Only a shrinking neighbourhood of t₀ contributes at leading order.",
        },
        {
          stepNumber: 2,
          description: "Taylor-expand the phase and freeze the amplitude.",
          workingLatex: "\\phi(t)\\approx\\phi(t_0)+\\tfrac12\\phi''(t_0)(t-t_0)^{2},\\quad g(t)\\approx g(t_0)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Reduce to a Fresnel integral.",
          workingLatex: "g(t_0)e^{i x\\phi(t_0)}\\int_{-\\infty}^{\\infty}e^{i x\\phi''(t_0)s^{2}/2}\\,ds",
          explanation: "Extending the limits to ±∞ adds only exponentially-corrected error.",
        },
        {
          stepNumber: 4,
          description: "Evaluate the Fresnel integral.",
          workingLatex: "\\int_{-\\infty}^{\\infty}e^{i a s^{2}/2}\\,ds=\\sqrt{\\frac{2\\pi}{a}}\\,e^{i\\pi/4}\\ (a>0)\\Rightarrow g(t_0)e^{i x\\phi(t_0)}\\sqrt{\\frac{2\\pi}{x\\phi''(t_0)}}\\,e^{i\\pi/4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( g(t_0)e^{i x\\phi(t_0)}\\sqrt{\\frac{2\\pi}{x\\phi''(t_0)}}\\,e^{i\\pi/4} \\) (shown)",
    },
  },
  {
    id: "am3-039",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{-\\infty}^{\\infty}\\cos(x t^{2})\\,dt \\) for \\( x>0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Fresnel integral"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Real part of the full-line Fresnel integral.",
          workingLatex: "\\int_{-\\infty}^{\\infty}\\cos(x t^{2})\\,dt=\\operatorname{Re}\\Big(\\sqrt{\\frac{\\pi}{x}}\\,e^{i\\pi/4}\\Big)=\\sqrt{\\frac{\\pi}{x}}\\cos\\frac{\\pi}{4}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify using cos(π/4)=1/√2.",
          workingLatex: "\\sqrt{\\frac{\\pi}{x}}\\cdot\\frac{1}{\\sqrt2}=\\sqrt{\\frac{\\pi}{2x}}",
          explanation: "Check at x=1: √(π/2)=1.2533=∫_{−∞}^{∞}cos(t²)dt.",
        },
      ],
      finalAnswer: "\\( \\sqrt{\\dfrac{\\pi}{2x}} \\)",
      canonicalAnswer: "sqrt(pi/(2*x))",
    },
  },
  // REVIEW: oscillatory Airy (Ai of a negative argument) asymptotic — standard result, but
  // the connection-formula/phase was not machine-verified here beyond the structural match.
  {
    id: "am3-040",
    topicRef: "am3",
    topicTitle: "Stationary Phase & Steepest Descent",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "State the leading oscillatory asymptotic of \\( \\mathrm{Ai}(-x) \\) as \\( x\\to+\\infty \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["stationary phase", "Airy function"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "For a negative argument the two saddles are real and interfere.",
          workingLatex: "\\mathrm{Ai}(-x)=\\frac{1}{2\\pi}\\int_{-\\infty}^{\\infty}e^{i(s^{3}/3-xs)}\\,ds",
          explanation: "Stationary points at s=±√x produce an oscillatory (cosine/sine) result.",
        },
        {
          stepNumber: 2,
          description: "Combine the two stationary-phase contributions.",
          workingLatex: "\\mathrm{Ai}(-x)\\sim\\frac{1}{\\sqrt{\\pi}}\\,x^{-1/4}\\sin\\!\\Big(\\frac{2}{3}x^{3/2}+\\frac{\\pi}{4}\\Big)",
          explanation: "Compare am3-032: the same two-saddle interference gives the sine with the π/4 Fresnel offset.",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{\\sqrt{\\pi}}\\,x^{-1/4}\\sin\\!\\Big(\\tfrac23 x^{3/2}+\\tfrac{\\pi}{4}\\Big) \\)",
      canonicalAnswer: "(1/sqrt(pi))*x^(-1/4)*sin((2/3)*x^(3/2)+pi/4)",
    },
  },
];
