import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — Regular & Singular Perturbation; Matched Asymptotics
 * Ref:   am4  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Regular perturbation of polynomial roots and ODEs; singular perturbation,
 * lost roots and dominant-balance rescaling; boundary layers (location, width,
 * inner/outer solutions); Van Dyke matching and additive composite expansions.
 *
 * NO exemplar was supplied for this subtopic — authored from the standard theory.
 * DRAFT (year-3): boundary-layer composites checked against exact constant-
 * coefficient BVP solutions and root expansions against numerical roots (mpmath).
 * // REVIEW marks variable-coefficient / higher-correction items. Expert review
 * required before student use.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am4-001",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( \\varepsilon y''+y'+y=0 \\) on \\( [0,1] \\) with \\( 0<\\varepsilon\\ll1 \\), at which endpoint does the boundary layer sit?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "location"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the sign of the first-derivative coefficient.",
          workingLatex: "\\varepsilon y''+a\\,y'+\\cdots,\\quad a=+1>0",
          explanation: "For constant a>0 the layer is at the left endpoint; for a<0 it is at the right.",
        },
        {
          stepNumber: 2,
          description: "State the location.",
          workingLatex: "x=0",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x=0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am4-002",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "The boundary layer of \\( \\varepsilon y''+y'+y=0 \\) has width \\( \\delta\\sim\\varepsilon^{p} \\). Find \\( p \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "width", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance the highest derivative against the first.",
          workingLatex: "\\varepsilon y''\\sim y'\\Rightarrow \\frac{\\varepsilon}{\\delta^{2}}\\sim\\frac{1}{\\delta}",
          explanation: "Inside the layer y varies on the scale δ.",
        },
        {
          stepNumber: 2,
          description: "Solve for δ.",
          workingLatex: "\\delta\\sim\\varepsilon\\Rightarrow p=1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( p=1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am4-003",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the outer (reduced) equation for \\( \\varepsilon y''+y'+y=0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "outer equation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set ε=0.",
          workingLatex: "y'+y=0",
          explanation: "The outer solution solves the reduced first-order equation; it cannot meet both boundary conditions.",
        },
      ],
      finalAnswer: "\\( y'+y=0 \\)",
      canonicalAnswer: "y'+y=0",
    },
  },
  {
    id: "am4-004",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For a boundary layer of width \\( \\varepsilon \\) at \\( x=0 \\), write the stretched inner variable \\( X \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "inner variable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rescale the layer to O(1) width.",
          workingLatex: "X=\\frac{x}{\\varepsilon}",
          explanation: "This magnifies the thin layer so that derivatives become O(1) in X.",
        },
      ],
      finalAnswer: "\\( X=\\dfrac{x}{\\varepsilon} \\)",
      canonicalAnswer: "x/epsilon",
    },
  },
  {
    id: "am4-005",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Find the leading-order value of the root of \\( x^{2}+\\varepsilon x-1=0 \\) near \\( +1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["regular perturbation", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set ε=0.",
          workingLatex: "x^{2}-1=0\\Rightarrow x=\\pm1",
          explanation: "The leading-order root near +1 is x=1.",
        },
      ],
      finalAnswer: "\\( x=1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am4-006",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the root of \\( x^{2}+\\varepsilon x-1=0 \\) near \\( +1 \\) to two terms in \\( \\varepsilon \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["regular perturbation", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit x=1+aε and substitute.",
          workingLatex: "(1+a\\varepsilon)^{2}+\\varepsilon(1+a\\varepsilon)-1=0\\Rightarrow 2a\\varepsilon+\\varepsilon=O(\\varepsilon^{2})",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve for a.",
          workingLatex: "2a+1=0\\Rightarrow a=-\\tfrac12\\Rightarrow x\\sim1-\\tfrac{\\varepsilon}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim1-\\dfrac{\\varepsilon}{2} \\)",
      canonicalAnswer: "1-epsilon/2",
    },
  },
  {
    id: "am4-007",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The quadratic \\( \\varepsilon x^{2}+x-1=0 \\) has a root that diverges as \\( \\varepsilon\\to0 \\). Give its leading behaviour.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["singular perturbation", "lost root"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance the two largest terms.",
          workingLatex: "\\varepsilon x^{2}\\sim -x\\Rightarrow x\\sim-\\frac{1}{\\varepsilon}",
          explanation: "Setting ε=0 lowers the degree and loses this root; it reappears at the scale x=O(ε^{−1}).",
        },
      ],
      finalAnswer: "\\( x\\sim-\\dfrac{1}{\\varepsilon} \\)",
      canonicalAnswer: "-1/epsilon",
    },
  },
  {
    id: "am4-008",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "By dominant balance, find the layer width \\( \\delta \\) for \\( \\varepsilon y''+y'=0 \\)-type behaviour.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "width", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance εy'' against y'.",
          workingLatex: "\\frac{\\varepsilon}{\\delta^{2}}\\sim\\frac{1}{\\delta}\\Rightarrow\\delta\\sim\\varepsilon",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\delta\\sim\\varepsilon \\)",
      canonicalAnswer: "epsilon",
    },
  },
  {
    id: "am4-009",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( \\varepsilon y''-y'+y=0 \\) on \\( [0,1] \\), at which endpoint is the boundary layer?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["boundary layer", "location"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The coefficient of y' is negative.",
          workingLatex: "a=-1<0\\Rightarrow \\text{layer at the right endpoint}",
          explanation: "A negative a pushes the rapidly-varying region to x=1.",
        },
      ],
      finalAnswer: "\\( x=1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am4-010",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "An outer solution of a second-order singularly-perturbed BVP solves a first-order equation. How many of the two boundary conditions can it satisfy?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["singular perturbation", "outer solution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Count constants of integration.",
          workingLatex: "\\text{first order}\\Rightarrow 1\\text{ arbitrary constant}\\Rightarrow 1\\text{ BC}",
          explanation: "The other BC is recovered by the boundary layer.",
        },
      ],
      finalAnswer: "\\( 1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am4-011",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "How many roots of \\( \\varepsilon x^{3}-x+1=0 \\) tend to \\( \\infty \\) as \\( \\varepsilon\\to0 \\)?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["singular perturbation", "lost roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compare degree before and after setting ε=0.",
          workingLatex: "3\\to1\\Rightarrow 3-1=2\\text{ lost roots}",
          explanation: "The reduced equation −x+1=0 keeps one root; two diverge (to the balance εx³~x, x~±ε^{−1/2}).",
        },
      ],
      finalAnswer: "\\( 2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am4-012",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "How many roots of \\( \\varepsilon x^{2}+x-1=0 \\) are 'lost' when \\( \\varepsilon=0 \\)?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["singular perturbation", "lost roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Degree drops from 2 to 1.",
          workingLatex: "2-1=1",
          explanation: "One root escapes to infinity (x~−1/ε).",
        },
      ],
      finalAnswer: "\\( 1 \\)",
      canonicalAnswer: "1",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am4-013",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve the outer problem for \\( \\varepsilon y''+y'+y=0 \\) with \\( y(1)=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "outer solution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solve the reduced equation.",
          workingLatex: "y'+y=0\\Rightarrow y_{\\text{out}}=Ce^{-x}",
          explanation: "The outer solution must satisfy the boundary condition at x=1 (the layer is at x=0).",
        },
        {
          stepNumber: 2,
          description: "Apply y(1)=1.",
          workingLatex: "Ce^{-1}=1\\Rightarrow C=e\\Rightarrow y_{\\text{out}}=e^{1-x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{out}}=e^{1-x} \\)",
      canonicalAnswer: "exp(1-x)",
    },
  },
  {
    id: "am4-014",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the outer solution \\( y_{\\text{out}}=e^{1-x} \\) of \\( \\varepsilon y''+y'+y=0 \\), find the matching value \\( \\lim_{x\\to0^{+}}y_{\\text{out}} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matching", "outer solution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Evaluate the outer solution at x=0.",
          workingLatex: "y_{\\text{out}}(0)=e^{1-0}=e",
          explanation: "This is the value the inner solution must approach as X→∞.",
        },
      ],
      finalAnswer: "\\( e \\)",
      canonicalAnswer: "e",
    },
  },
  {
    id: "am4-015",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the leading inner solution of \\( \\varepsilon y''+y'+y=0 \\) near \\( x=0 \\) with \\( y(0)=0 \\), matched to the outer value \\( e \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "inner solution", "matching"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rescale X=x/ε and take the leading balance.",
          workingLatex: "Y''+Y'=0\\Rightarrow Y=A+Be^{-X}",
          explanation: "At leading order the y term is negligible inside the layer.",
        },
        {
          stepNumber: 2,
          description: "Apply Y(0)=0 and match Y(∞)=e.",
          workingLatex: "A+B=0,\\quad A=e\\Rightarrow B=-e",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Write the inner solution.",
          workingLatex: "y_{\\text{in}}=e\\big(1-e^{-x/\\varepsilon}\\big)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{in}}=e\\big(1-e^{-x/\\varepsilon}\\big) \\)",
      canonicalAnswer: "e*(1-exp(-x/epsilon))",
    },
  },
  {
    id: "am4-016",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the leading additive composite (uniform) approximation for \\( \\varepsilon y''+y'+y=0 \\), \\( y(0)=0 \\), \\( y(1)=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matched asymptotics", "composite"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Add outer and inner, subtract the common part e.",
          workingLatex: "y\\approx e^{1-x}+e\\big(1-e^{-x/\\varepsilon}\\big)-e",
          explanation: "The common (overlap) value is e.",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "y\\approx e^{1-x}-e^{\\,1-x/\\varepsilon}",
          explanation: "Satisfies y(0)=0 and y(1)≈1 to exponential accuracy.",
        },
      ],
      finalAnswer: "\\( y\\approx e^{1-x}-e^{\\,1-x/\\varepsilon} \\)",
      canonicalAnswer: "exp(1-x)-exp(1-x/epsilon)",
    },
  },
  {
    id: "am4-017",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the root of \\( x^{2}-(3+\\varepsilon)x+2=0 \\) near \\( 1 \\) to two terms in \\( \\varepsilon \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit x=1+aε and expand.",
          workingLatex: "(1+a\\varepsilon)^{2}-(3+\\varepsilon)(1+a\\varepsilon)+2=-(a+1)\\varepsilon+O(\\varepsilon^{2})",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Set the O(ε) term to zero.",
          workingLatex: "a+1=0\\Rightarrow a=-1\\Rightarrow x\\sim1-\\varepsilon",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim1-\\varepsilon \\)",
      canonicalAnswer: "1-epsilon",
    },
  },
  {
    id: "am4-018",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the root of \\( x^{2}-(3+\\varepsilon)x+2=0 \\) near \\( 2 \\) to two terms in \\( \\varepsilon \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit x=2+bε and expand.",
          workingLatex: "(2+b\\varepsilon)^{2}-(3+\\varepsilon)(2+b\\varepsilon)+2=(b-2)\\varepsilon+O(\\varepsilon^{2})",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve.",
          workingLatex: "b-2=0\\Rightarrow b=2\\Rightarrow x\\sim2+2\\varepsilon",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim2+2\\varepsilon \\)",
      canonicalAnswer: "2+2*epsilon",
    },
  },
  {
    id: "am4-019",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the regular (\\( O(1) \\)) root of \\( \\varepsilon x^{2}+x-1=0 \\) to two terms in \\( \\varepsilon \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "regular root"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit x=x₀+εx₁ with x₀ from the reduced equation.",
          workingLatex: "x-1=0\\Rightarrow x_0=1;\\quad \\varepsilon x_0^{2}+\\varepsilon x_1=0\\Rightarrow x_1=-1",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Assemble.",
          workingLatex: "x\\sim1-\\varepsilon",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim1-\\varepsilon \\)",
      canonicalAnswer: "1-epsilon",
    },
  },
  {
    id: "am4-020",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the singular root of \\( \\varepsilon x^{2}+x-1=0 \\) to two terms.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "rescaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rescale x=X/ε to capture the large root.",
          workingLatex: "\\varepsilon\\frac{X^{2}}{\\varepsilon^{2}}+\\frac{X}{\\varepsilon}-1=0\\Rightarrow X^{2}+X-\\varepsilon=0",
          explanation: "Multiplying by ε gives an O(1) problem for X.",
        },
        {
          stepNumber: 2,
          description: "Solve for the non-zero root and restore x.",
          workingLatex: "X\\sim-1+\\varepsilon\\Rightarrow x=\\frac{X}{\\varepsilon}\\sim-\\frac{1}{\\varepsilon}-1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim-\\dfrac{1}{\\varepsilon}-1 \\)",
      canonicalAnswer: "-1/epsilon-1",
    },
  },
  {
    id: "am4-021",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "The two large roots of \\( \\varepsilon x^{3}-x+1=0 \\) have magnitude \\( \\sim\\varepsilon^{q} \\). Find \\( q \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance the cubic against the linear term.",
          workingLatex: "\\varepsilon x^{3}\\sim x\\Rightarrow x^{2}\\sim\\frac{1}{\\varepsilon}\\Rightarrow x\\sim\\pm\\varepsilon^{-1/2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Read off the exponent.",
          workingLatex: "q=-\\tfrac12",
          explanation: "",
        },
      ],
      finalAnswer: "\\( q=-\\frac{1}{2} \\)",
      canonicalAnswer: "-1/2",
    },
  },
  {
    id: "am4-022",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the boundary-layer width for \\( \\varepsilon y''+2y'+y=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "width"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance εy'' against 2y'.",
          workingLatex: "\\frac{\\varepsilon}{\\delta^{2}}\\sim\\frac{2}{\\delta}\\Rightarrow\\delta\\sim\\frac{\\varepsilon}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\delta\\sim\\dfrac{\\varepsilon}{2} \\)",
      canonicalAnswer: "epsilon/2",
    },
  },
  {
    id: "am4-023",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve the outer problem for \\( \\varepsilon y''+2y'+y=0 \\) with \\( y(1)=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "outer solution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solve 2y'+y=0.",
          workingLatex: "y_{\\text{out}}=Ce^{-x/2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply y(1)=1.",
          workingLatex: "Ce^{-1/2}=1\\Rightarrow y_{\\text{out}}=e^{(1-x)/2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{out}}=e^{(1-x)/2} \\)",
      canonicalAnswer: "exp((1-x)/2)",
    },
  },
  {
    id: "am4-024",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the leading composite approximation for \\( \\varepsilon y''+2y'+y=0 \\), \\( y(0)=0 \\), \\( y(1)=1 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matched asymptotics", "composite"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Inner balance Y''+2Y'=0 gives Y=A+Be^{−2X}; match A=√e.",
          workingLatex: "y_{\\text{in}}=\\sqrt{e}\\,\\big(1-e^{-2x/\\varepsilon}\\big)",
          explanation: "Common part is the outer value at 0, e^{1/2}=√e.",
        },
        {
          stepNumber: 2,
          description: "Form outer+inner−common.",
          workingLatex: "y\\approx e^{(1-x)/2}-e^{\\,1/2-2x/\\varepsilon}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y\\approx e^{(1-x)/2}-e^{\\,1/2-2x/\\varepsilon} \\)",
      canonicalAnswer: "exp((1-x)/2)-exp(1/2-2*x/epsilon)",
    },
  },
  {
    id: "am4-025",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( \\varepsilon y''-y'+y=0 \\) with \\( y(0)=1,\\ y(1)=0 \\) (layer at \\( x=1 \\)), find the outer solution.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "outer solution", "right layer"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solve the reduced equation −y'+y=0.",
          workingLatex: "y_{\\text{out}}=Ce^{x}",
          explanation: "With the layer at x=1, the outer solution satisfies the left condition y(0)=1.",
        },
        {
          stepNumber: 2,
          description: "Apply y(0)=1.",
          workingLatex: "C=1\\Rightarrow y_{\\text{out}}=e^{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{out}}=e^{x} \\)",
      canonicalAnswer: "exp(x)",
    },
  },
  {
    id: "am4-026",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For a boundary layer of width \\( \\varepsilon \\) at the right endpoint \\( x=1 \\), write the stretched inner variable \\( X \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "inner variable", "right layer"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Measure distance from the right endpoint.",
          workingLatex: "X=\\frac{1-x}{\\varepsilon}",
          explanation: "X increases into the interior as x decreases from 1.",
        },
      ],
      finalAnswer: "\\( X=\\dfrac{1-x}{\\varepsilon} \\)",
      canonicalAnswer: "(1-x)/epsilon",
    },
  },
  {
    id: "am4-027",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "In Van Dyke matching for \\( \\varepsilon y''+y'+y=0 \\), \\( y(0)=0,\\ y(1)=1 \\), state the common part (overlap value) of the inner and outer solutions.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matching", "Van Dyke"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Equate inner-as-X→∞ with outer-as-x→0.",
          workingLatex: "\\lim_{X\\to\\infty}y_{\\text{in}}=\\lim_{x\\to0}y_{\\text{out}}=e^{1}=e",
          explanation: "This shared limit is subtracted once to form the composite.",
        },
      ],
      finalAnswer: "\\( e \\)",
      canonicalAnswer: "e",
    },
  },
  {
    id: "am4-028",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( y'=y+\\varepsilon y^{2} \\) with \\( y(0)=1 \\), find the leading-order solution \\( y_0(x) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "ODE"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set ε=0.",
          workingLatex: "y_0'=y_0,\\quad y_0(0)=1\\Rightarrow y_0=e^{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_0=e^{x} \\)",
      canonicalAnswer: "exp(x)",
    },
  },
  {
    id: "am4-029",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( y'=y+\\varepsilon y^{2} \\), \\( y(0)=1 \\), with \\( y=y_0+\\varepsilon y_1+\\cdots \\) and \\( y_0=e^{x} \\), find \\( y_1(x) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "ODE", "first correction"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Collect O(ε).",
          workingLatex: "y_1'-y_1=y_0^{2}=e^{2x},\\quad y_1(0)=0",
          explanation: "The boundary condition is carried entirely by y₀, so y₁(0)=0.",
        },
        {
          stepNumber: 2,
          description: "Solve the linear ODE (integrating factor e^{−x}).",
          workingLatex: "(e^{-x}y_1)'=e^{x}\\Rightarrow e^{-x}y_1=e^{x}-1\\Rightarrow y_1=e^{2x}-e^{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_1=e^{2x}-e^{x} \\)",
      canonicalAnswer: "exp(2*x)-exp(x)",
    },
  },
  {
    id: "am4-030",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the boundary-layer location rule for \\( \\varepsilon y''+a\\,y'+b\\,y=0 \\) with constant \\( a<0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "location"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Sign of a fixes the layer endpoint.",
          workingLatex: "a<0\\Rightarrow \\text{layer at }x=1",
          explanation: "The inner exponential e^{a X} must decay into the interior, which requires the layer to be at the right end when a<0.",
        },
      ],
      finalAnswer: "\\( x=1 \\) (right endpoint)",
      canonicalAnswer: "1",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am4-031",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the leading composite solution of \\( \\varepsilon y''+y'+y=0 \\), \\( y(0)=0 \\), \\( y(1)=1 \\), via matched asymptotics.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matched asymptotics", "composite", "boundary layer"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Outer solution.",
          workingLatex: "y'+y=0,\\ y(1)=1\\Rightarrow y_{\\text{out}}=e^{1-x}",
          explanation: "Layer at x=0 (a=+1>0), so the outer carries the right BC.",
        },
        {
          stepNumber: 2,
          description: "Inner solution.",
          workingLatex: "X=x/\\varepsilon:\\ Y''+Y'=0,\\ Y(0)=0\\Rightarrow Y=A(1-e^{-X})",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Match.",
          workingLatex: "\\lim_{X\\to\\infty}Y=A=\\lim_{x\\to0}y_{\\text{out}}=e\\Rightarrow y_{\\text{in}}=e(1-e^{-x/\\varepsilon})",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Composite = outer + inner − common.",
          workingLatex: "y\\approx e^{1-x}+e(1-e^{-x/\\varepsilon})-e=e^{1-x}-e^{\\,1-x/\\varepsilon}",
          explanation: "Uniformly valid on [0,1].",
        },
      ],
      finalAnswer: "\\( y\\approx e^{1-x}-e^{\\,1-x/\\varepsilon} \\)",
      canonicalAnswer: "exp(1-x)-exp(1-x/epsilon)",
    },
  },
  {
    id: "am4-032",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the leading composite solution of \\( \\varepsilon y''+y'=1 \\), \\( y(0)=0 \\), \\( y(1)=0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matched asymptotics", "composite", "forcing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Outer: y'=1.",
          workingLatex: "y_{\\text{out}}=x+C,\\ y(1)=0\\Rightarrow y_{\\text{out}}=x-1",
          explanation: "Layer at x=0 (coefficient of y' is +1).",
        },
        {
          stepNumber: 2,
          description: "Inner: Y''+Y'=0.",
          workingLatex: "Y=A+Be^{-X},\\ Y(0)=0\\Rightarrow A+B=0",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Match the inner limit to y_out(0)=−1.",
          workingLatex: "A=-1,\\ B=1\\Rightarrow y_{\\text{in}}=-1+e^{-x/\\varepsilon}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Composite.",
          workingLatex: "y\\approx (x-1)+(-1+e^{-x/\\varepsilon})-(-1)=x-1+e^{-x/\\varepsilon}",
          explanation: "Satisfies y(0)=0 and y(1)≈0.",
        },
      ],
      finalAnswer: "\\( y\\approx x-1+e^{-x/\\varepsilon} \\)",
      canonicalAnswer: "x-1+exp(-x/epsilon)",
    },
  },
  // REVIEW: two-term large-root correction; leading ε^{-1/2} confirmed numerically,
  // the −1/2 correction matched to ~1% at ε=0.01 — confirm before student use.
  {
    id: "am4-033",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the large positive root of \\( \\varepsilon x^{3}-x+1=0 \\) to two terms as \\( \\varepsilon\\to0^{+} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "rescaling", "dominant balance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rescale x=ε^{−1/2}u.",
          workingLatex: "\\varepsilon\\cdot\\varepsilon^{-3/2}u^{3}-\\varepsilon^{-1/2}u+1=0\\Rightarrow u^{3}-u+\\varepsilon^{1/2}=0",
          explanation: "Multiplying by ε^{1/2} gives an O(1) equation for u.",
        },
        {
          stepNumber: 2,
          description: "Perturb the root u≈1.",
          workingLatex: "u=1+a\\varepsilon^{1/2}:\\ (2a+1)\\varepsilon^{1/2}=0\\Rightarrow a=-\\tfrac12",
          explanation: "Leading u₀=1 from u³−u=0.",
        },
        {
          stepNumber: 3,
          description: "Restore x.",
          workingLatex: "x=\\varepsilon^{-1/2}u\\sim\\varepsilon^{-1/2}-\\tfrac12",
          explanation: "Check at ε=0.01: 10−0.5=9.5 against the numerical root 9.46.",
        },
      ],
      finalAnswer: "\\( x\\sim\\varepsilon^{-1/2}-\\dfrac{1}{2} \\)",
      canonicalAnswer: "epsilon^(-1/2)-1/2",
    },
  },
  // REVIEW: variable-coefficient outer solution; standard separable result, no exemplar —
  // confirm the outer/layer structure before student use.
  {
    id: "am4-034",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the outer solution of \\( \\varepsilon y''+(1+x)y'+y=0 \\) satisfying \\( y(1)=2 \\) (the layer is at \\( x=0 \\)).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "variable coefficient", "outer solution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Reduced equation is separable.",
          workingLatex: "(1+x)y'+y=0\\Rightarrow \\frac{y'}{y}=-\\frac{1}{1+x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "\\ln y=-\\ln(1+x)+\\text{const}\\Rightarrow y_{\\text{out}}=\\frac{C}{1+x}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Apply y(1)=2.",
          workingLatex: "\\frac{C}{2}=2\\Rightarrow C=4\\Rightarrow y_{\\text{out}}=\\frac{4}{1+x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{out}}=\\dfrac{4}{1+x} \\)",
      canonicalAnswer: "4/(1+x)",
    },
  },
  {
    id: "am4-035",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( \\varepsilon y''-y=0 \\) (no first-derivative term) on \\( [0,1] \\), find the width of the boundary layers.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "width", "WKB-type"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Balance εy'' against the y term.",
          workingLatex: "\\frac{\\varepsilon}{\\delta^{2}}\\sim1\\Rightarrow\\delta\\sim\\varepsilon^{1/2}",
          explanation: "With no first-derivative term the layers are thicker, O(√ε), and occur at both ends.",
        },
      ],
      finalAnswer: "\\( \\delta\\sim\\varepsilon^{1/2} \\)",
      canonicalAnswer: "sqrt(epsilon)",
    },
  },
  {
    id: "am4-036",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain why the additive composite \\( y_{\\text{comp}}=y_{\\text{out}}+y_{\\text{in}}-y_{\\text{common}} \\) is uniformly valid, where \\( y_{\\text{common}} \\) is the matched overlap value.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matched asymptotics", "composite", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Behaviour in the outer region.",
          workingLatex: "x=O(1):\\ y_{\\text{in}}\\to y_{\\text{common}}\\Rightarrow y_{\\text{comp}}\\to y_{\\text{out}}",
          explanation: "Outside the layer the inner solution has saturated to the common value, which cancels.",
        },
        {
          stepNumber: 2,
          description: "Behaviour in the inner region.",
          workingLatex: "x=O(\\delta):\\ y_{\\text{out}}\\to y_{\\text{common}}\\Rightarrow y_{\\text{comp}}\\to y_{\\text{in}}",
          explanation: "Inside the layer the outer solution is near the common value, which cancels.",
        },
        {
          stepNumber: 3,
          description: "Conclude uniformity.",
          workingLatex: "y_{\\text{comp}}\\ \\text{reproduces both limits, error }o(1)\\ \\text{everywhere}",
          explanation: "Subtracting the common part exactly once avoids double-counting the overlap.",
        },
      ],
      finalAnswer: "Composite reproduces outer and inner limits ⇒ uniformly valid (shown)",
    },
  },
  {
    id: "am4-037",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For \\( \\varepsilon y''+2y'+y=0 \\), \\( y(0)=0,\\ y(1)=1 \\), state the common (overlap) value used in matching.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["matching", "Van Dyke"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Outer value at the layer edge x=0.",
          workingLatex: "y_{\\text{out}}=e^{(1-x)/2}\\Rightarrow y_{\\text{out}}(0)=e^{1/2}=\\sqrt{e}",
          explanation: "This is the inner limit as X→∞.",
        },
      ],
      finalAnswer: "\\( \\sqrt{e} \\)",
      canonicalAnswer: "sqrt(e)",
    },
  },
  {
    id: "am4-038",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the outer solution of \\( \\varepsilon y''+y'=1 \\), \\( y(0)=0,\\ y(1)=0 \\), used to build the composite.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["boundary layer", "outer solution", "forcing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solve the reduced first-order equation.",
          workingLatex: "y'=1\\Rightarrow y_{\\text{out}}=x+C",
          explanation: "The layer is at x=0, so the outer carries the right BC y(1)=0.",
        },
        {
          stepNumber: 2,
          description: "Apply y(1)=0.",
          workingLatex: "1+C=0\\Rightarrow y_{\\text{out}}=x-1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y_{\\text{out}}=x-1 \\)",
      canonicalAnswer: "x-1",
    },
  },
  {
    id: "am4-039",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the real root of \\( x^{3}-\\varepsilon x-1=0 \\) near \\( 1 \\) to two terms in \\( \\varepsilon \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["regular perturbation", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Posit x=1+aε.",
          workingLatex: "(1+a\\varepsilon)^{3}-\\varepsilon(1+a\\varepsilon)-1=(3a-1)\\varepsilon+O(\\varepsilon^{2})",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve.",
          workingLatex: "3a-1=0\\Rightarrow a=\\tfrac13\\Rightarrow x\\sim1+\\tfrac{\\varepsilon}{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\sim1+\\dfrac{\\varepsilon}{3} \\)",
      canonicalAnswer: "1+epsilon/3",
    },
  },
  {
    id: "am4-040",
    topicRef: "am4",
    topicTitle: "Regular & Singular Perturbation; Matched Asymptotics",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain why setting \\( \\varepsilon=0 \\) in a singularly-perturbed second-order BVP generally prevents the solution from meeting both boundary conditions.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singular perturbation", "boundary layer", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Order reduction.",
          workingLatex: "\\varepsilon y''+a y'+b y=0\\ \\xrightarrow{\\varepsilon=0}\\ a y'+b y=0",
          explanation: "The highest derivative multiplies ε, so ε=0 drops the order from two to one.",
        },
        {
          stepNumber: 2,
          description: "Count constants.",
          workingLatex: "2\\ \\text{constants}\\to1\\ \\text{constant}",
          explanation: "A first-order solution has one free constant and can enforce only one boundary condition.",
        },
        {
          stepNumber: 3,
          description: "Conclude.",
          workingLatex: "\\Rightarrow\\text{a boundary layer restores the dropped condition}",
          explanation: "The missing condition is met inside a thin layer where εy'' is no longer negligible.",
        },
      ],
      finalAnswer: "Order reduction (2→1) loses one constant ⇒ a boundary layer is needed (shown)",
    },
  },
];
