import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — The WKB Method
 * Ref:   am5  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Liouville–Green / WKB ansatz and the q^{-1/4} amplitude; turning points,
 * classically allowed/forbidden regions and the π/4 connection; Bohr–Sommerfeld
 * quantization with eigenvalue scalings (SHO, square well, power-law potentials);
 * barrier tunnelling.
 *
 * DRAFT (year-3): quantization results verified with SymPy (SHO action = πE/ω →
 * E=(n+½)ħω; square well E=n²π²ħ²/2mL²; power-law exponents 2k/(k+2)). Style
 * pinned to content/undergrad/examples/am5.md. // REVIEW marks Airy-connection /
 * two-term-WKB items. Expert review required before student use.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am5-001",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Substituting \\( y=\\exp\\!\\big(\\tfrac1\\varepsilon S(x)\\big) \\) into \\( \\varepsilon^{2}y''=q(x)\\,y \\), write the leading-order (eikonal) equation for \\( S_0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "eikonal"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate the ansatz and substitute.",
          workingLatex: "y''=\\Big(\\tfrac1{\\varepsilon^{2}}(S')^{2}+\\tfrac1\\varepsilon S''\\Big)y\\Rightarrow (S')^{2}+\\varepsilon S''=q",
          explanation: "Divide by y and by the common ε^{−2}.",
        },
        {
          stepNumber: 2,
          description: "Take ε→0 with S=S₀+εS₁+….",
          workingLatex: "(S_0')^{2}=q",
          explanation: "The O(1) balance is the eikonal equation.",
        },
      ],
      finalAnswer: "\\( (S_0')^{2}=q \\)",
      canonicalAnswer: "(S0')^2=q",
    },
  },
  {
    id: "am5-002",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve the eikonal equation \\( (S_0')^{2}=q(x) \\) for \\( S_0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "eikonal"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take the square root and integrate.",
          workingLatex: "S_0'=\\pm\\sqrt{q}\\Rightarrow S_0=\\pm\\int\\sqrt{q}\\,dx",
          explanation: "Both signs are kept; they give the two WKB solutions.",
        },
      ],
      finalAnswer: "\\( S_0=\\pm\\displaystyle\\int\\sqrt{q}\\,dx \\)",
      canonicalAnswer: "+-integral(sqrt(q),x)",
    },
  },
  {
    id: "am5-003",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The next WKB order gives \\( 2S_0'S_1'+S_0''=0 \\). Solve for \\( S_1 \\) in terms of \\( q \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use S₀'=√q so S₀''=q'/(2√q).",
          workingLatex: "S_1'=-\\frac{S_0''}{2S_0'}=-\\frac{q'/(2\\sqrt q)}{2\\sqrt q}=-\\frac{q'}{4q}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "S_1=-\\tfrac14\\ln q",
          explanation: "So e^{S₁}=q^{−1/4}: the Liouville–Green amplitude.",
        },
      ],
      finalAnswer: "\\( S_1=-\\tfrac14\\ln q \\)",
      canonicalAnswer: "-ln(q)/4",
    },
  },
  {
    id: "am5-004",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the Liouville–Green amplitude factor multiplying the WKB exponential for \\( \\varepsilon^{2}y''=q(x)y \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "amplitude", "Liouville–Green"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "From S₁=−¼ln q.",
          workingLatex: "e^{S_1}=q^{-1/4}",
          explanation: "The amplitude diverges as q→0, signalling breakdown at turning points.",
        },
      ],
      finalAnswer: "\\( q^{-1/4} \\)",
      canonicalAnswer: "q^(-1/4)",
    },
  },
  {
    id: "am5-005",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For the Schrödinger equation \\( -\\tfrac{\\hbar^{2}}{2m}\\psi''+V(x)\\psi=E\\psi \\), where (in terms of \\( E,V \\)) is a turning point?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "turning point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Turning points are where the local momentum vanishes.",
          workingLatex: "p(x)=\\sqrt{2m(E-V(x))}=0\\Rightarrow E=V(x)",
          explanation: "There the classically allowed and forbidden regions meet.",
        },
      ],
      finalAnswer: "\\( E=V(x) \\)",
      canonicalAnswer: "E=V(x)",
    },
  },
  {
    id: "am5-006",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the classical turning points for the harmonic oscillator \\( V=\\tfrac12 m\\omega^{2}x^{2} \\) at energy \\( E \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "turning point", "harmonic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set E=V.",
          workingLatex: "\\tfrac12 m\\omega^{2}x^{2}=E\\Rightarrow x=\\pm\\sqrt{\\frac{2E}{m\\omega^{2}}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x=\\pm\\sqrt{\\dfrac{2E}{m\\omega^{2}}} \\)",
      canonicalAnswer: "+-sqrt(2*E/(m*omega^2))",
    },
  },
  {
    id: "am5-007",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "In which region (in terms of \\( E \\) and \\( V \\)) is the WKB wavefunction oscillatory?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "classically allowed"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Oscillatory where the momentum is real.",
          workingLatex: "2m(E-V)>0\\Rightarrow E>V",
          explanation: "The classically allowed region; the exponent is imaginary.",
        },
      ],
      finalAnswer: "\\( E>V \\) (classically allowed)",
      canonicalAnswer: "E>V",
    },
  },
  {
    id: "am5-008",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "In which region is the WKB wavefunction exponentially growing/decaying?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "classically forbidden"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Real exponent where the momentum is imaginary.",
          workingLatex: "E<V\\Rightarrow \\kappa=\\sqrt{2m(V-E)}/\\hbar\\ \\text{real}",
          explanation: "The classically forbidden region; the wavefunction is a real exponential.",
        },
      ],
      finalAnswer: "\\( E<V \\) (classically forbidden)",
      canonicalAnswer: "E<V",
    },
  },
  {
    id: "am5-009",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write the local WKB wavenumber \\( k(x) \\) in the classically allowed region of the Schrödinger equation.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "wavenumber"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Local momentum over ħ.",
          workingLatex: "k(x)=\\frac{p(x)}{\\hbar}=\\frac{\\sqrt{2m(E-V(x))}}{\\hbar}",
          explanation: "The WKB phase is ∫k dx.",
        },
      ],
      finalAnswer: "\\( k(x)=\\dfrac{\\sqrt{2m(E-V)}}{\\hbar} \\)",
      canonicalAnswer: "sqrt(2*m*(E-V))/hbar",
    },
  },
  {
    id: "am5-010",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Where does the leading WKB approximation break down?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "turning point", "breakdown"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The amplitude q^{−1/4} diverges where q=0.",
          workingLatex: "q(x)=0\\ (\\text{i.e. }E=V)\\Rightarrow q^{-1/4}\\to\\infty",
          explanation: "At turning points the slow-variation assumption fails and an Airy patch is needed.",
        },
      ],
      finalAnswer: "At turning points \\( q=0 \\) (\\( E=V \\))",
      canonicalAnswer: "q=0",
    },
  },
  {
    id: "am5-011",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write the WKB phase accumulated between \\( a \\) and \\( b \\) in the classically allowed region.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "phase"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate the local wavenumber.",
          workingLatex: "\\phi=\\int_a^b k(x)\\,dx=\\frac{1}{\\hbar}\\int_a^b\\sqrt{2m(E-V)}\\,dx",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{\\hbar}\\displaystyle\\int_a^b\\sqrt{2m(E-V)}\\,dx \\)",
      canonicalAnswer: "(1/hbar)*integral(sqrt(2*m*(E-V)),x,a,b)",
    },
  },
  {
    id: "am5-012",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the phase shift introduced at a single simple (linear) turning point by the WKB connection formulae.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["WKB", "connection formula"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recall the Airy-matching result.",
          workingLatex: "\\Delta\\phi=\\frac{\\pi}{4}",
          explanation: "Each soft turning point contributes a −π/4 to the Bohr–Sommerfeld phase, giving the +½ in (n+½).",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\pi}{4} \\)",
      canonicalAnswer: "pi/4",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am5-013",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the two leading WKB (Liouville–Green) solutions of \\( \\varepsilon^{2}y''=q(x)y \\) for \\( q>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Liouville–Green"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Combine the amplitude and exponential.",
          workingLatex: "y\\sim q^{-1/4}\\exp\\!\\Big(\\pm\\frac1\\varepsilon\\int\\sqrt{q}\\,dx\\Big)",
          explanation: "For q>0 these are real exponentials (forbidden-region behaviour).",
        },
      ],
      finalAnswer: "\\( y\\sim q^{-1/4}\\exp\\!\\big(\\pm\\tfrac1\\varepsilon\\int\\sqrt q\\,dx\\big) \\)",
      canonicalAnswer: "q^(-1/4)*exp(+-integral(sqrt(q),x)/epsilon)",
    },
  },
  {
    id: "am5-014",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the leading WKB solutions of \\( \\varepsilon^{2}y''=x^{2}y \\) (for \\( x>0 \\)).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Liouville–Green"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Here q=x², so √q=x and q^{−1/4}=x^{−1/2}.",
          workingLatex: "\\int\\sqrt{q}\\,dx=\\int x\\,dx=\\frac{x^{2}}{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Assemble.",
          workingLatex: "y\\sim x^{-1/2}\\exp\\!\\Big(\\pm\\frac{x^{2}}{2\\varepsilon}\\Big)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y\\sim x^{-1/2}\\exp\\!\\big(\\pm\\tfrac{x^{2}}{2\\varepsilon}\\big) \\)",
      canonicalAnswer: "x^(-1/2)*exp(+-x^2/(2*epsilon))",
    },
  },
  {
    id: "am5-015",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the leading WKB exponent for \\( \\varepsilon^{2}y''=(1+x^{2})y \\), i.e. evaluate \\( \\int\\sqrt{1+x^{2}}\\,dx \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eikonal", "integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard integral.",
          workingLatex: "\\int\\sqrt{1+x^{2}}\\,dx=\\tfrac12\\Big(x\\sqrt{1+x^{2}}+\\sinh^{-1}x\\Big)",
          explanation: "This is ±(1/ε) times this, giving the leading exponent.",
        },
      ],
      finalAnswer: "\\( \\tfrac12\\big(x\\sqrt{1+x^{2}}+\\sinh^{-1}x\\big) \\)",
      canonicalAnswer: "(x*sqrt(1+x^2)+asinh(x))/2",
    },
  },
  {
    id: "am5-016",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the Bohr–Sommerfeld quantization condition for a potential well with two soft turning points \\( a,b \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Bohr–Sommerfeld"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Total phase plus two −π/4 shifts equals nπ.",
          workingLatex: "\\frac{1}{\\hbar}\\int_a^b\\sqrt{2m(E-V)}\\,dx=\\Big(n+\\tfrac12\\Big)\\pi,\\quad n=0,1,2,\\dots",
          explanation: "The +½ comes from the two turning-point connections.",
        },
      ],
      finalAnswer: "\\( \\frac{1}{\\hbar}\\int_a^b\\sqrt{2m(E-V)}\\,dx=(n+\\tfrac12)\\pi \\)",
      canonicalAnswer: "(1/hbar)*integral(sqrt(2*m*(E-V)),x,a,b)=(n+1/2)*pi",
    },
  },
  {
    id: "am5-017",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The harmonic-oscillator action integral is \\( \\int_{-a}^{a}\\sqrt{2m(E-\\tfrac12 m\\omega^{2}x^{2})}\\,dx=\\dfrac{\\pi E}{\\omega} \\). Apply Bohr–Sommerfeld to find \\( E_n \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Bohr–Sommerfeld", "harmonic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set the action over ħ to (n+½)π.",
          workingLatex: "\\frac{1}{\\hbar}\\cdot\\frac{\\pi E}{\\omega}=\\Big(n+\\tfrac12\\Big)\\pi",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve for E.",
          workingLatex: "E_n=\\Big(n+\\tfrac12\\Big)\\hbar\\omega",
          explanation: "WKB is exact for the harmonic oscillator.",
        },
      ],
      finalAnswer: "\\( E_n=(n+\\tfrac12)\\hbar\\omega \\)",
      canonicalAnswer: "(n+1/2)*hbar*omega",
    },
  },
  {
    id: "am5-018",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the infinite square well \\( V=0 \\) on \\( [0,L] \\) (hard walls), the WKB condition is \\( \\sqrt{2mE}\\,L=n\\pi\\hbar \\). Find \\( E_n \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "square well"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square and solve.",
          workingLatex: "2mE\\,L^{2}=n^{2}\\pi^{2}\\hbar^{2}\\Rightarrow E_n=\\frac{n^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}}",
          explanation: "Hard walls contribute no π/4 shift, giving exactly the known spectrum.",
        },
      ],
      finalAnswer: "\\( E_n=\\dfrac{n^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}} \\)",
      canonicalAnswer: "n^2*pi^2*hbar^2/(2*m*L^2)",
    },
  },
  {
    id: "am5-019",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate the action integral \\( \\int_{-a}^{a}\\sqrt{2m\\big(E-\\tfrac12 m\\omega^{2}x^{2}\\big)}\\,dx \\) with \\( a=\\sqrt{2E/(m\\omega^{2})} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "action integral", "harmonic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Factor and substitute x=a sinθ.",
          workingLatex: "\\sqrt{2mE}\\int_{-a}^{a}\\sqrt{1-\\frac{x^{2}}{a^{2}}}\\,dx=\\sqrt{2mE}\\cdot\\frac{\\pi a}{2}",
          explanation: "The semicircle integral gives πa/2.",
        },
        {
          stepNumber: 2,
          description: "Insert a and simplify.",
          workingLatex: "\\sqrt{2mE}\\cdot\\frac{\\pi}{2}\\sqrt{\\frac{2E}{m\\omega^{2}}}=\\frac{\\pi E}{\\omega}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\pi E}{\\omega} \\)",
      canonicalAnswer: "pi*E/omega",
    },
  },
  {
    id: "am5-020",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the WKB (Gamow) tunnelling probability through a barrier where \\( V>E \\) on \\( (a,b) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "tunnelling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Exponential of minus twice the forbidden action.",
          workingLatex: "T\\approx\\exp\\!\\Big(-\\frac{2}{\\hbar}\\int_a^b\\sqrt{2m(V-E)}\\,dx\\Big)",
          explanation: "From the decaying WKB solution across the barrier.",
        },
      ],
      finalAnswer: "\\( T\\approx\\exp\\!\\big(-\\tfrac{2}{\\hbar}\\int_a^b\\sqrt{2m(V-E)}\\,dx\\big) \\)",
      canonicalAnswer: "exp(-(2/hbar)*integral(sqrt(2*m*(V-E)),x,a,b))",
    },
  },
  {
    id: "am5-021",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the WKB tunnelling probability through a rectangular barrier of height \\( V_0 \\) and width \\( L \\) (with \\( E<V_0 \\)).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "tunnelling", "rectangular barrier"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Constant integrand over width L.",
          workingLatex: "\\int_0^{L}\\sqrt{2m(V_0-E)}\\,dx=L\\sqrt{2m(V_0-E)}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Insert into the tunnelling formula.",
          workingLatex: "T\\approx\\exp\\!\\Big(-\\frac{2L}{\\hbar}\\sqrt{2m(V_0-E)}\\Big)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( T\\approx\\exp\\!\\big(-\\tfrac{2L}{\\hbar}\\sqrt{2m(V_0-E)}\\big) \\)",
      canonicalAnswer: "exp(-(2*L/hbar)*sqrt(2*m*(V0-E)))",
    },
  },
  {
    id: "am5-022",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For a power-law well \\( V=\\alpha|x|^{4} \\), the WKB eigenvalues scale as \\( E_n\\sim n^{r} \\). Find \\( r \\). (General rule: \\( r=2k/(k+2) \\).)",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eigenvalue scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the scaling rule with k=4.",
          workingLatex: "r=\\frac{2k}{k+2}=\\frac{8}{6}=\\frac{4}{3}",
          explanation: "Steeper walls give faster-growing spectra (k→∞ recovers n²).",
        },
      ],
      finalAnswer: "\\( r=\\frac{4}{3} \\)",
      canonicalAnswer: "4/3",
    },
  },
  {
    id: "am5-023",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For \\( V=\\alpha|x|^{6} \\), find the WKB eigenvalue exponent \\( r \\) in \\( E_n\\sim n^{r} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eigenvalue scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply r=2k/(k+2) with k=6.",
          workingLatex: "r=\\frac{12}{8}=\\frac{3}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( r=\\frac{3}{2} \\)",
      canonicalAnswer: "3/2",
    },
  },
  {
    id: "am5-024",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the symmetric linear well \\( V=\\alpha|x| \\), find the WKB eigenvalue exponent \\( r \\) in \\( E_n\\sim n^{r} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eigenvalue scaling"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply r=2k/(k+2) with k=1.",
          workingLatex: "r=\\frac{2}{3}",
          explanation: "Matches the Airy-zero spacing of the linear potential.",
        },
      ],
      finalAnswer: "\\( r=\\frac{2}{3} \\)",
      canonicalAnswer: "2/3",
    },
  },
  {
    id: "am5-025",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the WKB estimate for the number of bound states \\( N \\) with energy below \\( E \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "density of states"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Each state occupies phase-space area 2πħ.",
          workingLatex: "N(E)\\approx\\frac{1}{\\pi\\hbar}\\int_{V<E}\\sqrt{2m(E-V)}\\,dx",
          explanation: "Equivalently the Bohr–Sommerfeld index at energy E.",
        },
      ],
      finalAnswer: "\\( N(E)\\approx\\frac{1}{\\pi\\hbar}\\int\\sqrt{2m(E-V)}\\,dx \\)",
      canonicalAnswer: "(1/(pi*hbar))*integral(sqrt(2*m*(E-V)),x)",
    },
  },
  {
    id: "am5-026",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Near a turning point the WKB amplitude behaves like a power of the distance \\( s \\) to it (with \\( q\\propto s \\)). State that power.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "turning point", "amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Linearise q near the turning point.",
          workingLatex: "q\\propto s\\Rightarrow q^{-1/4}\\propto s^{-1/4}",
          explanation: "The amplitude diverges as s^{−1/4}, so WKB fails and is replaced by an Airy function there.",
        },
      ],
      finalAnswer: "\\( s^{-1/4} \\)",
      canonicalAnswer: "s^(-1/4)",
    },
  },
  {
    id: "am5-027",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the WKB validity condition for \\( \\varepsilon^{2}y''=q(x)y \\) (slow variation of the local wavelength).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "validity"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Require the next correction to be small.",
          workingLatex: "\\left|\\frac{\\varepsilon\\,q'}{q^{3/2}}\\right|\\ll1",
          explanation: "Equivalently |dλ/dx|≪1: the wavelength changes slowly over one wavelength. This fails as q→0.",
        },
      ],
      finalAnswer: "\\( \\left|\\dfrac{\\varepsilon q'}{q^{3/2}}\\right|\\ll1 \\)",
      canonicalAnswer: "abs(epsilon*q'/q^(3/2))<<1",
    },
  },
  {
    id: "am5-028",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Near a simple turning point the equation \\( \\varepsilon^{2}y''=q'(x_0)(x-x_0)\\,y \\) reduces to which standard equation (after rescaling)?",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Airy", "turning point"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rescale the local variable to absorb ε and the slope.",
          workingLatex: "\\xi=\\Big(\\frac{q'(x_0)}{\\varepsilon^{2}}\\Big)^{1/3}(x-x_0)\\Rightarrow \\frac{d^{2}y}{d\\xi^{2}}=\\xi\\,y",
          explanation: "This is the Airy equation, whose solution patches the two WKB branches.",
        },
      ],
      finalAnswer: "Airy equation \\( y''=\\xi y \\)",
      canonicalAnswer: "y''=xi*y",
    },
  },
  {
    id: "am5-029",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the two leading WKB solutions of \\( \\varepsilon^{2}y''=-q(x)y \\) with \\( q>0 \\) (oscillatory case).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "oscillatory"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Eikonal gives an imaginary exponent.",
          workingLatex: "(S_0')^{2}=-q\\Rightarrow S_0=\\pm i\\int\\sqrt q\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Attach the amplitude.",
          workingLatex: "y\\sim q^{-1/4}\\exp\\!\\Big(\\pm\\frac{i}{\\varepsilon}\\int\\sqrt q\\,dx\\Big)",
          explanation: "Oscillatory: the classically allowed region.",
        },
      ],
      finalAnswer: "\\( y\\sim q^{-1/4}\\exp\\!\\big(\\pm\\tfrac{i}{\\varepsilon}\\int\\sqrt q\\,dx\\big) \\)",
      canonicalAnswer: "q^(-1/4)*exp(+-I*integral(sqrt(q),x)/epsilon)",
    },
  },
  {
    id: "am5-030",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the WKB quantization condition for a well with one hard wall and one soft turning point.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Bohr–Sommerfeld", "half-well"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "One −π/4 shift (soft) and none from the hard wall.",
          workingLatex: "\\frac{1}{\\hbar}\\int\\sqrt{2m(E-V)}\\,dx=\\Big(n-\\tfrac14\\Big)\\pi,\\quad n=1,2,\\dots",
          explanation: "The single soft turning point contributes the −π/4, giving the −¼.",
        },
      ],
      finalAnswer: "\\( \\frac{1}{\\hbar}\\int\\sqrt{2m(E-V)}\\,dx=(n-\\tfrac14)\\pi \\)",
      canonicalAnswer: "(1/hbar)*integral(sqrt(2*m*(E-V)),x)=(n-1/4)*pi",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am5-031",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the harmonic-oscillator spectrum \\( E_n=(n+\\tfrac12)\\hbar\\omega \\) from Bohr–Sommerfeld quantization.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Bohr–Sommerfeld", "harmonic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Turning points.",
          workingLatex: "E=\\tfrac12 m\\omega^{2}x^{2}\\Rightarrow x=\\pm a,\\ a=\\sqrt{2E/(m\\omega^{2})}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Action integral.",
          workingLatex: "\\int_{-a}^{a}\\sqrt{2m(E-\\tfrac12 m\\omega^{2}x^{2})}\\,dx=\\frac{\\pi E}{\\omega}",
          explanation: "The semicircle substitution gives πE/ω.",
        },
        {
          stepNumber: 3,
          description: "Impose quantization.",
          workingLatex: "\\frac{1}{\\hbar}\\frac{\\pi E}{\\omega}=\\Big(n+\\tfrac12\\Big)\\pi",
          explanation: "Two soft turning points contribute the +½.",
        },
        {
          stepNumber: 4,
          description: "Solve.",
          workingLatex: "E_n=\\Big(n+\\tfrac12\\Big)\\hbar\\omega",
          explanation: "Exact for the SHO.",
        },
      ],
      finalAnswer: "\\( E_n=(n+\\tfrac12)\\hbar\\omega \\)",
      canonicalAnswer: "(n+1/2)*hbar*omega",
    },
  },
  {
    id: "am5-032",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the infinite-square-well spectrum from the WKB condition with two hard walls.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "square well"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Constant momentum inside.",
          workingLatex: "p=\\sqrt{2mE},\\quad \\frac{1}{\\hbar}\\int_0^{L}p\\,dx=\\frac{pL}{\\hbar}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Hard walls quantize to nπ (no π/4 shifts).",
          workingLatex: "\\frac{\\sqrt{2mE}\\,L}{\\hbar}=n\\pi",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Solve.",
          workingLatex: "E_n=\\frac{n^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}}",
          explanation: "Exact agreement with the elementary result.",
        },
      ],
      finalAnswer: "\\( E_n=\\dfrac{n^{2}\\pi^{2}\\hbar^{2}}{2mL^{2}} \\)",
      canonicalAnswer: "n^2*pi^2*hbar^2/(2*m*L^2)",
    },
  },
  {
    id: "am5-033",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "By a scaling argument, show the WKB eigenvalues of \\( V=\\alpha|x|^{k} \\) satisfy \\( E_n\\sim n^{2k/(k+2)} \\), and state the exponent for \\( k=2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eigenvalue scaling", "dimensional analysis"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Turning point scales with energy.",
          workingLatex: "E=\\alpha a^{k}\\Rightarrow a\\sim E^{1/k}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Action integral scales as √E · a.",
          workingLatex: "\\int_{-a}^{a}\\sqrt{2m(E-\\alpha|x|^{k})}\\,dx\\sim \\sqrt{E}\\,a\\sim E^{1/2+1/k}",
          explanation: "Non-dimensionalising x=a u pulls out √E and a.",
        },
        {
          stepNumber: 3,
          description: "Set proportional to n and invert.",
          workingLatex: "E^{(k+2)/(2k)}\\sim n\\Rightarrow E_n\\sim n^{2k/(k+2)}",
          explanation: "For k=2 the exponent is 1 (the SHO), as it must be.",
        },
        {
          stepNumber: 4,
          description: "State k=2 exponent.",
          workingLatex: "\\frac{2\\cdot2}{2+2}=1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( E_n\\sim n^{2k/(k+2)} \\); for \\( k=2 \\), exponent \\( =1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "am5-034",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "For the quartic oscillator \\( V=\\alpha x^{4} \\), state the large-\\( n \\) eigenvalue exponent and confirm it lies between the harmonic (\\( n \\)) and hard-wall (\\( n^{2} \\)) cases.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "eigenvalue scaling", "quartic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the power-law exponent with k=4.",
          workingLatex: "E_n\\sim n^{2\\cdot4/(4+2)}=n^{4/3}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Compare.",
          workingLatex: "1<\\tfrac43<2",
          explanation: "Steeper than harmonic, shallower than an infinite well — as expected.",
        },
      ],
      finalAnswer: "\\( E_n\\sim n^{4/3} \\), and \\( 1<\\tfrac43<2 \\)",
      canonicalAnswer: "4/3",
    },
  },
  {
    id: "am5-035",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the WKB tunnelling exponent for the inverted-parabola barrier \\( V=V_0-\\tfrac12 m\\omega^{2}x^{2} \\) at energy \\( E<V_0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "tunnelling", "parabolic barrier"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Forbidden region between the turning points.",
          workingLatex: "V-E=(V_0-E)-\\tfrac12 m\\omega^{2}x^{2}=0\\Rightarrow x=\\pm b,\\ b=\\sqrt{2(V_0-E)/(m\\omega^{2})}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Action integral (same form as the SHO).",
          workingLatex: "\\int_{-b}^{b}\\sqrt{2m\\big((V_0-E)-\\tfrac12 m\\omega^{2}x^{2}\\big)}\\,dx=\\frac{\\pi(V_0-E)}{\\omega}",
          explanation: "Replace E by V₀−E in the SHO action πE/ω.",
        },
        {
          stepNumber: 3,
          description: "Insert into the tunnelling formula.",
          workingLatex: "T\\approx\\exp\\!\\Big(-\\frac{2}{\\hbar}\\cdot\\frac{\\pi(V_0-E)}{\\omega}\\Big)=\\exp\\!\\Big(-\\frac{2\\pi(V_0-E)}{\\hbar\\omega}\\Big)",
          explanation: "Matches the small-T limit of the exact inverted-oscillator transmission.",
        },
      ],
      finalAnswer: "\\( T\\approx\\exp\\!\\big(-\\tfrac{2\\pi(V_0-E)}{\\hbar\\omega}\\big) \\)",
      canonicalAnswer: "exp(-2*pi*(V0-E)/(hbar*omega))",
    },
  },
  {
    id: "am5-036",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the Liouville–Green amplitude \\( q^{-1/4} \\) from the second-order WKB balance \\( 2S_0'S_1'+S_0''=0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "amplitude", "Liouville–Green", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the eikonal solution.",
          workingLatex: "S_0'=\\sqrt q\\Rightarrow S_0''=\\frac{q'}{2\\sqrt q}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve the transport equation for S₁'.",
          workingLatex: "S_1'=-\\frac{S_0''}{2S_0'}=-\\frac{q'}{4q}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Integrate and exponentiate.",
          workingLatex: "S_1=-\\tfrac14\\ln q\\Rightarrow e^{S_1}=q^{-1/4}",
          explanation: "Hence the amplitude is q^{−1/4}, conserving the WKB probability flux q^{−1/2}·√q.",
        },
      ],
      finalAnswer: "Amplitude \\( =q^{-1/4} \\) (shown)",
      canonicalAnswer: "q^(-1/4)",
    },
  },
  // REVIEW: Airy connection formulae (matching oscillatory and exponential WKB branches
  // through a turning point) — standard but the ±π/4 bookkeeping was not machine-checked.
  {
    id: "am5-037",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain how the Airy function provides the connection between the oscillatory and decaying WKB solutions across a simple turning point, and why this yields the \\( \\tfrac{\\pi}{4} \\) phase.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "Airy", "connection formula", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Local Airy equation.",
          workingLatex: "y''=\\xi y,\\quad \\xi\\propto(x-x_0)",
          explanation: "Valid in a neighbourhood where q is approximately linear.",
        },
        {
          stepNumber: 2,
          description: "Match Airy asymptotics to the outer WKB forms.",
          workingLatex: "\\mathrm{Ai}(\\xi)\\sim\\tfrac{1}{2\\sqrt\\pi}\\xi^{-1/4}e^{-\\frac23\\xi^{3/2}}\\ (\\xi\\to+\\infty);\\ \\sim\\tfrac{1}{\\sqrt\\pi}|\\xi|^{-1/4}\\sin(\\tfrac23|\\xi|^{3/2}+\\tfrac\\pi4)\\ (\\xi\\to-\\infty)",
          explanation: "The decaying side matches the forbidden WKB exponential; the oscillatory side matches the allowed WKB cosine.",
        },
        {
          stepNumber: 3,
          description: "Read off the phase.",
          workingLatex: "\\text{allowed-side phase}=\\tfrac23|\\xi|^{3/2}+\\tfrac\\pi4",
          explanation: "The +π/4 in the Airy oscillatory asymptotic is exactly the connection-formula phase per soft turning point.",
        },
      ],
      finalAnswer: "Airy matching gives the \\( +\\tfrac{\\pi}{4} \\) connection phase (shown)",
    },
  },
  {
    id: "am5-038",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the harmonic oscillator, estimate the number of bound states \\( N \\) with energy below a large \\( E \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "density of states", "harmonic oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Invert the spectrum.",
          workingLatex: "E_n=(n+\\tfrac12)\\hbar\\omega\\Rightarrow n\\approx\\frac{E}{\\hbar\\omega}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "State the count.",
          workingLatex: "N(E)\\approx\\frac{E}{\\hbar\\omega}",
          explanation: "Consistent with the phase-space estimate N≈(1/πħ)∮p dx /2.",
        },
      ],
      finalAnswer: "\\( N(E)\\approx\\dfrac{E}{\\hbar\\omega} \\)",
      canonicalAnswer: "E/(hbar*omega)",
    },
  },
  // REVIEW: two-term WKB (S2 correction) algebra — standard Liouville–Green result, not
  // machine-checked; confirm the S2 expression before student use.
  {
    id: "am5-039",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( \\varepsilon^{2}y''=q(x)y \\), the third WKB order gives \\( 2S_0'S_2'+(S_1')^{2}+S_1''=0 \\). Find \\( S_2' \\) in terms of \\( q \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "higher order"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Insert S₁'=−q'/(4q).",
          workingLatex: "S_1'=-\\frac{q'}{4q},\\quad S_1''=-\\frac{q''}{4q}+\\frac{(q')^{2}}{4q^{2}}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Form (S₁')²+S₁''.",
          workingLatex: "(S_1')^{2}+S_1''=\\frac{(q')^{2}}{16q^{2}}-\\frac{q''}{4q}+\\frac{(q')^{2}}{4q^{2}}=\\frac{5(q')^{2}}{16q^{2}}-\\frac{q''}{4q}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Solve for S₂' using S₀'=√q.",
          workingLatex: "S_2'=-\\frac{(S_1')^{2}+S_1''}{2\\sqrt q}=-\\frac{1}{2\\sqrt q}\\Big(\\frac{5(q')^{2}}{16q^{2}}-\\frac{q''}{4q}\\Big)",
          explanation: "This is the standard second-order Liouville–Green correction.",
        },
      ],
      finalAnswer: "\\( S_2'=-\\dfrac{1}{2\\sqrt q}\\Big(\\dfrac{5(q')^{2}}{16q^{2}}-\\dfrac{q''}{4q}\\Big) \\)",
      canonicalAnswer: "-(1/(2*sqrt(q)))*(5*(q')^2/(16*q^2)-q''/(4*q))",
    },
  },
  {
    id: "am5-040",
    topicRef: "am5",
    topicTitle: "The WKB Method",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain why the leading WKB approximation fails at a turning point and what replaces it there.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["WKB", "turning point", "Airy", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Amplitude divergence.",
          workingLatex: "q\\to0\\Rightarrow q^{-1/4}\\to\\infty",
          explanation: "The Liouville–Green amplitude blows up where E=V.",
        },
        {
          stepNumber: 2,
          description: "Validity condition fails.",
          workingLatex: "\\left|\\frac{\\varepsilon q'}{q^{3/2}}\\right|\\to\\infty",
          explanation: "The wavelength no longer varies slowly, so the WKB ansatz is invalid in a neighbourhood of width O(ε^{2/3}).",
        },
        {
          stepNumber: 3,
          description: "Local replacement.",
          workingLatex: "y''=\\xi y\\ \\Rightarrow\\ y=\\text{Airy functions}",
          explanation: "Linearising q gives the Airy equation; its solution is finite at the turning point and connects the two WKB branches.",
        },
      ],
      finalAnswer: "WKB fails (amplitude diverges); the Airy function replaces it at the turning point (shown)",
    },
  },
];
