import { Question } from "@/lib/types";

/**
 * Topic: Asymptotic Methods — Method of Multiple Scales
 * Ref:   am6  (Advanced undergraduate / Part II applied maths, year 3)
 *
 * 40 questions — 12 Foundation, 18 Standard, 10 Challenge.
 * Two-timing (fast t, slow T=εt) and the failure of naive expansions (secular
 * growth); the slow-flow amplitude/phase equations from removing secular terms;
 * weakly nonlinear oscillators — Duffing frequency–amplitude shift, Van der Pol
 * and Rayleigh limit cycles, weakly damped and forced oscillators.
 *
 * NO exemplar was supplied — authored from the standard theory. DRAFT (year-3):
 * the Duffing frequency ω=1+(3/8)εA², Van der Pol amplitude →2, and the damped
 * amplitude e^{−εt} were verified by numerical ODE integration. // REVIEW marks
 * O(ε²) / forced-resonance / parametric items. Expert review required.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (12) ─────────────────────────
  {
    id: "am6-001",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "In a two-timing analysis of a weakly perturbed oscillator, write the slow time variable \\( T \\) in terms of \\( t \\) and \\( \\varepsilon \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "slow time"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The slow time captures O(1) changes over t~1/ε.",
          workingLatex: "T=\\varepsilon t",
          explanation: "Amplitude and phase drift on this scale.",
        },
      ],
      finalAnswer: "\\( T=\\varepsilon t \\)",
      canonicalAnswer: "epsilon*t",
    },
  },
  {
    id: "am6-002",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "With \\( y=y(t,T) \\) and \\( T=\\varepsilon t \\), write the total derivative \\( \\dfrac{d}{dt} \\) using the chain rule.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "two-timing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate treating t and T as independent.",
          workingLatex: "\\frac{d}{dt}=\\frac{\\partial}{\\partial t}+\\varepsilon\\frac{\\partial}{\\partial T}",
          explanation: "The factor ε comes from dT/dt=ε.",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\partial}{\\partial t}+\\varepsilon\\dfrac{\\partial}{\\partial T} \\)",
      canonicalAnswer: "d/dt+epsilon*d/dT",
    },
  },
  {
    id: "am6-003",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Expand \\( \\dfrac{d^{2}}{dt^{2}} \\) for two-timing with \\( T=\\varepsilon t \\), to \\( O(\\varepsilon) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "two-timing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square the operator ∂_t+ε∂_T.",
          workingLatex: "\\frac{d^{2}}{dt^{2}}=\\frac{\\partial^{2}}{\\partial t^{2}}+2\\varepsilon\\frac{\\partial^{2}}{\\partial t\\,\\partial T}+\\varepsilon^{2}\\frac{\\partial^{2}}{\\partial T^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\partial_{tt}+2\\varepsilon\\,\\partial_{tT}+\\varepsilon^{2}\\partial_{TT} \\)",
      canonicalAnswer: "d2/dt2+2*epsilon*d2/dtdT+epsilon^2*d2/dT2",
    },
  },
  {
    id: "am6-004",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "A naive expansion of \\( y''+\\varepsilon y'+y=0 \\) produces a term proportional to which function of \\( t \\) that makes it non-uniform?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "secular term"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Resonant forcing of the O(ε) problem.",
          workingLatex: "y_1''+y_1=-y_0'\\propto\\sin t\\Rightarrow y_1\\propto t\\cos t",
          explanation: "The factor t grows without bound — the secular term that ruins uniformity for t~1/ε.",
        },
      ],
      finalAnswer: "\\( t\\cos t \\) (a secular term \\( \\propto t \\))",
      canonicalAnswer: "t*cos(t)",
    },
  },
  {
    id: "am6-005",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( y''+y=\\cos t \\) (a forced linear oscillator at resonance) and identify the secular part.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["resonance", "secular term"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Resonant particular integral.",
          workingLatex: "y_p=\\frac{t}{2}\\sin t",
          explanation: "Forcing at the natural frequency gives an amplitude growing linearly in t — the prototype secular term.",
        },
      ],
      finalAnswer: "\\( y_p=\\frac{t}{2}\\sin t \\) (secular)",
      canonicalAnswer: "(t/2)*sin(t)",
    },
  },
  {
    id: "am6-006",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write the general leading-order two-timing solution of \\( y''+y=O(\\varepsilon) \\) with slow-varying coefficients.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "leading order"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solve ∂_tt y₀+y₀=0 with T-dependent constants.",
          workingLatex: "y_0=A(T)\\cos t+B(T)\\sin t",
          explanation: "Equivalently A(T)cos(t+φ(T)); the slow dependence is fixed at next order.",
        },
      ],
      finalAnswer: "\\( y_0=A(T)\\cos t+B(T)\\sin t \\)",
      canonicalAnswer: "A(T)*cos(t)+B(T)*sin(t)",
    },
  },
  {
    id: "am6-007",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "On what variable do the amplitude and phase of the leading multiple-scales solution depend?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "slow flow"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Amplitude/phase drift slowly.",
          workingLatex: "A=A(T),\\ \\phi=\\phi(T),\\quad T=\\varepsilon t",
          explanation: "They are constant on the fast scale and evolve on the slow scale.",
        },
      ],
      finalAnswer: "the slow time \\( T=\\varepsilon t \\)",
      canonicalAnswer: "T=epsilon*t",
    },
  },
  {
    id: "am6-008",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Compute \\( \\dfrac{\\partial}{\\partial t}\\big[A(T)\\cos t\\big] \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "partial derivative"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "A(T) is constant under ∂/∂t.",
          workingLatex: "\\frac{\\partial}{\\partial t}\\big[A(T)\\cos t\\big]=-A(T)\\sin t",
          explanation: "Only the fast t inside cos t is differentiated.",
        },
      ],
      finalAnswer: "\\( -A(T)\\sin t \\)",
      canonicalAnswer: "-A(T)*sin(t)",
    },
  },
  {
    id: "am6-009",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "State the period of the leading oscillation \\( y_0=A(T)\\cos t \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "period"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Unit angular frequency.",
          workingLatex: "\\omega_0=1\\Rightarrow T_{\\text{period}}=\\frac{2\\pi}{\\omega_0}=2\\pi",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2\\pi \\)",
      canonicalAnswer: "2*pi",
    },
  },
  {
    id: "am6-010",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "The combination \\( \\varepsilon t \\) becomes \\( O(1) \\) when \\( t \\) reaches what scale?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "timescale"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set εt~1.",
          workingLatex: "t\\sim\\frac{1}{\\varepsilon}",
          explanation: "This is the timescale over which slow drift accumulates an O(1) effect.",
        },
      ],
      finalAnswer: "\\( t\\sim\\dfrac{1}{\\varepsilon} \\)",
      canonicalAnswer: "1/epsilon",
    },
  },
  {
    id: "am6-011",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using \\( \\cos^{3}\\psi=\\tfrac34\\cos\\psi+\\tfrac14\\cos3\\psi \\), identify which term is secular (resonant) when it forces \\( y_1''+y_1 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "secular term", "Duffing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Resonance occurs at the natural frequency (cos ψ).",
          workingLatex: "\\tfrac34\\cos\\psi\\ \\text{resonant};\\ \\tfrac14\\cos3\\psi\\ \\text{non-resonant}",
          explanation: "The cos3ψ term forces a bounded third harmonic; cosψ must be removed.",
        },
      ],
      finalAnswer: "\\( \\tfrac34\\cos\\psi \\) (the fundamental)",
      canonicalAnswer: "(3/4)*cos(psi)",
    },
  },
  {
    id: "am6-012",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Why must secular terms be removed in the method of multiple scales?",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["multiple scales", "uniform validity"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Secular terms break the ordering.",
          workingLatex: "\\varepsilon\\,t\\cos t\\ \\text{is }O(1)\\ \\text{when }t\\sim1/\\varepsilon",
          explanation: "Setting their coefficients to zero keeps εy₁ ≪ y₀ uniformly, giving a valid approximation on t~1/ε.",
        },
      ],
      finalAnswer: "To keep the expansion uniformly valid (bounded) for \\( t\\sim1/\\varepsilon \\)",
      canonicalAnswer: "remove unbounded secular growth",
    },
  },

  // ───────────────────────── Standard (18) ─────────────────────────
  {
    id: "am6-013",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the weakly damped oscillator \\( y''+2\\varepsilon y'+y=0 \\), find the slow amplitude \\( A(T) \\) with \\( A(0)=A_0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "damped oscillator", "slow flow"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Remove the secular term at O(ε).",
          workingLatex: "y_1''+y_1=-2\\,\\partial_{tT}y_0-2\\,\\partial_t y_0",
          explanation: "With y₀=A(T)cos(t+φ), the resonant terms give the amplitude equation.",
        },
        {
          stepNumber: 2,
          description: "Solvability gives the amplitude ODE.",
          workingLatex: "2A'+2A=0\\Rightarrow A'=-A",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Solve.",
          workingLatex: "A(T)=A_0e^{-T}=A_0e^{-\\varepsilon t}",
          explanation: "Matches the exact decay envelope e^{−εt}.",
        },
      ],
      finalAnswer: "\\( A(T)=A_0e^{-T}=A_0e^{-\\varepsilon t} \\)",
      canonicalAnswer: "A0*exp(-epsilon*t)",
    },
  },
  {
    id: "am6-014",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Duffing oscillator \\( y''+y+\\varepsilon y^{3}=0 \\) with leading solution \\( A\\cos\\psi \\), find the slow amplitude equation \\( A'(T) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "slow flow"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Identify the resonant (sin ψ) forcing.",
          workingLatex: "y^{3}=A^{3}\\cos^{3}\\psi=A^{3}\\big(\\tfrac34\\cos\\psi+\\tfrac14\\cos3\\psi\\big)",
          explanation: "There is no sin ψ term, so the amplitude does not change.",
        },
        {
          stepNumber: 2,
          description: "Solvability for the sin ψ coefficient.",
          workingLatex: "2A'=0\\Rightarrow A'=0",
          explanation: "The Duffing amplitude is constant; only the phase drifts.",
        },
      ],
      finalAnswer: "\\( A'(T)=0 \\) (constant amplitude)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am6-015",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Duffing oscillator \\( y''+y+\\varepsilon y^{3}=0 \\) with amplitude \\( A \\), find the corrected (nonlinear) frequency \\( \\omega \\) to \\( O(\\varepsilon) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "frequency shift"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Phase equation from the cos ψ resonance.",
          workingLatex: "2A\\phi'=\\tfrac34 A^{3}\\Rightarrow \\phi'=\\tfrac38 A^{2}",
          explanation: "The fundamental part ¾A³cosψ must be cancelled by the slow phase drift.",
        },
        {
          stepNumber: 2,
          description: "Read off the frequency.",
          workingLatex: "\\omega=1+\\varepsilon\\phi'=1+\\tfrac38\\varepsilon A^{2}",
          explanation: "The oscillation stiffens with amplitude (hardening spring).",
        },
      ],
      finalAnswer: "\\( \\omega=1+\\tfrac38\\varepsilon A^{2} \\)",
      canonicalAnswer: "1+(3/8)*epsilon*A^2",
    },
  },
  {
    id: "am6-016",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Expand \\( \\cos^{3}\\psi \\) in harmonics.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["trigonometric identity", "harmonics"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the triple-angle identity cos3ψ=4cos³ψ−3cosψ.",
          workingLatex: "\\cos^{3}\\psi=\\frac{3\\cos\\psi+\\cos3\\psi}{4}",
          explanation: "Rearranged from cos3ψ=4cos³ψ−3cosψ.",
        },
      ],
      finalAnswer: "\\( \\tfrac34\\cos\\psi+\\tfrac14\\cos3\\psi \\)",
      canonicalAnswer: "(3/4)*cos(psi)+(1/4)*cos(3*psi)",
    },
  },
  {
    id: "am6-017",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Van der Pol oscillator \\( y''+y+\\varepsilon(y^{2}-1)y'=0 \\), the slow amplitude obeys \\( A'=\\tfrac12 A(1-\\tfrac14 A^{2}) \\). Find the non-zero steady-state amplitude.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Van der Pol", "limit cycle"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set A'=0.",
          workingLatex: "\\tfrac12 A\\big(1-\\tfrac14 A^{2}\\big)=0\\Rightarrow A^{2}=4",
          explanation: "Reject A=0 (unstable).",
        },
        {
          stepNumber: 2,
          description: "Take the positive root.",
          workingLatex: "A=2",
          explanation: "Matches the numerically observed limit-cycle amplitude.",
        },
      ],
      finalAnswer: "\\( A=2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am6-018",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "State the limit-cycle amplitude of the Van der Pol oscillator \\( y''+y+\\varepsilon(y^{2}-1)y'=0 \\) for small \\( \\varepsilon \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Van der Pol", "limit cycle"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Stable fixed point of the amplitude equation.",
          workingLatex: "A'=\\tfrac12 A(1-\\tfrac14 A^{2})=0\\Rightarrow A=2",
          explanation: "All trajectories approach this amplitude regardless of (non-zero) start.",
        },
      ],
      finalAnswer: "\\( 2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am6-019",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( y''+2\\varepsilon y'+y=0 \\), write the leading two-timing solution (amplitude × oscillation) with \\( y(0)=A_0,\\ y'(0)=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "damped oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Amplitude from the slow flow, phase fixed.",
          workingLatex: "A(T)=A_0e^{-T},\\quad \\phi'=0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Assemble.",
          workingLatex: "y\\approx A_0e^{-\\varepsilon t}\\cos t",
          explanation: "Reproduces the exact envelope; frequency correction is O(ε²).",
        },
      ],
      finalAnswer: "\\( y\\approx A_0e^{-\\varepsilon t}\\cos t \\)",
      canonicalAnswer: "A0*exp(-epsilon*t)*cos(t)",
    },
  },
  {
    id: "am6-020",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the backbone (frequency–amplitude) relation for the Duffing oscillator \\( y''+y+\\varepsilon y^{3}=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Duffing", "backbone curve"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Frequency rises quadratically with amplitude.",
          workingLatex: "\\omega(A)=1+\\tfrac38\\varepsilon A^{2}",
          explanation: "The backbone curve of a hardening Duffing spring.",
        },
      ],
      finalAnswer: "\\( \\omega(A)=1+\\tfrac38\\varepsilon A^{2} \\)",
      canonicalAnswer: "1+(3/8)*epsilon*A^2",
    },
  },
  {
    id: "am6-021",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Duffing oscillator, the third harmonic appears at \\( O(\\varepsilon) \\). State its angular frequency.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Duffing", "harmonics"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "From the cos3ψ forcing term.",
          workingLatex: "\\tfrac14 A^{3}\\cos3\\psi\\Rightarrow \\text{frequency }3",
          explanation: "The non-resonant part produces a bounded third-harmonic correction at frequency 3.",
        },
      ],
      finalAnswer: "\\( 3 \\) (third harmonic)",
      canonicalAnswer: "3",
    },
  },
  {
    id: "am6-022",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State the amplitude decay rate (per unit \\( t \\)) of the weakly damped oscillator \\( y''+2\\varepsilon y'+y=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["damped oscillator", "decay rate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "From A=A₀e^{−εt}.",
          workingLatex: "-\\frac{1}{A}\\frac{dA}{dt}=\\varepsilon",
          explanation: "The envelope decays at rate ε.",
        },
      ],
      finalAnswer: "\\( \\varepsilon \\)",
      canonicalAnswer: "epsilon",
    },
  },
  {
    id: "am6-023",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "In multiple scales for an oscillator, the secular-removal (solvability) condition requires the coefficients of which two functions on the RHS to vanish?",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "solvability"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Resonant terms are the homogeneous solutions.",
          workingLatex: "\\cos t\\ \\text{and}\\ \\sin t\\ (\\text{equivalently }e^{\\pm it})",
          explanation: "These force the O(ε) problem at its natural frequency and must be removed.",
        },
      ],
      finalAnswer: "\\( \\cos t \\) and \\( \\sin t \\)",
      canonicalAnswer: "cos(t),sin(t)",
    },
  },
  {
    id: "am6-024",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using the Lindstedt–Poincaré strained coordinate \\( \\tau=\\omega t \\), write the Duffing frequency \\( \\omega \\) expansion to \\( O(\\varepsilon) \\) (amplitude \\( A \\)).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Lindstedt–Poincaré", "Duffing"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write ω=1+εω₁ and remove secular terms.",
          workingLatex: "\\omega=1+\\varepsilon\\omega_1,\\quad \\omega_1=\\tfrac38 A^{2}",
          explanation: "Strained coordinates give the same frequency shift as multiple scales.",
        },
        {
          stepNumber: 2,
          description: "State ω.",
          workingLatex: "\\omega=1+\\tfrac38\\varepsilon A^{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\omega=1+\\tfrac38\\varepsilon A^{2} \\)",
      canonicalAnswer: "1+(3/8)*epsilon*A^2",
    },
  },
  {
    id: "am6-025",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Explain (in one line) why straightforward regular perturbation fails for \\( y''+y+\\varepsilon y^{3}=0 \\) over long times.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "secular term"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Resonant self-forcing.",
          workingLatex: "y_1''+y_1=-y_0^{3}\\supset -\\tfrac34A^{3}\\cos t\\Rightarrow y_1\\propto t\\sin t",
          explanation: "The cubic self-forces the oscillator at its own frequency, producing secular growth εt that invalidates the expansion for t~1/ε.",
        },
      ],
      finalAnswer: "Self-resonance gives a secular term \\( \\propto t \\)",
      canonicalAnswer: "secular term grows like t",
    },
  },
  {
    id: "am6-026",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write the complex-amplitude form \\( y_0=A(T)e^{it}+\\bar A(T)e^{-it} \\); state \\( \\partial_t y_0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "complex amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate the fast dependence.",
          workingLatex: "\\partial_t y_0=iA(T)e^{it}-i\\bar A(T)e^{-it}",
          explanation: "The complex-amplitude form streamlines collecting e^{±it} (resonant) terms.",
        },
      ],
      finalAnswer: "\\( iA\\,e^{it}-i\\bar A\\,e^{-it} \\)",
      canonicalAnswer: "I*A(T)*exp(I*t)-I*conjugate(A(T))*exp(-I*t)",
    },
  },
  {
    id: "am6-027",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( y''+y+\\varepsilon y^{3}=0 \\) in complex-amplitude form, the solvability condition is \\( 2iA'+3A^{2}\\bar A=0 \\). Writing \\( A=\\tfrac12 R e^{i\\theta} \\), find \\( R'(T) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "complex amplitude"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate real and imaginary parts.",
          workingLatex: "2iA'=-3|A|^{2}A\\Rightarrow A'=\\tfrac{3i}{2}|A|^{2}A",
          explanation: "The right side is purely imaginary times A, so |A| is constant.",
        },
        {
          stepNumber: 2,
          description: "Magnitude is conserved.",
          workingLatex: "R'=0",
          explanation: "Consistent with constant Duffing amplitude; the phase carries the frequency shift.",
        },
      ],
      finalAnswer: "\\( R'(T)=0 \\)",
      canonicalAnswer: "0",
    },
  },
  {
    id: "am6-028",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Over what timescale is the leading two-timing approximation uniformly accurate?",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "uniform validity"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Slow drift resolved to O(1).",
          workingLatex: "t=O(1/\\varepsilon)",
          explanation: "Removing secular terms extends validity from O(1) to the slow timescale.",
        },
      ],
      finalAnswer: "\\( t=O(1/\\varepsilon) \\)",
      canonicalAnswer: "1/epsilon",
    },
  },
  {
    id: "am6-029",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Rayleigh equation \\( y''+y+\\varepsilon\\big(\\tfrac13(y')^{3}-y'\\big)=0 \\), state the limit-cycle amplitude of the velocity \\( y' \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Rayleigh", "limit cycle"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiating Rayleigh gives Van der Pol for v=y'.",
          workingLatex: "v''+v+\\varepsilon(v^{2}-1)v'=0",
          explanation: "So the velocity executes a Van der Pol limit cycle.",
        },
        {
          stepNumber: 2,
          description: "State the amplitude.",
          workingLatex: "|v|_{\\max}=2",
          explanation: "Same limit-cycle amplitude as Van der Pol.",
        },
      ],
      finalAnswer: "\\( 2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am6-030",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For the Van der Pol amplitude equation \\( A'=\\tfrac12 A(1-\\tfrac14 A^{2}) \\), determine the stability of the fixed point \\( A=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Van der Pol", "stability"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Linearise about A=0.",
          workingLatex: "A'\\approx\\tfrac12 A\\Rightarrow \\text{growth rate }+\\tfrac12>0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Conclude.",
          workingLatex: "A=0\\ \\text{is unstable}",
          explanation: "Small oscillations grow towards the stable limit cycle A=2.",
        },
      ],
      finalAnswer: "\\( A=0 \\) is unstable",
      canonicalAnswer: "unstable",
    },
  },

  // ───────────────────────── Challenge (10) ─────────────────────────
  {
    id: "am6-031",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use multiple scales to derive the Duffing frequency \\( \\omega=1+\\tfrac38\\varepsilon A^{2} \\) for \\( y''+y+\\varepsilon y^{3}=0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "frequency shift"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Two-time expansion.",
          workingLatex: "y=y_0+\\varepsilon y_1,\\ \\partial_{tt}y_0+y_0=0\\Rightarrow y_0=A(T)\\cos(t+\\phi(T))",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "O(ε) equation.",
          workingLatex: "\\partial_{tt}y_1+y_1=-2\\partial_{tT}y_0-y_0^{3}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand the forcing with ψ=t+φ.",
          workingLatex: "-2\\partial_{tT}y_0=2A'\\sin\\psi+2A\\phi'\\cos\\psi;\\quad -y_0^{3}=-A^{3}\\big(\\tfrac34\\cos\\psi+\\tfrac14\\cos3\\psi\\big)",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Remove secular sin ψ and cos ψ.",
          workingLatex: "2A'=0;\\quad 2A\\phi'-\\tfrac34A^{3}=0\\Rightarrow \\phi'=\\tfrac38A^{2}",
          explanation: "",
        },
        {
          stepNumber: 5,
          description: "Frequency.",
          workingLatex: "\\omega=1+\\varepsilon\\phi'=1+\\tfrac38\\varepsilon A^{2}",
          explanation: "Verified numerically (ω≈1.0188 at ε=0.05, A=1).",
        },
      ],
      finalAnswer: "\\( \\omega=1+\\tfrac38\\varepsilon A^{2} \\)",
      canonicalAnswer: "1+(3/8)*epsilon*A^2",
    },
  },
  {
    id: "am6-032",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use multiple scales to derive the Van der Pol amplitude equation \\( A'=\\tfrac12 A(1-\\tfrac14 A^{2}) \\) for \\( y''+y+\\varepsilon(y^{2}-1)y'=0 \\), and hence the limit-cycle amplitude.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Van der Pol", "limit cycle"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Leading solution and O(ε) forcing.",
          workingLatex: "y_0=A(T)\\cos\\psi,\\quad \\partial_{tt}y_1+y_1=-2\\partial_{tT}y_0-(y_0^{2}-1)\\partial_t y_0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand the nonlinear damping term.",
          workingLatex: "-(A^{2}\\cos^{2}\\psi-1)(-A\\sin\\psi)=A(1-A^{2}\\cos^{2}\\psi)\\sin\\psi",
          explanation: "Use cos²ψ sinψ = ¼(sinψ + ... ) to extract the resonant sin ψ part.",
        },
        {
          stepNumber: 3,
          description: "Collect resonant sin ψ and impose solvability.",
          workingLatex: "2A'=A\\big(1-\\tfrac14A^{2}\\big)\\Rightarrow A'=\\tfrac12 A\\big(1-\\tfrac14A^{2}\\big)",
          explanation: "The fundamental of A(1−A²cos²ψ)sinψ is A(1−¼A²)sinψ.",
        },
        {
          stepNumber: 4,
          description: "Steady state.",
          workingLatex: "A'=0\\Rightarrow A=2",
          explanation: "Globally attracting limit cycle.",
        },
      ],
      finalAnswer: "\\( A'=\\tfrac12 A(1-\\tfrac14 A^{2}) \\), limit cycle \\( A=2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "am6-033",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the leading uniformly-valid solution of \\( y''+2\\varepsilon y'+y=0 \\), \\( y(0)=1,\\ y'(0)=0 \\), and compare with the exact envelope.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "damped oscillator"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Solvability gives the amplitude equation.",
          workingLatex: "2A'+2A=0\\Rightarrow A=A_0e^{-T}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply initial conditions.",
          workingLatex: "A_0=1,\\ \\phi=0\\Rightarrow y\\approx e^{-\\varepsilon t}\\cos t",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Compare with the exact solution.",
          workingLatex: "y_{\\text{exact}}=e^{-\\varepsilon t}\\frac{\\cos(\\sqrt{1-\\varepsilon^{2}}\\,t-\\delta)}{\\cos\\delta}",
          explanation: "Envelope e^{−εt} matches exactly; the √(1−ε²) frequency correction is O(ε²), beyond this order.",
        },
      ],
      finalAnswer: "\\( y\\approx e^{-\\varepsilon t}\\cos t \\) (exact envelope \\( e^{-\\varepsilon t} \\))",
      canonicalAnswer: "exp(-epsilon*t)*cos(t)",
    },
  },
  // REVIEW: O(ε²) Duffing frequency correction — standard but the second-order multiple-scales
  // algebra was not machine-checked; confirm the −(21/256)A⁴ coefficient before student use.
  {
    id: "am6-034",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "State the Duffing frequency \\( \\omega \\) for \\( y''+y+\\varepsilon y^{3}=0 \\) to \\( O(\\varepsilon^{2}) \\) (amplitude \\( A \\)).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "higher order"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Leading shift.",
          workingLatex: "\\omega=1+\\tfrac38\\varepsilon A^{2}+\\varepsilon^{2}\\omega_2+\\cdots",
          explanation: "The O(ε) term is the standard hardening shift.",
        },
        {
          stepNumber: 2,
          description: "Second-order correction (standard result).",
          workingLatex: "\\omega_2=-\\tfrac{21}{256}A^{4}",
          explanation: "From carrying the multiple-scales expansion to O(ε²).",
        },
        {
          stepNumber: 3,
          description: "Assemble.",
          workingLatex: "\\omega=1+\\tfrac38\\varepsilon A^{2}-\\tfrac{21}{256}\\varepsilon^{2}A^{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\omega=1+\\tfrac38\\varepsilon A^{2}-\\tfrac{21}{256}\\varepsilon^{2}A^{4} \\)",
      canonicalAnswer: "1+(3/8)*epsilon*A^2-(21/256)*epsilon^2*A^4",
    },
  },
  {
    id: "am6-035",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain the solvability (secular-removal) condition as a Fredholm orthogonality requirement for the \\( O(\\varepsilon) \\) problem \\( \\partial_{tt}y_1+y_1=F(t,T) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "solvability", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Homogeneous solutions of the operator.",
          workingLatex: "\\partial_{tt}+1:\\ \\text{kernel}=\\{\\cos t,\\sin t\\}",
          explanation: "These are the resonant modes.",
        },
        {
          stepNumber: 2,
          description: "Bounded solution requires orthogonality to the kernel.",
          workingLatex: "\\int_0^{2\\pi}F\\cos t\\,dt=0,\\quad \\int_0^{2\\pi}F\\sin t\\,dt=0",
          explanation: "Otherwise the particular solution contains t cos t / t sin t (secular).",
        },
        {
          stepNumber: 3,
          description: "These two conditions are the slow-flow equations.",
          workingLatex: "\\Rightarrow \\text{ODEs for }A(T),\\ \\phi(T)",
          explanation: "Fredholm: a forced resonant problem is solvable (boundedly) iff the forcing is orthogonal to the homogeneous solutions.",
        },
      ],
      finalAnswer: "Forcing must be orthogonal to \\( \\cos t,\\sin t \\) ⇒ the slow-flow ODEs (shown)",
    },
  },
  {
    id: "am6-036",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( y''+y+\\varepsilon y^{3}=0 \\) with \\( y(0)=a,\\ y'(0)=0 \\), write the leading uniformly-valid solution including the amplitude-dependent frequency.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Duffing", "composite"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Constant amplitude, drifting phase.",
          workingLatex: "A=a,\\quad \\phi=\\tfrac38 a^{2}T=\\tfrac38\\varepsilon a^{2}t",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Assemble with the shifted frequency.",
          workingLatex: "y\\approx a\\cos\\!\\Big(\\big(1+\\tfrac38\\varepsilon a^{2}\\big)t\\Big)",
          explanation: "Uniformly valid for t~1/ε; the frequency depends on the initial amplitude a.",
        },
      ],
      finalAnswer: "\\( y\\approx a\\cos\\!\\big((1+\\tfrac38\\varepsilon a^{2})t\\big) \\)",
      canonicalAnswer: "a*cos((1+(3/8)*epsilon*a^2)*t)",
    },
  },
  // REVIEW: forced-resonance slow-flow / jump phenomenon — the detuned amplitude equation is
  // standard but the specific response curve was not machine-checked.
  {
    id: "am6-037",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the weakly forced, weakly damped Duffing oscillator near resonance, write the form of the slow-flow equations governing the amplitude \\( R(T) \\) and phase \\( \\theta(T) \\) (schematically).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "forced Duffing", "resonance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Detuning and forcing enter the slow flow.",
          workingLatex: "R'=-\\gamma R+\\tfrac{F}{2}\\sin\\theta,\\quad R\\theta'=\\sigma R-\\tfrac38R^{3}+\\tfrac{F}{2}\\cos\\theta",
          explanation: "γ is the damping, σ the detuning, F the forcing; the cubic gives the bent response curve.",
        },
        {
          stepNumber: 2,
          description: "Steady states give the (multivalued) response curve.",
          workingLatex: "R'=\\theta'=0\\Rightarrow \\text{amplitude response}",
          explanation: "Multiple steady amplitudes for some σ produce the hysteresis/jump phenomenon.",
        },
      ],
      finalAnswer: "Slow flow: \\( R'=-\\gamma R+\\tfrac F2\\sin\\theta \\), \\( R\\theta'=\\sigma R-\\tfrac38R^{3}+\\tfrac F2\\cos\\theta \\)",
      canonicalAnswer: "R'=-gamma*R+(F/2)*sin(theta); R*theta'=sigma*R-(3/8)*R^3+(F/2)*cos(theta)",
    },
  },
  {
    id: "am6-038",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that the method of multiple scales reproduces the linear-damping result: for \\( y''+2\\varepsilon y'+y=0 \\) the energy \\( E=\\tfrac12(y'^{2}+y^{2}) \\) decays on average like \\( e^{-2\\varepsilon t} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "damped oscillator", "energy"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Amplitude from multiple scales.",
          workingLatex: "y\\approx A_0e^{-\\varepsilon t}\\cos t\\Rightarrow E\\approx\\tfrac12A_0^{2}e^{-2\\varepsilon t}",
          explanation: "Energy is quadratic in amplitude.",
        },
        {
          stepNumber: 2,
          description: "Confirm via the exact energy balance.",
          workingLatex: "\\frac{dE}{dt}=-2\\varepsilon y'^{2},\\quad \\langle y'^{2}\\rangle=\\tfrac12A^{2}\\Rightarrow \\langle\\dot E\\rangle=-2\\varepsilon E",
          explanation: "Averaging over a fast period gives Ė=−2εE, i.e. E∝e^{−2εt}.",
        },
      ],
      finalAnswer: "\\( E\\approx\\tfrac12A_0^{2}e^{-2\\varepsilon t} \\) (shown)",
      canonicalAnswer: "(1/2)*A0^2*exp(-2*epsilon*t)",
    },
  },
  {
    id: "am6-039",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Explain why introducing the independent slow variable \\( T=\\varepsilon t \\) lets multiple scales remove secular terms that a single-variable expansion cannot.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "uniform validity", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Extra freedom in the amplitude.",
          workingLatex: "y_0=A(T)\\cos(t+\\phi(T))",
          explanation: "Promoting the integration constants to slow functions adds the freedom A(T),φ(T).",
        },
        {
          stepNumber: 2,
          description: "Use that freedom to kill resonance.",
          workingLatex: "\\text{choose }A',\\phi'\\ \\text{so that resonant forcing}=0",
          explanation: "A single-variable expansion has fixed constants and cannot cancel the resonant forcing, so it accumulates t·(osc) secular terms.",
        },
        {
          stepNumber: 3,
          description: "Result.",
          workingLatex: "\\Rightarrow y_1\\ \\text{bounded, expansion uniform for }t\\sim1/\\varepsilon",
          explanation: "",
        },
      ],
      finalAnswer: "Slow A(T),φ(T) provide the freedom to cancel resonant forcing ⇒ no secular growth (shown)",
    },
  },
  // REVIEW: parametric (Mathieu) resonance tongue — leading instability boundary is standard but
  // the multiple-scales derivation was not machine-checked.
  {
    id: "am6-040",
    topicRef: "am6",
    topicTitle: "Method of Multiple Scales",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For the Mathieu equation \\( y''+(1+\\varepsilon\\cos 2t)\\,y=0 \\), multiple scales predicts a parametric instability near the natural frequency. State the leading half-width of the unstable tongue in the forcing amplitude.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["multiple scales", "Mathieu", "parametric resonance"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Parametric forcing at 2× the natural frequency drives growth.",
          workingLatex: "y_0=A(T)\\cos t+B(T)\\sin t",
          explanation: "The cos2t modulation couples to the natural mode (principal parametric resonance).",
        },
        {
          stepNumber: 2,
          description: "Solvability gives a linear slow system with a growth rate.",
          workingLatex: "A'=\\tfrac14 B,\\quad B'=\\tfrac14 A\\Rightarrow \\text{growth rate }\\tfrac14",
          explanation: "Eigenvalue ±¼ of the slow system signals exponential growth e^{εt/4}.",
        },
        {
          stepNumber: 3,
          description: "Tongue half-width.",
          workingLatex: "\\text{instability for detuning }|\\delta|<\\tfrac{\\varepsilon}{4}",
          explanation: "The principal tongue opens with half-width ε/4 in the frequency detuning.",
        },
      ],
      finalAnswer: "Half-width \\( \\tfrac{\\varepsilon}{4} \\) (principal parametric resonance)",
      canonicalAnswer: "epsilon/4",
    },
  },
];
