import { Question } from "@/lib/types";

/**
 * Topic: Complex Numbers — Cartesian Arithmetic & Conjugates
 * Ref:   cx1  (Undergraduate Engineering Mathematics, year 1)
 *
 * 70 questions — 21 Foundation, 31 Standard, 18 Challenge.
 * Real/imaginary parts and equality; addition & subtraction; multiplication
 * and powers of i; the complex conjugate and its properties; division by
 * rationalising; solving for real unknowns; z·z̄ and modulus-squared.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (21) ─────────────────────────
  {
    id: "cx1-001",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "State the imaginary part of \\( z=7-4i \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "imaginary part"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Match z to the standard form a+bi.",
          workingLatex: "z=7+(-4)i",
          explanation: "Every complex number is written as a real part a plus b times i. Here a=7 and b=-4. Lining the number up against a+bi is what lets you read the parts off unambiguously.",
        },
        {
          stepNumber: 2,
          description: "Read off the coefficient of i.",
          workingLatex: "\\operatorname{Im}(z)=-4",
          explanation: "The imaginary part is the real number b that multiplies i — it is -4, not -4i. Forgetting the sign or keeping the i are the two usual slips here.",
        },
      ],
      finalAnswer: "\\( -4 \\)",
      canonicalAnswer: "-4",
    },
  },
  {
    id: "cx1-002",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "State the real part of \\( z=-3+5i \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "real part"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Identify the term with no i.",
          workingLatex: "z=-3+5i",
          explanation: "In a+bi the real part is the standalone constant a; here that is -3. The 5i term is the imaginary part and is ignored for this question.",
        },
        {
          stepNumber: 2,
          description: "Read off the real part.",
          workingLatex: "\\operatorname{Re}(z)=-3",
          explanation: "Keep the negative sign — the real part is -3, not 3.",
        },
      ],
      finalAnswer: "\\( -3 \\)",
      canonicalAnswer: "-3",
    },
  },
  {
    id: "cx1-003",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( (3+2i)+(4+i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "addition"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Group real parts and imaginary parts.",
          workingLatex: "(3+4)+(2+1)i",
          explanation: "Addition of complex numbers is componentwise: add the real parts together and the imaginary parts together, exactly like collecting like terms in algebra.",
        },
        {
          stepNumber: 2,
          description: "Carry out each addition.",
          workingLatex: "7+3i",
          explanation: "3+4=7 for the real part and 2+1=3 for the coefficient of i.",
        },
      ],
      finalAnswer: "\\( 7+3i \\)",
      canonicalAnswer: "7+3i",
    },
  },
  {
    id: "cx1-004",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( (6-i)-(2+3i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "subtraction"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Distribute the minus sign over the second bracket.",
          workingLatex: "6-i-2-3i",
          explanation: "Subtracting a complex number flips the sign of both of its parts. The most common error is to subtract the real part but forget to flip the sign of the imaginary part.",
        },
        {
          stepNumber: 2,
          description: "Collect real parts and imaginary parts.",
          workingLatex: "(6-2)+(-1-3)i",
          explanation: "Group 6 and -2 as the real part, and -1 and -3 as the coefficients of i.",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "4-4i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 4-4i \\)",
      canonicalAnswer: "4-4i",
    },
  },
  {
    id: "cx1-005",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Find \\( (2+5i)+(2-5i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "addition", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Add real and imaginary parts separately.",
          workingLatex: "(2+2)+(5-5)i",
          explanation: "These two numbers are conjugates of each other, so watch what happens to the imaginary parts when they are added.",
        },
        {
          stepNumber: 2,
          description: "Simplify; the imaginary parts cancel.",
          workingLatex: "4+0i=4",
          explanation: "Adding a complex number to its conjugate always cancels the imaginary part and leaves a real number equal to twice the real part.",
        },
      ],
      finalAnswer: "\\( 4 \\)",
      canonicalAnswer: "4",
    },
  },
  {
    id: "cx1-006",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( (4i)(3i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply the numerical coefficients and the i factors.",
          workingLatex: "4\\cdot3\\cdot i\\cdot i=12i^{2}",
          explanation: "Treat i like an algebraic symbol for now: multiply 4 and 3 to get 12, and i times i gives i².",
        },
        {
          stepNumber: 2,
          description: "Replace i² with −1.",
          workingLatex: "12(-1)=-12",
          explanation: "The defining property i²=-1 turns the imaginary product into a real number. Forgetting this and leaving 12i² is the classic mistake.",
        },
      ],
      finalAnswer: "\\( -12 \\)",
      canonicalAnswer: "-12",
    },
  },
  {
    id: "cx1-007",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Simplify \\( i^{3} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Split off an i² factor.",
          workingLatex: "i^{3}=i^{2}\\cdot i",
          explanation: "Any power of i above 2 is simplified by peeling off factors of i², because i² is just the constant -1.",
        },
        {
          stepNumber: 2,
          description: "Substitute i²=−1.",
          workingLatex: "(-1)\\cdot i=-i",
          explanation: "This is why the powers of i cycle: i, -1, -i, 1, then repeat.",
        },
      ],
      finalAnswer: "\\( -i \\)",
      canonicalAnswer: "-i",
    },
  },
  {
    id: "cx1-008",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Expand and simplify \\( (2+3i)(1+i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand using FOIL.",
          workingLatex: "2\\cdot1+2\\cdot i+3i\\cdot1+3i\\cdot i",
          explanation: "Multiply each term in the first bracket by each term in the second, just as for any two binomials.",
        },
        {
          stepNumber: 2,
          description: "Write the four products.",
          workingLatex: "2+2i+3i+3i^{2}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Replace i² with −1.",
          workingLatex: "2+2i+3i-3",
          explanation: "The 3i² term becomes -3, a real contribution. This is the step where complex multiplication differs from ordinary algebra.",
        },
        {
          stepNumber: 4,
          description: "Collect real and imaginary parts.",
          workingLatex: "-1+5i",
          explanation: "Real: 2-3=-1; imaginary: 2i+3i=5i.",
        },
      ],
      finalAnswer: "\\( -1+5i \\)",
      canonicalAnswer: "-1+5i",
    },
  },
  {
    id: "cx1-009",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the complex conjugate of \\( 5-8i \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Keep the real part, flip the sign of the imaginary part.",
          workingLatex: "\\overline{5-8i}=5+8i",
          explanation: "The conjugate of a+bi is a-bi: the real part is untouched and only the sign in front of i changes. Here -8i becomes +8i.",
        },
      ],
      finalAnswer: "\\( 5+8i \\)",
      canonicalAnswer: "5+8i",
    },
  },
  {
    id: "cx1-010",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the complex conjugate of \\( -2+i \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Flip the sign of the imaginary part only.",
          workingLatex: "\\overline{-2+i}=-2-i",
          explanation: "The real part -2 stays as it is; the +i (coefficient +1) becomes -i. Don't be tempted to also change the sign of the real part.",
        },
      ],
      finalAnswer: "\\( -2-i \\)",
      canonicalAnswer: "-2-i",
    },
  },
  {
    id: "cx1-011",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Evaluate \\( (4+i)(4-i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "difference of squares"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recognise a number times its conjugate.",
          workingLatex: "(4+i)(4-i)=4^{2}-(i)^{2}",
          explanation: "This is a difference of two squares (a+b)(a-b)=a²-b², with a=4 and b=i. Spotting this saves expanding all four terms.",
        },
        {
          stepNumber: 2,
          description: "Use i²=−1.",
          workingLatex: "16-(-1)=16+1",
          explanation: "Subtracting i²=-1 adds 1, which is why a number times its conjugate is always real and positive.",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "17",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 17 \\)",
      canonicalAnswer: "17",
    },
  },
  {
    id: "cx1-012",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "For \\( z=3+4i \\), evaluate \\( z\\bar z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "modulus"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply z·z̄ = a²+b².",
          workingLatex: "z\\bar z=3^{2}+4^{2}",
          explanation: "Multiplying z=a+bi by its conjugate a-bi always gives a²+b², a real number. You may quote this directly rather than expanding the brackets.",
        },
        {
          stepNumber: 2,
          description: "Evaluate.",
          workingLatex: "9+16=25",
          explanation: "This equals |z|², the square of the modulus.",
        },
      ],
      finalAnswer: "\\( 25 \\)",
      canonicalAnswer: "25",
    },
  },
  {
    id: "cx1-013",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Expand \\( (1+i)^{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "squaring"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply (a+b)²=a²+2ab+b².",
          workingLatex: "1^{2}+2(1)(i)+i^{2}",
          explanation: "Square the binomial with the standard identity; here a=1 and b=i.",
        },
        {
          stepNumber: 2,
          description: "Write out the terms.",
          workingLatex: "1+2i+i^{2}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Replace i²=−1 and collect.",
          workingLatex: "1+2i-1=2i",
          explanation: "The two real terms 1 and -1 cancel, leaving a purely imaginary result.",
        },
      ],
      finalAnswer: "\\( 2i \\)",
      canonicalAnswer: "2i",
    },
  },
  {
    id: "cx1-014",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Simplify \\( 5(2-3i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "scalar multiple"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Distribute the 5 over both parts.",
          workingLatex: "5\\cdot2-5\\cdot3i",
          explanation: "A real multiplier scales the real part and the imaginary part equally — just ordinary distribution.",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "10-15i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 10-15i \\)",
      canonicalAnswer: "10-15i",
    },
  },
  {
    id: "cx1-015",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Simplify \\( i^{10} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write the power as (i²) raised to a power.",
          workingLatex: "i^{10}=(i^{2})^{5}",
          explanation: "Because 10 is even, i^10 is a whole number of i² factors. Pairing the i's this way avoids cycling through all ten powers.",
        },
        {
          stepNumber: 2,
          description: "Substitute i²=−1.",
          workingLatex: "(-1)^{5}=-1",
          explanation: "An odd power of -1 is -1. (Equivalently, 10≡2 mod 4, and i²=-1.)",
        },
      ],
      finalAnswer: "\\( -1 \\)",
      canonicalAnswer: "-1",
    },
  },
  {
    id: "cx1-016",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( (7+2i)+(-7+2i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "addition"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Add real parts and imaginary parts separately.",
          workingLatex: "(7-7)+(2+2)i",
          explanation: "Group the real parts 7 and -7, and the imaginary coefficients 2 and 2.",
        },
        {
          stepNumber: 2,
          description: "Simplify; the real parts cancel.",
          workingLatex: "0+4i=4i",
          explanation: "The result is purely imaginary because the real parts were opposite.",
        },
      ],
      finalAnswer: "\\( 4i \\)",
      canonicalAnswer: "4i",
    },
  },
  {
    id: "cx1-017",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Simplify \\( -(3-6i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "negation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply each part by −1.",
          workingLatex: "-3-(-6i)",
          explanation: "Negating a complex number changes the sign of both the real and the imaginary part.",
        },
        {
          stepNumber: 2,
          description: "Simplify the double negative.",
          workingLatex: "-3+6i",
          explanation: "-(-6i) becomes +6i.",
        },
      ],
      finalAnswer: "\\( -3+6i \\)",
      canonicalAnswer: "-3+6i",
    },
  },
  {
    id: "cx1-018",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Expand and simplify \\( (2-i)(3+i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand with FOIL.",
          workingLatex: "6+2i-3i-i^{2}",
          explanation: "Multiply each term of (2-i) by each term of (3+i): 2·3, 2·i, -i·3, -i·i.",
        },
        {
          stepNumber: 2,
          description: "Replace i²=−1.",
          workingLatex: "6+2i-3i+1",
          explanation: "The -i² term becomes +1.",
        },
        {
          stepNumber: 3,
          description: "Collect real and imaginary parts.",
          workingLatex: "7-i",
          explanation: "Real: 6+1=7; imaginary: 2i-3i=-i.",
        },
      ],
      finalAnswer: "\\( 7-i \\)",
      canonicalAnswer: "7-i",
    },
  },
  {
    id: "cx1-019",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "For \\( z=6-2i \\), find \\( z+\\bar z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write down the conjugate, then add.",
          workingLatex: "(6-2i)+(6+2i)",
          explanation: "The conjugate of 6-2i is 6+2i; adding them lines up like terms.",
        },
        {
          stepNumber: 2,
          description: "The imaginary parts cancel.",
          workingLatex: "12",
          explanation: "In general z+z̄ = 2·Re(z), here 2·6 = 12 — always a real number.",
        },
      ],
      finalAnswer: "\\( 12 \\)",
      canonicalAnswer: "12",
    },
  },
  {
    id: "cx1-020",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( z=6-2i \\), find \\( z-\\bar z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Subtract the conjugate from z.",
          workingLatex: "(6-2i)-(6+2i)",
          explanation: "Distribute the minus sign over 6+2i carefully — both of its parts change sign.",
        },
        {
          stepNumber: 2,
          description: "The real parts cancel.",
          workingLatex: "-4i",
          explanation: "In general z-z̄ = 2i·Im(z); here 2i·(-2) = -4i — always purely imaginary.",
        },
      ],
      finalAnswer: "\\( -4i \\)",
      canonicalAnswer: "-4i",
    },
  },
  {
    id: "cx1-021",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Simplify \\( \\dfrac{4+2i}{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "division by real"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Split the fraction over each term.",
          workingLatex: "\\frac{4}{2}+\\frac{2}{2}i",
          explanation: "Dividing by a real number is easy: divide the real part and the imaginary part separately. No conjugate is needed because the denominator is already real.",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "2+i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2+i \\)",
      canonicalAnswer: "2+i",
    },
  },

  // ───────────────────────── Standard (31) ─────────────────────────
  {
    id: "cx1-022",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{3+i}{1-i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate of the denominator.",
          workingLatex: "\\frac{3+i}{1-i}\\cdot\\frac{1+i}{1+i}",
          explanation: "The conjugate of 1-i is 1+i. Multiplying by it over itself is multiplying by 1, so the value is unchanged, but it makes the denominator real.",
        },
        {
          stepNumber: 2,
          description: "Compute the real denominator.",
          workingLatex: "(1-i)(1+i)=1^{2}+1^{2}=2",
          explanation: "A number times its conjugate gives a²+b², here 1+1=2.",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(3+i)(1+i)=3+3i+i+i^{2}=2+4i",
          explanation: "Use i²=-1: the constant becomes 3-1=2 and the imaginary part is 3i+i=4i.",
        },
        {
          stepNumber: 4,
          description: "Divide each part by 2.",
          workingLatex: "\\frac{2+4i}{2}=1+2i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 1+2i \\)",
      canonicalAnswer: "1+2i",
    },
  },
  {
    id: "cx1-023",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{2-3i}{4+i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 4−i.",
          workingLatex: "\\frac{2-3i}{4+i}\\cdot\\frac{4-i}{4-i}",
          explanation: "The conjugate of 4+i is 4-i; this clears i from the denominator.",
        },
        {
          stepNumber: 2,
          description: "Compute the denominator.",
          workingLatex: "(4+i)(4-i)=16+1=17",
          explanation: "Again a²+b² with a=4, b=1.",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(2-3i)(4-i)=8-2i-12i+3i^{2}",
          explanation: "Keep careful track of signs on the cross terms.",
        },
        {
          stepNumber: 4,
          description: "Use i²=−1 and collect.",
          workingLatex: "8-14i-3=5-14i",
          explanation: "The 3i² term becomes -3, so the real part is 8-3=5.",
        },
        {
          stepNumber: 5,
          description: "Write over 17.",
          workingLatex: "\\frac{5}{17}-\\frac{14}{17}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{5}{17}-\\frac{14}{17}i \\)",
      canonicalAnswer: "(5-14i)/17",
    },
  },
  {
    id: "cx1-024",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{1}{2+i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "reciprocal", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 2−i.",
          workingLatex: "\\frac{1}{2+i}\\cdot\\frac{2-i}{2-i}=\\frac{2-i}{(2+i)(2-i)}",
          explanation: "To express a reciprocal in a+bi form, rationalise using the conjugate of the denominator.",
        },
        {
          stepNumber: 2,
          description: "Evaluate the denominator.",
          workingLatex: "(2+i)(2-i)=4+1=5",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Split into real and imaginary parts.",
          workingLatex: "\\frac{2-i}{5}=\\frac{2}{5}-\\frac{1}{5}i",
          explanation: "Note this is exactly z̄/|z|², the general formula for 1/z.",
        },
      ],
      finalAnswer: "\\( \\frac{2}{5}-\\frac{1}{5}i \\)",
      canonicalAnswer: "(2-i)/5",
    },
  },
  {
    id: "cx1-025",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{5+5i}{3-4i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 3+4i.",
          workingLatex: "\\frac{5+5i}{3-4i}\\cdot\\frac{3+4i}{3+4i}",
          explanation: "The conjugate of 3-4i is 3+4i.",
        },
        {
          stepNumber: 2,
          description: "Compute the denominator.",
          workingLatex: "(3-4i)(3+4i)=9+16=25",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(5+5i)(3+4i)=15+20i+15i+20i^{2}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Use i²=−1 and collect.",
          workingLatex: "15+35i-20=-5+35i",
          explanation: "Real: 15-20=-5; imaginary: 20i+15i=35i.",
        },
        {
          stepNumber: 5,
          description: "Divide by 25.",
          workingLatex: "\\frac{-5+35i}{25}=-\\frac{1}{5}+\\frac{7}{5}i",
          explanation: "Simplify -5/25 to -1/5 and 35/25 to 7/5.",
        },
      ],
      finalAnswer: "\\( -\\frac{1}{5}+\\frac{7}{5}i \\)",
      canonicalAnswer: "(-5+35i)/25",
    },
  },
  {
    id: "cx1-026",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{1+2i}{2-i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 2+i.",
          workingLatex: "\\frac{1+2i}{2-i}\\cdot\\frac{2+i}{2+i}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Compute the denominator.",
          workingLatex: "(2-i)(2+i)=4+1=5",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(1+2i)(2+i)=2+i+4i+2i^{2}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Use i²=−1 and collect.",
          workingLatex: "2+5i-2=5i",
          explanation: "The real parts cancel, leaving a purely imaginary numerator.",
        },
        {
          stepNumber: 5,
          description: "Divide by 5.",
          workingLatex: "\\frac{5i}{5}=i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( i \\)",
      canonicalAnswer: "i",
    },
  },
  {
    id: "cx1-027",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the complex number \\( z \\) satisfying \\( z+(2-3i)=5+i \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "solving"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Isolate z.",
          workingLatex: "z=(5+i)-(2-3i)",
          explanation: "Subtract 2-3i from both sides; treat z like an unknown in a linear equation.",
        },
        {
          stepNumber: 2,
          description: "Distribute the minus sign.",
          workingLatex: "z=5+i-2+3i",
          explanation: "Both parts of 2-3i change sign: -2 and +3i.",
        },
        {
          stepNumber: 3,
          description: "Collect real and imaginary parts.",
          workingLatex: "z=3+4i",
          explanation: "Real: 5-2=3; imaginary: i+3i=4i.",
        },
      ],
      finalAnswer: "\\( z=3+4i \\)",
      canonicalAnswer: "3+4i",
    },
  },
  {
    id: "cx1-028",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( 2z-i=z+3+2i \\) for \\( z \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "solving"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Gather z terms on the left, constants on the right.",
          workingLatex: "2z-z=3+2i+i",
          explanation: "Subtract z from both sides and add i to both sides, exactly as in a real linear equation.",
        },
        {
          stepNumber: 2,
          description: "Combine like terms.",
          workingLatex: "z=3+3i",
          explanation: "2z-z=z on the left; 2i+i=3i on the right.",
        },
      ],
      finalAnswer: "\\( z=3+3i \\)",
      canonicalAnswer: "3+3i",
    },
  },
  {
    id: "cx1-029",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Expand and simplify \\( (3+2i)^{2} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "squaring"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply (a+b)²=a²+2ab+b².",
          workingLatex: "3^{2}+2(3)(2i)+(2i)^{2}",
          explanation: "Square with a=3, b=2i. Remember (2i)² is 4i², not 2i².",
        },
        {
          stepNumber: 2,
          description: "Write out the terms.",
          workingLatex: "9+12i+4i^{2}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Use i²=−1 and collect.",
          workingLatex: "9+12i-4=5+12i",
          explanation: "The 4i² becomes -4.",
        },
      ],
      finalAnswer: "\\( 5+12i \\)",
      canonicalAnswer: "5+12i",
    },
  },
  {
    id: "cx1-030",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Expand and simplify \\( (2-i)^{3} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square the base first.",
          workingLatex: "(2-i)^{2}=4-4i+i^{2}",
          explanation: "Build the cube as (2-i)²·(2-i); doing the square first keeps the arithmetic manageable.",
        },
        {
          stepNumber: 2,
          description: "Simplify the square.",
          workingLatex: "4-4i-1=3-4i",
          explanation: "i²=-1 gives the real part 4-1=3.",
        },
        {
          stepNumber: 3,
          description: "Multiply by (2−i) again.",
          workingLatex: "(3-4i)(2-i)=6-3i-8i+4i^{2}",
          explanation: "Expand with FOIL.",
        },
        {
          stepNumber: 4,
          description: "Use i²=−1 and collect.",
          workingLatex: "6-11i-4=2-11i",
          explanation: "Real: 6-4=2; imaginary: -3i-8i=-11i.",
        },
      ],
      finalAnswer: "\\( 2-11i \\)",
      canonicalAnswer: "2-11i",
    },
  },
  {
    id: "cx1-031",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Evaluate \\( (1+i)^{4} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square once.",
          workingLatex: "(1+i)^{2}=1+2i+i^{2}=2i",
          explanation: "Squaring first turns a fourth power into the square of a square — much faster than expanding (1+i)⁴ directly.",
        },
        {
          stepNumber: 2,
          description: "Square the result.",
          workingLatex: "(2i)^{2}=4i^{2}",
          explanation: "(1+i)⁴ = ((1+i)²)² = (2i)².",
        },
        {
          stepNumber: 3,
          description: "Use i²=−1.",
          workingLatex: "4(-1)=-4",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -4 \\)",
      canonicalAnswer: "-4",
    },
  },
  {
    id: "cx1-032",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{1}{i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "reciprocal", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by −i, the conjugate of i.",
          workingLatex: "\\frac{1}{i}\\cdot\\frac{-i}{-i}=\\frac{-i}{-i^{2}}",
          explanation: "The conjugate of i (=0+i) is -i. This rationalises the denominator.",
        },
        {
          stepNumber: 2,
          description: "Simplify the denominator with i²=−1.",
          workingLatex: "\\frac{-i}{1}=-i",
          explanation: "-i² = -(-1) = 1, so the denominator becomes 1. A useful fact to memorise: 1/i = -i.",
        },
      ],
      finalAnswer: "\\( -i \\)",
      canonicalAnswer: "-i",
    },
  },
  {
    id: "cx1-033",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{3-2i}{i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by −i.",
          workingLatex: "\\frac{(3-2i)(-i)}{i(-i)}",
          explanation: "Using -i clears i from the denominator since i·(-i)=-i²=1.",
        },
        {
          stepNumber: 2,
          description: "Expand the numerator.",
          workingLatex: "\\frac{-3i+2i^{2}}{1}",
          explanation: "Distribute -i across 3-2i.",
        },
        {
          stepNumber: 3,
          description: "Use i²=−1.",
          workingLatex: "-2-3i",
          explanation: "2i² = -2 gives the real part.",
        },
      ],
      finalAnswer: "\\( -2-3i \\)",
      canonicalAnswer: "-2-3i",
    },
  },
  {
    id: "cx1-034",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the conjugate of \\( (2+3i)(1-i) \\), giving your answer in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "multiplication"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply out the product first.",
          workingLatex: "(2+3i)(1-i)=2-2i+3i-3i^{2}",
          explanation: "Expand before conjugating; it is cleaner than conjugating each factor (though that would also work).",
        },
        {
          stepNumber: 2,
          description: "Use i²=−1 and collect.",
          workingLatex: "2+i+3=5+i",
          explanation: "Real: 2+3=5; imaginary: -2i+3i=i.",
        },
        {
          stepNumber: 3,
          description: "Take the conjugate.",
          workingLatex: "\\overline{5+i}=5-i",
          explanation: "Flip the sign of the imaginary part only.",
        },
      ],
      finalAnswer: "\\( 5-i \\)",
      canonicalAnswer: "5-i",
    },
  },
  {
    id: "cx1-035",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Let \\( z=\\dfrac{2+i}{1-i} \\). Find \\( z\\bar z \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "modulus", "division"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recognise z·z̄ = |z|².",
          workingLatex: "z\\bar z=|z|^{2}",
          explanation: "Rather than first simplifying z to a+bi, use that the product of any z with its conjugate is the square of its modulus.",
        },
        {
          stepNumber: 2,
          description: "Use the quotient rule for modulus.",
          workingLatex: "|z|^{2}=\\frac{|2+i|^{2}}{|1-i|^{2}}=\\frac{2^{2}+1^{2}}{1^{2}+1^{2}}",
          explanation: "The modulus of a quotient is the quotient of the moduli, so |z|² is the ratio of the two a²+b² values.",
        },
        {
          stepNumber: 3,
          description: "Evaluate.",
          workingLatex: "\\frac{5}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{5}{2} \\)",
      canonicalAnswer: "5/2",
    },
  },
  {
    id: "cx1-036",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the complex number \\( z \\) for which \\( \\bar z=2z+3-i \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "solving"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute z=x+yi and z̄=x−yi.",
          workingLatex: "x-yi=2(x+yi)+3-i",
          explanation: "When an equation mixes z and z̄, splitting into real unknowns x and y is the reliable method.",
        },
        {
          stepNumber: 2,
          description: "Expand the right-hand side.",
          workingLatex: "x-yi=(2x+3)+(2y-1)i",
          explanation: "Group the real terms 2x+3 and the imaginary terms (2y-1)i.",
        },
        {
          stepNumber: 3,
          description: "Equate real and imaginary parts.",
          workingLatex: "x=2x+3,\\quad -y=2y-1",
          explanation: "Two complex numbers are equal exactly when their real parts match and their imaginary parts match.",
        },
        {
          stepNumber: 4,
          description: "Solve the two real equations.",
          workingLatex: "x=-3,\\quad y=\\frac{1}{3}",
          explanation: "From x=2x+3, x=-3; from -y=2y-1, 3y=1 so y=1/3.",
        },
      ],
      finalAnswer: "\\( z=-3+\\frac{1}{3}i \\)",
      canonicalAnswer: "-3+(1/3)i",
    },
  },
  {
    id: "cx1-037",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{4+3i}{4-3i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 4+3i.",
          workingLatex: "\\frac{4+3i}{4-3i}\\cdot\\frac{4+3i}{4+3i}",
          explanation: "Since the numerator is already the conjugate of the denominator, the numerator becomes (4+3i)².",
        },
        {
          stepNumber: 2,
          description: "Compute the denominator.",
          workingLatex: "(4-3i)(4+3i)=16+9=25",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(4+3i)^{2}=16+24i+9i^{2}=7+24i",
          explanation: "9i² = -9, so the real part is 16-9=7.",
        },
        {
          stepNumber: 4,
          description: "Divide by 25.",
          workingLatex: "\\frac{7}{25}+\\frac{24}{25}i",
          explanation: "Notice the modulus is 1, as expected for z̄ over z divided by... here z/z̄.",
        },
      ],
      finalAnswer: "\\( \\frac{7}{25}+\\frac{24}{25}i \\)",
      canonicalAnswer: "(7+24i)/25",
    },
  },
  {
    id: "cx1-038",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{1+i}{1-i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 1+i.",
          workingLatex: "\\frac{1+i}{1-i}\\cdot\\frac{1+i}{1+i}=\\frac{(1+i)^{2}}{(1-i)(1+i)}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Evaluate numerator and denominator.",
          workingLatex: "\\frac{2i}{2}",
          explanation: "(1+i)²=2i and (1-i)(1+i)=2.",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( i \\)",
      canonicalAnswer: "i",
    },
  },
  {
    id: "cx1-039",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{2+i}{1+2i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 1−2i.",
          workingLatex: "\\frac{2+i}{1+2i}\\cdot\\frac{1-2i}{1-2i}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Compute the denominator.",
          workingLatex: "(1+2i)(1-2i)=1+4=5",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(2+i)(1-2i)=2-4i+i-2i^{2}=4-3i",
          explanation: "The -2i² becomes +2, so the real part is 2+2=4.",
        },
        {
          stepNumber: 4,
          description: "Divide by 5.",
          workingLatex: "\\frac{4}{5}-\\frac{3}{5}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{4}{5}-\\frac{3}{5}i \\)",
      canonicalAnswer: "(4-3i)/5",
    },
  },
  {
    id: "cx1-040",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Find the real number \\( x \\) such that \\( (x+i)(2-i) \\) is real.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "real condition"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the product.",
          workingLatex: "(x+i)(2-i)=2x-xi+2i-i^{2}",
          explanation: "Treat x as a real constant and expand with FOIL.",
        },
        {
          stepNumber: 2,
          description: "Use i²=−1 and group into real + imaginary.",
          workingLatex: "(2x+1)+(2-x)i",
          explanation: "Real part 2x+1 (the +1 comes from -i²); imaginary part (2-x)i.",
        },
        {
          stepNumber: 3,
          description: "A real number has zero imaginary part.",
          workingLatex: "2-x=0\\Rightarrow x=2",
          explanation: "Set the coefficient of i to zero — that is exactly the condition for the result to be real.",
        },
      ],
      finalAnswer: "\\( x=2 \\)",
      canonicalAnswer: "2",
    },
  },
  {
    id: "cx1-041",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Find the real number \\( x \\) such that \\( \\dfrac{3+xi}{1+i} \\) is purely imaginary.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "imaginary condition", "division"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate 1−i.",
          workingLatex: "\\frac{(3+xi)(1-i)}{(1+i)(1-i)}=\\frac{(3+xi)(1-i)}{2}",
          explanation: "First put the quotient in a+bi form so its real and imaginary parts are visible.",
        },
        {
          stepNumber: 2,
          description: "Expand the numerator.",
          workingLatex: "(3+xi)(1-i)=3-3i+xi-xi^{2}=(3+x)+(x-3)i",
          explanation: "The -xi² becomes +x, contributing to the real part.",
        },
        {
          stepNumber: 3,
          description: "Purely imaginary means real part = 0.",
          workingLatex: "\\frac{3+x}{2}=0\\Rightarrow x=-3",
          explanation: "Set the real part to zero. (Check: the imaginary part x-3=-6 is non-zero, so it genuinely is purely imaginary.)",
        },
      ],
      finalAnswer: "\\( x=-3 \\)",
      canonicalAnswer: "-3",
    },
  },
  {
    id: "cx1-042",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "For \\( z=5-12i \\), evaluate \\( z\\bar z \\) and hence state \\( |z| \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "modulus"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute z·z̄ = a²+b².",
          workingLatex: "z\\bar z=5^{2}+12^{2}=25+144",
          explanation: "Multiplying z by its conjugate gives a²+b² directly.",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "z\\bar z=169",
          explanation: "This value is |z|².",
        },
        {
          stepNumber: 3,
          description: "Take the positive square root for the modulus.",
          workingLatex: "|z|=\\sqrt{169}=13",
          explanation: "Modulus is always non-negative, so take the positive root.",
        },
      ],
      finalAnswer: "\\( |z|=13 \\)",
      canonicalAnswer: "13",
    },
  },
  {
    id: "cx1-043",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Evaluate \\( (1-i)^{6} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square the base.",
          workingLatex: "(1-i)^{2}=1-2i+i^{2}=-2i",
          explanation: "The two real terms 1 and -1 cancel, leaving -2i.",
        },
        {
          stepNumber: 2,
          description: "Write the sixth power as a cube of the square.",
          workingLatex: "(1-i)^{6}=\\left((1-i)^{2}\\right)^{3}=(-2i)^{3}",
          explanation: "Reducing the exponent through the square keeps the numbers small.",
        },
        {
          stepNumber: 3,
          description: "Expand (−2i)³.",
          workingLatex: "(-2)^{3}i^{3}=-8i^{3}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Use i³=−i.",
          workingLatex: "-8(-i)=8i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 8i \\)",
      canonicalAnswer: "8i",
    },
  },
  {
    id: "cx1-044",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\dfrac{2+3i}{2-3i}+\\dfrac{2-3i}{2+3i} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use a common denominator (2−3i)(2+3i)=13.",
          workingLatex: "\\frac{(2+3i)^{2}+(2-3i)^{2}}{13}",
          explanation: "The two denominators are conjugates, so their product is the real number 2²+3²=13.",
        },
        {
          stepNumber: 2,
          description: "Expand each square.",
          workingLatex: "(2+3i)^{2}=-5+12i,\\quad (2-3i)^{2}=-5-12i",
          explanation: "These two results are themselves conjugates.",
        },
        {
          stepNumber: 3,
          description: "Add the numerators; imaginary parts cancel.",
          workingLatex: "\\frac{(-5+12i)+(-5-12i)}{13}=\\frac{-10}{13}",
          explanation: "A number plus its conjugate is twice its real part, here 2·(-5)=-10.",
        },
      ],
      finalAnswer: "\\( -\\frac{10}{13} \\)",
      canonicalAnswer: "-10/13",
    },
  },
  {
    id: "cx1-045",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Simplify \\( \\dfrac{3+i}{2-i}-(1-i) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "subtraction"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rationalise the quotient with the conjugate 2+i.",
          workingLatex: "\\frac{(3+i)(2+i)}{(2-i)(2+i)}=\\frac{5+5i}{5}",
          explanation: "Denominator (2-i)(2+i)=5; numerator (3+i)(2+i)=6+3i+2i+i²=5+5i.",
        },
        {
          stepNumber: 2,
          description: "Simplify the quotient.",
          workingLatex: "\\frac{5+5i}{5}=1+i",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Subtract (1−i).",
          workingLatex: "(1+i)-(1-i)=2i",
          explanation: "Real parts cancel; i-(-i)=2i.",
        },
      ],
      finalAnswer: "\\( 2i \\)",
      canonicalAnswer: "2i",
    },
  },
  {
    id: "cx1-046",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Simplify \\( i^{2026} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Recall the powers of i cycle with period 4.",
          workingLatex: "i^{1}=i,\\ i^{2}=-1,\\ i^{3}=-i,\\ i^{4}=1",
          explanation: "Only the exponent modulo 4 matters.",
        },
        {
          stepNumber: 2,
          description: "Reduce the exponent modulo 4.",
          workingLatex: "2026=4\\cdot506+2\\Rightarrow 2026\\equiv2",
          explanation: "Divide 2026 by 4: remainder 2.",
        },
        {
          stepNumber: 3,
          description: "Evaluate i² .",
          workingLatex: "i^{2026}=i^{2}=-1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -1 \\)",
      canonicalAnswer: "-1",
    },
  },
  {
    id: "cx1-047",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{(2+i)^{2}}{3-4i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "squaring", "division"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Square the numerator.",
          workingLatex: "(2+i)^{2}=4+4i+i^{2}=3+4i",
          explanation: "Simplify the top before dividing.",
        },
        {
          stepNumber: 2,
          description: "Multiply top and bottom by the conjugate 3+4i.",
          workingLatex: "\\frac{(3+4i)(3+4i)}{(3-4i)(3+4i)}=\\frac{(3+4i)^{2}}{25}",
          explanation: "Denominator (3-4i)(3+4i)=9+16=25.",
        },
        {
          stepNumber: 3,
          description: "Expand the numerator.",
          workingLatex: "(3+4i)^{2}=9+24i+16i^{2}=-7+24i",
          explanation: "16i² = -16, so the real part is 9-16=-7.",
        },
        {
          stepNumber: 4,
          description: "Divide by 25.",
          workingLatex: "-\\frac{7}{25}+\\frac{24}{25}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\frac{7}{25}+\\frac{24}{25}i \\)",
      canonicalAnswer: "(-7+24i)/25",
    },
  },
  {
    id: "cx1-048",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( z=4+3i \\), express \\( \\dfrac{1}{z} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "reciprocal", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use 1/z = z̄/(z·z̄).",
          workingLatex: "\\frac{1}{4+3i}=\\frac{4-3i}{(4+3i)(4-3i)}",
          explanation: "Multiply top and bottom by the conjugate; the denominator becomes the real number z·z̄.",
        },
        {
          stepNumber: 2,
          description: "Evaluate the denominator.",
          workingLatex: "(4+3i)(4-3i)=16+9=25",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Split into real and imaginary parts.",
          workingLatex: "\\frac{4-3i}{25}=\\frac{4}{25}-\\frac{3}{25}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\frac{4}{25}-\\frac{3}{25}i \\)",
      canonicalAnswer: "(4-3i)/25",
    },
  },
  {
    id: "cx1-049",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Simplify \\( (1+i)^{2}(1-i) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Evaluate the square first.",
          workingLatex: "(1+i)^{2}=2i",
          explanation: "Simplifying the squared factor before multiplying keeps the work light.",
        },
        {
          stepNumber: 2,
          description: "Multiply by (1−i).",
          workingLatex: "2i(1-i)=2i-2i^{2}",
          explanation: "Distribute 2i over both terms.",
        },
        {
          stepNumber: 3,
          description: "Use i²=−1.",
          workingLatex: "2i+2=2+2i",
          explanation: "-2i² = +2.",
        },
      ],
      finalAnswer: "\\( 2+2i \\)",
      canonicalAnswer: "2+2i",
    },
  },
  {
    id: "cx1-050",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find the complex number \\( z=x+yi \\) (with \\( x,y \\) real) satisfying \\( (x+yi)(1-i)=2+4i \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "solving", "real and imaginary parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the left side.",
          workingLatex: "(x+yi)(1-i)=x-xi+yi-yi^{2}",
          explanation: "Treat x and y as real constants and expand.",
        },
        {
          stepNumber: 2,
          description: "Group into real and imaginary parts.",
          workingLatex: "(x+y)+(y-x)i=2+4i",
          explanation: "The -yi² becomes +y, joining the real part.",
        },
        {
          stepNumber: 3,
          description: "Equate parts.",
          workingLatex: "x+y=2,\\quad y-x=4",
          explanation: "Match real with real and imaginary with imaginary.",
        },
        {
          stepNumber: 4,
          description: "Solve the simultaneous equations.",
          workingLatex: "x=-1,\\quad y=3",
          explanation: "Adding the equations gives 2y=6, so y=3 and then x=-1.",
        },
      ],
      finalAnswer: "\\( z=-1+3i \\)",
      canonicalAnswer: "-1+3i",
    },
  },
  {
    id: "cx1-051",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Evaluate \\( \\dfrac{1}{1+i}+\\dfrac{1}{1-i} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "reciprocal", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rationalise each fraction.",
          workingLatex: "\\frac{1-i}{(1+i)(1-i)}+\\frac{1+i}{(1-i)(1+i)}",
          explanation: "Multiply each term by the conjugate of its denominator; both denominators become (1)²+(1)²=2.",
        },
        {
          stepNumber: 2,
          description: "Write over the common denominator 2.",
          workingLatex: "\\frac{(1-i)+(1+i)}{2}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Add; the imaginary parts cancel.",
          workingLatex: "\\frac{2}{2}=1",
          explanation: "The two numerators are conjugates, so their sum is real.",
        },
      ],
      finalAnswer: "\\( 1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "cx1-052",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( z=2+i \\), evaluate \\( z+z^{2}+z^{3} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers", "addition"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute z².",
          workingLatex: "z^{2}=(2+i)^{2}=4+4i+i^{2}=3+4i",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Compute z³ = z²·z.",
          workingLatex: "z^{3}=(3+4i)(2+i)=6+3i+8i+4i^{2}=2+11i",
          explanation: "4i² = -4, so the real part is 6-4=2.",
        },
        {
          stepNumber: 3,
          description: "Add the three terms.",
          workingLatex: "(2+i)+(3+4i)+(2+11i)",
          explanation: "Line up real parts and imaginary parts.",
        },
        {
          stepNumber: 4,
          description: "Collect.",
          workingLatex: "7+16i",
          explanation: "Real: 2+3+2=7; imaginary: 1+4+11=16.",
        },
      ],
      finalAnswer: "\\( 7+16i \\)",
      canonicalAnswer: "7+16i",
    },
  },

  // ───────────────────────── Challenge (18) ─────────────────────────
  {
    id: "cx1-053",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( z=a+bi \\) and \\( w=c+di \\), prove that \\( \\overline{z+w}=\\bar z+\\bar w \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Add z and w componentwise.",
          workingLatex: "z+w=(a+c)+(b+d)i",
          explanation: "Start from the left-hand side: add real parts and imaginary parts.",
        },
        {
          stepNumber: 2,
          description: "Conjugate the sum by flipping the imaginary part.",
          workingLatex: "\\overline{z+w}=(a+c)-(b+d)i",
          explanation: "Conjugation negates the coefficient of i.",
        },
        {
          stepNumber: 3,
          description: "Now build the right-hand side: conjugate each separately.",
          workingLatex: "\\bar z+\\bar w=(a-bi)+(c-di)",
          explanation: "z̄=a-bi and w̄=c-di.",
        },
        {
          stepNumber: 4,
          description: "Add those conjugates.",
          workingLatex: "\\bar z+\\bar w=(a+c)-(b+d)i",
          explanation: "Group real and imaginary parts.",
        },
        {
          stepNumber: 5,
          description: "The two sides are identical.",
          workingLatex: "\\overline{z+w}=\\bar z+\\bar w",
          explanation: "Since both expressions equal (a+c)-(b+d)i, the identity holds for all complex z, w.",
        },
      ],
      finalAnswer: "\\( \\overline{z+w}=\\bar z+\\bar w \\) (shown)",
    },
  },
  {
    id: "cx1-054",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Prove that for any complex number \\( z=a+bi \\), the product \\( z\\bar z \\) is real and equals \\( a^{2}+b^{2} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write out the product z·z̄.",
          workingLatex: "z\\bar z=(a+bi)(a-bi)",
          explanation: "The conjugate of a+bi is a-bi.",
        },
        {
          stepNumber: 2,
          description: "Recognise a difference of two squares.",
          workingLatex: "=a^{2}-(bi)^{2}",
          explanation: "(a+b)(a-b)=a²-b² with the second term bi.",
        },
        {
          stepNumber: 3,
          description: "Expand (bi)² and use i²=−1.",
          workingLatex: "=a^{2}-b^{2}i^{2}=a^{2}+b^{2}",
          explanation: "Since i²=-1, the term -b²i² becomes +b².",
        },
        {
          stepNumber: 4,
          description: "Conclude the result is real.",
          workingLatex: "z\\bar z=a^{2}+b^{2}\\in\\mathbb{R}",
          explanation: "a²+b² has no imaginary part, so z·z̄ is real (and non-negative). It equals |z|².",
        },
      ],
      finalAnswer: "\\( z\\bar z=a^{2}+b^{2} \\) (shown)",
    },
  },
  {
    id: "cx1-055",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all complex numbers \\( z=x+yi \\) (with \\( x,y \\) real) satisfying \\( z^{2}=3+4i \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "square roots", "simultaneous equations"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand z² and set equal to 3+4i.",
          workingLatex: "(x^{2}-y^{2})+2xyi=3+4i",
          explanation: "z²=(x+yi)²=x²-y²+2xyi.",
        },
        {
          stepNumber: 2,
          description: "Equate real and imaginary parts.",
          workingLatex: "x^{2}-y^{2}=3,\\quad 2xy=4",
          explanation: "This gives two real equations in x and y.",
        },
        {
          stepNumber: 3,
          description: "Use the second equation to substitute y=2/x.",
          workingLatex: "x^{2}-\\frac{4}{x^{2}}=3",
          explanation: "From 2xy=4 we get y=2/x; substitute into the first equation.",
        },
        {
          stepNumber: 4,
          description: "Clear the fraction to form a quadratic in x².",
          workingLatex: "x^{4}-3x^{2}-4=0",
          explanation: "Multiply through by x² and rearrange.",
        },
        {
          stepNumber: 5,
          description: "Factor and keep the real root.",
          workingLatex: "(x^{2}-4)(x^{2}+1)=0\\Rightarrow x^{2}=4",
          explanation: "x is real, so x²=-1 is rejected; hence x=±2.",
        },
        {
          stepNumber: 6,
          description: "Recover y from y=2/x for each x.",
          workingLatex: "x=2,y=1\\ \\text{or}\\ x=-2,y=-1",
          explanation: "The two roots are negatives of each other, as square roots always are.",
        },
      ],
      finalAnswer: "\\( z=2+i \\) or \\( z=-2-i \\)",
      canonicalAnswer: "{2+i, -2-i}",
    },
  },
  {
    id: "cx1-056",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find the two square roots of \\( -15+8i \\) in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "square roots", "simultaneous equations"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set (x+yi)²=−15+8i and equate parts.",
          workingLatex: "x^{2}-y^{2}=-15,\\quad 2xy=8",
          explanation: "Real part of the square is x²-y², imaginary part is 2xy.",
        },
        {
          stepNumber: 2,
          description: "Substitute y=4/x from 2xy=8.",
          workingLatex: "x^{2}-\\frac{16}{x^{2}}=-15",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Form a quadratic in x².",
          workingLatex: "x^{4}+15x^{2}-16=0",
          explanation: "Multiply by x² and rearrange.",
        },
        {
          stepNumber: 4,
          description: "Factor and keep the real root.",
          workingLatex: "(x^{2}+16)(x^{2}-1)=0\\Rightarrow x^{2}=1",
          explanation: "Reject x²=-16; so x=±1.",
        },
        {
          stepNumber: 5,
          description: "Recover y=4/x.",
          workingLatex: "x=1,y=4\\ \\text{or}\\ x=-1,y=-4",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\pm(1+4i) \\)",
      canonicalAnswer: "{1+4i, -1-4i}",
    },
  },
  {
    id: "cx1-057",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find the two square roots of \\( 5-12i \\) in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "square roots", "simultaneous equations"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set (x+yi)²=5−12i and equate parts.",
          workingLatex: "x^{2}-y^{2}=5,\\quad 2xy=-12",
          explanation: "Note the imaginary part is negative, so x and y have opposite signs.",
        },
        {
          stepNumber: 2,
          description: "Substitute y=−6/x.",
          workingLatex: "x^{2}-\\frac{36}{x^{2}}=5",
          explanation: "From 2xy=-12, y=-6/x.",
        },
        {
          stepNumber: 3,
          description: "Form a quadratic in x².",
          workingLatex: "x^{4}-5x^{2}-36=0",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Factor and keep the real root.",
          workingLatex: "(x^{2}-9)(x^{2}+4)=0\\Rightarrow x^{2}=9",
          explanation: "Reject x²=-4; so x=±3.",
        },
        {
          stepNumber: 5,
          description: "Recover y=−6/x.",
          workingLatex: "x=3,y=-2\\ \\text{or}\\ x=-3,y=2",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\pm(3-2i) \\)",
      canonicalAnswer: "{3-2i, -3+2i}",
    },
  },
  {
    id: "cx1-058",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that if \\( z+\\dfrac{1}{z} \\) is real (with \\( z\\neq0 \\)), then either \\( z \\) is real or \\( |z|=1 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "modulus", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rewrite 1/z using the conjugate.",
          workingLatex: "\\frac{1}{z}=\\frac{\\bar z}{z\\bar z}=\\frac{\\bar z}{|z|^{2}}",
          explanation: "Multiplying top and bottom by z̄ makes the denominator the real number |z|².",
        },
        {
          stepNumber: 2,
          description: "Write the whole expression.",
          workingLatex: "z+\\frac{1}{z}=z+\\frac{\\bar z}{|z|^{2}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Take imaginary parts, using Im(z̄)=−Im(z).",
          workingLatex: "\\operatorname{Im}\\!\\left(z+\\frac1z\\right)=\\operatorname{Im}(z)-\\frac{\\operatorname{Im}(z)}{|z|^{2}}",
          explanation: "Im(z) and Im(z̄) are opposite in sign.",
        },
        {
          stepNumber: 4,
          description: "Factor the imaginary part.",
          workingLatex: "=\\operatorname{Im}(z)\\left(1-\\frac{1}{|z|^{2}}\\right)",
          explanation: "",
        },
        {
          stepNumber: 5,
          description: "The expression is real iff this imaginary part is zero.",
          workingLatex: "\\operatorname{Im}(z)\\left(1-\\frac{1}{|z|^{2}}\\right)=0",
          explanation: "A product is zero exactly when one factor is zero.",
        },
        {
          stepNumber: 6,
          description: "Conclude.",
          workingLatex: "\\operatorname{Im}(z)=0\\ \\text{or}\\ |z|^{2}=1",
          explanation: "Either z is real, or |z|=1, as required.",
        },
      ],
      finalAnswer: "\\( z\\in\\mathbb{R} \\) or \\( |z|=1 \\) (shown)",
    },
  },
  {
    id: "cx1-059",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all complex numbers \\( z \\) satisfying \\( \\bar z=z^{2} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "simultaneous equations"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write z=a+bi and expand both sides.",
          workingLatex: "a-bi=(a^{2}-b^{2})+2abi",
          explanation: "Left side is z̄; right side is z²=(a²-b²)+2abi.",
        },
        {
          stepNumber: 2,
          description: "Equate real and imaginary parts.",
          workingLatex: "a^{2}-b^{2}=a,\\quad 2ab=-b",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Factor the imaginary equation.",
          workingLatex: "b(2a+1)=0\\Rightarrow b=0\\ \\text{or}\\ a=-\\frac12",
          explanation: "Move all terms to one side: 2ab+b=0.",
        },
        {
          stepNumber: 4,
          description: "Case b=0: solve a²=a.",
          workingLatex: "a^{2}=a\\Rightarrow a=0\\ \\text{or}\\ a=1",
          explanation: "Gives the real solutions z=0 and z=1.",
        },
        {
          stepNumber: 5,
          description: "Case a=−1/2: solve for b.",
          workingLatex: "\\frac14-b^{2}=-\\frac12\\Rightarrow b^{2}=\\frac34",
          explanation: "Substitute a=-1/2 into a²-b²=a; b=±√3/2.",
        },
        {
          stepNumber: 6,
          description: "Collect all four solutions.",
          workingLatex: "z=0,\\ 1,\\ -\\frac12\\pm\\frac{\\sqrt3}{2}i",
          explanation: "The non-real solutions are the primitive cube roots of unity.",
        },
      ],
      finalAnswer: "\\( z=0,\\ 1,\\ -\\frac12\\pm\\frac{\\sqrt3}{2}i \\)",
      canonicalAnswer: "{0, 1, -1/2+(sqrt(3)/2)i, -1/2-(sqrt(3)/2)i}",
    },
  },
  {
    id: "cx1-060",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Given that the real quadratic \\( z^{2}+pz+q=0 \\) has \\( 1+i \\) as a root, find the real numbers \\( p \\) and \\( q \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate root", "quadratics"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the conjugate-root property.",
          workingLatex: "\\text{roots: } 1+i\\ \\text{and}\\ 1-i",
          explanation: "A polynomial with real coefficients has complex roots in conjugate pairs, so 1-i must also be a root.",
        },
        {
          stepNumber: 2,
          description: "Sum of roots equals −p.",
          workingLatex: "(1+i)+(1-i)=2=-p\\Rightarrow p=-2",
          explanation: "For z²+pz+q, the sum of roots is -p.",
        },
        {
          stepNumber: 3,
          description: "Product of roots equals q.",
          workingLatex: "(1+i)(1-i)=1^{2}+1^{2}=2=q",
          explanation: "The product of conjugates is a²+b².",
        },
      ],
      finalAnswer: "\\( p=-2,\\ q=2 \\)",
      canonicalAnswer: "{-2, 2}",
    },
  },
  {
    id: "cx1-061",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Evaluate \\( (1+i)^{10} \\), giving your answer in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute the square of the base.",
          workingLatex: "(1+i)^{2}=2i",
          explanation: "This is the key simplification: a high power of 1+i is easiest via its square.",
        },
        {
          stepNumber: 2,
          description: "Rewrite the tenth power.",
          workingLatex: "(1+i)^{10}=\\left((1+i)^{2}\\right)^{5}=(2i)^{5}",
          explanation: "Ten is 2×5, so the square is raised to the fifth power.",
        },
        {
          stepNumber: 3,
          description: "Separate the constant and the power of i.",
          workingLatex: "(2i)^{5}=2^{5}\\,i^{5}=32\\,i^{5}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Reduce i⁵.",
          workingLatex: "i^{5}=i\\Rightarrow 32i",
          explanation: "5≡1 mod 4, so i⁵=i.",
        },
      ],
      finalAnswer: "\\( 32i \\)",
      canonicalAnswer: "32i",
    },
  },
  {
    id: "cx1-062",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Prove that for all complex \\( z \\), both \\( z+\\bar z \\) and \\( z\\bar z \\) are real.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write z and its conjugate.",
          workingLatex: "z=a+bi,\\quad \\bar z=a-bi",
          explanation: "Let a,b be real.",
        },
        {
          stepNumber: 2,
          description: "Add them.",
          workingLatex: "z+\\bar z=2a",
          explanation: "The imaginary parts +bi and -bi cancel, leaving twice the real part.",
        },
        {
          stepNumber: 3,
          description: "Multiply them.",
          workingLatex: "z\\bar z=(a+bi)(a-bi)=a^{2}+b^{2}",
          explanation: "Difference of squares with i²=-1.",
        },
        {
          stepNumber: 4,
          description: "Conclude both are real.",
          workingLatex: "2a,\\ a^{2}+b^{2}\\in\\mathbb{R}",
          explanation: "Both 2a and a²+b² are built only from the real numbers a,b, so neither has an imaginary part.",
        },
      ],
      finalAnswer: "\\( z+\\bar z=2a,\\ z\\bar z=a^{2}+b^{2}\\in\\mathbb{R} \\) (shown)",
    },
  },
  {
    id: "cx1-063",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Given \\( |z|=1 \\), simplify \\( \\dfrac{1+z}{1+\\bar z} \\) as far as possible.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate", "modulus"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use |z|=1 to replace z̄.",
          workingLatex: "|z|=1\\Rightarrow z\\bar z=1\\Rightarrow \\bar z=\\frac{1}{z}",
          explanation: "On the unit circle the conjugate equals the reciprocal — the key idea here.",
        },
        {
          stepNumber: 2,
          description: "Substitute into the denominator.",
          workingLatex: "1+\\bar z=1+\\frac{1}{z}=\\frac{z+1}{z}",
          explanation: "Combine over a common denominator z.",
        },
        {
          stepNumber: 3,
          description: "Form the full quotient.",
          workingLatex: "\\frac{1+z}{(z+1)/z}=\\frac{(1+z)\\,z}{z+1}",
          explanation: "Dividing by a fraction multiplies by its reciprocal.",
        },
        {
          stepNumber: 4,
          description: "Cancel the common factor (1+z).",
          workingLatex: "=z",
          explanation: "Provided z≠-1, the factor 1+z cancels, leaving simply z.",
        },
      ],
      finalAnswer: "\\( z \\)",
      canonicalAnswer: "z",
    },
  },
  {
    id: "cx1-064",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Evaluate the sum \\( 1+i+i^{2}+\\cdots+i^{2026} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers of i", "series"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Note any four consecutive powers of i sum to zero.",
          workingLatex: "i^{k}+i^{k+1}+i^{k+2}+i^{k+3}=0",
          explanation: "Because 1+i+i²+i³ = 1+i-1-i = 0, every full block of four cancels.",
        },
        {
          stepNumber: 2,
          description: "Count the terms.",
          workingLatex: "k=0,1,\\dots,2026\\ \\Rightarrow\\ 2027\\ \\text{terms}",
          explanation: "The sum runs from i⁰ to i²⁰²⁶ inclusive.",
        },
        {
          stepNumber: 3,
          description: "Divide into blocks of four.",
          workingLatex: "2027=4\\cdot506+3",
          explanation: "506 complete blocks contribute 0; three terms remain.",
        },
        {
          stepNumber: 4,
          description: "Evaluate the leftover three terms.",
          workingLatex: "i^{2024}+i^{2025}+i^{2026}=i^{0}+i^{1}+i^{2}=1+i-1=i",
          explanation: "2024≡0, 2025≡1, 2026≡2 modulo 4.",
        },
      ],
      finalAnswer: "\\( i \\)",
      canonicalAnswer: "i",
    },
  },
  {
    id: "cx1-065",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Solve \\( z^{2}+2z+5=0 \\), giving both roots in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "quadratics", "complex roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the quadratic formula.",
          workingLatex: "z=\\frac{-2\\pm\\sqrt{2^{2}-4\\cdot1\\cdot5}}{2}",
          explanation: "With a=1, b=2, c=5.",
        },
        {
          stepNumber: 2,
          description: "Evaluate the discriminant.",
          workingLatex: "z=\\frac{-2\\pm\\sqrt{-16}}{2}",
          explanation: "4-20=-16; a negative discriminant signals complex roots.",
        },
        {
          stepNumber: 3,
          description: "Write the root of the negative number using i.",
          workingLatex: "\\sqrt{-16}=4i",
          explanation: "√(-16) = √16·√(-1) = 4i.",
        },
        {
          stepNumber: 4,
          description: "Simplify.",
          workingLatex: "z=\\frac{-2\\pm4i}{2}=-1\\pm2i",
          explanation: "The roots are a conjugate pair, as expected for a real quadratic.",
        },
      ],
      finalAnswer: "\\( z=-1\\pm2i \\)",
      canonicalAnswer: "{-1+2i, -1-2i}",
    },
  },
  {
    id: "cx1-066",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "One root of \\( z^{2}-(3+i)z+(2+2i)=0 \\) is a real integer. Find both roots.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "quadratics", "complex coefficients"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Because the coefficients are complex, the conjugate-root rule does NOT apply; test integers instead.",
          workingLatex: "\\text{try } z=2",
          explanation: "With complex coefficients the roots need not come in conjugate pairs, so we use the hint that one root is a real integer.",
        },
        {
          stepNumber: 2,
          description: "Substitute z=2.",
          workingLatex: "4-(3+i)(2)+(2+2i)=4-6-2i+2+2i=0",
          explanation: "It satisfies the equation, so z=2 is a root.",
        },
        {
          stepNumber: 3,
          description: "Use product of roots = constant term.",
          workingLatex: "2\\cdot z_{2}=2+2i",
          explanation: "For z²-(sum)z+(product), the product of the roots is the constant term 2+2i.",
        },
        {
          stepNumber: 4,
          description: "Solve for the second root.",
          workingLatex: "z_{2}=\\frac{2+2i}{2}=1+i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( z=2 \\) and \\( z=1+i \\)",
      canonicalAnswer: "{2, 1+i}",
    },
  },
  {
    id: "cx1-067",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Prove that for real \\( a,b \\) not both zero, \\( \\left|\\dfrac{a+bi}{a-bi}\\right|=1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "modulus", "conjugate", "proof"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the quotient rule for modulus.",
          workingLatex: "\\left|\\frac{a+bi}{a-bi}\\right|=\\frac{|a+bi|}{|a-bi|}",
          explanation: "The modulus of a quotient equals the quotient of the moduli.",
        },
        {
          stepNumber: 2,
          description: "Compute each modulus.",
          workingLatex: "|a+bi|=\\sqrt{a^{2}+b^{2}},\\quad |a-bi|=\\sqrt{a^{2}+(-b)^{2}}=\\sqrt{a^{2}+b^{2}}",
          explanation: "A number and its conjugate have the same modulus because squaring removes the sign of b.",
        },
        {
          stepNumber: 3,
          description: "Form the ratio.",
          workingLatex: "\\frac{\\sqrt{a^{2}+b^{2}}}{\\sqrt{a^{2}+b^{2}}}=1",
          explanation: "The denominator is non-zero since a,b are not both zero.",
        },
      ],
      finalAnswer: "\\( \\left|\\frac{a+bi}{a-bi}\\right|=1 \\) (shown)",
    },
  },
  {
    id: "cx1-068",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "numeric",
    questionText: "Find the smallest positive integer \\( n \\) for which \\( (1+i)^{n} \\) is a real number.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Compute the first three powers.",
          workingLatex: "(1+i)^{1}=1+i,\\ (1+i)^{2}=2i,\\ (1+i)^{3}=2i(1+i)=-2+2i",
          explanation: "None of n=1,2,3 gives a real result (each has a non-zero imaginary part).",
        },
        {
          stepNumber: 2,
          description: "Compute the fourth power.",
          workingLatex: "(1+i)^{4}=\\left((1+i)^{2}\\right)^{2}=(2i)^{2}=-4",
          explanation: "This is real.",
        },
        {
          stepNumber: 3,
          description: "Identify the least such n.",
          workingLatex: "n=4",
          explanation: "Since n=1,2,3 fail and n=4 works, 4 is the smallest. (In polar form 1+i has argument π/4, and nπ/4 is a multiple of π first at n=4.)",
        },
      ],
      finalAnswer: "\\( n=4 \\)",
      canonicalAnswer: "4",
    },
  },
  {
    id: "cx1-069",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Solve \\( z+\\dfrac{1}{z}=1 \\) for \\( z \\), giving answers in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "quadratics", "complex roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply through by z to clear the fraction.",
          workingLatex: "z^{2}+1=z",
          explanation: "Valid since z≠0 (z=0 cannot satisfy the original equation).",
        },
        {
          stepNumber: 2,
          description: "Rearrange into a standard quadratic.",
          workingLatex: "z^{2}-z+1=0",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Apply the quadratic formula.",
          workingLatex: "z=\\frac{1\\pm\\sqrt{1-4}}{2}=\\frac{1\\pm\\sqrt{-3}}{2}",
          explanation: "Discriminant 1-4=-3 is negative, so the roots are complex.",
        },
        {
          stepNumber: 4,
          description: "Write the surd in terms of i.",
          workingLatex: "z=\\frac12\\pm\\frac{\\sqrt3}{2}i",
          explanation: "√(-3) = √3·i.",
        },
      ],
      finalAnswer: "\\( z=\\frac12\\pm\\frac{\\sqrt3}{2}i \\)",
      canonicalAnswer: "{1/2+(sqrt(3)/2)i, 1/2-(sqrt(3)/2)i}",
    },
  },
  {
    id: "cx1-070",
    topicRef: "cx1",
    topicTitle: "Cartesian Arithmetic & Conjugates",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find real numbers \\( x,y \\) such that \\( \\dfrac{x}{1+i}+\\dfrac{y}{1-i}=3-i \\), and state \\( x \\) and \\( y \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division", "simultaneous equations"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Rationalise each fraction.",
          workingLatex: "\\frac{x(1-i)}{2}+\\frac{y(1+i)}{2}",
          explanation: "Multiply each term by the conjugate of its denominator; both denominators become 2.",
        },
        {
          stepNumber: 2,
          description: "Combine into one complex number.",
          workingLatex: "\\frac{(x+y)+(y-x)i}{2}",
          explanation: "Group the real parts x+y and the imaginary parts (y-x)i.",
        },
        {
          stepNumber: 3,
          description: "Equate to 3−i and compare parts.",
          workingLatex: "\\frac{x+y}{2}=3,\\quad \\frac{y-x}{2}=-1",
          explanation: "Real with real, imaginary with imaginary.",
        },
        {
          stepNumber: 4,
          description: "Solve x+y=6 and y−x=−2.",
          workingLatex: "x=4,\\quad y=2",
          explanation: "Adding gives 2y=4 so y=2, then x=4.",
        },
      ],
      finalAnswer: "\\( x=4,\\ y=2 \\)",
      canonicalAnswer: "x=4, y=2",
    },
  },
];
