import { Question } from "@/lib/types";

/**
 * Topic: Complex Numbers
 * Ref:   em01  (Undergraduate Engineering Mathematics)
 *
 * 20 questions — 6 Foundation, 9 Standard, 5 Challenge.
 * Arithmetic, conjugates, modulus/argument, polar & exponential form,
 * quadratics with complex roots, De Moivre's theorem and nth roots.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (6) ─────────────────────────
  {
    id: "em01-001",
    topicRef: "em01",
    topicTitle: "Complex Numbers 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find the sum \\( (3+2i)+(1+4i) \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "addition"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Add real parts and imaginary parts separately.",
          workingLatex: "(3+1)+(2+4)i",
          explanation: "Real with real, imaginary with imaginary.",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "4+6i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 4+6i \\)",
      canonicalAnswer: "4+6i",
    },
  },
  {
    id: "em01-002",
    topicRef: "em01",
    topicTitle: "Complex Numbers 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( (5+3i)-(2+7i) \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "subtraction"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Subtract real parts and imaginary parts separately.",
          workingLatex: "(5-2)+(3-7)i",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "3-4i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 3-4i \\)",
      canonicalAnswer: "3-4i",
    },
  },
  {
    id: "em01-003",
    topicRef: "em01",
    topicTitle: "Complex Numbers 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Expand and simplify \\( (2+i)(3-2i) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the brackets.",
          workingLatex: "6-4i+3i-2i^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( i^{2}=-1 \\).",
          workingLatex: "6-4i+3i+2",
          explanation: "The \\( -2i^{2} \\) term becomes \\( +2 \\).",
        },
        {
          stepNumber: 3,
          description: "Collect terms.",
          workingLatex: "8-i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 8-i \\)",
      canonicalAnswer: "8-i",
    },
  },
  {
    id: "em01-004",
    topicRef: "em01",
    topicTitle: "Complex Numbers 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write down the complex conjugate of \\( 4-7i \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "conjugate"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Reverse the sign of the imaginary part.",
          workingLatex: "\\overline{4-7i}=4+7i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 4+7i \\)",
      canonicalAnswer: "4+7i",
    },
  },
  {
    id: "em01-005",
    topicRef: "em01",
    topicTitle: "Complex Numbers 05",
    difficulty: "Foundation",
    answerType: "numeric",
    questionText: "Find the modulus of \\( 3+4i \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "modulus"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply \\( |a+bi|=\\sqrt{a^{2}+b^{2}} \\).",
          workingLatex: "\\sqrt{3^{2}+4^{2}}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Evaluate.",
          workingLatex: "\\sqrt{9+16}=\\sqrt{25}=5",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 5 \\)",
      canonicalAnswer: "5",
    },
  },
  {
    id: "em01-006",
    topicRef: "em01",
    topicTitle: "Complex Numbers 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Simplify \\( i^{3} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "powers of i"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write as \\( i^{2}\\cdot i \\).",
          workingLatex: "i^{3}=i^{2}\\cdot i",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( i^{2}=-1 \\).",
          workingLatex: "(-1)\\cdot i=-i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -i \\)",
      canonicalAnswer: "-i",
    },
  },

  // ───────────────────────── Standard (9) ─────────────────────────
  {
    id: "em01-007",
    topicRef: "em01",
    topicTitle: "Complex Numbers 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( \\dfrac{3+2i}{1-i} \\) in the form \\( a+bi \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "division"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Multiply top and bottom by the conjugate of the denominator.",
          workingLatex: "\\frac{3+2i}{1-i}\\cdot\\frac{1+i}{1+i}",
          explanation: "The conjugate of \\( 1-i \\) is \\( 1+i \\).",
        },
        {
          stepNumber: 2,
          description: "Expand the numerator.",
          workingLatex: "(3+2i)(1+i)=3+3i+2i+2i^{2}=1+5i",
          explanation: "Using \\( i^{2}=-1 \\).",
        },
        {
          stepNumber: 3,
          description: "Expand the denominator.",
          workingLatex: "(1-i)(1+i)=1-i^{2}=2",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Divide.",
          workingLatex: "\\frac{1+5i}{2}=\\frac{1}{2}+\\frac{5}{2}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\tfrac{1}{2}+\\tfrac{5}{2}i \\)",
      canonicalAnswer: "1/2 + (5/2)*i",
    },
  },
  {
    id: "em01-008",
    topicRef: "em01",
    topicTitle: "Complex Numbers 08",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Solve the equation \\( z^{2}=-9 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "roots"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take square roots, writing \\( -1=i^{2} \\).",
          workingLatex: "z=\\pm\\sqrt{-9}=\\pm\\sqrt{9}\\,\\sqrt{-1}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "z=\\pm 3i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( z=\\pm 3i \\)",
      canonicalAnswer: "{3i, -3i}",
    },
  },
  {
    id: "em01-009",
    topicRef: "em01",
    topicTitle: "Complex Numbers 09",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Find the argument of \\( 1+i\\sqrt{3} \\), giving your answer in radians.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "argument"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The point lies in the first quadrant, so the argument is \\( \\arctan(b/a) \\).",
          workingLatex: "\\arg z=\\arctan\\!\\left(\\frac{\\sqrt{3}}{1}\\right)",
          explanation: "Here \\( a=1>0 \\) and \\( b=\\sqrt{3}>0 \\).",
        },
        {
          stepNumber: 2,
          description: "Evaluate.",
          workingLatex: "\\arctan(\\sqrt{3})=\\frac{\\pi}{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\tfrac{\\pi}{3} \\)",
      canonicalAnswer: "pi/3",
    },
  },
  {
    id: "em01-010",
    topicRef: "em01",
    topicTitle: "Complex Numbers 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Expand and simplify \\( (1+i)^{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "powers"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the square.",
          workingLatex: "(1+i)^{2}=1+2i+i^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( i^{2}=-1 \\).",
          workingLatex: "1+2i-1=2i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2i \\)",
      canonicalAnswer: "2i",
    },
  },
  {
    id: "em01-011",
    topicRef: "em01",
    topicTitle: "Complex Numbers 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( -1+i \\) in modulus–argument form.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "polar form"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find the modulus.",
          workingLatex: "r=\\sqrt{(-1)^{2}+1^{2}}=\\sqrt{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Locate the quadrant.",
          workingLatex: "a=-1<0,\\ b=1>0\\ \\Rightarrow\\ \\text{2nd quadrant}",
          explanation: "The argument is between \\( \\tfrac{\\pi}{2} \\) and \\( \\pi \\).",
        },
        {
          stepNumber: 3,
          description: "Compute the argument.",
          workingLatex: "\\theta=\\pi-\\arctan\\!\\left(\\tfrac{1}{1}\\right)=\\pi-\\tfrac{\\pi}{4}=\\tfrac{3\\pi}{4}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Write in modulus–argument form.",
          workingLatex: "\\sqrt{2}\\left(\\cos\\tfrac{3\\pi}{4}+i\\sin\\tfrac{3\\pi}{4}\\right)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{2}\\left(\\cos\\tfrac{3\\pi}{4}+i\\sin\\tfrac{3\\pi}{4}\\right) \\)",
      canonicalAnswer: "sqrt(2)*(cos(3*pi/4)+i*sin(3*pi/4))",
    },
  },
  {
    id: "em01-012",
    topicRef: "em01",
    topicTitle: "Complex Numbers 12",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Solve \\( z^{2}-4z+13=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "quadratic"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the quadratic formula.",
          workingLatex: "z=\\frac{4\\pm\\sqrt{(-4)^{2}-4\\cdot 13}}{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Evaluate the discriminant.",
          workingLatex: "z=\\frac{4\\pm\\sqrt{-36}}{2}",
          explanation: "Negative discriminant \\( \\Rightarrow \\) complex roots.",
        },
        {
          stepNumber: 3,
          description: "Simplify the surd.",
          workingLatex: "z=\\frac{4\\pm 6i}{2}=2\\pm 3i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( z=2\\pm 3i \\)",
      canonicalAnswer: "{2+3i, 2-3i}",
    },
  },
  {
    id: "em01-013",
    topicRef: "em01",
    topicTitle: "Complex Numbers 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Use De Moivre's theorem to evaluate \\( (1+i)^{8} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "de moivre"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write \\( 1+i \\) in polar form.",
          workingLatex: "1+i=\\sqrt{2}\\left(\\cos\\tfrac{\\pi}{4}+i\\sin\\tfrac{\\pi}{4}\\right)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply De Moivre's theorem.",
          workingLatex: "(1+i)^{8}=(\\sqrt{2})^{8}\\left(\\cos\\tfrac{8\\pi}{4}+i\\sin\\tfrac{8\\pi}{4}\\right)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Simplify.",
          workingLatex: "16\\left(\\cos 2\\pi+i\\sin 2\\pi\\right)=16(1+0)=16",
          explanation: "\\( (\\sqrt{2})^{8}=2^{4}=16 \\).",
        },
      ],
      finalAnswer: "\\( 16 \\)",
      canonicalAnswer: "16",
    },
  },
  {
    id: "em01-014",
    topicRef: "em01",
    topicTitle: "Complex Numbers 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( 2e^{i\\pi/2} \\) in the form \\( a+bi \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "exponential form"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use Euler's formula \\( e^{i\\theta}=\\cos\\theta+i\\sin\\theta \\).",
          workingLatex: "2e^{i\\pi/2}=2\\left(\\cos\\tfrac{\\pi}{2}+i\\sin\\tfrac{\\pi}{2}\\right)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Evaluate the trig values.",
          workingLatex: "2(0+i\\cdot 1)=2i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2i \\)",
      canonicalAnswer: "2i",
    },
  },
  {
    id: "em01-015",
    topicRef: "em01",
    topicTitle: "Complex Numbers 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given \\( z_{1}=2+3i \\) and \\( z_{2}=1-i \\), find \\( z_{1}z_{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex numbers", "multiplication"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Expand the product.",
          workingLatex: "(2+3i)(1-i)=2-2i+3i-3i^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( i^{2}=-1 \\) and collect terms.",
          workingLatex: "2+i+3=5+i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 5+i \\)",
      canonicalAnswer: "5+i",
    },
  },

  // ───────────────────────── Challenge (5) ─────────────────────────
  {
    id: "em01-016",
    topicRef: "em01",
    topicTitle: "Complex Numbers 16",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all three cube roots of \\( 8 \\), giving each in the form \\( a+bi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "nth roots", "de moivre"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write \\( 8 \\) in polar form, including all coterminal angles.",
          workingLatex: "8=8\\left(\\cos(2k\\pi)+i\\sin(2k\\pi)\\right),\\ k\\in\\mathbb{Z}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Take the cube root using De Moivre's theorem.",
          workingLatex: "z=8^{1/3}\\left(\\cos\\tfrac{2k\\pi}{3}+i\\sin\\tfrac{2k\\pi}{3}\\right)=2\\left(\\cos\\tfrac{2k\\pi}{3}+i\\sin\\tfrac{2k\\pi}{3}\\right)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Evaluate for \\( k=0,1,2 \\).",
          workingLatex: "k=0:\\ 2;\\quad k=1:\\ 2\\!\\left(-\\tfrac{1}{2}+\\tfrac{\\sqrt{3}}{2}i\\right);\\quad k=2:\\ 2\\!\\left(-\\tfrac{1}{2}-\\tfrac{\\sqrt{3}}{2}i\\right)",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Simplify.",
          workingLatex: "2,\\ -1+i\\sqrt{3},\\ -1-i\\sqrt{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 2,\\ -1+i\\sqrt{3},\\ -1-i\\sqrt{3} \\)",
      canonicalAnswer: "{2, -1+sqrt(3)*i, -1-sqrt(3)*i}",
    },
  },
  {
    id: "em01-017",
    topicRef: "em01",
    topicTitle: "Complex Numbers 17",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use De Moivre's theorem to evaluate \\( (1-i\\sqrt{3})^{6} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "de moivre"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Find the modulus.",
          workingLatex: "r=\\sqrt{1^{2}+(\\sqrt{3})^{2}}=\\sqrt{4}=2",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Find the argument (4th quadrant).",
          workingLatex: "\\theta=-\\arctan\\!\\left(\\tfrac{\\sqrt{3}}{1}\\right)=-\\tfrac{\\pi}{3}",
          explanation: "Here \\( a=1>0 \\), \\( b=-\\sqrt{3}<0 \\).",
        },
        {
          stepNumber: 3,
          description: "Apply De Moivre's theorem.",
          workingLatex: "(1-i\\sqrt{3})^{6}=2^{6}\\left(\\cos\\!\\left(-2\\pi\\right)+i\\sin\\!\\left(-2\\pi\\right)\\right)",
          explanation: "\\( 6\\times(-\\tfrac{\\pi}{3})=-2\\pi \\).",
        },
        {
          stepNumber: 4,
          description: "Simplify.",
          workingLatex: "64(1+0)=64",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 64 \\)",
      canonicalAnswer: "64",
    },
  },
  {
    id: "em01-018",
    topicRef: "em01",
    topicTitle: "Complex Numbers 18",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Solve \\( z^{4}=-16 \\), giving the four roots in the form \\( a+bi \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "nth roots", "de moivre"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write \\( -16 \\) in polar form with all coterminal angles.",
          workingLatex: "-16=16\\left(\\cos(\\pi+2k\\pi)+i\\sin(\\pi+2k\\pi)\\right)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Take the fourth root.",
          workingLatex: "z=16^{1/4}\\left(\\cos\\tfrac{\\pi+2k\\pi}{4}+i\\sin\\tfrac{\\pi+2k\\pi}{4}\\right)=2\\left(\\cos\\theta_{k}+i\\sin\\theta_{k}\\right)",
          explanation: "\\( \\theta_k=\\tfrac{\\pi}{4},\\tfrac{3\\pi}{4},\\tfrac{5\\pi}{4},\\tfrac{7\\pi}{4} \\) for \\( k=0,1,2,3 \\).",
        },
        {
          stepNumber: 3,
          description: "Evaluate each root.",
          workingLatex: "2\\!\\left(\\tfrac{\\sqrt2}{2}\\pm\\tfrac{\\sqrt2}{2}i\\right)=\\sqrt{2}\\pm\\sqrt{2}i,\\quad -\\sqrt{2}\\pm\\sqrt{2}i",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sqrt{2}+\\sqrt{2}i,\\ -\\sqrt{2}+\\sqrt{2}i,\\ -\\sqrt{2}-\\sqrt{2}i,\\ \\sqrt{2}-\\sqrt{2}i \\)",
      canonicalAnswer: "{sqrt(2)+sqrt(2)*i, -sqrt(2)+sqrt(2)*i, -sqrt(2)-sqrt(2)*i, sqrt(2)-sqrt(2)*i}",
    },
  },
  {
    id: "em01-019",
    topicRef: "em01",
    topicTitle: "Complex Numbers 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use De Moivre's theorem to express \\( \\cos 3\\theta \\) in terms of \\( \\cos\\theta \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "de moivre", "trig identities"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply De Moivre's theorem to \\( n=3 \\).",
          workingLatex: "(\\cos\\theta+i\\sin\\theta)^{3}=\\cos 3\\theta+i\\sin 3\\theta",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Expand the left side with the binomial theorem.",
          workingLatex: "\\cos^{3}\\theta+3i\\cos^{2}\\theta\\sin\\theta-3\\cos\\theta\\sin^{2}\\theta-i\\sin^{3}\\theta",
          explanation: "Using \\( i^{2}=-1,\\ i^{3}=-i \\).",
        },
        {
          stepNumber: 3,
          description: "Equate real parts.",
          workingLatex: "\\cos 3\\theta=\\cos^{3}\\theta-3\\cos\\theta\\sin^{2}\\theta",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Replace \\( \\sin^{2}\\theta=1-\\cos^{2}\\theta \\).",
          workingLatex: "\\cos 3\\theta=\\cos^{3}\\theta-3\\cos\\theta(1-\\cos^{2}\\theta)=4\\cos^{3}\\theta-3\\cos\\theta",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\cos 3\\theta=4\\cos^{3}\\theta-3\\cos\\theta \\)",
      canonicalAnswer: "4*cos(x)^3 - 3*cos(x)",
    },
  },
  {
    id: "em01-020",
    topicRef: "em01",
    topicTitle: "Complex Numbers 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use De Moivre's theorem to evaluate \\( (1+i)^{10} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex numbers", "de moivre"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write \\( 1+i \\) in polar form.",
          workingLatex: "1+i=\\sqrt{2}\\left(\\cos\\tfrac{\\pi}{4}+i\\sin\\tfrac{\\pi}{4}\\right)",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply De Moivre's theorem.",
          workingLatex: "(1+i)^{10}=(\\sqrt{2})^{10}\\left(\\cos\\tfrac{10\\pi}{4}+i\\sin\\tfrac{10\\pi}{4}\\right)",
          explanation: "\\( (\\sqrt{2})^{10}=2^{5}=32 \\).",
        },
        {
          stepNumber: 3,
          description: "Reduce the angle and simplify.",
          workingLatex: "32\\left(\\cos\\tfrac{5\\pi}{2}+i\\sin\\tfrac{5\\pi}{2}\\right)=32\\left(\\cos\\tfrac{\\pi}{2}+i\\sin\\tfrac{\\pi}{2}\\right)=32i",
          explanation: "\\( \\tfrac{5\\pi}{2} \\) and \\( \\tfrac{\\pi}{2} \\) are coterminal.",
        },
      ],
      finalAnswer: "\\( 32i \\)",
      canonicalAnswer: "32i",
    },
  },
];
