import { Question } from "@/lib/types";

/**
 * Topic: Differentiation Techniques
 * Ref:   em04  (Undergraduate Engineering Mathematics)
 *
 * 20 questions — 6 Foundation, 9 Standard, 5 Challenge.
 * Power rule, standard derivatives (trig/exp/log), product, quotient and chain
 * rules, higher derivatives, implicit, parametric and logarithmic
 * differentiation, and stationary points.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (6) ─────────────────────────
  {
    id: "em04-001",
    topicRef: "em04",
    topicTitle: "Differentiation 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=x^{5} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "power rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply the power rule \\( \\frac{d}{dx}x^{n}=nx^{n-1} \\).",
          workingLatex: "\\frac{dy}{dx}=5x^{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 5x^{4} \\)",
      canonicalAnswer: "5*x^4",
    },
  },
  {
    id: "em04-002",
    topicRef: "em04",
    topicTitle: "Differentiation 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=3x^{2}-4x+7 \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "polynomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate term by term.",
          workingLatex: "\\frac{dy}{dx}=6x-4",
          explanation: "The constant differentiates to \\( 0 \\).",
        },
      ],
      finalAnswer: "\\( 6x-4 \\)",
      canonicalAnswer: "6*x-4",
    },
  },
  {
    id: "em04-003",
    topicRef: "em04",
    topicTitle: "Differentiation 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\sin x \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard derivative.",
          workingLatex: "\\frac{dy}{dx}=\\cos x",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\cos x \\)",
      canonicalAnswer: "cos(x)",
    },
  },
  {
    id: "em04-004",
    topicRef: "em04",
    topicTitle: "Differentiation 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=e^{x} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "The exponential is its own derivative.",
          workingLatex: "\\frac{dy}{dx}=e^{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x} \\)",
      canonicalAnswer: "e^x",
    },
  },
  {
    id: "em04-005",
    topicRef: "em04",
    topicTitle: "Differentiation 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\ln x \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard derivative.",
          workingLatex: "\\frac{dy}{dx}=\\frac{1}{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{x} \\)",
      canonicalAnswer: "1/x",
    },
  },
  {
    id: "em04-006",
    topicRef: "em04",
    topicTitle: "Differentiation 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\sqrt{x} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "power rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write as a power and apply the power rule.",
          workingLatex: "y=x^{1/2}\\ \\Rightarrow\\ \\frac{dy}{dx}=\\frac{1}{2}x^{-1/2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Rewrite.",
          workingLatex: "\\frac{1}{2\\sqrt{x}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{2\\sqrt{x}} \\)",
      canonicalAnswer: "1/(2*sqrt(x))",
    },
  },

  // ───────────────────────── Standard (9) ─────────────────────────
  {
    id: "em04-007",
    topicRef: "em04",
    topicTitle: "Differentiation 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=x^{2}e^{x} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "product rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Product rule with \\( u=x^{2} \\), \\( v=e^{x} \\).",
          workingLatex: "u'=2x,\\qquad v'=e^{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( (uv)'=u'v+uv' \\).",
          workingLatex: "\\frac{dy}{dx}=2xe^{x}+x^{2}e^{x}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Factorise.",
          workingLatex: "e^{x}(x^{2}+2x)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}(x^{2}+2x) \\)",
      canonicalAnswer: "e^x*(x^2+2*x)",
    },
  },
  {
    id: "em04-008",
    topicRef: "em04",
    topicTitle: "Differentiation 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\dfrac{x}{x+1} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "quotient rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Quotient rule with \\( u=x \\), \\( v=x+1 \\).",
          workingLatex: "u'=1,\\qquad v'=1",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( \\frac{u'v-uv'}{v^{2}} \\).",
          workingLatex: "\\frac{(x+1)(1)-x(1)}{(x+1)^{2}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Simplify the numerator.",
          workingLatex: "\\frac{1}{(x+1)^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{(x+1)^{2}} \\)",
      canonicalAnswer: "1/(x+1)^2",
    },
  },
  {
    id: "em04-009",
    topicRef: "em04",
    topicTitle: "Differentiation 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\sin 3x \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "chain rule", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Chain rule: derivative of the outside times derivative of the inside.",
          workingLatex: "\\frac{dy}{dx}=\\cos(3x)\\cdot 3",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Tidy.",
          workingLatex: "3\\cos 3x",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 3\\cos 3x \\)",
      canonicalAnswer: "3*cos(3*x)",
    },
  },
  {
    id: "em04-010",
    topicRef: "em04",
    topicTitle: "Differentiation 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=(2x+1)^{4} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "chain rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Chain rule.",
          workingLatex: "\\frac{dy}{dx}=4(2x+1)^{3}\\cdot 2",
          explanation: "Inside derivative is \\( 2 \\).",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "8(2x+1)^{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 8(2x+1)^{3} \\)",
      canonicalAnswer: "8*(2*x+1)^3",
    },
  },
  {
    id: "em04-011",
    topicRef: "em04",
    topicTitle: "Differentiation 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=e^{x^{2}} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "chain rule", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Chain rule: \\( \\frac{d}{dx}e^{f}=f'e^{f} \\).",
          workingLatex: "\\frac{dy}{dx}=2x\\,e^{x^{2}}",
          explanation: "Inside derivative is \\( 2x \\).",
        },
      ],
      finalAnswer: "\\( 2x\\,e^{x^{2}} \\)",
      canonicalAnswer: "2*x*e^(x^2)",
    },
  },
  {
    id: "em04-012",
    topicRef: "em04",
    topicTitle: "Differentiation 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\ln(2x+1) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "chain rule", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Chain rule: \\( \\frac{d}{dx}\\ln f=\\frac{f'}{f} \\).",
          workingLatex: "\\frac{dy}{dx}=\\frac{2}{2x+1}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{2}{2x+1} \\)",
      canonicalAnswer: "2/(2*x+1)",
    },
  },
  {
    id: "em04-013",
    topicRef: "em04",
    topicTitle: "Differentiation 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=x\\cos x \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "product rule", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Product rule with \\( u=x \\), \\( v=\\cos x \\).",
          workingLatex: "u'=1,\\qquad v'=-\\sin x",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( u'v+uv' \\).",
          workingLatex: "\\frac{dy}{dx}=\\cos x-x\\sin x",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\cos x-x\\sin x \\)",
      canonicalAnswer: "cos(x)-x*sin(x)",
    },
  },
  {
    id: "em04-014",
    topicRef: "em04",
    topicTitle: "Differentiation 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Differentiate \\( y=\\tan x \\) from \\( \\dfrac{\\sin x}{\\cos x} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "quotient rule", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Quotient rule on \\( \\frac{\\sin x}{\\cos x} \\).",
          workingLatex: "\\frac{\\cos x\\cos x-\\sin x(-\\sin x)}{\\cos^{2}x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( \\cos^{2}x+\\sin^{2}x=1 \\).",
          workingLatex: "\\frac{1}{\\cos^{2}x}=\\sec^{2}x",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sec^{2}x \\)",
      canonicalAnswer: "sec(x)^2",
    },
  },
  {
    id: "em04-015",
    topicRef: "em04",
    topicTitle: "Differentiation 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\dfrac{d^{2}y}{dx^{2}} \\) for \\( y=x^{3}-2x^{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differentiation", "second derivative"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "First derivative.",
          workingLatex: "\\frac{dy}{dx}=3x^{2}-4x",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Differentiate again.",
          workingLatex: "\\frac{d^{2}y}{dx^{2}}=6x-4",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 6x-4 \\)",
      canonicalAnswer: "6*x-4",
    },
  },

  // ───────────────────────── Challenge (5) ─────────────────────────
  {
    id: "em04-016",
    topicRef: "em04",
    topicTitle: "Differentiation 16",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Given \\( x^{2}+y^{2}=25 \\), find \\( \\dfrac{dy}{dx} \\) by implicit differentiation.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "implicit"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate both sides with respect to \\( x \\).",
          workingLatex: "2x+2y\\frac{dy}{dx}=0",
          explanation: "The \\( y^{2} \\) term uses the chain rule.",
        },
        {
          stepNumber: 2,
          description: "Make \\( \\frac{dy}{dx} \\) the subject.",
          workingLatex: "\\frac{dy}{dx}=-\\frac{x}{y}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\dfrac{x}{y} \\)",
      canonicalAnswer: "-x/y",
    },
  },
  {
    id: "em04-017",
    topicRef: "em04",
    topicTitle: "Differentiation 17",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Use logarithmic differentiation to differentiate \\( y=x^{x} \\) for \\( x>0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "logarithmic differentiation"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Take natural logs.",
          workingLatex: "\\ln y=x\\ln x",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Differentiate implicitly (product rule on the right).",
          workingLatex: "\\frac{1}{y}\\frac{dy}{dx}=\\ln x+x\\cdot\\frac{1}{x}=\\ln x+1",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Multiply through by \\( y=x^{x} \\).",
          workingLatex: "\\frac{dy}{dx}=x^{x}(\\ln x+1)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x^{x}(\\ln x+1) \\)",
      canonicalAnswer: "x^x*(ln(x)+1)",
    },
  },
  {
    id: "em04-018",
    topicRef: "em04",
    topicTitle: "Differentiation 18",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A curve is given parametrically by \\( x=t^{2} \\), \\( y=t^{3} \\). Find \\( \\dfrac{dy}{dx} \\) in terms of \\( t \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "parametric"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Differentiate each parameter.",
          workingLatex: "\\frac{dx}{dt}=2t,\\qquad \\frac{dy}{dt}=3t^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Use \\( \\frac{dy}{dx}=\\frac{dy/dt}{dx/dt} \\).",
          workingLatex: "\\frac{dy}{dx}=\\frac{3t^{2}}{2t}=\\frac{3t}{2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{3t}{2} \\)",
      canonicalAnswer: "3*t/2",
    },
  },
  {
    id: "em04-019",
    topicRef: "em04",
    topicTitle: "Differentiation 19",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find the \\( x \\)-coordinates of the stationary points of \\( y=x^{3}-3x \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "stationary points"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Set the first derivative to zero.",
          workingLatex: "\\frac{dy}{dx}=3x^{2}-3=0",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Solve.",
          workingLatex: "x^{2}=1\\ \\Rightarrow\\ x=\\pm 1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x=\\pm 1 \\)",
      canonicalAnswer: "{1, -1}",
    },
  },
  {
    id: "em04-020",
    topicRef: "em04",
    topicTitle: "Differentiation 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Differentiate \\( y=e^{2x}\\sin 3x \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differentiation", "product rule", "chain rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Product rule with \\( u=e^{2x} \\), \\( v=\\sin 3x \\).",
          workingLatex: "u'=2e^{2x},\\qquad v'=3\\cos 3x",
          explanation: "Each piece needs the chain rule.",
        },
        {
          stepNumber: 2,
          description: "Apply \\( u'v+uv' \\).",
          workingLatex: "\\frac{dy}{dx}=2e^{2x}\\sin 3x+3e^{2x}\\cos 3x",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Factorise.",
          workingLatex: "e^{2x}(2\\sin 3x+3\\cos 3x)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{2x}(2\\sin 3x+3\\cos 3x) \\)",
      canonicalAnswer: "e^(2*x)*(2*sin(3*x)+3*cos(3*x))",
    },
  },
];
