import { Question } from "@/lib/types";

/**
 * Topic: Integration Techniques
 * Ref:   em05  (Undergraduate Engineering Mathematics)  prereq: em04
 *
 * 20 questions — 6 Foundation, 9 Standard, 5 Challenge.
 * Power rule, standard integrals (trig/exp/1·x⁻¹), linear substitution,
 * definite integrals, substitution, integration by parts (incl. twice),
 * partial fractions, and the half-angle trick.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (6) ─────────────────────────
  {
    id: "em05-001",
    topicRef: "em05",
    topicTitle: "Integration 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int x^{4}\\,dx \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "power rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Apply \\( \\int x^{n}\\,dx=\\frac{x^{n+1}}{n+1}+C \\).",
          workingLatex: "\\frac{x^{5}}{5}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{x^{5}}{5}+C \\)",
      canonicalAnswer: "x^5/5",
    },
  },
  {
    id: "em05-002",
    topicRef: "em05",
    topicTitle: "Integration 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int (3x^{2}-4x)\\,dx \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "polynomial"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate term by term.",
          workingLatex: "x^{3}-2x^{2}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x^{3}-2x^{2}+C \\)",
      canonicalAnswer: "x^3-2*x^2",
    },
  },
  {
    id: "em05-003",
    topicRef: "em05",
    topicTitle: "Integration 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\cos x\\,dx \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard integral.",
          workingLatex: "\\sin x+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\sin x+C \\)",
      canonicalAnswer: "sin(x)",
    },
  },
  {
    id: "em05-004",
    topicRef: "em05",
    topicTitle: "Integration 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int e^{x}\\,dx \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard integral.",
          workingLatex: "e^{x}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}+C \\)",
      canonicalAnswer: "e^x",
    },
  },
  {
    id: "em05-005",
    topicRef: "em05",
    topicTitle: "Integration 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\frac{1}{x}\\,dx \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard integral.",
          workingLatex: "\\ln|x|+C",
          explanation: "The modulus covers negative \\( x \\).",
        },
      ],
      finalAnswer: "\\( \\ln|x|+C \\)",
      canonicalAnswer: "ln(abs(x))",
    },
  },
  {
    id: "em05-006",
    topicRef: "em05",
    topicTitle: "Integration 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\frac{1}{x^{2}}\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "power rule"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Write as a power.",
          workingLatex: "\\int x^{-2}\\,dx=\\frac{x^{-1}}{-1}+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Rewrite.",
          workingLatex: "-\\frac{1}{x}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\dfrac{1}{x}+C \\)",
      canonicalAnswer: "-1/x",
    },
  },

  // ───────────────────────── Standard (9) ─────────────────────────
  {
    id: "em05-007",
    topicRef: "em05",
    topicTitle: "Integration 07",
    difficulty: "Standard",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{0}^{2} x^{2}\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "definite"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "\\left[\\frac{x^{3}}{3}\\right]_{0}^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Substitute the limits.",
          workingLatex: "\\frac{8}{3}-0=\\frac{8}{3}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{8}{3} \\)",
      canonicalAnswer: "8/3",
    },
  },
  {
    id: "em05-008",
    topicRef: "em05",
    topicTitle: "Integration 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int 2x(x^{2}+1)^{3}\\,dx \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "substitution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Substitute \\( u=x^{2}+1 \\), so \\( du=2x\\,dx \\).",
          workingLatex: "\\int u^{3}\\,du",
          explanation: "The \\( 2x\\,dx \\) is exactly \\( du \\).",
        },
        {
          stepNumber: 2,
          description: "Integrate and substitute back.",
          workingLatex: "\\frac{u^{4}}{4}+C=\\frac{(x^{2}+1)^{4}}{4}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{(x^{2}+1)^{4}}{4}+C \\)",
      canonicalAnswer: "(x^2+1)^4/4",
    },
  },
  {
    id: "em05-009",
    topicRef: "em05",
    topicTitle: "Integration 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int e^{2x}\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "exponential"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Divide by the coefficient of \\( x \\).",
          workingLatex: "\\frac{1}{2}e^{2x}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{2}e^{2x}+C \\)",
      canonicalAnswer: "e^(2*x)/2",
    },
  },
  {
    id: "em05-010",
    topicRef: "em05",
    topicTitle: "Integration 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\sin 3x\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate, dividing by the coefficient of \\( x \\).",
          workingLatex: "-\\frac{1}{3}\\cos 3x+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( -\\dfrac{1}{3}\\cos 3x+C \\)",
      canonicalAnswer: "-cos(3*x)/3",
    },
  },
  {
    id: "em05-011",
    topicRef: "em05",
    topicTitle: "Integration 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int x e^{x}\\,dx \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "By parts with \\( u=x \\), \\( dv=e^{x}\\,dx \\).",
          workingLatex: "u=x,\\ du=dx;\\quad v=e^{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( \\int u\\,dv=uv-\\int v\\,du \\).",
          workingLatex: "xe^{x}-\\int e^{x}\\,dx=xe^{x}-e^{x}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}(x-1)+C \\)",
      canonicalAnswer: "e^x*(x-1)",
    },
  },
  {
    id: "em05-012",
    topicRef: "em05",
    topicTitle: "Integration 12",
    difficulty: "Standard",
    answerType: "numeric",
    questionText: "Evaluate \\( \\displaystyle\\int_{0}^{\\pi/2} \\sin x\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "definite", "trig"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "\\left[-\\cos x\\right]_{0}^{\\pi/2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Substitute the limits.",
          workingLatex: "-\\cos\\tfrac{\\pi}{2}+\\cos 0=0+1=1",
          explanation: "",
        },
      ],
      finalAnswer: "\\( 1 \\)",
      canonicalAnswer: "1",
    },
  },
  {
    id: "em05-013",
    topicRef: "em05",
    topicTitle: "Integration 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int (2x+1)^{5}\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "linear substitution"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Raise the power by one and divide by it and by the inside coefficient.",
          workingLatex: "\\frac{(2x+1)^{6}}{6\\cdot 2}+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Simplify.",
          workingLatex: "\\frac{(2x+1)^{6}}{12}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{(2x+1)^{6}}{12}+C \\)",
      canonicalAnswer: "(2*x+1)^6/12",
    },
  },
  {
    id: "em05-014",
    topicRef: "em05",
    topicTitle: "Integration 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\frac{1}{2x+3}\\,dx \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["integration", "logarithm"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integral of \\( \\frac{1}{ax+b} \\) is \\( \\frac{1}{a}\\ln|ax+b| \\).",
          workingLatex: "\\frac{1}{2}\\ln|2x+3|+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{2}\\ln|2x+3|+C \\)",
      canonicalAnswer: "ln(abs(2*x+3))/2",
    },
  },
  {
    id: "em05-015",
    topicRef: "em05",
    topicTitle: "Integration 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\ln x\\,dx \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "By parts with \\( u=\\ln x \\), \\( dv=dx \\).",
          workingLatex: "u=\\ln x,\\ du=\\frac{1}{x}\\,dx;\\quad v=x",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply the formula.",
          workingLatex: "x\\ln x-\\int x\\cdot\\frac{1}{x}\\,dx=x\\ln x-\\int 1\\,dx",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Finish.",
          workingLatex: "x\\ln x-x+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( x\\ln x-x+C \\)",
      canonicalAnswer: "x*ln(x)-x",
    },
  },

  // ───────────────────────── Challenge (5) ─────────────────────────
  {
    id: "em05-016",
    topicRef: "em05",
    topicTitle: "Integration 16",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\frac{1}{(x-1)(x+1)}\\,dx \\) using partial fractions.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "partial fractions"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Decompose into partial fractions.",
          workingLatex: "\\frac{1}{(x-1)(x+1)}=\\frac{1}{2}\\left(\\frac{1}{x-1}-\\frac{1}{x+1}\\right)",
          explanation: "Cover-up: \\( A=\\tfrac12 \\) at \\( x=1 \\), \\( B=-\\tfrac12 \\) at \\( x=-1 \\).",
        },
        {
          stepNumber: 2,
          description: "Integrate each term.",
          workingLatex: "\\frac{1}{2}\\left(\\ln|x-1|-\\ln|x+1|\\right)+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Combine the logarithms.",
          workingLatex: "\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right|+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{1}{2}\\ln\\left|\\dfrac{x-1}{x+1}\\right|+C \\)",
      canonicalAnswer: "ln(abs((x-1)/(x+1)))/2",
    },
  },
  {
    id: "em05-017",
    topicRef: "em05",
    topicTitle: "Integration 17",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int x^{2}e^{x}\\,dx \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "by parts"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "By parts with \\( u=x^{2} \\), \\( dv=e^{x}\\,dx \\).",
          workingLatex: "\\int x^{2}e^{x}\\,dx=x^{2}e^{x}-\\int 2x e^{x}\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply by parts again to \\( \\int xe^{x}\\,dx=e^{x}(x-1) \\).",
          workingLatex: "=x^{2}e^{x}-2\\,e^{x}(x-1)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Expand and factorise.",
          workingLatex: "e^{x}\\left(x^{2}-2x+2\\right)+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( e^{x}(x^{2}-2x+2)+C \\)",
      canonicalAnswer: "e^x*(x^2-2*x+2)",
    },
  },
  {
    id: "em05-018",
    topicRef: "em05",
    topicTitle: "Integration 18",
    difficulty: "Challenge",
    answerType: "exactValue",
    answerMeta: { exactForm: true },
    questionText: "Evaluate \\( \\displaystyle\\int_{0}^{1} \\frac{1}{1+x^{2}}\\,dx \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "definite", "arctan"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Standard integral.",
          workingLatex: "\\left[\\arctan x\\right]_{0}^{1}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Substitute the limits.",
          workingLatex: "\\arctan 1-\\arctan 0=\\frac{\\pi}{4}-0=\\frac{\\pi}{4}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{\\pi}{4} \\)",
      canonicalAnswer: "pi/4",
    },
  },
  {
    id: "em05-019",
    topicRef: "em05",
    topicTitle: "Integration 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find \\( \\displaystyle\\int \\sin^{2}x\\,dx \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "trig", "double angle"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Use the identity \\( \\sin^{2}x=\\frac{1-\\cos 2x}{2} \\).",
          workingLatex: "\\int\\frac{1-\\cos 2x}{2}\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate term by term.",
          workingLatex: "\\frac{x}{2}-\\frac{\\sin 2x}{4}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\dfrac{x}{2}-\\dfrac{\\sin 2x}{4}+C \\)",
      canonicalAnswer: "x/2 - sin(2*x)/4",
    },
  },
  {
    id: "em05-020",
    topicRef: "em05",
    topicTitle: "Integration 20",
    difficulty: "Challenge",
    answerType: "numeric",
    questionText: "Evaluate \\( \\displaystyle\\int_{0}^{\\pi} x\\sin x\\,dx \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["integration", "by parts", "definite"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "By parts with \\( u=x \\), \\( dv=\\sin x\\,dx \\).",
          workingLatex: "\\int x\\sin x\\,dx=-x\\cos x+\\int\\cos x\\,dx=-x\\cos x+\\sin x",
          explanation: "\\( v=-\\cos x \\).",
        },
        {
          stepNumber: 2,
          description: "Apply the limits \\( 0 \\) to \\( \\pi \\).",
          workingLatex: "\\left[-x\\cos x+\\sin x\\right]_{0}^{\\pi}=(-\\pi\\cos\\pi+\\sin\\pi)-(0+0)",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Evaluate.",
          workingLatex: "-\\pi(-1)+0=\\pi",
          explanation: "",
        },
      ],
      finalAnswer: "\\( \\pi \\)",
      canonicalAnswer: "pi",
    },
  },
];
