import { Question } from "@/lib/types";

/**
 * Topic: First-Order Differential Equations
 * Ref:   em08  (Undergraduate Engineering Mathematics)  prereq: em05
 *
 * 20 questions — 6 Foundation, 9 Standard, 5 Challenge.
 * Direct integration, separable equations, linear equations via integrating
 * factor, initial-value problems, and growth/decay applications.
 */
export const questions: Question[] = [
  // ───────────────────────── Foundation (6) ─────────────────────────
  {
    id: "em08-001",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 01",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=2x \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "direct integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate both sides.",
          workingLatex: "y=\\int 2x\\,dx=x^{2}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=x^{2}+C \\)",
      canonicalAnswer: "x^2+C",
    },
  },
  {
    id: "em08-002",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 02",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=e^{x} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "direct integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "y=e^{x}+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=e^{x}+C \\)",
      canonicalAnswer: "e^x+C",
    },
  },
  {
    id: "em08-003",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 03",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=\\cos x \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "direct integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "y=\\sin x+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\sin x+C \\)",
      canonicalAnswer: "sin(x)+C",
    },
  },
  {
    id: "em08-004",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 04",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=6x^{2}-4 \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "direct integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate term by term.",
          workingLatex: "y=2x^{3}-4x+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=2x^{3}-4x+C \\)",
      canonicalAnswer: "2*x^3-4*x+C",
    },
  },
  {
    id: "em08-005",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 05",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=y \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate the variables.",
          workingLatex: "\\int\\frac{1}{y}\\,dy=\\int 1\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate and exponentiate.",
          workingLatex: "\\ln|y|=x+C\\ \\Rightarrow\\ y=Ae^{x}",
          explanation: "\\( A=e^{C} \\).",
        },
      ],
      finalAnswer: "\\( y=Ae^{x} \\)",
      canonicalAnswer: "A*e^x",
    },
  },
  {
    id: "em08-006",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 06",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=\\dfrac{1}{x} \\).",
    marks: 1,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "direct integration"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "y=\\ln|x|+C",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\ln|x|+C \\)",
      canonicalAnswer: "ln(abs(x))+C",
    },
  },

  // ───────────────────────── Standard (9) ─────────────────────────
  {
    id: "em08-007",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 07",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=xy \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate.",
          workingLatex: "\\int\\frac{1}{y}\\,dy=\\int x\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "\\ln|y|=\\frac{x^{2}}{2}+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Exponentiate.",
          workingLatex: "y=Ae^{x^{2}/2}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=Ae^{x^{2}/2} \\)",
      canonicalAnswer: "A*e^(x^2/2)",
    },
  },
  {
    id: "em08-008",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 08",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=\\dfrac{y}{x} \\) for \\( x>0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate and integrate.",
          workingLatex: "\\int\\frac{1}{y}\\,dy=\\int\\frac{1}{x}\\,dx\\ \\Rightarrow\\ \\ln|y|=\\ln x+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Exponentiate.",
          workingLatex: "y=Ax",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=Ax \\)",
      canonicalAnswer: "A*x",
    },
  },
  {
    id: "em08-009",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 09",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=\\dfrac{2x}{y} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate.",
          workingLatex: "\\int y\\,dy=\\int 2x\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "\\frac{y^{2}}{2}=x^{2}+C\\ \\Rightarrow\\ y^{2}=2x^{2}+C",
          explanation: "The constant is renamed.",
        },
      ],
      finalAnswer: "\\( y^{2}=2x^{2}+C \\)",
      canonicalAnswer: "y^2=2*x^2+C",
    },
  },
  {
    id: "em08-010",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 10",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}+y=e^{x} \\) using an integrating factor.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "integrating factor", "linear"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrating factor \\( e^{\\int 1\\,dx}=e^{x} \\).",
          workingLatex: "\\frac{d}{dx}\\!\\left(e^{x}y\\right)=e^{x}\\cdot e^{x}=e^{2x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "e^{x}y=\\frac{1}{2}e^{2x}+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Divide by \\( e^{x} \\).",
          workingLatex: "y=\\frac{1}{2}e^{x}+Ce^{-x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\dfrac{1}{2}e^{x}+Ce^{-x} \\)",
      canonicalAnswer: "e^x/2 + C*e^(-x)",
    },
  },
  {
    id: "em08-011",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 11",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}+2y=0 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "separable", "linear"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate and integrate.",
          workingLatex: "\\int\\frac{1}{y}\\,dy=\\int -2\\,dx\\ \\Rightarrow\\ \\ln|y|=-2x+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Exponentiate.",
          workingLatex: "y=Ae^{-2x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=Ae^{-2x} \\)",
      canonicalAnswer: "A*e^(-2*x)",
    },
  },
  {
    id: "em08-012",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 12",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=3x^{2} \\) given \\( y(0)=2 \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["differential equations", "initial value"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrate.",
          workingLatex: "y=x^{3}+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( y(0)=2 \\).",
          workingLatex: "2=0+C\\ \\Rightarrow\\ C=2",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=x^{3}+2 \\)",
      canonicalAnswer: "x^3+2",
    },
  },
  {
    id: "em08-013",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 13",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}+\\dfrac{1}{x}\\,y=x \\) for \\( x>0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "integrating factor", "linear"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrating factor \\( e^{\\int (1/x)\\,dx}=e^{\\ln x}=x \\).",
          workingLatex: "\\frac{d}{dx}(xy)=x\\cdot x=x^{2}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "xy=\\frac{x^{3}}{3}+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Divide by \\( x \\).",
          workingLatex: "y=\\frac{x^{2}}{3}+\\frac{C}{x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\dfrac{x^{2}}{3}+\\dfrac{C}{x} \\)",
      canonicalAnswer: "x^2/3 + C/x",
    },
  },
  {
    id: "em08-014",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 14",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=y^{2} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate.",
          workingLatex: "\\int y^{-2}\\,dy=\\int 1\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "-\\frac{1}{y}=x+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Rearrange for \\( y \\).",
          workingLatex: "y=-\\frac{1}{x+C}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=-\\dfrac{1}{x+C} \\)",
      canonicalAnswer: "-1/(x+C)",
    },
  },
  {
    id: "em08-015",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 15",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dt}=-3y \\) given \\( y(0)=5 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "decay", "initial value"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Exponential decay solution.",
          workingLatex: "y=Ae^{-3t}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Apply \\( y(0)=5 \\).",
          workingLatex: "5=A\\ \\Rightarrow\\ y=5e^{-3t}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=5e^{-3t} \\)",
      canonicalAnswer: "5*e^(-3*t)",
    },
  },

  // ───────────────────────── Challenge (5) ─────────────────────────
  {
    id: "em08-016",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 16",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}+y=x \\) given \\( y(0)=1 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "integrating factor", "initial value"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrating factor \\( e^{x} \\).",
          workingLatex: "\\frac{d}{dx}(e^{x}y)=xe^{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate (by parts on the right).",
          workingLatex: "e^{x}y=e^{x}(x-1)+C",
          explanation: "\\( \\int xe^{x}\\,dx=e^{x}(x-1) \\).",
        },
        {
          stepNumber: 3,
          description: "Solve for \\( y \\).",
          workingLatex: "y=x-1+Ce^{-x}",
          explanation: "",
        },
        {
          stepNumber: 4,
          description: "Apply \\( y(0)=1 \\).",
          workingLatex: "1=-1+C\\ \\Rightarrow\\ C=2",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=x-1+2e^{-x} \\)",
      canonicalAnswer: "x-1+2*e^(-x)",
    },
  },
  {
    id: "em08-017",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 17",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=1+y^{2} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable", "arctan"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate.",
          workingLatex: "\\int\\frac{1}{1+y^{2}}\\,dy=\\int 1\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "\\arctan y=x+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Solve for \\( y \\).",
          workingLatex: "y=\\tan(x+C)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\tan(x+C) \\)",
      canonicalAnswer: "tan(x+C)",
    },
  },
  {
    id: "em08-018",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 18",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=xe^{-y} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate (multiply by \\( e^{y} \\)).",
          workingLatex: "\\int e^{y}\\,dy=\\int x\\,dx",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "e^{y}=\\frac{x^{2}}{2}+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Take logs.",
          workingLatex: "y=\\ln\\!\\left(\\frac{x^{2}}{2}+C\\right)",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=\\ln\\!\\left(\\dfrac{x^{2}}{2}+C\\right) \\)",
      canonicalAnswer: "ln(x^2/2+C)",
    },
  },
  {
    id: "em08-019",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 19",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}-2y=e^{3x} \\) using an integrating factor.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "integrating factor", "linear"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Integrating factor \\( e^{\\int -2\\,dx}=e^{-2x} \\).",
          workingLatex: "\\frac{d}{dx}\\!\\left(e^{-2x}y\\right)=e^{-2x}e^{3x}=e^{x}",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Integrate.",
          workingLatex: "e^{-2x}y=e^{x}+C",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Multiply by \\( e^{2x} \\).",
          workingLatex: "y=e^{3x}+Ce^{2x}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=e^{3x}+Ce^{2x} \\)",
      canonicalAnswer: "e^(3*x)+C*e^(2*x)",
    },
  },
  {
    id: "em08-020",
    topicRef: "em08",
    topicTitle: "First-Order ODEs 20",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Solve \\( \\dfrac{dy}{dx}=2xy \\) given \\( y(0)=1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["differential equations", "separable", "initial value"],
    workedSolution: {
      steps: [
        {
          stepNumber: 1,
          description: "Separate and integrate.",
          workingLatex: "\\int\\frac{1}{y}\\,dy=\\int 2x\\,dx\\ \\Rightarrow\\ \\ln|y|=x^{2}+C",
          explanation: "",
        },
        {
          stepNumber: 2,
          description: "Exponentiate.",
          workingLatex: "y=Ae^{x^{2}}",
          explanation: "",
        },
        {
          stepNumber: 3,
          description: "Apply \\( y(0)=1 \\).",
          workingLatex: "1=A\\ \\Rightarrow\\ y=e^{x^{2}}",
          explanation: "",
        },
      ],
      finalAnswer: "\\( y=e^{x^{2}} \\)",
      canonicalAnswer: "e^(x^2)",
    },
  },
];
