import { Question } from "@/lib/types";

/*
 * Complex Methods — cm1a
 * Differentiability from first principles & the Cauchy–Riemann equations
 * Topic group: Analytic Functions
 *
 * 30 fully-worked questions seeded from Cambridge Part IB Complex Methods
 * Example Sheet 1, Q1 (Cauchy–Riemann equations: where Im z, |z|^2, sech z are
 * differentiable/analytic; the f = z^5/|z|^4 counterexample; the z,zbar chain-rule
 * formulation), with constants, functions and framing varied.
 *
 * Difficulty split 6 / 12 / 12 (Foundation / Standard / Challenge).
 *
 * Conventions: worked-solution fractions use big \frac; stems use \dfrac.
 * "analytic" = differentiable on an open neighbourhood. Every CR computation was
 * re-derived from u_x = v_y, u_y = -v_x and cross-checked against the limit of the
 * difference quotient along the real and imaginary axes.
 */
export const questions: Question[] = [
  // --------- Foundation (6) ---------
  {
    id: "cm1a-001",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( f(z) = u + iv \\) with \\( u(x,y) = x^2 - y^2 \\) and \\( v(x,y) = 2xy \\), compute the four partial derivatives \\( u_x, u_y, v_x, v_y \\) and state whether the Cauchy–Riemann equations \\( u_x = v_y,\\ u_y = -v_x \\) hold.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "partial derivatives"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate u.", workingLatex: "u_x = 2x, \\qquad u_y = -2y.", explanation: "Treat each variable as independent when taking the partial derivative." },
        { stepNumber: 2, description: "Differentiate v.", workingLatex: "v_x = 2y, \\qquad v_y = 2x.", explanation: "" },
        { stepNumber: 3, description: "Test the first CR equation.", workingLatex: "u_x = 2x = v_y. \\quad\\checkmark", explanation: "The real-axis limit of the difference quotient forces u_x = v_y." },
        { stepNumber: 4, description: "Test the second CR equation.", workingLatex: "u_y = -2y = -v_x. \\quad\\checkmark", explanation: "The imaginary-axis limit forces u_y = -v_x; both hold everywhere, consistent with f(z)=z^2." },
      ],
      finalAnswer: "\\( u_x = 2x,\\ u_y = -2y,\\ v_x = 2y,\\ v_y = 2x \\); the CR equations hold for all \\( (x,y) \\).",
      canonicalAnswer: "u_x=2x, u_y=-2y, v_x=2y, v_y=2x; CR holds everywhere",
    },
  },
  {
    id: "cm1a-002",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Write \\( f(z) = \\operatorname{Re} z \\) in the form \\( u + iv \\) and find \\( u_x, u_y, v_x, v_y \\). Hence state whether the Cauchy–Riemann equations hold anywhere.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "Re z"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate real and imaginary parts.", workingLatex: "f(z) = x + i\\cdot 0, \\qquad u = x,\\ v = 0.", explanation: "Re z = x, and there is no imaginary part." },
        { stepNumber: 2, description: "Compute the partials.", workingLatex: "u_x = 1,\\ u_y = 0,\\quad v_x = 0,\\ v_y = 0.", explanation: "" },
        { stepNumber: 3, description: "Test CR.", workingLatex: "u_x = 1 \\ne 0 = v_y.", explanation: "The first CR equation fails at every point, since 1 can never equal 0." },
      ],
      finalAnswer: "\\( u_x = 1,\\ u_y = 0,\\ v_x = 0,\\ v_y = 0 \\); since \\( u_x \\ne v_y \\) the CR equations hold nowhere.",
      canonicalAnswer: "CR holds nowhere",
    },
  },
  {
    id: "cm1a-003",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( f(z) = e^{z} \\) one has \\( u = e^{x}\\cos y,\\ v = e^{x}\\sin y \\). Verify the Cauchy–Riemann equations by computing \\( u_x, v_y \\) and \\( u_y, v_x \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "exponential function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate u.", workingLatex: "u_x = e^{x}\\cos y, \\qquad u_y = -e^{x}\\sin y.", explanation: "Differentiate the product; cos y differentiates to -sin y." },
        { stepNumber: 2, description: "Differentiate v.", workingLatex: "v_x = e^{x}\\sin y, \\qquad v_y = e^{x}\\cos y.", explanation: "" },
        { stepNumber: 3, description: "Check the CR pair.", workingLatex: "u_x = e^{x}\\cos y = v_y, \\qquad u_y = -e^{x}\\sin y = -v_x.", explanation: "Both equations hold for all (x,y), so e^z is entire (analytic everywhere)." },
      ],
      finalAnswer: "\\( u_x = v_y = e^{x}\\cos y \\) and \\( u_y = -v_x = -e^{x}\\sin y \\); the CR equations hold everywhere.",
      canonicalAnswer: "CR holds everywhere; e^z entire",
    },
  },
  {
    id: "cm1a-004",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "set",
    questionText: "For \\( f(z) = |z|^2 = x^2 + y^2 \\) (so \\( u = x^2+y^2,\\ v = 0 \\)), find all points where the Cauchy–Riemann equations hold.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "|z|^2"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the partials.", workingLatex: "u_x = 2x,\\ u_y = 2y,\\qquad v_x = 0,\\ v_y = 0.", explanation: "v is identically zero so its derivatives vanish." },
        { stepNumber: 2, description: "Impose CR.", workingLatex: "u_x = v_y \\Rightarrow 2x = 0, \\qquad u_y = -v_x \\Rightarrow 2y = 0.", explanation: "Both equations must hold simultaneously." },
        { stepNumber: 3, description: "Solve.", workingLatex: "x = 0 \\text{ and } y = 0 \\Rightarrow z = 0.", explanation: "Only the origin satisfies both, so CR holds at z = 0 alone." },
      ],
      finalAnswer: "\\( \\{0\\} \\) — the CR equations hold only at \\( z = 0 \\).",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1a-005",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using the definition \\( f'(z) = \\lim_{h\\to 0}\\dfrac{f(z+h)-f(z)}{h} \\), compute the derivative of \\( f(z) = z^2 \\) from first principles.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["first principles", "complex derivative"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the difference quotient.", workingLatex: "\\frac{(z+h)^2 - z^2}{h} = \\frac{z^2 + 2zh + h^2 - z^2}{h}.", explanation: "Expand the square; h is a complex increment." },
        { stepNumber: 2, description: "Simplify.", workingLatex: "= \\frac{2zh + h^2}{h} = 2z + h.", explanation: "Cancel one factor of h; valid since h \\ne 0 in the limit." },
        { stepNumber: 3, description: "Take the limit.", workingLatex: "\\lim_{h\\to 0}(2z + h) = 2z.", explanation: "The limit is the same along every path h \\to 0, so the derivative exists and equals 2z." },
      ],
      finalAnswer: "\\( f'(z) = 2z \\).",
      canonicalAnswer: "2z",
    },
  },
  {
    id: "cm1a-006",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For an analytic \\( f = u + iv \\), the derivative is \\( f'(z) = u_x + i v_x \\). Given \\( u = x^3 - 3xy^2 \\) and \\( v = 3x^2 y - y^3 \\), compute \\( f'(z) \\) and express it in terms of \\( z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["complex derivative", "f'=u_x+i v_x"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate u and v in x.", workingLatex: "u_x = 3x^2 - 3y^2, \\qquad v_x = 6xy.", explanation: "These are the x-partials needed for the derivative formula." },
        { stepNumber: 2, description: "Assemble f'.", workingLatex: "f'(z) = u_x + i v_x = (3x^2 - 3y^2) + i\\,6xy.", explanation: "Valid because CR holds (u,v are Re and Im of z^3)." },
        { stepNumber: 3, description: "Recognise the z-form.", workingLatex: "3(x^2 - y^2) + i\\,6xy = 3\\big((x+iy)^2\\big) = 3z^2.", explanation: "Since f(z) = z^3, the derivative is 3z^2, as expected." },
      ],
      finalAnswer: "\\( f'(z) = 3z^2 \\).",
      canonicalAnswer: "3z^2",
    },
  },
  // --------- Standard (12) ---------
  {
    id: "cm1a-007",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show from first principles that \\( f(z) = \\operatorname{Im} z \\) is differentiable nowhere, by evaluating \\( \\lim_{h\\to 0}\\dfrac{f(z+h)-f(z)}{h} \\) along the real and imaginary axes.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["first principles", "path-independence", "Im z"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the difference quotient.", workingLatex: "Q(h) = \\frac{\\operatorname{Im}(z+h) - \\operatorname{Im}(z)}{h} = \\frac{\\operatorname{Im} h}{h}.", explanation: "Im is additive, so Im(z+h) - Im(z) = Im h." },
        { stepNumber: 2, description: "Approach along the real axis.", workingLatex: "h = t \\in \\mathbb{R}: \\quad Q = \\frac{\\operatorname{Im} t}{t} = \\frac{0}{t} = 0.", explanation: "A real increment has zero imaginary part, so the quotient is 0." },
        { stepNumber: 3, description: "Approach along the imaginary axis.", workingLatex: "h = it,\\ t\\in\\mathbb{R}: \\quad Q = \\frac{\\operatorname{Im}(it)}{it} = \\frac{t}{it} = \\frac{1}{i} = -i.", explanation: "An imaginary increment gives quotient -i." },
        { stepNumber: 4, description: "Compare the two limits.", workingLatex: "0 \\ne -i.", explanation: "The limit depends on the direction of approach, so it does not exist; this holds at every z." },
      ],
      finalAnswer: "The difference quotient tends to \\( 0 \\) along the real axis but \\( -i \\) along the imaginary axis, so \\( f(z) = \\operatorname{Im} z \\) is differentiable nowhere.",
    },
  },
  {
    id: "cm1a-008",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Determine the set of points at which \\( f(z) = z\\,\\bar z \\) is differentiable, and state where (if anywhere) it is analytic.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "z zbar", "analytic vs differentiable"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u and v.", workingLatex: "f(z) = z\\bar z = |z|^2 = x^2 + y^2, \\qquad u = x^2+y^2,\\ v = 0.", explanation: "The product z·zbar is real and equals the modulus squared." },
        { stepNumber: 2, description: "Compute partials.", workingLatex: "u_x = 2x,\\ u_y = 2y,\\qquad v_x = 0,\\ v_y = 0.", explanation: "" },
        { stepNumber: 3, description: "Apply CR.", workingLatex: "2x = 0 \\text{ and } 2y = 0 \\Rightarrow x = y = 0.", explanation: "CR holds only at the origin." },
        { stepNumber: 4, description: "Decide differentiability and analyticity.", workingLatex: "z = 0 \\text{ only; no open neighbourhood of differentiability.}", explanation: "Differentiable at a single point cannot be analytic, since analyticity needs an open set." },
      ],
      finalAnswer: "Differentiable only at \\( z = 0 \\); analytic nowhere.",
      canonicalAnswer: "differentiable {0}, analytic nowhere",
    },
  },
  {
    id: "cm1a-009",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "By taking the limit of the difference quotient along the real axis (\\( h = t \\)) and along the imaginary axis (\\( h = it \\)) for an arbitrary differentiable \\( f = u + iv \\), derive the Cauchy–Riemann equations.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["first principles", "deriving CR"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Limit along the real axis.", workingLatex: "f'(z) = \\lim_{t\\to 0}\\frac{f(x+t+iy)-f(x+iy)}{t} = u_x + i v_x.", explanation: "A real increment t changes only x, giving the x-partials." },
        { stepNumber: 2, description: "Limit along the imaginary axis.", workingLatex: "f'(z) = \\lim_{t\\to 0}\\frac{f(x+i(y+t))-f(x+iy)}{it} = \\frac{1}{i}(u_y + i v_y).", explanation: "An imaginary increment it changes only y; divide the y-partials by i." },
        { stepNumber: 3, description: "Simplify the second expression.", workingLatex: "\\frac{1}{i}(u_y + i v_y) = -i u_y + v_y = v_y - i u_y.", explanation: "Using 1/i = -i." },
        { stepNumber: 4, description: "Equate the two forms of f'.", workingLatex: "u_x + i v_x = v_y - i u_y.", explanation: "Differentiability means the limit is path-independent, so the two values must agree." },
        { stepNumber: 5, description: "Match real and imaginary parts.", workingLatex: "u_x = v_y, \\qquad v_x = -u_y.", explanation: "Equating real and imaginary parts gives the Cauchy–Riemann equations." },
      ],
      finalAnswer: "\\( u_x = v_y \\) and \\( u_y = -v_x \\).",
    },
  },
  {
    id: "cm1a-010",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Locate all points where \\( f(z) = \\bar z \\) is differentiable, working from the difference quotient directly.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["first principles", "conjugate", "path-independence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the quotient.", workingLatex: "Q(h) = \\frac{\\overline{z+h} - \\bar z}{h} = \\frac{\\bar h}{h}.", explanation: "Conjugation is additive, so the z-terms cancel leaving hbar/h." },
        { stepNumber: 2, description: "Real-axis approach.", workingLatex: "h = t: \\quad Q = \\frac{\\bar t}{t} = \\frac{t}{t} = 1.", explanation: "A real number equals its own conjugate." },
        { stepNumber: 3, description: "Imaginary-axis approach.", workingLatex: "h = it: \\quad Q = \\frac{\\overline{it}}{it} = \\frac{-it}{it} = -1.", explanation: "The conjugate of it is -it." },
        { stepNumber: 4, description: "Compare.", workingLatex: "1 \\ne -1 \\text{ at every } z.", explanation: "The limit is direction-dependent everywhere, so f is nowhere differentiable." },
      ],
      finalAnswer: "\\( \\varnothing \\) — \\( f(z) = \\bar z \\) is differentiable nowhere (hence analytic nowhere).",
      canonicalAnswer: "differentiable nowhere",
    },
  },
  {
    id: "cm1a-011",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find where \\( f(z) = \\sech z = \\dfrac{1}{\\cosh z} \\) is differentiable and where it is analytic. Give the set of points to exclude.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["analytic functions", "sech z", "poles of cosh"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Note cosh z is entire.", workingLatex: "\\cosh z = \\tfrac12(e^z + e^{-z}) \\text{ is differentiable for all } z.", explanation: "Sums and compositions of entire functions are entire." },
        { stepNumber: 2, description: "A reciprocal is analytic away from zeros.", workingLatex: "\\sech z = (\\cosh z)^{-1} \\text{ is analytic where } \\cosh z \\ne 0.", explanation: "Quotient rule: 1/g is differentiable wherever g is differentiable and nonzero." },
        { stepNumber: 3, description: "Find the zeros of cosh.", workingLatex: "\\cosh z = 0 \\iff \\cos(iz)=0 \\iff iz = \\tfrac{\\pi}{2} + n\\pi.", explanation: "Using cosh z = cos(iz)." },
        { stepNumber: 4, description: "Solve for z.", workingLatex: "z = -i\\left(\\tfrac{\\pi}{2} + n\\pi\\right) = i\\pi\\left(n + \\tfrac12\\right),\\ n\\in\\mathbb{Z}.", explanation: "These are the poles of sech z." },
        { stepNumber: 5, description: "State the conclusion.", workingLatex: "\\text{differentiable } = \\text{analytic} = \\mathbb{C}\\setminus\\{i\\pi(n+\\tfrac12)\\}.", explanation: "Away from its poles sech z is analytic; on each pole it is undefined, so neither holds there." },
      ],
      finalAnswer: "Analytic (and differentiable) on \\( \\mathbb{C}\\setminus\\{\\,z = i\\pi(n+\\tfrac12):\\ n\\in\\mathbb{Z}\\,\\} \\); undefined at the poles \\( z = i\\pi(n+\\tfrac12) \\).",
      canonicalAnswer: "C \\ {i*pi*(n+1/2): n in Z}",
    },
  },
  {
    id: "cm1a-012",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Verify that \\( u(x,y) = e^{x}(x\\cos y - y\\sin y) \\) and \\( v(x,y) = e^{x}(y\\cos y + x\\sin y) \\) satisfy the Cauchy–Riemann equations, confirming \\( f(z) = z e^{z} \\) is analytic.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "z e^z"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate u in x.", workingLatex: "u_x = e^{x}(x\\cos y - y\\sin y) + e^{x}\\cos y = e^{x}\\big((x+1)\\cos y - y\\sin y\\big).", explanation: "Product rule on the e^x prefactor." },
        { stepNumber: 2, description: "Differentiate v in y.", workingLatex: "v_y = e^{x}\\big(\\cos y - y\\sin y + x\\cos y\\big) = e^{x}\\big((x+1)\\cos y - y\\sin y\\big).", explanation: "Differentiate y cos y and x sin y in y." },
        { stepNumber: 3, description: "First CR equation.", workingLatex: "u_x = v_y. \\quad\\checkmark", explanation: "The two expressions are identical." },
        { stepNumber: 4, description: "Differentiate u in y.", workingLatex: "u_y = e^{x}(-x\\sin y - \\sin y - y\\cos y) = -e^{x}\\big((x+1)\\sin y + y\\cos y\\big).", explanation: "Differentiate x cos y and y sin y in y." },
        { stepNumber: 5, description: "Differentiate v in x.", workingLatex: "v_x = e^{x}(y\\cos y + x\\sin y) + e^{x}\\sin y = e^{x}\\big(y\\cos y + (x+1)\\sin y\\big).", explanation: "Product rule on the e^x prefactor." },
        { stepNumber: 6, description: "Second CR equation.", workingLatex: "u_y = -v_x. \\quad\\checkmark", explanation: "Both CR equations hold for all (x,y), so z e^z is entire." },
      ],
      finalAnswer: "Both \\( u_x = v_y \\) and \\( u_y = -v_x \\) hold everywhere, so \\( f(z) = z e^{z} \\) is analytic on \\( \\mathbb{C} \\).",
    },
  },
  {
    id: "cm1a-013",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "For \\( f(z) = (\\operatorname{Re} z)^2 = x^2 \\) (so \\( u = x^2,\\ v = 0 \\)), find the set of points where the Cauchy–Riemann equations hold, and state where \\( f \\) is analytic.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "(Re z)^2"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Partials.", workingLatex: "u_x = 2x,\\ u_y = 0,\\qquad v_x = 0,\\ v_y = 0.", explanation: "v vanishes identically." },
        { stepNumber: 2, description: "Apply CR.", workingLatex: "u_x = v_y \\Rightarrow 2x = 0; \\qquad u_y = -v_x \\Rightarrow 0 = 0.", explanation: "The second equation is automatically satisfied; only the first constrains." },
        { stepNumber: 3, description: "Solve.", workingLatex: "x = 0 \\Rightarrow \\{z : \\operatorname{Re} z = 0\\} = i\\mathbb{R}.", explanation: "CR holds on the whole imaginary axis." },
        { stepNumber: 4, description: "Analyticity.", workingLatex: "i\\mathbb{R} \\text{ contains no open set.}", explanation: "A line has empty interior, so there is no open neighbourhood of differentiability: f is analytic nowhere." },
      ],
      finalAnswer: "CR holds on the imaginary axis \\( \\{x = 0\\} \\); \\( f \\) is differentiable only there and analytic nowhere.",
      canonicalAnswer: "differentiable on x=0 (imaginary axis), analytic nowhere",
    },
  },
  {
    id: "cm1a-014",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Given the harmonic function \\( u(x,y) = x^2 - y^2 + 2x \\), find a harmonic conjugate \\( v(x,y) \\) (up to a constant) using the Cauchy–Riemann equations.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "harmonic conjugate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use the first CR equation.", workingLatex: "v_y = u_x = 2x + 2.", explanation: "u_x = v_y supplies the y-derivative of v." },
        { stepNumber: 2, description: "Integrate in y.", workingLatex: "v = \\int (2x+2)\\,dy = 2xy + 2y + g(x).", explanation: "The constant of integration is an unknown function g(x) of x alone." },
        { stepNumber: 3, description: "Use the second CR equation.", workingLatex: "v_x = -u_y. \\quad u_y = -2y \\Rightarrow -u_y = 2y.", explanation: "Compute u_y and apply v_x = -u_y." },
        { stepNumber: 4, description: "Differentiate the trial v in x.", workingLatex: "v_x = 2y + g'(x) \\overset{!}{=} 2y \\Rightarrow g'(x) = 0.", explanation: "Match to the required v_x; g is therefore constant." },
        { stepNumber: 5, description: "Assemble v.", workingLatex: "v = 2xy + 2y + C.", explanation: "f = u + iv = z^2 + 2z + iC, confirming v is a valid conjugate." },
      ],
      finalAnswer: "\\( v(x,y) = 2xy + 2y + C \\) for an arbitrary real constant \\( C \\).",
      canonicalAnswer: "2xy+2y+C",
    },
  },
  {
    id: "cm1a-015",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Determine the set on which \\( f(z) = x^2 + i y^2 \\) (i.e. \\( u = x^2,\\ v = y^2 \\)) is differentiable, and state whether it is analytic anywhere.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "differentiable on a line"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Partials.", workingLatex: "u_x = 2x,\\ u_y = 0,\\qquad v_x = 0,\\ v_y = 2y.", explanation: "" },
        { stepNumber: 2, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 2x = 2y \\Rightarrow x = y.", explanation: "This restricts to the diagonal line." },
        { stepNumber: 3, description: "Second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow 0 = 0.", explanation: "Automatically satisfied." },
        { stepNumber: 4, description: "Combine and conclude.", workingLatex: "\\{x = y\\}.", explanation: "Since the partials are continuous, CR holding on this line means f is differentiable exactly on the line y = x; a line has no interior, so f is analytic nowhere." },
      ],
      finalAnswer: "Differentiable exactly on the line \\( y = x \\); analytic nowhere.",
      canonicalAnswer: "differentiable on y=x, analytic nowhere",
    },
  },
  {
    id: "cm1a-016",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using the Wirtinger operator \\( \\dfrac{\\partial}{\\partial \\bar z} = \\dfrac12\\left(\\dfrac{\\partial}{\\partial x} + i\\dfrac{\\partial}{\\partial y}\\right) \\), show that \\( \\dfrac{\\partial f}{\\partial \\bar z} = 0 \\) for \\( f = u + iv \\) is equivalent to the Cauchy–Riemann equations.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "d/dzbar = 0"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the operator to f.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z} = \\frac12\\big((u+iv)_x + i(u+iv)_y\\big).", explanation: "Substitute f = u + iv into the Wirtinger derivative." },
        { stepNumber: 2, description: "Expand.", workingLatex: "= \\frac12\\big(u_x + i v_x + i u_y - v_y\\big).", explanation: "Distribute and use i·i = -1 on the iv_y term." },
        { stepNumber: 3, description: "Group real and imaginary parts.", workingLatex: "= \\frac12\\big[(u_x - v_y) + i(v_x + u_y)\\big].", explanation: "Collect terms without and with a factor i." },
        { stepNumber: 4, description: "Set to zero.", workingLatex: "u_x - v_y = 0 \\text{ and } v_x + u_y = 0.", explanation: "A complex number is zero iff both parts vanish." },
        { stepNumber: 5, description: "Read off CR.", workingLatex: "u_x = v_y, \\qquad u_y = -v_x.", explanation: "Exactly the Cauchy–Riemann equations; so analyticity ⇔ ∂f/∂zbar = 0." },
      ],
      finalAnswer: "\\( \\partial f/\\partial\\bar z = \\tfrac12[(u_x - v_y) + i(v_x + u_y)] = 0 \\iff u_x = v_y,\\ u_y = -v_x \\).",
    },
  },
  {
    id: "cm1a-017",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find all points where \\( f(z) = x^3 + i(1 - y)^3 \\) (so \\( u = x^3,\\ v = (1-y)^3 \\)) is differentiable.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "differentiable set"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Partials.", workingLatex: "u_x = 3x^2,\\ u_y = 0,\\qquad v_x = 0,\\ v_y = -3(1-y)^2.", explanation: "Chain rule on (1-y)^3 gives a factor -1." },
        { stepNumber: 2, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 3x^2 = -3(1-y)^2 \\Rightarrow x^2 + (1-y)^2 = 0.", explanation: "Move everything to one side; a sum of squares." },
        { stepNumber: 3, description: "Solve the sum of squares.", workingLatex: "x = 0 \\text{ and } 1 - y = 0 \\Rightarrow x = 0,\\ y = 1.", explanation: "A sum of real squares vanishes only when each square is zero." },
        { stepNumber: 4, description: "Check the second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow 0 = 0. \\quad\\checkmark", explanation: "Holds everywhere, so the single point survives." },
      ],
      finalAnswer: "Differentiable only at \\( z = i \\) (\\(x=0,\\ y=1\\)); analytic nowhere.",
      canonicalAnswer: "{i}",
    },
  },
  {
    id: "cm1a-018",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( f(z) = \\dfrac{1}{z} \\), \\( z \\ne 0 \\), find \\( f'(z) \\) from first principles using the difference quotient.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["first principles", "reciprocal"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the quotient.", workingLatex: "Q(h) = \\frac{1}{h}\\left(\\frac{1}{z+h} - \\frac{1}{z}\\right).", explanation: "Difference quotient for 1/z." },
        { stepNumber: 2, description: "Combine the inner fractions.", workingLatex: "\\frac{1}{z+h} - \\frac{1}{z} = \\frac{z - (z+h)}{z(z+h)} = \\frac{-h}{z(z+h)}.", explanation: "Common denominator z(z+h)." },
        { stepNumber: 3, description: "Divide by h.", workingLatex: "Q(h) = \\frac{-h}{h\\,z(z+h)} = \\frac{-1}{z(z+h)}.", explanation: "Cancel h (nonzero in the limit)." },
        { stepNumber: 4, description: "Take the limit.", workingLatex: "\\lim_{h\\to 0}\\frac{-1}{z(z+h)} = -\\frac{1}{z^2}.", explanation: "Independent of the path of approach, so the derivative exists for z \\ne 0." },
      ],
      finalAnswer: "\\( f'(z) = -\\dfrac{1}{z^2} \\) for \\( z \\ne 0 \\).",
      canonicalAnswer: "-1/z^2",
    },
  },
  // --------- Challenge (12) ---------
  {
    id: "cm1a-019",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f(z) = \\dfrac{z^5}{|z|^4} \\) for \\( z \\ne 0 \\) and \\( f(0) = 0 \\). Show that \\( u \\) and \\( v \\) satisfy the Cauchy–Riemann equations at \\( z = 0 \\), yet \\( f \\) is not differentiable there.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["CR holds but not differentiable", "z^5/|z|^4", "counterexample"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rewrite f on a ray.", workingLatex: "z = re^{i\\theta}: \\quad f = \\frac{r^5 e^{5i\\theta}}{r^4} = r e^{5i\\theta}.", explanation: "Since |z|^4 = r^4 and z^5 = r^5 e^{5iθ}." },
        { stepNumber: 2, description: "Compute partials at 0 from the definition.", workingLatex: "u_x(0) = \\lim_{t\\to 0}\\frac{u(t,0)-0}{t}, \\quad \\theta=0:\\ f(t)= t,\\ u(t,0)=t.", explanation: "Along the positive real axis θ=0 so f = r = t, giving u = t, v = 0." },
        { stepNumber: 3, description: "Real-axis partials.", workingLatex: "u_x(0) = 1, \\qquad v_x(0) = 0.", explanation: "From u(t,0)=t, v(t,0)=0." },
        { stepNumber: 4, description: "Imaginary-axis partials.", workingLatex: "z = it,\\ \\theta=\\tfrac{\\pi}{2}:\\ f = t e^{5i\\pi/2} = t\\,i,\\ u(0,t)=0,\\ v(0,t)=t.", explanation: "e^{5iπ/2}=e^{iπ/2}=i, so f = it; hence u=0, v=t along the imaginary axis." },
        { stepNumber: 5, description: "y-partials and CR check.", workingLatex: "u_y(0)=0,\\ v_y(0)=1 \\Rightarrow u_x=v_y=1,\\ u_y=-v_x=0. \\checkmark", explanation: "So the Cauchy–Riemann equations hold at the origin." },
        { stepNumber: 6, description: "Test the full limit along a general ray.", workingLatex: "\\frac{f(z)-0}{z} = \\frac{r e^{5i\\theta}}{re^{i\\theta}} = e^{4i\\theta}.", explanation: "The difference quotient depends on θ." },
        { stepNumber: 7, description: "Conclude non-differentiability.", workingLatex: "e^{4i\\theta} \\text{ varies with } \\theta \\ (\\theta=0\\Rightarrow 1,\\ \\theta=\\tfrac{\\pi}{4}\\Rightarrow i).", explanation: "Direction-dependent limit, so f'(0) does not exist despite CR holding: CR is necessary but not sufficient without continuity of the partials." },
      ],
      finalAnswer: "The CR equations hold at \\( 0 \\) (\\(u_x=v_y=1,\\ u_y=-v_x=0\\)), but the difference quotient \\( e^{4i\\theta} \\) depends on the direction \\( \\theta \\), so \\( f \\) is not differentiable at \\( 0 \\).",
    },
  },
  {
    id: "cm1a-020",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f \\) is analytic on a domain \\( D \\) and \\( |f(z)| \\) is constant on \\( D \\). Use the Cauchy–Riemann equations to show that \\( f \\) is itself constant.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "constant modulus implies constant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set up.", workingLatex: "|f|^2 = u^2 + v^2 = c \\ (\\text{const}).", explanation: "If |f| is constant so is its square. If c = 0 then f ≡ 0; assume c > 0." },
        { stepNumber: 2, description: "Differentiate in x and y.", workingLatex: "u u_x + v v_x = 0, \\qquad u u_y + v v_y = 0.", explanation: "Differentiate u^2 + v^2 = c with respect to each variable." },
        { stepNumber: 3, description: "Apply CR to eliminate y-derivatives.", workingLatex: "u_y = -v_x,\\ v_y = u_x \\Rightarrow -u v_x + v u_x = 0.", explanation: "Substitute the CR equations into the second relation." },
        { stepNumber: 4, description: "Write as a linear system.", workingLatex: "\\begin{cases} u\\,u_x + v\\,v_x = 0 \\\\ v\\,u_x - u\\,v_x = 0 \\end{cases}", explanation: "Two homogeneous equations in the unknowns u_x and v_x." },
        { stepNumber: 5, description: "Examine the determinant.", workingLatex: "\\det = \\begin{vmatrix} u & v \\\\ v & -u \\end{vmatrix} = -(u^2+v^2) = -c \\ne 0.", explanation: "Since c > 0 the coefficient matrix is invertible." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "u_x = v_x = 0 \\Rightarrow u_y = v_y = 0 \\Rightarrow f' = u_x + i v_x = 0.", explanation: "A function with zero derivative on a connected domain is constant." },
      ],
      finalAnswer: "If \\( c = 0 \\) then \\( f\\equiv 0 \\); if \\( c>0 \\) the determinant \\( -c \\ne 0 \\) forces \\( u_x=v_x=0 \\), so \\( f'=0 \\) and \\( f \\) is constant on \\( D \\).",
    },
  },
  {
    id: "cm1a-021",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Given the smooth real functions \\( u, v \\), define \\( g(z,\\bar z) = u\\big(\\tfrac12(z+\\bar z),\\,-\\tfrac{i}{2}(z-\\bar z)\\big) + i\\,v\\big(\\tfrac12(z+\\bar z),\\,-\\tfrac{i}{2}(z-\\bar z)\\big) \\). Using \\( x = \\tfrac12(z+\\bar z),\\ y = -\\tfrac{i}{2}(z-\\bar z) \\) and the chain rule, show \\( \\dfrac{\\partial g}{\\partial \\bar z} = 0 \\) is equivalent to the CR equations.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["chain rule", "z zbar coordinates", "CR equivalence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the coordinates.", workingLatex: "\\frac{\\partial x}{\\partial \\bar z} = \\frac12, \\qquad \\frac{\\partial y}{\\partial \\bar z} = -\\frac{i}{2}\\cdot(-1) = \\frac{i}{2}.", explanation: "From x = (z+zbar)/2 and y = -i(z - zbar)/2, differentiate treating z, zbar as independent." },
        { stepNumber: 2, description: "Apply the chain rule to g.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z} = (u_x + i v_x)\\frac{\\partial x}{\\partial \\bar z} + (u_y + i v_y)\\frac{\\partial y}{\\partial \\bar z}.", explanation: "g = u + iv with u, v depending on (x,y); apply chain rule in zbar." },
        { stepNumber: 3, description: "Substitute the coordinate derivatives.", workingLatex: "= \\frac12(u_x + i v_x) + \\frac{i}{2}(u_y + i v_y).", explanation: "Insert ∂x/∂zbar = 1/2 and ∂y/∂zbar = i/2." },
        { stepNumber: 4, description: "Expand the second bracket.", workingLatex: "= \\frac12\\big(u_x + i v_x + i u_y - v_y\\big).", explanation: "Use i·i v_y = -v_y." },
        { stepNumber: 5, description: "Group parts.", workingLatex: "= \\frac12\\big[(u_x - v_y) + i(v_x + u_y)\\big].", explanation: "Collect real and imaginary pieces." },
        { stepNumber: 6, description: "Set to zero and conclude.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=0 \\iff u_x = v_y,\\ u_y = -v_x.", explanation: "So g depends on z alone iff the CR equations hold; any genuine zbar-dependence introduces a nonzero ∂g/∂zbar and hence non-differentiability." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial g}{\\partial\\bar z} = \\tfrac12[(u_x - v_y) + i(v_x + u_y)] \\), which vanishes iff \\( u_x=v_y,\\ u_y=-v_x \\); a \\( \\bar z \\)-dependence makes this nonzero, giving non-differentiability.",
    },
  },
  {
    id: "cm1a-022",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Determine where \\( f(z) = z\\,\\operatorname{Im} z \\) is differentiable. Write \\( z = x + iy \\), find \\( u, v \\), and apply the Cauchy–Riemann equations.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "z Im z", "differentiable at a point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand f.", workingLatex: "f = (x+iy)\\,y = xy + i y^2, \\qquad u = xy,\\ v = y^2.", explanation: "Im z = y, multiply through by z." },
        { stepNumber: 2, description: "Partials.", workingLatex: "u_x = y,\\ u_y = x,\\qquad v_x = 0,\\ v_y = 2y.", explanation: "" },
        { stepNumber: 3, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow y = 2y \\Rightarrow y = 0.", explanation: "Forces y = 0." },
        { stepNumber: 4, description: "Second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow x = 0.", explanation: "Forces x = 0." },
        { stepNumber: 5, description: "Intersect the conditions.", workingLatex: "x = 0 \\text{ and } y = 0 \\Rightarrow z = 0.", explanation: "Both must hold, leaving only the origin." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\text{differentiable at } 0 \\text{ only; analytic nowhere.}", explanation: "The partials are continuous, so CR at the single point z=0 gives differentiability there but no open neighbourhood." },
      ],
      finalAnswer: "Differentiable only at \\( z = 0 \\); analytic nowhere.",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1a-023",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For an analytic \\( f \\) verify that the two expressions for the derivative agree: show \\( f'(z) = u_x + i v_x = v_y - i u_y \\). Then evaluate both for \\( f(z) = \\sin z \\), where \\( u = \\sin x\\cosh y,\\ v = \\cos x\\sinh y \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex derivative", "two forms", "sin z"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State both derivative forms.", workingLatex: "f'(z) = u_x + i v_x \\quad\\text{and}\\quad f'(z) = v_y - i u_y.", explanation: "The first is the real-axis limit; the second the imaginary-axis limit. CR makes them equal." },
        { stepNumber: 2, description: "Differentiate u.", workingLatex: "u_x = \\cos x\\cosh y, \\qquad u_y = \\sin x\\sinh y.", explanation: "" },
        { stepNumber: 3, description: "Differentiate v.", workingLatex: "v_x = -\\sin x\\sinh y, \\qquad v_y = \\cos x\\cosh y.", explanation: "" },
        { stepNumber: 4, description: "First form.", workingLatex: "u_x + i v_x = \\cos x\\cosh y - i\\sin x\\sinh y.", explanation: "Substitute the x-partials." },
        { stepNumber: 5, description: "Second form.", workingLatex: "v_y - i u_y = \\cos x\\cosh y - i\\sin x\\sinh y.", explanation: "Identical, confirming agreement (CR holds since u_x=v_y, u_y=-v_x)." },
        { stepNumber: 6, description: "Recognise the z-form.", workingLatex: "\\cos x\\cosh y - i\\sin x\\sinh y = \\cos(x+iy) = \\cos z.", explanation: "Matches the known derivative (sin z)' = cos z." },
      ],
      finalAnswer: "Both forms give \\( f'(z) = \\cos x\\cosh y - i\\sin x\\sinh y = \\cos z \\).",
      canonicalAnswer: "cos z",
    },
  },
  {
    id: "cm1a-024",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find the set on which \\( f(z) = e^{x}(\\cos y + i\\,\\lambda\\sin y) \\) is differentiable, in terms of the real parameter \\( \\lambda \\). For which \\( \\lambda \\) is \\( f \\) entire?",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "parameter", "entire condition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u, v.", workingLatex: "u = e^{x}\\cos y, \\qquad v = \\lambda e^{x}\\sin y.", explanation: "" },
        { stepNumber: 2, description: "Partials.", workingLatex: "u_x = e^{x}\\cos y,\\ u_y = -e^{x}\\sin y,\\quad v_x = \\lambda e^{x}\\sin y,\\ v_y = \\lambda e^{x}\\cos y.", explanation: "" },
        { stepNumber: 3, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow e^{x}\\cos y = \\lambda e^{x}\\cos y \\Rightarrow (1-\\lambda)\\cos y = 0.", explanation: "Divide by e^x > 0." },
        { stepNumber: 4, description: "Second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow -e^{x}\\sin y = -\\lambda e^{x}\\sin y \\Rightarrow (1-\\lambda)\\sin y = 0.", explanation: "" },
        { stepNumber: 5, description: "Case λ = 1.", workingLatex: "\\lambda = 1: \\text{ both hold for all } (x,y).", explanation: "Then f = e^x(cos y + i sin y) = e^z is entire." },
        { stepNumber: 6, description: "Case λ ≠ 1.", workingLatex: "\\lambda \\ne 1: \\cos y = 0 \\text{ and } \\sin y = 0 \\text{ simultaneously — impossible.}", explanation: "Since cos y and sin y never vanish together, CR holds at no point; f is differentiable nowhere." },
      ],
      finalAnswer: "If \\( \\lambda = 1 \\), \\( f = e^{z} \\) is entire (differentiable everywhere); if \\( \\lambda \\ne 1 \\), \\( f \\) is differentiable nowhere.",
      canonicalAnswer: "lambda=1: entire; lambda != 1: nowhere differentiable",
    },
  },
  {
    id: "cm1a-025",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Given that \\( v(x,y) = e^{x}\\sin y \\) is the imaginary part of an analytic function, reconstruct \\( u(x,y) \\) (up to a real constant) using the Cauchy–Riemann equations and identify \\( f(z) \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "reconstruct u from v", "e^z"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use u_x = v_y.", workingLatex: "v_y = e^{x}\\cos y \\Rightarrow u_x = e^{x}\\cos y.", explanation: "The first CR equation gives the x-derivative of u." },
        { stepNumber: 2, description: "Integrate in x.", workingLatex: "u = \\int e^{x}\\cos y\\,dx = e^{x}\\cos y + h(y).", explanation: "Integrate treating y as constant; h(y) is unknown." },
        { stepNumber: 3, description: "Use u_y = -v_x.", workingLatex: "v_x = e^{x}\\sin y \\Rightarrow u_y = -e^{x}\\sin y.", explanation: "The second CR equation gives the y-derivative of u." },
        { stepNumber: 4, description: "Differentiate the trial u in y.", workingLatex: "u_y = -e^{x}\\sin y + h'(y) \\overset{!}{=} -e^{x}\\sin y \\Rightarrow h'(y) = 0.", explanation: "Match; h is constant." },
        { stepNumber: 5, description: "Assemble u.", workingLatex: "u = e^{x}\\cos y + C.", explanation: "" },
        { stepNumber: 6, description: "Identify f.", workingLatex: "f = u + iv = e^{x}(\\cos y + i\\sin y) + C = e^{z} + C.", explanation: "Using Euler's formula, the analytic function is e^z up to an additive real constant." },
      ],
      finalAnswer: "\\( u(x,y) = e^{x}\\cos y + C \\) and \\( f(z) = e^{z} + C \\) for a real constant \\( C \\).",
      canonicalAnswer: "u=e^x cos y + C; f=e^z+C",
    },
  },
  {
    id: "cm1a-026",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Investigate where \\( f(z) = |z|^2 \\,\\bar z \\) is differentiable. Write it in terms of \\( x, y \\) and apply the Cauchy–Riemann equations.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "|z|^2 zbar", "differentiable at a point"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand.", workingLatex: "|z|^2\\bar z = (x^2+y^2)(x - iy).", explanation: "|z|^2 = x^2+y^2 and zbar = x - iy." },
        { stepNumber: 2, description: "Separate parts.", workingLatex: "u = (x^2+y^2)x = x^3 + xy^2, \\qquad v = -(x^2+y^2)y = -x^2 y - y^3.", explanation: "" },
        { stepNumber: 3, description: "Partials of u.", workingLatex: "u_x = 3x^2 + y^2, \\qquad u_y = 2xy.", explanation: "" },
        { stepNumber: 4, description: "Partials of v.", workingLatex: "v_x = -2xy, \\qquad v_y = -x^2 - 3y^2.", explanation: "" },
        { stepNumber: 5, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 3x^2 + y^2 = -x^2 - 3y^2 \\Rightarrow 4x^2 + 4y^2 = 0.", explanation: "Collect terms: a sum of squares equals zero." },
        { stepNumber: 6, description: "Solve.", workingLatex: "x^2 + y^2 = 0 \\Rightarrow x = y = 0.", explanation: "Only the origin." },
        { stepNumber: 7, description: "Check second CR and conclude.", workingLatex: "u_y = 2xy = 0 = -v_x \\text{ at } 0. \\checkmark", explanation: "CR holds only at z=0, so f is differentiable there alone and analytic nowhere." },
      ],
      finalAnswer: "Differentiable only at \\( z = 0 \\); analytic nowhere.",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1a-027",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that if \\( f = u + iv \\) is analytic on a domain and \\( v = u^2 \\) there, then \\( f \\) is constant. Use the Cauchy–Riemann equations.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "relation between u and v", "constant"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the relation.", workingLatex: "v = u^2 \\Rightarrow v_x = 2u\\,u_x, \\qquad v_y = 2u\\,u_y.", explanation: "Chain rule on v = u^2." },
        { stepNumber: 2, description: "Apply CR.", workingLatex: "u_x = v_y = 2u\\,u_y, \\qquad u_y = -v_x = -2u\\,u_x.", explanation: "Substitute u_x = v_y and u_y = -v_x." },
        { stepNumber: 3, description: "Substitute one into the other.", workingLatex: "u_x = 2u\\,u_y = 2u(-2u\\,u_x) = -4u^2 u_x.", explanation: "Replace u_y using the second relation." },
        { stepNumber: 4, description: "Factor.", workingLatex: "u_x(1 + 4u^2) = 0.", explanation: "Move all to one side and factor out u_x." },
        { stepNumber: 5, description: "Deduce u_x = 0.", workingLatex: "1 + 4u^2 \\ge 1 > 0 \\Rightarrow u_x = 0.", explanation: "The bracket is strictly positive (u real), so u_x must vanish." },
        { stepNumber: 6, description: "Deduce u_y = 0.", workingLatex: "u_y = -2u\\,u_x = 0.", explanation: "From the CR-derived relation with u_x = 0." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "f' = u_x + i v_x = 0 + i(2u\\,u_x) = 0.", explanation: "All partials of u vanish, hence those of v, so f' = 0 and f is constant on the connected domain." },
      ],
      finalAnswer: "The CR equations force \\( u_x(1+4u^2)=0 \\Rightarrow u_x=u_y=0 \\), so \\( f'=0 \\) and \\( f \\) is constant.",
    },
  },
  {
    id: "cm1a-028",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find the set of points where \\( f(z) = \\bar z^{\\,2} \\) is differentiable, both from first principles and via the Cauchy–Riemann equations.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "conjugate squared", "first principles"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand into u, v.", workingLatex: "\\bar z^2 = (x - iy)^2 = x^2 - y^2 - 2ixy, \\quad u = x^2 - y^2,\\ v = -2xy.", explanation: "Square the conjugate." },
        { stepNumber: 2, description: "Partials.", workingLatex: "u_x = 2x,\\ u_y = -2y,\\quad v_x = -2y,\\ v_y = -2x.", explanation: "" },
        { stepNumber: 3, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 2x = -2x \\Rightarrow x = 0.", explanation: "" },
        { stepNumber: 4, description: "Second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow -2y = 2y \\Rightarrow y = 0.", explanation: "" },
        { stepNumber: 5, description: "CR conclusion.", workingLatex: "x = y = 0 \\Rightarrow z = 0.", explanation: "Only the origin satisfies both." },
        { stepNumber: 6, description: "Confirm from first principles.", workingLatex: "\\frac{\\overline{(z+h)}^2 - \\bar z^2}{h} = \\frac{2\\bar z\\,\\bar h + \\bar h^2}{h} = 2\\bar z\\frac{\\bar h}{h} + \\bar h\\frac{\\bar h}{h}.", explanation: "Expand; hbar/h is direction-dependent (±1 on the axes), but the term with it vanishes as h→0 only when its coefficient 2zbar = 0, i.e. z = 0." },
      ],
      finalAnswer: "Differentiable only at \\( z = 0 \\) (where \\( f'(0)=0 \\)); analytic nowhere.",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1a-029",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Determine where \\( f(z) = x^2 + 2ixy - y^2 + \\bar z \\) is differentiable. (Hint: simplify first, then apply CR.)",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "analytic plus conjugate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise the analytic part.", workingLatex: "x^2 + 2ixy - y^2 = (x+iy)^2 = z^2.", explanation: "The first three terms are exactly z^2." },
        { stepNumber: 2, description: "Rewrite f.", workingLatex: "f(z) = z^2 + \\bar z, \\qquad u = x^2 - y^2 + x,\\ v = 2xy - y.", explanation: "zbar = x - iy, so add x to u and -y to v." },
        { stepNumber: 3, description: "Partials.", workingLatex: "u_x = 2x + 1,\\ u_y = -2y,\\quad v_x = 2y,\\ v_y = 2x - 1.", explanation: "" },
        { stepNumber: 4, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 2x + 1 = 2x - 1 \\Rightarrow 1 = -1.", explanation: "A contradiction — never satisfied." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\text{No } (x,y) \\text{ solves the CR equations.}", explanation: "The non-analytic zbar term shifts u_x by +1 and v_y by -1, breaking u_x = v_y everywhere; f is differentiable nowhere." },
      ],
      finalAnswer: "\\( \\varnothing \\) — \\( f(z) = z^2 + \\bar z \\) is differentiable nowhere (the \\( \\bar z \\) term obstructs CR).",
      canonicalAnswer: "differentiable nowhere",
    },
  },
  {
    id: "cm1a-030",
    topicRef: "cm1a",
    topicTitle: "Differentiability from first principles & the CR equations",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "For real constants \\( a, b \\), find all \\( (a,b) \\) and all points such that \\( f(z) = (x^2 + a y^2) + i(b\\,xy) \\) is differentiable somewhere, and state when \\( f \\) is entire.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy–Riemann equations", "parameter matching", "entire condition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u, v and partials.", workingLatex: "u = x^2 + ay^2,\\ v = bxy: \\quad u_x = 2x,\\ u_y = 2ay,\\ v_x = by,\\ v_y = bx.", explanation: "" },
        { stepNumber: 2, description: "First CR equation.", workingLatex: "u_x = v_y \\Rightarrow 2x = bx \\Rightarrow (b-2)x = 0.", explanation: "Holds for all x iff b = 2; otherwise only x = 0." },
        { stepNumber: 3, description: "Second CR equation.", workingLatex: "u_y = -v_x \\Rightarrow 2ay = -by \\Rightarrow (2a + b)y = 0.", explanation: "Holds for all y iff 2a + b = 0; otherwise only y = 0." },
        { stepNumber: 4, description: "Entire case.", workingLatex: "b = 2 \\text{ and } 2a + b = 0 \\Rightarrow a = -1,\\ b = 2.", explanation: "Then both CR equations hold for all (x,y)." },
        { stepNumber: 5, description: "Identify f when entire.", workingLatex: "a=-1,b=2:\\ f = x^2 - y^2 + 2ixy = z^2.", explanation: "So the only entire member of the family is f(z) = z^2." },
        { stepNumber: 6, description: "Otherwise: locate isolated points.", workingLatex: "\\text{If } b\\ne 2 \\text{ or } 2a+b\\ne 0, \\text{ CR forces } x=0 \\text{ and/or } y=0.", explanation: "When exactly one parameter condition fails, CR holds on a single axis through 0 (no open set)." },
        { stepNumber: 7, description: "Generic point.", workingLatex: "b\\ne 2 \\text{ and } 2a+b\\ne 0 \\Rightarrow x=0,\\ y=0 \\Rightarrow z=0 \\text{ only.}", explanation: "In the fully generic case f is differentiable solely at the origin and analytic nowhere." },
      ],
      finalAnswer: "Entire iff \\( a=-1,\\ b=2 \\) (then \\( f=z^2 \\)). Otherwise \\( f \\) is differentiable only on \\( \\{x=0\\} \\) (if \\( b\\ne2 \\)) intersected with \\( \\{y=0\\} \\) (if \\( 2a+b\\ne0 \\)) — generically just \\( z=0 \\) — and analytic nowhere.",
      canonicalAnswer: "entire iff a=-1,b=2 (f=z^2); else differentiable only at z=0 generically",
    },
  },
];
