import { Question } from "@/lib/types";

/**
 * Complex Methods — cm1b
 * CR in polar form; analyticity of elementary functions
 * Topic group: Analyticity & the Cauchy–Riemann Equations
 *
 * 30 fully-worked questions seeded from Cambridge Part IB Complex Methods,
 * Example Sheet 1, Q1(i) (the sech z part: where is sech z differentiable /
 * analytic, and where are its singularities), with the seed varied across the
 * polar-form Cauchy–Riemann equations u_r = v_θ/r, v_r = −u_θ/r and the
 * analyticity / singularity structure of the standard transcendental functions.
 *
 * Split: 6 Foundation / 12 Standard / 12 Challenge.
 *
 * Conventions: worked-solution fractions use big \frac; stems use \dfrac.
 * Singularities of sech z sit at z = iπ(n+1/2) (simple poles), of tan z at
 * z = π(n+1/2), of 1/(e^z−1) at z = 2πi n. Every "entire/analytic" claim was
 * checked by verifying the CR equations, and every pole located/typed from the
 * zeros of the denominator.
 */
export const questions: Question[] = [
  // --------- Foundation (6) ---------
  {
    id: "cm1b-001",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "State the Cauchy–Riemann equations in polar form for \\( f = u(r,\\theta) + i\\,v(r,\\theta) \\), and give the formula for \\( f'(z) \\) in terms of \\( u_r \\) and \\( v_r \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["polar Cauchy–Riemann", "complex derivative"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the polar CR equations.", workingLatex: "u_r = \\frac{1}{r}\\,v_\\theta, \\qquad v_r = -\\frac{1}{r}\\,u_\\theta.", explanation: "These come from transforming the Cartesian equations under x=r\\cos\\theta, y=r\\sin\\theta; the 1/r factors are the Jacobian of the polar map." },
        { stepNumber: 2, description: "Write the derivative.", workingLatex: "f'(z) = e^{-i\\theta}\\left(u_r + i\\,v_r\\right).", explanation: "Differentiating along the radial direction dz = e^{i\\theta}\\,dr gives this compact form, valid wherever the polar CR equations hold." },
      ],
      finalAnswer: "\\( u_r = \\dfrac{1}{r}v_\\theta,\\ v_r = -\\dfrac{1}{r}u_\\theta \\); and \\( f'(z) = e^{-i\\theta}(u_r + i\\,v_r) \\).",
    },
  },
  {
    id: "cm1b-002",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( f(z) = z^2 \\) written in polar form, identify \\( u(r,\\theta) \\) and \\( v(r,\\theta) \\), then compute \\( u_r \\) and \\( \\dfrac{1}{r}v_\\theta \\) to confirm the first polar CR equation holds.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["polar Cauchy–Riemann", "power function"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand in polar form.", workingLatex: "z^2 = r^2 e^{2i\\theta} = r^2\\cos 2\\theta + i\\,r^2\\sin 2\\theta.", explanation: "Using z = re^{i\\theta} and de Moivre, the modulus squares and the argument doubles." },
        { stepNumber: 2, description: "Read off u and v.", workingLatex: "u = r^2\\cos 2\\theta, \\qquad v = r^2\\sin 2\\theta.", explanation: "Real and imaginary parts are read directly from the expansion." },
        { stepNumber: 3, description: "Compute the two sides.", workingLatex: "u_r = 2r\\cos 2\\theta, \\qquad \\frac{1}{r}v_\\theta = \\frac{1}{r}\\,(2r^2\\cos 2\\theta) = 2r\\cos 2\\theta.", explanation: "Differentiating u in r and v in θ and dividing by r gives the same expression, so u_r = v_θ/r." },
      ],
      finalAnswer: "\\( u = r^2\\cos 2\\theta,\\ v = r^2\\sin 2\\theta \\); both equal \\( u_r = \\dfrac{1}{r}v_\\theta = 2r\\cos 2\\theta \\).",
    },
  },
  {
    id: "cm1b-003",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "set",
    questionText: "Find all points where \\( \\cosh z = 0 \\), and hence state where \\( \\operatorname{sech} z = \\dfrac{1}{\\cosh z} \\) fails to be analytic.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["sech z", "singularities"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Relate cosh to cos.", workingLatex: "\\cosh z = \\cos(iz).", explanation: "The standard identity converts the hyperbolic zero problem into a trigonometric one." },
        { stepNumber: 2, description: "Solve cos(iz)=0.", workingLatex: "\\cos(iz) = 0 \\;\\Rightarrow\\; iz = \\frac{\\pi}{2} + n\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "The cosine vanishes exactly at the odd multiples of π/2." },
        { stepNumber: 3, description: "Solve for z.", workingLatex: "z = \\frac{1}{i}\\left(\\frac{\\pi}{2}+n\\pi\\right) = -i\\Big(n+\\tfrac12\\Big)\\pi = i\\Big(n+\\tfrac12\\Big)\\pi.", explanation: "Multiplying by 1/i = −i, and noting n ranges over all integers so the sign of n is immaterial." },
      ],
      finalAnswer: "\\( \\cosh z = 0 \\) at \\( z = i\\big(n+\\tfrac12\\big)\\pi \\); sech \\( z \\) fails to be analytic exactly there.",
      canonicalAnswer: "{ i*(n+1/2)*pi : n in Z }",
    },
  },
  {
    id: "cm1b-004",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Show, using the polar CR equations, that the principal branch of \\( \\log z = \\ln r + i\\theta \\) (with \\( -\\pi < \\theta < \\pi \\)) is analytic, and find \\( \\dfrac{d}{dz}\\log z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["logarithm", "polar Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u and v.", workingLatex: "u = \\ln r, \\qquad v = \\theta.", explanation: "The log is naturally in polar form: real part is ln of the modulus, imaginary part is the argument." },
        { stepNumber: 2, description: "Check the CR equations.", workingLatex: "u_r = \\frac{1}{r},\\ \\frac{1}{r}v_\\theta = \\frac{1}{r}; \\qquad v_r = 0,\\ -\\frac{1}{r}u_\\theta = 0.", explanation: "Both polar CR equations hold for all r>0, so log z is analytic off the branch cut and origin." },
        { stepNumber: 3, description: "Form the derivative.", workingLatex: "f'(z) = e^{-i\\theta}(u_r + i v_r) = e^{-i\\theta}\\cdot\\frac{1}{r} = \\frac{1}{re^{i\\theta}} = \\frac{1}{z}.", explanation: "Substituting into f'(z)=e^{-iθ}(u_r+iv_r) recovers the familiar 1/z." },
      ],
      finalAnswer: "\\( \\log z \\) is analytic for \\( r>0,\\ -\\pi<\\theta<\\pi \\), with \\( \\dfrac{d}{dz}\\log z = \\dfrac{1}{z} \\).",
    },
  },
  {
    id: "cm1b-005",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "set",
    questionText: "Determine where \\( f(z) = \\operatorname{Im} z \\) is differentiable. (Write \\( z = x+iy \\) so \\( u = y,\\ v = 0 \\).)",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Im z", "Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u and v.", workingLatex: "u = y, \\qquad v = 0.", explanation: "Im(z) is real-valued, so the imaginary part v is identically zero." },
        { stepNumber: 2, description: "Compute the partial derivatives.", workingLatex: "u_x = 0,\\ u_y = 1; \\qquad v_x = 0,\\ v_y = 0.", explanation: "Straightforward partials of u=y and v=0." },
        { stepNumber: 3, description: "Test the CR equations.", workingLatex: "u_x = v_y:\\ 0 = 0\\ \\checkmark; \\qquad u_y = -v_x:\\ 1 = 0\\ \\times.", explanation: "The second equation fails everywhere, so the CR equations hold nowhere." },
      ],
      finalAnswer: "\\( \\operatorname{Im} z \\) is differentiable nowhere (hence analytic nowhere).",
      canonicalAnswer: "nowhere",
    },
  },
  {
    id: "cm1b-006",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Foundation",
    answerType: "set",
    questionText: "Find all singularities of \\( \\tan z = \\dfrac{\\sin z}{\\cos z} \\) by locating the zeros of \\( \\cos z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["tan z", "singularities"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the denominator to zero.", workingLatex: "\\cos z = 0.", explanation: "tan z is the ratio of two entire functions, so its only singularities are the zeros of the denominator." },
        { stepNumber: 2, description: "Solve over the complex plane.", workingLatex: "\\cos z = 0 \\;\\Rightarrow\\; z = \\frac{\\pi}{2} + n\\pi = \\Big(n+\\tfrac12\\Big)\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "cos z has only real zeros (the usual ones), since |cos z| grows away from the real axis." },
        { stepNumber: 3, description: "Confirm sin z ≠ 0 there.", workingLatex: "\\sin\\!\\Big(\\big(n+\\tfrac12\\big)\\pi\\Big) = \\pm 1 \\neq 0.", explanation: "Numerator nonzero at each zero of the denominator, so these are genuine (simple) poles, not removable." },
      ],
      finalAnswer: "\\( \\tan z \\) has simple poles at \\( z = \\big(n+\\tfrac12\\big)\\pi,\\ n\\in\\mathbb{Z} \\), and is analytic elsewhere.",
      canonicalAnswer: "{ (n+1/2)*pi : n in Z }",
    },
  },

  // --------- Standard (12) ---------
  {
    id: "cm1b-007",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using the polar CR equations, verify that \\( f(z) = z^n \\) ( \\( n \\) a positive integer ) is analytic for all \\( z\\neq 0 \\), and show \\( f'(z) = n z^{n-1} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["power function", "polar Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write in polar form.", workingLatex: "z^n = r^n e^{in\\theta} = r^n\\cos n\\theta + i\\,r^n\\sin n\\theta.", explanation: "De Moivre gives the real and imaginary parts directly." },
        { stepNumber: 2, description: "Read off u and v.", workingLatex: "u = r^n\\cos n\\theta, \\qquad v = r^n\\sin n\\theta.", explanation: "Standard separation into real and imaginary parts." },
        { stepNumber: 3, description: "Check the first CR equation.", workingLatex: "u_r = n r^{n-1}\\cos n\\theta, \\qquad \\frac{1}{r}v_\\theta = \\frac{1}{r}\\,n r^n\\cos n\\theta = n r^{n-1}\\cos n\\theta.", explanation: "u_r = v_θ/r holds identically." },
        { stepNumber: 4, description: "Check the second CR equation.", workingLatex: "v_r = n r^{n-1}\\sin n\\theta, \\qquad -\\frac{1}{r}u_\\theta = -\\frac{1}{r}(-n r^n\\sin n\\theta) = n r^{n-1}\\sin n\\theta.", explanation: "v_r = −u_θ/r also holds, so z^n is analytic for all r>0." },
        { stepNumber: 5, description: "Compute the derivative.", workingLatex: "f'(z) = e^{-i\\theta}(u_r + i v_r) = e^{-i\\theta}\\,n r^{n-1}e^{in\\theta} = n r^{n-1}e^{i(n-1)\\theta} = n z^{n-1}.", explanation: "Assembling u_r + i v_r = n r^{n-1}e^{inθ} and multiplying by e^{−iθ} gives n z^{n−1}." },
      ],
      finalAnswer: "\\( z^n \\) is analytic for \\( z\\neq 0 \\) with \\( f'(z) = n z^{n-1} \\) (in fact entire for \\( n\\ge 0 \\)).",
    },
  },
  {
    id: "cm1b-008",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Verify that \\( f(z) = e^z \\) is entire by writing \\( u = e^x\\cos y,\\ v = e^x\\sin y \\) and checking the Cartesian CR equations, and confirm \\( f'(z) = e^z \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["exponential", "Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the partials of u.", workingLatex: "u_x = e^x\\cos y, \\qquad u_y = -e^x\\sin y.", explanation: "Differentiate u = e^x cos y in x and y." },
        { stepNumber: 2, description: "Compute the partials of v.", workingLatex: "v_x = e^x\\sin y, \\qquad v_y = e^x\\cos y.", explanation: "Differentiate v = e^x sin y in x and y." },
        { stepNumber: 3, description: "Check the CR equations.", workingLatex: "u_x = v_y:\\ e^x\\cos y = e^x\\cos y\\ \\checkmark; \\qquad u_y = -v_x:\\ -e^x\\sin y = -e^x\\sin y\\ \\checkmark.", explanation: "Both hold for all (x,y), and the partials are continuous, so e^z is differentiable everywhere — entire." },
        { stepNumber: 4, description: "Form the derivative.", workingLatex: "f'(z) = u_x + i v_x = e^x\\cos y + i\\,e^x\\sin y = e^x e^{iy} = e^z.", explanation: "Using f' = u_x + i v_x recovers e^z, as expected." },
      ],
      finalAnswer: "\\( e^z \\) is entire and \\( f'(z) = e^z \\).",
    },
  },
  {
    id: "cm1b-009",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Locate all singularities of \\( \\operatorname{sech} z = \\dfrac{1}{\\cosh z} \\) and classify their type.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sech z", "simple poles"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Find the zeros of cosh z.", workingLatex: "\\cosh z = 0 \\;\\Rightarrow\\; z = z_n := i\\Big(n+\\tfrac12\\Big)\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "Using cosh z = cos(iz), the zeros sit on the imaginary axis at odd multiples of iπ/2." },
        { stepNumber: 2, description: "Check the order of each zero.", workingLatex: "\\frac{d}{dz}\\cosh z = \\sinh z, \\qquad \\sinh z_n = \\sinh\\!\\Big(i\\big(n+\\tfrac12\\big)\\pi\\Big) = i\\sin\\!\\Big(\\big(n+\\tfrac12\\big)\\pi\\Big) = \\pm i \\neq 0.", explanation: "Since cosh vanishes but its derivative sinh does not, each zero of cosh is simple." },
        { stepNumber: 3, description: "Translate to sech z.", workingLatex: "\\operatorname{sech} z = \\frac{1}{\\cosh z}.", explanation: "A simple zero of the denominator (numerator nonzero) gives a simple pole of the reciprocal." },
        { stepNumber: 4, description: "Optionally compute a residue.", workingLatex: "\\operatorname{Res}_{z=z_n}\\operatorname{sech} z = \\frac{1}{\\sinh z_n} = \\frac{1}{\\pm i} = \\mp i = (-1)^{n+1} i.", explanation: "The residue at a simple pole is 1/(denominator)'; here it alternates in sign with n." },
      ],
      finalAnswer: "Simple poles at \\( z = i\\big(n+\\tfrac12\\big)\\pi,\\ n\\in\\mathbb{Z} \\); analytic elsewhere.",
      canonicalAnswer: "{ i*(n+1/2)*pi : n in Z }",
    },
  },
  {
    id: "cm1b-010",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find and classify all singularities of \\( f(z) = \\dfrac{1}{e^z - 1} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singularities", "exponential"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Set the denominator to zero.", workingLatex: "e^z - 1 = 0 \\;\\Rightarrow\\; e^z = 1.", explanation: "f is a ratio of entire functions, so singularities are exactly the zeros of e^z − 1." },
        { stepNumber: 2, description: "Solve e^z = 1.", workingLatex: "z = 2\\pi i\\,n, \\quad n\\in\\mathbb{Z}.", explanation: "e^z = 1 iff the real part is 0 and the imaginary part is a multiple of 2π." },
        { stepNumber: 3, description: "Check the order of each zero.", workingLatex: "\\frac{d}{dz}(e^z-1) = e^z, \\qquad e^{2\\pi i n} = 1 \\neq 0.", explanation: "The derivative is nonzero at each root, so e^z − 1 has simple zeros." },
        { stepNumber: 4, description: "Conclude and compute the residue.", workingLatex: "\\operatorname{Res}_{z=2\\pi i n} \\frac{1}{e^z-1} = \\frac{1}{e^{2\\pi i n}} = 1.", explanation: "Simple zero of the denominator gives a simple pole; the residue 1/(e^z)|_{z=2πin} = 1." },
      ],
      finalAnswer: "Simple poles at \\( z = 2\\pi i\\,n,\\ n\\in\\mathbb{Z} \\), each with residue \\( 1 \\); analytic elsewhere.",
      canonicalAnswer: "{ 2*pi*i*n : n in Z }",
    },
  },
  {
    id: "cm1b-011",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Determine where \\( f(z) = |z|^2 = x^2 + y^2 \\) is differentiable, using the Cauchy–Riemann equations.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["|z|^2", "Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u and v.", workingLatex: "u = x^2 + y^2, \\qquad v = 0.", explanation: "|z|^2 is real-valued, so its imaginary part vanishes identically." },
        { stepNumber: 2, description: "Compute the partials.", workingLatex: "u_x = 2x,\\ u_y = 2y; \\qquad v_x = 0,\\ v_y = 0.", explanation: "Direct differentiation." },
        { stepNumber: 3, description: "Apply the CR equations.", workingLatex: "u_x = v_y:\\ 2x = 0; \\qquad u_y = -v_x:\\ 2y = 0.", explanation: "Both require x=0 and y=0, so the CR equations hold only at the origin." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "z = 0 \\text{ only}; \\quad \\text{but no neighbourhood, so } |z|^2 \\text{ is nowhere analytic.}", explanation: "Differentiability at a single isolated point gives no analyticity, which requires differentiability on an open set." },
      ],
      finalAnswer: "Differentiable only at \\( z = 0 \\); analytic nowhere.",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1b-012",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Verify the polar CR equations for \\( f(z) = \\dfrac{1}{z} \\) ( \\( z\\neq 0 \\) ), and hence find \\( f'(z) \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["polar Cauchy–Riemann", "reciprocal"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write in polar form.", workingLatex: "\\frac{1}{z} = \\frac{1}{re^{i\\theta}} = r^{-1}e^{-i\\theta} = r^{-1}\\cos\\theta - i\\,r^{-1}\\sin\\theta.", explanation: "Invert the modulus and negate the argument, then take real and imaginary parts." },
        { stepNumber: 2, description: "Read off u and v.", workingLatex: "u = r^{-1}\\cos\\theta, \\qquad v = -r^{-1}\\sin\\theta.", explanation: "Separation into real and imaginary parts." },
        { stepNumber: 3, description: "Check the CR equations.", workingLatex: "u_r = -r^{-2}\\cos\\theta = \\frac{1}{r}v_\\theta; \\qquad v_r = r^{-2}\\sin\\theta = -\\frac{1}{r}u_\\theta.", explanation: "Here v_θ = −r^{-1}cosθ so v_θ/r = −r^{-2}cosθ = u_r, and u_θ = −r^{-1}sinθ so −u_θ/r = r^{-2}sinθ = v_r." },
        { stepNumber: 4, description: "Form the derivative.", workingLatex: "f'(z) = e^{-i\\theta}(u_r + i v_r) = e^{-i\\theta}(-r^{-2})(\\cos\\theta - i\\sin\\theta) = -r^{-2}e^{-2i\\theta} = -\\frac{1}{z^2}.", explanation: "u_r + i v_r = −r^{-2}e^{−iθ}; multiplying by e^{−iθ} gives −r^{-2}e^{−2iθ} = −1/z^2." },
      ],
      finalAnswer: "Polar CR hold for \\( z\\neq 0 \\); \\( f'(z) = -\\dfrac{1}{z^2} \\).",
    },
  },
  {
    id: "cm1b-013",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find all singularities of \\( \\cot z = \\dfrac{\\cos z}{\\sin z} \\) and state their type.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cot z", "simple poles"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Zero the denominator.", workingLatex: "\\sin z = 0 \\;\\Rightarrow\\; z = n\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "sin z has only the real zeros nπ; it never vanishes off the real axis." },
        { stepNumber: 2, description: "Check the order.", workingLatex: "\\frac{d}{dz}\\sin z = \\cos z, \\qquad \\cos(n\\pi) = (-1)^n \\neq 0.", explanation: "The derivative cos z is nonzero at each nπ, so the zeros of sin z are simple." },
        { stepNumber: 3, description: "Check the numerator there.", workingLatex: "\\cos(n\\pi) = (-1)^n \\neq 0.", explanation: "Numerator nonzero, so each is a genuine simple pole (residue cos(nπ)/cos(nπ) = 1)." },
      ],
      finalAnswer: "Simple poles at \\( z = n\\pi,\\ n\\in\\mathbb{Z} \\), each with residue \\( 1 \\); analytic elsewhere.",
      canonicalAnswer: "{ n*pi : n in Z }",
    },
  },
  {
    id: "cm1b-014",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that \\( f(z) = \\sin z \\) is entire by writing \\( u = \\sin x\\cosh y,\\ v = \\cos x\\sinh y \\) and verifying the Cauchy–Riemann equations.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sine", "Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Justify the real/imaginary split.", workingLatex: "\\sin z = \\sin(x+iy) = \\sin x\\cos(iy) + \\cos x\\sin(iy) = \\sin x\\cosh y + i\\cos x\\sinh y.", explanation: "Using the angle-sum formula and cos(iy)=cosh y, sin(iy)=i\\sinh y." },
        { stepNumber: 2, description: "Compute the partials of u.", workingLatex: "u_x = \\cos x\\cosh y, \\qquad u_y = \\sin x\\sinh y.", explanation: "Differentiate u = sin x cosh y." },
        { stepNumber: 3, description: "Compute the partials of v.", workingLatex: "v_x = -\\sin x\\sinh y, \\qquad v_y = \\cos x\\cosh y.", explanation: "Differentiate v = cos x sinh y." },
        { stepNumber: 4, description: "Check the CR equations.", workingLatex: "u_x = v_y:\\ \\cos x\\cosh y = \\cos x\\cosh y\\ \\checkmark; \\qquad u_y = -v_x:\\ \\sin x\\sinh y = \\sin x\\sinh y\\ \\checkmark.", explanation: "Both hold everywhere with continuous partials, so sin z is entire." },
        { stepNumber: 5, description: "State the derivative.", workingLatex: "f'(z) = u_x + i v_x = \\cos x\\cosh y - i\\sin x\\sinh y = \\cos z.", explanation: "This assembles to cos z, confirming the standard derivative." },
      ],
      finalAnswer: "\\( \\sin z \\) is entire with \\( f'(z) = \\cos z \\).",
    },
  },
  {
    id: "cm1b-015",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Find all singularities of \\( f(z) = \\dfrac{1}{\\sin z} = \\operatorname{cosec} z \\), classify them, and give the residue at \\( z = 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["cosec z", "residue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Zero the denominator.", workingLatex: "\\sin z = 0 \\;\\Rightarrow\\; z = n\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "Only real zeros nπ, since |\\sin z| grows off the real axis." },
        { stepNumber: 2, description: "Check the order.", workingLatex: "\\cos(n\\pi) = (-1)^n \\neq 0 \\;\\Rightarrow\\; \\text{simple zeros of } \\sin z.", explanation: "Nonzero derivative means simple zeros, hence simple poles of cosec z." },
        { stepNumber: 3, description: "Compute the residue at z=0.", workingLatex: "\\operatorname{Res}_{z=0}\\frac{1}{\\sin z} = \\frac{1}{\\cos 0} = 1.", explanation: "At a simple pole the residue is 1/(\\sin z)' = 1/cos z evaluated at the pole." },
      ],
      finalAnswer: "Simple poles at \\( z = n\\pi \\); residue at \\( z=0 \\) is \\( 1 \\).",
      canonicalAnswer: "{ n*pi : n in Z }",
    },
  },
  {
    id: "cm1b-016",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using the polar CR equations, show that the principal branch \\( f(z) = z^{1/2} = r^{1/2}e^{i\\theta/2} \\) ( \\( -\\pi<\\theta<\\pi \\) ) is analytic, and find \\( f'(z) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["square-root branch", "polar Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate into u and v.", workingLatex: "u = r^{1/2}\\cos\\tfrac{\\theta}{2}, \\qquad v = r^{1/2}\\sin\\tfrac{\\theta}{2}.", explanation: "The half-power halves the argument and square-roots the modulus." },
        { stepNumber: 2, description: "Check the first CR equation.", workingLatex: "u_r = \\tfrac12 r^{-1/2}\\cos\\tfrac{\\theta}{2}, \\qquad \\frac{1}{r}v_\\theta = \\frac{1}{r}\\cdot \\tfrac12 r^{1/2}\\cos\\tfrac{\\theta}{2} = \\tfrac12 r^{-1/2}\\cos\\tfrac{\\theta}{2}.", explanation: "u_r = v_θ/r holds for all r>0." },
        { stepNumber: 3, description: "Check the second CR equation.", workingLatex: "v_r = \\tfrac12 r^{-1/2}\\sin\\tfrac{\\theta}{2}, \\qquad -\\frac{1}{r}u_\\theta = -\\frac{1}{r}\\big(-\\tfrac12 r^{1/2}\\sin\\tfrac{\\theta}{2}\\big) = \\tfrac12 r^{-1/2}\\sin\\tfrac{\\theta}{2}.", explanation: "v_r = −u_θ/r also holds, so the branch is analytic on the cut plane." },
        { stepNumber: 4, description: "Form the derivative.", workingLatex: "f'(z) = e^{-i\\theta}(u_r + i v_r) = e^{-i\\theta}\\cdot \\tfrac12 r^{-1/2}e^{i\\theta/2} = \\tfrac12 r^{-1/2}e^{-i\\theta/2} = \\frac{1}{2z^{1/2}}.", explanation: "u_r + i v_r = ½ r^{-1/2}e^{iθ/2}; the e^{−iθ} factor leaves ½ r^{-1/2}e^{−iθ/2} = 1/(2 z^{1/2})." },
      ],
      finalAnswer: "Analytic on \\( -\\pi<\\theta<\\pi,\\ r>0 \\); \\( f'(z) = \\dfrac{1}{2z^{1/2}} \\).",
    },
  },
  {
    id: "cm1b-017",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "For \\( f(z) = \\dfrac{1}{\\cosh z + 1} \\), find all singularities and identify the order of the pole at \\( z = i\\pi \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singularities", "double pole"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Zero the denominator.", workingLatex: "\\cosh z + 1 = 0 \\;\\Rightarrow\\; \\cosh z = -1.", explanation: "Singularities of the reciprocal are the zeros of cosh z + 1." },
        { stepNumber: 2, description: "Solve cosh z = −1.", workingLatex: "\\cos(iz) = -1 \\;\\Rightarrow\\; iz = \\pi + 2\\pi n \\;\\Rightarrow\\; z = i\\pi(2n+1), \\quad n\\in\\mathbb{Z}.", explanation: "cosh z = cos(iz), and cos = −1 at odd multiples of π." },
        { stepNumber: 3, description: "Test the order at z = iπ.", workingLatex: "\\frac{d}{dz}(\\cosh z + 1) = \\sinh z, \\qquad \\sinh(i\\pi) = i\\sin\\pi = 0.", explanation: "The first derivative vanishes, so the zero is at least double — the pole is not simple." },
        { stepNumber: 4, description: "Confirm it is exactly order 2.", workingLatex: "\\frac{d^2}{dz^2}(\\cosh z + 1) = \\cosh z, \\qquad \\cosh(i\\pi) = \\cos\\pi = -1 \\neq 0.", explanation: "Second derivative nonzero, so cosh z + 1 has a double zero, giving a double (order-2) pole of f." },
      ],
      finalAnswer: "Double poles at \\( z = i\\pi(2n+1),\\ n\\in\\mathbb{Z} \\); in particular a pole of order 2 at \\( z = i\\pi \\).",
      canonicalAnswer: "{ i*pi*(2*n+1) : n in Z }",
    },
  },
  {
    id: "cm1b-018",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Standard",
    answerType: "set",
    questionText: "Determine where \\( f(z) = \\bar z = x - iy \\) is differentiable, using the Cauchy–Riemann equations.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["conjugate", "Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify u and v.", workingLatex: "u = x, \\qquad v = -y.", explanation: "The conjugate keeps the real part and negates the imaginary part." },
        { stepNumber: 2, description: "Compute the partials.", workingLatex: "u_x = 1,\\ u_y = 0; \\qquad v_x = 0,\\ v_y = -1.", explanation: "Direct differentiation." },
        { stepNumber: 3, description: "Apply the CR equations.", workingLatex: "u_x = v_y:\\ 1 = -1\\ \\times.", explanation: "The first CR equation already fails everywhere, so the conjugate is nowhere differentiable." },
      ],
      finalAnswer: "\\( \\bar z \\) is differentiable nowhere (analytic nowhere).",
      canonicalAnswer: "nowhere",
    },
  },

  // --------- Challenge (12) ---------
  {
    id: "cm1b-019",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Derive the polar form Cauchy–Riemann equations \\( u_r = \\dfrac{1}{r}v_\\theta,\\ v_r = -\\dfrac{1}{r}u_\\theta \\) from the Cartesian equations \\( u_x = v_y,\\ u_y = -v_x \\) using the chain rule with \\( x = r\\cos\\theta,\\ y = r\\sin\\theta \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["polar Cauchy–Riemann", "chain rule"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the chain rule in r.", workingLatex: "u_r = u_x\\,x_r + u_y\\,y_r = u_x\\cos\\theta + u_y\\sin\\theta.", explanation: "Since x_r = cosθ and y_r = sinθ, this expresses the radial derivative of u in Cartesian partials." },
        { stepNumber: 2, description: "Apply the chain rule in θ.", workingLatex: "v_\\theta = v_x\\,x_\\theta + v_y\\,y_\\theta = v_x(-r\\sin\\theta) + v_y(r\\cos\\theta).", explanation: "Here x_θ = −r sinθ and y_θ = r cosθ." },
        { stepNumber: 3, description: "Substitute the Cartesian CR equations.", workingLatex: "v_\\theta = (-u_y)(-r\\sin\\theta) + (u_x)(r\\cos\\theta) = r\\big(u_x\\cos\\theta + u_y\\sin\\theta\\big).", explanation: "Replace v_x = −u_y and v_y = u_x; the bracket is exactly r·u_r from step 1." },
        { stepNumber: 4, description: "Read off the first polar equation.", workingLatex: "v_\\theta = r\\,u_r \\;\\Rightarrow\\; u_r = \\frac{1}{r}\\,v_\\theta.", explanation: "Dividing by r yields the first polar CR equation." },
        { stepNumber: 5, description: "Compute v_r and u_θ.", workingLatex: "v_r = v_x\\cos\\theta + v_y\\sin\\theta = -u_y\\cos\\theta + u_x\\sin\\theta, \\qquad u_\\theta = -r\\,u_x\\sin\\theta + r\\,u_y\\cos\\theta.", explanation: "Here v_r uses the Cartesian CR substitution v_x = -u_y, v_y = u_x, and u_θ = u_x(-r\\sin\\theta) + u_y(r\\cos\\theta)." },
        { stepNumber: 6, description: "Combine to get the second equation.", workingLatex: "-\\frac{1}{r}u_\\theta = u_x\\sin\\theta - u_y\\cos\\theta = v_y\\sin\\theta + v_x\\cos\\theta = v_r.", explanation: "Using u_x = v_y and −u_y = v_x turns −u_θ/r into v_r, giving the second polar CR equation." },
      ],
      finalAnswer: "The Cartesian CR equations transform to \\( u_r = \\dfrac{1}{r}v_\\theta,\\ v_r = -\\dfrac{1}{r}u_\\theta \\).",
    },
  },
  {
    id: "cm1b-020",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all singularities of \\( f(z) = \\dfrac{\\operatorname{sech} z}{z} \\), classify each, and identify the order of the singularity at \\( z = 0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sech z", "singularity classification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "List candidate singularities.", workingLatex: "z = 0 \\ (\\text{from } 1/z), \\qquad \\cosh z = 0 \\Rightarrow z = i\\big(n+\\tfrac12\\big)\\pi.", explanation: "Singularities come from the explicit 1/z and from the poles of sech z." },
        { stepNumber: 2, description: "Behaviour at z = 0.", workingLatex: "\\operatorname{sech} 0 = 1 \\neq 0, \\qquad f(z) = \\frac{\\operatorname{sech} z}{z} \\sim \\frac{1}{z} \\text{ as } z\\to 0.", explanation: "sech z is analytic and nonzero at 0, so dividing by z leaves a simple pole there." },
        { stepNumber: 3, description: "Compute the residue at 0.", workingLatex: "\\operatorname{Res}_{z=0} f = \\lim_{z\\to 0} z\\cdot\\frac{\\operatorname{sech} z}{z} = \\operatorname{sech} 0 = 1.", explanation: "The residue at the simple pole z=0 is just the value of the analytic factor sech z there." },
        { stepNumber: 4, description: "Behaviour at the sech poles.", workingLatex: "z_n = i\\big(n+\\tfrac12\\big)\\pi \\neq 0, \\qquad \\cosh z_n = 0,\\ \\sinh z_n \\neq 0.", explanation: "At each z_n the factor 1/z is analytic nonzero while sech z has a simple pole, so f has a simple pole." },
        { stepNumber: 5, description: "Collect the singularities.", workingLatex: "\\{0\\}\\cup\\Big\\{\\,i\\big(n+\\tfrac12\\big)\\pi : n\\in\\mathbb{Z}\\,\\Big\\}, \\quad \\text{all simple poles}.", explanation: "Every singularity is a simple pole; in particular z=0 is order 1, not removable, since the numerator does not vanish there." },
      ],
      finalAnswer: "Simple poles at \\( z=0 \\) (residue 1) and \\( z = i\\big(n+\\tfrac12\\big)\\pi \\); the singularity at \\( 0 \\) has order 1.",
      canonicalAnswer: "{0} ∪ { i*(n+1/2)*pi : n in Z }",
    },
  },
  {
    id: "cm1b-021",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using the polar CR equations, prove that \\( f(z) = z^\\alpha := r^\\alpha e^{i\\alpha\\theta} \\) (principal branch, \\( -\\pi<\\theta<\\pi \\), \\( \\alpha \\) real) is analytic, and show \\( f'(z) = \\alpha z^{\\alpha-1} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["complex power", "polar Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Separate into u and v.", workingLatex: "u = r^\\alpha\\cos\\alpha\\theta, \\qquad v = r^\\alpha\\sin\\alpha\\theta.", explanation: "Real and imaginary parts of r^α e^{iαθ}." },
        { stepNumber: 2, description: "Check the first CR equation.", workingLatex: "u_r = \\alpha r^{\\alpha-1}\\cos\\alpha\\theta, \\qquad \\frac{1}{r}v_\\theta = \\frac{1}{r}\\,\\alpha r^\\alpha\\cos\\alpha\\theta = \\alpha r^{\\alpha-1}\\cos\\alpha\\theta.", explanation: "u_r = v_θ/r holds for all r>0." },
        { stepNumber: 3, description: "Check the second CR equation.", workingLatex: "v_r = \\alpha r^{\\alpha-1}\\sin\\alpha\\theta, \\qquad -\\frac{1}{r}u_\\theta = -\\frac{1}{r}(-\\alpha r^\\alpha\\sin\\alpha\\theta) = \\alpha r^{\\alpha-1}\\sin\\alpha\\theta.", explanation: "v_r = −u_θ/r also holds, so z^α is analytic on the cut plane (away from the branch cut and origin)." },
        { stepNumber: 4, description: "Assemble u_r + i v_r.", workingLatex: "u_r + i v_r = \\alpha r^{\\alpha-1}\\big(\\cos\\alpha\\theta + i\\sin\\alpha\\theta\\big) = \\alpha r^{\\alpha-1}e^{i\\alpha\\theta}.", explanation: "Collecting the trig terms into a single exponential." },
        { stepNumber: 5, description: "Form the derivative.", workingLatex: "f'(z) = e^{-i\\theta}\\,\\alpha r^{\\alpha-1}e^{i\\alpha\\theta} = \\alpha r^{\\alpha-1}e^{i(\\alpha-1)\\theta} = \\alpha z^{\\alpha-1}.", explanation: "The factor e^{−iθ} lowers the exponent by one, giving the expected power rule." },
      ],
      finalAnswer: "\\( z^\\alpha \\) is analytic on the principal-branch cut plane, with \\( f'(z) = \\alpha z^{\\alpha-1} \\).",
    },
  },
  {
    id: "cm1b-022",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "The branch of \\( \\log z = \\ln r + i\\theta \\) with \\( -\\pi<\\theta<\\pi \\) is analytic on the cut plane. State precisely where it fails to be analytic and explain why the failure on the negative real axis is a discontinuity rather than an isolated singularity.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["logarithm", "branch cut"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Locate the origin failure.", workingLatex: "u = \\ln r \\to -\\infty \\text{ as } r\\to 0^+.", explanation: "The real part is unbounded at the origin, so log z cannot be defined (let alone analytic) at z=0." },
        { stepNumber: 2, description: "Examine the negative real axis.", workingLatex: "\\theta \\to \\pi^- \\Rightarrow \\operatorname{Im}\\log z \\to \\pi, \\qquad \\theta \\to -\\pi^+ \\Rightarrow \\operatorname{Im}\\log z \\to -\\pi.", explanation: "Approaching a negative real point from above and below gives arguments differing by 2π." },
        { stepNumber: 3, description: "Identify the jump.", workingLatex: "\\lim_{\\theta\\to\\pi^-}\\log z - \\lim_{\\theta\\to-\\pi^+}\\log z = 2\\pi i.", explanation: "There is a genuine 2πi jump across the cut, so the function is not even continuous there." },
        { stepNumber: 4, description: "Contrast with an isolated singularity.", workingLatex: "z = x<0:\\ \\text{points lie on a curve (the cut), not isolated.}", explanation: "An isolated singularity has an analytic punctured neighbourhood; here every neighbourhood of a cut point straddles the discontinuity, so no Laurent series exists." },
        { stepNumber: 5, description: "State the conclusion.", workingLatex: "\\text{Analytic on } \\mathbb{C}\\setminus(-\\infty,0]; \\text{ fails on the cut } (-\\infty,0].", explanation: "The failure is along a whole ray (a branch cut), a removable artefact of the chosen branch, not a pole or essential singularity." },
      ],
      finalAnswer: "Analytic on \\( \\mathbb{C}\\setminus(-\\infty,0] \\); it fails on the cut \\( (-\\infty,0] \\), where there is a \\( 2\\pi i \\) jump (a branch discontinuity), not an isolated singularity.",
      canonicalAnswer: "C \\ (-inf, 0]",
    },
  },
  {
    id: "cm1b-023",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find and classify all singularities of \\( f(z) = \\dfrac{e^z}{\\sinh z} \\), and compute the residue at \\( z = 0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singularity classification", "residue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Zero the denominator.", workingLatex: "\\sinh z = 0 \\;\\Rightarrow\\; \\sin(iz)/i \\text{ form}: \\ z = i\\pi n, \\quad n\\in\\mathbb{Z}.", explanation: "sinh z = −i sin(iz), which vanishes at iz = nπ, i.e. z = iπn." },
        { stepNumber: 2, description: "Check the order of the zeros.", workingLatex: "\\frac{d}{dz}\\sinh z = \\cosh z, \\qquad \\cosh(i\\pi n) = \\cos(\\pi n) = (-1)^n \\neq 0.", explanation: "Nonzero derivative means each zero of sinh z is simple, so f has simple poles." },
        { stepNumber: 3, description: "Confirm numerator nonzero.", workingLatex: "e^{z}\\big|_{z=i\\pi n} = e^{i\\pi n} = (-1)^n \\neq 0.", explanation: "The exponential never vanishes, so no pole is cancelled — all are genuine simple poles." },
        { stepNumber: 4, description: "Compute the residue at z=0.", workingLatex: "\\operatorname{Res}_{z=0}\\frac{e^z}{\\sinh z} = \\frac{e^z}{\\cosh z}\\bigg|_{z=0} = \\frac{1}{1} = 1.", explanation: "At a simple pole, Res = numerator / (denominator)' evaluated at the pole, i.e. e^0/cosh 0." },
      ],
      finalAnswer: "Simple poles at \\( z = i\\pi n,\\ n\\in\\mathbb{Z} \\); residue at \\( z=0 \\) is \\( 1 \\).",
      canonicalAnswer: "{ i*pi*n : n in Z }",
    },
  },
  {
    id: "cm1b-024",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Classify the singularity of \\( f(z) = e^{1/z} \\) at \\( z = 0 \\), and state whether \\( f \\) is analytic on \\( \\mathbb{C}\\setminus\\{0\\} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["essential singularity", "Laurent series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand in a Laurent series about 0.", workingLatex: "e^{1/z} = \\sum_{k=0}^{\\infty}\\frac{1}{k!}\\,z^{-k} = 1 + \\frac{1}{z} + \\frac{1}{2!z^2} + \\frac{1}{3!z^3} + \\cdots.", explanation: "Substituting 1/z into the exponential series gives a Laurent series valid for z≠0." },
        { stepNumber: 2, description: "Inspect the principal part.", workingLatex: "\\text{Principal part} = \\sum_{k=1}^{\\infty}\\frac{1}{k!}z^{-k} \\ (\\text{infinitely many terms}).", explanation: "Infinitely many negative powers appear, so the singularity is not a pole of any finite order." },
        { stepNumber: 3, description: "Classify the singularity.", workingLatex: "z = 0 \\text{ is an essential singularity}.", explanation: "An infinite principal part is the defining feature of an essential singularity (cf. the Casorati–Weierstrass behaviour near 0)." },
        { stepNumber: 4, description: "Discuss analyticity off 0.", workingLatex: "1/z \\text{ analytic on } \\mathbb{C}\\setminus\\{0\\},\\ e^w \\text{ entire} \\Rightarrow e^{1/z} \\text{ analytic on } \\mathbb{C}\\setminus\\{0\\}.", explanation: "A composition of analytic maps is analytic, so f is analytic everywhere except the essential singularity at 0." },
      ],
      finalAnswer: "Essential singularity at \\( z = 0 \\); \\( f \\) is analytic on \\( \\mathbb{C}\\setminus\\{0\\} \\).",
      canonicalAnswer: "{0}",
    },
  },
  {
    id: "cm1b-025",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Show that \\( z = 0 \\) is a removable singularity of \\( f(z) = \\dfrac{\\sin z}{z} \\) and state the analytic continuation's value there. Then give all genuine singularities of \\( \\dfrac{\\sin z}{z(z^2+\\pi^2)} \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["removable singularity", "singularity classification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand sin z about 0.", workingLatex: "\\sin z = z - \\frac{z^3}{6} + \\frac{z^5}{120} - \\cdots.", explanation: "Taylor series of sin z; the leading term is z, matching the z in the denominator." },
        { stepNumber: 2, description: "Divide and inspect.", workingLatex: "\\frac{\\sin z}{z} = 1 - \\frac{z^2}{6} + \\frac{z^4}{120} - \\cdots.", explanation: "No negative powers remain, so the singularity at z=0 is removable and the limit is 1." },
        { stepNumber: 3, description: "Now treat the second function.", workingLatex: "g(z) = \\frac{\\sin z}{z(z^2+\\pi^2)} = \\frac{\\sin z}{z(z-i\\pi)(z+i\\pi)}.", explanation: "Factor the quadratic; candidate singularities are z=0, ±iπ." },
        { stepNumber: 4, description: "Resolve z=0.", workingLatex: "g(z) = \\frac{\\sin z}{z}\\cdot\\frac{1}{z^2+\\pi^2}, \\qquad \\frac{\\sin z}{z}\\to 1, \\ \\frac{1}{z^2+\\pi^2}\\to\\frac{1}{\\pi^2}.", explanation: "The sin z/z factor is analytic at 0, so z=0 is removable for g too (value 1/π²)." },
        { stepNumber: 5, description: "Check ±iπ.", workingLatex: "\\sin(\\pm i\\pi) = \\pm i\\sinh\\pi \\neq 0, \\qquad \\frac{d}{dz}(z^2+\\pi^2)\\big|_{\\pm i\\pi} = \\pm 2i\\pi \\neq 0.", explanation: "Numerator nonzero and the quadratic has simple zeros at ±iπ, so these are simple poles." },
        { stepNumber: 6, description: "State the genuine singularities.", workingLatex: "\\{\\,i\\pi,\\ -i\\pi\\,\\}, \\quad \\text{both simple poles}.", explanation: "z=0 is removable, so the only true singularities are the simple poles at ±iπ." },
      ],
      finalAnswer: "\\( \\sin z/z \\) has a removable singularity at \\( 0 \\) with value \\( 1 \\); the second function has simple poles only at \\( z = \\pm i\\pi \\).",
      canonicalAnswer: "{ i*pi, -i*pi }",
    },
  },
  {
    id: "cm1b-026",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all singularities of \\( f(z) = \\tan^2 z \\) and determine the order of the pole at \\( z = \\tfrac{\\pi}{2} \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["tan z", "pole order"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write in terms of cos.", workingLatex: "\\tan^2 z = \\frac{\\sin^2 z}{\\cos^2 z}.", explanation: "Singularities are where cos² z = 0, i.e. where cos z = 0." },
        { stepNumber: 2, description: "Locate the singularities.", workingLatex: "\\cos z = 0 \\;\\Rightarrow\\; z = \\Big(n+\\tfrac12\\Big)\\pi, \\quad n\\in\\mathbb{Z}.", explanation: "These are the only zeros of cos z, all real and simple." },
        { stepNumber: 3, description: "Order of the cos² zero at π/2.", workingLatex: "\\cos z \\text{ has a simple zero at } \\tfrac{\\pi}{2} \\;\\Rightarrow\\; \\cos^2 z \\text{ has a double zero there.}", explanation: "Squaring a simple zero produces a zero of order 2 in the denominator." },
        { stepNumber: 4, description: "Check the numerator.", workingLatex: "\\sin^2\\!\\Big(\\tfrac{\\pi}{2}\\Big) = 1 \\neq 0.", explanation: "Numerator nonzero, so no cancellation; the pole order equals the denominator's zero order." },
        { stepNumber: 5, description: "State the order.", workingLatex: "\\text{Pole of order } 2 \\text{ at } z = \\tfrac{\\pi}{2} \\ (\\text{and at each } (n+\\tfrac12)\\pi).", explanation: "Hence tan² z has double poles at all the odd multiples of π/2." },
      ],
      finalAnswer: "Double poles at \\( z = \\big(n+\\tfrac12\\big)\\pi,\\ n\\in\\mathbb{Z} \\); in particular order 2 at \\( z = \\tfrac{\\pi}{2} \\).",
      canonicalAnswer: "{ (n+1/2)*pi : n in Z }",
    },
  },
  {
    id: "cm1b-027",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Using the polar CR equations, show that \\( f(z) = r^2 \\) (i.e. \\( |z|^2 \\), so \\( u = r^2,\\ v = 0 \\)) satisfies neither polar CR equation for \\( r\\neq 0 \\), and reconcile this with the Cartesian finding that \\( |z|^2 \\) is differentiable at the origin.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["|z|^2", "polar Cauchy–Riemann"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the polar parts.", workingLatex: "u = r^2, \\qquad v = 0.", explanation: "|z|² = r² is real, so its imaginary part is zero." },
        { stepNumber: 2, description: "Test the first polar CR equation.", workingLatex: "u_r = 2r, \\qquad \\frac{1}{r}v_\\theta = 0.", explanation: "u_r = 2r ≠ 0 for r≠0 while v_θ/r = 0, so the first equation fails away from the origin." },
        { stepNumber: 3, description: "Test the second polar CR equation.", workingLatex: "v_r = 0, \\qquad -\\frac{1}{r}u_\\theta = -\\frac{1}{r}\\cdot 0 = 0.", explanation: "The second equation 0 = 0 holds trivially since u has no θ-dependence; only the first equation is violated." },
        { stepNumber: 4, description: "Note the polar coordinates exclude the origin.", workingLatex: "r = 0 \\text{ is the coordinate singularity of polar coordinates; } \\theta \\text{ undefined there.}", explanation: "The polar test is valid only for r>0, so it can say nothing about r=0." },
        { stepNumber: 5, description: "Reconcile with the Cartesian result.", workingLatex: "u_x = 2x,\\ u_y = 2y,\\ v\\equiv 0:\\ \\text{CR} \\Leftrightarrow 2x=0,\\ 2y=0 \\Leftrightarrow z=0.", explanation: "In Cartesian form the CR equations do hold at the single point z=0; the polar form simply cannot reach that excluded point, so there is no contradiction." },
      ],
      finalAnswer: "The first polar CR equation \\( u_r = v_\\theta/r \\) fails for all \\( r>0 \\); \\( |z|^2 \\) is differentiable only at \\( z=0 \\), the point polar coordinates exclude, so analytic nowhere.",
    },
  },
  {
    id: "cm1b-028",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Find all singularities of \\( f(z) = \\dfrac{1}{e^{z} + 1} \\), classify them, and give the residue at the singularity nearest the real axis with positive imaginary part.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["singularities", "residue"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Zero the denominator.", workingLatex: "e^z + 1 = 0 \\;\\Rightarrow\\; e^z = -1.", explanation: "Singularities are the zeros of e^z + 1." },
        { stepNumber: 2, description: "Solve e^z = −1.", workingLatex: "z = i\\pi(2n+1), \\quad n\\in\\mathbb{Z}.", explanation: "e^z = −1 needs real part 0 and imaginary part an odd multiple of π." },
        { stepNumber: 3, description: "Classify and find the nearest pole.", workingLatex: "\\frac{d}{dz}(e^z+1) = e^z \\neq 0 \\Rightarrow \\text{simple poles}; \\quad \\text{nearest with } \\operatorname{Im}>0:\\ z = i\\pi.", explanation: "Simple zeros of the denominator give simple poles; the one with smallest positive imaginary part is z=iπ." },
        { stepNumber: 4, description: "Compute the residue at z=iπ.", workingLatex: "\\operatorname{Res}_{z=i\\pi}\\frac{1}{e^z+1} = \\frac{1}{e^{z}}\\bigg|_{z=i\\pi} = \\frac{1}{e^{i\\pi}} = \\frac{1}{-1} = -1.", explanation: "Residue at a simple pole is 1/(denominator)' = 1/e^z evaluated at the pole, here e^{iπ} = −1." },
      ],
      finalAnswer: "Simple poles at \\( z = i\\pi(2n+1),\\ n\\in\\mathbb{Z} \\); the residue at \\( z = i\\pi \\) is \\( -1 \\).",
      canonicalAnswer: "{ i*pi*(2*n+1) : n in Z }",
    },
  },
  {
    id: "cm1b-029",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f(z) = u + iv \\) be analytic with \\( u = u(r) \\) depending on \\( r=|z| \\) alone. Using the polar CR equations, determine the most general such \\( f \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["polar Cauchy–Riemann", "logarithm"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use that u is θ-independent.", workingLatex: "u_\\theta = 0.", explanation: "Given u depends only on r, its θ-derivative vanishes." },
        { stepNumber: 2, description: "Apply the second polar CR equation.", workingLatex: "v_r = -\\frac{1}{r}u_\\theta = 0 \\;\\Rightarrow\\; v = v(\\theta) \\text{ only}.", explanation: "With u_θ = 0 the equation forces v to be independent of r." },
        { stepNumber: 3, description: "Apply the first polar CR equation.", workingLatex: "u_r = \\frac{1}{r}v_\\theta \\;\\Rightarrow\\; r\\,u'(r) = v'(\\theta).", explanation: "The left side depends only on r, the right side only on θ, so both equal a constant." },
        { stepNumber: 4, description: "Separate variables.", workingLatex: "r\\,u'(r) = c, \\qquad v'(\\theta) = c \\quad (c \\text{ constant}).", explanation: "A function of r alone equal to a function of θ alone must be constant." },
        { stepNumber: 5, description: "Integrate.", workingLatex: "u = c\\ln r + a, \\qquad v = c\\theta + b \\quad (a,b \\text{ real constants}).", explanation: "Integrating r u' = c gives the logarithm; integrating v' = c gives the linear term." },
        { stepNumber: 6, description: "Assemble f.", workingLatex: "f = (c\\ln r + a) + i(c\\theta + b) = c(\\ln r + i\\theta) + (a + ib) = c\\log z + d.", explanation: "Recognising ln r + iθ = log z, the general analytic f with u=u(r) is a complex multiple of log z plus a constant." },
      ],
      finalAnswer: "\\( f(z) = c\\,\\log z + d \\) for real constant \\( c \\) and complex constant \\( d \\).",
    },
  },
  {
    id: "cm1b-030",
    topicRef: "cm1b",
    topicTitle: "CR in polar form; analyticity of elementary functions",
    difficulty: "Challenge",
    answerType: "set",
    questionText: "Compare the singularity at \\( z = 0 \\) of \\( g(z) = \\dfrac{\\cosh z - 1}{z^2} \\) with that of \\( h(z) = \\dfrac{\\cosh z}{z^2} \\): classify each and give the residue of \\( h \\) at \\( 0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["removable singularity", "Laurent series"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Expand cosh z about 0.", workingLatex: "\\cosh z = 1 + \\frac{z^2}{2} + \\frac{z^4}{24} + \\cdots.", explanation: "Even Taylor series of cosh z." },
        { stepNumber: 2, description: "Analyse g(z).", workingLatex: "\\cosh z - 1 = \\frac{z^2}{2} + \\frac{z^4}{24} + \\cdots \\;\\Rightarrow\\; g(z) = \\frac{1}{2} + \\frac{z^2}{24} + \\cdots.", explanation: "Subtracting 1 cancels the constant; dividing by z² leaves a power series with no negative powers, so z=0 is removable for g (value ½)." },
        { stepNumber: 3, description: "Analyse h(z).", workingLatex: "h(z) = \\frac{\\cosh z}{z^2} = \\frac{1}{z^2}\\Big(1 + \\frac{z^2}{2} + \\cdots\\Big) = \\frac{1}{z^2} + \\frac{1}{2} + \\frac{z^2}{24} + \\cdots.", explanation: "Now the constant 1 in the numerator survives, producing a z^{−2} term." },
        { stepNumber: 4, description: "Classify h at 0.", workingLatex: "\\text{Principal part} = \\frac{1}{z^2} \\;\\Rightarrow\\; \\text{double pole (order 2)}.", explanation: "Highest negative power is z^{−2}, with no z^{−1} term, so it is a pole of order 2." },
        { stepNumber: 5, description: "Read off the residue of h.", workingLatex: "\\operatorname{Res}_{z=0} h = \\text{coefficient of } z^{-1} = 0.", explanation: "The Laurent series of h has no 1/z term (cosh is even), so the residue at 0 is zero." },
      ],
      finalAnswer: "\\( g \\) has a removable singularity at \\( 0 \\) (value \\( \\tfrac12 \\)); \\( h \\) has a double pole at \\( 0 \\) with residue \\( 0 \\).",
      canonicalAnswer: "g: removable; h: pole of order 2, residue 0",
    },
  },
];
