import { Question } from "@/lib/types";

/*
 * Complex Methods — cm1c
 * The Wirtinger ∂/∂z̄ viewpoint
 * Topic group: cm1 — Analyticity & the Cauchy–Riemann Equations
 * Sheet ref: S1Q1(iii) (Cambridge Part IB Complex Methods, Lent 2026)
 *
 * 30 fully-worked questions. Difficulty split 6 / 12 / 12 (Foundation /
 * Standard / Challenge).
 *
 * Scope: the Wirtinger operators ∂/∂z = ½(∂/∂x − i∂/∂y),
 * ∂/∂z̄ = ½(∂/∂x + i∂/∂y); the theorem f analytic ⇔ ∂f/∂z̄ = 0, equivalently
 * the Cauchy–Riemann equations; rewriting functions in z, z̄ and reading off
 * analyticity by inspection; harmonic functions via ∂²/∂z∂z̄; constructing the
 * general f with prescribed ∂f/∂z̄.
 *
 * Conventions: worked-solution fractions use big \frac; stems use \dfrac.
 * Treating z and z̄ as independent: ∂z/∂z̄ = 0, ∂z̄/∂z̄ = 1. Every ∂/∂z̄
 * computation was checked against the real-coordinate form
 * ∂f/∂z̄ = ½(∂f/∂x + i∂f/∂y).
 */
export const questions: Question[] = [
  // --------- Foundation (6) ---------
  {
    id: "cm1c-001",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Treating \\( z \\) and \\( \\bar z \\) as independent variables, compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = z^{3}\\bar z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "partial differentiation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the Wirtinger rule.", workingLatex: "\\frac{\\partial z}{\\partial \\bar z}=0,\\qquad \\frac{\\partial \\bar z}{\\partial \\bar z}=1.", explanation: "In the Wirtinger calculus z and z̄ are treated as independent coordinates, so z is constant when differentiating in z̄." },
        { stepNumber: 2, description: "Differentiate, holding z fixed.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\big(z^{3}\\bar z\\big)=z^{3}\\,\\frac{\\partial \\bar z}{\\partial \\bar z}=z^{3}.", explanation: "The factor z^3 is a constant under ∂/∂z̄, so only the z̄ factor differentiates." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z} = z^{3} \\).",
      canonicalAnswer: "z^3",
    },
  },
  {
    id: "cm1c-002",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = |z|^{2} = z\\bar z \\), and hence state whether \\( f \\) is analytic anywhere.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the modulus squared in z, z̄.", workingLatex: "f=|z|^{2}=z\\bar z.", explanation: "The squared modulus is the product of z with its conjugate." },
        { stepNumber: 2, description: "Differentiate with respect to z̄.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\big(z\\bar z\\big)=z\\,\\frac{\\partial \\bar z}{\\partial \\bar z}=z.", explanation: "Hold z fixed; only the z̄ factor differentiates." },
        { stepNumber: 3, description: "Apply the analyticity criterion.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z=0 \\iff z=0.", explanation: "f is analytic on an open set only where ∂f/∂z̄ vanishes identically; here it vanishes only at the single point z=0, which is not an open set." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=z \\); since this is non-zero except at \\( z=0 \\), \\( f \\) is nowhere analytic.",
      canonicalAnswer: "z",
    },
  },
  {
    id: "cm1c-003",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = \\bar z^{\\,2} + 4z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "partial differentiation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate term by term.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\big(\\bar z^{2}+4z\\big)=\\frac{\\partial}{\\partial \\bar z}\\bar z^{2}+\\frac{\\partial}{\\partial \\bar z}(4z).", explanation: "The Wirtinger operator is linear." },
        { stepNumber: 2, description: "Evaluate each piece.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\bar z^{2}=2\\bar z,\\qquad \\frac{\\partial}{\\partial \\bar z}(4z)=0.", explanation: "Power rule in z̄ for the first term; the term 4z is constant under ∂/∂z̄." },
        { stepNumber: 3, description: "Combine.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=2\\bar z.", explanation: "Only the conjugate-dependent term survives." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=2\\bar z \\).",
      canonicalAnswer: "2*conjugate(z)",
    },
  },
  {
    id: "cm1c-004",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using \\( \\dfrac{\\partial}{\\partial \\bar z}=\\dfrac{1}{2}\\left(\\dfrac{\\partial}{\\partial x}+i\\dfrac{\\partial}{\\partial y}\\right) \\), compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = x^{2}+y^{2} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Wirtinger operator", "real coordinates"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Take the real partial derivatives.", workingLatex: "\\frac{\\partial f}{\\partial x}=2x,\\qquad \\frac{\\partial f}{\\partial y}=2y.", explanation: "Differentiate x²+y² in x and y separately." },
        { stepNumber: 2, description: "Insert into the operator.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{1}{2}\\big(2x+i\\,2y\\big)=x+iy.", explanation: "The Wirtinger z̄-operator combines the two real derivatives with the +i weighting." },
        { stepNumber: 3, description: "Recognise the result.", workingLatex: "x+iy=z.", explanation: "Consistent with |z|²=zz̄ giving ∂/∂z̄=z." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=x+iy=z \\).",
      canonicalAnswer: "z",
    },
  },
  {
    id: "cm1c-005",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "set",
    questionText: "For each of \\( f_1=z^{2} \\), \\( f_2=\\bar z \\), \\( f_3=z\\bar z \\), \\( f_4=e^{z} \\), use \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) to decide which are analytic on \\( \\mathbb{C} \\). Give the set of analytic ones.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["analyticity test", "Wirtinger derivative"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate each in z̄.", workingLatex: "\\frac{\\partial f_1}{\\partial \\bar z}=0,\\quad \\frac{\\partial f_2}{\\partial \\bar z}=1,\\quad \\frac{\\partial f_3}{\\partial \\bar z}=z,\\quad \\frac{\\partial f_4}{\\partial \\bar z}=0.", explanation: "z² and e^z contain no z̄, so their z̄-derivatives vanish; z̄ and zz̄ do depend on z̄." },
        { stepNumber: 2, description: "Apply the criterion.", workingLatex: "f\\text{ analytic}\\iff \\frac{\\partial f}{\\partial \\bar z}\\equiv 0.", explanation: "A function is analytic exactly where its Wirtinger z̄-derivative is identically zero on an open set." },
        { stepNumber: 3, description: "Select.", workingLatex: "\\{f_1,\\ f_4\\}=\\{z^{2},\\ e^{z}\\}.", explanation: "Only these two have vanishing ∂/∂z̄ everywhere." },
      ],
      finalAnswer: "Analytic: \\( \\{\\,z^{2},\\ e^{z}\\,\\} \\).",
      canonicalAnswer: "{z^2, e^z}",
    },
  },
  {
    id: "cm1c-006",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given that \\( g=z^{2}\\bar z^{\\,2} \\), compute \\( \\dfrac{\\partial g}{\\partial \\bar z} \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "product rule"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Hold z² fixed and apply the power rule in z̄.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\big(z^{2}\\bar z^{2}\\big)=z^{2}\\,\\frac{\\partial}{\\partial \\bar z}\\bar z^{2}.", explanation: "The factor z² is constant under ∂/∂z̄." },
        { stepNumber: 2, description: "Differentiate the conjugate power.", workingLatex: "\\frac{\\partial}{\\partial \\bar z}\\bar z^{2}=2\\bar z.", explanation: "Ordinary power rule with z̄ as the variable." },
        { stepNumber: 3, description: "Combine.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=2z^{2}\\bar z.", explanation: "Note g=|z|⁴ is real and non-analytic, consistent with a non-zero z̄-derivative." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial g}{\\partial \\bar z}=2z^{2}\\bar z \\).",
      canonicalAnswer: "2*z^2*conjugate(z)",
    },
  },

  // --------- Standard (12) ---------
  {
    id: "cm1c-007",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express the real function \\( f = x^{2}-y^{2}+2ixy \\) in terms of \\( z \\) and \\( \\bar z \\), compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\), and state whether \\( f \\) is analytic.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recognise the real and imaginary parts.", workingLatex: "u=x^{2}-y^{2},\\qquad v=2xy.", explanation: "These are precisely the real and imaginary parts of z²." },
        { stepNumber: 2, description: "Assemble in z, z̄ form.", workingLatex: "f=(x^{2}-y^{2})+i(2xy)=(x+iy)^{2}=z^{2}.", explanation: "Completing the square in x+iy collapses the expression to z²; no z̄ appears." },
        { stepNumber: 3, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial}{\\partial \\bar z}z^{2}=0.", explanation: "z² has no z̄-dependence, so its Wirtinger z̄-derivative vanishes identically." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}\\equiv 0 \\implies f\\text{ analytic on }\\mathbb{C}.", explanation: "Vanishing ∂/∂z̄ everywhere is exactly the criterion for entire analyticity." },
      ],
      finalAnswer: "\\( f=z^{2} \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\); \\( f \\) is analytic on all of \\( \\mathbb{C} \\).",
      canonicalAnswer: "f=z^2, df/dconjugate(z)=0",
    },
  },
  {
    id: "cm1c-008",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Write \\( x = \\dfrac{z+\\bar z}{2} \\) and \\( y = \\dfrac{z-\\bar z}{2i} \\). Express \\( f = x^{2}+y^{2}+2x \\) in terms of \\( z,\\bar z \\), compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\), and decide where \\( f \\) is analytic.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute the standard identities.", workingLatex: "x^{2}+y^{2}=|z|^{2}=z\\bar z,\\qquad 2x=z+\\bar z.", explanation: "x²+y² is exactly the squared modulus, and 2x is the sum of z and its conjugate." },
        { stepNumber: 2, description: "Assemble f.", workingLatex: "f=z\\bar z+z+\\bar z.", explanation: "Direct substitution; the conjugate appears explicitly." },
        { stepNumber: 3, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z\\cdot 1+0+1=z+1.", explanation: "Hold z fixed: the zz̄ term gives z, the z term gives 0, the z̄ term gives 1." },
        { stepNumber: 4, description: "Apply the analyticity criterion.", workingLatex: "z+1=0 \\iff z=-1.", explanation: "∂f/∂z̄ vanishes only at the isolated point z=−1, which is not open, so f is analytic nowhere." },
      ],
      finalAnswer: "\\( f=z\\bar z+z+\\bar z \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=z+1 \\); \\( f \\) is nowhere analytic (zero only at the point \\( z=-1 \\)).",
      canonicalAnswer: "z+1",
    },
  },
  {
    id: "cm1c-009",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that \\( f = z^{3} \\) satisfies \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\), and obtain \\( f'(z) \\) as \\( \\dfrac{\\partial f}{\\partial z} \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["analyticity test", "complex derivative via d/dz"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial}{\\partial \\bar z}z^{3}=0.", explanation: "z³ involves no z̄, so the Wirtinger z̄-derivative is identically zero — f is analytic." },
        { stepNumber: 2, description: "State that f' equals the z-Wirtinger derivative for analytic f.", workingLatex: "f\\text{ analytic}\\implies f'(z)=\\frac{\\partial f}{\\partial z}.", explanation: "When ∂f/∂z̄=0 the complex derivative coincides with the Wirtinger ∂/∂z operator." },
        { stepNumber: 3, description: "Compute the z-derivative.", workingLatex: "\\frac{\\partial}{\\partial z}z^{3}=3z^{2}.", explanation: "Power rule with z held as the active variable, z̄ fixed (and absent)." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\) and \\( f'(z)=3z^{2} \\).",
      canonicalAnswer: "3*z^2",
    },
  },
  {
    id: "cm1c-010",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "The function \\( f = e^{x}\\cos y + i\\,e^{x}\\sin y \\) is given in real form. Express it in \\( z \\), confirm \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\), and find \\( f'(z) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "complex derivative via d/dz"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Combine into a single exponential.", workingLatex: "e^{x}\\cos y+i\\,e^{x}\\sin y=e^{x}(\\cos y+i\\sin y)=e^{x}e^{iy}.", explanation: "Euler's formula packages the trig pair into a complex exponential." },
        { stepNumber: 2, description: "Recognise the exponent.", workingLatex: "e^{x}e^{iy}=e^{x+iy}=e^{z}.", explanation: "x+iy=z, so f is just the entire function e^z." },
        { stepNumber: 3, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial}{\\partial \\bar z}e^{z}=0.", explanation: "No z̄ appears, confirming analyticity everywhere." },
        { stepNumber: 4, description: "Compute f'.", workingLatex: "f'(z)=\\frac{\\partial}{\\partial z}e^{z}=e^{z}.", explanation: "The z-Wirtinger derivative gives the usual complex derivative since f is analytic." },
      ],
      finalAnswer: "\\( f=e^{z} \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\), and \\( f'(z)=e^{z} \\).",
      canonicalAnswer: "e^z",
    },
  },
  {
    id: "cm1c-011",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that the two Wirtinger conditions \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\) and the Cauchy–Riemann equations \\( u_x=v_y,\\ u_y=-v_x \\) are equivalent, for \\( f=u+iv \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger operator", "Cauchy-Riemann equivalence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the operator on f=u+iv.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{1}{2}\\Big(\\frac{\\partial}{\\partial x}+i\\frac{\\partial}{\\partial y}\\Big)(u+iv).", explanation: "Apply the z̄-Wirtinger operator in real coordinates to the split into real and imaginary parts." },
        { stepNumber: 2, description: "Expand and collect i.", workingLatex: "=\\frac{1}{2}\\big(u_x+iv_x+i u_y - v_y\\big)=\\frac{1}{2}\\big[(u_x-v_y)+i(v_x+u_y)\\big].", explanation: "Distribute the operator; using i²=−1 turns the i·iv_y term into −v_y, and group real with imaginary." },
        { stepNumber: 3, description: "Set the derivative to zero.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=0 \\iff u_x-v_y=0\\ \\text{and}\\ v_x+u_y=0.", explanation: "A complex number is zero iff both its real and imaginary parts vanish." },
        { stepNumber: 4, description: "Rearrange to the CR form.", workingLatex: "u_x=v_y,\\qquad u_y=-v_x.", explanation: "These are exactly the Cauchy–Riemann equations, so the two conditions are equivalent." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=\\tfrac{1}{2}[(u_x-v_y)+i(u_y+v_x)] \\), which vanishes iff \\( u_x=v_y \\) and \\( u_y=-v_x \\).",
    },
  },
  {
    id: "cm1c-012",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = \\dfrac{1}{\\bar z} \\) (for \\( z\\neq 0 \\)) and state where, if anywhere, \\( f \\) is analytic.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write as a negative power of z̄.", workingLatex: "f=\\bar z^{\\,-1}.", explanation: "Express the reciprocal to apply the power rule in z̄." },
        { stepNumber: 2, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=-\\bar z^{\\,-2}=-\\frac{1}{\\bar z^{2}}.", explanation: "Power rule with exponent −1; z is held fixed and does not appear anyway." },
        { stepNumber: 3, description: "Test for analyticity.", workingLatex: "-\\frac{1}{\\bar z^{2}}\\neq 0\\ \\text{ for all } z\\neq 0.", explanation: "The z̄-derivative never vanishes on the punctured plane, so f is analytic nowhere." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=-\\dfrac{1}{\\bar z^{2}} \\); \\( f \\) is nowhere analytic.",
      canonicalAnswer: "-1/conjugate(z)^2",
    },
  },
  {
    id: "cm1c-013",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( f = 2xy + i(y^{2}-x^{2}) \\) in terms of \\( z,\\bar z \\) and determine whether it is analytic by computing \\( \\dfrac{\\partial f}{\\partial \\bar z} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the structure.", workingLatex: "u=2xy,\\qquad v=y^{2}-x^{2}.", explanation: "Compare with z²=(x²−y²)+i(2xy); the parts here look like −i times that." },
        { stepNumber: 2, description: "Factor out −i from z².", workingLatex: "-i z^{2}=-i\\big[(x^{2}-y^{2})+i\\,2xy\\big]=2xy + i(y^{2}-x^{2}).", explanation: "Multiplying z² by −i rotates real and imaginary parts: the result matches f exactly." },
        { stepNumber: 3, description: "Conclude the z-form.", workingLatex: "f=-i z^{2}.", explanation: "f is a constant multiple of z², purely a function of z." },
        { stepNumber: 4, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=-i\\,\\frac{\\partial}{\\partial \\bar z}z^{2}=0.", explanation: "No z̄-dependence, so f is analytic on all of ℂ." },
      ],
      finalAnswer: "\\( f=-iz^{2} \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\); \\( f \\) is analytic everywhere.",
      canonicalAnswer: "f=-i*z^2",
    },
  },
  {
    id: "cm1c-014",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) for \\( f = \\operatorname{Re}(z) = \\dfrac{z+\\bar z}{2} \\), and explain why \\( f \\) is nowhere differentiable as a complex function.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "non-analyticity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write Re(z) in z, z̄.", workingLatex: "\\operatorname{Re}(z)=\\frac{z+\\bar z}{2}.", explanation: "The real part is the average of z and its conjugate." },
        { stepNumber: 2, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{1}{2}\\big(0+1\\big)=\\frac{1}{2}.", explanation: "Hold z fixed: the z term gives 0 and the z̄ term gives 1, halved." },
        { stepNumber: 3, description: "Interpret.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{1}{2}\\neq 0\\ \\text{everywhere}.", explanation: "Since ∂f/∂z̄ is a non-zero constant, f is differentiable nowhere — the z̄-dependence is irreducible." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=\\dfrac{1}{2} \\), constant and non-zero, so \\( \\operatorname{Re}(z) \\) is nowhere complex-differentiable.",
      canonicalAnswer: "1/2",
    },
  },
  {
    id: "cm1c-015",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( f = z^{2}\\bar z \\), compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) and identify the only point where it vanishes. Is \\( f \\) analytic there?",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "analyticity vs differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate, holding z² fixed.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z^{2}\\frac{\\partial \\bar z}{\\partial \\bar z}=z^{2}.", explanation: "The z² factor is constant under ∂/∂z̄; only the z̄ factor contributes." },
        { stepNumber: 2, description: "Find the zero set.", workingLatex: "z^{2}=0 \\iff z=0.", explanation: "The derivative vanishes only at the origin." },
        { stepNumber: 3, description: "Distinguish differentiable from analytic.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}\\Big|_{z=0}=0,\\quad\\text{but not on any neighbourhood of }0.", explanation: "f is complex-differentiable at z=0 (the z̄-derivative vanishes there), yet not analytic, since analyticity needs ∂f/∂z̄=0 on an open set, which fails." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=z^{2} \\), zero only at \\( z=0 \\); \\( f \\) is differentiable at \\( z=0 \\) but nowhere analytic.",
      canonicalAnswer: "z^2",
    },
  },
  {
    id: "cm1c-016",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Express \\( f = x^{3}-3xy^{2} + i(3x^{2}y - y^{3}) \\) in terms of \\( z \\), verify \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\), and compute \\( f'(z) \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "complex derivative via d/dz"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the real and imaginary parts of z³.", workingLatex: "z^{3}=(x+iy)^{3}=(x^{3}-3xy^{2})+i(3x^{2}y-y^{3}).", explanation: "Binomial expansion of (x+iy)³ separates exactly into the given u and v." },
        { stepNumber: 2, description: "Identify f.", workingLatex: "f=z^{3}.", explanation: "The expression matches z³ term for term, with no z̄ present." },
        { stepNumber: 3, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial}{\\partial \\bar z}z^{3}=0.", explanation: "Confirms f is entire." },
        { stepNumber: 4, description: "Compute the derivative.", workingLatex: "f'(z)=\\frac{\\partial}{\\partial z}z^{3}=3z^{2}.", explanation: "The z-Wirtinger derivative gives f' since f is analytic." },
      ],
      finalAnswer: "\\( f=z^{3} \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\), and \\( f'(z)=3z^{2} \\).",
      canonicalAnswer: "3*z^2",
    },
  },
  {
    id: "cm1c-017",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f = \\bar z\\,e^{z} \\). Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\) and explain why \\( f \\) fails to be analytic anywhere, even though \\( e^{z} \\) is entire.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "product rule", "non-analyticity"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply the product rule in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\Big(\\frac{\\partial \\bar z}{\\partial \\bar z}\\Big)e^{z}+\\bar z\\,\\frac{\\partial}{\\partial \\bar z}e^{z}.", explanation: "Differentiate the product, treating z as constant." },
        { stepNumber: 2, description: "Evaluate each factor.", workingLatex: "\\frac{\\partial \\bar z}{\\partial \\bar z}=1,\\qquad \\frac{\\partial}{\\partial \\bar z}e^{z}=0.", explanation: "e^z has no z̄-dependence, so its z̄-derivative is zero." },
        { stepNumber: 3, description: "Combine.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=e^{z}.", explanation: "Only the z̄-factor contributes; e^z survives as a multiplier." },
        { stepNumber: 4, description: "Test analyticity.", workingLatex: "e^{z}\\neq 0\\ \\text{for all } z.", explanation: "Since e^z is never zero, ∂f/∂z̄ never vanishes, so the z̄-factor spoils analyticity everywhere." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=e^{z}\\neq 0 \\) everywhere; \\( f \\) is nowhere analytic.",
      canonicalAnswer: "e^z",
    },
  },
  {
    id: "cm1c-018",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Using \\( \\dfrac{\\partial}{\\partial z}=\\dfrac{1}{2}\\left(\\dfrac{\\partial}{\\partial x}-i\\dfrac{\\partial}{\\partial y}\\right) \\), verify that \\( \\dfrac{\\partial z}{\\partial z}=1 \\) and \\( \\dfrac{\\partial \\bar z}{\\partial z}=0 \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger operator", "independence of z and z̄"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Apply ∂/∂z to z=x+iy.", workingLatex: "\\frac{\\partial z}{\\partial z}=\\frac{1}{2}\\Big(\\frac{\\partial}{\\partial x}-i\\frac{\\partial}{\\partial y}\\Big)(x+iy)=\\frac{1}{2}(1-i\\cdot i)=\\frac{1}{2}(1+1)=1.", explanation: "∂x/∂x=1, ∂(iy)/∂y=i, and −i·i=1; the two real contributions add to give 1." },
        { stepNumber: 2, description: "Apply ∂/∂z to z̄=x−iy.", workingLatex: "\\frac{\\partial \\bar z}{\\partial z}=\\frac{1}{2}\\Big(\\frac{\\partial}{\\partial x}-i\\frac{\\partial}{\\partial y}\\Big)(x-iy)=\\frac{1}{2}(1-i(-i))=\\frac{1}{2}(1-1)=0.", explanation: "Here −i·(−i)=i²=−1, so the contributions cancel." },
        { stepNumber: 3, description: "State the conclusion.", workingLatex: "\\frac{\\partial z}{\\partial z}=1,\\qquad \\frac{\\partial \\bar z}{\\partial z}=0.", explanation: "This justifies treating z and z̄ as independent variables in the Wirtinger calculus." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial z}{\\partial z}=1 \\) and \\( \\dfrac{\\partial \\bar z}{\\partial z}=0 \\), confirming the independence of \\( z \\) and \\( \\bar z \\).",
    },
  },

  // --------- Challenge (12) ---------
  {
    id: "cm1c-019",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( g(x,y)=u(x,y)+iv(x,y) \\) be smooth, regarded as a function \\( g(z,\\bar z) \\) via \\( x=\\tfrac{1}{2}(z+\\bar z),\\ y=\\tfrac{1}{2i}(z-\\bar z) \\). Using the chain rule, show \\( \\dfrac{\\partial g}{\\partial \\bar z}=\\tfrac{1}{2}\\!\\left(\\dfrac{\\partial g}{\\partial x}+i\\dfrac{\\partial g}{\\partial y}\\right) \\) and deduce that \\( g \\) is differentiable in \\( z \\) iff \\( \\dfrac{\\partial g}{\\partial \\bar z}=0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["chain rule derivation", "Wirtinger operator", "Cauchy-Riemann equivalence"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the coordinate relations in z̄.", workingLatex: "\\frac{\\partial x}{\\partial \\bar z}=\\frac{1}{2},\\qquad \\frac{\\partial y}{\\partial \\bar z}=\\frac{1}{2i}(0-1)=-\\frac{1}{2i}=\\frac{i}{2}.", explanation: "From x=½(z+z̄) and y=(z−z̄)/(2i), holding z fixed; note −1/(2i)=i/2." },
        { stepNumber: 2, description: "Apply the multivariable chain rule.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=\\frac{\\partial g}{\\partial x}\\frac{\\partial x}{\\partial \\bar z}+\\frac{\\partial g}{\\partial y}\\frac{\\partial y}{\\partial \\bar z}=\\frac{1}{2}\\frac{\\partial g}{\\partial x}+\\frac{i}{2}\\frac{\\partial g}{\\partial y}.", explanation: "The chain rule converts the z̄-derivative into a combination of the real partials with the computed weights." },
        { stepNumber: 3, description: "Factor to the standard operator form.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=\\frac{1}{2}\\Big(\\frac{\\partial g}{\\partial x}+i\\frac{\\partial g}{\\partial y}\\Big).", explanation: "This is exactly the Wirtinger z̄-operator acting on g." },
        { stepNumber: 4, description: "Substitute g=u+iv and expand.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=\\frac{1}{2}\\big[(u_x-v_y)+i(u_y+v_x)\\big].", explanation: "Splitting into real and imaginary parts and using i²=−1, as in the equivalence calculation." },
        { stepNumber: 5, description: "Set the derivative to zero.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=0 \\iff u_x=v_y,\\ u_y=-v_x.", explanation: "Vanishing requires both real and imaginary parts zero — the Cauchy–Riemann equations." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\text{CR equations}\\iff g\\text{ complex-differentiable}\\iff \\frac{\\partial g}{\\partial \\bar z}=0.", explanation: "Since CR (with smoothness) is necessary and sufficient for differentiability, z̄-independence is the differentiability criterion; any genuine z̄-dependence destroys it." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial g}{\\partial \\bar z}=\\tfrac{1}{2}(g_x+i g_y)=\\tfrac{1}{2}[(u_x-v_y)+i(u_y+v_x)] \\), which is zero iff the CR equations hold, i.e. iff \\( g \\) is differentiable in \\( z \\).",
    },
  },
  {
    id: "cm1c-020",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that for any smooth real-valued \\( \\phi(x,y) \\), \\( \\dfrac{\\partial^{2}\\phi}{\\partial z\\,\\partial \\bar z}=\\dfrac{1}{4}\\nabla^{2}\\phi \\), and hence that \\( \\phi \\) is harmonic iff \\( \\dfrac{\\partial^{2}\\phi}{\\partial z\\,\\partial \\bar z}=0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed Wirtinger derivative", "Laplacian", "harmonic functions"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the two operators.", workingLatex: "\\frac{\\partial}{\\partial z}=\\frac{1}{2}\\Big(\\frac{\\partial}{\\partial x}-i\\frac{\\partial}{\\partial y}\\Big),\\qquad \\frac{\\partial}{\\partial \\bar z}=\\frac{1}{2}\\Big(\\frac{\\partial}{\\partial x}+i\\frac{\\partial}{\\partial y}\\Big).", explanation: "The standard Wirtinger operators in real coordinates." },
        { stepNumber: 2, description: "Compose them.", workingLatex: "\\frac{\\partial^{2}}{\\partial z\\,\\partial \\bar z}=\\frac{1}{4}\\Big(\\frac{\\partial}{\\partial x}-i\\frac{\\partial}{\\partial y}\\Big)\\Big(\\frac{\\partial}{\\partial x}+i\\frac{\\partial}{\\partial y}\\Big).", explanation: "Multiply the two operators; their product is a ¼-scaled difference of squares." },
        { stepNumber: 3, description: "Expand the product.", workingLatex: "=\\frac{1}{4}\\Big(\\frac{\\partial^{2}}{\\partial x^{2}}+i\\frac{\\partial^{2}}{\\partial x\\partial y}-i\\frac{\\partial^{2}}{\\partial y\\partial x}-i^{2}\\frac{\\partial^{2}}{\\partial y^{2}}\\Big).", explanation: "Distribute; the cross terms carry opposite signs." },
        { stepNumber: 4, description: "Cancel and simplify.", workingLatex: "=\\frac{1}{4}\\Big(\\frac{\\partial^{2}}{\\partial x^{2}}+\\frac{\\partial^{2}}{\\partial y^{2}}\\Big)=\\frac{1}{4}\\nabla^{2}.", explanation: "Mixed partials cancel (equality of mixed derivatives for smooth φ) and −i²=+1 restores the y-second-derivative." },
        { stepNumber: 5, description: "Apply to φ.", workingLatex: "\\frac{\\partial^{2}\\phi}{\\partial z\\,\\partial \\bar z}=\\frac{1}{4}\\nabla^{2}\\phi.", explanation: "The operator identity acts on the scalar field φ." },
        { stepNumber: 6, description: "Read off the harmonicity criterion.", workingLatex: "\\nabla^{2}\\phi=0 \\iff \\frac{\\partial^{2}\\phi}{\\partial z\\,\\partial \\bar z}=0.", explanation: "Since the two differ only by the non-zero factor ¼, one vanishes exactly when the other does." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial^{2}\\phi}{\\partial z\\,\\partial \\bar z}=\\tfrac{1}{4}\\nabla^{2}\\phi \\), so \\( \\phi \\) is harmonic iff the mixed Wirtinger derivative vanishes.",
    },
  },
  {
    id: "cm1c-021",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the most general smooth \\( f(z,\\bar z) \\) satisfying \\( \\dfrac{\\partial f}{\\partial \\bar z}=2\\bar z \\). Describe the structure of the answer.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["prescribed d/dz̄", "general solution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate in z̄ holding z fixed.", workingLatex: "f=\\int 2\\bar z\\,\\partial \\bar z = \\bar z^{2}+C.", explanation: "Treat z as a parameter; integrating 2z̄ in z̄ gives z̄² plus a 'constant'." },
        { stepNumber: 2, description: "Identify the constant of integration.", workingLatex: "C=h(z),\\quad h\\text{ arbitrary analytic (holomorphic) function of }z.", explanation: "The 'constant' under ∂/∂z̄ is any function with no z̄-dependence, i.e. an arbitrary analytic function of z." },
        { stepNumber: 3, description: "State the general solution.", workingLatex: "f(z,\\bar z)=\\bar z^{2}+h(z).", explanation: "Adding any analytic h(z) leaves ∂f/∂z̄ unchanged, so this is the full family." },
        { stepNumber: 4, description: "Verify.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=2\\bar z+h'(z)\\cdot 0=2\\bar z.", explanation: "h(z) is killed by ∂/∂z̄, confirming the prescribed derivative." },
      ],
      finalAnswer: "\\( f(z,\\bar z)=\\bar z^{2}+h(z) \\) for an arbitrary analytic \\( h(z) \\).",
      canonicalAnswer: "conjugate(z)^2 + h(z)",
    },
  },
  {
    id: "cm1c-022",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find the most general smooth \\( f \\) with \\( \\dfrac{\\partial f}{\\partial \\bar z}=z\\,\\bar z \\). Then determine which member (if any) is real-valued.",
    marks: 6,
    examStyle: true,
    tags: ["prescribed d/dz̄", "general solution"],
    yearCreated: 2026,
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate in z̄ with z held fixed.", workingLatex: "f=\\int z\\bar z\\,\\partial \\bar z = z\\,\\frac{\\bar z^{2}}{2}+h(z)=\\frac{1}{2}z\\bar z^{2}+h(z).", explanation: "z is a constant of the z̄-integration; the additive 'constant' is an arbitrary analytic h(z)." },
        { stepNumber: 2, description: "Verify the prescribed derivative.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{1}{2}z\\cdot 2\\bar z=z\\bar z.", explanation: "Differentiating back recovers the required right-hand side; h(z) contributes nothing." },
        { stepNumber: 3, description: "Impose reality: f must equal its conjugate.", workingLatex: "\\bar f=\\frac{1}{2}\\bar z z^{2}+\\overline{h(z)}.", explanation: "Conjugating swaps z and z̄; reality requires f=f̄." },
        { stepNumber: 4, description: "Compare the two non-analytic pieces.", workingLatex: "\\tfrac{1}{2}z\\bar z^{2}\\neq \\tfrac{1}{2}z^{2}\\bar z\\ \\text{in general}.", explanation: "The mixed monomials differ (one is z|z|²·... — explicitly ½z z̄² versus ½ z² z̄), and no analytic h(z) can repair this since h is z̄-independent while h̄ is z-independent." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "\\text{No choice of }h\\text{ makes }f\\text{ real-valued}.", explanation: "The asymmetric term ½z z̄² has no real counterpart obtainable by adding analytic-plus-anti-analytic pieces, so no real member exists." },
      ],
      finalAnswer: "\\( f=\\tfrac{1}{2}z\\bar z^{2}+h(z) \\) with \\( h \\) arbitrary analytic; no choice of \\( h \\) makes \\( f \\) real-valued.",
      canonicalAnswer: "(1/2)*z*conjugate(z)^2 + h(z)",
    },
  },
  {
    id: "cm1c-023",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( \\phi=\\operatorname{Re} F(z) \\) for some analytic \\( F \\). Show \\( \\dfrac{\\partial \\phi}{\\partial \\bar z}=\\tfrac{1}{2}\\overline{F'(z)} \\), and hence recover that \\( \\phi \\) is harmonic.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed Wirtinger derivative", "harmonic functions", "real part"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write the real part in z, z̄.", workingLatex: "\\phi=\\operatorname{Re}F=\\frac{1}{2}\\big(F(z)+\\overline{F(z)}\\big)=\\frac{1}{2}\\big(F(z)+\\overline{F}(\\bar z)\\big).", explanation: "The real part is the half-sum of F and its conjugate; since F is analytic, F̄ depends only on z̄ (write it as the conjugate-analytic function F̄(z̄))." },
        { stepNumber: 2, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial \\phi}{\\partial \\bar z}=\\frac{1}{2}\\Big(\\frac{\\partial F}{\\partial \\bar z}+\\frac{\\partial \\overline{F}(\\bar z)}{\\partial \\bar z}\\Big)=\\frac{1}{2}\\,\\overline{F'(z)}.", explanation: "F(z) is killed by ∂/∂z̄ (it is analytic), and differentiating the conjugate-analytic part in z̄ gives the conjugate of F'." },
        { stepNumber: 3, description: "Apply the mixed-derivative Laplacian identity.", workingLatex: "\\frac{1}{4}\\nabla^{2}\\phi=\\frac{\\partial}{\\partial z}\\Big(\\frac{\\partial \\phi}{\\partial \\bar z}\\Big)=\\frac{\\partial}{\\partial z}\\Big(\\tfrac{1}{2}\\overline{F'(z)}\\Big).", explanation: "Use ∂²/∂z∂z̄=¼∇² from the operator identity, applied to the result of step 2." },
        { stepNumber: 4, description: "Differentiate the conjugate-analytic factor in z.", workingLatex: "\\frac{\\partial}{\\partial z}\\,\\overline{F'(z)}=0.", explanation: "F'(z)‾ depends only on z̄, so its ∂/∂z vanishes." },
        { stepNumber: 5, description: "Conclude harmonicity.", workingLatex: "\\frac{1}{4}\\nabla^{2}\\phi=0\\implies \\nabla^{2}\\phi=0.", explanation: "The mixed Wirtinger derivative of φ is zero, so φ is harmonic — the real part of any analytic function." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial \\phi}{\\partial \\bar z}=\\tfrac{1}{2}\\overline{F'(z)} \\); since \\( \\partial_z \\) of this is zero, \\( \\nabla^{2}\\phi=4\\partial_z\\partial_{\\bar z}\\phi=0 \\), so \\( \\phi \\) is harmonic.",
    },
  },
  {
    id: "cm1c-024",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Express \\( f = \\dfrac{x-iy}{x^{2}+y^{2}} \\) in terms of \\( z,\\bar z \\), compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\), and decide where \\( f \\) is analytic. (Take \\( z\\neq 0 \\).)",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["express in z and z̄", "analyticity test"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify numerator and denominator.", workingLatex: "x-iy=\\bar z,\\qquad x^{2}+y^{2}=z\\bar z.", explanation: "The numerator is the conjugate; the denominator is the squared modulus." },
        { stepNumber: 2, description: "Form the quotient.", workingLatex: "f=\\frac{\\bar z}{z\\bar z}=\\frac{1}{z}.", explanation: "The z̄ factors cancel, leaving a pure function of z." },
        { stepNumber: 3, description: "Differentiate in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial}{\\partial \\bar z}\\Big(\\frac{1}{z}\\Big)=0.", explanation: "After cancellation no z̄ remains, so the z̄-derivative vanishes." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "f=\\frac{1}{z}\\ \\text{analytic on}\\ \\mathbb{C}\\setminus\\{0\\}.", explanation: "Despite its conjugate-laden appearance, f is 1/z, analytic on the punctured plane with a simple pole at 0." },
      ],
      finalAnswer: "\\( f=\\dfrac{1}{z} \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=0 \\); \\( f \\) is analytic on \\( \\mathbb{C}\\setminus\\{0\\} \\).",
      canonicalAnswer: "1/z",
    },
  },
  {
    id: "cm1c-025",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( f=|z|^{2}z = z^{2}\\bar z \\), compute both \\( \\dfrac{\\partial f}{\\partial z} \\) and \\( \\dfrac{\\partial f}{\\partial \\bar z} \\). At \\( z=0 \\), evaluate the complex derivative \\( f'(0) \\) and explain why \\( f \\) is still not analytic at \\( 0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "differentiable vs analytic"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the z-derivative.", workingLatex: "\\frac{\\partial f}{\\partial z}=\\frac{\\partial}{\\partial z}\\big(z^{2}\\bar z\\big)=2z\\bar z.", explanation: "Differentiate in z with z̄ fixed; the power rule gives 2z times the z̄ factor." },
        { stepNumber: 2, description: "Compute the z̄-derivative.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z^{2}.", explanation: "z² is constant under ∂/∂z̄; only the single z̄ factor differentiates." },
        { stepNumber: 3, description: "Locate where the z̄-derivative vanishes.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z^{2}=0\\iff z=0.", explanation: "f is complex-differentiable only at z=0, where the obstruction z² vanishes." },
        { stepNumber: 4, description: "Evaluate the complex derivative at 0.", workingLatex: "f'(0)=\\frac{\\partial f}{\\partial z}\\Big|_{0}=2\\cdot 0\\cdot 0=0.", explanation: "At a point where ∂f/∂z̄=0, the complex derivative equals ∂f/∂z; here it is 0." },
        { stepNumber: 5, description: "Explain the failure of analyticity.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z^{2}\\not\\equiv 0\\ \\text{on any disc about }0.", explanation: "Analyticity needs the z̄-derivative to vanish on an open neighbourhood; it vanishes only at the single point 0, so f is differentiable at 0 but not analytic there." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial z}=2z\\bar z \\), \\( \\dfrac{\\partial f}{\\partial \\bar z}=z^{2} \\); \\( f'(0)=0 \\) but \\( f \\) is not analytic at \\( 0 \\) since \\( \\partial f/\\partial \\bar z \\) is non-zero on every punctured disc about \\( 0 \\).",
      canonicalAnswer: "f'(0)=0",
    },
  },
  {
    id: "cm1c-026",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f \\) and \\( \\bar f \\) are both analytic on a domain \\( D \\). Using the Wirtinger operators, show that \\( f \\) is constant on \\( D \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger operator", "constancy argument"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Use analyticity of f.", workingLatex: "f\\ \\text{analytic}\\implies \\frac{\\partial f}{\\partial \\bar z}=0.", explanation: "Analyticity is exactly z̄-independence." },
        { stepNumber: 2, description: "Use analyticity of f̄, then conjugate.", workingLatex: "\\bar f\\ \\text{analytic}\\implies \\frac{\\partial \\bar f}{\\partial \\bar z}=0.", explanation: "Apply the same criterion to the (assumed analytic) conjugate function." },
        { stepNumber: 3, description: "Relate to the z-derivative of f via conjugation.", workingLatex: "\\overline{\\Big(\\frac{\\partial f}{\\partial z}\\Big)}=\\frac{\\partial \\bar f}{\\partial \\bar z}=0\\implies \\frac{\\partial f}{\\partial z}=0.", explanation: "Conjugating the operator identity ∂/∂z swaps to ∂/∂z̄ acting on f̄; both real partials of the conjugate vanish, so ∂f/∂z=0 too." },
        { stepNumber: 4, description: "Combine the two vanishing derivatives.", workingLatex: "\\frac{\\partial f}{\\partial z}=0\\ \\text{and}\\ \\frac{\\partial f}{\\partial \\bar z}=0.", explanation: "Both Wirtinger derivatives are zero throughout D." },
        { stepNumber: 5, description: "Translate back to real partials.", workingLatex: "\\frac{\\partial f}{\\partial x}=\\frac{\\partial f}{\\partial z}+\\frac{\\partial f}{\\partial \\bar z}=0,\\qquad \\frac{\\partial f}{\\partial y}=i\\Big(\\frac{\\partial f}{\\partial z}-\\frac{\\partial f}{\\partial \\bar z}\\Big)=0.", explanation: "The inverse relations express ∂/∂x and ∂/∂y as combinations of the Wirtinger operators; both vanish." },
        { stepNumber: 6, description: "Conclude constancy.", workingLatex: "f_x=f_y=0\\ \\text{on connected }D\\implies f=\\text{const}.", explanation: "Zero gradient on a connected domain forces f to be constant." },
      ],
      finalAnswer: "Both \\( \\partial f/\\partial z=0 \\) and \\( \\partial f/\\partial \\bar z=0 \\), so \\( f_x=f_y=0 \\) and \\( f \\) is constant on \\( D \\).",
    },
  },
  {
    id: "cm1c-027",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Find all smooth \\( f \\) with \\( \\dfrac{\\partial f}{\\partial \\bar z}=3\\bar z^{2} \\) that are also real-valued, or show none exist.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["prescribed d/dz̄", "reality condition"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate in z̄.", workingLatex: "f=\\int 3\\bar z^{2}\\,\\partial \\bar z=\\bar z^{3}+h(z),\\quad h\\text{ analytic}.", explanation: "z is a parameter; the additive 'constant' is any z̄-independent (analytic) function." },
        { stepNumber: 2, description: "Impose reality.", workingLatex: "f=\\bar f \\iff \\bar z^{3}+h(z)=z^{3}+\\overline{h(z)}.", explanation: "Conjugate the candidate and require equality with itself." },
        { stepNumber: 3, description: "Separate analytic and anti-analytic parts.", workingLatex: "h(z)-z^{3}=\\overline{h(z)}-\\bar z^{3}.", explanation: "Rearrange so each side is the conjugate of the other; the left depends on z, the right on z̄." },
        { stepNumber: 4, description: "Argue both sides are a real constant.", workingLatex: "h(z)-z^{3}=\\overline{h(z)-z^{3}}=c\\in\\mathbb{R}.", explanation: "A quantity equal to its own conjugate and analytic must be a real constant (its z̄-derivative is zero and it is real)." },
        { stepNumber: 5, description: "Solve for h and assemble f.", workingLatex: "h(z)=z^{3}+c\\implies f=\\bar z^{3}+z^{3}+c=2\\operatorname{Re}(z^{3})+c.", explanation: "Substituting back, the analytic z³ pairs with z̄³ to give twice the real part." },
        { stepNumber: 6, description: "State the family.", workingLatex: "f=2\\operatorname{Re}(z^{3})+c,\\quad c\\in\\mathbb{R}.", explanation: "These are exactly the real-valued solutions; one-parameter family indexed by the real constant c." },
      ],
      finalAnswer: "\\( f=\\bar z^{3}+z^{3}+c=2\\operatorname{Re}(z^{3})+c \\) for a real constant \\( c \\).",
      canonicalAnswer: "2*Re(z^3) + c",
    },
  },
  {
    id: "cm1c-028",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( f=g(z)\\,\\bar z \\) where \\( g \\) is analytic. Compute \\( \\dfrac{\\partial f}{\\partial \\bar z} \\), and find the set of points at which \\( f \\) is complex-differentiable in terms of the zeros of \\( g \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "differentiability set"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Differentiate the product in z̄.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=\\frac{\\partial g}{\\partial \\bar z}\\,\\bar z+g(z)\\,\\frac{\\partial \\bar z}{\\partial \\bar z}.", explanation: "Product rule treating z as fixed." },
        { stepNumber: 2, description: "Use analyticity of g.", workingLatex: "\\frac{\\partial g}{\\partial \\bar z}=0\\implies \\frac{\\partial f}{\\partial \\bar z}=g(z).", explanation: "g is analytic so its z̄-derivative vanishes, leaving only the second term." },
        { stepNumber: 3, description: "Apply the differentiability criterion.", workingLatex: "f\\ \\text{differentiable at }z_0 \\iff \\frac{\\partial f}{\\partial \\bar z}\\Big|_{z_0}=0 \\iff g(z_0)=0.", explanation: "Pointwise complex-differentiability requires the z̄-derivative to vanish at that point." },
        { stepNumber: 4, description: "Describe the set.", workingLatex: "\\{z_0:\\ f\\ \\text{differentiable at }z_0\\}=\\{z_0:\\ g(z_0)=0\\}.", explanation: "f is differentiable exactly at the zeros of g." },
        { stepNumber: 5, description: "Comment on analyticity.", workingLatex: "\\text{zeros of analytic }g\\ \\text{are isolated (unless }g\\equiv 0).", explanation: "Unless g≡0, the zeros form an isolated set with no interior, so f is differentiable on a discrete set but analytic nowhere." },
      ],
      finalAnswer: "\\( \\dfrac{\\partial f}{\\partial \\bar z}=g(z) \\); \\( f \\) is complex-differentiable exactly at the zeros of \\( g \\) (and, unless \\( g\\equiv0 \\), analytic nowhere since those zeros are isolated).",
      canonicalAnswer: "df/dconjugate(z)=g(z); differentiable where g(z)=0",
    },
  },
  {
    id: "cm1c-029",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Express \\( u=e^{x}\\cos y \\) in terms of \\( z,\\bar z \\), then use \\( \\dfrac{\\partial^{2}u}{\\partial z\\,\\partial \\bar z} \\) to confirm \\( u \\) is harmonic, and read off an analytic \\( F \\) with \\( \\operatorname{Re}F=u \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["mixed Wirtinger derivative", "harmonic functions", "real part"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write u as a real part.", workingLatex: "u=e^{x}\\cos y=\\operatorname{Re}\\big(e^{x}e^{iy}\\big)=\\operatorname{Re}(e^{z}).", explanation: "Euler's formula identifies e^x cos y as the real part of e^z." },
        { stepNumber: 2, description: "Express in z, z̄.", workingLatex: "u=\\frac{1}{2}\\big(e^{z}+e^{\\bar z}\\big).", explanation: "Re(w)=½(w+w̄); here w=e^z has conjugate e^{z̄}." },
        { stepNumber: 3, description: "Take the z̄-derivative.", workingLatex: "\\frac{\\partial u}{\\partial \\bar z}=\\frac{1}{2}e^{\\bar z}.", explanation: "e^z is z̄-independent (gives 0); e^{z̄} differentiates to itself in z̄." },
        { stepNumber: 4, description: "Take the mixed second derivative.", workingLatex: "\\frac{\\partial^{2}u}{\\partial z\\,\\partial \\bar z}=\\frac{\\partial}{\\partial z}\\Big(\\frac{1}{2}e^{\\bar z}\\Big)=0.", explanation: "e^{z̄} is z-independent, so the mixed derivative vanishes." },
        { stepNumber: 5, description: "Conclude harmonicity.", workingLatex: "\\nabla^{2}u=4\\frac{\\partial^{2}u}{\\partial z\\,\\partial \\bar z}=0.", explanation: "By the operator identity, vanishing mixed Wirtinger derivative means u is harmonic." },
        { stepNumber: 6, description: "Read off F.", workingLatex: "F(z)=e^{z},\\qquad \\operatorname{Re}F=e^{x}\\cos y=u.", explanation: "The analytic part whose real part is u is simply e^z (up to an added imaginary constant)." },
      ],
      finalAnswer: "\\( u=\\tfrac{1}{2}(e^{z}+e^{\\bar z}) \\), \\( \\partial^2 u/\\partial z\\partial\\bar z=0 \\) so \\( u \\) is harmonic, with \\( F(z)=e^{z} \\) (any added imaginary constant allowed).",
      canonicalAnswer: "F(z)=e^z",
    },
  },
  {
    id: "cm1c-030",
    topicRef: "cm1c",
    topicTitle: "The Wirtinger d/dz̄ viewpoint",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "A smooth function satisfies \\( \\dfrac{\\partial f}{\\partial \\bar z}=z \\) and \\( f(0)=0 \\), and is required to be real on the real axis (\\( f(x)=\\overline{f(x)} \\) for real \\( x \\)). Find the general such \\( f \\) and its most symmetric representative.",
    marks: 7,
    examStyle: true,
    yearCreated: 2026,
    tags: ["prescribed d/dz̄", "boundary condition", "general solution"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Integrate the prescribed derivative in z̄.", workingLatex: "f=\\int z\\,\\partial\\bar z = z\\bar z + h(z),\\quad h\\text{ analytic}.", explanation: "z is constant under the z̄-integration; the additive analytic h(z) is the homogeneous part." },
        { stepNumber: 2, description: "Verify.", workingLatex: "\\frac{\\partial f}{\\partial \\bar z}=z+0=z.", explanation: "h(z) is annihilated by ∂/∂z̄; the zz̄ term returns z." },
        { stepNumber: 3, description: "Apply f(0)=0.", workingLatex: "f(0)=0\\cdot 0+h(0)=h(0)=0.", explanation: "At z=0 the zz̄ term vanishes, forcing h(0)=0." },
        { stepNumber: 4, description: "Apply reality on the real axis.", workingLatex: "x\\ \\text{real}:\\ f(x)=x\\cdot x+h(x)=x^{2}+h(x)\\ \\text{must be real}.", explanation: "On y=0, z=z̄=x, so zz̄=x²; reality then forces h(x) to be real for all real x." },
        { stepNumber: 5, description: "Translate the real-axis condition into the coefficients of h.", workingLatex: "h(x)\\in\\mathbb{R}\\ \\forall x\\in\\mathbb{R}\\iff h\\ \\text{has real Taylor coefficients}.", explanation: "An analytic function real on the real axis has a real power series (Schwarz reflection); equivalently h(z̄)=h(z)‾." },
        { stepNumber: 6, description: "State the general solution.", workingLatex: "f=z\\bar z + h(z),\\quad h\\ \\text{analytic},\\ h(0)=0,\\ \\text{real coefficients}.", explanation: "This is the full family meeting derivative, value, and reality constraints." },
        { stepNumber: 7, description: "Pick the symmetric representative.", workingLatex: "h\\equiv 0:\\quad f=z\\bar z=|z|^{2}.", explanation: "The simplest, fully real and rotationally symmetric member takes h=0, giving f=|z|² which automatically satisfies all three conditions." },
      ],
      finalAnswer: "\\( f=z\\bar z+h(z) \\) with \\( h \\) analytic, \\( h(0)=0 \\), real Taylor coefficients; the symmetric representative is \\( f=|z|^{2} \\).",
      canonicalAnswer: "z*conjugate(z) + h(z)",
    },
  },
];
