import { Question } from "@/lib/types";

/*
 * Complex Methods — cm1d
 * CR satisfied yet not differentiable
 * Topic group: Cauchy–Riemann equations & analyticity
 *
 * 30 fully-worked questions seeded from Cambridge Part IB Complex Methods
 * Example Sheet 1, Q1(ii): the canonical counterexample f(z)=z^5/|z|^4 (z!=0),
 * f(0)=0, where the Cauchy–Riemann equations hold at the origin yet f fails to
 * be complex-differentiable there. The recurring theme: CR at a point is
 * NECESSARY but not SUFFICIENT for differentiability — sufficiency also needs
 * the four real partials to be continuous in a neighbourhood of the point.
 * The path-dependent limit of f(z)/z along z = r e^{i theta} is the diagnostic.
 *
 * Split: 6 Foundation / 12 Standard / 12 Challenge.
 * Conventions: worked-solution fractions use big \frac; stems use \dfrac.
 * Every difference-quotient and directional-limit computation re-derived from
 * scratch and checked. "Show that" items omit canonicalAnswer.
 */
export const questions: Question[] = [
  // --------- Foundation (6) ---------
  {
    id: "cm1d-001",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Let \\( f(z)=\\dfrac{z^5}{|z|^4} \\) for \\( z\\neq 0 \\) and \\( f(0)=0 \\). Restrict to the real axis \\( z=x \\). Simplify \\( f(x) \\) and hence write down \\( u(x,0) \\) and \\( v(x,0) \\), where \\( f=u+iv \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "difference quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Substitute a real argument.", workingLatex: "z=x\\in\\mathbb{R}\\setminus\\{0\\} \\implies z^5=x^5,\\quad |z|^4=x^4.", explanation: "On the real axis the modulus is just \\(|x|\\), so \\(|z|^4=|x|^4=x^4\\) since the fourth power kills the sign." },
        { stepNumber: 2, description: "Form the quotient.", workingLatex: "f(x)=\\frac{x^5}{x^4}=x.", explanation: "The pathological factor \\(|z|^{4}\\) cancels cleanly on this axis, leaving the identity." },
        { stepNumber: 3, description: "Read off the parts.", workingLatex: "u(x,0)=x,\\qquad v(x,0)=0.", explanation: "The restriction to the real axis is purely real, so the imaginary part vanishes identically." },
      ],
      finalAnswer: "\\( f(x)=x,\\quad u(x,0)=x,\\ v(x,0)=0. \\)",
      canonicalAnswer: "u(x,0)=x, v(x,0)=0",
    },
  },
  {
    id: "cm1d-002",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "With \\( f(z)=\\dfrac{z^5}{|z|^4} \\) for \\( z\\neq 0 \\), \\( f(0)=0 \\), restrict to the imaginary axis \\( z=iy \\). Simplify \\( f(iy) \\) and write down \\( u(0,y) \\) and \\( v(0,y) \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "difference quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute the fifth power of iy.", workingLatex: "z=iy \\implies z^5=(i)^5 y^5 = i\\,y^5,", explanation: "Since \\(i^5=(i^4)\\,i=i\\), the fifth power of \\(iy\\) is purely imaginary." },
        { stepNumber: 2, description: "Compute the modulus factor.", workingLatex: "|z|^4=|iy|^4=y^4.", explanation: "The modulus of \\(iy\\) is \\(|y|\\), and the fourth power removes the sign." },
        { stepNumber: 3, description: "Form the quotient.", workingLatex: "f(iy)=\\frac{i\\,y^5}{y^4}=i\\,y.", explanation: "Again the troublesome modulus factor cancels on this special axis." },
        { stepNumber: 4, description: "Read off the parts.", workingLatex: "u(0,y)=0,\\qquad v(0,y)=y.", explanation: "On the imaginary axis the value is purely imaginary, so the real part is zero." },
      ],
      finalAnswer: "\\( f(iy)=iy,\\quad u(0,y)=0,\\ v(0,y)=y. \\)",
      canonicalAnswer: "u(0,y)=0, v(0,y)=y",
    },
  },
  {
    id: "cm1d-003",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given that on the real axis the real part of \\( f(z)=z^5/|z|^4 \\) is \\( u(x,0)=x \\) and \\( u(0,y)=0 \\) on the imaginary axis, evaluate the partial derivatives \\( u_x(0,0) \\) and \\( u_y(0,0) \\) directly from difference quotients.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["partial derivatives", "difference quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Difference quotient in x.", workingLatex: "u_x(0,0)=\\lim_{h\\to 0}\\frac{u(h,0)-u(0,0)}{h}=\\lim_{h\\to0}\\frac{h-0}{h}.", explanation: "Use the value \\(u(h,0)=h\\) found on the real axis and \\(u(0,0)=0\\)." },
        { stepNumber: 2, description: "Evaluate.", workingLatex: "u_x(0,0)=\\lim_{h\\to0}1=1.", explanation: "The quotient is identically \\(1\\) for every nonzero \\(h\\)." },
        { stepNumber: 3, description: "Difference quotient in y.", workingLatex: "u_y(0,0)=\\lim_{k\\to0}\\frac{u(0,k)-u(0,0)}{k}=\\lim_{k\\to0}\\frac{0-0}{k}=0.", explanation: "Along the imaginary axis the real part is identically zero, so its \\(y\\)-derivative at the origin is zero." },
      ],
      finalAnswer: "\\( u_x(0,0)=1,\\quad u_y(0,0)=0. \\)",
      canonicalAnswer: "u_x(0,0)=1, u_y(0,0)=0",
    },
  },
  {
    id: "cm1d-004",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Given that on the real axis the imaginary part of \\( f(z)=z^5/|z|^4 \\) is \\( v(x,0)=0 \\) and on the imaginary axis \\( v(0,y)=y \\), evaluate \\( v_x(0,0) \\) and \\( v_y(0,0) \\) from difference quotients.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["partial derivatives", "difference quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Difference quotient in x.", workingLatex: "v_x(0,0)=\\lim_{h\\to0}\\frac{v(h,0)-v(0,0)}{h}=\\lim_{h\\to0}\\frac{0-0}{h}=0.", explanation: "On the real axis the imaginary part vanishes identically, so its \\(x\\)-derivative at \\(0\\) is zero." },
        { stepNumber: 2, description: "Difference quotient in y.", workingLatex: "v_y(0,0)=\\lim_{k\\to0}\\frac{v(0,k)-v(0,0)}{k}=\\lim_{k\\to0}\\frac{k-0}{k}=1.", explanation: "On the imaginary axis \\(v(0,k)=k\\), so the quotient is identically \\(1\\)." },
      ],
      finalAnswer: "\\( v_x(0,0)=0,\\quad v_y(0,0)=1. \\)",
      canonicalAnswer: "v_x(0,0)=0, v_y(0,0)=1",
    },
  },
  {
    id: "cm1d-005",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "Using \\( u_x(0,0)=1,\\ u_y(0,0)=0,\\ v_x(0,0)=0,\\ v_y(0,0)=1 \\) for \\( f(z)=z^5/|z|^4 \\), state whether the Cauchy–Riemann equations \\( u_x=v_y,\\ u_y=-v_x \\) hold at the origin.",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "verification"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Check the first CR equation.", workingLatex: "u_x(0,0)=1,\\qquad v_y(0,0)=1 \\implies u_x=v_y.", explanation: "Both equal \\(1\\), so the first Cauchy–Riemann equation is satisfied at the origin." },
        { stepNumber: 2, description: "Check the second CR equation.", workingLatex: "u_y(0,0)=0,\\qquad -v_x(0,0)=-0=0 \\implies u_y=-v_x.", explanation: "Both sides are zero, so the second equation also holds." },
        { stepNumber: 3, description: "Conclude.", workingLatex: "u_x=v_y,\\quad u_y=-v_x \\text{ at } z=0.", explanation: "The CR equations are satisfied at the origin — though, as later questions show, this does not force differentiability there." },
      ],
      finalAnswer: "\\( \\text{Both CR equations hold at } z=0. \\)",
    },
  },
  {
    id: "cm1d-006",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Foundation",
    answerType: "expression",
    questionText: "For \\( f(z)=\\dfrac{z^5}{|z|^4}\\ (z\\neq0) \\), use \\( |z|^4=(z\\bar z)^2 \\) to rewrite \\( f \\) as a quotient of powers of \\( z \\) and \\( \\bar z \\).",
    marks: 2,
    examStyle: false,
    yearCreated: 2026,
    tags: ["conjugate variables", "z and zbar"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Express the modulus via z and zbar.", workingLatex: "|z|^2=z\\bar z \\implies |z|^4=(z\\bar z)^2=z^2\\bar z^{\\,2}.", explanation: "The squared modulus is \\(z\\bar z\\); squaring again gives the fourth power." },
        { stepNumber: 2, description: "Substitute into f.", workingLatex: "f=\\frac{z^5}{z^2\\bar z^{\\,2}}=\\frac{z^{3}}{\\bar z^{\\,2}}.", explanation: "Cancel two powers of \\(z\\) from numerator and denominator." },
        { stepNumber: 3, description: "Note the zbar dependence.", workingLatex: "f=z^{3}\\,\\bar z^{\\,-2}.", explanation: "The explicit \\(\\bar z\\) dependence flags non-holomorphy: a genuinely differentiable function must be free of \\(\\bar z\\)." },
      ],
      finalAnswer: "\\( f=\\dfrac{z^{3}}{\\bar z^{\\,2}}. \\)",
      canonicalAnswer: "z^3/zbar^2",
    },
  },
  // --------- Standard (12) ---------
  {
    id: "cm1d-007",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Show that for \\( f(z)=\\dfrac{z^5}{|z|^4}\\ (z\\neq0),\\ f(0)=0 \\), the complex difference quotient along the ray \\( z=r e^{i\\theta}\\ (r\\to0^+) \\) equals \\( e^{4i\\theta} \\), and deduce that \\( f \\) is not differentiable at \\( 0 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the difference quotient.", workingLatex: "\\frac{f(z)-f(0)}{z-0}=\\frac{1}{z}\\cdot\\frac{z^5}{|z|^4}=\\frac{z^4}{|z|^4}.", explanation: "Since \\(f(0)=0\\), the quotient is \\(f(z)/z\\); one power of \\(z\\) cancels." },
        { stepNumber: 2, description: "Insert polar form.", workingLatex: "z=re^{i\\theta}\\implies z^4=r^4 e^{4i\\theta},\\quad |z|^4=r^4.", explanation: "In polar coordinates the modulus is \\(r\\), so \\(|z|^4=r^4\\) cancels the magnitude of \\(z^4\\)." },
        { stepNumber: 3, description: "Simplify the quotient.", workingLatex: "\\frac{z^4}{|z|^4}=\\frac{r^4 e^{4i\\theta}}{r^4}=e^{4i\\theta}.", explanation: "The radial dependence cancels entirely; only the argument survives." },
        { stepNumber: 4, description: "Take the limit along the ray.", workingLatex: "\\lim_{r\\to0^+}\\frac{f(re^{i\\theta})}{re^{i\\theta}}=e^{4i\\theta}.", explanation: "The expression is independent of \\(r\\), so the limit along each fixed ray is exactly \\(e^{4i\\theta}\\)." },
        { stepNumber: 5, description: "Compare different rays.", workingLatex: "\\theta=0:\\ e^{0}=1;\\qquad \\theta=\\tfrac{\\pi}{4}:\\ e^{i\\pi}=-1.", explanation: "Two rays give different limits, so the limit defining \\(f'(0)\\) does not exist." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "f'(0)\\ \\text{does not exist} \\implies f \\text{ not differentiable at } 0.", explanation: "A complex derivative requires a single limit independent of the approach direction; here it is not." },
      ],
      finalAnswer: "\\( \\dfrac{f(z)}{z}=e^{4i\\theta}\\text{; direction-dependent, so } f \\text{ is not differentiable at } 0. \\)",
    },
  },
  {
    id: "cm1d-008",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Consider \\( g(z)=\\dfrac{z^3}{|z|^2}\\ (z\\neq0),\\ g(0)=0 \\). By restricting to the coordinate axes, find \\( u_x,u_y,v_x,v_y \\) at the origin and test the Cauchy–Riemann equations there.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "difference quotient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Restrict to the real axis.", workingLatex: "z=x:\\ g(x)=\\frac{x^3}{x^2}=x \\implies u(x,0)=x,\\ v(x,0)=0.", explanation: "The modulus factor cancels on the real axis, leaving the identity." },
        { stepNumber: 2, description: "Restrict to the imaginary axis.", workingLatex: "z=iy:\\ z^3=(i)^3y^3=-iy^3,\\ |z|^2=y^2 \\implies g(iy)=\\frac{-iy^3}{y^2}=-iy.", explanation: "Here \\(i^3=-i\\), so the imaginary-axis value is \\(-iy\\): \\(u(0,y)=0,\\ v(0,y)=-y\\)." },
        { stepNumber: 3, description: "Differentiate along the axes.", workingLatex: "u_x=1,\\ v_x=0;\\qquad u_y=0,\\ v_y=-1.", explanation: "Each partial is the slope of a linear restriction, read off directly." },
        { stepNumber: 4, description: "Test CR.", workingLatex: "u_x=1\\neq v_y=-1.", explanation: "The first Cauchy–Riemann equation already fails, so \\(g\\) is certainly not differentiable at \\(0\\)." },
        { stepNumber: 5, description: "Contrast with cm1d's z^5 case.", workingLatex: "\\text{Here CR fails at } 0;\\ \\text{for } z^5/|z|^4 \\text{ CR held yet } f' \\text{ still failed.}", explanation: "The odd-power exponent changes the sign pattern: the \\(z^3/|z|^2\\) map is not even a CR-satisfying borderline case." },
      ],
      finalAnswer: "\\( u_x=1,\\,u_y=0,\\,v_x=0,\\,v_y=-1;\\ \\text{CR fails at } 0. \\)",
    },
  },
  {
    id: "cm1d-009",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "State carefully the sufficient condition for a function \\( f=u+iv \\) to be complex-differentiable at a point \\( z_0 \\), and explain in one sentence why \\( f(z)=z^5/|z|^4 \\) at \\( 0 \\) does not contradict it despite satisfying CR there.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sufficiency theorem", "continuity of partials"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "State the sufficient condition.", workingLatex: "u,v\\ \\text{have continuous first partials near } z_0\\ \\text{AND}\\ u_x=v_y,\\ u_y=-v_x\\ \\text{at } z_0.", explanation: "Continuity of the four partials in a neighbourhood together with CR at the point guarantees differentiability at the point." },
        { stepNumber: 2, description: "Identify the missing hypothesis.", workingLatex: "\\text{CR holds at } 0,\\ \\text{but the partials of } u,v\\ \\text{are NOT continuous at } 0.", explanation: "Off the axes the partials oscillate with direction and do not approach the origin's values, breaking continuity." },
        { stepNumber: 3, description: "Resolve the apparent paradox.", workingLatex: "\\text{No contradiction: the theorem's continuity hypothesis is violated.}", explanation: "CR alone is necessary, not sufficient; the sufficiency theorem simply does not apply here." },
      ],
      finalAnswer: "\\( \\text{Sufficient: CR at } z_0 \\text{ plus continuous partials near } z_0;\\ \\text{the latter fails for } z^5/|z|^4. \\)",
    },
  },
  {
    id: "cm1d-010",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( f(z)=z^5/|z|^4\\ (z\\neq0),\\ f(0)=0 \\), compute the limit of \\( f(z)/z \\) as \\( z\\to0 \\) along (a) the line \\( y=x \\) approached from the first quadrant, and (b) the negative real axis. Are they equal?",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Reduce to the angular factor.", workingLatex: "\\frac{f(z)}{z}=\\frac{z^4}{|z|^4}=e^{4i\\theta},\\quad z=re^{i\\theta}.", explanation: "As established, the difference quotient depends only on the argument \\(\\theta\\)." },
        { stepNumber: 2, description: "Path (a): y=x in the first quadrant.", workingLatex: "\\theta=\\frac{\\pi}{4}\\implies e^{4i\\theta}=e^{i\\pi}=-1.", explanation: "The ray \\(y=x,\\ x>0\\) has argument \\(\\pi/4\\); four times that is \\(\\pi\\)." },
        { stepNumber: 3, description: "Path (b): negative real axis.", workingLatex: "\\theta=\\pi\\implies e^{4i\\theta}=e^{4i\\pi}=1.", explanation: "The negative real axis has argument \\(\\pi\\); \\(4\\pi\\) is a full multiple of \\(2\\pi\\), giving \\(1\\)." },
        { stepNumber: 4, description: "Compare.", workingLatex: "-1\\neq 1.", explanation: "The two directional limits disagree, confirming once more that \\(f'(0)\\) does not exist." },
      ],
      finalAnswer: "\\( \\text{(a) } -1,\\ \\text{(b) } 1;\\ \\text{not equal, so the limit does not exist.} \\)",
      canonicalAnswer: "(a) -1, (b) 1; unequal",
    },
  },
  {
    id: "cm1d-011",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( h(z)=\\dfrac{\\bar z^{\\,2}}{|z|^2}\\ (z\\neq0),\\ h(0)=0 \\). Show \\( h(z)/z \\) has a direction-dependent limit at \\( 0 \\), and find its value along the ray \\( z=re^{i\\theta} \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "conjugate variables"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Rewrite using z and zbar.", workingLatex: "|z|^2=z\\bar z \\implies h=\\frac{\\bar z^{\\,2}}{z\\bar z}=\\frac{\\bar z}{z}.", explanation: "One factor of \\(\\bar z\\) cancels, exposing the pure ratio \\(\\bar z/z\\)." },
        { stepNumber: 2, description: "Form the difference quotient.", workingLatex: "\\frac{h(z)}{z}=\\frac{\\bar z}{z^2}.", explanation: "Divide the simplified \\(h=\\bar z/z\\) by \\(z\\)." },
        { stepNumber: 3, description: "Insert polar form.", workingLatex: "z=re^{i\\theta},\\ \\bar z=re^{-i\\theta}\\implies \\frac{\\bar z}{z^2}=\\frac{re^{-i\\theta}}{r^2 e^{2i\\theta}}=\\frac{e^{-3i\\theta}}{r}.", explanation: "The magnitude is \\(1/r\\), which blows up; the phase carries the angular dependence." },
        { stepNumber: 4, description: "Interpret the limit.", workingLatex: "\\left|\\frac{h(z)}{z}\\right|=\\frac{1}{r}\\to\\infty\\ \\text{as } r\\to0,\\ \\text{with phase } e^{-3i\\theta}.", explanation: "The quotient diverges in modulus along every ray, with a \\(\\theta\\)-dependent direction; \\(h'(0)\\) does not exist (the limit is not even finite)." },
      ],
      finalAnswer: "\\( \\dfrac{h(z)}{z}=\\dfrac{e^{-3i\\theta}}{r}\\to\\infty;\\ \\text{direction-dependent and unbounded, so not differentiable.} \\)",
    },
  },
  {
    id: "cm1d-012",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Take \\( p(z)=z^2\\ \\) (the ordinary polynomial). Verify \\( p(z)/[\\,(z-0)\\,] \\) evaluated as the difference quotient of \\( p \\) at \\( 0 \\), namely \\( (p(z)-p(0))/z \\), tends to a single limit independent of \\( \\theta \\), and contrast this with the \\( z^5/|z|^4 \\) case.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the difference quotient.", workingLatex: "\\frac{p(z)-p(0)}{z}=\\frac{z^2-0}{z}=z.", explanation: "For the genuine polynomial there is no modulus factor, so the quotient simplifies to \\(z\\)." },
        { stepNumber: 2, description: "Take the limit.", workingLatex: "\\lim_{z\\to0} z = 0,", explanation: "As \\(z\\to0\\) along any path the quotient \\(z\\to0\\); the limit is the single value \\(0=p'(0)\\)." },
        { stepNumber: 3, description: "Check direction-independence in polar form.", workingLatex: "z=re^{i\\theta}\\to0\\ \\text{means}\\ r\\to0,\\ \\text{so}\\ z\\to0\\ \\text{for every } \\theta.", explanation: "The limit does not see \\(\\theta\\) at all — exactly what differentiability requires." },
        { stepNumber: 4, description: "Contrast.", workingLatex: "z^5/|z|^4:\\ \\frac{f(z)}{z}=e^{4i\\theta}\\ \\text{depends on } \\theta;\\quad z^2:\\ \\text{quotient}\\to0\\ \\text{always.}", explanation: "The modulus factor in \\(z^5/|z|^4\\) prevents the magnitude from cancelling the angular part, destroying the single limit that \\(z^2\\) enjoys." },
      ],
      finalAnswer: "\\( (p(z)-p(0))/z\\to0\\ \\text{independently of } \\theta;\\ \\text{contrasting the } e^{4i\\theta} \\text{ of } z^5/|z|^4. \\)",
    },
  },
  {
    id: "cm1d-013",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( f(z)=z^5/|z|^4 \\), write \\( f=z^3\\bar z^{\\,-2} \\) and use the Wirtinger derivative \\( \\partial f/\\partial\\bar z \\) (formally, away from \\( 0 \\)) to comment on why differentiability fails.",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "z and zbar"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Express f in z, zbar.", workingLatex: "f=\\frac{z^5}{(z\\bar z)^2}=\\frac{z^3}{\\bar z^{\\,2}}=z^3\\bar z^{\\,-2}.", explanation: "Using \\(|z|^4=(z\\bar z)^2\\) and cancelling two powers of \\(z\\)." },
        { stepNumber: 2, description: "Differentiate with respect to zbar.", workingLatex: "\\frac{\\partial f}{\\partial\\bar z}=z^3\\cdot(-2)\\bar z^{\\,-3}=-\\frac{2z^3}{\\bar z^{\\,3}}.", explanation: "Treat \\(z\\) as constant when differentiating in \\(\\bar z\\); the Wirtinger derivative measures \\(\\bar z\\)-dependence." },
        { stepNumber: 3, description: "Note it is nonzero.", workingLatex: "\\frac{\\partial f}{\\partial\\bar z}=-\\frac{2z^3}{\\bar z^{\\,3}}\\neq0\\quad(z\\neq0).", explanation: "A holomorphic function satisfies \\(\\partial f/\\partial\\bar z=0\\); here it is nonzero everywhere off the origin." },
        { stepNumber: 4, description: "Relate to the origin.", workingLatex: "\\left|\\frac{\\partial f}{\\partial\\bar z}\\right|=2\\ \\text{(constant)},\\quad \\frac{\\partial f}{\\partial\\bar z}=-2\\,\\frac{r^3e^{3i\\theta}}{r^3e^{-3i\\theta}}=-2e^{6i\\theta}.", explanation: "The \\(\\bar z\\)-derivative has constant modulus \\(2\\) on every ray and does not vanish as \\(z\\to0\\); its phase \\(e^{i(\\pi+6\\theta)}\\) is direction-dependent (not constant). The persistent \\(\\bar z\\)-dependence is precisely what kills the complex derivative at \\(0\\)." },
      ],
      finalAnswer: "\\( \\partial f/\\partial\\bar z=-2z^3/\\bar z^{\\,3}\\neq0;\\ \\text{the } \\bar z\\text{-dependence prevents differentiability.} \\)",
    },
  },
  {
    id: "cm1d-014",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Define \\( f(z)=\\dfrac{z^3}{|z|^2}\\ (z\\neq0),\\ f(0)=0 \\). Compute \\( f(z)/z \\) along \\( z=re^{i\\theta} \\) and identify all rays \\( \\theta\\in[0,2\\pi) \\) on which the directional limit equals \\( 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "phase"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Simplify the difference quotient.", workingLatex: "\\frac{f(z)}{z}=\\frac{z^2}{|z|^2}=\\frac{r^2e^{2i\\theta}}{r^2}=e^{2i\\theta}.", explanation: "One power of \\(z\\) cancels; the modulus removes the magnitude, leaving the phase \\(e^{2i\\theta}\\)." },
        { stepNumber: 2, description: "Set the limit equal to 1.", workingLatex: "e^{2i\\theta}=1 \\iff 2\\theta=2\\pi k,\\ k\\in\\mathbb{Z}.", explanation: "A unit-modulus exponential equals \\(1\\) exactly when its argument is an integer multiple of \\(2\\pi\\)." },
        { stepNumber: 3, description: "Solve for theta in the period.", workingLatex: "\\theta=\\pi k \\implies \\theta=0\\ \\text{or}\\ \\theta=\\pi\\ \\text{in } [0,2\\pi).", explanation: "Only \\(k=0,1\\) land in the half-open interval; these are the positive and negative real axes." },
        { stepNumber: 4, description: "Interpret.", workingLatex: "\\text{Limit}=1\\ \\text{on the real axis only; elsewhere it differs, so } f'(0) \\text{ fails.}", explanation: "Differentiability would require the same limit on every ray, but it varies, so it cannot exist." },
      ],
      finalAnswer: "\\( \\theta=0,\\ \\pi\\ (\\text{the real axis}). \\)",
      canonicalAnswer: "theta=0, pi",
    },
  },
  {
    id: "cm1d-015",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "A student claims: \"If \\( u_x=v_y \\) and \\( u_y=-v_x \\) hold at a point, then \\( f \\) is differentiable there.\" Give the precise correction and a one-line reason, citing the \\( z^5/|z|^4 \\) example.",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sufficiency theorem", "necessary vs sufficient"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Diagnose the error.", workingLatex: "\\text{CR at a point is NECESSARY, not SUFFICIENT.}", explanation: "Necessity: any differentiable function obeys CR; the converse needs more." },
        { stepNumber: 2, description: "State the correct sufficient condition.", workingLatex: "u,v\\in C^1\\ \\text{near } z_0\\ \\text{and CR at } z_0 \\implies f'(z_0)\\ \\text{exists}.", explanation: "Continuity of the four partials in a neighbourhood is the extra hypothesis that makes CR sufficient." },
        { stepNumber: 3, description: "Cite the counterexample.", workingLatex: "f=z^5/|z|^4:\\ \\text{CR holds at } 0\\ \\text{but } f'(0)\\ \\text{does not exist.}", explanation: "Here the partials are not continuous at \\(0\\), so the sufficiency theorem does not apply and differentiability genuinely fails." },
      ],
      finalAnswer: "\\( \\text{CR at a point is necessary only; sufficiency needs continuous partials near } z_0. \\)",
    },
  },
  {
    id: "cm1d-016",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z)=z|z|^2 \\) (defined for all \\( z \\), with \\( f(0)=0 \\)). Show CR holds at \\( z=0 \\), and determine whether \\( f \\) is differentiable there by computing \\( (f(z)-f(0))/z \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Restrict to the axes.", workingLatex: "z=x:\\ f=x\\cdot x^2=x^3;\\quad z=iy:\\ f=iy\\cdot y^2=iy^3.", explanation: "On the real axis \\(f=x^3\\) (real); on the imaginary axis \\(f=iy^3\\) (imaginary), so \\(u,v\\) are odd cubics." },
        { stepNumber: 2, description: "Differentiate the restrictions at 0.", workingLatex: "u_x=\\tfrac{d}{dx}x^3\\big|_0=0,\\ v_x=0;\\quad u_y=0,\\ v_y=\\tfrac{d}{dy}y^3\\big|_0=0.", explanation: "Every cubic restriction has zero slope at the origin, so all four partials vanish at \\(0\\)." },
        { stepNumber: 3, description: "Check CR.", workingLatex: "u_x=v_y=0,\\quad u_y=-v_x=0.", explanation: "All partials are zero, so the Cauchy–Riemann equations hold trivially at \\(0\\)." },
        { stepNumber: 4, description: "Compute the full difference quotient.", workingLatex: "\\frac{f(z)}{z}=\\frac{z|z|^2}{z}=|z|^2=r^2.", explanation: "The factor \\(z\\) cancels exactly, leaving \\(|z|^2\\), independent of direction." },
        { stepNumber: 5, description: "Take the limit.", workingLatex: "\\lim_{z\\to0}|z|^2=\\lim_{r\\to0}r^2=0,", explanation: "The limit is \\(0\\) regardless of \\(\\theta\\) — a genuine single value." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "f'(0)=0\\ \\text{exists; } f\\ \\text{IS differentiable at } 0\\ (\\text{but only there}).", explanation: "Unlike \\(z^5/|z|^4\\), here the difference quotient has no surviving phase, so \\(f\\) is differentiable at the origin." },
      ],
      finalAnswer: "\\( \\text{CR holds at } 0\\ \\text{and } f'(0)=0\\ \\text{exists: } f \\text{ is differentiable at } 0. \\)",
    },
  },
  {
    id: "cm1d-017",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "For \\( f(z)=z^5/|z|^4 \\), show that \\( f \\) is continuous at \\( 0 \\) (so non-differentiability is not a continuity failure) by estimating \\( |f(z)| \\).",
    marks: 3,
    examStyle: true,
    yearCreated: 2026,
    tags: ["continuity", "modulus estimate"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Bound the modulus.", workingLatex: "|f(z)|=\\frac{|z|^5}{|z|^4}=|z|\\quad(z\\neq0).", explanation: "The modulus of a quotient is the quotient of moduli; powers of \\(|z|\\) combine cleanly." },
        { stepNumber: 2, description: "Take the limit.", workingLatex: "\\lim_{z\\to0}|f(z)|=\\lim_{z\\to0}|z|=0=|f(0)|.", explanation: "Since \\(|f(z)|=|z|\\to0\\) and \\(f(0)=0\\), the value approaches the assigned value at \\(0\\)." },
        { stepNumber: 3, description: "Conclude continuity.", workingLatex: "f(z)\\to f(0)=0 \\implies f\\ \\text{continuous at } 0.", explanation: "Continuity holds; the pathology is purely in the derivative, where the phase \\(e^{4i\\theta}\\) survives." },
      ],
      finalAnswer: "\\( |f(z)|=|z|\\to0,\\ \\text{so } f \\text{ is continuous at } 0. \\)",
    },
  },
  {
    id: "cm1d-018",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Standard",
    answerType: "expression",
    questionText: "Let \\( f(z)=z^7/|z|^6\\ (z\\neq0),\\ f(0)=0 \\). Find the directional difference quotient \\( f(z)/z \\) along \\( z=re^{i\\theta} \\) and the number of distinct rays in \\( [0,2\\pi) \\) on which it equals \\( 1 \\).",
    marks: 4,
    examStyle: true,
    yearCreated: 2026,
    tags: ["directional limit", "phase counting"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Simplify the quotient.", workingLatex: "\\frac{f(z)}{z}=\\frac{z^6}{|z|^6}=\\frac{r^6e^{6i\\theta}}{r^6}=e^{6i\\theta}.", explanation: "One power of \\(z\\) cancels; the modulus to the sixth removes the magnitude, leaving \\(e^{6i\\theta}\\)." },
        { stepNumber: 2, description: "Set equal to 1.", workingLatex: "e^{6i\\theta}=1 \\iff 6\\theta=2\\pi k.", explanation: "Unit exponential equals \\(1\\) iff the phase is a multiple of \\(2\\pi\\)." },
        { stepNumber: 3, description: "Solve in the period.", workingLatex: "\\theta=\\frac{\\pi k}{3},\\ k=0,1,\\dots,5 \\implies 6\\ \\text{values in } [0,2\\pi).", explanation: "The spacing \\(\\pi/3\\) yields six equally spaced rays before wrapping around." },
        { stepNumber: 4, description: "Conclude.", workingLatex: "6\\ \\text{rays give limit } 1;\\ \\text{the limit still varies overall, so } f'(0)\\ \\text{fails.}", explanation: "Even though six rays agree, infinitely many others give different phases, so no single limit exists." },
      ],
      finalAnswer: "\\( f(z)/z=e^{6i\\theta};\\ 6 \\text{ rays where it equals } 1. \\)",
      canonicalAnswer: "e^{6i theta}; 6 rays",
    },
  },
  // --------- Challenge (12) ---------
  {
    id: "cm1d-019",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Give a complete argument that \\( f(z)=z^5/|z|^4\\ (z\\neq0),\\ f(0)=0 \\) satisfies the Cauchy–Riemann equations at \\( 0 \\) yet is not differentiable at \\( 0 \\). Include the axis difference quotients for all four partials and the polar limit of \\( f(z)/z \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "directional limit"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Values on the real axis.", workingLatex: "z=x:\\ f=\\frac{x^5}{x^4}=x \\implies u(x,0)=x,\\ v(x,0)=0.", explanation: "The modulus cancels on the real axis, giving the identity." },
        { stepNumber: 2, description: "Values on the imaginary axis.", workingLatex: "z=iy:\\ f=\\frac{i\\,y^5}{y^4}=iy \\implies u(0,y)=0,\\ v(0,y)=y.", explanation: "With \\(i^5=i\\), the imaginary-axis value is \\(iy\\)." },
        { stepNumber: 3, description: "Partial derivatives at 0.", workingLatex: "u_x=\\lim_{h\\to0}\\frac{h}{h}=1,\\ u_y=0;\\quad v_x=0,\\ v_y=\\lim_{k\\to0}\\frac{k}{k}=1.", explanation: "Each partial is the limiting difference quotient of a linear restriction." },
        { stepNumber: 4, description: "Verify CR.", workingLatex: "u_x=v_y=1,\\quad u_y=-v_x=0.", explanation: "Both Cauchy–Riemann equations hold at the origin." },
        { stepNumber: 5, description: "Polar difference quotient.", workingLatex: "\\frac{f(z)}{z}=\\frac{z^4}{|z|^4}=\\frac{r^4e^{4i\\theta}}{r^4}=e^{4i\\theta}.", explanation: "The full complex difference quotient retains the phase \\(e^{4i\\theta}\\)." },
        { stepNumber: 6, description: "Exhibit two unequal limits.", workingLatex: "\\theta=0:\\ 1;\\quad \\theta=\\frac{\\pi}{4}:\\ e^{i\\pi}=-1.", explanation: "The limit depends on the approach direction, so it is not single-valued." },
        { stepNumber: 7, description: "Conclude.", workingLatex: "f'(0)\\ \\text{does not exist, despite CR holding at } 0.", explanation: "CR is necessary but not sufficient; the partials fail to be continuous at \\(0\\), so the sufficiency theorem does not save differentiability." },
      ],
      finalAnswer: "\\( \\text{CR holds at } 0\\ (u_x=v_y=1,\\ u_y=-v_x=0)\\ \\text{but } f(z)/z=e^{4i\\theta}\\ \\text{is direction-dependent, so } f'(0)\\ \\text{fails.} \\)",
    },
  },
  {
    id: "cm1d-020",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Consider \\( F(z)=\\dfrac{(\\bar z)^3}{|z|^2}\\ (z\\neq0),\\ F(0)=0 \\). Determine whether the CR equations hold at \\( 0 \\) and whether \\( F \\) is differentiable at \\( 0 \\), using axis difference quotients and the polar limit.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "conjugate variables"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Simplify F.", workingLatex: "|z|^2=z\\bar z \\implies F=\\frac{\\bar z^{\\,3}}{z\\bar z}=\\frac{\\bar z^{\\,2}}{z}.", explanation: "Cancel one \\(\\bar z\\); the residual \\(\\bar z^2/z\\) still carries conjugate dependence." },
        { stepNumber: 2, description: "Real axis.", workingLatex: "z=x:\\ \\bar z=x \\implies F=\\frac{x^2}{x}=x \\implies u(x,0)=x,\\ v(x,0)=0.", explanation: "On the real axis \\(\\bar z=z=x\\), so \\(F=x\\)." },
        { stepNumber: 3, description: "Imaginary axis.", workingLatex: "z=iy:\\ \\bar z=-iy,\\ \\bar z^{\\,2}=-y^2 \\implies F=\\frac{-y^2}{iy}=\\frac{-y}{i}=iy.", explanation: "Using \\(1/i=-i\\): \\(-y/i=-y(-i)=iy\\). So \\(u(0,y)=0,\\ v(0,y)=y\\)." },
        { stepNumber: 4, description: "Partials and CR.", workingLatex: "u_x=1,\\ u_y=0,\\ v_x=0,\\ v_y=1 \\implies u_x=v_y,\\ u_y=-v_x.", explanation: "The axis behaviour is identical to the \\(z^5/|z|^4\\) case, so CR holds at \\(0\\)." },
        { stepNumber: 5, description: "Polar difference quotient.", workingLatex: "\\frac{F(z)}{z}=\\frac{\\bar z^{\\,2}}{z^2}=\\frac{r^2e^{-2i\\theta}}{r^2e^{2i\\theta}}=e^{-4i\\theta}.", explanation: "Now the phase is \\(e^{-4i\\theta}\\), again direction-dependent." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\theta=0:1,\\ \\theta=\\tfrac{\\pi}{4}:e^{-i\\pi}=-1 \\implies F'(0)\\ \\text{does not exist.}", explanation: "CR holds yet the directional limit varies; this is another instance of the necessary-not-sufficient phenomenon." },
      ],
      finalAnswer: "\\( \\text{CR holds at } 0\\ \\text{but } F(z)/z=e^{-4i\\theta}\\ \\text{is direction-dependent: } F'(0)\\ \\text{fails.} \\)",
    },
  },
  {
    id: "cm1d-021",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For which integer exponents \\( n\\ge2 \\) does \\( f_n(z)=\\dfrac{z^{n+1}}{|z|^{2}} \\) (with \\( f_n(0)=0 \\)) satisfy the Cauchy–Riemann equations at \\( 0 \\)? Analyse the difference quotients of \\( u \\) and \\( v \\) along the real and imaginary axes.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "general exponent"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Real-axis restriction.", workingLatex: "z=x:\\ f_n=\\frac{x^{n+1}}{x^2}=x^{n-1}.", explanation: "On the real axis the modulus cancels, leaving a real power \\(x^{n-1}\\)." },
        { stepNumber: 2, description: "Imaginary-axis restriction.", workingLatex: "z=iy:\\ f_n=\\frac{i^{n+1}y^{n+1}}{y^2}=i^{n+1}y^{n-1}.", explanation: "The phase \\(i^{n+1}\\) carries the imaginary-axis behaviour." },
        { stepNumber: 3, description: "Axis slopes at 0.", workingLatex: "u_x=\\tfrac{d}{dx}x^{n-1}\\big|_0=\\begin{cases}1,&n=2\\\\0,&n\\ge3\\end{cases};\\ \\text{similarly for the imaginary axis.}", explanation: "For \\(n-1=1\\) (i.e. \\(n=2\\)) the slope at \\(0\\) is \\(1\\); for \\(n-1\\ge2\\) (i.e. \\(n\\ge3\\)) the slope of \\(x^{n-1}\\) at \\(0\\) is \\(0\\), so all four axis partials vanish." },
        { stepNumber: 4, description: "Set n=2 and read partials.", workingLatex: "n=2:\\ f_2=\\frac{z^3}{|z|^2};\\ z=x\\!\\to\\!x,\\ z=iy\\!\\to\\!i^3y=-iy.", explanation: "Then \\(u(x,0)=x,\\ v(0,y)=-y\\) (since \\(i^{3}=-i\\))." },
        { stepNumber: 5, description: "Test CR at n=2.", workingLatex: "u_x=1,\\ v_y=-1 \\implies u_x\\neq v_y:\\ \\text{CR FAILS.}", explanation: "The exponent \\(n=2\\) gives the wrong sign on the imaginary axis, so CR is not satisfied here." },
        { stepNumber: 6, description: "Case n\\ge3: all partials vanish.", workingLatex: "n\\ge3:\\ u_x=u_y=v_x=v_y=0 \\implies u_x=v_y,\\ u_y=-v_x.", explanation: "When \\(n\\ge3\\) the exponent \\(n-1\\ge2\\), so every axis difference quotient has zero slope at \\(0\\); CR then holds trivially as \\(0=0\\), regardless of the phase \\(i^{n+1}\\)." },
        { stepNumber: 7, description: "Resolve.", workingLatex: "\\text{For } f_n=z^{n+1}/|z|^2:\\ \\text{CR at } 0 \\iff n\\ge3\\ (\\text{fails only at } n=2).", explanation: "CR holds at \\(0\\) for every \\(n\\ge3\\) (all four partials vanish); it fails only at \\(n=2\\), where \\(u_x=1\\neq-1=v_y\\). All the \\(n\\ge3\\) cases are nonetheless non-differentiable by the same \\(e^{ik\\theta}\\) directional-limit argument." },
      ],
      finalAnswer: "\\( \\text{CR holds at } 0\\ \\text{for every } n\\ge3\\ (\\text{all four partials vanish, so } 0=0);\\ \\text{it fails only at } n=2. \\)",
      canonicalAnswer: "n>=3 (fails only at n=2)",
    },
  },
  {
    id: "cm1d-022",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Show that for \\( f(z)=z^5/|z|^4 \\) the map \\( \\theta\\mapsto \\arg\\big(f(z)/z\\big) \\) along \\( z=re^{i\\theta} \\) winds around the unit circle as \\( \\theta \\) runs over \\( [0,2\\pi) \\), and state the winding number. Explain what this says about differentiability.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["winding number", "directional limit"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Identify the angular map.", workingLatex: "\\frac{f(z)}{z}=e^{4i\\theta},\\quad \\arg\\Big(\\frac{f(z)}{z}\\Big)=4\\theta\\ (\\mathrm{mod}\\ 2\\pi).", explanation: "The quotient lies on the unit circle with argument exactly \\(4\\theta\\)." },
        { stepNumber: 2, description: "Track the total change of argument.", workingLatex: "\\theta:0\\to2\\pi \\implies 4\\theta:0\\to8\\pi.", explanation: "As the approach direction sweeps once around, the argument of the quotient sweeps through \\(8\\pi\\)." },
        { stepNumber: 3, description: "Compute the winding number.", workingLatex: "\\text{winding}=\\frac{8\\pi}{2\\pi}=4.", explanation: "Total argument change divided by \\(2\\pi\\) gives the number of times the quotient circles the origin." },
        { stepNumber: 4, description: "Interpret for differentiability.", workingLatex: "\\text{A single limit would need winding } 0\\ (\\text{constant value}).", explanation: "Differentiability requires \\(f(z)/z\\) to approach one constant; a winding number \\(4\\) means it visits the whole unit circle four times, so no limit exists." },
      ],
      finalAnswer: "\\( \\text{Winding number } 4;\\ \\text{the quotient is non-constant on the circle, so } f'(0)\\ \\text{does not exist.} \\)",
      canonicalAnswer: "winding number 4",
    },
  },
  {
    id: "cm1d-023",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Let \\( g(z)=\\overline{z}^{\\,2}/z\\ (z\\neq0),\\ g(0)=0 \\). Show \\( g \\) is continuous at \\( 0 \\), satisfies CR at \\( 0 \\), but is not differentiable at \\( 0 \\). Provide the full chain.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "continuity", "directional limit"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Continuity estimate.", workingLatex: "|g(z)|=\\frac{|z|^2}{|z|}=|z|\\to0=g(0).", explanation: "The modulus is \\(|z|\\), which tends to \\(0\\); so \\(g\\) is continuous at the origin." },
        { stepNumber: 2, description: "Real axis.", workingLatex: "z=x:\\ \\bar z=x \\implies g=\\frac{x^2}{x}=x \\implies u(x,0)=x,\\ v(x,0)=0.", explanation: "On the real axis conjugation does nothing, so \\(g=x\\)." },
        { stepNumber: 3, description: "Imaginary axis.", workingLatex: "z=iy:\\ \\bar z^{\\,2}=(-iy)^2=-y^2 \\implies g=\\frac{-y^2}{iy}=iy.", explanation: "Using \\(1/i=-i\\): \\(-y^2/(iy)=-y/i=iy\\). Hence \\(u(0,y)=0,\\ v(0,y)=y\\)." },
        { stepNumber: 4, description: "Partials and CR.", workingLatex: "u_x=1,\\ u_y=0,\\ v_x=0,\\ v_y=1 \\implies u_x=v_y,\\ u_y=-v_x.", explanation: "All four axis difference quotients match the CR pattern, so CR holds at \\(0\\)." },
        { stepNumber: 5, description: "Polar difference quotient.", workingLatex: "\\frac{g(z)}{z}=\\frac{\\bar z^{\\,2}}{z^2}=\\frac{r^2e^{-2i\\theta}}{r^2e^{2i\\theta}}=e^{-4i\\theta}.", explanation: "The quotient is unimodular with phase \\(-4\\theta\\), depending on direction." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\theta=0:1,\\ \\theta=\\tfrac{\\pi}{4}:e^{-i\\pi}=-1 \\implies g'(0)\\ \\text{fails.}", explanation: "Continuous and CR-satisfying at \\(0\\), yet not differentiable: the textbook borderline case." },
      ],
      finalAnswer: "\\( g\\ \\text{is continuous and CR holds at } 0,\\ \\text{but } g(z)/z=e^{-4i\\theta}\\ \\text{so } g'(0)\\ \\text{does not exist.} \\)",
    },
  },
  {
    id: "cm1d-024",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Contrast two functions at \\( 0 \\): \\( f(z)=z^5/|z|^4 \\) and \\( P(z)=z^2 \\). Both satisfy CR at \\( 0 \\). Explain precisely, via the continuity of partials, why \\( P \\) is differentiable everywhere but \\( f \\) is not differentiable at \\( 0 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sufficiency theorem", "continuity of partials"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Partials of P=z^2.", workingLatex: "P=x^2-y^2+2ixy:\\ u_x=2x,\\ u_y=-2y,\\ v_x=2y,\\ v_y=2x.", explanation: "Writing \\(z^2=(x+iy)^2\\) gives polynomial real and imaginary parts." },
        { stepNumber: 2, description: "Note continuity for P.", workingLatex: "u_x,u_y,v_x,v_y\\ \\text{are polynomials} \\implies \\text{continuous everywhere.}", explanation: "Polynomials are continuous, so the sufficiency theorem applies at every point." },
        { stepNumber: 3, description: "Apply the sufficiency theorem to P.", workingLatex: "\\text{CR} (u_x=v_y=2x,\\ u_y=-v_x=-2y)\\ +\\ C^1 \\implies P'\\ \\text{exists.}", explanation: "Both ingredients hold for \\(P\\), so it is differentiable everywhere — indeed entire." },
        { stepNumber: 4, description: "Partials of f off the axes are discontinuous at 0.", workingLatex: "\\frac{f(z)}{z}=e^{4i\\theta}\\ \\text{shows the local linear behaviour depends on } \\theta.", explanation: "The direction-dependence of the difference quotient reflects that the partials of \\(f\\) do not settle to limits as \\(z\\to0\\); they are discontinuous at \\(0\\)." },
        { stepNumber: 5, description: "Conclude the contrast.", workingLatex: "P:\\ \\text{CR}+C^1\\Rightarrow\\text{diff'ble};\\quad f:\\ \\text{CR but partials NOT }C^1\\ \\text{at }0\\Rightarrow\\text{not diff'ble.}", explanation: "The decisive difference is the continuity of the partials near the point — present for \\(P\\), absent for \\(f\\)." },
      ],
      finalAnswer: "\\( P\\ \\text{has continuous (polynomial) partials so CR}\\Rightarrow\\text{diff'ble; } f\\text{'s partials are discontinuous at } 0,\\ \\text{so CR alone does not suffice.} \\)",
    },
  },
  {
    id: "cm1d-025",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( f(z)=z^5/|z|^4 \\), compute the two iterated/path limits of \\( f(z)/z \\) as \\( z\\to0 \\) along the parabola \\( y=x^2 \\) (approached with \\( x\\to0^+ \\)) and along the line \\( y=x \\), and confirm they agree with the ray formula in the limit.",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["path limit", "directional limit"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Recall the quotient is angular.", workingLatex: "\\frac{f(z)}{z}=\\frac{z^4}{|z|^4}=e^{4i\\arg z}.", explanation: "Only the argument of \\(z\\) matters, not its modulus; so the limiting value depends on the limiting direction of the path." },
        { stepNumber: 2, description: "Limiting direction of the parabola.", workingLatex: "y=x^2,\\ x\\to0^+:\\ \\arg z=\\arctan\\frac{x^2}{x}=\\arctan x\\to0.", explanation: "Near the origin the parabola is tangent to the real axis, so its limiting argument is \\(0\\)." },
        { stepNumber: 3, description: "Parabola limit.", workingLatex: "\\lim_{x\\to0^+}\\frac{f}{z}=e^{4i\\cdot0}=1.", explanation: "The limiting direction is the positive real axis, giving the same value \\(1\\) as the ray \\(\\theta=0\\)." },
        { stepNumber: 4, description: "Line y=x limit.", workingLatex: "y=x:\\ \\arg z=\\frac{\\pi}{4}\\implies \\frac{f}{z}=e^{4i\\cdot\\pi/4}=e^{i\\pi}=-1.", explanation: "This path has constant argument \\(\\pi/4\\), so the value is \\(-1\\)." },
        { stepNumber: 5, description: "Consistency and conclusion.", workingLatex: "1\\ (\\text{parabola, dir }0)\\neq -1\\ (\\text{line, dir }\\pi/4).", explanation: "Path limits match the ray formula evaluated at the path's limiting direction; the two values differ, so \\(f'(0)\\) does not exist." },
      ],
      finalAnswer: "\\( \\text{Parabola}\\to1,\\ \\text{line } y=x\\to-1;\\ \\text{consistent with } e^{4i\\theta}\\text{, and unequal.} \\)",
      canonicalAnswer: "parabola 1, line -1",
    },
  },
  {
    id: "cm1d-026",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Suppose \\( f=u+iv \\) has \\( u(x,y)=x,\\ v(x,y)=y \\) on the two coordinate axes only, with arbitrary smooth-elsewhere behaviour. Show that this axis data forces CR at \\( 0 \\), and construct an explicit non-differentiable \\( f \\) consistent with it.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "construction"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Compute partials from axis data.", workingLatex: "u(x,0)=x\\Rightarrow u_x(0)=1;\\ u(0,y)=0\\Rightarrow u_y(0)=0.", explanation: "Reading \\(u=x\\) on the real axis and (from \\(v=y\\) requiring \\(u=0\\) on the imaginary axis) gives these partials." },
        { stepNumber: 2, description: "Same for v.", workingLatex: "v(x,0)=0\\Rightarrow v_x(0)=0;\\ v(0,y)=y\\Rightarrow v_y(0)=1.", explanation: "On the real axis \\(v=0\\); on the imaginary axis \\(v=y\\)." },
        { stepNumber: 3, description: "Check CR.", workingLatex: "u_x=v_y=1,\\ u_y=-v_x=0.", explanation: "The axis data alone pins down CR at \\(0\\) — it does not, however, control the off-axis behaviour." },
        { stepNumber: 4, description: "Construct a witness.", workingLatex: "f(z)=\\frac{z^5}{|z|^4}\\ \\text{has exactly this axis data}\\ (u(x,0)=x,\\ v(0,y)=y).", explanation: "Our canonical function realises the prescribed axis values, as shown earlier." },
        { stepNumber: 5, description: "Show it is non-differentiable.", workingLatex: "\\frac{f(z)}{z}=e^{4i\\theta}\\ \\text{direction-dependent.}", explanation: "Off the axes the modulus factor injects the phase \\(e^{4i\\theta}\\), so the derivative cannot exist at \\(0\\)." },
        { stepNumber: 6, description: "Conclusion.", workingLatex: "\\text{Axis data}\\Rightarrow\\text{CR at }0,\\ \\text{but off-axis behaviour decides differentiability.}", explanation: "This shows concretely that CR at a point is a one-dimensional (axis) condition, while differentiability is a genuinely two-dimensional requirement." },
      ],
      finalAnswer: "\\( \\text{Axis data forces } u_x=v_y=1,\\ u_y=-v_x=0;\\ f=z^5/|z|^4 \\text{ realises it yet is not differentiable.} \\)",
    },
  },
  {
    id: "cm1d-027",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Define \\( f(z)=z^5/|z|^4 \\). Using \\( f=z^3/\\bar z^{\\,2} \\), compute both Wirtinger derivatives \\( \\partial f/\\partial z \\) and \\( \\partial f/\\partial\\bar z \\) (for \\( z\\neq0 \\)) and explain why \\( \\partial f/\\partial\\bar z\\not\\to0 \\) as \\( z\\to0 \\) obstructs differentiability at \\( 0 \\).",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Wirtinger derivative", "z and zbar"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Write f in z, zbar.", workingLatex: "f=z^3\\bar z^{\\,-2}.", explanation: "From \\(|z|^4=(z\\bar z)^2\\) after cancelling two powers of \\(z\\)." },
        { stepNumber: 2, description: "Holomorphic Wirtinger derivative.", workingLatex: "\\frac{\\partial f}{\\partial z}=3z^2\\bar z^{\\,-2}=\\frac{3z^2}{\\bar z^{\\,2}}.", explanation: "Differentiate in \\(z\\) treating \\(\\bar z\\) as constant." },
        { stepNumber: 3, description: "Anti-holomorphic Wirtinger derivative.", workingLatex: "\\frac{\\partial f}{\\partial\\bar z}=z^3\\cdot(-2)\\bar z^{\\,-3}=-\\frac{2z^3}{\\bar z^{\\,3}}.", explanation: "Differentiate in \\(\\bar z\\) treating \\(z\\) as constant; this measures the conjugate dependence." },
        { stepNumber: 4, description: "Its modulus on rays.", workingLatex: "\\left|\\frac{\\partial f}{\\partial\\bar z}\\right|=\\frac{2|z|^3}{|z|^3}=2,\\quad z\\neq0.", explanation: "The modulus is the constant \\(2\\) everywhere off the origin — it does not decay to \\(0\\)." },
        { stepNumber: 5, description: "Phase on rays.", workingLatex: "z=re^{i\\theta}:\\ \\frac{\\partial f}{\\partial\\bar z}=-2\\,\\frac{r^3e^{3i\\theta}}{r^3e^{-3i\\theta}}=-2e^{6i\\theta}.", explanation: "The anti-holomorphic part rotates with \\(\\theta\\), never approaching a single value, let alone \\(0\\)." },
        { stepNumber: 6, description: "Differentiability criterion.", workingLatex: "f\\ \\text{differentiable at }0 \\iff \\frac{\\partial f}{\\partial\\bar z}\\to0;\\ \\text{here it} \\to -2e^{6i\\theta}\\neq0.", explanation: "Complex differentiability is equivalent to the vanishing of the \\(\\bar z\\)-derivative; its non-vanishing (and direction-dependence) at the origin is exactly the obstruction." },
      ],
      finalAnswer: "\\( \\partial f/\\partial z=3z^2/\\bar z^{\\,2},\\ \\partial f/\\partial\\bar z=-2z^3/\\bar z^{\\,3}=-2e^{6i\\theta}\\not\\to0,\\ \\text{so } f'(0)\\ \\text{fails.} \\)",
    },
  },
  {
    id: "cm1d-028",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Build a function that is differentiable at \\( 0 \\) only: let \\( f(z)=\\bar z\\,|z|^2 \\). Show CR holds at \\( 0 \\) (and \\( f \\) is differentiable there with \\( f'(0)=0 \\)) but CR fails at every \\( z\\neq0 \\), so \\( f \\) is nowhere analytic.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["Cauchy-Riemann", "isolated differentiability"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Difference quotient at 0.", workingLatex: "\\frac{f(z)-f(0)}{z}=\\frac{\\bar z|z|^2}{z}=\\frac{\\bar z\\cdot z\\bar z}{z}=\\bar z^{\\,2}.", explanation: "Using \\(|z|^2=z\\bar z\\), the \\(z\\) cancels, leaving \\(\\bar z^2\\)." },
        { stepNumber: 2, description: "Limit at 0.", workingLatex: "\\lim_{z\\to0}\\bar z^{\\,2}=0 \\implies f'(0)=0\\ \\text{exists.}", explanation: "Since \\(|\\bar z^2|=|z|^2\\to0\\) along every path, the limit is the single value \\(0\\): \\(f\\) IS differentiable at \\(0\\)." },
        { stepNumber: 3, description: "Wirtinger derivative away from 0.", workingLatex: "f=\\bar z\\,z\\bar z=z\\bar z^{\\,2} \\implies \\frac{\\partial f}{\\partial\\bar z}=2z\\bar z.", explanation: "Write \\(f=z\\bar z^2\\) and differentiate in \\(\\bar z\\)." },
        { stepNumber: 4, description: "CR away from 0.", workingLatex: "\\frac{\\partial f}{\\partial\\bar z}=2z\\bar z=2|z|^2\\neq0\\quad(z\\neq0).", explanation: "CR is equivalent to \\(\\partial f/\\partial\\bar z=0\\); here it is \\(2|z|^2\\), nonzero away from the origin." },
        { stepNumber: 5, description: "Conclude.", workingLatex: "f'(0)=0\\ \\text{exists, but } f\\ \\text{not differentiable for any } z\\neq0.", explanation: "Differentiability at a single isolated point gives no neighbourhood of differentiability, so \\(f\\) is analytic nowhere." },
        { stepNumber: 6, description: "Contrast with cm1d's main example.", workingLatex: "z^5/|z|^4:\\ \\text{CR at }0\\ \\text{but NOT diff'ble; here CR}+\\text{diff'ble at }0\\ \\text{but not analytic.}", explanation: "Two complementary subtleties: CR-without-derivative, and derivative-at-a-point-without-analyticity." },
      ],
      finalAnswer: "\\( f'(0)=0\\ \\text{exists; } \\partial f/\\partial\\bar z=2|z|^2\\neq0\\ \\text{for } z\\neq0,\\ \\text{so } f \\text{ is nowhere analytic.} \\)",
    },
  },
  {
    id: "cm1d-029",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "For \\( f(z)=z^5/|z|^4 \\), examine the increment form \\( f(z)=f(0)+A z+B\\bar z+o(|z|) \\). Determine whether constants \\( A,B \\) exist making this hold, and connect \\( B\\neq0 \\) to non-differentiability.",
    marks: 6,
    examStyle: true,
    yearCreated: 2026,
    tags: ["increment form", "real-linear approximation"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Form the candidate increment.", workingLatex: "f(z)=\\frac{z^5}{|z|^4}=z\\cdot\\frac{z^4}{|z|^4}=z\\,e^{4i\\theta},\\quad \\theta=\\arg z.", explanation: "Factor out one \\(z\\); the remaining factor is the pure phase \\(e^{4i\\theta}\\)." },
        { stepNumber: 2, description: "Test the complex-linear form Az.", workingLatex: "\\frac{f(z)}{z}=e^{4i\\theta}\\ \\text{is not constant} \\implies \\text{no single } A.", explanation: "A complex-linear approximation \\(Az\\) would force \\(f(z)/z\\to A\\); but the phase varies, so no \\(A\\) works." },
        { stepNumber: 3, description: "Express in z and zbar to find A, B.", workingLatex: "f=z^3\\bar z^{\\,-2};\\ \\text{near }0\\ \\text{the leading real-linear part is } A z+B\\bar z\\ \\text{with } A=f_z(0),\\ B=f_{\\bar z}(0).", explanation: "A real-differentiable function has increment \\(f_z(0)z+f_{\\bar z}(0)\\bar z+o(|z|)\\)." },
        { stepNumber: 4, description: "But f is not even real-differentiable in the usual o(|z|) sense.", workingLatex: "f(z)=z\\,e^{4i\\theta}=|z|e^{i\\theta}e^{4i\\theta}=|z|e^{5i\\theta},\\quad |f|=|z|.", explanation: "The increment is \\(|z|e^{5i\\theta}\\): order \\(|z|\\) in modulus but with a \\(5\\theta\\) phase that is NOT of the form \\(Az+B\\bar z\\) (which would give phases \\(\\theta\\) and \\(-\\theta\\) only)." },
        { stepNumber: 5, description: "Match phases.", workingLatex: "Az+B\\bar z=|z|(Ae^{i\\theta}+Be^{-i\\theta});\\ \\text{phase } 5\\theta\\ \\text{cannot be reproduced.}", explanation: "A real-linear map produces only first harmonics \\(e^{\\pm i\\theta}\\); the \\(e^{5i\\theta}\\) content cannot be captured, so no \\((A,B)\\) exist." },
        { stepNumber: 6, description: "Conclude.", workingLatex: "\\text{No } (A,B);\\ \\text{in particular complex-differentiability } (B=0)\\ \\text{fails.}", explanation: "Differentiability would need \\(B=0\\) with a valid \\(A\\); here not even the weaker real-linear approximation exists, so \\(f'(0)\\) certainly does not." },
      ],
      finalAnswer: "\\( \\text{No constants } A,B\\ \\text{work: the increment is } |z|e^{5i\\theta},\\ \\text{a fifth harmonic beyond } Az+B\\bar z;\\ f \\text{ is not differentiable.} \\)",
    },
  },
  {
    id: "cm1d-030",
    topicRef: "cm1d",
    topicTitle: "CR satisfied yet not differentiable",
    difficulty: "Challenge",
    answerType: "expression",
    questionText: "Synthesis: state the full logical relationship between (A) CR holding at \\( z_0 \\), (B) the partials being continuous near \\( z_0 \\), and (C) \\( f \\) being differentiable at \\( z_0 \\). Illustrate each implication or non-implication with one of: \\( z^5/|z|^4 \\), \\( \\bar z|z|^2 \\), \\( z^2 \\).",
    marks: 5,
    examStyle: true,
    yearCreated: 2026,
    tags: ["sufficiency theorem", "synthesis"],
    workedSolution: {
      steps: [
        { stepNumber: 1, description: "Necessity of CR.", workingLatex: "(C)\\Rightarrow(A):\\ \\text{differentiable}\\Rightarrow\\text{CR holds.}", explanation: "Equating the real-axis and imaginary-axis difference quotients of a differentiable \\(f\\) yields CR; this direction is always true." },
        { stepNumber: 2, description: "CR alone does not give C.", workingLatex: "(A)\\not\\Rightarrow(C):\\ f=z^5/|z|^4\\ \\text{has CR at }0\\ \\text{but no } f'(0).", explanation: "The canonical counterexample: CR at \\(0\\), direction-dependent quotient \\(e^{4i\\theta}\\)." },
        { stepNumber: 3, description: "CR plus continuity gives C.", workingLatex: "(A)\\wedge(B)\\Rightarrow(C):\\ \\text{sufficiency theorem.}", explanation: "Continuous partials near \\(z_0\\) plus CR at \\(z_0\\) implies differentiability — illustrated by \\(z^2\\), whose polynomial partials are continuous." },
        { stepNumber: 4, description: "C at a point need not give B around it.", workingLatex: "(C)\\ \\text{at one point}\\not\\Rightarrow\\text{analyticity}:\\ f=\\bar z|z|^2,\\ f'(0)=0\\ \\text{only.}", explanation: "Differentiability at an isolated point gives no neighbourhood, hence no analyticity; \\(\\bar z|z|^2\\) is the witness." },
        { stepNumber: 5, description: "Summarise the implication chart.", workingLatex: "(C)\\Rightarrow(A);\\ (A)\\wedge(B)\\Rightarrow(C);\\ (A)\\not\\Rightarrow(C);\\ (C)_{\\text{pt}}\\not\\Rightarrow\\text{analytic.}", explanation: "These four facts capture the entire necessary/sufficient structure of the Cauchy–Riemann theory at a point." },
      ],
      finalAnswer: "\\( (C)\\Rightarrow(A);\\ (A)\\wedge(B)\\Rightarrow(C);\\ (A)\\not\\Rightarrow(C)\\ [z^5/|z|^4];\\ (C)\\ \\text{at a point}\\not\\Rightarrow\\text{analytic}\\ [\\bar z|z|^2];\\ z^2\\ \\text{shows } (A)\\wedge(B)\\Rightarrow(C). \\)",
    },
  },
];
